### ISSUE TITLE
Pickers

### ISSUE THREAD

**Issue by ahmedlhanafy** [callstack/react-native-paper#10]
[MD Docs Link](https://material.google.com/components/pickers.html#pickers-time-pickers)
We will need an IOS developer for this one to be implemented on IOS

**Comment by satya164** [comment]
This should be implemented in JS

**Comment by DennyLoko** [comment]
Would be nice to have some docs on how to do this.

**Comment by marsonmao** [comment]
+1 looking for date pickers...but it looks like material design has removed it from standard components?

**Comment by marsonmao** [comment]
The closest one is https://github.com/mmazzarolo/react-native-modal-datetime-picker, but it actually just use the android native picker (which of course follows the guide)

**Comment by luissmg** [comment]
I am also using the one @marsonmao mentioned. It works just fine for both OS. I don't think there is MD specifications for this. What can be done is to create a component using a `TextInput` and when clicked it opens the picker. That's what I have done in my project

**Comment by ahce** [comment]
Hello everyone!
This is a simple [example](https://snack.expo.io/@ahce/react-native-paper-datepicker)

**Comment by luissmg** [comment]
@ahce That's what I do right now. But in your example there is a problem. If it is a date picker you can't print the time in the input. Just a few things that we should be careful about.

**Comment by ahce** [comment]
@luissmg In the example, I just want to show, how to make the material style.
The text can be formatted by the mode or prop with moment or date-fns.

I think that this component should be included in react-native-paper
