### ISSUE TITLE
How to pass  props to child route in Bottom Navigation

### ISSUE THREAD

**Issue by Yajan** [callstack/react-native-paper#1000]
## Passing Props to child route

I want to pass props to child routes like 

```
switch (route.key) {
      case 'music':
        return <MusicScreen add={this.updateMedia} download={this.downloadMedia} />;
      case 'albums':
        return <AlbumGallery />;
      case 'recents':
        return <RecentsRoute/>
    }
  }
```

Using the above code is giving error as route is undefined. How this can be implemented using sceneMap ?.

**Comment by Yajan** [comment]
I am trying to implement [Standard bottom sheet ](https://material.io/design/components/sheets-bottom.html#standard-bottom-sheet) of material UI. I want to have a component globally above the bottom navigation. How this feature can be implemented using react native paper components ?

**Comment by jaysbytes** [comment]
You should reproduce your issue using https://snakc.expo.io to let others help you. 
But I'm guessing that if you want to pass props inside screenMap you could use Higher Order Component to wrap your actual component and add some props there or use React context

**Comment by Yajan** [comment]
I resolved this issue using redux. Sorry for inconvenience.
