### ISSUE TITLE
menu layout problem in web

### ISSUE THREAD

**Issue by geminiyellow** [callstack/react-native-paper#1005]
## Environment

`react-native-web@latest` 

## Description

![nb2](https://user-images.githubusercontent.com/929878/56345309-65d9c680-61fa-11e9-89f3-36f028ece1d4.gif)

![nb2](https://user-images.githubusercontent.com/929878/56345395-96216500-61fa-11e9-8c44-c991e304941e.gif)

## Reproducible Demo

copy from demo

**Comment by satya164** [comment]
cc @Trancever

**Comment by geminiyellow** [comment]
thanks @satya164 , should i add a resize watcher ? and set the window size from outside ?

**Comment by satya164** [comment]
resizing the window should probably dismiss the menu automatically

**Comment by ferrannp** [comment]
Also when you rotate your phone it should dismiss too.

**Comment by geminiyellow** [comment]
woo, great , thank you @satya164 .

**Comment by Trancever** [comment]
It's going to be included in next release
