### ISSUE TITLE
wrong text align in RTL

### ISSUE THREAD

**Issue by sijad** [callstack/react-native-paper#1007]
## Environment

react-native: 0.59.3
react-native-paper: 2.15.2

## Description

[this commit](https://github.com/facebook/react-native/commit/871290f) changes text align behavior in android.
`react-native-paper` also try to achieve something similar via styling but now it introduces conflict with that commit and text components (Subheader, Text, etc) renders in apposite direction.

`react-native`'s Text component renders as it should be but `react-native-paper` text components are not.

**Comment by RaheelJaved** [comment]
as far as the TextInput concerns, seems like it's aligning the text contents based on the actual value entered (the first letter), not the current language. 

For example...
input value = "Ahmed", alignment = left
input value = "احمد", alignment = right
input value = "Ahmed احمد", alignment = left
input value = "احمد Ahmed", alignment = right
input value = "123 احمد", alignment = right

This is irrespective of I18nManager.isRTL returns true or false, numbers and special characters also have no effect on alignment

`"react-native-paper": "^2.15.2",`

**Comment by satya164** [comment]
Looks like the change in RN is going to be reverted https://github.com/facebook/react-native/pull/24580

Closing the issue
