### ISSUE TITLE
Allow further style customisation with nested custom styles api

### ISSUE THREAD

**Issue by Secretmapper** [callstack/react-native-paper#1010]
First of all, awesome project!

## Describe the feature

Allow passing of styles to nested components/make components more decomposed

## Motivation

I wanted to create a custom FAB that's bigger than the current one (single main button). However, since FAB styles are only applied to root, I can only change the size of the main/actual button, and if I do the label stays small.

## Related Issues

N/A

Just for reference, with [material-ui](https://material-ui.com/demos/buttons/) the API for something like this is:

```

<Fab
    style={styles.fab}
>
    <MyIcon classes={{ root: props.classes.icon }} />
</Fab>

const styles = {
  fab: {
    color: 'white',
    height: 100,
    width: 100
  },
  icon: {
    fontSize: 48
  }
}
```

I don't think it's possible to customise FAB right now in a similar as for example the icon size is hardcoded:

`<CrossFadeIcon source={icon} size={24} color={foregroundColor} />`

Even still, internal components such as CrossFadeIcon isn't exported so having to copy/customize FAB requires a lot of copy paste

**Comment by RichardLindhout** [comment]
Maybe do it even further and allow nested props and merge the styles.

**Comment by satya164** [comment]
We don't want to do this. Exposing internal components means it becomes significantly harder to make sure we don't introduce any breaking changes. If you need some specific feature, please open an issue so we can consider adding some props consumable via the public API.

**Comment by Secretmapper** [comment]
Fair enough, I created a more restricted feature request only pertinent to fab size [here](https://github.com/callstack/react-native-paper/issues/1040)
