### ISSUE TITLE
Unable to use ref in TextInput

### ISSUE THREAD

**Issue by KPS250** [callstack/react-native-paper#1011]
## Environment
react-native-cli: 2.0.1
react-native: 0.59.3
react-native-paper: "^2.15.1",

## Description
Unable to use refs in React Native Paper for TextInput

## Reproducible Demo

 <TextInput
            ref={(c) => { **this.firstName** = c; }}
            label= {Strings.firstName}
            mode={'outlined'}
            value={this.state.fname}
            theme={this.inputStyle()}
            style={styles.inputContainer}
            onChangeText={text => this.setState({ fname : text })}
          />

**And if I try to use it:**

 if(this.firstName.isFocused()){
    alert('First Name is Focused')
  }

Error is:

console.error: "Unhandled JS Exception: TypeError: TypeError: Cannot read property 'isFocused' of undefined

This error is located at:
    in ProfileForm (created by SceneView)
    in SceneView (at StackViewLayout.js:795)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.js:69)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:57)
    in Card (at createPointerEventsContainer.js:27)
    in Container (at StackViewLayout.js:860)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:311)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.js:307)
    in PanGestureHandler (at StackViewLayout.js:300)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:79)
    in RCTView (at View.js:45)
    in View (at Transitioner.js:214)
    in Transitioner (at StackView.js:22)
    in StackView (created by Navigator)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:388)
    in NavigationContainer (at App.js:11)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

This error is located at:
    in NavigationContainer (at App.js:11)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)"

console.error
    YellowBox.js:59:8
Object.logToConsole
    RCTLog.js:47:4
Object.logIfNoNativeHook
    RCTLog.js:30:6
MessageQueue.__callFunction
    MessageQueue.js:366:41
<unknown>
    MessageQueue.js:106:11
MessageQueue.__guard
    MessageQueue.js:314:8
MessageQueue.callFunctionReturnFlushedQueue
    MessageQueue.js:105:9
<unknown>
    debuggerWorker.js:80:58

**Comment by AtlasRider** [comment]
Try using 

`ref="textInput"`

then access it via 

`this.refs.textInput.focus();`

I had success with this approach

**Comment by KPS250** [comment]
That Worked like charm. Thanks @AtlasRider !!

**Comment by KPS250** [comment]
That Worked! Thanks @AtlasRider
