### ISSUE TITLE
Docs website is down

### ISSUE THREAD

**Issue by manelsanz** [callstack/react-native-paper#1013]
The docs website is no longer working. Please, fix this ASAP...

Thanks

**Comment by satya164** [comment]
Works for me

**Comment by manelsanz** [comment]
I'm saying this website: https://callstack.github.io/react-native-paper/index.html 
For me it's not working, stucked loading...

**Comment by Krizzu** [comment]
Works for me

**Comment by manelsanz** [comment]
You have reason, in 4G on my mobile is working.. hmmm.. maybe I have to restart my router.
Thanks.
