### ISSUE TITLE
Card.Title expects type `React.ReactNode` but is rendered inside a `StyledText` -- which means in effect it can only accept a Text node

### ISSUE THREAD

**Issue by chadlavi-casebook** [callstack/react-native-paper#1015]
## Description

Per the type definitions[[1](https://github.com/callstack/react-native-paper/blob/901745bc840bdef85446fc7d58160642c8f4b7de/typings/components/Card.d.ts#L19)], `Card.Title`'s `title` prop should accept any react node. However, because it is wrapped in a `StyledText` via the `<Title>` component[[2](https://github.com/callstack/react-native-paper/blob/master/src/components/Typography/Title.js)], it can only accept _text_ nodes. This is quite limiting for devs who want to customize their Card titles, especially since the `left` prop does not have style controls. 

For example, in my use case: I want to put an Icon before the text of the title, at the same size as the title text, and with only a gap of 16px between the icon and the text. I have to either put the icon in the `left` then give the title a negative left margin (because the `left` has a fixed width of 40), or I have to use an icon set that renders as text glyphs so that I can include it in the `title` itself; passing anything that is/contains a `<View>` to `title` results in the error `Invariant Violation: Nesting of <View> within <Text> is not currently supported`.

The `title` prop of `Card.Title` should not be wrapped in a `<Text>`-based component, so that `<View>`-based children can be passed to it. Either that or the type definition for `CardTitleProps` should be updated to admit its limitation to only `<Text>` components.

for example, here's the desired state:
<img width="689" alt="Screen Shot 2019-04-23 at 12 32 28 PM" src="https://user-images.githubusercontent.com/45078010/56599138-f67e2100-65c3-11e9-94ab-85b1909ee930.png">

and here's how that looks if I _don't_ do the hacky negative left margin on the `title`:
<img width="689" alt="Screen Shot 2019-04-23 at 12 32 51 PM" src="https://user-images.githubusercontent.com/45078010/56599165-07c72d80-65c4-11e9-86ad-cac62b511295.png">

**Comment by jaulz** [comment]
Use left or right prop.

**Comment by chadlavi-casebook** [comment]
> Use left or right prop.

I mentioned left explicitly in my issue. Left has a fixed width of 40, and cannot be styled. It's not possible to do this without a hacky workaround where you apply a negative left margin to the title.

**Comment by jaulz** [comment]
Hm, maybe we should think about having a `leftStyle` and `rightStyle` then. This would be backward compatible and similar to the props we have for other components. Could you please come up with a PR which also includes the change of the type of `title`?

**Comment by chadlavi-casebook** [comment]
> Hm, maybe we should think about having a `leftStyle` and `rightStyle` then. This would be backward compatible and similar to the props we have for other components. Could you please come up with a PR which also includes the change of the type of `title`?

I'm not too familiar with flow-style typing but I'll give it a go. The logic to implement this, anyway, looks fairly straightforward.

**Comment by jaulz** [comment]
Great, thanks! It should be mostly copy&paste from other components 😊Please do not forget the Typescript types as well.

**Comment by chadlavi** [comment]
> Great, thanks! It should be mostly copy&paste from other components 😊Please do not forget the Typescript types as well.

hello, this is me from my personal account. I've just done a PR for this.
