### ISSUE TITLE
TextInput active colour ?

### ISSUE THREAD

**Issue by AlexMachin1997** [callstack/react-native-paper#1031]
Hi,

How can I modify the TextInputs active underline colour?

Cheers,

Alex

**Comment by iyadthayyil** [comment]
To change inactive color you can pass `underlineColor` prop.
To change active color you can pass theme object with primary color.

Example:
```javascript
<TextInput
     label="Text input"
     placeholder="Type something"
     value={this.state.text}
     theme={{ colors: { primary: 'green' } }}
     underlineColor="green"
/>
```
