### ISSUE TITLE
Implement button components, customize subtypes

### ISSUE THREAD

**Issue by chico-malo** [callstack/react-native-paper#1033]
## Describe the feature
My requirement is that I want to wrap my custom elements with button components to realize the click function.

I want to use the click wave effect.

## Motivation

I'll describe the problem here.
In the code, the parent component Hard coding is Text, which prevents me from adding View

**Comment by Trancever** [comment]
Hi @chico-malo . This library follows Material Design Guidelines, and our buttons are compatible with this design pattern. Why don't you build your own custom button that satisfy your needs (They are probably not compatible with Material Design)?

**Comment by satya164** [comment]
You can use the `TouchableRipple` component to add ripple effect with fallbacks for unsupported platforms.

**Comment by chico-malo** [comment]
> 嗨@ chico-malo。该库遵循Material Design Guidelines，我们的按钮与此设计模式兼容。为什么不构建自己的自定义按钮来满足您的需求（它们可能与Material Design不兼容）？

I also know this, but ... I want to have the click effect of material button. if I use the original ones, I can't do it at all.

**Comment by chico-malo** [comment]
> You can use the `TouchableRipple` component to add ripple effect with fallbacks for unsupported platforms.

I really appreciate it． This component is in the document, but I didn't read it carefully. Thank you, it solves my problem.

**Comment by chico-malo** [comment]
> 嗨@ chico-malo。该库遵循Material Design Guidelines，我们的按钮与此设计模式兼容。为什么不构建自己的自定义按钮来满足您的需求（它们可能与Material Design不兼容）？
I know how to solve this problem, thank you for your reply.
