### ISSUE TITLE
FAB.Group Icon source

### ISSUE THREAD

**Issue by AlexMachin1997** [callstack/react-native-paper#1034]
Hi,

I know React-Native-Vector-Icons is used for the icons, but which section is it? MaterialIcons?

Sorry for asking a lot of questions, it's just unclear in the docs

UPDATE: Ok it seems it pulls the icon from MaterialIcons. Shame really as I can't seem find a pencil icon

**Comment by AlexMachin1997** [comment]
I'm going to close this issue as I've managed to solve the issue.

**Comment by satya164** [comment]
You can see the list of icons on the icons page: https://callstack.github.io/react-native-paper/icons.html
