### ISSUE TITLE
How can a designer prepare a mockup for a programmer using Paper?

### ISSUE THREAD

**Issue by scottybo** [callstack/react-native-paper#1036]
Our usual flow is:

1. Project manager creates wireframes
2. Designer takes wireframes and makes them into visual prototype
3. Programmer takes visual prototype and implements it

Paper is new to us and we were wondering whether there are any design resources available to allow us to see all the available components and edit them in a design tool such as Sketch, Figma, Photoshop, Illustrator etc?

Any advice would be greatly appreciated!

**Comment by raajnadar** [comment]
I think this issue has nothing to do with react native paper. Paper is build according to google material design guidelines. Generally UX/UI designer don't create designs according a UI library.

**Comment by cltsang** [comment]
There is no react-native-paper design tool, but there is an [official theme editor for Sketch](https://material.io/tools/theme-editor/theme-editor-home.html).

**Comment by jaysbytes** [comment]
considering solved, closing
