### ISSUE TITLE
Pass views as children to Datatable.Cell

### ISSUE THREAD

**Issue by yousseftarek** [callstack/react-native-paper#1038]
## Feature Description

I'd like to have the ability to pass custom views as children to be displayed within the Datatable.Cell as such:
```sh
<DataTable.Cell >
    <View style={styles.actionCell}>
        <IconButton
              icon="delete"
              color={Colors.red500}
              size={20}
              onPress={() => console.log('Pressed')}
        />
        <IconButton
              icon="edit"
              color={Colors.grey400}
              size={20}
              onPress={() => console.log('Pressed')}
        />
    </View>
</DataTable.Cell>
```

## Motivation

The reason is, as the example above shows, I need to have quick actions available for the rows in the table.

Thank you for your efforts!

**Comment by satya164** [comment]
Just render a view. You don't need to wrap it in `DataTable.Cell`

**Comment by yousseftarek** [comment]
That works just fine! 
Thank You so much!
(Sorry, I wasn't paying attention)

**Comment by ufukucar** [comment]
> 
> 
> Just render a view. You don't need to wrap it in `DataTable.Cell`

Thanks :))

**Comment by 99uno** [comment]
I thought it was my fault and spent many hours analyzing the code. Cell should support custom views.

**Comment by ramirobg94** [comment]
```
 <DataTable.Row>
              <DataTable.Cell>Frozen yogurt</DataTable.Cell>
              <Item />
              <DataTable.Cell numeric>6.0</DataTable.Cell>
            </DataTable.Row>
```
