### ISSUE TITLE
Textinput - unfocus inputs on outer action

### ISSUE THREAD

**Issue by realioseb** [callstack/react-native-paper#1039]
I think it would be better if inputs unfocus on outer action.

Is it achievable somehow or are you planning to integrate?

**Comment by jbinda** [comment]
Hi @realioseb

Did you try to use methods described in docs ?
https://callstack.github.io/react-native-paper/text-input.html#underlineColor

You should achieve what you need by add ref to your TextInput and then call blur() method on that ref in your outer action.

**Comment by Trancever** [comment]
@realioseb This is the default behaviour of React-Native and there is nothing we can do to change it. If you want your TextInput to be automatically blurred on outer action, just put this in ScrollView.
