### ISSUE TITLE
Allow custom size of FAB

### ISSUE THREAD

**Issue by Secretmapper** [callstack/react-native-paper#1040]
## Describe the feature

Allow passing of size to FAB that will apply it to the FAB and the label (or perhaps, `size` and a `sizeLabel` prop)

## Motivation

I wanted to create a custom FAB that's bigger than the current one (single main button). However, since FAB styles are only applied to root, I can only change the size of the main/actual button, and if I do the label stays small.

## Related Issues

https://github.com/callstack/react-native-paper/issues/1010

**Comment by Secretmapper** [comment]
Still a problem

**Comment by potier97** [comment]
sigue  siendo un problema

**Comment by Pra3t0r5** [comment]
Still a problem.

**Comment by VityaSchel** [comment]
Still a problem. Padding + borderRadius does not change size of inner ripple.
