### ISSUE TITLE
RadioButton in RadioButton.Group not showing active status anymore

### ISSUE THREAD

**Issue by dylancompanjen** [callstack/react-native-paper#1041]
## Environment

iOS, Version 2.15.2

## Description

The RadioButton.Group example from the docs would auto show which radiobutton is active. Since a recent update, this doesn't work anymore and I have to put a "Status" prop on the RadioButton. I also noticed that it doesn't pick up my custom color theme (provided in PaperProvider), which also used to work a month ago.

## Reproducible Demo

https://callstack.github.io/react-native-paper/radio-button-group.html

**Comment by brunohkbx** [comment]
Hey @dylancompanjen. I've tried both platforms(android, ios) using this snack example and it is working fine. I also didn't have to pass the `status` prop. :thinking:

**Comment by Taym95** [comment]
> Hey @dylancompanjen. I've tried both platforms(android, ios) using this snack example and it is working fine. I also didn't have to pass the `status` prop. 🤔

Same for me, can you provide a coding example, please?
