### ISSUE TITLE
DatePicker Component

### ISSUE THREAD

**Issue by gjvpaet** [callstack/react-native-paper#1048]
Hi, first of all, thank you for creating this really awesome library! We're using this library at work and I notice that it didn't have a date picker material design component. It would be nice if that will be included in future releases so we can make use of that component.

**Comment by iyadthayyil** [comment]
This library follows [material design guidelines](https://material.io/guidelines/).
And there is no specific component for DatePicker in material design.

You can use [TextInput component](https://callstack.github.io/react-native-paper/text-input.html) from this library with react native's [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html) api and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios) component.

**Comment by jocelynlecomte** [comment]
I don't know if I should comment here or open the same exact issue, but there is now a date picker component in material design: https://material.io/components/pickers/
Your workaround is of course still perfectly valid, but do you plan to embark this new component in a future release ?

**Comment by RichardLindhout** [comment]
I'm working on this in a separate package https://github.com/web-ridge/react-native-paper-dates

**Comment by RichardLindhout** [comment]
Datepicker and timepicker are added to the package!
