### ISSUE TITLE
Prepare a nice/bigger example

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#105]
Our current example is good to see all the components we build but I think it would be nice to create an extra more complex example where all material patterns can shine.

**Comment by satya164** [comment]
Do you have anything in mind? A mockup, example app etc?

**Comment by ahmedlhanafy** [comment]
I think Google used a couple of apps to showcase material design when it was first starting, couldn't find them again tho

**Comment by ferrannp** [comment]
I think about one, I also now that Google used some examples, I have them somewhere. But probably this issue needs to wait till we implement more stuff like FAB.

**Comment by ferrannp** [comment]
Would be nice to implement this https://github.com/chrisbanes/cheesesquare with paper.

**Comment by ferrannp** [comment]
https://github.com/callstack/react-native-paper/issues/428
