### ISSUE TITLE
this.props.theme = undefined

### ISSUE THREAD

**Issue by odesey** [callstack/react-native-paper#1050]
## Background Info
I am new to `react-native` and have been testing out `react-native-paper` with `react-native-navigation`. I came across an example repo in #857, I cloned this repo and have been familiarizing myself with `react-native-paper` and `react-native-navigation`

https://github.com/Trancever/paper-navigation-example

One issue I ran into was that my customized theme was not being applied. I "fixed" this (not sure if this is the right thing to do) by removing the `Provider` component from wrapping the rest of the `Home` and `Overview` components

```javascript
<Provider>
  <View>...</View>
</Provider>
```

Once I removed the `Provider`, the colors I set in the theme started to work.

## Ask your Question

The problem I now have is that in the `Home` and `Overview` components, `this.props.theme` is returning as `undefined`, which means I cannot seamlessly over-ride other component colors using the colors defined in my theme.

My question is, given the example repo above, should I be able to access the theme provider in the 2 screens using `this.props.theme`?

Thanks.

**Comment by Trancever** [comment]
@odosey Yes, you can safely remove that wrapping `Provider` from both `Home` and `Overview` screens, cause `Provider` is already applied thanks to `HOC`.
If you want to access theme in your component, you have to use `withTheme` hoc.

**Comment by odesey** [comment]
Thanks for the clarification @Trancever.

I got the theme to show up in the props by adding the following to your example app:

```javascript
import {
  DefaultTheme,
  Provider as PaperProvider,
  withTheme
} from "react-native-paper";

const theme = {
  ...DefaultTheme,
  roundness: 4,
  colors: {
    ...DefaultTheme.colors,
    background: COLORS.white,
    accent: COLORS.blueShadow,
    primary: COLORS.blue
  }
};

export default function HOC(WrappedComponent) {
  class Wrapper extends Component {
    render() {
      return (
        <Provider testStore={testStore}>
          <PaperProvider theme={theme}>
            <WrappedComponent {...this.props} />
          </PaperProvider>
        </Provider>
      );
    }
  }
  if (WrappedComponent) {
    Wrapper.options = WrappedComponent.options;
  }

  return withTheme(Wrapper); //this guy here
}
```
