### ISSUE TITLE
Add contentContainerStyle property to ModalProps interface

### ISSUE THREAD

**Issue by mihaidaviddev** [callstack/react-native-paper#1051]
ModalProps interface in Modal.d.ts is missing contentContainerStyle property from documentation

```
import * as React from 'react';
import { ThemeShape } from '../types';

export interface ModalProps {
  dismissable?: boolean;
  onDismiss?: () => any;
  visible: boolean;
  children: React.ReactNode;
  theme?: ThemeShape;
}

export declare class Modal extends React.Component<ModalProps> {}
```

**Comment by Taym95** [comment]
I will fix this one!

**Comment by Otik133040040** [comment]
> ModalProps interface in Modal.d.ts is missing contentContainerStyle property from documentation
> 
> ```
> import * as React from 'react';
> import { ThemeShape } from '../types';
> 
> export interface ModalProps {
>   dismissable?: boolean;
>   onDismiss?: () => any;
>   visible: boolean;
>   children: React.ReactNode;
>   theme?: ThemeShape;
> }
> 
> export declare class Modal extends React.Component<ModalProps> {}
> ```

can i private chat with you?

**Comment by Otik133040040** [comment]
@mihaidaviddev can i private chat with you?
