### ISSUE TITLE
Shadow not stacking properly

### ISSUE THREAD

**Issue by greatwitenorth** [callstack/react-native-paper#1053]
## Environment

iOS Simulator
expo: 32.0.0
react: 16.5.0
react-native-paper: 2.15.2

## Description

I currently have a searchbar at the top of my app followed by a scroll view below. The searchbar is set to elevation 2 to show a slight drop shadow. When the list below is scrolled up, the items correctly scroll behind the searchbar, but the searchbar's  shadow disappears as seen in the image below:

<img width="363" alt="Screenshot 2019-05-06 10 30 15" src="https://user-images.githubusercontent.com/547583/57236125-f893a700-6fe9-11e9-9b01-42e815883c54.png">

## Reproducible Demo

This is what I currently have in my home screen:

```js
<View style={styles.container}>
    <View style={{flexDirection: "row", marginLeft: 10, marginRight: 10, position: "relative"}} >
        <Searchbar
            style={{flex: 1, elevation: 2}}
            placeholder="Search Collection"
            onChangeText={query => {
                this.setState({query});
            }}
            value={query}
        />
    </View>
    <ScrollView contentContainerStyle={styles.contentContainer}>
        <GameListing
            image={"https://picsum.photos/400/400"}
            title={"Thing"}
            year={"2017"}
        />
        <GameListing
            image={"https://picsum.photos/400/400"}
            title={"Thing 2"}
            year={"2018"}
        />
    </ScrollView>
</View>
```

**Comment by iyadthayyil** [comment]
Try adding some padding to searchBar's parent View.

**Comment by greatwitenorth** [comment]
That seems to help, but I don't see the list item moving below the shadow since the View is now padded 5px down:


![collection](https://user-images.githubusercontent.com/547583/57244126-5ed5f500-6ffd-11e9-9492-ce85694a379d.gif)

**Comment by satya164** [comment]
Absolutely position the search bar and add some top margin to your list. This is not an issue paper, it's because views are clipped on Android in RN.
