### ISSUE TITLE
Upgrade React native version to 0.59.8

### ISSUE THREAD

**Issue by hussainahmad** [callstack/react-native-paper#1058]
There is an [RTL issue](https://github.com/facebook/react-native/issues/24267)  which introduced in `0.59.3` due this [PR](https://github.com/facebook/react-native/commit/b3c74967ca6b20d7bda84c690ae3a99dfe255843) , Now this is reverted in with this [Commit](https://github.com/facebook/react-native/commit/f3801d90fad4720357989d6b5bdf630ef874ae5d) and published in `0.59.8` ,

**Comment by satya164** [comment]
wdym by upgrade React Native? Paper doesn't depend on a particular version of RN

**Comment by hussainahmad** [comment]
Thanks , there is a confusion, and I got it thank you.
