### ISSUE TITLE
Outlined TextInput - placeholder and border colors

### ISSUE THREAD

**Issue by realioseb** [callstack/react-native-paper#1059]
## Describe the feature
It would be great to add possibility to add different colors props for placeholder and border

**Comment by jaysbytes** [comment]
related to #1054

**Comment by samuelmataraso** [comment]
@realioseb try this: [https://github.com/callstack/react-native-paper/issues/656](#656)

**Comment by jbinda** [comment]
As @samuelmataraso and @jaysbytes  pointed you can use theme color object to set up colors. Currently border and placeholder color is set up by the same prop - if anything change it will be cover with PR related to this issue: #688
