### ISSUE TITLE
Cross fade icon animation time

### ISSUE THREAD

**Issue by jordy-wijman** [callstack/react-native-paper#1064]
## Describe the feature
The cross fade icon animation is now hardcoded to value 200, it would be awesome if this could be changed through props.

https://github.com/callstack/react-native-paper/blob/f4ef4bddc28764d8f87b3f98ccf8773d902535d2/src/components/CrossFadeIcon.js#L60-L64

## Motivation
I have a collapse functionality in my application, upon collapsing it executes a animation, however this animation is 300ms instead of 200ms, so the cross fade icon animation finishes first which I do not want.

## Related Issues
None I think

**Comment by Trancever** [comment]
@jordy-wijman It should be controlled via theme just like modal animatyion speed is controlled in 3.0 branch. Would you like to implement that?

**Comment by Taym95** [comment]
Hey @jordy-wijman, if you are not working on this issue I would like to take it over.

**Comment by jordy-wijman** [comment]
Hey @Trancever yeah I could do that! However @Taym95 offered to help here, if you could then yes please, I'm quite busy atm so it would take some time.

**Comment by lukewalczak** [comment]
Closing - fixed by #1067
