### ISSUE TITLE
Child components in Modal are destroyed when visible = false

### ISSUE THREAD

**Issue by hanwenbo** [callstack/react-native-paper#1065]
Why is it that when Modal sets visible = false all the child components in Modal are destroyed and perform componentWillUnmount so that I can't save the paged data loaded in the page

**Comment by jbinda** [comment]
Hi - I modified the title because of its length

**Comment by satya164** [comment]
Modal unmounts the components because it is unnecessary to keep things rendered when they are not visible and will increase memory usage. If you need to preserve the state inside modal, [lift the state up](https://reactjs.org/docs/lifting-state-up.html) to a parent component
