### ISSUE TITLE
IconButton performance and Render 

### ISSUE THREAD

**Issue by DevSoFar** [callstack/react-native-paper#1070]
## Environment

React native mobile, ios/android 
 
## Description
I have two problem: 
1-Click on the IconButton is so slow when user click even in production. 

2- IconButton not rounded in Android version.

**Comment by wojteg1337** [comment]
Hello @DevSoFar,
1. Could you provide an example? On what platform do you face performance issues?
2. It's fixed by @pan-pawel. I've merged it today so we will release a new version soon

**Comment by ferrannp** [comment]
Fixed.
