### ISSUE TITLE
Menu goes outside of screen when many items are present

### ISSUE THREAD

**Issue by jordy-wijman** [callstack/react-native-paper#1075]
## Environment
Pretty sure it happens everywhere, I checked on iOS and Android, not web.

## Description
When using the menu component with many items, it overflows out of the screen, towards the top. See the demo for an example. I noticed that it also expands towards the wrong side (top instead of bottom), this only happens when lots of items are present. It would be great if it would just expand towards the bottom with a scrollable view inside of it.

## Reproducible Demo
Here is a snack that demo's the issue, I just took the example in the docs, and copy pasted one of the items many times. You will see that the component will overflow out of the screen.
https://snack.expo.io/Syejcq62E

**Comment by iyadthayyil** [comment]
Will fix this
