### ISSUE TITLE
Docs for integration with react-router-native?

### ISSUE THREAD

**Issue by Shriram-Balaji** [callstack/react-native-paper#1077]
Hey! First of all, thanks for making react-native-paper. Its great to find such a useful component library. 

I'd like to know if there's a document that you can point me to integrate with react-router-native? I'm able to see that [BottomNavigation docs](https://callstack.github.io/react-native-paper/bottom-navigation.html) explicitly mention how to integrate with react-navigation, but I'm using react-router-native and react-router-dom because web support for [react-navigation](https://reactnavigation.org/docs/en/web-support.html) is still experimental, and I had a couple of issues (eg. Couldn't get the browser back button working to goBack to previous page on browserHistory) with it while trying out on web.

**Comment by Trancever** [comment]
Unfortunately we don't have, but there shouldn't be many differences between integrating it with react-navigation or any other lib since paper is navigation agnostic framework

**Comment by Shriram-Balaji** [comment]
@Trancever thanks for the response :+1:
