### ISSUE TITLE
Card subheading wrap lines

### ISSUE THREAD

**Issue by JBaczuk** [callstack/react-native-paper#1080]
## Describe the feature

The subheading property of a card would wrap lines

## Motivation

If the screen is not wide enough it limits the text to a few words. Even on large phones:

<img width="361" alt="Screen Shot 2019-05-21 at 9 22 19 AM" src="https://user-images.githubusercontent.com/8162417/58108975-fb75c680-7ba9-11e9-9c36-851042827d08.png">

## Related Issues

?

**Comment by Taym95** [comment]
Do you think should add multiline?

**Comment by JBaczuk** [comment]
> Do you think should add multiline?

Yeah I think it should wrap to the next line.
