### ISSUE TITLE
Remove / Rename prepare script

### ISSUE THREAD

**Issue by TikiTDO** [callstack/react-native-paper#1082]
## Environment

Any version.

## Description

When managing running `yarn`, the package manager will automatically run several [specifically named scripts](https://yarnpkg.com/en/docs/package-json#toc-scripts). 

This in turn can cause a lot of weird issues when running in yarn workspaces due to this script running outside of the expected order. While this is strictly a `yarn` bug, the direct cause is using the fact that this lib uses a script with a special meaning.

Given that all the script seems to do is generate a build artifact used by a particular babel gem a simple fix would be to rename the script to some other name, and then to run it once whenever releasing a new version. This would both speed up the build, and prevent any weird out-of-order issues.

## Reproducible Demo

The bug is intermittent, but I have some more details here:

https://github.com/yarnpkg/yarn/issues/7212#issuecomment-493720324

**Comment by satya164** [comment]
> the direct cause is using the fact that this lib uses a script with a special meaning
> rename the script to some other name, and then to run it once whenever releasing a new version

the whole point of using `prepare` is to do less work when publishing by automatically running the script. we don't want to run an extra script manually before publishing. the script also needs to be run on git installs etc. automatically so the lib can be consumed from GitHub.

> This would both speed up the build

we don't have any issues with build speed, the babel plugin is pretty fast.

> and prevent any weird out-of-order issues

what kind of out of order issues?

**Comment by TikiTDO** [comment]
The issue is an intermittent failure when installing yarn libraries in a CI environment. 

Yarn tries to give the `prepare` script it's own environment, which can conflict with the parent instance of yarn. This can cause one of the instances of yarn to extract an archive that does not exist, or is still being downloaded by the other, which causes the an error akin to this one:

`error https://registry.yarnpkg.com/glob/-/glob-7.1.3.tgz: Extracting tar content of "/home/adys/.cache/yarn/v4/npm-glob-7.1.3-3960832d3f1574108342dafd3a67b332c0969df1/node_modules/glob/.yarn-tarball.tgz" failed, the file appears to be corrupt: "ENOENT: no such file or directory, open '/home/adys/.cache/yarn/v4/npm-glob-7.1.3-3960832d3f1574108342dafd3a67b332c0969df1/node_modules/glob/changelog.md'"`

The worst part is that the failing library can differ arbitrarily based on how fast any given lib is fetched, so debugging is is particularly difficult.

There's a lot more info in the link at the bottom of my post.

I have my own fork of rn-paper with the prepare script removed, and it does not affect my ability to run the lib from github. As I mentioned before this command seems to be specific to a babel plugin which does not appear to be a included in the default RN install.
