### ISSUE TITLE
Wrong tag for 3.0.0-alpha.1

### ISSUE THREAD

**Issue by jaulz** [callstack/react-native-paper#1087]
It seems the version `3.0.0-alpha.1` got a wrong tag: 
![image](https://user-images.githubusercontent.com/5358638/58248542-ab8b3100-7d5c-11e9-8540-5c1cbda807b5.png)

**Comment by jaulz** [comment]
Solved as far as I can see 😊

**Comment by Trancever** [comment]
@jaulz Yep, should be good now
