### ISSUE TITLE
[QUESTION] How to disable List.Accordion

### ISSUE THREAD

**Issue by fgagneten** [callstack/react-native-paper#1092]
I would like to disable specific List.Accordion depends on condition, Is it possible? Override onPress so I can avoid expanding the accordion. I do not want to expand the accordion.

Thanks

**Comment by lukewalczak** [comment]
Hey @fgagneten 	, what is your use case for that? Can you tell us how it should look like? Honestly, I'm not sure if Material Design is supporting that.

**Comment by jaysbytes** [comment]
inactive, closing
