### ISSUE TITLE
Republish example app on expo

### ISSUE THREAD

**Issue by brunohkbx** [callstack/react-native-paper#1093]
The current version is very outdated.

Could someone please republish it with the latest updates?

**Comment by ferrannp** [comment]
@satya164 is in your account?

**Comment by brunohkbx** [comment]
@satya164 I think only `Collaborators` can edit environment variables on CircleCI and it's not possible to retrieve the original value after adding.

Do you mind if I set up this workflow to deploy? It's related to #276

**Comment by satya164** [comment]
I'll publish it.

> I think only Collaborators can edit environment variables on CircleCI and it's not possible to retrieve the original value after adding.

If you can run a script in the CI, you can access the env variables. All it takes is to send a PR adding a script which logs them/sends them to a server and you have them.

**Comment by ferrannp** [comment]
No need to keep this open. @satya164 feel free to publish it or give somebody else accces, we can chat on Discord.
