### ISSUE TITLE
Dynamically choose Icon set from react-native-vector-icons through a prop

### ISSUE THREAD

**Issue by yoeven** [callstack/react-native-paper#1098]
Wouldn't it better to choose an icon by exposing a prop rather than having a render method to render another icon component from the same react-native-vector-icons library. I would suggest a prop for the Icon component that allows us to choose an icon set. This has actually been done by [react-native-elements](https://react-native-training.github.io/react-native-elements/docs/icon.html), it would be great to have this simple feature in this library along with all the other components.

**Comment by jbinda** [comment]
I agree that its the most flexible way to select Icons.

I will take a closer look on that when we merge #1091

**Comment by jbinda** [comment]
Feature will be handle with #1210
