### ISSUE TITLE
Migrate project to TypeScript

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#1103]
Flow gives us a lot of issues when upgrading RN version. We want to migrate to TS which gives a much better DX.

**Comment by wojteg1337** [comment]
We are working on migration to TS from Flow. 
There is a feature branch called `feat/flow-to-typescript`

List of migrated components:
- Button
- Snackbar
- Surface
- Appbar
- Avatar
- Card
- DataTable
- Modal
- SearchBar
- Dialog
- Drawer 
- FAB


For now, we keep `.js` files and `.tsx` files - Right after code review we will get rid of `.js` files.

**Comment by Trancever** [comment]
Good job @wojteg1337 !
