### ISSUE TITLE
FAB Group broken on snack

### ISSUE THREAD

**Issue by netochaves** [callstack/react-native-paper#1105]
## Environment

Snack.

## Description

When i try to run the fab group example on snack i'm getting this error.
![image](https://user-images.githubusercontent.com/19830660/58963718-0b81ce80-8784-11e9-8ff7-baa1e70cc790.png)

## Reproducible Demo

Just run on [snack](https://snack.expo.io/BJID18r0E?name=FAB.Group&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Ffab-group.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20FAB%2C%20Portal%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aexport%20default%20class%20MyComponent%20extends%20React.Component%20%7B%0A%20%20state%20%3D%20%7B%0A%20%20%20%20open%3A%20false%2C%0A%20%20%7D%3B%0A%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20<Portal>%0A%20%20%20%20%20%20%20%20<FAB.Group%0A%20%20%20%20%20%20%20%20%20%20open%3D%7Bthis.state.open%7D%0A%20%20%20%20%20%20%20%20%20%20icon%3D%7Bthis.state.open%20%3F%20%27today%27%20%3A%20%27add%27%7D%0A%20%20%20%20%20%20%20%20%20%20actions%3D%7B%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%20icon%3A%20%27add%27%2C%20onPress%3A%20()%20%3D>%20console.log(%27Pressed%20add%27)%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%20icon%3A%20%27star%27%2C%20label%3A%20%27Star%27%2C%20onPress%3A%20()%20%3D>%20console.log(%27Pressed%20star%27)%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%20icon%3A%20%27email%27%2C%20label%3A%20%27Email%27%2C%20onPress%3A%20()%20%3D>%20console.log(%27Pressed%20email%27)%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%20icon%3A%20%27notifications%27%2C%20label%3A%20%27Remind%27%2C%20onPress%3A%20()%20%3D>%20console.log(%27Pressed%20notifications%27)%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%5D%7D%0A%20%20%20%20%20%20%20%20%20%20onStateChange%3D%7B(%7B%20open%20%7D)%20%3D>%20this.setState(%7B%20open%20%7D)%7D%0A%20%20%20%20%20%20%20%20%20%20onPress%3D%7B()%20%3D>%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(this.state.open)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20do%20something%20if%20the%20speed%20dial%20is%20open%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%20%20%20%20%2F>%0A%20%20%20%20%20%20<%2FPortal>%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D&dependencies=react-native-paper)

**Comment by netochaves** [comment]
The error message is pretty clear, adding the Provider wrapper on Render will solve the problem, code after change: 
```js
import * as React from 'react';
import { FAB, Portal, Provider} from 'react-native-paper';

export default class MyComponent extends React.Component {
  state = {
    open: false,
  };

  render() {
    return (
      <Provider>
        <Portal>
          <FAB.Group
            open={this.state.open}
            icon={this.state.open ? 'today' : 'add'}
            actions={[
              { icon: 'add', onPress: () => console.log('Pressed add') },
              { icon: 'star', label: 'Star', onPress: () => console.log('Pressed star')},
              { icon: 'email', label: 'Email', onPress: () => console.log('Pressed email') },
              { icon: 'notifications', label: 'Remind', onPress: () => console.log('Pressed notifications') },
            ]}
            onStateChange={({ open }) => this.setState({ open })}
            onPress={() => {
              if (this.state.open) {
                // do something if the speed dial is open
              }
            }}
          />
        </Portal>
      </Provider>
    );
  }
}
```
can i send a pr to fix this in docs?

**Comment by raajnadar** [comment]
Sure send a PR to fix this issue
