### ISSUE TITLE
Android: FAB group open changes status bar color

### ISSUE THREAD

**Issue by jtklein** [callstack/react-native-paper#1108]
## Environment
The screenshots are tacken from production version, i.e. Android apk run on an Android emulator.

## Description

When pressing a FAB group button, the Android status bar changes color. Happens on emulator and actual device. Expected behaviour: the color of the status bar stays the same.
The screenshots are from before and after expanding and closing the FAB group.

## Reproducible Demo
The FAB group is not wrapped in a Portal because I would like it to stay on one page. In case this helps a bit. Let me know if you need more information.
![Screenshot_1559762397](https://user-images.githubusercontent.com/17345891/58983798-e4ed8300-87d7-11e9-8b25-53731a68a767.png)
![Screenshot_1559762402](https://user-images.githubusercontent.com/17345891/58983805-e919a080-87d7-11e9-95b7-4d2bd0065355.png)
![Screenshot_1559762405](https://user-images.githubusercontent.com/17345891/58983814-eb7bfa80-87d7-11e9-943b-0e39ca301df5.png)

**Comment by raajnadar** [comment]
Can you link a repro?? A snack will be easier to debug the issue

**Comment by jtklein** [comment]
Thanks for your interest!
The issue seems to have disappeared after upgrading some dependencies. (Expo -> 33 and others)
Closing for now
