### ISSUE TITLE
Loading indicator in icon button

### ISSUE THREAD

**Issue by Yajan** [callstack/react-native-paper#1112]
## Describe the feature
As we have loading indicator in button, is it possible to have loading indicator in icon button with animation? 

## Motivation
It is useful to display an action icon once pre actions are done.

**Comment by mauro0x52** [comment]
+1

**Comment by iamisathya** [comment]
+1

**Comment by angelxmoreno** [comment]
The PR to add the loading prop is stale. are there any other solutions?
