### ISSUE TITLE
Remove imports from expo

### ISSUE THREAD

**Issue by raajnadar** [callstack/react-native-paper#1119]
Remove imports from expo package

https://github.com/expo/expo/issues/4501 to remove this warning.

https://github.com/callstack/react-native-paper/blob/8746abab9d26bb7eef76ec8f08648bb77d6fb04f/src/components/Appbar/AppbarHeader.js#L36

https://github.com/callstack/react-native-paper/blob/8746abab9d26bb7eef76ec8f08648bb77d6fb04f/src/components/Icon.js#L13

**Comment by brentvatne** [comment]
not necessary to remove these as we have patched the expo global to not raise these warnings. in the future when [optional imports](https://github.com/react-native-community/discussions-and-proposals/issues/120) are supported in metro we can get rid of the global and instead just wrap an import with try/catch to make it optional

**Comment by ferrannp** [comment]
Awesome!
