### ISSUE TITLE
[WEB] Style not working properly while using Icon on Component (RNW latest)

### ISSUE THREAD

**Issue by hedikasmanto** [callstack/react-native-paper#1120]
## Environment

Using RNW 0.11.1 - latest (current : 0.11.4)

## Description

Component style looks great while using RNW 0.11.0 (with Icon)
![image](https://user-images.githubusercontent.com/9128724/59166920-96821080-8b58-11e9-9ff1-4a6089860f7f.png)

Component style lost padding while using RNW 0.11.1-latest (with Icon)
![image](https://user-images.githubusercontent.com/9128724/59166981-01334c00-8b59-11e9-8628-a108da5dcf2d.png)

Component style looks great while using RNW 0.11.1 - latest (without Icon)
![image](https://user-images.githubusercontent.com/9128724/59167031-5ec79880-8b59-11e9-9b3e-573905e37faf.png)

## Reproducible Demo
Just use example demo with Icon and upgrade RNW to latest

**Comment by jaysbytes** [comment]
It is not an issue if it is related to just one version of RNW. If the issue still occurs consider adding code to reproduce
