### ISSUE TITLE
IconButton: Not using primary theme color

### ISSUE THREAD

**Issue by RyanMcDonald** [callstack/react-native-paper#1122]
## Environment

react-native-paper@2.16.0

## Description

The IconButton is currently [using the text color](https://github.com/callstack/react-native-paper/blob/master/src/components/IconButton.js#L95) from the theme provider. It should use the primary color instead, to be consistent with the Button component.

**Comment by TrzyRazyCztery** [comment]
Hi @RyanMcDonald 
Thanks for the message!
I'm not sure about it if treat IconButton more like clickable Icon so when we follow material design guidelines icons should have text colour. @Trancever what do you think about it?
