### ISSUE TITLE
Can't transform Text to uppercase inside Button

### ISSUE THREAD

**Issue by Morsmetus** [callstack/react-native-paper#1126]
### Current behaviour
Can't transform text to uppercase inside button

### Expected behaviour
textTransform: 'uppercase' should display uppercase letters inside button

### Code sample
        <Button style={props.disabled ? styles.disabledButton : styles.primaryButton}>
            <Text style={styles.buttonFont}>{props.loading ? "Loading" : props.children}</Text>
        </Button>

         buttonFont: {
            fontSize: 16,
            fontFamily: 'Mont',
            color: Colors.white,
            textTransform: 'uppercase',
        }

### What have you tried

- passing text directly into Button component without Text, but in that case i Can't apply font
- tried to apply uppercase={true} to both Text and Button, but it didn't work

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 8
| react-native          |  "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
| react-native-paper    | "^2.16.0",
| node                  | v10.15.2
| npm or yarn           | 6.9.0
| expo sdk              |     "expo": "^32.0.0",

**Comment by satya164** [comment]
You're rendering `Text`, which is a React Native component, not from this library. I don't think the `Button` component matters in this case. If this is supposed to be working and is not working, you should open an issue in the React Native repo.

**Comment by jonathanmv** [comment]
You can see the [uppercase property](https://callstack.github.io/react-native-paper/button.html#uppercase) to `false`. However, the children of the button will be the text string, not a Text component.

```
<Button uppercase={false}>The Case Is Maintained</Button>
<Button>this looks all uppercase</Button>
```

**Comment by parmarravi** [comment]
I have a text "contact us"
I want to show the button as Contact Us.
But it's not working 

 ```
contactBtnStyle: {
    color: PUMPKIN_ORANGE,
    textTransform: 'capitalize',
  },

<Button
                accessibilityLabel="EditProfileScreen-CallSupport"
                style={styles.contactBtnStyle}
                mode="text"
                uppercase={false}
                onPress={callSupport}>
                {CONTACT_US[code]}
              </Button>
```
