### ISSUE TITLE
React Hooks support for ThemeProvider

### ISSUE THREAD

**Issue by halileohalilei** [callstack/react-native-paper#1127]
## Describe the feature

We should have the option to use `Theme`'s with React's `useContext` hook, instead of wrapping our components with HOC's using `withTheme`.

## Motivation

It looks like the new Hooks API is here to stay, and [Material UI](https://github.com/mui-org/material-ui/issues/15231) has mostly migrated to using it. It would be nice to reflect the same changes here too.

## Related Issues

I honestly couldn't find any issue related to React Hooks.

**Comment by GollyJer** [comment]
It already does I think.
https://github.com/callstack/react-theme-provider

**Comment by ferrannp** [comment]
We need to update `react-theme-provider` https://github.com/callstack/react-native-paper/issues/1085. If somebody can do it, feel free to take it :). Let's have the discussion in that issue.
