### ISSUE TITLE
state swap of RadionButton not working using react native paper 2.16.0

### ISSUE THREAD

**Issue by gabriel-silva** [callstack/react-native-paper#1129]
## Current behaviour

state swap not working in version 2.16, in version 2.15.2 the RadioButton working normal.

## Expected behaviour

RadioButton working using react-native-paper how version 2.15.2

**Comment by ferrannp** [comment]
Hello @gabriel-silva,

I tried the Radio Button for `2.16.0` in our [example](https://github.com/callstack/react-native-paper/tree/master/example) app and it works fine for me. Could you share a repo or a snack with your code to try it out?

**Comment by rjerue** [comment]
@ferrannp

May be related to https://github.com/callstack/react-native-paper/issues/1117

**Comment by gabriel-silva** [comment]
Yeah @rjerue, I am with problem. in version 2.13 or 2.15.2 working very nice.

**Comment by gabriel-silva** [comment]
> Hello @gabriel-silva,
> 
> I tried the Radio Button for `2.16.0` in our [example](https://github.com/callstack/react-native-paper/tree/master/example) app and it works fine for me. Could you share a repo or a snack with your code to try it out?

@ferrannp, repo https://snack.expo.io/@rjerue/radiobutton.group

**Comment by ferrannp** [comment]
All right, let's close this one and keep the discussion in #1117.
