### ISSUE TITLE
FAB: loading prop not working if there is no label

### ISSUE THREAD

**Issue by netochaves** [callstack/react-native-paper#1130]
## Environment
react-native: ^0.59.6,
react-native-paper: ^2.16.0
## Description
The loading prop should show an activity indicator when it is true, but in my case it is not.
My FAB component
```js
<FAB
   icon="arrow-forward"
   style={styles.fab}
   onPress={this.next}
   loading
/>
```
![image](https://user-images.githubusercontent.com/19830660/59471196-c78c6a80-8e10-11e9-96c1-0b167c4563a2.png)

**Comment by netochaves** [comment]
Looking at [components/FAB/FAB.js#L220](https://github.com/callstack/react-native-paper/blob/3b19f18822200bdbb33f4d8ff32faa525dc810b6/src/components/FAB/FAB.js#L220) i realize that to show the indicator, label has to be true too, why this? if i remove this extra condition the loading works fine.

**Comment by ferrannp** [comment]
@Trancever do you remember why we show loading only when there is a label (extended FAB)? That was an external contribution so not sure if we missed something or is in the spec?

**Comment by Trancever** [comment]
@ferrannp It was buggy in non extended type, the position was incorrect. If we can make sure it works fine for different icon/loading/label props combinations and position is correct I am ok with accepting a PR.

**Comment by netochaves** [comment]
I made all the combinations with loading, the position is fine i think

![image](https://user-images.githubusercontent.com/19830660/59519612-9d818980-8e9e-11e9-89dc-6c52f99b02ba.png)
icon + loading -> false

![image](https://user-images.githubusercontent.com/19830660/59519845-28628400-8e9f-11e9-86be-145a8a36f8c6.png)
label + loading

![image](https://user-images.githubusercontent.com/19830660/59519962-619af400-8e9f-11e9-8da5-58047e0d1d10.png)
loading without icon and label

@Trancever should the label be showing when the loading is true? because if it is not, then the condition must be 
```js
...
{loadind ? (
  <ActivityIndicator size={18} color={foregroundColor} />
) : null}
{label && loading !== true ? (
...
```
