### ISSUE TITLE
Hi! TextInput with button like show 

### ISSUE THREAD

**Issue by ProKashif** [callstack/react-native-paper#1133]
## Ask your Question

I have tested TextInput and tried to add button inside it but failed. Is there any support for the button in TextInput.

I have also added an image to explain my question.
![2019-06-14 14 47 29](https://user-images.githubusercontent.com/33416799/59500953-e98af900-8eb3-11e9-9efa-e66ba0c45d93.png)

**Comment by ferrannp** [comment]
We plan to add such trailing icon/button. See https://github.com/callstack/react-native-paper/issues/792. Let's keep the discussion there.

**Comment by karthikcyadav98** [comment]
hi, did you find any solution? please let me know

**Comment by karthikcyadav98** [comment]
Hi, did you find any solution? please reply it will be very helpful.

**Comment by kkkasio** [comment]
@ferrannp is this function already available?
