### ISSUE TITLE
RNW - TextInput with wrong height

### ISSUE THREAD

**Issue by brunohkbx** [callstack/react-native-paper#1135]
## Environment
"expo": "^33.0.0"
"react": "16.8.3"
"react-dom": "^16.8.6"
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz"
"react-native-web": "^0.11.4"

## Description
RNW renders TextInput with a wrong height. Its focus shouldn't overflow the container.
![Screenshot from 2019-06-14 13-33-11](https://user-images.githubusercontent.com/6487206/59524400-2b16a680-8eaa-11e9-82d9-b8a9157af54d.png)

## Reproducible Demo
Just render a TextInput using expo 33 on web

**Comment by brunohkbx** [comment]
cc @jbinda

**Comment by jaulz** [comment]
Could it be related to this https://github.com/callstack/react-native-paper/pull/1132? I noticed similar issues after upgrading.

**Comment by jbinda** [comment]
Hi guys - I will take a look and try to fix it.

**Comment by jbinda** [comment]
should be fine after merge #1132 as jaulz wrote
