### ISSUE TITLE
Flex doesn't work on Button

### ISSUE THREAD

**Issue by cpboyd** [callstack/react-native-paper#1137]
## Environment

Expo 33 & react-native-paper 2.16.0.

## Description

Applying `{flex: 1}` to the `Button` only applies to the `Surface` container, with no clear ability to properly stretch the `TouchableRipple` to fit.

As a result, the outline of the button fills the space, but the actual touchable portion does not.

**Comment by notjulian** [comment]
working example

`        <View style={{flex: 1, flexDirection: 'row', justifyContent: 'space-between', marginTop: 10}}>
          <Button
            onPress={() => this.props.navigation.navigate(NavScreen.PASSWORD_RESET_SCREEN)}
            >{strings.forgottenPassword}</Button>

          <Button
            onPress={() => this.props.navigation.navigate(NavScreen.REGISTER_SCREEN)}
            >{strings.register}</Button>
        </View>`

![photo5830024479613497946](https://user-images.githubusercontent.com/2241601/60647133-4b98a780-9e3d-11e9-8f9b-9efd27c3d560.jpg)

**Comment by notjulian** [comment]
same behavior with latest version

**Comment by Trancever** [comment]
@notjulian @cpboyd There is no need to set `flex: 1` in a button. Just wrap it with an `View`. Check this [Snack](https://snack.expo.io/@trensik/blessed-cheese) .
