### ISSUE TITLE
Is there a way to get BottomNavigation to unmount / remount components?

### ISSUE THREAD

**Issue by marchaos** [callstack/react-native-paper#1141]
From what I can tell, once you navigate to a tab using bottom navigation, the component rendered is not mounted / remounted when navigating away / back again. Is there any way to get it to unmount the component when you navigate away?

**Comment by egunsoma** [comment]
Exactly, control over this would nice to have!

**Comment by satya164** [comment]
You have `renderScene` method where you can return what's rendered. You can check if a route is focused and if not, return null.

**Comment by jvgaeta** [comment]
@satya164 - That doesn't seem to be correct. Only the `renderIcon` method is passed a focused flag. The `renderScene` method does not. I'm looking to unmount an expensive component to improve performance. It seems hacky to use the `renderIcon` method to accomplish that.

**Comment by satya164** [comment]
You already own the navigation state and index. You can use it to check if the route is focused.

**Comment by jvgaeta** [comment]
Ah, okay. I think I understand how to do it now. Thanks!

**Comment by satya164** [comment]
```js
renderScene = ({ route }) => {
  if (this.state.routes[this.state.index].key !== route.key) {
    return null;
  }

  // rest
}
```

**Comment by jvgaeta** [comment]
@satya164 - Aha. So, it makes sense now. I misunderstood the renderScene method thinking that the route is only called with the route I'm navigating to. Thanks!

**Comment by nmateo** [comment]
How can i unmount screen when navigation to an other screen with this, thanks: 
```` 
   const renderSceneHome = BottomNavigation.SceneMap({
        
        home: HomeScreen,
        messages: MessageScreen,
        offers: OffersScreen,
        offer_view: OfferViewScreen,
        historic: HistoryScreen,
        account: AccountScreen,
    });

 <BottomNavigation
      navigationState={{ index: indexHome, routes: routesHomeFlow }}
      onIndexChange={setIndexHome}
      renderScene={renderSceneHome}
      theme={Theme}
      inactiveColor="white"
      sceneAnimationEnabled={true}
      sceneAnimationType="shifting"
      barStyle={{ height: ((indexHome === 3) || (indexHome === 5) ? 0 : 70), backgroundColor: Theme.colors.secondary }}
      safeAreaInsets={{ bottom: 0 }}
/>
```
