### ISSUE TITLE
TextInput label position 

### ISSUE THREAD

**Issue by pixelize** [callstack/react-native-paper#1144]
My TextInput styles:

```jsx
const styles = StyleSheet.create({
  inputPaper: {
    backgroundColor: "transparent",
    height: 50,
  },
});
```

My Input:

```jsx
 <RNPTextInput
      style={styles.inputPaper}
      padding="none"
      label={children} />
```

Result with inspector:

![](https://i.imgur.com/W5feWGo.png)

My question is : How can i move the label on top of the input container please ?

What i'd like : 

![](https://i.imgur.com/AfJ2Pf7.png)

**Comment by jbinda** [comment]
Hi @pixelize 

Thanks for posting your message !

Currently the label position has predefined top position. We need internal discussion to decide if we want the feature to modify it.

**Comment by pixelize** [comment]
@jbinda Good to know, thanks for the reply @jbinda, this feature would be awesome for me ! Very good work on the whole RN paper otherwise :)

**Comment by jbinda** [comment]
Hi! after internal discussion we diceded not to implement this feature. Regards

**Comment by pixelize** [comment]
@jbinda thanks for having track this issue

**Comment by pixelize** [comment]
related https://github.com/callstack/react-native-paper/pull/1167

**Comment by sjonchhe** [comment]
Has anybody fonud any solution fotr this??
