### ISSUE TITLE
ProgressBar indeterminate prop not working

### ISSUE THREAD

**Issue by hamidfzm** [callstack/react-native-paper#1146]
## Environment
- react-native: 0.59.9
- react-native-paper: 2.16.0

## Description
When we pass indeterminate prop to progress bar in react native paper we expect something like this:
![ezgif-4-5fb9a37944c1](https://user-images.githubusercontent.com/5591800/59968198-09bd5680-954b-11e9-8c91-717400205b30.gif)

But nothing is animating and the progress bar is static. Unless I missed a step in creating an intermediate progress bar this is a bug!

## Reproducible Demo
Just use this component!
```jsx
<ProgressBar color={primary} indeterminate animating/>
```
I also edited react native paper expo example progress bar. You can check it on expo snack too
https://snack.expo.io/@hamidfzm/github.com-callstack-react-native-paper:example

**Comment by Trancever** [comment]
@hamidfzm Can you try 3.0.0-alpha.2 version? It works fine in our example app.

**Comment by lukewalczak** [comment]
Hey @hamidfzm 	, in version `2.16.0` among available [props](https://github.com/callstack/react-native-paper/blob/v2.16.0/src/components/ProgressBar/ProgressBar.js#L10-#L24) there is no prop called `indeterminate` (we were not supporting it yet) however, we are going to release soon version `3.0.0` where this functionality is supported. If you need it, try to use `3.0.0-alpha.2` version mentioned above.
