### ISSUE TITLE
Appbar.content onPress props typescript interface

### ISSUE THREAD

**Issue by yogurtandjam** [callstack/react-native-paper#1148]
## Environment

Adding onPress property, which is part of the Appbar.Content api, in a typescript environment 

## Description

onPress is not on the ts interface

## Fix

https://github.com/callstack/react-native-paper/pull/1147

**Comment by Trancever** [comment]
@yogurtandjam Did you try latest master? We rewrote whole codebase to use typescript so it should be fixed

**Comment by yogurtandjam** [comment]
Yup! Sorry forgot to close this issue when the PR was rendered obsolete
