### ISSUE TITLE
Custom font in Chips

### ISSUE THREAD

**Issue by FoxInFlame** [callstack/react-native-paper#1153]
## Describe the feature

Chips should be able to support custom fonts through the `theme` prop.

## Motivation

Many other components support this, and it hinders developers from using custom fonts throughout their app to establish their identity.

**Comment by Trancever** [comment]
@FoxInFlame You can customize font using textStyle prop for now.

**Comment by Trancever** [comment]
@satya164 Should we add possibility to also customize it via theme prop or textStyle prop is enough?

**Comment by FoxInFlame** [comment]
@Trancever Ah, I'm sorry, I must've missed that commit. Thank you! I'll leave this issue open in case further discussion will happen.
