### ISSUE TITLE
Set custom background colour for Chips

### ISSUE THREAD

**Issue by vpuonti** [callstack/react-native-paper#1154]
## Describe the feature

Please allow setting a custom background colour for chips. The default grey one looks very fugly when the rest of my app is themed. 

## Motivation

Not being able to have full control over my chips' colours is a deal breaker.

**Comment by comontes** [comment]
I was just playing with the Chip component, I was able to change background and font colors, check this: https://snack.expo.io/@cmontesino/chip

**Comment by raajnadar** [comment]
Use this props 

https://callstack.github.io/react-native-paper/chip.html#textStyle
https://callstack.github.io/react-native-paper/chip.html#stylev

[Read docs about chip here](https://callstack.github.io/react-native-paper/chip.html)

**Comment by lionogueira** [comment]
here an example of styling selected / unselected chips

`
const ChipWrapper = (props) => {
    const { chipKey, value, chipPressed, sel } = props;

    const [selected, setSelected] = useState(false);
    const [textColor, setTextColor] = useState(`#FBA200`);
    const [style, setStyle] = useState({ borderColor: `#FBA200`, backgroundColor: `white` });

    useEffect(() => {
        if (selected) {
            setTextColor(`white`);
            setStyle({ borderColor: `#FBA200`, backgroundColor: `#FBA200` });
        } else {
            setTextColor(`#FBA200`);
            setStyle({ borderColor: `#FBA200`, backgroundColor: `transparent` });
        }
    }, [selected]);

    const handlePress = () => {
        setSelected(!selected);
        if (chipPressed) {
            chipPressed(selected);
        }
    };

    return (
        <Chip
            mode="outlined"
            style={style}
            selected={selected}
            selectedColor={textColor}
            onPress={handlePress}>
            {value}
        </Chip>
    );
};
`
