### ISSUE TITLE
Padding="none" not working on TextInput

### ISSUE THREAD

**Issue by harrydema** [callstack/react-native-paper#1158]
## Environment

React native: 0.59.8
React native paper: 2.16.0

## Description

![image](https://user-images.githubusercontent.com/13423169/60271287-74aeba80-98c8-11e9-83f4-3cc4ab7473de.png)

This is the error when I add the padding property on none on the TextInput

## Reproducible Demo
```
<TextInput
      {...props}
      error
      selectionColor="black"
      underlineColor="black"
      type="outlined"
      padding="none"  <------
      theme={{
        colors: {
          primary: 'red',
        },
      }}
      style={{
        backgroundColor: 'transparent',
        width: '100%',
      }}
      onChangeText={text => {
      }}
    />
```

**Comment by questionablequestion** [comment]
Make sure to install `3.0.0-alpha.2` version if you want to use it right now.

**Comment by harrydema** [comment]
You should version the documentation if the documentation is not reflecting the last stable version
