### ISSUE TITLE
Wrong Dialog size

### ISSUE THREAD

**Issue by m-ochyra** [callstack/react-native-paper#1159]
## Environment

React Native Paper version 2.16.0 and 3.0.0-alpha.2.

## Description

Dialog component in horizontal orientation is too wide and on the iPhone X part of the component is hidden under the notch:
<img width="866" alt="Zrzut ekranu 2019-06-27 o 19 28 23" src="https://user-images.githubusercontent.com/5583015/60287699-ced46d80-9912-11e9-828e-ed38aa369a47.png">
![Zrzut ekranu 2019-06-27 o 19 28 36](https://user-images.githubusercontent.com/5583015/60287706-d431b800-9912-11e9-908b-60af698fc8c8.png)

Original Android dialog:
![Zrzut ekranu 2019-06-27 o 19 29 02](https://user-images.githubusercontent.com/5583015/60287726-e27fd400-9912-11e9-82dc-44d6a2d95541.png)

## Reproducible Demo

Example Dialog code.

**Comment by devdebajyotidas** [comment]
Any update on this ?

**Comment by robclouth** [comment]
For now you can set maxWidth and alignSelf on the Dialog:
```
<Dialog style={{ maxWidth: 500, alignSelf: "center" }} />
```

**Comment by sepsol** [comment]
> For now you can set maxWidth and alignSelf on the Dialog:
> 
> ```
> <Dialog style={{ maxWidth: 500, alignSelf: "center" }} />
> ```

This doesn't work anymore. Any new solutions?

**Comment by federicogomezcactus** [comment]
> For now you can set maxWidth and alignSelf on the Dialog:
> 
> ```
> <Dialog style={{ maxWidth: 500, alignSelf: "center" }} />
> ```

This causes the dialog to occupy the entire screen's height if I don't set a maxHeight for the Dialog.Content

**Comment by hakanayaz14159** [comment]
> For now you can set maxWidth and alignSelf on the Dialog:
> 
> ```
> <Dialog style={{ maxWidth: 500, alignSelf: "center" }} />
> ```


Small addition on this answer. It helps to solve height issue.
```javascript
<Dialog style={{ maxWidth: 500, alignSelf: "center" }}>
   {...otherThings}
   <Dialog.Actions style={{flexGrow:0}}>
      <Button>Ok</Button>
   </Dialog.Actions>
</Dialog>
```

**Comment by JakubTiimo** [comment]
> > For now you can set maxWidth and alignSelf on the Dialog:
> > ```
> > <Dialog style={{ maxWidth: 500, alignSelf: "center" }} />
> > ```
> 
> Small addition on this answer. It helps to solve height issue.
> 
> <Dialog style={{ maxWidth: 500, alignSelf: "center" }}>
>    {...otherThings}
>    <Dialog.Actions style={{flexGrow:0}}>
>       <Button>Ok</Button>
>    </Dialog.Actions>
> </Dialog>

Doesn't work. Dialog takes full screen height.

Solution that worked for me
```
const { width } = useWindowDimensions();
const dialogMargin = (width - enterYourMaxWidthHere) / 2;

<Dialog style={dialogMargin > 0 && { marginHorizontal: dialogMargin }}>
```
