### ISSUE TITLE
List.Item: description is not a function (regarding #996)

### ISSUE THREAD

**Issue by HenryQuan** [callstack/react-native-paper#1160]
## Intro
Recently, I updated my [app](https://github.com/HenryQuan/WoWs-Info-Origin) and there were massive amount of crashes due to pull 996. It is mainly my fault but I still want to report it here.

~~~
"react-native": "^0.59.9",
"react-native-paper": "^2.16.0"
~~~

## About #996 
~~~javascript
inside a list...
<List.Item title={item.nickname} onPress={() => this.pushToPlayer(item)} 
    description={item.account_id} key={String(item.account_id)}
    right={() => <IconButton color={Colors.grey500} icon='close' 
    onPress={() => this.removeFriend(item)}/> }/>}
~~~
This was the code I used before. `item.account_id` was an integer but nevertheless, it was fine because description was simply passed to Text like `<Text>{description}</Text>`. 
Currently, it is checking if [description is a string](https://github.com/callstack/react-native-paper/blob/12f3cf109683d365e7c672d7df626b5900ee1e02/src/components/List/ListItem.tsx#L119). I think it might be better to check if description is a `function` instead of a string because people like me might pass an integer in and break everything. However, it is still mainly my fault because I didn't pass a string to it and I haven't seen other having the same issue.

**Comment by brunohkbx** [comment]
@HenryQuan thanks for reporting.
#1199 should solve that :grin:
