### ISSUE TITLE
Text vertical align in Chip 

### ISSUE THREAD

**Issue by si0ls** [callstack/react-native-paper#1162]
## Environment

react-native 0.59.9
react-native-paper 2.16.0

## Description

On some Android devices the text in Chip and SearchBar components is not vertically aligned.

**Nexus S (Android 26)**
![image](https://user-images.githubusercontent.com/6978560/60348761-84112f00-99c0-11e9-955c-aef1a30aaf09.png)

**One Plus 5T (Android 28)**
![image](https://user-images.githubusercontent.com/6978560/60349502-01896f00-99c2-11e9-8b77-a55c336e501f.png)

**Comment by brunohkbx** [comment]
@si0ls could you please provide a [Snack](https://snack.expo.io/) reproducing this issue?

**Comment by wojteg1337** [comment]
@si0ls you could add android version + device name :)

**Comment by jaysbytes** [comment]
inactive, closing
