### ISSUE TITLE
Use context instead of passing props with cloneElement

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#1173]
For components such as `Appbar.Action` etc., we pass some props with `cloneElement`. We should use context so that:

1. Works even if the element is not immediate child
1. Works better with type system
1. Avoids circular dependency in some cases due to no need of checking `child.type`
1. Cleaner, avoids exposing props that should be internal

**Comment by Trancever** [comment]
@satya164 It's not breaking, right? I am thinking if we should implement it before releasing stable 3.0 version or it can wait

**Comment by satya164** [comment]
It's kind of breaking
