### ISSUE TITLE
persian/arabic numbers in Text-like components

### ISSUE THREAD

**Issue by alikazemkhanloo** [callstack/react-native-paper#1177]
## Describe the feature

Add an option to show numbers in Persian/English.
## Motivation
Numbers in Arabic and Persian are (similarly) different from English. So I think it is a good idea to provide an option (probably in theme) to select the format. I wanted to create my own component, But I think it makes more sense to be handled in this library.
Persian numbers: ۰۱۲۳۴۵۶۷۸۹
I can provide a PR if you think it worth it. It is a simple `replace`.

**Comment by alikazemkhanloo** [comment]
I'm waiting for a yes/no 😀

**Comment by Trancever** [comment]
@alikazemkhanloo We think it should be handled by some Internationalization library and not by UI component library.
