### ISSUE TITLE
Button - changing the value of disabled prop messes up with the state of the button

### ISSUE THREAD

**Issue by artus9033** [callstack/react-native-paper#1188]
## Environment

React: 16.8.6
React Native: 0.60.0
react-native-paper: 2.16.0

## Description

There is an issue with the `disabled` prop in the `Button` component: if I pass `true` as its value and then set it back to `false`, the button becomes visually disabled and then enabled again (which is an expected behaviour), but there is no TouchableRipple on its surface anymore - tapping it has no visual effects and it doesn't fire the onPress handler either; the strict bounds of the `Text` component inside the button are still touchable & working though.

I even tried to completely get rid of the `disabled` prop, without even setting it, if its value should be false, by using the spread operator, but with no luck - the wrong behaviour still occurs:
`<Button {...(buttonDisabled ? {} : { disabled: true })} onPress={() => { alert("Pressed!"); }}>Button text</Button>`

**Comment by immortalx** [comment]
This only happens in android for me. Tried with 2.16.0 and also with the latest alpha. 
Same react and react native version, hermes enabled and disabled.

@artus9033 does it happen in iOS as well for you?

**Comment by artus9033** [comment]
Thanks, this solves the problem. When is it planned to be published on NPM?

**Comment by immortalx** [comment]
@pan-pawel 
Inside <KeyboardAvoidingView/> on ios, i need to double click for the button to work. This is expected behavior?
 
Before your PR it wasn't working at all, thank you!
