### ISSUE TITLE
How to make datatable sortable?

### ISSUE THREAD

**Issue by leandrobviana** [callstack/react-native-paper#1189]
Good night,
I am using your DataTable to show data in a react native app in android. But i didn't found any example showing how to make column sortable. I imagine that for sure exists, but I couldn't find how to. Do you have any example? Passing a function or not.

**Comment by Trancever** [comment]
@leandrobviana Just sort the data that you display inside DataTable e.g. if you keep data in state just call setState with sorted data

**Comment by leandrobviana** [comment]
Oh! Sorry about my very poor explanation. I mean, for example, when the user clicks in the header it sort the data accordingly to the column of that header. Do you have any example like that? I some datatables you have this, you just pass the function.
I will edit the question to make it clear.
Thanks! Sorry again.

**Comment by leandrobviana** [comment]
Just found out in: [https://github.com/callstack/react-native-paper/blob/master/example/src/Examples/DataTableExample.tsx](url)

**Comment by Nucolx** [comment]
Hello I'm looking for the same issue. Did you find something ? Thank you

**Comment by aerohh** [comment]
> Hello I'm looking for the same issue. Did you find something ? Thank you

Found any fixes for this ?

**Comment by caiodonat** [comment]
```typescript
const toggleColumnOne = () => {
		if (sortDirectionColumnOne == 'descending') {
			setSortDirectionColumnOne('ascending');
			setData(data.sort(function (a, b) {
				if (a?.client?.name < b?.client?.name) { return -1; }
				if (a?.client?.name > b?.client?.name) { return 1; }
				return 0;
			}));

		} else {
			setSortDirectionColumnOne('descending');
			setData(data.sort(function (a, b) {
				if (a?.client?.name > b?.client?.name) { return -1; }
				if (a?.client?.name < b?.client?.name) { return 1; }
				return 0;
			}));
		}
	}
```

**Comment by somkietacode** [comment]
This should solve your problem: [https://globalanalysissarl.wordpress.com/2024/09/06/how-to-implement-dynamic-column-sorting-in-react-native-datatable/](https://globalanalysissarl.wordpress.com/2024/09/06/how-to-implement-dynamic-column-sorting-in-react-native-datatable/)

`import React, { useState } from 'react';
import { View, StyleSheet } from 'react-native';
import { DataTable, Text } from 'react-native-paper';

interface Person {
  id: number;
  name: string;
  age: number;
  city: string;
}

const SimpleTable: React.FC = () => {
  const [data, setData] = useState<Person[]>([
    { id: 1, name: 'John', age: 25, city: 'New York' },
    { id: 2, name: 'Alice', age: 30, city: 'London' },
    { id: 3, name: 'Bob', age: 22, city: 'Paris' },
  ]);

  const [sortDirection, setSortDirection] = useState<'ascending' | 'descending'>('ascending');
  const [sortedColumn, setSortedColumn] = useState<string>('name');

  const handleSort = (column: keyof Person) => {
    const newSortDirection = sortedColumn === column && sortDirection === 'ascending' ? 'descending' : 'ascending';
    setSortDirection(newSortDirection);
    setSortedColumn(column);

    const sortedData = [...data].sort((a, b) => {
      if (newSortDirection === 'ascending') {
        return a[column] > b[column] ? 1 : -1;
      } else {
        return a[column] < b[column] ? 1 : -1;
      }
    });

    setData(sortedData);
  };

  return (
    <View style={styles.container}>
      <DataTable>
        <DataTable.Header>
          <DataTable.Title
            sortDirection={sortedColumn === 'name' ? sortDirection : undefined}
            onPress={() => handleSort('name')}
          >
            Name
          </DataTable.Title>
          <DataTable.Title
            sortDirection={sortedColumn === 'age' ? sortDirection : undefined}
            onPress={() => handleSort('age')}
          >
            Age
          </DataTable.Title>
          <DataTable.Title
            sortDirection={sortedColumn === 'city' ? sortDirection : undefined}
            onPress={() => handleSort('city')}
          >
            City
          </DataTable.Title>
        </DataTable.Header>

        {data.map((person) => (
          <DataTable.Row key={person.id}>
            <DataTable.Cell>{person.name}</DataTable.Cell>
            <DataTable.Cell>{person.age}</DataTable.Cell>
            <DataTable.Cell>{person.city}</DataTable.Cell>
          </DataTable.Row>
        ))}
      </DataTable>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    paddingTop: 16,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default SimpleTable;
`
