### ISSUE TITLE
Chip does not apply text wrapping properly using textStyle prop

### ISSUE THREAD

**Issue by 0x01Brain** [callstack/react-native-paper#1197]
## Environment

Environment: Android

## Description

The **Chip** component does not wrap long text even when setting styles in **textStyle** prop and **style** prop:

`<Chip textStyle={{ flexWrap: 'wrap' }} style={{  flexDirection: "row" }}>{message.text}aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</Chip>
`

![image](https://user-images.githubusercontent.com/13728193/60900985-31682a80-a27e-11e9-9cc0-1b91d48afe7a.png)

### Expected behavior

When using the following:

```
<View style={{ flexDirection: 'row'}}>
  <Text style={{ flexWrap: 'wrap' }}>{message.text}aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</Text>
</View>
```

**Note**: The **message.text** contains a new line character.

![image](https://user-images.githubusercontent.com/13728193/60901316-c834e700-a27e-11e9-82f3-5c187984e233.png)

**Comment by lukewalczak** [comment]
`Chip` component should be a compact component which contains only the most important information. I think that `multiline` option shouldn't be supported.
