### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop 

### ISSUE THREAD

**Issue by AsafAbrhmoff** [callstack/react-native-paper#1198]
Hi,

I got this warning when i used in List.section and inside him i have list.accordion:

Each child in a list should have a unique "key" prop

What i need to do for fix it?

thanks
Asaf

**Comment by Trancever** [comment]
Provide a [snack](https://snack.expo.io/) that reproduces issue

**Comment by byCedric** [comment]
[Check out this too](https://stackoverflow.com/questions/28329382/understanding-unique-keys-for-array-children-in-react-js/43892905#43892905), this error and solutions are pretty well documented there

**Comment by Taym95** [comment]
This is a known react warning check the official react doc please [lists-and-keys](https://reactjs.org/docs/lists-and-keys.html).

**Comment by temuccio** [comment]
Hi all, I have try to add key pams to Menu.Item, but I have yet this warning.
