### ISSUE TITLE
Preload a WebView into Modal?

### ISSUE THREAD

**Issue by GollyJer** [callstack/react-native-paper#1202]
Hi. I was hoping putting a WebView into a modal would begin loading the webpage while "invisible" and then when the user hits a button to show the modal it would be rendered (or much further along than waiting until they push the button).

[Here's a very simple Expo Snack showing the example](https://snack.expo.io/@gollyjer/modal-webview).
You'll see google.com doesn't begin to load until the Modal is made visible.

Is there a simple way to accomplish what I'm looking this task?

This is for our apps login flow. We use web based Auth0 login and the page has to load when the user pulls it up. I'm hoping to pre-load it to provide a more native feel.

Thanks! 👍

**Comment by lukewalczak** [comment]
Hey @GollyJer 	, in our `Modal` content [won't be rendered](https://github.com/callstack/react-native-paper/blob/master/src/components/Modal.tsx#L177) until the prop `visible` is set to `true`.
