### ISSUE TITLE
BottomNavigation Shifting Ripple Animation Bug

### ISSUE THREAD

**Issue by Moh-Kur** [callstack/react-native-paper#1207]
Hello,
There is a bug in the changing color ripple effect for less than 4 items with shifting enabled.
The center of the ripple is not centered with respect to the click.
You can see it in this example by @Trancever in https://github.com/callstack/react-native-paper/issues/631#issuecomment-434644915_ 

His link: https://snack.expo.io/@trensik/bottom-navigation

I tried it on multiple devices ios and android but the same bug appears.
Thanks

**Comment by MiGi7** [comment]
If you have three items you can change line 699 in BottomNavigation.js from layout.width / 8, to 
layout.width / 3,. This will even out the ripple effect.
