### ISSUE TITLE
Appbar doesn't pass props to Appbar content

### ISSUE THREAD

**Issue by pan-pawel** [callstack/react-native-paper#1215]
## Environment

Latest React Native Paper. Both Android and iOS

## Description

In appbar [render](https://github.com/callstack/react-native-paper/blob/1899651cdc517a6996e228a4cf0d8962ae350f89/src/components/Appbar/Appbar.tsx#L138-L169) we check if child is valid Appbar child like "Appbar Content" and then we passing props to it, otherwise we just returning child as it is.
https://github.com/callstack/react-native-paper/blob/1899651cdc517a6996e228a4cf0d8962ae350f89/src/components/Appbar/Appbar.tsx#L138-L149
I noticed that Appbar Content `child.type.name` is undefined, that's why it always return in line 148 and never passes props to it
https://github.com/callstack/react-native-paper/blob/1899651cdc517a6996e228a4cf0d8962ae350f89/src/components/Appbar/Appbar.tsx#L169

<img width="336" alt="Zrzut ekranu 2019-07-15 o 19 25 16" src="https://user-images.githubusercontent.com/3886886/61241069-0f215180-a743-11e9-95c0-4cd7560ff40b.png">
<img width="366" alt="Zrzut ekranu 2019-07-15 o 19 24 53" src="https://user-images.githubusercontent.com/3886886/61241070-0f215180-a743-11e9-9072-041ebdc47c0e.png">
In those examples appbar Content didnt recieve correct color prop from Apbbar, that's why title has wrong color

Can anyone check if it's my bad or Appbar Content doesn't receive props from Appbar (for example color prop)

**Comment by iyadthayyil** [comment]
This should be fixed by #1174

**Comment by brunohkbx** [comment]
cc @Trancever

**Comment by pan-pawel** [comment]
Ok, it should be fixed by that
