### ISSUE TITLE
Dailog is not visible inside modal

### ISSUE THREAD

**Issue by YajanaRao** [callstack/react-native-paper#1217]
## Description
I have a Dailog inside modal. Dailog is not opening inside modal.
## Reproducible Demo

[Snack](https://snack.expo.io/@yajana/dialog?name=Dialog&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fdialog.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20View%20%7D%20from%20%27react-native%27%3B%0Aimport%20%7B%20Button%2C%20Paragraph%2C%20Dialog%2C%20Portal%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aexport%20default%20class%20MyComponent%20extends%20React.Component%20%7B%0A%20%20state%20%3D%20%7B%0A%20%20%20%20visible%3A%20false%2C%0A%20%20%7D%3B%0A%0A%20%20_showDialog%20%3D%20()%20%3D%3E%20this.setState(%7B%20visible%3A%20true%20%7D)%3B%0A%0A%20%20_hideDialog%20%3D%20()%20%3D%3E%20this.setState(%7B%20visible%3A%20false%20%7D)%3B%0A%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3CView%3E%0A%20%20%20%20%20%20%20%20%3CButton%20onPress%3D%7Bthis._showDialog%7D%3EShow%20Dialog%3C%2FButton%3E%0A%20%20%20%20%20%20%20%20%3CPortal%3E%0A%20%20%20%20%20%20%20%20%20%20%3CDialog%0A%20%20%20%20%20%20%20%20%20%20%20%20%20visible%3D%7Bthis.state.visible%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20onDismiss%3D%7Bthis._hideDialog%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CDialog.Title%3EAlert%3C%2FDialog.Title%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CDialog.Content%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CParagraph%3EThis%20is%20simple%20dialog%3C%2FParagraph%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FDialog.Content%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CDialog.Actions%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%20onPress%3D%7Bthis._hideDialog%7D%3EDone%3C%2FButton%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FDialog.Actions%3E%0A%20%20%20%20%20%20%20%20%20%20%3C%2FDialog%3E%0A%20%20%20%20%20%20%20%20%3C%2FPortal%3E%0A%20%20%20%20%20%20%3C%2FView%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D&dependencies=react-native-paper)

**Comment by lukewalczak** [comment]
Hey @YajanaRao 	, wrap your example within `Provider`, like in the following [example](https://snack.expo.io/@happiryu/dialog)
