### ISSUE TITLE
[RFC] Improvements for internal `Icon` component

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#122]
### Background

Currently we have a [simple icon component](https://github.com/callstack-io/react-native-paper/blob/master/src/components/Icon.js) internally which we use in all our components. Usually those components accept an `icon` prop, which takes the icon name as a parameter.

### Issues with the approach

This approach allows all our components to be able to use icons from the material design library, which mostly works. But when users need to use an icon (a different icon font, an image) which is not available in the material design library, they have to rewrite the component from scratch.

### Proposal

The idea is to make the `icon` prop more versatile, right now it's a `string`

```js
type IconSource =
  | string // it's a material design icon font name
  | ImageSource // it's a object similar to what's passed to Image, { uri ... }, require(...) etc.
  | React.Element<*>
```

The changes will need to be done in the  `Icon` component to allow these. The components using the `Icon` component will need 2 changes, update the type definition of `icon` prop to `IconSource` and update the prop name passed to `Icon`.

This will benefit all the components which support a `icon` prop and they'll be able to render any kind of icon, be it a material design icon, an image or a react element.

Thoughts? Any ideas for improvements to API?

**Comment by ferrannp** [comment]
`Icon` accepts `icon` right now? I thought right now it accepts only `name` ?

**Comment by satya164** [comment]
No, components which use `Icon` accept `icon` prop. `ToolbarAction` for example.

**Comment by ferrannp** [comment]
I see, well API will continue to accept string (material one) so I am totally ok with this proposal.

**Comment by adamTrz** [comment]
So basically, we should be able to call sth like below?
```
const withUri = {uri: 'https://facebook.github.io/react/img/logo_og.png'}
const required = require('./my-icon.png')
const Comp = <Image source={...} />
<Button icon={withUri} > withUri</Button>
<Button icon={required} > required</Button>
<Button icon={Comp} > Comp</Button>
```

**Comment by satya164** [comment]
Yes

**Comment by ferrannp** [comment]
Done.
