### ISSUE TITLE
Elevation on the AppBar.Header

### ISSUE THREAD

**Issue by david-saint** [callstack/react-native-paper#1225]
## Describe the feature

It would be nice if we could set elevation on the AppBar Header component.

## Motivation

Just to add depth ¯\_(ツ)_/¯

**Comment by pan-pawel** [comment]
Hello @david-saint, thanks for the message.
Default elevation
<img width="369" alt="Zrzut ekranu 2019-07-19 o 09 21 08" src="https://user-images.githubusercontent.com/3886886/61517236-124c6400-aa07-11e9-9c38-c0ab135d059d.png">
You need to put elevation in styles, like this:
![Zrzut ekranu 2019-07-19 o 09 23 25](https://user-images.githubusercontent.com/3886886/61518407-b33c1e80-aa09-11e9-9ec8-e39ac30375b5.png)
And it works
<img width="373" alt="Zrzut ekranu 2019-07-19 o 09 22 08" src="https://user-images.githubusercontent.com/3886886/61518425-bfc07700-aa09-11e9-888d-ecde8f6805a3.png">

**Comment by franziz** [comment]
Mine is not working, any idea?
```js
<Appbar.Header theme={{ colors: {primary: "white"} }} style={{ elevation: 24 }}>
    {props.navigation?(
      <Appbar.BackAction onPress={handleBackPress}/>
    ): null}
    <Appbar.Content title={props.title} subtitle={props.subtitle}/>
</Appbar.Header>
```

**Comment by pan-pawel** [comment]
Could you provide more details? package versions, screenshots etc?

**Comment by franziz** [comment]
@pan-pawel sorry a bit late to reply. 
Package Versions: `2.16.0`

I am using `react-native-paper` and `react-navigation`. However, the `navigationOptions` for my `react-navigation` is `{header: null}`

Here is my screenshot
![Screenshot 2019-08-27 at 18 13 49](https://user-images.githubusercontent.com/5362839/63763152-bbd02080-c8f6-11e9-8609-922e94d06e5a.png)

**Comment by david-saint** [comment]
Yeah, I noticed it only does this when the AppBar and the background are of the same color.

**Comment by franziz** [comment]
I take a look at the source code and try to remove from something from `AppbarHeader.js`, and it works. Here something that I remove, is it the correct way?

```js
const styles = StyleSheet.create({
  appbar: {
    elevation: 0,
  },
});
```

**Comment by Ce234** [comment]
Coming from Android(and Staying on Android), new on react, i have found a workaround which worked,

I just wrapped the Appbar.Header into a <Card> with elevation,

By the way Android is by far, Better

**Comment by pan-pawel** [comment]
@franziz I'm not sure if it's a correct way.
You can use `Appbar` without `Appbar.Header` with it's own elevation. So, if we are using `Appbar` inside `Appbar.Header` we need to set `Appbar` elevation by default to 0 and rely on `Appbar.Header` elevation only to avoid  situations like here:
<img width="353" alt="Screenshot 2019-08-31 at 19 13 07" src="https://user-images.githubusercontent.com/3886886/64067207-13d39380-cc25-11e9-958f-c35cece903c5.png">
Where you can notice `Appbar` elevation in the middle of `Appbar.Header` component because its smaller.
I linked my solution for that #1319. But we need to recheck it and merge first so I will keep you informed about it

**Comment by pan-pawel** [comment]
@franziz we merged #1319  to master, so with next release elevation should work for both platforms

**Comment by jkol36** [comment]
this doesn't work for me. Any idea why?
<img width="454" alt="Screen Shot 2020-02-21 at 1 10 54 PM" src="https://user-images.githubusercontent.com/2565155/75059791-ac97ed00-54ab-11ea-9aa4-650592bde24d.png">

**Comment by lewibs** [comment]
also doesnt seem to work for me
