### ISSUE TITLE
Radio/Checkbox larger sizes

### ISSUE THREAD

**Issue by evantrimboli** [callstack/react-native-paper#1229]
## Describe the feature

Expose a size config (or another hook) to be able to increase the size of a checkbox/radio.

## Motivation

In some scenarios it would be good to make these options more prominent. It also seems as though there isn't any technical impediment, the sizes just seem to be hard coded.

**Comment by potier97** [comment]
El problema continua, aún no se deja modificar el tamaño, algo como size={32}, aún no esta en la API

**Comment by lt35** [comment]
Me tooo. Please update the size of a checkbox/radio.
