### ISSUE TITLE
Getting Started documentation link broken

### ISSUE THREAD

**Issue by Akshay-Katariya** [callstack/react-native-paper#1232]
The Getting Started guide page is unable to load properly, I think It's without any CSS or styling applied to it.

When I navigate to any inner specific component page it shows 404 error.

[Getting Started guide][1] I followed.

[![Home Page without CSS and styling][2]][2]

[![Detail Page with 404 error][3]][3]

  [1]: https://callstack.github.io/react-native-paper/getting-started.html
  [2]: https://i.stack.imgur.com/3VryA.png
  [3]: https://i.stack.imgur.com/hJuCz.png

**Comment by Nemferno** [comment]
I looked over the debugger and it's missing `https://callstack.github.io/react-native-paper/app.bundle.js`. There is an app.bundle.js in the 1.0 folder in gh-pages branch, so I'm guessing this is a faulty path that can easily be fixed.

**Comment by mehmetnyarar** [comment]
I'm trying to run the docs from the source code. I installed dependencies and run `yarn start`.

First, it gave me the following error:

> Cannot find module 'react-native-vector-icons/glyphmaps/MaterialIcons.json'

I installed `react-native-vector-icons` via yarn.

Then:

> TypeError: (0 , _color.default)(...).isLight is not a function
    at isLight (/<root_dir>/react-native-paper/docs/pages/src/Showcase.js:59:49)

Maybe it's a different issue I'm not sure..

**Comment by Nemferno** [comment]
I checked the commit history and looks there was a huge deletion of files in commit https://github.com/callstack/react-native-paper/commit/a1448518a91ee2701a5ec0856f72b70ee61f1d40. Not sure if this is intentional or it was a mistake.

**Comment by Nemferno** [comment]
I got it to work on my end. I made a little mistake on not including a commit before the big change so will do that. Use "nemferno.github.com/react-native-paper" in the mean time while I try to pull request.

**Comment by Nemferno** [comment]
Checked back, looks like they resolved it 👍

**Comment by Akshay-Katariya** [comment]
> Checked back, looks like they resolved it 👍

Thanks, working fine now 👍 Cheers
