### ISSUE TITLE
RN 0.60.4 White Screen

### ISSUE THREAD

**Issue by jack828** [callstack/react-native-paper#1235]
## Environment

RN 0.60.4
Android P - OnePlus 7 Pro

## Description

App only shows a white screen when using RN >= 0.60.

## Reproducible Demo

```
$ react-native init Project --version react-native@0.60.4
```

Follow the [Getting Started](https://callstack.github.io/react-native-paper/1.0/getting-started.html) instructions:

```
$ yarn add react-native-paper react-native-vector-icons
```
Note no react-native link!

Edit the `App.js` to include PaperProvider around `App`, exactly as the Usage example

Setup android app - `react-native run-android`
Init bundler - `react-native start`

App screen is just white!

If I now run `react-native link react-native-vector-icons`, when trying to use any component from `react-native-paper`, I just get the `Invariant Violation: Element type is invalid...` error.

Any ideas how to debug this? More than happy to produce a PR to support 0.60.

EDIT:
okok more specifically I'm bunging this into the default view:
```jsx
import {
  Button,
  Card,
  CardActions,
  CardContent,
  CardCover,
  Title,
  Paragraph
} from 'react-native-paper';

const MyComponent = () => (
  <Card>
    <CardContent>
      <Title>Card title</Title>
      <Paragraph>Card content</Paragraph>
    </CardContent>
    <CardCover source={{ uri: 'https://picsum.photos/700' }} />
    <CardActions>
      <Button>Cancel</Button>
      <Button>Ok</Button>
    </CardActions>
  </Card>
);
```

If I reduce this to 
```jsx
<Title>Card title</Title>
```
It renders fine - meaning the library is loading just fine, which is good.
So trying to remove each component at once, this works:

```jsx
const MyComponent = () => (
  <Card>
    <Fragment>
      <Title>Card title</Title>
      <Paragraph>Card content</Paragraph>
    </Fragment>
    <Fragment>
      <Button>Cancel</Button>
      <Button>Ok</Button>
    </Fragment>
  </Card>
);
```

Looks like `CardActions`, `CardContent`, and `CardCover` do not work.

EDIT 2:

Looking into `node_modules/react-native-paper/src/index.js` for the source of each module...the above ones aren't `export`'d!

EDIT 3:

Figured it out! The components `CardActions`, `CardContent`, and `CardCover` should be used as `Card.Actions`, `Card.Content`, and `Card.Cover`! The documentation needs updating :)

**Comment by satya164** [comment]
Please follow the guide for latest version, not 1.0

https://callstack.github.io/react-native-paper/getting-started.html
