### ISSUE TITLE
List.Accordion and List.Item title wrap

### ISSUE THREAD

**Issue by odesey** [callstack/react-native-paper#1242]
## Ask your Question
Is it possible to have the text used in the `title` prop to be wrapped when it is too long to fit on one line?

Right now the text is ending with the 3 dots ellipsis `some super duper ultra too long to fit on one...`

I've tried:

```javascript
<List.Item title={<Text> "My super long text in here"</Text>} />
```
That also does not work. Also tried the `numberOfLines` prop as well as other suggestions found here:
https://github.com/facebook/react-native/issues/1438

Nothing seems to work.

Thanks in advance and thanks for the great package!

**Comment by deeuu** [comment]
I'm pretty sure that this is due to the number of lines being [limited to 1](https://github.com/callstack/react-native-paper/blob/master/src/components/List/ListItem.tsx#L183).

I'd prefer for this to be an optional property.

Note also that the description text is [limited to 2 lines](https://github.com/callstack/react-native-paper/blob/master/src/components/List/ListItem.tsx#L127)

**Comment by deeuu** [comment]
Just to confirm that this is the case.
Personally I don't see the reason for a default line limit.
Thoughts on making this an optional prop (or just support a full blown `titleProps`)?

**Comment by odesey** [comment]
Thanks for pointing this out @deeuu , I am definitely in favor of making this a prop and simply defaulting to 1 line if it's not set.

However, shouldn't this not be an issue if I pass the `title` or `description` as a React Node like `<Text> Some text </Text>`, then the props I set should take precedence?
```javascript
<List.Item title={<Text numberOfLines={4}> "My super long text in here"</Text>} />
```

Thanks.

**Comment by deeuu** [comment]
Hey,

> shouldn't this not be an issue if I pass the `title` or `description` as a React Node

No because the given `title` is wrapped by [`<Text numberOfLines={1}>`](https://github.com/callstack/react-native-paper/blob/master/src/components/List/ListItem.tsx#L186)

**Comment by odesey** [comment]
Thanks for the explanation @deeuu, I will close this issue for now.

**Comment by deeuu** [comment]
@odesey Note the pull-request #1245 I've made which adds a `numberOfLines` prop for the title and description text.
