### ISSUE TITLE
Babel plugin git access permission denied

### ISSUE THREAD

**Issue by TriangularCube** [callstack/react-native-paper#1243]
I just tried to install the babel plugin, and I'm getting the following error:

Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/react-native-paper/babel.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

Is there something I'm missing or did the public key change at some point?

**Comment by jaysbytes** [comment]
the plugin is a part of a library.
