### ISSUE TITLE
Change minimized label size on TextInputOutlined

### ISSUE THREAD

**Issue by Gabogg07** [callstack/react-native-paper#1247]
## Ask your Question

I'm looking forward to change the minimized label fontsize without needing to change the source code for the component.
I realized it can be made by changing the const MINIMIZED_LABEL_FONT_SIZE on TextInputOutlined, but no way to make it through props or theme

**Comment by jbinda** [comment]
Hi @Gabogg07 

Currently there is no way to change label text size or style. You are not the first person asking about that and I would like to raise the topic on internal discussion in recent future.
