### ISSUE TITLE
RNW - TextInput with wrong label placement

### ISSUE THREAD

**Issue by brunohkbx** [callstack/react-native-paper#1248]
## Environment
"expo": "^33.0.0"
"react": "16.8.3"
"react-dom": "^16.8.6"
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz"
"react-native-web": "^0.11.4"

## Description
RNW renders TextInput with a wrong label position. TextInput container shouldn't be visible underneath its label.

![Screenshot from 2019-07-25 15-12-54](https://user-images.githubusercontent.com/6487206/61898225-37e9d980-aeef-11e9-84d3-603d3c4bc4b5.png)

Material-ui TextInput example:
![Screenshot from 2019-07-25 15-19-57](https://user-images.githubusercontent.com/6487206/61898468-c1011080-aeef-11e9-9889-d6897d141b19.png)

**Comment by brunohkbx** [comment]
cc @jbinda

**Comment by jbinda** [comment]
Hi 

Thanks for raised an issue on that. It should be fixed with label rafactor I recently did. Checkout this PR: #1241

**Comment by jbinda** [comment]
fixed with #1241

**Comment by brunohkbx** [comment]
@jbinda its working fine on android/ios but the input's border is still visible underneath the label on web.

**Comment by jbinda** [comment]
Ok I will double check that
