### ISSUE TITLE
Use react-router-native `<Link />` in `<Button />`

### ISSUE THREAD

**Issue by wolverineks** [callstack/react-native-paper#1251]
## Ask your Question

It looks like react-native-paper `<Button />` wraps its children in a `<Text />`, which prevents the following. 
```js
<Button>
  <Link>
    <Text>Next</Text>
  </Link>
</Button
```
Error: `Invariant Violation: Nesting of <View> within <Text> is not currently supported.`

Other Libraries provide a prop to replace the `<Text>{children}</Text>` component, as well as passing along unused props, for cases like this. Something like 

```js
<Button title={"Next"} InnerComponent={Link} to={"/some/navigation/path/"} />
```

Is there something similar for this library?

**Comment by ArnaudBan** [comment]
I don't know if it work but in React native but in React it is the other way works

```jsx
<Link>
  <Button>
    <Text>Next</Text>
  </Button>
</Link>
```

**Comment by wolverineks** [comment]
As it turns out, React Router has this built in 
https://reacttraining.com/react-router/native/api/Link/component-func

**Comment by shristov-iMeniu** [comment]
Hi, did you find any solution of the issue?
