### ISSUE TITLE
UnhandledPromiseRejectionWarning: E:\project\project_name\node_modules\snapdragon-util\index.js:282

### ISSUE THREAD

**Issue by KiranreddySrDev** [callstack/react-native-paper#1252]
I am getting this issues in an android emulator while running react-android.
I have checked with npm ls snapdragon-util then it was shown paper dependency is snapdragon-utile 

error below like this

 DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit .

is it react-native project issue or package-issue?

**Comment by jaysbytes** [comment]
Paper does not have such a dependency, on third-party paper's dependencies is supposed to have `snapdragon-util`. It's probably your project issue or third party package issue.
