### ISSUE TITLE
When can we expect new release

### ISSUE THREAD

**Issue by netbull** [callstack/react-native-paper#1255]
## Release roadmap

Hello guys! 

First of all great work, this package is quite awesome. My question is when can we expect a new release? Currently the pre-release **alpha2** have big difference with the master and many bugs are cleared so far, but there is no release yet..

**Comment by ferrannp** [comment]
We want to release 3.0 this week. Please re-open if this does not happen :)

**Comment by marcorm** [comment]
any updates?
