### ISSUE TITLE
Error while wrapping paper component in separate functional component: Element type is invalid: expected a string 

### ISSUE THREAD

**Issue by Akshay-Katariya** [callstack/react-native-paper#1256]
I want to customize the FAB component so I created a wrapper as below

```
import React from "react";
import { StyleSheet } from "react-native";
import FAB from 'react-native-paper'

const MyFab = (props) => (
    <FAB
        style={styles.fab}
        icon="add"
        color='white'
        onPress={() => this.props.navigation.navigate('AddDeviceScreen')}
    />
)
export default MyFab;

const styles = StyleSheet.create({
    fab: {
        backgroundColor: '#48B3FF',
        position: 'absolute',
        margin: 16,
        right: 0,
        bottom: 0,
    }
});
```

And imported in my main page using 

`import MyFab from '../components/MyFab'`

and used as below 

`{this.state.shouldShow ? <MyFab /> : null}`

[![Actual Error ScreenShot][1]][1]

> I am using the following versions:-
> "react": "16.8.6",
> "react-native": "0.60.4",
> "react-native-paper": "^2.16.0",

  [1]: https://i.stack.imgur.com/tdA8Q.jpg

**Comment by ferrannp** [comment]
Should be: `import { FAB } from 'react-native-paper'.
