### ISSUE TITLE
FAB not responding if at least once disabled [working with RN 0.59.8 but not with 0.60.4]

### ISSUE THREAD

**Issue by devsrv** [callstack/react-native-paper#1259]
If problematically set `disabled` prop to false then afterwords the FAB never responds with `disabled={true}`. FAB is greyed out properly according to whether disabled or not but completely freezes if once disabled.

**TRIED WITH MULTIPLE PROJECTS USING RN 0.60.4 - GOT SAME RESULTS**

Here is my code:-

```
import React, {Component} from 'react';
import {
    StyleSheet,
    View,
    Text,
    Button,
    Alert
} from 'react-native';

import { FAB } from 'react-native-paper';

export default class FabComponent extends Component {
    state = {
        disableFab: false
    }

    handleFabPress = () => {
        Alert.alert(
            'Alert Title',
            'You pressed the floating button',
            [
              {
                text: 'Cancel',
                onPress: () => console.log('Cancel Pressed'),
                style: 'cancel',
              },
              {text: 'OK', onPress: () => console.log('OK Pressed')},
            ],
            {cancelable: false},
          );
    }

    render() {
        return (
            <View style={styles.container}>
                <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
                    <Button
                        onPress={() => {
                                this.setState((prevState) => {
                                    return {
                                        disableFab: ! prevState.disableFab
                                    }
                                })
                            }
                        }
                        title={this.state.disableFab? 'Enable FAB' : 'Disable FAB'}
                        color="#488c51"
                    />
                </View>

                <FAB
                    style={styles.fab}
                    small={false}
                    icon="add"
                    disabled={this.state.disableFab}
                    onPress={this.handleFabPress}
                />
            </View>
        )
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    fab: {
        position: 'absolute',
        margin: 16,
        right: 0,
        bottom: 0,
      },
  });
  
```

the repo is here - https://github.com/devsrv/rnpaper-fab

**Comment by Trancever** [comment]
It must be something with accessibility. @pan-pawel Can you check it?

**Comment by mahdinabi** [comment]
normal Button component acts like this as well.

**Comment by pan-pawel** [comment]
Hello @devsrv!
Can you please try upgrade react-native-paper to 3.0.0-alpha.3? 
My fix [touchable-ripple-toggling-disable-prop ](https://github.com/callstack/react-native-paper/commit/16e3569) was merged there

**Comment by devsrv** [comment]
the problem is fixed in 3.0.0-alpha.3 however getting a prop error warning & the icon is not appearing on the FAB.


![Untitled](https://user-images.githubusercontent.com/26733312/62832916-a8b12580-bc53-11e9-8e37-2326d0b5b40d.png)

![image](https://user-images.githubusercontent.com/26733312/62832932-283ef480-bc54-11e9-87c6-6f889e538b76.png)

**Comment by pan-pawel** [comment]
@Trancever This is related to icon problems in paper 3?

**Comment by Trancever** [comment]
@devsrv Paper v3 uses `react-native-vector-icons/Material-Community-Icons` instead of `react-native-vector-icons/Material-Icons` by default so you need to update name of the icon or use old Icon component via settings prop on PaperProvider. You can see how to do it [here](https://github.com/callstack/react-native-paper/blob/2bb643652d5192d93de85f22ea1d652d2dd6b48d/example/src/index.native.tsx#L122)

**Comment by devsrv** [comment]
fixed 🥳
