### ISSUE TITLE
Icons error in current 3.0-alpha.3

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#1261]
Probably after merging https://github.com/callstack/react-native-paper/pull/1210.

```
transform[stderr]: Could not resolve "@expo/vector-icons/MaterialCommunityIcons" in file /Users/ferrannp/Development/Callstack/OSS/react-native-paper/src/components/MaterialCommunityIcon.tsx.
```

We get:

![Simulator Screen Shot - iPhone X - 2019-08-01 at 12 23 22](https://user-images.githubusercontent.com/774577/62286034-29ec0980-b457-11e9-9186-0fe5b5618d5a.png)

**Comment by ferrannp** [comment]
03e484abadf80638b4953650f9f12c9f59abcbdd.

**Comment by fgagneten** [comment]
I'm having the same error using alpha.3. It is not depend on the icon name. Using alpha.2 works like a charm
