### ISSUE TITLE
To close an expanded accordion on opening another accordion

### ISSUE THREAD

**Issue by akhilsanker** [callstack/react-native-paper#1262]
## Describe the feature

If an accordion is expanded and trying to open another, automatically close the expanded one. 

## Motivation

Usually this feature is seen in every accordion

**Comment by jaysbytes** [comment]
We could create AccordionGroup component that would map its children.

**Comment by jaysbytes** [comment]
I'm working on implementation right now.

**Comment by akhilsanker** [comment]
Hi @iyadthayyil ,

Is it woking in version 3.0.0?

**Comment by Trancever** [comment]
@akhilsanker Yes, AccordionGroup is available in 3.0.0
