### ISSUE TITLE
BottomNavigation transitions have rendering issues when there are shadows in the views

### ISSUE THREAD

**Issue by lfrodrigues** [callstack/react-native-paper#1263]
## Environment

- Latest version of react-native-paper
- RN 0.59.9
- Android 8 and 9

## Description
When we have shadows the transition keeps them visible until the transition finishes.

See recording here: https://drive.google.com/open?id=1ZioLEHFcnkRu28aMHEedCzZ-_CGQnX_Y

**Comment by aniss** [comment]
I confirm that.

**Comment by satya164** [comment]
It's a bug in React Native https://github.com/facebook/react-native/issues/23090

**Comment by lfrodrigues** [comment]
Is it possible to disable or replace the animation?
