### ISSUE TITLE
While running in iOS device, the List.Accordion List indicator is coming with different icons(not up and down arrow). Please check into it.

### ISSUE THREAD

**Issue by AmitPandya007** [callstack/react-native-paper#1266]
## Environment

iOS device testing

## Description

While running project with the library, the List item indicators are coming with some different icons(scissor and disk icon) which has to be (up arrow and down arrow icons).
Please look into it and reply.

    "react": "16.6.3",
    "react-native-paper": "2.16.0",
    "react-native": "0.59.0",

**Comment by jaysbytes** [comment]
Can you attach any screenshot or code to debug (preferably on https://snack.expo.io)

**Comment by Trancever** [comment]
@AmitPandya007 I am closing this because of no repro. We use the icons that are recommended by MD Guidelines.
