### ISSUE TITLE
How to use vector icon in Banner

### ISSUE THREAD

**Issue by fgagneten** [callstack/react-native-paper#1267]
## Ask your Question

I want to implement a Banner Component. This is how I wrote the component (Same as the doc): 

    <Banner
        visible={this.state.visible}
        actions={[
          {
            label: 'Fix it',
            onPress: () => this.setState({ visible: false }),
          },
          {
            label: 'Learn more',
            onPress: () => this.setState({ visible: false }),
          },
        ]}
        image={({ size }) =>
          <Image
            source={{ uri: 'https://avatars3.githubusercontent.com/u/17571969?s=400&v=4' }}
            style={{
              width: size,
              height: size,
            }}
          />
        }
      >
        There was a problem processing a transaction on your credit card.
      </Banner>

How can I replace local or remote image by a vector icon? Instead of 

    image= 
    ...

Something like:

    icon="sentiment-dissatisfied

Thanks

**Comment by Trancever** [comment]
@fgagneten You can do it like that right now: 
```
import Icon from 'react-native-vector-icons/Material-Community-Icons'; // or any other Icon

image={(...props) => <Icon {...props} />}
```
Unfortunately, there is no way to pass only name of the icon right now, we will think about fixing it.
