### ISSUE TITLE
Buttons inside Modal isn't clickable. (Android)

### ISSUE THREAD

**Issue by joshualimpj** [callstack/react-native-paper#1268]
TouchableOpacity rendered inside the Modal isn't clickable. Clicking anywhere on the modal just flashes it.

**Comment by jaysbytes** [comment]
Can you provide a reproducible demo, preferably on https://snack.expo.io ?

**Comment by kaloraat** [comment]
ya same issue, I have created a modal with TextInput which works fine. 
Then I have a button under that TextInput which is not clickable at all :(

**Comment by pankajgupta1** [comment]
II removed flex: 1  from immediate child, and that solved my problem
