### ISSUE TITLE
Icon doesn't work with web and expo

### ISSUE THREAD

**Issue by zRelux** [callstack/react-native-paper#1271]
## Environment

Expo SDK 34

## Description

I started using the web module everything works great but is seems like the icon can't load properly.
I get this error in the console from the webpack loader
```
WARNING in ./node_modules/react-native-paper/src/components/Icon.js
Module not found: Error: Can't resolve 'react-native-vector-icons/MaterialIcons' in '/Users/dricil/Documents/Personal/salavideo_app/node_modules/react-native-paper/src/components'
 @ ./node_modules/react-native-paper/src/components/Icon.js
 @ ./node_modules/react-native-paper/src/components/BottomNavigation.js
 @ ./node_modules/react-native-paper/src/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
```
I added the source with style like this: 
```
<style type="text/css">{`
        @font-face {
          @expo/vector-icons/src/vendor/react-native-vector-icons/Fonts/MaterialIcons.ttf
          font-family: 'MaterialIcons';
          src: url(${require('@expo/vector-icons/website/src/fonts/MaterialIcons.ttf')}) format('truetype');
        }
      `}</style>
```
I tried to change the source to `@expo/vector-icons/website/src/fonts/MaterialIcons.ttf` but it doesn't seem to load the icons. Is there anything i can do to make it work?

**Comment by jaysbytes** [comment]
Did you install the `react-native-vector-icons` package? It seems to be mandatory on the web.

**Comment by zRelux** [comment]
I'm using expo, do I still have to?

**Comment by jaysbytes** [comment]
I'm not 100% sure but try to exclude `react-native-vector-icons` similar as we have in our example app https://github.com/callstack/react-native-paper/blob/2.0/example/webpack.config.js.

Our example also has `"@expo/vector-icons": "^8.0.0",` dependency https://github.com/callstack/react-native-paper/blob/2.0/example/package.json

**Comment by antgel** [comment]
@zRelux Did you get anywhere with this?

**Comment by zRelux** [comment]
No not really, but I think we can close this and we can open it back again if this comes ups again
