### ISSUE TITLE
Button bold content

### ISSUE THREAD

**Issue by ckristhoff** [callstack/react-native-paper#1273]
## Ask your Question
Hi everyone,
How can I set text bold for buttons?

**Comment by jaysbytes** [comment]
Currently, it's not possible. There should be a prop `textStyle`

**Comment by pan-pawel** [comment]
@ckristhoff I added PR with labelStyle for button. I will notify you if we add it to paper

**Comment by pan-pawel** [comment]
@ckristhoff  we added labelStyle to master, so with next release you will be able to set custom font for button

**Comment by mschipperheyn** [comment]
Could you release this on the 2.x branch?
