### ISSUE TITLE
Add ability to change padding between fab group children

### ISSUE THREAD

**Issue by soumyamishra89** [callstack/react-native-paper#1274]
## Describe the feature

The fabs in fab group have a fixed gap (vertical) between them. In some cases it looks too much gap between the children. 
Add styling option to customise the gap between the children fabs of fab group

**Comment by jaysbytes** [comment]
I didn't find any specs about spacing size so PR welcome 😀

**Comment by elizamaria** [comment]
> I didn't find any specs about spacing size so PR welcome 😀

Would it be fine to send an itemStyle?
