### ISSUE TITLE
Can I access .PropTypes from a component rendered from the withTheme HOC

### ISSUE THREAD

**Issue by zRelux** [callstack/react-native-paper#1275]
## Ask your Question
So basically I created a table component is able to render the props need for the component based on the `.PropTypes` object
Example
```
import Component from '.';
import Table from './Table';

...

<Table component={Component}/>

...
```

Inside the table I'm able to log the propTypes like this `console.log(props.component.PropTypes);`

But if `Component` gets exported with the `withTheme` HOC `.PropTypes` is no more accessible.

Now what I am wondering is if there is a way to access `.PropTypes` from the `withTheme` rendered component.

**Comment by zRelux** [comment]
Any update?

**Comment by Trancever** [comment]
@zRelux Can you create a Snack with your component? I am not sure if I understand your problem.

**Comment by zRelux** [comment]
Here is the snack: https://snack.expo.io/HJY6TRvNH
In line 10 in App.js i want to be able to log the props that the components needs.

**Comment by satya164** [comment]
Please don't rely on such pattern. `propTypes` are internal details of a component. If you really need to access it, export them separately.
