### ISSUE TITLE
ChangeLog / Breaking Changes for v3 Migration?

### ISSUE THREAD

**Issue by creambyemute** [callstack/react-native-paper#1276]
## Describe the feature
A ChangeLog / Breaking Changes section for the V2 --> V3 migration.

## Motivation
I just wanted to quickly try out v3.0.0-alpha.3 and ran into problems with not rendering react-native-vector-icons (rendered as ?).

## Related Issues
Probably related to switching from `MaterialIcons` to `MaterialCommunityIcons`

**Comment by lironsher** [comment]
Thanks, your tip saved my night.

**Comment by GollyJer** [comment]
Yeah... go here to replace your icon props.
https://materialdesignicons.com/

**Comment by jaysbytes** [comment]
We will work internally on detailed changelog.

**Comment by jaysbytes** [comment]
Changelog, all done until alpha 4 release. Still WIP
https://github.com/callstack/react-native-paper/wiki/Migration-guide-from-2.0-to-3.0
