### ISSUE TITLE
FAB does not inherit theme?

### ISSUE THREAD

**Issue by DianaKoenraadt** [callstack/react-native-paper#1278]
## Environment

    {
      "main": "node_modules/expo/AppEntry.js",
      "scripts": {
        "start": "expo start",
        "android": "expo start --android",
        "ios": "expo start --ios",
        "eject": "expo eject",
        "test": "node ./node_modules/jest/bin/jest.js --watchAll"
      },
      "jest": {
        "preset": "jest-expo"
      },
      "dependencies": {
        "@expo/samples": "2.1.1",
        "@redux-offline/redux-offline": "^2.5.2",
        "babel-plugin-inline-dotenv": "^1.3.3",
        "dotenv": "^8.0.0",
        "expo": "^32.0.0",
        "moment": "^2.24.0",
        "react": "16.5.0",
        "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
        "react-native-masked-text": "^1.12.4",
        "react-native-paper": "^2.16.0",
        "react-native-swipeable-row": "^0.8.1",
        "react-navigation": "^3.11.1",
        "react-redux": "^6.0.1",
        "redux": "^4.0.4",
        "redux-persist": "^5.10.0",
        "redux-saga": "^1.0.5",
        "uuid": "^3.3.2"
      },
      "devDependencies": {
        "babel-preset-expo": "^5.2.0",
        "jest-expo": "^32.0.1"
      },
      "private": true
    }

## Description

I have made a theme, ThemeRed. If I apply this theme to the topmost view, FAB does not inherit it.

## Reproducible Demo

I've made a snack that illustrates the issue.
https://snack.expo.io/HyVI1W2Qr
(Edit: updated snack with PaperProvider)

Is this expected behavior? Am I doing something that prevents the theme from being inherited?

**Comment by Trancever** [comment]
Pass theme to Provider and it's gonna work.
