### ISSUE TITLE
Animating dialog action buttons causes invisible buttons on iOS

### ISSUE THREAD

**Issue by schellack** [callstack/react-native-paper#1282]
## Environment

iOS only: reproduced in Snack on iOS simulator (link below) and on physical iPhone Xs Max running iOS 12.4 in the Expo app.

## Description

When using a [Dialog](https://callstack.github.io/react-native-paper/dialog.html), I hide the [Dialog.Actions](https://callstack.github.io/react-native-paper/dialog-actions.html) until the user has completed some task inside the dialog. Once that task is complete, I update state and show the Dialog.Actions, which contains a single [Button](https://callstack.github.io/react-native-paper/button.html) that can close the Dialog.

In order to not make the action button appear suddenly and jump out at the user, I animate it using React Native's Animated functionality.

Many times, on iOS only (as far as I can reproduce), the button inside of the Dialog.Actions is invisible. It is still there (if you tap around enough you can find it), but you cannot see it, and the user certainly would not know it is there.

This only occurs if I use the React Native Paper Button. This does not occur if I use the React Native Button.

Here is what it looks like (the purple spot in the bottom-right corner is where the button should be; I have tapped on it to make it visible for the screenshot):
![image](https://user-images.githubusercontent.com/70819/62842922-90ed9780-bc7b-11e9-921e-b14c32947a9f.png)

## Reproducible Demo
Here is a snack where you will see the issue occur, if you run it on iOS:
https://snack.expo.io/@salus/dialog-with-animated-action-button

Note that the issue is intermittent; it will not occur every single time. I do find that it seems to happen more often than not, however.

**Comment by schellack** [comment]
I upgraded to react-native-paper 3.3.0 and the issue persists.

Upgraded snack demo link: https://snack.expo.io/Bk9aum-CS

**Comment by Trancever** [comment]
@schellack Thanks for updated Snack. We will try to look into this as soon as possible.
