### ISSUE TITLE
yarn add git repo

### ISSUE THREAD

**Issue by burlapdesign** [callstack/react-native-paper#1283]
## Ask your Question

Not sure if this is right place. We're trying to use this as the start for building a component library for our internal use. I was trying to add it to a project as a test using "yarn add git https://thisrepo.git  and I get the following errors. This doesn't happen if I use yarn add [package]

Errors found when building definition files.
example/src/index.native.tsx(1,25): error TS2307: Cannot find module 'expo'.
example/src/index.native.tsx(2,30): error TS2307: Cannot find module 'expo-keep-awake'.
example/src/index.native.tsx(17,39): error TS2307: Cannot find module 'react-navigation'.
example/src/RootNavigator.native.tsx(2,38): error TS2307: Cannot find module 'react-navigation'.

bob build

build files for publishing

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Error: Failed to build definition files.
    at build (/.../Yarn/v4/.tmp/54fd92deebdcf55a1eec6522e44f98ae.2e7c88a9d16ee7d786a9e176eb5c476dcc49a914.prepare/node_modules/@react-native-community/bob/lib/targets/typescript.js:63:11)
    at async Object.handler (/.../Yarn/v4/.tmp/54fd92deebdcf55a1eec6522e44f98ae.2e7c88a9d16ee7d786a9e176eb5c476dcc49a914.prepare/node_modules/@react-native-community/bob/lib/cli.js:287:9)
error Command failed with exit code 1.

**Comment by jaulz** [comment]
https://github.com/callstack/react-native-paper/pull/1203

**Comment by burlapdesign** [comment]
Thanks. That was what helped.
