### ISSUE TITLE
[TextInput] Wrong placeholder opacity during init pharse

### ISSUE THREAD

**Issue by giautm** [callstack/react-native-paper#1286]
## Environment

https://github.com/callstack/react-native-paper/blob/2bb643652d5192d93de85f22ea1d652d2dd6b48d/src/components/TextInput/Label/InputLabel.tsx#L79-L85

## Description

The placeholder move from bottom to top during calculate label height, I believe this condition was wrong. It should be:

```javascript
          opacity:
            // Hide the label in minimized state until we measure it's width
            parentState.labelLayout.measured
            ? 1
            : 0,
```

## Reproducible Demo

Just set TextInput with custom height.

**Comment by jaysbytes** [comment]
cc @jbinda
