### ISSUE TITLE
How to betatest version 3?

### ISSUE THREAD

**Issue by msageryd** [callstack/react-native-paper#1289]
As I'm right now evaluating RNP for my project I might as well try to help out with beta/alpha-testing of v3. Is there any guidelines on how to install v3?

I tried to `yarn add https://github.com/callstack/react-native-paper.git` and got the following error:

```
✖ Errors found when building definition files.
example/src/index.native.tsx(1,25): error TS2307: Cannot find module 'expo'.
example/src/index.native.tsx(2,30): error TS2307: Cannot find module 'expo-keep-awake'.
example/src/index.native.tsx(18,39): error TS2307: Cannot find module 'react-navigation'.
example/src/RootNavigator.native.tsx(2,38): error TS2307: Cannot find module 'react-navigation'.
```

**Comment by RichardLindhout** [comment]
```yarn add react-native-paper@3.0.0-alpha.3```

**Comment by RichardLindhout** [comment]
I think that is only on master. If you want to have master fork it en change some values like this
https://github.com/profects/react-native-paper/commit/c9f787b8eaed02da9e9ce0519306be31f84c0fa7
https://github.com/profects/react-native-paper/commit/ea3efc2963a252ae86d1e4d64774313bf1c73467

**Comment by msageryd** [comment]
Thanks @RichardLindhout!
It worked great.
