### ISSUE TITLE
ToggleButton.Row not working

### ISSUE THREAD

**Issue by msageryd** [callstack/react-native-paper#1290]
## Environment

Expo SDK 34
RNP 2.16.0

## Description

I'm not sure if ToggleButton.Row should work in 2.16, but it's in the docs so I think it's supposed to work.

It spits out Invariant Violation, both in my local test app and in the Snack linked from the [docs page](https://callstack.github.io/react-native-paper/toggle-button-row.html) 

## Reproducible Demo

- Copy/Paste the example from the [docs](https://callstack.github.io/react-native-paper/toggle-button-row.html)  into your app.

- Or just try to run the Snack demo: [Snack demo from RNP docs](https://snack.expo.io/?name=ToggleButton.Row&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Ftoggle-button-row.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20View%20%7D%20from%20%27react-native%27%3B%0Aimport%20%7B%20ToggleButton%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aexport%20default%20class%20MyComponent%20extends%20React.Component%20%7B%0A%20%20state%20%3D%20%7B%0A%20%20%20%20value%3A%20%27left%27%2C%0A%20%20%7D%3B%0A%0A%20%20render()%20%7B%0A%20%20%20%20return(%0A%20%20%20%20%20%20%3CToggleButton.Row%0A%20%20%20%20%20%20%20%20onValueChange%3D%7Bvalue%20%3D%3E%20this.setState(%7B%20value%20%7D)%7D%0A%20%20%20%20%20%20%20%20value%3D%7Bthis.state.value%7D%0A%20%20%20%20%20%20%3E%0A%20%20%20%20%20%20%20%20%20%20%3CToggleButton%20icon%3D%22format-align-left%22%20value%3D%22left%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%3CToggleButton%20icon%3D%22format-align-right%22%20value%3D%22right%22%20%2F%3E%0A%20%20%20%20%20%20%3C%2FToggleButton.Row%3E%0A%20%20%20%20)%0A%20%20%7D%0A%7D&dependencies=react-native-paper)

**Comment by Trancever** [comment]
@msageryd This was added to 3.0 with https://github.com/callstack/react-native-paper/pull/1169.
