### ISSUE TITLE
Textinput props "padding" and "dense" not implemented as per the docs

### ISSUE THREAD

**Issue by msageryd** [callstack/react-native-paper#1292]
I'm starting to realise that the docs are probably for version 3. Both the padding and dense props are missing from 2.16.

If v3 is being released soon, this is not a problem. Otherwise I think it would be good to either:
- Mark v3 props/methods as "v3" in the docs
- Or simply remove them from the docs for now

**Comment by msageryd** [comment]
I have now installed a forked master for testing. Would you (maintainers) be interested in PRs for the docs? I could tag the new v3 props with `(coming in version 3)` or something when I encounter them?

**Comment by Trancever** [comment]
@msageryd This was added to 3.0.
