### ISSUE TITLE
Too much roundness makes outline interfere with label on TextInput

### ISSUE THREAD

**Issue by msageryd** [callstack/react-native-paper#1293]
## Environment

RNP 3.0.0 alpha3

## Description 

Large amounts of `roundness` on outlined `TextInput` does not play well with the label position when it's animated up to the outline.

![image](https://user-images.githubusercontent.com/4483085/63362796-b6149100-c372-11e9-9509-5dd0602ae46c.png)

Possible solutions:
- Move the label some amount to the right with a formula affected by roundness.
- Move all labels to the right (might be too far for those who use little or no roundness)
- Render a solid background behind the label to hide the interfering line behind

**Comment by msageryd** [comment]
I tried alternative 3 (solid background). It doesn't look good to me. Apart from the look, there would also be a problem with the animation. If the label background has a different color from the input background the color would have to be applied after the animation.

![image](https://user-images.githubusercontent.com/4483085/63363817-9bdbb280-c374-11e9-8b30-d44c8c594ad5.png)

**Comment by msageryd** [comment]
Here is a somewhat "hacky" version where the label is moved to the right 10px. I haven't quite grasped the way the line behind the label is hidden by rendering two different views (thin gray views to cover the line). I managed to move the grey view 10px, but I didn't put the effort in to give it correct line. This is just for the sake of example screen shots.

![image](https://user-images.githubusercontent.com/4483085/63365036-14437300-c377-11e9-9545-a92ba9672ac2.png)

The same 10px label move on a TextInput with roundness=0 does not look good. I think the correct solution would be to use a calculated position based on the roundness.

![image](https://user-images.githubusercontent.com/4483085/63365112-42c14e00-c377-11e9-97d2-a4bb0eee9377.png)

**Comment by RichardLindhout** [comment]
You could also round the label background like the screenshots in this pull request I did a while ago.
https://github.com/callstack/react-native-paper/pull/887

**Comment by anil-maharjan** [comment]
@msageryd  can you tell me how did you move the label right by 10px. I couldn't find any solution to that.

**Comment by msageryd** [comment]
@anil-maharjan There is no property for setting the label position. I altered the source code in a fork in order to try out the layout. I have sinced moved away from overly rounded borders, so this is not a problem to me anymore.

**Comment by badalsaibo** [comment]
I think this should be fixed. Rounded text inputs are a common thing.
