### ISSUE TITLE
Export StyledText in order to ease custom component development

### ISSUE THREAD

**Issue by msageryd** [callstack/react-native-paper#1296]
## Describe the feature

It would be great to have the internally used `StyledText` exported.

## Motivation

Custom components created with `withTheme` gets access to the theme object so they can look like the other RNP components. I would also like to have my custom labels and captions looking like the standard RNP ones.

**Comment by Trancever** [comment]
@msageryd You can always pass `style` to Paper components to customize them.

**Comment by msageryd** [comment]
Thanks.
My use case is that I need some text elements in a component. One of the elements should have the same type of translucency as the your `Caption` component. 

I'm now calculating my own textColor with the `color` package in exactly the same way as is done inside of StyledText. I thought it would be neat to reuse the functionality in StyledText instead of duplicating it.

This is absolutely no biggie. Just an idea for a feature that others might have use for as well.
