### ISSUE TITLE
BottomNavigation with shifting and single route crashes app

### ISSUE THREAD

**Issue by lafiosca** [callstack/react-native-paper#1299]
## Environment

n/a, see Snack below

## Description

Configuring a `BottomNavigation` with a single route and `shifting` enabled causes the app to crash with `Invariant Violation: Bad output range`. The crash can be avoided by having at least two routes or disabling `shifting`.

This is perhaps an obscure edge case, but I ran into it while establishing react-navigation-material-bottom-tabs in a new project, adding one route at a time. I thought I would report it on that repo, but then I tested and found it's a problem with this underlying code. I doubt this is impacting many people in practice, but it could cause difficulties for new people just starting to test the features.

## Reproducible Demo

Here's a Snack demonstrating the issue: https://snack.expo.io/SJ5BLmnVr

You should see the red crash screen when loading that Snack in the device.

![image](https://user-images.githubusercontent.com/9442662/63523934-13225b00-c4c9-11e9-8eb8-d95fc524393b.png)

If you comment out `shifting` on line 31, the app will run fine and provide a tab bar with a single icon without shifting.

Alternatively, if you uncomment lines 15-16 and 24-25, the app will run fine and provide a tab bar with 3 icons with shifting.

**Comment by jaysbytes** [comment]
On one hand, there is an error but on the other what is the purpose of using a shifting prop with only one tab? WIll this bug appear in the real-world app?

**Comment by jaysbytes** [comment]
Yes, we definitely should at least have better error reporting here, especially for newcomers, as you said. Or fix the issue :D
