### ISSUE TITLE
Remove animation for BottomNavigation

### ISSUE THREAD

**Issue by chuabingquan** [callstack/react-native-paper#1310]
Hi, is it possible to disable animation for BottomNavigation when switching between the tabs?

**Comment by jaysbytes** [comment]
Try playing with `shifting` prop. Maybe it is that what you mean.
From docs:
> Whether the shifting style is used, the active tab appears wider and the inactive tabs won't have a label. By default, this is `true` when you have more than 3 tabs.

**Comment by chuabingquan** [comment]
My bad, I wasn't clear. When I click on the bottom tabs, there would be a transition animation as the screen changes. This seems to introduce lag during between page changes using the BottomNavigation and renders some momentary stray shadows near my app bar as shown in the video below

[Example](https://youtu.be/OSR-L7BPxHs)

Snack: https://snack.expo.io/@chuabingquan/lag

**Comment by jaysbytes** [comment]
These shadows bug is related to a bug in Android 9 in react-native. But I cannot reproduce a lag. To support animation disabling we need to add a prop. It will resolve shadows issue but I'm not sure about the lag issue. Did you try the code on a real device?

**Comment by chuabingquan** [comment]
Did you try to test on an android device? The issue seems to be exclusive to android only. I’ve tried it on both an emulator and an actual device but still got some lag that’s similar to this [issue](https://github.com/callstack/react-native-paper/issues/1264)

**Comment by jaysbytes** [comment]
Yes, I tested on a high-end device. Maybe it occurs on weaker ones.

**Comment by chuabingquan** [comment]
I've tested it on a flagship android device and there's still a latency of about a second. I'm not an android user, perhaps I'm not used to the animation. However, is there a workaround for the bug you mentioned with react native?

**Comment by talaikis** [comment]
+1

**Comment by gdoudeng** [comment]
+1

**Comment by andrestone** [comment]
Any updates on this? I'm running on a Note 10+ and there's a noticeable delay.
