### ISSUE TITLE
TextInput padding prop is not available in react-native

### ISSUE THREAD

**Issue by HasnainSomroBuzzInteractive** [callstack/react-native-paper#1311]
## Ask your Question

I was trying to apply padding prop of TextInput (as mentioned in document) but it was giving error. Then I decided to look into source code and found nothing as padding prop. But your [github source](https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/TextInput.tsx) does have padding prop in TextInput file.
Please guide me in the right direction. What I am missing to do??

I have
react-native-paper@2.16.0
react-native-cli@2.0.1
react-native@0.60.4
npm@6.11.2

**Comment by jbinda** [comment]
Hi @HasnainSomroBuzzInteractive 

You need to update react-native-paper version to 3.0. The prop should be accessible then

**Comment by HasnainSomroBuzzInteractive** [comment]
Thank you for your fast response. I tried
`npm install --save react-native-paper@3.0`

But it gave me below error:
`npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native-paper@3.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.`
