### ISSUE TITLE
Icon prop error.

### ISSUE THREAD

**Issue by cngjsskaisme** [callstack/react-native-paper#1312]
## Ask your Question
As it says in documentation, I tried to add button with icon which is 'dots-vertical'. And it says that is invalid though the document says that icon is in the supported list.

And I'm using expo so AFAIK there's no need of extra configuration.

The error message was : Invalid prop name of value 'dots-vertical' supplied to 'icon'.

The code was like below :
`                    <Button
                        icon='dots-vertical'
                        size={20}
                        onPress={() => {this._openMenu}}
                    />`

Please help with this problem. Many thanks!

**Comment by chuabingquan** [comment]
@cngjsskaisme you could try `more-vert` for the icon prop instead

**Comment by cngjsskaisme** [comment]
> 
> 
> @cngjsskaisme you could try `more-vert` for the icon prop instead

Thanks for your help but that didn't help... But anyways I appreciate it :)

**Comment by jaysbytes** [comment]
@cngjsskaisme Which version of Paper are you using? 2.x or 3.x (master)

**Comment by cngjsskaisme** [comment]
@jaysbytes I have followed the 'Getting started' page instructions, so I think it's 3.x.

**Comment by jaysbytes** [comment]
You should check the version in package.json.
Check this example https://snack.expo.io/@jaysbytes/jealous-carrot
In your case `dots-vertical` (3.x) or `more-vert` (2.x) should work. If both don't work I cannot help without more complex reproduction

**Comment by rodrigo98rm** [comment]
I'm experiencing the very same issue.
My environment:
- React Native without Expo
- React Native Paper V2.16.0

Icon names on my project seem to point to [Google Material Icons](https://material.io/resources/icons/), but the icon list available on the [docs](https://callstack.github.io/react-native-paper/icons.html) point to [Material Community Icons](https://materialdesignicons.com/).

If Material Community Icons works only on (3.x), which is currently on alpha (according to the [releases page](https://github.com/callstack/react-native-paper/releases)), shouldn't the docs show the list of icons available for (2.x)?

**Comment by Arnaud-J** [comment]
I can confirm the following from @rodrigo98rm 

> Icon names on my project seem to point to [Google Material Icons](https://material.io/resources/icons/), but the icon list available on the [docs](https://callstack.github.io/react-native-paper/icons.html) point to [Material Community Icons](https://materialdesignicons.com/).
> 
> If Material Community Icons works only on (3.x), which is currently on alpha (according to the [releases page](https://github.com/callstack/react-native-paper/releases)), shouldn't the docs show the list of icons available for (2.x)?

Also, I am a little confused with the docs. Are they entirely 3.x ? Or are they 2.x with some (probably misplaced) 3.x parts ?
For the record, I lost about one hour trying icons, checking linking of my react-native-vector-icon lib, checking my ttf files and so on.

**Comment by vivek25constants** [comment]
This issue is far from closed

**Comment by lydongcanh** [comment]
I'm using 3.6.0 and [Google Material Icons](https://material.io/resources/icons/?style=baseline) doesn't seem to work either.
I've posted the available name list [here](https://gist.github.com/lydongcanh/4350326c44a7d60738dbf6c07b9b4d35) (extracted from their warning message, have no idea where it came from). Hope they update the docs soon.

**Comment by dennis-gonzales** [comment]
> You should check the version in package.json.
> Check this example https://snack.expo.io/@jaysbytes/jealous-carrot
> In your case `dots-vertical` (3.x) or `more-vert` (2.x) should work. If both don't work I cannot help without more complex reproduction

dots-vertical worked with me.
