### ISSUE TITLE
Bottom navigation android hardware back button press

### ISSUE THREAD

**Issue by mrsanta79** [callstack/react-native-paper#1313]
Hi, is there any way to control the hardware back button ? Cause, if I press the back button on any of the screen of bottom navigation tabs, it should take me to the first tab, and if I'm on the first tab, it should exit the app. But it's exiting no matter in which tab I'm in.

**Comment by jaysbytes** [comment]
Hi, Bottom navigation in Paper does not support navigation stack. But you can use react-navigation react-native-material-bottom-tabs (which uses paper's bottom navigation). Find out more in react-navigation docs https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html

If you are building an app, using a navigation library would be a great idea.

**Comment by mrsanta79** [comment]
Okay. Thanks a lot.
