### ISSUE TITLE
Button with Icon defined as URI or local asset is not being rendered as expected

### ISSUE THREAD

**Issue by rimbosUY** [callstack/react-native-paper#1315]
## Environment
Using "react-native-paper": "^2.15.2" with react-native-web. 
Button component is not working as expected when an image is set to the Icon property as it appears on ButtonExample.tsx (and also as it is documented at https://callstack.github.io/react-native-paper/icons.html)

## IT IS WORKING AS EXPECTED IN 2 DIFFERENT CONFIGURATIONS :
 1)  icon="camera" 
 2) using a custom component.
              icon={({ size }) => (
                <Image
                  source={require('../../assets/images/chameleon.jpg')}
                  style={{ width: size, height: size, borderRadius: size / 2 }}
                />
              )}

## BUT IT NOT WORKING AS EXPECTED IN THE FOLLOWING CONFIGURATIONS:
3) icon={require('../../assets/images/favorite.png')}
4) icon={{uri: 'https://avatars0.githubusercontent.com/u/17571969?v=3&s=400'}} 

The observed problem is because the image is not being rendered, only a solid square appears as the image placeholder.

**Comment by jaysbytes** [comment]
Hi! A few questions to define a problem better
1. Does the problem occur both on react-native and on the web? 
2. Does console prints any warnings/errors? 
3. Does an icon specified by name display correctly? `icon="favorite"`

**Comment by rimbosUY** [comment]
Thanks @jaysbytes for your response.   
Doing more research about the issue, it appears to be a problem between react-native-web and Safari Mobile. 
Please take a look at this issue report: https://github.com/necolas/react-native-web/issues/1319

I couldn't find more information regarding safari bug state.
So, please close this bug report because it is not related to react-native-paper (but it would be important to add a small note in the documentation for the rest of the devs).
Best regards.
