### ISSUE TITLE
Allow styling of text in Button and modification of Icon size

### ISSUE THREAD

**Issue by Sam-Martin** [callstack/react-native-paper#1317]
## Describe the feature

At the moment the text styling in Button is [hardcoded with a combination](https://github.com/callstack/react-native-paper/blob/master/src/components/Button.tsx#L272) of `styles. label` and `textStyle` neither of which are accessible outside the component. 

Also the `size` parameter passed to `Icon` is [fixed to 16](https://github.com/callstack/react-native-paper/blob/master/src/components/Button.tsx#L256) and cannot be changed.

## Motivation

I wish to use a button as a larger styling component and in order to make the appearance as I wish I would need to use a larger font and icon

## Related Issues

N/A

**Comment by pan-pawel** [comment]
@Sam-Martin I added PR with labelStyle for button. I will notify you if we add it to paper

**Comment by Sam-Martin** [comment]
That's awesome! Any thoughts on icon size?

**Comment by pan-pawel** [comment]
@Sam-Martin  we added labelStyle to master, so with next release you will be able to set custom font for button.
We will also talk about icon size, I will keep you informed

**Comment by futantan** [comment]
Any plan of releasing?

**Comment by tomchomiak** [comment]
Any update on controlling size of icon in buttons?

**Comment by GBGitUser** [comment]
I'd be interested also - I need to leave icons off at the moment as I am designing an app for construction workers which need big buttons and the size 16 icons just get lost :(

**Comment by rodrigo98rm** [comment]
I've managed to find a workaround for the icon situation.
I had to use the [React Native Vector Icons](https://github.com/oblador/react-native-vector-icons) library as well.

Here is the code:

```js
import { Button, Text } from 'react-native-paper';
import Icon from 'react-native-vector-icons/FontAwesome';

<Button
  style={buttonStyle}
  mode="contained"
  contentStyle={buttonContentStyle}
  onPress={() => this.props.navigation.navigate('Ocorrencias')}
>
  <Icon name="warning" size={24} color="#fff" />
  <View style={{ width: 16, height: 1 }} />
  <Text style={buttonTextStyle}>Hello World</Text>
</Button>
```

Here is the result:
![Screenshot (Nov 24, 2019 13_10_40)](https://user-images.githubusercontent.com/20744710/69497491-4e636a00-0ebc-11ea-8856-7a929ca8531c.png)


I've tried to add margin and padding to the Button contentStyle prop but it didn't work. That's why I've included the `<View />` between the `<Icon />` and the `Text />`.
I've also tried to put a `<View />` inside the `<Button />` and then put the rest of the stuff inside the View but I get an error.

Hope it helps!

**Comment by chriswiesner** [comment]
+1 for a iconSize prop

**Comment by CesarGomezTissini** [comment]
Commenting for needed feature.

**Comment by kopax** [comment]
It could also support `accessibilityRole="link"` for app that use button for changing pages. See https://github.com/callstack/react-native-paper/issues/1666

**Comment by CesarGomezTissini** [comment]
Why is closed? Neither news, nor devs core reaching us for at least say something about this.

**Comment by fender** [comment]
+1

**Comment by AhmedKEpfl** [comment]
Hey I think you can also pass a function to the `icon` props:

```tsx
<Button
    onPress={() => console.log('Clicked')}
    icon={() => <FontAwesomeIcon name='plus' size={24} />}
>    
    {'Add user'}
</Button>
```

The function returns any React component, so you can return an icon too.
