### ISSUE TITLE
Menu in AppBar?

### ISSUE THREAD

**Issue by talaikis** [callstack/react-native-paper#1327]
## Ask your Question

Can I use menu in AppBar? Currently menu 's height = AppBar height.
```
<Appbar.Header>
  { backIcon }
  <Appbar.Content title={title} />
  { menuProvider }
  <Appbar.Action icon="more-vert" onPress={this._openMenu} />
</Appbar.Header>
```

**Comment by brunocrpontes** [comment]
Yes, you can! Just insert a Menu as children into a Appbar.Header and set Appbar.Action as anchor prop like this:

```
<Appbar.Header>
<Menu
  onDismiss={onDismissMenu}
  visible={isMenuVisible}
  anchor={
     <Appbar.Action
       disabled={isLoading}
       color="white"
       icon="more-vert"
       onPress={onShowMenu}
     />
   }>
       <Menu.Item icon="edit" title="Editar" onPress={onPressEdit} />
</Menu>
</Appbar.Header>
```

**Comment by talaikis** [comment]
Nice, seems that `<Provider>` should be removed and it works fine.

**Comment by dihan** [comment]
@talaikis what do you mean by removing <Provider>? I did as @brunocrpontes mentioned but seems to be hidden on the backgroud
