### ISSUE TITLE
Weird behaviour when using `theme` prop in Button

### ISSUE THREAD

**Issue by ahmedlhanafy** [callstack/react-native-paper#133]
<img width="487" alt="screen shot 2017-08-10 at 1 48 30 pm" src="https://user-images.githubusercontent.com/7052827/29175531-96627226-7de9-11e7-990a-3082c91a01f2.png">
I only changed the theme of the second button in the second row to use color red as the primary color; it updated correctly but unexpectedly the second button in the third row updated to the same theme

**Comment by ferrannp** [comment]
@ahmedlhanafy we need some code to reproduce.

**Comment by satya164** [comment]
Cannot reproduce.
