### ISSUE TITLE
How to use outline icons?

### ISSUE THREAD

**Issue by ckristhoff** [callstack/react-native-paper#1332]
## Ask your Question

That's it, how to use outline icons in paper components🤔?

**Comment by devdennisj** [comment]
If you for example have a Button component it would be <Button icon='help-outline'>Help</Button>

**Comment by ckristhoff** [comment]
That's so confusing. Why only some icons works?
I'm trying 

```javascript
<IconButton icon="add-a-photo-outline" />
```
but it doesn't works.

**Comment by ferrannp** [comment]
@ckristhoff we support all icons from https://materialdesignicons.com/. If it is not there, it won't work.
