### ISSUE TITLE
How to make dynamic DataTable?

### ISSUE THREAD

**Issue by chubecode** [callstack/react-native-paper#1335]
## Dynamic DataTable
Hi, I'm working on DataTable.
But I want make dynamic DataTable seems like when click button It'll increase a new row.
How to do it? I already read the docs but nothing helpful for this case.
Thanks.

**Comment by Trancever** [comment]
@chubecode There is no special way of doing this. The flow is as follow: button onPress -> update state -> rerender with new row/content. If you want to somehow animate the new row/content, you have to do it manually.
