### ISSUE TITLE
allowFontScaling prop on <Avatar.Text>?

### ISSUE THREAD

**Issue by bvelasquez** [callstack/react-native-paper#1340]
## Ask your Question

Is it possible to set the <Avatar.Text /> allowFontScaling property on the underlying Text?

**Comment by sonhgc00016** [comment]
same question here

**Comment by satya164** [comment]
Why do you need to control it?

@Trancever I think we should set `allowFontScaling={false}` there, no?

**Comment by mondash** [comment]
+1 on this issue. Font scaling doesn't work properly for this component, so when using larger font sizes on a device, the text clips outside the border.

**Comment by josehernandezv** [comment]
Any news? This still happens
