### ISSUE TITLE
ripple effect renders wrong in buttons with borderRadius

### ISSUE THREAD

**Issue by fermmm** [callstack/react-native-paper#1342]
## Environment

react-native-paper: 2.16.0

## Description
 Apply a borderRadious to a button and the ripple effect will render outside the button:

![bug](https://user-images.githubusercontent.com/3660373/65380055-685cb280-dca9-11e9-8458-5439756a1224.jpg)

I could not find a way to apply a border radius to the ripple effect

**Comment by Ashkan-Oliaie** [comment]
I'm still having this issue on TouchableRipple on 3.8.0

**Comment by NathanC** [comment]
@Trancever This issue still seems to be present. I set the border radius to 0, but the ripple is still the same rounded shape. Is there any workaround?

**Comment by NathanC** [comment]
@iyadthayyil I looked through your associated PR that fixed this. I'm using `5.0.0-rc.6`, and it's not working-- it appears your changes are still live though. Do you think something regressed or the way border radius works on `TouchableRipple` changed?

**Comment by NathanC** [comment]
For anyone seeing this, there's a new related issue in the latest v5 release candidate: https://github.com/callstack/react-native-paper/issues/3387

It's inverted though, the ripple is showing inside the button (not filling it), as opposed to this issue where the ripple was outside of the button. Very similar though.

**Comment by BojanHribernik** [comment]
I am still having this issue with react-native-paper@5.10.3

[Screencast from 2023-08-30 00-25-17.webm](https://github.com/callstack/react-native-paper/assets/114930095/34379807-2a72-483f-b0d9-c3324d1a6dc8)

This is my component. It works with `borderRadius`, but not with `borderTopLeftRadius` etc ...

```tsx
import { StyleSheet, Text } from 'react-native'
import { Button, ButtonProps } from 'react-native-paper'

export type PrimaryButtonProps = Omit<ButtonProps, 'mode'>

export function PrimaryButton({
  children,
  style,
  ...props
}: PrimaryButtonProps) {
  return (
    <Button
      {...props}
      mode="contained"
      rippleColor={'red'}
      contentStyle={styles.buttonContent}
      style={[styles.button, style]}
    >
      <Text style={styles.text}>{children}</Text>
    </Button>
  )
}

const styles = StyleSheet.create({
  button: {
    minWidth: 200,
    //borderRadius: 0,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 15,
  },
  buttonContent: {
    //borderRadius: 0,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 15,
  },
  text: {
    color: 'white',
    textTransform: 'uppercase',
    fontWeight: '700',
  },
})
```

**Comment by mauroiemboli** [comment]
Sorry, how did you guys apply borderRadios on Button? Even if I pass bordeRadius: 0 I still have the button rounded
