### ISSUE TITLE
fontFamily "material" is not a system font when using Expo

### ISSUE THREAD

**Issue by connercms** [callstack/react-native-paper#1347]
## Environment

Expo SDK 35
react-native-paper 2.16.0 

## Description

Trying to use react-native-paper components in an expo project, I receive the error "fontFamily "material" is not a system font and has not been loaded through Font.loadAsync.". The docs state that when using expo, there is no need to install vector-icons as it is prepackaged with expo, so I am not sure where the issue lies. I see an open issue for this dating back to earlier this year with no definitive solution but suggesting to load the fonts via `    await Font.loadAsync({ 'MaterialIcons': require('@expo/vector-icons/fonts/MaterialIcons.ttf') })`, but I do not have a fonts directory under vector-icons.

**Comment by nsdub** [comment]
I hit a similar issue with `Font.loadAsync()` after upgrading from Expo SDK 35 (and 34). The fix for me was to:

1. Delete node_modules folder: `rm -rf node_modules`
2. Delete `package-lock.json`
3. Run `npm install`

**Comment by connercms** [comment]
This was actually the fix for me also, I had forgotten to close this issue. Thanks!

**Comment by Arjun-Aggarwal** [comment]
Hi, I am facing the same issue. I tried removing and reinstalling node_modules; however, it did not work for me

**Comment by kevinvugts** [comment]
Re-opening this issue as of the newest version it still doesn't work with expo. SDK 36.0.2

**Comment by nonameolsson** [comment]
https://github.com/callstack/react-native-paper/issues/2450#issuecomment-813066356

**Comment by zehrabilgin** [comment]
You can paste this line to page that you get error. It worked fine for me.

import * as Font from 'expo-font';

**Comment by tr4g** [comment]
still not fixed??
