### ISSUE TITLE
Font error when migrating from "2.16.0" to "3.0.0-alpha.5"

### ISSUE THREAD

**Issue by fermmm** [callstack/react-native-paper#1348]
When migrating from "2.16.0" to "3.0.0-alpha.5" I get this error when running my app:

![65636971-b7605b80-dfb9-11e9-83c4-659b244fab98](https://user-images.githubusercontent.com/3660373/65719295-e939f680-e07b-11e9-9edd-eb5054bc7844.png)

If you need any information from my code let me know.

**Comment by matyj** [comment]
I have this issue as well

**Comment by Trancever** [comment]
You need to update fonts in a theme. Check [this](https://github.com/callstack/react-native-paper/blob/master/src/styles/fonts.tsx) for reference.
