### ISSUE TITLE
In Android, Surface component's shadow flashes when switching tabs in a bottom tab navigator

### ISSUE THREAD

**Issue by ablbol** [callstack/react-native-paper#1349]
## Environment

Here are all my dependencies
```
  "dependencies": {
    "expo": "^34.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-paper": "^2.16.0",
    "react-native-reanimated": "~1.1.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^4.0.5",
    "react-navigation-material-bottom-tabs": "^2.1.2",
    "react-navigation-stack": "^1.7.3",
    "uuid": "^3.3.3"
  },
```

## Description

The following issue happens in Android only.  I have not seen it happen in ios.
I have couple tab screens in a bottom tab navigator.  In screen 1, I have several simple components that look like this:

```
      <Surface style={{ elevation: 4, width: 100, margin: 12 }}>
        <View style={{ width: 100, height: 100, padding: 12 }}>
          <Text>some text will go here.</Text>
          <Text>some text will go here.</Text>
        </View>
      </Surface>
```

When I switch from tab 1 to tab 2 in the tab navigator, I see flash around all the View components.  Most likely the flash is due to the animations of the shadows in Surface component.  If I use elevation=0, I don't see the flash.  Please see attached pictures.

When you have many components in the screen surrounded with Surface component, things get really ugly.  Is there a way to stop the flash in the surface component

![ezgif-2-3b57ffb5b53b](https://user-images.githubusercontent.com/22548671/65700744-34123900-e091-11e9-9e36-912eb3a3a271.gif)

?

**Comment by gdoudeng** [comment]
+1

**Comment by ferrannp** [comment]
Hey,

This is not Paper issue but react-native issue with elevation on Android P and above.  See https://github.com/facebook/react-native/issues/6480 & https://github.com/react-navigation/react-navigation/issues/5535. Please continue the discussion in the `react-native` repo.

**Comment by vtoupet** [comment]
@ferrannp even though it seems to be a react native issue, there seems to be a solution (see https://github.com/facebook/react-native/issues/23090#issuecomment-669157170) that is also validated here (https://github.com/facebook/react-native/issues/23090#issuecomment-710803743).

Do you think this could be implemented in react-native-paper?
