### ISSUE TITLE
Modal appears below Surface

### ISSUE THREAD

**Issue by yasir-netlinks** [callstack/react-native-paper#1350]
## Ask your Question

I am trying to have Modal in a separate component
```
render() {
    const {visible, onHideModal} = this.props;
    return (
      <Provider>
        <Portal>
          <Modal visible={visible} onDismiss={onHideModal}>
            <View style={{height: 300, width: 200, backgroundColor: '#fff'}}>
              <Text>Example Modal</Text>
            </View>
          </Modal>
        </Portal>
      </Provider>
    );
  }
}
```
and using this component in another that has `Surface` , the modal appears below the `Surface` and also overlaps `Text`

<img width="437" alt="Screen Shot 2019-09-26 at 10 38 24 PM" src="https://user-images.githubusercontent.com/26054956/65713417-654d3200-e0ae-11e9-9469-78bb8c13481c.png">

**Comment by ferrannp** [comment]
Can you provide a repro?

**Comment by Trancever** [comment]
I am closing because no repro is provided.
