### ISSUE TITLE
Font Size as Theme Variable

### ISSUE THREAD

**Issue by ZhengYuTay** [callstack/react-native-paper#1351]
## Describe the feature

1. Make fontSize a variable for theming

## Motivation

1. With the current configuration, the only way to change fontSize for an existing component is to copy it and make our new component with custom fontSize styling. A theme variable would help solve many of this issues. For example of implementation https://material-ui.com/customization/typography/#font-size

**Comment by sdiaz** [comment]
+1

**Comment by bkazula** [comment]
Hello, is there a possibility it has been already done or it might be done?

**Comment by willparsons** [comment]
Still no word on this?

**Comment by abumalick** [comment]
We can upvote this https://github.com/callstack/react-native-paper/issues/1489#issuecomment-746142215
