### ISSUE TITLE
TextField label has margin initialValues

### ISSUE THREAD

**Issue by douglaszaltron** [callstack/react-native-paper#1354]
## Environment

react-nativo > 0.61.1
react-native-paper `3.0.0-alpha.5`

## Description

In input text fields, when fields are filled in by redux or the label has a different margin than the text. after you change the value back to normal

## Reproducible Demo

![image](https://user-images.githubusercontent.com/4502670/65796245-7a73a080-e142-11e9-83f1-ca94a0f0520d.png)

**Comment by mishojan** [comment]
PLEASE FIX THIS :((((((

**Comment by satya164** [comment]
@mishojan please send a pull request

**Comment by RichardLindhout** [comment]
Will try to fix this, this week probably Tuesday.

**Comment by RichardLindhout** [comment]
Ok little bit later than Tuesday but I  found the cause :-)

**Comment by RichardLindhout** [comment]
The code here is never ran when you have an initial value
```
https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/TextInput.tsx#L210
```
There is an initial value available in the state so it's never changed there
https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/TextInput.tsx#L191

**Comment by RichardLindhout** [comment]
Pull request: https://github.com/callstack/react-native-paper/pull/1440

**Comment by RichardLindhout** [comment]
FIx for this merged: https://github.com/callstack/react-native-paper/pull/1441
