### ISSUE TITLE
OnPress event on radio button does not work

### ISSUE THREAD

**Issue by Nysans** [callstack/react-native-paper#1355]
## Environment

react-native  0.60.4
react-native-paper 2.16.0

## Description

When I pass the function to the RadioButton prop OnPress, the event doesn't fire no matter how many times I press the button.

## Reproducible Demo

The example itself passed by the documentation is enough to reproduce the error.

```javascript
import * as React from 'react';
import { View } from 'react-native';
import { RadioButton } from 'react-native-paper';

export default class MyComponent extends React.Component {
  state = {
    checked: 'first',
  };

  render() {
    const { checked } = this.state;

    return (
      <View>
        <RadioButton
          value="first"
          status={checked === 'first' ? 'checked' : 'unchecked'}
          onPress={() => { this.setState({ checked: 'first' }); }}
        />
        <RadioButton
          value="second"
          status={checked === 'second' ? 'checked' : 'unchecked'}
          onPress={() => { this.setState({ checked: 'second' }); }}
        />
      </View>
    );
  }
}
```

**Comment by sseoussama** [comment]
same here !!

**Comment by Taym95** [comment]
Hey, first of all, RadioButton needs to be wrapped with RadioButton.Group because it needs `context`, and I submitted a PR to fix `onPress`.

**Comment by Trancever** [comment]
@Taym95 RadioButton does not have to be wrapped in RadioButton.Group. It can be used as a standalone component. I left a comment under your PR asking for a change.

**Comment by saadheikh** [comment]
state:{
checked:'first'
}

<RadioButton
                                                                              value="first"
                                                                              status={checked === 'first' ? 'unchecked' : 'checked'}
                                                                              onPress={() => {
                                                                                console.log(this.state.checked)
                                                                                 if(checked === 'first')
                                                                                 {
                                                                                      this.setState({
                                                                                        checked:'clicked'
                                                                                      })
                                                                                 } 
                                                                                 else if(checked === 'clicked'){
                                                                                       this.setState({ checked: 'first' });
                                                                                 } }}
                                                                            />

this is working
