### ISSUE TITLE
Warning: "TextInput" : `ref` is not a prop. 

### ISSUE THREAD

**Issue by redbluenat** [callstack/react-native-paper#1358]
## Environment

React Native: 0.60.5
React Native Paper: 3.0.0-alpha.5

## Description
I had some issues with auto complete and text suggestion in previous version so I updated lib to the alpha version. It works like a charm for me and solved my problems but I start having a yellow warning screen.

<img width="347" alt="Zrzut ekranu 2019-10-1 o 11 22 02" src="https://user-images.githubusercontent.com/15861135/65950536-8ca15780-e43e-11e9-8034-2a0dcdb70064.png">

any ideas how to solve it? when I comment `ref={this.handleTextInputRef}` yellow screen disappear. 

## Reproducible Demo
```

  <PaperTextInput
              {...this.props}
              mode={isOutlined ? 'outlined' : 'flat'}
              ref={this.handleTextInputRef}
              onChangeText={this.onChangeText}
              value={this.state.textInputValue}
            />
...
 private handleTextInputRef = (ref: any) => {
    this.textInputReference = ref;
  };
```

**Comment by ferrannp** [comment]
It is fixed here https://github.com/callstack/react-native-paper/pull/1361. Thanks for opening the issue!
