### ISSUE TITLE
🔥 this._searchbar.focus() does not show typing indicator on focus (ANDROID)

### ISSUE THREAD

**Issue by kevinvugts** [callstack/react-native-paper#1360]
## Environment

```
 React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
      Memory: 3.73 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.npm/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz => 0.59.8 
```

React-native-paper:   "react-native-paper": "^2.16.0",

## Description

```
this._searchbar.focus()
```

The above code does focus the searchbar but it doesn't show an indicator / typing indicator on Android. On iOS it does work as expected. When clicking manually in the searchbar it shows the indicator / typing indicator tho.

**Comment by Trancever** [comment]
@kevinvugts Can you check if `TextInput` from react-native has the same behaviour on Android?

**Comment by kevinvugts** [comment]
> @kevinvugts Can you check if `TextInput` from react-native has the same behaviour on Android?

I would love to. But what do you want me to check?

**Comment by Trancever** [comment]
If TextInput from React-Native shows typing indicator when it's focused via `ref.focus()`. I want to make sure that this is an issue in Paper and not in React-Native.
