### ISSUE TITLE
Set TextInput BorderWidth in outline mode

### ISSUE THREAD

**Issue by Auticcat** [callstack/react-native-paper#1362]
I would like to set the borderWidth to 2 to a disabled but valued text-input.

Now it stays with borderWidth set to 1.

Is there a way to control it?

**Comment by Trancever** [comment]
It is not MD guidelines compliant and we do not support it.

**Comment by kabonKoda** [comment]
set width property in theme

`<TextInput
          theme={{ width: 2 }}
          {...props}
  />`
