### ISSUE TITLE
RadioButton label is not shown on web (snack example too)

### ISSUE THREAD

**Issue by littlehome-eugene** [callstack/react-native-paper#1364]
## Environment

with "react-native-web": "^0.11.7",

## Description

Even snack sample has the same problem.

https://callstack.github.io/react-native-paper/radio-button.html

If you click on Try ` this example on Snack ` , you will see that labels are missing in the web.

## Reproducible Demo

https://callstack.github.io/react-native-paper/radio-button.html

**Comment by jaysbytes** [comment]
Hi @littlehome-eugene ! Radio Button in paper does not support any kind of UI label. If you want to add a label you have to wrap RadioButton within a container and add some text there. It only supports accessibility label, but it is not displayed.
