### ISSUE TITLE
Can we make Divider vertical ?

### ISSUE THREAD

**Issue by rockfight** [callstack/react-native-paper#1365]
## Ask your Question

Is there any prop which we can use to make Divider component vertical ?

**Comment by Trancever** [comment]
@rockfight There is no such prop.

**Comment by DarshanNDK** [comment]
It can be done via style prop, right?

**Comment by masoud-msk** [comment]
> <Divider style={{ width: 1, height: '100%' }} />

@D-Navadiya That would be a [**bold** divider](https://callstack.github.io/react-native-paper/docs/components/Divider#bold--available-in-v5x-with-theme-version-3). It's better to use `StyleSheet.hairlineWidth` for the `width` as it's set for the `height` by default:

```jsx
<Divider style={{ width: StyleSheet.hairlineWidth, height: '100%' }} />
```
