### ISSUE TITLE
Touchable area of Buttons doesn't match width

### ISSUE THREAD

**Issue by byteasc** [callstack/react-native-paper#1369]
It seems as if the issue where the width of a button does not control the actual Touchable width still, so the ripple effect is just barely a portion of the button.

Example, create a button with a flex:1 view as a Parent, the button will be full width (or should be), but then clicking it is only around the area with the text. 

I saw this report that was previously closed due to it getting too heated, but there didn't seem to be a resolution or workaround posted that I could see

#871

**Comment by satya164** [comment]
That issue is about height. Width should fill always the parent. Can you post a repro?

**Comment by byteasc** [comment]
I changed to 

```
  nextButton: {
    flexDirection: 'row',
    padding: 0,
    height: 64,
  },
```

Removed the Text component as well, to just use what exists currently, to eliminate any possibility of issues there. 
```
      <Button 
      style={styles.nextButton} 
      mode="contained" 
      color="rgb(9, 109, 168)" 
      onPress={() => console.log('Pressed')}
      >
          NEXT
      </Button>
```
If the button itself is filling the entire space with the background color, shouldn't the touchable also be doing the same.

![ScreenRecording2019-10-08at11031](https://user-images.githubusercontent.com/10793868/66412885-fa5bff00-e9bb-11e9-9f5a-0ce4429ff4c1.gif)

**Comment by satya164** [comment]
You're still adding `flexDirection: 'row'`. If you need custom size, use `contentStyle` as mentioned in the docs: https://callstack.github.io/react-native-paper/button.html#contentStyle

**Comment by harrykalsi9899** [comment]
> You have added these styles which result in the touchable not stretching to the area:
> 
> ```js
> alignItems: 'center',
> justifyContent: 'center',
> ```

thanks bro , it worked

**Comment by Irfanwani** [comment]
add styles to button content using the prop contentStyle  to increase the touchable area
