### ISSUE TITLE
Radiobuttons and checkboxes are functionally incomplete

### ISSUE THREAD

**Issue by DianaKoenraadt** [callstack/react-native-paper#1371]
## Environment
All

## Description

Expected behavior: The user can provide children to the radiobutton that will be rendered inside the clickable area. 

The documentation of react-native-paper, and especially the screenshots, make implicit promises about the functionality that the library does not meet.  

In html, you can put the checkbox and some text inside a label and then couple the label to the textbox to make all of it clickable.

Can you please extend radiobutton/checkbox to accept children so that _all of it_ is clickable?

## Reproducible Demo

Go to the documentation at https://callstack.github.io/react-native-paper/radio-button.html and click "try this example on Snack". This just shows two empty radio buttons.

**Comment by Trancever** [comment]
@DianaKoenraadt Our library provides all necessary low level components that you can combine together to build more complex ones like the one you are requesting. Check the source code of our [RadioButton example](https://github.com/callstack/react-native-paper/blob/master/example/src/Examples/RadioButtonExample.tsx).
