### ISSUE TITLE
RadioButton.ref not working?

### ISSUE THREAD

**Issue by DianaKoenraadt** [callstack/react-native-paper#1372]
## Environment

Android

## Description

I cannot obtain the ref. I wanted to work around issue #1371 for now, by wrapping the RadioButton in a Touchable (Can be a TouchableOpacity too, doesn't matter). But I cannot obtain the ref to do so.

## Reproducible Demo
```
import React from 'react'; // eslint-disable-next-line no-unused-vars
import { View } from 'react-native';
import { RadioButton, Text } from 'react-native-paper';
import { Styles } from '../constants/Styles';
import Touchable from 'react-native-platform-touchable';

export default class MyRadioButton extends React.Component {
    constructor(props) {
        super(props);

        this._radio = null;
    }

    _onPress() {
        console.log('click!');
        if (this._radio) {
            console.log('radio');
            //this._radio.click();
            this._radio.handlePress();
            //this._radio.onValueChange(true);
        }
    }

    render() {
        return (
            <Touchable onPress={this._onPress}>
                <View style={Styles.radioButton}>
                    <RadioButton value={this.props.value} ref={(ref) => this._radio = ref} />
                    <Text>{this.props.text}</Text>
                </View>
            </Touchable>
        )
    }
}
```

Above, `this._radio` is and stays null. I also tried it with `React.createRef()` but that doesn't work either:

```
import React from 'react'; // eslint-disable-next-line no-unused-vars
import { View } from 'react-native';
import { RadioButton, Text } from 'react-native-paper';
import { Styles } from '../constants/Styles';
import Touchable from 'react-native-platform-touchable';

export default class MyRadioButton extends React.Component {
    constructor(props) {
        super(props);

        this._radio = React.createRef();
    }

    _onPress() {
        console.log('click!');
        if (this._radio && this._radio.current) {
            console.log('radio');
            //this._radio.click();
            this._radio.current.handlePress();
            //this._radio.onValueChange(true);
        }
    }

    render() {
        return (
            <Touchable onPress={this._onPress}>
                <View style={Styles.radioButton}>
                    <RadioButton value={this.props.value} ref={this._radio} />
                    <Text>{this.props.text}</Text>
                </View>
            </Touchable>
        )
    }
}
```

**Comment by satya164** [comment]
This is not supported. You need to pass the value in a prop.

**Comment by DianaKoenraadt** [comment]
Hi @satya164, I am not interested in value/props: I want to wrap the RadioButton in a Touchable. How can I do this? I tried this, but that doesn't work either:

```
import React from 'react'; // eslint-disable-next-line no-unused-vars
import { View } from 'react-native';
import { RadioButton, Text } from 'react-native-paper';
import { Styles } from '../constants/Styles';
import Touchable from 'react-native-platform-touchable';

export default class JodiRadioButton extends RadioButton {
    onPress() {
        RadioButton.prototype.handlePress.call(this);
    }

    render() {
        return (
            <Touchable onPress={() => this.onPress()}>
                <View style={Styles.radioButton}>
                    {/* Because JodiRadioButton extends RadioButton, we say 'at this spot, render yourself as if we didn't tell you how to render'  */}
                    {super.render()} 
                    <Text>{this.props.text}</Text>
                </View>
            </Touchable>
        )
    }
}
```

How do I pass the click on to the RadioButton?

**Comment by DianaKoenraadt** [comment]
This is the error I get when I try the last method:

![image](https://user-images.githubusercontent.com/5881327/66421308-eccc6680-ea07-11e9-81ee-cac3e385137f.png)

**Comment by satya164** [comment]
> I tried this, but that doesn't work either
> This is the error I get when I try the last method

You're not supposed to extend react components. You need to create a custom component and render it inside.

```js
function RadioButtonItem({ onPress, label, ...rest }) {
  return (
    <Touchable onPress={onPress}>
      <View style={styles.row}>
        <Paragraph>First</Paragraph>
        <RadioButton {...rest} />
      </View>
    </Touchable>
  );
}
```

**Comment by satya164** [comment]
You need to update your state on `onPress`

```js
function MyExample() {
  const [value, setValue] = React.useState(false);

  return (
    <RadioButtonItem label="Test" value={value} onPress={() => setValue(v => !v)} />
  )
}
```

**Comment by DianaKoenraadt** [comment]
I appreciate your help, but this is not working either. `value` is not a boolean, it is a string. https://callstack.github.io/react-native-paper/radio-button.html#value

I'm still trying here, but there's just no way that I get the RadioButton to update unless I click directly on the RadioButton. I truly think I need a `ref` to force this.

**Comment by satya164** [comment]
@DianaKoenraadt it should be `status`. My mistake.

**Comment by satya164** [comment]
> I truly think I need a `ref` to force this.

You very rarely need a `ref`. Most of the time you need `ref` is when you want to manage focus or scroll.

**Comment by DianaKoenraadt** [comment]
Found it!! Ended up with this:

    function MyRadioButton({ onPress, text, ...rest }) {
        return (
            <Touchable onPress={onPress}>
                <View style={Styles.radioButton}>
                    <RadioButton {...rest} />
                    <Text>{text}</Text>
                </View>
            </Touchable>
        );
    }

    <RadioButton.Group
        onValueChange={value => this._setState(value)}
        value={this._getState()} >
            <MyRadioButton value="a" text="a" onPress={() => this._setState({ something: "a"})} />
            <MyRadioButton value="b" text="b" onPress={() => this._setState({ something: "b"})} />
    </RadioButton.Group>

Thanks!
