### ISSUE TITLE
How do I put my own component in a RadioButton.Group?

### ISSUE THREAD

**Issue by DianaKoenraadt** [callstack/react-native-paper#1373]
## Ask your Question

If I manage to get MyRadioButton in issue #1372 working, how do I make it so that RadioButton.Group does its thing? What should I expose in terms of props/methods?

**Comment by satya164** [comment]
https://github.com/callstack/react-native-paper/blob/bd4296116d841ed355f3dbebb40cfbc3b87a79ff/example/src/Examples/RadioButtonGroupExample.tsx#L41
