### ISSUE TITLE
with react-native-web, icons are all displayed as square

### ISSUE THREAD

**Issue by littlehome-eugene** [callstack/react-native-paper#1374]
## Environment

     "react-native-paper": "^2.16.0",
     "react-native-vector-icons": "^6.6.0",
     "react-native-web": "^0.11.7",
## Description
<img width="312" alt="Screen Shot 2019-10-09 at 11 23 37 AM" src="https://user-images.githubusercontent.com/24217396/66446933-67889680-ea87-11e9-8223-757861035081.png">

I am trying to load a button with icon.. 

```
           <ToggleButton
             icon="bluetooth"/>
  <ToggleButton icon="format-align-left" value="asc" />
```

I followed https://callstack.github.io/react-native-paper/using-on-the-web.html even though I didn't use `react-app-rewired`

**Comment by Trancever** [comment]
Since you are using paper v2, you should use MaterialIcons names instead MaterialCommunityIcons. Let me know if that helps.
