### ISSUE TITLE
"Try the demo on Snack" link in documentation links to broken snack project

### ISSUE THREAD

**Issue by hrastnik** [callstack/react-native-paper#1375]
## Environment
Device: Any

## Description

The "Try the demo on Snack" link in the frontpage of the documentation is broken.
This is the main entry point for most developers wanting to try out the library, and if the demo is broken it doesn't give much confidence for the rest of the library. 

## Reproducible Demo
1. Open https://callstack.github.io/react-native-paper/index.html
2. Click the "Try the demo on Snack" link and try to run the project.

**Comment by Trancever** [comment]
@hrastnik Is it still an issue?

**Comment by hrastnik** [comment]
Yep, just tested it and here's what I get

![Screenshot_20191114-143212](https://user-images.githubusercontent.com/3407234/68861372-b9a68280-06eb-11ea-954f-410245e608dc.png)
