### ISSUE TITLE
TextInput Label wrong position without focus and given value

### ISSUE THREAD

**Issue by Brainyoo** [callstack/react-native-paper#1380]
## Environment

RN-Version: 0.61.2
React-Verison 16.9.0
RN-Paper-Version: 3.0.0-alpha.5

## Description

If I use the TextInput-Component and set the label with an existing value, the label gets padding on the left side. The longer the label, the longer the padding.
If I click in the input-field, the label corrects his position.
It happens on Android and iOS.

**(without focus)**
![Bildschirmfoto 2019-10-10 um 12 54 48](https://user-images.githubusercontent.com/54897979/66563057-3f6b6700-eb5d-11e9-927b-838b8aaf28f0.png)
![Bildschirmfoto 2019-10-10 um 12 55 01](https://user-images.githubusercontent.com/54897979/66563063-42665780-eb5d-11e9-8b01-f94aac9339e3.png)
![Bildschirmfoto 2019-10-10 um 12 55 07](https://user-images.githubusercontent.com/54897979/66563068-44c8b180-eb5d-11e9-9fd7-e41c00afd428.png)
![Bildschirmfoto 2019-10-10 um 12 55 24](https://user-images.githubusercontent.com/54897979/66563070-45614800-eb5d-11e9-8b31-3120fcbac60e.png)

**(with focus)**
![Bildschirmfoto 2019-10-10 um 12 56 49](https://user-images.githubusercontent.com/54897979/66563147-717cc900-eb5d-11e9-98bc-650a44c84cbf.png)

**Comment by Brainyoo** [comment]
Im closing this issue because it seems to happen only with my Dialog. In other cases it works

**Comment by Brainyoo** [comment]
Ok I found out how to cause this issue.
If you already defined the value for your TextInput, it causes the padding problem.

`const MainScreen = () => {`

   ` const [text, setText] = useState('bla');
    return <TextInput label={"translate('dialog.editWord')"} value={text} onChangeText={setText} padding={'none'} />;
};`

**Comment by RichardLindhout** [comment]
Not true, I have the same bug. Its not your dialog. It does the padding on the flat input which should only be done on the outlined one.

**Comment by hugopretorius914** [comment]
I too have this bug, and it's on both Android and iOS.

**Comment by jaulz** [comment]
Please try `3.0.0` which was released today. Maybe it's related to https://github.com/callstack/react-native-paper/pull/1405

**Comment by Shywim** [comment]
Same bug on 3.0.0 (not alpha).

**Comment by RichardLindhout** [comment]
It's very strange it does not happen always, now it's only when I open the app for the first time and have not touched the input yet. After a focus this TextInput will be right even after a second screen mount.

**Comment by RichardLindhout** [comment]
I'm on mobile right now but maybe this is the problem
https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/TextInput.tsx#L187

Labeled will not be 0 if this.props.value is filled, needs more casing around the statement, but I'm not sure about that

**Comment by lunks** [comment]
In 0.61.2 is pretty easy to reproduce (at least in my app), just enable Fast Refresh on a class component and let it trigger when you overwrite the file.

**Comment by Trancever** [comment]
@lunks Does it happen only when fast refresh is enabled? Can you create a minimal repro on [Snack](https://snack.expo.io/) where we could try it?

**Comment by diablourbano** [comment]
This issue is happening with `^3.0.0` version installed, I downgrade my version to `^2.15.0` and it works as expected.

**Comment by RichardLindhout** [comment]
Pull request: https://github.com/callstack/react-native-paper/pull/1440

**Comment by RichardLindhout** [comment]
Fix for this merged: https://github.com/callstack/react-native-paper/pull/1441
