### ISSUE TITLE
Segmented Control

### ISSUE THREAD

**Issue by msageryd** [callstack/react-native-paper#1382]
## It would be great with a Segmented Control component

Actually, the ToggleButton.Row is already quite close. Maybe this component could be extended to solve this?

What ToggleButton.Row would need:
- flex:1 for the complete width of the button row so the row can fill the width of a view
- LabelText (only Icon is supported now)
- Adaptive width of each button (only square now)

## Motivation

I haven't found any good Segmented Controls other than the iOS version shipped with react-native. I need `<Segmented>` for Android as well.

**Comment by jaysbytes** [comment]
I might be wrong, but there is no segmented control in material design so it will probably not be supported by this library.

**Comment by satya164** [comment]
You're always right Jay.

**Comment by pratikdhody** [comment]
I second @msageryd's request. This can be supported as per the above bullet points.

**Comment by maximilianotaverna** [comment]
I don't understand why this issue is closed as it does not meet the material guidelines specifications "Width | dynamic based on labels, but fixed (equal segments)" as per layout values .. ref https://m3.material.io/components/segmented-buttons/specs
