### ISSUE TITLE
Flat TextInput textColor getting overwritten if black

### ISSUE THREAD

**Issue by Auticcat** [callstack/react-native-paper#1384]
Is it a desired behaviour that, if passing a theme with textColor the textInput will overwrite the black color to a greyish one?

I'm facing this problem when, passing this theme:

```
const theme={
   colors:{ 
      text: "black"
   }
}
```
to my textInput:

```
 <TextInput
  mode={"flat"}
  label={myLabel}
  value={myValue}     //have a value prefilled when disabled
  theme={theme}
  disabled={true}
/>
```

Is there a way to get the black text written inside of it?

**Comment by jaysbytes** [comment]
hmm maybe try using `editable={false}` instead of `disabled={true}`. Then color should be taken from as `theme.colors.text`. When You use `disabled` prop, colors is 

```
inputTextColor = activeColor = color(colors.text)
        .alpha(0.54)
        .rgb()
        .string();
```

see https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/TextInputFlat.tsx Line `88` fro details

**Comment by Auticcat** [comment]
Problem with editable is that it does not actually block the component, it still lets you press it and open keyboard, even if while writing it does not work.
 I had seen that part of code that's why i asked if it was a desired behavior to overwrite a color.
I'll just deal with it and leave it grey!
