### ISSUE TITLE
Card background with dark theme

### ISSUE THREAD

**Issue by chriswiesner** [callstack/react-native-paper#1388]
Shouldn't the card reflect also the background (surface) of the theme?

I set my theme to dark but the cards background is still white. Shouldn't this be also recognized? Or am I missing sth?

**Comment by lukewalczak** [comment]
What version of `react-native-paper` are you using?

**Comment by chriswiesner** [comment]
Just found out that v3 (with dark support) is not public yet.
was using 2.x -- maybe the docs should not that the "dark" flag is only available on 3+
