### ISSUE TITLE
Add size props to Chip

### ISSUE THREAD

**Issue by YajanaRao** [callstack/react-native-paper#1389]
## Describe the feature

Can we add size prop to Chip. 

## Motivation
To use Chip of different sizes if required.

**Comment by Trancever** [comment]
@YajanaRao What are you trying to achieve? Do you want to make whole Chip bigger, or only increase the font size?

**Comment by YajanaRao** [comment]
I want to make whole Chip bigger

**Comment by Trancever** [comment]
@YajanaRao Chip component accepts `style` and `textStyle` props. It should be possible to make it bigger using these two props.
