### ISSUE TITLE
Does Badges contain Icon ? 

### ISSUE THREAD

**Issue by YajanaRao** [callstack/react-native-paper#1390]
## Describe the feature

Can I use Badge to display Icons like done or cancel. 

## Motivation

I want to show selected items by using a badge on it. 
![WhatsApp Image 2019-10-15 at 9 27 19 PM](https://user-images.githubusercontent.com/38914337/66848413-aa200680-ef92-11e9-8f65-c49e7c9874ba.jpeg)

Or using a children like this. 
![image](https://user-images.githubusercontent.com/38914337/66848055-07678800-ef92-11e9-9755-66d5206214c3.png)

**Comment by Trancever** [comment]
@YajanaRao Badge component supports strings or numbers as children so it's not possible. However, you can create your own component based on Paper's badge that supports displaying icons inside.
