### ISSUE TITLE
RadioButton onPress doesn't get called on press.

### ISSUE THREAD

**Issue by katbusch** [callstack/react-native-paper#1391]
## Environment

At least not working on web and android

## Description

RadioButton onPress doesn't get called on press.

## Reproducible Demo

The [demo snack](https://snack.expo.io/?name=RadioButton&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fradio-button.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20View%20%7D%20from%20%27react-native%27%3B%0Aimport%20%7B%20RadioButton%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aexport%20default%20class%20MyComponent%20extends%20React.Component%20%7B%0A%20%20state%20%3D%20%7B%0A%20%20%20%20checked%3A%20%27first%27%2C%0A%20%20%7D%3B%0A%0A%20%20render()%20%7B%0A%20%20%20%20const%20%7B%20checked%20%7D%20%3D%20this.state%3B%0A%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3CView%3E%0A%20%20%20%20%20%20%20%20%3CRadioButton%0A%20%20%20%20%20%20%20%20%20%20value%3D%22first%22%0A%20%20%20%20%20%20%20%20%20%20status%3D%7Bchecked%20%3D%3D%3D%20%27first%27%20%3F%20%27checked%27%20%3A%20%27unchecked%27%7D%0A%20%20%20%20%20%20%20%20%20%20onPress%3D%7B()%20%3D%3E%20%7B%20this.setState(%7B%20checked%3A%20%27first%27%20%7D)%3B%20%7D%7D%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%20%20%3CRadioButton%0A%20%20%20%20%20%20%20%20%20%20value%3D%22second%22%0A%20%20%20%20%20%20%20%20%20%20status%3D%7Bchecked%20%3D%3D%3D%20%27second%27%20%3F%20%27checked%27%20%3A%20%27unchecked%27%7D%0A%20%20%20%20%20%20%20%20%20%20onPress%3D%7B()%20%3D%3E%20%7B%20this.setState(%7B%20checked%3A%20%27second%27%20%7D)%3B%20%7D%7D%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%3C%2FView%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D&dependencies=react-native-paper) included in React Native Paper documentation has this issue.

**Comment by Taym95** [comment]
Hey, you're using old version `2.16.0` and this issue was fixed [here](https://github.com/callstack/react-native-paper/pull/1359), you can upgrade `react-native-paper` version to latest and close this issue, thanks!
