### ISSUE TITLE
Text Field with Icon??

### ISSUE THREAD

**Issue by ElavanResu** [callstack/react-native-paper#1392]
## Is there a way to implement TextField with Icon?? Like the one in the image bellow
![Screen Shot 2019-10-16 at 10 04 39 AM](https://user-images.githubusercontent.com/33317917/66888528-95785880-effc-11e9-80be-1b4bd85e4fca.png)

**Comment by Trancever** [comment]
@ElavanResu There is no such option, but @jbinda is working on making this possible.
