### ISSUE TITLE
Using "padding" prop in TextInput gives an error

### ISSUE THREAD

**Issue by ElavanResu** [callstack/react-native-paper#1393]
## When I am using "padding" prop in TextInput, my app gives me an error as "Error in updating property 'padding' in shadow node of type: AndroidTextInput"

![IMG_20191016_161219](https://user-images.githubusercontent.com/33317917/66912645-9d51f000-f030-11e9-85d9-1c2f7003c1f2.jpg)
 

## Code
           <TextInput
              label='Email'
              value={''}
              style={{ backgroundColor: 'transparent' }}
              dense
              padding={'none'}
            />

**Comment by Trancever** [comment]
@venits Yes, you're right. However there is a PR that removes that prop and we are likely gonna merge it. https://github.com/callstack/react-native-paper/pull/1394
