### ISSUE TITLE
TextInput background transparent

### ISSUE THREAD

**Issue by poptocrack** [callstack/react-native-paper#1395]
## Ask your Question

I'm using TextInput on a gradient background, and I can't use the background transparent since it displays a line under the title.
I can't really put a fixed color since the exact color behind the input might change according to the screen size.

Here's the code 

```
<TextInput
  label="Email"
  mode="outlined"
  theme={{ colors: { background: 'transparent' } }}
/>
```
Here's what I got:
[TextInput](https://drive.google.com/file/d/16m8hRLQXGbbtlZpRt8KidYJqcALpxBf9/view?usp=sharing)

Is there any way to make this work?

**Comment by shiroze** [comment]
for me it work this way

```
const theme = {
  ...DarkTheme,
  roundness: 2,
  colors: {
    ...DarkTheme.colors,
    primary: '#3498db',
    accent: '#f1c40f',
    background: 'transparent'
  },
};
```

Change DarkTheme with DefaultTheme if using White.

**Comment by Trancever** [comment]
@poptocrack Can you provide a [Snack](https://snack.expo.io/) that reproduces your issue? You could also upload a screenshot so we can see that line under the title.
