### ISSUE TITLE
Snackbar dismiss timeout reset

### ISSUE THREAD

**Issue by aibekmamatov** [callstack/react-native-paper#1396]
## Is it right to reset `_hideTimeout` when children of snackbar changes?

I use one snackbar to display message of user action and when user does something snackbar become visible, then while it's visible user does another action that changes message.

I can't use multiple snackbars because it's message context is the same.

**Comment by Trancever** [comment]
@aibekmamatov What do you mean saying context is the same? You should be able to show two snackbars at the same time.
