### ISSUE TITLE
BottomNavigation barStyle backgroundColor ignored

### ISSUE THREAD

**Issue by jsamr** [callstack/react-native-paper#1397]
## Environment

- Android Emulator, Android API 28
- `react-native-paper@3.0.0-alpha.7`

```bash
$ react-native info
info Fetching system and libraries information...
System:
    OS: Linux 4.19 Manjaro Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz
    Memory: 683.50 MB / 31.33 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.11.1 - /usr/bin/node
    npm: 6.12.0 - /usr/bin/npm
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ~0.61.2 => 0.61.2

```

## Description

`barStyle.backgroundColor` prop is not applied to `BottomNavigation` bar.

The issue is reproducible in `react-native-paper@3.0.0-alpha.6` but not on `react-native-paper@3.0.0-alpha.5`.

## Reproducible Demo

[react-native-paper-bottom-navigation-bar-style-background-color-bug](https://github.com/jsamr/react-native-paper-bottom-navigation-bar-style-background-color-bug)

**Comment by pan-pawel** [comment]
ok i know what is wrong there, I will fix it today
