### ISSUE TITLE
Add ability to create nice front page for our docs

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#140]
We need to add support to write a page with a React component, so we can do a nice front page (web-like).

**Comment by ferrannp** [comment]
@satya164 makes a design.

**Comment by herbowicz** [comment]
Is there a chance to see the default theme in action? [The link](https://callstack.github.io/react-native-paper/blob/master/src/styles/DefaultTheme.js) doesn't seem to work. Thanks

**Comment by satya164** [comment]
You can try on Expo https://expo.io/@satya164/react-native-paper-example
