### ISSUE TITLE
[v3] Multiline input's text starts from vertical center

### ISSUE THREAD

**Issue by vkasraj** [callstack/react-native-paper#1403]
Same issue as #648 which was also resolved in #651. Earlier I raised this issue #1400 which was resolved in #1401. Using v3.0.0-alpha.8.

## Screen Shot
![Screenshot_20191021-210908](https://user-images.githubusercontent.com/24727447/67220692-de3e7000-f447-11e9-8fd2-de9aee9bcc17.jpg)

**Comment by venits** [comment]
Hi,

I created pull request for this issue :)

https://github.com/callstack/react-native-paper/pull/1408

It will be fixed in next release.

**Comment by vkasraj** [comment]
Closing Now. Issue fixed v3.1.0 release.
