### ISSUE TITLE
Jest tests are failing with react native paper 3.0.0

### ISSUE THREAD

**Issue by YajanaRao** [callstack/react-native-paper#1410]
## Environment
react-native-cli: 2.0.1
react-native: 0.61.2
react-native-paper: 3.0.0

Windows 10

## Description

After updating react native paper to 3.0.0 I am getting error with Jest tests.
![image](https://user-images.githubusercontent.com/38914337/67301564-355a4880-f50d-11e9-8b19-1a6b274b56f4.png)

## Reproducible Demo
Link to the repository:
https://github.com/YajanaRao/Serenity

**Comment by oshimayoan** [comment]
This is also happening on `react-native: 0.59.8` with Expo SDK 34.
