### ISSUE TITLE
HelperText is not exposing its properties correctly

### ISSUE THREAD

**Issue by lunks** [callstack/react-native-paper#1412]
## Environment

Using react-native-paper with 0.60.6
## Description

Although `HelperText` does have a `style?` property, it's not being exposed correctly. As such, other components that rely on them like `createAnimatableComponent` from `react-native-animatable`.
## Reproducible Demo
```typescript
const typeTest = (component: ComponentClass<{ style?: any }>) => {
  return component;
};

typeTest(HelperText);
```
Error is: 
```
Argument of type '(ComponentClass<Pick<Props, string | number | symbol> & { theme?: $DeepPartial<Theme> | undefined; }, any> & NonReactStatics<(ComponentClass<Props, any> & typeof HelperText) | (FunctionComponent<Props> & typeof HelperText), {}>) | (FunctionComponent<Pick<Props, string | number | symbol> & { theme?: $DeepPartial<Theme> | undefined; }> & NonReactStatics<(ComponentClass<Props, any> & typeof HelperText) | (FunctionComponent<Props> & typeof HelperText), {}>)' is not assignable to parameter of type '{ style?: any; }'. [E]
```

## Workaround

As a workaround, I'm just casting it to what I need: 

```typescript
const AnimatedErrorMessage = createAnimatableComponent(
  HelperText as ComponentClass<{ style?: any }>
);
```

**Comment by satya164** [comment]
In your reproducible demo, you are annotating `component` as `{ style?: any }` which means an object with `style` property. Ofc its failing cause `HelperText` is a component, not an object with a `style` property.

Don't think that's what's happening with `createAnimatableComponent`

**Comment by lunks** [comment]
Indeed I forgot to update the example. Is this clearer on what the issue is?

**Comment by Trancever** [comment]
The root of this issue is that all Animated components e.g. Text, View are typed as any. The best way to fix this issue is to fix the types for React-Native itself.
