### ISSUE TITLE
How to change borderRadius of Avatar.Image

### ISSUE THREAD

**Issue by halileohalilei** [callstack/react-native-paper#1418]
## Ask your Question

Is there a way to change the `borderRadius` of `Avatar.Image`? I set its style to `{ borderRadius: 0 }`, but that only changes the radius of the outer `View`, and the `Image` inside it is still round. Any way to do this?

**Comment by Trancever** [comment]
@halileohalilei Hey, this component is just a View and an Image inside. If you need different border radius you can implement it on your own. We do not support your use case because it's not MD Guidelines compliant.

**Comment by peterchibunna** [comment]
Hi @Trancever, we appreciate your feedback. However, as you mentioned, it is just a "guideline". Users must not be forced to do things certain way. Those guidelines are called guidelines for a reason. They are not laws. 

When I inspected the code for this, I see that it could have easily been extended to allow square (or even custom) borderRadius on the left Avatar. You also know that Google MD Guidelines change. Do you expect that each time Google updates their design then you update the library?

**Comment by Musigwa** [comment]
> Hi @Trancever, we appreciate your feedback. However, as you mentioned, it is just a "guideline". Users must not be forced to do things certain way. Those guidelines are called guidelines for a reason. They are not laws.
> 
> When I inspected the code for this, I see that it could have easily been extended to allow square (or even custom) borderRadius on the left Avatar. You also know that Google MD Guidelines change. Do you expect that each time Google updates their design then you update the library?
> 
> Anyway @halileohalilei, I was able to achieve the 'soft square'

Could you kindly, help me understand how I need to use 'soft square' to achieve the same results that you got?

**Comment by mashamcnyky** [comment]
> Hi @Trancever, we appreciate your feedback. However, as you mentioned, it is just a "guideline". Users must not be forced to do things certain way. Those guidelines are called guidelines for a reason. They are not laws.
> 
> When I inspected the code for this, I see that it could have easily been extended to allow square (or even custom) borderRadius on the left Avatar. You also know that Google MD Guidelines change. Do you expect that each time Google updates their design then you update the library?
> 
> Anyway @halileohalilei, I was able to achieve the 'soft square'

Same here - could you please post the style/code for the square?
