### ISSUE TITLE
Adding my app to "Showcase"

### ISSUE THREAD

**Issue by layerssss** [callstack/react-native-paper#1421]
## Ask your Question

Hello!

Thank you for the work on this library. I would like to introduce an App I just recently built using it: 

* landing page: https://racecalendar.app/
* AppStore: https://apps.apple.com/us/app/race-calendar/id1481539104
* Play: https://play.google.com/store/apps/details?id=in.micy.racecalendar

Would you like me to try to come up with a PR adding this to the Showcase page? I assume it's just adding an entry in https://github.com/callstack/react-native-paper/blob/master/docs/pages/src/Showcase.js

**Comment by Trancever** [comment]
@layerssss If your app uses paper, then sure. We are happy to accept your PR :)
