### ISSUE TITLE
[v3] Unable to resolve module `react-native-paper/src/core/Provider` from `src/App.js`

### ISSUE THREAD

**Issue by dacsang97** [callstack/react-native-paper#1427]
## Environment
```
react-native: 0.61.2
react-native-paper: 3.0.0
NODE_ENV: production
```
**I only occur this problem when I run build, not appear Development environment**
## Description

babel.config.js (**I'm not using TypeScript**)
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  env: {
    production: {
      plugins: ['react-native-paper/babel'],
    },
  },
}
```
import `Provider` in `App.js`
```
import { Provider as PaperProvider } from 'react-native-paper'
```

## Reproducible Demo

Run react-native bundle for Android
```
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
```
Then, I receive the error
![Screen Shot 2019-10-29 at 1 15 22 AM](https://user-images.githubusercontent.com/5728560/67705457-9be9d580-f9e9-11e9-866e-1c0b6cf7e98d.png)

I think babel has a problem with `typings`. Instead of, react-native bundle load `react-native-paper` from `lib`, it loaded from `src`, but we don't have `src` folder in the `react-native-paper` package inside `node_modules`.

**Comment by satya164** [comment]
Have you tried resetting metro cache like the error message says?

**Comment by dacsang97** [comment]
@satya164 yes, I had tried

**Comment by hamzakashifCL** [comment]
how did you resolve this issue?

**Comment by maximilianotaverna** [comment]
would be great to know how you resolved it..

**Comment by IsmailJanParacha** [comment]
@maximilianotaverna i fixed this issue using `npx react-native start --reset-cache`
