### ISSUE TITLE
Decrease Checkbox animation duration

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#143]
Try to match it to native Android where it is faster.

**Comment by satya164** [comment]
What should be the duration?

**Comment by ferrannp** [comment]
I don't have a number, we should compare it to native app. Or hey, we can use the native component (It is in RN repo).

**Comment by satya164** [comment]
> we can use the native component (It is in RN repo)

it's the stock OS one. it'll not be material themed on pre-lollipop.

**Comment by KrzysztofKarol** [comment]
I'm working on it.

**Comment by gawrysiak** [comment]
I have used AZ Screen Recorder for Android to look into it a bit deeper.

<img width="102" alt="screen shot 2018-04-03 at 22 09 04" src="https://user-images.githubusercontent.com/7827311/38273408-2729f7c8-378c-11e8-956a-a54778dd73da.png">First one is Android 6.0 - settings page. It takes ~0.4s to finish.

<img width="116" alt="screen shot 2018-04-03 at 22 09 41" src="https://user-images.githubusercontent.com/7827311/38273447-3a8e3004-378c-11e8-806d-6e982f7c2d4e.png">Somewhere in the middle (0.2s) the checkbox transition is over.

<img width="119" alt="screen shot 2018-04-03 at 22 09 59" src="https://user-images.githubusercontent.com/7827311/38273455-434d7fec-378c-11e8-9fbe-c90f840db6f4.png">Then it's still another 0.2s to finish the ripple effect and background color transition.

<img width="114" alt="screen shot 2018-04-03 at 22 11 24" src="https://user-images.githubusercontent.com/7827311/38273462-47dbcafa-378c-11e8-848c-6c31a25bb767.png">Second one is Paper inside the Expo app. It takes ~0.7s to finish.

<img width="113" alt="screen shot 2018-04-03 at 22 11 37" src="https://user-images.githubusercontent.com/7827311/38273467-4b419990-378c-11e8-98de-acd4b0dc1e68.png">The empty checkbox appeared a bit faster, but it takes some more time before it reaches the full size. The background & ripple effect goes darker than native.

<img width="114" alt="screen shot 2018-04-03 at 22 11 49" src="https://user-images.githubusercontent.com/7827311/38273472-4fc4ab6a-378c-11e8-929d-acd510326452.png">Somewhere in the middle (0.35s) the checkbox transition is over.

<img width="112" alt="screen shot 2018-04-03 at 22 12 04" src="https://user-images.githubusercontent.com/7827311/38273477-52beb04a-378c-11e8-8084-d11c53ff7fdd.png">For Paper it takes more time before the background goes back to the original color & ripple is gone completely.

**Comment by ferrannp** [comment]
Thanks @gawrysiak ! We'll try to use it :)

**Comment by Trancever** [comment]
Checkbox animation duration should be configurable with a `animation.scale` property from theme. 
It should be implemented in a same way as in [Menu](https://github.com/callstack/react-native-paper/blob/0a08a8b9ea687e1171e35b5933f017d8aa152fdf/src/components/Menu/Menu.tsx#L300)

**Comment by karthick1231** [comment]
When I click the checkbox it takes some delay to show the tick. how to stop the animation. my code is `<TouchableOpacity activeOpacity={0.6}  onPress={()=> this.toggleSelected(item)}>
                                        <View style={styles.row}>
                                            <View pointerEvents="none">
                                                <Checkbox
                                                    color={theme.colors.primary}
                                                    value="normal"
                                                    status={this.isExistInSelected(item) === -1 ? 'unchecked': 'checked'}
                                                />
                                            </View>
                                            <Subheading style={styles.text}>{item.name}</Subheading>
                                        </View>
                                    </TouchableOpacity>}`
