### ISSUE TITLE
[Docs] Add link to implementation for each component

### ISSUE THREAD

**Issue by m2mathew** [callstack/react-native-paper#1431]
Many projects will provide a link from the documentation to the source file in GitHub for each component. This provides a developer an easy way to jump into the documentation for a better understanding of how the component is implemented.

I use Material-UI all day everyday, and I click on a link to the source code several times a day. It's helpful! 😎 

My team created MUI, and we are starting to use RNP on a React Native project. I would be willing to jump in to add this to the docs, if the overseers approve of this feature. :bowtie: 

![image](https://user-images.githubusercontent.com/11624407/67797619-0cc3d880-fa50-11e9-94b5-b79730691207.png)

**Comment by MarkPollmann** [comment]
I think it's a great idea :+1:

**Comment by Trancever** [comment]
@satya164 It should be implemented in component-docs, right? We could add support for parsing some comment that points to the right file e.g. `/* sourcePath: './src/components/Menu.tsx'' */`

**Comment by Trancever** [comment]
@m2mathew Ok, so it looks like we already support this feature. There is a pencil icon in the top right corner that takes you to the github edit page for a component.

**Comment by m2mathew** [comment]
@Trancever The screenshot below is what I see when I click the "edit" pencil icon. It might be safe to assume that most visitors to the docs site have not forked the project.

![image](https://user-images.githubusercontent.com/11624407/71281913-4d3f2480-2324-11ea-8fb0-f18ee476d013.png)
