### ISSUE TITLE
PaperProvider theme doesn't work for release build on IOS

### ISSUE THREAD

**Issue by orcunorcun** [callstack/react-native-paper#1432]
For debug build it show my custom theme but for release it shows purple color instead of mine.

**Version:**
```
    "react": "16.8.1",
    "react-native": "0.61.3",
    "react-native-paper": "3.1.1",
```

**Code:**

```
import {DefaultTheme, Provider as PaperProvider} from 'react-native-paper';

const theme = {
  ...DefaultTheme,
  roundness: 7,
  dark: true,
  mode: 'adaptive',
  colors: {
    ...DefaultTheme.colors,
    primary: Colors.mantis,
    accent: Colors.nero,
  },
};

const logger = createLogger();
const persistedReducer = persistReducer(persistConfig, reducers);
const store = createStore(persistedReducer, {}, applyMiddleware(ReduxThunk, logger));
const persistor = persistStore(store);


const App = () => (
  <StoreProvider store={store}>
    <PersistGate persistor={persistor}>
      <PaperProvider theme={theme}>
        <App />
      </PaperProvider>
    </PersistGate>
  </StoreProvider>
);
```

**Comment by orcunorcun** [comment]
And also  `<Portal>` cause to crash on release build if I add

```
  env: {
    production: {
      plugins: ['react-native-paper/babel'],
    },
  },
```

to babel.config.js file

**Error message is:**

> 
> ** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: Looks like you forgot to wrap your root component with `Provider` component from `react-native-paper`.
> 
> Please read our getting-started guide and make sure you've followed all the required steps.
> 
> https://callstack.github.io/react-native-paper/getting-started.html
> 
> This error is located at:
>     in P
>     in RCTView
>     in p
>     in _
>     in c
>     in RCTView
>     in Portal.Host
>     in l
>     in b
>     in f
>     in R
>     in RCTView
>     in Unknown
>     in t
>     in Root
>     in RCTView
>     in h', reason: 'Unhandled JS Exception: Error: Looks like you forgot to wrap your root component with `Provider` component from `react-native-paper`.
> 
> Please read our getting-started guide an..., stack:
> value@849:952
> value@849:835
> Ri@108:57222
> Ui@108:57947
> Di@108:60917
> Fl@108:76347
> Fl@<null>:<null>
> unstable_runWithPriority@183:3915
> Dl@108:74615
> Dl@<null>:<null>
> Pl@108:65839
> Pl@<null>:<null>
> <unknown>@108:25495
> unstable_runWithPriority@183:3915
> sn@108:25442
> cn@108:25377
> _e@108:88686
> Ne@108:13582
> Ue@108:13755
> receiveTouches@108:14547
> value@41:3685
> <unknown>@41:841
> value@41:2939
> value@41:813
> value@<null>:<null>
> '
> *** First throw call stack:
> (0x1b6b8a3a8 0x1b5d8fd00 0x1003395e4 0x1003ab750 0x1b6b91d04 0x1b6a6dea8 0x1b6a6eb2c 0x10036c018 0x10036e128 0x10036de8c 0x1009af1f8 0x1009b0778 0x1009b8a34 0x1009b973c 0x1009c3474 0x1b6794a98 0x1b679adc4)

**Comment by bjjeong** [comment]
Same here. Doesn't work on 3.1.1 or 3.1.0. I had to go down to 3.0.0 in order for my app to run in release build.

**Comment by jaysbytes** [comment]
It might be caused by this commit https://github.com/callstack/react-native-paper/commit/9b74d21709d430708d3f41723beb388f856c206e

Probably mappings are generated incorrectly and some parts of source code are not available when you use babel plugin. But It's only my guess, someone needs to check that.

**Comment by kevinsoellner** [comment]
> Same here for iOS and Android. Doesn't work on `3.1.1` or `3.1.0`. I had to go down to `3.0.0` in order for my app to run in release build.

Same issue here. I tried to go down to `3.0.0` but it's still crashing on start. 
Any news on this?

**Comment by satya164** [comment]
@kevinsoellner try resetting metro cache: `react-native start --reset-cache` or `expo start -c` if using expo

**Comment by KjellConnelly** [comment]
Has this been fixed? I'm getting the same error when I build for release via Xcode:
```Objective-C
Invariant Violation: Native module cannot be null.

This error is located at:
    in l
    in c
    in RCTView
    in Portal.Host
    in n
    in RCTView
    in n
    in RCTView
    in RCTView
    in h
```

I just updated to the latest npm version and tried pod install again. Still getting the same error message even after resetting cache.
