### ISSUE TITLE
Menu.Item Custom MaxWidth

### ISSUE THREAD

**Issue by karvulf** [callstack/react-native-paper#1439]
## Describe the feature

I'm trying to build my own Dropdown-Menu. For that I use the Menu-Component. My problem is that the Menu.Item has a maxWidth of 280. So the touchable area of my items are wrong if my Dropdown-Menu is larger.

## Motivation

Give the possibility to set the maxWidth.

**Comment by karvulf** [comment]
In the newest version, it works, so im closing this issue

**Comment by michan85** [comment]
for anyone else who stumbles on this issue, it is hardcoded in the dropdown file:
https://github.com/callstack/react-native-paper/blob/main/src/components/Menu/MenuItem.tsx#L144

but this code can unset it:
```ts
 <Menu.Item
        titleStyle={selected ? styles.selectedTitle : null}
        title={label}
        key={value}
        style={{
          maxWidth:undefined,
          ...style,
          ...(selected ? styles.selectedItem : null),
        }}
        contentStyle={{
          maxWidth:undefined
        }}
        onPress={onSelect}
      />
```

but be aware if you use an icon you will need to cater for it
