### ISSUE TITLE
How to hide dialog backdrop?

### ISSUE THREAD

**Issue by ahce** [callstack/react-native-paper#1445]
I tried this, but didn't work.
```
        <Dialog
          theme={{
            colors: {
              backdrop: 'transparent'
            }
          }}
        />
```

**Comment by savagematt** [comment]
I don't know why your example doesn't work, but I do know that this does:

```tsx
<PaperProvider theme={{colors: {backdrop: 'transparent'}}}>
   <Dialog/>
</PaperProvider>
```

**Comment by MarkPollmann** [comment]
From how I understand it a `Dialog` renders a `Modal` under the hood. The `Modal` looks for a theme prop, the `Dialog` doesn't hand it down to the `Modal`, though.  So it gets the theme from the theme provider like usual.
