### ISSUE TITLE
How to change the opacity of the disabled button?

### ISSUE THREAD

**Issue by jasonkw9** [callstack/react-native-paper#1446]
Hi all, may I know how to change the opacity of a button when it is in disabled mode. I have attached an image below. As you can see in the screenshot, the button is nearly visible.

![Screenshot_20191104_192056_com abc_members_app](https://user-images.githubusercontent.com/18546855/68117543-9ab02f80-ff38-11e9-92f3-aaa755470b94.jpg)

**Comment by Trancever** [comment]
@jasonkw9 Can you provide a [Snack](https://snack.expo.io/) showing how you use the button? It shouldn't look like that by default.
