### ISSUE TITLE
How can I make label always visible in BottomNavigation ?

### ISSUE THREAD

**Issue by Priyam-tricon** [callstack/react-native-paper#1447]
## Ask your Question
I want to make all the labels in BottomNavigation to be visible not just the selected one.
How can I achieve that ?

**Comment by satya164** [comment]
https://callstack.github.io/react-native-paper/bottom-navigation.html#labeled

**Comment by Priyam-tricon** [comment]
Hi,

My question was about showing **all the labels**  not about showing/hiding the label of the active tab.

I figured it out. The solution was using shifting actually.
https://callstack.github.io/react-native-paper/bottom-navigation.html#shifting

**Comment by zcmgyu** [comment]
Same question here
