### ISSUE TITLE
ActivityIndicator bug with react-native LayoutAnimation

### ISSUE THREAD

**Issue by camogg** [callstack/react-native-paper#1451]
## Environment

- Expo SDK v35.0.0
- React Native Paper v3.1.1
- Running in iPhone XS iOS 13.2

## Description

I am experiencing a bug trying to make disappear ActivityIndicator with EaseOut presets of LayoutAnimation. The ActivityIndicator shows a double bar when animation is in progress. Looks like ActivityIndicator spinning animation just stop while another animation is performed on it.

Here's a demo of the issue:
![ezgif-2-ef6f4282b69d](https://user-images.githubusercontent.com/3686870/68217804-ed96ef00-ffeb-11e9-8a9a-d6d8b24e2218.gif)

**Comment by satya164** [comment]
`LayoutAnimation` works by animating any components that updated, which might result in unintended glitches. I'd suggest to avoid using it and use https://github.com/kmagiera/react-native-reanimated
