### ISSUE TITLE
Type error using useRef hook with TextInput

### ISSUE THREAD

**Issue by Alain00** [callstack/react-native-paper#1453]
When i use the hook ```useRef<TextInput>(null)``` this gives me this type error ```'TextInput' refers to a value, but is being used as a type here```. And the same when i use ```React.forwardRef<TextInput, MyProps>```. This does't happend with the RN TextInput

**Comment by Trancever** [comment]
try `typeof TextInput`

**Comment by Alain00** [comment]
Thanks @Trancever it works, but now I get the following error by assigning the ref:

```
Type 'Ref<(ComponentClass<Pick<TextInputProps, "ref" | "label" | "style" | "allowFontScaling" | "autoCapitalize" | "autoCorrect" | "autoFocus" | "blurOnSubmit" | "caretHidden" | "contextMenuHidden" | ... 99 more ... | "dense"> & { ...; }, any> & NonReactStatics<...>) | (FunctionComponent<...> & NonReactStatics<...>)>' is not assignable to type 'Ref<TextInput>'.
```

This is the code:

```
const MyInput = withTheme(React.forwardRef<typeof TextInput, MyInputProps>(({label, ...props}, ref) => {
    return (
        <TextInput
            {...props}
            ref={ref}
            label={label}/>
    )
}))
```

**Comment by sangdth** [comment]
I still have this problem.
@Alain00 , have you overcome this problem?

**Comment by Alain00** [comment]
No @sangdth, I just avoid it using the `any` type

**Comment by salockhart** [comment]
I am seeing this issue was well on version 3.8.0

**Comment by Nohac** [comment]
Same issue on version `4.0.0-alpha.0`

**Comment by lafiosca** [comment]
I have not yet verified this solution by testing the app, but it seems to me that the ref attribute is referring to the React Native TextInput type rather than the react-native-paper type. Specifically, this clears up the ts errors for me:

```
import { TextInput as RNTextInput } from 'react-native';
import { TextInput } from 'react-native-paper';
```

```
const fieldRef = useRef<RNTextInput>(null);

const focusField = useCallback(
	() => {
		fieldRef.current?.focus();
	},
	[],
);
```

```
<TextInput
	ref={fieldRef}
	[...]
>
```

Again, this is hot off the presses from my code, in the middle of a large refactor, and I'm not able to verify the functionality yet.

**Comment by gluons** [comment]
I also face this problem. Importing double `TextInput` is uncomfortable.  
Is it possible to get this problem resolved in the future?

**Comment by lafiosca** [comment]
I believe importing the two separate types is the only resolution, at least without a breaking change to the library. The react-native-paper `TextInput` is exposing a ref to the underlying react-native `TextInput`, so they are two different types. It's possible that react-native-paper could create and use their own type for the ref, but if they're not augmenting the underlying methods that is just extra work for no great benefit.

**Comment by ashuvssut** [comment]
I faced no issue in using useRef hook with TextInput
```ts
import { TextInput as RNTextInput } from "react-native";
import { TextInput } from "react-native-paper";
```

**Comment by ashuvssut** [comment]
I faced no issue in using useRef hook with TextInput
```ts
import { TextInput as RNTextInput } from "react-native";
import { TextInput } from "react-native-paper";

export const MyCompo = () => {
  const barRef = useRef<RNTextInput | null>(null);
  return(
    <TextInput
      ref={barRef}
      placeholder="Where to?"
    />    
  )
}
```
