### ISSUE TITLE
Menu crashes on the second open

### ISSUE THREAD

**Issue by rolandjitsu** [callstack/react-native-paper#1455]
## Environment

Running a react-native app on a Pixel 3 with the latest Android version.

## Description

It seems like every 2nd open of a `<Menu>` triggers some error. This is happening after `3.0.0-alpha.4`. I think it might have been introduced with https://github.com/callstack/react-native-paper/commit/fa22a68.
Might be related to https://github.com/callstack/react-native-paper/issues/1329.

![error](https://user-images.githubusercontent.com/1479737/68271951-2fcc3900-009d-11ea-9927-f8a7578bbb24.png)

## Reproducible Demo

Made a simple [snack](https://snack.expo.io/@rolandjitsu/menu-bug-on-android-10), but this is more or less the component I'm rendering the menu in:
```js
import React, {
  useCallback,
  useMemo,
  useState
} from 'react';
import {
  ScrollView,
  StyleSheet,
  Vibration,
  View
} from 'react-native';
import {SafeAreaView} from 'react-navigation';
import {
  Appbar,
  Divider,
  Menu,
  Provider
} from 'react-native-paper';

export default function MyComp() {
  const [menuVisible, setMenuVisible] = useState(false);
  const hideMenu = useCallback(() => setMenuVisible(false), [setMenuVisible]);
  const showMenu = useCallback(() => setMenuVisible(true), [setMenuVisible]);
  const menuAnchor = useMemo(() => (
    <Appbar.Action
      onPress={showMenu}
      icon="dots-vertical"
    />
  ), []);

  return (
    <SafeAreaView>
      <Provider>
       <Appbar.Header>
         <Appbar.Content
            title="Title"
            subtitle="Subtitle"
          />
          <Menu
            visible={menuVisible}
            onDismiss={hideMenu}
            anchor={menuAnchor}
          >
            <Menu.Item onPress={hideMenu} title="Item 1" />
            <Menu.Item onPress={hideMenu} title="Item 2" />
            <Divider />
            <Menu.Item
              // onPress={() => {}}
              title="Logout"
              icon="logout"
            />
          </Menu>
        </Appbar.Header>
      </Provider>
    </SafeAreaView>
  );
}
```

**Comment by solace** [comment]
I'm experiencing this issue, so installed 3.0.0-alpha.4, but now get `Cannot find module '../../dist/mappings.json'` which is mentioned in #1302 that is fixed in 3.0.0-alpha.5.

Any suggestions on a workaround for either?

**Comment by satya164** [comment]
The current stable version is 3.2.1

**Comment by solace** [comment]
@satya164 Yes, but as indicated by OP, it crashes on second tap. alpha.4 is the last version where it works as expected.

**Comment by Excalimbinhu** [comment]
Same for me. It also render realy wierd.
![MenuPaper](https://user-images.githubusercontent.com/58036407/69342874-376a1100-0c4b-11ea-8c0d-8c9a2204ff99.png)

I'm using:

- react-native: 0.59.9

- react-native-paper: 3.2.1

**Comment by SwitiSM** [comment]
Any solution for this !?

**Comment by solace** [comment]
@SwitiSM Updated to most recent version of react-native-paper and replaced the menu with react-native-material-menu.

**Comment by SwitiSM** [comment]
@solace thank you

**Comment by rolandjitsu** [comment]
This is still a valid issue.

**Comment by Trancever** [comment]
@rolandjitsu What is a Paper version and android version on which you can reproduce the issue? Could you provide us a [Snack](https://snack.expo.io/) so we can easily test it?

**Comment by Nitheeshsalian** [comment]
"react-native-paper": "3.3.0"

**Comment by Subway19** [comment]
This is still an issue.
App works on debug mode but crashes on production
"react-native-paper": "^3.1.0"

**Comment by AlfonsoCerrato** [comment]
It still happens for me at the first menu dismiss.

`"react-native": "^0.59.9", 
"react-native-paper": "^3.8.0"`

Crashes on production.

**Comment by LRNZ09** [comment]
This is still a problem with `4.0.1`, causing the same error as OP
