### ISSUE TITLE
Icons not rendering correctly

### ISSUE THREAD

**Issue by enthussb** [callstack/react-native-paper#1458]
## Environment
react-native-cli: 2.0.1
react-native: 0.61.4
react-native-paper: 3.2.1
VSCode
Windows 10

### Warning: failed prop type invalid prop name of value supplied to icon
![screenshot](https://user-images.githubusercontent.com/29205181/68399666-c4699080-019c-11ea-82ca-c44981b38a7d.png)

## Reproducible Demo
```
<Appbar.Header>
          <Appbar.Action icon="menu" />
          <Appbar.Content title="ReactApp" />
          <Appbar.Action icon="search" />
          <Appbar.Action icon="more-vert" />
</Appbar.Header>
```

**Comment by oskrd** [comment]
@enthussb Did you solve this?

**Comment by enthussb** [comment]
Yes I solved it.

**Comment by jcarloTA** [comment]
@enthussb  how did you do it?

**Comment by enthussb** [comment]
> @enthussb how did you do it?
- First of all, if you are getting a **question mark** then the issue is due to **incorrect** name of the icon. Refer [https://oblador.github.io/react-native-vector-icons/](https://oblador.github.io/react-native-vector-icons/) for the names of different icon packs that you are using.

- If you are getting symbol like ☒ then add the following line of code `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"` in `android/app/build.gradle`. It seems like a linking issue so when you add that line and build again you will see the icons to be rendered perfectly.

**Comment by mersimoski** [comment]
> > @enthussb how did you do it?
> 
> * First of all, if you are getting a **question mark** then the issue is due to **incorrect** name of the icon. Refer https://oblador.github.io/react-native-vector-icons/ for the names of different icon packs that you are using.
> * If you are getting symbol like ☒ then add the following line of code `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"` in `android/app/build.gradle`. It seems like a linking issue so when you add that line and build again you will see the icons to be rendered perfectly.


Thanks boss
