### ISSUE TITLE
Fonts Theme not working for Search Bar

### ISSUE THREAD

**Issue by wardjk87** [callstack/react-native-paper#1459]
## Environment

Expo 35 SDK
React-Native-Paper 3.2.1

## Description

When setting a theme font, the SearchBar components gets the following error:

ExceptionsManager.js:82 Warning: Failed prop type: Invalid props.style key `0` supplied to `Text`.
Bad object: {
  "0": "R",
  "1": "o",
  "2": "b",
  "3": "o",
  "4": "t",
  "5": "o",
  "color": "rgba(0, 0, 0, 0.54)",
  "textAlign": "left",
  "fontSize": 14,
  "paddingTop": 4,
  "fontFamily": "Roboto-Light"
}

Following is the theme: 
const theme = {
  ...DefaultTheme,
  fonts: {
    bold: 'Roboto-Bold',
    light: 'Roboto-Light',
    medium: 'Roboto-Medium',
    regular: 'Roboto',
    thin: 'Roboto-Thin',
  },
};

Apparently the theme font is being incorrectly applied. This was not an issue prior to upgrading to version 3.0

**Comment by satya164** [comment]
Please read the release notes https://github.com/callstack/react-native-paper/releases/tag/v3.0.0

**Comment by wardjk87** [comment]
@satya164 I don't see anything in release notes about this. The official docs on icons state that it uses react-native-vector-icons.

**Comment by wardjk87** [comment]
@satya164 is the migration guide posted on the official docs? It would help others like me migrate.

**Comment by Trancever** [comment]
@wardjk87 Sorry but we forgot to include notes about fonts in the release notes/migration guide. We will try to fix it as soon as possible.

**Comment by wardjk87** [comment]
@Trancever thanks for looking into this although the ticket was closed. I ended up just commenting the code and adding the styles directly.

I'm glad the team is with Typescript now. I have another question, I've modified the source code here and there before and used 2.0 code for reference. Now however, it is harder to find the source code in the node_modules/react-native-paper for specific elements. When I look and find the code it doesn't look like what I expect. For example: react-native-paper/lib/module/components/SearchBar files.Can you explain what you all did? 

Also is there a way to debug the react-native-paper code when it runs inside my application? It gets minified so it makes it difficult. I wanted to debug this specific issue.
