### ISSUE TITLE
Missing Material Icons in ver 3

### ISSUE THREAD

**Issue by wardjk87** [callstack/react-native-paper#1460]
## Environment

React-Native-Paper 3.2.1.

## Description

Certain MaterialIcons currently available through react-native-vector-icons are no longer available through React-Native-Paper that were available in version 2.0. 

For example: 'add', 'notifications', and 'language'.

Workaround: Using @expo/vector-icons and extracting MaterialIcons from there instead.

**Comment by satya164** [comment]
Please read the release notes https://github.com/callstack/react-native-paper/releases/tag/v3.0.0

**Comment by wardjk87** [comment]
@satya164 I went to the link and I could not find any information on this issue.

**Comment by Trancever** [comment]
@wardjk87 You can still use MaterialIcons via `settings` prop on `Provider`. It's explained in migration guide

**Comment by wardjk87** [comment]
@Trancever thanks for commenting after this ticket was closed. I'll try that.
