### ISSUE TITLE
Change the font size and font Weight of the label text

### ISSUE THREAD

**Issue by DevanshaniR** [callstack/react-native-paper#1464]
When change the font size & font weight to bold in **TextInput** label text also getting bold & also increasing the font size. How to change the font weight & font size of the floating label text only?

**Comment by jaskeerat789** [comment]
i would suggest you to use [react-native-material-textfield
](https://www.npmjs.com/package/react-native-material-textfield), they have a very good docs and provide a good set of customizable options

**Comment by Trancever** [comment]
@DevanshaniR There is no way. You can pass style prop to the textInput but it will affect both text and label.

**Comment by Return-1** [comment]
> @DevanshaniR There is no way. You can pass style prop to the textInput but it will affect both text and label.

I suggest we reopen this, we too opted in for react-native-material-textfield because of this as our designs were in need of such functionality.

**Comment by pallavkarya** [comment]
Hi any solutions ? want to change label fontweight and label text size

**Comment by freakk101** [comment]
Any update on this ?

**Comment by nlaffey** [comment]
One solution I found to this is to use the `render` property to render a TextInput imported from 'react-native'. You can pass on the inputProps and then modify the styles to inject the TextInput specific styles. 


```
    render={(inputProps) => (
            <RnTextInput
              {...inputProps}
              style={inputProps.style.concat({ fontWeight: "600" })}
            />
          )}
```
