### ISSUE TITLE
Apply animation.scale to checkbox.android

### ISSUE THREAD

**Issue by msageryd** [callstack/react-native-paper#1467]
The checkbox animation speed on checkbox.android does not care about the new animation.scale theme setting.

To me it's annoyingly slow, so I would love if the animation scale were applied to it.

**Comment by Trancever** [comment]
@msageryd Can you submit a PR?

**Comment by msageryd** [comment]
Yes, that’s the right thing to do. I don’t have the time right now, so I posted the issue as a todo-post for myself or anyone else.

On 12 Nov 2019, at 18:26, Dawid Urbaniak <notifications@github.com<mailto:notifications@github.com>> wrote:


@msageryd<https://github.com/msageryd> Can you submit a PR?
