### ISSUE TITLE
What is mappings.json doing inside the lib folder

### ISSUE THREAD

**Issue by gbhasha** [callstack/react-native-paper#1469]
## Ask your Question

I am working on a react-native component library project which is similar to react-native-paper and I am using bob to create the package.

I see the script './scripts/generate-mappings.js' which generates the mappings.json inside the lib folder. (after running the prepare command).

I am curious to know the purpose of having the mappings.json inside the lib folder.

Thanks in advance.

**Comment by jaysbytes** [comment]
Hi @gbhasha . Mappings are generated to be used by paper's babel plugin https://github.com/callstack/react-native-paper/tree/master/src/babel. Babel plugin change imports like `import { Button } from 'react-native-paper` to `import Button from 'react-native-paper/lib/components/Button.tsx` (not sure if path in example is correct, but you got the idea).
It changes imports to avoid including whole paper code into the app's release JS bundle.  
In `mappings.json` you can find mappings of components imports to their implementation path inside paper's lib folder.
