### ISSUE TITLE
Material Community List.Icon styling

### ISSUE THREAD

**Issue by Peechiz** [callstack/react-native-paper#1470]
## Ask your Question

Importing an icon outside of the standard set results in wildly different styles.
```
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';

...

<List.Item
  title="Logout"
  left={ props =>
    <Icon {...props} name="exit-to-app"/>
  }
/>
```
looks different from 
```
<List.Item
  title="Leave Feedback"
  left={ props => <List.Icon {...props} icon="thumbs-up-down"/> }
/>
```

How do I apply the default `List.Icon` styling to the materialcommunity icon?  Wouldn't it be easier to pass a prop to `List.Icon` like `<List.Icon iconFamily='materialCommunity' />` ?

**Comment by YajanaRao** [comment]
@Peechiz  in React native paper 3.0 Material community Icons are used. If you want to use other icons than MaterialCommunityIcons please refer this documentation 

https://callstack.github.io/react-native-paper/icons.html

**Comment by satya164** [comment]
The `icon` prop accepts a lot more than strings as per the docs linked above. You can provide your own render callback to `List.Icon` to keep styling.
