### ISSUE TITLE
Surface Component color and useTheme surface variable color are different in dark mode

### ISSUE THREAD

**Issue by YajanaRao** [callstack/react-native-paper#1472]
## Environment

react-native-paper 3.1.1
react-native 0.61.2

## Description

I am trying to get the surface component color using useTheme. The color of surface returned from useTheme and Surface Component are different. I am getting background color as surface color in theme. 

In Default theme I am not facing the above issue.
## Reproducible Demo

Link to the Snack
https://snack.expo.io/@yajana/surface-color

**Comment by Trancever** [comment]
https://github.com/callstack/react-native-paper/blob/e5cd6fb6029396f35c7a6ca0f6ded2bb6526b64b/src/components/Surface.tsx#L74

In dark theme, if mode is `adaptive` we adds some opacity to the surface color (based on elevation) that's why you see two different values. It is explained in [documentation](https://callstack.github.io/react-native-paper/theming.html#dark-theme)

**Comment by YajanaRao** [comment]
@Trancever  Thank you for the response. 
How Can I get the surface color ?

**Comment by Trancever** [comment]
You would have to get access to the overlay function but it's not exported currently and we are not sure if it should be. We need to investigate it more.

However, if you pass `mode: 'exact'` in your theme, you will be able to access right color.

**Comment by YajanaRao** [comment]
@Trancever I am coloring react navigation headers and tab bars using theme color. I would be nice if I get overlay function instead of implementing.

**Comment by Trancever** [comment]
@YajanaRao Can you provide some code sample explaining your second sentence. That would be helpful, because  I am not sure I understand you correctly.

**Comment by satya164** [comment]
@YajanaRao why not just use `Surface` component to wrap your component? seems easier than doing all of that yourself
