### ISSUE TITLE
Consider making List.Item a PureComponent

### ISSUE THREAD

**Issue by DottieDot** [callstack/react-native-paper#1473]
## Describe the feature

Consider making `List.Item` a PureComponent instead of a regular Component.

## Motivation

Having 100's of unchanged list items update every time you add something to your list makes your app extremely laggy.

**Comment by satya164** [comment]
Making things pure component will cause unexpected behaviour. For example:

```
_renderItem = () => this.state.foo;

render() {
  return <MyComponent someProp={this._renderItem} />
}
```

If `this.state.foo` updates, `MyComponent` won't re-render. You can wrap it in `PureComponent` yourself to optimize it.
