### ISSUE TITLE
Add typescript typings for Icon names.

### ISSUE THREAD

**Issue by nandorojo** [callstack/react-native-paper#1475]
## Describe the feature

Big fan of this awesome library. This is a small suggestion.

If you give an icon an invalid name, you get an error telling you all of the available icon names:

```es6
<Button icon="some-inexistent-name"></Button>

// Invalid prop `name` of value `some-inexistent-name` supplied to `Icon`
```

![Screen Shot 2019-11-14 at 9 19 30 PM](https://user-images.githubusercontent.com/13172299/68911893-787e9480-0724-11ea-922d-459de727866e.png)

It would be useful if the `icon` prop had Typescript suggestions with the available names.

Also, in the error message, it would be useful to add a link to a website that has the available icon names.

## Motivation

It's hard to know which icon types are usable while coding. Also, the error message is long, so it slows the logs down a little.

**Comment by jaysbytes** [comment]
It's currently impossible to statically type icon name since the actual Icon component is defined in runtime. The best way you can achieve it now is to override types for a particular paper component, assuming that you have a list of all icon names. Paper uses `material-vector-icons` by default.

```ts
// MyIconButton.ts
import { IconButton } from 'react-native-paper'

type IconButtonProps = React.ComponentProps<typeof IconButton> & { icon : 'icon1' | 'icon2' | ...}

export default IconButton as React.ComponentType<IconButtonProps>

```

**Comment by jaysbytes** [comment]
Could you please add a comment in this thread regarding the typing icon prop? https://github.com/callstack/react-native-paper/issues/1489
Then we could try to find a solution for that in 4.0

**Comment by nandorojo** [comment]
Definitely! Thanks for your attention here.
