### ISSUE TITLE
DatePicker component from Material Design

### ISSUE THREAD

**Issue by srodney86** [callstack/react-native-paper#1476]
Are there any plans to implement the DatePicker component as described in https://material.io/components/pickers/#specs

## Describe the feature

Input field which when clicked opens calendar as described in the spec.

## Motivation

Would complement the other React Native Paper components well

https://github.com/callstack/react-native-paper/issues/1048

Many thanks for the continued development as I am really enjoying using this package.

**Comment by satya164** [comment]
You should use https://github.com/react-native-community/react-native-datetimepicker

**Comment by RichardLindhout** [comment]
I'm working on this in a separate package https://github.com/web-ridge/react-native-paper-dates
