### ISSUE TITLE
Snackbar not comes to end of the page

### ISSUE THREAD

**Issue by mreorhan** [callstack/react-native-paper#1478]
## Ask your Question
I tried everything about that. But thats not happened.

![test](https://user-images.githubusercontent.com/17215194/69007071-f53e8800-0949-11ea-89b1-0ce2ca518a62.PNG)

**Comment by Trancever** [comment]
@mreorhan Looks like you don't wrap snackbar with Portal and view containing snackbar is not expanded  to the bottom of the screen.

Make sure the view containing snackbar is as big as screen is or just use Portal.
