### ISSUE TITLE
Can't edit TextInput with functional component and useState 

### ISSUE THREAD

**Issue by vedmant** [callstack/react-native-paper#1480]
Hi, I tried to replace my TextField from react-native-material-textfield with TextInput from this package and it's not working properly. My component is a functional component with useState for form state, it worked normally with other text input. Here is Snack link https://snack.expo.io/H1GrKS13H

## Environment

On Snack

## Description

Here is Snack link https://snack.expo.io/H1GrKS13H

## Reproducible Demo

https://snack.expo.io/H1GrKS13H

**Comment by satya164** [comment]
You're mutating the state on update which makes React skip re-rendering. Use spread operator instead of `Object.assign`

**Comment by vedmant** [comment]
Thanks, my bad, weird that it worked fine with "react-native-material-textfield".
