### ISSUE TITLE
[Web] Switch trackColor is white when disabled. 

### ISSUE THREAD

**Issue by lovetofail** [callstack/react-native-paper#1481]
![7rhVGOmgXC](https://user-images.githubusercontent.com/4531542/69035820-35a31200-09ed-11ea-8c45-88fe953355e6.gif)

## Environment
react-native-web"
"react-native-paper": "3.2.1"

## Description
Switch, when disabled, has trackColor white.

## Reproducible Demo
https://snack.expo.io/@lovetofail/switch-trackcolor-issue

**Comment by satya164** [comment]
Hey, seems like this is an issue in React Native web, not necessarily in Paper.

**Comment by lovetofail** [comment]
Ok. It's just that I've tried import `{ Switch } from 'react-native';` at it looked ok. So I thought the issue happens only in Paper.

**Comment by vedadeepta** [comment]
They're using the old api for `Switch`. Fix it with `trackColor: DISABLED_TRACK_COLOR` prop.
