### ISSUE TITLE
TextInput's placeholder is not being displayed initially with multiline set to true on iOS

### ISSUE THREAD

**Issue by ImTheC** [callstack/react-native-paper#1483]
### Current behaviour

On iOS, when using <TextInput/>, if multiline is true and label and placeholder both have a value, the placeholder is not displayed when you click on the input filed. If you type something in, selected it all, and delete it, then the placeholder is displayed and works as expected.

### Expected behaviour

The placeholder should be displayed after clicking on the input field.

### Code sample

https://snack.expo.io/S1_Ags-nB

### Screenshots (if applicable)

N/A

### What have you tried

At first I was passing in the values with props, so I tried setting them directly as strings, but it didn't seem to matter either way.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.60.5
| react-native-paper    |  3.1.1
| node                  | 11.15.0
| npm or yarn           | npm
| expo sdk              | 35.0.0

**Comment by Trancever** [comment]
@ImTheC Can you check if it still occurs in paper v3.3.0?

**Comment by kotavy** [comment]
@Trancever This behavior still exists as of v3.5.1, running the [TextInput example](https://callstack.github.io/react-native-paper/text-input.html#placeholder) on Snack and only adding multiline and a placeholder string. Placeholder works as expected without multiline.

**Comment by jeffjvick** [comment]
We are experiencing the same issue on iOS.  Paper v 3.6.0

If you enter two lines of text into the text input and then erase them, then you will see the placeholder.  See the video for an example of this behavior.

![RNP_multiline_textinput_placeholder](https://user-images.githubusercontent.com/203289/75285085-cfd3dc80-57ca-11ea-985a-e7b7e559a124.gif)

**Comment by ovbm** [comment]
Having this same issue. Was anyone able to resolve it?

**Comment by kotavy** [comment]
@ovbm My team has not prioritized finding a workaround, but I can confirm the issue remains. I tested again using the example Snack, running 3.10.1.

**Comment by Biciato** [comment]
Still present

**Comment by JulienRst** [comment]
We might want to re-open this issues as it still occurs ?

**Comment by enagorny** [comment]
This is still the issue in latest version

**Comment by yhbyOff** [comment]
+1

**Comment by blixit** [comment]
Still having this issue

**Comment by angel-venchev-toptal** [comment]
I am having the same issue

**Comment by HassanHaiderIX** [comment]
in IOS build I am facing same issue Placeholder is missing, can some one help me?

**Comment by wennaspeedy** [comment]
Is there any way to always show placeholder?

**Comment by HassanHaiderIX** [comment]
what I found out that turning off dark mode  will resolve this issue.

**Comment by neilgamb** [comment]
still an issue... not in dark mode

**Comment by dylanrandle** [comment]
This is still an issue. Please re-open.

**Comment by dylanrandle** [comment]
Created a new issue #3138: https://github.com/callstack/react-native-paper/issues/3138.

**Comment by mehdinourollah** [comment]
` "react-native-paper": "^4.12.3"` still have this issue on iOS

**Comment by benasdom** [comment]
add this as a prop to fix the issue <TextInput  placeholderTextColor={"grey"}/>
