### ISSUE TITLE
Snackbar component to allow arbitrary react nodes as children

### ISSUE THREAD

**Issue by ctbucha** [callstack/react-native-paper#1486]
## Describe the feature

Snackbar component allows arbitrary react node as children.

## Motivation

I would like to add an icon to the Snackbar component before the text. E.g. I want to do something like this:

```
<Snackbar
  style={{
    backgroundColor: theme.colors.warning,
  }}
  visible={errorMessage}
  onDismiss={() => setErrorMessage(null)}
>
  <View style={{ flexDirection: 'row' }} >
    <Avatar.Icon size={24} icon="alert-circle" />
    <Paragraph>{errorMessage}</Paragraph>
  </View>
</Snackbar>
```

The current implementation of the Snackbar component wraps the children in a Text component, so the only valid type of child for a Snackbar component is a string.

## Related Issues

N/a

**Comment by Trancever** [comment]
@ctbucha It's against MD Guideliness https://material.io/components/snackbars/#anatomy

<img width="889" alt="Screenshot 2019-11-21 at 11 55 08" src="https://user-images.githubusercontent.com/18584155/69331885-d267e880-0c55-11ea-8f6e-1a606da1374f.png">
