### ISSUE TITLE
Change the BorderRadis of Outlined TextField 

### ISSUE THREAD

**Issue by jaskeerat789** [callstack/react-native-paper#1487]
## Ask your Question

I need help in customize the borderRadius of outlined textInput. I cant find where to add the appropriate styling.
i have tried styling the TextInput through the prop `style={{ borderRadius:20 }}` but is of no help.

**Comment by LuckyLuke19** [comment]
Try setting the `theme` prop in TextInput like this:
```jsx
<TextInput theme={{roundness: 0}}
// other TextInput props
/>
```
I have not actually tried this, but I think it might work.

https://callstack.github.io/react-native-paper/theming.html

**Comment by jaskeerat789** [comment]
@LuckyLuke19 thanks for the help but it didn't work.
here is the [expo snack](https://snack.expo.io/B1jk8_U3H)

**Comment by LuckyLuke19** [comment]
@jaskeerat789 it does work for me.
https://snack.expo.io/@luckyluke19/round-textinput

**Comment by jaskeerat789** [comment]
@LuckyLuke19 thanks for the help buddy
