### ISSUE TITLE
How to change background modal to transparent, currently is backdrop?

### ISSUE THREAD

**Issue by NguyenPhatBG** [callstack/react-native-paper#1491]

**Comment by jaulz** [comment]
You can use a custom theme around the modal and adjust the backdrop within.

**Comment by sfelix-martins** [comment]
An example for @jaulz response:

```jsx
<Modal
   theme={{
     colors: {
       backdrop: 'transparent',
     },
   }}
  {...otherProps}
>
 {children}
</Modal>
```

**Comment by thalesog** [comment]
Guys, on `v4.10.1` this solution is not working.
I tried to use `backgroundColor: 'black'` but the safe area remains with default opacity, there's another solution for this?

**Comment by devmohmmad** [comment]
> An example for @jaulz response:
> 
> ```js
> <Modal
>    theme={{
>      colors: {
>        backdrop: 'transparent',
>      },
>    }}
>   {...otherProps}
> >
>  {children}
> </Modal>
> ```

How to change the intensity of backdrop?

**Comment by AlexisHerrera** [comment]
> > An example for @jaulz response:
> > ```js
> > <Modal
> >    theme={{
> >      colors: {
> >        backdrop: 'transparent',
> >      },
> >    }}
> >   {...otherProps}
> > >
> >  {children}
> > </Modal>
> > ```
> 
> How to change the intensity of backdrop?

Use rgba to adjust the opacity, for example:
`theme={{colors: {backdrop: 'rgba(255, 255, 255, 0.7)'}}`
