### ISSUE TITLE
ide hints

### ISSUE THREAD

**Issue by Stevemoretz** [callstack/react-native-paper#1492]
I'm using intellij for example it gets help from:
@types/* libraries to give you hints.I searched the repository for @types/react-native-paper but it doesn't exist that's so wired.Found:
"types": "lib/typescript/src/index.d.ts",
in package.json of react native paper is it related?How do I set it up with intellij if it is?

**Comment by Trancever** [comment]
@Stevemoretz Yes, this is related. Our codebase is 100% typescript and we ship the types directly in the package (this is standard). I would suggest to check intellij documentation regarding typescript support or ask on stackoverflow, because this is not a `react-native-paper` issue.

**Comment by Stevemoretz** [comment]
I still couldn't get it working would you please help if you can.It's somehow related to this library there are other libraries without @types but they work just fine.This one does'nt

**Comment by Stevemoretz** [comment]
The components are defined in rather unusual way in library typings... Like:

```
declare const _default: (React.ComponentClass<Pick<Props, "color" | "onPress" | "disabled" | "status" | "uncheckedColor"> & {
    theme?: import("@callstack/react-theme-provider").$DeepPartial<Theme> | undefined;
}, any> & import("@callstack/react-theme-provider/typings/hoist-non-react-statics").NonReactStatics<(React.ComponentClass<Props, any> & typeof Checkbox) | (React.FunctionComponent<Props> & typeof Checkbox), {}>) | (React.FunctionComponent<Pick<Props, "color" | "onPress" | "disabled" | "status" | "uncheckedColor"> & {
    theme?: import("@callstack/react-theme-provider").$DeepPartial<Theme> | undefined;
}> & import("@callstack/react-theme-provider/typings/hoist-non-react-statics").NonReactStatics<(React.ComponentClass<Props, any> & typeof Checkbox) | (React.FunctionComponent<Props> & typeof Checkbox), {}>);
```
export default _default;
The IDE can't resolve props when using such definitions, they require special support.

This is the response I got from intellij forums.the link is :
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006862660-react-native-paper-auto-complete-not-working-?page=1#community_comment_360001205360

**Comment by satya164** [comment]
They are generated by typescript compiler. Nothing unusual about them. They don't look pretty because they aren't hand written. Autocompletion works fine in VSCode with TypeScript language service with no special support.

**Comment by Awais6** [comment]
The same issue here still not resolved!

**Comment by E-Viskhan** [comment]
The problem still remains, does anyone know how to solve this problem? 

VS Code everything works as expected, but in WebStorm without typescript, props does not prompt. And even if you install typescript, Webstorm cannot prompt the props values
