### ISSUE TITLE
Menu Component, anchor, align right when rendering list of items

### ISSUE THREAD

**Issue by jonasgroendahl** [callstack/react-native-paper#1493]
I have a list of items using the <List.Item /> component

I want to render a Menu when somebody clicks the {right} part of a a list item. How am I going to implement this with react-native-paper? I tried to render a Menu component for each <List.Item /> but since you wrap the entire <List.Item /> component, the menu would always display on the left of the component even though I'm clicking the right side.

**Comment by Trancever** [comment]
You can pass `x` and `y` via `anchor` prop.
