### ISSUE TITLE
In ios, the textinput falls under the keyboard

### ISSUE THREAD

**Issue by meftunca** [callstack/react-native-paper#1495]
"react-native": "0.61.5",
react-native-paper: 3.3.0
![Simulator Screen Shot - iPhone 8 Plus - 2019-12-02 at 13 55 52](https://user-images.githubusercontent.com/19187204/69954160-c6104500-150b-11ea-89f6-791902665039.png)

## In ios, the textinput falls under the keyboard

**Comment by Trancever** [comment]
@meftunca Please provide a [Snack](https://snack.expo.io/) that reproduces issue.

**Comment by meftunca** [comment]
> @meftunca Please provide a [Snack](https://snack.expo.io/) that reproduces issue.

The shareable link to your Snack https://snack.expo.io/r1JUktzTr

**Comment by GauthierG** [comment]
I have the same issue with React Native 0.59.10 and react-native-paper 3.2.1

**Comment by Trancever** [comment]
@meftunca Check [this](https://snack.expo.io/@trensik/paper-bug). I wrapped a dialog in a KeyboardAvoidingView and it works perfectly on iOS. Let me know if it works for you, and if it doesn't try to play with different options for `behavior` prop.

**Comment by thiagog3** [comment]
@Trancever I checked your example and I found an issue.  When you add a second field, and do focus inside another then dialog position will be reseted to center.

**Comment by bboure** [comment]
I am having issues with this too.
Wrapping the Modal/Dialog in `<KeyboardAvoidingView>` works. However, this blocks all the other UIs when the modal is closed, since `KeyboardAvoidingView` stays on top of everything (empty).

Doing like so:

```tsx
{visible && <KeyboardAvoidingView>...</KeyboardAvoidingView>}}
```

works. However, it messes up the animations since the modal shows/goes way immediately.
