### ISSUE TITLE
Sliders

### ISSUE THREAD

**Issue by ahmedlhanafy** [callstack/react-native-paper#15]
[MD Docs Link](https://material.google.com/components/sliders.html#)

**Comment by ferrannp** [comment]
Explore https://facebook.github.io/react-native/docs/slider.

**Comment by luissmg** [comment]
@ferrannp Correct me if I am wrong.
I think that with the current implementation of RN's `Slider` we can't customize it as needed to apply MD specifications.

**Comment by satya164** [comment]
I think we'll need to implement our own using gesture handler.

**Comment by samichoulo911** [comment]
Hi I haven't found a slider in the current documentation and the RN version is deprecated. What is the work around or suggested library (if any)?
