### ISSUE TITLE
Custom Fonts with React Native Paper 3 and Expo 35.0.0

### ISSUE THREAD

**Issue by xNiallC** [callstack/react-native-paper#1500]
## Ask your Question

Hello,

I recently upgraded React Native Paper from version 2 to version 3 and am struggling to make custom fonts work. I updated my app to use the new theme management, using the exact format in the [Fonts documentation](https://callstack.github.io/react-native-paper/fonts.html), except replacing sans-serif with montserrat and montserrat-bold, etc. These fonts have been loaded using [Expo's font loading systems](https://docs.expo.io/versions/latest/sdk/font/) in Expo SDK 35.0.0. However, in the app now, all RNPaper `<Text />` components are using the system default font rather than montserrat. I was wondering whether there's further documentation or if I'm missing something here.

Thanks

**Comment by jonasgroendahl** [comment]
Maybe #1502  if using ios

**Comment by shiroze** [comment]
Simple Customize, this code what I use.

```
const fontConfig = {
  default: {
    regular: {
      fontFamily: Fonts.FONTS.PRIMARY,
      fontWeight: 'normal',
    },
  },
};

const theme = {
  ...DarkTheme,
  roundness: 5,
  colors: {
    ...DarkTheme.colors,
    text: Theme.COLORS.WHITE,
    placeholder: Theme.COLORS.WHITE,
    primary: Theme.COLORS.SWITCH_ON,
    background: 'transparent',
  },
  fonts: configureFonts(fontConfig),
};
```

or you can try use #1502 like @jonasgroendahl said

**Comment by xNiallC** [comment]
> Maybe #1502 if using ios

Thanks, this helped!
