### ISSUE TITLE
Icons are spinning in production build in web

### ISSUE THREAD

**Issue by acro5piano** [callstack/react-native-paper#1501]
First of all, thank you for the great library.

## Environment

```
    "react-native-paper": "^3.2.1",
```

```
    "html-webpack-plugin": "^3.2.0",
    "ts-loader": "^6.0.2",
    "webpack": "^4.33.0",
    "webpack-cli": "^3.3.3",
    "webpack-dev-server": "^3.7.1"
```

## Description

All material community icons are spinning in production build.
Not spinning in development environment running with webpack-dev-server.

Please refer to this screen record:

![spin](https://user-images.githubusercontent.com/10719495/70060884-a883ce00-1626-11ea-81e4-07b8fb6b4a3e.gif)

## Reproducible Demo

(not yet)

**Comment by acro5piano** [comment]
I added the following style to stop weird animations:

```css
div[role=img] {
  animation: none !important;
}
```

**Comment by Trancever** [comment]
@acro5piano Can you provide a small repro that we can easily build and try locally?

**Comment by acro5piano** [comment]
@Trancever Sorry for not providing repro. I'll try to reproduce this weekend or so. Thanks

**Comment by Trancever** [comment]
@acro5piano Cool, thanks!

**Comment by acro5piano** [comment]
@Trancever I'm really sorry, but I couldn't create any reproductions with any code, version, and browsers.
The most mysterious thing is I used the same version of the code (with git checkout) and build almost the same environment, but couldn't reproduce the issue. Maybe a bug in Chrome or something I guess.

Anyway, I have to close the issue. Thanks very much.
