### ISSUE TITLE
onLongPress is not working

### ISSUE THREAD

**Issue by yasir-netlinks** [callstack/react-native-paper#1507]
## Environment
react: 16.9.0
react-native: 0.61.2
react-native-paper: ^2.16.0

## Description
Below doesn't work
```
<TouchableRipple onLongPress={() => console.log('on long press')}>
 //
</TouchableRipple>
```
whereas `onPress` works

**Comment by Usamaliaquat123** [comment]
Hey, @yasir-netlinks , can i reproduce that issue cause i didn't get any issue on `onLongPress` .

**Comment by yasir-netlinks** [comment]
@Usamaliaquat123 I'm really not sure, but one thing I forgot to mention, I have `TouchableRipple` wrapped in a component, like so
```
class MyButton extends PureComponent {
     render() {
         const {isWithoutFeedback = false, hitSlop, children, ...rest} = this.props;
         if (isAndroid) {
              return (
                 <TouchableRipple {...rest}>
                        {children}
                 </TouchableRipple>
              )
         }
     }
}
```
Usage 
```
<MyButton
    onLongPress={() => console.log('long press')}   // it doesn't work, whereas 'onPress' works
>
    //
</MyButton>
```

**Comment by Artem-Kushch** [comment]
+1, don't  work

`            <TouchableRipple
                onLongPress={() => Alert.alert("LONG PRESS")}
                rippleColor="rgba(0, 0, 0, .32)"
                style={{backgroundColor: "yellow"}}
            >
            <View style={{alignItems: "center"}}>
                <Text style={{ fontSize: 18}}>{"hey ho"}</Text>
            </View>
            </TouchableRipple>`

`onPress` - works fine

"react-native-paper": "^3.2.1"

**Comment by Trancever** [comment]
Check this working [example](https://snack.expo.io/@trensik/carefree-macaroni-and-cheese). Make sure to also pass onPress.

**Comment by kendallroth** [comment]
@Trancever Ran into a similar issue and realized that it was because I had not specificed an empty `onPress`. Is there anywhere this is documented (vaguely recall running into this before but can't remember where)?

**Comment by lordjack** [comment]
For my work normally, It's my example.

` <List.Section>
                {this.state.contatoList.map((item, i) => (
                    <>

                        <TouchableOpacity
                            onLongPress={() => {
                                Alert.alert(
                                    'Remover Usuário',
                                    'Deseja realmente remover o registro?',
                                    [
                                        {
                                            text: 'Cancel',
                                            onPress: () => console.log('Cancel Pressed'),
                                            style: 'cancel',
                                        },
                                        {
                                            text: 'OK',
                                            onPress: () => this.remover(item.id),
                                        },
                                    ],
                                    { cancelable: false }
                                );
                            }}
                            onPress={() => {
                                let objContato = {
                                    id: item.id,
                                    nome: item.nome,
                                    telefone: item.telefone,
                                    dataNascimento: item.dataNascimento,
                                };
                                this.props.navigation.navigate("Formulário Contato", {
                                    contato: objContato,
                                    contatos: this.state.contatoList,
                                });
                            }}
                        >

                            <Divider />
                            <Paragraph>{i + 1}</Paragraph>
                            <Title>{item.nome}</Title>
                            <Paragraph>{item.telefone}</Paragraph>
                            <Paragraph>{item.dataNascimento}</Paragraph>
                            <Divider />
                        </TouchableOpacity>

                    </>
                ))}
  </List.Section> `

**Comment by nick-burczyk-cs** [comment]
> Check this working [example](https://snack.expo.io/@trensik/carefree-macaroni-and-cheese). Make sure to also pass onPress.

@Trancever Is the fact that `onPress` is required for `onLongPress` to work in the docs anywhere? I must have missed that. It worked for me though.
