### ISSUE TITLE
Use commitizen instead of the custom commit msg checker

### ISSUE THREAD

**Issue by jukben** [callstack/react-native-paper#152]
https://github.com/commitizen/cz-cli 
 
Then we could also use https://github.com/semantic-release/ for better releases.

What do you think?

**Comment by ferrannp** [comment]
It sounds to me like too much hassle for a small repository. Also, tbh, I prefer to type `git commit` than thinking of another command.

**Comment by jukben** [comment]
It was just suggesting how to standardize the repo. We could use it in another project.

[OT: Yeah, tell me about "too much hassle for a small repository" in my PR which is opened since ancient times 😂 ]
