### ISSUE TITLE
Button events don't fire in react-native-reanimated-bottom-sheet with enabledContentGestureInteraction

### ISSUE THREAD

**Issue by jsamr** [callstack/react-native-paper#1522]
## Environment

- expo SDK 36
- react-native-paper 3.3.0
- react-native-reanimated 1.4.0,
- reanimated-bottom-sheet 1.0.0-alpha.18
- react-native-gesture-handler 1.5.0

## Description

Despite `react-native-reanimated-bottom-sheet` being recommended, your button components (`FAB`, `Button`, `IconButton`) are not firing events when `enabledContentGestureInteraction` is set to `true`, because of `react-native-gesture-handler` `PanGestureHandler` taking precedence. A hack consists in nesting `react-native-paper` buttons inside `RectButton` from `react-native-gesture-handler`. But we lose the ripple effect and the overall experience is very unsatisfying regarding material design guidelines.

## Reproducible Demo

https://snack.expo.io/@jsamr/react-native-paper-issue-with-reanimated-bottom-sheet

## Proposition

The best for library consumers would be that you allow your buttons to be interfaced with `react-native-gesture-handler`.

**Comment by Trancever** [comment]
@satya164 Is there any other workaround for this issue?

**Comment by andreibarabas** [comment]
I'm playing with the drop in replacements for the Touchables* and it works so far. Here is the code.

https://github.com/andreibarabas/react-native-paper/commit/07e6567bbcf0caedb8c120b1b066fbecbe4d9af7


@Trancever - if you are interested in this direction, let me know and I can cleanup the code, do the tests and send a PR. I saw that in 2018 you didn't want to go this route so don't want to work something that will not be useful.

P.S: the ripple effect is much smoother with react-native-gesture-handler, so definitely worth it.

**Comment by jsamr** [comment]
Still occurring.
