### ISSUE TITLE
`<CircleIconButton />` - IconButton with background color

### ISSUE THREAD

**Issue by vpontis** [callstack/react-native-paper#1528]
## Describe the feature

Show an icon in a circular button with a background. 

![IMG_5246](https://user-images.githubusercontent.com/1319079/70841094-4ff1c500-1dcc-11ea-85c8-6e1b6f680870.jpg)

## Motivation

Right now you can create an `IconButton` but that has a transparent background. This is nice when the color of the button is on a static background. 

But when you have a variable background, like a map or image, the icon can easily get lost on the background. So you want to have a background color.

**Comment by Trancever** [comment]
@vpontis It looks like a FAB for me, why don't you use it instead?

**Comment by vpontis** [comment]
@Trancever wow it does look like a FAB! I didn't know what FAB stood for or that it existed. 

For reference: https://callstack.github.io/react-native-paper/fab.html

Thanks! Will close...
