### ISSUE TITLE
Issue using react-native-paper with typescript

### ISSUE THREAD

**Issue by crofoot** [callstack/react-native-paper#1536]
## Ask your Question

So I am trying react-native-paper for the first time. I am trying to test it out with a bootstrapped expo and typescript application but every time I declare a component I keep getting the following error:

`Type '{ children: Element[]; }' is missing the following properties from type 'Pick<any, "style" | "children" | "onLayout" | "testID" | "nativeID" | "accessible" | "accessibilityLabel" | "accessibilityRole" | "accessibilityStates" | "accessibilityHint" | ... 41 more ... | "onTouchEndCapture">'`

or similar errors like this: 

`Type '{ children: string; }' is missing the following properties from type 'Pick<any, "style" | "onLayout" | "testID" | "nativeID" | "accessible" | "accessibilityLabel" | "accessibilityRole" | "accessibilityStates" | "accessibilityHint" | "accessibilityComponentType" | ... 19 more ... | "textBreakStrategy">': style, onLayout, testID, nativeID, and 26 more.` 

Dependencies Versions:
`"@types/react": "~16.9.0"`
`"@types/react-native": "~0.60.23"`
`"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz"`
`"react-native-paper": "^3.4.0"`
`"expo": "36.0.0"`

Any thoughts? 
Thanks

**Comment by satya164** [comment]
You need to provide some code mate

**Comment by davisuga** [comment]
Im getting the same error just importing the components and using it on my application.
![image](https://user-images.githubusercontent.com/33470530/73023786-005eda00-3e0b-11ea-9908-55edb08a8140.png)

**Comment by andrewdeakins** [comment]
i had a similar issue but tried 
npm install
npm audit fix 

and then it started to work, i guess give it a go as there maybe libs not in sync etc.

**Comment by andordavoti** [comment]
I have the same issue, @davisuga @crofoot  did you manage to solve it?

**Comment by antoniocapelo** [comment]
@andordavoti just tried this and it fixed for me: https://brucelefebvre.com/blog/2019/11/26/typescript-react-native-paper/

**Comment by andrefedev** [comment]
The same happens to me, the previous solution does not work, because I am using react-native 0.62

**Comment by andrefedev** [comment]
I just installed "react-native-elements" and didn't get any type problem, use any example and it just works, but with paper it seems we have some error with dependencies and types.

**Comment by raajnadar** [comment]
I am using react native paper from past 1 year I never had any problem with types. I am sure you are doing something wrong from your end.

**Comment by andrefedev** [comment]
@raajnadar I don't think so, I have a clean react-native installation with the typescript template, then install paper and just copy and paste some of your examples and it throws me type errors for any component.
<img width="1235" alt="Captura de Pantalla 2020-06-01 a la(s) 12 23 14 p  m" src="https://user-images.githubusercontent.com/14114839/83435965-b2826000-a402-11ea-8c58-6ee406ffa8f3.png">

**Comment by proteche** [comment]
any update? how to solve this @andrefedev

**Comment by raajnadar** [comment]
Locked this issue because the original poster & @andrefedev @proteche issue is totally different.

I tried reproducing the issue in a fresh RN installation but every this is working fine for me. Create a new issue with more information & a repro so that we can debug the issue.
