### ISSUE TITLE
Give ability to our components like Checkbox/TextInput to be uncontrolled components

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#154]

**Comment by KrzysztofKarol** [comment]
I'm working on it.

**Comment by alvaromb** [comment]
@Moreno97 can you look into this?

**Comment by Moreno97** [comment]
As I see, TextInput is now an uncontrolled component, but Checkbox doesn't. Am I right?

**Comment by Moreno97** [comment]
> @Moreno97 can you look into this?

Yeah, already working on it @ferrannp

**Comment by jbinda** [comment]
I make PR to make TextInputs uncontrolled, probably there are also below components left to modify:
- [ ] Checkbox
- [ ]  Switch
- [ ] RadioButton
