### ISSUE TITLE
Need skeleton component

### ISSUE THREAD

**Issue by irshadpalayadan** [callstack/react-native-paper#1551]
Need skeleton component to show the loading geometrically which is similar to the loaded component.
eg: loading in youtube has skeleton

**Comment by Trancever** [comment]
@irshadpalayadan  We won't support skeleton components. We think that [react-native-shimmer](https://github.com/oblador/react-native-shimmer) provides a great UX and should be used instead.

**Comment by EduVencovsky** [comment]
@Trancever Are you going to reconsider this? Do you still think that [react-native-shimmer](https://github.com/oblador/react-native-shimmer) should be used?

**Comment by nathandonnelly** [comment]
Any update on this? [Last release](https://github.com/oblador/react-native-shimmer/commit/620a9e899df40e1bef38127d4ef61384e1a195c5) from react-native-shimmer looks like it was 2 years ago. Would love to see one baked into react-native-paper.

**Comment by hke-ghtest2** [comment]
Any update on this? [react-native-shimmer](https://github.com/oblador/react-native-shimmer) was 3 years ago.

**Comment by fwielstra** [comment]
There was a PR for react-native-shimmer that adds support for React's new architecture (https://github.com/oblador/react-native-shimmer/pull/37). At the moment, I cannot install react-native-shimmer regardless because it's set up to not work with react 17 and beyond. The PR mentioned does not seem to be stable, and has not had activity for 4 months.

I'd love for this project to take ownership of this functionality, or update its recommendations.

**Comment by Aichnerc** [comment]
Would be great to have a Skeleton component. Really tired of using additional packages for such basic functionality.

**Comment by jacquesdev** [comment]
Do people have any favourites? I found this one https://moti.fyi/skeleton which seems good?

**Comment by Alarees** [comment]
Any update ??

**Comment by jacquesdev** [comment]
@Trancever - would it be possible to re-review this issue?

**Comment by Awethentique** [comment]
Would it be more efficient if all components would have a variation of a loading state? For example if you used an Avatar and Text component in your view, Then you would pass in a prop called loading={true} similar to Button. The loading state would then show the skeleton of that component in the shape that it is. An additional prop such as skeletonStyle could be passed to style the skeleton for customisation.

Your thoughts and feedback would be appreciated.

**Comment by nathandonnelly** [comment]
That is, in my opinion, the better way to do it. Just pass a loading prop.

**Comment by bilal12367** [comment]
Guys, Idk why are you not supporting this idea of including Skeleton in react-native-paper. I see your suggesting us to use another library for such basic functionality. It would be better if you include it, most of the other react native UI libraries included these things. For a UI library, for me it feels like this is a basic thing, this should be included.

**Comment by edwinvrgs** [comment]
Should this be reopen?

**Comment by techweevil** [comment]
@Trancever I might not know why your team had made that decision not to add the skeleton, but I trust it was an informed one, however, as a fan of react native paper who has used other UI libraries which some of the support this specific feature, I think with the type of community we have, Isay you should give it to us

**Comment by TaylorFoster-Informulate** [comment]
Disappointed this was closed. Skeleton loaders are the preferred loading state UI in applications now-a-days as opposed to splash screens. Any chance this gets revisited?

**Comment by sir-george2500** [comment]
I think there a need for a skeleton component this really suck react-native-skimmer was last updated 2 years ago you don't expect us to relaid on a library that is not well maintain and ancient

**Comment by milan-vala** [comment]
a bit disappointed that react native paper team does not support skeleton, i think this looks promising `https://www.npmjs.com/package/moti`

**Comment by storm345s** [comment]
Support the @Awethentique idea, i think it could be great. The spinners are okey in some situations but in some components like avatar, accordions, etc. isn't a good option. Expect that the react native papers team reconsider that idea.

**Comment by Awethentique** [comment]
> Support the [@Awethentique](https://github.com/Awethentique) idea, i think it could be great. The spinners are okey in some situations but in some components like avatar, accordions, etc. isn't a good option. Expect that the react native papers team reconsider that idea.

Mobile Ui components have become quite complex these days, especially if you are needing an immersive and intuitive user interface. Some people have loader bars or spinners on the view, but there are instances where you need the component to perhaps have a skeleton loader state or sometimes just a spinner like the button needs. Each component should be treated upon their own merit and usage

**Comment by LouisMuriuki** [comment]
We are about to end 2025. still no skeleton loader.
I read that someone pushed a pr for this and it was rejected 
@Trancever At least let us know why you wont add it then. Community seems to massively want this
