### ISSUE TITLE
TextInputMask removed?

### ISSUE THREAD

**Issue by fgagneten** [callstack/react-native-paper#1553]
## Environment

react-native-paper 3.4.0 and RN >60

## Description

I'm trying to use the text input mask as the demo said but is not working. I got a red error screen saying 

> Invariant Violation: Element type is invalid: expecteda string but got: undefined

## Reproducible Demo

Just try to use a TextInput with input mask:

    
    `
     import { TextInput, TextInputMask } from "react-native-paper";
     ...
     <TextInput
          label="input"
          value={this.state.phoneNumberInput}
          onChangeText={phoneNumber =>
            this.setState({ phoneNumberInput: phoneNumber })
          }
          error={this.state.phoneNumberError}
          render={props => (
            <TextInputMask {...props} mask="+[00] [000] [000] [000]" />
          )}
    />`
 
Moreover, I can't find **TextInputMask** class

If I remove:

    render={props => (
        <TextInputMask {...props} mask="+[00] [000] [000] [000]" />
     )}

TextInput works like a charm

Probably someone removed the class unintentionally?

Thanks

**Comment by fgagneten** [comment]
Solved importing TextInputMask from https://github.com/react-native-community/react-native-text-input-mask

**Comment by baronchng** [comment]
@fgagneten May I ask by any chance are you using Expo for the above project?

**Comment by fgagneten** [comment]
Nop. I'm not using Expo
