### ISSUE TITLE
Checkbox icon missing (checkbox-blank-outline)

### ISSUE THREAD

**Issue by AslamPangestu** [callstack/react-native-paper#1554]
## Environment

Depedencies i use:
```
 "dependencies": {
    "react": "16.12.0",
    "react-native": "0.61.5",
    "react-native-paper": "3.4.0",
    "react-native-vector-icons": "6.6.0",
},

```

## Description

MaterialCommunityIcon for checkbox is not detected. (checkbox-blank-outline)

![Screenshot_1578282622](https://user-images.githubusercontent.com/26374086/71794476-51817680-3074-11ea-9fcc-e30db2a372ff.png)

## Reproducible Demo

There is some simple code i use
```javascript
<View style={styles.containerTermReference}>
   <Checkbox
       status={checked ? 'checked' : 'unchecked'}
       onPress={() => { this.setState({ checked: !checked }); }}
   />
   <View>
      <Text>{Strings.REFERENCE} </Text>
      <Text style={{ fontWeight: 'bold' }}>{Strings.TERM}</Text>
   </View>
</View>
```

**Comment by AslamPangestu** [comment]
If you using MaterialIcon, maybe you have to change with check-box-outline-blank and check-box

**Comment by christian0712** [comment]
Problem persists:
"react-native-vector-icons": "^8.1.0",
"react-native-paper": "^4.7.2",
"react": "16.13.1",
"react-native": "0.63.4",
