### ISSUE TITLE
Feature Request: Multiline Buttons

### ISSUE THREAD

**Issue by rub1e** [callstack/react-native-paper#1555]
## Describe the feature

Allow button text to be multiline - nothing more!

## Motivation

Currently buttons are limited to a single line ([ref](https://github.com/callstack/react-native-paper/blob/master/src/components/Button.tsx#L283)). It would be great if the button component could take a `numberOfLines` prop and apply that to the text component if present.

I'm stuck on v2 at the moment so it's a moot point for me - I have to fork the repo anyway; but I'd be happy to do a little PR for v3 if this is a goer?

## Related Issues

-

**Comment by Trancever** [comment]
This is against [MD Guidelines](https://material.io/components/buttons/#anatomy)

<img width="805" alt="Screenshot 2020-01-07 at 16 49 07" src="https://user-images.githubusercontent.com/18584155/71908141-c1275c80-316d-11ea-9a25-62b9d0e47924.png">

**Comment by jazzdragon** [comment]
This seems like a very easy fix to help those of us who don't follow the MD guidelines to the letter.

**Comment by latobibor** [comment]
@Trancever 
I get it, in that regular example it does not make sense, but here's some real world example:
<img width="308" alt="image" src="https://user-images.githubusercontent.com/12050526/207165508-9d9ff534-4282-4f51-b577-5263cfe7958f.png">

The user can select from different groups. We like the `Button` component as it has animation for loading.
