### ISSUE TITLE
Not Being Able to Scroll While Touching Input

### ISSUE THREAD

**Issue by Siyavoshi** [callstack/react-native-paper#1556]
React Native 059.10
Platform: Android

I have a form which has a lot of RNP inputs inside a <ScrollView> tag.
The problem is when I touch the input and swipe up and down, page doesn't scroll. If I try to scroll from somewhere outside of inputs, it scrolls just fine but since this page has a form with lots of inputs, there's not enough space outside of inputs.

When I add multiline={true} prop, the problem gets solved but is there a better way to avoid this?

UPDATE: After creating some brand new RN projects with 0.59.10, 0.61.4 and 0.61.5 I've found out the cause of my problem is RN's RTL plugin.
I've followed [this](https://stackoverflow.com/a/52381831/4982800) instruction as how to make my application RTL and it causes inputs not to scroll while inside a ScrollView.

Is there any solution for this?

**Comment by Trancever** [comment]
@Siyavoshi Can you provide a repro on [Snack](https://snack.expo.io/). 

I tried it and [it](https://snack.expo.io/@trensik/crabby-apples) works for me on both android and iOS.

**Comment by Siyavoshi** [comment]
@Trancever The inputs are inside a Flatlist which itself is inside a ScrollView.
I'll try to make a repro and update this post.

**Comment by satya164** [comment]
FYI you shouldn't put `FlatList` in `ScrollView`

**Comment by Siyavoshi** [comment]
UPDATE: After creating some brand new RN projects with 0.59.10, 0.61.4 and 0.61.5 I've found out the cause of my problem is RN's RTL plugin.
I've followed [this](https://stackoverflow.com/a/52381831/4982800) instruction as how to make my application RTL and it causes inputs not to scroll while inside a ScrollView.

Is there any solution for this?

**Comment by akshay4040** [comment]
React Native 064.10
Platform: Android
language :hebrew

The problem is when I touch the searchabledropdown and swipe up and down, page doesn't scroll. If I try to scroll from somewhere outside of inputs, it scrolls just fine but since this page has a form with lots of inputs, there's not enough space outside of inputs.

the problem is in hebrew language not in english

When I add multiline={true}  the problem gets solved in input field but i have same issue in searchable dropdown is there a better way to avoid this?
what i have to do in this senario please help me

**Comment by ZeeshanAhmadKhalil** [comment]
Found any Solution?

**Comment by TiagoDanin** [comment]
This happens to me on every TextInput that has custom style with height set.
https://snack.expo.dev/@tdanin/26350f

@satya164 Can we reopen this issue?

**Comment by TiagoDanin** [comment]
This happens to me on every TextInput that has custom style with height set.
https://snack.expo.dev/@tdanin/textinput-bug-paper-with-height

@satya164 Can we reopen this issue?

**Comment by meysam25** [comment]
i have same problem, why no one fix this, i am using rtl and when i put multiline={true} its work just fine

**Comment by Subhashish-Mishra** [comment]
@TiagoDanin have You found any solution to this problem yet??

**Comment by philemonpeter02** [comment]
Any Solutions?

**Comment by edward99enclave** [comment]
any solutions yet?

**Comment by diego5f5** [comment]
I solved this removing the height property of the View that wraps my TextInput, and on it I'm just using padding to reach the desired visual aspect.

**Comment by faforus** [comment]
In my case I could not have both paddingTop and paddingBottom at the same time. After removing both it worked.

**Comment by diegoleondev** [comment]
Did you find any solution? @satya164

**Comment by diegoleondev** [comment]
Did you find any solution? @akshay4040

**Comment by DhruvaKhunt** [comment]
Make sure you have imported TextInput from react-native and not from react-native-gesture-handle
