### ISSUE TITLE
Flow is broken in example folder

### ISSUE THREAD

**Issue by jukben** [callstack/react-native-paper#156]
**Expected Behavior**

If you use `<Checkbox>` without mandatory `checked` prop the Flow check has to fail.

**Current Behavior**

I've used `<Checkbox>` without mandatory `checked` prop. Flow check was valid.

**Steps to reproduce**

- In `CheckboxExample.js` remove `checked` prop on random `Checkbox`
- run `yarn flow`

**Comment by ferrannp** [comment]
We need to update Flow (which will break a lot of component types) and fix this. It is related to `withTheme`.

**Comment by ferrannp** [comment]
@satya164 so Flow is not broken anymore, if something needs to be change/adapt, let's open an issue for it.
