### ISSUE TITLE
Components Dont Listen to Theme Provider

### ISSUE THREAD

**Issue by declan-m** [callstack/react-native-paper#1564]
### Current behaviour

Everything defaults to purple.

### Expected behaviour

I have set the theme up using theme provider changing default primary and secondary colours. I expected every element to inherit the colour from the theme provider but everything is stuck on purple

### Code sample

```
<PaperProvider theme={Theme}>
  <View style={styles.container}>
    {Platform.OS === 'ios' && <StatusBar barStyle="default"/>}
    <AppNavigator/>
  </View>
</PaperProvider>

.....

const Theme = {
  ...DefaultTheme,
  color: {
    ...DefaultTheme.colors,
    primary: Colours.Primary,
    secondaryColor: Colours.Secondary,
  }
};

```

**Comment by satya164** [comment]
```js
color: {
```

The field is `colors` not `color`
