### ISSUE TITLE
Reverse List.Accordion icon(arrow) rotation

### ISSUE THREAD

**Issue by LeviYoder2112** [callstack/react-native-paper#1565]
The behavior of the List.Accordion arrow icon on the right side is to point up if the list is expanded, and down if the list is collapsed.
Is it possible for me to reverse that behavior since I'm using the List.Accordion at the top of my screen and it is expanding down? 

Example:

<img width="373" alt="Screen Shot 2020-01-10 at 1 51 10 PM" src="https://user-images.githubusercontent.com/34454615/72185574-59148880-33b0-11ea-8694-434f8dc08d3d.png">
<img width="374" alt="Screen Shot 2020-01-10 at 1 51 29 PM" src="https://user-images.githubusercontent.com/34454615/72185576-59148880-33b0-11ea-9c29-ce1db40289e0.png">

**Comment by mmarkusik** [comment]
Hey @LeviYoder2112. Currently we are not planning such a feature. This is because the arrow icons pointing up and down correspond with the actions happening once you press them. When pressing arrow down, the list opens downward. Similarly, when pressing the up arrow the whole list closes upward.

**Comment by grpeteros** [comment]
Please implement this, we need a way to customize or show & hide the icon

**Comment by meliodev** [comment]
Any solution for this ?? :/
