### ISSUE TITLE
Question/feature : control of textAlignVertical for TextInput (multiline)

### ISSUE THREAD

**Issue by amauryfischer** [callstack/react-native-paper#1570]
Hi,
I'm currently working with react-native-paper for both classical TextInput and multiline TextInput.
Currently i have a style problem :
![Capture d’écran 2020-01-13 à 13 29 21](https://user-images.githubusercontent.com/16059663/72256300-21544d80-3609-11ea-8d4d-321417b96ed4.png)
![Capture d’écran 2020-01-13 à 13 29 33](https://user-images.githubusercontent.com/16059663/72256307-274a2e80-3609-11ea-8af0-2b077aa61d94.png)

The distance between the label and the first line of TextInput value is different for multiline and !multiline TextInput.
This is due to the property textAlignVertical which is set as "top" for !multiline fields and "center" for multiline.
It is partially related to https://github.com/callstack/react-native-paper/pull/1020

Here is the code responsible of this behaviour : https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/TextInputFlat.tsx
Line 267
```
textAlignVertical: multiline ? 'top' : 'center',
```
(and of course same for TextInputOutlined
https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/TextInputOutlined.tsx

Is there a way to customize this style ?
It seems there is not a lot of style going that far from style props to TextInput, they are intercepted by the line76 in TextInputFlat
```
    const {
      fontSize: fontSizeStyle,
      fontWeight,
      height,
      paddingHorizontal,
      ...viewStyle
    } = (StyleSheet.flatten(style) || {}) as TextStyle;
```

**Comment by amauryVedana** [comment]
Any news for this ?
Do not hesitate if you need more informations.

**Comment by redbluenat** [comment]
I have the same problem, any news for it?

**Comment by amauryVedana** [comment]
@firede Should i try to submit a PR for this ?

**Comment by firede** [comment]
Hi, @amauryVedana 
I'm just a contributor on this project, maybe you should ask the owners.

**Comment by amauryVedana** [comment]
@firede Oh okay sorry^^
@satya164 ?

**Comment by amauryVedana** [comment]
Still no response ?

**Comment by Huxpro** [comment]
Hi folks, I just opened #1824 which add an ad-hoc fix for this issue ;)

**Comment by amauryVedana** [comment]
Hi @Huxpro thanks for this, i'm watching out when this will be merged

**Comment by raajnadar** [comment]
@amauryVedana you can send a PR to fix the issue

**Comment by amauryVedana** [comment]
No information on this ?

**Comment by AwabIjaz** [comment]
a fix by using native text input in the render prop https://github.com/callstack/react-native-paper/issues/1810#issuecomment-616817037

**Comment by MaxInMoon** [comment]
@AwabIjaz thank you, it did the trick!
