### ISSUE TITLE
Carousel inside PaperProvider not works

### ISSUE THREAD

**Issue by ricaragao** [callstack/react-native-paper#1575]
I tried to use many Carousel inside of the PaperProvider, but every not work. If I remove PaperProvider them works fine. 

Someone has a good way to create a Image Carousel inside of the PaperProvider?

I tried with:

@react-native-community/viewpager
react-swipeable-views-native

**Comment by mmarkusik** [comment]
Hi @ricaragao, please prove repro for your issue so we can look into it.

**Comment by ricaragao** [comment]
When I try like this below, ViewPager is not showed. If I remove PaperProvider, it works fine.

```
<PaperProvider theme={paperTheme} >
     <ViewPager style={{ flex: 1 }} initialPage={0}>
                    <View key="1">
                        <Image source={image} />
                    </View>
                    <View key="2">
                        <Text>Second page</Text>
                    </View>
    </ViewPager>
</PaperProvider>
```

**Comment by Trancever** [comment]
@ricaragao Are you sure it works without PaperProvider? The only thing PaperProvider do is context providers rendering and it can't affect children.

Try passing `style={{flex: 1}}` to the `View`. That might fix your issue

**Comment by ricaragao** [comment]
@Trancever , not work.

**Comment by satya164** [comment]
Please provide a runnable repro

**Comment by ricaragao** [comment]
I guess that I isolated the problem and you are sure. Cause of problem isn't Provider. Thanks.

**Comment by ricaragao** [comment]
I mapped an incompatibility with ScrollView.
Thanks guys.
