### ISSUE TITLE
Allow class override

### ISSUE THREAD

**Issue by mauro0x52** [callstack/react-native-paper#1582]
## Describe the feature

As a developer, I want to override component so that I can make small adjustments to fit the requirements.

Currently, all components are exported as `export default withTheme(PaperComponent);`, which is not inheritable. Named export could be used to export the raw class without breaking old imports using the component with theme. For example:

```
export default withTheme(PaperComponent);
export { PaperComponent }
```

This simple change would allow overriding entire methods. 

Also, splitting the render function into smaller methods would be helpful for replacing parts of the rendered component.

## Motivation

Sometimes there is a small change I want to change in a component to fit the requirements.

For example, I need to use the List.Accordion with the chevron on the left and add a dropdown menu on the right.

## Related Issues

None

**Comment by satya164** [comment]
Whether a component is a class or a function is an implementation detail. It can change anytime in a minor version.

React components should be customized by wrapping them in components and passing props. We don't support inhertance or overriding internal methods.

If you need a feature that's not available, you should open an issue. If it's something that cannot be added in the library, you can either fork it or use [patch-package](github.com/ds300/patch-package) to add your customizations.
