### ISSUE TITLE
Card's innerContainer flexGrow: 1 breaks shrink to fit

### ISSUE THREAD

**Issue by indigoviolet** [callstack/react-native-paper#1583]
## Environment

I see this on Android (and on the android and ios snacks)

## Description

See the snack below. I have a FlatList inside a Card, and as the height of the FlatList grows, I want it to start scrolling once the container is filled. To do this, I set `{flex: -1}` appropriately. However, this breaks if I use `Card`, I believe because of this [line](https://github.com/callstack/react-native-paper/blob/6e274f5654b79961c6e0748eeaaf5fcf882e4f78/src/components/Card/Card.tsx#L175) which sets `flexGrow: 1` on the Card's innerContainer.

If I replace the Card with a Surface, it works as expected.
## Reproducible Demo

https://snack.expo.io/@indigoviolet/card-flexgrow:-1

**Comment by indigoviolet** [comment]
Don't think this has been addressed.

**Comment by Reggionick** [comment]
I think that this also prevent the content to be vertically centered if the card has a size bigger that it's content: it's not possible to change innerContainer's style.

Could this be reopened?
