### ISSUE TITLE
How to add custom colors/attributes to the theme?

### ISSUE THREAD

**Issue by indigoviolet** [callstack/react-native-paper#1584]
Previously: #317, #568, #799, but I don't think the question has been answered:

What is the recommended way to pass custom attributes (eg. custom accent colors besides the one `accent` property) through the theme? The typescript type currently makes this inconvenient. 

One way is to make a separate `auxTheme` object and pass it through a custom context, but it would be nicer to be able to use a single theme object.

Perhaps adding a `auxiliary: any` key to the theme type will be sufficient? Perhaps we can make `Provider` take a generic type for the auxiliary object, or infer it?

**Comment by kamui545** [comment]
This is bugging me so much as well.

I just managed to do something like that:

```ts
// app/themes.ts

import {
  DefaultTheme as PaperDefaultTheme,
  Theme as PaperTheme,
} from 'react-native-paper';

export interface Theme extends PaperTheme {
  custom: {
    muted: string;
  };
}

export const DefaultTheme: Theme = {
  ...PaperDefaultTheme,
  colors: {
    ...PaperDefaultTheme.colors,

    //
  },
  custom: {
    muted: '#ccc',
  },
};
```

and then use `as` to give the new Theme Interface:

```ts
import { Theme } from 'app/themes';

const { colors, custom } = useTheme() as Theme;
```

Not sure if it is the right way, I am no expert tbh, but at least it is working for me.
TypeScript is not yelling about it and your IDE will also benefit from the autocomplete.

**Comment by kamui545** [comment]
https://github.com/callstack/react-native-paper/issues/1835

Let's hope they find a sexy implementation for 4.0 <3

**Comment by kamui545** [comment]
Support has been merged (#2002) and it is now available on `react-native-paper@^4.0.0-alpha.2`, just tried it out and it works like a charm.

Usage:

```
declare global {
  namespace ReactNativePaper {
    interface ThemeColors {
      myOwnColor: string;
    }
    interface Theme {
      myOwnProperty: boolean;
    }
  }
}
```

**Comment by dlferro** [comment]
Was there anything more needed to get this to work? I've tried the example with no luck.

**Comment by stearruda** [comment]
Is there any workaround with the ESLint rule over **typescript-eslint/no-namespace**?
