### ISSUE TITLE
examples crash on drawer opening on the web

### ISSUE THREAD

**Issue by kopax** [callstack/react-native-paper#1590]
## Environment

I am trying to test the drawer on the web and it's currently not working. 

## Description

```
TypeError: navigation.openDrawer is not a function
```

## Reproducible Demo

```
git clone git@github.com:callstack/react-native-paper.git
cd react-native-paper
git checkout v3.4.0
yarn bootstrap
yarn example
npx expo start --web
```

**Comment by kopax** [comment]
If removing the `<App />` web specific rendering, the drawer can open, but the click on the overlay does not close it, making it impossible to close the drawer and visit the website. Is there a way I can fix this? Thanks.

**Comment by satya164** [comment]
React Navigation's drawer doesn't work on web yet.

**Comment by kopax** [comment]
Surprising, this is what I have when rendering on the web:

![image](https://user-images.githubusercontent.com/1866564/72699584-a1cffc80-3b7b-11ea-977e-c4eb067ab7c5.png)

It seems to work, except the closing gesture. How can I have a drawer on the web? (a designing mine is an option but, it would make more sense to use a lib, or lastly to fix the drawer)

**Comment by satya164** [comment]
> It seems to work, except the closing gesture.

Well if gesture doesn't work, then it doesn't work. It uses reanimated and gesture handler libs for animations and gestures whose web support is still in progress. It needs to be fixed in those libs. For now, you need to build your own drawer for web.

**Comment by kopax** [comment]
Ok thanks for your answer. This seems to be a 2 year's old issue: https://github.com/react-navigation/react-navigation/issues/174#issuecomment-277458895 , some attempt have been done to fix it. I am surprise no solution as upcome yet.

**Comment by kopax** [comment]
@satya164 you seem to know quite well the topic, may I kindly ask if you have or know a GitHub project that mix react-navigation and react-router to support web, iOS and Android navigation? I have done something but it is quite buggy and my knowledge makes me thing web first, which is maybe bad for the design pattern native code requires.
