### ISSUE TITLE
Set dark or light theme according to device preferences by default

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#1597]
React Native 0.62 will have an `Appearance` module which gives us the preferred color scheme of the device. We can detect and switch to dark theme automatically by default if it's preferred.

https://github.com/facebook/react-native/blob/a27e31c059971b1d554ad6c7c81706f08eafac87/RNTester/js/examples/Appearance/AppearanceExample.js#L14

It'll be a breaking change due to React Native version requirement, so we might want to wait a bit and drop support for older versions of React Native when we release it.

**Comment by troZee** [comment]
Please don't close it :p

**Comment by troZee** [comment]
I close this issue, because it has been implemented. 

cc @Trancever
