### ISSUE TITLE
TouchableRipple not respecting borderRadius on Android

### ISSUE THREAD

**Issue by odesey** [callstack/react-native-paper#1602]
## Environment

React Native: **0.61.2**
React Native Paper: **3.4.0** 

## Description

When using `TouchableRipple` component, the `borderRadius` style property is **NOT** respected on Android

```javascript
<TouchableRipple
        onPress={...}
        rippleColor="rgba(206,232,255,0.8)"
        style={{
            borderRadius: 50,  //Works on iOS but on Android the ripple is square
            height: 40, 
           width: 40}}
 />
```

This appears related to this PR: #788 

Also might be related to issue #1601

**Comment by pixelize** [comment]
@odesey Have you tried using borderless props on the TouchableRipple ?

**Comment by odesey** [comment]
@pixelize, setting the `borderless` prop works.

Thanks.

**Comment by NathanC** [comment]
This doesn't solve it for me-- it makes the opacity of the ripple change/not work properly, and hides some of my content. Instead, I'm wrapping the Touchable Ripple in a view, and making it so that view has the same border radius and hidden overflow

**Comment by EmmaEG** [comment]
lo que funcionó para mí es usar la prop borderLess y el style borderRadius  en el TouchableRipple , y envolver con un View que el TouchableRipple con el style borderRadius y darle a ambos el mismo valor.

**Comment by joaoaoluiz** [comment]
Setting it to borderless causes an undesired opacity effect on the content when pressed. I end up adding the wrapper, but it was troublesome because I had to handle every instance that passes padding, since that needs to go directly to TouchableRipple.
I think this issue should not be closed as completed

**Comment by HyperMorgado** [comment]
style={{borderRadius: 8}} and borderless={true} fix the problem for me

**Comment by whtjs** [comment]
@pixelize do you know why does borderless solve this problem? I understand that borderless option renders ripple outside of view bounds. So i understand `false` option will solve this problem but it was opposite. I'm little bit confuse
