### ISSUE TITLE
Navigation Rail

### ISSUE THREAD

**Issue by sohcah** [callstack/react-native-paper#1603]
## Describe the feature

The new Material Design Navigation Rail
https://material.io/components/navigation-rail/#

## Motivation

Adding the Navigation Rail would allow for expanded UI options for Tablets and Web and allow for easier-to-use interfaces.

**Comment by satya164** [comment]
Also note

> Guidance in beta reflects the latest Material Design insights. It may significantly change to support new research and code.

**Comment by BenJeau** [comment]
I think we should potentially reopen this issue since it's still part of Material You https://m3.material.io/components/navigation-rail/overview

**Comment by lukewalczak** [comment]
It partially done, please check: https://callstack.github.io/react-native-paper/drawer-collapsed-item.html

**Comment by micahlt** [comment]
@lukewalczak Should this not be implemented more as another layout for BottomNavigation?  Seems like that would make more sense rather than an entirely different component.  Integration with React Navigation would be excellent to have.

**Comment by micahlt** [comment]
Just bumping this @lukewalczak - since this is just the large-screen version of bottom tabs, it really needs to be just another display method for the existing bottom tabs component.  The optimal use case would be to use bottom tabs on phones and the rail on tablets.
