### ISSUE TITLE
List.Accordion no way to change "right" or customize 

### ISSUE THREAD

**Issue by victorvarenic** [callstack/react-native-paper#1605]

**Comment by victorvarenic** [comment]
List.Accordion no chance to customize the right part of component and customize it. For example there no onLongPress event, and can't find how I can implement it. I've tried wrap by my Touchable (TouchableOpacity, TouchableRipple), but it doesn't help.

**Comment by victorvarenic** [comment]
In right part of List.Accordion using arrow up if it closed and arrow down if opened. I want to use my own component/icon for this feature

**Comment by GKGokul** [comment]
Did you manage to customize? @victorvarenic @dpossamai 
I want to customize such that the touchableRipple is present only for the icon instead of the whole list item title. And also add a custom icon.

**Comment by dpossamai** [comment]
@GKGokul  not so far :(

**Comment by Waqas4hmad** [comment]
here is customization of  right icon ..   
 right={props =>props.isExpanded===false? <List.Icon {...props} icon="plus" />:<List.Icon {...props} icon="minus" />}
(y)
