### ISSUE TITLE
Android Checkbox bug

### ISSUE THREAD

**Issue by odesey** [callstack/react-native-paper#1606]
## Environment

React Native: **0.61.2**
React Native Paper: **3.4.0**

## Description

When using `FontAwesome Icons` via:

```javascript
         <PaperProvider
            theme={theme}
            settings={{
              icon: props => <FontAwesomeIcon {...props} />
            }}>
            {...}
        </PaperProvider>
```

The Android checkbox icon no longer renders properly. You get the question mark icon usually rendered for an incorrect icon name.

So, instead of this:
![Screen Shot 2020-01-26 at 4 42 59 PM](https://user-images.githubusercontent.com/3899366/73142279-eddadf80-405a-11ea-8932-9bea847515fb.png)

You get this:
![Screen Shot 2020-01-26 at 4 41 22 PM](https://user-images.githubusercontent.com/3899366/73142252-bec46e00-405a-11ea-8ce6-bcdbb2bc42e4.png)

**Comment by Bound3R** [comment]
Yeah, i have same problem, you can send custom icons but the checkbox use a specific variable to determine the icon to show..

you can see the variables on this  [line.](https://github.com/callstack/react-native-paper/blob/master/src/components/CheckboxAndroid.tsx#L120)
```javascript
const icon = indeterminate
      ? 'minus-box'
      : checked
      ? 'checkbox-marked'
      : 'checkbox-blank-outline';
```
works for my ignore customs icons for now, and only use the custom icons when its required.

```javascript
settings={{
  icon: props => <FontAwesomeIcon {...props} />
}}>
```
