### ISSUE TITLE
ProgressBar won't show within Card.Content with 'flexDirection: "row"'

### ISSUE THREAD

**Issue by Dan-Young-AA** [callstack/react-native-paper#1608]
## Environment

iOS & Android.
react-native-paper v3.4.0

## Description

I'm trying to display a `<Paragraph>` and `<ProgressBar` next to each other. If I put both into a container (in this case, `<Card.Content>` and give it a style of `{ flexDirection: "row" }`, the ProgressBar will not display.

This does not happen when the container has `{ flexDirection: "column" }`. The provided example shows both.

Using some debugging tools, it looks as though the `ProgressBar` component has `width: 0` set on its state.

## Reproducible Demo

Expo example here: https://snack.expo.io/@dan-aa/e8300e

**Comment by satya164** [comment]
You need to set a width on your items by setting a `width` or using flexbox. Otherwise the progress bar doesn't now how big it should be.
