### ISSUE TITLE
labelStyle prop not working in Fab.Group actions.

### ISSUE THREAD

**Issue by narensprinter** [callstack/react-native-paper#1613]
Hi

I tried to apply background color for Fab.Group each action label. but there is no style props for label. is there any possible way to change background color for label?

**Comment by robertLichtnow** [comment]
You should use the `style` prop inside each member of the `action` prop array

**Comment by nihp** [comment]
Can i able to align the label below the icon in FAB.group

As the attached image(marked)
![Screenshot 2020-02-06 at 12 09 42 PM](https://user-images.githubusercontent.com/36992338/73912828-8d119980-48db-11ea-9494-ac0ff93ce13a.png)

**Comment by Trancever** [comment]
@nihp No. According to MD Guidelines, labels should be placed on the left from the icon.

**Comment by Trancever** [comment]
@narensprinter Did you find the solution? Can we close the issue?

**Comment by narensprinter** [comment]
@Trancever No.. if i use the style prop inside each member of the Action prop array. its only applying background colour for Icon but expected result should be apply for both icon and label. Is there any other way to change label background colour?

**Comment by narensprinter** [comment]
@Trancever  Hi , do you know any fix for applying background color for icon and label?

**Comment by nihp** [comment]
Any update for this?

**Comment by narensprinter** [comment]
No solution as for now. i'm just using default background colour. not able to customize.

**Comment by nihp** [comment]
Okay

**Comment by satenchauhan** [comment]
no solution for that

**Comment by functioncall** [comment]
Is there a solution for this?

**Comment by dan-betmate** [comment]
@narensprinter @satenchauhan 

Has anyone found a solution for this yet?

**Comment by Korin92** [comment]
>@narensprinter @satenchauhan
>
>Has anyone found a solution for this yet?


I found the solution. You must add style tag for the background of the icons, labelStyle for the label and labelTextColor for the color of the text. example:
**actions={[
                        {
                            style:{backgroundColor: '#474747'},
                            labelStyle:{backgroundColor:'#474747'},
                            labelTextColor:'#a9ba37',
                            icon: '',
                            label: 'Añadir tarea',
                            onPress: () => console.log('Pressed email'),
                        },
                ]}**
