### ISSUE TITLE
TextInput value isn't getting preserved during navigation

### ISSUE THREAD

**Issue by vivekkumar16** [callstack/react-native-paper#1620]
I have two screens, A and B. Screen A contains just a react-native-paper TextInput, e.g.,

                <View>
                    <TextInput
                        error={error}
                        label='Enter something'
                        mode='outlined'
                        onBlur={this.onBlurHandler}
                        onChangeText={text => this.setState({text})}
                        value ={this.state.text}
                    />
                </View> 

In above case, when I move from screen A to screen B, and if I press back to come to screen A, the value of TextInput goes, though `this.state.text` has whatever the data I filled on screen A.

If I hardcode the value, then it remains preserved after navigating from A to B and then back to A. E.g.,

        <View>
            <TextInput
                error={error}
                label='Enter something'
                mode='outlined'
                onBlur={this.onBlurHandler}
                onChangeText={text => this.setState({text})}
                value ={'Hello World'}
            />
        </View> 

Please tell me how can I make sure that the value of TextInput remains preserved when I move from screen B to screen A.

**Comment by satya164** [comment]
Please provide a runnable repro

**Comment by RichardLindhout** [comment]
Could it be that you reset the state in the onBlur?
