### ISSUE TITLE
Modify style of placeholder text in TextInput component

### ISSUE THREAD

**Issue by AlexZhenWang** [callstack/react-native-paper#1621]
Version: 3.4.0

Hi, thanks for provider this awesome library. I want to change the style of placeholder text of TextInput component but didn't see any interface to do this, may I have a hand?

![image](https://user-images.githubusercontent.com/14008461/73494337-31499b00-4419-11ea-8687-630639876fde.png)

**Comment by robertLichtnow** [comment]
@AlexZhenWang if you go to the TextInput docs, you'll see that it extends the react-native `TextInput` component, meaning you should be able to change the placeholder color with the prop `placeholderTextColor`

https://callstack.github.io/react-native-paper/text-input.html
https://facebook.github.io/react-native/docs/textinput.html#placeholdertextcolor

**Comment by w90** [comment]
Placeholder text is implemented here in a bit different way. It actually is not a classic input's placeholder at all, just a regular, styled div/View. So it should be tweakable from components custom options.

**Comment by watnFoehn** [comment]
At least in my project that is not working.
Also I have no way to change the font size. I need that onFocus the font size stays the same for example.
So far I have no success at all in styling the label of the text input.
