### ISSUE TITLE
Ability to have different placeholder & border color on an Outlined Text Input

### ISSUE THREAD

**Issue by Tiltorito** [callstack/react-native-paper#1647]
It would be really nice to be able to control those 2 colours individually. By placeholder I mean the label when the text input is not focused

**Comment by w90** [comment]
+1

On React Native Web I can style it somehow using nasty hacks, but on android/ios there is no such possibility.

**Comment by aviemore** [comment]
+1  We need it! Any perspectives about this idea @Trancever ?

**Comment by Tiltorito** [comment]
still exists

**Comment by benb7760** [comment]
Perhaps adding an additional theme property named 'outline' or something similar which can be used in all components which have an outline (outline input, the underline on an unfocused flat input, outline button, etc?

**Comment by hari3110** [comment]
@Tiltorito Any updates?
I want to change border color & other things?
