### ISSUE TITLE
Add onLongPress to FAB

### ISSUE THREAD

**Issue by cayasso** [callstack/react-native-paper#1649]
## Describe the feature

Add onLongPress to FAB. Current only onPress is supported.

## Motivation
Any CTA button should support onLongPress.

**Comment by jadeirving9** [comment]
My application requires this too

**Comment by cayasso** [comment]
Issue is still valid!

**Comment by BlackWild** [comment]
+1 to this feature.

**Comment by achuinard** [comment]
See pull #2072
