### ISSUE TITLE
How to reduce borderWidth in textinput?

### ISSUE THREAD

**Issue by lastch** [callstack/react-native-paper#1650]
I'd like to reduce borderWidth in TextInput, but when i add `borderWidth: 1` in style, i can see two borders appear in one TextInput.
Does anybody know about this issue?
Thanks.

**Comment by danielkv** [comment]
+1

**Comment by aviemore** [comment]
It's hardcoded now as I remember, when focused this is 2, otherwise always 1. 
joining +1 me to this question to react-native-paper team!
Anyone?

**Comment by danielkv** [comment]
it is

**Comment by userotti** [comment]
![Annotation 2020-07-10 144702](https://user-images.githubusercontent.com/1686713/87156047-4fff6800-c2bc-11ea-9e0d-676df16f763d.png)

Anybody see this before?

**Comment by longb1997** [comment]
+ 1

**Comment by ganesh-papola** [comment]
any solution?

**Comment by userotti** [comment]
I ended up reducing the border width on the input.

**Comment by farhan067** [comment]
> 
> 
> I ended up reducing the border width on the input.

How?

**Comment by paulintrognon** [comment]
This issue should not be closed: there are still no solutions to this, AFAIK

**Comment by amit00978** [comment]
Any one Found anything ?

**Comment by jeafgilbert** [comment]
Go to _node_modules/react-native-paper/src/components/TextInput/TextInputOutlined.tsx_ find `borderWidth: hasActiveOutline ? 2 : 1`  update to `borderWidth: hasActiveOutline ? 1 : 1`. But if we do `npm install` or `yarn install` in the future, your changes will be gone. To prevent this, use [React Native Patch Pacakge](https://www.npmjs.com/package/patch-package) to re-apply the changes.

**Comment by SantiagoCor** [comment]
Thanks @jeafgilbert!!! That worked for me

**Comment by GubanovIgor** [comment]
Has this been fixed?

**Comment by EricSoeun** [comment]
I 'm not sure if it's relevant but I managed to keep my outlined input to have a 1px border even when active by doing this :

```
<TextInput
      outlineStyle={{ borderWidth: 1 }}
      mode="outlined"
/>
```

Hope it may helps 🙂

**Comment by SontranBK** [comment]
> Go to _node_modules/react-native-paper/src/components/TextInput/TextInputOutlined.tsx_ find `borderWidth: hasActiveOutline ? 2 : 1` update to `borderWidth: hasActiveOutline ? 1 : 1`. But if we do `npm install` or `yarn install` in the future, your changes will be gone. To prevent this, use [React Native Patch Pacakge](https://www.npmjs.com/package/patch-package) to re-apply the changes.

jeafgilbert's answer works for me, the only drawback is that you have to re-apply change every time you reinstall this package. This hardcoding is really uncomfortable

**Comment by badalsaibo** [comment]
> ![Annotation 2020-07-10 144702](https://user-images.githubusercontent.com/1686713/87156047-4fff6800-c2bc-11ea-9e0d-676df16f763d.png)
> 
> Anybody see this before?

Adding some horizontal padding fixed it for me,

```jsx
<TextInput
      style={{ paddingHorizontal: 12 }}
/>
```
