### ISSUE TITLE
How can i change Button's icon size 

### ISSUE THREAD

**Issue by yoojeen126** [callstack/react-native-paper#1659]
<Button icon="facebook" mode="contained" onPress={() => console.log('Pressed')} color={theme.colors.facebook}>
        Facebook Login
</Button>

I saw icon size default 16, and i know labelStyle to change text. 
So what's prop to change icon size more big?

**Comment by quantjamespecutus** [comment]
agree this would be useful

**Comment by Abban-Fahim** [comment]
Yes it is neccessary
