### ISSUE TITLE
Create a row component for Checkboxes and Radio Buttons

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#166]
If we want to use a checkbox or a radio button with a label, common pattern is that the whole `row` is clickable. We should have a component in place for it.

Example where this behaviour is needed is in the Dialog with Radio Buttons example.

**Comment by felixaa** [comment]
I'd love to jump on this if possibru!🙏🏽

**Comment by Trancever** [comment]
Created pull request for this issue - #219
