### ISSUE TITLE
When a TextInput is inside a Portal, cursor jumps around on edit

### ISSUE THREAD

**Issue by togakangaroo** [callstack/react-native-paper#1668]
[Here is a code sandbox demonstrating the issue](https://codesandbox.io/s/react-native-yw1sy)

Position your cursor at the first character of the TextInput and type `a` several times

Note that while the first appeared at the correct location, afterwards the cursor jumps to the end and you end up with something like `afooaa`. My guess is that the input is (incorrectly) re-mounting.

I'm using this very simple component

```
import React, { useState } from "react";
import { Portal, TextInput, Provider } from "react-native-paper";

export default () => {
  const [data, setData] = useState(`foo`);

  return (
    <Provider>
      <Portal>
        <TextInput value={data} onChangeText={setData} />
      </Portal>
    </Provider>
  );
};
```

When not inside of a `Portal` this works fine. 

It also *sometimes* works fine even in a Portal, I have a team member that tried to fix this issue by modifying our code, and actually got it working from inside a Portal by introducing a ton of duplication and awkward state. I have not been able to narrow down what exactly makes it work again, but this reduced test case shows the incorrect behavior regardless.

**Comment by togakangaroo** [comment]
Using this terrible hack instead of `TextInput` is terrible but seems to work

```
type TextInputInAPortalProps = TextInputProps & {
  value: string
  onChangeText: (t: string) => void

}

// Use this whenever you need a TextInput inside that appears inside of a Portal
//
// Wait what now?
// This seems to fix this bug: https://github.com/callstack/react-native-paper/issues/1668
export const TextInputInAPortal = (props: TextInputInAPortalProps) => {
  const [value, setValue] = useState(props.value)

  useEffect(() => {
    if(value !== props.value)
      setValue(props.value)
  }, [props.value])

  const onChangeText = (text: string) => {
    setValue(text)
    props.onChangeText(text)
  }
  return React.createElement(TextInput, {...props, value, onChangeText})
}
```

**Comment by rubengt01** [comment]
I am seeing this issue too.

**Comment by hermanho** [comment]
This issue also affect when input with CJK languages

**Comment by natedx** [comment]
This is still happening, I have a TextInput inside a Modal itself inside a Portal and I get buggy text edition

**Comment by zombie6888** [comment]
I guess, if you move Portal outside component, somewhere to it's parents, it will work. Try out my workaround from here: https://github.com/jeremybarbet/react-native-portalize/issues/6#issuecomment-761907191

**Comment by jslok** [comment]
Same issue here

**Comment by younes0** [comment]
maybe https://github.com/gorhom/react-native-portal could solve your problem ?

**Comment by mertcankose** [comment]
if you still have an problem with multiline prop use defaultValue={text} instead of value={text}

**Comment by eisodev** [comment]
> if you still have an problem with multiline prop use defaultValue={text} instead of value={text}

This seems to stop the rerender loop. Thank you.

**Comment by adam-kuhn** [comment]
@mertcankose this saved me tons of headache. Do you happen to know why this is the cause?

**Comment by seba9999** [comment]
> if you still have an problem with multiline prop use defaultValue={text} instead of value={text}

With this solution you can't control the text value anymore ... If you want to clear the input for example...
