### ISSUE TITLE
Create a RadioGroup wrapper

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#167]
We can create a RadioGroup wrapper that includes all logic for radio buttons (like only 1 selected at a time).

**Comment by marinsokol** [comment]
I can take a look at this.

**Comment by Trancever** [comment]
Hey, I would like to take this one. Already started working on it.

**Comment by Trancever** [comment]
#214

**Comment by Trancever** [comment]
Created pull request #214 . Need some help with styling.
