### ISSUE TITLE
Typescript issue in Banner component when trying to customize an action button

### ISSUE THREAD

**Issue by gevorgsahakyann** [callstack/react-native-paper#1670]
## Environment
"react-native": "0.61.5",
"react-native-paper": "^3.6.0",
"typescript": "^3.7.5"

## Description
I tried to customize the action button for the Banner component and got the typescript issue. Can't pass other properties except for the label and onPress.

<img width="497" alt="Screen Shot 2020-02-14 at 18 21 07" src="https://user-images.githubusercontent.com/45065751/74541310-d6f12400-4f5a-11ea-9d25-f150cd988ddd.png">

Please set the button's typescript type for banner actions.
<img width="624" alt="Screen Shot 2020-02-14 at 18 20 43" src="https://user-images.githubusercontent.com/45065751/74541323-db1d4180-4f5a-11ea-9392-f6b352b9e650.png">

**Comment by kamui545** [comment]
I noticed the same issue, however, I was wondering: Would it make sense to have the same kind of API as we have for Card?

I think it would be more flexible. But maybe I am missing something / it's not really a good fit / we could just use the Card components...

```html
<Banner>
  <Banner.Content>
    There was a problem processing a transaction on your credit card.
  </Banner.Content>
  <Banner.Actions>
    <Button>Fix it</Button>
    <Button>Learn more</Button>
  </Banner.Actions>
</Banner>
```

**Comment by reutg** [comment]
I am having the same issue.

**Comment by mesamhaid** [comment]
Experiencing this exact same issue. Can we reopen this issue please?

**Comment by mister-conor** [comment]
I think the proposal from @kamui545 would work very well here.

**Comment by ericledonge** [comment]
I'd like to PR a simple solution that I've done in a project with a patch npm, but for that, I also need to modify the file lib/typescript/components/Banner.d.ts and I don't understand how to do it. I am new in open source and typescript worlds. Any help, please?
