### ISSUE TITLE
How to change TextInput :focus state border color ?

### ISSUE THREAD

**Issue by oguzsh** [callstack/react-native-paper#1672]
## Environment
"react-native" : "0.61.5"
"react-native-paper": "^3.5.1"

## Description
I created a focus state and I used the "onFocus()" feature. When I click on the text input, the focus state changed "true" but the "border color" feature didn't change. I don't know why 😢 

Thanks in advance for the answers ❤️ 

## Code

<img src="https://i.ibb.co/rd0gvyc/carbon-1.png" />

**Comment by oguzsh** [comment]
I solved my problem 😆 
I added this code in <TextInput> :
`theme={{colors: {primary: 'green', underlineColor: 'transparent'}}}`

Reference : https://github.com/callstack/react-native-paper/issues/656

**Comment by Apollo1207** [comment]
@oguzsh, thank you!
