### ISSUE TITLE
Checkbox reverse issue with RTL mode on, the Icon is displayed from right to left.

### ISSUE THREAD

**Issue by Ashkan-Oliaie** [callstack/react-native-paper#1675]
## Environment

react-native 61.5
react-native-paper 3.3 , 3.6
android 

## Description

when switching to RTL mode the checkbox icon is displayed in reverse mode !
![Capture](https://user-images.githubusercontent.com/47322896/74604099-f493ca00-50cf-11ea-91e9-fe69eb7f6293.JPG)

I've switched to 3.1.0 in order to get the correct result.

>

**Comment by avirankatzsofi** [comment]
Any update on this issue?
