### ISSUE TITLE
icon source does not work when trying to use rtl using icon name

### ISSUE THREAD

**Issue by kopax** [callstack/react-native-paper#1679]
### Current behaviour

I do not have any icon when writting this:

```jsx
        <Button
          icon={{
            source: 'archive'
          }}
          mode="text"
          color={colors.white}
          title="Tap to undo"
          uppercase
        >
          Tap to undo
        </Button>
```

### Expected behaviour

I expect to have the same behavior as in here:

```jsx
        <Button
          icon="archive'
          mode="text"
          color={colors.white}
          title="Tap to undo"
          uppercase
        >
          Tap to undo
        </Button>
```
### Code sample

I tried to do a snack, but icon are not displayed : https://snack.expo.io/@kopax/courageous-hummus

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | all
| react-native          | expo sdk36
| react-native-paper    | 3.6.0
| node                  | 13.5.0
| npm or yarn           | 6.13.7
| expo sdk              | 36

**Comment by iyadthayyil** [comment]
You should pass `direction` in icon object
See the [docs](https://callstack.github.io/react-native-paper/icons.html#rtl-support)

```js
<Button
          icon={{
            source: 'archive',
            direction: 'rtl'
          }}
          mode="contained"
          uppercase
>
```

**Comment by kopax** [comment]
Thanks a lot
