### ISSUE TITLE
Center avatar inside a list item

### ISSUE THREAD

**Issue by sorxrob** [callstack/react-native-paper#1683]
Hi. How do you guys place an avatar inside a list item? 

Currently, I did like this

```html
<List.Item
    title="First Item"
    description="Item description"
    left={props =><Avatar.Image size={35} source='https://robohash.org/robert' />}
  />
<List.Item
    title="First Item"
    description="Item description"
    left={props =><Avatar.Image size={35} source='https://robohash.org/robert' />}
  />
```

And it looks like this

![Capture](https://user-images.githubusercontent.com/13049130/74800951-11b6db80-5310-11ea-8334-6bc9e3df3bf5.PNG)

As you can see, the avatar is at the upper part of the left prop. Is there an easy way to move it down so it goes at the center of the title and description? Thank you.

**Comment by danieldecsi** [comment]
You can add `alignSelf: 'center'` on the `Image`:

`ts
    <List.Item
      title="First Item"
      description="Item description"
      left={props => <Avatar.Image style={{ alignSelf: 'center' }} size={35} source={{ uri: 'https://robohash.org/robert' }} />}
    />
`

**Comment by sorxrob** [comment]
> You can add `alignSelf: 'center'` on the `Image`:
> 
> ```ts
> <List.Item
>   title="First Item"
>   description="Item description"
>   left={props => <Avatar.Image style={{ alignSelf: 'center' }} size={35} source={{ uri: 'https://robohash.org/robert' }} />}
> />
> ```

This works. Thank you.
