### ISSUE TITLE
Property 'ref' does not exist on type 'IntrinsicAttributes & ...'

### ISSUE THREAD

**Issue by bboure** [callstack/react-native-paper#1692]
Hi, 

I am trying to use `ref` on the `Searchbar` element, but intellisense is giving me the following error: 
````
Property 'ref' does not exist on type 'IntrinsicAttributes & Pick<Props, "style" | "removeClippedSubviews" | "hitSlop" | "onLayout" | "pointerEvents" | "testID" | "nativeID" | "collapsable" | ... 97 more ... | "clearIcon"> & { ...; } & { ...; }
````

here is my code:

````tsx
return (
    <Searchbar
        ref={myRef}
        // other props
    />
);
````

Could this be a bug in the Typing?

Thank you

**Comment by jaulz** [comment]
I think the `ref` property is missing on most components so far. Would you be able to raise a PR and add it also to `Button` etc.?

**Comment by AkalUstat** [comment]
having issue with this as well
