### ISSUE TITLE
Typescript breaks lib/typescript/src/components/HelperText.d.ts

### ISSUE THREAD

**Issue by omerman** [callstack/react-native-paper#1697]
## Environment

A newly created expo project,
![image](https://user-images.githubusercontent.com/6780529/75225252-ea9a5700-57b2-11ea-9db5-c66dda394a23.png)

## Description

![image](https://user-images.githubusercontent.com/6780529/75225023-634ce380-57b2-11ea-8e38-5080dcb363d7.png)

as you can see the ts definitions in `node_modules/react-native-paper/lib/typescript/src/components/HelperText.d.ts`
_default breaks. The generated statement `Pick<Props, string | number | symbol>` is invalid.
Help?

## Reproducible Demo

install this dependency on a project with typescript, run `tsc` command, see it finds errors in the above file.

Help anyone?

**Comment by omerman** [comment]
solved it after changed my tsconfig, So everything works :)

**Comment by tribou** [comment]
@omerman What did you change in your tsconfig?

**Comment by raghavyadavm** [comment]
I added this `skipLibCheck: true` to my tsconfig file to fix this error
