### ISSUE TITLE
How to make Snackbar fit content width?

### ISSUE THREAD

**Issue by twisger** [callstack/react-native-paper#1699]
## Ask your Question

The default behaviour of SnackBar is fit container width, I try to make it fit content width but failed, I found that content is wrapped with a Text component which is styled with `flex: 1` in [here](https://github.com/callstack/react-native-paper/blob/2a29dc6d6bca0cb8f529b192d2af3a1794e61a2a/src/components/Snackbar.tsx#L288).

Is there any solution?Or we can add a props like `contentStyle`

**Comment by muneem90** [comment]
Any solution for this?
