### ISSUE TITLE
TextInput label is center aligned for multiline textInputs

### ISSUE THREAD

**Issue by gautam678** [callstack/react-native-paper#1700]
## Environment
react-native-paper: "3.6.0"
iOS: 13.3.1

## Description
Label for multiline Textareas are aligned to the center. I expected the label to be aligned to the top. I don't see a prop to style label for Textinput either.

![Screen Shot 2020-02-26 at 5 31 43 PM](https://user-images.githubusercontent.com/5861253/75394345-f161c080-58bd-11ea-97b4-3e9f35d8f329.png)

## Reproducible Demo
```import * as React from 'react';
import { TextInput } from 'react-native-paper';

export default class MyComponent extends React.Component {
  state = {
    text: ''
  };

  render(){
    return (
      <TextInput
        label='Email'
        value={this.state.text}
        multiline
        onChangeText={text => this.setState({ text })}
        style={{height:400}}
      />
    );
  }
}```

**Comment by gautam678** [comment]
![centeralign](https://user-images.githubusercontent.com/5861253/75394261-c1b2b880-58bd-11ea-997c-d0f1d2727f18.gif)

**Comment by antaehyeon** [comment]
Hi.

Can you use the render props ?

below example code.

```

import { ..., TextInput } from "react-native";
import { TextInput as PaperTextInput } from "react-native-paper";
 ...

 // just temporarily style
  const PAPER_TEXT_INPUT_STYLE = {
    width: "100%",
    height: 160,
    marginBottom: 15,
    borderRadius: 4
  };

  const RN_TEXT_INPUT_STYLE = {
    width: "100%",
    height: 160,
    fontSize: 14,
    padding: 16,
    ...Platform.select({
      android: {
        textAlignVertical: "top"
      }
    })
  };

  return (
    <PaperTextInput
      style={PAPER_TEXT_INPUT_STYLE}
      multiline={true}
      mode={"outlined"}
      render={props => (
        <TextInput
          {...props}
          style={RN_TEXT_INPUT_STYLE}
          placeholder={PLACE_HOLDER}
          placeholderTextColor={Colors.grey490}
        />
      )}
    />
  );
```
![image](https://user-images.githubusercontent.com/18719042/75417052-66db9880-5973-11ea-8529-f871437f562c.png)

I hope will be applied in the textInput style attribute of the react native paper.

**Comment by gautam678** [comment]
@antaehyeon I tried the code snippet. The label is still center aligned when out of focus.

**Comment by gautam678** [comment]
This PR will fix the issue: https://github.com/callstack/react-native-paper/pull/1824

**Comment by Huxpro** [comment]
@gautam678 unfortunately, the team seems to be slowly responding to PRs.

**Comment by nguyen-vo** [comment]
For those looking for the answer, set the numberOfLine seems to fixed the issue

**Comment by isinha-onefc** [comment]
This issue is still occurring. However, `mode="outlined"` seemed to fix this issue for me on Android.

**Comment by davidgvf** [comment]
you need put heigh in content style and fixed 

contentStyle={
                    props.multiline && {
                        height: 150
                    }
                }

**Comment by FitzroyITDev** [comment]
@davidgvf 's response is the right one, just in case any of you still have this issue with iOS

**Comment by CervarlCG** [comment]
I achieved the desired result playing with `placeholder` and `label` properties depending if the input has content or not (Only works for controlled components)

```ts
...

export default function Textarea(props: InputProps) {
  const [label, setLabel] = useState("");
  const { styles } = useStyles<StyleProps>(createStyles, {
    numberOfLines: props.numberOfLines,
  });

  return (
    <TextInput
      mode="outlined"
      multiline
      style={[styles.textarea, !label ? styles.noLabel : {}]}
      outlineStyle={styles.outline}
      {...props}
      label={label}
      placeholder={!label ? (props.label as string) : " "}
      onFocus={() => setLabel(props.label as string)}
      onBlur={() => !props.value && setLabel("")}
    />
  );
}

const createStyles: CreateStyleSheet<StyleProps> = (theme, props) =>
  StyleSheet.create({
    textarea: {
      backgroundColor: "transparent",
      borderColor: theme.colors.outline,
      paddingVertical: 0,
      height: 48 + 20 * (props.numberOfLines || 1),
    },
    noLabel: {
      marginTop: 8,
    },
    outline: {
      borderRadius: theme.spacing(),
      paddingVertical: 0,
    },
  });

Textarea.Affix = TextInput.Affix;
Textarea.Icon = TextInput.Icon;

```
