### ISSUE TITLE
Having loading on Searchbar and TextInput Components

### ISSUE THREAD

**Issue by kopax** [callstack/react-native-paper#1705]
## Describe the feature

I am using `Searchbar` as follow:

```jsx
        <Searchbar
          placeholder={`${t('homeView.search')}...`}
          value={cityOrPostalCode}
          onChangeText={this.onChangeText}
          loading={1}
          onSubmitEditing={this.submit}
        />
```
 
## Motivation

So far, there is no way to switch the left icon, the right icon, or to add a component within the text to display an asynchronous task.

A use case would be a `<Searchbar />` used for autocomplete, it will fetch some data.

So far I must create my own indicator, which most likely does not respect material ui guidelines

Thanks again for your time,

Dimitri

**Comment by belgamo** [comment]
What do you think about adding a boolean prop such as `inverseIcons`, as a way to switch icons?

**Comment by kopax** [comment]
Why not just icon left and icon right ? :/?

**Comment by belgamo** [comment]
I thought you just wanted changing the position of the icons. There's already exists a prop to do that but the name is not very semantic... Maybe we can restructuring the `icon` and `clearIcon` props so that they can be treated as `leftIcon` and `rightIcon`.

See: https://callstack.github.io/react-native-paper/searchbar.html#icon

**Comment by kopax** [comment]
This features would be so much appreciated, yes that would be awesome. 

I am just thinking, would it be nice to toggle the clear icon with a loading icon while searching something asynchronously (which is almost always the case). I have this proposal in mind:

- Keep `icon` for previous version with a deprectation warning
- Create `leftIcon` that will serv the purpose of `icon`
- Keep `clearIcon` for clearing the search bar
- Add `rightIcon` for example for adding a spinner displayed on the left to the clear icon in the search bar


Allow user to rearrange those 3 icons on it's while

**Comment by brunohkbx** [comment]
@Trancever what do you think about this issue? Allowing the user to change the `rightIcon` shouldn't be a problem at all, right?  Instead of forcing this behavior as I did on #1538

**Comment by brunohkbx** [comment]
@Trancever :point_up:

**Comment by brunohkbx** [comment]
It's still open

**Comment by kopax** [comment]
It's still open

**Comment by zholmes1** [comment]
Yes, a `left` and `right` prop would be super useful on this component. Just like `List.Item`. But a `loading` prop that sticks an `ActivityIndicator` on the right of the `TextInput`/`Searchbar` would cover by far the biggest use case. As of right now, there is really no good way to use the Searchbar in an app that fetches search results every time the text changes.
