### ISSUE TITLE
How use Badge with Button

### ISSUE THREAD

**Issue by GuilhermeAB** [callstack/react-native-paper#1711]
## Ask your Question

How can I use the badge with the button as the first image on:  https://github.com/callstack/react-native-paper/pull/620#issue-224921438

![image](https://user-images.githubusercontent.com/27172892/75839149-d5bb5600-5da6-11ea-8b58-ebbe015c5d3d.png)

**Comment by jaulz** [comment]
Check out the code of the example app: https://github.com/callstack/react-native-paper/blob/master/example/src/Examples/BadgeExample.tsx
