### ISSUE TITLE
Button icon property should allow startIcons and endIcons

### ISSUE THREAD

**Issue by mschipperheyn** [callstack/react-native-paper#1718]
## Describe the feature

icons can either occur at the end of a button or at the start. I would like to see a startIcon and endIcon property.

## Motivation

Not everything is strict Material Design and it's a very common pattern.

**Comment by justindra** [comment]
For usage-wise, it used to be in Material Design guidelines for MobileSteppers. But it's no longer there I guess.

Material-ui is still supporting it.
https://material-ui.com/components/steppers/#mobile-stepper

**Comment by kabus202** [comment]
yep good feature

**Comment by mschipperheyn** [comment]
There is actually a little trick you can do get the end icon effect. Apple a `row-reverse` to the `contentStyle` and add the icon as you would normally. Make sure you pass the icon as an svg component, not an icon name. Place a `View` around it and compensate the now wrong margin on it.
