### ISSUE TITLE
Custom Font setting

### ISSUE THREAD

**Issue by doliolarzz** [callstack/react-native-paper#1720]
I've tried using this config for the Provider
```
const fontConfig = {
  ios: {}, android: {}, web: {},
  default: {
    regular: {
      fontFamily: 'NotoSans-Bold',
      fontWeight: 'normal',
    },
    medium: {
      fontFamily: 'NotoSans-Bold',
      fontWeight: 'normal',
    },
    light: {
      fontFamily: 'NotoSans-Regular',
      fontWeight: 'normal',
    },
    thin: {
      fontFamily: 'NotoSans-Regular',
      fontWeight: 'normal',
    },
  },
};

fontConfig.ios = fontConfig.default;
fontConfig.android = fontConfig.default;
fontConfig.web = fontConfig.default;

const theme = {
  ...DefaultTheme,
  fonts: configureFonts(fontConfig),
};
```

but theme setting in props still unchanged.
Do you have any suggestion?

<img width="351" alt="Screen Shot 2563-03-08 at 22 42 30" src="https://user-images.githubusercontent.com/17764453/76166050-24456780-618e-11ea-87f8-3e167aa0b36f.png">

**Comment by jaulz** [comment]
What does `configureFonts` do?

**Comment by raajnadar** [comment]
Try removing this two lines

`ios: {}, android: {}, web: {},`

```
fontConfig.ios = fontConfig.default;
fontConfig.android = fontConfig.default;
fontConfig.web = fontConfig.default;
```

And replace this lines `fontWeight: 'normal'` with this `fontWeight: 'normal' as 'normal'` ts was complaining after making this changes it worked for me.

**Comment by selrond** [comment]
Can confirm it's not working as expected
