### ISSUE TITLE
Unable to customize the icon and text in Fab.Group

### ISSUE THREAD

**Issue by nihp** [callstack/react-native-paper#1722]
I need to align the Fab with the Image and text.

Here If I increate the size of the image it will simultaneously increasing the width and height of the text box which is in the left to the image.

Here how to align the text and image separately.

I need the image as big siz and text as small.

How can I achieve this?

**Comment by Trancever** [comment]
@nihp This is not compliant with MD Guidelines. You should use patch-package or fork the repo to adjust the component.

**Comment by nihp** [comment]
But forking the repo is not a good practice I think. Because if there is any upgrade in this package it can't reflect in my forked repo.
