### ISSUE TITLE
Modifying with patch-package and Typescript

### ISSUE THREAD

**Issue by vpontis** [callstack/react-native-paper#1724]
I have a React Native project that uses TypeScript. I want to modify the `node_modules/react-native` code and have the changes reflected in my application. 

In `node_modules/react-native` there are 3 different versions of the package: `src` which is TypeScript, `commonjs` and `module`. 

It looks like my project picks up the `module` code, but I'd like it to pick up the `src` which is TypeScript.

Below is my TypeScript configuration. Do I need to update either my TypeScript or Metro configuration?

---

**`tsconfig.json`**

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "jsx": "react-native",
    "lib": ["es2015", "esnext.asynciterable"],
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "strict": true,
    "types": ["react", "jest", "node"],
    "target": "es5",
    "skipLibCheck": true
  },
  "include": ["./@types/**/*.ts", "src/**/*", "App.ts"]
}
````

**Comment by satya164** [comment]
Change this line to point to src https://github.com/callstack/react-native-paper/blob/77fe132d5dbb220ebcac3ae0b83e6432ddfc12c3/package.json#L7
