### ISSUE TITLE
Provide Checkbox.Item as a companion to RadioButton.Item

### ISSUE THREAD

**Issue by evantrimboli** [callstack/react-native-paper#1728]
## Describe the feature

There should be a checkbox component that encompasses the checkbox itself and a label.

## Motivation

Checkboxes often have labels, one would expect tapping the label to change the checked state. It would also be consistent with the existing `RadioButton.Item`.

**Comment by Bound3R** [comment]
and would also be super useful there was a `Checkbox.Group` like the `RadioButton.Group`.

**Comment by evantrimboli** [comment]
For posterity, this was resolved in the linked PR.

https://github.com/callstack/react-native-paper/pull/1844
