### ISSUE TITLE
Add testing suite

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#173]
- [ ] Unit test, specially for our logic in `ThemeProvider`, `withTheme`, etc
- [ ] Detox

**Comment by manjula91** [comment]
I would like to start with snapshot testing for components using jest. @ferrannp Would like your thoughts on the same

**Comment by ferrannp** [comment]
Yeah recently I was thinking to use Jest for some more logical stuff like the theming and so on. And then I was thinking of taking snapshots (but screenshots in this case) using Jest + something like puppeteer. However Snapshots would be faster and we could also write our own output for them.

What would be your preferred approach?

**Comment by satya164** [comment]
> Jest + something like puppeteer

Can't use puppeteer coz it's only for web, right?

**Comment by ferrannp** [comment]
> Can't use puppeteer coz it's only for web, right?

Haha sure I mixed projects but, yea something similar for mobile.

**Comment by manjula91** [comment]
I have worked with Jest? Any thoughts on what could go well with Jest on mobile?
@ferrannp  @satya164

**Comment by manjula91** [comment]
Although if we are just targeting snapshots first we can use react-test-render & move forward. Would like to know both of your thoughts ? @ferrannp @satya164

**Comment by satya164** [comment]
@manjula91 let's go ahead with react-test-render first :)

**Comment by manjula91** [comment]
@satya164 cool

**Comment by manjula91** [comment]
Starting on this weekend. Starting with Portals component

**Comment by satya164** [comment]
@manjula91 I think next could be components with lots of logic in render like `Button`, `Card` and `Toolbar` :)

**Comment by manjula91** [comment]
Cool :)

**Comment by Aidurber** [comment]
Sorry, I know this is an old issue, but would it be beneficial to use Callstack's [react-native-testing-library](https://github.com/callstack/react-native-testing-library)? In my recent PR around TextInput outlines and error states, I thought it would have been beneficial to have some integration tests to test focus and unfocused modes.

**Comment by satya164** [comment]
Yeah, we want to use it, but haven't gotten time :D

Pull requests are always welcome!

cc @esemesek

**Comment by Aidurber** [comment]
@satya164 Already doing some exploratory work. First time using react-native-testing-library, I think I'm in love! Props to Kent C Dodds too! Trying to do meaningful tests with Enzyme + React Native was always a dead-end. 

I'll create a PR if I produce anything meaningful on this TextInput. I won't go through the whole suite, I'll just add some tests for my previous PR and we can evaluate from there.  :)

**Comment by ferrannp** [comment]
We'll split this in different issues.
