### ISSUE TITLE
TouchableRipple with React Navigation no feedback when fast pressed

### ISSUE THREAD

**Issue by kalicki** [callstack/react-native-paper#1730]
## Environment
```
"react-native": "^0.61.5",
"react-native-paper": "^3.3.0",
"react-navigation": "^4.0.10",
```

## Description

Hey,

I was analyzing that when `onPress` is pressed quickly and it is integrated with React Navigation, transacting to another screen (page) does not show any feedback. It only shows if I press for a longer time.

Check: 
![Screen Recording 2020-03-11 at 15 16 38](https://user-images.githubusercontent.com/3674885/76451324-01919980-63ae-11ea-8d91-21d9635f2654.gif)

- - - 
Ps: I tested it with `react-native-material-ripple` and there the feedback form is shown regardless of the time you press. (always shows animation)
Ref: https://github.com/n4kz/react-native-material-ripple

**Comment by brunohkbx** [comment]
@kalicki I think you will need to use [requestAnimationFrame](https://reactnative.dev/docs/performance#my-touchablex-view-isnt-very-responsive) to have a touchable responsive when switching screens.
