### ISSUE TITLE
Snackbar overlaps bottom navigation

### ISSUE THREAD

**Issue by CJMcGregor** [callstack/react-native-paper#1736]
## Environment

Web, iOS, Android

## Description

When using both bottom navigation and snackbar, the snackbar message overlaps the bottom navigation rather than going above it.  

## Reproducible Demo

https://snack.expo.io/ryPAPZ6B8

**Comment by Trancever** [comment]
You need to move it manually using style prop.  Try increasing bottom position or adding some margin. You can post here the solution so other people can see it in the future.

**Comment by CJMcGregor** [comment]
margin bottom did the trick! I'm new to react and was too quick with the report bug trigger finger !
`    <Snackbar
      style={{marginBottom: 65}}
    >`
