### ISSUE TITLE
UnderlineColor not aplicable on InputText with outlined mode

### ISSUE THREAD

**Issue by jcarloTA** [callstack/react-native-paper#1740]
## Environment

    "react-native-paper": "^3.6.0",
    "react": "16.9.0",
    "react-native": "0.61.5",

## Description

I'm tried to change the default color for underline color for the inputText, but this not change. 
but when I change the mode to "flat" the input change the underlineColor
### Code
`              <TextInput
                label=''
                value={this.state.text}
                mode="outlined"
                style={styles.inputStyle}
                underlineColor="#FFFFFF"
                selectionColor="#FFFFFF"
                underlineColorAndroid="#FFFFFF"
                theme={{colors: {primary: '#FFFAF0', text: '#fff'}}}
                onChangeText={text => this.setState({ text })}
              />`

**Comment by anarkrypto** [comment]
For **outlined** InputText use `outlineColor`
