### ISSUE TITLE
Badge on Drawer.Item icon

### ISSUE THREAD

**Issue by usama-asfar** [callstack/react-native-paper#1747]
It would be nicer if there is Badge on Drawer.item icon :-)

**Comment by buffaloDeveloper** [comment]
I had a similar need and created custom component that takes a "badge" prop.

import color from 'color';
import * as React from 'react';
import { View, StyleSheet, StyleProp, ViewStyle } from 'react-native';
import { Text, Badge, TouchableRipple, withTheme } from 'react-native-paper';
import { MaterialCommunityIcons } from '@expo/vector-icons';

const CustomDrawerItem = props => {
  const { colors, roundness } = props.theme;
  const backgroundColor = props.active
    ? color(colors.primary).alpha(0.12).rgb().string()
    : 'transparent';
  const contentColor = props.active
    ? colors.primary
    : color(colors.text).alpha(0.68).rgb().string();
  const font = props.theme.fonts.medium;
  const labelMargin = props.icon ? 32 : 0;

  return (
    <View
      style={[
        styles.container,
        { backgroundColor, borderRadius: roundness },
        props.style,
      ]}
    >
      <TouchableRipple
        borderless
        delayPressIn={0}
        onPress={props.onPress}
        style={{ borderRadius: roundness }}
        // @ts-expect-error We keep old a11y props for backwards compat with old RN versions
        accessibilityTraits={props.active ? ['button', 'selected'] : 'button'}
        accessibilityComponentType="button"
        accessibilityRole="button"
        accessibilityState={{ selected: props.active }}
        accessibilityLabel={props.accessibilityLabel}
      >
        <View style={styles.wrapper}>
          {props.icon ? <MaterialCommunityIcons name={props.icon} size={24} color={contentColor} /> : null}
          <Text
            selectable={false}
            numberOfLines={1}
            style={[
              styles.label,
              {
                color: contentColor,
                ...font,
                marginLeft: labelMargin,
              },
            ]}
          >
            {props.label}
          </Text>
          {props.badge ? <Badge style={{marginLeft: 'auto'}}>{props.badge}</Badge> : null}
        </View>
      </TouchableRipple>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    marginHorizontal: 10,
    marginVertical: 4,
  },
  wrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
  },
  label: {
    marginRight: 32,
  },
});

export default withTheme(CustomDrawerItem);
`
`
