### ISSUE TITLE
Multiline not working on iOS

### ISSUE THREAD

**Issue by nthegedus** [callstack/react-native-paper#1750]
## Environment

React Native Environment Info:
  react-native: 0.59.9
  react-native-paper: 3.6.0

## Description

I'm facing this issue occurring only on iOS, numberOfLines is 1 and multiline is false.
While the input is focused, there's nothing wrong. The problem is when it loses the focus and the text is too long. The input breaks the text in a new line. The text max length is 80.

`<PaperTextInput
        numberOfLines={1}
        multiline={false}
        ...
/>
`
## Demo

![react-native-paper](https://user-images.githubusercontent.com/1063383/77459135-03ac1d00-6dde-11ea-94cf-b25526f68b4c.gif)

**Comment by Trancever** [comment]
I believe this is an issue in RN core. Can you confirm that TextInput from RN with `textAlign` set works properly?

**Comment by StebanDev** [comment]
I can confirm this behavior is only happening with `TextInput` from paper on iOS

**Comment by mmehmetAliIzci** [comment]
Any news on this ?

**Comment by v-anton** [comment]
Seems like 'textAligh': 'left' breaks the behavior of the component. Setting it to 'textAligh': 'auto' helps.

**Comment by vfa-namnk** [comment]
Still appear with react-native-paper 4.0.1

**Comment by wwwenjie** [comment]
Still apper with 4.7.2 also, maybe we can reopen this issue?
Find a way to fix: add textAlign: auto to input style

**Comment by FaisalKhawaj** [comment]
TextInput multiline working fine on android , but not working on ios . 
Here is the code : 
          <TextInput
                    keyboardAppearance="dark"
                    numberOfLines={3}
                    multiline={true}
                    textAlignVertical="top"
                    onChangeText={(val) => setProfileDescription(val)}
                    style={mystyles.simpleTextInput}
                    placeholder="Profile Description" placeholderTextColor="#111B18" />

**Comment by mirzazaman** [comment]
Web need to Add minHeight in style.
Like: 
<TextInput
    multiline={true}
    style={{
        // For iOS
        minHeight: 250,
    }}
    // For Android
    numberOfLines={15}
    dense
    mode="outlined"
    label="Summary"
/>

**Comment by IanDaley** [comment]
This issue is still there!

**Comment by oussamakh96** [comment]
Add maxHeight={35} solve the problem choose the number wiith the Height of your input
