### ISSUE TITLE
Documentation 404 - Everything down

### ISSUE THREAD

**Issue by actuallymentor** [callstack/react-native-paper#1751]
See [docs website](https://callstack.github.io/react-native-paper/index.html).

![image](https://user-images.githubusercontent.com/9071382/77548031-4806ee00-6eae-11ea-9297-ae62898a40fc.png)

**Comment by actuallymentor** [comment]
For anyone coding right now who needs the docs, there is a [wayback machine entry](https://web.archive.org/web/20200126230834/https://callstack.github.io/react-native-paper/index.html).

**Comment by enthussb** [comment]
I am also facing the same issue, the website is completely down.

**Comment by pedrofs** [comment]
Wayback machine entry is also down here.

**Comment by actuallymentor** [comment]
Page is back up.

@Team maybe check if this was an issue with you or Github. They have had some weird outages lately.

Closing until the issue crops up again.
