### ISSUE TITLE
spacing between icon and label of BottomNavigation?

### ISSUE THREAD

**Issue by taeingyu** [callstack/react-native-paper#1754]
## Ask your Question

icon and label look too close when `shifting` is `false`.
I think `renderLabel` should work for this though, any other options?

<img width="352" alt="Screen Shot 2020-03-26 at 6 55 30 PM" src="https://user-images.githubusercontent.com/24571455/77634392-3435b780-6f94-11ea-806c-4550fda1d4e0.png">

**Comment by kaloca** [comment]
I also, need this answer, please reopen issue

**Comment by saurabhnemade** [comment]
I am also looking for something similar. It would be good to have show/hide label by passing props.

**Comment by raajnadar** [comment]
You can try this https://github.com/callstack/react-native-paper/discussions/2428#discussioncomment-430524

**Comment by EddyJens** [comment]
Same issue here, @raajnadar that didn't worked here

**Comment by rossicler-hostalky** [comment]
same issue here, anyone found a solution?
