### ISSUE TITLE
 Portal > Fab.Group prevent any click to happen on the AppBar actions.

### ISSUE THREAD

**Issue by kopax** [callstack/react-native-paper#1762]
### Current behaviour

When using an Appbar with actions (such as back action) and the `<Fab.Group />` included in `<Portal />`, it makes it impossible to click on any actions.

More widely, it makes it impossible to use Fab.Group in my application (or any application that use an AppBar (if not all))

### Expected behaviour

I expect to be able to use the app bar action normally

### Code sample

```jsx
    <View style={[styles.container]} pointerEvents="none">
      <Camera style={styles.container} type={type}>
        <Portal>
          <FAB.Group
            open={Platform.OS !== 'web'}
            icon="camera"
            actions={[
              {
                icon: 'camera-switch',
                onPress: () => {
                  setType(
                    type === Camera.Constants.Type.back
                      ? Camera.Constants.Type.front
                      : Camera.Constants.Type.back,
                  );
                },
              },
            ]}
            onStateChange={() => {} /* required! */}
            onPress={() => alert('take a pic')}
          />
        </Portal>
      </Camera>
    </View>
```

### What have you tried

I have tried to add some `paddingTop: 56` in the parent view, but that just add a blank line and I still can't click on the back action

### Snack reproduction

https://snack.expo.io/@kopax/fascinated-cashew

https://snack.expo.io/@kopax/anxious-pudding

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios android and web
| react-native          | expo sdk 36
| react-native-paper    | 3.6.0
| node                  | v13.11.0
| npm or yarn           | npm 6.13.7
| expo sdk              | 36

**Comment by satya164** [comment]
It doesn't work because you have provided `open={true}` which puts a touchable behind the group. The `open` prop is supposed to be toggled on opening the group by pressing the FAB, and then closed by pressing the touchable.
