### ISSUE TITLE
Convert all examples into Hooks

### ISSUE THREAD

**Issue by nainardev** [callstack/react-native-paper#1766]
.

**Comment by jayu** [comment]
What is your motivation?

**Comment by nainardev** [comment]
Hooks are the future of React

Atleast let me do it. where is source of examples

**Comment by Trancever** [comment]
@nainardev Example for each component is in its source file above the component implementation.

**Comment by Sampath-Lokuge** [comment]
Hi @jayu @Trancever Is this library support React Hooks? I can see lot of examples still show `Class` components? e.g. https://callstack.github.io/react-native-paper/list-accordion.html

**Comment by nainardev** [comment]
This is built on top of React so it supports. But the examples needs to be
refactored

**Comment by Sampath-Lokuge** [comment]
@nainardev I hope you'll do that one by one because Hooks is the Future. Thanks.

**Comment by Sampath-Lokuge** [comment]
@nainardev I hope you'll do that one by one because Hooks is the Future. I'm new to the React and I will use Hooks pattern only. I hope there are a lot of such devs. Thanks.
