### ISSUE TITLE
FontFamily "material" is not a system font and has not been loaded through Font.loadAsync

### ISSUE THREAD

**Issue by kevinvugts** [callstack/react-native-paper#1768]
Re-opening this issue as of the newest version it still doesn't work with expo.  I have undertaken all steps in this ticket that I quoted but it does not seem to have any efect.

Environment
** React Native version:     "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",

**REACT NATIVE PAPER VERSISON** 3.6.0
**EXPO SDK** 36.0.2

Step I have undertaking:

- [x] Restarting pc

- [x] Removing cach, node_modules etc and reinstall everything

- [x] Try to link to the node modules font and load it in expo's loadAsync function like here [https://github.com/oblador/react-native-vector-icons/issues/789#issuecomment-554675931](url)

- [x]  Import font ttf file in local src and link to it with absolute path.

None of the above seems te work and the material font is used in the internals of react-native-paper

### /Users/kevin/Enorm/xclsv-500/node_modules/@expo/vector-icons/build/MaterialIcons.js
```
import createIconSet from './createIconSet';
import font from './vendor/react-native-vector-icons/Fonts/MaterialIcons.ttf';
import glyphMap from './vendor/react-native-vector-icons/glyphmaps/MaterialIcons.json';
export default createIconSet(glyphMap, 'material', font);
//# sourceMappingURL=MaterialIcons.js.map
```

_Originally posted by @kevinvugts in https://github.com/callstack/react-native-paper/issues/1347#issuecomment-606694962_

**Comment by nonameolsson** [comment]
This is how I solved it https://github.com/callstack/react-native-paper/issues/2450#issuecomment-813066356
