### ISSUE TITLE
TextInput in outlined mode : crop text / content can be scroll verticaly

### ISSUE THREAD

**Issue by ludwig-pro** [callstack/react-native-paper#1772]
## Environment
   "react-native-paper": "^3.6.0" on Android

## Description

Text inside textInput can be scroll verticaly and crop when you use `height` with style prop in outlined mode. Look like there is a problem with `paddingVertical`.

```
<TextInput
        mode="outlined"
        placeholder="I'm crop and can scroll verticaly 🙁"
        style={{ height: 64}}
        value={this.state.text}
        onChangeText={text => this.setState({ text })}
      />
```

![20200401_162354](https://user-images.githubusercontent.com/62896243/78148901-ac3d2b00-7435-11ea-8477-46590a94d771.jpg)

## Reproducible Demo
https://snack.expo.io/@lvantours/bug-on-textinput-in-outlined-mode

**Comment by narensprinter** [comment]
Yeah I'm facing same issue.

**Comment by hieuluis96** [comment]
I'm also facing same issue.

**Comment by hieuluis96** [comment]
Anyone have fixed issue ???

**Comment by ludwig-adoria** [comment]
that's still the case on android and web too now
web :
![Capture d’écran 2020-07-09 à 09 16 10](https://user-images.githubusercontent.com/52496289/87009275-3c250a80-c1c5-11ea-8dd5-242d126eb7cf.png)

**Comment by medmo7** [comment]
I also face this issue on android if i reduce the height of the textInput.

**Comment by aleksanderpaliszewski** [comment]
Same problem on Android

**Comment by aleksanderpaliszewski** [comment]
I found an error, `paddingOut` in `react-native-paper/src/components/TextInput/TextInputOutlined.tsx` generates a problem.

**Comment by Sebastian-Neubert** [comment]
I have the same problem. Please reopen this issue.

**Comment by santana125** [comment]
I have the same problem, removing paddingOut worked.

**Comment by AmadeusWM** [comment]
> I found an error, `paddingOut` in `react-native-paper/src/components/TextInput/TextInputOutlined.tsx` generates a problem.

Same problem here, removing `paddingOut` from the `style` argument worked in the <InputLabel>.

**Comment by PEDROFELIX92** [comment]
Estou com o mesmo problema, mas no meu caso esta comendo a primeira letra do input, alguém conseguiu resolver?

Utilizando o paddingOut não deu certo, visto que altera  o padding superior.

**Comment by fillybrese** [comment]
Please re-open issue still present on Release 4.11.2

**Comment by frankl1** [comment]
I had the same problem. I don't know why, but removing the `height` property from the style fixed the scrolling and the cropping.

**Comment by Soft-Gurus** [comment]
same issue is occuring on iOS, setting the height crops characters from bottom

**Comment by Lynnze-24** [comment]
If you just want a smaller textInput,
1. remove height property from TextInput style.
2. add dense = {true} property in TextInput.
This does not solve the bug but will solve some cases when you want just smaller input.

**Comment by JoaoBagvanji** [comment]
> Estou com o mesmo problema, mas no meu caso esta comendo a primeira letra do input, alguém conseguiu resolver?
> 
> Utilizando o paddingOut não deu certo, visto que altera o padding superior.

> Remove o Heading na estilização, para heading: 0, ou não o adiciona

**Comment by rahmanharoon** [comment]
facing this issue..is there any other solution other than removing height

**Comment by MaxInMoon** [comment]
Fixed with 
```
contentStyle={{
 paddingTop: 0,
 paddingBottom: 0,
}}
````

**Comment by marshal-truman** [comment]
> Fixed with
> 
> ```
> contentStyle={{
>  paddingTop: 0,
>  paddingBottom: 0,
> }}
> ```

This worked. Thanks.
