### ISSUE TITLE
vector-icons not appearing react-native 0.62.0 unless i link them with npx react-native link

### ISSUE THREAD

**Issue by hakimhassani97** [callstack/react-native-paper#1773]
## Description
hello team  
just starting out with this beautiful collection  
i installed it using :
`yarn add react-native-paper`
then since i'm on vanilla js i installed the vector icons
`yarn add react-native-vector-icons`
but as the doc says (PS : i'm on react-native 0.62.0):

> Note: If you are using react-native version 0.60 or higher you don't need to link react-native-vector-icons.

i didn't link react-native-vector-icons, so i faced a problem with the **icons not appearing**
## Environment
`"react-native": "0.62.0",`
`"react-native-paper": "^3.6.0",  `
`"react-native-vector-icons": "^6.6.0"`

## Solution
the solution was for me to link vector-icons with
` npx react-native link`
😃

**Comment by raajnadar** [comment]
Link is deprecated and so don't use it. Try this method https://github.com/oblador/react-native-vector-icons/issues/1117#issuecomment-589958315

**Comment by raajnadar** [comment]
I am closing this issue. Keep in mind new version of cli will ask you to un-link all the deps.
