### ISSUE TITLE
Card sizes based on container instead of content resulting in wrong height

### ISSUE THREAD

**Issue by actuallymentor** [callstack/react-native-paper#1775]
## Environment

Android preview app. Not an issue on react-native-web.

## Description

If a `Card` is inside a container that has styles of: `{ flex: 1, alignItems: 'center', justifyContent: 'center', padding: 30 } ` it doesn't size based on it's content but based on the container.

## Reproducible Demo

See [this snack](https://snack.expo.io/@mentor/playful-apples). Note how the web version shows expected behaviour but the android one does not.

**Comment by actuallymentor** [comment]
**Diagnosis**

Digging a big deeper. I looked at the [source](https://github.com/callstack/react-native-paper/blob/master/src/components/Card/Card.tsx) of the card component and replicated it which isolated the issue.

I reproduced the setup of the source code and found that the issue seems to be the `{ flexGrow: 1, flexShrink: 1 }` on the `View` nested in the `TouchableWithoutFeedback` [see snack](https://snack.expo.io/@mentor/eager-carrot)


Full some trial and error (for reference):

- [x] `Surface` components do NOT have this issue [see snack](https://snack.expo.io/@mentor/intrigued-yogurt)
- [x] `Cards` inside a surface component do also have this issue, [see snack](https://snack.expo.io/@mentor/crabby-waffles) (*note: the source code indicates that the card is already wrapped in a `Surface` so doing this double wraps it.* )
- [x] Replicated source code has the issue due to the `View` component [see snack](https://snack.expo.io/@mentor/eager-carrot)

**Suggestion**

I see no reason why a card should have to flexGrow to the size of it's parent.

Change the :

```js
const styles = StyleSheet.create({
  innerContainer: {
    flexGrow: 1,
    flexShrink: 1,
  },
});
```

to

```js
const styles = StyleSheet.create({
  innerContainer: {
    flexGrow: 0,
    flexShrink: 1,
  },
});
```

I am happy to do a PR. Please let me know if you'd like me to.

**Comment by Trancever** [comment]
@actuallymentor Can you try version 3.8 and let us know if the issue is still there? We merged https://github.com/callstack/react-native-paper/pull/1691 that probably fixes it

**Comment by actuallymentor** [comment]
As you can see in [this updated snack running 3.8](https://snack.expo.io/@mentor/nervous-raspberries) the issue persists.

The problem is not the `flexShrink` but the `flexGrow`. There is no need for the inner container to grow since the parents are the size of their children.

As I suggest in my previous comment I think adding `flexGrow: 0` would solve the issue.

**Comment by actuallymentor** [comment]
Issue persists in `3.10.1`, see [this repro](https://snack.expo.io/@mentor/suspicious-popsicle).

Verified:

- Web works fine
- Android misbehaves
- IOS misbehaves

**Comment by simonmasinde** [comment]
This issue still persists in `4.12.2`

**Comment by R4Y-repo** [comment]
issue still persisting in `4.12.4`

**Comment by lukewalczak** [comment]
Closing via: #3469
