### ISSUE TITLE
Warning - Animated : UseNativeDriver was not specified

### ISSUE THREAD

**Issue by stephpasquini** [callstack/react-native-paper#1782]
## Environment

React native : 0.62.1
React native paper : 3.7.0

## Description

I have a new warning message after upgrading my project to React Native 0.62.1:
 Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

## Reproducible Demo

The warning message is fired after clicking on the Button component.

The Button components and few others components don't have useNativeDriver set to true

**Comment by fmsouza** [comment]
I'm experiencing the same thing.

**Comment by shubhamtakode** [comment]
Any work around to fix this temporarily ?

**Comment by fmsouza** [comment]
@shubhamtakode you can always go directly to the file and modify the code. It's ugly and hard, as it's already compiled, but works.

It's in `node_modules/react-native-paper/lib/module/components/Button.js`.
Look for `Animated.timing`, add `useNativeDriver: false` right after `duration:200*scale`.
There are two places to do that, though.

Note: it's not a permanent fix. Whenever you change dependencies or reinstall (npm install) the app it might be cleared again.

**Comment by ntcong91** [comment]
+1 same in react-native 0.62

**Comment by Trancever** [comment]
For now, you can use patch-package. We have an open PR that fixes it but we need to figure out a good strategy for releasing it cause it requires us to drop support for RN < 0.60 which is a breaking change unfortunately.

**Comment by anteeek** [comment]
The issue also seems to affect FAB.Group. The same warning is displayed and the animation is delayed by a bit when the group is expanded

**Comment by MBach** [comment]
> 
> 
> The issue also seems to affect FAB.Group. The same warning is displayed and the animation is delayed by a bit when the group is expanded

and the Chip component too

**Comment by stephpasquini** [comment]
The issue also affects the CheckBox component

**Comment by Trancever** [comment]
Fixed in v3.8

**Comment by stephpasquini** [comment]
I still have some issues with the CheckBoxAndroid component

**Comment by berksafran** [comment]
> I still have some issues with the CheckBoxAndroid component

Me too. CheckBox (CheckBox.Android and CheckBox.IOS) needs an update.

**Comment by Samranvirk44** [comment]
I,m also facing this issue one here to help me?

**Comment by xXFracXx** [comment]
Facing the issue with checkbox.

**Comment by Hasnain-code** [comment]
Solution:

Animated.timing(formHeight,{
    toValue:height/2.5,
    duration:600,
    easing:Easing.bezier(0,1.19,0.74,1.2),
    useNativeDriver:false
  }).start();

**Comment by tranhoangduong1994** [comment]
I'm using 3.10.1 and it seems fixed now.

**Comment by imamrobani** [comment]
RN 0.62
Animated.timing(
			this.state.fadeAnim,
			{
				toValue: 1,
				duration: 2000,
				useNativeDriver: true ---> Add this
			}
		).start()

**Comment by sharmapr25** [comment]
Solution:
 just add useNativeDriver: false to the animation config

`Animated.timing(formHeight,{useNativeDriver:false. //Add this line }).start();`

**Comment by devamiya** [comment]
If still someone is getting this error they can ignore it by placing below two lines of code. 

```
import {YellowBox} from 'react-native';
YellowBox.ignoreWarnings(['Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`']);
```

**Comment by rjbl16** [comment]
is added in app.js in my case and the warnings you want to ignore can be added. 

import { LogBox } from "react-native";

LogBox.ignoreLogs([
  "Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`",
]);

**Comment by rjbl16** [comment]
En mi caso para ignorar esta advertencia, app.js principal y agregue lo siguiente:
import { LogBox } from "react-native";

LogBox.ignoreLogs([
"Animated: useNativeDriver was not specified. This is a required option and must be explicitly set to true or false",
]);

a mi me funciono, espero los ayude.
