### ISSUE TITLE
TouchableRipple is not touchable outside parent view when being inside an absolute view

### ISSUE THREAD

**Issue by 0x01Brain** [callstack/react-native-paper#1795]
## Environment

"react-native": "0.59.10",
"react-native-paper": "^3.7.0",

## Description

When setting TouchableRipple inside an absolute view the TouchableRipple is not touchable outside the parent view.

![NotClickable](https://user-images.githubusercontent.com/13728193/78764145-2e2dd680-7997-11ea-9fd4-9c3d09f98454.PNG)

## Reproducible Demo

This is the code I am using as an example:

`<Card elevation={4}>
            <Card.Cover resizeMode="contain" source={{ uri: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTRDxz5NrZ1gdQOqyodN9Qudpw9Z2HTMsfzBm-D1vURyNQdJtNFJ6OLbS_wTlwr15b36BSDddr9&usqp=CAc" }}></Card.Cover>
            <Card.Content>
                <Title>Maverick Drone</Title>
            </Card.Content>
            <View style={{ flex: 1, position: "absolute", bottom: "-8%", right: 0, flexDirection: "row" }}>
                <View style={{ elevation: 6, shadowOffset: 0.8, position: "relative", justifyContent: 'center', alignItems: "center", backgroundColor: "red", width: 45, height: 45, borderRadius: 80 }}>
                    <TouchableRipple borderless rippleColor={Colors.purple600} style={{ justifyContent: 'center', alignItems: "center" }} onPress={this.onDecrement}>
                        <MatIcon color="white" size={32} name="minus"></MatIcon>
                    </TouchableRipple>
                </View>
                <View style={{ padding: 8 }}></View>            
                <View style={{ elevation: 6, shadowOffset: 0.8, justifyContent: "center", alignItems: "center", borderRadius: 20, backgroundColor: "darkred", width: 60 }}>
                        <Text style={{ fontSize: 18, fontWeight: "bold", color: "white" }}>{this.state.quantity}</Text>
                </View>
                <View style={{ padding: 8 }}></View>
                <View style={{ elevation: 6, shadowOffset: 0.8, position: "relative", justifyContent: 'center', alignItems: "center", backgroundColor: "red", width: 45, height: 45, borderRadius: 80 }}>
                    <TouchableRipple borderless rippleColor={Colors.purple600} style={{ justifyContent: 'center', alignItems: "center" }} onPress={this.onIncrement}>
                        <MatIcon color="white" size={32} name="plus"></MatIcon>
                    </TouchableRipple>
                </View>
            </View>
        </Card>
`

**Comment by Trancever** [comment]
This won't work as far as I know and this is not a Paper issue. React Native itself does not support this.

**Comment by 0x01Brain** [comment]
@Trancever Is there any workaround for this?

**Comment by Trancever** [comment]
@0x01Brain I would suggest to layout buttons in a different way e.g. you can make it a sibling of the View and apply a negative margin to a button.
