### ISSUE TITLE
Bottom Tabs

### ISSUE THREAD

**Issue by ahmedlhanafy** [callstack/react-native-paper#18]
[MD Docs Link](https://material.io/guidelines/components/bottom-navigation.htmll#)
Top tabs from https://github.com/react-native-community/react-native-tab-view

**Comment by ferrannp** [comment]
Should this be here or in https://github.com/react-native-community/react-native-tab-view.

**Comment by Krizzu** [comment]
Correct link:
https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-usage

**Comment by ferrannp** [comment]
Check out this one https://github.com/timomeh/react-native-material-bottom-navigation.

**Comment by ferrannp** [comment]
Let's see what comes from here https://github.com/react-navigation/react-navigation/pull/3414. Maybe if it is as standalone component, both libraries can use it.
