### ISSUE TITLE
TextInput multiline is always vertical padded

### ISSUE THREAD

**Issue by IngenieroLata** [callstack/react-native-paper#1810]
## TextInput multiline is always vertical padded

Is there a way to prevent the vertical paddings for TextInputs multiline? I'm currently fixed to v3.6.0 since I require ellipsis for Card titles and it seems that for multiline TextInputs the content is always padded.

<img width="393" alt="Screen Shot 2020-04-10 at 11 25 22 AM" src="https://user-images.githubusercontent.com/5667514/79006370-a246b680-7b1e-11ea-83a7-882d65bd71b6.png">

Not sure if this is intended. Or how do I prevent this behavior?

**Comment by raajnadar** [comment]
Try adding this to style to `TextInput` component `textAlignVertical: 'top'`

**Comment by IngenieroLata** [comment]
@raajnadar It didn't work for me. I end up using the render prop

```
<TextInput
    {...props}
    style={styles.field}
    render={(innerProps) => (
    <NativeTextInput
        {...innerProps}
        style={[
        innerProps.style,
        props.multiline
            ? {
                paddingTop: 8,
                paddingBottom: 8,
                height: 100,
            }
            : null,
        ]}
    />
    )}
/>
```

**Comment by anshumanworks** [comment]
> @raajnadar It didn't work for me. I end up using the render prop
> 
> ```
> <TextInput
>     {...props}
>     style={styles.field}
>     render={(innerProps) => (
>     <NativeTextInput
>         {...innerProps}
>         style={[
>         innerProps.style,
>         props.multiline
>             ? {
>                 paddingTop: 8,
>                 paddingBottom: 8,
>                 height: 100,
>             }
>             : null,
>         ]}
>     />
>     )}
> />
> ```

What is <NativeTextInput /> component here?

**Comment by Ramesh-Chathuranga** [comment]
Hi, I had the same issue and using render method also fix my issue. but don't use ` innerProps.style`  for styling, and use your own styles. and it will be solved your issue.

**Comment by WillSmithTE** [comment]
Should this be closed? Is using the native TextInput in `render` really the final solution?

**Comment by brunomaismei** [comment]
same problem here 
![image](https://github.com/callstack/react-native-paper/assets/165693180/85f19873-7256-4135-947d-5a7ad732fd14)
