### ISSUE TITLE
Menu.Item is weird, needs reworking

### ISSUE THREAD

**Issue by karimcambridge** [callstack/react-native-paper#1811]
## Environment

Expo CLI 3.17.21 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 13.1.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.7 => 37.0.7
      react: ^16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4

## Description

1. You can't center menu items properly
2. You can't change their colours

![image](https://user-images.githubusercontent.com/4283893/79016612-db465180-7b45-11ea-9c77-188fce43602a.png)

^ Centering issue

## Reproducible Demo

```js
<Menu
				visible={data.available}
				onDismiss={() => {}}
				anchor={{ x: 0, y: 0 }}
				style={{ margin: wp('25%') }}
			>
				<Subheading
					style={{ alignSelf: 'center', textAlign: 'center', padding: 10, paddingTop: 5, paddingBottom: 15, fontFamily: 'open-sans-bold' }}
				>
					Have you arrived at the Kingstown Port?
				</Subheading>
				<Divider />
				<Menu.Item
					onPress={null}
					title='Confirm'
					style={{ color: '#FF0000', alignSelf: 'center' }}
					titleStyle={{ color: '#FF0000' }}
				/>
				<Divider />
				<Menu.Item
					onPress={null}
					title='Cancel'
					titleStyle={{ textAlign: 'center' }}
				/>
			</Menu>
```

# My comments

Looking at the source code, menu items are wrapped in 2 views where you can't change their styling, why? Pretty sure whatever base styling that it needs can be achieved in 1 view.

**Comment by satya164** [comment]
Just use a custom component if you need custom styling. Also don't open issues in projects saying something is "weird". It's rude.

**Comment by karimcambridge** [comment]
Okay, understandable, sorry about the 'weird' comment.

I think this is still an issue, you should be able to center it and change the colours
