### ISSUE TITLE
Menu.Item styling issues

### ISSUE THREAD

**Issue by karimcambridge** [callstack/react-native-paper#1812]
## Environment

Expo CLI 3.17.21 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 13.1.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.7 => 37.0.7
      react: ^16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4

## Description

1. You can't center menu items properly
2. You can't change the component colours

![image](https://user-images.githubusercontent.com/4283893/79016612-db465180-7b45-11ea-9c77-188fce43602a.png)

^ Centering issue

## Reproducible Demo

```js
<Menu
				visible={data.available}
				onDismiss={() => {}}
				anchor={{ x: 0, y: 0 }}
				style={{ margin: wp('25%') }}
			>
				<Subheading
					style={{ alignSelf: 'center', textAlign: 'center', padding: 10, paddingTop: 5, paddingBottom: 15, fontFamily: 'open-sans-bold' }}
				>
					Have you arrived at the Kingstown Port?
				</Subheading>
				<Divider />
				<Menu.Item
					onPress={null}
					title='Confirm'
					style={{ color: '#FF0000', alignSelf: 'center' }}
					titleStyle={{ color: '#FF0000' }}
				/>
				<Divider />
				<Menu.Item
					onPress={null}
					title='Cancel'
					titleStyle={{ textAlign: 'center' }}
				/>
			</Menu>
```

# My comments

Now my last issue got closed, but I figured that was out of annoyance, the Menu.Item has issues, yes I used a custom component instead but it needs to be fixed either way.

- If the centering issue is a design problem fine, but the colour should be changable, no?

**Comment by Trancever** [comment]
color of Menu.Item is configurable using `theme` or `titleStyle` prop. Make sure you use latest version of paper.
