### ISSUE TITLE
TextInput multiline inconsistencies across platform

### ISSUE THREAD

**Issue by Huxpro** [callstack/react-native-paper#1820]
## Description

`<TextInput multiline />` is rendered quite inconsistently across iOS, Android and Web in terms of its behaviors of vertical alignment and padding.

## Reproducible Demo

See <https://snack.expo.io/@huxpro/textinput>

Here are some screenshots showing the inconsistencies

- iOS (all good, single-line content looks the same with or without `multiline`)

![Screen Shot 2020-04-12 at 4 12 07 PM](https://user-images.githubusercontent.com/5563315/79082138-5ccde900-7cd8-11ea-9569-c9dac20d822a.png)

- Android (single-line content looks different with or without `multiline`. This seems related to https://github.com/callstack/react-native-paper/issues/1570 where text always being aligned top under `multiline` and passing in `textVerticalAlign` doesn't work)

![Screen Shot 2020-04-12 at 4 11 30 PM](https://user-images.githubusercontent.com/5563315/79082125-46c02880-7cd8-11ea-875f-92e1ae35e7af.png)

- Web (good for single-line content, but loses padding-bottom for multiline contents...)

![Screen Shot 2020-04-12 at 4 13 19 PM](https://user-images.githubusercontent.com/5563315/79082170-871fa680-7cd8-11ea-9105-b9e3613c45b4.png)

**Comment by daviddossantos** [comment]
hello guys, I created a component that maybe can solve the problem in IOS, take a look at the repository https://github.com/daviddossantos/textinput-multiline-multiplataform
