### ISSUE TITLE
How to increase space between one icon and another icon in material-bottom-tabs

### ISSUE THREAD

**Issue by ppv94** [callstack/react-native-paper#1823]
## Ask your Question
**Current Behavior**
More space is left on Right and Left of the bottom tab bar, I am not able to align space equally between icons as shown in the below image.

![sample](https://user-images.githubusercontent.com/28724702/79115153-be5a8a00-7da2-11ea-8896-42a4ee1ba0dc.png)

**Expected Behavior**
I am using material-bottom-tabs and I want to increase space between one icon and another icon in material-bottom-tabs ( or ) align icons space equally.

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | android
| @react-navigation/native               |^5.1.5
| @react-navigation/material-bottom-tabs |^5.1.8
| react-native-paper                     |^3.8.0
| react-native                           |0.62.1
| node                                   |12.16.1
| npm or yarn                            |6.14.3

**Comment by Trancever** [comment]
I believe this is not possible.  It's implemented according to MD Guidelines and we want to keep it as it is.
