### ISSUE TITLE
Add missing screenshots of the components in the documentation.

### ISSUE THREAD

**Issue by Trancever** [callstack/react-native-paper#1834]
Couple components are missing the screenshots in the documentation. We should provide nice-looking screenshots that will improve the developer experience.

The first part of the ticket is to find out which components are missing screenshots.
The second part is to create them.

**Comment by cmargieson** [comment]
- [x]  ActivityIndicator

- [x] Appbar
- [ ] Appbar.Action 
- [ ] Appbar.BackAction 
- [ ] Appbar.Content 
- [x] Appbar.Header

- [ ] Avatar
- [x] Avatar.Icon
- [x] Avatar.Image
- [x] Avatar.Text

- [ ] Badge 

- [x] Banner

- [x] BottomNavigation

- [x] Button

- [x] Card
- [ ] Card.Actions 
- [ ] Card.Content 
- [ ] Card.Cover 
- [x] Card.Title
 
- [x] Checkbox
- [x] Checkbox.Android
- [x] Checkbox.IOS

- [x] Chip

- [x] DataTable
- [ ] DataTable.Cell
- [ ] DataTable.Header
- [ ] DataTable.Pagination
- [ ] DataTable.Row
- [ ] DataTable.Title

- [x] Dialog
- [ ] Dialog.Actions 
- [ ] Dialog.Content 
- [ ] Dialog.ScrollArea 
- [ ] Dialog.Title 

- [ ] Divider 

- [ ] Drawer 
- [ ] Drawer.Item 
- [ ] Drawer.Section 

- [x] Fab
- [x] FAB.Group

- [x] HelperText

- [x] IconButton

- [ ] TouchableRipple 

- [ ] List 
- [x] List.Accordion
- [ ] List.AccordionGroup 
- [ ] List.Icon 
- [x] List.Item
- [x] List.Section
- [x] List.Subheader

- [x] Menu
- [ ] Menu.Item 

- [ ] Modal 

- [ ] Portal 
- [ ] Portal.Host 

- [x] ProgressBar

- [x] RadioButton
- [x] RadioButton.Android
- [ ] RadioButton.Group 
- [x] RadioButton.IOS
- [ ] RadioButton.Item 

- [x] Searchbar

- [x] Snackbar

- [x] Surface

- [x] Switch

- [x] TextInput

- [x] ToggleButton
- [ ] ToggleButton.Group 
- [ ] ToggleButton.Row 

- [ ] Typography 
- [ ] Text 
- [x] Subheading
- [x] Title
- [x] Paragraph
- [x] Headline
- [x] Caption

**Comment by potatowave** [comment]
I was going to make a new thread, but thought I might as well tack on to this issue.

![chip ui elements](https://callstack.github.io/react-native-paper/screenshots/chip-1.png)

The documentation states 

> Both icon and avatar cannot be specified.

However the image above shows Chips with both avatars and icons.  I consider that the Icon's in the avatar Chip's may simple be nested icons, however the documentation could better articulate this by providing an example as per the included pictures.

**Comment by cmargieson** [comment]
Thanks for the feedback @Trancever, I'm glad the list us useful!

I'd like to see how live previews could be implemented. Do you mind if I try to come up with a PR?

**Comment by mMajch** [comment]
I've created a PR with screenshots that I find missing in docs. For some components, I've decided not to add a new screenshot, as there is another image in the given section that already presents the component.

**Comment by Trancever** [comment]
@cmargieson Yeah, we are always happy to accept PRs from external contributors!
