### ISSUE TITLE
menu items not rendering

### ISSUE THREAD

**Issue by AvneeshD** [callstack/react-native-paper#1838]
```
<Menu
        visible={true}
        onDismiss={this._closeMenu}
        anchor={this.props.passedRef.current}
        style={{ height: 100, backgroundColor: 'red' }}
      >
        <Menu.Item onPress={() => {}} title="Item 1" />
        {console.log('hey')}
        <Menu.Item onPress={() => {}} title="Item 2" />
        <Divider />
        <Menu.Item onPress={() => {}} title="Item 3" />
      </Menu>
```

The menu itself is rendering and so is the console.log statement

EDIT: I am trying to render a dropdown menu from the appbar component using the "dots-vertical" action button

**Comment by Trancever** [comment]
@AvneeshD Not sure if this is causing the issue but anchor doesn't accept a ref. It accepts a React.ReactNode e.g. `<Button />` or object with `x` and `y` properties.

https://callstack.github.io/react-native-paper/menu.html#anchor

**Comment by AvneeshD** [comment]
@Trancever the click functionality is working and hence the menu is rendering with the "red" backgroundColor. It shouldn't render if the problem was with that, right? Also, it renders as transparent if I don't give it a background color. Console logs inside it are logged so I know it is rendering for sure.

**Comment by Trancever** [comment]
@AvneeshD Please provide a [Snack](https://snack.expo.io/) that reproduces the issue.

**Comment by zetaron** [comment]
This [Snack](https://snack.expo.io/!Ow3xJyWm) shows the described behaviour, it is a minimally modified version taken from the [Menu Documentation](https://callstack.github.io/react-native-paper/menu.html) where only the initial `visibility` was changed to `true`

**Comment by macfanatic** [comment]
I'm trying to achieve the same effect, rendering a menu from a `dots-vertical` right action item in the app bar, rendered with `react-navigation` v5.

The key points were:

- rendering the entire header, instead of trying to render a button to then show the menu from the `headerRight` option in react navigation
- calling `useEffect` with the state as a dependency, so that the menu is actually rendered

I followed suggestions in #1327 and was able to get the following component working:

```ts
import { Appbar, Paragraph } from "react-native-paper"
import React, { useState } from "react"

export default function MyComponent({ navigation}) {
  const [menuVisible, setMenuVisible] = useState<boolean>(false)

  useEffect(() => {
    navigation.setOptions({
      header: () => (<Appbar.Header>
        <Appbar.BackAction onPress={() => navigation.goBack() } />
        <Appbar.Content title="Project" />
        <Menu visible={menuVisible} onDismiss={() => setMenuVisible(false) } anchor={<Appbar.Action icon="dots-vertical" color="white" onPress={() => setMenuVisible(true)} />}>
          <Menu.Item title="My Action" onPress={() =>console.info("action triggered") } />
        </Menu>
      </Appbar.Header>)
    })
  }, [menuVisible])

  return (<Paragraph>Testing</Paragraph>)
}
```

**Comment by macfanatic** [comment]
Following up, that replacing `useEffect` with `useLayoutEffect` drastically improved the *feel* of this implementation, as the menu appeared immediately instead of waiting for the next render.

**Comment by Birat77** [comment]
Menu only works if visible is set to true, doesn't work on onDismiss and anchor Button., checked on snack example

**Comment by UmairHussain123** [comment]
> Menu only works if visible is set to true, doesn't work on onDismiss and anchor Button., checked on snack example

same problem

**Comment by Pat-Gekoski** [comment]
I had the same problem. For me the problem was in the dependency array of useLayoutEffect. I was using React Navigation v5 and setting the headerRight component with my Menu. I added the navigation object but forgot to add the visible state.

**Comment by nufair2006** [comment]
has anyone found a solution for this issue?
