### ISSUE TITLE
Unable to select menu over List.Item

### ISSUE THREAD

**Issue by gayucode** [callstack/react-native-paper#1848]
## Description
Using ReactNative Modal to show Some list of options to the user. Using List.Item to render the options. In List.Item I am trying to set menu options for right prop. But unable to select the menu over List.Item

## Reproducible Demo
https://snack.expo.io/@gayathri_perumal/testmenu

**Comment by felixpis** [comment]
I've also encountered this problem. But after some investication looks like the problem not in List.Item, but in Modal.
If you add Menu to list items on the View, everythig works perfect. Looks like Modal overlaps Menu
