### ISSUE TITLE
Disable checkmark icon when chip selected

### ISSUE THREAD

**Issue by AvneeshD** [callstack/react-native-paper#1852]
I don't want the checkmark to appear when I select a chip, I'm already changing it's background color. How can I do that?

**Comment by xXFracXx** [comment]
Can this be done?

**Comment by sharmad1205** [comment]
@AvneeshD  a workaround for this dont use selected option in your chip

**Comment by BishoyBishai** [comment]
set icon with { source: null }

**Comment by Tze-Sien** [comment]
How can I set the selected "tick" icon to be null ?

**Comment by shanedaugherty** [comment]
The tick looks pretty old school. You can get rid of it by passing a function that returns null. But that doesn't remove the padding so unfortunately, the chip text is off-center. 

```
const emptyIcon = () => null

const MyComponent = () => (
  <Chip icon={emptyIcon}
)
```

<img width="59" alt="Screen Shot 2021-05-30 at 9 08 13 PM" src="https://user-images.githubusercontent.com/32719539/120134451-5aa04580-c18b-11eb-9a8f-ef74c720f60f.png">

**Comment by gregorojstersek** [comment]
@BishoyBishai @shanedaugherty It seems that resolving with null or {source: null} creates an empty space on the left. See picture below (first one is without it and second one has it):

![Screenshot 2022-11-14 at 15 43 35](https://user-images.githubusercontent.com/9784551/201689192-420132ef-0926-456b-ac5f-c85d4f6c503c.png)

**Comment by sivakarthikeyanrumango** [comment]
in Latest version you can use `showSelectedCheck={false}` to hide checkmark
