### ISSUE TITLE
Cannot use modal under the backdrop overlay

### ISSUE THREAD

**Issue by kopax** [callstack/react-native-paper#1854]
## Environment

Web

## Description

I am tryint the demo with the modal and it seems the content is displayed under the modal, I have tried to set `zIndex` but it keep being under, see demo for details.

## Reproducible Demo

https://snack.expo.io/@kopax/modal?name=Modal

**Comment by ygerg** [comment]
The text doesn't have any background color, so it appears to be under the backdrop, since the background color is transparent.
Try e.g. `<Text style={{backgroundColor: 'white'}}>Example Modal</Text>`

**Comment by kopax** [comment]
Thanks, this should update the documentation. I wanted to do that but after customizing to make it look like a modal a bit, I noticed the bottom shadow which seems to be added to the main element.

See https://snack.expo.io/@kopax/modal?name=Modal

![image](https://user-images.githubusercontent.com/1866564/82992390-60ef6500-9fff-11ea-84e0-642164e961cb.png)

How do you add margin to the view OR how do you remove the bottom shadow?

**Comment by kopax** [comment]
I am also trying to add an animation from bottom to top, I found the original [modal](https://reactnative.dev/docs/modal.html#animationtype) from `react-native` to be exactly what I want, except it does not have a clickable backdrop to close the overlay that has react-native-paper, see react-native original modal demo [here](https://snack.expo.io/?session_id=snack-session-9nMRCakcg&preview=true&platform=web&iframeId=razcrv10d5&supportedPlatforms=android,ios&name=Modal&description=Example%20usage&waitForData=true)

Do you have any clue on how to achieve such result with react-native-paper modal ?

**Comment by sutgeorge** [comment]
I know this is a late answer @kopax, but others might need this as well.

You can edit the overlay by using the `contentContainerStyle` prop of the `Modal` component. I spent around 2 hours figuring this out, since I needed it as well. Pass the following style into the prop:

```ts
      shadowOffset: {
        width: 0,
        height: 0,
      }
```

and you should be good to go 💯
