### ISSUE TITLE
TextInput without style{width} is full heigh

### ISSUE THREAD

**Issue by Spit-Biagio** [callstack/react-native-paper#1858]
## Description
Hello, im looking to use this component for make a login screen, but when i use a TextInput i get an input with 30width (can to be right) but 100% of height, its no sense, i'm looking to understand if is a bug... since on documentation not is written anything about it, i find an possible issue... if i edit the flex on View the height will change... hope that someone can help me about it, if need more information please tell me.

its possible fix it if i passing a width, but for default where is the problem??

## Reproducible Demo
this is the code:
`import React from 'react';
import {View, Text} from 'react-native';
import BgView from "components/BgView.js";
import {TextInput} from "react-native-paper";
import {getWidthPercentOfScreen} from "../../components/utilis.js";

const LoginView = ({navigation}) => {
  const [email, setEmail] = React.useState();
  return (
    <BgView> //BgView is a my component, the children so
      <View style={{flex:1, justifyContent:"center", alignContent:"center"}} >
        <TextInput
          label='Email'
          value={email}
          onChangeText={text => setEmail(text)}
          style={{backgroundColor:"red"}}
        />
      </View>
    </BgView>
  );
}

export default LoginView;`

![image](https://user-images.githubusercontent.com/47725236/80134841-a43d5a80-859f-11ea-9659-e0634aadc79e.png)

**Comment by eliasws** [comment]
@Spit-Biagio How did you solve it?

**Comment by Spit-Biagio** [comment]
@eliasws need to set the width on textInput...

**Comment by caleb-harrelson** [comment]
Here's a [minimal snack](https://snack.expo.io/LZjAWFpfZ) with the problem. 

It appears that a `View` with the css prop `alignItems: 'center'` up the chain causes this behavior, unless you set `width` to a specific value somewhere below it. In the snack you can set `width` on the second `View` or on the `TextInput`, but if you add `alignItems: 'center'` to the second `View` you must set `width` on the `TextInput` as well.
