### ISSUE TITLE
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

### ISSUE THREAD

**Issue by nurmohammed840** [callstack/react-native-paper#1867]
![Image](https://raw.githubusercontent.com/nurmohammed840/ScreenShots/master/Screenshot%20(32).png)

I got this message after `import {createMaterialBottomTabNavigator} from '@react-navigation/material-bottom-tabs';`

And How can I rid of this warning?

**Comment by hugosbg** [comment]
+1

**Comment by MinaroShikuchi** [comment]
#638

**Comment by kamui545** [comment]
@github-actions the issue is still there, please do not close.

Also, here's a related PR: https://github.com/callstack/react-native-paper/pull/1851

**Comment by unikvozm** [comment]
The fixes are merged and will be available in the next release soon =)
