### ISSUE TITLE
Enhanced Theme Capabilities

### ISSUE THREAD

**Issue by karrettgelley** [callstack/react-native-paper#1869]
## Describe the feature
I have been building react apps for a while a my go to has always been [material-ui](https://material-ui.com/). It is a fantastic implementation of the Material spec. In particular, the theme provider is absolute butter, so smooth. Anyways, now I'm building a react-native app and as far as I can tell, react-native-paper is the premiere component framework analogous to material-ui. I would love to see a similar implementation of the theme provider with things like spacing, tertiary color themes (e.g. primary.dark, primary.main, primary.light, etc), and typography templates for web fonts (i.e. h1, h2, etc.). All of this with the ability to hook into a StyleSheet:

```
const useStyles = makeStyles(theme => ({
  buttonx: {
    paddingTop: theme.spacing(2)
  }
}));

function MyComponent() {
  const classes = useStyles();
  return (
    <Button style={classes.buttonx}>a button with padding</Button>
  );
}
```

It's really troublesome to have to do inline styling if I want to have access to the theme with react-native-paper. Also, it would be great if I could extend the capability of the theme by adding my own definitions and have them be picked up by typescript. I understand that I can add my own custom props like so:

```
import { DefaultTheme } from 'react-native-paper';
const theme = {
    ...DefaultTheme,
  spacing: [0, 4, 8, 16, 32, 64],
}
```

but I am unable to get typescript to notice the spacing props of my theme. 

## Motivation

My request is motivated by my love for material-ui. Again, it is a great framework. I'm not sure if any of the devs here have used it or are familiar with the material-ui team, but it is second to none in the react world. By the looks of it, react-native-paper is on its way to becoming held in the same light as material-ui and I would love to see a similar feature set for its theme provider.

**Comment by ryanvanderpol** [comment]
I'd love to see more semantic coloring for components (especially buttons) in the form of a `error`, `success`, `warning`, options like Material UI.

I've also found the global theming to be rather limiting. As far as I can tell, there is no way to define spacing, change elevation, border colors, border widths, icon sizes, etc. with a theme.

**Comment by MohammedFaragallah** [comment]
Here `makeStyles` WIP simple implementation

```ts
import { StyleSheet } from "react-native";
import { useTheme } from "react-native-paper";

// TODO: props type

export const makeStyles = <
  T extends StyleSheet.NamedStyles<T> | StyleSheet.NamedStyles<any>,
  P extends any = any
>(
  cb:
    | ((
        theme: ReactNativePaper.Theme,
        props?: P
      ) => T | StyleSheet.NamedStyles<T>)
    | StyleSheet.NamedStyles<T>
    | T
) => {
  return (props?: P) => {
    const theme = useTheme();

    if (typeof cb === "function") return StyleSheet.create(cb(theme, props));

    return StyleSheet.create(cb);
  };
};
```
