### ISSUE TITLE
Babel plugin not working anymore

### ISSUE THREAD

**Issue by jaulz** [callstack/react-native-paper#1877]
## Environment

react-native-paper@3.9.0

## Description

With the latest release the babel plugin is not working anymore:
```
Failed to compile.
/Users/Julian/Documents/dev/.../src/components/index.ts
Module not found: Can't resolve 'react-native-paper/lib/module/components/Checkbox' in '/Users/Julian/Documents/dev/.../src/components'
```

I assume it's related to this PR: https://github.com/callstack/react-native-paper/pull/1844

## Reproducible Demo

Use `babel.config.json`:
```
module.exports = {
  plugins: [
    // Use single imports from react-native-paper
    'react-native-paper/babel',
  ],
}
```

**Comment by iamshrikantjha** [comment]
Hi @jaulz I am not sure but try to rename file as babel.config.json as babel.config.js
