### ISSUE TITLE
Error: Unable to resolve module ./components/Checkbox from node_modules\react-native-paper\lib\module\index.js

### ISSUE THREAD

**Issue by hugosbg** [callstack/react-native-paper#1879]
## Environment
react-native: 0.62.2
react-native-paper: 3.9.0

## Description
`Error: Unable to resolve module ./components/Checkbox from node_modules\react-native-paper\lib\module\index.js`

Error after updating from **3.8.0** to **3.9.0**

> Note: I've tried, cleared the cache and deleted node_modules and reinstalled.

![image](https://user-images.githubusercontent.com/14058763/80849553-fc064200-8bed-11ea-9a18-1e4e079ea62a.png)

**Comment by nashsaint** [comment]
got same error

**Comment by pitpitpat** [comment]
Same here. The app is built using Expo

**Comment by mafideju** [comment]
First i get rid of node modules `rm -rf node_modules`, then package-lock `rm package-lock.json` but nothing happens. 

Using the command `expo upgrade`, which does delete node_modules and package-lock, then reinstall packages automatically suddenly things back to work on.
Ensure to have your node_modules in place before runing this command. It needs to find the expo package at node_modules to proceed in updating.

You'll notice whats happening reading the message log after running `expo upgrade`.

**Comment by ivks** [comment]
**NOT A SOLUTION TO THE PROBLEM JUST AN FYI**
I reverted back to version 3.8.0 to fix this issue for now, as this started showing up after I updated it to 3.9.0. I will keep following this thread for the real solution.

**Comment by mafideju** [comment]
> **NOT A SOLUTION TO THE PROBLEM JUST AN FYI**
> I reverted back to version 3.8.0 to fix this issue for now, as this started showing up after I updated it to 3.9.0. I will keep following this thread for the real solution.

Just upgrade expo. There is an incompatibility with react-native-paper and an other dozen of packages.

**Comment by prashen** [comment]
I am gettig this error in create react native not in expo today. What is the solution to fix. Anyone?

**Comment by vincenzopalazzo** [comment]
+1

**Comment by leonoronhas** [comment]
> **NOT A SOLUTION TO THE PROBLEM JUST AN FYI**
> I reverted back to version 3.8.0 to fix this issue for now, as this started showing up after I updated it to 3.9.0. I will keep following this thread for the real solution.

How did you revert back? I'm too tried everything possible and still nothing...
My exact error is  - Unable to resolve "react-native-paper/lib/typescript/src/components/MaterialCommunityIcon"

**Comment by brightsider** [comment]
+1

**Comment by hadpro24** [comment]
Somebody are resolve this problem ?

**Comment by notjulian** [comment]
> Somebody are resolve this problem ?

yes with this [#1882](https://github.com/callstack/react-native-paper/issues/1882)

`npx react-native start --reset-cache`

**Comment by Return-1** [comment]
i too am facing this at 3.11.0

**Comment by adnansudozai** [comment]
delete node module folder from your project 
and type npm install in your project cmd
