### ISSUE TITLE
Module not found in react-native-paper

### ISSUE THREAD

**Issue by CodeKazuko** [callstack/react-native-paper#1881]
I keep getting module not found error.

./node_modules/react-native-paper/lib/module/constants.js
Module not found: Can't resolve 'react-native' in 'C:\Users\hille\Desktop\virus-attack - Copy\node_modules\react-native-paper\lib\module'

This is my package.json file. I try deleting package-lock.json and yarn.lock, then npm install to get rid of error.  I have react in my node modules. Is there something I need to download or because I download too many things in react?

{
  "name": "virus-attack",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@ionic-native/core": "^5.24.0",
    "@ionic-native/native-audio": "^5.24.0",
    "@mdi/font": "^5.1.45",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "classnames": "^2.2.6",
    "materialize-css": "^1.0.0",
    "mdi-react": "^7.1.0",
    "node-sass": "^4.13.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-helmet": "^6.0.0",
    "react-hooks": "^1.0.1",
    "react-native-paper": "^3.9.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.8.3"
  }
}

**Comment by pan-pawel** [comment]
Hello @CodeKazuko, your package.json looks like pure react project. React Native paper is a library for [native](https://reactnative.dev/) usage. If you want to use paper with web, you need to follow  [this](https://callstack.github.io/react-native-paper/using-on-the-web.html) guideline. But all of these are based on React native not React projects.

**Comment by CodeKazuko** [comment]
thank you for replying!
