### ISSUE TITLE
onPress not detected on position: absolute element inside Menu's anchor property

### ISSUE THREAD

**Issue by mohanyadav** [callstack/react-native-paper#1883]
## OnPress not working on position absolute element inside Menu anchor
![image](https://user-images.githubusercontent.com/11350400/80909916-b2326e80-8d49-11ea-9249-102a5a774930.png)

I have a FAB button(the purple button in the image above with the horizontal menu icon) that has a position: absolute and it is inside a Menu element.  The onPress event is not triggered when it is inside the Menu's anchor property. If I change the FAB's position to relative then the onPress events are triggered.

## Code
````
<Menu
    visible={this.state.profile_edit_menu_visible}
    onDismiss={this._dismissProfileMenu}
    anchor={
        <FAB
            icon="dots-vertical"
            color="#FFFFFF"
            small
            style={styles.infoBtn}
            onPress={() => {
            console.log("Pressed...");
            this._showProfileMenu();
            }}
        />
    }
>
    <Menu.Item ... />
    <Menu.Item ... />
</Menu>
````
I am not able to get this working in any way. I don't want to change it to a normal button, so appreciate any workarounds and suggestions.
Thanks

**Comment by luisiacc** [comment]
I have this issue as well, when position is absolute onPress just does not work, but it does work when set to relative, is there any workaround  to this ?

**Comment by MrTilllus** [comment]
I have this issue as well.

**Comment by luisiacc** [comment]
This is still an issue

**Comment by ramazan-sambapos** [comment]
Hi I solved my  problem, are you trying to change the z-index property of its FAB?

**Comment by jdbarras** [comment]
Very late to this, but I wrapped my entire `Menu` in a `View` and gave the `View` absolute positioning and it fixed this for me.

**Comment by abdulbasit01** [comment]
when we adjust the button with position property it is visible for us but no event is
 reached on it which means it is a dead button add one more property in in the style component which is the z-index or in javascript it is zIndex 
fab: {
        position: 'absolute',
        margin: 16,
        right: 0,
        bottom: 20,
        zIndex:10,
      },

**Comment by techfortified** [comment]
> I have this issue as well, when position is absolute onPress just does not work, but it does work when set to relative, is there any workaround to this ? btw, my fab is just inside a View.

anyone still facing this issue should add zIndex: 99 to the css props.

**Comment by michael-duren** [comment]
I've been having this issue with a dropdown menu I'm trying to create. 
I've literally rearranged all the elements every way I can think, tried adding different z indexes, nothing works unless I just remove position absolute, which I need for a dropdown..
