### ISSUE TITLE
The Demo App is not Rendering Example Components

### ISSUE THREAD

**Issue by valoricDe** [callstack/react-native-paper#1893]
## Environment

Browser: Firefox latest

## Description

The page https://callstack.github.io/react-native-paper/index.html links to an snack expo demo site. In the web view it gives following error:
![Screenshot 2020-05-05 at 11 27 58](https://user-images.githubusercontent.com/22564188/81058326-81c80d00-8ece-11ea-8722-1034052397fb.png)

## Reproducible Demo

https://snack.expo.io/@satya164/github.com-callstack-react-native-paper:example

Is this a know issue?

**Comment by Vn-ChemGio** [comment]
using expo in IOs has error too,

**Comment by mMajch** [comment]
The snack is outdated - it uses react-native-paper 3.3.0. I created a new one that uses the latest version and everything seems to work https://snack.expo.io/@mmajch/github.com-callstack-react-native-paper:example 

@satya164 I see that you created the current snack. You can export mine and update yours.

**Comment by mMajch** [comment]
The snack is outdated - it uses react-native-paper 3.3.0. I created a new one that uses the latest version and everything seems to work https://snack.expo.io/@mmajch/github.com-callstack-react-native-paper:example

@satya164 I see that you created the current snack. You can export mine and update yours.

**Comment by valoricDe** [comment]
https://github.com/callstack/react-native-paper/pull/1976/files is not merged yet. So yes please stay open

**Comment by valoricDe** [comment]
@Trancever could you reopen this, and or merge this one-liner? https://github.com/callstack/react-native-paper/pull/1976
