### ISSUE TITLE
Snackbar Opacity

### ISSUE THREAD

**Issue by lnickdnguyen** [callstack/react-native-paper#1902]
## Ask your Question

I am using dark theme and for some reason my snackbars have an opacity less than one (making the content below visible). Is there a way to make the snackbar a solid color (opacity = 1)?

**Comment by mohanyadav** [comment]
Use the onSurface color property in theme to edit the color of the Snackbar

**Here I am reducing the opacity of the Snackbar**
```javascript
theme={{
    colors: {
        onSurface: "rgba(0, 0, 0, 0.4)",
    },
}}
```

**Output**
![image](https://user-images.githubusercontent.com/11350400/81951494-d7b15900-9622-11ea-88e6-4abe277859fc.png)


**In your case, you can set the opacity to 1 in the onSurface property to make it a solid color**
**In the example below I have changed the color of the Snackbar and the Text**
```javascript
theme={{
    colors: {
      onSurface: "rgba(0, 204, 204, 1)",
      surface: "black",
    },
}}
```

**Output**
![image](https://user-images.githubusercontent.com/11350400/81951417-c23c2f00-9622-11ea-8788-7aaab2ff965c.png)


**Snackbar Code for Reference**
```javascript
<Snackbar
    visible={visible}
    onDismiss={this._onDismissSnackBar}
    action={{
        label: "Undo",
        onPress: () => {
            // Do something
            console.log("Hello");
        },
    }}

    theme={{
        colors: {
            onSurface: "rgba(0, 0, 0, 1)",
        },
    }}
>
    I'm a Snackbar.
</Snackbar>
```

**Output**
![image](https://user-images.githubusercontent.com/11350400/81951871-54443780-9623-11ea-8cf4-38cb0d261854.png)

**Comment by lnickdnguyen** [comment]
> Use the onSurface color property in theme to edit the color of the Snackbar
> 
> **Here I am reducing the opacity of the Snackbar**
> 
> ```js
> theme={{
>     colors: {
>         onSurface: "rgba(0, 0, 0, 0.4)",
>     },
> }}
> ```
> 
> **Output**
> ![image](https://user-images.githubusercontent.com/11350400/81951494-d7b15900-9622-11ea-88e6-4abe277859fc.png)
> 
> **In your case, you can set the opacity to 1 in the onSurface property to make it a solid color**
> **In the example below I have changed the color of the Snackbar and the Text**
> 
> ```js
> theme={{
>     colors: {
>       onSurface: "rgba(0, 204, 204, 1)",
>       surface: "black",
>     },
> }}
> ```
> 
> **Output**
> ![image](https://user-images.githubusercontent.com/11350400/81951417-c23c2f00-9622-11ea-8788-7aaab2ff965c.png)
> 
> **Snackbar Code for Reference**
> 
> ```js
> <Snackbar
>     visible={visible}
>     onDismiss={this._onDismissSnackBar}
>     action={{
>         label: "Undo",
>         onPress: () => {
>             // Do something
>             console.log("Hello");
>         },
>     }}
> 
>     theme={{
>         colors: {
>             onSurface: "rgba(0, 0, 0, 1)",
>         },
>     }}
> >
>     I'm a Snackbar.
> </Snackbar>
> ```
> 
> **Output**
> ![image](https://user-images.githubusercontent.com/11350400/81951871-54443780-9623-11ea-8cf4-38cb0d261854.png)

@mohanyadav Hey thanks for the tip! Unfortunately, I still am seeing items beneath the snackbar, even after setting the opacity to 1 as you mentioned. Any other ideas?

**Comment by TheHuns** [comment]
Thanks @mohanyadav! I could not figure out how to change the text color of my message...why would that call it `surface`...Thanks for the post!

**Comment by ShivamGoyal26** [comment]
Thank you very much! it has solved my problem :)

**Comment by Malik-Usman17** [comment]
> Use the onSurface color property in theme to edit the color of the Snackbar
> 
> **Here I am reducing the opacity of the Snackbar**
> 
> ```js
> theme={{
>     colors: {
>         onSurface: "rgba(0, 0, 0, 0.4)",
>     },
> }}
> ```
> 
> **Output** ![image](https://user-images.githubusercontent.com/11350400/81951494-d7b15900-9622-11ea-88e6-4abe277859fc.png)
> 
> **In your case, you can set the opacity to 1 in the onSurface property to make it a solid color** **In the example below I have changed the color of the Snackbar and the Text**
> 
> ```js
> theme={{
>     colors: {
>       onSurface: "rgba(0, 204, 204, 1)",
>       surface: "black",
>     },
> }}
> ```
> 
> **Output** ![image](https://user-images.githubusercontent.com/11350400/81951417-c23c2f00-9622-11ea-8788-7aaab2ff965c.png)
> 
> **Snackbar Code for Reference**
> 
> ```js
> <Snackbar
>     visible={visible}
>     onDismiss={this._onDismissSnackBar}
>     action={{
>         label: "Undo",
>         onPress: () => {
>             // Do something
>             console.log("Hello");
>         },
>     }}
> 
>     theme={{
>         colors: {
>             onSurface: "rgba(0, 0, 0, 1)",
>         },
>     }}
> >
>     I'm a Snackbar.
> </Snackbar>
> ```
> 
> **Output** ![image](https://user-images.githubusercontent.com/11350400/81951871-54443780-9623-11ea-8cf4-38cb0d261854.png)

Looking for this , thanks,
Can you please tell me how I can change the height and width of snackbar.
