### ISSUE TITLE
react-native-paper expo demo snack fails

### ISSUE THREAD

**Issue by davvit** [callstack/react-native-paper#1910]
## Description

opening snack from react-native-paper home page and then scanning expo QR on android phone.

## Error
![image](https://user-images.githubusercontent.com/4433698/81590016-c72d8400-937f-11ea-95e1-476f0f5d7823.png)

**Comment by raajnadar** [comment]
I tried but the application opened without any problem. Can you please test it again, it seems like an issue from react navigation that was fixed in the past.
