### ISSUE TITLE
Example App - react-native-paper not listed in package.json dependencies?

### ISSUE THREAD

**Issue by joshglenn** [callstack/react-native-paper#1912]
The example app in this repo: I noticed it does not have `react-native-paper` in its package.json dependencies. 

I am trying to troubleshoot a problem, and I'm hoping that by finding the answer to this question, it will lead me to a solution.

The structure of the repo here to me does not appear like a typical monorepo, so I am wondering: how does the example app know where to find 'react-native-paper'?

**Comment by joshglenn** [comment]
After looking into it more, It looks like the example app 's dependency on react-native-paper is being met using a babel module transformer defined in babel.config.js. Is that right? Is that all there is to it?

**Comment by satya164** [comment]
Yes, it's aliased to `src`.
