### ISSUE TITLE
Stylization of TextInput

### ISSUE THREAD

**Issue by luka-rmar** [callstack/react-native-paper#1913]
I can't change the color of the label, the characters inside the input, the borders. What procedure to style TextInput?

**Comment by mohanyadav** [comment]
You can use the Theme property in the TextInput

Here I have changed  the color to red

```javascript
theme={{
  colors: {
    primary: "red",
  },
}}
```

**Output**
![image](https://user-images.githubusercontent.com/11350400/81795983-6ee6b580-952a-11ea-912d-0f1c4a616a59.png)

**Full TextInput Code for Reference**
```javascript
<TextInput
  mode="outlined"
  label="Name*"
  value={this.state.name}
  theme={{
    colors: {
      primary: "red",
    },
  }}
  onChangeText={(name) => {
    this.setState({
      name,
    });
  }}
  style={styles.customStyles}
/>
```
