### ISSUE TITLE
Icons are not showing

### ISSUE THREAD

**Issue by imsam67** [callstack/react-native-paper#1914]
This is a fresh `React Native` app using `React Native Paper`. I followed the instructions at https://callstack.github.io/react-native-paper/getting-started.html and installed `react-native-paper` and `react-native-vector-icons`. The app is using `react` 16.11.0 and `react-native` 0.62.2.

For some reason, none of the icons are showing in the app -- see below:
![Annotation 2020-05-13 092453](https://user-images.githubusercontent.com/15844030/81842319-0d621f00-9509-11ea-8a07-cecc36ecb3e3.jpg)

For example, I have a `Searchbar` at the top of this screen with the following code. As far as I can see, I don't even have to specify an icon there. It should automatically display a magnifying glass but no icon is showing.

`<Searchbar placeholder="New to do item..." />`

Any idea why?

**Comment by mohanyadav** [comment]
Can you post the entire class code here? That would be helpful in evaluating the problem.
A quick question - Are you wrapping your root component in Provider?

**Comment by imsam67** [comment]
This fixed the issue: https://github.com/oblador/react-native-vector-icons#android
