### ISSUE TITLE
Chrome adding blue border around TextInput

### ISSUE THREAD

**Issue by zelin** [callstack/react-native-paper#1917]
## Environment
 "react-native-paper": "^3.9.0",
 "react-native-web": "~0.11.7",
Expo

## Description
I am using InputText as
```

<TextInput
					style={{outlineColor: 'rgba(0,0,0,0)', outlineOffset: 0, outlineStyle: 'none', 
							outlineWidth: 0, backgroundColor: 'white'}}
					theme={this.textValidationTheme(styles)}
					mode="flat"
					ref={o => (this.txtInput = o)}
					label={this.props.label}
					//placeholder={this.state.isFocused ? "" : this.props.label}
					value={this.state.text}
					onFocus={this.onFocus}
					onChangeText={this.onChangeText}
					onBlur={this.onBlur}
					onSubmitEditing={this.onSubmit}
					underlineColor={color.lightGray}
					{...this.props.textInputProps}
				/>

```

It seems that chrome is adding a default blue outline and no modification in outline settings seem to be working..

<img width="499" alt="Screenshot 2020-05-15 at 5 24 06 AM" src="https://user-images.githubusercontent.com/1249435/81998707-a6f61180-966c-11ea-9fd4-e7c02792c50c.png">

**Comment by jbinda** [comment]
[here](https://github.com/callstack/react-native-paper/issues/1377) is the walkaround for this. Not sure if we can pass some prop to disable this shadowBox when focused

**Comment by timsonater** [comment]
I fixed this with no libs by doing 

```
<TextInput
   outline="none"
/>
```

**Comment by timsonater** [comment]
with react native web you can do:
<TextInput
   style={{outline: "none"}}
/>

**Comment by jbinda** [comment]
@zelin can you confirm if above solution works for you ?

**Comment by thorxtecnologia** [comment]
> with react native web you can do:
> 
> ```
> <TextInput
>    style={{outline: "none"}}
> />
> ```

it doesn't work

**Comment by jcarraway** [comment]
`outlineWidth: 0,` worked for me

**Comment by satya164** [comment]
The focus ring is important for accessibility. If you are removing it, you need to make sure that you're not removing it for keyboard users.

You can use this polyfill to achieve this https://github.com/WICG/focus-visible

**Comment by Jonatthu** [comment]
This is still not working for me

**Comment by brandonpearcy** [comment]
I'm stuck with this issue as well. Any known workarounds?

**Comment by brandonpearcy** [comment]
I was able to disable the default blue highlight on `react-native-paper` TextInputs when using `react-native-web` like so:

App.css
```
.disable-outline input {
    outline-width: 0;
}
```

CustomTextInput.tsx
```
return (
      <div className={'disable-outline'}>
        <TextInput .../>
     </div>
);
```

**Comment by Menganitou** [comment]
@brandonpearcy I'm having problems with your solution. Do I need a babel plugin or something related to transpile the App.css file? Even on the web it throw an error when i write `import './App.css';` .

I have replicated your solution but using instead a package called  [emotion](https://emotion.sh/docs/globals) that allows me to embed global css styles in web format without babel plugins. This is just another workaround.

Here it's a live example on expo snack [link](https://snack.expo.io/@menganitou/without-outline-2)

**Comment by brandonpearcy** [comment]
My solution works in a modern `create-react-app` environment. If I understand correctly, under the hood, CRA is using CSS Modules. More info here: https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/
If you're using a different CSS framework, you'll almost certainly have to adjust the solution. Thanks for sharing a solution using Emotion!

**Comment by kamalthebidigital** [comment]
<img width="705" alt="Screenshot 2020-09-09 at 6 20 12 PM" src="https://user-images.githubusercontent.com/66624803/92600394-2ae1a280-f2c9-11ea-9313-36818aa2d81d.png">
This is not working, please help.

**Comment by ahlun** [comment]
> I was able to disable the default blue highlight on `react-native-paper` TextInputs when using `react-native-web` like so:
> 
> App.css
> 
> ```
> .disable-outline input {
>     outline-width: 0;
> }
> ```
> 
> CustomTextInput.tsx
> 
> ```
> return (
>       <div className={'disable-outline'}>
>         <TextInput .../>
>      </div>
> );
> ```

This works. Also, needs to add `textarea` to the CSS selector too if your `TextInput` is configured as  `multiline`. e.g. add the following to the css:
```
.disable-outline textarea {
    outline-width: 0 !important;
}
```
