### ISSUE TITLE
Specify the Portal.Host in which to render?

### ISSUE THREAD

**Issue by divonelnc** [callstack/react-native-paper#1918]
## Can I specify in which `Portal.Host` I want a `Portal` to render?

I have a `Portal.Host` **A** at the root of my app and another `Portal.Host` **B** further down the component hierarchy.

I have a `Portal` that would like to render in Portal.Host **A**, but it currently gets rendered in B (because B is a closer ancestor).

Can I somehow specify that I want this Portal to render in A?

**Comment by divonelnc** [comment]
Still no answer, so I would like to keep it open :).

**Comment by alimertcakar** [comment]
Still nothing?

**Comment by divonelnc** [comment]
I ended up using a mix of react-native-paper Portal host and `https://github.com/chardskarth/react-gateway` (not the cloudfare one, cause it's outdated).

Gateway is not perfect, but it lets you specify where to render. When I don't need to specify a portal and Gateway is not providing satisfying results, I use RNPaper Portals.

**Comment by thoughtworks-tcaceres** [comment]
@divonelnc Were you able to find a solution by any chance? Running into this issue now.
