### ISSUE TITLE
Make bg color selection/property more obvious

### ISSUE THREAD

**Issue by ORESoftware** [callstack/react-native-paper#1919]
The property "color" doesn't yield any suggestions:

<img width="741" alt="Screen Shot 2020-05-15 at 3 26 11 PM" src="https://user-images.githubusercontent.com/11139560/82101160-95d6f000-96c0-11ea-9fef-46391e82b5f7.png">

I can't guess how to change the bg color from black to another color, I have to google it which is less than ideal.

**Comment by firede** [comment]
Try this:

```js
<Snackbar theme={{ colors: { surface: "#f7f7f7", onSurface: "#333" } }} />
```
