### ISSUE TITLE
react-native 0.62.x removed accessibilityStates

### ISSUE THREAD

**Issue by firede** [callstack/react-native-paper#1920]
## Environment

- react: 16.11.0
- react-native: 0.62.2
- react-native-paper: 3.10.1
- typescript: 3.9.2

## Description

> Remove accessibilityStates: We’ve [removed](https://github.com/facebook/react-native/commit/7b35f427fd66cb0f36921b992095fe5b3c14d8b9) the deprecated accessibilityStates property in favor of the new accessibilityState prop which is a more semantically rich way for components to describe information about their state to accessibility services.
> -- https://reactnative.dev/blog/#breaking-changes

![image](https://user-images.githubusercontent.com/157338/82108724-12baa600-9763-11ea-914c-2048f27478cc.png)

## Reproducible Demo

Code:

```tsx
import React from "react"
import { View } from "react-native"
import { Text } from "react-native-paper"

interface Props {}

const Component: React.FC<Props> = () => {
  return (
    <View>
      <Text>Component</Text>
    </View>
  )
}

export default Component
```

**Comment by GoMino** [comment]
This is a real issue

**Comment by numToStr** [comment]
I was about a start a project and faced this issue :cry: . Hope it will be fixed soon.

**Comment by hb12DevTn** [comment]
I Hope that a fix will be published soon..

**Comment by pan-pawel** [comment]
Hey, thanks for messages.
To solve this issue we need to upgrade types for react-native also but It's abreaking change so we will  publish this change in 4.0 since we have users with older versions of react than 0.6.

**Comment by ianmartorell** [comment]
What's the timeline for the release of 4.0? Any chance of getting the updated types some other way if that's not happening very soon?

**Comment by stage88** [comment]
This is not a fix.... however I've removed all occurrences of '"accessibilityStates" | ' in ./node_modules/react-native-paper/lib/typescript, which makes the annoying errors go away.

Don't follow my advice, I know nothing.

**Comment by firede** [comment]
A way to **IGNORE** errors using `patch-package`:

```patch
diff --git a/node_modules/@types/react-native/index.d.ts b/node_modules/@types/react-native/index.d.ts
index 98681f1..825c536 100644
--- a/node_modules/@types/react-native/index.d.ts
+++ b/node_modules/@types/react-native/index.d.ts
@@ -2069,6 +2069,7 @@ export interface AccessibilityProps extends AccessibilityPropsAndroid, Accessibi
      * Accessibility State tells a person using either VoiceOver on iOS or TalkBack on Android the state of the element currently focused on.
      */
     accessibilityState?: AccessibilityState;
+    accessibilityStates?: any; // react-native-paper 3.x
     /**
      * An accessibility hint helps users understand what will happen when they perform an action on the accessibility element when that result is not obvious from the accessibility label.
      */

```

Put this file to `patches/@types+react-native+0.62.11.patch`, run `yarn patch-package`.

NOTE: This just ignores the error, `accessibilityStates` does not work as expected.

**Comment by pan-pawel** [comment]
@ianmartorell, for now, we can say the end of June

**Comment by ardyfeb** [comment]
Nobody care about accessbility on hello world application

**Comment by rpCal** [comment]
@firede Awesome! It's fixed and it's working! Thank you for code and instruction!

**Comment by mkdesilva** [comment]
Still waiting for 4.0 release
