### ISSUE TITLE
Menu choices list is having text that goes outside of the view

### ISSUE THREAD

**Issue by kopax** [callstack/react-native-paper#1922]
### Current behaviour

After having a scrollable list of choices, closing and reopening the keyboard cause the text to be displayed outside of the scroll

### Expected behaviour

I expect the scroll to be kept

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/1866564/82122469-28948f00-9794-11ea-89e0-b31f9ca8cdce.png)

### What have you tried

I am trying to play with `zIndex` without sucess.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | web
| react-native          | expo sdk 36
| react-native-paper    | 3.6.0
| node                  | 13
| npm or yarn           | 6.4.1
| expo sdk              | 36

**Comment by mMajch** [comment]
Hi @kopax, can you provide a snack or record a giph which shows this behaviour? I struggle to reproduce the issue

**Comment by kopax** [comment]
Yes, https://preprod-www.icimatin.com/

Usage iPhone X view. Let me know when I can remove that link.

**Comment by kopax** [comment]
It can be removed by adding:

```jsx
            style={{
              overflow: 'hidden',
            }}
``` 

To `<Menu.Item />`, I believe this is not MD guidelines and should be set by default.
