### ISSUE TITLE
TextInput with mode="outlined", how to use bigger height for multiline and how to remove the paddingTop

### ISSUE THREAD

**Issue by kopax** [callstack/react-native-paper#1923]
### Expected behaviour

I am setting `height` in `<TextInput  multiline style={{height: 200, paddingTop: 0}} />` to have a bigger textarea field.

It seems that the padding top is forced by react native paper

### Code sample

`<TextInput  multiline style={{height: 200, paddingTop: 0}} />`

### Reproduction

https://snack.expo.io/@kopax/blessed-popsicle

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/1866564/82123613-980d7d00-979a-11ea-9cdf-e1e748c2b713.png)

### What have you tried

So far, I don't see how to use my `paddingTop` preference to fix the issue

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | web
| react-native          | expo sdk 36
| react-native-paper    | 3.6.0
| node                  | 13
| npm or yarn           | 6.4.1
| expo sdk              | 36

**Comment by kopax** [comment]
It seems to be related to react final form and not RNP.

**Comment by kopax** [comment]
Reopening since I can't find anything to blame in react-final-form nor final-form.

**Comment by jasongaare** [comment]
I've hit this same issue. When using `mode="outlined"` the text is padding on the top, creating an undesirable user experience.

My ultimate solution has been to hack together my own outlined TextInput, by extending the styles of the flat style, as seen here (using styled components):

```jsx
const OutlinedTextInput = styled(TextInput).attrs({
  dense: true,
  underlineColor: 'transparent',
})`
  margin: 8px 0px;
  border: ${StyleSheet.hairlineWidth}px solid ${colors.charcoal};
  border-radius: 4px;
  padding-bottom: 4px;
`;
```

**Comment by kopax** [comment]
Yes, but that involve to use styled-components. I have the issue with both `outlined` and `contained`, each time the label must be in the middle, it is not possible to `contained` text input not to have a grey background and the outlined height can't be set up correctly. Time to deduplicate the RNP component is 1 day because of the density of the component chain, but this would be much better fixed in this repo.

**Comment by AwabIjaz** [comment]
a fix by using native text input in the render prop #1810 (comment)

**Comment by AwabIjaz** [comment]
a fix by using native text input in the render prop https://github.com/callstack/react-native-paper/issues/1810#issuecomment-616817037

**Comment by kopax** [comment]
Keep open please.

**Comment by OlimpiaZurek** [comment]
@kopax Look at this https://github.com/callstack/react-native-paper/issues/1810#issuecomment-616817037. I think this is the solution to this issue.

**Comment by Svarto** [comment]
@OlimpiaZurek that comment does not fixed the forced paddingTop, or am I missing something? The paddingTop comes from the view that RNP have wrapped the textinput in, it is set at 8, and I can't find a way to make it zero

**Comment by Ramesh-Chathuranga** [comment]
I had the same issue and @OlimpiaZurek comment also helpful for me to fix the issue  , thanks your reply . but it is not completely success for me . so i  removed `innerProps.style`, form NativeText input style. Then my issue was fixed.

**Comment by abannura** [comment]
@Svarto problem looks to be [here](https://github.com/callstack/react-native-paper/blob/8d1cfa1a17ab89ee989b1efc06f346f5b19d2af1/src/components/TextInput/TextInputOutlined.tsx#L389).

Would be great to customize that top positioning, specially when there is no label (and therefore no need to move the outline box down).

**Comment by Svarto** [comment]
@abannura long time, but I noticed that adding `lineHeight` into the style prop for the TextInput actually fixes the padding issue on Android.

**Comment by Rubenvdveen** [comment]
I've noticed that setting `maxHeight` instead of `height` on the `style` prop of the TextInput does actually work. The paddingTop is still there, but it doesn't mess with the TextInput, which is centered (with all content like `left` `right` and the `value`)
