### ISSUE TITLE
List.Section and List.Item margins

### ISSUE THREAD

**Issue by zivl** [callstack/react-native-paper#1927]
Is it possible to get rid of the margins when using `List.Section` / `List.Item`?
see example image:
![image](https://user-images.githubusercontent.com/4571570/82159179-2b2add80-9895-11ea-99bb-5c7d99867aa2.png)

I'd like to control the margin between items...
I was trying different approaches with `margin`/`padding` but it didn't work for me.
```javascript
<List.Section style={{ margin: 0, padding: 0 }}>
      <List.Item style={{ margin: 0, padding: 0 }}>
```

**Comment by Trancever** [comment]
This is not possible. We use the same margins/paddings as MD Guidelines recommend.

**Comment by zivl** [comment]
@Trancever are you sure?
according to [MD Lists specs](https://material.io/components/lists#specs)
there should be a divider, for sure, and list items should not have such margins between them

**Comment by longebane** [comment]
> @Trancever are you sure?
> according to [MD Lists specs](https://material.io/components/lists#specs)
> there should be a divider, for sure, and list items should not have such margins between them

I agree. The margins are massive (and moreso that it isn't editable). I think I can see the margins from outer space

**Comment by longebane** [comment]
Workaround for this arbitrary restriction is to wrap it with a `<View>` and give it negative marginVertical values

**Comment by khanhubgit** [comment]
In my case I applied negative margins and it worked
```
<List.Section style={{ margin: -10, padding: 0 }}>
      <List.Item style={{ margin: -10, padding: 0 }}>
```

**Comment by leecommamichael** [comment]
`marginVertical: 0` will do the trick.

**Comment by trevorglick** [comment]
Thanks @leecommamichael that works! SAVED

**Comment by aleksandarbos** [comment]
> This is not possible. We use the same margins/paddings as MD Guidelines recommend.

guess default values should convey MD specs, but if one simply needs to override it for different purposes, it should probably be customizable

**Comment by hkniyi** [comment]
<List.Item
                title="Fruit :"
                right={props => <List.Item {...props} title="Apple" />}
                style={{marginHorizontal: -10, marginVertical: -20}}
            />
