### ISSUE TITLE
Card animation slow.

### ISSUE THREAD

**Issue by LucasShaffer** [callstack/react-native-paper#1928]
## Ask your Question

I am working with the Card component that is being rendered in a FlatList. Resulting in about a hundred or so Cards, there will be more in the future but that should not affect what I am trying to do... I think. I am rendering the function that has the FlastList from a parent function, like so: 
```
export const ParentFunction = () => {
 return (
  <ChildFunction
   dataArray={mobxStore.array}
   onPress={(id) => mobxStore.customActionThatUpdatedDataArray(id)} />
 )
}
```
```
export const ChildFunction = ({onPress}) => {
 const Item = ({item}) => {
  return (
   <Card onPress={() => onPress}>
     {stuff in here}
   </Card>
  );

  return (
   <FlastList
    data={dataArray}
     renderItem={({ item }) => <Item item={item} />}
     keyExtractor={item => item.transactionId}
   />
  )
}
```
So I have everything working the way I want. I have the data on the card that I am hiding and showing when the card is clicked. The function in the mobX store handles all that just fine and I can see that the proper data and rerendering happens immediately. 
The interesting thing that I am running into is that when the Card is clicked, it has its own animation/feedback that runs (looks like it gets elevated). This takes some time about 1 second, then, once complete, my data shows up. I also tried wrapping the Card in a react-native touchableX and it was taking just as long.

My questions are:
Why is that default animation happening?
Why is is taking so long?
Why do I have to wait to see the changes I am making?

**Edit:** Also, since this is happening to the touchables from react-native as well I am not sure if this is the right place to ask these questions. But, thanks for your time anyway.

**Comment by Trancever** [comment]
@LucasShaffer Could you prepare a minimal [Snack](https://snack.expo.io/) that reproduces the issue? It's hard to say what is wrong without the repro. In the meantime, you can check if all the cards are rerendering when you change the state of one of them or all of the rerender.

**Comment by LucasShaffer** [comment]
@Trancever , I just saw this today. I am working on getting the snack example to work right now. Just running into a FlatList KeyExtractor error but pretty much done otherwise... I think.
Also, good point. I do have everything rerendering. What the onPress is doing is expanding the card in order to display additional data on the card, but it is also closing any other card that might be open, so it does check each item in the data set.

**Comment by LucasShaffer** [comment]
@Trancever Okay, I fixed that issue, it is working as expected. Please take a look. The only thing is that the delay is not being reproduced on snack.

Although, I think I may have fixed the issue in the process of replicating it in snack. In the snack example I am showing the bonusData if that individual item.showBonusData is true as seen in the ListItems.js file.

In my app, instead of storing a display value of true or false, I was storing the height of the bonusData view (0 if i did not want anything displayed and null if I did want it displayed. I found this solution online). Now I changed it to true false like I have in snack. It seems to be much faster. It was 1.5 ish seconds delay and not down to like .25 - .5 second delay, but only when running as a release build on android. I dont have the option to run as a release build on ios to test it though.

If you have any ideas/suggestions/feedback to improve what I have I would love to hear it!

Thanks for your time!
