### ISSUE TITLE
Allow custom properties for theme in typescript

### ISSUE THREAD

**Issue by AkalUstat** [callstack/react-native-paper#1929]
## Describe the feature

I would like to add my own properties to my theme to use in my app, such as `LineHighlight`. However, right now, typescript will not allow it
## Motivation

I am using react-native-paper in a majority of my components so it would be helpful to really solidify all theming in one area. I have multiple themes for my app (depending on user settings, so it will also reduce headache there)

**Comment by raajnadar** [comment]
It is possible in v4 https://callstack.github.io/react-native-paper/theming.html#extending-the-theme
