### ISSUE TITLE
FAB wrong color and position

### ISSUE THREAD

**Issue by mojeimi** [callstack/react-native-paper#1930]
I haven't applied any global theme or anything.

![image](https://user-images.githubusercontent.com/36441064/82215505-31b26700-9920-11ea-8e2a-38f8bdfb4f16.png)

`import 'react-native-gesture-handler';
//import { NavigationContainer } from '@react-navigation/native';
//import { createStackNavigator } from '@react-navigation/stack';
import React , {Component} from 'react';
import { Text,TextInput, StyleSheet, View } from 'react-native';
import { FAB, } from 'react-native-paper';
import Toast from 'react-native-simple-toast';
import { FlatList } from 'react-native-gesture-handler';

export default class Home extends Component {
  constructor(props) {
    super(props)
    this.state = {
      URL: ''
    };
    
  }
  
    render(){
         
      //console.log(global.id);
      
      return (
        <View>

           <TextInput
           style={styles.input}
        placeholder="Enter a Youtube URL"
        placeholderTextColor='white'
        value={this.state.URL}
        onChangeText={URL => this.setState({ URL })}
      />
      <Text style={styles.txt}>My Videos</Text>
      

      
        <FAB
    style={styles.fab}
    icon="plus"
    onPress={()=>{

          
      fetch('http://192.168.1.100:3000/videos/add', {
  method: 'POST',
  headers: {
    Accept : 'application/json',
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({

    URL : this.state.URL,

    folder : 'none',

    id : global.id

  })

  }).then((response) => response.text())
      .then((responseJson) => {
       

        
        //Alert.alert(JSON.stringify(responseJson));
        if (responseJson == "Success") {
          
          Toast.show("Video Successfully Added")
          //username=responseJson;
          // global.id=(responseJson);
          // console.log(responseJson);
          // this.props.navigation.navigate('Home');
          //this.props.navigation.navigate('Home',{name : username});
        }
        else{
          Alert.alert("Wrong Email/Password Combination");

        }

      }).catch((error) => {
        console.error(error);
      });
    }}
     />
  </View>
  // this.props.navigation.navigate('Watch');
  //     console.log('Pressed')}
        
      );}
    
  }
  const styles = StyleSheet.create({
    fab: {
      position: 'absolute',
      bottom: 0,                                                   
      right: 0, 
      color: 'black',
      margin: 16,
      
    },
    txt:{
      textAlign: 'center',
      fontSize: 20,
      fontWeight: 'bold'

    },
    input:{
       borderColor: 'gray', borderWidth: 1, backgroundColor:'black',color:'white' }
    })`

Whether I use top or bottom it stays up

**Comment by ardyfeb** [comment]
Place `<Fab/>` outside your view

```jsx
render() {
  return (
     <React.Fragment>
        <View>
           .....
       </View>
       <Fab
          ....
       />
    </React.Fragment>
  )
}
```
