### ISSUE TITLE
How to render custom component in DataTable.Cell

### ISSUE THREAD

**Issue by waghcwb** [callstack/react-native-paper#1941]
I'm trying to create a table with a button in the last column. But, when I add something different than a text node I get this error:

```
Cannot add a child that doesn't have a YogaNode to a parent withou a measure function!
```

So, this is working:

```jsx
<DataTable.Cell>Test</DataTable.Cell>
```

But this is not:

```jsx
<DataTable.Cell children={<Button>Test</Button>} />

// neither this
<DataTable.Cell>
  <Button>Test</Button>
</DataTable.Cell>
```

Am I doing something wrong?

------------

| Package  | Version |
|-------|-------|
| react | 16.11.0 |
| react-native | 0.62.2 |
| react-native-paper | 3.10.1 |

**Comment by 12343954** [comment]
same issus +1
DataTable.Cell didn't support children component yet. 3.10.1

**Comment by GabrielDvt** [comment]
I was facing the same problem.. Had a button component inside a datatable.cell and the button was not clickable ...

Thanks for the answer, Had to change the datatable.cell to a view component

**Comment by ramirobg94** [comment]
Same problem... crazy, tried some libraries a no one solve the issue... :S

**Comment by ConjuringCoffee** [comment]
You can use a `View` instead of `DataTable.Cell`. Here's an example:

```
            <DataTable.Row>
                <DataTable.Cell>Text</DataTable.Cell>
                <View>
                    <IconButton
                        icon='information-outline'
                        onPress={() => console.log('hi')} />
                </View>
            </DataTable.Row>
```
