### ISSUE TITLE
Document theme.colors.onBackground, theme.colors.onSurface and theme.colors.notification

### ISSUE THREAD

**Issue by JulianKingman** [callstack/react-native-paper#1944]
## Describe the feature

These colors are missing from the [theming documentation](https://callstack.github.io/react-native-paper/theming.html):
```javascript
    onBackground: '#000000',
    onSurface: '#000000',
    notification: pinkA400,
```

It looks like `onBackground` isn't used? `onSurface` appears to be used for the SnackBar background, and `notification` for the badge background.

**Comment by pan-pawel** [comment]
Hey @JulianKingman, thanks for pointing this out. I added these colors when I added a dark theme to be more consistent with material guidelines but I forgot to add them to the documentation! Will do that shortly
