### ISSUE TITLE
autoComplete="off" on TextInput does not work on the web

### ISSUE THREAD

**Issue by kopax** [callstack/react-native-paper#1946]
## Environment

Web

## Description

I am trying to disable the `autocomplete` on the web using [`TextInput`](https://callstack.github.io/react-native-paper/text-input.html) from [react-native-paper](https://github.com/callstack/react-native-paper) 3.10.1

```jsx
<TextInput
  name="city"
  textContentType="addressCity"
  autoComplete="off"
  mode="outlined"
/>
```

The `autoComplete="off"` is replaced with `autocomplete="noop"` in the rendered HTML, which cause the auto complete not to be disabled.

![image](https://user-images.githubusercontent.com/1866564/82732345-fa233080-9d0c-11ea-906e-0335097d7feb.png)

From where does the `noop` comes from and how can I disable the autocomplete?

## Reproducible Demo

https://snack.expo.io/@kopax/curious-pizza

**Comment by raajnadar** [comment]
Chrome started ignoring autoComplete attribute, IDK how after I removed the `autoComplete="nope"` the auto complete stopped.

I am talking about ReactJs.

**Comment by pan-pawel** [comment]
Did you check it locally?
It looks like a problem inside react-native-web, not in paper itself.
https://github.com/necolas/react-native-web/commit/b10711bddd1fdf6e01e82c0d49840dce9c2e04d2
It was changed in 0.12.2, can you check version used in your project?

**Comment by kopax** [comment]
I am not using RNW 0.12 since they removed a few useful things that have not been replaced yet.

This error happen I believe because of chrome, which force the auto complete. I was able to remove it using `onFocus={Platform.OS === 'web' ? (e) => e.target.setAttribute('autocomplete', 'off'): undefined}`

**Comment by pan-pawel** [comment]
hey @kopax, you are right, we are using lower RNW for the same reasons. 
What i was trying to say, It's not a paper issue, since we are using RNW and there is a code
https://github.com/necolas/react-native-web/blob/e810f1fd2b41293cb1efe04e332fb6f8d4bcca65/packages/react-native-web/src/exports/TextInput/index.js#L261

**Comment by kopax** [comment]
Well, that was EXACTLY what I was looking for (sorry it wasn't obvious...). I have transferred the issue on the appropriate repo. Thanks a lot for pointing me in the right direction.

**Comment by bouaoud** [comment]
hello,

any solution was found for this issue 0.13.14 andalready have the issue (autoCompleteType='off' is not working in chrome)

thanks
