### ISSUE TITLE
How can i reset duration when using single snack more than one time to show snack bar

### ISSUE THREAD

**Issue by kdpadhiyar** [callstack/react-native-paper#1954]
## How can i reset duration of single snack for  multiple purpose.
 How can i reset duration when using single snack more than one time to show snack bar?
I am  using state to reset duration but it wont help.

**Comment by raajnadar** [comment]
Use a state variable and update it accordingly.

**Comment by kdpadhiyar** [comment]
> Use a state variable and update it accordingly.

i have used it but its not working..
when first triggered and after that second triggered than last one is dissmiss with last called snack's duration

**Comment by satya164** [comment]
You should be showing multiple snackbars, not reuse a single snackbar. It's very hard to notice changes in a snackbar content as a user https://material.io/components/snackbars#behavior

**Comment by kdpadhiyar** [comment]
@satya164  i am using react native
react-native-paper 's snack bar
