### ISSUE TITLE
Official Way to Use Custom Font with Expo

### ISSUE THREAD

**Issue by karrettgelley** [callstack/react-native-paper#1967]
What is the official way to use a custom font in an expo project, in terms of the theme?

I noticed that the rnp documentation and the xpo documentation have very different instructions on how to implement a custom font, and I'm just wondering what the best practices are.

I have found some success with the following code: 

```
import React from 'react';
import { AppLoading } from 'expo';
import { useFonts, Inter_900Black } from '@expo-google-fonts/inter';
import RootStack from '../navigation/RootStack';
import { DefaultTheme, configureFonts } from 'react-native-paper';
import { Provider as PaperProvider } from 'react-native-paper';

const AppWithTheme: React.FC<{}> = () => {
  let [fontsLoaded] = useFonts({
    Inter_900Black,
  });

  if (!fontsLoaded) {
    return <AppLoading />;
  } else {
    const fontConfig = {
      default: {
        regular: {
          fontFamily: 'Inter_900Black',
          fontWeight: '900' as '900',
        },
        medium: {
          fontFamily: 'Inter_900Black',
          fontWeight: '900' as '900',
        },
        light: {
          fontFamily: 'Inter_900Black',
          fontWeight: '900' as '900',
        },
        thin: {
          fontFamily: 'Inter_900Black',
          fontWeight: '900' as '900',
        },
      },
    };
    // @ts-ignore
    fontConfig.ios = fontConfig.default;
    // @ts-ignore
    fontConfig.android = fontConfig.default;

    const theme = {
      ...DefaultTheme,
      fonts: configureFonts(fontConfig),
    };

    return (
      <PaperProvider theme={theme}>
        <MyComponent />
      </PaperProvider>
    );
  }
};

export default AppWithTheme;
```

But something tells me that it's inefficient. I guess what I'm really curious about is how configureFonts() works and what a typical implementation looks like in an expo project. If anyone could enlighten me that'd be great

expo version: 37.0.3
react-native-paper version: 3.10.1

EDIT: Added expo and rnp version

**Comment by tevonsb** [comment]
+1 to this, would love to use Google Fonts through Expo along with RNP. Is the above method the right way to go about it?

**Comment by Sbrjt** [comment]
It's much easier if you want to override any font property for all variants:


	import { Poppins_400Regular, useFonts } from '@expo-google-fonts/poppins'
	import { configureFonts, MD3LightTheme, Provider } from 'react-native-paper'

	const theme = {
		...MD3LightTheme,
		fonts: configureFonts({
			config: {
				fontFamily: 'Poppins_400Regular'
			}
		})
	}

	function App() {
		const [fontsLoaded] = useFonts({
			Poppins_400Regular
		})

		if (!fontsLoaded) return

		return (
			<Provider theme={theme}>
				<Text>
					Hello world!
				</Text>
			</Provider>
		)
	}

	export default App

	
[Docs](https://callstack.github.io/react-native-paper/docs/guides/fonts/#using-configurefonts-helper-1) (See the last eg)
