### ISSUE TITLE
Add prop to control the number of lines visible for a button

### ISSUE THREAD

**Issue by salockhart** [callstack/react-native-paper#1968]
**Is your feature request related to a problem? Please describe.**
For some of the buttons in my project, labels that are too long may sometimes get clipped with an ellipses. This is usually made more difficult by supporting multiple languages - a text size or similar for one language may not work for another.

**Describe the solution you'd like**
I've noticed that the `numberOfLines` prop for the Text component inside the Button is hardcoded to be 1. It would be nice to be able to modify this with a prop on the Button component.

**Describe alternatives you've considered**
N/A

**Additional context**
Here is an example of long text in a button:
![actual](https://user-images.githubusercontent.com/6651364/83771403-267a6d80-a67a-11ea-9978-1bf8b809a37f.jpg)

And here is what it would look like if we had 2 lines instead of 1:
![expected](https://user-images.githubusercontent.com/6651364/83771396-25494080-a67a-11ea-934e-8d0f47310ea1.jpg)

**Comment by neugartf** [comment]
Wouldn't it be better for that use case to let that happen automatically (i.e. not to have it defined but autoscaled)?

**Comment by salockhart** [comment]
> Wouldn't it be better for that use case to let that happen automatically (i.e. not to have it defined but autoscaled)?

Absolutely, but that would be a "breaking" change, stylistically. Current users expect it to truncate, and I wouldn't want to spring wrap-by-default.

However, if any of the maintainers agree to make wrap the default, I would be happy to update this.
