### ISSUE TITLE
❓Close button call back in Search Bar

### ISSUE THREAD

**Issue by hackrx** [callstack/react-native-paper#1970]
Hey, team, I want to ask is there any prop available just like as onIconPress for the close button in the search bar? I am calling an API when a user enters text in the search bar and taps on the search button, though it is working fine and I am showing a loader till data loads but I want to stop that loading when if the user presses the close button.
  
This is my code for SearchBar

```
<Searchbar
          placeholder="Search by hashtag #"
          iconColor={PrimaryColor}
          autoCapitalize="none"
          autoFocus={true}
          onIconPress={() => onEndSearchQueryHandler()}
          onEndEditing={() => onEndSearchQueryHandler()}
          value={search}
          
          onChangeText={text => onChangeSearchQueryHandler(text)}
        />
```

Is there any prop available which I can use here when  closed button is tapped by the user?

**Comment by brunohkbx** [comment]
https://github.com/callstack/react-native-paper/pull/1774

**Comment by brunohkbx** [comment]
not stale

**Comment by gluons** [comment]
I really want this feature too. Why did @github-actions close feature request?

**Comment by rossparachute** [comment]
Ditto, it would be really handy to have an event to hook into whenever the close icon is pressed.

"react": "17.0.1",
"react-dom": "17.0.1",
"react-native": "0.64.3",
"react-native-paper": "^4.10.1",
"expo": "^44.0.0",
