### ISSUE TITLE
 Typescript Error with React native Paper Components.

### ISSUE THREAD

**Issue by proteche** [callstack/react-native-paper#1971]
TO REPRODUCE:
`// **tsconfig file** 

{  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "react",
    "lib": ["es6"],
    "moduleResolution": "node",
    "noEmit": true,
    "strict": true,
    "target": "esnext"
  },
  "exclude": [
    "node_modules",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js"
  ]
}`

SAMPLE CODE: =
`const StoreFront: React.FC = () => {
  return (
    <ScrollView horizontal={true}>
      <Card key="key1">
        <Card.Cover
          source={{
            uri: "https://image"
          }}
        />
        <Card.Actions>
          <Button>Cancel</Button>
        </Card.Actions>
      </Card>
      ))}
    </ScrollView>
  );
};
export default StoreFront;`

TYPESCRIPT ERROR: = **note**:(  following error present on `<Card >, <Button>,` etc components of react native paper.)
`(alias) const Card: (React.ComponentClass<Pick<Pick<ViewProps & React.RefAttributes<View> & {
    children: React.ReactNode;
    style?: StyleProp<ViewStyle>;
    theme: Theme;
}, "style" | "children" | "ref" | "onLayout" | ... 49 more ... | "onTouchEndCapture"> & {
    ...;
} & {
    ...;
} & {
    ...;
}, "style" | ... 55 more ... | "elevation"> & {
    ...;
}, any> & hoistNonReactStatics.NonReactStatics<...>) | (React.FunctionComponent<...> & hoistNonReactStatics.NonReactStatics<...>)
import Card

Property 'accessibilityStates' is missing in type '{ children: Element[]; key: string; }' but required in type 'Pick<Pick<ViewProps & RefAttributes<View> & { children: ReactNode; style?: StyleProp<ViewStyle>; theme: Theme; }, "ref" | "style" | "removeClippedSubviews" | "hitSlop" | "onLayout" | ... 48 more ... | "accessibilityStates"> & { ...; } & { ...; } & { ...; }, "ref" | ... 55 more ... | "elevation">'.ts(2741)
`

**Comment by proteche** [comment]
The easy fix is to install the version 0.62.2 or 0.62.2+ (the errors are removed in this version, 4-5 days ago)
`npm i @types/react-native@0.62.2 --save-dev`

**Note:** previously i had 0.62.12 installed

**Comment by andordavoti** [comment]
having this issue when using @types/react-native@0.63.0, is there any solution for this other than using an older version of types? because this introduces other type errors for new react native APIs

**Comment by tylerthedeveloper** [comment]
still hitting above issue - this should work in latest versions of RN Types

**Comment by mirezko** [comment]
Still having this error with components Card, Card.Title, Card.Cover, Button, ActivityIndicator, FAB

```
  "dependencies": {
    "react-native-paper": "^4.5.0",
...
  "devDependencies": {
    "@types/react-native": "~0.63.2",
```

Typescript Error

```
No overload matches this call.
  Overload 1 of 2, '(props: Pick<Props, "hitSlop" | "onLayout" | "pointerEvents" | "removeClippedSubviews" | "style" | "testID" | "nativeID" | "collapsable" | "needsOffscreenAlphaCompositing" | ... 50 more ... | "elevation"> & { ...; }, context?: any): ReactElement<...> | ... 1 more ... | null', gave the following error.
    Type '{ children: Element[]; style: { flex: number; marginHorizontal: number; marginVertical: number; padding: number; elevation: number; }; onPress: VoidFunction; }' is missing the following properties from type 'Pick<Props, "hitSlop" | "onLayout" | "pointerEvents" | "removeClippedSubviews" | "style" | "testID" | "nativeID" | "collapsable" | "needsOffscreenAlphaCompositing" | ... 50 more ... | "elevation">': accessibilityComponentType, accessibilityTraits
  Overload 2 of 2, '(props: PropsWithChildren<Pick<Props, "hitSlop" | "onLayout" | "pointerEvents" | "removeClippedSubviews" | "style" | "testID" | "nativeID" | "collapsable" | "needsOffscreenAlphaCompositing" | ... 50 more ... | "elevation"> & { ...; }>, context?: any): ReactElement<...> | ... 1 more ... | null', gave the following error.
    Type '{ children: Element[]; style: { flex: number; marginHorizontal: number; marginVertical: number; padding: number; elevation: number; }; onPress: VoidFunction; }' is missing the following properties from type 'Pick<Props, "hitSlop" | "onLayout" | "pointerEvents" | "removeClippedSubviews" | "style" | "testID" | "nativeID" | "collapsable" | "needsOffscreenAlphaCompositing" | ... 50 more ... | "elevation">': accessibilityComponentType, accessibilityTraits
```

Is there a way how to ignore/suppress it in the meantime?

**Comment by Nicwalle** [comment]
Same for me using the basic Text component. Any clue ? 
```
{
  ...
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.3",
    ...
  },
  "devDependencies": {
    ...
    "@types/react-native": "^0.63.2",
    ...
    "typescript": "^3.8.3"
  },
}
```

This is the result of a clean install made yesterday with the Typescript template.

**Comment by mirezko** [comment]
I _fixed_ it temporarily with **exact version** of types. (It's not a fix, but an acceptable solution while the issue is being solved. I will want to keep libs updating)

1. set devDependencies as such
2. run npm install to update

package.json
```
...
  "devDependencies": {
    "@types/react-native": "0.63.40",
...
```

**Comment by andordavoti** [comment]
@mirezko Thanks, that forked for now!

**Comment by stasgm** [comment]
"react-native-paper": "4.6.0" - Same problem ("@types/react-native": "0.63.45")

**Comment by lorstenoplo** [comment]
you can try this solution : https://github.com/callstack/react-native-paper/issues/2482#issuecomment-762276065

**Comment by ImAbhishekTomar** [comment]
Hi @stasgm,
Did you find any solution for this issue?

My issue details: #2528

**Comment by lorstenoplo** [comment]
@ImAbhishekTomar  do you use functional components?

**Comment by stasgm** [comment]
> Hi @stasgm,
> Did you find any solution for this issue?
> 
> My issue details: #2528

No. still crying

**Comment by lorstenoplo** [comment]
@stasgm  did u try my solution : https://github.com/callstack/react-native-paper/issues/2482#issuecomment-762276065

If you use functional components my solution should work

**Comment by rajderks** [comment]
The fact that this became a thing is driving me nuts:
```
<Button
            mode="contained"
            accessibilityTraits={undefined} <===== Annoying
            accessibilityComponentType={undefined} <====== Annoying
```

`"@types/react-native": "0.63.49",`
`"react-native-paper": "4.7.1",`

None the suggested solutions are working either.
I'm not going to pin a lower `@types/react-native` version just for this lib, and solutions to alter source code, well...

**Comment by diazdell91** [comment]
@mirezko Thanks!!

**Comment by akumar09071988** [comment]
I am using `"react-native-paper": "^4.7.2",` and ` "@types/react-native": "^0.64.2",` 

For the below code 
```
export const CustomActivityIndicator = () => {
   return  <ActivityIndicator animating={true} color={Colors.red800} />;
}
```
I get errors like ` Unexpected token, expected ","`

**Comment by Flip32** [comment]
I'm having the same issue in my project

I'm using
"@types/react-native": "~0.63.2",

**Comment by mndaipre** [comment]
I'm also having the same issue in my project.

I'm using "@types/react-native": "^0.64.0".

**Comment by mariasyedd** [comment]
Still occuring

**Comment by KristenLeach** [comment]
I am also running into this issue now - have there been any updates?

**Comment by kendallroth** [comment]
Noticing the same issue, specifically on `Text` component from RNP. Tried pinning my `@types/react-native` package to match the react native version, but without success.

```js
Type '{ children: string; style: { marginBottom: number; paddingVertical: number; paddingLeft: number; fontSize: number; lineHeight: number; borderLeftWidth: number; borderLeftColor: string; borderRadius: number; }; }' is missing the following properties from type 'Pick<TextProps & { style?: StyleProp<TextStyle>; theme: Theme; } & RefAttributes<{}>, "testID" | "ref" | "style" | "onLayout" | ... 35 more ... | "key">': onPressIn, onPressOut
```

```js
  "react-native": "0.64.2",
  "react-native-paper": "^4.10.0",
  "@types/react-native": "0.64.2"
```

**Comment by rayjackson13** [comment]
Hi! I think I found a temporary solution to this issue.
I just looked into react-native-paper's `package.json` in my node_modules. And I found out that they have
```"@types/react-native": "^0.66.1",``` in the devDependencies.

Trying to match that version in my project, it resolved the issue.
Although now I have mismatching versions for react-native and @types/react-native, and I don't know the consequences of this solution.
```
"react-native": "0.64.3",
"@types/react-native": "~0.66.1",
```

**Comment by sajumani** [comment]
This combination works for me!

```
yarn add react-native-paper@^4.8.1
yarn add @types/react-native@^0.64.5 --save-dev
yarn add react-native@0.64.1
```
For npm 

npm install react-native-paper@^4.8.1
npm install @types/react-native@^0.64.5 --save-dev
npm install react-native@0.64.1

**Comment by jbrumwell** [comment]
Having this issue with a fresh install in an expo application

```
No overload matches this call.
  Overload 1 of 2, '(props: Pick<TextInputProps, "ref" | "label" | "style" | "children" | "pointerEvents" | "onLayout" | "testID" | "nativeID" | "accessible" | "accessibilityActions" | ... 114 more ... | "dense"> & { ...; }, context?: any): ReactElement<...> | ... 1 more ... | null', gave the following error.
    Property 'autoComplete' is missing in type '{ label: string; }' but required in type 'Pick<TextInputProps, "ref" | "label" | "style" | "children" | "pointerEvents" | "onLayout" | "testID" | "nativeID" | "accessible" | "accessibilityActions" | "accessibilityLabel" | ... 113 more ... | "dense">'.
  Overload 2 of 2, '(props: PropsWithChildren<Pick<TextInputProps, "ref" | "label" | "style" | "children" | "pointerEvents" | "onLayout" | "testID" | "nativeID" | "accessible" | "accessibilityActions" | ... 114 more ... | "dense"> & { ...; }>, context?: any): ReactElement<...> | ... 1 more ... | null', gave the following error.
    Property 'autoComplete' is missing in type '{ label: string; }' but required in type 'Pick<TextInputProps, "ref" | "label" | "style" | "children" | "pointerEvents" | "onLayout" | "testID" | "nativeID" | "accessible" | "accessibilityActions" | "accessibilityLabel" | ... 113 more ... | "dense">'.ts(2769)
(alias) const TextInput: (React.ComponentClass<Pick<TextInputProps, "ref" | "label" | "style" | "disabled" | "maxLength" | "value" | "onChange" | "onBlur" | "error" | "mode" | "allowFontScaling" | "autoCapitalize" | ... 112 more ... | "dense"> & {
    ...;
}, any> & hoistNonReactStatics.NonReactStatics<...>) | (React.FunctionComponent<...> & hoistNonReactStatics.NonReactStatics<...>)
import TextInput
```

```
react-native@0.64.3
react-native-paper@4.11.2
@types/react-native@0.64.23
```

**Comment by praveen-adroitminds** [comment]
Still getting the error with typescript
`'Button' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<(Pick<Pick<ViewProps & RefAttributes<View>`
  "react-native": "0.68.2",
    "react-native-paper": "^4.12.1",
    "@types/react-native": "~0.66.13",

**Comment by alifa20** [comment]
@praveen-adroitminds Have you tried this
```
"resolutions": {
	"@types/react": "<version-of-react>"
},
```
https://github.com/callstack/react-native-paper/issues/2965#issuecomment-1120449109
?

**Comment by matmelous** [comment]
It worked, thank you

> @praveen-adroitminds Have you tried this
> 
> ```
> "resolutions": {
> 	"@types/react": "<version-of-react>"
> },
> ```
> 
> [#2965 (comment)](https://github.com/callstack/react-native-paper/issues/2965#issuecomment-1120449109) ?

it worked, Thank you

**Comment by dennis-gonzales** [comment]
Have a freshly created expo project and I experienced this error.
`
"expo": "~45.0.0",
"react-native": "0.68.2",
"react-native-paper": "^4.12.2",
`

In my dev dependency there is a package called
`"@types/react": "17.0.21",`

Fixed my issue by removing the _tilde_ ~, like so
`@types/react`
