### ISSUE TITLE
How to use patch-package with react-native-paper

### ISSUE THREAD

**Issue by Stringsaeed** [callstack/react-native-paper#1978]
Hey all,
I wanted to ask how to use patch-package how to build after patching `src/` directory, I searched in bob, tried to build but `react-native-paper` didn't update
### Why?
* i wanted to edit radio button item color because it's not right
* i wanted to edit radio button item icon position to make it left, because of design wise

thank you in advance

**Comment by shubhamdeol** [comment]
Any available solution for this. My patch only worns in debug mode. But in release its not getting applied

**Comment by Stringsaeed** [comment]
@shubhamdeol you can open issue in [react-native-builder-bob](https://github.com/callstack/react-native-builder-bob) as it the infrastructure for react-native-paper

**Comment by kelokchan** [comment]
I'm facing similar issue too where my patch is not applied when building the app in release mode

**Comment by saadi-ninjasCode** [comment]
Any solution for it?
