### ISSUE TITLE
Button width is not adaptive to its contents

### ISSUE THREAD

**Issue by knakamura13** [callstack/react-native-paper#1979]
### Current behaviour

A Button, without any styling, fills the screen width on all devices.

### Expected behaviour

Based on [the documentation for the Button component](https://callstack.github.io/react-native-paper/button.html), a Button's width should adapt to fit its contents instead of always having a width of '100%'.

### Code sample

[Snack: react-native-paper button styling issue (demo)](https://snack.expo.io/@knakamura13dev/button)

### Screenshots

Expected behavior of unstyled buttons (from the official Paper documentation):
![button](https://user-images.githubusercontent.com/20162718/84219067-91fe7980-aa84-11ea-873e-e16c8a6a20d0.png)

Current behavior of unstyled buttons (from the Snack):
<img width="340" alt="buttons-ios" src="https://user-images.githubusercontent.com/20162718/84219164-bc503700-aa84-11ea-8bea-52b9fe3adf8e.png">
<img width="338" alt="buttons-android" src="https://user-images.githubusercontent.com/20162718/84219171-be19fa80-aa84-11ea-8e09-52e474eaaf6d.png">

### What have you tried

N/A, because I am not looking for a one-time solution for the styling issue.

### Your Environment

**Packages**
react 16.9.0
react-native 37.0.1
react-native-paper 3.10.1
expo 37.0.0

**Expo SDK Version**
37.0.0

**Snack**
https://snack.expo.io/@knakamura13dev/react-native-paper-button-styling-issue-(demo)

**Comment by yamifr07** [comment]
Same issue

**Comment by dksouza** [comment]
Solution?

**Comment by yamifr07** [comment]
Wrap button into a view with the following style
<View style={{display: 'flex', flexDirection: 'row'}}><Button/></View>

**Comment by dksouza** [comment]
@yamifr07 very thank's...
working for me 👍 👍

**Comment by raajnadar** [comment]
Did anyone try this prop https://callstack.github.io/react-native-paper/button.html#compact

**Comment by jcbags101** [comment]
> Wrap button into a view with the following style <View style={{display: 'flex', flexDirection: 'row'}}>

not working for me

**Comment by sarabjit20s** [comment]
Try this:
```
<Pressable style={{ alignSelf: 'flex-start' }}>
```

> This is still a thing. Same goes for the chip component.
