### ISSUE TITLE
Adapt our docs style to material.io style

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#198]
Our docs: https://callstack.github.io/react-native-paper/toolbar.html should be similar to Google docs https://material.io/guidelines/layout/principles.html#

* Nicer sidebar
* Use more colors (for titles)
* Typography

So we have:

* Header with component name (like Layout screen from material.io)
* Small description (1 line)
* Usage - Screenshots
* Props

**Comment by jukben** [comment]
https://github.com/callstack/component-docs/pull/6
