### ISSUE TITLE
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

### ISSUE THREAD

**Issue by mlopezfernandez** [callstack/react-native-paper#1981]
### Current behaviour

There are already two open issues that have been closed indicating that the problem has been solved in version 3.8 but in the checkboxes it continues to occur.

### Expected behaviour

It is a warning that occurs when you check or uncheck on a checkbox

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/17619458/84474664-803af300-ac8b-11ea-9b9a-3f1245381056.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android 9
| react-native          | 0.62.2
| react-native-paper    | 3.8.0
| node                  | 12.16.2
| npm or yarn           | 6.14.5

**Comment by raajnadar** [comment]
Try upgrading to latest version

**Comment by mlopezfernandez** [comment]
Hi @raajnadar before upgrate to latest version returns the following error.

![image](https://user-images.githubusercontent.com/17619458/84486459-bb462200-ac9d-11ea-992c-fb7a2ab07fe8.png)

Do I need to do something else? Thanks!

**Comment by mlopezfernandez** [comment]
Sorry @raajnadar I have cleared the cache and now it works correctly! Thanks!
