### ISSUE TITLE
Searchbar component inside Appbar

### ISSUE THREAD

**Issue by sorxrob** [callstack/react-native-paper#1984]
Hi everyone!

Is there a sample implementation of adding a `Searchbar` component inside a `Appbar`? Something like this:

![102683478_189436882413180_1133745411049036819_n](https://user-images.githubusercontent.com/13049130/84592345-986f6580-ae77-11ea-9647-b7e837207d5b.jpg)

Any help would be much appreciated.

**Comment by raajnadar** [comment]
You can keep it outside the Appbar.

**Comment by sorxrob** [comment]
> You can keep it outside the Appbar.

Well yes, that's the current implementation we can do. I'm asking if someone already implemented `Searchbar` inside `Appbar`. Thanks anyway.
