### ISSUE TITLE
upgrade to 4.0.0-alpha.0 in react-native 0.60.4

### ISSUE THREAD

**Issue by samaneh-kamalian** [callstack/react-native-paper#1987]
Hi. thanks for your update.
I use react-native 0.60.4 and I can not use your last update.
after run my app it shows red screen and print this error "the module compoents/Checkbox could not be found from myappDirectory/reac-native-paper/lib/module/index.js".
Is there a solution other than upgrading my react-native?
I do not have enough time to upgrade it!

**Comment by raajnadar** [comment]
Clear the cache

**Comment by samaneh-kamalian** [comment]
gradlew clean ?

**Comment by raajnadar** [comment]
`npx react-native run-android --reset-cache` or `expo start -c`

**Comment by samaneh-kamalian** [comment]
Hi . thanks for your reply.
I test first but return error:
error: unknown option `--reset-cache'

**Comment by raajnadar** [comment]
1) Upgrade your react native cli.
2) Upgrade react native paper to latest stable version. (Don't use alpha)
3) Clear metro cache.

**Comment by samaneh-kamalian** [comment]
I had the same problem!

**Comment by samaneh-kamalian** [comment]
I used this to clear cache and solved my problem.
thank you.
watchman watch-del-all && rm -rf /tmp/react-native-packager-cache-* && rm
-rf /tmp/metro-bundler-cache-* && rm -rf node_modules/ && npm cache clean
--force && npm install && npm start -- --reset-cache
