### ISSUE TITLE
TouchableRipple effect not working when using non-transparent view inside it on Android

### ISSUE THREAD

**Issue by lakaniemi** [callstack/react-native-paper#1990]
Hey! I'm not sure if this exactly is a bug, but I've been trying to crawl through documentation and library source code to figure out the cause without success. At least there is not any mention that this is the expected behavior.

**See comments below for further investigation**

### Current behaviour

Ripple effect does not work when using `Surface` component. If `Surface` is commented out from the following code snippet, and `Text` is the first child element of `TouchableRipple`, ripple effect works as expected.

### Expected behaviour

Ripple effect should work with `Surface` too.

### Code sample

Here is a snack:

https://snack.expo.io/SBjEtFbhc

When creating the Snack, I realized that the Snack is actually working as expected in the web review. However, if you run it on an Android device (tried on my OnePlus 6T with Android 10) it's not working. So this might actually be issue related to Android.

One funny thing that I also noticed is that if you uncomment the margin thing from the snack, a ripple effect is actually appearing where the margin is but not on the content itself. Weird :D

### What have you tried

Extensive debugging, basically everything that I've come up with. It seems that the `Surface` component is the problem here, but I have no idea why.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android 10
| react-native          | 0.62.2
| react-native-paper    | ^3.10.1
| node                  | v12.16.2
| npm or yarn           | yarn
| expo sdk              | not used

**Comment by lakaniemi** [comment]
Also one weird thing that I noticed: when I set the background color of the surface to `theme.colors.disabled` the ripple effect is showing as expected. Here's a snack: https://snack.expo.io/KJ0XQuwOK

But this is currently the only color that I've found that works :D For example `theme.colors.primary` does not work

**Comment by lakaniemi** [comment]
Upon further debugging and diving deeper into the color thing, I actually realized something common: all the colors it worked with were somewhat transparent. Could this maybe be a rendering order issue? For example, the following snack is displaying the ripple effect as the color has alpha value of `0.3` and thus is transparent: https://snack.expo.io/XrRbrV9VF

If you change it to 1, the ripple effect disappears.

This makes sense with the previous finding as `primary` is defined as following:
`primary: '#6200ee',`

While `disabled` is:
```
disabled: color(black)
      .alpha(0.26)
      .rgb()
      .string(),
```

**Comment by lakaniemi** [comment]
Seems like this is not specific to `Surface` either. When using `View` instead of `Surface` with background that is not transparent, the same is happening: https://snack.expo.io/xmWf9p_PB

Am I maybe just misusing the Ripple thing, or is this a real issue? One thing to take into account is that in all these cases, the web part in Snack is working as intended.

**Comment by Nabeeldev20** [comment]
Why this is closed. Have the same issue.

**Comment by iammursal** [comment]
I'm having the same issue.

**Comment by kendallroth** [comment]
This is still an issue in 2023, and should be re-opened for investigation

**Comment by rdgomt** [comment]
I am facing the exactly same issue.

**Comment by g-hamilton** [comment]
Me too :(

**Comment by g-hamilton** [comment]
I had to use a bit of a workaround... 

```
<View style={{backgroundColor: 'blue'}}>
    <TouchableRipple onPress={() => alert('Pressed!')}>
        <View style={styles.myCard}>...</View>
    </TouchableRipple>
</View>
```

Applying the background color to a parent container view rather then the card, nested in the touchable ripple works for me :)

**Comment by richardhyesungo** [comment]
> I had to use a bit of a workaround...
> 
> ```
> <View style={{backgroundColor: 'blue'}}>
>     <TouchableRipple onPress={() => alert('Pressed!')}>
>         <View style={styles.myCard}>...</View>
>     </TouchableRipple>
> </View>
> ```
> 
> Applying the background color to a parent container view rather then the card, nested in the touchable ripple works for me :)

having the same issue. this workaround worked for me

**Comment by thecodeinfluencer** [comment]
For me I was leaving out the `onPress` prop

**Comment by shawhu** [comment]
That's just great....
Another 30 minutes of my life....

But thank you guys!
