### ISSUE TITLE
Bottom sheets

### ISSUE THREAD

**Issue by ahmedlhanafy** [callstack/react-native-paper#2]
[Material Design Docs Link](https://material.google.com/components/bottom-sheets.html#)

**Comment by satya164** [comment]
We can implement a simple bottom sheet without the scrolling behavior for initial implementation.

**Comment by osdnk** [comment]
I would be grateful if you could do it. Frankly speaking I'm extremely curious how to do it smoothly without native modules

**Comment by gawrysiak** [comment]
I'm just trying to find a quick replacement. Ended up using react-native-modalbox. Looking forward for a paper solution though :+1:

**Comment by satya164** [comment]
We'd probably use `react-native-gesture-handler` and `react-native-reanimated` to build it when we finally get to it. It's a tricky component.

**Comment by ferrannp** [comment]
Our recommendation https://github.com/osdnk/react-native-reanimated-bottom-sheet.

**Comment by gawrysiak** [comment]
I've been trying the reanimated-bottom-sheet but then ended up with https://github.com/osdnk/react-native-reanimated-bottom-sheet/issues/16 (can't press elements inside the bottom sheet on android). For now I'm using https://github.com/root-two/react-native-drawer and waiting for a better solution

**Comment by kodayashi** [comment]
@satya164, @ferrannp - Is this closed b/c it won't be implemented? Would be nice to keep on the backlog at least since it's part of the material design spec.

**Comment by Trancever** [comment]
@kodayashi Yes, it won't be implemented. There is [react-native-reanimated-bottom-sheet](https://github.com/osdnk/react-native-reanimated-bottom-sheet/issues/16) that implements bottom-sheet and we encourage to use this package instead.

**Comment by react-ram** [comment]
@Trancever may i know the reason why it won't be implemented?

**Comment by Trancever** [comment]
@react-ram It's impossible to implement it properly without using gesture-handler, reanimated and we don't want to include these two libs into Paper.

**Comment by crystalarcus** [comment]
> @react-ram It's impossible to implement it properly without using gesture-handler, reanimated and we don't want to include these two libs into Paper.

Maybe you can make a library "Bottom-Sheet-React-Native-Paper" and which have material design and is usable with paper, which depends on reanimated and gesture handler, instead of implementing it directly in Paper. So If someone in case wanna use it, they can install those library. If you don't have time, I can make it and you can test it and if its fine than mention it on paper's recommended libraries.

**Comment by yannick-softwerft** [comment]
> > @react-ram It's impossible to implement it properly without using gesture-handler, reanimated and we don't want to include these two libs into Paper.
> 
> @Trancever Maybe you can make a library "Bottom-Sheet-React-Native-Paper" and which have material design and is usable with paper, which depends on reanimated and gesture handler, instead of implementing it directly in Paper. So If someone in case wanna use it, they can install those library. If you don't have time, I can make it and you can test it and if its fine than mention it on paper's recommended libraries.

Have you been able to take the time to implement this?
