### ISSUE TITLE
Flex AlignItems not renders list

### ISSUE THREAD

**Issue by shubham14596** [callstack/react-native-paper#2005]
### Current behaviour
On Assigning AlignItems:'center' style to List.Item parent, List doesn't render but it reserves space.

### Expected behaviour
List should be rendered with center aligned.

### Code sample
    <View style={styles.container}>
      <FlatList
        data={threads}
        keyExtractor={(item) => item._id}
        ItemSeparatorComponent={() => <Divider />}
        renderItem={({ item }) => (
          <List.Item title={item.name}/>
        )}
      />
    </View>

```
const styles = StyleSheet.create({
  container: {
    backgroundColor: '#f5f5f5',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center' // THIS IS CAUSING PROBLEMS
  }
});
```

### Your Environment

| software              | version
| --------------------- | -------
| android        | 8.1.0
| react-native          | 0.61.5
| react-native-paper    |3.10.1
| node                  |10.19
| npm           |6.13.4

**Comment by vamshi9666** [comment]
I think you need to set prop ```contentContainerStyle``` of ```FlatList``` instead of wrapping with ```View```. 

example : 



```
  <FlatList
    contentContainerStyle={styles.container}
    data={threads}
    keyExtractor={(item) => item._id}
    ItemSeparatorComponent={() => <Divider />}
    renderItem={({ item, index }) => (
      <List.Item title={String(index)}/>
    )}
  />
```

**Comment by shubham14596** [comment]
@vamshi9666 still the same problem persists, your solution works fine for web version only not android version.
