### ISSUE TITLE
TextInput with Typescript giving Error when we pass number to value attribute

### ISSUE THREAD

**Issue by proteche** [callstack/react-native-paper#2006]
the Error is **"Type 'number' is not assignable to type 'string | undefined'"**

code: -
``<TextInput
          keyboardType="numeric"
          style={{ marginHorizontal: 10, backgroundColor: 'white' }}
          label="Mobile Number"
          value={formData.mobileNumber}
          onChangeText={(text) =>
            setFormData({ ...formData, mobileNumber: parseInt(text, 10) })
          }
        />``
**versions:**
react-native-paper: "^3.10.1",
react-native: "~0.61.5",

**Comment by Trancever** [comment]
value should be of type string. Please convert the number to string by doing `value={formData.mobileNumber.toString()}`
