### ISSUE TITLE
[ TypeError ] in new TextInput 4.0.0-alpha.1 Release

### ISSUE THREAD

**Issue by Alarees** [callstack/react-native-paper#2008]
### Current behaviour

i got this error
```
[TypeError: JSON.stringify cannot serialize cyclic structures.]
```
### Expected behaviour

working TextInput as in [picture here](https://github.com/callstack/react-native-paper/pull/1850)

### Code sample

i used the code provided in [here](https://github.com/callstack/react-native-paper/blob/4.0/example/src/Examples/TextInputExample.tsx)

so i wrote 
```
<TextInput
... other props
right={<TextInput.Affix text="/100" />}
        />
```

### Error pic

![error](https://user-images.githubusercontent.com/18484561/85344673-9bf69280-b4f0-11ea-846c-b3e095e6502a.PNG)

### My Environment

| software              | version
| --------------------- | -------
| android        | 6.0
| react-native          | 0.61.5
| react-native-paper    | 4.0.0-alpha.1
| node                  | 12.14.0
| npm           | 6.13.4
| react-native-vector-icons              | 6.6.0

**Comment by Trancever** [comment]
@matkoson @jbinda Could one of you look into this?

**Comment by matkoson** [comment]
@Trancever I'll take it.

**Comment by matkoson** [comment]
@Alarees Could you create some repository with reproducible example? I've just tested `TextInput.Affix` on `4.0.0-alpha.1` and it works fine on both Android emulator and device, when using fresh Expo/React Native Cli app.

**Comment by rahmanharoon** [comment]
facing this issue now version: `"react-native-paper": "4.11.2"`
