### ISSUE TITLE
Side menu drawer example

### ISSUE THREAD

**Issue by Jonatthu** [callstack/react-native-paper#2009]
I have not found any example of how to create a side menu or drawer in the docs, How can I do this?

react-native: 16.9.x
react-native-paper latest

**Comment by Alarees** [comment]
use [react navigation lib](https://reactnavigation.org/docs/getting-started), after you install it move to the [Drawer navigation Section](https://reactnavigation.org/docs/drawer-based-navigation) in their web side docs, after that you can use the (`side menu or drawer in the docs`)

**Comment by lukewalczak** [comment]
Hey @Jonatthu please also check the [article](https://reactnavigation.org/blog/2020/01/29/using-react-navigation-5-with-react-native-paper#drawer), it can be helpful!

**Comment by Jonatthu** [comment]
@Alarees and @lukewalczak I am using that solution right now, but using a drawer should not require a navigator as a must, sometimes we just want to show a drawer for external links or really simple UI, so this library should just show a way to create a drawer without us to require to create a navigator. Is this right?

**Comment by Jonatthu** [comment]
https://material-bread.org/components/drawer

**Comment by BoughezalaMohamedAimen** [comment]
Missing in the docs , creating  a simple  sidemenu Drawer , without react navigation , if any body can help ?

**Comment by Tarvone** [comment]
In the React Navigation Docs there is a drawer that does not use a navigator [here](https://reactnavigation.org/docs/drawer-layout/).

Yes it does require another library but it works really nicely and is recommended in the React Navigation Docs

If you're using the tab layout from Expo you can then use it like this:
```
  import { Drawer } from 'react-native-drawer-layout';

  export default function TabLayout() {
  
    return (
      <Drawer
        drawerStyle={{ width: '70%' }}
        drawerPosition='left'
        open={open}
        onOpen={() => setOpen(true)}
        onClose={() => setOpen(false)}
        renderDrawerContent={() => <DrawerContent />}
      >
        <Tabs
          screenOptions={{
            animation: 'fade'
        >
          <Tabs.Screen
            name="home"
            options={{
              title: 'Home',
              header: () => <PageHeader page="Home" setOpen={setOpen} />,
              tabBarIcon: ({ color }) => <TabBarIcon name="home" color={color} />
            }}
          />
        </Tabs>
      </Drawer>
    );
  }
```

And then for the Drawer Content, you can then use the React Native Paper Elements like this:
```
import { Drawer } from 'react-native-paper';

const DrawerContent = () => {
  const [active, setActive] = React.useState('');

  return (
    <Drawer.Section title="Some title">
      <Drawer.Item
        label="First Item"
        active={active === 'first'}
        onPress={() => setActive('first')}
      />
      <Drawer.Item
        label="Second Item"
        active={active === 'second'}
        onPress={() => setActive('second')}
      />
    </Drawer.Section>
  );
};
```
