### ISSUE TITLE
BUG - Chip with custom icons

### ISSUE THREAD

**Issue by odesey** [callstack/react-native-paper#2014]
### Current behaviour
When using custom icons (FontAwesome) as outlined here:
https://callstack.github.io/react-native-paper/icons.html

The `close` \ `delete` button icon does not render in the `Chip` component. 

### Expected behaviour

The `close` \ `delete` should render using the custom icon or an over-ride function should be made available

### Code sample
```javascript
   <Chip onPress={() => {}} onClose={() => {}} style={styles.chip}>
       My Chip
   </Chip>
```

### Screenshots (if applicable)

<img width="246" alt="Screen Shot 2020-06-24 at 9 02 33 PM" src="https://user-images.githubusercontent.com/3899366/85642010-2c9eb100-b65e-11ea-8a0f-3e54cb3dce65.png">

### What have you tried
Tried to over-ride the close icon but this does not seem possible currently:

https://github.com/callstack/react-native-paper/blob/ef59f4142ae1f7a9e6515650e0d55065ce19bc42/src/components/Chip.tsx#L309

### Your Environment

| software              | version
| --------------------- | -------
| ios or android      | Both
| react-native         | 0.61.5
| react-native-paper    | 3.10.1
| node              | 14.2  
| npm or yarn     | Both
| expo sdk       | NA

**Comment by vaishnavi3** [comment]
Hi, we were facing the same issue.This issue is caused as FontAwesome does not have an icon called ```close-circle```.
The workaround we use is:
```  
 const replacementIcons= {
    'close-circle': 'times-circle',
 };

 <FontAwesome5ProIcon
    {...props}
    name={replacementIcons[props.name] || props.name}
  />
```

This helped us to not make any changes to ```Chip``` component, and also display the correct result.
