### ISSUE TITLE
Menu does not work as expected on iOS

### ISSUE THREAD

**Issue by crater19** [callstack/react-native-paper#2015]
I have taken the menu example component and dropped it without editing in to an iOS app and when i click on Show Menu, the menu items appear half way down the screen. I can't see any property that controls this behaviour.
The web example works as expected, the menu items appear right below the Show Menu button that is clicked.

Also, the menu is not hidden if i click outside the vicinity of the Show Menu view, it stays displayed until i click on the button again, or at least around the menu, almost like the click is being registered by container only.

Ultimately i want to use this menu for three dots menu in screen header, will this work ?

"react-native": "0.62.2"
"react-native-paper": "^3.10.1"
"react-native-vector-icons": "^6.6.0"

**Comment by Trancever** [comment]
@crater19 Could you provide a [Snack](https://snack.expo.io/) that reproduces the issue?
