### ISSUE TITLE
Double arrow

### ISSUE THREAD

**Issue by joelnbl** [callstack/react-native-paper#2031]
**You may be interested in adding in UI >> Button and << Button.**
The idea is that when the user clicks on the ">>" button it should take the user to the last page and if the user clicks on the "<<" button it should take the user to the first page.

I can do it!

**Comment by Trancever** [comment]
@joelnbl Thanks for the idea, but we don't think Paper needs this change. Our users can already build such a Button from the building blocks that we currently provide.
