### ISSUE TITLE
Missing types all over the codebase

### ISSUE THREAD

**Issue by RohovDmytro** [callstack/react-native-paper#2033]
### Current behaviour

Props are not recognized:
![image](https://user-images.githubusercontent.com/1548235/86230447-bdfbaf00-bb99-11ea-9383-f7fa92bebe4e.png)

### Expected behaviour

Not sure why are they happening. I expect to use simple components without writing down all 50 of their props.

### Code sample

See below.

### Screenshots (if applicable)

All over the codebase I see this warnings:
![image](https://user-images.githubusercontent.com/1548235/86230447-bdfbaf00-bb99-11ea-9383-f7fa92bebe4e.png)

### What have you tried

I've tried to add some props that are missing. It was 50, now it's 48 props are missing. :)

### Your Environment

![image](https://user-images.githubusercontent.com/1548235/86230606-f7341f00-bb99-11ea-8a89-a0a7cfcde27e.png)

**Comment by satya164** [comment]
Update to React Native Paper 4.x
