### ISSUE TITLE
`configureFonts` not working with `default` key

### ISSUE THREAD

**Issue by selrond** [callstack/react-native-paper#2038]
I just want to reopen #1720, as the issue still persists. 

Setting just `default` key inside `fontConfig` doesn't do anything. 

As mentioned in the [docs](https://callstack.github.io/react-native-paper/fonts.html#configuring-fonts-in-themeprovider) it should override the config on all platforms:

> Note: To override font on all platforms use default key.

**Comment by raajnadar** [comment]
Did you try this https://github.com/callstack/react-native-paper/issues/1720#issuecomment-610759746

**Comment by selrond** [comment]
@raajnadar I did work around it eventually:

```js
const fontConfig = {
  regular: {
    fontFamily: iOSUIKit.body.fontFamily,
    fontWeight: systemWeights.regular.fontWeight,
  },
  medium: {
    fontFamily: iOSUIKit.body.fontFamily,
    fontWeight: systemWeights.semibold.fontWeight,
  },
  light: {
    fontFamily: iOSUIKit.body.fontFamily,
    fontWeight: systemWeights.light.fontWeight,
  },
  thin: {
    fontFamily: iOSUIKit.body.fontFamily,
    fontWeight: systemWeights.thin.fontWeight,
  },
}

const fonts = configureFonts({
  default: fontConfig,
  android: fontConfig,
  ios: fontConfig,
})
```

but the docs state it should be possible to do just by setting `default` key, which doesn't work; and which is the point of this issue

**Comment by selrond** [comment]
not stale

**Comment by selrond** [comment]
What's wrong with this? 

> If the issue is still present in the latest version, please leave a comment within 7 days to keep it open

I immediately replied

**Comment by selrond** [comment]
bumping this issue, should not be closed
