### ISSUE TITLE
I can't click on anything in my page using FAB.Group

### ISSUE THREAD

**Issue by kopax** [callstack/react-native-paper#2041]
I can't click on anything in my page using `<FAB.Group />`

### Current behaviour

I expect to render a `FAB` in bottom right corner of my screen without side effect

### Expected behaviour

I expect to be able to click on anything on my page

### Code sample

With `react-native-paper` 3.10.1, I can't click after rendering this component in my page.

```jsx
import React from 'react';
import { useIsFocused } from '@react-navigation/native';
import { Platform } from 'react-native';
import { Portal, useTheme } from 'react-native-paper';
import { FAB } from 'react-native-paper';

export default function Filters({
  isVisible,
  setIsVisible,
  ...rest
}) {
  const theme = useTheme();
  const isFocused = useIsFocused()
  console.log({ useReactRouter, isFocused, isVisible });
  return (
      <FAB.Group
          style={{
            bottom: 30,
          }}
          fabStyle={{
            backgroundColor: theme.colors.primary,
          }}
          visible={!isVisible}
          open={false}
          icon="filter"
          actions={[]}
          onStateChange={() => {} /* required! */}
          onPress={() => setIsVisible(true)}
      />
  );
}
```

### What have you tried

Still looking

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios and android
| react-native          | sdk36
| react-native-paper    | 3.10.1
| node                  | 13.3.0
| npm or yarn           | 6.5.0
| expo sdk              | 36

When rendering this component in my view, I can't click on anything on my page, it seems that there's an invisible element on top of everything.

This happen on android/ios, why?

**Comment by giniedp** [comment]
Can we reopen this? Happens to me as well when `actions` is set to empty list.

**Comment by giniedp** [comment]
nevermind. Issue somehow disappeared and i dont know Why. Will open another issue once i can reproduce.
