### ISSUE TITLE
how to enable dark theme?

### ISSUE THREAD

**Issue by arasrezaei** [callstack/react-native-paper#2043]
hello,
i set `dark: true` in theme object but no change!
i use android 9 emulator with react native 0.62 & and latest react native paper;

- `react-native`: 0.62.2
- `react-native-paper`: 3.10.1
- `react-native-vector-icons`: 7.0.0

**Comment by SleeplessByte** [comment]
The colors also need to be "dark". Instead of `DefaultTheme`, use `DarkTheme` as your base, or provide your own colors.
