### ISSUE TITLE
Colors on <Switch /> on the web are transparent

### ISSUE THREAD

**Issue by kopax** [callstack/react-native-paper#2045]
### Current behaviour

Rendering a `<Switch />` ont he web will have no border

### Expected behaviour

I expect to see some relief or at least border when I am on the web

### Screenshots (if applicable)

I have on the web: 

[![enter image description here][1]][1]

Since it doesn't look like a switch, I want to add some `border`. 

I can see that `.css-view-1dbjc4n.r-bottom-1p0dtai.r-height-1dernwh.r-left-1d2f490.r-margin-ywje51.r-position-u8s1d.r-right-zchlnj.r-top-ipm5af.r-transitionDuration-13tjlyg.r-width-13qz1uu` is what I want to target in my console so I can fix the web, but that's not helping to target it:

[![enter image description here][2]][2]

This is what I have in my `Component` tabs:

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/NcVXO.png
  [2]: https://i.stack.imgur.com/BoaBZ.png
  [3]: https://i.stack.imgur.com/evqQA.png

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | web
| react-native          | expo
| react-native-paper    | 3.10.1
| node                  | 13.5.0
| npm or yarn           | 6.5.0
| expo sdk              | 36

How can I fix the border of the switch on the web (instead of transparent)?

**Comment by kopax** [comment]
I solved it with:

```css
[data-switch]>div:first-child {
    background-color: #999;
}
```

and adding the `data-switch` props.

Perhaps this could be done in react-native-paper?

**Comment by BatDroid** [comment]
I see the same issue even in the [react native docs](https://reactnative.dev/docs/switch)
