### ISSUE TITLE
Disabling a checkbox does not disable onPress

### ISSUE THREAD

**Issue by msageryd** [callstack/react-native-paper#2047]
Setting disabled={true} on a checkbox does not seem to disable the onPress event. Is this by design?

**Comment by BatDroid** [comment]
could you provide a snack example?

**Comment by msageryd** [comment]
Argh.. I' soo sorry for bothering you with this. It turned out that the component I was using was a Checkbox.android wrapped in a TouchableRipple. The touchable needed to be disabled as well, of course.

Good thing to ask for a snack. I suppose many "bugs" disappears when you need to go through the code properly enough to create a snack =)
