### ISSUE TITLE
Card.title Overflow handling

### ISSUE THREAD

**Issue by tylerthedeveloper** [callstack/react-native-paper#2065]
### Current behaviour

When the card.title title text is too long it overflows with ... and pushes the right icon off the page

### Expected behaviour

Wrapping should automatically apply; this was working in the past 

### Code sample

<Card.Title
            title={'This is a really long text aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}
            subtitle={subtitle}
            titleStyle={{ flexWrap: 'wrap', flexDirection: 'row' }}
            left={(props) => <Avatar.Icon icon={left}  {...props} />}
            right={(props) => {
                    <IconButton icon={rightIcon} {...props} onPress={_onPress} />
            }}
        />

### Screenshots (if applicable)

This is working

![previously workibg](https://user-images.githubusercontent.com/13102536/87843882-d55ebb80-c86c-11ea-861f-f742a290e654.png)

This is not working

![no wrap for overflow](https://user-images.githubusercontent.com/13102536/87843871-ba8c4700-c86c-11ea-9bdb-217874e15f26.png)

### What have you tried

I have tried to play around with the styling of the title and the card.title style of the container and have had no success

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | (both)
| react-native          |  38.0.0
| react-native-paper    | 3.8.0
| node                  | 14.4.0
| npm or yarn           | 6.14.5
| expo sdk              | 3.21.13
| expo  | 38.0.0

**Comment by tylerthedeveloper** [comment]
Updated - i dont carry a dependency for vector icons and the rest are there

**Comment by tylerthedeveloper** [comment]
Any thoughts here? 

I do think there was a breaking change but haven't been able to locate it

**Comment by tylerthedeveloper** [comment]
I assume this is because of this: https://github.com/callstack/react-native-paper/pull/821

Is there not a case to make for not restricting? Why cant we jsut allow people to put max lines instead of defaulting it to 1

**Comment by albertbuchard** [comment]
Any way to solve that ?

**Comment by warmijusti** [comment]
Same issue here...

**Comment by chrismerino** [comment]
> Same issue here...

Can you try with "titleNumberOfLines={2}" or any number that fit your needs.
