### ISSUE TITLE
IconButton animating constantly, tested on 3.11.0 and 4.0.1

### ISSUE THREAD

**Issue by karimcambridge** [callstack/react-native-paper#2069]
### Current behaviour

The icon is constantly animating, prior to 3.11.0, it would only animate when interacted with, which I assume is how it should be, right?

### Expected behaviour

Not having a constant animation unless interacted with.

### Code sample
```
import { FontAwesome5 } from '@expo/vector-icons';

<IconButton
										key={4}
										icon={props => <FontAwesome5 {...props} name='bars' />}
										color={theme.colors.black}
										size={20}
										style={{ ...styles.drawerIcon, top: insets.top + 5, left: insets.left + 5 }}
										onPress={props.navigation.openDrawer}
										animated={true}
									/>
```

### Screenshots (if applicable)

https://share.icloud.com/photos/0ff39CAqCmv8fO0ouBIodG83w

### What have you tried

Not applicable.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS 13.5.1
| react-native          | 0.62.2
| react-native-paper    | 4.0.1
| node                  | 14.4
| npm or yarn           | latest
| expo sdk              | 38

**Comment by karimcambridge** [comment]
Just bumping for stale bot.

**Comment by mmaass** [comment]
Not sure if I am experiencing the same issue, but the symptoms are similar. 
My app freezes and the CPU usage skyrockets, if i specify the name of the icon as follows
`<IconButton icon={props.type === 'like' ? 'thumb-up-outline' : 'thumb-down-outline' />`

if instead i do this, the problem doesn't arise
`{props.type === 'like' && <IconButton icon="thumb-up-outline" />}
      {props.type === 'dislike' && <IconButton icon="thumb-down-outline"  />}`

**Comment by micahlt** [comment]
Same issue here - this is making my app almost unusable.
