### ISSUE TITLE
Fix progress bar

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#207]
We broke it. It shows an indeterminate circle right now.

**Comment by lukewalczak** [comment]
@satya164 @ferrannp probably we have to wait for fix this issue within react native. Read the discussion in the commit about it: https://github.com/facebook/react-native/commit/ccddbf82d79833702f19d9f6ed1ca23755655187#diff-6e407d4b540029e5d7becdb789c5680c

**Comment by lukewalczak** [comment]
Thanks to Satya's PR #208 it works properly again!
