### ISSUE TITLE
MaterialBottomTabNavigator doesn't have tap feedback on iOS

### ISSUE THREAD

**Issue by andreialecu** [callstack/react-native-paper#2073]
### Current behaviour

The MaterialBottomTabNavigator uses `TouchableWithoutFeedback` on iOS:
https://github.com/callstack/react-native-paper/blob/master/src/components/BottomNavigation.tsx#L300

This results in no sort of feedback appearing when tapping to switch the tab. On Android a Ripple is rendered.

This is especially bad when the entire tab bar is configured to only a single solid color (no separate colors per screen).

I'm using the bottom tab navigator via `@react-navigation/material-bottom-tabs`.

### Expected behaviour

I think it would be a good idea to display some sort of visual indication on tap. A `TouchableHighlight` might make more sense. The Facebook app on iOS displays a light gradient when tapping its bottom bar.

### What have you tried

There appears to be a `renderTouchable` property, but when using `createMaterialBottomTabNavigator` from `@react-navigation/material-bottom-tabs` it is never called. Example below:

```tsx
const Tab = createMaterialBottomTabNavigator();

<Tab.Navigator barStyle={styles.barStyle} renderTouchable={() => { console.log("foo") /* never called */ }}>
```

`renderTouchable` is not really documented, and `TouchableProps` is not exported so it makes it really hard to use. Seems to have been added in https://github.com/callstack/react-native-paper/pull/1901 but it's usage is unclear.

### Your Environment

| software              | version
| --------------------- | -------
| react-native          | 0.63.1
| react-native-paper    | 3.10.1

**Comment by micahlt** [comment]
Bumping this - seems to still be the case in the latest version of react-native-paper.  `renderTouchable` is documented but never called.
