### ISSUE TITLE
TextArea Component

### ISSUE THREAD

**Issue by abreumatheus** [callstack/react-native-paper#2081]
There's a component missing, following the material design guidelines, the TextArea. A text input for longer text. I know there's the option in the TexInput component to make it multiline, but it does not make it taller to show to the user that they can write multiple lines in there. And if you change the height of the component, the text stays in the center of the field, instead of being in the start.

![printscreen](https://user-images.githubusercontent.com/13948812/88468984-d4a7d400-cec1-11ea-8ecd-45c43fe7f092.jpg)

**Comment by sureshavv** [comment]
Im also facing the same issue

**Comment by mtakac** [comment]
@abreumatheus did you find some way how to solve this? I am also trying to use text input as a text area, but I cannot figure out how to position the text correctly after increasing the height of the text input.

**Comment by RichardLindhout** [comment]
Can you try

```jsx
const [height, setHeight] = React.useState(undefined)
 <TextInput 
        multiline 
        placeholder="Write something with multilines  here.."
         onContentSizeChange={(event) => {
           setHeight(event.nativeEvent.contentSize.height)
        }}
    
        style={{
          height, // <- set the max height here
        }} />
```

**Comment by roberts-d** [comment]
Try This!
```
    const [Description, setDescription] = React.useState('');

 <TextInput
                                    multiline
                                    mode="outlined"               
                                    numberOfLines={4}
                                    value={Description}
                                    onChangeText={(Description) => { setDescription(Description) }}
                                />
```

**Comment by adamchenwei** [comment]
> Try This!
> 
> ```
>     const [Description, setDescription] = React.useState('');
> 
>  <TextInput
>                                     multiline
>                                     mode="outlined"               
>                                     numberOfLines={4}
>                                     value={Description}
>                                     onChangeText={(Description) => { setDescription(Description) }}
>                                 />
> ```

That did not work for ios though. any idea to make it work?

**Comment by sufyansalim** [comment]
TextArea will be much appreciated component added to react native paper

**Comment by ajay-mandaviya** [comment]
Passing minHeight work fine
 <TextInput
                                    multiline
                                    mode="outlined"               
                                    numberOfLines={4}
                                   style = {{ minHeight : 100 }}

                                />

**Comment by ashaffah** [comment]
> Can you try
> 
> const [height, setHeight] = React.useState(undefined)
> <TextInput
> 	multiline
> 	placeholder="Write something with multilines  here.."
> 	onContentSizeChange={(event) => {
> 		setHeight(event.nativeEvent.contentSize.height)
> 	}}
> 	style={{
> 		height, // <- set the max height here
> 	}} 
> />

it's work for me Ty, this is mine :

```typescript
const [height, setHeight] = useState<number | undefined>(undefined);
const [numberOfLines, setNumberOfLines] = useState<number>(1);

const calculateNumberOfLines = (
    contentHeight: number,
    lineHeight: number,
  ) => {
    return Math.floor(contentHeight / lineHeight);
  };

  const handleContentSizeChange = (
    event: NativeSyntheticEvent<TextInputContentSizeChangeEventData>,
  ) => {
    const {height: contentHeight} = event.nativeEvent.contentSize;
    const lineHeight = 20;
    const lines = calculateNumberOfLines(contentHeight, lineHeight) - 1;
    setNumberOfLines(lines);
    setHeight(contentHeight);
  };

return (
/*
===== Your Code =====
*/
            <TextInput
                  onContentSizeChange={handleContentSizeChange}
                  style={[
                    styles.textInput,
                    {
                      height: numberOfLines <= 10 && height,
                      textAlignVertical: 'top',
                    },
                  ]}
                  editable={true}
                  outlineColor={errors.detail_report ? 'red' : undefined}
                  mode={'outlined'}
                  label={'Detail Report'}
                  multiline={true}
                  value={value}
                  numberOfLines={10}
                  onChangeText={onChange}
                />
)
```
