### ISSUE TITLE
The file back-chevron.png is crashing any app that uses expo-updates 

### ISSUE THREAD

**Issue by shamilovtim** [callstack/react-native-paper#2082]
### Current behaviour

Our app was crashing at startup. We thought the culprit was expo-updates but apparently it's an incompatibility between expo-updates and react-native-paper.

Context is here: https://github.com/expo/expo/issues/9310

Apparently the file `'/node_modules/react-native-paper/src/assets/back-chevron.png'` is in some way not properly included or referenced in the plugin, which breaks expo-updates. This causes user's apps to instantly shutdown when the application is opened.

### Expected behaviour

Stack trace from a different user is here: https://github.com/expo/expo/issues/9310
Here is our stack trace: https://pastebin.com/yMfLihni. 

### Your Environment

react-native-paper ^3.11.0

```shell
Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.1.0 - /usr/local/bin/fish
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4 => 4.4.0
    npmGlobalPackages:
      expo-cli: 3.22.3
```

**Comment by BatDroid** [comment]
To be honest, I'm not sure how it can be related to my PR. I just change the way that the icon was being render. Do you have any idea for that?

**Comment by satya164** [comment]
The asset is imported like any other asset in React Native. If it crashes with Expo, it needs to be fixed in Expo. Not an issue in React Native Paper.
