### ISSUE TITLE
Typescript "focusable" prop required issue in v4

### ISSUE THREAD

**Issue by jcbdev** [callstack/react-native-paper#2084]
### Current behaviour

All components that contain the property "focusable" are causing typescript to complain that focusable property has not been supplied.

### Expected behaviour

This property should not be required everywhere

### Code sample

Any component for example
```
<Surface></Surface>
```

### Screenshots (if applicable)

<img width="768" alt="Screenshot 2020-07-28 at 00 03 33" src="https://user-images.githubusercontent.com/17152092/88600343-eaee9500-d065-11ea-8f98-db22c272b55c.png">

### What have you tried

N/A

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | All
| react-native          | 0.62.2
| react-native-paper    | 4.0.1
| node                  | 14.4.0
| npm or yarn           | 1.22.4
| expo sdk              | 0.0.0 (None)
| react-native-vector-icons | 6.6.0

**Comment by azuxx** [comment]
I have the same problem and I've just updated from 0.62.2 to 0.63.2. Any help please?

**Comment by raajnadar** [comment]
what is the version of `@types/react-native`?

**Comment by azuxx** [comment]
> what is the version of `@types/react-native`?

you got right, I missed to update @types/react-native to version 0.63.2.
Fixed.

thanks! @raajnadar

**Comment by raajnadar** [comment]
Closing this issue assuming the OP forgot to update the types.

**Comment by jcbdev** [comment]
@raajnadar I did not update the types because I am still on react native 0.62.2 and not 0.63.2!  My app cannot be upgraded to 0.63.2 yet.  Shouldn't this be compatible with 0.62.2 as well?

**Comment by raajnadar** [comment]
Paper v4 requires react native 0.63 as minimum required version. If you want to use old rn version use paper v3.

**Comment by jcbdev** [comment]
> Paper v4 requires react native 0.63 as minimum required version. If you want to use old rn version use paper v3.

Ok cool. I didn't see that mentioned anywhere in the docs.

**Comment by raajnadar** [comment]
The docs is not yet updated for v4 I guess it is still for v3.
