### ISSUE TITLE
SearchBar re-renders itself on every text change, which makes it look jerky

### ISSUE THREAD

**Issue by bulatgab** [callstack/react-native-paper#2087]
Hi everyone!

### Issue
I'm using a SearchBar in my `render()` like this:
```
      <>
        <Searchbar
          onChangeText={query => this.getSearchResults(query)}
          value={this.state.query}/>

        <FlatList
          data={this.state.searchResults}
          /* renderItem ... */
        />
      </>
```
And on every text change, the SearchBar's text jitters, as `this.state.query` gets updated:
```
  async getSearchResults(query: string): Promise<void> {
    // ...

    this.setState({query, searchResults})
  }
```

But if I use a `TextInput` (without the `value` property), it works smoothly:
```
      <>
         <TextInput
          onChangeText={query => this.getSearchResults(query)}
         />

        <FlatList
          data={this.state.searchResults}
          /* renderItem ... */
        />
      </>
```
(but I'd prefer to use the SearchBar).

### Question
- Is it just me? What am I doing wrong?
- Why is the SearchBar's `value` prop mandatory? Can it be made optional?

Thanks!

### Package versions:
- `react-native 0.61.5`
- `react-native-paper 3.10.1`
- `react-native-vector-icons 6.6.0`

**Comment by raajnadar** [comment]
Read this docs 

https://reactjs.org/docs/forms.html#controlled-components
https://reactjs.org/docs/forms.html#alternatives-to-controlled-components

When you use uncontrolled component you do not pass a value prop to the text input which reduces the call between the JS & native side, so the performance is good in uncontrolled. But uncontrolled components have downsides like form validation is hard.

**Comment by bulatgab** [comment]
Thank you @raajnadar for a quick response, I'll read that
