### ISSUE TITLE
How do I use a Chip with "Remove" icon?

### ISSUE THREAD

**Issue by morfsys** [callstack/react-native-paper#2088]
I am trying to use Chip component with a "remove" icon on the right
The documentation here: https://callstack.github.io/react-native-paper/chip.html
says nothing about achieving anything like this. However, it is available

I am not sure what is suggested way to do this instead of using a custom style.

**Comment by thisBrian** [comment]
You'll need to define the [onClose](https://callstack.github.io/react-native-paper/chip.html#onClose) prop for it to appear.
