### ISSUE TITLE
Expose more styles via props

### ISSUE THREAD

**Issue by yermie** [callstack/react-native-paper#2093]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to apply custom styles to a component, but the `style` prop cannot override the property I am targeting. For example, while the `<Button>` component exposes `labelStyle`, the `<FAB>`does not. 

**Describe the solution you'd like**
To the fullest extent possible, components should allow their styles to be overridden via props that target all parts of the component. The best example I can give is the styling solution for material-ui, such as in their [button component](https://material-ui.com/api/button/). I would also vote for passing a style object where styles can be passed to override specific rule names. For example, a default key is `root`, another one for `label`, and so on.

**Describe alternatives you've considered**
Oftentimes I have to build an existing component from scratch in order for it to match our needed design.

**Additional context**
Some components expose many style properties, such as the [`<Card.Title>`](https://callstack.github.io/react-native-paper/card-title.html). However others like the [`<FAB>`](https://callstack.github.io/react-native-paper/fab.html) do not.

**Comment by satya164** [comment]
Please open separate specific feature requests about the features you need and why.

**Comment by yermie** [comment]
I don't understand your comment. The specific feature request is "expose style props consistently and comprehensively across components." I also gave specific examples of how one button component exposes the label while the other does not. Do you want me to go through each component and say which props I want exposed? I'd also be happy to simply open a PR since it will take the same amount of time. Please advise.

**Comment by satya164** [comment]
"expose style props consistently and comprehensively across components." is vague and doesn't help people who want to send PRs or try to look into what's needed to be done. You need to be more specific for your issue to be actionable.

You gave a single example for a missing label style in `FAB`. If you need label styling for FAB, open an issue specifically for FAB, similarly for any other features you want for specific components. Then they can be separately looked into and tracked.
