### ISSUE TITLE
FAB options

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#210]
https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions

Some animation fun.

![components-fab-flyouts-do](https://user-images.githubusercontent.com/774577/33379166-9ce90c38-d517-11e7-848b-fe3acad920c7.png)

**Comment by jukben** [comment]
This should be implemented also with the toolbar transformations? I mean FAB -> Toolbar -> (scroll) -> FAB, or just plain static FAB button and FAB button with animation (buttons raising from it)?

**Comment by lukewalczak** [comment]
Nope, this ticket will cover only one animation related to screenshot above. However I'm open to create more animations.
