### ISSUE TITLE
Type script errors

### ISSUE THREAD

**Issue by jauggy** [callstack/react-native-paper#2101]
### Current behaviour

I created a react native app then added typescript then added react-native-paper and added PaperProvider to the index.

Get errors after running

`yarn tsc`

Sample errors:

```
node_modules/react-native-paper/lib/typescript/src/components/Badge.d.ts:64:59 - error TS2344: Type '"visible" | "size" | "style" | "ref" | "children" | "key" | "onLayout" | "testID" | "nativeID" | "accessible" | "accessibilityActions" | "accessibilityLabel" | "accessibilityRole" | ... 26 more ... | "textBreakStrategy"' does not satisfy the constraint '"visible" | "size" | "style" | "ref" | "children" | "theme"'.
  Type '"key"' is not assignable to type '"visible" | "size" | "style" | "ref" | "children" | "theme"'.
```

### Expected behaviour

No errors

### Code sample

https://github.com/jauggy/ReactNativeDemo

### What have you tried

I'm not sure what I should do to fix the problem.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |   
| react-native          | 0.63.2
| react-native-paper    | 4.0.1
| node                  |
| npm or yarn           |  yarn version 1.22.4
| expo sdk              |

**Comment by raajnadar** [comment]
Make sure you have latest version of `@types/react-native`

**Comment by jauggy** [comment]
I have installed version 0.63.4 which is the latest.

**Comment by shubhamkes** [comment]
Facing similar issue

**Comment by contactsimonwilson** [comment]
@jauggy upgrading @types/react-native to from 0.63.4 to 0.63.6 and the issue will be resolved. I have verified the same in your repo.
