### ISSUE TITLE
getting error during react-native start

### ISSUE THREAD

**Issue by viveKing21** [callstack/react-native-paper#2102]
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Mon Aug 03 2020 13:10:40.700]  WARN     Require cycle: node_modules\react-native-paper\src\components\ToggleButton\ToggleButton.tsx -> node_modules\react-native-paper\src\components\ToggleButton\ToggleButtonRow.tsx -> node_modules\react-native-paper\src\components\ToggleButton\ToggleButton.tsx

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Mon Aug 03 2020 13:10:40.900]  ERROR    Invariant Violation: Tried to register two views with the same name GestureHandlerRootView
[Mon Aug 03 2020 13:10:40.100]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Mon Aug 03 2020 13:10:40.110]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Mon Aug 03 2020 13:10:40.120]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Mon Aug 03 2020 13:10:40.130]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by viveKing21** [comment]
please fix this issue

**Comment by Trancever** [comment]
Please ignore the warnings for now - https://github.com/callstack/react-native-paper/issues/639#issuecomment-522457956
