### ISSUE TITLE
Change Floating Label Style of TextInput

### ISSUE THREAD

**Issue by MaykonMorais** [callstack/react-native-paper#2103]
Hi There :smile:

Two days ago i was trying to change some styles of TextInput, i changed colors, fontsize and much more. But i couldn't change the **proximity between floating label (TextInput) and underline**. How i do this?

![Screenshot from 2020-08-03 11-37-32](https://user-images.githubusercontent.com/43121724/89194509-d9355200-d57d-11ea-8916-d036cf2dc6a6.png)

**Comment by sjonchhe** [comment]
I was also trying to create more space between label and textinput,couldnt find any solution yet.

**Comment by MaykonMorais** [comment]
@sjonchhe If you want more space between label and textinput, you can use vertical padding.

**Comment by Snowirbix** [comment]
How is there no customization for this ?
The default value is so off
there is like 10px of empty space above the label
