### ISSUE TITLE
fonts usage example 

### ISSUE THREAD

**Issue by andy-io** [callstack/react-native-paper#2105]
I have configured fonts as shown in the examples and documentation. 

By default if i use the text component from react native paper i get the regular font family which i have configured in the themes.

How do i use the medium, light and thin fonts in text components ?

Thank you

**Comment by andy-io** [comment]
react-native: 0.62.2
react-native-paper: 3.10.1
react-native-vector-icons: 6.6.0

**Comment by anhdevit** [comment]
This is should a question not issue

**Comment by andy-io** [comment]
yes this is a question, not an issue

**Comment by anhdevit** [comment]
I think you can add question tag like this

![Screen Shot 2020-08-05 at 16 41 09](https://user-images.githubusercontent.com/43532946/89397810-80f77f00-d73a-11ea-8217-a07d3c85e63f.png)

**Comment by andy-io** [comment]
i cant add a tag/label, i dont get the option to add a label. It needs to be added by moderators.
