### ISSUE TITLE
field sizes are different when using left or right in TextInput

### ISSUE THREAD

**Issue by anhdevit** [callstack/react-native-paper#2107]
### Current behaviour

I want to use left and right to add button hidden or visible password. But I cannot add their property. This error alway show: Malformed calls from JS: field sizes are different

### Expected behaviour
How can I add button like this

<img width="695" alt="Screen Shot 2020-08-05 at 16 25 48" src="https://user-images.githubusercontent.com/43532946/89396207-7936db00-d738-11ea-85a7-d079cba1edd3.png">

### Code sample
```
<TextInput
          mode="outlined"
          style={[styles.inputContainerStyle, styles.fontSize]}
          label="Outlined large font"
          placeholder="Type something"
          value={outlinedTextPassword}
          onChangeText={(outlinedTextPassword) =>
            inputActionHandler('outlinedTextPassword', outlinedTextPassword)
          }
          secureTextEntry={outlineTextSecureEntry}
          right={
            <TextInput.Icon
              name={outlineTextSecureEntry ? 'eye' : 'eye-off'}
              onPress={() =>
                dispatch({
                  type: 'outlineTextSecureEntry',
                  payload: !outlineTextSecureEntry,
                })
              }
            />
          }
        />
```

### Screenshots (if applicable)
![Simulator Screen Shot - iPhone 11 - 2020-08-05 at 16 23 07](https://user-images.githubusercontent.com/43532946/89395813-00d01a00-d738-11ea-97d0-342604bf039c.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS
| react-native          | 0.61.5
| react-native-paper    | 3.10.1
| node                  |
| npm or yarn           |
| expo sdk              |

**Comment by Trancever** [comment]
@anhdevit Could you post how did you resolve the issue so other devs who also encounter this problem can check that?

**Comment by anhdevit** [comment]
> @anhdevit Could you post how did you resolve the issue so other devs who also encounter this problem can check that?

The error appears when I using react-native-paper | 3.10.1 so I try to update latest version 4.0.1 and this is my way to resolve this problem

**Comment by namchuai** [comment]
I'm facing this problem, even though the version of "react-native-paper": "4.0.1" and "react-native-paper": "4.3.0".
