### ISSUE TITLE
iOS build breaking after 0.63.0 upgrade

### ISSUE THREAD

**Issue by aiaangel** [callstack/react-native-paper#2108]
### Current behaviour

iOS release build breaks after upgrading to 0.63.2, gives error on index.js

### Expected behaviour

iOS release builds work as expected

### Code sample

index.js

```
import React from 'react';
import {AppRegistry} from 'react-native';
import {Provider} from 'react-native-paper';

import App from './App';
import {name as appName} from './app.json';

const Main = () => {
  return (
    <Provider>
      <App />
    </Provider>
  );
};

AppRegistry.registerComponent(appName, () => Main);
```

### Error

Showing All Messages
+ node /Users/angel/repos/upgradetest/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/angel/Library/Developer/Xcode/DerivedData/upgradetest-eyabsoocsnwvyvdknlukemkgdcif/Build/Intermediates.noindex/ArchiveIntermediates/upgradetest/BuildProductsPath/Release-iphoneos/upgradetest.app/main.jsbundle --assets-dest /Users/angel/Library/Developer/Xcode/DerivedData/upgradetest-eyabsoocsnwvyvdknlukemkgdcif/Build/Intermediates.noindex/ArchiveIntermediates/upgradetest/BuildProductsPath/Release-iphoneos/upgradetest.app

                 Welcome to React Native!

                Learn once, write anywhere

error SyntaxError: /Users/angel/repos/upgradetest/ios/index.js: Unexpected token (15:6)

[0m [90m 13 | [39m  [36mreturn[39m ([0m
[0m [90m 14 | [39m    [33m<[39m[33mProvider[39m[33m>[39m[0m
[0m[31m[1m>[22m[39m[90m 15 | [39m      [33m<[39m[33mApp[39m [33m/[39m[33m>[39m[0m
[0m [90m    | [39m      [31m[1m^[22m[39m[0m
[0m [90m 16 | [39m    [33m<[39m[33m/[39m[33mProvider[39m[33m>[39m[0m
[0m [90m 17 | [39m  )[33m;[39m[0m
[0m [90m 18 | [39m}[33m;[39m[0m. Run CLI with --verbose flag for more details.

SyntaxError: /Users/angel/repos/vitality/upgradetest/ios/index.js: Unexpected token (15:6)

[0m [90m 13 | [39m  [36mreturn[39m ([0m
[0m [90m 14 | [39m    [33m<[39m[33mProvider[39m[33m>[39m[0m
[0m[31m[1m>[22m[39m[90m 15 | [39m      [33m<[39m[33mApp[39m [33m/[39m[33m>[39m[0m
[0m [90m    | [39m      [31m[1m^[22m[39m[0m
[0m [90m 16 | [39m    [33m<[39m[33m/[39m[33mProvider[39m[33m>[39m[0m
[0m [90m 17 | [39m  )[33m;[39m[0m
[0m [90m 18 | [39m}[33m;[39m[0m

echo 'error: File /Users/angel/Library/Developer/Xcode/DerivedData/upgradetest-eyabsoocsnwvyvdknlukemkgdcif/Build/Intermediates.noindex/ArchiveIntermediates/upgradetest/BuildProductsPath/Release-iphoneos/upgradetest.app/main.jsbundle does not exist. This must be a bug with'

### What have you tried

On RN 0.62.2 it works as expected, tried upgrading other dependencies but the result is the same. Removed the theme from index.js and just leave the provider, still displays the error on build.
The error can be reproduced on local via xcode and on Microsoft Appcenter

 react-native  0.63.2
 react-native-paper  4.0.1
 react-native-vector-icons 7.0.0
 node  12.18.3
 yarn     1.22.4

**Comment by raajnadar** [comment]
How did you know this error is from react native paper?

**Comment by aiaangel** [comment]
@raajnadar due to the errors an the fact that it was the only package installed, after some time onto it, turned out to be a babel issue
