### ISSUE TITLE
The Divider disappear when I set the alignItems attribute on the container

### ISSUE THREAD

**Issue by borgogelli** [callstack/react-native-paper#2110]
### Enviroment 

* react-native-paper: 3.6.0
* react-native-paper: 4.0.1
* react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz
* react-native-vector-icons: 0.0.0

### Current behaviour

The Divider element is not visible when I set the **alignItems** attribute for the container style

### Expected behaviour

The Divider element should be visible

### Code sample

https://snack.expo.io/@borgo/fbaf1b

### What have you tried

When I remove the **alignItems** attribute from the container, the Divider element becomes visible

**Comment by mattgoulet** [comment]
I can confirm that this is still happening in August, 2021. alignitems, when used on parent container, causes divider not to appear.

**Comment by rgold5950** [comment]
^^Reiterating this issue. center aligning parent view causes divider to disappear.

**Comment by antonvalletas** [comment]
This is still happening, should be reopened

**Comment by fathert0rque** [comment]
Is there a workaround for this? haha
