### ISSUE TITLE
Date and Time Picker component [WIP]

### ISSUE THREAD

**Issue by RichardLindhout** [callstack/react-native-paper#2118]
**Is your feature request related to a problem? Please describe.**
A lot of people requested the date / time picker components https://github.com/callstack/react-native-paper/issues/1489#issuecomment-559662408

**Describe the solution you'd like**
A date picker component which follows the specifications described here

**Describe alternatives you've considered**
There are no good quality libraries (as far as I know) who implement the Material Design spec with good integration on React Native (web)

**Additional context**
I'm working on a Date Picker component for React Native Paper. I'll publish this first as a separate package but I want to know if this could be integrated in React Native Paper is quality is good enough or maybe a section in the docs.

It uses VirtualizedList under the hood (to support endless scrolling, with the same strategy as this StackOverflow answer https://stackoverflow.com/questions/20584129/viewpager-in-android-to-switch-between-days-endlessly/23410686#23410686)

[WIP] Mobile layout (vertical for ranges)
![ezgif-7-f1e08465f79d](https://user-images.githubusercontent.com/6492229/89772566-8110c980-db02-11ea-9672-9096b4f90fcf.gif)

[WIP] Desktop layout 
![ezgif-7-a49b7927e6ff (1)](https://user-images.githubusercontent.com/6492229/89772685-bf0ded80-db02-11ea-994b-59aa2ae97bf8.gif)

**Comment by RichardLindhout** [comment]
Progress modal picker
![short-progress-react-native-date-picker](https://user-images.githubusercontent.com/6492229/89825522-fefdc080-db54-11ea-8efb-d2075f6fd399.gif)

**Comment by RichardLindhout** [comment]
Added input masking: https://twitter.com/RichardLindhout/status/1294636692540985344

**Comment by RichardLindhout** [comment]
First version is released: https://github.com/web-ridge/react-native-paper-dates

**Comment by raajnadar** [comment]
Nice work @RichardLindhout

**Comment by RichardLindhout** [comment]
![Schermafbeelding 2020-08-24 om 21 19 33](https://user-images.githubusercontent.com/6492229/91086675-86682b00-e64f-11ea-88d6-2d1c85a6c244.png)

Started working on time component

**Comment by RichardLindhout** [comment]
![ezgif-3-0bb4982423c4](https://user-images.githubusercontent.com/6492229/93935487-fe944000-fd24-11ea-8a27-c1c5003683aa.gif)

I'm slowly working on it in my spare time, here is some progress.

**Comment by RichardLindhout** [comment]
Progress can be followed on the development branch: https://github.com/web-ridge/react-native-paper-dates

**Comment by RichardLindhout** [comment]
![ezgif-6-0965298a1591](https://user-images.githubusercontent.com/6492229/94738735-23656480-0370-11eb-8d1c-58061bd9a86a.gif)

Slowly implementing all features :-)

**Comment by RichardLindhout** [comment]
Added minutes
![ezgif-2-340a10b79548](https://user-images.githubusercontent.com/6492229/95130241-913cd200-075c-11eb-8a9c-83efb4de7b90.gif)

**Comment by RichardLindhout** [comment]
0.2.1 released with dark mode and time picker!

https://github.com/web-ridge/react-native-paper-dates
![ezgif-4-0904a1b67ad7](https://user-images.githubusercontent.com/6492229/98868352-40fa1380-2470-11eb-9e28-5c3f3ec01856.gif)
Better frame rate: https://www.youtube.com/watch?v=SHhQU2doTug

**Comment by RichardLindhout** [comment]
Will do a PR for the react-native-paper website mentioning this library

**Comment by RichardLindhout** [comment]
Demo website is up: https://www.reactnativepaperdates.com/
