### ISSUE TITLE
Cannot change color of TextInput using styled compoents

### ISSUE THREAD

**Issue by vitogoh** [callstack/react-native-paper#2120]
### Current behaviour

```
import { TextInput } from 'react-native-paper';
import styled from 'styled-components/native';

const Input = styled(TextInput)`
  background-color: black;
  color: white;
`

const MyComponent = () => (
  <Input />
);

export default MyComponent;
```

### Expected behaviour

the background color is applied, but not the text color.

### Code sample

i was going to create a sample, but snack.expo.io doesn't support styled-components anymore

I'm running
react-native: 0.62.2
react-native-paper: 4.0.1
styled-components: 5.1.0

**Comment by SimonAM** [comment]
I'm using inline styling and still cant change text color of textinput.
    "react-native-paper": "^4.9.1",
    "expo": "^42.0.0"
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
