### ISSUE TITLE
TextInput `left` and `right` elements are not visible

### ISSUE THREAD

**Issue by sarmad1995** [callstack/react-native-paper#2128]
### Current behaviour

When the textinput has `right` or `left` element, it takes up the space which is required but doesn't show anything.

### Expected behaviour

It should show the react element which is provided.

### Code sample

https://snack.expo.io/@aashishdhawan/textinput?name=TextInput&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Ftext-input.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20TextInput%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Btext%2C%20setText%5D%20%3D%20React.useState(%27%27)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CTextInput%0A%20%20%20%20%20%20label%3D%22Email%22%0A%20%20%20%20%20%20value%3D%7Btext%7D%0A%20%20%20%20%20%20onChangeText%3D%7Btext%20%3D%3E%20setText(text)%7D%0A%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper

I have added a expo snack as well

### Screenshots (if applicable)

<img width="331" alt="Screenshot 2020-08-14 at 6 30 15 PM" src="https://user-images.githubusercontent.com/38377482/90251945-3ec9ee00-de5c-11ea-8479-1db0a1a2f7ee.png">

### What have you tried

I tried adding some zIndex to the container, but doesn't work

### Your Environment

| software              | version
| --------------------- | ------
| react-native-paper    | 4.0.1
| node                     | v12.16.3 
| npm or yarn         | 1.22.4
| expo sdk              | 38

**Comment by YahyaBagia** [comment]
You have to pass `<TextInput.Icon  name={"ICON-NAME"}/>` in the left and right props of TextInput.

```
import * as React from 'react';
import { View } from 'react-native'
import { TextInput } from 'react-native-paper';

const MyComponent = () => {
  const [text, setText] = React.useState('');
 const element = <TextInput.Icon name="lock-outline" />
  return (
    <TextInput
      label="Email"
      mode='outlined'
      style={{ backgroundColor: 'transparent' }}
      value={text}
      onChangeText={text => setText(text)}
      right= {element}
      left={element}
    />
  );
};

export default MyComponent;
```

**Comment by jsonpoindexter** [comment]
Thank you @YahyaBagia! I could not find this in the docs!

**Comment by YahyaBagia** [comment]
@jsonpoindexter, You're welcome. It isn't well documented yet.

**Comment by rizshivalli** [comment]
How do i add text to `right` and `left`? it only seems to be working with `<TextInput.Icon name={"ICON-NAME"}/>`

**Comment by raajnadar** [comment]
@rizshivalli use TextInput.Affix in left or right prop.

**Comment by AbdulmalekAlshugaa** [comment]
It seems the icons are not showing in my app :
![Screenshot_1661354301](https://user-images.githubusercontent.com/33663456/186457142-6249caa9-8063-4b66-a174-c458758e640a.png)

**Comment by gokulrajkp** [comment]
![Simulator Screen Shot - iPhone 13 - 2023-02-02 at 19 33 32](https://user-images.githubusercontent.com/73021893/216347270-d5f2daf4-5342-4bfb-a2e3-684700a7c7e4.png)

showing this error on iOS 

configured react native vector icons to iOS
but in react native vector icons there is no material design icons

installed versions ->

 "react": "18.1.0",
    "react-native": "0.70.6",
 "react-native-vector-icons": "^9.2.0"

**Comment by stephenson080** [comment]
@raajnadar how do i listen onPress event on the TextInput.Affix text

**Comment by eri-prado** [comment]
I changed NAME for ICON

<TextInput
          placeholder={placeholder}
          value={text}
          onChangeText={(text) => setText(text)}
          right={<TextInput.Icon icon={'menu-down'} />}
        />
