### ISSUE TITLE
List.Accordion: Can we change color of up arrow when its expanded ? 

### ISSUE THREAD

**Issue by rikinshah23** [callstack/react-native-paper#2132]
Hello,
is there a way to change color of up and down arrow for List.Accordion component? 

currently when the item is expanded it shows the upward arrow. I need to change color of up arrow when its expanded only. 

Thanks

**Comment by rubimbura** [comment]
The issue still exists. and it's annoying not to be able to change the color of the icon.

**Comment by MichielMortier** [comment]
Having the same issues, can this be added?

**Comment by spideyinf** [comment]
Yeah I do have this issue. Please take a look at this

**Comment by lukewalczak** [comment]
Hey, with the upcoming version new [prop](https://github.com/callstack/react-native-paper/blob/main/src/components/List/ListAccordion.tsx#L34) called `right` will be added to `List.Accordion` component, which will allow you to specify that component and customize it according to your needs. In the meantime you can use react-native-paper from main branch.

**Comment by manielli** [comment]
I have the latest 4.7.2 version and trying to use the `List.Icon` as the `right` prop for the `List.Accordion`. It seems like it completely ignores the right prop altogether. No matter what I pass to the `right` prop it will still show a black `chevron-up` or black `chevron-down` icon.

**Comment by lukewalczak** [comment]
Hey @manielli, that feature is not released yet. We are planning to do the release until the end of the week.

**Comment by manielli** [comment]
Thank you for your prompt response. Looking forward to it. It may be useful to put note on the docs at [https://callstack.github.io/react-native-paper/list-accordion.html](url) that this feature is not release yet. I have been scratching my head for 2 weeks now.

**Comment by lukewalczak** [comment]
@manielli new version 4.8.0 just landed on NPM.

**Comment by AvitaliyaORG** [comment]
In My case this is working

`theme={{colors: {text: UiColor.WHITE}}}`

**Comment by wiltonzanin** [comment]
> In My case this is working
> 
> `theme={{colors: {text: UiColor.WHITE}}}`

Thanks @AvitaliyaORG works for me!

**Comment by Subhashish-Mishra** [comment]
> In My case this is working
> 
> `theme={{colors: {text: UiColor.WHITE}}}`

Not working for me, in 2023

- `react-native` : `0.71.7`
- `react-native-paper` : `5.8.0`

**Comment by barth-zalewski** [comment]
Also not working

**Comment by Zenb0t** [comment]
After digging a bit into the implementation of the component, the theme prop responsible for the chevron color is onSurfaceVariant. So I did this in my component:

```
const accordionTheme = useMemo(
    () => ({
      ...theme,
      colors: {
        ...theme.colors,
        onSurfaceVariant: theme.colors.secondary,
      },
    }),
    [theme],
  );
```

And on the component:

```
 <List.Accordion
          theme={accordionTheme}
          {... all your other stuff} />
```

**Comment by soghammed** [comment]
@Zenb0t Thanks for onSurfaceVariant!

**Comment by thisisadithk** [comment]
> After digging a bit into the implementation of the component, the theme prop responsible for the chevron color is onSurfaceVariant. So I did this:
> 
> ```
> const accordionTheme = useMemo(
>     () => ({
>       ...theme,
>       colors: {
>         ...theme.colors,
>         onSurfaceVariant: theme.colors.secondary,
>       },
>     }),
>     [theme],
>   );
> ```
> 
> And on the component:
> 
> ```
>  <List.Accordion
>           theme={accordionTheme}
>           {... all your other stuff} />
> ```
> 
> Hope it helps. I know using the theme is an escape hatch, but it definitively works well.

This works exactly! Thanks :)

**Comment by alispa** [comment]
Works also directly in component: `theme={{colors: {onSurfaceVariant: "red"}}}`
