### ISSUE TITLE
List.Item onPress effect disable

### ISSUE THREAD

**Issue by b3rkaydem1r** [callstack/react-native-paper#2134]
Hello, how i can disable List.Item onpress effect? I want use like TouchableWithoutFeedback. No touch color.

An example;

`<List.Item
                title="NewYear" titleStyle={styles.text}
                onPress={updateNewYear}
                left={() => <Switch value={newyear} 
                color="#f18f01" onValueChange={updateNewYear} />}
            />`

**Comment by xXH4tchXx** [comment]
I would also like to see this feature implemented. Currently there isn't a "no feedback" prop
