### ISSUE TITLE
How to install new modules after setup?

### ISSUE THREAD

**Issue by ianaz** [callstack/react-native-paper#2135]
First of all thank you for your work! I followed your "getting started" guide and worked perfectly, but now I'm having quite a big issue on almost all new libraries I want to add...
I'm writing the application in React Native and having it transformed for web too and it works well until I install a library (For example the Bottom sheet [you recommend](https://callstack.github.io/react-native-paper/recommended-libraries.html)).

I install the new library, launch my application using `react-app-rewired start` and then, even if flow plugin, preset-env etc. are there I get errors like this one:

```.../workspace/Name/node_modules/react-native-gesture-handler/DrawerLayout.js: Support for the experimental syntax 'flow' isn't currently enabled (30:8):```

which suggests webpack isn't setup correctly; I then noticed in the `config-overrides.js` that you want babel presets/plugins only to be ran on `react-native-vector-icons` and `react-native-safe-area-view` modules.
To be clear ([as described here](https://callstack.github.io/react-native-paper/using-on-the-web.html)):

```
....
test: /\.js$/,
exclude: /node_modules[/\\](?!react-native-vector-icons|react-native-safe-area-view)/,
...
```

Whenever I add my new library there, I then get another compilation error:

```
./node_modules/react-native-gesture-handler/GestureButtons.js 244:65
Module parse failed: Unexpected token (244:65)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|           rest = _objectWithoutProperties(_this$props2, ["children", "style"]);
| 
>     const resolvedStyle = _reactNative.StyleSheet.flatten(style ?? {});
| 
|     return /*#__PURE__*/_react.default.createElement(BaseButton, _extends({}, rest, {

```

react: 16.13.1
react-native: 0.63.2
react-native-paper: 4.0.1
react-native-vector-icons: 7.0.0

Any suggestion? Thank you very much and sorry if it's a noob question

**Comment by arafatzahan** [comment]
Have you figured out how to solve this?

**Comment by arafatzahan** [comment]
@ianaz I've found the solution. '@babel/plugin-proposal-nullish-coalescing-operator' is needed.

**Comment by RichardLindhout** [comment]
You are trying to run react-native libraries on the web. Some of the react-native modules won't work on the web but only on Android and iOS.

In my opinion it's better to make an abstraction on top of react-router-dom and react-navigation and use react-router-dom on the web.

**Comment by kuasha420** [comment]
@RichardLindhout React Navigation Works SURPRISINGLY well on react native web, animation, url and everything. I was very surprised on how well it works.

**Comment by RichardLindhout** [comment]
Nice <3! I've tried react-navigation a few times in the past which is already 2/3 years ago I think and it did not work well enough back then performance wise on native.

I still use react-native-navigation, but I should try react-navigation since a lot of things have improved!
