### ISSUE TITLE
Add custom elements to TextInput left and right

### ISSUE THREAD

**Issue by samuelpetroline** [callstack/react-native-paper#2137]
As of v4.0.1, is there any way to add custom elements (icons, other components etc) to the `left` and `right` props of `TextInput`?

Thanks!

**Comment by samuelpetroline** [comment]
I did use `TextInput.Affix` but nothing really showed:

```js
left={startComplement && <TextInput.Affix>{startComplement}</TextInput.Affix>}
right={endComplement && <TextInput.Affix>{endComplement}</TextInput.Affix>}
```

![image](https://user-images.githubusercontent.com/22039767/91063162-ff419580-e603-11ea-8cb3-00621f012a9e.png)

I'm using a custom component so maybe that's the problem?

**Comment by raajnadar** [comment]
You can either pass icon prop or text prop, it does not accept children prop.

**Comment by arthurpankiewicz** [comment]
why was this issue closed? this would be a great feature to implement

**Comment by samuelpetroline** [comment]
For anyone needing something like this, this is how I solved:

```js
 <View style={{ display: 'flex', flexDirection: 'row' }}>
      <TextInput right={endComplement} />
      {endComplement && (
        <View
          style={{
            position: 'absolute',
            top: 0,
            bottom: 5,
            right: 16,
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
          }}
        >
          {endComplement}
        </View>
      )}
    </View>
```
