### ISSUE TITLE
Replace all touchable elements with Pressable to support hover/focus in the future

### ISSUE THREAD

**Issue by RichardLindhout** [callstack/react-native-paper#2142]
**Is your feature request related to a problem? Please describe.**

I would like it to make the Pressable status part of react-native-paper since it's an important part of moving forward and following the specifications on the web (focus/hover) and provide more and better styling when an elements is focused / pressed.

https://material.io/design/interaction/states.html#hover
https://material.io/design/interaction/states.html#focus

e.g.

```jsx
<Pressable
        onPress={() => {
          setTimesPressed((current) => current + 1);
        }}
        style={({ pressed, hovered, focused }) => [
          {
            backgroundColor: pressed
              ? 'rgb(210, 230, 255)'
              : 'white'
          },
          styles.wrapperCustom
        ]}>
        {({ pressed }) => (
          <Text style={styles.text}>
            {pressed ? 'Pressed!' : 'Press Me'}
          </Text>
        )}
      </Pressable>
```

**Describe a solution you'd like**

> To address these problems, we are shipping a new core component called Pressable. This component can be used to detect various types of interactions. The API was designed to provide direct access to the current state of interaction without having to maintain state manually in a parent component. **It was also designed to enable platforms to extend it's capabilities to include hover**, blur, focus, and more. We expect that most people will build and share components utilizing Pressable under the hood instead of relying on the default experience of something like TouchableOpacity.

https://reactnative.dev/blog/2020/07/06/version-0.63

**Additional context**
We will need to have support in React Native Web to support focus/hover which is where is also an issue about this subject
https://github.com/necolas/react-native-web/issues/1708

**Comment by RichardLindhout** [comment]
@Trancever Are you open for this change?

**Comment by weirdzardz** [comment]
@RichardLindhout nice job making react-native-web move forward with this on the Pressables.

I would also love to see react-native-paper integrate this feature as well. 

Note that it is both useful for cross-platform react native apps for web, but also for supporting mouse better on mobile.

**Comment by RichardLindhout** [comment]
Thanks! It would also integrate better with React Native on desktop Mac/Windows if they add the Pressable with hover. I see that Necolas pushed a lot of changes for hover support so I think it will be available in the next major release of react-native-web <3

**Comment by RichardLindhout** [comment]
Hover support is now available in React Native Web 0.14.0!

I'll look if I have time in the future to rewrite the TouchableRipple component to use the Pressable component so we'll have hover support there and in can add hover support to other components after that PR is merged

**Comment by RichardLindhout** [comment]
I'm working on a PR to add support for hover styles to the TouchableRipple!

**Comment by RichardLindhout** [comment]
https://github.com/callstack/react-native-paper/pull/2281
