### ISSUE TITLE
Breaking changes from 3x → 4x

### ISSUE THREAD

**Issue by m2mathew** [callstack/react-native-paper#2145]
Hey, team! 👋 

I am looking at how to upgrade from version 3x to 4x of RNP. The [release notes](https://github.com/callstack/react-native-paper/releases/tag/v4.0.0) do not indicate any breaking changes for this upgrade. I also don't see anything in the repo or the documentation site about upgrade paths.

Can someone direct me to where one might find the "gotchas" with the upgrade?

Thanks!

**Comment by raajnadar** [comment]
Hey, Check this out https://github.com/callstack/react-native-paper/wiki/Migration-guide-for-4.0

**Comment by m2mathew** [comment]
Thank you, @raajnadar! I humbly suggest the maintainers edit the Release notes for 4.0 to add a link to this helpful Wiki. It would also be wise to include in the `README.md` file.
