### ISSUE TITLE
How can i extend theme to my components that have separate style file?

### ISSUE THREAD

**Issue by vapstor** [callstack/react-native-paper#2147]
I have a (some) components and now i'm refactoring his styles to separate file.

i followed https://callstack.github.io/react-native-paper/theming.html#extending-the-theme and i don't know why for a moment _it works_, but now after some reloads he don't recognize the "theme" variable

```
import { StyleSheet } from 'react-native'
const styles = StyleSheet.create({ 
    container: {
       backgroundColor: theme.color.background
    }
})
export default styles
```
![Captura de tela de 2020-08-22 18-19-56](https://user-images.githubusercontent.com/15200187/90966070-b1fae200-e4a4-11ea-878a-eff6517ce3b1.png)
![Captura de tela de 2020-08-22 18-19-19](https://user-images.githubusercontent.com/15200187/90966073-b32c0f00-e4a4-11ea-8ca9-a987fd2edcea.png)
![Captura de tela de 2020-08-22 18-38-55](https://user-images.githubusercontent.com/15200187/90966254-cf30b000-e4a6-11ea-8338-ccbc7ddc4e0a.png)

My goal is pass the theme variable to this style.js separate file

Edit:
`"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz"`
`"react-native-paper": "^4.0.0"`
`"react-native-vector-icons": "^7.0.0"`
Edit2: attach my App.js

**Comment by nachozullo** [comment]
Hey @vapstor, im not sure about the performance impact with your solution.

I found another possible solution. 

Styles: 

```
const styles = StyleSheet.create({
    root: theme => ({
        flex: 1,
        backgroundColor: theme.colors.primary // access the theme
    }),
});
```

And inside your component, you can access the theme with `useTheme` hook or `withTheme` HOC and pass the theme as style prop like this:

`<Component style={styles.root(theme)} />`

**Comment by belfortmaycon** [comment]
Hi @nachozullo 
I'm using typescript... where can I found the type for theme in your code?
`root: (theme: ????) => ({...})`

Thanks

**Comment by nachozullo** [comment]
I think you can use the Theme type provided by react-native-paper.

 https://github.com/callstack/react-native-paper/blob/main/src/types.tsx

**Comment by belfortmaycon** [comment]
> I think you can use the Theme type provided by react-native-paper.
> 
> https://github.com/callstack/react-native-paper/blob/main/src/types.tsx

Got it! Thanks...
But now this is the error:
```
Type '(theme: Theme) => { alignSelf: string; paddingTop: number; color: string; }' is not assignable to type 'ViewStyle | TextStyle | ImageStyle'.
  Type '(theme: Theme) => { alignSelf: string; paddingTop: number; color: string; }' has no properties in common with type 'ImageStyle'.ts(2322)
styles.ts(12, 3): The expected type comes from property 'configText' which is declared here on type 'NamedStyles<any>

```
My style is:
```
import { StyleSheet } from 'react-native';
import { Theme } from 'react-native-paper/src/types';

const styles = StyleSheet.create({
  configText: (theme: Theme) => ({
    alignSelf: 'center',
    paddingTop: 20,
    color: theme.colors.primary,
  }),
});

export default styles;
```

**Comment by nachozullo** [comment]
Can you paste your package-json? What version of  `@types/react-native` are you using?

**Comment by belfortmaycon** [comment]
> Can you paste your `package.json`? What version of `@types/react-native` are you using?

I'm using 0.63.40 temporally because this issue: https://github.com/callstack/react-native-paper/issues/2442

package.json:
```
{
  "main": "src/index.ts",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest",
    "prettier:write": "npx prettier --write src/*.{js,jsx,ts,tsx} && npx prettier --write *.{js,jsx,ts,tsx}",
    "lint": "eslint src --ext .ts,.tsx"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
  "lint-staged": {
    "*.{ts,tsx}": [
      "eslint --fix",
      "git add"
    ]
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "@types/react-native": "0.63.40",
    "expo": "~40.0.0",
    "expo-splash-screen": "~0.8.0",
    "expo-status-bar": "~1.0.3",
    "expo-updates": "~0.4.0",
    "formik": "^2.2.6",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-paper": "^4.7.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.0",
    "react-native-unimodules": "~0.12.0",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@commitlint/cli": "^11.0.0",
    "@commitlint/config-conventional": "^11.0.0",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@typescript-eslint/eslint-plugin": "^4.11.1",
    "@typescript-eslint/parser": "^4.11.1",
    "babel-jest": "~25.2.6",
    "eslint": "^7.16.0",
    "eslint-config-prettier": "^7.1.0",
    "eslint-import-resolver-typescript": "^2.3.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-import-helpers": "^1.1.0",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "husky": "^4.3.6",
    "jest": "~25.2.6",
    "lint-staged": "^10.5.3",
    "prettier": "^2.2.1",
    "react-test-renderer": "~16.13.1",
    "typescript": "^4.1.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}

```

**Comment by yashpalraj** [comment]
@belfortmaycon Did you find any solution for this?

Type '(theme: Theme) => { alignSelf: string; paddingTop: number; color: string; }' is not assignable to type 'ViewStyle | TextStyle | ImageStyle'.
  Type '(theme: Theme) => { alignSelf: string; paddingTop: number; color: string; }' has no properties in common with type 'ImageStyle'.ts(2322)
styles.ts(12, 3): The expected type comes from property 'configText' which is declared here on type 'NamedStyles<any>


I am facing same error while using RN with Typescript.

TIA.
