### ISSUE TITLE
Error :No overload matches this call.

### ISSUE THREAD

**Issue by jaysu77** [callstack/react-native-paper#2149]
<img width="861" alt="Screenshot 2020-08-23 at 11 46 46 PM" src="https://user-images.githubusercontent.com/35101093/90985651-f668a980-e59a-11ea-88b6-b265add9ba74.png">

**Comment by testbuddy** [comment]
We are facing the same error :(

"react-native": "0.63.0",
"react-native-paper": "^4.0.1",
"react-native-vector-icons": "^7.0.0",

**Comment by raajnadar** [comment]
If you are using typescript upgrade it & also upgrade the react native types to latest version.

**Comment by kennethlynne** [comment]
I can confirm that upgrading @types/react-native to 0.63.23 solved it for me

**Comment by flesherj** [comment]
I continue to have this issue.  Any suggestions?  Below are a list of the dependencies.

"dependencies": {
    "@expo/vector-icons": "^12.0.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/native": "~5.9.2",
    "@react-navigation/stack": "~5.14.2",
    "@reduxjs/toolkit": "^1.5.0",
    "axios": "^0.21.1",
    "expo": "~40.0.1",
    "expo-asset": "~8.2.2",
    "expo-constants": "~10.0.1",
    "expo-font": "~9.0.0",
    "expo-linking": "~2.1.1",
    "expo-splash-screen": "~0.9.0",
    "expo-status-bar": "~1.0.3",
    "expo-web-browser": "~9.0.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-native-gesture-handler": "~1.10.0",
    "react-native": "^0.63.4",
    "react-native-paper": "^4.7.1",
    "react-native-vector-icons": "^8.0.0",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1",
    "react-native-web": "^0.14.13",
    "react-redux": "^7.2.2",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.13",
    "@types/axios": "^0.14.0",
    "@types/react": "^17.0.1",
    "@types/react-native": "^0.63.48",
    "@types/react-native-vector-icons": "^6.4.6",
    "@types/react-redux": "^7.1.16",
    "@typescript-eslint/eslint-plugin": "^4.15.0",
    "@typescript-eslint/parser": "^4.15.0",
    "eslint": "^7.19.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-config-standard": "^16.0.2",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "jest-expo": "~40.0.2",
    "prettier": "^2.2.1",
    "typescript": "~4.1.4"
  },
