### ISSUE TITLE
How can I change the accordion right 'chevron-up' 'chevron-down' icons to my custom icons?

### ISSUE THREAD

**Issue by sathwik77** [callstack/react-native-paper#2150]
Custom icons for accordion

- `react-native-paper 4.0.1`
- `expo 38.0`

**Comment by NagarajBD** [comment]
> Custom icons for accordion
> 
> * `react-native-paper 4.0.1`
> * `expo 38.0`

i am also have same problem, any one can help.

**Comment by henrik-d** [comment]
Maybe one could override the current chevron with a custom component if user passed a renderProp, e.g. like that:
```
right?: (props: {
        color: string;
        expanded: boolean;
    }) => React.ReactNode;
```
Would you accept an PR with this extension?

**Comment by moedeveloper** [comment]
why need answer :(, we really need this feature:(
did u guys solve it anyhow?

**Comment by samOpenforce** [comment]
Ability to customise the right icon (in both expanded and not-expanded states) would be a greatly appreciated feature. I'm not clever enough to create a PR to add this, please take pity :)
