### ISSUE TITLE
Add onLongPress to List.Item

### ISSUE THREAD

**Issue by kendallroth** [callstack/react-native-paper#2155]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add an `onLongPress` handler to the `List.Item` component (to complement existing `onPress` handler).

**Describe alternatives you've considered**
Likely will involve updating the `ListItem` file ([link](https://github.com/callstack/react-native-paper/blob/master/src/components/List/ListItem.tsx#L179)

**Additional context**
N/A

**Comment by brunohkbx** [comment]
`List.Item` [spread](https://github.com/callstack/react-native-paper/blob/master/src/components/List/ListItem.tsx#L180) the other props to the `TouchableRipple`, So you can pass `onLongPress` even though the component does not accept. That may be worth to be specified in the docs.

**Comment by kendallroth** [comment]
@brunohkbx Thank you for mentioning this, I'm not sure how I neglected to notice that while looking at the component source... 😕. At any rate, this was not working for me previously but clearly was the result of some other problem, as this does work as expected now. Updating the docs would be great though!

**Comment by kendallroth** [comment]
Ah @brunohkbx I realize now why I thought it wasn't working... If `onPress={() => {}}` is not also specified (ie. with an empty function), `onLongPress` will be ignored. Is there any documentation around this anywhere (seem to remember coming across it earlier, unsure where)?

**Comment by brunohkbx** [comment]
@kendallroth I had this problem once. It seems like something related to react native itself. You can try the same with a Touchable*. will only work If `onPress={() => {}}` is specified.

**Comment by kendallroth** [comment]
Ah, that is interesting. It would almost be nice (sometimes) to have the `onPress` ripple disabled if not specified with `onLongPress`, but that's just wishful thinking probably (and may seem to indicate to interactive ability). Thanks for the update!
