### ISSUE TITLE
upgrade to 4.0.1

### ISSUE THREAD

**Issue by samaneh-kamalian** [callstack/react-native-paper#2156]
I am in react native 0.61.4 and upgrade my react native paper to 4.0.1 but It has problem : 
```
react-native-paper/src/styles/DefaultTheme.tsx: Unexpected token (4:12)
import type { Theme } from '../types';
```
I upgrade my react native to 0.63 with upgrade command but the error is still remain.
How can solve my problem?
 thank you

**Comment by Trancever** [comment]
Please upgrade typescript version in your project. If that doesn't help then please reopen the issue.

**Comment by effektsvk** [comment]
Hello, I stumbled upon this as well, but I'm not using Typescript in my project, any suggestion what it could be?

**Comment by jLBasilio** [comment]
I encountered this, not using Typescript. Solved by deleting `node_modules/` and `yarn.lock` file (I'm using `yarn`).

**Comment by RahulLadybirdweb** [comment]
I am using react native 0.59.9 and upgrade my react native paper to 4.0.1 but It has problem :
 bundling failed: SyntaxError: node_modules/react-native-paper/src/styles/DefaultTheme.tsx: Unexpected token (4:12)

  2 | import { black, white, pinkA400 } from './colors';
  3 | import configureFonts from './fonts';
> 4 | import type { Theme } from '../types';
    |             ^
  5 | 
  6 | const DefaultTheme: Theme = {
  7 |   dark: false,
    at Object.raise (node_modules/@babel/parser/lib/index.js:6930:17)
