### ISSUE TITLE
Portal makes the app laggy when too many rerenders occur.

### ISSUE THREAD

**Issue by bboure** [callstack/react-native-paper#2157]
Hi,

I came across an issue when one of my  components forced a Portal to re-render too often.

My use case was a component with a `TextInput` wrapped in a Portal. Typing fast would cause some problems:
- The keyboard becomes laggy and becomes unresponsive
- `onChangeText` behaves strangely, some characters are duplicated. (example, typing `hello` very fast would sometimes become `hheello`.
After investigation, I found out that this happened because of Portal.

Example:

````tsx
const PortalWithTextInput = (props: Props) => {
  const [text, setText] = useState('');

  return (
    <Portal>
      <TextInput text={text} onChangeText={setText}>
    </Portal>
  );
};
````

Because of how this code is written, whenever the `text` state changes, the Component re-renders completely (including the Portal). This seems to be the root of all my issues.

When I moved the Portal outside of my component with Component composition, the problem went away.

Example:
````tsx
const MyTextInput = (props: Props) => {
  const [text, setText] = useState('');

  return (
      <TextInput text={text} onChangeText={setText} />
  );
};

const PortalWithTextInput = (props: Props) => {
  return (
    <Portal>
      <MyTextInput />
    </Portal>
  );
};
````

In the above code, Portal does not rerender after each keystroke.

I have not yet investigated what could be the source of this issue, but it looks like Portal has some performance issues when re-rendering too often/fast.

| software              | version
| --------------------- | -------
| ios or android        | problem is most visible on Android, but IOS seems also affected
| react-native          | 0.63.2
| react-native-paper    | 4.0.1
| node                  | v12.13.1
| npm or yarn           | yarn

**Comment by Stevemoretz** [comment]
I have the same issue

**Comment by yuukuari** [comment]
Same here

**Comment by karthick1231** [comment]
I have tried with 4.12.0-alpha.0  react-native-paper 0.66.4 react-native version. Still, Portal Dialog is Slow to hide. anything suggestions to hide fast?
