### ISSUE TITLE
AdjustsFontSizeToFit for Buttons

### ISSUE THREAD

**Issue by cr1979** [callstack/react-native-paper#2158]
Hello,
I need a way to automaticly scale a text in a button. So a larger text fit into a button. Currently there is no adjustsFontSizeToFit  property in the text element of the react native paper button.

**Is your feature request related to a problem? Please describe.**
React Native Paper supports adjustsFontSizeToFit property in the text element but not in buttons.

**Describe the solution you'd like**
I like that the attribute adjustsFontSizeToFit will be added to the button. So a text can automaticly scaled to fit. This is important if you have a multilanguage project.

**Describe alternatives you've considered**

**Additional context**
an example of a working text element:

     <Text adjustsFontSizeToFit={true} allowFontScaling={true} numberOfLines={1} style={[globalStyles.headline]}>{t('HEADER_TEXT')}</Text>

currently using:
react-native: ^0.62.2,
react-native-paper: ^3.6.0
react-native-vector-icons: ^6.6.0

**Comment by codekojo** [comment]
Still no solution?

**Comment by yannick-softwerft** [comment]
+1
