### ISSUE TITLE
TextInput height as percentage produce a warning, but actually works fine

### ISSUE THREAD

**Issue by MrSinaRJ** [callstack/react-native-paper#2159]
### Current behaviour

Right now when you enter height in style prop like this `{{ height: "100%" }}` it produce a warning that says 

> Currently we support only numbers in height prop
![Screen Shot 2020-08-25 at 9 04 31 AM](https://user-images.githubusercontent.com/25735924/91172099-03c48780-e6b2-11ea-92d4-08ed4d40464e.png)

but it works as it should be!

### Expected behaviour

As this works perfectly without any problem and bugs I think the warning should go away.

### Code sample

This is how I'm using it
```
<TextInput
          style={{ height: "100%" }}
          label="Review"
          mode="outlined"
          maxLength={maxLength}
          multiline
          returnKeyType="done"
          blurOnSubmit
          onChangeText={(text) => setReview(text)}
        />

```

### Screenshots

And this will be the result of the code above
![Screen Shot 2020-08-25 at 8 56 58 AM](https://user-images.githubusercontent.com/25735924/91171509-f3f87380-e6b0-11ea-8012-c9cf5d4cd307.png)

### Additional information

I should mention that this happens when I have this component got wrapped inside a view with `{{ height: 300 }}` prop. if I set the height directly to TextInput it will align vertically to center,( `{{ alignVertical: "top"}}` doesn't work) and there is no way to get a clean implementation like this one (Screenshot). Thus I'm suggesting that this warning is unnecessary and should be removed.

### Your Environment

| software              | version
| --------------------- | -------
| react-native          | 0.63.2
| react-native-paper    | 4.0.1
| node                  | 14.8.0
| npm            | 6.14.8
| yarn                  | 1.22.4
| expo              | 38.0.9
| @expo/vector-icons           | 10.2.0
|react-native-vector-icons    | 7.0.0

### EDIT
I added the environment section

I updated npm package to the latest version, even though I think it's completely irrelevant

### EDIT2
I just added the react-native-vector-icon to end the bot ………
what is this about really?! some unrelated packages versions are required!
I'm thinking of opening a new issue for that as well!! but I don't know what to put as version!!!!! 😂

**Comment by MrSinaRJ** [comment]
is this an abandoned repo?!?!
come on, at least say you will or will not fix this issue.

**Comment by RichardLindhout** [comment]
> is this an abandoned repo?!?!
> come on, at least say you will or will not fix this issue.

I understand your frustration, but please note people are all working for free on this. If you spit in the source code most of the time you can find the answer to the question yourself.

If you look at 
- https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/TextInputFlat.tsx#L94
you can see all kind of helpers where the calculateInputHeight with the provided height from styles
https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/TextInputFlat.tsx#L183

https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/helpers.tsx#L41

The internal calculations won't work when a percentage is provided. So the library maintainers can not easily remove this warning unless they rewrite everything.

I agree the Github Actions both should be less strict and the issue template could be better. I'll see if I can make a suggestion to make this better.
