### ISSUE TITLE
Theme roundness more manageable

### ISSUE THREAD

**Issue by mundurragac** [callstack/react-native-paper#2160]
**Is your feature request related to a problem? Please describe.**
TextInput roundness is currently only a plain number that change the border radius of the hole component, but i need to change the border corners independently.

**Describe the solution you'd like**
I suggest that roundness can be either a number or an object like {topRight, topLeft, bottomRight, bottomLeft}

react-native 0.62.2
react-native-paper 4.0.1
react-native-vector-icons 7.0.0

**Comment by e4basil** [comment]
Is there any workaround ?
