### ISSUE TITLE
"TypeError: touch is undefined" when using keyboard navigation on button on the web

### ISSUE THREAD

**Issue by NoemiRozpara** [callstack/react-native-paper#2162]
### Current behaviour

When I click button on the web, works ok, but when I focus using tab and hit enter, this happens:
<img width="1274" alt="obraz" src="https://user-images.githubusercontent.com/27765703/91420755-64d89080-e855-11ea-97de-430dbbcf3b18.png">

### Expected behaviour

Keyboard navigation should work correctly.

### Code sample

```
// submit is a state setter for now, so nothing could break here
<Button onPress={() => submit(email)}>Continue</Button>
```
Button.tsx
```
<PaperButton
        contentStyle={{}} // style
        style={[]} // style
        labelStyle={[]} // style
        disabled={undefined}
        mode="contained"
        theme={{}} // theme
        {...rest}> //actually just onPress
{children}
</PaperButton>
```
### What have you tried

Didn't find anything in Google, also nothing suspicious in the implementation

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | web "^0.13.1"
| react-native          | "0.62.2"
| react-native-paper    | "^4.0.1"
| node                  | v10.16.3
| npm or yarn           | yarn 
| expo sdk              | non-expo project

**Comment by Trancever** [comment]
Fixed in 4.1.0
