### ISSUE TITLE
Chip - allow icon on right or customizing close icon

### ISSUE THREAD

**Issue by jazzdragon** [callstack/react-native-paper#2163]
**Is your feature request related to a problem? Please describe.**
With the chip component, the close icon is hard coded.

**Describe the solution you'd like**
Either add a prop for icon on the right or prop to override the close icon

**Describe alternatives you've considered**
Overriding the call to font awesome or adding an icon in the body of the chip, both of them not great solutions.

**Additional context**
react-native 0.62.2
react-native-paper 4.0.1

**Comment by Trancever** [comment]
That's what MD Guidelines recommend.

**Comment by gblikas** [comment]
@Trancever I petition to open this issue. It would be really helpful to have the ability to _at least_ re-size the "close icon", and maybe not necessarily `rtl`, as @jazzdragon mentions; With many styles, having the ability to slightly enlarge or shrink the icon makes a big difference in look and feel.

**Comment by DeniferSantiago** [comment]
@gblikas I have the same opinion
