### ISSUE TITLE
[Question] Is a change of the Icon of IconButton possible?

### ISSUE THREAD

**Issue by Chaostheorie** [callstack/react-native-paper#2164]
I've recently started developing with react native paper. It's a really good library but for some reason I can't find a way to change the icon of an `IconButton` element. This should happen on press. I haven't found anything about manipulating this in the docs. Is there some method or prop I'm missing?

My purpose is to change the icon from `pause` to `play` and trigger a function. This is meant for a timer.

My current code with the button (abbreviated for simplicity}:
```
{ container and code }
<IconButton
  icon="pause"
  color={DefaultTheme.colors.primary}
  size={50}
 />
{ more code }
```

Environment;
react-native-paper: 4.0.1
react-native-vector-icons: 7.0.0
react-native: 38.0.2

**Comment by Trancever** [comment]
I don't understand. You can just pass another icon name e.g.:

```
<IconButton
  icon="play"
  color={DefaultTheme.colors.primary}
  size={50}
 />
```
