### ISSUE TITLE
Horizontal padding applied outside of the text input

### ISSUE THREAD

**Issue by isuert** [callstack/react-native-paper#2169]
### Current behaviour

Setting `paddingHorizontal` in the `style` prop of `TextInput` does not change the horizontal padding inside the input, but the one outside.

### Expected behaviour

I would expect `paddingHorizontal` to affect the horizontal padding inside the input. The outer padding can always be set by a wrapper component.

### Code sample

https://snack.expo.io/@isuert/paddinghorizontal-where-you-at

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios 13.6
| react-native          | 0.60.6
| react-native-paper    | 4.1.0
| node                  | 12.18.0
| npm or yarn           | 1.22.4
| expo sdk              | 38.0.0

**Comment by anhquan291** [comment]
Same problem here !
