### ISSUE TITLE
DrawerItem should have pointerEvents="none" when onPress not set

### ISSUE THREAD

**Issue by grabbou** [callstack/react-native-paper#217]
As in the title, when having DrawerItem embedded within Drawer (react-navigation), I don't want to set `onPress` and let the built-in handlers do their thing. 

Right now, DrawerItem registers Touchable that captures touches and automatically prevents the built-in handler from being called.

Expected behaviour:

I would expect DrawerItem to either not have Touchable component or have pointerEvents none when `onPress` is undefined.

**Comment by kpsroka** [comment]
@grabbou I think that I have a fix, could you give me an example code that I can use to test that? I'm not sure how you use the built-in handler.

**Comment by grabbou** [comment]
```
<TouchableOpacity onPress={() => alert('test')}><DrawerItem /></TouchableOpacity>
```
doesn't work unless I explicitly set pointerEvents on the TouchableOpacity to disable interaction with children.

Should work w/o issues/
