### ISSUE TITLE
[Proposal] Add an option to Modal in order to avoid keyboard

### ISSUE THREAD

**Issue by bboure** [callstack/react-native-paper#2172]
This is related to #1495

## The problem

When a Modal/Dialog contains a TextInput and you focus the TextInput, the keyboard comes over the Modal.
This often hides the Action buttons, other TextInput bellows, or even the focused text input in some cases (IOS).
This is not very user Friendly.
An option is to wrap the Modal around a `KeyboardAvoidingView`. However, this comes with its own set of issues:

- When the modal is hidden, the KeyboardAvoidingView remains, making the below views not responsive to touches.
- Adding `pointerEvents="box-none"` fixes the previous issue, but it is still not ideal, because when the modal is hidden, that View remains there top of everything (even if it's empty). It is useless but is still rendered.
- I have tried doing something like `{visible && <KeyboardAvoidingView><Modal ..../></KeyboardAvoidingView>}` but that messes up the fade in/out animations of the Dialog.

## Possible solutions

Ideally, what we want is KeyboardAvoidingView to be **inside** the Modal component, [around here](https://github.com/callstack/react-native-paper/blob/master/src/components/Modal.tsx#L202)
That way, it would get [rendered or not](https://github.com/callstack/react-native-paper/blob/master/src/components/Modal.tsx#L184) depending on the Modal state.

I can think of 2 ways to do this:

1) we add an `avoidKeyboard` prop (default to false) to the Modal/Dialog components. When true, we would wrap the Modal inside a KeyboardAvoidingView. Otherwise, we keep doing as now.

2) For more flexibility, we add a `WrapperComponent` prop that receives any kind of Component or a function that returns one. A bit similar to [CellRendererComponent](https://reactnative.dev/docs/virtualizedlist#cellrenderercomponent) in a VirtualizedList.
When given, the Modal is wrapped with it.
This would let users choose what Component to use. For example, one could pass KeyboardAvoidingView with specific props (like `behavior`, `keyboardVerticalOffset`).

Let me know if you have any comment.

Thanks

**Comment by a-gierczak** [comment]
Hello, I've ran into the same issue and also found out that there aren't any easy workarounds. I think this is an important issue because it totally breaks usability in some cases.
I know that guys at `react-native-modal` has this sorted out, maybe we should look into their solution?
I really like paper's modals and would prefer to use them instead of rolling yet another library.

**Comment by rye761** [comment]
Here is my solution in the mean time:

```javascript
import * as React from 'react';
import { Dialog } from 'react-native-paper';
import { Keyboard } from 'react-native';

export default class KeyboardAvoidingDialog extends React.Component {
  constructor(props) {
    super(props);
    this.subscriptions = [];
    this.state = {
      bottom: 0
    }
  }

  componentDidMount() {
    if (Platform.OS === 'ios') {
      this.subscriptions = [
        Keyboard.addListener('keyboardWillChangeFrame', this.onKeyboardChange.bind(this)),
      ];
    } else {
      this.subscriptions = [
        Keyboard.addListener('keyboardDidHide', this.onKeyboardChange.bind(this)),
        Keyboard.addListener('keyboardDidShow', this.onKeyboardChange.bind(this)),
      ];
    };
  }

  componentWillUnmount() {
    this.subscriptions.forEach(subscription => {
      subscription.remove();
    });
  }

  onKeyboardChange(e) {
    if (e.endCoordinates.screenY < e.startCoordinates.screenY)
      this.setState({ bottom: e.endCoordinates.height / 2});
    else
      this.setState({ bottom: 0 });
  }

  render() {
    return (
      <Dialog style={{ bottom: this.state.bottom }} visible={this.props.visible} onDismiss={this.props.onDismiss}>
        {this.props.children}
      </Dialog>
    )
  }
}```

Not perfect, it takes advantage of the fact that a dialog is centered on the screen and bumps it up by half the keyboard height. I'm pretty satisfied with this and it's a pretty simple implementation.

**Comment by RichardLindhout** [comment]
In my case this worked great: https://github.com/web-ridge/react-native-paper-dates/blob/master/src/Time/TimePickerModal.tsx#L118.

**Comment by RichardLindhout** [comment]
It would indeed be better if react-native-paper supported this use case. I think it would be nice without config and just works great out of the box.

**Comment by ezekel** [comment]
I have the same issue is this already fix ? but it's not documented

**Comment by teajohnson90** [comment]
Having issue with this as well, I think this is a useful proposal.

**Comment by ishiestar** [comment]
Please reopen this issue. I have this issue as well! Using @rye761's solution meanwhile...

**Comment by kelvinwelter** [comment]
Same issue here, is there something on the roadmap to address this issue?

**Comment by yinshurman** [comment]
🙄same issues , please make some improvements!

**Comment by jorgemasta** [comment]
Thanks for your workaround @rye761. Here is a version using hooks:
```jsx
  const [bottom, setBottom] = React.useState(0)

  React.useEffect(() => {
    function onKeyboardChange(e) {
      if (e.endCoordinates.screenY < e.startCoordinates.screenY)
        setBottom(e.endCoordinates.height / 2)
      else setBottom(0)
    }

    if (Platform.OS === "ios") {
      const subscription = Keyboard.addListener("keyboardWillChangeFrame", onKeyboardChange)
      return () => subscription.remove()
    }

    const subscriptions = [
      Keyboard.addListener("keyboardDidHide", onKeyboardChange),
      Keyboard.addListener("keyboardDidShow", onKeyboardChange),
    ]
    return () => subscriptions.forEach((subscription) => subscription.remove())
  }, [])
  
  
    return (
      <Dialog style={{ bottom }} visible={visible} onDismiss={onDismiss}>
        {children}
      </Dialog>
    )
  ```

**Comment by dk253** [comment]
Should this line: `if (e.endCoordinates.screenY < e.startCoordinates.screenY)`
Be: `if (e.endCoordinates.screenY <= e.startCoordinates.screenY)`

**Comment by TrustyTechSG** [comment]
Im facing "Cannot read property 'screenY' of undefined" error on Android on 5.0.1 (and newest 5.1.0). it happens when TextInput just get focused, and it only happens on Android, anyone have the same issue?

![image](https://user-images.githubusercontent.com/36871034/208635874-56b96d78-fbec-4c5c-ac01-bc7571f42d9b.png)

**Comment by error-try-again** [comment]
Hiya, during my testing I found that the onKeyboardChange event listener throws an undefined error on e.startCoordinates. After inspecting the event I could see that the endCoordinates value is being passed but the startCoordinates value isn't. 

```
    function onKeyboardChange(e) {
      console.log(e);
...
```

the event:
`{"duration": 0, "easing": "keyboard", "endCoordinates": {"height": 246, "screenX": 0, "screenY": 287.3333435058594, "width": 320}} `

> Thanks for your workaround @rye761. Here is a version using hooks:
> 
> ```js
>   const [bottom, setBottom] = React.useState(0)
> 
>   React.useEffect(() => {
>     function onKeyboardChange(e) {
>       if (e.endCoordinates.screenY < e.startCoordinates.screenY)
>         setBottom(e.endCoordinates.height / 2)
>       else setBottom(0)
>     }
> 
>     if (Platform.OS === "ios") {
>       const subscription = Keyboard.addListener("keyboardWillChangeFrame", onKeyboardChange)
>       return () => subscription.remove()
>     }
> 
>     const subscriptions = [
>       Keyboard.addListener("keyboardDidHide", onKeyboardChange),
>       Keyboard.addListener("keyboardDidShow", onKeyboardChange),
>     ]
>     return () => subscriptions.forEach((subscription) => subscription.remove())
>   }, [])
>   
>   
>     return (
>       <Dialog style={{ bottom }} visible={visible} onDismiss={onDismiss}>
>         {children}
>       </Dialog>
>     )
> ```

**Comment by nonam4** [comment]
I'll leave here my workaround too:

I was reading in docs and I saw:
`It requires a Portal.Host component to be rendered .... if you're using the Provider component, this already includes a Portal.Host`

So what I did was wraping my `Provider` with the `KeyboardAvoidingView` and now every Modal/Dialog goes up when keyboard is visible.

Sometime this can break your layout behind the Modal/Dialog but to me this is not a problem.
My code is something like this:

```
// index.tsx
import { Provider } from 'react-native-paper'
import { KeyboardAvoidingView } from 'react-native'

.....

return (
 <KeyboardAvoidingView .... >
    <Provider>
        <AppContent />
    </Provider>
 </KeyboardAvoidingView>
```

**Comment by PolyPlugins** [comment]
> @rye761 and @jorgemasta,
> 
> Should this line: `if (e.endCoordinates.screenY < e.startCoordinates.screenY)` Be: `if (e.endCoordinates.screenY <= e.startCoordinates.screenY)`

This should be updated, otherwise when switching input fields it will cause the modal to return to the original position behind the keyboard.

**Comment by simonbengtsson** [comment]
For us the keyboard change method mentioned above was crashing on Android (iOS was working fine). It happened when the keyboard was opened for other text fields not related to the dialog (e.endCoordinates was null so e.endCoordinates.startY crashed). 

We could have checked for this case, but chose the much simpler, although not perfect, solution of always presenting the dialog at the top of the screen. This is also used in the [comprehensive-portal-example](https://snack.expo.dev/@react-native-paper/comprehensive-portal-example) linked from the [portal docs](https://callstack.github.io/react-native-paper/docs/components/Portal).


      <Dialog style={{ position: 'absolute', top: '10%', left: 0, right: 0 }}>
         {...}
     </Dialog>

**Comment by JPStrydom** [comment]
Can we please re-open this as it's still an open issue?

**Comment by shuo-hiwintech** [comment]
> Thanks for your workaround [@rye761](https://github.com/rye761). Here is a version using hooks:
> 
>   const [bottom, setBottom] = React.useState(0)
> 
>   React.useEffect(() => {
>     function onKeyboardChange(e) {
>       if (e.endCoordinates.screenY < e.startCoordinates.screenY)
>         setBottom(e.endCoordinates.height / 2)
>       else setBottom(0)
>     }
> 
>     if (Platform.OS === "ios") {
>       const subscription = Keyboard.addListener("keyboardWillChangeFrame", onKeyboardChange)
>       return () => subscription.remove()
>     }
> 
>     const subscriptions = [
>       Keyboard.addListener("keyboardDidHide", onKeyboardChange),
>       Keyboard.addListener("keyboardDidShow", onKeyboardChange),
>     ]
>     return () => subscriptions.forEach((subscription) => subscription.remove())
>   }, [])
>   
>   
>     return (
>       <Dialog style={{ bottom }} visible={visible} onDismiss={onDismiss}>
>         {children}
>       </Dialog>
>     )

Compatible with android：

```
function onKeyboardChange(e: KeyboardEvent) {
      if (isIos()) {
        if (
          e?.startCoordinates &&
          e.endCoordinates.screenY < e.startCoordinates.screenY
        ) {
          setBottom(e.endCoordinates.height / 2);
        } else {
          setBottom(0);
        }
      } else {
        if (e?.endCoordinates?.height) {
          setBottom(e.endCoordinates.height / 2);
        } else {
          setBottom(0);
        }
      }
    }
```
