### ISSUE TITLE
Touchable is no longer maintained

### ISSUE THREAD

**Issue by 3Omar3** [callstack/react-native-paper#2176]
**"react": "^16.11.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz",
"react-native-paper": "^4.1.0",**

> Unable` to resolve "./components/TouchableRipple" from "node_modules\react-native-paper\src\index.tsx"

**Comment by dhash357** [comment]
I am having this issue also. 

here are the versions for the above-listed components
  "dependencies": {
    "@react-native-community/cli-platform-android": "^4.10.1",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/picker": "^1.6.5",
    "@react-navigation/compat": "^5.2.3",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/material-bottom-tabs": "^5.2.16",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "acorn": "^7.3.1",
    "core-js": "^3.1.4",
    "lodash": "^4.17.19",
    "mixin-deep": "^2.0.1",
    "react": "^16.13.1",
    "react-art": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-native": "^0.63.2",
    "react-native-appearance": "^0.3.4",
    "react-native-camera-kit": "^8.0.4",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-paper": "^4.0.1",
    "react-native-reanimated": "^1.10.1",
    "react-native-safe-area-context": "^3.1.1",
    "react-native-screens": "^2.9.0",
    "react-native-vector-icons": "^7.0.0",
    "react-native-web": "^0.13.4",
    "react-navigation": "^4.4.0",
    "set-value": "^3.0.2",
    "typescript": "^3.9.7"
  },

**Comment by borgogelli** [comment]
Same issue for me

**Comment by cescoallegrini** [comment]
@3Omar3 @borgogelli
Try `expo start -c`

**Comment by borgogelli** [comment]
@3Omar3 Resolved with version 4.2.0 and "expo start -c"
Thank you
