### ISSUE TITLE
FAB Group TouchableRipple Size

### ISSUE THREAD

**Issue by gsevla** [callstack/react-native-paper#2190]
Hey guys, I'm trying to increase FAB action TouchableRipple size, but I think it's not possible.

Analyzing FAB [Component https://github.com/callstack/react-native-paper/blob/master/src/components/FAB/FAB.tsx](url) we can **standard** and **small** styles match with sizes on these screenshots.

Then looking at FAB.Group Component [https://github.com/callstack/react-native-paper/blob/master/src/components/FAB/FABGroup.tsx](url) we can see **small** prop statically defined.

_Am I right when I think It's not possible (for now) change TouchableRipple size?_

- react-native: 0.61.5
- react-native-paper: ^4.1.0
- react-native-vector-icons: ^7.0.0

![Screenshot_20200904-100057_Rastro System 20](https://user-images.githubusercontent.com/36795971/92246161-c0c99780-ee9b-11ea-8f39-e37318f97995.png)
![Screenshot_20200904-100103_Rastro System 20](https://user-images.githubusercontent.com/36795971/92246163-c1622e00-ee9b-11ea-816e-3acc35dae83c.png)
![Screenshot_20200904-100115_Rastro System 20](https://user-images.githubusercontent.com/36795971/92246164-c1fac480-ee9b-11ea-849c-f58d4bc0677f.png)
![Screenshot_20200904-100140_Rastro System 20](https://user-images.githubusercontent.com/36795971/92246167-c2935b00-ee9b-11ea-8a54-6c0b1bea7ffd.png)

**Comment by RafikiTiki** [comment]
I'll try to make `FAB.Group` more customisable :)

**Comment by gsevla** [comment]
Oh, thanks man!

**Comment by Trancever** [comment]
@gsevla I've just merged the PR. Sorry it took so long. I'll release a new version this week!
