### ISSUE TITLE
App crashes on startup due to an `Calling synchronous methods not supported in Chrome` error.

### ISSUE THREAD

**Issue by rodperottoni** [callstack/react-native-paper#2193]
### Current behaviour

Activating the Chrome Debugger causes the app to crash on startup with this error:
`Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.`

This issue is originated from the `Provider.tsx` file (see image below). I found this issue by toggling "Pause on uncaught exceptions" on and navigating through the stack trace.

### Expected behaviour

App should run flawlessly with Chrome debugger turned.

### Screenshots (if applicable)

![Screen Shot 2020-09-06 at 4 04 26 pm](https://user-images.githubusercontent.com/15217227/92319395-06808e80-f05b-11ea-8699-f2c8b49ec9fa.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios  | 13.5
| react-native | 0.62.1
| react-native-paper    | both 4.0.1 and 4.1.0
| node                  | 10.15.3
| yarn           | yarn 1.21.1

**Comment by OlimpiaZurek** [comment]
@rodperottoni can't reproduce this issue. I'm using `react-native-paper 4.2.0`. Try to upgrade and then check if this issue still exist.
