### ISSUE TITLE
Customizable Checkbox icon size

### ISSUE THREAD

**Issue by kendallroth** [callstack/react-native-paper#2212]
**Is your feature request related to a problem? Please describe.**
It is semi-frustrating to not be able to change the checkbox (icon) size.

**Describe the solution you'd like**
It would be nice to be able to change the checkbox `MaterialIcon` size via a new prop (likely `size`), although it may be necessary to also update the styles (or pass them as another prop `iconStyle` through to the checkbox).

**Describe alternatives you've considered**
I have not been able to implement this at all currently.

An additional alternative would be allowing user to specify custom icons for the checkbox states (if they would animate).

**Additional context**
N/A

- `react-native`: `0.62.3`
- `react-native-paper`: `4.1.0`
- `react-native-vector-icons`: `6.6.0`

**Comment by kendallroth** [comment]
Still would like to see this being a possibility (and radio buttons)!

**Comment by kendallroth** [comment]
May I ask why this was closed? I left a comment to indicate that it still is applicable, albeit not an issue but a suggestion?

**Comment by tnewmanheggie** [comment]
Hi, I'd like to see this implemented as well.

**Comment by arafathmisree** [comment]
Hi, I cannot address to resize as well why you guys built an element library without being able to resize.

**Comment by Ranjithramesh67** [comment]
> Hello, I am also unable to change the size of checkbox icon, as I cannot find any prop in the documentation. Can anybody find the solution ?? My versions are:
> 
> **react-native: 0.66.0 react-native-paper: 4.9.2 react-native-vector-icons: 8.1.0**

This library doesn't have a feature for changing the size of the checkbox.

**Comment by egavrilova-indeed** [comment]
+1 to allowing user to specify custom icons for the checkbox states
