### ISSUE TITLE
Typescript + Styled-Components + withTheme

### ISSUE THREAD

**Issue by 1nfinity-5starZ** [callstack/react-native-paper#2217]
Hello guys, I'm kind of new to TypeScript so I can't really solve this issue.

I'm trying to create a custom component using Styled-Components and wrapping it with the withTheme helper

```

type TabProps =  {
  active?: Boolean;
}

const Tab = withTheme(
  styled(Text)<TabProps>`
    border-bottom-width: 3px;
    border-bottom-color: ${({ theme, active }) => active ? theme.colors.primary : 'transparent' };
    padding-bottom: 8px;
    margin: 16px;
    margin-left: 0;
    font-family: ${({ active }) => active ? 'Montserrat-SemiBold' : 'Montserrat-Regular' };
    font-size: 20px;
  `
)

```

Works fine but then when I render the component itself TS gives me an error:
![image](https://user-images.githubusercontent.com/19469895/92607290-4c6f6980-f28a-11ea-8d7b-2e4b41ca4e3d.png)

Was working fine without the withTheme wrapper. Any help on how to solve that ?

Versions:
    "react-native-paper": "^4.1.0",
    "styled-components": "^5.1.1"

**Comment by RemyMachado** [comment]
I think this issue is still not solved. We can't directly use the theme within the styledComponents library.
It's a pain to work with, please reopen.
