### ISSUE TITLE
Customize TextInput underline color and  height

### ISSUE THREAD

**Issue by shahmeerkhalid** [callstack/react-native-paper#2223]
I am using flat textInput. is there any way to change width of text input underline?
using "react-native-paper": "^4.1.0",

**Comment by kendallroth** [comment]
It does not look like it is customizable at the moment: [`TextInputFlat`](https://github.com/callstack/react-native-paper/blob/0a8f1b08195509889d1355b504c6bbbb87a61bd6/src/components/TextInput/TextInputFlat.tsx#L378). The `Underline` component styles are static and the height is set to `2`

_P.S. Maybe change the issue title to "Customize TextInput underline height" (title mentions color right now...)_

**Comment by jfbn** [comment]
According to [the documentation](https://callstack.github.io/react-native-paper/text-input.html) the prop "underlineColor" exists, however it does not have any effect - at least not on Android.

I tried with "underlineColorAndroid" aswell, also no result. 

It would be great to get this working :)

**Comment by saideep1011** [comment]
same issue if found any solution please share

**Comment by RichardLindhout** [comment]
For me underlineColor works but it uses the primary color when focused, correct? Maybe there should be an underlineColorFocused or something like that.

**Comment by gmartinu** [comment]
Yep, underlineColor works only when it's out of focus, there are any way to override the underline when focused ?

**Comment by gmartinu** [comment]
The color problem is fixed in #1797
