### ISSUE TITLE
Add imports to docs examples

### ISSUE THREAD

**Issue by thymikee** [callstack/react-native-paper#223]
Currently docs feature examples like this:
```js
const MyComponent = () => (
  <Button raised onPress={() => console.log('Pressed')}>
    Press me
  </Button>
);
```
What I find not great for DX here is the lack of `import` statement, which clearly states how to import the module.

This looks much better and removes the ambiguity of how to import specific component:
```js
import { Button } from 'react-native-paper';

const MyComponent = () => (
  <Button raised onPress={() => console.log('Pressed')}>
    Press me
  </Button>
);
```

**Comment by jukben** [comment]
+1

**Comment by iamclaytonray** [comment]
@thymikee, @ferrannp  - I can tackle this if you guys are open to that?

**Comment by thymikee** [comment]
Sure!

**Comment by iamclaytonray** [comment]
Cool. Should I include other imports as well? IE:

```js
import { View } from 'react-native';

// etc

```

**Comment by thymikee** [comment]
If it doesn't take too much of real estate then I'm ok with it. @satya164 what do you think?

**Comment by satya164** [comment]
Sounds good to me

**Comment by iamclaytonray** [comment]
Cool

**Comment by iamclaytonray** [comment]
I'll leave off React imports. I think most people know React has to be in scope. If you guys say otherwise, I'll add it, else, I'll just do necessary imports

**Comment by satya164** [comment]
If we are adding imports, let's add everything that's needed to copy/paste and run the example

**Comment by iamclaytonray** [comment]
Will do

**Comment by thymikee** [comment]
Hm, later on we can add snacks to some more advanced examples as a playground.

**Comment by iamclaytonray** [comment]
Hmm. So, am I namespacing React or not?

**Comment by thymikee** [comment]
Do it :)

**Comment by iamclaytonray** [comment]
I think I got everything about right. Feel free to review whenever you have time. (No rush)
