### ISSUE TITLE
React native paper require cycle warnings

### ISSUE THREAD

**Issue by khaledBou** [callstack/react-native-paper#2233]
I don't understand why the issue #1897 is closed, i still got the same warning 

System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Memory: 49.22 MB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - /usr/local/opt/node@12/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native: 0.61.5

"react-native-paper": "^3.10.1",

## Description
I tried to use react native paper components for my react native applications.
Currently i use  `"react-native-paper": "^3.9.0",`
I launched the application in Android mobile
I got warnings 
`[Tue May 05 2020 13:06:41.270]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\Checkbox\Checkbox.js -
> node_modules\react-native-paper\lib\module\components\Checkbox\CheckboxItem.js -> node_modules\react-native-paper\lib\module\compo
nents\Checkbox\Checkbox.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Tue May 05 2020 13:06:41.272]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\FAB\FAB.js -> node_mod
ules\react-native-paper\lib\module\components\FAB\FABGroup.js -> node_modules\react-native-paper\lib\module\components\FAB\FAB.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Tue May 05 2020 13:06:41.273]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\RadioButton\RadioButto
n.js -> node_modules\react-native-paper\lib\module\components\RadioButton\RadioButtonItem.js -> node_modules\react-native-paper\lib\
module\components\RadioButton\RadioButton.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Tue May 05 2020 13:06:41.273]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\Appbar\Appbar.js -> no
de_modules\react-native-paper\lib\module\components\Appbar\AppbarHeader.js -> node_modules\react-native-paper\lib\module\components\
Appbar\Appbar.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Tue May 05 2020 13:06:41.273]  WARN     Require cycle: node_modules\react-native-paper\lib\module\components\ToggleButton\ToggleBut
ton.js -> node_modules\react-native-paper\lib\module\components\ToggleButton\ToggleButtonRow.js -> node_modules\react-native-paper\l
ib\module\components\ToggleButton\ToggleButton.js`
## React Native version:
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 12.35 GB / 23.88 GB
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Java: 1.8.0_211 - /c/Program Files/Java/jdk1.8.0_211/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. yarn add react-native-paper
2. react-native run-android

## Expected Results
I don't want to see warnings about react native paper

**Comment by khaledBou** [comment]
System:
OS: macOS 10.15.5
CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
Memory: 49.22 MB / 24.00 GB
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 12.18.2 - /usr/local/opt/node@12/bin/node
Yarn: 1.22.4 - ~/.yarn/bin/yarn
npm: 6.14.5 - /usr/local/opt/node@12/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6626763
Xcode: /undefined - /usr/bin/xcodebuild
npmPackages:
react: 16.9.0 => 16.9.0
react-native: 0.61.5 => 0.61.5
npmGlobalPackages:
react-native: 0.61.5

"react-native-paper": "^3.10.1",

**Comment by shahul-tarams** [comment]
Yes me too facing the same issue, below are the versions:
"react-native": "0.63.2",
"react-native-paper": "^4.1.0",
"react-native-vector-icons": "^7.1.0",

**Comment by ezekel** [comment]
Yeah me too got warning...

Version RNP 4.2.0

**Comment by abhishektc** [comment]
Yes me too facing same issue.
I don't want to see warnings about react native paper, please help me

**Comment by abhishektc** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `react-native-vector-icons`
> * `yarn`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `npm` (found: `6.14.4`, latest: `6.14.8`)
> * `react-native` (found: `0.62.2`, latest: `0.63.2`)
> * `react-native-paper` (found: `3.9.0`, latest: `4.1.0`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Everything I'm using latest version, but still it's showing same warning

**Comment by usupsuparma** [comment]
i get same issue, but the issue #1897 is closed i don't know why is close.

**Comment by alexnaiman** [comment]
Hello! Can I try to tackle this issue for the Hacktoberfest2020? If so, can you assign it to me?

**Comment by chobits4** [comment]
#### solved my issue by next:
>- Wrap your root component in Provider from react-native-paper
```js
import * as React from 'react';
import { AppRegistry } from 'react-native';
import { Provider as PaperProvider } from 'react-native-paper';
import App from './src/App';

export default function Main() {
  return (
    <PaperProvider>
      <App />
    </PaperProvider>
  );
}

AppRegistry.registerComponent('main', () => Main);
```

**Comment by Hurdock** [comment]
Up any methods to fix it ?

**Comment by Angelk90** [comment]
@Trancever , @#satya164, @jaulz , @chobits4 , @khaledBou :

<img width="1439" alt="Schermata 2020-11-17 alle 18 26 44" src="https://user-images.githubusercontent.com/20476002/99425228-dd099c00-2902-11eb-8373-3a1617da3451.png">

**Comment by Angelk90** [comment]
@unikvozm : is there any news?

**Comment by unikvozm** [comment]
> @unikvozm : is there any news?

@Angelk90, need to wait for @Trancever approve.  It will merged soon

**Comment by hadihassan09** [comment]
Same Issue...

My Versions:
    "react-native": "0.63.4",
    "react-native-vector-icons": "^7.1.0",
    "react-native-paper": "^4.4.1",
    "npm" : 6.14.8

![image](https://user-images.githubusercontent.com/20710730/101294019-82f54b80-37c9-11eb-88b8-59efc128d610.png)

The weird thing is I didn't require any of the things mentioned in the warning, and react-native-paper was used in one file only and that file is imported in one file also.

**Comment by unikvozm** [comment]
The fixes are merged and will be available in the next release soon =)

**Comment by Angelk90** [comment]
Thx, @unikvozm can I ask you something about a component?

**Comment by unikvozm** [comment]
@Angelk90, yeah, would be happy to help (if I can 😊)

**Comment by Angelk90** [comment]
@unikvozm : Thank you, you are very kind.

One is a problem, it would be this: #2387

Another proposal would be this, I would like to know if you are interested: https://github.com/callstack/react-native-paper/issues/1254#issuecomment-738345650

Where I have noticed a possible problem inside `DataTablePagination.tsx`.

Reference link:
https://github.com/callstack/react-native-paper/issues/1254#issuecomment-738266619

**Comment by unikvozm** [comment]
@Angelk90, thanks for pointing out on the issues, we'll take look at all these (and other) issues and give our answers in those issues.
