### ISSUE TITLE
cannot convert undefined value to null

### ISSUE THREAD

**Issue by deepakverma4** [callstack/react-native-paper#2236]
### Current behaviour

random crash with textinput

### Screenshots (if applicable)

![WhatsApp Image 2020-09-17 at 12 30 58 PM](https://user-images.githubusercontent.com/31440793/93431364-aeab1880-f8e1-11ea-8d3c-7fec86b299a6.jpeg)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 10.0
| react-native          | 0.62.2
| react-native-paper    | ^3.10.1
| react-native-vector-icons   | ^6.6.0

**Comment by RichardLindhout** [comment]
Please reproduce your example with snack.expo.io. I can't fix your issue with no information
