### ISSUE TITLE
Cannot put a Card inside a DataTable: composable DataTable

### ISSUE THREAD

**Issue by Drecula** [callstack/react-native-paper#2241]
Putting a Card inside a DataTable Cell (either with DataTable.Cell or View) does not
constrain the Card, so it overflows the Cell.

A composable DataTable would be ideal.

I can manually make a Card-like UX, which I guess is the workaround

<img width="337" alt="DataTableOverflow" src="https://user-images.githubusercontent.com/6826347/93634526-c3111300-f9be-11ea-88ef-bace14a53973.png">

react-native 0.63.2
react-native-paper 4.1.0
react-native-vector-icons 7.0.0

**Comment by RichardLindhout** [comment]
I think it's better to create a custom layout for this. I don't think it's in the scope of react-native-paper and hard to add
