### ISSUE TITLE
How to style in List.Item

### ISSUE THREAD

**Issue by ezekel** [callstack/react-native-paper#2243]
How can I add style on my description. or how can I achieve like the image below the text color is grey in 3rd line 

react-native:  ""react-native@0.63.2"

react-native-paper:"react-native-paper@4.1.0"

react-native-vector-icons: react-native-vector-icons@7.1.0

```
                       <List.Item
                                title={item.id}
                                description={`${item.amount}\n${item.created_at}`}
                                left={props => <Icon {...props}  name="cc-paypal"  />}
                            />
```

I want to add color like this grey

![image](https://user-images.githubusercontent.com/6830057/93709356-4887f500-fb70-11ea-8ef6-ad50921c2bc9.png)

Thank you in advance.

**Comment by levieraf** [comment]
Try with: 

`descriptionStyle={{color: 'red'}}`

**Comment by levieraf** [comment]
There is a property with name descriptionStyle, try this:

```
<List.Item
                                title={item.id}
                               descriptionStyle={{color: 'red'}}
                                description={`${item.amount}\n${item.created_at}`}
                                left={props => <Icon {...props}  name="cc-paypal"  />}
                            />
```

**Comment by RichardLindhout** [comment]
In these cases it's probably better to copy and simplify the code from https://github.com/callstack/react-native-paper/blob/master/src/components/List/ListItem.tsx and change it in your own project with extra properties for this use case.
