### ISSUE TITLE
Modal is not showing correctly

### ISSUE THREAD

**Issue by yzobairi** [callstack/react-native-paper#2245]
### Current behaviour

When I use Modal, view of the modal is not showing correctly.
Modal view is showing under the Portal.

### Expected behaviour

Modal should appear on top of the current view thanks to the Portal.

### Code sample

I took your example without changing anything : [Snack](https://snack.expo.io/?name=Modal&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fmodal.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20Modal%2C%20Portal%2C%20Text%2C%20Button%2C%20Provider%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bvisible%2C%20setVisible%5D%20%3D%20React.useState(false)%3B%0A%0A%20%20const%20showModal%20%3D%20()%20%3D%3E%20setVisible(true)%3B%0A%0A%20%20const%20hideModal%20%3D%20()%20%3D%3E%20setVisible(false)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CProvider%3E%0A%20%20%20%20%20%20%3CPortal%3E%0A%20%20%20%20%20%20%20%20%3CModal%20visible%3D%7Bvisible%7D%20onDismiss%3D%7BhideModal%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%3CText%3EExample%20Modal%3C%2FText%3E%0A%20%20%20%20%20%20%20%20%3C%2FModal%3E%0A%20%20%20%20%20%20%20%20%3CButton%20style%3D%7B%7BmarginTop%3A%2030%7D%7D%20onPress%3D%7BshowModal%7D%3E%0A%20%20%20%20%20%20%20%20%20%20Show%0A%20%20%20%20%20%20%20%20%3C%2FButton%3E%0A%20%20%20%20%20%20%3C%2FPortal%3E%0A%20%20%20%20%3C%2FProvider%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper)

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/10465749/93743818-08b52200-fbf1-11ea-8392-ea6388989810.png)

### What have you tried

I've tried to move the Portal component, to use Portal.Host instead but it does not work.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 10
| react-native-paper    | 4.1.0
| node                  | 12.8.3
| npm or yarn           | 6.14.6
| expo sdk              | 38.0.2

**Comment by Lpaydat** [comment]
I faced the same issue, not only on the snack but also on my project as well.

Switch from `Modal` to `Dialog` as @unikvozm suggestion did the trick. ;)
