### ISSUE TITLE
Theme not working when generating release build  APK RNP 4.2.0

### ISSUE THREAD

**Issue by ezekel** [callstack/react-native-paper#2246]
Hi after issuing this command `npx react-native run-android --variant=release` 
and install the release apk to my real device the theme is not working

RN version : react-native@0.63.2

RNP version: react-native-paper@4.2.0

react-native-vector-icons:react-native-vector-icons@7.1.0
Header is black instead default color purplr
![image](https://user-images.githubusercontent.com/6830057/93750453-13da7300-fc2e-11ea-9b84-017d255924ae.png)

but in emulator it works

![image](https://user-images.githubusercontent.com/6830057/93750490-20f76200-fc2e-11ea-9d02-9eafc7a11fd7.png)

**Comment by ezekel** [comment]
> 
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `react-native-paper` (found: `4.1.0`, latest: `4.2.0`)
> 
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Hey I'm using yarn

**Comment by ezekel** [comment]
Not working in react-native-paper 
react-native-paper@4.2.0

**Comment by ezekel** [comment]
@satya164 , please help

**Comment by JonatanSalas** [comment]
It appears to be a trouble with the `babel.config.js`, I've removed the `react-native-paper/babel` from my `babel.config.js` and it seems to work properly.

**Comment by MohammedFaragallah** [comment]
same here
Default theme only after build

**Comment by actuallymentor** [comment]
I notice that a bunch of my theme doesn't work in production builds (fine in test builds).

Is it safe to just remove `react-native-paper/babel`? What does that plugin usually do?

**Comment by JonatanSalas** [comment]
I don't know if it is safe to remove it. I think that the plugin might remove unused components and perform other optimizations behind the scenes, but as workaround for now it works well.

**Comment by actuallymentor** [comment]
> I don't know if it is safe to remove it. I think that the plugin might remove unused components and perform other optimizations behind the scenes, but as workaround for now it works well.

I can confirm my apps do build and run, but it's a bit distressing that such a central plugin to the package is malfunctioning on production.

**Comment by lucascampelo** [comment]
I'm having a similar trouble using `expo` and `react-native-paper`. After build the cards of paper are rendering on dark theme even forcing a light theme on expo `app.json` and using `DefaultTheme` from react-native-paper. I can't reproduce this on development mode.

**Comment by Hirbod** [comment]
I have the same issue, I was getting crazy finding the issue. The Babel-Thing is a good workaround for now.

**Comment by Hirbod** [comment]
Still relevant, still unanswered

**Comment by lucascampelo** [comment]
Issue persist on `react-native-paper@^4.7.0`

**Comment by Hirbod** [comment]
@satya164 could you have a look at this?

**Comment by satya164** [comment]
Please don't ping me. There are other maintainers in this repo as well, and maintainers get notifications for every issue.

If you want more attention on an issue, you should join the discord and post there https://discord.gg/zwR2Cdh

**Comment by Hirbod** [comment]
Thanks, I'll leave a comment there

**Comment by lucascampelo** [comment]
> I have the same issue, I was getting crazy finding the issue. The Babel-Thing is a good workaround for now.

I've tried here, but still have the problem here. Can you explain the workaround ?

**Comment by projit-thetaonelab** [comment]
Same issue. Only work around is use,
 AppRegistry.registerComponent(appName, () => App);
as other paper components works fine without the theme.

**Comment by Hirbod** [comment]
Looks like this issue is still unresolved, right?

**Comment by kidculli** [comment]
> Looks like this issue is still unresolved, right? 

Yep I ran into it today and found this issue

**Comment by raajnadar** [comment]
is this happening with latest version?

**Comment by kidculli** [comment]
I tried with 4.9.2 I can try with the latest @raajnadar

**Comment by Bashin** [comment]
Still an issue with 4.12.4
Build only shows default theme with 'react-native-paper/babel' in the babel.config.js

**Comment by kaisoapbox** [comment]
This issue still exists with the latest version of `react-native-paper@5.10.0` @lukewalczak. As before, removing the babel plugin restores proper theming behaviour. 

My environment:

```
"react": "18.2.0",
"react-native": "0.72.3",
"react-native-paper": "5.10.0",
"react-native-vector-icons": "10.0.0",
```

**Comment by avtarvikas** [comment]
facing the same issue in the version 5.11.4

**Comment by RohovDmytro** [comment]
Still an issue.

"react-native-paper": "^5.13.1",
