### ISSUE TITLE
How do I pass navigation props to BottomNavigation

### ISSUE THREAD

**Issue by imsam67** [callstack/react-native-paper#2252]
In my React Native app, I use `react-navigation` version 5. 
I'm using:
`react` version 16.13.1
`react-native` version 0.63.2
`react-native-paper` version 4.1.0
`react-native-vector-icons` version 7.1.0

How do I pass the navigation object to the scenes in `BottomNavigation`?

Here's the component where I create the `BottomNavigation`:
```
import React from 'react';
import { BottomNavigation } from 'react-native-paper';

// Components
import CodeScanner from '../../../screens/vendors/CodeScannerScreen';
import Home from '../../../screens/home/HomeScreen';
import Vendors from '../vendors/VendorsStack';
   
// Routes
const homeRoute = () => <Home />;
const vendorsRoute = () => <Vendors />;
const scanRoute = () => <CodeScanner />;

const HomeTabs = (props) => {
   
   const [index, setIndex] = React.useState(0);
   
   const [routes] = React.useState([
      { key: 'home', title: 'Home', icon: 'newspaper-variant-multiple' },
      { key: 'vendors', title: 'Vendors', icon: 'storefront' },
      { key: 'codescanner', title: 'Scan', icon: 'qrcode-scan' }
   ]);
   
   const renderScene = BottomNavigation.SceneMap({
      home: homeRoute,
      vendors: vendorsRoute,
      codescanner: scanRoute
   });

   return (
      <BottomNavigation
         navigationState={{ index, routes }}
         onIndexChange={setIndex}
         renderScene={renderScene}
         labeled={false} />
   );
}

export default HomeTabs;
```

In this code, I do have the navigation in the `props` but haven't been able to figure out a way to pass navigation to the screens. Please also note that the vendor one is actually a stack navigator. In particular, that's where I need access to `navigation` so that I can open up other screens.

**Comment by sudhiryadav** [comment]
@imsam67  did you find the solution for the same. I am also looking for the same functionality.

**Comment by raajnadar** [comment]
Did you try this?

```
 <BottomNavigation
     {...props}
     navigationState={{ index, routes }}
     onIndexChange={setIndex}
     renderScene={renderScene}
     labeled={false}
/>
```

**Comment by sudhiryadav** [comment]
@raajnadar , No I haven't tried that but I did that using 
```import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';
```
The rest of the steps are exactly likewise any other tab navigator except that I had to add them in the NavigationContainer to make it theme-specific.

**Comment by imsam67** [comment]
@sudhiryadav Because at the root level I'm using `<NavigationContainer>`, navigation is available in children automatically. So, my tabs looks like below. Notice that I receive navigation into `myTabs` without passing it from parent. Simply because the `NavigationContainer` wraps the all the navigation elements, they have access to the `navigation` object.

```
const myTabs = ({ navigation }) => {
   return(
     <Tab.Navigator>
        <Tab.Screen />
        <Tab.Screen />
     </Tab.Navigator>
   );
};
```

**Comment by sudhiryadav** [comment]
@imsam67 yes this is the trick that I did. Instead of using the BottomNavigation from paper, I did it the same way.  Thank you.
