### ISSUE TITLE
Label miss-alignment issue after upgrading to latest Expo (39)

### ISSUE THREAD

**Issue by hamedmam** [callstack/react-native-paper#2254]
### Current behaviour

Label is not in the center of input field and after focus it is not placed in the middle of top line

### Expected behaviour

Having the the label in the center of input vertically and in the center of top line of input field

### Code sample

N/A

### Screenshots (if applicable)

![Screen Shot 2020-09-21 at 10 14 19 PM](https://user-images.githubusercontent.com/24867760/93838662-76486900-fc58-11ea-9c17-efe52d462eef.png)

### What have you tried

tried upgrading to version 4.2.0 and it is the same

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 
| react-native          | 
| react-native-paper    | 4.1.0 and 4.2.0
| node                  |
| npm or yarn           |
| expo sdk              | 39

**Comment by cj** [comment]
@hamedmam It is actually worse than that for react-native-web https://snack.expo.io/Hv98xiEmj (react-native-paper 4.2.0, react-native-web 0.13.13 and expo 39) the input text is completely hidden.  I have tracked the cause of it, it is to do with the changes in how the ref is handled via this commit https://github.com/necolas/react-native-web/commit/376ccc31b1b1a11de1cab6bd7df4385be1a6a28c by @necolas

**Comment by cj** [comment]
@hamedmam if you are using react-native-web 0.13.13 and expo 39 you can use the patch https://gist.github.com/cj/4d5e2494a0510b3185d38db936d2a297 with https://www.npmjs.com/package/patch-package as a quick fix for now.

**Comment by necolas** [comment]
File a bug

**Comment by cj** [comment]
@necolas opened one up https://github.com/necolas/react-native-web/issues/1749

**Comment by necolas** [comment]
I'll need a reduced test case as this package is a hassle to run on web due to its dependencies

**Comment by jaulz** [comment]
There is a similar issue with the banner in this line: 
https://github.com/callstack/react-native-paper/blob/efe17beafcc3bd83f4d84971499bd85647df9c84/src/components/Banner.tsx#L184

When `Animated.View` sets native props all unanimated styles are lost.

**Comment by himrocks33** [comment]
@jaulz is there going to be a patch soon?  This broke all of my banners across the entire app.

**Comment by necolas** [comment]
This problem should be fixed in react native for web 0.13.14. Ref memoization shouldn't change behavior but I don't yet understand why it did here. If you're running this lib on web you should know that there are several accessibility and performance issues with the implementation here though.

**Comment by himrocks33** [comment]
@necolas Yes, Thank you upgrading to 0.13.14 fixed my issue.  I'm aware of some of the issues running this lib on the web. I've been working around the issues as I find them.  Thank you.
