### ISSUE TITLE
fontFamily "MaterialCommunityIcons" is not a system font and has not been loaded through Font.loadAsync.

### ISSUE THREAD

**Issue by iman2420** [callstack/react-native-paper#2257]
`      fontFamily "MaterialCommunityIcons" is not a system font and has not been loaded through Font.loadAsync.
      
      - If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
      
      - If this is a custom font, be sure to load it with Font.loadAsync.
      
      Stack trace:
        node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
        node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
        node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
        node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
        node_modules\expo-font\build\Font.js:29:16 in processFontFamily
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3681:14 in diffProperties
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3553:37 in addNestedProperty
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3692:40 in diffProperties
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:4015:28 in createInstance
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:14706:39 in completeWork
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18123:27 in completeUnitOfWork
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18096:29 in performUnitOfWork
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18013:38 in workLoopSync
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17977:18 in renderRootSync
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17674:33 in performSyncWorkOnRoot
        [native code]:null in performSyncWorkOnRoot
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5321:31 in runWithPriority$argument_1
        node_modules\scheduler\cjs\scheduler.development.js:653:23 in unstable_runWithPriority
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5316:21 in flushSyncCallbackQueueImpl
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5304:28 in flushSyncCallbackQueue
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17125:30 in scheduleUpdateOnFiber
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:20527:14 in updateContainer
        node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:21068:17 in render
        node_modules\react-native\Libraries\ReactNative\renderApplication.js:54:4 in renderApplication
        node_modules\react-native\Libraries\ReactNative\AppRegistry.js:117:25 in runnables.appKey.run
        node_modules\react-native\Libraries\ReactNative\AppRegistry.js:202:4 in runApplication
        node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
        node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
        node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
        node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
        [native code]:null in callFunctionReturnFlushedQueue`

### src/App.js

    `     import React from 'react';
     import {AppRegistry, StyleSheet, View,} from 'react-native';
     import Home from './home'
     import PaperHome from './paperHome'
     import { configureFonts, DefaultTheme,DarkTheme, Provider as PaperProvider } from 'react-native-paper';
     import {expo as appName} from '../app.json';
     const fontConfig = {
         default: {
             regular: {
                 fontFamily: 'iran_sans_mobile_bold',
                 fontWeight: 'normal',
             },
             medium: {
                 fontFamily: 'iran_sans_mobile_bold',
                 fontWeight: 'normal',
             },
             light: {
                 fontFamily: 'iran_sans_mobile_bold',
                 fontWeight: 'normal',
             },
             thin: {
                 fontFamily: 'iran_sans_mobile_bold',
                 fontWeight: 'normal',
             },
         },
     };
     
     const theme = {
         ...DefaultTheme,
         //fonts: {},
         fonts: configureFonts(fontConfig),
     };
     class App extends React.Component {
         render() {
             return (
                 <PaperProvider theme={theme}>
                     <View style={styles.appContainer}>
                         <PaperHome/>
                     </View>
                 </PaperProvider>
             );
         }
     }
     
     const styles = StyleSheet.create({
         appContainer: {
             flex: 1,
             backgroundColor: 'red'
         },
     });
     
     AppRegistry.registerComponent(appName, () => App);
     
     export default App;`

### package.json

        `"dependencies": {
       "@react-native-community/masked-view": "0.1.10",
       "@testing-library/jest-dom": "^4.2.4",
       "@testing-library/react": "^9.3.2",
       "@testing-library/user-event": "^7.1.2",
       "expo": "^39.0.3",
       "react": "^16.13.1",
       "react-art": "^16.13.1",
       "react-devtools": "^4.8.2",
       "react-dom": "^16.13.1",
       "react-native": "^0.63.0-rc.1",
       "react-native-gesture-handler": "~1.7.0",
       "react-native-paper": "^4.1.0",
       "react-native-reanimated": "~1.13.0",
       "react-native-safe-area-context": "3.1.4",
       "react-native-screens": "~2.10.1",
       "react-native-status-bar-height": "^2.5.0",
       "react-native-vector-icons": "^7.1.0",
       "react-native-web": "^0.11.7",
       "react-navigation": "^4.4.0",
       "react-navigation-stack": "^2.8.2",
       "react-scripts": "3.4.3"
     },
     "devDependencies": {
       "babel-plugin-module-resolver": "^4.0.0",
       "babel-plugin-transform-object-rest-spread": "^6.26.0",
       "babel-plugin-transform-react-jsx-source": "^6.22.0",
       "babel-preset-expo": "^8.2.3"
     },`

- 
- react-native-cli: 2.0.1
- react-native: 0.63.2

so why in got this error on android emulator ?

**Comment by iman2420** [comment]
I try to change react-native-paper version from `4.1.0` to `4.2.0`. Then i run `rm -rf node_modules && yarn` command.

but issue still exists :
 `fontFamily "iran_sans_mobile_bold" is not a system font and has not been loaded through Font.loadAsync.`

**Comment by RichardLindhout** [comment]
If you use Expo you should not use react-native-vector-icons but @expo/vector-icons.
As for your fontFamily iran_sans_mobile_bold,  you should follow the doumentation from expo https://docs.expo.io/guides/using-custom-fonts/

**Comment by nonameolsson** [comment]
This is how I solved it https://github.com/callstack/react-native-paper/issues/2450#issuecomment-813066356
