### ISSUE TITLE
Text is selectable on the web inside buttons

### ISSUE THREAD

**Issue by RichardLindhout** [callstack/react-native-paper#2258]
I would like to make the text/icons non-selectable by default which is the case on iOS and Android but not on the web where the text is selectable by default. This will be the cause in the future too as I discussed with the maintainer of react-native-web, because text selecting is important on the web.

> That's right, you can disable text selection as needed. I think React Native gets text selection wrong by default and produces inaccessible experiences, especially on web.

https://github.com/necolas/react-native-web/issues/1741

### Current behaviour
![ezgif-7-623a8fe9c78c](https://user-images.githubusercontent.com/6492229/94059145-50e76680-fde2-11ea-82d9-8c01f65f6415.gif)

### Expected behaviour
That the text is non-selectable like on Android and iOS.

### What have you tried

https://github.com/oblador/react-native-vector-icons/pull/1252 > PR for icons non-selectable by default on the web

https://github.com/web-ridge/react-native-paper-dates/issues/19. I can send PR's but I think I better wait till the PR's from @unikvozm are merged?

**Comment by RichardLindhout** [comment]
@unikvozm do you know when your PR's will get merged? Or should I make PR's to existing components

**Comment by unikvozm** [comment]
> @unikvozm do you know when your PR's will get merged? Or should I make PR's to existing components

Merging my PRs is still in progress... I think you can create your branch from my branch and in your PR  mention that “should be merged after ...”

**Comment by RichardLindhout** [comment]
Looks like this is almost fixed, I think not all the changes from the PR are merged since the Icon inside a button is still selectable
