### ISSUE TITLE
Selecting a Radio Button takes really long

### ISSUE THREAD

**Issue by rusagent** [callstack/react-native-paper#2264]
I uploaded my project to github at https://github.com/rusagent/testmepls . It's a copy of https://github.com/Trancever/twitterClone/
and the issua is already in there. 
So when selecting a theme in the Preferences Screen from the drawer it takes really long to change that. Can someone here please explain to me why that is and how i can fix that? 
Kind Regards,
rusagent

**Comment by rusagent** [comment]
"react-native": "0.63.3"
    "react-native-paper": "^4.2.0"
    "react-native-vector-icons": "^7.1.0"

**Comment by rusagent** [comment]
Here is the Stackoverflow post: https://stackoverflow.com/questions/64162512/react-native-paper-radio-button-takes-a-long-time-to-change

**Comment by codecog** [comment]
I'm going to suspect this is not a problem with the component but a problem with your state and what is rerendering once you try to change the state after press. Your efforts are likely better focused there.

**Comment by rusagent** [comment]
Do you maybe know how to solve that?

**Comment by davwheat** [comment]
The change event seems to fire a bit later than it feels like it should, making the state update later, making the entire redraw to reflect the new chosen value take too long.

I have no clue where the "delay" starts, or if it's just Android being Android.
