### ISSUE TITLE
Font.tsx Unexpected Token (2:12) 

### ISSUE THREAD

**Issue by topher17091** [callstack/react-native-paper#2266]
I have an issue on the node_modules/react-native-paper/src/styles/fonts.tsx 

There was an unexpected token (2:12) 

I did not edit anything after I install the package. 

react-native : v0.59.9
react-native-vector-icons : v6.7.0
react-native-paper: v4.2.0

**Comment by tehtea** [comment]
I had a similar problem. It was fixed by updating `babel-runtime` and `babel-core`. See the whole context to it here: https://github.com/callstack/react-native-paper/issues/2261
