### ISSUE TITLE
Support for downward vertical orientation in FABs

### ISSUE THREAD

**Issue by pushingit** [callstack/react-native-paper#2268]
Would like to be able to use FABs at the top of the screen and have them expand downward (in things like nav headers) rather be forced to only use them further down the screen as they only expand upward - a prop like "verticalOrientation" with values "up" or "down" in react-native-action-button.

react-native=0.63.2
react-native-paper=3.11.0
react-native-vector-icons=7.1.0

**Comment by RichardLindhout** [comment]
Is this specified in the Material Design specification?
