### ISSUE TITLE
BottomNavigation not animating top correctly- stuck at FAR_FAR_AWAY

### ISSUE THREAD

**Issue by no12345678** [callstack/react-native-paper#2270]
### Current behaviour

I copied the example of BottomNavigation from the docs, all working. instead of rendering the 3 dummy components in the example, i changed 1 of them to be my component.
The first tab is loaded and displayed as it should, but when i change tab i see nothing (content is still at top: 9999px, FAR_FAR_AWAY value). it seems i have to visit each tab and only then when i will try to go back to one of those tabs it will now work as it should have.

### Expected behaviour
on tab change, opacity changes from 0 to 1 as it should, but top is stuck at 9999px and not animating to 0px

### Code sample
import React, { useEffect } from "react";
import { Text, View } from "react-native";
import Main from "./Main";
import { BottomNavigation } from "react-native-paper";

const MusicRoute = () => < Main />;

const AlbumsRoute = () => < Text >Albums</ Text >;

const RecentsRoute = () => < Text >Recents</ Text >;

export default function BottomNavigator() {
  const [index, setIndex] = React.useState(0);
  const [routes] = React.useState([
    { key: 'music', title: 'Music', icon: 'queue-music' },
    { key: 'albums', title: 'Albums', icon: 'album' },
    { key: 'recents', title: 'Recents', icon: 'history' },
  ]);

  const renderScene = BottomNavigation.SceneMap({
    music: MusicRoute,
    albums: AlbumsRoute,
    recents: RecentsRoute,
  });
    console.log(index)
  return (
    <BottomNavigation
      navigationState={{ index, routes }}
      onIndexChange={setIndex}
      renderScene={renderScene}
    />
  );
}
### What have you tried

i've tried overriding the top value but i cant seem to get to that css class or override it from the child.
tried looking into the bottom navigation implementation on git and see the code and figure out why wouldn't it change the top value, but had no luck.

### Your Environment
    "react-native": "^0.63.3",
    "react-native-paper": "^4.2.0",
    "npm": "6.14.8",
    "expo: "39.0.3",
    "react-native-vector-icons": "^7.1.0",

**Comment by no12345678** [comment]
after updating everything as suggested, the issue is still there..

**Comment by no12345678** [comment]
It seems to happen when the component displayed has an < Image /> element...

**Comment by jasperro** [comment]
@no12345678, do you think this pull request sufficiently fixes this? Do you happen know if this workaround impacts performance?

**Comment by no12345678** [comment]
> @no12345678, do you think this pull request sufficiently fixes this? Do you happen know if this workaround impacts performance?

hey, how can i check it? do i need to npm install to the latest version? i read what you said and it sounds like you got it right because that was exactly the issue. Thank you :)

**Comment by jasperro** [comment]
@no12345678 `git clone https://github.com/jasperro/react-native-paper/`, in the downloaded directory type `npx @react-native-community/bob`, go to your project directory and type `npm install /downloadpath/react-native-paper`
