### ISSUE TITLE
menu overlap with view(custom component)

### ISSUE THREAD

**Issue by govind1530** [callstack/react-native-paper#2274]
in both platform menu overlap with custom component / View

it should be not overlap

`<Appbar.Action icon="dots-vertical" onPress={openMenu} />
          <Provider>
            <View
              style={{
                //paddingTop: 50,
                flexDirection: 'row',
                justifyContent: 'center',
               // zIndex: 1,
              }}>
              <Menu
                visible={visible}
                onDismiss={closeMenu}
                anchor={
                  { x: width, y: 50 }
              }
              overlayAccessibilityLabel={'Close menu'}
                >
                <Menu.Item onPress={() => {}} title="Call lab" />
                <Menu.Item onPress={() => {}} title="Deny" />
              </Menu>
            </View>
          </Provider>`

![MicrosoftTeams-image](https://user-images.githubusercontent.com/33393692/95298533-d4e92600-0899-11eb-9333-fdda6a74d91e.png)

### Your Environment
react-native-cli: 2.0.1
react-native: 0.63.2
npm  6.14.5
react-native-paper": "^4.1.0"
react-native-vector-icons": "^7.1.0
android 7

**Comment by govind1530** [comment]
yes its still exit

**Comment by medmo7** [comment]
Same issue on iOS. Did you find a solution for it?
