### ISSUE TITLE
TextInput/Field flickering while rendering multiple times

### ISSUE THREAD

**Issue by traingethermarc** [callstack/react-native-paper#2282]
Hi there!
I have a Panel sliding in from the bottom which is rendered twice. Unfortunately the TextInput (outlined) from React-native-paper is flickering. The placeholder text is flickering up and down (like a buggy glitch effect)  (but now every time). I tried so many different approaches to this "bug" - still not working. Any ideas?  Thanks so much!

Your Environment
react-native: 0.63.3
react-native-paper: 4.2.0
react-native-vector-icons: 7.1.0 
- yes still with the latest versions

**Comment by traingethermarc** [comment]
yes

**Comment by RichardLindhout** [comment]
Can you make a reproduction on snack.expo.io? Or is it using native modules?

Maybe https://github.com/gorhom/react-native-bottom-sheet could work out great if the bottomsheet is the reason why it flickers.

**Comment by Return-1** [comment]
This is also an issue when quickly rendering a TextInput.
If you render any TextInput with a label on an already existing screen ( i.e not using react-navigation ) you can see this at any point

**Comment by raphaelmsr** [comment]
Still present ...

**Comment by AnthonyCerdasAnalisis** [comment]
any solution?

**Comment by abdullahmehboob20s** [comment]
any solution?

**Comment by markendy** [comment]
Progress never stands still, so perhaps the new solution described in this question will help you! https://stackoverflow.com/questions/79253174
