### ISSUE TITLE
Custom button style

### ISSUE THREAD

**Issue by ravi-poonia** [callstack/react-native-paper#2284]
Hi, 
I have to style button like the attached image. I'm not sure if it's a strict material design but I have seen this in some places.
Is it possible to get the same result with theme? Or is there some example you can share?
![Screen Shot 2020-10-11 at 1 08 40 AM](https://user-images.githubusercontent.com/61002302/95663643-9afc7600-0b5e-11eb-8af1-458a7c387392.png)

Your Environment
react-native: 0.63.3
react-native-paper: 4.2.0
react-native-vector-icons: 7.1.0

**Comment by RichardLindhout** [comment]
It's better to create a custom button component for this with the TouchableRipple provided by React Native Paper. This is not possible with the default Button

**Comment by ravi-poonia** [comment]
Yeah, I figured that out eventually. Thx. I just created my own button.

**Comment by RichardLindhout** [comment]
Great!

When creating custom buttons don't forget to include (some of the) accessibility props to the TouchableRipple. I forgot them a lot in the past on buttons :)

An example can be found here:
```
        accessibilityLabel={accessibilityLabel}
        accessibilityTraits={disabled ? ['button', 'disabled'] : 'button'}
        accessibilityComponentType="button"
        accessibilityRole="button"
        accessibilityState={{ disabled }}
```

https://github.com/callstack/react-native-paper/blob/master/src/components/Button.tsx#L262
