### ISSUE TITLE
RCTSwitch was not found in UIManager

### ISSUE THREAD

**Issue by Svarto** [callstack/react-native-paper#2285]
### Current behaviour

I try to navigate to a screen with the Switch component, and the app crashes on both production and development throwing a Component Exception error.

![Screenshot from 2020-10-11 20-21-15](https://user-images.githubusercontent.com/24279217/95686654-b57e3000-0bee-11eb-9953-956384b6b6a4.png)

### Expected behaviour

I expected the Switch component to be properly rendered.

```
Invariant Violation: requireNativeComponent: "RCTSwitch" was not found in the UIManager.
- node_modules/react-native/Libraries/LogBox/LogBox.js:148:8 in registerError
- node_modules/react-native/Libraries/LogBox/LogBox.js:59:8 in errorImpl
- node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
- node_modules/expo/build/environment/react-native-logs.fx.js:27:4 in error
- node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
- node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
- node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
- node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:9:32 in ErrorUtils.setGlobalHandler$argument_0
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:293:29 in invoke
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:154:27 in invoke
- node_modules/regenerator-runtime/runtime.js:164:18 in PromiseImpl.resolve.then$argument_0
- node_modules/react-native/node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
- node_modules/react-native/node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:14 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:30 in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
```

### What have you tried

I tried to run expo upgrade to install all the compatible libraries for SDK39, I have now commented out the switch to keep the app to work.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.63.3
| react-native-paper    | 4.2.0
| node                  | v10.19.0
| npm           | 6.14.8
| expo             |  39.0.3
| react-native-vector-icons | 7.1.0

**Comment by Svarto** [comment]
any ideas on this one? Still have this issue

**Comment by Svarto** [comment]
For people coming after me, this was due to me mistyping an instance of using Platform.OS as Platform.OS = "ios". Changing it to === fixed the issue.

**Comment by ramvilla997** [comment]
> For people coming after me, this was due to me mistyping an instance of using Platform.OS as Platform.OS = "ios". Changing it to === fixed the issue.

worked nicely
