### ISSUE TITLE
SyntaxError: node_modules/react-native-paper/src/styles/DefaultTheme.tsx: Unexpected token

### ISSUE THREAD

**Issue by RahulLadybirdweb** [callstack/react-native-paper#2286]
I am using react native 0.59.9 and upgrade my react native paper to 4.0.0 but It has problem :
bundling failed: SyntaxError: node_modules/react-native-paper/src/styles/DefaultTheme.tsx: Unexpected token

2 | import { black, white, pinkA400 } from './colors';
3 | import configureFonts from './fonts';

4 | import type { Theme } from '../types';
| ^
5 |
6 | const DefaultTheme: Theme = {
7 | dark: false,
at Object.raise (node_modules/@babel/parser/lib/index.js:6930:17)
 "react-native": "0.59.9",
"react-native-paper": "^4.0.0",
 "react-native-vector-icons": "^6.6.0",

**Comment by RahulLadybirdweb** [comment]
"react-native": "0.59.9",
"react-native-paper": "^4.0.0",
"react-native-vector-icons": "^6.6.0",

**Comment by tribou** [comment]
Hi @RahulLadybirdweb, what steps did you take that fixed this issue?

**Comment by arnaldoquagliatoEst** [comment]
I saw a feel people updating babel but dosen´t work for me.

**Comment by Kewal89** [comment]
> 
> 
> I saw a feel people updating babel but dosen´t work for me.

For me the issue was with ```react-native start``` command. I tried ```yarn start``` instead since i was using yarn package manager instead of npm.

**Comment by cullsin** [comment]
![image](https://user-images.githubusercontent.com/5137598/115863571-46ae4900-a453-11eb-9980-94c6fa664a08.png)

**Comment by cullsin** [comment]
the issue persists. it works fine on the web, but the problem in android. Can you please suggest. i am using expo environment.
