### ISSUE TITLE
Appbar.Header causes an offset of components when used with BottomTabNavigator

### ISSUE THREAD

**Issue by ixez** [callstack/react-native-paper#2287]
### Current behaviour
When using BottomTabNavigator of react-navigation, putting a Appbar.Header inside the screen will cause other components to shift down and be behind the bottom tab bar. Like the screenshots below, use a Appbar.Header will make some items (number 37-39) invisible behind the tab bar. This problem will disappear when there is no Appbar.Header and change to other header implementation such as native-base.

![Screenshot_1602748670](https://user-images.githubusercontent.com/1274945/96098787-3f473980-0f1e-11eb-8a28-ec2171bdd677.png)
![Screenshot_1602748657](https://user-images.githubusercontent.com/1274945/96098792-40786680-0f1e-11eb-8a9a-9b5f28e8a6aa.png)

### Code sample
A minimal code sample is given for reproduction.
```javascript
data = []
for (i=0; i<40; i++) {
    data.push(i);
}

Screen = () => (
    <View>
        <Appbar.Header>
            <Appbar.Content title="Title" subtitle="Subtitle" />
        </Appbar.Header>
        <FlatList
            data={data}
            renderItem={({item}) => (
                <Text>{item}</Text>
            )}
            keyExtractor={(item, index) => index.toString()}
        />
    </View>
)

const Tab = createBottomTabNavigator();
const App: () => React$Node = () => {
    return (
        <NavigationContainer>
            <Tab.Navigator screenOptions={{ headerShown: true }}>
                <Tab.Screen 
                    name="Screen" 
                    component={Screen} 
                />
            </Tab.Navigator>
        </NavigationContainer>
    );
}
```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.63.3
| react-native-paper    |  4.2.0

**Comment by RichardLindhout** [comment]
Does this solve the problem?

```
Screen = () => (
    <View style={{flex:1}}>
        <Appbar.Header>
            <Appbar.Content title="Title" subtitle="Subtitle" />
        </Appbar.Header>
        <FlatList
            style={{flex:1}}
            data={data}
            renderItem={({item}) => (
                <Text>{item}</Text>
            )}
            keyExtractor={(item, index) => index.toString()}
        />
    </View>
)
```

**Comment by ixez** [comment]
> Does this solve the problem?
> 
> ```
> Screen = () => (
>     <View style={{flex:1}}>
>         <Appbar.Header>
>             <Appbar.Content title="Title" subtitle="Subtitle" />
>         </Appbar.Header>
>         <FlatList
>             style={{flex:1}}
>             data={data}
>             renderItem={({item}) => (
>                 <Text>{item}</Text>
>             )}
>             keyExtractor={(item, index) => index.toString()}
>         />
>     </View>
> )
> ```

It works. Oh, it seems a stupid problem, just wrapping.
Thank you very much!

**Comment by RichardLindhout** [comment]
Yes it's a strange issue! I'm happy it did work out 👍
