### ISSUE TITLE
React native Unexpected token, expected ";"

### ISSUE THREAD

**Issue by gron01** [callstack/react-native-paper#2295]
React native Unexpected token, expected ";" error problem

The versions I use :
"react-native": "0.63.2",
"react-native-paper": "4.0.1",
"react-native-vector-icons": "7.0.0",

**Comment by wililam444** [comment]
Hello friends today I got this problem after I deleted my node_modules and installed it again.
![React native](https://user-images.githubusercontent.com/46619747/96295257-4477b780-0ff6-11eb-8f2d-c6f4fa59b6b3.PNG)
The versions I use :
    "react-native": "0.63.2",
    "react-native-paper": "4.0.1",
    "react-native-vector-icons": "7.0.0",

**Comment by wililam444** [comment]
The methods I tried.

- Delete and reinstall node_modules.
- ./gradlew clean

**Comment by SirKadogan** [comment]
I'm getting the same on expo, brand new project.

"expo": "~39.0.2"
"react": "16.13.1"
"react-native-paper": "^4.2.0"

**Comment by wililam444** [comment]
> I'm getting the same on expo, brand new project.
> 
> "expo": "~39.0.2"
> "react": "16.13.1"
> "react-native-paper": "^4.2.0"

Version update is not be useful

**Comment by wililam444** [comment]
I updated latest version
And Error: 
![React native paper](https://user-images.githubusercontent.com/46619747/96325212-b3710280-102e-11eb-9713-4f6b26d4871c.PNG)

**Comment by pscarey** [comment]
I resolved locally by setting:

```
  "react-native": "lib/module/index.js",
```

in the `package.json` of `react-native-paper` - it appears the default value is redirecting to the Typescript source files.
