### ISSUE TITLE
Dialog backdrop not fill all screen

### ISSUE THREAD

**Issue by LorhanSohaky** [callstack/react-native-paper#2298]
I'm using this package with Expo on web, and was experiencing several difficulties with the `Dialog` component. In some screens the Dialog was not fill all screen. Like the GIF below.
![dialog-error](https://user-images.githubusercontent.com/16273730/96533759-d1c04380-1264-11eb-9c66-8097b039aee4.gif)

### Screenshots

![dialog-error](https://user-images.githubusercontent.com/16273730/96533759-d1c04380-1264-11eb-9c66-8097b039aee4.gif)

### What have you tried

So, inspecting all element I found a `View` between the `Portal` and `Provider`

![image](https://user-images.githubusercontent.com/16273730/96533962-3e3b4280-1265-11eb-9cb3-92dbc3a8ae50.png)

Modifying this `View` with `overflow:'scroll' the `Dialog` works "properly"

![dialog-sug](https://user-images.githubusercontent.com/16273730/96535180-a4c16000-1267-11eb-88b3-6f329b2d4dff.gif)

So I tried changes style of `View` adding `overflow: 'scroll'`, but this remove scroll of all screen also.

[Here my changes](https://github.com/callstack/react-native-paper/issues/1445)

My suggestion is somehow this more external portal to know when a Dialog is opened

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | web
| react-native          |0.62.0
| react-native-paper    |3.8.0
| node                  |12
| npm           | 6.14.6
| expo sdk              | 37

**Comment by LorhanSohaky** [comment]
Any news?

**Comment by milvoj** [comment]
I know this issue has been open for a while. If you're using React Navigation, you can try adding `cardstyle: {flex: 1}` to the `screenOptions` of your stack navigator:

```
const LoginStack = createStackNavigator();

const LoginNavigator = () => (
  <LoginStack.Navigator
    initialRouteName={PAGES.LoginPage}
    screenOptions={{cardStyle: {flex: 1}}}>
    <LoginStack.Screen
    ...
```

**Comment by lukewalczak** [comment]
Are u able to provide the repro in form of expo snack or sample repo?
