### ISSUE TITLE
Icon component to button

### ISSUE THREAD

**Issue by newfylox** [callstack/react-native-paper#2308]
react-native 0.63.2
react-native-paper 4.2.0
Icon from react-native-elements 2.3.2 or from @expo/vector-icons 10.2.1 (so react-native-vector-icons behind the scenes)

Hi, great library by the way.

Is there a way to pass an Icon component to a button instead of only passing the name string of the icon? It would be great because we would be able to choose our own Icon and also styling it (bigger, smaller, etc.)

Thanks!

**Comment by OlimpiaZurek** [comment]
you can pass Icon component to a button like this: 

`  <Button
        icon={() => <IconComponent />}
        mode="contained"
        onPress={() => console.log('Pressed')}
      >
        Press me
      </Button>`
