### ISSUE TITLE
style width menu

### ISSUE THREAD

**Issue by temuccio** [callstack/react-native-paper#2314]
- react-native: 0.63.3
- react-native-paper: 4.2.0
- react-native-vector-icons: 7.1.0

I have a menu with a anchor to a button.
I would like to style width of menu such as button.
I have try with style=width:100% but doesn't works. If I change the dimension in pixel, it change.
How I can style with flex mode (for dynamic width).
This is an example: https://snack.expo.io/@temuccio/menu

**Comment by rajprakash00** [comment]
@temuccio I dont know if you have solved the issue or not but this is a little hack you can do as of now [Snack](https://snack.expo.io/L_9vAMdXM).

**Comment by temuccio** [comment]
Thanks, 
this resolve my problem.
With this option I can make a component such as a select.

**Comment by GautamiDhokte** [comment]
above solution didn't worked for me..
as even if the width of Menu.Item becomes 100% ,some part of Menu.Item at right becomes not clickable
In case anyone is facing same issue just replace Menu.Item with List.Item [Snack](https://snack.expo.io/@gautami123/menu)
