### ISSUE TITLE
Appbar.Action custom Icon rotates on rerender

### ISSUE THREAD

**Issue by leighquince** [callstack/react-native-paper#2315]
### Current behaviour

When the `Appbar.Action` re-renders and is being passed a custom `icon` it adds a small 90-degree rotation on rerendering.

### Expected behaviour

I expect the image to remain still like it does if I pass a string icon name for it to use.

### Code sample

https://snack.expo.io/@domosafety/mature-apples

### What have you tried

Identified the issue by removing the use of `Appbar.Action` and using a plane `View` and the issue is not present. I have also used a named icon in place of a custom icon and again the issue does not appear.

This issue also only presents its self in `react-native-paper` version >= `3.11.0 `

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 10
| react-native          | 0.63.3
| react-native-paper    | 4.2.0
| node                  |  v12.2.0
| npm           | 6.14.8
| expo              | 39.0.0 (but that's just in the snack, I don't use expo on my actual project)
| react-native-vector-icons | 7.1.0

**Comment by leighquince** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `expo` (found: `39.0.0`, latest: `39.0.3`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

the snack only lets me use expo 39.0.0 as latest but seeing as the same issue happens on a normal react=native project and expo project i don't think it will make a difference

**Comment by leighquince** [comment]
This issue is still present in the latest release `4.3.0`

**Comment by JaeWangL** [comment]
I have same issue

**Comment by RichardLindhout** [comment]
It's because it's a new component for react-native-paper you can fix this if you keep the same reference to the component instead of returning a new renderer every render.
https://snack.expo.io/eww_Kulak
```
const appbarIcon = ({ size }) => {
  return <Text>HI</Text>; //just an example but doesn't matter waht you put here, real icon or anything it will rotate
}
<Appbar.Action
          onPress={this.props.backAction}
          icon={appbarIcon}
        />
```

**Comment by tibbe** [comment]
This still happens in 5.11.4. The workaround works but it seems that this should be made to work by default or otherwise everyone who uses a custom icon needs a workaround.

**Comment by leonardoinhoqui** [comment]
Version 5.12.5 still happening with custom icons

I used the tip from my colleague above animate= {false}

This is ridiculous for over 3 years and they haven't fixed it.
