### ISSUE TITLE
HelperText consumes space when invisible

### ISSUE THREAD

**Issue by mbpictures** [callstack/react-native-paper#2316]
### Current behaviour
When using the HelperText component and it's not visible, space is consumed nevertheless. That looks weird, especially when using multiple HelperTexts. The text box doesn't indicate the error status (in the docs, the text box become red as well)

### Expected behaviour
HelperText doesn't consume space when it's not visible. TextBox becomes red when the input is not valid.

### Code sample
```
<TextInput onChangeText={this.handleAddTextChange} value={this.state.addText} label="Name" mode="outlined" />
<HelperText type="error" visible={!this.addNameIsUnique()}>
    A list with this name does already exist!
</HelperText>
<HelperText type="error" visible={!this.addNameIsEmpty()}>
    The name can not be empty!
</HelperText>
```

### What have you tried
I followed the docu and tried the official example

### Your Environment

| software              | version
| --------------------- | -------
| android        | 10
| react-native          | 39.0.3
| react-native-paper    | 4.2.0
| node                  | 10.15.0
| npm          | 6.10.2
| expo sdk              | v39.0.2

[snack](https://snack.expo.io/?name=HelperText&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fhelper-text.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20View%20%7D%20from%20%27react-native%27%3B%0Aimport%20%7B%20HelperText%2C%20TextInput%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Btext%2C%20setText%5D%20%3D%20React.useState(%27%27)%3B%0A%0A%20%20%20const%20onChangeText%20%3D%20text%20%3D%3E%20setText(text)%3B%0A%0A%20%20const%20hasErrors%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20return%20!text.includes(%27%40%27)%3B%0A%20%20%7D%3B%0A%0A%20return%20(%0A%20%20%20%20%3CView%3E%0A%20%20%20%20%20%20%3CTextInput%20label%3D%22Email%22%20value%3D%7Btext%7D%20onChangeText%3D%7BonChangeText%7D%20%2F%3E%0A%20%20%20%20%20%20%3CHelperText%20type%3D%22error%22%20visible%3D%7BhasErrors()%7D%3E%0A%20%20%20%20%20%20%20%20Email%20address%20is%20invalid!%0A%20%20%20%20%20%20%3C%2FHelperText%3E%0A%20%20%20%20%3C%2FView%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper)

**Comment by OlimpiaZurek** [comment]
If you want to hide that space, you can use a conditional expression eg.
` {!this.addNameIsUnique() && (
          <HelperText type="error" visible={!this.addNameIsUnique()}>
            A list with this name does already exist!
          </HelperText>
        )}`

**Comment by Yugue** [comment]
Hi, this issue still occurs. I posted a SO : [here](https://stackoverflow.com/questions/68153446/react-native-paper-helpertext-consumes-space-when-invisible)

**Comment by VariabileAleatoria** [comment]
> If you want to hide that space, you can use a conditional expression eg. ` {!this.addNameIsUnique() && ( <HelperText type="error" visible={!this.addNameIsUnique()}> A list with this name does already exist! </HelperText> )}`

this will break the only useful thing of this component, the animation.
