### ISSUE TITLE
support icon style for Button component

### ISSUE THREAD

**Issue by yichengq** [callstack/react-native-paper#2318]
**Is your feature request related to a problem? Please describe.**
We need a button with icon as 1 color, while label/text as another color.
![image](https://user-images.githubusercontent.com/2976232/97095633-d430ed80-1616-11eb-9961-a7f5e9128a04.png)

**Describe the solution you'd like**
support iconStyle as button props
Material design also allows icon style: https://material.io/develop/android/components/buttons#icon-attributes

**Describe alternatives you've considered**
N/A

**Additional context**
react-native: 0.63.3
react-native-paper: 4.2.0
react-native-vector-icons: 7.1.0

**Comment by OlimpiaZurek** [comment]
You can try this: 
`    <Button
            icon={() => (
              <Icon source="wechat" style={{ color: 'green' }} size={24} />
            )}
            onPress={() => {}}
            style={styles.button}
          >
            Icon
          </Button>`

**Comment by yichengq** [comment]
Thanks for the answer! It works awesome!
