### ISSUE TITLE
Error: Unable to resolve module `./components/TouchableRipple` from `node_modules\react-native-paper\src\index.tsx`:

### ISSUE THREAD

**Issue by feliperoan** [callstack/react-native-paper#2321]
### Current behaviour

Hello, 
 when I run, after compiling before starting I get that error
I have tried installing modules returning versions but it does not disappear
"react-native-paper": "^4.0.1",
"react-native-safe-area-context": "^3.1.4",
"react-native-screens": "^2.10.1", "react-native-reanimated": "^1.13.0",
"@react-native-community/masked-view": "^0.1.10",

error: Error: Unable to resolve module ./components/TouchableRipplefromnode_modules\react-native-paper\src\index.tsx`:

None of these files exist:

node_modules\react-native-paper\src\components\TouchableRipple(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
node_modules\react-native-paper\src\components\TouchableRipple\index(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
at ModuleResolver.resolveDependency`
### Code sample
complete log
error: Error: Unable to resolve module ./components/TouchableRipplefromnode_modules\react-native-paper\src\index.tsx`:

None of these files exist:

node_modules\react-native-paper\src\components\TouchableRipple(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
node_modules\react-native-paper\src\components\TouchableRipple\index(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
at ModuleResolver.resolveDependency (C:\Developement\reactnativeapp\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
at ResolutionRequest.resolveDependency (C:\Developement\reactnativeapp\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
at DependencyGraph.resolveDependency (C:\Developement\reactnativeapp\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
at Object.resolve (C:\Developement\reactnativeapp\node_modules\metro\src\lib\transformHelpers.js:267:42)
at C:\Developement\reactnativeapp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
at Array.map ()
at resolveDependencies (C:\Developement\reactnativeapp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
at C:\Developement\reactnativeapp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
at Generator.next ()
at asyncGeneratorStep (C:\Developement\reactnativeapp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)`

### What have you tried
I have tried installing modules returning versions but it does not disappear
I also tried giving it npm update and installing it newer but still 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          |0.63.3
| react-native-paper    |4.2.0
| node                  |v12.18.3
| npm           |6.14.8
| expo              |  39.0.3  
| react-native-vector-icons              | 7.1.0

idont use expo

**Comment by feliperoan** [comment]
I already tried with the latest version npm update and I still have the same error

**Comment by Abhishek9717t** [comment]
try using react-native-paper@3.6.0
It worked for me

**Comment by radu-m** [comment]
I'm using
 `
"react-native-paper": "^4.2.0",
`
here's the relevant bit from npm logs:

> 56576 verbose lifecycle react-native-paper@4.2.0~prepare: CWD: /home/radium/dev/misc/react-native-paper
> 56577 silly lifecycle react-native-paper@4.2.0~prepare: Args: [ '-c', 'bob build && node ./scripts/generate-mappings.js' ]
> 56578 silly lifecycle react-native-paper@4.2.0~prepare: Returned: code: 1  signal: null
> 56579 info lifecycle react-native-paper@4.2.0~prepare: Failed to exec prepare script
> 56580 verbose stack Error: react-native-paper@4.2.0 prepare: `bob build && node ./scripts/generate-mappings.js`
> 56580 verbose stack Exit status 1
> 56580 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 56580 verbose stack     at EventEmitter.emit (events.js:198:13)
> 56580 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 56580 verbose stack     at ChildProcess.emit (events.js:198:13)
> 56580 verbose stack     at maybeClose (internal/child_process.js:982:16)
> 56580 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 56581 verbose pkgid react-native-paper@4.2.0
> 56582 verbose cwd /home/radium/dev/misc/react-native-paper
> 56583 verbose Linux 5.4.0-52-generic
> 56584 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "i"
> 56585 verbose node v10.19.0
> 56586 verbose npm  v6.14.8
> 56587 error code ELIFECYCLE
> 56588 error errno 1
> 56589 error react-native-paper@4.2.0 prepare: `bob build && node ./scripts/generate-mappings.js`
> 56589 error Exit status 1
> 56590 error Failed at the react-native-paper@4.2.0 prepare script.
> 56590 error This is probably not a problem with npm. There is likely additional logging output above.
> 56591 verbose exit [ 1, true ]
>
