### ISSUE TITLE
Material Tab Navigator not compatible with iPhone 12

### ISSUE THREAD

**Issue by comvenger-brandon** [callstack/react-native-paper#2323]
The dependency react-native-safe-area-view should be changed to "^2.0.0", which supports the iPhone 12 series.

At the moment, the safe area does not work properly on iPhone 12.

**Comment by mark9white** [comment]
I can see this issue with:

react-native: 0.63.3
react-native-paper: 4.2.0
react-native-vector-icons: 7.0.0

**Comment by Hirbod** [comment]
I can confirm this. The fix was to:

```
expo install react-native-safe-area-view@next react-native-safe-area-context@next
```

And add this to your package.json (below devDependencies on root level)

```
  "resolutions": {
    "react-native-safe-area-view": "^2.0.0"
  },
```

**Comment by LRNZ09** [comment]
I still have this issue with react-native-paper version `4.3.1`

**Comment by Hirbod** [comment]
@LRNZ09 just pick the workaround I've posted. Works flawlessly

**Comment by LRNZ09** [comment]
@Hirbod your workaround works, but I'd like the @callstack team to take care of this bug

**Comment by mars-lan** [comment]
@Trancever any chance we can get this fixed soon?

**Comment by HughBerriez** [comment]
sadly tried this but to no avail. Here's where a few of us are still having issues https://github.com/react-navigation/react-navigation/issues/9110#issuecomment-742642540
