### ISSUE TITLE
Contained Button onPress crashes on react-native-windows

### ISSUE THREAD

**Issue by capc0** [callstack/react-native-paper#2329]
### Current behaviour

clicking a button like this one crashes on react-native-windows

```tsx
<Button mode="contained" onPress={() => console.log('clicked crash button')}>
      click to crash
</Button>
```

### Expected behaviour

it should not crash

### Code sample

https://github.com/capc0/rn-paper-btn-click-crash-win

### What have you tried

with no mode specified, it does not crash

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | windows
| react-native          | 0.63.3
| react-native-paper    | 4.3.0
| node                  | 12.13.0
| npm or yarn           | 6.14.2
| expo sdk              | -

**Comment by creambyemute** [comment]
Maybe something to have a look at with the team of rn-windows?

**Comment by capc0** [comment]
the rn-windows team identified the crash - described here https://github.com/microsoft/react-native-windows/issues/6430#issuecomment-722327863

**Comment by alexiadorneles** [comment]
Hey I'm having the issue still.
"react-native": "0.63.4"
"react-native-paper": "^4.7.2"

**Comment by milkmanmatty** [comment]
Issue still happening, elevation property is still trying to be animated on windows.
"react-native": "0.64.1",
"react-native-paper": "^4.9.1",
