### ISSUE TITLE
Broken links to React Native Props Official Documentation

### ISSUE THREAD

**Issue by MihirSomani** [callstack/react-native-paper#2331]
### Current behaviour

When I am navigating documentation of (for example) https://callstack.github.io/react-native-paper/text.html and I click on `...Text props` link at the bottom to look at addition props supported by React Native, I get routed to a 404 page. 
This is due to the `href` to the official docs pointing to `https://reactnative.dev/docs/text.html#props` while the official docs do not have (probably removed recently) `.html` in the URI.
I am using the official docs on `https://callstack.github.io/react-native-paper/index.html` and React Native v0.63

The same issue persists in the documentation of every(as far as I can tell) component on React Native Paper due to incorrect href.

### Expected behaviour

To get routed to the correct page instead of a 404.

### Code sample

Not applicable

### Screenshots (if applicable)

N/A

### What have you tried

N/A

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    |
| node                  |
| npm or yarn           |
| expo sdk              |

**Comment by RichardLindhout** [comment]
React Native redirects now but it still needs to be fixed as it does not take in account the anchor (`#`) element in the url.
@MihirSomani could you do a PR where you replace these urls in the whole repository?

In visual code you do a search replace with regex the .* should be enabled.

https://reactnative.dev/docs/(.*).html#props
https://reactnative.dev/docs/$1#props

**Comment by MihirSomani** [comment]
Sure thing, I'll handle it in the next couple of days.

**Comment by Trancever** [comment]
This should be fixed right now.
