### ISSUE TITLE
Checkbox on iOS is not visible

### ISSUE THREAD

**Issue by rumax** [callstack/react-native-paper#2334]
### Current behaviour

Checkbox on iOS is no visible if not checked. 

### Code sample

[Use the demo from docs](https://snack.expo.io/?name=Checkbox&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fcheckbox.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20Checkbox%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bchecked%2C%20setChecked%5D%20%3D%20React.useState(false)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CCheckbox%0A%20%20%20%20%20%20status%3D%7Bchecked%20%3F%20%27checked%27%20%3A%20%27unchecked%27%7D%0A%20%20%20%20%20%20onPress%3D%7B()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20setChecked(!checked)%3B%0A%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper)

```
import * as React from 'react';
import { Checkbox } from 'react-native-paper';

const MyComponent = () => {
  const [checked, setChecked] = React.useState(false);

  return (
    <Checkbox
      status={checked ? 'checked' : 'unchecked'}
      onPress={() => {
        setChecked(!checked);
      }}
    />
  );
};

export default MyComponent;
```

### Screenshots (if applicable)

Unchecked state: 

<img width="928" alt="Screenshot 2020-11-01 at 16 02 14" src="https://user-images.githubusercontent.com/2707180/97810109-c102cb00-1c71-11eb-92d7-24716e796ec4.png">

Checked state:

<img width="347" alt="Screenshot 2020-11-01 at 18 44 20" src="https://user-images.githubusercontent.com/2707180/97810176-500fe300-1c72-11eb-9734-2d9f856f4445.png">

### What have you tried

Used official docs https://callstack.github.io/react-native-paper/checkbox.html

Also not `style` property to checkbox?

<img width="592" alt="Screenshot 2020-11-01 at 18 47 31" src="https://user-images.githubusercontent.com/2707180/97810244-cd3b5800-1c72-11eb-9eae-60e1a71f0e12.png">

<img width="649" alt="Screenshot 2020-11-01 at 18 47 41" src="https://user-images.githubusercontent.com/2707180/97810245-d0364880-1c72-11eb-8cd2-ce041349519b.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS or web case with expo
| react-native          | 0.63.3
| react-native-paper    | 4.3.0
| node                  | v12.16.1
| npm or yarn           | 6.13.4
| expo sdk              | 39.0.0

**Comment by rumax** [comment]
> Couldn't find version numbers for the following packages in the issue:
> react-native-vector-icons

```
"react-native-vector-icons": "^7.1.0"
```

expo and NPM is in the issue description

**Comment by Selfmade-RuLeZ** [comment]
https://callstack.github.io/react-native-paper/checkbox.html

As you can see, it's the typically behavior. You have to wrap a box or anything by yourself.

**Comment by rumax** [comment]
Hi @Selfmade-RuLeZ and thanks for your reply.

> As you can see, it's the typical behavior. 

can you, please, elaborate a bit more on what is the typical behaviour? If a user cannot see the element, where he should tap? I also tried to wrap the checkbox into the `View` with a background colour, but result is the same - element is not visible. 

> Edit: Or just use <Checkbox.Android ... />

On iOS? Why?

**Comment by Selfmade-RuLeZ** [comment]
The thing that I was pointing to, is that it's not a bug, it's a well formed implementation. 
On iOS you should not use Checkboxes if you want to strictly fit their guidlines. 
Here is a example of [Material Design Cross Platform Adaption](https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines), there you can see the controls guideline

**Comment by dfabreguette-ap** [comment]
Still, this example is not working for me on my device : 
https://snack.expo.io/?name=Checkbox&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fcheckbox.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20Checkbox%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bchecked%2C%20setChecked%5D%20%3D%20React.useState(false)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CCheckbox%0A%20%20%20%20%20%20status%3D%7Bchecked%20%3F%20%27checked%27%20%3A%20%27unchecked%27%7D%0A%20%20%20%20%20%20onPress%3D%7B()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20setChecked(!checked)%3B%0A%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper

Is it just me ?

**Comment by Selfmade-RuLeZ** [comment]
As I mentioned one post above, the CheckBox is implemented correctly, as iOS should not show boxes around CheckBoxes. On iOS you should use sliders for most things.

**Comment by dfabreguette-ap** [comment]
@Selfmade-RuLeZ ok so I'll need some specific iOS Code for each boolean form values ?

**Comment by Selfmade-RuLeZ** [comment]
Depends on the use case. You could life with the missing box, use sliders for android too or implement specific code.

**Comment by dfabreguette-ap** [comment]
alright, thanks for the quick answer, maybe it'd be good to mention it inside documentation

**Comment by butterfly-valley** [comment]
> On iOS? Why?
Because on iOS it sucks.

**Comment by JooAndriano** [comment]
type mode="android"
the box will appear in ios...

**Comment by septe01** [comment]
> Still, this example is not working for me on my device : https://snack.expo.io/?name=Checkbox&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fcheckbox.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20Checkbox%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bchecked%2C%20setChecked%5D%20%3D%20React.useState(false)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CCheckbox%0A%20%20%20%20%20%20status%3D%7Bchecked%20%3F%20%27checked%27%20%3A%20%27unchecked%27%7D%0A%20%20%20%20%20%20onPress%3D%7B()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20setChecked(!checked)%3B%0A%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper
> 
> Is it just me ?

but when false not show check? on ios

**Comment by FaisalKhawaj** [comment]
You can always use <Checkbox.Android /> to just use the Android properties (ie. outlined unchecked box) on iOS devices.

**Comment by avalonder** [comment]
This was solved for me by implementing `<Checkbox.Item>` along with `mode="android"`. 

Example:

```
<Checkbox.Item 
         status={checked ? 'checked' : 'unchecked'}
         onPress={() => {
           setChecked(!checked);
         }}
         color="red"
         uncheckedColor="green"
         mode="android"
        />
```

**Comment by lasithalakmal** [comment]
> You can always use <Checkbox.Android /> to just use the Android properties (ie. outlined unchecked box) on iOS devices.

Worked perfectly. Thanks

**Comment by ansarikhurshid786** [comment]
> This was solved for me by implementing `<Checkbox.Item>` along with `mode="android"`.
> 
> Example:
> 
> ```
> <Checkbox.Item 
>          status={checked ? 'checked' : 'unchecked'}
>          onPress={() => {
>            setChecked(!checked);
>          }}
>          color="red"
>          uncheckedColor="green"
>          mode="android"
>         />
> ```

solved my problem

**Comment by Prajwaltechversant** [comment]
@ansarikhurshid786 But there is an indicator on the left side when checking in android
