### ISSUE TITLE
Fab icon not working on web

### ISSUE THREAD

**Issue by oste** [callstack/react-native-paper#2346]
### Current behaviour

The fab icon is not properly loading the font. As seen in the official demo [here](https://snack.expo.io/?name=FAB&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Ffab.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20StyleSheet%20%7D%20from%20%27react-native%27%3B%0Aimport%20%7B%20FAB%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20(%0A%20%20%3CFAB%0A%20%20%20%20style%3D%7Bstyles.fab%7D%0A%20%20%20%20small%0A%20%20%20%20icon%3D%22plus%22%0A%20%20%20%20onPress%3D%7B()%20%3D%3E%20console.log(%27Pressed%27)%7D%0A%20%20%2F%3E%0A)%3B%0A%0Aconst%20styles%20%3D%20StyleSheet.create(%7B%0A%20%20fab%3A%20%7B%0A%20%20%20%20position%3A%20%27absolute%27%2C%0A%20%20%20%20margin%3A%2016%2C%0A%20%20%20%20right%3A%200%2C%0A%20%20%20%20bottom%3A%200%2C%0A%20%20%7D%2C%0A%7D)%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper) 

<img width="70" alt="Screen Shot 2020-11-07 at 9 37 19 PM" src="https://user-images.githubusercontent.com/350275/98455691-06c40580-2142-11eb-931c-cd4ec6fd08cd.png">

### Expected behaviour

Font icon loads as seen on android and ios

### Code sample

```
import * as React from 'react';
import { StyleSheet } from 'react-native';
import { FAB } from 'react-native-paper';

const MyComponent = () => (
  <FAB
    style={styles.fab}
    small
    icon="plus"
    onPress={() => console.log('Pressed')}
  />
);
```

### Your Environment

See expo snack listed above and locally I am using

| software              | version
| --------------------- | -------
| react-native          | 0.63
| react-native-paper    | ^4.3.1
| react-native-vector-icons | ^7.1.0
| expo | 39.0.0

**Comment by oste** [comment]
note: I also ran into an issue with deprecated TabBarIOS in react-native-vector-icons. MR fix here https://github.com/oblador/react-native-vector-icons/pull/1266

Maybe this is related to more deprecations/changes.

**Comment by RichardLindhout** [comment]
> note: I also ran into an issue with deprecated TabBarIOS in react-native-vector-icons. MR fix here [oblador/react-native-vector-icons#1266](https://github.com/oblador/react-native-vector-icons/pull/1266)
> 
> Maybe this is related to more deprecations/changes.

Me too, I forked react-native-vector-icons for this to remove it but maintainer is not very responsive.

To answer your question.
Have you followed the instructions in the 'Load the Material Community Icons' section on this page https://callstack.github.io/react-native-paper/using-on-the-web.html#load-the-material-community-icons
?

**Comment by RichardLindhout** [comment]
Oops I see you are using Expo I'll try to find out why it won't load

**Comment by RichardLindhout** [comment]
Related issue: https://github.com/callstack/react-native-paper/issues/2129

**Comment by RichardLindhout** [comment]
Workaround is


```
import * as React from 'react';
import { StyleSheet } from 'react-native';
import { FAB } from 'react-native-paper';
import { MaterialCommunityIcons } from '@expo/vector-icons';

const MyComponent = () => (
  <FAB
    style={styles.fab}
    small
    icon={(props) => <MaterialCommunityIcons name="plus" {...props}/>}
    onPress={() => console.log('Pressed')}
  />
);
```

**Comment by RichardLindhout** [comment]
At the moment react-native-paper relies on internal Expo which is probably a bad idea and results in issues like this where web expo is different and does not expose the icons on the global.__expo variable

https://github.com/callstack/react-native-paper/blob/2e62169febfcd0f5cf2757ab1bb0f9cbbe8a324e/src/components/MaterialCommunityIcon.tsx#L19

I think we should do something like this

```typescript

let MaterialCommunityIcons: any;

try {
  // Optionally require vector-icons
  MaterialCommunityIcons = require("react-native-vector-icons/MaterialCommunityIcons")
    .default;
} catch (e) {
  try {
    MaterialCommunityIcons = require("@expo/vector-icons/MaterialCommunityIcons")
      .default;
  } catch (expoError) {
    let isErrorLogged = false;
    MaterialCommunityIcons = ({ name, color, size, ...rest }) => {
      /* eslint-disable no-console */
      if (!isErrorLogged) {
        if (
          !/(Cannot find module|Module not found|Cannot resolve module)/.test(
            e.message
          )
        ) {
          console.error(e);
        }

        console.warn(
          `Tried to use the icon '${name}' in a component from 'react-native-paper', but 'react-native-vector-icons' could not be loaded.`,
          `To remove this warning, try installing 'react-native-vector-icons' or use another method to specify icon: https://callstack.github.io/react-native-paper/icons.html.`
        );

        isErrorLogged = true;
      }

      return (
        <Text
          {...rest}
          style={[styles.icon, { color, fontSize: size }]}
          // @ts-ignore
          pointerEvents="none"
        >
          □
        </Text>
      );
    };
  }
}

```

I don't have time a.t.m. to test my code for all platforms and make a good PR. Could you do that?

**Comment by RichardLindhout** [comment]
I don't use expo but with create-react-app 4 i had problems with react-native-vector-items

```
     {Platform.OS === 'web' ? (
              <style type="text/css">
                {`@font-face {
                font-family: 'MaterialCommunityIcons';
                src: url(${
                  require('react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf')}) format('truetype');
              }`}
              </style>
            ) : null}
```

Adding .default fixed it for me
```
     {Platform.OS === 'web' ? (
              <style type="text/css">
                {`@font-face {
                font-family: 'MaterialCommunityIcons';
                src: url(${
                  require('react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf')
                    .default
                }) format('truetype');
              }`}
              </style>
            ) : null}
```
