### ISSUE TITLE
How to add Image with the Radio Group button

### ISSUE THREAD

**Issue by scrapecoder** [callstack/react-native-paper#2347]
I'm trying to add image inside the Radio button
`
<RadioButton.Group>
 <RadioButton.Item>
  <Image source={...}/>
 </RadioButton.Item>
<RadioButton.Group>`
but `image` is not showing .

`react-native: "0.63.0"`
`react-native-paper:"3.10.1"`
`react-native-vector-icons:"6.6.0"`

**Comment by RichardLindhout** [comment]
Radio Items does not have support for images. You'll need to create a custom component for this.

<View style={{flexDirection:'row'}}>
<RadioButton />
<Image />
</View>

**Comment by Trancever** [comment]
As @RichardLindhout said, you need to create a custom component.
