### ISSUE TITLE
Long text in TextInput isn't scrollable (IOS only)

### ISSUE THREAD

**Issue by valeriik** [callstack/react-native-paper#2355]
### Current behaviour

It is impossible to scroll long text by swipe (in case if text is longer then TextInput width) (IOS only)

### Expected behaviour

User should have possibility to move at start/end of long text by scrolling as it works on Android.
Please note: I tried on iOS simulator, did not try on real iOS device.

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/24571089/98947010-51a49b00-24fd-11eb-9742-b816c02dd590.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.61.2
| react-native-paper    | ^4.3.1
| node                  | v12.8.0
| npm or yarn           | npm 6.10.2
| expo sdk              | -
| react-native-vector-icons              | not installed

**Comment by RichardLindhout** [comment]
Does the native textinput from React Native has the same behaviour or only with the React Native Paper Textinput?

**Comment by valeriik** [comment]
TextInput from React Native has the same behavior, and it was surprise for me.
It seems this is something native for iOS. Really very weird. Intuitively it seems that there should definitely be a scroll!

Official React Native documentation says:

https://reactnative.dev/docs/textinput#scrollenabled

> If false, scrolling of the text view will be disabled. The default value is true. Only works with multiline={true}.
> 
> PLATFORM
> iOS

_Only works with multiline={true}_ - but so if there is no space for multiline text in UI and user can write long text?
Actually, if I used
`import { TextInput } from 'react-native'`
I could wrap it in ScrollView, but looks like I can't do nothing here :)

**Comment by RichardLindhout** [comment]
As far as I have used an iPhone you can have to longpress and go to the left with the cursor. Or you can go right with the space on the keyboard

**Comment by RichardLindhout** [comment]
So when you longpress the textinput and go to the right I think it will scroll fine!
