### ISSUE TITLE
react-native-paper can no longer create animated component using react-native-reanimated (v1) since 4.3.1

### ISSUE THREAD

**Issue by SleeplessByte** [callstack/react-native-paper#2364]
### Current behaviour

When trying to animate text by `react-native-paper` using `react-native-reanimated` (v1), native apps crash, and web apps can't find the native component.

```text
Error: Unable to locate attached view in the native tree
```

### Expected behaviour

It works.

### Code sample

[Snack](https://snack.expo.io/@derk-jan/react-native-paper-4.4.0-no-reanimated) for minimal reproducible example

```tsx
import * as React from 'react';
import { Animated, Text, View } from 'react-native';
import Reanimated from 'react-native-reanimated'

import { Text as PaperText } from 'react-native-paper'

const AnimatedText = Animated.createAnimatedComponent(Text)
const ReanimatedText = Reanimated.createAnimatedComponent(Text)
const AnimatedPaperText = Animated.createAnimatedComponent(PaperText)
const ReanimatedPaperText = Reanimated.createAnimatedComponent(PaperText)

export default function AssetExample() {
  return (
    <View>
      <AnimatedText>Non-Paper Animated works</AnimatedText>
      <ReanimatedText>Non-Paper Re-animated works</ReanimatedText>
      <AnimatedPaperText>Paper Animated works</AnimatedPaperText>
      <ReanimatedPaperText>it breaks?</ReanimatedPaperText>
    </View>
  );
}
```

1. Change version to `4.3.0` and it starts working
2. Change version to `4.3.1` and it stops working
3. Change version back to `4.4.0` and it still is broken
3. Alternatively, comment out `<ReanimatedPaperText>` and it starts working

### Using 4.3.0 is not a workaround

In 4.3.0, `@react-navigation/material-bottom-tabs` won't "show" the screens (they stay on `display: none`). This is solved in `4.3.1`, which introduces this other issue.

### Using 4.2.0 *is* a workaround

In 4.2.0, none of the aforementioned issues are present.

### Your Environment

| software              | version
| --------------------- | -------
| ios android web      |  0.13.x for web
| react-native          |  expo-39.0.4
| react-native-paper    | 4.4.0
| react-native-reanimated | 1.13.0
| node                  | 12.18.2
| yarn           | 1.22.10
| expo | 39.0.4

Snack SDK: 39.0.0

**Comment by SleeplessByte** [comment]
I have not yet confirmed if it's still present.

**Comment by SleeplessByte** [comment]
I can confirm this is still present.

**Comment by cltsang** [comment]
related: #2292

**Comment by cltsang** [comment]
I'm not able to create an animated Dialog using reanimated 2.0.0-rc.2 with paper 4.7.1 either.

**Comment by actuallymentor** [comment]
I'm having issues with `Animated` as well.

**Comment by andreibarabas** [comment]
Same issue here:

react-native-paper: 4.7.2
reanimated: 1.13.2

We tried by animating the progressbar

`
import {ProgressBar} from 'react-native-paper';
const AnimatedProgressBar = Animated.createAnimatedComponent(ProgressBar);

const ProgressBarView: React.FC<ProgressBarProps> = props => {

...

return (
   <AnimatedProgressBar style={progressBarStyle} />
);

}
`

**Comment by Hektar90** [comment]
Same issue here...

@andreibarabas createAnimatedComponent does not accept functional components. ProgressBar and other react-native-paper components are written as functional

**Comment by Hektar90** [comment]
Using the HOC mentioned [here](https://stackoverflow.com/questions/57359389/pass-functional-component-to-animated-createanimatedcomponent) works fine for me.

**Comment by SleeplessByte** [comment]
@satya164 is the stale bot here bugged? I responded within hours, and definitely within 7 days of the stalebot comment https://github.com/callstack/react-native-paper/issues/2364#issuecomment-761705015, but it still closed this issue.

**Comment by andreibarabas** [comment]
Thanks @Hektar90

**Comment by SleeplessByte** [comment]
It's not fixed. Please reopen @raajnadar.

There is a workaround, which is great, but that's undocumented, which is not.

**Comment by actuallymentor** [comment]
> It's not fixed. Please reopen @raajnadar.
> 
> There is a workaround, which is great, but that's undocumented, which is not.

What is said undocumented workaround?

**Comment by actuallymentor** [comment]
> ...of gewoon schreeuwen tot het werkt. Trying that right now.

Schreeuwen werkte niet, my laptop has more patience than I. `storyofmylife.gif`

For those landing here from Google as I did, here is the js annotated solution:

```js
export const withAnimated = WrappedComponent => {

  // Extract the display name of the inputted component
  const displayName = WrappedComponent.displayName || WrappedComponent.name || 'Component'

  // Create a class based on the React Component built-in
  class WithAnimated extends React.Component {
    
    // Set display name property of new class
    displayName = `WithAnimated( ${ displayName } )`

    // Return the inputted component wrapped as a WithAnimated that is so far only a default React Component
    render() {
      return <WrappedComponent { ...this.props } />
    }

  }

  // Run the React Component through the built-in animatifier
  return Animated.createAnimatedComponent( WithAnimated )

}
```

**Comment by SleeplessByte** [comment]
> `storyofmylife.gif`

`same.apng`

I think the reason no one bothered to annotate it before is because this is the standard Higher-Order Component.
Only information missing is how to use:

```javascript
// Instead of...
const AnimatedParagraph = Animated.createAnimatedComponent(Paragraph)

// ...use 
const AnimatedParagraph = withAnimated(Paragraph)
```

**Comment by ashuvssut** [comment]
can some TypeScript wizard help with with assigning types for the proposed solution?

I am writing the types for it like a noob😢

```ts
const DummyReText = Animated.createAnimatedComponent(Text);
type TReText = typeof DummyReText; // << I AM USING THIS TO GET THE TYPE FOR ReText
export function ReTextCC(Compo: any) {
  const displayName = Compo.displayName || Compo.name || "Component";

  class WithAnimated extends React.Component {
    static displayName = `WithAnimated(${displayName})`;

    override render() {
      return <Compo {...this.props} />;
    }
  }

  return Animated.createAnimatedComponent(WithAnimated);
}
const ReText = ReTextCC(Text) as unknown as TReText; // << TYPE ASSERTION
```

**Comment by aditasha** [comment]
@ashuvssut Here's the wrapper that I use based on the SO mentioned, written in TypeScript. The type is assigned based on the inserted component's type.
```TypeScript
export function withAnimated<T extends object>(
  WrappedComponent: React.ComponentType<T>
): React.ComponentClass<AnimateProps<T>, any> {
  const displayName =
    WrappedComponent.displayName || WrappedComponent.name || 'Component';

  class WithAnimated extends React.Component<T, any> {
    static displayName = `WithAnimated(${displayName})`;

    render(): React.ReactNode {
      return <WrappedComponent {...this.props} />;
    }
  }
  return Animated.createAnimatedComponent(WithAnimated);
}
```
Usage:
```TypeScript
const AnimatedTextInput = withAnimated(TextInput);
```
