### ISSUE TITLE
Divider color should be inside theme (to be able to override it too)

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#237]
Right now the `dark` theme does not work for it. See: https://github.com/callstack/react-native-paper/blob/master/src/components/Divider.js#L53-L66

**Comment by satya164** [comment]
@ferrannp can you elaborate what the issue is with a code sample and screenshot? divider works fine for me with the dark theme in the example app.

**Comment by Trancever** [comment]
For me also divider works fine in both themes in the example app and I am able to override it. Haven't checked it carefully before submitting PR.. :D

**Comment by ferrannp** [comment]
Yeah I guess my problem has been that the divider in dark theme for iOS is almost not visible for my taste here:

<img width="425" alt="screen shot 2018-02-10 at 19 06 43" src="https://user-images.githubusercontent.com/774577/36065060-9fff63ce-0e95-11e8-9e89-3d50b960665b.png">

So I wanted to override the color like:

<img width="423" alt="screen shot 2018-02-10 at 19 07 09" src="https://user-images.githubusercontent.com/774577/36065063-a80bd52a-0e95-11e8-8921-d359ffb0d894.png">

However, I'd like to have all colors as part of the `theme`. 

Maybe can we extract the nested `theme` so it's easier to override/extend the type? Like `type Theme = ThemeColors & ThemeFonts...` ?

For me it would be fine to have colors that material guide specify like for dividers and icons directly into the theme but if you don't want that, I'm fine too.

**Comment by satya164** [comment]
Let's check it on Monday

**Comment by ferrannp** [comment]
Caused by using older version.
