### ISSUE TITLE
TextInput is behaving weird in rtl..

### ISSUE THREAD

**Issue by moedeveloper** [callstack/react-native-paper#2371]
I am having weird behaving when forcing the application to rtl,
When I type the cursor is jumping backward please see the following video. 

https://drive.google.com/file/d/1YHps0mQwk-qx__W3moiaGwLDG5NfvWeX/view?usp=drivesdk

Any idea ?

**Comment by juspeeh** [comment]
@moedeveloper  I'm facing similar issues. Did you solve it somehow?
