### ISSUE TITLE
Flickering on TextInput with label

### ISSUE THREAD

**Issue by Dkokkonas** [callstack/react-native-paper#2380]
### Current behaviour

When rendering a TextInput on the screen instantly ( i.e conditional rendering logic, not using react-navigation which prerenders ) with a label we’re getting fickering behaviour.
Not using a label but only a placeholder doesn’t have the same issue.
So TL;DR , labels on TextInput components cause flickering

### Expected behaviour
No flickering as placeholder 

### Code sample
```
class App extends React.Component {

  constructor(props) {
    super(props)
    this.state = {
      nubmerofRows: 1,
    }
  }

  componentDidMount() {
    console.log("did mount");
  }

  render() {

    let { nubmerofRows } = this.state
    let arrayOfRows = Array.from(Array(nubmerofRows).keys())
    return (

      <View style={{ flex: 1 }}>
        <StatusBar />
        <View style={{ flex: 1 }}>
          {arrayOfRows.map((item, index) => {
            return (
              <View key={`RowWith${index}`} style={{ flexDirection: "row", marginBottom: 1 }}>
                <View style={{ flex: 1, marginRight: 1, }}>
                  <TextInput
                    placeholder={"placeholder"} />
                </View>
                <View style={{ flex: 1 }}>

                  <TextInput
                    label={"label"} />
                </View>
              </View>
            )
          })}
        </View>
        <View style={{ width: "100%", height: 40, flexDirection: "row" }}>
          <TouchableOpacity
            onPress={() => { this.setState({ nubmerofRows: nubmerofRows + 10 }) }}
            style={{ flex: 1, backgroundColor: "red", justifyContent: "center" }}>
            <Text style={{ textAlign: "center" }}>Add Inputs</Text>
          </TouchableOpacity>
          <TouchableOpacity
            onPress={() => { this.setState({ nubmerofRows: nubmerofRows - 10 }) }}
            style={{ flex: 1, backgroundColor: "green", justifyContent: "center" }}>
            <Text style={{ textAlign: "center" }}>Remove Inputs</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }
};
```

### Screenshots (if applicable)
![flickeringTextInput](https://user-images.githubusercontent.com/10373137/100088254-80553680-2e58-11eb-99a3-ea23b4f2f922.gif)

### What have you tried

Tried to add some logic with onFocus Event( showing placeholder until onfocus triggers and then display label) but the result is not pretty 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.61.5
| react-native-paper    | 3.11.0
| node                  | 12.13.0
| npm or yarn           | npm

**Comment by brunohkbx** [comment]
could it be related to #1648? cc @OlimpiaZurek

**Comment by Dkokkonas** [comment]
Tested with latest version of react-native and react-native-paper and it still happerns
