### ISSUE TITLE
Strange button behavior when text is taken from i18n

### ISSUE THREAD

**Issue by Angelk90** [callstack/react-native-paper#2387]
### Current behaviour

Hi @Trancever , 

As seen from the image when the text is fetched via `react-i18next`, from that problem you can't see the text, there has to be a rendering of something inside for the text to be seen.

### Expected behaviour

<img width="90" alt="Schermata 2020-12-01 alle 11 49 09" src="https://user-images.githubusercontent.com/20476002/100731133-47bedb00-33cb-11eb-9285-65fdf946b805.png">

### Code sample

```javascript
import {useTranslation} from 'react-i18next';
const {t} = useTranslation();

const language = (
    <Button
      raised
      mode="contained"
      onPress={bottomSheetLang}>
      {t('language')}
    </Button>
  );
```

### Screenshots (if applicable)

<img width="97" alt="Schermata 2020-12-01 alle 11 41 43" src="https://user-images.githubusercontent.com/20476002/100730673-a46dc600-33ca-11eb-8ccb-7bccc75281f9.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.63.3
| react-native-paper    | 4.4.1
| node                  | 12.18.3
| npm or yarn           | yarn
| react-native-vector-icons                  | 7.1.0

**Comment by Angelk90** [comment]
@Trancever : 
Are there any news?

I created an example, link: https://snack.expo.io/syV2taPQY

The problem happens if I try it on a physical device, then I scan the qr and I try it on my device or on the mac emulator.

On the expo emulator it seems that it gives no problems.

**Comment by unikvozm** [comment]
We need some time to investigate it. Maybe this is not a problem with our component, it's more likely the text that comes from i18n library is somehow longer and doesn't fit inside the button so the elipsis is made at the end...

**Comment by Angelk90** [comment]
![Screenshot_20201209-110359.png](https://user-images.githubusercontent.com/20476002/101615464-6f86f200-3a0e-11eb-8450-7ed7f38cab16.png)

**Comment by Angelk90** [comment]
@unikvozm : Are there any news?

**Comment by shubhamdeol** [comment]
Any update on this?
