### ISSUE TITLE
Chip - How to change icon color only

### ISSUE THREAD

**Issue by tlgreg86** [callstack/react-native-paper#2392]
I'm currently trying to use the Chip component with an icon and haven't read about a way to change the color of only the icon. Is there a step in the docs that I'm missing? If not, would it be possible to add that to the Chip components functionality?

**Comment by tlgreg86** [comment]
```sh
"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz"
"react-native-gesture-handler": "~1.7.0"
"react-native-paper": "^4.4.1"
```

**Comment by dfabreguette-ap** [comment]
Hi !
Real issue for me - there's no way that I know to do that.
One way could to pass on an "iconStyle" prop.
Would be a great idea to do that don't you think ?

**Comment by francesco-clementi-92** [comment]
Any news on this?

**Comment by PunainenAurinko** [comment]
Guys, like with any icon prop in React Native Paper you can pass an Icon component here and change the icon color for that component:

```
import Icon from 'react-native-vector-icons/MaterialCommunityIcons'
```
and then:

```
<Chip
    icon={() => (
        <Icon name="icon-name" size={16} color="red" />
    )}
>
    Your Chip Label Text
</Chip>
```

You can then add a separate getter function for the icon to avoid having unnecessary anonymous functions in render.

**Comment by AmandaSkraba** [comment]
> Pessoal, como em qualquer prop de ícone no React Native Paper, você pode passar um componente de ícone aqui e alterar a cor do ícone desse componente:
> 
> ```
> import Icon from 'react-native-vector-icons/MaterialCommunityIcons'
> ```
> 
> e depois:
> 
> ```
> <Chip
>     icon={() => (
>         <Icon name="icon-name" size={16} color="red" />
>     )}
> >
>     Your Chip Label Text
> </Chip>
> ```
> 
> Você pode adicionar uma função getter separada para o ícone para evitar funções anônimas desnecessárias na renderização.

Essa resposta resolveu meu problema, obrigada!
