### ISSUE TITLE
TouchableWithNoFeedback Equivalents for Components such as Button and List.Item

### ISSUE THREAD

**Issue by ChrisHatchDev** [callstack/react-native-paper#2396]
**Is your feature request related to a problem? Please describe.**
The touchable feedback (i.e. ripple effect on android) looks bad when wrapped in certain elements such as a List.Item with rounded edges on the parent view. The ripple effect plays to fill a box outside the bounds and distracts from the color based feedback we have already implemented in the view.

**Describe the solution you'd like**
I would love the option to disable touch feedback on a given component. Such as Buttons and List.Items. The behavior would be similar to the TouchableWithoutFeedback component from the React-Native base library. 

The usage would be a simple prop passed on the component. i.e. `<List.Item touchFeedback={false}....></List.Item>`

**Describe alternatives you've considered**
I've considered using a touchable without feedback and re-implementing the logos on the left/right of a list item but, that felt very hacky and could lead to a disconnect with style around the rest of the app.

I also considered this for the Button component but, I also use the style and icon props to stay consistent throughout the app.

**Additional context**
![Simulator Screen Shot - iPhone 11 - 2020-12-03 at 19 35 28](https://user-images.githubusercontent.com/9088061/101106741-c4ee7980-359e-11eb-8d50-6a6386bfd9e9.png)

react-native: 0.63.2
react-native-paper: ^4.2.0
react-native-vector-icons: ^7.1.0

**Comment by xXH4tchXx** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native` (found: `0.63.2`, latest: `0.63.4`)
> * `react-native-paper` (found: `4.2.0`, latest: `4.4.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Not relevant to version number at this time as it's a feature request.
