### ISSUE TITLE
Error Message: currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput

### ISSUE THREAD

**Issue by SupaMario123** [callstack/react-native-paper#2397]
First, i really like your package, thanks a lot for providing it. 

I use the TextInput, and everytime it is focused i get the following error message:

currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput
- node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
- node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
- node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
- node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
- node_modules\react-native\Libraries\Components\TextInput\TextInputState.js:39:4 in currentlyFocusedField
* http://192.168.178.21:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:274366:90 in _updateKeyboardSpace
- node_modules\react-native\Libraries\vendor\emitter\EventEmitter.js:189:10 in emit
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

Can someone replace currentlyFocusedField  with currentlyFocusedInput? 
That would be awesome. 

My versions:

    "expo": "^39.0.0",
    "react-native": 0.63.2
    "react-native-paper": "4.4.1"
    "react-native-svg": "12.1.0"
    "@expo/vector-icons": "^10.0.0",

Tested on a Samsung Galaxy S10.

**Comment by SupaMario123** [comment]
Updated.

**Comment by SupaMario123** [comment]
Anybody there?

**Comment by Trancever** [comment]
@SupaMario123 We will try to look into that this or next week, but I can't promise cause we want to focus on higher priority work. Feel free to submit a PR that fixes the issue tho 🙏 We are more than happy to accept PRs from external contributors!

**Comment by haxonadora** [comment]
@SupaMario123 I couldn't reproduce this issue using libraries versions you provided. Could you send the code you are using on https://snack.expo.io/? or link to repository where this problem occurs?

**Comment by SupaMario123** [comment]
@haxonadora i will try to put a small example of it on snack. 
I cant give you access to the repo since this is a project for a customer.

Thanks for replying, i will message you when i have a link.
