### ISSUE TITLE
[WARN] Require cycle: node_modules\react-native-paper\src\index.tsx

### ISSUE THREAD

**Issue by PRA1995SAG** [callstack/react-native-paper#2401]
### Current behaviour

>  WARN     Require cycle: node_modules\react-native-paper\src\index.tsx -> node_modules\react-native-paper\src\components\Checkbox\Checkbox.tsx -> node_modules\react-native-paper\src\components\Checkbox\CheckboxItem.tsx -> node_modules\react-native-paper\src\index.tsx
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> RCTView
> RCTView
> RNCSafeAreaProvider
> GestureHandlerRootView
> RCTView
> RCTView

### Expected behaviour
> idk, if it is normal behaviour or it needs to be fixed. But I request a response, why this warning comes? how to fix ?

### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/41970756/101448303-cd530580-394c-11eb-8cb6-a6be5ef23ac4.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.63.3
| react-native-paper    | 4.4.1
| node                  | 12.18.2
| npm or yarn           | 1.22.4
| expo sdk              | no

> *Notice: I use `yarn`

**Comment by unikvozm** [comment]
The fixes are merged (#2378) and will be available in the next release soon =)
