### ISSUE TITLE
a possible bug with Datatable pagination

### ISSUE THREAD

**Issue by unikvozm** [callstack/react-native-paper#2405]
### Current behaviour

https://github.com/callstack/react-native-paper/blob/a973af024fd7cbf0ccf9d43f86de1cdc78ab0bdd/src/components/DataTable/DataTablePagination.tsx#L108-L133

If `page = 0` and `numberOfPages = 0`, the second button is not `disabled` because the condition is `false`, so you can click and move on.
If you click also then the first button is not `disabled`.

**Comment by Trancever** [comment]
Fixed in v4.5.0
