### ISSUE TITLE
Datatable pagination record start and end buttons and select the number of records to display

### ISSUE THREAD

**Issue by Angelk90** [callstack/react-native-paper#2416]
**Is your feature request related to a problem? Please describe.**

![](https://lh3.googleusercontent.com/4Rk51S-HAaoypmnSS0g4XpOtNx9adOCOBRmdIdQa0fgruMdWjFKTfRXepqG3uVIblbPMFDMroNuHFcrazxh8SpevUcHR4gsMRQPF6w=w1064-v0)

Hi @Trancever , @unikvozm : 

it would be possible to add through an optional props in the pagination also to have the possibility of:
1) add the two buttons that allow you to go to the end of the records and the beginning of the records without having to scroll through all the pages.

2) Select the number of records to be displayed using a select

**Additional context**

Taken from the official material.io:
https://material.io/components/data-tables#anatomy

**Comment by Angelk90** [comment]
Hi @Trancever, @unikvozm: Any news?

**Comment by unikvozm** [comment]
@Angelk90, thanks for the issue. I’m going to work on it this week.

**Comment by Angelk90** [comment]
@unikvozm : Let me know if you need me to do some tests.

**Comment by Angelk90** [comment]
@unikvozm : Let me know if you need me to do some tests.
