### ISSUE TITLE
Doubt about the ordering of the datatable

### ISSUE THREAD

**Issue by Angelk90** [callstack/react-native-paper#2417]
Hi @Trancever , @unikvozm ,

In the datatable header documentation, [here](https://callstack.github.io/react-native-paper/data-table-header.html).

There is the following image (see below), with its example saying that if `sortDirection = 'descending'` then the arrow is down, but trying the code is opposite the arrow is up.

So I got the doubt, which is the right way?

![](https://callstack.github.io/react-native-paper/screenshots/data-table-header.png)

Expo:

<img width="323" alt="Schermata 2020-12-11 alle 12 28 40" src="https://user-images.githubusercontent.com/20476002/101898455-7186b780-3bac-11eb-9fef-29dacf0b50b2.png">

**Comment by Angelk90** [comment]
Hi @Trancever, @unikvozm: Any news?

**Comment by haxonadora** [comment]
Hey @Angelk90. Thanks for submitting the issue. According to Material design guidelines down arrow should indicate descending sorting as documentation shows. However, as you pointed, that wasn't a case in paper code. Fix for this is already merged and it will be available in next release.

**Comment by Angelk90** [comment]
Hi @haxonadora , 

before making the request I had also checked the material design documentation, which is why I doubted.
Thanks for the correction.

P.s.
You might check out this #2416.
