### ISSUE TITLE
BottomNavigation SafeArea inconsistent

### ISSUE THREAD

**Issue by hardcodet** [callstack/react-native-paper#2419]
### Current behaviour

My bottom navigation has inconsistent padding at the bottom depending on whether it runs on an iPhone 11 or iPhone 12 Max simulator:

- if enclosed in a `SaveAreaView`, it looks good on the 12 Max, but has a huge bottom-padding on the 11
- without a `SaveAreaView`, it looks good on the 11, but is placed outside the safe area on the 12

It appears that the component tries to do some safe area calculations by itself, but fails at the more recent and bigger 12 Max.

### Expected behaviour

This should be consistent. I would prefer it to *not* try and be smart about safe areas. After all, I have to take care of those on every screen, whether it contains a bottom navigation or not.

### Code sample

Really just a simple bottom navigation. Every other control aligns properly on the bottom (if I use a SaveAreaView).

                    <BottomNavigation shifting={false}
                                      style={{position: "absolute", bottom: 0, left: 0, right: 0,}}
                                      navigationState={{index: viewModel.pageIndex, routes}}
                                      onIndexChange={changePageIndex}
                                      renderScene={renderScene}

### Screenshots (if applicable)

Without a SafeArewView around. 11 left, 12 Pro Max on the right:

![image](https://user-images.githubusercontent.com/873009/101989982-3798dc80-3ca4-11eb-847f-3fafcabf4a69.png)

### Your Environment

react-native: 0.63.4
react-native-paper: 4.4.1
react-native-vector-icons: 0.0.0
expo: 40.0.0

**Comment by hardcodet** [comment]
Found a workaround: https://github.com/react-navigation/react-navigation/issues/8972#issuecomment-714474997

 That feels dirty though - as said, IMO, devs should be able and responsible to take care of safe areas themselves. That issues wouldn't even exist then. Just my 0.02$ of course 👍

**Comment by vtoupet** [comment]
@hardcodet This is a regression that came with 4.5.0 If you downgrade to 4.4.1 it works consistently out of the box (no need for additional SafeAreaView)

**Comment by hardcodet** [comment]
Hi @vtoupet 

I'm afraid I actually *am* on 4.4.1. Here's my yarn.lock:

```
react-native-paper@^4.1.0:
  version "4.4.1"
  resolved "https://registry.yarnpkg.com/react-native-paper/-/react-native-paper-4.4.1.tgz#b2fb7c0889fd15d52d6fd5c27df13075104ef911"
  integrity sha512-c2+0XsTg6aAwyJNwumtZLPuFw72/kYyFS2vXDzWZddx5OYF052DbPPUhX4SVom2jxVaI1y9izx88RO5c4hGJEA==
  dependencies:
    "@callstack/react-theme-provider" "^3.0.5"
    color "^3.1.2"
    react-native-safe-area-view "^0.14.9"
```

**Comment by Trancever** [comment]
@hardcodet Could you try version v4.5.0? We migrated away from safe-are-view which seems to be buggy on the latest Iphone.

**Comment by hardcodet** [comment]
yup, 4.5.0 seems to fix the issue, thanks! Good timing! ;)

**Comment by reimibeta** [comment]
> style={{position: "absolute", bottom: 0, left: 0, right: 0,}}
# add this one to your BottomNavigation, you will love it.
safeAreaInsets={{ bottom: 0 }}

**Comment by JesusTectronic** [comment]
<BottomNavigation
      safeAreaInsets={{ bottom: 35 }}
      ...
    />
