### ISSUE TITLE
provide an optional real checkbox for IOS similar to Apple's

### ISSUE THREAD

**Issue by gregbonney-rgare** [callstack/react-native-paper#2430]
Many people have run into the problem that it is hard to find a good checkbox implementation for IOS in react native. Apparently, on IOS you have to implement it as a custom component. That doesn't mean you won't see examples of it such as on the Settings->Maps->Notifications screen. Unfortunately, Google seemed to overlook the fact that Apple actually has a checkbox in such places. Apple does not mention it in their HIG, but it is there for all to see if you have an iPhone or are running the IOS simulator.

While I understand the desire to follow the material design standard, we are forced to look elsewhere for this functionality, and I found it in NativeBase. Their checkmark looks fairly similar to Apple's. So, now the question becomes do I bloat my app by using two competing UI component libraries? Material design standard is a nice starting point and guideline, but if you cannot go beyond it then you will never grow.

![image](https://user-images.githubusercontent.com/56322924/102136989-c4b47080-3e1f-11eb-9cf0-c932caad6b77.png)

**Comment by RichardLindhout** [comment]
You can use a Switch for this: https://callstack.github.io/react-native-paper/switch.html

**Comment by gregbonney-rgare** [comment]
Thanks for the suggestion, Richard, but the example screenshot I provided actually has both types of controls on the same screen which demonstrates that they are not exactly the same thing. If they were, Apple would not have used them both on that screen. The switch is nice for toggling app options, but there are other uses for checkbox where a switch will not look right. While it is technically possible to use them interchangeably the issue is more subtle than that.

**Comment by gregbonney-rgare** [comment]
I found this other project, https://github.com/vonovak/react-native-round-checkbox, which seems to work quite well.

**Comment by Trancever** [comment]
@gregbonney-rgare Sorry, but we won't add components that don't follow MD Guidelines -  it doesn't comply with our idea for this library.

As a workaround, I would suggest to look into NativeBase source code and just copy the needed files into your project. This way you won't end up adding a lot of bytes to the bundle.
