### ISSUE TITLE
react-native-safe-area-view missing after upgrading to 4.5.0

### ISSUE THREAD

**Issue by imsam67** [callstack/react-native-paper#2438]
I just upgraded the npm package in my React Native app from 4.4.1 to 4.5.0 and now I'm getting the following error:

![Screenshot 2020-12-15 150013](https://user-images.githubusercontent.com/15844030/102277981-44a50e00-3ee6-11eb-80dd-9bc5d807588f.jpg)

This is a React Native 0.63.4 app

**Comment by maltoze** [comment]
Just run `npm start -- --reset-cache` worked for me.

**Comment by imsam67** [comment]
Yup, that did it for me too! Thanks!

**Comment by tylerthedeveloper** [comment]
i am still facing this issue
    "react-native-paper": "^4.5.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
