### ISSUE TITLE
Require cycle warnings is still appear after upgrade to 4.5.0

### ISSUE THREAD

**Issue by maltoze** [callstack/react-native-paper#2439]
### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/18044730/102300643-47f4d400-3f90-11eb-9cf6-3ec80fc8dc3b.png)

### What have you tried

```bash
rm -rf node_modules
npm install
npm start -- --reset-cache
```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.63.3
| react-native-paper    | 4.5.0
| node                  | 14.5.0
| npm or yarn           | npm
| expo sdk              | bare workflow

**Comment by rodinhatokay** [comment]
I'm having same issue

**Comment by maltoze** [comment]
Fixed. #2508

**Comment by maltoze** [comment]
Fixed. #2508
