### ISSUE TITLE
BottomNavigation custom height

### ISSUE THREAD

**Issue by spexacloud** [callstack/react-native-paper#2440]
We need to be able to change the height of BottomNavigation. Because we had a problem when we used the custom label. Is there a solution to this issue?

![Screen Shot 2020-12-14 at 10 01 18 PM](https://user-images.githubusercontent.com/75990401/102120522-e7fb1200-3e57-11eb-89e4-2a55ab209b99.png)

_Originally posted by @spexacloud in https://github.com/callstack/react-native-paper/discussions/2428_

**Comment by SpectreWulf** [comment]
@spexa-io Hi did you find any solution for the custom height?
