### ISSUE TITLE
@types/react-native@0.63.41 or newer causes "No overload matches this call."

### ISSUE THREAD

**Issue by pnthach95** [callstack/react-native-paper#2442]
### Current behaviour

Run `yarn add @types/react-native --dev` to install latest version.

After that, VSCode reports "no overload matches this call" with React Native Paper components.

On [version 0.63.41 commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b1253fc6e1057e85ad76cc2f107092756f7becd7), they remove `accessibilityTraits` and `accessibilityComponentType`.

### Expected behaviour

No error when install `@types/react-native` latest version.

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/31266357/102454372-7c3fc180-4070-11eb-8b4d-30bc2c7de5e7.png)

### What have you tried

I installed old version (`yarn add @types/react-native@0.63.40 --dev`), no errors was showed.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 10
| react-native          | 0.63.4
| react-native-paper    | 4.5.0
| node                  | 14.15.2
| npm or yarn           | yarn@1.22.5
| expo sdk              | none

**Comment by Kauto** [comment]
can confirm. There are type errors everywhere with `@types/react-native@0.63.42`. Anyway ```yarn add @types/react-native@0.63.40 --dev``` fixed it for me too.

**Comment by davidvmckay** [comment]
Downgrading to @types/react-native@0.63.40 did not solve this for me.  A possible variable in my situation is use of typescript 4.1.3 ( react-native-paper seems to use 3.8 in its 4.5.0 release ? )

 @Kauto 
 @pnthach95 


  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@fortawesome/react-native-fontawesome": "^0.2.6",
    "react": "17.0.1",
    "react-dom": "^17.0.1",
    "react-native": "0.63.4",
    "react-native-paper": "4.5.0",
    "tslib": "^2.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-native": "^0.63.40",
    "@typescript-eslint/eslint-plugin": "^4.10.0",
    "@typescript-eslint/parser": "^4.10.0",
    "babel-plugin-transform-react-jsx-source": "latest",
    "eslint": "^7.15.0",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-native-typescript-transformer": "^1.2.13",
    "typescript": "^4.1.3"
  },

**Comment by davidvmckay** [comment]
> can confirm. There are type errors everywhere with `@types/react-native@0.63.42` ("properties `accessibilityTraits` and `accessibilityComponentType` are missing"). Anyway `yarn add @types/react-native@0.63.40 --dev` fixed it for me too.

This was the exact problem - those two props.

**Comment by maltoze** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49983

**Comment by drfbwilliams** [comment]
@davidvmckay 

> ACTUALLY using the command `yarn add @types/react-native@0.63.40 --dev` did the correct thing and solved my errors, even with ts4.1.3.

@davidvmckay thank you for posting the correct command.

This was also the source of so many issues I was seeing in TS, crazy stuff like icon resolution etc.

**Comment by pnthach95** [comment]
Version 4.7.2 fixed this issue. Now you can install `@types/react-native` latest version.

**Comment by pnthach95** [comment]
Errors reappear with `react-native-paper 4.10.0` and `@types/react-native 0.66.1`. #2953 didn't fix this issue.

In `TextInput`, there is `Property 'autoCompleteType' is missing in type` error, it is required but `unknown` type

![image](https://user-images.githubusercontent.com/31266357/140056271-c1acc5ca-33ba-4d4d-8b58-63e9903edc61.png)

**Comment by frenberg** [comment]
downgrading "@types/react-native": "0.65.15",  from 0.66.0 worked for me which is also latest version according to vscode when I hover the version in package.json.

**Comment by lukewalczak** [comment]
Could you please try the version `4.10.1`?

`autoCompleteType` was replaced in favour of `autoComplete` in 0.66

**Comment by frenberg** [comment]
Ahh, I was still on 4.9.2 🤦 4.10.1 works great with 0.66 👍  Thanks 💯

**Comment by pnthach95** [comment]
Resolved, `react-native-paper 4.10.1` and `@types/react-native 0.66.4`.
