### ISSUE TITLE
Error: Unable to resolve module `./Adornment/Icon` from `node_modules/react-native-paper/src/components/TextInput/TextInput.tsx`:

### ISSUE THREAD

**Issue by limkimsan** [callstack/react-native-paper#2447]
### Current behaviour

I got error: Error: Unable to resolve module `./Adornment/Icon` from `node_modules/react-native-paper/src/components/TextInput/TextInput.tsx` after I upgrade to react-native-paper 4.4.1. It was working fine on 4.2.0, but I try to upgrade the version in order to fix "useNativeDriver" warning. 

### What have you tried

I try to upgrade react-native-paper to 4.5.0 and it still shows the same error.

### Your Environment

react-native version: 0.63.2
react-native-vector-icons: 7.1.0
react-native-paper: 4.4.1

**Comment by maltoze** [comment]
Try `npm start -- --reset-cache`

**Comment by Trancever** [comment]
Pls reinstall node_modules and reset metro cache with `npm start -- --reset-cache` or `yarn start --reset-cache`.

**Comment by limkimsan** [comment]
It is working now. I need to restart my computer, reinstall node_modules, and use `npm start --reset-cache`. Thank @maltoze and @Trancever .
