### ISSUE TITLE
Datatable problem icon version web

### ISSUE THREAD

**Issue by Angelk90** [callstack/react-native-paper#2453]
### Current behaviour

Hi @Trancever , @unikvozm , @haxonadora : 

As you can see from the image using the web version on snack.expo, the icons in the table are not seen in the correct way it would be possible to have a look at them.

### Code sample

Link: [expo](https://snack.expo.io/ZKUECtyF7)

### Screenshots (if applicable)

<img width="332" alt="Schermata 2020-12-20 alle 10 06 38" src="https://user-images.githubusercontent.com/20476002/102709555-37a06a00-42ac-11eb-98b3-8fd468034e6f.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | web
| react-native          | 0.63.3
| react-native-paper    | 4.5.0
| node                  | 12.18.3
| npm or yarn           | yarn
| react-native-vector-icons                  | 7.1.0
| expo sdk              | 40

**Comment by Angelk90** [comment]
The problem doesn't seem to be just the web.
But kind of all the icons.

<img width="654" alt="Schermata 2020-12-20 alle 10 28 38" src="https://user-images.githubusercontent.com/20476002/102709823-26f0f380-42ae-11eb-9dae-557ef32f526c.png">

**Comment by Angelk90** [comment]
@Trancever , @unikvozm , @haxonadora : Are there any news?

**Comment by Angelk90** [comment]
@Trancever , @unikvozm , @haxonadora : Are there any news?

**Comment by raajnadar** [comment]
Make sure you are following the proper setup process of react native vector icons. https://github.com/oblador/react-native-vector-icons#installation
