### ISSUE TITLE
Storybook with react-native-paper problem assets

### ISSUE THREAD

**Issue by Angelk90** [callstack/react-native-paper#2454]
### Current behaviour

Hi @Trancever , @unikvozm , @haxonadora : 

I wanted to use `Storybook` with` react-native-paper` but I'm having the following problem.

The component I am using is the `table`, the problem seems to be due to the `assets` of the `pagination` arrow.

As you can see below the errors the component is `rendered`.

Can you give me a hand?

```bash
ERROR in ./node_modules/react-native-paper/lib/module/assets/back-chevron.png 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/react-native-paper/lib/module/components/Appbar/AppbarBackIcon.js 17:10-50
 @ ./node_modules/react-native-paper/lib/module/components/Appbar/AppbarElements.js
 @ ./node_modules/react-native-paper/lib/module/components/Appbar/Appbar.js
 @ ./node_modules/react-native-paper/lib/module/index.js
 @ ./src/components/TestComponent10/TestComponent1.stories.js
 @ ./src/components sync ^\.\/(?:(?:|\/|(?:(?:(?!(?:|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:\[tj\]|[tj])s)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

### Screenshots (if applicable)

<img width="1224" alt="Schermata 2020-12-20 alle 13 01 22" src="https://user-images.githubusercontent.com/20476002/102713332-ddad9d80-42c7-11eb-9c98-cf91026bd749.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | web
| react-native          | 0.63.3
| react-native-paper    | 4.5.0
| node                  | 12.18.3
| npm or yarn           | yarn
| react-native-vector-icons                  | 7.1.0
| expo sdk              | 40

**Comment by Angelk90** [comment]
@Trancever , @unikvozm , @haxonadora: is there any news?
Could you give an example of a storybook, I'm following the guide but I'm not getting it to work.

**Comment by robertkibet** [comment]
anyone found a fix for this? I am curios to get a solution too 🤔

**Comment by conor909** [comment]
Would it be because the components you're importing into storybook are not wrapped in the `react-native-paper` `Provider`?

**Comment by Gab1988** [comment]
This is still an issue guys, storybook works okay with react-native-paper when run locally but when I'm trying to build it with build-storybook it fails with the below message

ERR! => Failed to build the preview
ERR! ./node_modules/react-native-paper/lib/module/assets/back-chevron.png

Below my web pack config
```
const { resolve } = require("path");
const { withUnimodules } = require("@expo/webpack-config/addons");

module.exports = ({ config }) => {
  let _config = withUnimodules(config, {
    projectRoot: resolve(__dirname, "../"),
  });
  _config = {
    ..._config,
    module: {
      ..._config.module,
      rules: [
        ..._config.module.rules,
        {
          test: /\.js$/,
          exclude: /node_modules[/\\](?!react-native-paper)/,
          use: {
            loader: "babel-loader",
            options: {
              // Disable reading babel configuration
              babelrc: false,
              configFile: false,

              // The configuration for compilation
              presets: [
                ["@babel/preset-env", { useBuiltIns: "usage" }],
                "@babel/preset-react",
                "@babel/preset-flow",
                "@babel/preset-typescript",
              ],
              plugins: [
                "@babel/plugin-proposal-class-properties",
                "@babel/plugin-proposal-object-rest-spread",
              ],
            },
          },
        },
      ],
    },
  };
  return config;
};

```

**Comment by serybva** [comment]
You probably need to install and configure file-loader for webpack as explained [https://callstack.github.io/react-native-paper/using-on-the-web.html#3-configure-file-loader](here)
