### ISSUE TITLE
ToggleButton label

### ISSUE THREAD

**Issue by yamila-fraiman** [callstack/react-native-paper#2465]
**Is your feature request related to a problem? Please describe.**
I want to display toggle buttons but icon is not enough to explain what the option means.

react-native: 0.63.4
react-native-paper: 4.7.1
react-native-vector-icons: 8.0.0

**Describe the solution you'd like**
Add a label property to ToggleButton so it displays a text below the icon.

**Describe alternatives you've considered**
Create a custom component but when wrapping into a view the border disappears.

[
![image](https://user-images.githubusercontent.com/71793326/103136313-1b327200-469e-11eb-8385-96ee3bf99de7.png)
](url)

**Comment by JuSenpai** [comment]
+1, I don't know why this wouldn't be an option

**Comment by seba9999** [comment]
+1 and would suggest to delete the required icon in order to just add some text just as Material-UI possibilities in React JS :

<iframe src="https://codesandbox.io/embed/material-demo-j2wp0?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Material demo"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

**Comment by GautamiDhokte** [comment]
Pass icon as function
`<ToggleButton
      icon={()=><View><Text style={{color:'blue'}}>blue</Text></View>}
      value="blue"
      status={status}
      onPress={onButtonToggle}
    />`
    
    example:
  [Snack](https://snack.expo.io/@gautami123/toggle)

**Comment by gluons** [comment]
@github-actions Don't close feature request, please.

![](https://media1.giphy.com/media/vyTnNTrs3wqQ0UIvwE/giphy.gif)

**Comment by MartijnGevaert** [comment]
This probably shouldn't be stale as that's not really usefull to keep track of feature requests, right?

**Comment by SamuelLeclerc33** [comment]
Bump

**Comment by Wenxchn** [comment]
+1

**Comment by vadim-isakov** [comment]
Perhaps SegmentedButtons component will suit you.
https://github.com/callstack/react-native-paper/blob/813cdd47a90ee3bb693c6ec143af73092cd3edae/example/src/Examples/SegmentedButtons/SegmentedButtonDefault.tsx
