### ISSUE TITLE
Custom icon size for Chip components

### ISSUE THREAD

**Issue by BlackWild** [callstack/react-native-paper#2471]
I am trying to design a responsive UI, where font and icon sizes are scaled based on the screen's height; however, the icon of the `Chip` component is currently fixed on `18` making it unresponsive.

I think it would be good to add an option for custom icon size via `Chip`'s props or scale the icon size based on the `fontSize` of the currently available `textStyle` property (which is currently kind of the case for the `Button` component).

```json
{
  "react-native": "0.63.4",
  "react-native-paper": "4.4.0",
  "react-native-vector-icons": "7.1.0",
}
```

**Comment by BlackWild** [comment]
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes dear bot. I checked the latest source code on GitHub and the `Chip` component is still using fixed size for its icon!

**Comment by contactsimonwilson** [comment]
@BlackWild the icon prop supports a custom render function that will allow you to do this
`          icon={p => <Icon {...p} name="check" size={yourCustomSizeCalcFunc(p.size)} />}
`

**Comment by BlackWild** [comment]
@contactsimonwilson Thanks!
I get it now! The `IconSource` type can also be a react component that renders an `Icon`. Am I right? I am wondering how I didn't see this in the documentation... maybe it is a good idea to dedicate a page in the documentation to this (to explain the `IconSource` type).
Anyway, My problem is resolved.

**Comment by contactsimonwilson** [comment]
@BlackWild yup - I also didn't notice that in the docs at first.

@Trancever this issue can be closed =)
