### ISSUE TITLE
onPress for Avatar

### ISSUE THREAD

**Issue by b-tiwari** [callstack/react-native-paper#2472]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
It will be nice if the Avatar component can provide a `onPress` prop, will save me from wrapping it around `TouchableOpacitiy ` or something

**Describe alternatives you've considered**
none

**Additional context**
The versions I have presently: 
"react-native": "0.63.4",
"react-native-paper": "^4.5.0",
"react-native-vector-icons": "^7.1.0"

**Comment by lukewalczak** [comment]
Hello @b-tiwari, actually wrapping within touchable is preferred solution, hence closing the issue.
