### ISSUE TITLE
TextInput.Afflix is not displaying in TextInput left or right Prop

### ISSUE THREAD

**Issue by YajanaRao** [callstack/react-native-paper#2477]
### Current behaviour

TextInput.Afflix is not displaying in TextInput left or right Prop

### Expected behaviour

TextInput.Affix should be displayed or an error is expected.

### Code sample

https://snack.expo.io/@yajana/forlorn-cheese

### What have you tried

```
 <TextInput
      label={'Mobile number'}
      value={mobile}
      maxLength={10}
      mode="outlined"
      keyboardType={'number-pad'}
      onChangeText={(text) => setMobile(text)}
      right={<TextInput.Affix text="+91" />}
  />
```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          | 63
| react-native-paper    |  4.5.0
| node                  |
| npm or yarn           |
| expo sdk              | 40

**Comment by YajanaRao** [comment]
Issue is present in 4.5.0 as well.

**Comment by PreetS123** [comment]
I am facing the same issue in react-native-paper - 5.13.1 
`<TextInput
                  mode="outlined"
                  label="Pulse Rate"
                  outlineStyle={{
                    borderWidth: 1,
                    borderColor: Colors.activeFieldColor,
                    borderRadius: 8,
                  }}
                  style={{ backgroundColor: Colors.white, width: '70%', height: 46 }}
                  activeOutlineColor={Colors.activeFieldColor}
                  textColor={Colors.activeFieldColor}
                  selectionColor={Colors.textColorLightOrange}
                  keyboardType="numeric"
                 right={<TextInput.Affix text="/100" textStyle={{color:'red'}} />}
                />`
the right element is not displayed inside the TextInput
