### ISSUE TITLE
Anormal behaviour on all react-native-paper component style 

### ISSUE THREAD

**Issue by emmanuel-D** [callstack/react-native-paper#2480]
I am using **react-native-paper ^4.5.0** with **expo ^39.0.0**.

- react-native : 0.63
- react-native-paper : 4.5.0
- @expo/vector-icons: 10.0.0,
- react-native-vector-icons :  not used

My <**Searchbar**>, <**Surface**>, <**Appbar.Heade**r> components have all a **black background color** when it is installed on an iOS device (iPhone 6 and iPad running on iOS 14).

However when developing on a Simulator in the Expo Client App, all the **background colors** are white as expected.

The below screenshots show an example of what I meaning.

-> Expected behaviour
![photo_2021-01-03_21-35-43](https://user-images.githubusercontent.com/37305687/103488320-d4661a00-4e0b-11eb-81f3-403fd88f09f0.jpg)

-> Current behaviour in production
![photo_2021-01-03_21-35-47](https://user-images.githubusercontent.com/37305687/103488322-d4feb080-4e0b-11eb-95a1-b6f2c87885e2.jpg)

I would like the have the normal white background color on all my components.

**Comment by Trancever** [comment]
@emmanuel-D Do you use dark mode on your device? We automatically detect it and use light/dark colors if you don't explicitly pass theme to the Provider.

To fix the issue you might want to adjust all your components to work with both light and dark theme or just pass our default theme to the Provider so we won't automatically adjust the colors.

**Comment by emmanuel-D** [comment]
@Trancever I am not using dark mode.
On android devices and simulators, I don’t have this issue.

Can you provide an example how I pass the theme ?

**Comment by Trancever** [comment]
@emmanuel-D https://callstack.github.io/react-native-paper/theming.html

Please follow our guide. You need to import the DefaultTheme and pass it as a theme prop to the Provider.
