### ISSUE TITLE
Typescript error: No overload matches this call.

### ISSUE THREAD

**Issue by rahadkc** [callstack/react-native-paper#2482]
I just init a expo typescript project. Then add 'react-native-paper' in my project.
When try to use Button component it gives me this typescript error. 
Do you have any idea why getting error?

Error
```
No overload matches this call.
  Overload 1 of 2, '(props: Pick<Props, "ref" | "style" | "children" | "hitSlop" | "onLayout" | "pointerEvents" | "removeClippedSubviews" | "testID" | "nativeID" | "collapsable" | "needsOffscreenAlphaCompositing" | ... 57 more ... | "contentStyle"> & { ...; }, context?: any): ReactElement<...> | ... 1 more ... | null', gave the following error.
    Type '{ children: string; mode: "outlined"; onPress: () => void; }' is missing the following properties from type
```

Code -
```javascript
<PaperProvider>
  <View >
      <Button mode="outlined" onPress={() => {}}>
         press me
      </Button>
   </View>
</PaperProvider>
```

package.json
```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-paper": "^4.5.0",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-dom": "~16.9.8",
    "@types/react-native": "~0.63.2",
    "typescript": "~4.0.0"
  },
  "private": true
}

```

**Comment by rahadkc** [comment]
Hi, according to 'react-native-paper' documentation

`If you're on a vanilla React Native project, you also need to install and link react-native-vector-icons.`
`If you use Expo, you don't need to install vector icons.`

Since the project created by `expo init`  it uses Expo SDK 40. Which include
 - `react-native: 0.63`

**Comment by rahadkc** [comment]
Hi got the solution. When initializing project using `expo init` it automatically added types for 
- `@types/react-native@0.63.2`

After upgrading the react-native type version to 
- `@types/react-native@0.63.40`

It is working fine.

**Comment by byCedric** [comment]
For more context, see the linked issue:

> ... this looks like an issue with either `@types/react-native` or `react-native-paper`. Right now, the templates require `~0.63.2`, which includes version `0.63.40`. The issue here is that the types starting from `~0.63.41` contains changes, made somewhere between 14 and 16 December (looking at NPM version timestamps), that breaks the button component. ...

Hope this helps!

**Comment by EthanStandel** [comment]
This issue is back for me with the most recent version of @types/react-native (@0.63.45 for @latest at time of writing this)

**Comment by oussamabouchareb** [comment]
this issue is also present for me with many attempts over the last few days trying to figure out which ```@types/react-native``` version is causing this leading to nowhere

creating a new TS project with expo init and following RN paper instructions for installing the library should recreate the issue.

**Comment by lorstenoplo** [comment]
I just got into their `.d.ts` file and changed ( actually removed most of it ) to `React.FC<Props>`.
If you use functional components to write code then you may like to follow my code.

I guess they should update their type definitions

**Comment by oussamabouchareb** [comment]
I looked a little bit into the code from this library and I think the outdated accessibility props are what's causing it but I'm not 100% sure, it seems that they might need to update the props on some components that have these accessibility props.

**Comment by EnzoH8321** [comment]
Issue is back for me as well. Currently on  @types/react-native 0.63.46.

**Comment by leoafarias** [comment]
Yes, same here. This seems very annoying due to our tooling failing

**Comment by ImAbhishekTomar** [comment]
same for me...

```
<Button
              mode="outlined"
              onPress={() => {
                setCounter(counter + 1);
                observableAppStore.setTracker(counter);
              }}>
              Press me
            </Button>

```
**ERROR**
No overload matches this call.
  Overload 1 of 2, '(props: Pick<Props, "ref" | "style" | "children" | "hitSlop" | "onLayout" | "pointerEvents" | "removeClippedSubviews" | "testID" | "nativeID" | "collapsable" | "needsOffscreenAlphaCompositing" | ... 57 more ... | "contentStyle"> & { ...; }, context?: any): ReactElement<...> | ... 1 more ... | null', gave the following error.
    Type '{ children: string; mode: "outlined"; onPress: () => void; }' is missing the following properties from type 'Pick<Props, "ref" | "style" | "children" | "hitSlop" | "onLayout" | "pointerEvents" | "removeClippedSubviews" | "testID" | "nativeID" | "collapsable" | "needsOffscreenAlphaCompositing" | ... 57 more ... | "contentStyle">': accessibilityComponentType, accessibilityTraits
  Overload 2 of 2, '(props: PropsWithChildren<Pick<Props, "ref" | "style" | "children" | "hitSlop" | "onLayout" | "pointerEvents" | "removeClippedSubviews" | "testID" | "nativeID" | "collapsable" | "needsOffscreenAlphaCompositing" | ... 57 more ... | "contentStyle"> & { ...; }>, context?: any): ReactElement<...> | ... 1 more ... | null', gave the following error.
    Type '{ children: string; mode: "outlined"; onPress: () => void; }' is missing the following pr

**PACKEGE**

"dependencies": {
    "@babel/plugin-proposal-decorators": "^7.12.12",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "mobx": "^6.0.5",
    "mobx-react": "^7.0.6",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-paper": "^4.7.1",
    "react-native-vector-icons": "^8.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "@types/color": "^3.0.1",
    "@types/jest": "^25.2.3",
    "@types/react-native": "^0.63.46",
    "@types/react-test-renderer": "^16.9.2",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1",
    "typescript": "^3.8.3"
  },

**Comment by sergeymild** [comment]
the same for me, on every react-native-paper components i have got that errors

**Comment by chybisov** [comment]
I have this error on Button component also. Could somebody look on this please? @satya164 @Trancever

**Comment by leoafarias** [comment]
It seems this PR once closed will fix problem #2522

**Comment by EnzoH8321** [comment]
> It seems this PR once closed will fix problem #2522

Currently on "@types/react-native": "0.63.47" and the issue still persists.

**Comment by saurabhnemade** [comment]
> > It seems this PR once closed will fix problem #2522
> 
> Currently on "@types/react-native": "0.63.47" and the issue still persists.

Working configuration right now:

```
    "react-native": "~0.63.4",
    "react-native-paper": "^4.7.1",
    "@types/react-native": "^0.62.0",
```

There is one easy way to know what should be these version. 

Just pick version of `@types/react-native` from https://github.com/callstack/react-native-paper/blob/main/package.json

**Comment by codeSantiago** [comment]
> > > It seems this PR once closed will fix problem #2522
> > 
> > 
> > Currently on "@types/react-native": "0.63.47" and the issue still persists.
> 
> Working configuration right now:
> 
> ```
>     "react-native": "~0.63.4",
>     "react-native-paper": "^4.7.1",
>     "@types/react-native": "^0.62.0",
> ```
> 
> There is one easy way to know what should be these versions.
> 
> Just pick version of `@types/react-native` from https://github.com/callstack/react-native-paper/blob/main/package.json

I tried version 0.62.0 of `@types/react-native` and it didn't work, i installed 0.63.0 and the errors disappeared

**Comment by saurabhnemade** [comment]
> > > > It seems this PR once closed will fix problem #2522
> > > 
> > > 
> > > Currently on "@types/react-native": "0.63.47" and the issue still persists.
> > 
> > 
> > Working configuration right now:
> > ```
> >     "react-native": "~0.63.4",
> >     "react-native-paper": "^4.7.1",
> >     "@types/react-native": "^0.62.0",
> > ```
> > 
> > 
> > There is one easy way to know what should be these versions.
> > Just pick version of `@types/react-native` from https://github.com/callstack/react-native-paper/blob/main/package.json
> 
> I tried version 0.62.0 of `@types/react-native` and it didn't work, i installed 0.63.0 and the errors disappeared

Interesting. Do you recall if you have tried just `0.62.0` or `^0.62.0`?  Because `^0.62.0` should have bring the latest minor version as per https://michaelsoolee.com/npm-package-tilde-caret/ . Or it could be fetching 0.63.4 which is latest version.

**Comment by EnzoH8321** [comment]
I followed @codeSantiago 's tips and it worked. `@types/react-native: 0.63.0` seems to have removed the issues for me.

**Comment by Alarid** [comment]
I was facing the same issue. I did:
```
npm i react-native@latest
npm i react-native-paper@latest
npm i --save-dev @types/react-native@latest
```
Worked like a charm !

**Comment by EthanStandel** [comment]
> I was facing the same issue. I did:
> 
> ```
> npm i react-native@latest
> npm i react-native-paper@latest
> npm i --save-dev @types/react-native@latest
> ```
> 
> Worked like a charm !

If we can just @latest all the associated packages then I would think this can be closed.

**Comment by dalcib** [comment]
I am using 
```
npm i react-native-paper@latest (4.7.2)
npm i --save-dev @types/react-native@latest (0.63.50)
```
and I keep having the same issue for several components:
- FAB
- ActivityIndicator
- Appbar...
- List...
- Avatar...
- Switch
- Badge
- Banner
- Card...
- TouchableRipple
- Chip
- DataTable
- TextInput

**Comment by AhmadHamze** [comment]
I did:
`npm i react-native@latest
npm i react-native-paper@latest
npm i --save-dev @types/react-native@latest`
and it didn't work

**Comment by rishabhyadavv** [comment]
@AhmadHamze @EthanStandel  were you able to fix that. I am facing this issue with below versions.
"@types/react-native": "^0.64.6",
"react-native": "^0.64.1",
"react-native-paper": "^4.8.1",

Thanks

**Comment by AhmadHamze** [comment]
@rishabhyadavv I didn't fix it, and I stopped working on the project a long time ago, sorry.

**Comment by ImAbhishekTomar** [comment]
yes; this is resolved for me after downgrading package version.

**Comment by butterfly-valley** [comment]
After upgrading EXPO to SDK 43 the issue has reappeared even if downgrading @types/react-native to 0.62.0
"react-native": "0.64.2"

**Comment by gloredo** [comment]
Working with Expo SDK 43 (react-native 0.64.3 - @types/react-native 0.64.19) and react-native-paper 4.9.2

**Comment by Neosoulink** [comment]
I'm currently facing this issue when trying to import the **Text** component😕

Error : 
```
No overload matches this call.
  Overload 1 of 2, '(props: Pick<TextProps & { style?: StyleProp<TextStyle>; theme: Theme; } & RefAttributes<{}>, "testID" | "ref" | "children" | ... 37 more ... | "onPressOut"> & { ...; }, context?: any): ReactElement<...> | ... 1 more ... | null', gave the following error.
    Type '{ children: string; style: { fontSize: number; marginBottom: number; }; }' is missing the following properties from type 'Pick<TextProps & { style?: StyleProp<TextStyle>; theme: Theme; } & RefAttributes<{}>, "testID" | "ref" | "children" | "onLayout" | ... 36 more ... | "onPressOut">': onPressIn, onPressOut
  Overload 2 of 2, '(props: PropsWithChildren<Pick<TextProps & { style?: StyleProp<TextStyle>; theme: Theme; } & RefAttributes<{}>, "testID" | "ref" | "children" | ... 37 more ... | "onPressOut"> & { ...; }>, context?: any): ReactElement<...> | ... 1 more ... | null', gave the following error.
    Type '{ children: string; style: { fontSize: number; marginBottom: number; }; }' is missing the following properties from type 'Pick<TextProps & { style?: StyleProp<TextStyle>; theme: Theme; } & RefAttributes<{}>, "testID" | "ref" | "children" | "onLayout" | ... 36 more ... | "onPressOut">': onPressIn, onPressOutts(2769)
```
    
 Package.json:
  
  ```json
    "dependencies": {
		"@react-navigation/native": "^6.0.6",
		"@react-navigation/native-stack": "^6.2.5",
		"@reduxjs/toolkit": "^1.7.1",
		"expo": "~44.0.0",
		"expo-status-bar": "~1.2.0",
		"react": "17.0.1",
		"react-dom": "17.0.1",
		"react-native": "0.64.3",
		"react-native-paper": "^4.11.2",
		"react-native-safe-area-context": "3.3.2",
		"react-native-screens": "~3.10.1",
		"react-native-web": "0.17.1",
		"react-redux": "^7.2.6"
	},
	"devDependencies": {
		"@babel/core": "^7.12.9",
		"@types/react": "~17.0.21",
		"@types/react-native": "~0.64.12",
		"babel-preset-expo": "^9.0.2",
		"ts-node": "^10.4.0",
		"typescript": "^4.5.4"
	},

**Comment by kukuricapolna** [comment]
I just ran this command and everything works fine: `yarn add -D @types/react-native` and everything works well

**Comment by lukehatcher** [comment]
I was able to fix this by only upgrading my `@types/react-native` to the latest version (0.66.15 at time of writing this).

My relevant dependencies prior to upgrading were as follows:

```
"@types/react-native": "^0.66.15",
"react-native": "0.63.4",
"react-native-paper": "^4.11.2",
```

**Comment by yannseree** [comment]
To all strugling with react native paper lint errors 
Simply search in the package.json of react native paper : https://github.com/callstack/react-native-paper/blob/main/package.json, (change the tag with the version of react native user you use)
And change the react-native and @types/react-native version to the same as in the package.json of react native paper

**Comment by oscar-gallog** [comment]
Why they're so many issues about this? I'm still having the same issue with
```
"expo": "^44.0.6",
"react-native-paper": "^4.12.0",
"react-native": "0.64.3",
"@types/react-native": "~0.64.12",
```

**Comment by foxsnow38** [comment]
Still, the problem have ...

![image](https://user-images.githubusercontent.com/31081148/190856662-dbe747e7-beeb-4baf-9d61-c127901909f6.png)

![image](https://user-images.githubusercontent.com/31081148/190856645-b20be848-5ff4-4d9a-b47f-82459501b89f.png)

**Comment by mowais-ac** [comment]
any workaround for this issue?

**Comment by macsj200** [comment]
I'm running into this issue as well

```
    "@types/react-native": "~0.70.8",
    "react-native-paper": "^5.1.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
```

I'm on Expo as well, SDK version 45
`"expo": "^45.0.0"`

Previously, I was able to resolve a similar issue by bumping `@types/react-native` to `~0.70.6`, but now I'm running into an issue with the `ref` prop.

**Comment by ByomkeshVai** [comment]
I have just do a small task, 
on react-apexchart.d-ts , just comment out the line 

  // export interface Props {
  //   type?:
  //     | "line"
  //     | "area"
  //     | "bar"
  //     | "pie"
  //     | "donut"
  //     | "radialBar"
  //     | "scatter"
  //     | "bubble"
  //     | "heatmap"
  //     | "candlestick"
  //     | "boxPlot"
  //     | "radar"
  //     | "polarArea"
  //     | "rangeBar"
  //     | "rangeArea"
  //     | "treemap";
  //   series?: ApexOptions["series"];
  //   width?: string | number;
  //   height?: string | number;
  //   options?: ApexOptions;
  //   [key: string]: any;
  // }
  
![tricky](https://github.com/callstack/react-native-paper/assets/65497090/31b9cd72-7c6b-4661-8afd-5c119efe9a6a)

bad practice :P but i can't build my project without it.

**Comment by ant100** [comment]
I'm also running into this issue, why has it been closed? what was the fix?

**Comment by yannseree** [comment]
Its very easy to fix, already tell how to fix : 
https://github.com/callstack/react-native-paper/issues/2482#issuecomment-1056309355
