### ISSUE TITLE
DataTable.Row onPress not firing in web

### ISSUE THREAD

**Issue by zaheradev** [callstack/react-native-paper#2488]
### Current behaviour

on pressing a row a ripple shows but the event handler isn't called in react-native web but it is on ios/android (happens on 4.5.0 and 4.6.0)

### Expected behaviour

onPress should be called when a row is pressed

### Code sample

https://snack.expo.io/@bmabsout/datatablerow

### What have you tried

I got an error generated by react-native-gesture-handler on web when trying to use a TouchableOpacity instead which may be related (upgrading it to  version 1.9.0 fixed the issue)

### Your Environment

| software              | version
| --------------------- | -------
| react-native-paper    | 4.5.0, 4.6.0
| expo sdk              | 40.0.0

**Comment by Zanluca** [comment]
Someone find a solution?
