### ISSUE TITLE
react-native-paper v4.5.0 to 4.6.0 build fails with error Unable to resolve module react-native-safe-area-view

### ISSUE THREAD

**Issue by cultulhul** [callstack/react-native-paper#2489]
### Current behaviour
When react-native run-android command is run app wont build it gives error cant find module react-native-safe-area-view

### Expected behaviour
App builds and starts when react-native  run-android command is run

error: Error: Unable to resolve module `react-native-safe-area-view` from `node_modules\react-native-paper\src\components\BottomNavigation.tsx`: react-native-safe-area-view could not be found within the project.

### What have you tried
Downgrading to v4.4.1 resolves the issue

### Your Environment

| software              | version
| --------------------- | -------
| react-native          | 0.63.3
| react-native-paper    | 4.6.0

**Comment by 99uno** [comment]
[https://github.com/callstack/react-native-paper/issues/2438](url)

Try
npm start -- --reset-cache

**Comment by cultulhul** [comment]
Thanks it worked
