### ISSUE TITLE
How to add several icons to one of the left or right props of TextIput?

### ISSUE THREAD

**Issue by parice02** [callstack/react-native-paper#2492]
Hello.
I would like to add several icons to one of the left or right props of TextIput but nothing is displayed. Is there a way to do this?

react-native version 0.63
react-native-paper version 4.4.1
react-native-vector-icons version 7.1.0

Thank you.

**Comment by system32uwu** [comment]
You can make a resource out of the icons that you want to display, finally having your TextInput icon property like this:

icon={require("path/to/source.jpg")}

Being source.jpg a handcrafted image of course, you can't pass an array of icons, it only expects a single value.

**Comment by Trancever** [comment]
@parice02 We support only one icon per side.

**Comment by badalsaibo** [comment]
Use the `render` prop and customize as your need.

```js
import { TextInput } from 'react-native-paper'
import styled from 'styled-components/native'

const InputContainer = styled.View`
  flex-direction: row;
`
const Input = styled.TextInput`
  flex: 1;
`
const AdornmentContainer = styled.View`
  align-items: center;
  justify-content: center;
  padding: 0 10px;
`

const CustomInput = ({ left, right, ...props }) => (
  <TextInput
    { ...props }
    render={ (inputProps) => (
      <InputContainer>
        {left && (
          <AdornmentContainer>
            {left}
          </AdornmentContainer>
        )}
        <Input { ...inputProps } />
        {right && (
          <AdornmentContainer>
            {right}
          </AdornmentContainer>
        )}
      </InputContainer>
    ) }
   />
)
```

https://github.com/callstack/react-native-paper/issues/2305#issuecomment-778847694
