### ISSUE TITLE
The theme is changed to Dark theme when i minimize the app and open it again

### ISSUE THREAD

**Issue by denerFernandes** [callstack/react-native-paper#2496]
### Current behaviour

If I minimize the app and open it again it changes the theme to Dark mode, even though I haven't implemented dark mode support yet.

### Expected behaviour

The colors should continue as they are.

### Code sample

I use the example: 

```javascript
import * as React from 'react';
import { DefaultTheme, Provider as PaperProvider } from 'react-native-paper';
import App from './src/App';

const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: 'tomato',
    accent: 'yellow',
  },
};

export default function Main() {
  return (
    <PaperProvider theme={theme}>
      <App />
    </PaperProvider>
  );
}
```

### Screenshots (if applicable)
![Gif error](https://i.ibb.co/6HN3vh3/ezgif-com-gif-maker.gif "Gif Error")

https://i.ibb.co/6HN3vh3/ezgif-com-gif-maker.gif

### What have you tried

I tried update RN and RN Paper and tried to change theme.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | IOS 14
| react-native          | 0.63.3
| react-native-paper    | 4.5.0
| node                  | 14.8.0
| npm           | 6.14.9
| rn-cli              | 4.13.1
| react-native-vector-icons   | 7.1.0

**Comment by danielbenedykt** [comment]
+1

I was able to reproduce this with versions:
react-native 0.63.3
react-native-paper 4.7.1

If I don't set any theme and then minimize and show again, it will set to dark theme(black)
if I set the default theme,  this won't happen

**Comment by denerFernandes** [comment]
In my case I have the default theme defined, but I still have the problem.

In Provider.tsx sometimes the value of the props is not enough.

`if (providedTheme) {
      return providedTheme;
    } else {
      const theme = (colorScheme === 'dark'
        ? DarkTheme
        : DefaultTheme) as ReactNativePaper.Theme;`

**Comment by triptec** [comment]
Did you guys manage to fix it?

**Comment by lukewalczak** [comment]
Please check the discussion in the issue: https://github.com/callstack/react-native-paper/issues/2639
