### ISSUE TITLE
Memory Leak in Avatar.Image

### ISSUE THREAD

**Issue by buffaloDeveloper** [callstack/react-native-paper#2506]
Using the Avatar component in a React Native FlatList.  The Avatar image is loaded from a remote URI.

`<Avatar.Image {...props} size={36} source={{uri: uri}} />`

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Image (created by Avatar.Image)
    in div (created by View)
    in View (created by Avatar.Image)
    in Avatar.Image (created by Context.Consumer)
    in ThemedComponent (created by withTheme(Avatar.Image))
```

**Comment by mariohmol** [comment]
Isn't that dup to #2507?

 "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
"react-native-vector-icons": "^8.0.0",
"expo": "^40.0.0",
"react-native-paper": "^4.7.0",
