### ISSUE TITLE
react-native-paper v4.6.0 to v4.7.0 build fails with error Unable to resolve module `./CheckboxElements`

### ISSUE THREAD

**Issue by hadihassan09** [callstack/react-native-paper#2510]
### Current behavior

After upgrading to v4.7.0 from v4.6.0 the app build fails with the error unable to resolve module CheckboxElements.

Error:
`
error: Error: Unable to resolve module ./CheckboxElements from 
node_modules\react-native-paper\src\components\Checkbox\Checkbox.tsx:
`

### Expected behavior

App to run successfully.

### What have you tried

Downgrading to v4.6.0 resolves the issue

### Your Environment
| software              | version
| --------------------- | -------
| ios or android        |  android
| react-native          | 0.63.4
| react-native-paper    | 4.7.0
| node                  | v14.10.1
| npm or yarn | npm
| npm           | 6.14..8
| expo sdk              | 
| react-native-vector-icons | 7.1.0

> note: I'm using react-native CLI and not EXPO.

**Comment by maltoze** [comment]
See #2447

**Comment by hadihassan09** [comment]
> See #2447

`npm start -- --reset-cache` solved the problem for me.
