### ISSUE TITLE
RadioButtom.Group / RadioButtom.Item provoking wasted renders (More components affected)

### ISSUE THREAD

**Issue by lHersey** [callstack/react-native-paper#2511]
### Current behaviour

When using `RadioBurrom.Group` / `RadioButtom.Item` is provoking some wasted renders because of some props with different ref but same value

### Expected behaviour

Render the component only when is needed

### Code sample

```js
const VehicleTypeSelector: FC<Props> = props => {
  const { onValueChange, currentValue } = props;

  const vehicleTypes = useVehicleTypesSelector();
  const theme = useTheme();

  return (
    <RadioButton.Group onValueChange={onValueChange} value={currentValue.toString()}>
      {vehicleTypes.map(vehicleType => (
        <RadioButton.Item
          color={theme.SECONDARY_COLOR_LIGHT_2}
          key={vehicleType.id}
          value={vehicleType.id.toString()}
          label={vehicleType.description}
        />
      ))}
    </RadioButton.Group>
  );
};

export default React.memo(VehicleTypeSelector);

```

wdyr  output: 

```

Object {
  "Icon": [Function Icon],
} Re-rendered because of props changes:

props.style

different objects that are equal by value. (more info at http://bit.ly/wdyr02)

Object {
  "prev style": Array [
    Object {
      "lineHeight": 24,
      "transform": Array [
        Object {
          "scaleX": 1,
        },
      ],
    },
    Object {
      "backgroundColor": "transparent",
    },
  ],
} !== Object {
  "next style": Array [
    Object {
      "lineHeight": 24,
      "transform": Array [
        Object {
          "scaleX": 1,
        },
      ],
    },
    Object {
      "backgroundColor": "transparent",
    },
  ],
}
Object {
  "For detailed diff, right click the following fn, save as global, and run: ": [Function diffFn],
}
```

### Screenshots (if applicable)

No applicable

### What have you tried

I used `patch-package` to memo the styles object and it worked

I changed:
```js
export default defaultIcon;
```
to:
```js
export default React.memo(defaultIcon);
```

https://github.com/callstack/react-native-paper/blob/d34f030871ff2a2688b9b54e06e5b3ed85b56a7a/src/components/MaterialCommunityIcon.tsx#L79

Since this is happening in `MaterialCommunityIcon` I think more components are affected

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |both
| react-native          |https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz
| react-native-paper    | v4.7.0
| node                  |v12.x
| npm or yarn           |yarn
| expo sdk              |40

Cloud not make work the snack with react-native-paper and wdyr (why did you render)

**Comment by SomnathKadam** [comment]
same issue occurred, can any one has solution?
