### ISSUE TITLE
TextInput center label

### ISSUE THREAD

**Issue by tomto1** [callstack/react-native-paper#2518]
Is it possible to center label of flat TextInput? I did manage to center text but label is always at top left corner. 

react-native 0.63.3
react-native-paper 4.7.0
react-native-vector-icons 6.4.6

**Comment by system32uwu** [comment]
You may want to use the placeholder property then.

**Comment by tomto1** [comment]
Placeholder is not working. Thx anyway :)

**Comment by system32uwu** [comment]
> 
> 
> Placeholder is not working. Thx anyway :)

How is placeholder "not working"? Can you share the code that you are using?
