### ISSUE TITLE
How to customize TextInput?

### ISSUE THREAD

**Issue by Quernest** [callstack/react-native-paper#2523]
Is it possible to change the **size of the borders** and the **color of the label** (**only label, but not borders**)?

![изображение](https://user-images.githubusercontent.com/21086792/105725771-03b30700-5f32-11eb-8d27-a7e59d21b2be.png)

Can't find a flexible way to customize TextInput 🙄

**Comment by danielkv** [comment]
+1

**Comment by artthurz** [comment]
+1

**Comment by danielkv** [comment]
Didn't see the fix or workaround for it.
