### ISSUE TITLE
✨ make it possible to disable the ripple effect on a button component

### ISSUE THREAD

**Issue by Quernest** [callstack/react-native-paper#2529]
**Is your feature request related to a problem? Please describe.**
Ripple effect cannot be disabled on a button component.

**Describe the solution you'd like**
It would be nice to replace the TouchableRipple component with [TouchableWithoutFeedback](https://reactnative.dev/docs/touchablewithoutfeedback).

```jsx
import { TouchableWithoutFeedback } from 'react-native';
import { Button } from 'react-native-paper';

// option 1
<Button TouchableComponent={TouchableWithoutFeedback}>Button</Button>

// option 2
<Button disableRipple>Button</Button>
```

**Versions**
react-native: 0.63.3
react-native-paper: 4.6.0
react-native-vector-icons: 7.1.0

**Comment by Quernest** [comment]
👋

**Comment by zchwyng** [comment]
🖐

**Comment by Lea23VC** [comment]
Hello?, I have the same problem

**Comment by elmahdi-souilmi** [comment]
I have the same problem any solution?

**Comment by DishantSthapit** [comment]
Any progress on this?

**Comment by AntonyF-Andreani** [comment]
Any Progress??

I need this feature, we can help with a PR 😁

**Comment by arjun9218** [comment]
This is very much needed, any update on this?

**Comment by Akah** [comment]
To anyone still looking for a solution you can set `rippleColor="transparent` and you won't see any ripple.

**Comment by vpodolyan** [comment]
`rippleColor="transparent"` didn't help unfortunately, it draws dark ripples in this case

**Comment by byStrange** [comment]
background={{
              rippleRadius: 0,
              borderless: true,
              type: "RippleAndroid",
            }}

**Comment by gedu** [comment]
Hey, did you try this?
```
<PaperProvider theme={theme} settings={{rippleEffectEnabled: false}}>
```
the `TouchableRipple` checks if the ripple effect is enabled from the settings, so you can disable it like that.

**Comment by jayantVashisth1** [comment]
this works for me, taken from the react native paper docs
import { Provider as PaperProvider } from 'react-native-paper';
// ...

<PaperProvider
  settings={{
    rippleEffectEnabled: false
  }}
>
  // ...
</PaperProvider>

**Comment by inductionotg** [comment]
<PaperProvider
  settings={{
    rippleEffectEnabled: false
  }}
> 
While using this I am getting Icon is undefined

**Comment by FidFenix** [comment]
<Button> rippleColor={'transparent'} </Button>, working fine for expo 54
