### ISSUE TITLE
SafeArea BottomNavigation not working for iPads

### ISSUE THREAD

**Issue by vtoupet** [callstack/react-native-paper#2533]
### Current behaviour

`paddingBottom` is not added in case of recent iPads since react-native-paper v4.5.0. This occurs since the replacement of safe-area-view by iphonex-helper. iphonex-helper does not support iPad (only iPhones see https://github.com/ptelad/react-native-iphone-x-helper/issues/20 for full explanation)

### Expected behaviour

`paddingBottom` should be added in case of recent iPads

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.63.4
| react-native-paper    | 4.7.1
| react-native-vector-icons | 8.0.0

**Comment by comvenger-brandon** [comment]
This issue still exists.

**Comment by comvenger-brandon** [comment]
> This issue still exists.

I have to correct myself here, updating to the latest RN Paper and react-navigation versions solves this! 👍
