### ISSUE TITLE
Difference in alignment with different android

### ISSUE THREAD

**Issue by EnzoArg** [callstack/react-native-paper#2537]
I have different view alignment with different version of android. 
I don't know how solve this. I need that all version has the same alignment.

Android 7.1 (aligntment to Rigth)
![img1](https://user-images.githubusercontent.com/1648027/106635293-6e31fb80-655f-11eb-8460-6008dd089bd5.jpg)

Android 10 (Alignament Left)
![im2](https://user-images.githubusercontent.com/1648027/106635301-70945580-655f-11eb-948d-33aade433dae.jpg)

Somebody can help me?

**Comment by raajnadar** [comment]
May be the due to RTL?
