### ISSUE TITLE
Card.Cover component with the prop resizeMode='contain' behaves as if  resizeMode='cover'

### ISSUE THREAD

**Issue by nherment** [callstack/react-native-paper#2538]
### Current behaviour

A `Card.Cover` component with the prop `resizeMode='contain'` ignores the prop and behaves as if  `resizeMode='cover'`.
This is happening on Expo + an Android 8.1 device.

### Expected behaviour

A `Card.Cover` component with the prop `resizeMode='contain'` should keep the image within the allowed size

### Code sample

The folllowing code does not work as expected:
```
<Card.Cover>
    style={{height: '195px'}}
    resizeMode={'contain'}
    source={...}
</View>
```

The following code with react native components works as expected:
```
<View>
  <Image
    style={{height: '195px'}}
    resizeMode={'contain'}
    source={...}
    />
</View>
```

### Screenshots (if applicable)

![IncorrectBehaviour_resizeMode_contain](https://user-images.githubusercontent.com/1041426/106720102-f74a4080-65fa-11eb-8ee8-39b77bd81d06.PNG)

### What have you tried

I have tried overriding the style. From the react-native-paper code, it is actually not possible and it seems the CSS style `resizeMode='cover'` is enforced in the CardCover component and cannot be overriden by the user.

Cf. The component properties are defined [here](https://github.com/callstack/react-native-paper/blob/e5c0c777f90b5b3ad06a58d03b3de60ffb200cbd/src/components/Card/CardCover.tsx#L71) in react-native-paper codebase.
The style is defined [here](https://github.com/callstack/react-native-paper/blob/e5c0c777f90b5b3ad06a58d03b3de60ffb200cbd/src/components/Card/CardCover.tsx#L89).

### Your Environment

| software              | version
| --------------------- | -------
| android        | 8.1.0
| react-native          | 0.63.2
| react-native-paper    | 4.7.1
| node                  | v14.15.1
| yarn           | 1.22.10
| expo sdk              | 40.0.1

**Comment by lukewalczak** [comment]
Hey @nherment, thanks for reporting the bug, I will try to handle it!

**Comment by teamelliel** [comment]
It also makes the image blur on Android devices.
Seems like a similar issue to https://stackoverflow.com/questions/55802711/react-native-android-images-are-blurry-on-resizemodecontain
