### ISSUE TITLE
Custom Radio Button Icon Not Showing

### ISSUE THREAD

**Issue by aonawale** [callstack/react-native-paper#2539]
### Current behaviour

The RadioButton.IOS component does not show the check icon.

### Expected behaviour

I expected the RadioButton.IOS component to show the check icon because I am using custom icons via the Paper Provider settings. 

### Code sample

https://snack.expo.io/@ahmedonawale/172279

### Screenshots (if applicable)

![Screenshot 2021-02-03 at 11 45 43](https://user-images.githubusercontent.com/10553988/106736161-6339a280-6615-11eb-8a6c-ded1ff405469.png)

### What have you tried

Found this. 
https://github.com/callstack/react-native-paper/blob/main/src/components/RadioButton/RadioButtonIOS.tsx#L116

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios 14
| react-native          | 0.63.3
| react-native-paper    | 4.7.1
| node                  | v12.18.0
| npm or yarn           | yarn
| expo sdk              | NO

**Comment by landonwjohnson** [comment]
I was also having issues with this
