### ISSUE TITLE
TextInput.focus() doesn't work

### ISSUE THREAD

**Issue by oliverox** [callstack/react-native-paper#254]
```
<TextInput 
        label='Email' 
        value={email}
         ref={(c) => {
             this.inputs.email = c;
         }} />
```
We are unable to get a reference to `TextInput` because the `ref` prop is being overwritten by `react-native-paper`'s `ref` prop. See here: https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput.js#L276-L282

If we switch to using native `TextInput`, `focus()` works fine.

**Comment by oliverox** [comment]
After looking at the source code, it seems the reference is being returned as an object under `_root`.
I was able to fix it by calling `this.inputs.email._root.focus()`
Maybe this could go into the documentation?

**Comment by satya164** [comment]
Should be fixed now. Lemme know if still doesn't work.
