### ISSUE TITLE
Change borderRadius of Card

### ISSUE THREAD

**Issue by buffaloDeveloper** [callstack/react-native-paper#2543]
Is this configurable? I have tried by setting the style, but it does no take.  In some cases (mobile) I want the borderRadius to be 0.

"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
"react-native-paper": "^4.2.0",

**Comment by lukewalczak** [comment]
Hello @buffaloDeveloper, I've tested it and passing `borderRadius` into the `Card` styles works. Please check the attached [snack](https://snack.expo.io/Y-9Lo5r_8).

**Comment by buffaloDeveloper** [comment]
You are right.  I got it working, thank you.
