### ISSUE TITLE
drawer.item font style

### ISSUE THREAD

**Issue by vigyanhoon** [callstack/react-native-paper#2545]
Hi,

I have to change font size, weight etc of the drawer item label. I tried using style props, but nothing works except for backgroundColor. Is there a way to enable font change to drawer item?

Thanks.

<Drawer.Item
     style={{ backgroundColor: '#64ffda' }}
     icon="star"
     label="First Item"
   />

**Comment by vigyanhoon** [comment]
"react-native": "0.63.4",
"react-native-paper": "^4.7.1",
"react-native-vector-icons": "^8.0.0",

**Comment by Alarees** [comment]
use the `theme` prop
```
theme={{colors:{text:'red'}}}

**Comment by mike-rbrts** [comment]
`theme={{ fonts: { labelLarge: { fontWeight: '700', fontSize: 15, color: 'red' } } }}`
