### ISSUE TITLE
roundness override of text input

### ISSUE THREAD

**Issue by AvneeshD** [callstack/react-native-paper#2547]
### Current behaviour

Setting the indiviual textinput borderradius does not override the roundness set in the theme

### Expected behaviour

Setting the indiviual textinput borderradius should override the roundness set in the theme

**Comment by lukewalczak** [comment]
Hey @AvneeshD if you want to change the `borderRadius` in `TextInput` you can do it via theme prop:

```
	<TextInput
		theme={{ roundness: 10 }} 
		...
```

**Comment by hapablap21** [comment]
Is anyone aware of a workaround if I just want to change the borderRadius of one or two corners but not all of them?

**Comment by federicogomezcactus** [comment]
> Is anyone aware of a workaround if I just want to change the borderRadius of one or two corners but not all of them?

You can use the TextInput's theme prop:

`<TextInput theme={{ roundness: 0 }} ... />`

**Comment by renefitzke** [comment]
> Is anyone aware of a workaround if I just want to change the borderRadius of one or two corners but not all of them?

In case anyone stumbles upon that issue:
You can now do it using
`outlineStyle={{ bordeBottomLeftRadius: 0 }}`

etc
