### ISSUE TITLE
Using dark theme on iOS

### ISSUE THREAD

**Issue by ajengrf** [callstack/react-native-paper#2553]
I want to use react-native-paper dark theme on my apps, however, all my `<View>` are still had a white background and causing all the Text component unreadable because the text turns white in dark mode. I didn't use custom theming since the docs mention that:

> If you don't use a custom theme, Paper will automatically turn animations on/off, depending on device settings.

This is my code in App.js: 

```
import React from 'react';
import {Provider as PaperProvider} from 'react-native-paper';
import Home from './src/Home';

const App = () => {
  return (
    <PaperProvider>
      <Home />
    </PaperProvider>
  );
};

export default App;
```

This is in my Home.js:
```
import React from 'react';
import {View} from 'react-native';
import {Appbar, Card, Title} from 'react-native-paper';

const Home = () => {
  return (
    <View style={{flex: 1}}>
      <Appbar.Header>
        <Appbar.BackAction onPress={() => console.log('back')} />
        <Appbar.Content title="Title" subtitle={'Subtitle'} />
      </Appbar.Header>
      <View>
        <Title>Hello World</Title>
        <Card
          style={{margin: 15, padding: 15}}
          onPress={() => console.log('press card')}>
          <Title>This is Card</Title>
        </Card>
      </View>
    </View>
  );
};

export default Home;

```

and this is the result:
![Simulator Screen Shot - iPhone 11 - 2021-02-19 at 06 36 50](https://user-images.githubusercontent.com/30023314/108437399-d3842d00-727f-11eb-9c1c-0fadee393a9f.png)

The text turns white because it is the behavior of dark mode, but why my `<View>` is still white? This is only happening on iOS, it works fine on android.

It works fine on android device
![43225](https://user-images.githubusercontent.com/30023314/108439270-81dda180-7283-11eb-8581-0fa534fb8bb8.jpg)

This is a new react native project, and based on documentation in react-native-paper it will turn the dark theme automatically. So, I need help if I missed something in setting up this project on iOS. Any help would be appreciated.

- react: 16.13.1
- react-native: 0.63.4
- react-native-paper: ^4.7.1
- react-native-vector-icons: ^8.0.0

**Comment by GiFarina** [comment]
you can use 
`import * as React from 'react';
import { withTheme } from 'react-native-paper';

function MyThemedView(props) {
  const { colors } = props.theme;
  return <View style={{ backgroundColor: colors.primary }, props.style}/>;
}

export default withTheme(MyComponent);`

**Comment by ArtArnaud** [comment]
Anything new here ? I still have the same issue

**Comment by OkancanCosar** [comment]
This is not actually an bug. The package does not contain a custom view. You can create by yourself like @GiFarina's answer
