### ISSUE TITLE
Inconsistent documentation on mandatory `textAlign` prop of `TextInput` component

### ISSUE THREAD

**Issue by latobibor** [callstack/react-native-paper#2558]
### Current behaviour
The [documentation of TextInput](https://callstack.github.io/react-native-paper/text-input.html) does not specify `textAlign` as a prop of the component, however `TypeScript` compiler complains about the lack of it if you don't specify it.

### Expected behaviour
Either it should be dropped as a mandatory property so no **compiler error** or update documentation to involve `textAlign` property and mark it as mandatory (and also add it to the example).

### Code sample
```typescript
<TextInput label={content.login.inputLabel} value={id} onChangeText={handleChange} textAlign={textAlign} />
```

### What have you tried
Passing either `left` or `right` helps obviously.

### Your Environment

| software              | version
| --------------------- | -------
| react-native               | 0.63.2
| react-native-paper    | 4.7.2
| react-native-vector-icons | 8.0.0
| node                  | 14.15.0
| yarn           | 1.22.5

**Comment by latobibor** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native` (found: `0.63.2`, latest: `0.63.4`)
> * `yarn` (found: `1.22.5`, latest: `1.22.10`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes, since it is a type and documentation related problem.

**Comment by Robbilie** [comment]
Ive been working in my project for weeks and suddenly i get the error that i am missing the textAlign prop. it started around the time i began integrating react-navigation and its theme bottom navigation

**Comment by dariomalfatti-centropaghe** [comment]
I have the same problem (textAlign props missing) with react-native-paper 4.7.2 but with the 4.7.1 it works.

**Comment by latobibor** [comment]
Do you also have problem with any `<Text />` component wanting a `dataDetectorType` property?

**Comment by wobsoriano** [comment]
Any updates on this?

**Comment by lukewalczak** [comment]
Does the issue still occur for you in the latest paper version (4.8.1)?

**Comment by dariomalfatti-centropaghe** [comment]
Yes, it occurs in the latest version 4.8.1

**Comment by lukewalczak** [comment]
Does that happen for other components and props? Could you please to provide some example?

**Comment by dariomalfatti-centropaghe** [comment]
I'm using react-native-paper 4.7.1 with Typescript. If I update to 4.8.1, Typescript compiler raise an error that TextInput and SearchBar need textAlign property. Setting it to undefined, it compile.
I don't know if other components has this issue but on my project I'm using quite all paper compoments.

**Comment by TMaszko** [comment]
Which version of `@types/react-native` are you using in your projects ?

**Comment by dariomalfatti-centropaghe** [comment]
@types/react-native: 0.63.30

**Comment by TMaszko** [comment]
I had same issue and it's gone one I have bumped up `@types/react-native` to the `0.63.52`

**Comment by dariomalfatti-centropaghe** [comment]
Yes, it works. `react-native-paper` 4.8.1 with `@types/react-native` 0.63.52 works fine, thanks!

**Comment by Nikolay-Vovk-dataart** [comment]
> Yes, it works. `react-native-paper` 4.8.1 with `@types/react-native` 0.63.52 works fine, thanks!

Agreed. Just updated the types to latest version and now its working

**Comment by lukewalczak** [comment]
Since we have two confirmations that upgrading `@types/react-native` solves the issue, I'm closing it
