### ISSUE TITLE
No scrolling when touching TextInput

### ISSUE THREAD

**Issue by atheck** [callstack/react-native-paper#2561]
### Current behaviour

When setting

`style={{ textAlign: "right" }}`

on a TextInput the user can't scroll the screen.

### Expected behaviour

When the user wants to scroll and touches the TextInput, scrolling should work.

### Code sample

With:

```jsx
<TextInput
  value={...}
  onChangeText={...}
  style={{ textAlign: "right" }}
/>
```

scrolling does not work.

With:

```jsx
<TextInput
  value={...}
  onChangeText={...}
/>
```

it does.

### What have you tried

It's the same for textAlign: "center".

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.63.4
| react-native-paper    | 4.7.2
| react-native-vector-icons | 8.1.0
| node                  | 14.15.4
| npm           | 7.5.4

**Comment by atheck** [comment]
The bug still exists in v4.8.1.

**Comment by raajnadar** [comment]
Yes I guess it is React native bug. Because I can reproduce it with vanilla text input as well.
