### ISSUE TITLE
Cursor in TextInput jumps when using in Modal/Dialog

### ISSUE THREAD

**Issue by atheck** [callstack/react-native-paper#2565]
### Current behaviour

I'm using a `TextInput` inside a `Dialog`. When entering text somewhere in the middle, the cursor jumps back before that newly entered character. When deleting a character, the cursor jumps before the previous character.

### Code sample

```jsx
const [value, setValue] = useState("");

return (
  <Portal>
    <Dialog visible={props.visible} dismissable={false}>
      <Dialog.Title>Title</Dialog.Title>
      <Dialog.Content>
        <TextInput value={value} onChangeText={setValue} />
     </Dialog.Content>
   </Dialog>
  </Portal>
);
```

### Screenshots (if applicable)

![Peek 2021-02-25 11-01](https://user-images.githubusercontent.com/28619065/109136921-ece21900-7758-11eb-8e7e-16b9d40d3333.gif)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          |  0.63.4
| react-native-paper    | 4.7.2
| node                  | 14.15.4
| npm         | 7.5.4

**Comment by lukewalczak** [comment]
Hey @atheck, it looks like there is an issue related to controlled input by state within portal component. I can suggest you to move `TextInput` along with state to the separate component and then use it within portal component. Please check the [snack](https://snack.expo.io/ihWaUhgQO) and let me know if that helps.

**Comment by atheck** [comment]
Thank you for your reply @lukewalczak. Yes it works, but only as long as I don't want to change the value from outside. Looks like I need some workaround here...

**Comment by lukewalczak** [comment]
@atheck please also check the other [thread](https://github.com/callstack/react-native-paper/issues/1668) related to the same issue.

**Comment by alexandreandriesse** [comment]
I still have this problem, and it's annoying !

**Comment by raajnadar** [comment]
Pass the state value to the defaultValue prop it will make the input uncontrolled and the issue will get solved

**Comment by Lancer521** [comment]
> Pass the state value to the defaultValue prop it will make the input uncontrolled and the issue will get solved

I'm totally new to ReactNative and ran into this exact issue. `defaultValue` is the solution I was looking for, just didn't know where to look. Thanks @raajnadar

**Comment by DennyWanye** [comment]
> defaultValue
Hi @raajnadar , I get a same issue, and could you please explain more about defaultValue? I'm not sure where to find defaultValue prop.
