### ISSUE TITLE
On iOS Build only question marks in square boxes are shown instead of a checked icon

### ISSUE THREAD

**Issue by Pinny3** [callstack/react-native-paper#2566]
### Current behaviour

After building an iOS-IPA-Bundle and run it on a iPhone-Devices the Checkboxes and the Radiogroups are marked with a question mark in a square if they are checked. On Android a checked-icon is displayed as wanted. 

Running it on the simulator it works. 

### Expected behaviour

Show a checked-icon on iOS as on Android.

### Code sample

 ```
                       <Checkbox
                            status={changedByMarket ? 'checked' : 'unchecked'}
                            onPress={() => {
                                setChangedByMarket(!changedByMarket);
                            }}
                        />
```

```
                        <RadioButton
                            value="yes"
                            status={layoutOk === 'yes' ? 'checked' : 'unchecked'}
                            onPress={() => setLayoutOk('yes')}
                        />
                        <Text>ja</Text>
                        <RadioButton
                            value="no"
                            status={layoutOk === 'no' ? 'checked' : 'unchecked'}
                            onPress={() => setLayoutOk('no')}
                        />
```

### Screenshots (if applicable)

![IMG_0106](https://user-images.githubusercontent.com/2385101/109192508-9811c300-7797-11eb-83f0-d104af9e1b61.PNG)

### What have you tried

Build iOS App with 

 expo build:ios

### Your Environment

| software              | version
| --------------------- | -------
| ios        | 14.4.0
| react-native          | 0.63.4
| react-native-paper    | 4.0.1
| node                  | 12.14.1
| yarn           | 1.22.10
| expo              |  40.0.0
| react-native-vector-icons | 8.1.0

**Comment by Pinny3** [comment]
| ios        | 14.4.0
| react-native          | 0.63.4
| react-native-paper    | 4.0.1
| node                  | 12.14.1
| yarn           | 1.22.10
| expo              |  40.0.0
| react-native-vector-icons | 8.1.0

**Comment by ronaldborla** [comment]
@Pinny3 did you find a solution for this? I'm having the same issue

**Comment by appsgenie** [comment]
same issue only on iOS when upgrading from SDK 50 to 51... :(

did anyone find a fix?
