### ISSUE TITLE
On iOS iPhone-Device: After a build only question marks in square boxes are shown instead of a checked icon

### ISSUE THREAD

**Issue by Pinny3** [callstack/react-native-paper#2567]
### Current behaviour

After building an iOS-IPA-Bundle and run it on a iPhone-Devices the Checkboxes and the Radiogroups are marked with a question mark in a square if they are checked. On Android a checked-icon is displayed as wanted. 

Running it on the simulator it works. 

### Expected behaviour

Show a checked-icon on iOS as on Android.

### Code sample

 ```
                       <Checkbox
                            status={changedByMarket ? 'checked' : 'unchecked'}
                            onPress={() => {
                                setChangedByMarket(!changedByMarket);
                            }}
                        />
```

```
                        <RadioButton
                            value="yes"
                            status={layoutOk === 'yes' ? 'checked' : 'unchecked'}
                            onPress={() => setLayoutOk('yes')}
                        />
                        <Text>ja</Text>
                        <RadioButton
                            value="no"
                            status={layoutOk === 'no' ? 'checked' : 'unchecked'}
                            onPress={() => setLayoutOk('no')}
                        />
```

### Screenshots (if applicable)

![IMG_0106](https://user-images.githubusercontent.com/2385101/109192508-9811c300-7797-11eb-83f0-d104af9e1b61.PNG)

### What have you tried

Build iOS App with 

 expo build:ios

### Your Environment

| software              | version
| --------------------- | -------
| ios        | 14.4.0
| react-native          | 0.63.4
| react-native-paper    | 4.7.2
| node                  | 12.14.1
| yarn           | 1.22.10
| expo              |  40.0.1
| react-native-vector-icons | 8.1.0

**Comment by Pinny3** [comment]
Any news on this?

**Comment by enagorny** [comment]
For me even in simulator I see question mark boxes

**Comment by lukewalczak** [comment]
It looks like that issue is more related to the lib providing the icons (react-native-vector-icons)

> For me even in simulator I see question mark boxes

Did you properly set up icons in your project?

**Comment by ronaldborla** [comment]
I'm having the same issue, I already followed the steps on react-native-vector-icons (making sure that it's in plist, etc.)

**Comment by lukewalczak** [comment]
Could you please create the example repo presenting the issue?

**Comment by gudlyf** [comment]
I had the same issue, and it turned out it was because I was using the `react-native-paper` package to use a `TextInput.Icon` element, which seems to require the inclusion of the `MaterialCommunityIcons` font pack. Once I added that, I saw the icon I needed.

So I would say make sure you first try installing ALL of the icons/font files from `react-native-vector-icons` and, if that solves it, consider removing some until you get only what you need.
