### ISSUE TITLE
Dismiss keyboard when clicking outside TextField

### ISSUE THREAD

**Issue by wmattei** [callstack/react-native-paper#2568]
**Is your feature request related to a problem? Please describe.**
If you click outside the TextField you would like to fire the `blur` event, therefore dismiss the keyboard.

**Describe the solution you'd like**
Maybe a property `dismissKeyboardOnTapAway` or even a function `onTapAway`

**Describe alternatives you've considered**
We currently can wrap our page into a `TouchableWithoutFeedback` from `react-native-gesture-handler` but that makes buttons inside the content not pressable

### Versions
react-native: expo sdk 40.0.1
react-native-paper: `^4.7.2`
react-native-vector-icons: `8.1.0`

**Comment by shamxeed** [comment]
Why not importing the TouchableWithoutFeedback from react-native? That should make the buttons clickable.
