### ISSUE TITLE
dark prop required in <Toolbar> for dark themes

### ISSUE THREAD

**Issue by pshrmn** [callstack/react-native-paper#257]
### Current behaviour

A theme with a dark primary color requires the `dark={true}` prop to be attached to the `<Toolbar>` or [`<Toolbar(Back)Action>`](https://github.com/callstack/react-native-paper/blob/3e1cfa8e9335a7ff6d59defdefad4e91edc4192a/src/components/Toolbar/ToolbarAction.js#L41-L46) for the icon to be displayed as a light color.

### Expected behaviour

I would expect the component to use `theme.colors.text` for the icon color instead of deriving a color. The `<ToolbarContent>` already uses this value (unless it or the `<Toolbar>` has `dark={true}`, in which case it also sets the color to white).

### Code sample

https://snack.expo.io/Hyjv6rV_z

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    | 1.0.1 |
| node                  |
| npm or yarn           |

**Comment by satya164** [comment]
Thanks for the repro. Looks like a bug. I don't think toolbar should be using `theme.colors.text` for the icons. If no `dark` prop is specified, `Toolbar` should automatically detect if the background color of the toolbar is dark or light and pass the `dark` prop to its children accordingly.

- `<Toolbar dark />` should pass `dark={true}` to it's children
- `<Toolbar dark={false} />` should pass `dark={false}` to it's children
- `<Toolbar style={{ backgroundColor: 'black' }} />`  should pass `dark={true}` to it's children
- `<Toolbar style={{ backgroundColor: 'white' }} />`  should pass `dark={false}` to it's children

**Comment by satya164** [comment]
Should be fixed by 4b4492831d5f76a6478665b52a87b83c6da3f8d8
