### ISSUE TITLE
Text Collision when defaultValue supplied

### ISSUE THREAD

**Issue by Hektar90** [callstack/react-native-paper#2572]
### Current behaviour
This issue is related to [#1072](https://github.com/callstack/react-native-paper/issues/1072)

<img width="341" alt="Bildschirmfoto 2021-03-01 um 10 42 28" src="https://user-images.githubusercontent.com/15243732/109479710-f500c800-7a7a-11eb-87b7-6b59b1884fc1.png">

### Expected behaviour

<img width="341" alt="Bildschirmfoto 2021-03-01 um 10 42 52" src="https://user-images.githubusercontent.com/15243732/109479765-05b13e00-7a7b-11eb-890f-662a5bd39195.png">

### Code sample

`      <TextInput
                  style={styles.textInputMargin}
                  mode="outlined"
                  error={title === null || title === ''}
                  defaultValue={title ?? undefined}
                  label="Fach"
                  onChangeText={(text) => {
                    setTitle(text);
                  }}
                />`

` <TextInput
                  mode="outlined"
                  label="Kürzel"
                  defaultValue={shorthand ?? undefined}
                  onChangeText={(text) => {
                    setShorthand(text);
                  }}
                />`

### Screenshots (if applicable)

see above

### What have you tried

Adding a plain string as default value is working as expected.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          |  0.63.4 
| react-native-paper    | 4.7.2
| node                  | 12.14.0
| npm           | 6.13.4
| react-native-vector-icons   | 7.0.0
| expo              | -

**Comment by lukewalczak** [comment]
Hey @Hektar90, I created a [snack](https://snack.expo.io/tdgcZ2Cjm) using your code sample, but I wasn't able to reproduce the bug. Do the issue still exist for you, if yes could you please provide more details?

**Comment by Hektar90** [comment]
Hi @lukewalczak , the issue still exist. Check this [snack](https://snack.expo.io/1KoAOzQ_k).

**Comment by lukewalczak** [comment]
@Hektar90 what do you think about the solution where label prop is also conditioned: `label={title ?? "Fach"}`? Please check the following [snack](https://snack.expo.io/IRRvpvxPV)

**Comment by Hektar90** [comment]
I build a form with the TextInput, where I insert the already made inputs from the user into the defaultProp. Title as name was misleading in my snack. If I would take the property label, the individual inputs from the user would appear in the label, which is not desired.

Assuming there is an address field and the user has already saved an entry, it would appear as a label. I hope I could make myself clear.
