### ISSUE TITLE
Style property 'backgroundColor' is not supported by native animated module, when navigating back from browser.

### ISSUE THREAD

**Issue by codeyogi911** [callstack/react-native-paper#2574]
### Current behaviour
I am using the card component to display news in my app. On click, I use the react-native's inbuilt `Linking` to open a browser to display the article. Everything works fine till here. But when I click navigate back to the app using the back navigation button on iOS the app crashes with the below error.

### Expected behaviour
I don't expect any errors on navigating back to the app.

### JSX

> <Section header={'News'}>
      {loading ? (
        <ActivityIndicator />
      ) : news.length < 1 ? (
        <Text>No News</Text>
      ) : (
        news.slice(0, 5).map((item) => {
          const date = new Date(item.publishedAt);
          return (
            <Card
              style={{marginVertical: 10}}
              key={`${item.url}`}
              onPress={() => handlePress(item.url)}>
              {/* <Surface> */}
              <Card.Title
                style={{padding: 10}}
                title={item.title}
                titleNumberOfLines={3}
                subtitle={moment(date).format('DD MMMM YY')}
                // left={LeftContent}
              />
              <Card.Content style={{padding: 10}}>
                <Paragraph>{item.description}</Paragraph>
              </Card.Content>
              <Card.Cover source={{uri: item.urlToImage}} />
              {/* </Surface> */}
            </Card>
          );
        })
      )}
    </Section>

### Function to open article

> const handlePress = useCallback(async (url) => {
    // Checking if the link is supported for links with custom URL scheme.
    const supported = await Linking.canOpenURL(url);

    if (supported) {
      // Opening the link with some app, if the URL scheme is "http" the web link should be opened
      // by some browser in the mobile
      await Linking.openURL(url);
    } else {
      Alert.alert(`Don't know how to open this URL: ${url}`);
    }
  }, []);

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/29333988/109508782-2d37f300-7adb-11eb-8fce-1203c1a7dfdb.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS
| react-native          | 0.63.4
| react-native-paper    | ^4.7.1
| node                  | v15.3.0
| npm or yarn           | yarn
| expo sdk              |

**Comment by girish54321** [comment]
Any update i am all so feacing this problem when i change theme to light to dark.

**Comment by codeyogi911** [comment]
@girish54321 try this article. It solved my problem. [Theming with React navigation](https://callstack.github.io/react-native-paper/theming-with-react-navigation.html)

**Comment by girish54321** [comment]
Thanks for you help 
but i did the same 
im puting my code here so anyone can take a look at

`
import {
  NavigationContainer,
  DefaultTheme as NavigationDefaultTheme,
  DarkTheme as NavigationDarkTheme,
} from '@react-navigation/native';
import {
  Provider as PaperProvider,
  DefaultTheme as PaperDefaultTheme,
  DarkTheme as PaperDarkTheme,
} from 'react-native-paper';


let CustomDefaultTheme = {
    ...PaperDefaultTheme,
    ...NavigationDefaultTheme,
    colors: {
      ...PaperDefaultTheme.colors,
      ...NavigationDefaultTheme.colors,
      accent: Colors.primary,
      card: 'rgb(255, 255, 255)',
      background: '#ffffff',
      text: '#333333',
    },
  };

  let CustomDarkTheme = {
    ...PaperDarkTheme,
    ...NavigationDarkTheme,
    colors: {
      ...PaperDarkTheme.colors,
      ...NavigationDarkTheme.colors,
      accent: Colors.primary,
      card: 'rgb(18, 18, 18)',
      background: '#333333',
      text: '#ffffff',
    },
  };

<PaperProvider theme={darkTheme ? CustomDarkTheme : CustomDefaultTheme}>
      <NavigationContainer
        theme={darkTheme ? CustomDarkTheme : CustomDefaultTheme}>
        {authState.userLoggedIn ? (
          <MainAppStackScreens />
        ) : (
          <AuthStackScreens />
        )}
      </NavigationContainer>
    </PaperProvider>![Screenshot_20210310-172410_WhatsApp.jpg](https://user-images.githubusercontent.com/47414322/110625455-71a34d00-81c5-11eb-8bac-da8d6729ebb1.jpg)

`

**Comment by girish54321** [comment]
Hi All after remove `onPress `form `<Card />` fixed the theme problem to now I am using` TouchableOpacity` for `onPress  `action.
