### ISSUE TITLE
List.Item not visible on some devices (production)

### ISSUE THREAD

**Issue by Rebsos** [callstack/react-native-paper#2579]
### Current behaviour

List.Item not visible on Samsung 10e and Samsung 10 Lite.

### Expected behaviour

List.Item visible on all devices.

### Code sample

```
  <List.Item
    title="First Item"
    description="Item description"
    left={props => <List.Icon {...props} icon="folder" />}
  />
```

### What have you tried

Tested on real devices. Also some users complain. Most devices seem to work, but at least **Samsung 10e and 10 Lite do not work**.
Try e. g. Samsung 10e with Android 10.
Samsung 10+, 8 and so on do work, emulators also.

_TouchableRipple_ does work, also _TouchableNativeFeedback_ with ripple.

I've also tested List.Item with a lot of different props, but it's just not visible (blank/white). It takes the space and is clickable.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.63.4
| react-native-paper    | 4.7.2
| node                  | 10.19.0
| npm or yarn           | npm
| expo sdk              | -
| react-native-vector-icons | 8.1.0

**Comment by lukewalczak** [comment]
Hey @Rebsos, we are using `TouchableNativeFeedback` inside the `List.Item`, are you able to reproduce the issue in the RN with the similar setup? If yes, please open the issue there.

**Comment by Rebsos** [comment]
I've replaced List.Item with a custom solution. But I'm using TouchableNativeFeedback without problems in other parts of the app.

**Comment by lukewalczak** [comment]
Could you please download the RNP [example app](https://play.google.com/store/apps/details?id=com.callstack.reactnativepaperexample&hl=pl&gl=US) from google store and confirm whether `List.Item` is not visible on mentioned devices as well?
