### ISSUE TITLE
TextInput: long text results in linebreak

### ISSUE THREAD

**Issue by Hektar90** [callstack/react-native-paper#2581]
### Current behaviour

Typing a long text in TextInput and unfocusing it breaks the line

### Expected behaviour

Text is cut off at the end and is only visible by scrolling while editing

### Code sample

<img width="920" alt="Bildschirmfoto 2021-03-03 um 18 39 29" src="https://user-images.githubusercontent.com/15243732/109847750-db64a980-7c4f-11eb-8856-d8743d42f279.png">

### Screenshots (if applicable)

<img width="397" alt="Bildschirmfoto 2021-03-03 um 18 47 24" src="https://user-images.githubusercontent.com/15243732/109849068-3ba81b00-7c51-11eb-8629-04cde5baaf8a.png">

### What have you tried

set numberOfLines to 1 and multiline to false

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.63.4
| react-native-paper    | 4.7.2
| node                  | 12.14.0
| npm           | 6.13.4
| expo             | -

**Comment by dingziqi** [comment]
[It seems to be caused by the `textAlign`](https://github.com/callstack/react-native-paper/blob/975cfa3be4956b629aa8255e226ff9ca068448eb/src/components/TextInput/TextInputOutlined.tsx#L336), only when `textAlign: default`, the ellipsis will work corectly。

**Comment by Hektar90** [comment]
> [It seems to be caused by the `textAlign`](https://github.com/callstack/react-native-paper/blob/975cfa3be4956b629aa8255e226ff9ca068448eb/src/components/TextInput/TextInputOutlined.tsx#L336), only when `textAlign: default`, the ellipsis will work corectly。This is the bug of react-native, see the [issues](https://github.com/facebook/react-native/issues/29068#issue-631523357).
> 
> You can passdown `textAlign: 'auto'` to fixed it.

Unfortunately this is not working. Either adding textAlign:'auto' | 'left' | 'right' nor leaving the property out to take the default has no effect.
The latter leads to an type error saying textAlign needs to be set.

**Comment by shllg** [comment]
I my case `textAlign: 'auto'` does not work.

Additionally, I recognized the following behavior in development:
- changing the vertical padding will "adjust" the component correctly. The ellipsis is still missing but the content is in one line
- entering any text and remove it again results again in line breaks

Initially, it renders correctly (except of missing ellipsis) and changes result in line breaks.

**Comment by mohamedanwer123** [comment]
This issue still occur

**Comment by lirimkrosa** [comment]
In my case `textAlign={undefined}` it works!

**Comment by kostiantyn-ccm** [comment]
Still reproduce such issue

**Comment by joaoVictorDeAndrade** [comment]
In my case textAlign={"auto"} works, but the placeholder  is no longer centered

**Comment by LorianAtashi01** [comment]
For people that use styled-components together with react-native-paper just add into your styling text-align: auto and it works:

`const StyledInput = styled(TextInput)"
  background-color: transparent;
  text-align: auto;"
`

**Comment by ademagic** [comment]
Still seeing this issue. Adding `{textAlign: 'auto'}` or `{textAlign: undefined}` to the styles of the TextInput component doesn't seem to make a difference. I can see the textAlign property working with other values, but "auto" (or any other value) doesn't fix it.

**Comment by VictorioMolina** [comment]
Same here

**Comment by simonbengtsson** [comment]
For me adding `textAlign: 'auto'` works.

Only `<TextInput />`:

<img width="366" alt="Screenshot 2023-09-17 at 17 02 35" src="https://github.com/callstack/react-native-paper/assets/3586691/575aa91f-db59-4140-a08c-ec252697463b">

With fix: `<TextInput style={{ textAlign: 'auto' }} />`

<img width="364" alt="Screenshot 2023-09-17 at 17 04 16" src="https://github.com/callstack/react-native-paper/assets/3586691/d3ab4419-3e13-46b0-ae82-9835b80f4233">

**Comment by Manasa2903** [comment]
Not working with textAlign: 'auto', undefined. Tried as a prop for TextInput as well as in 'style'.

**Comment by bleedweedsuz** [comment]
I tried this still not working:

`<TextInput  label={label} placeholder={placeholder} style={[{textAlign: 'auto'}, style ]} onChangeText={onChangeText} value={value?.toString()}  />`

![Screenshot 2023-11-14 at 2 08 14 PM](https://github.com/callstack/react-native-paper/assets/10117919/0f4d2ab3-2c29-45ba-8533-df27b4d3f9d9)

**Comment by aannaassalam** [comment]
> [It seems to be caused by the textAlign](https://github.com/callstack/react-native-paper/blob/975cfa3be4956b629aa8255e226ff9ca068448eb/src/components/TextInput/TextInputOutlined.tsx#L336), only when textAlign: default, the ellipsis will work corectly。This is the bug of react-native, see the https://github.com/facebook/react-native/issues/29068#issue-631523357.
> You can passdown textAlign: 'auto' to fixed it.

Hi, I have figured it out. If some else thinks that this solution is not working for you then try using it with `textAlignVertical="auto"` coz this, is what worked for me.

**Comment by bleedweedsuz** [comment]
@aannaassalam which version u are using coz i am using ( "react-native-paper": "^5.11.1") it's not working.
My current code which i tried:
`<TextInput textAlignVertical='auto' multiline={false} numberOfLines={1} label={label} placeholder={placeholder} mode={mode} style={[{textAlign: undefined, overflow:'hidden'}, style ]} onChangeText={onChangeText} value={value?.toString()} right={right} />`

i am using overflow hidden to make useable currently it look like in the example image.
![Screenshot 2023-11-16 at 6 36 12 PM](https://github.com/callstack/react-native-paper/assets/10117919/563c04df-814d-44dc-b196-316582262297)

**Comment by m4rv4ul3r** [comment]
This bug occurs on IOS in my case. On android it seems to be rendered correct. I tried it on IOS simulator and IOS physical device as well. Both are showing the bug. So it seems to be an IOS issue.

**Comment by aannaassalam** [comment]
> @aannaassalam which version u are using coz i am using ( "react-native-paper": "^5.11.1") it's not working. My current code which i tried: `<TextInput textAlignVertical='auto' multiline={false} numberOfLines={1} label={label} placeholder={placeholder} mode={mode} style={[{textAlign: undefined, overflow:'hidden'}, style ]} onChangeText={onChangeText} value={value?.toString()} right={right} />`
> 
> i am using overflow hidden to make useable currently it look like in the example image. ![Screenshot 2023-11-16 at 6 36 12 PM](https://private-user-images.githubusercontent.com/10117919/283455049-563c04df-814d-44dc-b196-316582262297.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NTY2MDEsIm5iZiI6MTcwMDg1NjMwMSwicGF0aCI6Ii8xMDExNzkxOS8yODM0NTUwNDktNTYzYzA0ZGYtODE0ZC00NGRjLWIxOTYtMzE2NTgyMjYyMjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDIwMDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMDg4ZDI2ZjhmOTYyMDk2MTQ5Zjg3YzYwYTdhOGMyMzRmYmQ1ZDEzNzFkMjY5MjY4NGRkNTk2YzRiM2FhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UFT1ZLWig6TeWGwN_-9nKbdZPRocsUDHqy9F9CyoIEA)
> 
> Edit: after i did some tinkering, this issue only occur in mode={"outlined"} ; flat is working fine.

Yes, you should pass it to style prop instead of passing it to the component and again there was a mistake in my comment textAlignVertical is not the correct way to do that.

**Comment by aannaassalam** [comment]
Here is my piece of working code - 

`<TextInput
                      onChangeText={onChange}
                      outlineColor="#268C43"
                      underlineColorAndroid="transparent"
                      activeOutlineColor="#268C43"
                      mode="outlined"
                      outlineStyle={{
                        borderRadius: 10,
                      }}
                      label={
                        <Text
                          style={{
                            fontSize: 16 / fontScale,
                            textTransform: 'capitalize',
                          }}>
                          {t('address')}
                        </Text>
                      }
                      value={value}
                      style={styles.textInput}
                      placeholder={t('address')}
                      placeholderTextColor={'#333'}
                      keyboardType="default"
                      editable={false}
                      right={
                        <TextInput.Icon
                          icon="crosshairs-gps"
                          size={24}
                          color="#268C43"
                          onPress={getLocation}
                        />
                      }
                    />`

Styles:                

`textInput: {
      backgroundColor: '#fff',
      fontFamily: 'ubuntu-medium',
      fontSize: 16 / fontScale,
      textAlign: 'auto',
    },`

**Comment by mertcankose** [comment]
error still exist

**Comment by danielle-cruz** [comment]
Same error on iOS

**Comment by truonghoangpham123** [comment]
> Same error on iOS

Have you solved the problem yet? You can use:
```css
inputStyle: {
    textAlign: 'auto',
    lineHeight: undefined,
}
```
I think it can help you solve the problem!

**Comment by bleedweedsuz** [comment]
if this issue still exist for single line Textinput then use this code
Trick is u need to set **height** for non multiline. issue only in iOS. It try to accommodate the overflowing text that is why, this error
React-native-paper: version 5.11.4

Code and demo of Before and After
Before:
![Screenshot 2023-12-25 at 3 21 59 PM](https://github.com/callstack/react-native-paper/assets/10117919/fb171bf1-e00c-490c-b8e2-29eeeb7322e9)
`<TextInput mode='outlined' value='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut cursus orci. Fusce condimentum leo id facilisis porttitor.'/>`

After:
![Screenshot 2023-12-25 at 3 53 45 PM](https://github.com/callstack/react-native-paper/assets/10117919/8d56f5f9-b148-40dd-80e7-a9fc0dc4a888)

`<TextInput style={{ height: 56 }} mode='outlined' value='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut cursus orci. Fusce condimentum leo id facilisis porttitor.'/>`

Note: 56 is default height for outlined

**Comment by truonghoangpham123** [comment]
> if this issue still exist for single line Textinput then use this code Trick is u need to set **height** for non multiline. issue only in iOS. It try to accommodate the overflowing text that is why, this error React-native-paper: version 5.11.4
> 
> Code and demo of Before and After Before: ![Screenshot 2023-12-25 at 3 21 59 PM](https://private-user-images.githubusercontent.com/10117919/292745830-fb171bf1-e00c-490c-b8e2-29eeeb7322e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDE1NzYsIm5iZiI6MTcwMzUwMTI3NiwicGF0aCI6Ii8xMDExNzkxOS8yOTI3NDU4MzAtZmIxNzFiZjEtZTAwYy00OTBjLWI4ZTItMjllZWViNzMyMmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDEwNDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YjdmOGM4OTQ2ZDEyNDMzNjczYTA3M2RhMWYwNDlmMDhjN2Q2NzhjNTg1ODU4ZDkyOGZmZTY3NTg3MDU3MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eErWzlBILFLt0hgjkhmvb3pleberASNdMjUNrfGWHJQ) `<TextInput mode='outlined' value='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut cursus orci. Fusce condimentum leo id facilisis porttitor.'/>`
> 
> After: ![Screenshot 2023-12-25 at 3 53 45 PM](https://private-user-images.githubusercontent.com/10117919/292746074-8d56f5f9-b148-40dd-80e7-a9fc0dc4a888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDE1NzYsIm5iZiI6MTcwMzUwMTI3NiwicGF0aCI6Ii8xMDExNzkxOS8yOTI3NDYwNzQtOGQ1NmY1ZjktYjE0OC00MGRkLTgwZTctYTlmYzBkYzRhODg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDEwNDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZGY2NjRjNjBjMzhlYzZmNDlkZDQ3ODQzMjQ5OGZmOWM2MWJiY2FiYWRkODQyYjhkMmQ0YTNiMTY2ZGU2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z6a2JfnTSnaGH-s2zD97KE9z0Ep8anfACrjMZSEUB-A)
> 
> `<TextInput style={{ height: 56 }} mode='outlined' value='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut cursus orci. Fusce condimentum leo id facilisis porttitor.'/>`
> 
> Note: 56 is default height for outlined

Yep, your results are still correct but in terms of UX, it doesn't seem very good. 
The desired result is shown below.

**Before:**
<img width="367" alt="Screenshot 2023-12-25 at 17 57 15" src="https://github.com/callstack/react-native-paper/assets/14884073/96fe4971-bade-45a1-88bc-70a532dbfd4e">

**After:**
<img width="358" alt="Screenshot 2023-12-25 at 17 57 22" src="https://github.com/callstack/react-native-paper/assets/14884073/7379c3f3-737a-484e-90d3-6873f0d1f2c8">

However your results are missing ```truncated```

**Comment by john-trieu-nguyen** [comment]
Ran into the same issue when I updated the react-native-paper library.
Found a bug in release 5.10.5 that broke existing behaivour.

Have submitted a pull request #4261 which has fixed it :)

**Comment by AlexKyrdyukov** [comment]
hi everyone, I have the same problem and I am fixing it by removing it from the input styles 
    // // lineHeight: 15,

leaving only the fontSize

I hope this helps. 

if it helped, a like is welcome

**Comment by vpume** [comment]
For me, adding this to the reat-native-paper `<TextInput>` element works. all the other suggestions here either didn't, or long words are truncated from the end when the TextInput element is no longer focued.

```
...Platform.select({
      ios: {
        contentStyle: {
          textAlign: undefined,
        },
      },
    }),
```

**Comment by mister-conor** [comment]
@vpume Adding `contentStyle={{ textAlign: undefined }}` to the input props worked for me, thanks.

**Comment by ioane-margiani-lemontaps** [comment]
> [@vpume](https://github.com/vpume) Adding `contentStyle={{ textAlign: undefined }}` to the input props worked for me, thanks.

Only this one worked for my, I tried every single option in this thread (  "react-native-paper": "^5.13.1" )

**Comment by JelsonJr** [comment]
Hey guys, the way I found to solve the problem in a "perfect" way on IOS was as follows:

```
<TextInput
     style={styles.input}
     contentStyle={{
        ...Platform.select({
          ios: { textAlign: undefined }, // To change only on IOS
          android: {},
        }),
     }}
/>
```

```
const styles = StyleSheet.create({
  input: {
    backgroundColor: colors.cinza[100],
    borderRadius: 16,
    height: 46,
  }
});
```
"expo": "~53.0.20",
"react-native-paper": "^5.14.5",

**Comment by rkchoudhury** [comment]
Is there any way to truncate the TextInput and add three dots to the end for Android ?

**Comment by Aman-Shukla-18** [comment]
```contentStyle={{ textAlign: undefined }}``` alone didn’t resolve the issue for me. After some trial and error, I found that the root cause was ```lineHeight```. Removing ```lineHeight```  and applying ```testAlign: undefined``` fixed the problem.

So make sure ```lineHeight``` is not applied along with this.
