### ISSUE TITLE
How to have a multiline button?

### ISSUE THREAD

**Issue by EduVencovsky** [callstack/react-native-paper#2583]
I'm trying to use the `Button` component with multiple lines of text, is it even possible?

I was looking at the source code and found that the `Text` component of the `Button` have a fixed prop `numberOfLines={1}`. Maybe it should be possible to customize the `Text` component passing something like `textProps`?

I know that multiline button goes agains material design guide lines, but... is it possible?

**Comment by raajnadar** [comment]
Did you try

```
<Button>
   <Text>Multiline test</Text>
   <Text>Did that work?</Text>
</Button>
```

**Comment by EduVencovsky** [comment]
@raajnadar doesn't work because nested `Text` components are treated as only one "text" for react native
