### ISSUE TITLE
dialog issue with Maximum update depth exceeded

### ISSUE THREAD

**Issue by devjaw** [callstack/react-native-paper#259]
### Current behaviour
i got this error when i'm trying to open a dialog":

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### Expected behaviour
the dialog should open

### Code sample
as in the documentation 
https://callstack.github.io/react-native-paper/dialog.html

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 
| react-native          | 0.51.0
| react-native-paper    |1.0.1
| node                  | 9.6.1
| npm or yarn           | npm

**Comment by satya164** [comment]
Should be fixed by 228749346c4d877545d05938040b248409473d55
