### ISSUE TITLE
Outlined input label not showing while using React Native LayoutAnimation in Android 

### ISSUE THREAD

**Issue by aliburhankeskin** [callstack/react-native-paper#2592]
###  Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          |  https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz
| react-native-paper    | 4.7.2
| node                  |  15.4.0
| npm or yarn           | yarn
| expo sdk              |  40.0.0

**Outlined input label not showing while using React Native LayoutAnimation in Android .**
Note: ios also works well.

Video:
https://user-images.githubusercontent.com/32386753/110314781-5c89bb00-8019-11eb-9351-2b09a03d3a94.mp4

Code:

```
import {
// something...
  LayoutAnimation,
  UIManager,
  Platform
} from 'react-native';
```

   ```
       if (
            Platform.OS === 'android'
            && UIManager.setLayoutAnimationEnabledExperimental
          ) {
            UIManager.setLayoutAnimationEnabledExperimental(true);
          }
         
    // Somethingg....

         
        const _animationClick = () => {
          LayoutAnimation.configureNext(LayoutAnimation.Presets.spring);  
          setIsRegister(!isRegister);
        };

    

```
 // Somethingg...

```
         {isRegister && (

          <View style={Styles.input}>          
               
            <TextInput
              label={i18n.t('login.email')}
              value={email}
              mode="outlined"
              onChangeText={_onChangeEmail}
            />        

               
            <HelperText type="error" visible={errors.email}>
              Email address is invalid!
            </HelperText>
          
          </View>
        )}
```

Thank you for your help

**Comment by lukewalczak** [comment]
Looks like the issue is related to `LayoutAnimation` which is experimental on Android platform. I can suggest you to write your custom spring animation.

**Comment by aliburhankeskin** [comment]
Thanks for your answer @lukewalczak. I will try your suggestion.
