### ISSUE TITLE
TextInput with mode outlined - Outline over label when focused

### ISSUE THREAD

**Issue by denniske** [callstack/react-native-paper#2598]
### Current behaviour

When the text input is focused the outline is all around the text input and as such also over the label.

### Expected behaviour

Do not cover the label with the outline.

### Code sample

```
<TextInput
    right={
        <TextInput.Affix
            text={' %'}
        />
    }
    dense={true}
    mode="outlined"
    label="Opacity"
    value={text}
    onChangeText={text => setText(text)}
/>

```
### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/1076211/110711663-370ad600-8200-11eb-8f31-7d004384bacf.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |  web
| react-native          | 0.63
| react-native-paper    | 4.7.2
| node                  | 12
| npm or yarn           | both
| expo sdk              | 40

**Comment by aiapps2020** [comment]
same issues using
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-vector-icons": "^8.1.0"
"react-native-paper": "4.7.2",

**Comment by NoumanSakhawat** [comment]
same issues using
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-vector-icons": "^8.1.0"
"react-native-paper": "4.7.2",

**Comment by brunohkbx** [comment]
@denniske @NoumanSakhawat  can you please create a snack reproducing this issue?

**Comment by FelipeACP** [comment]
https://snack.expo.io/P1bac2SGL
