### ISSUE TITLE
List.Item onPress not always firing.

### ISSUE THREAD

**Issue by samtsejerome** [callstack/react-native-paper#2599]
I've rendered a number of List.Item components and only the first in the list  fires the onPress callback when clicked!

### Expected behaviour
all List.Items should call the  onPress callback when clicked.

### What have you tried

I  tried creating a new list (with static items ) in a test project, but was unable to recreate the issue. and also couldnt see any differences between working and failing projects  rendering of List.Item elements
I also tried changing styling to provide more space in case this was a factor.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 37.0.1
| react-native-paper    | 3.8.0
| node                  | 10.16.3
| npm or yarn           | yarn 1.22.4
| expo sdk              | 37.0.12

**Comment by samtsejerome** [comment]
* react-native 37.0.1
* react-native-paper 3.8.0
* react-native-vector-icons 6.6.0
* npm 6.9.0 (but not used )
* yarn 1.22.4
* expo cli3.11.7
* expo sdk: 37.0.12 
* node: 10.16.3
* 

Jerome Mayeux

**Comment by jamesdward** [comment]
I also recently began having issues with onPress across any component (List.Item, Button, IconButton etc). The event fires intermittently, usually every 5-10 taps

- react-native 40.0.1
- react-native-paper 4.0.1
- react-native-vector-icons 8.1.0
- Expo 40.0.0

**Comment by jamesdward** [comment]
Okay fixed the problem for me - seems to actually be a strange react native bug https://github.com/facebook/react-native/issues/29083#issuecomment-642457919 that intermittently affects onPress functionality when you are debugging remotely. By turning off "Debug remote js" in Expo, the onPress functionality is back to working perfectly
