### ISSUE TITLE
icons error with custom webpack using on the web

### ISSUE THREAD

**Issue by learncodingforweb** [callstack/react-native-paper#2600]
Getting errors
ERROR in ./node_modules/react-native-vector-icons/dist/FontAwesome.js 1:0-55
Module not found: Error: Can't resolve 'core-js/modules/es6.object.define-property.js' in '/home/box/dev/rn_web_webpack/node_modules/react-native-vector-icons/dist'

even though steps mentioned https://callstack.github.io/react-native-paper/using-on-the-web.html
package.json file
`{
  "name": "dev",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-native-vector-icons": "^8.1.0",
    "react-native-web": "^0.15.0"
  },
  "devDependencies": {
    "@babel/core": "^7.13.10",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.13.8",
    "@babel/preset-env": "^7.13.10",
    "@babel/preset-flow": "^7.12.13",
    "@babel/preset-react": "^7.12.13",
    "@babel/preset-typescript": "^7.13.0",
    "babel-loader": "^8.2.2",
    "babel-plugin-react-native-web": "^0.15.0",
    "html-webpack-plugin": "^5.3.1",
    "prettier": "^2.2.1",
    "url-loader": "^4.1.1",
    "webpack": "^5.25.0",
    "webpack-cli": "^4.5.0",
    "webpack-dev-server": "^3.11.2"
  },
  "scripts": {
    "start": "webpack serve --config webpack.config.js",
    "build": "webpack --config webpack.config.js",
    "format": "prettier --write ."
  }
}`

**Comment by learncodingforweb** [comment]
Building app for website using 

"react-native-paper": "^4.7.2",
"react-native-vector-icons": "^8.1.0",
"react-native-web": "^0.15.0"

**Comment by learncodingforweb** [comment]
webpack.config.js
`
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './index.js',
  output: {
    path: path.resolve(__dirname, './release'),
    filename: 'bundle.js',
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: './index.html',
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules[/\\](?!react-native-vector-icons)/,
        use: {
          loader: 'babel-loader',
          options: {
            babelrc: false,
            configFile: false,
            presets: [
              ['@babel/preset-env', { useBuiltIns: 'usage' }],
              '@babel/preset-react',
              '@babel/preset-flow',
              '@babel/preset-typescript',
            ],
            plugins: [
              'babel-plugin-react-native-web',
              '@babel/plugin-proposal-class-properties',
              '@babel/plugin-proposal-object-rest-spread',
            ],
          },
        },
      },
      {
        test: /\.ttf$/,
        loader: 'url-loader', // or directly file-loader
        include: path.resolve(
          __dirname,
          'node_modules/react-native-vector-icons'
        ),
      },
    ],
  },
  devServer: {
    contentBase: path.join(__dirname, 'release'),
    compress: true,
    port: 3000,
  },
  resolve: {
    alias: {
      'react-native$': 'react-native-web',
    },
  },
};
`

**Comment by learncodingforweb** [comment]
Was doing wrong webpack configuration
Followed steps as per documentation mentioned [https://callstack.github.io/react-native-paper/using-on-the-web.html]()
working fine

**Comment by samaneh-kamalian** [comment]
I followed these steps in https://callstack.github.io/react-native-paper/using-on-the-web.html
for an existence react native project. 
but compiler can not transpile react jsx code:
```
ERROR in ./src/app/index.js 20:6
Module parse failed: Unexpected token (20:6)
You may need an appropriate loader to handle this file type
```
I searched a lot but did not find any solution.

**Comment by learncodingforweb** [comment]
May you are doing wrong webpack. Note down webpack config as 

``
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, './release'),
    filename: 'bundle.js',
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: './index.html',
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        include: [
          path.resolve('src'),
          path.resolve('node_modules/react-native-paper'),
          path.resolve('node_modules/react-native-vector-icons'),
        ],
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              '@babel/preset-env',
              '@babel/preset-react',
              '@babel/preset-flow',
              '@babel/preset-typescript',
            ],
            plugins: [
              'babel-plugin-react-native-web',
              '@babel/plugin-proposal-class-properties',
              '@babel/plugin-proposal-object-rest-spread',
            ],
          },
        },
      },
      {
        test: /\.(jpg|png|woff|woff2|eot|ttf|svg)$/,
        loader: 'file-loader',
        include: [
          path.resolve('node_modules/react-native-vector-icons'),
          path.resolve('node_modules/react-native-paper'),
        ],
      },
    ],
  },
  devServer: {
    contentBase: path.join(__dirname, 'release'),
    compress: true,
    port: 4000,
    historyApiFallback: true,
  },
  resolve: {
    alias: {
      'react-native$': 'react-native-web',
    },
  },
};
```

**Comment by samaneh-kamalian** [comment]
Thanks for your reply.
I get this error for several of my modules : 

```
ERROR in ./node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedDebug.js 9:10
Module parse failed: Unexpected token (9:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class AnimatedDebug extends AnimatedNode {
>   _message;
|   _value;
```
Although I added it to the list of `include` !
Also I have this type of error: 

```
ERROR in ./node_modules/react-native-material-ui/src/Avatar/Avatar.react.js 99:8
Module parse failed: Unexpected token (99:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     if (icon) {
|       content = (
>         <Icon
```
So what is loader for `_someVariable`and jsx syntax!???

**Comment by learncodingforweb** [comment]
checkout repo for reanimated for its config
https://github.com/learncodingforweb/web_reanimated
