### ISSUE TITLE
Portal stays visible indefinitely if unmounted immediately after mounting

### ISSUE THREAD

**Issue by matthieugicquel** [callstack/react-native-paper#2606]
### Current behaviour

When trying to remove a portal immediately after mounting it, it stays visible indefinitely. See the failing test below.

### Expected behaviour

The portal is unmounted and does not stay visible.

### Code sample

Here's a minimal failing test case (something equivalent happened to me in more complicated, real world code)

```tsx
import React, { useEffect, useState } from 'react';
import { Portal, Text } from 'react-native-paper';
import { render, waitForElement } from 'react-native-testing-library';

const TestComponent = () => {
  const [isPortalVisible, setIsPortalVisible] = useState(true);
  useEffect(() => {
    // Unmount the portal immediately after mounting it
    setIsPortalVisible(false);
  }, []);

  return (
    <Portal.Host>
      {isPortalVisible && (
        <Portal>
          <Text>{"I'm here"}</Text>
        </Portal>
      )}
    </Portal.Host>
  );
};

test('portal is properly unmounted', async () => {
  const component = render(<TestComponent />);

  // This expectation is failing, the portal is never unmounted, despite the useEffect
  await waitForElement(() => {
    const portalContent = component.queryByText("I'm here");
    if (portalContent) throw new Error('Portal is still visible');
  });
});
```

### What have you tried

The cause seems to be with the `await` here:
https://github.com/callstack/react-native-paper/blob/975cfa3be4956b629aa8255e226ff9ca068448eb/src/components/Portal/PortalConsumer.tsx#L10-L17

The await in `componentDidMount` causes a race condition with the synchronous unmounting:
https://github.com/callstack/react-native-paper/blob/975cfa3be4956b629aa8255e226ff9ca068448eb/src/components/Portal/PortalConsumer.tsx#L25-L29

The portal gets (not really) unmounted before being mounted → it stays registered with the portal manager.

One possible fix is to make componentWillUnmount async too:

```diff
-  componentWillUnmount() {
+  async componentWillUnmount() {
     this._checkManager();

+    await Promise.resolve();
     this.props.manager.unmount(this._key);
   }
 ```

I'm not sure why the `await Promise.resolve()` was introduced, so I can't tell for sure if it's possible to fix this in a cleaner way.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | irrelevant
| react-native          | 0.63.3
| react-native-paper    | bug confirmed in 2.16 and 4.7.2
| node                  | 14.15
| npm or yarn           | irrelevant
| expo sdk              | not used

**Comment by juspeeh** [comment]
Facing same issue. Any workarounds?

**Comment by AndresAltomobile** [comment]
Facing the same issue. I tried modifying `PortalConsumer.tsx` as pointed out by @matthieugicquel and it works in debug mode, but when I try in release mode it keeps happening. Any workaround for release/prod mode?

**react-native-paper**: 4.7.1
**react-native**: 0.63.4

**Comment by raajnadar** [comment]
use https://www.npmjs.com/package/patch-package

**Comment by fnimick** [comment]
Can confirm this is still an issue in the latest version. Our solution is to always render a `Portal` and have actual contents or an empty body based on our condition, rather than conditional rendering of the `Portal` itself.

**Comment by angelos3lex** [comment]
Any case this gets opened again and be fixed?

**Comment by ali-rantakari** [comment]
This issue should be reopened. We've been hit by a similar race condition in `componentDidUpdate`, otherwise matching the description in this issue.

https://github.com/callstack/react-native-paper/blob/975cfa3be4956b629aa8255e226ff9ca068448eb/src/components/Portal/PortalConsumer.tsx#L22

**Comment by juspeeh** [comment]
Still an issue
