### ISSUE TITLE
Is there an official way to use Icon?

### ISSUE THREAD

**Issue by Invertisment** [callstack/react-native-paper#2609]
I'd like to design my own component which uses an Icon. I'd like to reuse your mechanism of requesting an icon by its name and displaying it.
Is this doable?

**Comment by lukewalczak** [comment]
Hey @Invertisment we are not exporting the `Icon` as a standalone component, but the same mechanism is used in `react-native-vector-icons` [library](https://github.com/oblador/react-native-vector-icons#icon-component) on which our component is based.
