### ISSUE TITLE
onClose icon moves out with flexWrap

### ISSUE THREAD

**Issue by jereztech** [callstack/react-native-paper#2618]
### Current behaviour

onClose icon moves out with flexWrap

### Expected behaviour

onClose icon must remain in the correct position such as the main icon (Chip::icon)

### Code sample

<View style={{ flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-start' }}>
    {this.state.hashtagsSet.map((item, index) => (
        <Chip
            key={index}
            icon="pound"
            onClose={() => this.onExcludeHashtag(index)}
            style={{ margin: 5 }}
        >
            {item}
        </Chip>
    ))}
</View>

### Screenshots

<img width="227" alt="no-wrap-ok" src="https://user-images.githubusercontent.com/31424362/112247362-eac58a00-8c32-11eb-8f1b-dbcf486265c9.png">
<img width="227" alt="wrap-moves-out" src="https://user-images.githubusercontent.com/31424362/112247373-f022d480-8c32-11eb-95f2-e67f9160d4ac.png">

### What have you tried

I tried using FlatList with numColumns but large elements are cut off

### Your Environment

| software              | version
| --------------------- | -------
| react-native          |0.63.2
| react-native-paper    |4.7.2
| node                  |14.15.4
| npm           |7.6.3
| expo sdk              |40.0.0

**Comment by lukewalczak** [comment]
Hey @jereztech I was not able to reproduce the issue on the [snack](https://snack.expo.io/ICIUleNRw) using your code sample. Could you please try to send similar snack where we can observer the issue?

**Comment by jereztech** [comment]
hi @lukewalczak snack has bugs too hahahaha, to reproduce, please create new expo app and then install react-native-paper@4.7.2, use the fallowing code:

import React from 'react';
import { View, StyleSheet } from 'react-native';
import { TextInput, Chip } from 'react-native-paper';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      hashtag: null,
      hashtags: [],
    };
  }

  render() {
    return (
      <View style={styles.mainContainer}>
        <View style={styles.form}>
          <TextInput
            label="hashtag"
            value={this.state.hashtag}
            onChangeText={(hashtag) => this.setState({ hashtag })}
            onSubmitEditing={() => {
              let hashtags = [...this.state.hashtags, this.state.hashtag];
              this.setState({ hashtags, hashtag: null });
            }}
            onFocus={() =>
              !this.state.hashtag?.startsWith('#') &&
              this.setState({ hashtag: '#' })
            }
          />
          <View style={styles.rowFlexWrap}>
            {this.state.hashtags.map((item, index) => (
              <Chip
                key={index}
                icon="pound"
                onClose={() => { }}
                style={{ margin: 5 }}>
                {item}
              </Chip>
            ))}
          </View>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  form: {
    flexDirection: 'column',
    padding: 30,
    paddingBottom: 70,
  },
  rowFlexWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
  },
});

thanks a lot

**Comment by lukewalczak** [comment]
@jereztech If snack also has a bug, please move your code into [snack](https://snack.expo.io/), save it and post there a link into it. That'll make finding issue easier.

**Comment by jereztech** [comment]
https://snack.expo.io/@jjerezalo/chips-close-out

**Comment by lukewalczak** [comment]
I've checked your snack example, and it looks like removing `alignItems: 'flex-start'` fix your issue, however I will investigate it within the lib.

**Comment by jereztech** [comment]
Using flexWrap is for the purpose of placing items in multiple lines for good user experience, withow flexWrap more than 4 elements are hidden, and using FlatList with numColumns large elements are cut off, so flexWrap is the solution for this goal (many chips in multiple lines for good user experience).
