### ISSUE TITLE
Possible to pass a ref as the anchor for a menu?

### ISSUE THREAD

**Issue by buffaloDeveloper** [callstack/react-native-paper#2620]
I want to put the Menu in a separate component and the parent will pass a ref to it that will serve as the anchor.

Is this possible?

"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
"react-native-paper": "^4.7.2",
react-native-vector-icons

**Comment by lukewalczak** [comment]
Hey @buffaloDeveloper, actually I'm not sure if it's possible, but maybe instead passing the ref you can pass the component via prop?
