### ISSUE TITLE
[Fab] Fab button doesn't inherit DefaultTheme primary color 

### ISSUE THREAD

**Issue by akshaynaik404** [callstack/react-native-paper#2627]
### Current behaviour
In a single app if I use Appbar and Fab button the background colors are different.

I am not providing any theme explicitly to `<PaperProvider>`. As a novice user exploring the library It was a hassle to look for ways to change the styling of the button.
### Expected behaviour
Just like there is default background color for appbar same color should be present as fab button background color in DefaultTheme.

Do let me know if there is any specific reason why these colors are kept different by default.

### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/8489816/112763835-bfbcab00-9023-11eb-85cd-c2190598c3a1.png)

### What have you tried
I came across [this thread](https://github.com/callstack/react-native-paper/issues/677)  and was able to customize the css.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 10.0 (Q) - API 29
| react-native          | 0.64.0
| react-native-paper    | ^4.7.2
| node                  | v12.21.0
| npm or yarn           | 6.14.11
| expo sdk              | NA

**Comment by lukewalczak** [comment]
Hello @akshaynaik404, the behaviour which you observed is correct, actually FAB is using _accent_ color from theme as a background color. I guess that MaterialDesign guidelines indicates that secondary color should be on FAB.

**Comment by akshaynaik404** [comment]
Oh got it. Then this is correct behaviour. Thanks @lukewalczak .
