### ISSUE TITLE
ZIndex overlapping in Android

### ISSUE THREAD

**Issue by khamisEDX** [callstack/react-native-paper#2635]
### Expected behaviour

I am using zIndex but still the component behind the option from "react-native-paper" is still getting clicked. I tried using TouchableOpactiy it's not getting clicked, In iOS everything works fine the issue is only in Android.

### Code sample

[Home Page](https://gist.github.com/khamisEDX/1aa41fffea2db1491b25cbe3ea7780a9)
[Appbar](https://gist.github.com/khamisEDX/5226a266a68547fa07bbcf064e0642a3)
[CustomSearchbar](https://gist.github.com/khamisEDX/84623fb5fca55c8409e72919dfb6bb49)

### Screenshots (if applicable)
![giiif](https://user-images.githubusercontent.com/68809241/112967950-7750da80-9154-11eb-95ec-1766f7d243d9.gif)

### What have you tried

I tried zIndex , elevation , wrapping whole button by View nothing works , when i switch to TouchableOpacity it works fine, but i need to use the "react-native-paper"

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | only Android
| react-native          |"0.64.0"
| react-native-paper    | "^4.7.2"
| node                  | v15.0.1
| npm    | 7.7.6
| react-native-vector-icons          | "^8.1.0"

**Comment by Surdok** [comment]
I ran to the very same issue.. Please help

**Comment by khamisEDX** [comment]
I solved it. you can close this issue
