### ISSUE TITLE
component's colors gets inverted in iOS [🐛 ]

### ISSUE THREAD

**Issue by mykelaballe** [callstack/react-native-paper#2639]
components like Button, Text, TextInput, Chip, Badge, Card, etc are getting inverted colors in iOS when you go the device's home screen (without killing the app, basically just minimizing the app) and then bringing the app in focus again

NORMAL LOOK / INITIAL UI
![Simulator Screen Shot - iPhone 11 - 2021-03-31 at 21 34 41](https://user-images.githubusercontent.com/22584900/113153413-a5740e80-9269-11eb-97ac-77dcc4d142a6.png)

AFTER GOING TO HOME SCREEN AND THEN BRING THE APP IN FOCUS AGAIN
![Simulator Screen Shot - iPhone 11 - 2021-03-31 at 21 34 53](https://user-images.githubusercontent.com/22584900/113153595-d6ecda00-9269-11eb-8cc2-548b27a22f6f.png)

**Expected behavior**
the colors should not get inverted

react: 16.13.1
react-native: 0.63.4
react-native-paper: 4.5.0
react-native-vector-icons: 7.1.0
platform: iOS

**Comment by mykelaballe** [comment]
yes

**Comment by mykelaballe** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native` (found: `0.63.4`, latest: `0.64.0`)
> * `react-native-paper` (found: `4.5.0`, latest: `4.7.2`)
> * `react-native-vector-icons` (found: `7.1.0`, latest: `8.1.0`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

yes

**Comment by mykelaballe** [comment]
has anybody experienced this?

**Comment by nicoache1** [comment]
@mykelaballe im also struggling with this. Also im experiencing that sometimes in outline mode the border disappears at all

**Comment by mykelaballe** [comment]
@nicoache1 i fixed it by adding theme prop in Provider component, my whole app is wrapped with Provider component from react-native-paper, the  i just added the theme prop in combination with useColorScheme from react-native:

import {useColorScheme} from 'react-native'
import {Provider, DefaultTheme, DarkTheme} from 'react-native-paper'

<Provider theme={useColorScheme() == 'dark' ? DarkTheme : DefaultTheme}>
      <App/>
  </Provider>

**Comment by nicoache1** [comment]
> @nicoache1 i fixed it by adding theme prop in Provider component, my whole app is wrapped with Provider component from react-native-paper, the  i just added the theme prop in combination with useColorScheme from react-native:
> 
> 
> 
> import {useColorScheme} from 'react-native'
> 
> import {Provider, DefaultTheme, DarkTheme} from 'react-native-paper'
> 
> 
> 
> <Provider theme={useColorScheme() == 'dark' ? DarkTheme : DefaultTheme}>
> 
>       <App/>
> 
>   </Provider>

I would try this, thank you! @mykelaballe

**Comment by triptec** [comment]
@mykelaballe I'm sorry but this should be considered a bug with a known workaround? I mean flipping the theme on every "to background/foreground" can't be expected behavior right?

**Comment by mykelaballe** [comment]
@triptec yes i agree, let me change this to a bug. thanks for pointing out

**Comment by triptec** [comment]
@mykelaballe also thanks for the workaround!

**Comment by lukewalczak** [comment]
Looks like this is the correct way to fix that issue, I've checked paper's example and there themes are also [conditional](https://github.com/callstack/react-native-paper/blob/main/example/src/index.tsx#L132)
