### ISSUE TITLE
Card onPress error when change theme from light to dark

### ISSUE THREAD

**Issue by wwwenjie** [callstack/react-native-paper#2641]
### Current behaviour

Card onPress error when change theme from light to dark

linked issue: https://github.com/callstack/react-native-paper/issues/2063 https://github.com/callstack/react-native-paper/issues/2574 https://github.com/callstack/react-native-paper/issues/2167
linked PR: https://github.com/callstack/react-native-paper/pull/2113 https://github.com/callstack/react-native-paper/pull/2068

### Expected behaviour

When theme changes from light to dark, Card should not throw error of background.

### Code sample

https://snack.expo.io/@jinwenjie/card-error-in-rnp

note: I can't reproduce it on snack(the theme dosent change when i toggle theme), but I reproduce in local with same code.

behaviour: when pressed card. then change theme from light to dark, error occur. when haven't pressed card, everything works well.

### What have you tried

The problem should from here, when theme is light, useNativeDriver is true but when change to dark, it adds background and maybe useNativeDriver is still true due to some unknown reason?

```
 useNativeDriver: !dark || mode === 'exact',
```

Not sure if https://github.com/callstack/react-native-paper/pull/2113 can fix this error. The PR looks like old, if the PR can fix this problem, Im willing to update it to FC style.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    |
| node                  |
| npm or yarn           |
| expo sdk              | 40

**Comment by DoctorJohn** [comment]
This is still an issue in `4.10.1`, in my case using custom dark and light themes. The app crashes when switching between both themes as described by @wwwenjie. All linked issues and PRs refer to the same underlying problem. #2113 would probably fix it.
