### ISSUE TITLE
List.Accordion ripple not following the borderRadius

### ISSUE THREAD

**Issue by MichielMortier** [callstack/react-native-paper#2643]
### Current behaviour

```<List.Accordion title={'accordion'} style={styles.drawerStyle}>```

The added style contains 'borderRadius' and 'backgroundColor'. This will set a background color to the title.
When clicked on it to expand, the ripple effect will folow the original square, instead of the square with border raduis on it.

### Expected behaviour

When clicked on it, the ripple effect needs to be the same size as the colored background with rounded corners.

### Screenshots (if applicable)

![169413459_286484452852114_1783851408094969320_n](https://user-images.githubusercontent.com/17470246/113510836-ff701f00-955c-11eb-823f-727d9ee66fe5.jpg)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          |  0.64.0
| react-native-paper    | 4.7.2
| node                  | 14.16.0
| npm or yarn           | yarn
| expo sdk              | 40
| expo                | 40.0.1
| yarn               |  1.22.10
| npm             |  6.14.11
| react-native-vector-icons | 8.1.0

**Comment by lukewalczak** [comment]
Hey @MichielMortier, thanks for reporting the bug, it looks like `ListAccordion` component should have `borderless` prop since it accepts style prop. I will handle it.

**Comment by MichielMortier** [comment]
@lukewalczak thanks for taking this!

**Comment by Denly** [comment]
Hi I think the issue is still there? It just shows white at the corner.

reproduced here  https://snack.expo.dev/@007623/list.accordion

<img width="332" alt="Screenshot 2024-02-24 at 8 14 21 AM" src="https://github.com/callstack/react-native-paper/assets/7588279/6575cdd1-b2d5-4d99-99e9-a355b417340a">

**Comment by Denly** [comment]
Ok I found the solution...
You can achieve it by passing a theme prop into List.Accordion with customized background color, in the following way:
```
<List.Accordion
    theme={{colors: {background: 'orange'}}}
    style={{ backgroundColor: 'white', marginBottom: 20 }}
    title="Uncontrolled Accordion"
    left={(props) => <List.Icon {...props} icon="folder" />}>
        <List.Item title="First item" />
        <List.Item title="Second item" />
</List.Accordion>
```
ref https://github.com/callstack/react-native-paper/issues/2994#issuecomment-986240488
