### ISSUE TITLE
Searchbar clear press does not trigger onChangeText

### ISSUE THREAD

**Issue by jack828** [callstack/react-native-paper#2649]
### Current behaviour

Create a Searchbar component with an `onChangeText` prop. Enter text. Use clear button to clear the text. `onChangeText` not called with empty value - so no way to know it occured.

### Expected behaviour

This should trigger `onChangeText` with an empty string `''`. Alternatively, provide `onClearText` and we'll do it ourselves.

### Code sample

```jsx
        <Searchbar
          style={styles.searchBar}
          placeholder="Search"
          value={query}
          onChangeText={(q) => setQuery(q)} />

```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          | 0.63
| react-native-paper    | 4.4.1
| node                  | 12.20.0
| npm or yarn           | yarn v1.12.3
| expo sdk              | n/a

I am aware I am on an outdated version of this library. Will be updating later but currently in the middle of a workaround:

```jsx
        <Searchbar
          style={styles.searchBar}
          placeholder="Search"
          value={query}
          onChangeText={(q) => setQuery(q)}
          clearIcon={(props) => (
            <Icon name="close" onPress={handleSearchClear} {...props} />
          )}
        />
```

**Comment by jack828** [comment]
Still an issue.

**Comment by jack828** [comment]
Why was this closed? I commented within 7 days?

**Comment by laffed** [comment]
still an issue

**Comment by bhar4620** [comment]
@jack828 Thanks, bro. it's awesome. the react-native paper search bar has to miss this onClearPress properties. I was searching solution to my project finely I found your code 
 clearIcon={(props) => (
            <Icon name="close" onPress={handleSearchClear} {...props} />
          )}
and its work.
can you explain pls? how should clearIcon have functional properties? how should it work on props in the parameter? and the icon tag is owned onPress properties itself?
