### ISSUE TITLE
Is there a prop keyboardType or something like that on TextInput component?

### ISSUE THREAD

**Issue by dichai1983** [callstack/react-native-paper#2650]
react-native-paper 4.7.1

Thanks.

**Comment by lukewalczak** [comment]
Hey @dichai1983, since paper's TextInput is based on the input from react-native, there is an access to the [prop](https://reactnative.dev/docs/textinput#keyboardtype) `keyboardType`.

**Comment by dichai1983** [comment]
Thanks 😊
