### ISSUE TITLE
How to set transparent background on fab group opened

### ISSUE THREAD

**Issue by francesco-clementi-92** [callstack/react-native-paper#2652]
I'd like to have a transparent background instead of the grey one in the fab group:

![i2](https://user-images.githubusercontent.com/30288622/114052840-af5fc800-988e-11eb-871f-4fbd25996644.JPG)
![i1](https://user-images.githubusercontent.com/30288622/114052849-b1298b80-988e-11eb-9e26-25826ea4eee9.JPG)

I checked the documentation and the issues but I didn't find a way to configure the transparent background color.

**Comment by lukewalczak** [comment]
@francesco-clementi-92 you can achieve it by passing theme with transparent backdrop color. Please check the sample code below:

```
      <FAB.Group
        open={open}
        icon={open ? 'calendar-today' : 'plus'}
        theme={{ colors: { backdrop: 'transparent' } }}
        ...
 ```

**Comment by francesco-clementi-92** [comment]
Cool! Really appreciate it, it's working!

Thanks

I'll close the issue
