### ISSUE TITLE
Position Affix in Text Input

### ISSUE THREAD

**Issue by nguyentanhoangnth** [callstack/react-native-paper#2653]
I'm using affix to custom Text Input . But i can not set position affix which always place holder . 
Please , help me 
 "react-native": "0.63.4",
"react-native-paper": "^4.7.2",
 "react-native-vector-icons": "^8.1.0",

**Comment by nguyentanhoangnth** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native` (found: `0.63.4`, latest: `0.64.0`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

yes , it's still be like

**Comment by lukewalczak** [comment]
Hey @nguyentanhoangnth, could you please specify more details about your issue and attach [snack](https://snack.expo.io/) or some code sample which can help us with reproducing the bug?

**Comment by nguyentanhoangnth** [comment]
> Hey! Thanks for opening the issue. Can you provide more information about the issue? Please fill the issue template when opening the issue without deleting any section. We need all the information we can, to be able to help. Make sure to at least provide - Current behaviour, Expected behaviour, A way to reproduce the issue with minimal code (link to [snack.expo.io](https://snack.expo.io)) or a repo on GitHub, and the information about your environment (such as the platform of the device, versions of all the packages etc.).

![Screen Shot 2021-04-13 at 08 11 59](https://user-images.githubusercontent.com/39661885/114482945-a45fbb80-9c31-11eb-8322-d882b2835c38.png)
<img width="373" alt="Screen Shot 2021-04-13 at 08 12 08" src="https://user-images.githubusercontent.com/39661885/114482948-a75aac00-9c31-11eb-8407-8afedf73b4e0.png">
this is way that i implement affix component .

**Comment by lukewalczak** [comment]
I think that `TextInput` affix component should be always attached to the left/right side based on LTR/RTL setting and it cannot follow the placeholder like in your example.
