### ISSUE TITLE
Card onLongPress not showing animation/feedback

### ISSUE THREAD

**Issue by francesco-clementi-92** [callstack/react-native-paper#2656]
### Current behaviour

Card prop onLongPress doesn't show animation/touchable feedback:

https://snack.expo.io/@nordup/card-onlongpress-missing-animation

### Expected behaviour

I expect the same feedback such as onPress prop.

As a workaround I can add onPress prop with a useless function, but I'd lile to have a clean code

### Code sample

https://snack.expo.io/@nordup/card-onlongpress-missing-animation

### Your Environment

"react": "17.0.1",
"react-native": "0.64.0",
"react-native-paper": "^4.7.2",
"react-native-vector-icons": "^8.1.0"

**Comment by lukewalczak** [comment]
Thanks for reporting the issue, we'll handle it.
