### ISSUE TITLE
 there was an error message when i clicked the anchor button in debug environment

### ISSUE THREAD

**Issue by ClownWang-1217** [callstack/react-native-paper#2658]
![image](https://user-images.githubusercontent.com/48983541/114340997-598b6880-9b8b-11eb-8379-bc80253e33dd.png)

Here is my project environment:

"react": "16.8.6"
"react-native": "^0.59.9"
"react-native-paper": "4.5.0"

Here is my code：

const MyComponent = () => {
     const [visible, setVisible] = React.useState(false);
  
     const openMenu = () => setVisible(true);
  
     const closeMenu = () => setVisible(false);
  
     return (
           <Menu
             visible={visible}
             onDismiss={closeMenu}
             anchor={<Button onPress={openMenu}>Show menu</Button>}>
             <Menu.Item onPress={() => {}} title="Item 1" />
             <Menu.Item onPress={() => {}} title="Item 2" />
             <Menu.Item onPress={() => {}} title="Item 3" />
           </Menu>
     );
   };
  
   export default MyComponent;

how can i solve?
thanks!

**Comment by ClownWang-1217** [comment]
There is still the problem after upgrade to the  last version of "react-native-paper"

**Comment by raajnadar** [comment]
Try clearing the metro cache `npx react-native --reset-cache`

**Comment by ClownWang-1217** [comment]
I found it worked when I used react-native(>=0.60)and if you used react-native(0.59.9 || <0.60) it would report error.
