### ISSUE TITLE
TextInput dark mode question/possible issue

### ISSUE THREAD

**Issue by BrenoVelasco** [callstack/react-native-paper#2662]
Hi everyone!
I am an experienced React developer but really new to React Native so sorry if I'm asking dumb questions here.

# Current behaviour
TextInput is showing white background color in dark mode.

![white-input-in-dark-mode](https://user-images.githubusercontent.com/21113340/114503095-25ec2500-9c03-11eb-9dc5-00f0182f9c86.jpeg)

# Expected behaviour
TextInput show a darker color for dark mode.

# Code Sample
<img width="502" alt="Screen Shot 2021-04-13 at 02 55 15" src="https://user-images.githubusercontent.com/21113340/114503635-030e4080-9c04-11eb-9549-c3af25d5b060.png">
<img width="579" alt="Screen Shot 2021-04-13 at 02 55 33" src="https://user-images.githubusercontent.com/21113340/114503642-04d80400-9c04-11eb-872f-806f2b28260f.png">
<img width="363" alt="Screen Shot 2021-04-13 at 02 57 22" src="https://user-images.githubusercontent.com/21113340/114503644-06093100-9c04-11eb-8c40-35af7e4b54bc.png">

# Your Environment
"react": "17.0.1",
"react-native": "0.64.0",
"react-native-paper": "^4.7.2",
"react-native-vector-icons": "^8.1.0"

Developing for iPhone (iOS 14.4.2) connected to my laptop via USB-C cable.

**Comment by jaworek** [comment]
Hi!

Please take a look at the example app:
https://github.com/callstack/react-native-paper/blob/main/example/src/index.tsx

You need to prepare light and dark theme.

Your code should look something like this: 

```
function getTheme(isDark) {
	return isDark ? DarkTheme : DefaultTheme
}
```

If you want to make some custom changes you can overwrite default values like you did with `DefaultTheme`

**Comment by BrenoVelasco** [comment]
Thanks! That helped =)

**Comment by BrenoVelasco** [comment]
@jaworek sorry to reopen this issue but just confirm one thing with me, please: I have to "create" TextInput's dark mode or react-native-paper has some kind of native TextInput dark color?

**Comment by BrenoVelasco** [comment]
Guys, I was able to figure this out. Just to give an update:
When setting theme configuration for `PaperProvider`, you have to spread `DefaultTheme` or `DarkTheme`. In my case I forgot to spread `DarkTheme` in colors:

<img width="573" alt="Screen Shot 2021-04-13 at 20 46 10" src="https://user-images.githubusercontent.com/21113340/114634676-7910b700-9c99-11eb-83e8-84c999a07ab3.png">

Thanks a lot!
