### ISSUE TITLE
Change Card backgroundColor onPressIn 

### ISSUE THREAD

**Issue by voulgarakis** [callstack/react-native-paper#2666]
Is it possible to change the card's background color when the user presses the card, in order to give some feedback to the user that the card is pressed?

**Comment by lukewalczak** [comment]
I guess you meant changing the shadow color _(please correct me if I'm wrong)_. I've checked the code and it seems impossible, since `shadowColor` is based on the constant [color](https://github.com/callstack/react-native-paper/blob/main/src/styles/shadow.tsx#L12).

**Comment by voulgarakis** [comment]
I mean something like:
style={({pressed}) => [
{
    backgroundColor: pressed ? 'red' : 'green',
},
 {
...
  },
 ]}

so when Card is pressed we can change the card's backgroundColor for a while

**Comment by lukewalczak** [comment]
I see, however I have the feeling there is no direct way to achieve it within `Card` component.
