### ISSUE TITLE
Expo SDK 41.0.0 does not approve of .expo.* files.

### ISSUE THREAD

**Issue by AugustinasMK** [callstack/react-native-paper#2667]
### Current behaviour

Project is using deprecated .expo.* file extensions.
Please refactor the following files and upgrade modules accordingly:

- node_modules/react-native-paper/lib/module/constants.expo.js
- node_modules/react-native-paper/src/constants.expo.tsx

### Expected behavior

The warning is not shown.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    |
| node                  |
| npm or yarn           |
| expo sdk              | 41.0.0

**Comment by AugustinasMK** [comment]
The expo provided link for steps to fix this. https://github.com/expo/fyi/blob/master/expo-extension-migration.md

**Comment by lukewalczak** [comment]
Solved within: https://github.com/callstack/react-native-paper/pull/2560
