### ISSUE TITLE
Add a `useModal` hook?

### ISSUE THREAD

**Issue by likeSo** [callstack/react-native-paper#2668]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
---
For now, I have to handle `onDismiss` event on `<Modal />`, and a 'Task Complete' event on my modal screen.
Both `onDismiss` and 'Task Complete'  should dismiss a modal: Here is the sample code:
```tsx
<Modal
          visible={visible}
          onDismiss={() => {setVisible(false)}}
        >
  <ModalScreen onFinish={() => {setVisible(false)}} />
</Modal>
```
i think `() => {setVisible(false)}` is redundant and unnecessary

**Describe alternatives you've considered**
---
Provide a `useModal` hook, so we can access modal props and close the modal itself inside a modal screen.
When an operation completed inside modal, we can close the modal such as this way:
```tsx
const modal = useModal();

const onFinish = () => {
  /*
    My stuff here... When things are done, this modal has completed its work and it should be closed immediately 
  */
  modal.dismiss()
}
```
By `modal.dismiss()`, `Modal.onDismiss` should be called

**Additional context**
---
- "react-native": "~0.63.4",
- "react-native-paper": "^4.7.2",

**Comment by francesco-clementi-92** [comment]
Just put the redundant code in a function
```
const onFinish = () => {
   setVisible(false)
}

<Modal
          visible={visible}
          onDismiss={onFinish}
        >
  <ModalScreen onFinish={onFinish} />
</Modal>
```

**Comment by likeSo** [comment]
> Just put the redundant code in a function
> 
> ```
> const onFinish = () => {
>    setVisible(false)
> }
> 
> <Modal
>           visible={visible}
>           onDismiss={onFinish}
>         >
>   <ModalScreen onFinish={onFinish} />
> </Modal>
> ```

Yes, this does works.

 But I think if modal's works are done, the modal should close itself immediately. It should not be decided by the parent components, it's a part of the modal's work!

And, `onDismiss` is not the same as `onFinish`. The `onDismiss` callback is called when the user press outside of modal, and the `onFinish` callback is called when my modal's works are done, in this callback, I should only take care of my business logics, not modal's visibility
