### ISSUE TITLE
design problems with the roundness property

### ISSUE THREAD

**Issue by yayoalfredoortiz** [callstack/react-native-paper#2670]
Hi , I have problems in the design with the roundness property, it looks weird, could someone give me a solution please
 
<img width="416" alt="Captura de Pantalla 2021-04-19 a la(s) 9 49 27 a  m" src="https://user-images.githubusercontent.com/25714377/115257915-25b5c300-a0f6-11eb-9c89-f0b066c3e9d7.png">

I applied set the property of the textinput in this way
theme={{roundness: 25}}

"react-native-paper": "^4.7.2",
"react": "16.13.1",
"react-dom": "16.13.1", 
"react-native": "0.64.0",
"react-native-vector-icons":"8.1.0"

**Comment by lukewalczak** [comment]
Please check the latest library version `4.8.1`.

**Comment by yayoalfredoortiz** [comment]
Hi , I have the same problem with the version 4.8.1

**Comment by yayoalfredoortiz** [comment]
<img width="416" alt="Captura de Pantalla 2021-04-23 a la(s) 8 49 14 a  m" src="https://user-images.githubusercontent.com/25714377/115881542-776d8e80-a411-11eb-9ecf-6390f82dc2ec.png">

Hi lukewalczak  ,I have the same problem with the version 4.8.1.
