### ISSUE TITLE
Change Appbar Title Font  

### ISSUE THREAD

**Issue by 24thDawn** [callstack/react-native-paper#2675]
How can I change the font family of the Appbar title text?
Using the style prop like below doesn't work
`` <Appbar.Header style={styles.newfont}>``

react-native: 40.0.1
react-native-paper: 4.7.2
react-native-svg: 12.1.1-0

**Comment by lukewalczak** [comment]
Hey @24thDawn, you have to specify the `fontFamily` using `theme` prop on `Appbar.Header` component.

**Comment by relez** [comment]
Hi there, I am trying to override the font for the Appbar.Header but its not overriding the font, here is my code:

```
<Appbar.Header
    style={styles.appBar}
    theme={{
        fonts: {
            regular: {
                fontFamily: "AsapCondensed-Regular",
                fontWeight: "normal"
            }
        }
    }}
>
    <Appbar.Content title={t("dashboard.header")} />
</Appbar.Header>
```
Any help, please? Thanks
