### ISSUE TITLE
Lower case letters 'ygpq' cuts from down when we set height to TextInput

### ISSUE THREAD

**Issue by Parth15Ordex** [callstack/react-native-paper#2680]
### Current behaviour

When we set height to TextInput using style prop, height of text input sets smaller which is fine but when we type some lower case characters (e.g - 'qpgy') it cuts from down.

### Expected behaviour

All characters should be visible properly without cutting down in small height TextInput.

### Code sample

I have set below style to TextInput

textInputStyle : {
    height: RFValue(40),
    fontSize: RFValue(13),
    backgroundColor: Colors.color_white,
}

### Screenshots (if applicable)

![Simulator Screen Shot - iPhone 12 - 2021-04-23 at 20 21 48](https://user-images.githubusercontent.com/48586479/115891242-7d945700-a473-11eb-9af2-dcaaf0b54a6d.png)

### What have you tried

I have tried to set lineHeight property of textInput but it doesn't work.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.64.0
| react-native-paper    | ^4.8.0
| node                  | v14.16.0
| npm or yarn           | npm v6.14.11
| expo sdk              | --
| react-native-vector-icons              | --

**Comment by Parth15Ordex** [comment]
I have updated version of npm, and I am not using expo, yarn and react-native-vector-icons in my project.
Let me know if you need anything else.

**Comment by Parth15Ordex** [comment]
@lukewalczak any update on this?

**Comment by lukewalczak** [comment]
You cannot change the `height`, but you can tweak the `fontSize` to achieve the desired height, however currently it's working only for larger font sizes, so we need to fix to support smaller as well.

**Comment by Parth15Ordex** [comment]
@lukewalczak 
Yes for smaller font size it's not working so basically we are not able to decrease the height smaller than default height of TextInput so that's the problem...

**Comment by Parth15Ordex** [comment]
@lukewalczak 
Any update on this, when it can be fixed?

**Comment by lukewalczak** [comment]
> Any update on this, when it can be fixed?

Actually, it's hard to say once we'll be available to fix that functionality. In the meantime maybe you can use combination of prop called `dense` and your custom font size equal 13?

**Comment by Parth15Ordex** [comment]
> > Any update on this, when it can be fixed?
> 
> Actually, it's hard to say once we'll be available to fix that functionality. In the meantime maybe you can use combination of prop called `dense` and your custom font size equal 13?

Yes I have used it 13 but it's dynamic for different devices and also how can I use dense?

**Comment by lukewalczak** [comment]
> how can I use dense

`dense` is just a boolean, use it in the following way:

```
<TextInput
	...
	dense
/>
```

**Comment by Parth15Ordex** [comment]
> > how can I use dense
> 
> `dense` is just a boolean, use it in the following way:
> 
> ```
> <TextInput
> 	...
> 	dense
> />
> ```

What can we achieve using that prop?

**Comment by lukewalczak** [comment]
> What can we achieve using that prop?

Everything is described in the [documentation](https://callstack.github.io/react-native-paper/text-input.html#dense), please look on it

**Comment by kamil-maslowski** [comment]
Well the problem is still there... any fixes or workarounds?

**Comment by heltonbase** [comment]
> ### Comportamento atual
> Quando definimos a altura para TextInput usando o estilo prop, a altura da entrada de texto é menor, o que é bom, mas quando digitamos alguns caracteres minúsculos (por exemplo, 'qpgy'), ele diminui.
> 
> ### Comportamento esperado
> Todos os caracteres devem estar visíveis corretamente sem cortar em pequena altura TextInput.
> 
> ### Exemplo de código
> Eu defini o estilo abaixo como TextInput
> 
> textInputStyle : { altura: RFValue(40), fontSize: RFValue(13), backgroundColor: Colors.color_white, }
> 
> ### Capturas de tela (se aplicável)
> ![Captura de tela do simulador - iPhone 12 - 2021-04-23 às 20 21 48](https://user-images.githubusercontent.com/48586479/115891242-7d945700-a473-11eb-9af2-dcaaf0b54a6d.png)
> 
> ### O que você tentou
> Eu tentei definir a propriedade lineHeight de textInput, mas não funcionou.
> 
> ### Seu ambiente
> Programas	versão
> ios ou android	ios
> react-native	0,64,0
> react-native-paper	^4.8.0
> nó	v14.16.0
> npm ou fio	npm v6.14.11
> expo sdk	--
> react-native-vector-icons	--

Setting a lineHeight in the TextInput style worked for me
```
 <TextInput
      {...props} 
      style={{
         lineHeight: 28,
     }}
/>
```
