### ISSUE TITLE
Button's touchable area doesn't follow material design accessibility guide 

### ISSUE THREAD

**Issue by ArthurMbraga** [callstack/react-native-paper#2682]
I'm utilizing the react-native-paper's  Button 

```js
import { Button } from 'react-native-paper';

...

return (
   ...
   <Button
      mode="contained"
      onPress={() => navigation.navigate('register')}>
      Enviar
   </Button>
   ...
);

```  
<br/>
And got this issue at google play console: 
<br/><br/>

> Recommendation
> Consider increasing this clickable item.
> 
> The height of this item is 37dp. Consider setting the height of this touch area to 48dp or greater. know more 

![image](https://user-images.githubusercontent.com/16090650/115976026-21e3cf80-a540-11eb-830f-b92421864ad3.png)  

After checking at google material design guide, I found:
At  [Accessibility > Touch target spacing](https://material.io/design/usability/accessibility.html#layout-and-typography)

![image](https://user-images.githubusercontent.com/16090650/115976740-645cda80-a547-11eb-88b4-d714a989f9fe.png)

Actually, the react-native-paper's button touchable area has the same height of the button's content

So I have two questions:  
- Is that supossed to happen?
- Is there a way to change only the button's touchable area height?

---

software | version
-- | --
react-native | ^0.64.0
react-native-paper | ^4.8.1
react-native-vector-icons | ^8.1.0

**Comment by likeSo** [comment]
I think Paper should provide a way to remove all paddings on buttons.
Everything needs a customize way because fixed padding not compatible with all our scenes

**Comment by lukewalczak** [comment]
If you need to customize the `Button` please try to use [prop](https://callstack.github.io/react-native-paper/button.html#contentStyle) `contentStyle`.

**Comment by simonbengtsson** [comment]
Isn't this a major issue? To follow basic material design guidelines everyone would need to custumize the Button component. 
 Still an issue in the latest m3 theme as far as I can tell. 

The buttons with the m3 theme seems to be 40 dp in height but this is just the height of the container in [the material design spec](https://m3.material.io/components/buttons/specs#85e63496-f905-4978-ae35-69ab83b70536). The [touch target recommendation](https://m3.material.io/foundations/accessible-design/accessibility-basics#28032e45-c598-450c-b355-f9fe737b1cd8) is 48 as before.

**Comment by athrvk** [comment]
Any update on this issue ?
