### ISSUE TITLE
List.Accordion: The ripple effect gets outside of the specified allowed limits

### ISSUE THREAD

**Issue by leonelhenriquez** [callstack/react-native-paper#2683]
### Current behaviour

![screen1](https://user-images.githubusercontent.com/28768498/116030372-a6098600-a618-11eb-9f50-a64231ae67fe.png)

### Expected behaviour

![screen2](https://user-images.githubusercontent.com/28768498/116030377-a86be000-a618-11eb-86c7-99eef93261fe.png)

### Code sample
```javascript
  <List.AccordionGroup>
    <List.Accordion title="Accordion 1" id="1">
      <List.Item title="Item 1" />
    </List.Accordion>
    <List.Accordion title="Accordion 2" id="2">
      <List.Item title="Item 2" />
    </List.Accordion>
  </List.AccordionGroup>
```

[Expo](https://snack.expo.io/?name=List.AccordionGroup&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Flist-accordion-group.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20View%2C%20Text%20%7D%20from%20%27react-native%27%3B%0Aimport%20%7B%20List%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20(%0A%20%20%3CList.AccordionGroup%3E%0A%20%20%20%20%3CList.Accordion%20title%3D%22Accordion%201%22%20id%3D%221%22%3E%0A%20%20%20%20%20%20%3CList.Item%20title%3D%22Item%201%22%20%2F%3E%0A%20%20%20%20%3C%2FList.Accordion%3E%0A%20%20%20%20%3CList.Accordion%20title%3D%22Accordion%202%22%20id%3D%222%22%3E%0A%20%20%20%20%20%20%3CList.Item%20title%3D%22Item%202%22%20%2F%3E%0A%20%20%20%20%3C%2FList.Accordion%3E%0A%20%20%20%20%3CView%3E%0A%20%20%20%20%20%20%3CText%3E%0A%20%20%20%20%20%20%20%20List.Accordion%20can%20be%20wrapped%20because%20implementation%20uses%20React.Context.%0A%20%20%20%20%20%20%3C%2FText%3E%0A%20%20%20%20%20%20%3CList.Accordion%20title%3D%22Accordion%203%22%20id%3D%223%22%3E%0A%20%20%20%20%20%20%20%20%3CList.Item%20title%3D%22Item%203%22%20%2F%3E%0A%20%20%20%20%20%20%3C%2FList.Accordion%3E%0A%20%20%20%20%3C%2FView%3E%0A%20%20%3C%2FList.AccordionGroup%3E%0A)%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper)

### Your Environment

| software              | version
| --------------------- | -------
| android        | 7.0
| react-native          | 0.64.0
| react-native-paper    | 4.8.1
| node                  |  14.16.1
| npm or yarn           | yarn
| npm           | 6.14.2
| yarn           | 1.22.5
| react-native-vector-icons | 8.1.0

**Comment by lukewalczak** [comment]
Thanks for reporting the bug, I'm able to reproduce it and working on the fix.
