### ISSUE TITLE
TextInput without label wraps the value of the field

### ISSUE THREAD

**Issue by lmcjt37** [callstack/react-native-paper#2684]
### Current behaviour

When using a TextInput component, if I omit the label prop on iOS and then input something longer than the input's width, the value will wrap onto the next line. Also note I am not using multiline so this isn't expected behaviour.

### Expected behaviour

I should expect the value not to wrap, but instead clip the value of the text input.

### Code sample

```
import * as React from 'react';
import { TextInput } from 'react-native-paper';

const MyComponent = () => {
  const [text, setText] = React.useState('');

  return (
    <TextInput
      value={text}
      onChangeText={text => setText(text)}
    />
  );
};

export default MyComponent;
```

### Screenshots (if applicable)

![Screen Shot 2021-04-26 at 10 27 47 AM](https://user-images.githubusercontent.com/5430873/116060821-1ac0dc80-a67a-11eb-8cde-675817925246.png)

### What have you tried

Steps to fix: N/A

Steps to reproduce: 
- Use a standard paper text input
- Do not define any additional properties for the component, other than what's needed to change/update text
- Type into the input until the value is longer than the width of the input.
- Tap away from the input (blur) and notice how the value/text wraps (as seen in the screenshot)

### Your Environment

| software              | version
| --------------------- | -------
| ios        | iOS 14.4 (iPhone 11)
| android        | N/A
| react-native          | 0.63.4
| react-native-paper    | 4.8.1
| node                  | 16.0.0
| npm           | 7.10.0
| yarn           | 1.22.5
| expo sdk              | N/A
| react-native-vector-icons              | 8.0.0

**Comment by lmcjt37** [comment]
Upgraded some of the tooling, and reflected that in the edited comment. 

Issue is still appearing with environment details above. Not using Expo.

**Comment by lmcjt37** [comment]
Additionally, "outlined" mode appears to work as expected.

**Comment by lmcjt37** [comment]
I have managed to solve my requirements, by adjusting some styles based on the behaviour the padding creates after some investigation into how the paper component works and calculates the padding.

The styles I used to adjust to what I needed were;
```
textWrapFix: Platform.select({
  ios: {
    paddingBottom: 12,
    height: 52,
  },
}),
```
This adjusts it to match the expected 64 height set for a flat text input component. I also had to adjust my right icon adornments due to the additional padding, so would expect all adornments to be affected.

The bug is still present however, and doesn't function as expected where the value should simply clip rather than wrap as though it's a multiline.

**Comment by lukewalczak** [comment]
Hey @lmcjt37, that issue looks similarly to the [bug](https://github.com/facebook/react-native/issues/29068#issue-631523357) from react-native related to setting `textAlign` which we are handling within our [input](https://github.com/callstack/react-native-paper/blob/main/src/components/TextInput/TextInputFlat.tsx#L357) due to RTL.

More details: https://github.com/callstack/react-native-paper/issues/2581.

**Comment by lmcjt37** [comment]
@lukewalczak Looks like it is the exact same issue. `textAlign: 'auto'` has fixed the wrapping issue and added the expected ellipsis. 

Which is great as now I can remove the hack 😅 

Happy for this issue to be closed if not needed now.

**Comment by vpume** [comment]
this might help you too, altough the solution is for people using react-native-paper:
https://github.com/callstack/react-native-paper/issues/2581#issuecomment-2900611635
