### ISSUE TITLE
Accordion: Possibility to support transitions when collapse in and out

### ISSUE THREAD

**Issue by sahanatroam** [callstack/react-native-paper#2691]
https://github.com/callstack/react-native-paper/blob/837e9035689b05eb22b51950c79ef81c914f542d/src/components/List/ListAccordion.tsx#L249-L264

Example: https://material-ui.com/components/accordion/#simple-accordion

**Comment by likeSo** [comment]
I agree with you. 
Additional feature request: 
- Support customize chevron label of Accordion. For now, it's hard-coded by Paper.

**Comment by lukewalczak** [comment]
Hey @sahanatroam, I think that feature it's worth considering, however in the meantime you can run `LayoutAnimation` on list item press.

@likeSo could you please specify which line are you referring to?

**Comment by likeSo** [comment]
> Hey @sahanatroam, I think that feature it's worth considering, however in the meantime you can run `LayoutAnimation` on list item press.
> 
> @likeSo could you please specify which line are you referring to?

In `node_modules/react-native-paper/src/components/List/ListAccordion.tsx:228`:
```tsx
<MaterialCommunityIcon
              name={isExpanded ? 'chevron-up' : 'chevron-down'}
              color={titleColor}
              size={24}
              direction={I18nManager.isRTL ? 'rtl' : 'ltr'}
            />
```
I need to change the chevron label, or just provide a way to customize all the accordion content

I think every component should be fully customizable, so Paper can stay active and popular🌝

**Comment by lukewalczak** [comment]
@likeSo from version 4.8.0 there is an option to customize the component on the right side in `List.Accordion` using `right` [prop](https://callstack.github.io/react-native-paper/list-accordion.html#right)

**Comment by likeSo** [comment]
> @likeSo from version 4.8.0 there is an option to customize the component on the right side in `List.Accordion` using `right` [prop](https://callstack.github.io/react-native-paper/list-accordion.html#right)

Thank you, I upgraded `paper` in my project, and it can solve my problem, thank you!

**Comment by bryanjosue17** [comment]
> @likeSo from version 4.8.0 there is an option to customize the component on the right side in `List.Accordion` using `right` [prop](https://callstack.github.io/react-native-paper/list-accordion.html#right)

How i can do it? You have a specific example? I wanna change the color when is expanded the arrow

**Comment by lukewalczak** [comment]
Usage is exactly the same as for `left` prop:

```
<List.Accordion
  onPress={handlePress}
  right={(props) => (
    <List.Icon
      {...props}
      icon={expanded ? 'chevron-up' : 'chevron-down'}
      color={expanded ? 'red' : 'blue'}
    />
  )}
  title="Expandable list item"
>
  <List.Item title="List item 1" />
  <List.Item title="List item 2" />
</List.Accordion>
```
