### ISSUE TITLE
react-native paper button vector-icons float right

### ISSUE THREAD

**Issue by chetanmajithiya** [callstack/react-native-paper#2692]
I'm not able to show icon in right-side it's by default left side!

**Comment by lukewalczak** [comment]
Hey @chetanmajithiya What component is your problem about? Are you able to introduce a piece of code or share a [snack](https://snack.expo.io/)?

**Comment by chetanmajithiya** [comment]
@lukewalczak 

`<Button icon="camera" mode="contained" onPress={() => {}}>Press Me</Button>`

it will be by default show left side camera icon in the button, but I want to show it as right side, but I did not find any props like `iconSide="left/right"` in the docs.

thanks

**Comment by lukewalczak** [comment]
Hey @chetanmajithiya, Material Design which we are following indicates only _leading_ icon in `Button` that's why there is no option to choose the side.
