### ISSUE TITLE
Snackbar action button not working.......please help...

### ISSUE THREAD

**Issue by krishnawork** [callstack/react-native-paper#2698]
import React, { useState, useEffect } from "react";
import {
  StyleSheet,
  View,
  StatusBar,
  ImageBackground,
  Text,
  TextInput,
  TouchableOpacity,
} from "react-native";
import EvilIconsIcon from "react-native-vector-icons/EvilIcons";
import IoniconsIcon from "react-native-vector-icons/Ionicons";
import firebase, { db } from "../model/firebase";
import * as Google from "expo-google-app-auth";
import * as Facebook from "expo-facebook";
import { ProgressBar, Colors, Snackbar,Button } from "react-native-paper";

function Login(props) {
  const [loading, setloading] = useState(false);
 
  const [email, setemail] = useState("");
  const [password, setpassword] = useState("");
  const [error, setError] = useState("");
  const [visible, setVisible] = React.useState(false);

  const onToggleSnackBar = () => setVisible(!visible);

  const onDismissSnackBar = () => setVisible(false);

  const signIn = async () => {
    setloading(true);
    try {
      const response = await firebase
        .auth()
        .signInWithEmailAndPassword(email, password);
      if (response) {
        setloading(false);
        setError("");
        console.log("xdata", response);
        // console.log("response", response.user.uid);
        // navigation.navigate('home')
      }
    } catch (err) {
      setloading(false);
      setVisible(true);
      setError("Please Enter Right Email and Password.....");
      // console.log("err")
      //   setError("Please Enter Right Email and Password.....");
    }
  };

  return (
    <View style={styles.root}>
      <ProgressBar
        progress={0.5}
        color={Colors.red800}
        indeterminate={loading}
        visible={loading}
      />
      <Snackbar
        visible={visible}
        onDismiss={onDismissSnackBar}
        action={{
          label: "Dismiss",
          onPress: () => {alert("helo")}
        }}
      >
        {error}
      </Snackbar>      
      <StatusBar barStyle="light-content" backgroundColor="rgba(0,0,0,0)" />
      <View style={styles.background}>
        <ImageBackground
          style={styles.rect}
          imageStyle={styles.rect_imageStyle}
          source={require("../assets/bgc.png")}
        >
          <View style={styles.logoColumn}>
            <View style={styles.logo}>
              <View style={styles.endWrapperFiller}></View>
              <View style={styles.text3Column}>
                <Text style={styles.text3}>STOCK TEACHERS</Text>
                <View style={styles.rect7}></View>
                <Text style={styles.text3subtitle}>FIND YOUR COACH</Text>
              </View>
            </View>
            <View style={styles.form}>
              <View style={styles.usernameColumn}>
                <View style={styles.username}>
                  <EvilIconsIcon
                    name="user"
                    style={styles.icon22}
                  ></EvilIconsIcon>
                  <TextInput
                    placeholder="Enter Your Email Here"
                    placeholderTextColor="rgba(255,255,255,1)"
                    secureTextEntry={false}
                    onChangeText={setemail}
                    style={styles.usernameInput}
                  ></TextInput>
                </View>
                <View style={styles.password}>
                  <EvilIconsIcon
                    name="lock"
                    style={styles.icon2}
                  ></EvilIconsIcon>
                  <TextInput
                    placeholder="Password"
                    placeholderTextColor="rgba(255,255,255,1)"
                    secureTextEntry={true}
                    onChangeText={setpassword}
                    style={styles.passwordInput}
                  ></TextInput>
                </View>
              </View>
              <View style={styles.usernameColumnFiller}></View>
              <TouchableOpacity onPress={() => signIn()} style={styles.button}>
                <Text style={styles.text2}>LOG IN</Text>
              </TouchableOpacity>
            </View>
            <View>
              <Text style={styles.loginwithtext}>Log in with </Text>
            </View>

            <View style={styles.iconcontainer}>
              <IoniconsIcon
                name="logo-google"
                style={styles.iconitem}
                onPress={() => Googlelogin()}
              ></IoniconsIcon>

              <IoniconsIcon
                style={styles.iconitem}
                name="logo-facebook"
                onPress={() => facebooklogin()}
              ></IoniconsIcon>
              <IoniconsIcon
                style={styles.iconitem}
                name="ios-phone-portrait"
                onPress={() => navigation.navigate("phonelogin")}
              ></IoniconsIcon>
            </View>
          </View>
          <View style={styles.logoColumnFiller}></View>
          <View style={styles.footerTexts}>
            <TouchableOpacity
              onPress={() => props.navigation.navigate("SignUp")}
              style={styles.button2}
            >
              <View style={styles.createAccountFiller}></View>
              <Text style={styles.createAccount}>Create Account</Text>
            </TouchableOpacity>
            <View style={styles.button2Filler}></View>
            {/* <Text style={styles.needHelp}>Need Help?</Text> */}
            <Text style={styles.needHelp}>Forgot Password ? </Text>
          </View>
        </ImageBackground>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    // backgroundColor: "linear-gradient(to bottom, #991e61 0%, #4d052c 100%)"
    backgroundColor: "rgb(255,255,255)",
  },
  background: {
    flex: 1,
  },
  rect: {
    flex: 1,
    // background: "linear-gradient(to bottom, #991e61 0%, #4d052c 100%)",
  },
  rect_imageStyle: {},
  logo: {
    width: "70%",
    height: 111,
    alignSelf: "center",
  },
  endWrapperFiller: {
    flex: 1,
  },
  text3: {
    color: "rgba(255,255,255,1)",
    fontSize: 30,
    // marginBottom: 4
  },
  text3subtitle: {
    color: "rgba(255,255,255,1)",
    fontSize: 15,
  },
  rect7: {
    height: 8,
    backgroundColor: "#911E4D",
    // backgroundColor: "#C9AC1D",
    marginRight: 4,
  },
  text3Column: {
    marginBottom: 6,
    marginLeft: 2,
    marginRight: -1,
  },
  form: {
    height: 230,
    marginTop: 59,
  },
  username: {
    height: 59,
    backgroundColor: "rgba(251,247,247,0.25)",
    borderRadius: 5,
    flexDirection: "row",
  },
  icon22: {
    color: "rgba(255,255,255,1)",
    fontSize: 30,
    marginLeft: 20,
    alignSelf: "center",
  },
  usernameInput: {
    height: 30,
    color: "rgba(255,255,255,1)",
    flex: 1,
    marginRight: 11,
    marginLeft: 11,
    marginTop: 14,
  },
  password: {
    height: 59,
    backgroundColor: "rgba(253,251,251,0.25)",
    borderRadius: 5,
    flexDirection: "row",
    marginTop: 27,
  },
  icon2: {
    color: "rgba(255,255,255,1)",
    fontSize: 33,
    marginLeft: 20,
    alignSelf: "center",
  },
  passwordInput: {
    height: 30,
    color: "rgba(255,255,255,1)",
    flex: 1,
    marginRight: 17,
    marginLeft: 8,
    marginTop: 14,
  },
  usernameColumn: {},
  usernameColumnFiller: {
    flex: 1,
  },
  button: {
    height: 59,
    backgroundColor: "rgba(31,178,204,1)",
    // backgroundColor: "#C9AC1D",
    borderRadius: 5,
    justifyContent: "center",
  },
  text2: {
    color: "rgba(255,255,255,1)",
    // color: "#C9AC1D",
    alignSelf: "center",
  },
  loginwithtext: {
    marginTop: 40,
    color: "rgba(255,255,255,1)",
    alignSelf: "center",
  },
  iconcontainer: {
    marginTop: 30,
    paddingLeft: 40,
    paddingRight: 40,
    flexDirection: "row",
    color: "rgba(128,128,128,1)",
    justifyContent: "space-between",
  },
  iconitem: {
    fontSize: 40,
    margin: 15,
    color: "silver",
  },
  logoColumn: {
    marginTop: 130,
    marginLeft: 41,
    marginRight: 41,
  },
  logoColumnFiller: {
    flex: 1,
  },
  footerTexts: {
    height: 14,
    flexDirection: "row",
    marginBottom: 36,
    marginLeft: 37,
    marginRight: 36,
  },
  button2: {
    width: 104,
    height: 14,
    alignSelf: "flex-end",
  },
  createAccountFiller: {
    flex: 1,
  },
  createAccount: {
    color: "rgba(255,255,255,0.5)",
  },
  button2Filler: {
    flex: 1,
    flexDirection: "row",
  },
  needHelp: {
    color: "rgba(255,255,255,0.5)",
    alignSelf: "flex-end",
    marginRight: -1,
  },
  icon: {
    flexDirection: "row",
    color: "rgba(128,128,128,1)",
    alignSelf: "center",
  },
});

export default Login;

**Comment by krishnawork** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `react-native`
> * `react-native-paper`
> * `react-native-vector-icons`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

"react-native-paper": "^4.8.1",

**Comment by lukewalczak** [comment]
Hey @krishnawork please specify what exactly doesn't work for you in `Snackbar` component and please try to create a [snack](https://snack.expo.io/) with bug reproduction or refactor your snippet code to allow us debug the issue.
