### ISSUE TITLE
TextInput mode='outlined' background: transparent >> Incorrect output

### ISSUE THREAD

**Issue by syedquadri1982** [callstack/react-native-paper#2699]
<TextInput theme={
            {
              colors: {
                primary: 'black', 
                placeholder: 'blue',
                background: 'transparent'
              }
            }
            } mode="outlined" label="Email" value="" /> 

![image](https://user-images.githubusercontent.com/82794945/117103146-210f3100-adbd-11eb-8ffe-8f0b891841b6.png)

"react-native-vector-icons": "^8.1.0"
"react-native-paper": "^4.8.1"
"react-native": "0.64.0"

**Comment by syedquadri1982** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `react-native`
> * `react-native-paper`
> * `react-native-vector-icons`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

"react-native-vector-icons": "^8.1.0"
"react-native-paper": "^4.8.1"
"react-native": "0.64.0"

**Comment by lukewalczak** [comment]
Hey @syedquadri1982, it happens when `backgroundColor` is `transparent` since it's applied to label as well which results in visible border. I can suggest you to pass the same color which you have for container (_violet-ish_) as a `background`.

**Comment by MakChan** [comment]
Hey @lukewalczak, suppose we have a linear gradient as the background, in that case we need to set `backgroundColor` as `transparent`. So, is there any other solution?

**Comment by SatyamBansal** [comment]
Same problem I am having, i have gradient as the background so I can't pass background colour specifically, and setting background as transparent resulting in above mentioned problem

**Comment by vyas-git** [comment]
Yes , Same for me you can maintain separate labelBackgroundColor in library and pass same pixel color of background container for each input field ..



or simply I used placeholder instead of label , removed label
