### ISSUE TITLE
Touchable 

### ISSUE THREAD

**Issue by ahmedlhanafy** [callstack/react-native-paper#27]
Cross-platform touchable component that implements ripple effect. In Android we will use TouchbaleNativeFeedback in IOS we need to bridge a native library or implementation

**Comment by SkyzohKey** [comment]
You can do that without native code:  https://github.com/TheToxProject/shathui/blob/master/src/components/Touchable.js

**Comment by ferrannp** [comment]
We decided we won't be working on this issue for now.

**Comment by chuihinwai** [comment]
This there something that could be borrowed from https://github.com/xotahal/react-native-material-ui? They have cross platform ripples. This is the best and most up-to-date material library, I'd love to help get the ripple on iOS working via pull request if it's possible

**Comment by sraka1** [comment]
@ferrannp @grabbou it's been 2 years since the last update. Will this ever hit the roadmap? PRs accepted?

**Comment by MonliH** [comment]
@ferrannp Just bumping this again, as it's been another year. This would be a great addition to the already awesome library!
