### ISSUE TITLE
Use pure component in BottomNavigation example

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#270]

**Comment by Rafaell416** [comment]
Hi, @ferrannp  could you please give a little bit more information about the issue? 

do you mean doing this ? 

`
import { PureComponent } from 'react';

export default class Example extends PureComponent {
  render() {
    return <SomeComponent someProp={props.someProp}/>
  }
}
})

`

**Comment by ferrannp** [comment]
Hello @Rafaell416, not really, what we meant here is to follow the BottomNavigation docs https://callstack.github.io/react-native-paper/bottom-navigation.html.

Specifically this part:

```js
_renderScene = BottomNavigation.SceneMap({
  music: MusicRoute,
  albums: AlbumsRoute,
  recents: RecentsRoute,
});
```

Which is explained here https://callstack.github.io/react-native-paper/bottom-navigation.html#renderScene.

Let me know if you need something more! :)
