### ISSUE TITLE
TextInput can't style padding and underline.

### ISSUE THREAD

**Issue by likon416** [callstack/react-native-paper#2700]
Hello.

I'm trying to style TextInput as it is so bulky. 
<img width="300" alt="Screenshot 2021-05-05 at 15 45 39" src="https://user-images.githubusercontent.com/83599161/117160560-1d79ab00-adb9-11eb-9cf1-65aaead80dc5.png">

How I can style paddings/margins, the height of this input? Documentation not saying anything about styling it although on the ios example app I see small input fields. 

Also how to remove the outline? how to make it transparent fully?

Would be great if you would make this iOS example app public so we can go and see how to style these components.

**Comment by pinpointpanda** [comment]
@likon416 the first place to look would be to add the `dense` prop, which will make the component much smaller.
There are some things you can do with the `style` prop, but for real fine-grained control (e.g. changing the label padding) there isn't actually a prop exposed for that, so you would need to tweak in node_modules and use patch package or submit a PR (or feature request) here. But it's only label padding specifically where I've ever needed to do that myself.

Definitely start with `dense` though - that may well be exactly what you need. And you can remove the underline if you don't want it by using `underlineColor={'transparent'}`
