### ISSUE TITLE
Checkbox.Android bugged for react-native-web

### ISSUE THREAD

**Issue by alessiocancian** [callstack/react-native-paper#2711]
### Current behaviour

Sometimes when a checkbox is unchecked it keeps a border with the checked tint color, and the 'v' icon gets hidden by borders...
This is probably related to some animation not working well with react-native-web.

### Expected behaviour

The checkbox should display normally

### Screenshots (if applicable)

![IMG_20210509_233813.jpg](https://user-images.githubusercontent.com/18497523/117587742-a9743580-b11f-11eb-9ba2-ad2efff80fe2.jpg)
![IMG_20210509_233756.jpg](https://user-images.githubusercontent.com/18497523/117587748-ada05300-b11f-11eb-868d-b6fdda23767e.jpg)

**Comment by lukewalczak** [comment]
Hey @alessiocancian, could you please try to create the [snack](https://snack.expo.io/) with bug reproduction which will help investigate the problem?
