### ISSUE TITLE
In the example, the `yarn` command is not available

### ISSUE THREAD

**Issue by fungmo** [callstack/react-native-paper#2717]
I pulled the repository to the local and wanted to run the `Example` in the repository, but the `yarn` command did not respond.

![image](https://user-images.githubusercontent.com/16655229/117765204-30302c00-b260-11eb-8f84-a195b7ad53a3.png)

> my node npm yarn version

![image](https://user-images.githubusercontent.com/16655229/117765808-22c77180-b261-11eb-8be3-d7bd6e7e6148.png)

---

**Versions:**
* yarn: 1.22.10
* node: 14.16.1
* npm: 6.14.12

**Comment by BartoszKlonowski** [comment]
I have the same problem with latest installed:
* yarn: 1.22.10
* node: 14.17.3
* npm: 7.19.1

There's no output of any `yarn` command.
`npm` installs packages, but hangs near the finish.

@fungmo Did you manage to solve the issue on your side?

**Comment by fungmo** [comment]
@BartoszKlonowski 

You need to configure yarn in global variables

**Comment by BartoszKlonowski** [comment]
@fungmo Thank you for a fast response 👍 
But what do you mean in global variables? You mean in environment variables? But wouldn't it throw `'yarn' is not recognized as the name...` error if it would be in global variables?
Moreover, `yarn` command is correctly recognized in all my other repos/projects.

**Comment by fungmo** [comment]
@BartoszKlonowski 
In your computer environment variables, manually configure。
`path` add `C:\Users\Administrator\AppData\Local\Yarn\bin`

**Comment by BartoszKlonowski** [comment]
So like I guessed: you meant in the environment variables.
Thing is that `yarn` is already added to environment variables and is recognized in other projects. Moreover, *AppData/Local/Yarn/bin* contains only `react-native-windows-init`, no yarn binary.
Still I gave it a try and adding this to my env variables did not change a thing.

**Comment by fungmo** [comment]
@BartoszKlonowski 
Did you try to restart the computer? If it still doesn't work, it is beyond my scope.
