### ISSUE TITLE
At this line, you should remove the opening and closing parentheses

### ISSUE THREAD

**Issue by galgamp** [callstack/react-native-paper#2719]
https://github.com/callstack/react-native-paper/blob/2f21b9ad75c56d0307bfaaffaa73e5bb8c8c029c/src/components/List/ListAccordion.tsx#L234

react-native-paper | ^4.8.1

**Comment by lukewalczak** [comment]
Hey @galgamp, prettier adds parentheses around ternary expression in our whole project, there is no need to change that.

**Comment by galgamp** [comment]
Have you tested? It doesn't work in my project with parentheses, if I remove them it works. What can i do so ?

**Comment by galgamp** [comment]
here is my code which does not work
`
```tsx
<List.Accordion
    left={() => <FontAwesomeIcon
            color="#fff"
            icon={faWineBottle}
            size={20}
          ></FontAwesomeIcon>}
    right={(props) => {
      if (props.isExpanded) {
        return (
          <FontAwesomeIcon
            color="#fff"
            icon={faChevronUp}
            size={20}
          ></FontAwesomeIcon>
        );
      } else {
        return (
          <FontAwesomeIcon
            color="#fff"
            icon={faChevronDown}
            size={20}
          ></FontAwesomeIcon>
        );
      }
    }}
  >
````

left props is working, but not the right props. And if i remove parentheses in node modules, right props is working.

**Comment by lukewalczak** [comment]
It works properly with both props, please check the [snack](https://snack.expo.io/ckWOZa9Jt) example. I guess that probably something has to be wrong with your project setup or environment.

**Comment by galgamp** [comment]
I finally solved the problem, I updated my expo version from 40.0.0 to 41.0.0 and it works. It's still a mystery.
