### ISSUE TITLE
New Component: Loading Toast (HUD)

### ISSUE THREAD

**Issue by likeSo** [callstack/react-native-paper#2720]
**Is your feature request related to a problem? Please describe.**
I don't know how to show a loading toast(A dialog with an `ActicityIndicator` and an optional title) when networking happens.  
A loading toast looks like this ( iOS SVProgressHUD)
![image](https://user-images.githubusercontent.com/12247340/117913402-e274fb80-b313-11eb-8a7b-a6d17faf34ff.png)

**Describe the solution you'd like**
As for now, Papers `Dialog` component with an ActivityIndicator and a title is also a good choice, but we need a way to show them easily such as this:
- `Toast.show()`
- `Toast.showInfo([message])`
- `Toast.showError([message])`
- `Toast.hide()`

**Describe alternatives you've considered**

**Additional context**

**Comment by lukewalczak** [comment]
Could you please point us to the Material Design documentation with that component specification?

**Comment by likeSo** [comment]
Actually, a `Dialog` with a title and an activity indicator is pretty close to my requirements: 
![IMG_204C89CE9064-1](https://user-images.githubusercontent.com/12247340/117972079-47087880-b35d-11eb-807c-001ab988a18f.jpeg)
I wanna show a dialog like this when loading a screen. 
But I need an easier way to operate this because I want to control the dialog visibility in the network layer, not just JSX.
As for now, I am only used RefreshControls in my project, which is so bad because the user doesn't know what's happening when he presses a button

> Could you please point us to the Material Design documentation with that component specification?

**Comment by lukewalczak** [comment]
I cannot find similar component in Material Design which our library follows and we are not going to build custom components which are not specified in the guidelines.

The screenshot which you attached is just the example of `Dialog` usage and it's presenting how users can compose different component from the library.

**Comment by likeSo** [comment]
So may I have an ask, when your user presses a button or uploads an image or something, which component should be used for feedback?
What if I wanna control it in my network layer? I mean display loading toast before network begins, close toast after response end?

**Comment by likeSo** [comment]
In other words, how do I display Toasts in Paper? Snakbars cannot prevent user interactions and the Dialogs are too heavy.....
So they can't replace Toasts. A complete application needs Toast components!

**Comment by lukewalczak** [comment]
You can create your custom absolutely positioned `View` with `ActivityIndicator` in the middle, which is visible when action is performed. I quickly created something like that on the [snack](https://snack.expo.io/2ykvFSng1)

**Comment by likeSo** [comment]
Great! And is the Toast component in `Paper`s roadmap? After all, there is no existing `Toast` API built-in. A complete application needs this!
We need a way to easily show or hide `Toast`s such as `Toast.show(), Toast.hide()`
