### ISSUE TITLE
Datatable appears and functions fine in simulator, but not in TestFlight version of application

### ISSUE THREAD

**Issue by john-martinez-729** [callstack/react-native-paper#2725]
Hey everyone,

I'm working on a React Native app using RNP for Datatables. It works fine in the simulator and on the Android version, however the iOS version (currently on TestFlight) is not displaying tables properly. They simply don't show up.

Any advice or assistance with this would be greatly appreciated!

**Comment by rufat** [comment]
Any fix?

**Comment by AshishAcharya083** [comment]
Not fixed yet
