### ISSUE TITLE
Android: Material Bottom Tab Nav + Nested Stack Nav causing flicker

### ISSUE THREAD

**Issue by quicksnap** [callstack/react-native-paper#2726]
**Note** this is a copy paste issue from https://github.com/react-navigation/react-navigation/issues/9560 -- Let me know if anything is missing. Thanks in advance! Awesome library.

**Current Behavior**

Flickering when switching tabs

**Expected Behavior**

No flicker! :)

**How to reproduce**

I've set up a simple example here: 
- https://expo.io/@quicksnap/projects/material-bottom-flicker-repro
- https://github.com/quicksnap/material-bottom-flicker-repro

This is the boilerplate Expo init project, but with react-paper and material bottom tab swapped out. Switching to the second tab will cause a flicker on my phone (Android 11, Pixel 3)

This issue may be related: https://github.com/react-navigation/react-navigation/issues/9256

Attached a video of my other project with some colors: 

https://user-images.githubusercontent.com/1199742/117392635-542def00-aea7-11eb-9b55-8401d9e48399.mp4

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | Android
| @react-navigation/native               | 5.9.4
| @react-navigation/material-bottom-tabs | 5.3.15
| react-native-paper                     | 4.8.1
| react-native                           | 0.63.4
| expo                                   | 41.0.1
| node                                   | 16
|  yarn                            | 1.22.10
| react-native-vector-icons  | 8.1.0

**Comment by quicksnap** [comment]
Updated

**Comment by quicksnap** [comment]
Like many with Expo, I'm somewhat locked in to 0.63.4.

**Comment by quicksnap** [comment]
Still a problem

**Comment by quicksnap** [comment]
![yNlQWRM (1)](https://user-images.githubusercontent.com/1199742/126854543-a32837c4-af99-4191-a408-fc24af8bf1f4.jpeg)

**Comment by gloredo** [comment]
Same problem here.

**Comment by palaganaskurl** [comment]
Same problem here. I have three bottom tabs, only flickers in the first two tabs, the third one doesn't flicker.

**Comment by lukewalczak** [comment]
Do the issue still exists on the latest version or material bottom tabs or react native paper?

**Comment by GaylordP** [comment]
@lukewalczak 5-rc version of react-native-paper fixes the problem :)

**Comment by lukewalczak** [comment]
@GaylordP glad to hear that, I hope it's working properly on `4.12.5` as well. Closing the issue then.
