### ISSUE TITLE
Material Bottom Tab with nested Stack Navigator: Inactive tabs are not properly removed from DOM

### ISSUE THREAD

**Issue by schaefermichael** [callstack/react-native-paper#2727]
Copied over from https://github.com/react-navigation/react-navigation/issues/9265

**Current Behavior**

- What code are you running and what is happening?
See [Snack](https://snack.expo.io/@schaefermichi/react-navigation-materialbottomtabnavigator-and-stacknavigator-issue)
When using Stack Navigators inside a Material Bottom Tab Navigator and navigating between the tabs, they are overlaying each other.

**Expected Behavior**

- What do you expect should be happening?
The second stack navigator should not be clickable when navigating back

**How to reproduce**
See [Snack](https://snack.expo.io/@schaefermichi/react-navigation-materialbottomtabnavigator-and-stacknavigator-issue)
Run Web. Once you navigate to tab two and navigate back to tab one, it's still being overlayed by tab two (you can see the pointer area of the button in the second tab).

**Your Environment**
| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | Web |
| @react-navigation/native               | 5.9.2 |
| @react-navigation/stack | 5.14.2 |
| @react-navigation/material-bottom-tabs | 5.3.13 |
| react-native-paper                     | 4.7.0 |
| react-native                           | 0.63.3 |
| expo                                   | 40.0.0 |
| node                                   | 12.16.1 |
| npm or yarn                            | npm |

**Comment by lukewalczak** [comment]
Hey @schaefermichael, please try to update `react-native-paper` to `4.8.1`, the issue should be fixed via [merged PR](https://github.com/callstack/react-native-paper/pull/2552)

**Comment by Decimator** [comment]
Hi @lukewalczak, I'm seeing the same issue as @schaefermichael is describing. This is with `react-native-paper@4.8.1` installed. Based on the previously merged PR you linked, I think the issue has something to do with the invisible screen still being overlaid on top of the desired screen, so nothing is clickable.

Inspecting the HTML shows that the previous screen is still on the DOM as @schaefermichael referenced, but it is opacity 0 as that merged PR fixes. I think this is a separate bug.

**Comment by kchoo1118** [comment]
Is this issue resolved?

**Comment by misterjacket** [comment]
I still have this issue right now.
