### ISSUE TITLE
TextInput content scrolls in outlined mode on Android

### ISSUE THREAD

**Issue by pedrobneto** [callstack/react-native-paper#2730]
### Current behaviour

When height property is set on an outlined input, it becomes scrollable when focused

Edit: only happens on Android

### Expected behaviour

TextInput should not be scrollable

### Code sample

`import * as React from 'react';
import {TextInput} from 'react-native-paper';

export default function App() {
  return (
        <TextInput
          style={{marginTop: 24, height: 40}}
          mode='outlined'
          placeholder='This placeholder will scroll when focused'
        />
  );
}`

### Screenshots (if applicable)

![input-bug](https://user-images.githubusercontent.com/15621292/118539241-94059980-b725-11eb-9f6d-f8d07a3b9f25.gif)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          | "4.13.0"
| react-native-paper    | "^4.8.1"
| node                  | "14.7.0"
| npm or yarn           | "7.12.0"
| expo sdk              |  "3.24.0"

Snack that reproduces the issue:
[https://snack.expo.io/6tTczRnvw](url)

**Comment by lukewalczak** [comment]
Hey @PedroBern, I will check that, however since you set the height on `40` maybe you can use the [prop](https://callstack.github.io/react-native-paper/text-input.html#dense) `dense` as a workaround?

**Comment by pedrobneto** [comment]
Hi @lukewalczak, thanks for replying. I'm currently using dense, but this happens regardless of the height set, it will still "scroll", which makes it impossible to use inside a SrollView, for example.

**Comment by lukewalczak** [comment]
@PedroBern Without specifying the height and with `dense` prop, I'm not able to observe the input scrolling issue on the [snack](https://snack.expo.io/lBhW9y4Fs). Do I miss something?

**Comment by pedrobneto** [comment]
@lukewalczak, you do need to specify the height to reproduce it, I meant that it doesn't matter what height value you use, the bug still happens. Using the dense prop without height is working for me as well.

**Comment by sommcz** [comment]
same here, on android. If i specify any height, it happens. Calculated paddingTop/Bottom is probably too big. But if i change it to zero (with render prop), it works as expected in my case (text is already aligned in the center so paddingTop/Bottom is not needed for my single line case).

**Comment by lukewalczak** [comment]
@sommcz could you please attach the snack presenting the issue?

**Comment by sommcz** [comment]
https://snack.expo.dev/wV8wWJ9pS

Type some text and drag it up and down.

**Comment by Ahaseeb98** [comment]
facing same issue on android any solution for this issue other then dense prop?

**Comment by sommcz** [comment]
> facing same issue on android any solution for this issue other then dense prop?

i've used render prop to render TextInput with overriden style (paddingTop/Bottom: 0) => it works.

**Comment by rahmanharoon** [comment]
Whats the solution for this

**Comment by H4mxa** [comment]
any update on this issue,

**Comment by Ujjwal-Neupane** [comment]
Giving maxHeight and justifyContent: 'center' worked for me

**Comment by Dhurika-V** [comment]
> > facing same issue on android any solution for this issue other then dense prop?
> 
> i've used render prop to render TextInput with overriden style (paddingTop/Bottom: 0) => it works.

can you please share the snack? I'm getting like two TextInput one over another, one with default props.

**Comment by ffkraemer** [comment]
This worked for me: 

`{
  includeFontPadding: false,
  padding: 0,
  margin: 0
}`
