### ISSUE TITLE
Is there a way to center the text of the snackbar?

### ISSUE THREAD

**Issue by SantyLorenzo** [callstack/react-native-paper#2731]
Hi there,
I am trying to replicate this snackbar:

![image](https://user-images.githubusercontent.com/43711998/118559608-8e687d80-b73e-11eb-8f67-323e8255a9b9.png)

but setting text-align or justify-content doesn't do the work.
I also tried adding a ```Text``` tag as children but the result doesn't change.
Is there a way to achieve this?

This is the code for my snackbar and styles:

![image](https://user-images.githubusercontent.com/43711998/118559696-b2c45a00-b73e-11eb-84b4-fdbf83cc6abf.png)
![image](https://user-images.githubusercontent.com/43711998/118558854-970c8400-b73d-11eb-81be-2657c74068f1.png)
![image](https://user-images.githubusercontent.com/43711998/118559820-e901d980-b73e-11eb-867c-e7d294d9bc2f.png)

**Comment by lukewalczak** [comment]
Hey @SantyLorenzo, you can do that by passing `Text` component with `style: {{textAlign: 'center'}}` as a children into `Snackbar`. Please look at the [snack](https://snack.expo.io/xL1d-LEiZ) example.

**Comment by SantyLorenzo** [comment]
Hey @lukewalczak, in the example the snackbar text is not centered.

**Comment by DoctorJohn** [comment]
@SantyLorenzo [This snack](https://snack.expo.io/@doctorjohn/centered-text-in-snack-bar) appears to be working. Have a look. The material design specs specify that the text should be left aligned, thats propbably why this library does not provide a simple option to center the text.

**Comment by Karemhz** [comment]
> Hey @SantyLorenzo, you can do that by passing `Text` component with `style: {{textAlign: 'center'}}` as a children into `Snackbar`. Please look at the [snack](https://snack.expo.io/xL1d-LEiZ) example.

It doesn't work

**Comment by Karemhz** [comment]
> @SantyLorenzo [This snack](https://snack.expo.io/@doctorjohn/centered-text-in-snack-bar) appears to be working. Have a look. The material design specs specify that the text should be left aligned, thats propbably why this library does not provide a simple option to center the text.

Didn't work on android

**Comment by fmohtadi99** [comment]
@SantyLorenzo 
Yes you can, I found it hardly :))
Open this file:
"[PROJECT]\node_modules\react-native-paper\src\components\Snackbar.tsx"
Go to line 210. You might have:
`<Text
          style={[
            styles.content,
            { marginRight: action ? 0 : 16, color: colors.surface},
          ]}
        >
          {children}
        </Text>`
Change this to:
`
<Text
          style={[
            styles.content,
            { marginRight: action ? 0 : 16, color: colors.surface, textAlign:'center' },
          ]}
        >
          {children}
        </Text>
`
**NOTE: textAlign:'center' ADDED!**

This worked for me :) Have fun.
