### ISSUE TITLE
Prop missing: Drawer.Item's right prop

### ISSUE THREAD

**Issue by codakkk** [callstack/react-native-paper#2732]
### Current behaviour

From documentation (https://callstack.github.io/react-native-paper/drawer-item.html) we can see that there should be a "right" prop.
right: "Callback which returns a React element to display on the right side. For instance a Badge."
When we try to use the prop, nothing happens and errors come out.

### Expected behaviour

From documentation, there should be a "right" prop.

### Code sample
```typescript 
<Drawer.Item
    label="Theme"
    icon="wb-sunny"
    right={pppp => <CustomSwitch />}
/>
```

### Screenshots (if applicable)

None

### What have you tried

Updating, etc.

### Your Environment

| software              | version
| ------------------ | -------
| android               | any
| react-native        | 0.64.0
| rn-paper             | 4.8.1
| node                   | v14.5.0
| yarn                    | v1.22.4

**Comment by lukewalczak** [comment]
Hey @codakkk, that feature will be introduced in the upcoming release. In the meantime you can install paper from the `main` branch to have that functionality.

**Comment by codakkk** [comment]
> Hey @codakkk, that feature will be introduced in the upcoming release. In the meantime you can install paper from the `main` branch to have that functionality.

Thank you!

**Comment by noctivityinc** [comment]
@codakkk This apepars to have been released in v5 but doesnt appear to work:

```
   <DrawerItem
                key={"dp_" + index}
                icon={({ color, size }) => (
                  <MaterialCommunityIcons
                    name="folder"
                    color={color}
                    size={size}
                  />
                )}
                label="Hello"
                right={({ color }) => (
                  <Badge>6</Badge>
                )}
                onPress={() => {}}
              />
```

Any thoughts?
