### ISSUE TITLE
Unable to remove box-shadow (elevation) on Card component (iOS)

### ISSUE THREAD

**Issue by g-hamilton** [callstack/react-native-paper#2733]
"react-native-paper": "^4.8.1"

Hi, I'm trying to remove the box-shadow completely on the Card component. Setting `elevation={0}` seems to work on web, but doesn't appear to be working on iOS (untested on Android).

When I preview on Snack using iOS, I can still see a faint gray line around the card. I've also tried `style={{ boxShadow: "none" }}` but that seems to make the shadow even more visible.

How can I remove all box-shadow so that there's no visible border/shadow around the card?
[card.zip](https://github.com/callstack/react-native-paper/files/6500744/card.zip)

Thanks!

**Comment by lukewalczak** [comment]
Hey @g-hamilton, try to use `shadowColor: 'transparent' within Card styles.

**Comment by g-hamilton** [comment]
Thanks @lukewalczak that seems to work :)

Unfortunately, I'm doing all my styling in styled components (written in CSS syntax) so the `shadowColor` property (JSX) isn't the ideal solution. It would be really nice if `elevation={0}` did that for me ;)

But.. works for now so thanks!

**Comment by satya164** [comment]
> shadowColor property (JSX) 

`shadowColor` is a style
