### ISSUE TITLE
TextInput cursor color

### ISSUE THREAD

**Issue by davepaiva** [callstack/react-native-paper#2757]
Is there any way we can change the cursor colour using any props from the TextInput component from this library?
I have seen posts where we can change the colour by specifying colours in `android/app/src/main/res/values/styles.xml` etc.
But this is not ideal for me as I require different colours in different places .
`react-native` version 0.61.5
`react-native-paper` version 4.9.1
`react-native-vector-icons` version 8.1.0
Thanks.

**Comment by lukewalczak** [comment]
You can change the caret color along with selection color using [prop](https://reactnative.dev/docs/textinput#selectioncolor) `selectionColor` on mobile platform.

**Comment by ferrannp** [comment]
@davepaiva this is a React Native bug. See https://github.com/facebook/react-native/issues/30283. `selectionColor` will style the selection cursors but not the caret. To style the caret you can do it as you say with `styles.xml`. It looks to me that this PR https://github.com/facebook/react-native/pull/31007 might solve the issue... You can try using `patch-package`.

**Comment by davepaiva** [comment]
> @davepaiva this is a React Native bug. See [facebook/react-native#30283](https://github.com/facebook/react-native/issues/30283). `selectionColor` will style the selection cursors but not the caret. To style the caret you can do it as you say with `styles.xml`. It looks to me that this PR [facebook/react-native#31007](https://github.com/facebook/react-native/pull/31007) might solve the issue... You can try using `patch-package`.

Unfortunately, this just changes the bg colour of the selected text and not the cursor
