### ISSUE TITLE
All documentation links to material.io lead to blank pages

### ISSUE THREAD

**Issue by chriswayg** [callstack/react-native-paper#2759]
### Current behaviour

All documentation links that refer to Material Design specifics on material.io display a white page. It seems the site has been down for months.

Example:
https://material.io/design/platform-guidance/cross-platform-adaptation.html

### Expected behaviour

To see the actual information such as found via Wayback Machine (Web Archive):
http://web.archive.org/web/20210430072259if_/https://material.io/design

### Screenshots (if applicable)
Try the first two links on https://github.com/callstack/react-native-paper

![image](https://user-images.githubusercontent.com/13681327/120592477-8adc3280-c470-11eb-8c28-76f1a2c7beb0.png)

Pages show this
![image](https://user-images.githubusercontent.com/13681327/120591872-75b2d400-c46f-11eb-8279-7e8c45f69f7b.png)

### What have you tried

- Tried links for a few days already
- Web Archive shows nothing after February

Suggested workaround:
- change links to Web Archive

### Your Environment

Chrome 83

**Comment by lukewalczak** [comment]
I'm not able to reproduce it and looks like links work properly. Maybe some setup on your machine is blocking the access to those pages? Did you try to clean caches / run in the incognito mode / disable add-ons in your browser / try different browser ?

**Comment by chriswayg** [comment]
Strange, this is the only site that basically disappeared. 

> I'm not able to reproduce it and looks like links work properly. Maybe some setup on your machine is blocking the access to those pages? Did you try to clean caches / run in the incognito mode / disable add-ons in your browser / try different browser ?

Thanks for checking, you are right. It seems to be an issue with my current Chrome browser. It does not work in Chrome incognito (without any extensions running) either. I think I will need to reinstall this browser or switch to another one. - The page does work in Safari for example.
