### ISSUE TITLE
Anytime I add TextInput inside a View, the app crashes with no logs

### ISSUE THREAD

**Issue by Pat-Gekoski** [callstack/react-native-paper#2761]
### Current behavior

Anytime I add TextInput to a View, my application crashes. If I comment out the TextInput, the app runs fine. If I move the TextInput outside of the containing View (which is just a regular View), then the app doesn't crash but the TextInput's width shrinks and the height get's jacked up. 

### Expected behavior

I expect the app not to crash when I place a TextInput inside of a view. I also expected the TextInput to at least be a wide as it's content since no explicit width is set. 

Also, I expected to see some error/crash logs. I got nothing. So, I'm lost as to where to begin resolving this issue.

### Code sample

```
export default function ProfileSettings({ setShowEditProfileModal }) {
   const [name, setName] = useState('')
   const [email, setEmail] = useState('')

   return (
      <SafeAreaView style={styles.safeArea}>
          <View style={styles.root}>

            <Text style={{ textAlign: 'center' }}>Edit Profile</Text>

            <TextInput
              label='Name'
              mode='flat'
              textContentType='name'
              keyboardType='name-phone-pad'
              autoCapitalize='words'
              autoCorrect={false}
              value={name}
              onChangeText={(text) => setName(text)}
              dense={true}
              style={styles.inputStyles}
              theme={{ colors: { text: 'black', primary: 'red' } }}
            />

            {/* Form */}
            <View style={styles.form}>
               {/* Input 1 */}
               <View style={styles.row}>
                  <Ionicons name='md-person-sharp' size={26} color='black' style={{ marginRight: 10 }} />
                  
                  <View style={{ width: '100%' }}>
                     {/**  <TextInput
                        label='Name'
                        mode='flat'
                        textContentType='name'
                        keyboardType='name-phone-pad'
                        autoCapitalize='words'
                        autoCorrect={false}
                        value={name}
                        onChangeText={(text) => setName(text)}
                        dense={true}
                        style={styles.inputStyles}
                        theme={{ colors: { text: 'black', primary: 'red' } }}
                     /> */}
                  </View>
               </View>

               {/* Input 2 */}
               <View style={styles.row}>
                  <MaterialIcons name='email' size={26} color='black' style={{ marginRight: 10 }} />
                  <View style={{ flex: 1 }}>
                     {/* <TextInput
                        label='Email'
                        mode='flat'
                        textContentType='emailAddress'
                        keyboardType='email-address'
                        autoCapitalize='none'
                        autoCorrect={false}
                        value={email}
                        onChangeText={(text) => setEmail(text)}
                        dense={true}
                        style={styles.inputStyles}
                        theme={{ colors: { text: colors.colorCharcoal, primary: colors.colorPrimary } }}
                     /> */}
                  </View>
               </View>

            </View>
         </View>
      </SafeAreaView>
   )
}

const styles = StyleSheet.create({
   safeArea: {
      flex: 1,
      backgroundColor: 'white',
   },
   root: {
      flex: 1,
      padding: 20,
      alignItems: 'center',
   },
   form: {
      width: '100%',
      paddingTop: 30,
   },
   row: {
      flexDirection: 'row',
      // height: 55,
		paddingBottom: 30,
		alignItems: 'baseline',
   },
   inputStyles: {
      fontSize: 16,
   },
})
```

To reproduce the crash: 

1. run the snack and take a look at the layout. You'll see why I 'm trying to place the TextInput inside a View. Without that the bounds of the component are messed up. 
2. comment out the top TextInput and un-comment the lower one. As soon as the app is run it crashes. I see no reason why this would be the case. I'm only placing it inside a simple View

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/45214870/120668833-d5ec4a80-c45c-11eb-8e37-1ddc2c522189.png)

### What have you tried

I have tried moving the TextInput around my UI. I have commented out most of its attributes. I have run it in a snack as well as on my simulator and iPhone. Same result every time. 

### Your Environment

| software  |  version
| ----------------------------
| ios  |  14
| react-native  |  SDK 41
| react-native-paper  |  4.9.1
| expo  |  ~41.0.1

Here is a snack that displays this issue: [https://snack.expo.io/@patric-gekoski/text-input-crashes](https://snack.expo.io/@patric-gekoski/text-input-crashes)

**Comment by raajnadar** [comment]
alignItems: 'center'

In the root styles is the reason for this issue.

**Comment by raajnadar** [comment]
It should not crash the app, But that is how flexbox works in react native. Let's wait for future version maybe it will be fixed or any alternate solution will be added.
