### ISSUE TITLE
Card.Title "Right" Function Does Not Work with Menu

### ISSUE THREAD

**Issue by buffaloDeveloper** [callstack/react-native-paper#2766]
### Current behaviour

Menu will not open onPress

### Expected behaviour

Menu should open on press

### Code sample

https://snack.expo.io/@midnightrider/card-title-with-menu

### What have you tried

Created snack showing basic config and the issue.

### Your Environment

See snack.

https://snack.expo.io/@midnightrider/card-title-with-menu

react-native-paper: *
expo: 41

**Comment by lukewalczak** [comment]
@buffaloDeveloper Did you wrap your root component with the `Provider` from `react-native-paper`?

**Comment by buffaloDeveloper** [comment]
> @buffaloDeveloper Did you wrap your root component with the `Provider` from `react-native-paper`?

That fixed it, thanks!

https://snack.expo.io/@midnightrider/card-title-with-menu
