### ISSUE TITLE
`expo start --no-dev --minify` mess up render and functionality of App

### ISSUE THREAD

**Issue by adilusman51** [callstack/react-native-paper#2768]
### Current behaviour

run `expo start --no-dev --minify`, select Android or iOS, Theme of the App is messed up switching between dark theme and light theme, Missing Icons (using FeatherIcons), Card inset margins goes to zero, Text theme is inconsistent and Button/FAB onPress does not work properly.

run `expo start -c`, select Android or iOS, App works fine as expected.

### Expected behaviour

App should work in production mode same as in development mode.

### Your Environment

| software              | version
| --------------------- | -------
| android        |29
| react-native          |0.63
| react-native-paper    |4.9.1
| node                  |12.19.0
| npm or yarn           |1.22.5
| expo sdk              |41.0.1

**Comment by adilusman51** [comment]
This is caused by adding `plugins: ['react-native-paper/babel']` in the `babel.config.js` file as recommended by the getting started documentation [React Native Paper - Getting Started](https://callstack.github.io/react-native-paper/getting-started.html)
```javascript
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    env: {
      production: {
        plugins: ['react-native-paper/babel'],
      },
    },
  };
};
```

This is supposed to remove unused code, but it removes a lot of useful code and also code from other modules. 
Kindly have a look into this.

**Comment by raajnadar** [comment]
I am using that config for many application but didn’t find any issue can you please elaborate your issue?

**Comment by adilusman51** [comment]
I am using expo to build react native app. When I test app in dev environment with `expo start -c` everything works fine, App renders fine and switching theme have effect through out the app. When I test app in prod environment with `expo start --no-dev --minify`, App renders incorrectly, switch theme does not take effect through out the app.

Removing  `plugins: ['react-native-paper/babel']` in the `babel.config.js`, and then running `expo start --no-dev --minify`, App again works fine and renders same as in the case of running `expo start -c`

**Comment by tdotdm** [comment]
Hi @adilusman51 I am experiencing this problem too although I do not have `babel-preset-expo` in my config. 

Have you found a solution / workaround?

**Comment by adilusman51** [comment]
@tdotdm I have removed the `plugins: ['react-native-paper/babel']` in the `babel.config.js` file, for both production and development environment. and it is working fine for me


Note: I am using Expo for my projects, and latest version of Expo SDK recommends to use their babel preset in `babel.config.js`.
Following is the state of `babel.config.js` file in my project (Note that I have commented out the `react-native-paper/babel` section)

```javascript
module.exports = function (api) {
	api.cache(true);
	return {
		presets: ['babel-preset-expo'],
		// env: {
		// 	production: {
		// 		plugins: ['react-native-paper/babel'],
		// 	},
		// },
		plugins: [ 'react-native-reanimated/plugin'],
	};
};

```

I hope this is helpful for you

**Comment by MOUTAIROU** [comment]
I have the same problem, can anyone find a solution?

**Comment by seanblonien** [comment]
I am still having the same problem w/ latest react-native-paper, react-native, and expo, but the symptom I am seeing is exactly this issue #1432. commenting out the babel plugin seems to be the only work around for me as well...

anyone know what this file is doing exactly? 
https://github.com/callstack/react-native-paper/blob/main/src/babel/index.js
never worked on a babel plugin, but yea am curious to know how to look into this bug. clearly there is something not behaving as expected within the plugin code given our configuration, but not sure what

**Comment by srosato** [comment]
Also happened to me once I added [react-native-paper-dropdown](https://github.com/fateh999/react-native-paper-dropdown).

After couple of hours of trying everything, I stumbled on this issue here and it was also the babel plugin added in production environment that was giving the error `forgot to wrap your root component with Provider component from react-native-paper`.

Not sure about the side effects of removing that plugin though.

**Comment by codetheorist** [comment]
I'm not entirely well-versed in debugging Babel config, but I think I may have spotted an issue with the Babel plugin code.

On line 6 we have `const { name, index, mappings } = require(options.mappings || '../../mappings.json');` however, for a start there is no file called `mappings.json` in the root of the repository, which is where the file should be located for this code to work.  I'm not entirely sure where the `options` object comes or how to debug whether `options.mappings` exists, but if it does not then this require will not work and must be failing silently.

There does not look to be many other issues in the plugin.  Maybe a missed check-in of a file perhaps?
