### ISSUE TITLE
Menu does not avoid intersecting keyboard on Android

### ISSUE THREAD

**Issue by WesleyAC** [callstack/react-native-paper#2769]
### Current behaviour

When a `Menu` is created near the bottom of the app, while the keyboard is expanded, the `Menu` opens behind the keyboard.

### Expected behaviour

I expect the menu to open upwards instead.

### Code sample

I don't have one that's easy to run, unfortunately :(

### Screenshots (if applicable)

![Screenshot_20210611-141306](https://user-images.githubusercontent.com/5001092/121749370-68c16080-cabf-11eb-8a72-2b4f3fb4fe8e.png)
![Screenshot_20210611-141336](https://user-images.githubusercontent.com/5001092/121749376-69f28d80-cabf-11eb-9ba7-a2651738c9e8.png)

### What have you tried

I looked at the documented props, and did not find any that controlled the direction that the `Menu` attempts to open in.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android 11
| react-native          | 0.63.4
| react-native-paper    | ^4.8.1
| node                  | N/A
| npm or yarn           | yarn
| expo sdk              | N/A

**Comment by WesleyAC** [comment]
[Here's a repro](https://snack.expo.io/vN5XcHE4R)

Tested on react-native-paper 4.9.1, same issue.

**Comment by brunohkbx** [comment]
@WesleyAC how about wrapping it with [KeyboardAvoidingView](https://reactnative.dev/docs/keyboardavoidingview) ?

**Comment by bombillazo** [comment]
Any solution to this issue?
