### ISSUE TITLE
Snack example web online no work

### ISSUE THREAD

**Issue by Angelk90** [callstack/react-native-paper#2772]
### Current behaviour

Hi @lukewalczak , @unikvozm : 
When trying the web version on snack.expo.io which is mentioned in the callstack documentation it does not work correctly from the error reported in the screenshot.

Link: https://snack.expo.io/@react-native-paper/github.com-callstack-react-native-paper:example

### Screenshots (if applicable)

<img width="310" alt="Schermata 2021-06-13 alle 13 35 15" src="https://user-images.githubusercontent.com/20476002/121805617-3729d000-cc4c-11eb-922f-c87889a37d3e.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | web
| react-native          |  0.63.0
| react-native-paper    | 4.0.0-alpha.0
|react-native-vector-icons | 6.6.0

**Comment by lukewalczak** [comment]
@Angelk90 thanks for a note, it's already fixed!

**Comment by Angelk90** [comment]
@lukewalczak : 

can't say it works very well:

![Screenshot_20210624-222401.png](https://user-images.githubusercontent.com/20476002/123327679-faf34b00-d53a-11eb-8a05-af598a23019a.png)
