### ISSUE TITLE
Snackbar Styling 

### ISSUE THREAD

**Issue by pkkasu** [callstack/react-native-paper#2774]
Is it possible to style Snack bar width and height ?  I want to show a tiny snackbar which covers just the width of text (Just like in Skype App)

**Comment by LeonArantes** [comment]
Yes it is possible, just add the width and height properties in your SnackBar component. 

**Example**

```
<Snackbar
   width={230}
   height={90}
   visible={visible}
   onDismiss={() => setVisible(false)}
     action={{
        label: 'Undo',
        onPress: () => {
           // Do something
         },
      }}
   duration={Snackbar.DURATION_MEDIUM}
>
    Hey there! Im a Snackbar.
</Snackbar>
```

**Comment by LeonArantes** [comment]
> Is it possible to style Snack bar width and height ? I want to show a tiny snackbar which covers just the width of text (Just like in Skype App)


Yes it is possible, just add the width and height properties in your SnackBar component. 

**Example**

```
<Snackbar
   width={230}
   height={90}
   visible={visible}
   onDismiss={() => setVisible(false)}
     action={{
        label: 'Undo',
        onPress: () => {
           // Do something
         },
      }}
   duration={Snackbar.DURATION_MEDIUM}
>
    Hey there! Im a Snackbar.
</Snackbar>
```

**Comment by lukewalczak** [comment]
Hey @pkkasu `Snackbar` components accept `style` prop where you can define your width and height.
