### ISSUE TITLE
[Searchbar] Not able set "caret-color" or how to set it, not able set color of search icon and close icon.

### ISSUE THREAD

**Issue by chetanmajithiya** [callstack/react-native-paper#2782]
- Not able set "caret-color" or how to set it, 
- Not able set color of search icon and close icon.
- I know we can put our icon but I want to use default icons and set styles of default icons.

[https://callstack.github.io/react-native-paper/searchbar.html](url)

**Comment by ahmedsamirdev** [comment]
I need to put icon on right to close the search
https://snack.expo.io/?name=Searchbar&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fsearchbar.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20Searchbar%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5BsearchQuery%2C%20setSearchQuery%5D%20%3D%20React.useState(%27%27)%3B%0A%0A%20%20const%20onChangeSearch%20%3D%20query%20%3D%3E%20setSearchQuery(query)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CSearchbar%0A%20%20%20%20%20%20placeholder%3D%22Search%22%0A%20%20%20%20%20%20onChangeText%3D%7BonChangeSearch%7D%0A%20%20%20%20%20%20value%3D%7BsearchQuery%7D%0A%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B%0A&dependencies=react-native-paper
