### ISSUE TITLE
Menu not opening in project but works in snack

### ISSUE THREAD

**Issue by KrisLau** [callstack/react-native-paper#2783]
### Current behaviour
Menu not opening. No error message.

### Expected behaviour
Menu should open when I click show menu button

### Code sample
https://snack.expo.io/@kris_lau/menu

### Screenshots (if applicable)
N/A

### What have you tried
I have tried testing using other components (like Switch) and those all work fine in my project so I know I set it up correctly. I also tried setting a higher `zIndex` on the menu to ensure the menu wasn't being hidden by anything. 

Also not sure if this is helpful but I have a similar-ish problem in my project with react-native-draggable-flatlist that I still do not know the cause of: https://github.com/computerjazz/react-native-draggable-flatlist/issues/285

### Your Environment
| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | ^0.64.0 => 0.64.2
| react-native-paper    |  ^4.9.2
| react-native-vector-icons  | ^8.1.0
| node                  | 14.16.1
| npm                   | 7.13.0
| yarn                   | 1.22.10
| expo sdk              | N/A

**Comment by lukewalczak** [comment]
Could you please create a sample repository _(since snack works properly)_ with bug reproduction to investigate root of the problem?

**Comment by KrisLau** [comment]
Couldn't repro in a new repo. Ended up just replacing menu with an overlay
