### ISSUE TITLE
Typing with TextInput is disorderly when inside Portal

### ISSUE THREAD

**Issue by ngotrongphuc** [callstack/react-native-paper#2787]
### Current behaviour

When handling TextInput with useState inside Portal, if i type faster than 1 word per second, it will becomes disorderly.
![useState within Portal](https://user-images.githubusercontent.com/72039796/123096428-4a614a80-d459-11eb-9b68-8ae62cba210f.gif)

### Expected behaviour

Without useState or wrapping TextInput inside Portal, everything works normally.
![without useState](https://user-images.githubusercontent.com/72039796/123097773-a5e00800-d45a-11eb-85a7-44c26e57b801.gif)

### Code sample

[https://snack.expo.io/@phucngo/test](url)
Try to type fast as possible and you will see the bug

### What have you tried

1. I've remove Portal from the code and everything works perfectly
2. I've tried not to use useState, just a simple <TextInput/> and it works fine but still a bit laggy

### Your Environment

| software              | version
| --------------------- | -------
| android        | AVD 9
| react-native-cli          | 2.0.1
| react-native          | 0.64.1
| react-native-paper    | 4.9.1
| node                  | 14.17.0
| yarn           | 1.22.10
| expo sdk              |

**Comment by lukewalczak** [comment]
There is an issue with inputs within portals in general, not only in the paper library. Within the other issue you can find the [workaround](https://github.com/callstack/react-native-paper/issues/1668#issuecomment-586005762).

Please also check that [approach](https://github.com/jeremybarbet/react-native-portalize/issues/6#issuecomment-761907191) which can be helpful.

**Comment by JaiminPatel345** [comment]
in TextInput use `defaultValue` , not use value 

Correct :
```
             <TextInput
                 mode="outlined"
                  label="Country"
                  defaultValue={location.country}
               
              />
```
