### ISSUE TITLE
Theme doesn't work on Menu

### ISSUE THREAD

**Issue by ngotrongphuc** [callstack/react-native-paper#2795]
Theme does not work on Menu. I need to change the color of text and icon of Menu.Item but neither style nor theme work

**Comment by peterchibunna** [comment]
Hi @ngotrongphuc can you post the code that you have tried?

**Comment by ngotrongphuc** [comment]
> Hi @ngotrongphuc can you post the code that you have tried?

Here is the example https://snack.expo.io/@phucngo/menu . I can only change the color of title or the background of Menu.Item, i have no idea how to change the color of Icon or its size

**Comment by peterchibunna** [comment]
Thanks for providing the snack. I checked the source code and found out that only `roundness`, `animation` are used from the `theme` props. However if you assign the theme to the Provider, the theme is passed down correctly.

**Comment by brunohkbx** [comment]
Related to #2844
