### ISSUE TITLE
TextInput - a cursor goes to the end of the line

### ISSUE THREAD

**Issue by DIUSII** [callstack/react-native-paper#2797]
Write something to the input and completely delete it, your cursor will go to the end of the line

An important condition you must have placeholder and textAlign: cetner

<img width="359" alt="Снимок экрана 2021-07-02 в 16 32 47" src="https://user-images.githubusercontent.com/49521201/124254415-40270680-db53-11eb-8a9c-2ee74ada6a64.png">

android and ios 
react-native ^0.63.4
react-native-paper ^4.7.2
node js ^10.3.0
yarn  
rect-native-init

this was the decision with React Native TextInput https://github.com/facebook/react-native/issues/27658

**Comment by DIUSII** [comment]
yarn 1.22.5
react-native-vector-icons 6.4.5

i am updated react-native-paper before 4.9.2, it isn't helps me 

i am checked texInput reac-native he is cool worked

**Comment by DIUSII** [comment]
<img width="600" alt="Снимок экрана 2021-07-02 в 16 45 35" src="https://user-images.githubusercontent.com/49521201/124255947-ef181200-db54-11eb-96d8-153c19860810.png">

this problem recently was decision in react-native

**Comment by raajnadar** [comment]
Closed https://github.com/facebook/react-native/pull/28995
