### ISSUE TITLE
TextInput: autofill yellow highlight overflows when the field is not long enought

### ISSUE THREAD

**Issue by manuelgarciacr** [callstack/react-native-paper#2802]
### Current behaviour

TextInput: autofill yellow highlight overflows when the field is not long enought and do not cover all the field. Sending attached github link and screenshots.
In long fields with autocomplete like email the issue can be particularly recurring.
This is a react-native bug (code #31811), but affects directly this component, 

### Expected behaviour

Yellow highlighting must cover all text and cannot overflow the beginning of the field. Or custom highlight property.

### Code sample

https://github.com/manuelgarciacr/rnp-textinput-bug.git

### Screenshots (if applicable)

![Screenshot_20210704-182440_Expo Go2](https://user-images.githubusercontent.com/29376434/124392830-d2680f80-dcf7-11eb-9ceb-0dca7ed4c9c8.jpg)
![Screenshot_20210704-182450_Expo Go2](https://user-images.githubusercontent.com/29376434/124392855-df84fe80-dcf7-11eb-97c7-13a741330859.jpg)

### What have you tried

React native bug: [https://github.com/facebook/react-native/issues/31811](https://github.com/facebook/react-native/issues/31811
)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android API Levels: 27, 28, 29, 30. Build Tools: 28.0.3, 29.0.2, 30.0.2. Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
| react-native          | react: 16.13.1 => 16.13.1. react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
| react-native-paper    | "react-native-paper": "^4.9.2"
| node                  |  14.7.0 - C:\Program Files\nodejs\node.EXE
| npm or yarn           | Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD. npm: 7.11.1 - C:\Program Files\nodejs\npm.CMD
| expo sdk              |  4.7.1

[https://snack.expo.io/6G1hj2FBN](https://snack.expo.io/6G1hj2FBN)

**Comment by manuelgarciacr** [comment]
react-native: 0.63.2
react-native-vector-icons: 8.1.0
Yarn: 1.22.10
expo: 4.7.2
npm: 7.19.1

The issue still exists after upgrading

**Comment by lukewalczak** [comment]
I think from couple Paper versions there is no _yellow highlight_, hence closing the issue.
