### ISSUE TITLE
Toggle secureTextEntry in the TextInput

### ISSUE THREAD

**Issue by m7he4rt** [callstack/react-native-paper#2817]
Hi! 

How does it toggle secureTextEntry for  password TextInput component. My code example doesn't work:

`
"react-native": "0.64.2"
`
`
"react-native-paper": "4.9.2"
`
`
"react-native-vector-icons": "8.1.0"
`

https://snack.expo.io/@m7ez1n/textinput.icon?name=TextInput.Icon&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Ftext-input-icon.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20TextInput%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Btext%2C%20setText%5D%20%3D%20React.useState(%27%27)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CTextInput%0A%20%20%20%20%20%20label%3D%22Password%22%0A%20%20%20%20%20%20secureTextEntry%0A%20%20%20%20%20%20right%3D%7B%3CTextInput.Icon%20name%3D%22eye%22%20%2F%3E%7D%0A%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper

**Comment by Omar-Belghaouti** [comment]
@m7he4rt how did you manage to toggle the password input ?
