### ISSUE TITLE
Swipe from left edge opens side menu in iOS

### ISSUE THREAD

**Issue by charlie-axsy** [callstack/react-native-paper#282]
Using the example app in Expo.

### Current behaviour

Swiping from the left edge of the screen opens the side menu.

### Expected behaviour

As per the standard iOS user experience, the app should navigate back to the previous screen in the stack.  

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS 11

**Comment by luissmg** [comment]
As far as I can see, the example app is using `react-navigation`, right?
I think you should check [this[(https://reactnavigation.org/docs/en/stack-navigator.html#gestureresponsedistance) prop on their API. With this I think you can customize the distance from the left edge and try to fix this with it

**Comment by satya164** [comment]
@luissmg yes

do you want to send a PR? will be much appreciated :D

**Comment by luissmg** [comment]
Sure thing. PR to update the example app, right?

**Comment by satya164** [comment]
Yup
