### ISSUE TITLE
How to align headers with columns in Data Tables

### ISSUE THREAD

**Issue by shanu95** [callstack/react-native-paper#2828]
![Screenshot_1626852491](https://user-images.githubusercontent.com/39364254/126449521-a269fbc5-298e-4c91-86ac-7ed5653d2a8f.png)

I'm using Data Table with two seperate arrays to populate table headers and table body. But they are not align each other unless i manually set a width. anyway to align them without setting width manually? tried with flex: 1 and still the same.

**Comment by Akshay-fullstack** [comment]
I am facing same issue.
