### ISSUE TITLE
Is there any way to make radio button in iOS same way as android - round type

### ISSUE THREAD

**Issue by pallaviMN** [callstack/react-native-paper#2829]
Let me know, if is there any way to make radio button circle

**Comment by pallaviMN** [comment]
version number - 4.7.2

**Comment by Trancever** [comment]
`RadioButton.Android`

**Comment by pallaviMN** [comment]
@Trancever , can i use it in iOS as well?

**Comment by amiramira22** [comment]
> You can use `RadioButton.Android` component on iOS.

works very good
