### ISSUE TITLE
How to preserve theme settings

### ISSUE THREAD

**Issue by ShabareeshSunku** [callstack/react-native-paper#284]
### Current behaviour

In the example if user opts for dark theme, its getting updated but when app is closed and reloaded its back to default theme.

### Expected behaviour

Still the interface should be in dark theme. I am sure we can preserve theme in asyncstorage, but where can I initialize saved theme from async storage

**Comment by satya164** [comment]
> but where can I initialize saved theme from async storage

At the root of your app.

```js
export default class App extends React.Component {
  state = {
    isReady: false,
    theme: DefaultTheme,
  };

  async componentDidMount() {
    try {
      const theme = JSON.parse(await AsyncStorage.getItem('app-theme'));

      this.setState({
        isReady: true,
        theme,
      });
    } catch (e) {
      this.setState({
        isReady: true,
      });
    }
  }

  render() {
    if (this.state.isReady) {
      return <Provider theme={this.state.theme}>{...}</Provider>;
    }

    return <SplashScreen />;
  }
}
```
