### ISSUE TITLE
DataTable.Pagination Issues

### ISSUE THREAD

**Issue by bruffster** [callstack/react-native-paper#2840]
Hello there!

I'm trying to follow the example here:
https://callstack.github.io/react-native-paper/data-table-pagination.html

However, loading the example as well as implementing it myself, it appears that the pagination is not working for the DataTable.  The number of items per page is not getting reflected in the DataTable, nor does the data change in the table if you change page.  Are there any known issues with pagination currently?

link to my own example: https://snack.expo.dev/hKLbvPRXD

Thanks!

**Comment by sahilvicesoftware** [comment]
Facing the same issue

**Comment by bruffster** [comment]
Edited my original post, but repro example is: https://snack.expo.dev/hKLbvPRXD

**Comment by jsmr04** [comment]
Same issue here. Any updates?

**Comment by impactcolor** [comment]
Any one discover a solution? I'm also facing the same issue.

**Comment by bruffster** [comment]
@impactcolor I never had any luck following their guide for the pagination. I ended up implementing my own pagination in my Java Spring Boot Rest API and then tweaking the setup of the plugin in my React app to utilize that capability.
