### ISSUE TITLE
Dialog in web

### ISSUE THREAD

**Issue by samaneh-kamalian** [callstack/react-native-paper#2841]
### Current behaviour

The dialogue style is messed up in the web.

### Expected behaviour

Padding and margins are correct.

### Code sample

```    
       <Portal>
              <Dialog
                visible={this.props.dialogVisible}
             >
              {
                !this.props.showActivity &&
              <Dialog.Title
                accessibilityLabel={testLabels.mainPage.dialogTitle}
              >
                {this.props.dialogTitle}
              </Dialog.Title>
            }
            {
              this.props.showActivity ?
                <Dialog.Content style={styles.spinnerDialogContent}>
                  <ActivityIndicator animating={true} style={styles.activityIndicator} />
                  <Paragraph>{this.props.showActivityText}</Paragraph>

                </Dialog.Content> :
                <Dialog.Content
                  accessibilityLabel={testLabels.mainPage.dialogContent}
                >
                  <Paragraph>{this.props.dialogContent}</Paragraph>
                </Dialog.Content>

            }
            {
              !this.props.showActivity &&
              <Dialog.Actions>
                <Button
                  accessibilityLabel={testLabels.mainPage.errorHandlingDialogBtn}
                  onPress={() => { this.props.actionOfFirstBtnOfDialog() }}>
                  {this.props.textOfFirstBtnOfDialog}
                </Button>
                {
                  this.props.appearSecondBtnForDialog &&
                  <Button
                    accessibilityLabel={testLabels.mainPage.dialogSecondBtn}
                    onPress={() => { this.props.actionOfSecondBtnOfDialog(); }}
                  >
                    {this.props.textOfSecondBtnOfDialog}
                  </Button>
                }
              </Dialog.Actions>
            }


          </Dialog>
        </Portal>
```

### Screenshots (if applicable)

![Screen Shot 2021-08-08 at 9 40 42 AM](https://user-images.githubusercontent.com/57032373/128621609-c438c7ef-b170-4858-b021-065b6c87ae05.png)

### What have you tried

Noting. if you does not have any idea, I must to change my module in web :(

### Your Environment

| software              | version
| --------------------- | -------
| android        | 11
| react-native          | 0.63.4
| react-native-paper    | 4.9.1
| node                  | v15.2.1
| npm          | 7.0.15

**Comment by brunohkbx** [comment]
@samaneh-kamalian seems like the examples here example/src/Examples/DialogExample.tsx is working fine. Can you provide a snack reproducing this issue?

**Comment by samaneh-kamalian** [comment]
@brunohkbx Thanks a lot for your reply.
Unfortunately I do not have enough time to make a snack.
But the code I used, as you can see in my previous post, follows this pattern like the examples:
 
 `  
<Portal>
    <Dialog>
      <Dialog.Title>Alert</Dialog.Title>
      <Dialog.Content>
        <Paragraph>This is a dialog!!</Paragraph>
      </Dialog.Content>
      <Dialog.Actions>
        <Button color={Colors.teal500} disabled>
          Disagree
        </Button>
        <Button onPress={close}>Agree</Button>
      </Dialog.Actions>
    </Dialog>
  </Portal>
`

This code works well on the Android platform, but in the PWA version, the styles break down!

**Comment by brunohkbx** [comment]
@samaneh-kamalian maybe there's something wrong with your styles?

This code is working fine, just copy and past it here: https://snack.expo.dev/

```js
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';

// You can import from local files
import AssetExample from './components/AssetExample';

// or any pure javascript modules available in npm
import { Button, Card, Dialog, Paragraph, Portal, Provider } from 'react-native-paper';

export default function App() {
  return (
    <View style={styles.container}>
      <Provider>
        <Portal> 
          <Dialog visible> 
            <Dialog.Title>Alert</Dialog.Title> 
            <Dialog.Content> 
              <Paragraph>This is a dialog!!</Paragraph> 
            </Dialog.Content> 
            <Dialog.Actions> 
              <Button disabled> Disagree </Button> 
              <Button>Agree</Button> 
            </Dialog.Actions> 
          </Dialog> 
        </Portal>
      </Provider>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
```

![Screenshot from 2021-08-10 23-23-44](https://user-images.githubusercontent.com/6487206/128960000-49a4092f-6d38-463c-929e-3b719266a20d.png)

**Comment by samaneh-kamalian** [comment]
I used Appbar as header page. 
When I remove Appbar, dialog style is correct!!!!
Do you know why???!!!
