### ISSUE TITLE
secureTextEntry not working in TextInput

### ISSUE THREAD

**Issue by Omar-Belghaouti** [callstack/react-native-paper#2853]
### Current behaviour

As my following code shows, the secureTextInput is not working in the TextInput as it should work.

and here is the result (Nothing):
![image](https://user-images.githubusercontent.com/48713070/129340561-c67ba9b4-f525-469a-b9ac-5acaf493a57b.png)

### Expected behaviour

Well it should show some bullet points as it shows for normal TextInput from `react-native`.

### Code sample

```js
 <TextInput
            keyboardType={"visible-password"}
            mode="outlined"
            label="Password"
            secureTextEntry={true}
            value={password}
            onChangeText={(text) => setPassword(text)}
          />
```

### Your Environment

| software              | version
| --------------------- | -------
| android        |  11
| react-native          | https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
| react-native-paper    | ^4.9.2
| node                  | 14.x
| yarn           | 1.22.10
| expo sdk              | 42.0.0

**Comment by wave2006** [comment]
> ### Current behaviour
> As my following code shows, the secureTextInput is not working in the TextInput as it should work.
> 
> and here is the result (Nothing): ![image](https://user-images.githubusercontent.com/48713070/129340561-c67ba9b4-f525-469a-b9ac-5acaf493a57b.png)
> 
> ### Expected behaviour
> Well it should show some bullet points as it shows for normal TextInput from `react-native`.
> 
> ### Code sample
> ```js
>  <TextInput
>             keyboardType={"visible-password"}
>             mode="outlined"
>             label="Password"
>             secureTextEntry={true}
>             value={password}
>             onChangeText={(text) => setPassword(text)}
>           />
> ```
> 
> ### What have you tried
> ### Your Environment
> software	version
> android	11
> react-native	https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
> react-native-paper	^4.9.2
> node	14.x
> yarn	1.22.10
> expo sdk	42.0.0

**hi, i had met this issue before. AND the soluation is not to use this pros value -->'visible-password'**
