### ISSUE TITLE
Material Icons not showing

### ISSUE THREAD

**Issue by KevinBorjaLundero** [callstack/react-native-paper#2855]
Hi, I'm trying to show an iconbutton with material icons but it shows ? . After following all the steps in the docs I don't what I missing. 
Steps that I follow:

1. Added:

```
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

project.ext.vectoricons = [
    iconFontNames: [ 'MaterialIcons.ttf', 'MaterialCommunityIcons.ttf' ] // Name of the font files you want to copy
]
```
to ```android/app/build.gradle```

2. Then added Paper Provider to my App.tsx like

```
import 'react-native-gesture-handler';
import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { MenuLateral } from './src/navigator/MenuLateral';
import { DefaultTheme, Provider as PaperProvider } from 'react-native-paper';
import MaterialIcons  from 'react-native-vector-icons/MaterialIcons';

const App = () => {
  return (
    <PaperProvider
        settings={{
          icon: props => <MaterialIcons {...props} />,
        }}
        theme={DefaultTheme} // -> this is differente from the docs cause {this.state.theme} said that 'this' is undefined
      >
        <NavigationContainer>
      {/*<StackNavigator />*/}
      <MenuLateral />
    </NavigationContainer>
      </PaperProvider>
  );
}

export default App;
```
3. In my component I added like
```
...
 <View>
        <IconButton icon="more_vert" size={20} onPress={() => console.log('Pressed')}  />
 </View>
```

But I'm getting this error invalid prop name of value "more_vert" supplied to icon expected one of: [list of icons]. But more_vert is part of material icons. So I don't know what I missing thanks in advance 

Additional info:

"react-native-paper": "^4.9.2",
"react-native-vector-icons": "^8.1.0"
"react-native": "0.64.1",

**Comment by viv3kk** [comment]
not working with

**Comment by alapanerao** [comment]
Facing same issue. 
Check out this snack [Click Me](https://snack.expo.dev/@arao_18/d7b93b?name=TextInput.Icon&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Ftext-input-icon.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20TextInput%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Btext%2C%20setText%5D%20%3D%20React.useState(%27%27)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CTextInput%0A%20%20%20%20%20%20label%3D%22Password%22%0A%20%20%20%20%20%20secureTextEntry%0A%20%20%20%20%20%20right%3D%7B%3CTextInput.Icon%20name%3D%22eye%22%20%2F%3E%7D%0A%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper)
