### ISSUE TITLE
Create optional setting to disable all animations entirely

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#286]
Useful for example when battery saver on Android is on. We can show how to listen for:

```xml
<action android:name="android.os.action.POWER_SAVE_MODE_CHANGED"/> 
```

**Comment by onitzschke** [comment]
Hi, i'm using the experimental `LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);` and the animation of FAB icon is stuck at the end. Any idea?

**Comment by satya164** [comment]
@onitzschke `LayoutAnimation` is very invasive and can affect other components in unexpected ways. Unfortunately, it's not something we can help with. You should consider removing `LayoutAnimation`.

**Comment by onitzschke** [comment]
Yes, that's the problem. I'll try to abstract the components. Maybe that helps. Thanks.

**Comment by onitzschke** [comment]
For all with the same issue:
I use a custom animation with less duration and it works great now.
```
const CustomAnimation = {
  duration: 100,
  create: {
    type: LayoutAnimation.Types.easeInEaseOut,
    property: LayoutAnimation.Properties.opacity
  },
  update: {
    type: LayoutAnimation.Types.easeInEaseOut,
    duration: 100
  }
};
```

`              LayoutAnimation.configureNext(CustomAnimation);
`

**Comment by Subv** [comment]
For anyone stumbling upon this issue looking for a way to disable all animations, it seems there is now a theme property to do that: https://github.com/callstack/react-native-paper/pull/1594
https://github.com/callstack/react-native-paper/blob/d2f61fbee9bd9bd11daa206313d8069876fbccd5/src/styles/DefaultTheme.tsx#L24
