### ISSUE TITLE
The Dialog with ScrollArea, Title and Actions goes beyond SafeAreaView

### ISSUE THREAD

**Issue by robertoosantos** [callstack/react-native-paper#2863]
### Current behaviour

The Dialog with ScrollArea, Title and Actions goes beyond SafeAreaView

### Expected behaviour

When I use a Dialog with ScrollArea, Title and Actions, it should fit the viewable screen.

### Code sample

[On Snack.io](https://snack.expo.dev/@robertoosan/dialog.scrollarea?name=Dialog.ScrollArea&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fdialog-scroll-area.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20ScrollView%20%7D%20from%20%27react-native%27%3B%0Aimport%20%7B%20Dialog%2C%20Portal%2C%20Text%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bvisible%2C%20setVisible%5D%20%3D%20React.useState(false)%3B%0A%0A%20%20const%20hideDialog%20%3D%20()%20%3D%3E%20setVisible(false)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CPortal%3E%0A%20%20%20%20%20%20%3CDialog%20visible%3D%7Bvisible%7D%20onDismiss%3D%7BhideDialog%7D%3E%0A%20%20%20%20%20%20%20%20%3CDialog.ScrollArea%3E%0A%20%20%20%20%20%20%20%20%20%20%3CScrollView%20contentContainerStyle%3D%7B%7BpaddingHorizontal%3A%2024%7D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CText%3EThis%20is%20a%20scrollable%20area%3C%2FText%3E%0A%20%20%20%20%20%20%20%20%20%20%3C%2FScrollView%3E%0A%20%20%20%20%20%20%20%20%3C%2FDialog.ScrollArea%3E%0A%20%20%20%20%20%20%3C%2FDialog%3E%0A%20%20%20%20%3C%2FPortal%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper)

```
import * as React from 'react';
import { SafeAreaView, ScrollView } from 'react-native';
import { Provider, Button, Dialog, Portal, Text } from 'react-native-paper';

const MyComponent = () => {
  const DATA = Array.from(Array(45).keys());

  const [visible, setVisible] = React.useState(false);

  const hideDialog = () => setVisible(false);

  const showDialog = () => setVisible(true);

  return (
    <Provider>
      <SafeAreaView>
        <Button mode="contained" onPress={showDialog}>Show Dialog</Button>
        <Portal>
          <Dialog visible={visible} onDismiss={hideDialog}>
            <Dialog.Title>Scroll Dialog</Dialog.Title>
            <Dialog.ScrollArea>
              <ScrollView>
                {DATA.map((d, i) => (<Text key={i} style={{ padding: 10 }}>Item {i}</Text>))}
              </ScrollView>
            </Dialog.ScrollArea>
            <Dialog.Actions>
              <Button onPress={hideDialog}>OK</Button>
            </Dialog.Actions>
          </Dialog>
        </Portal>
      </SafeAreaView>
    </Provider>
  );
};

export default MyComponent;
```

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/46982941/129906510-3c4cbb3a-eeaa-4be5-a135-c51a46118553.png)

### What have you tried

I've tried to fix the ScrollArea height but it's a poor experience for user.
I've also tried to set a relative maxHeight in percentage, but also a poor experience.

### Your Environment

| software              | version
| --------------------- | -------
| android        |11
| react-native          |0.63
| react-native-paper    |4.9.2
| node                  |14.17.5
| npm           |7.20.6
| expo sdk              |41

**Comment by brunohkbx** [comment]
@robertoosantos isn't it the expected behavior since it's wrapped with a Portal? In the example app there's a `maxHeight` 
`style={{ maxHeight: 0.6 * Dimensions.get('window').height }}`

**Comment by robertoosantos** [comment]
> @robertoosantos isn't it the expected behavior since it's wrapped with a Portal? In the example app there's a `maxHeight`
> `style={{ maxHeight: 0.6 * Dimensions.get('window').height }}`

Sorry, which example app?

It wasn't the expected behavior to me, because if there's no Title and Actions even if the SrollArea is really large, the Dialog fits the SafeAreaView.

**Comment by brunohkbx** [comment]
This one:
https://github.com/callstack/react-native-paper/blob/main/example/src/Examples/Dialogs/DialogWithLongText.tsx

https://play.google.com/store/apps/details?id=com.callstack.reactnativepaperexample

**Comment by robertoosantos** [comment]
> This one:
> https://github.com/callstack/react-native-paper/blob/main/example/src/Examples/Dialogs/DialogWithLongText.tsx
> 
> https://play.google.com/store/apps/details?id=com.callstack.reactnativepaperexample

Yeah, it does the job. But I would like to not have to set maxHeights or paddings. If there's no Title and Actions, it works out of the box, respecting SafeAreaView.
