### ISSUE TITLE
Using just Icon without a Button

### ISSUE THREAD

**Issue by simplenotezy** [callstack/react-native-paper#2877]
It's not clear from the documentation how I can reference just an icon. I need an icon but without a Button, how can I do that?

https://callstack.github.io/react-native-paper/icons.html

**Comment by simplenotezy** [comment]
Really annoying github actions bot by the way :P

**Comment by simplenotezy** [comment]
Wonder if it is even possible? 🤔 I've spend 30 minutes now. It might be because I'm an idiot, nevertheless, it's quite frustating being hold up with such simple things! Once I know, I'll make sure to contribute that to the documentation...

**Comment by raajnadar** [comment]
https://github.com/oblador/react-native-vector-icons#icon-component

Read this docs

**Comment by simplenotezy** [comment]
Thanks! Just what I needed.

Perhaps the docs should have some addition like:

To display a single icon:

    import Icon from 'react-native-vector-icons/FontAwesome';
    const myIcon = <Icon name="rocket" size={30} color="#900" />;

Have a look at: https://github.com/oblador/react-native-vector-icons#icon-component for more details

Also, what icon package does react-native-paper use? I guess it's not font awesome.

**Comment by raajnadar** [comment]
Material community icons is default, but you can use any custom icons.
