### ISSUE TITLE
Appbar Action icon Jiggling

### ISSUE THREAD

**Issue by maulanauls** [callstack/react-native-paper#2887]
### Current behaviour

I just tried to attach icon custom in appbar header action icon using svg or image resource but my components after move it new screen is jiggling icon

### Code sample

<code>import * as React from 'react';
import {
  StyleSheet,
  View,
  useContext,
  TextInput,
  Dimensions,
  Platform,
  ImageBackground,
  Pressable,
} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import {
  Appbar,
  Text,
  Badge,
  DefaultTheme as PaperDefaultTheme,
} from 'react-native-paper';
import {Context} from 'state/store';

import SearchIcon from '../../assets/icon/search-icon.svg';
import CartIcon from '../../assets/icon/cart-icon.svg'

const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;

const HeaderHome = ({route, navigation}) => {
  return (
    <LinearGradient
      colors={['#62B047', '#62B047']}
      start={{x: 0.5, y: 0.1}}
      end={{x: 0.5, y: 0.7}}
      style={styles.header}>
      <Appbar.Header
        theme={{
          ...PaperDefaultTheme,
          colors: {
            primary: '#62B047',
          },
        }}
        style={{
          elevation: 0,
          paddingHorizontal: 10,
          justifyContent: 'center',
        }}>
        <View style={styles.wrapper}>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
              justifyContent: 'center',
              alignItems: 'center',
              backgroundColor: '#fff',
              elevation: 4,
              color: '#000',
              borderWidth: 0,
              borderRadius: 8
            }}>
            <SearchIcon width={50} height={50} />
            <TextInput
              style={styles.searchBar}
              onFocus={() => navigation.navigate('search')}
            />
          </View>
          <View>
            <Appbar.Action
              style={{marginVertical: 20}}
              color="white"
              size={30}
              icon={({size, color}) => <CartIcon width={size} height={size} />}
              onPress={() => navigation.navigate('category')}
            />
          </View>
        </View>
      </Appbar.Header>
    </LinearGradient>
  );
};

const styles = StyleSheet.create({
  header: {
    width: width,
    height: 60
  },
  wrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  searchBar: {
    fontSize: 14,
    width: width - 140,
    height: 50
  },
});

export default HeaderHome;</code>

### Screenshots (if applicable)
https://ibb.co/0sCwQ2h

### Your Environment

| software              | version
| --------------------- | -------
| android        |
| react-native        | 0.65.1 
| react-native-paper  | 4.9.2
| react-native-vector-icons |  8.1.0 
| react-native-svg | 12.1.1
| react-native-svg-transformer  |  0.14.3
| npm |  7.19.1
| node | 14.16.1
| yarn | 1.19.1 
![WhatsApp-Video-2021-09-05-at-06 50 07](https://user-images.githubusercontent.com/25361048/132110696-13fabd40-6b9a-47a7-a08c-eefa4521486c.gif)

**Comment by maulanauls** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `expo`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `npm` (found: `7.19.1`, latest: `7.22.0`)
> * `yarn` (found: `1.19.1`, latest: `1.22.11`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

No this issue still not fixed

**Comment by lukewalczak** [comment]
Hey @maulanauls could you please create an example repo or use the snack presenting the issue, to help us investigate the bug?

**Comment by biangwua** [comment]
> 嘿，您能否创建一个示例存储库或使用呈现问题的零食来帮助我们调查错误？

https://snack.expo.dev/@biang_wua/searchbar-and-icomoon-in-rnpaper-5-3-1

**Comment by biangwua** [comment]
This bug is three years old and still hasn't been fixed
