### ISSUE TITLE
Using components from `react-native-gesture-handler` to improve performance 

### ISSUE THREAD

**Issue by Pix-00** [callstack/react-native-paper#2888]
### Is your feature request related to a problem? Please describe.

Encountering performance issue when putting lots of components (such as `TextInput`) in a same screen.

### Describe the solution you'd like

Import components (such as `TextInput` and `Touchables`) directly from `react-native-gesture-handler` instead of `react-native`. They have exactly the same API, so theoretically no extra adaptations need to do.

In addition, implement ripple effect and other animations with `react-native-reanimated`. This do required extra adaptations.

As most of the large react native projects (or projects that using `react-navigation`) rely on those to package, it should not be a problems that involving new dependences.

### Describe alternatives you've considered
- Using components from `react-native-gesture-handler` without Martial Design.
- Separating components into different pages.

### Environments
- react-native: 0.65.1
- react-native-paper: 4.9.2
- react-native-vector-icons: 8.1.0

### Additional context

https://docs.swmansion.com/react-native-gesture-handler/docs/api/components/touchables
https://github.com/software-mansion/react-native-reanimated

**Comment by KrifaYounes** [comment]
i am alright with,
if you want  we can create a branch with this features together
