### ISSUE TITLE
Chip component strange behavior on Android

### ISSUE THREAD

**Issue by melihmuratpesmen** [callstack/react-native-paper#2889]
### Current behaviour
Chip component strange behavior on Android
On android inside Data Table component, I am rendering CHIP with the condition. In one condition chip is not rendered. First of all, I think it could be because of color or icon but this is not the problem. After that, I noticed when I change the condition order, chips start the disappear.
As shown on the code sample only the first condition ('Onay Bekliyor' ) does not appear at the first time.

### Expected behaviour
On the IOS side everything works as expected with no problem.

### Code sample
```
`<DataTable.Cell>
              {item.operation === 'Onay Bekliyor' && (
                <Chip
                  style={{backgroundColor: '#ff7f50'}}
                  icon="clock-check-outline">
                  {item.operation}
                </Chip>
              )}
              {item.operation === 'Hazırlanıyor' && (
                <Chip style={{backgroundColor: 'lightgrey'}} icon="information">
                  {item.operation}
                </Chip>
              )}

              {item.operation === 'Tamamlandı' && (
                <Chip style={{backgroundColor: 'deepskyblue'}} icon="check-all">
                  {item.operation}
                </Chip>
              )}

              {item.operation === 'Reddedildi' && (
                <Chip style={{backgroundColor: 'crimson'}} icon="alert-circle">
                  {item.operation}
                </Chip>
              )}`

```

### Screenshots (if applicable)
**ANDROID**
![resim](https://user-images.githubusercontent.com/33424490/132133483-1c71bc0b-a208-44dd-a90a-91a073c724f8.png)
**IOS**
![simulator_screenshot_C717EC38-9477-4B39-A2F1-E69129A070CC](https://user-images.githubusercontent.com/33424490/132133492-dcdbc582-365c-4821-9933-87f2441732c2.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | BOTH
| react-native          | 0.63.4
| react-native-paper    | ^4.7.1
| node                  | v15.11.0
| npm or yarn           |npm
| expo sdk              | NA

**Comment by lukewalczak** [comment]
Hey @melihmuratpesmen, could you please provide a snack or simple repository presenting the bug?
