### ISSUE TITLE
TextInput placeholder showing 2 line

### ISSUE THREAD

**Issue by pritipatona** [callstack/react-native-paper#2891]
<img width="345" alt="Screenshot 2021-09-07 at 11 08 03 AM" src="https://user-images.githubusercontent.com/72775274/132290064-1ddaa960-f594-4cfb-a7e2-f433304cd504.png">

Any solution for this?

**Comment by David-Nguyen17** [comment]
> Hi, @pritipatona I'm not able to reproduce this. Could you create an example?

When you create TextInput and add a placeholder. If the placeholder is long the UI will create a broken line. (mode = 'flat'). It's only an android platform.
