### ISSUE TITLE
`withTheme` throws uncaught errors when called with arrow function SFCs

### ISSUE THREAD

**Issue by you-fail-me** [callstack/react-native-paper#290]
### Current behaviour

I'm getting uncaught errors coming from `withTheme`, more exactly from `isClassComponent` helper. If I wrap an SFC, written with an arrow function. The error is that it can't read property `render` of undefined. The reason is that arrow functions don't have a prototype (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions ).

### Expected behaviour

Expected behavior is the absence of uncaught errors when working with arrow functions

### Code sample

```
const component = () => <div />;
const failingComponent = withTheme(component);
```

### What have you tried

For now my workaround is to either use class or monkey-patch component's `prototype` property so `withTheme` doesn't fail.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 11.2
| react-native          | 0.54.0
| react-native-paper    | 1.1.1
| node                  | 9.4.0
| npm or yarn           | yarn 1.3.2

* also using `haul` and typescript with `awesome-typescript-loader` btw

I don't mind making a PR, just confirm you recognize the issue and look forward to merging that asap and I'll make it

**Comment by satya164** [comment]
Will be awesome if you can send a PR :D
