### ISSUE TITLE
How to add a placeholder in Avatar?

### ISSUE THREAD

**Issue by parmarravi** [callstack/react-native-paper#2912]

**Comment by lukewalczak** [comment]
Hey @parmarravi, could you please elaborate on the issue you are facing?

**Comment by parmarravi** [comment]
I have an Avatar component i want to set a default placeholder image  like this https://reactnativeelements.com/docs/avatar/  so when it fetch image it will just come above it

**Comment by parmarravi** [comment]
@klebaniukp  I am trying to say is . Avatar should have a parameter of placeholder. If u  see there are not many cases. It's like Image.networking in flutter .
https://flutter.dev/docs/cookbook/images/network-image
