### ISSUE TITLE
Custom Fonts missing bold

### ISSUE THREAD

**Issue by likon416** [callstack/react-native-paper#2917]
We are attaching custom fonts to our project and we want the theme to use custom bold font.
It works but it's missing bold font. Basically, all our fonts with the weight 'bold' have not assigned custom fonts.

export declare type Fonts = {
    regular: Font;
    medium: Font;
    light: Font;
    thin: Font;
};

it should have bold here, why it is missing? Why I can't specify custom bold font?

**Comment by YahyaBagia** [comment]
I am also thinking about the same..!! Did you get any solution / workaround to provide **Bold** font to react-native-paper?

**Comment by likon416** [comment]
@YahyaBagia yes, I'm just using expo-font and @expo-google-fonts/roboto packages and specify the fontFamily in styles each time I want to use Bold. Tbh I think better option if you dont care about material design is to use react native elements.

**Comment by raajnadar** [comment]
In the new version we can add custom properties to the theme us that https://callstack.github.io/react-native-paper/theming.html#extending-the-theme

**Comment by likon416** [comment]
@raajnadar yeah somehow I tried to do that, but it didn't work for me.

**Comment by raajnadar** [comment]
Did you try adding it in the fonts object? along with font name?

**Comment by likon416** [comment]
yeah I did all that, tried many different configuration I could find in google as well. didn't work for me.
