### ISSUE TITLE
Responsive font size

### ISSUE THREAD

**Issue by RemyMachado** [callstack/react-native-paper#2919]
### I was wondering if there is a convenient way to make the font responsive?
For instance, by customizing the theme object.

#### Use case:
Bigger font size on tablet device and smaller font size on smartphone.

**Comment by RemyMachado** [comment]
I ended up using a custom hook that checks the viewport dimension and returns the right `font-size`.
It would be better to give this job to the library since it already handles the typography components.

**Comment by R4Y-repo** [comment]
> I ended up using a custom hook that checks the viewport dimension and returns the right `font-size`. It would be better to give this job to the library since it already handles the typography components.

Hello 
Could you please tell the setup to make the text responsive?

**Comment by RemyMachado** [comment]
@R4Y-repo 
Hey, sorry I didn't go into details. The code was pretty bad.
As I said, I used a custom hook `useResponsiveFontSize` that returns the fontSize value depending on the current screen width (retrieved with [useWindowDimensions](https://reactnative.dev/docs/usewindowdimensions)).
Basically the hook is a `switch case` instruction, checking the screen width and returning an arbitrary value that seems to fit.
