### ISSUE TITLE
how to change paper components style at onece? (ex> Title and Dialog.Title)

### ISSUE THREAD

**Issue by jb9229** [callstack/react-native-paper#2927]
Hello

My app's font should be bigger than other apps.

So I'd like to increase the font size of the <Title/> Paper component.

Then, is there a way to enlarge the font of Paper's <Title/> component and the font of <Dialog.Title/> component at once?

react-native: 0.63.4
react-native-paper: 4.9.2
react-native-vector-icons: 7.1.0

**Comment by pihomeserver** [comment]
Via a theme props ?
