### ISSUE TITLE
When modal pops-up how to make android bottom navigation and statusBar translucent or transparent?

### ISSUE THREAD

**Issue by siddharth-kt** [callstack/react-native-paper#2944]
when modal(https://callstack.github.io/react-native-paper/modal.html) show up backdrop color is black but status bar color and bottom navigation menu (softmenu) on android are visible as white its looks weird.

(NOTE : I want to show these the same way, as default android Alert changes the statusbar and bottom navigation(softmenu) bar, colors.)

any solutions ?

As in default example of modal(Try this example on Snack) provided in react-native-paper docs, here : https://callstack.github.io/react-native-paper/modal.html

when I open this same example on expo then it makes statusBar transparent but on putting the same code in my react-native app status bar is visible as white. In both case bottom navigation(softmenu) is visible as white. 

versions :
react-native             :  0.65.1
react-native-paper  :  4.9.2

**Comment by chrismerino** [comment]
I'm facing the same issue, I have added the same code from the example but the status bar is still white while the backdrop is not on Android 11.

**Comment by BubbleTrouble14** [comment]
Same here, haven't found a way to fix it yet either :/

**Comment by ucheNkadiCode** [comment]
I added an answer to something similar on stackoverflow https://stackoverflow.com/a/75046007/17172147

This is the answer below. I did not test it on the status bar, but maybe you could try using "android:statusBarColor" and also setting it to @android:color/transparent as well. Good luck!
-------------------------------------------
I had this problem in Android as well. What I believe is happening is the react-native modal is simply taking the default `android:navigationBarColor` in the styles.xml and so every time it pops up, it overwrites the current navigation bar color until it gets dismissed. 

The flag statusBarTranslucent did not work for me. 

I was able to fix this by navigating to `res/values/styles.xml`

Then in the AppTheme style I added navigationBarColor to be transparent. 
It looks like this 

```xml
 <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">@android:color/black</item>
    <item name="android:navigationBarColor">@android:color/transparent</item> // <----This is what I added
  </style>
```

Then in my react native code, I used `react-native-navigation-bar-color`. I believe this should work with `expo-navigation-bar` since the main issue is derived from react native modal trying to overlay the default navBarColor value.

```javascript
import changeNavigationBarColor from "react-native-navigation-bar-color";

  const setDarkMode = (isDarkMode: boolean) => {
    // logic to change my app's themeProvider to dark mode
    changeNavigationBarColor(isDarkMode ? "black" : "white"); // Then I change the navigation bar color.
  };
```

**Comment by JairajJangleSLIOT** [comment]
Any updates on this issue? This issue is also observed for FAB backdrop. The  FAB backdrop down not go over the status bar and navigation bar in Android which looks bad.

**Comment by MADahab** [comment]
> ```
>     <item name="android:navigationBarColor">@android:color/transparent</item> // <----This is what I added
> ```

when i 
npx expo prebuild, this line get deleted. 5 years later any one find a solution?

**Comment by Kasendwa** [comment]
> > ```
> >     <item name="android:navigationBarColor">@android:color/transparent</item> // <----This is what I added
> > ```
> 
> when i npx expo prebuild, this line get deleted. 5 years later any one find a solution?

@MADahab  you'd need to add a config plugin for this to work. Something along the lines of 

```
/* Filename: ./with-transparent-navigation-bar.js */

const { AndroidConfig, withAndroidStyles } = require('@expo/config-plugins');

const withModalVisibleNavigationBarColor = (config) => {
  return withAndroidStyles(config, async (config) => {
    config.modResults = await configureModalNavigationBarColor(config.modResults);

    return config;
  });
};

async function configureModalNavigationBarColor(styles) {
  const noActionBar = styles.resources.style.find((style) => style.$.name === 'AppTheme');

  if (noActionBar) {
    noActionBar.item = noActionBar.item.filter((item) => item.$.name !== 'android:navigationBarColor');

    noActionBar.item.push(
      AndroidConfig.Resources.buildResourceItem({
        name: 'android:navigationBarColor',
        value: '@android:color/transparent',
      }),
    );
  }

  return styles;
}
```
and then you can add it in the Expo configs like

```
/* Filename: app.json */

{
  "expo": {
    "plugins": [
        ...yourOtherPlugins,
        "./with-transparent-navigation-bar.js"
      ]
   }
}
```

Where `yourOtherPlugins` is your other plugins :-)

**Comment by MADahab** [comment]
@Kasendwa Thank you for your solution i am gona try it in the next release, thanks again.

**Comment by Silverun** [comment]
Hello I just tried to setting Expo's app.json to this and ran prebuild:

"androidNavigationBar": {
      "backgroundColor": "@android:color/transparent"
    },

Work's the same as manually setting styles from above. 

Results in:
styles.xml:
<item name="android:navigationBarColor">@color/navigationBarColor</item>
colors.xml:
<color name="navigationBarColor">@android:color/transparent</color>

Hope this helps.
