### ISSUE TITLE
DataTable.Row borderStyle not working

### ISSUE THREAD

**Issue by sidnetopia** [callstack/react-native-paper#2957]
### Current behaviour

DataTable.Row borderStyle seems not working

### Code sample

```
<DataTable>
    <DataTable.Header>
      <DataTable.Title style={{ flex: 8 }}></DataTable.Title>
      <DataTable.Title style={{ flex: 6 }}></DataTable.Title>
      <DataTable.Title style={{ flex: 5 }}></DataTable.Title>
    </DataTable.Header>
    <DataTable.Row
        style={{
            marginTop: 30,
            paddingBottom: 30,
            borderBottomWidth: 10,
            borderRadius: 1,
            borderStyle: 'dashed',
        }}
    >
    <DataTable.Cell style={{ flex: 7, paddingRight: 10 }}>
        <Text style={{ fontWeight: 'bold', width: 10 }}></Text>
        <Text style={{ fontWeight: 'bold' }}></Text>
    </DataTable.Cell>
    <DataTable.Cell style={{ flex: 6, left: 6 }}>
        <Text style={{ fontWeight: 'bold' }}></Text>
    </DataTable.Cell>
    <DataTable.Cell style={{ flex: 5, left: 15 }}>
    </DataTable.Cell>
    </DataTable.Row>
  </DataTable>
```

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/36142076/139595705-0a3d7029-5e0f-4378-b00e-b305f2947e4f.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android 11.0
| react-native          | 0.66.1
| react-native-paper    | ^4.9.2
| node                  | 14.18.1
| npm or yarn           | npm 6.14.15
| expo sdk              | 42.0.0

**Comment by lukewalczak** [comment]
Hey @sidnetopia, could you please explain what doesn't work specifically? I assume the `dashed` border doesn't work, could you please confirm it?

**Comment by sidnetopia** [comment]
> Hey @sidnetopia, could you please explain what doesn't work specifically? I assume the `dashed` border doesn't work, could you please confirm it? Is your plan to have only bottom border dashed?

Yes, that was my plan tho I made an improvised version; by adding another row with just the `dashed` border.
![image](https://user-images.githubusercontent.com/36142076/140758105-dfe463d1-6589-4fc4-b4f1-2c5c08d79262.png)

**Comment by lukewalczak** [comment]
I think there is an issue with an individual dashed border on Android in `react-native` in general – not sure if the reported bug is specific to the library.
