### ISSUE TITLE
Chip styles

### ISSUE THREAD

**Issue by root-io** [callstack/react-native-paper#2959]
### Current behaviour

The size of the 3 chips in my example are shrink, we can't see the text

### Expected behaviour

The size of the 3 chips in my example should display a full height

### Code sample

```javascript
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Chip, List } from 'react-native-paper';

const ChipExample = () => {
  return (
    <>
      <List.Section title="Flat chip">
        <View style={styles.row}>
          <Chip selected onPress={() => { }} style={styles.chip}>
            Simple 1
          </Chip>
          <Chip selected onPress={() => { }} style={styles.chip}>
            Simple 2
          </Chip>
          <Chip selected onPress={() => { }} style={styles.chip}>
            Simple 3
          </Chip>
        </View>
      </List.Section>
    </>
  );
};

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 12,
  },
  chip: {
    margin: 4,
  },
});

export default ChipExample;
```

### Screenshots (if applicable)

![screenshot](https://user-images.githubusercontent.com/6101308/140511138-2de3cafe-bf12-4e9a-aa36-33bb3bf0afb7.jpg)

### What have you tried

Broken since 4.10.0, was working as expected in 4.9.2

### Your Environment

| software              | version
| --------------------- | -------
| android        | 12
| react-native          | 0.66.2
| react-native-paper    | 4.10.0
| node                  | 16.13.0
| npm           | 8.1.0
| expo sdk              | no

**Comment by lukewalczak** [comment]
Hello @root-io, please put your bug reproduction on [snack](snack.expo.io)

**Comment by jvincent-dev** [comment]
> Hello @root-io, please put your bug reproduction on [snack](snack.expo.io)

I added his code to a snack but changed the color of the Chip to make it more visible [here](https://snack.expo.dev/hYObt69RY)

**Comment by lukewalczak** [comment]
Thanks, I will be working on the fix in the upcoming days!
