### ISSUE TITLE
Modal is not visible on stacked page with react-navigation/native-stack

### ISSUE THREAD

**Issue by alesdvorakcz** [callstack/react-native-paper#2962]
### Current behaviour

Modal (or anything inside Portal component) is not visible on stacked pages when I use Native Stack Navigator from `react-navigation`. It is actually behind the modal screen.
Its only working when 'UIModalPresentationCurrentContext' is used (for example `presentation: 'containedModal'`.
https://reactnavigation.org/docs/native-stack-navigator#presentation

repro: https://github.com/alesdvorakcz/navigationtest

![Simulator Screen Recording - iPhone 13 - 2021-11-05 at 23 57 40](https://user-images.githubusercontent.com/1890782/140587245-147e2b3b-79a6-4a82-b813-56a93cc2e90e.gif)

### Expected behaviour

I am not 100% sure if a fix/support needs to be done on react native paper side or if its outside of your scope. But at least some explanation in docs would be maybe helpful for other users.

###Environment

| software              | version
| --------------------- | -------
| ios        | 15
| react-native          | 0.66.2 (also tested on 0.63.2)
| react-native-paper    | 4.10.0
| @react-navigation/native | 6.0.6
| @react-navigation/native-stack | 6.2.5 
| react-native-screens | 3.9.0
| react-native-vector-icons | 9.0.0

**Comment by iM-GeeKy** [comment]
Here is a [snack](https://snack.expo.dev/@fitzwabs/hello-react-navigation-%7C-react-navigation) demonstrating the issue as well. I'm curious what the recommendation is.

**Comment by lukewalczak** [comment]
Hello, I wasn't investigate that issue yet, so unfortunately cannot recommend any solution. Did you try to debug it on your end?

**Comment by iM-GeeKy** [comment]
> Hello, I wasn't investigate that issue yet, so unfortunately cannot recommend any solution. Did you try to debug it on your end?

I may have some bandwidth this weekend. I haven't done too much digging, but it looks like the `Modal` methods are firing, which would lead me to believe it could be `Portal` related.

**Comment by lukewalczak** [comment]
Hello, I guess you are missing `Portal.Host` around your screens. Please take a look on the presented [snack](https://snack.expo.dev/xcLTrOyOL) and let me know if it fix your issue.

**Comment by iM-GeeKy** [comment]
> 

Thanks for the quick response. I did ultimately end up getting it resolved by rearchitecting the navigation, but your solutions works as well. Feel free to close this and thanks again.

**Comment by iM-GeeKy** [comment]
> Hello, I guess you are missing `Portal.Host` around your screens. Please take a look on the presented [snack](https://snack.expo.dev/xcLTrOyOL) and let me know if it fix your issue.

Thanks for the quick response. I did ultimately end up getting it resolved by rearchitecting the navigation, but your solutions works as well. Feel free to close this and thanks again.

**Comment by MathisBarre** [comment]
> Hello, I guess you are missing `Portal.Host` around your screens. Please take a look on the presented [snack](https://snack.expo.dev/xcLTrOyOL) and let me know if it fix your issue.

Thanks, this is helpful !

**Comment by tanishapatel-zymr** [comment]
@iM-GeeKy @lukewalczak  How did you fix this issue cause I am facing the same issue where the modal is rendering but not visible this lead to the app become non responsible
