### ISSUE TITLE
Card Border Color on Android is always grey 

### ISSUE THREAD

**Issue by checklist** [callstack/react-native-paper#2966]
### Current behaviour
When setting card border color it works for iOS but not for Android: I always get grey color

### Expected behaviour
The color of the border to be as set

### Code sample

https://snack.expo.dev/@checklist/card

### Screenshots (if applicable)

For Web/ iOS:
![image](https://user-images.githubusercontent.com/1918168/140609137-8f128353-e1a8-445f-bcff-3e823039e8fe.png)

For Android:

![image](https://user-images.githubusercontent.com/1918168/140609152-9b4f88cd-845d-41ba-89b9-6b6cab7e629a.png)

### What have you tried

Different colors
Different widths

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | both
| react-native          | latest
| react-native-paper    | latest
| node                  | not applicable
| npm or yarn           |not applicable
| expo sdk              | not applicable

**Comment by checklist** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `react-native`
> * `react-native-paper`
> * `react-native-vector-icons`
> * `npm`
> * `yarn`
> * `expo`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

react-native 0.64
react-native-paper 4.10.0
react-native-vector-icons N/A
npm N/A
yarn N/A
expo N/A

**Comment by lukewalczak** [comment]
Hey @checklist, please try to use `borderStartColor` instead.

**Comment by checklist** [comment]
> Hey @checklist, please try to use `borderStartColor` instead.

Yes!!! That did the trick.

Would be nice if you could somehow put it in the docs as I didn't find it anywhere. 

Thanks so much for your help! Have a great weekend.
