### ISSUE TITLE
Unable to get Appbar with proper Hamburger, Back Button with Screen Title

### ISSUE THREAD

**Issue by sodhigurpreetsingh** [callstack/react-native-paper#2971]
### Discussed in https://github.com/callstack/react-native-paper/discussions/2969

<div type='discussions-op-text'>

<sup>Originally posted by **sodhigurpreetsingh** November  7, 2021</sup>
Hello all

I am trying to use the Appbar inside Drawer Navigation but i am unable to find an example where i could display a Hamburger Menu and when clicked on a Route, it displays the Page Screen Name  or Title with a back button.. the standard Drawer Navigator style where everything is on top left..

I have uploaded my code on Snack, can someone please advise how can i achieve this with react native paper.

Here is my link to code: https://snack.expo.dev/@smith.james1982/github.com-callstack-react-native-paper-login-template

Thanks
Gurpreet</div>

**Comment by sodhigurpreetsingh** [comment]
Link to snack

https://snack.expo.dev/@smith.james1982/github.com-callstack-react-native-paper-login-template

**Comment by lukewalczak** [comment]
Hey @sodhigurpreetsingh I have a problem with understanding your issue. Could you please elaborate more on what are you trying to achieve?
