### ISSUE TITLE
Chip does not have a height

### ISSUE THREAD

**Issue by dardinier** [callstack/react-native-paper#2972]
### Current behaviour

Chip does not have height.

![Screenshot_2021-11-08-16-19-30-706_host exp exponent](https://user-images.githubusercontent.com/24563898/140774220-4e7a07bc-2eaf-43d1-a5fc-2878c1092044.jpg)

### Expected behaviour

Chip should have a height and be visible.

![Screenshot_2021-11-08-16-19-50-355_host exp exponent](https://user-images.githubusercontent.com/24563898/140774251-99a7c7d0-27e5-406d-9b12-d49f856f1b2e.jpg)

### Code sample

https://snack.expo.io/o8csskeeVo

On mobile only. The web version shows the correct result.

### What have you tried

Having the `Chip` component inside a `ScrollView` seems to fix the bug.

Example : https://snack.expo.io/CXZOrbGgY

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android 10 (API level 29)
| react-native          | 0.63.4
| react-native-paper    | 4.10.0
| node                  | 14.11.0
| npm or yarn           | yarn 1.22.5
| expo sdk              | 43.0.0

**Comment by dardinier** [comment]
I provided two samples, they are hosted under `snack.expo.dev` instead of `snack.expo.io` from now.

**Comment by lukewalczak** [comment]
Similar to: https://github.com/callstack/react-native-paper/issues/2959. It's on my radar, will fix it soon.
