### ISSUE TITLE
textbox placeholde behind the text

### ISSUE THREAD

**Issue by devjaw** [callstack/react-native-paper#298]
the placeholder should be empty if the Textbox value length is greater than zero. 

![capture3](https://user-images.githubusercontent.com/15944990/38289721-ac3a39bc-37e8-11e8-828d-35819f6de7a7.PNG)

**Comment by ferrannp** [comment]
Can you provide code sample or snack with this behavior? `TextInput` placeholder works ok in our example.

**Comment by gawrysiak** [comment]
@ferrannp this happens when the value field is not set

**Comment by ferrannp** [comment]
Oh, so basically our `TextInput` only supports controlled component way right now. For this to work we would have to address: https://github.com/callstack/react-native-paper/issues/154.

**Comment by devjaw** [comment]
hello again, 
this is the TextInput without value : 
![capture1](https://user-images.githubusercontent.com/15944990/38315276-2f0ff246-3839-11e8-9885-c67430b6c4aa.PNG)

and here TextInput with value : 
![capture2](https://user-images.githubusercontent.com/15944990/38315286-34ba5506-3839-11e8-8731-e314cd74cc0b.PNG)

and it should be like this : 
![capture3](https://user-images.githubusercontent.com/15944990/38315297-3cd43ce8-3839-11e8-87fc-dfdcc538d00b.PNG)

**Comment by Trancever** [comment]
@devjaw Can you provide code/repository with reproduced issue?

**Comment by devjaw** [comment]
@Trancever this is my code for `TextInput` : 

`<TextInput
            ref ="EmailPassword"
            label='Password'
            onChangeText={(text)=>this.setState({Password:text})}
            secureTextEntry={true}
            ref={input => {this.PasswordInputRef = input}}
            onSubmitEditing={this.switchToApp.bind(this)}
          />`
