### ISSUE TITLE
TextInput Affix only displays after focus 

### ISSUE THREAD

**Issue by conor909** [callstack/react-native-paper#2983]
TextInput Affix only displays after focus

`react-native-paper 4.9.2`
`react-native sdk42`
`expo 42.0.0`

A user should know of any Affix information before they start to type.  I suggest always display the `right` node, or optionally always display it

**Alternatives**
We need to write a custom `TextInput`, or fork `rn-paper` to change the `right` property behaviour

**Screenshots**
![Screenshot 2021-11-19 at 16 40 16](https://user-images.githubusercontent.com/2417359/142659640-92d61612-f203-4562-980c-8ee6d9785a94.png)
![Screenshot 2021-11-19 at 16 40 21](https://user-images.githubusercontent.com/2417359/142659655-4e89a74b-dd64-4a9e-8618-3a83cd1994f5.png)

**Comment by lukewalczak** [comment]
Hey @conor909, MD documentation indicates that suffix or affix should be visible in **focused** state if input is **empty**.

affix | suffix
--- | --- |
![image](https://user-images.githubusercontent.com/22746080/142728585-0c01e1c3-2813-49ce-b993-d00ff0bc5369.png) | ![image](https://user-images.githubusercontent.com/22746080/142728591-c20363e5-4a05-45c9-89f7-f20774634b24.png) |

**Comment by conor909** [comment]
Fair enough, just another quirk of MD. Thanks

**Comment by mkhoussid** [comment]
> Hey @conor909, MD documentation indicates that suffix or affix should be visible in **focused** state if input is **empty**.
> 
> affix	suffix
> ![image](https://user-images.githubusercontent.com/22746080/142728585-0c01e1c3-2813-49ce-b993-d00ff0bc5369.png)	![image](https://user-images.githubusercontent.com/22746080/142728591-c20363e5-4a05-45c9-89f7-f20774634b24.png)

Here we go again with [`patch-package`](https://www.npmjs.com/package/patch-package).

**Comment by badalsaibo** [comment]
Still can we have a prop for such edge cases?

**Comment by amanpuranik** [comment]
A prop would be much more useful. pretty common usecase

**Comment by VictorioMolina** [comment]
this sucks

**Comment by salememd** [comment]
We need to control this , using TextInput.Affix as labels is common thing

**Comment by BenDevelopment** [comment]
Any fix/workaround for this problem?
