### ISSUE TITLE
How to prevent the ListAccordion from leaking into the corner of a Card?

### ISSUE THREAD

**Issue by gloredo** [callstack/react-native-paper#2988]
```js
<Card mode="outlined" style={{ margin: 16, borderColor: 'red' }}>
  <List.Accordion style={{ borderWidth: 1, borderRadius: 4, borderColor: 'blue' }}}>
      <List.Item style={{ borderWidth: 1, borderRadius: 4 }}/>
  </List.Accordion>
</Card>
``` 
`List.Accordion` leaks
![accordion](https://user-images.githubusercontent.com/20311005/143621560-763524f0-c129-4f40-b9d7-81744cf6724e.png)

`List.Item` works
![item](https://user-images.githubusercontent.com/20311005/143621562-72db308e-9920-4d17-9803-c7f2c41f5ef0.png)

**Comment by gloredo** [comment]
`overflow: 'hidden'` solve this

**Comment by quicksilverr** [comment]
nah, man, it's still not hidding
