### ISSUE TITLE
The Appbar.BackAction icon in RTL is the opposite in Web

### ISSUE THREAD

**Issue by samaneh-kamalian** [callstack/react-native-paper#2989]
As you can see, in RTL back icon is not correct. Can anybody help how to solve it?
![Screen Shot 2021-11-27 at 11 34 41 AM](https://user-images.githubusercontent.com/57032373/143673932-43f4c62d-7be9-434f-874f-ba903deaad89.png)

The correct display is:

![Screen Shot 2021-11-27 at 11 55 07 AM](https://user-images.githubusercontent.com/57032373/143674131-70708c7a-4045-429d-9402-225791830421.png)

react-native : 0.63.4
react-native-paper: 4.9.2
react-native-vector-icons: 7.0.0

**Comment by samaneh-kamalian** [comment]
I upgraded react-native-paper and react-native-vector-icons but the issue still exist

**Comment by samaneh-kamalian** [comment]
According to source code of backAction, I think this is bug of react-native-paper in web: 

```
 return Platform.OS === 'ios' ? (
    <View
      style={[
        styles.wrapper,
        {
          width: size,
          height: size,
          transform: [{ scaleX: I18nManager.isRTL ? -1 : 1 }],
        },
      ]}
    >
      <Image
        source={require('../../assets/back-chevron.png')}
        style={[
          styles.icon,
          { tintColor: color, width: iosIconSize, height: iosIconSize },
        ]}
      />
    </View>
  ) : (
    <MaterialCommunityIcon
      name="arrow-left"
      color={color}
      size={size}
      direction={I18nManager.isRTL ? 'rtl' : 'ltr'}
    />
  );
};
```
Am I right?

**Comment by lukewalczak** [comment]
@samaneh-kamalian could you please provide the repro in form on [snack](expo.snack.dev) or sample repository?

**Comment by samaneh-kamalian** [comment]
> @samaneh-kamalian could you please provide the repro in form on [snack](expo.snack.dev) or sample repository?

Thanks for your consideration. I used this code in my pages:

```
    this.props.navigation.setOptions({
      header: () =>
        <Appbar.Header>
          <Appbar.BackAction color="white" onPress={this.props.navigation.goBack} />
          <Appbar.Content color="white" title={this.context.translate("UiTexts.help.title")} />
        </Appbar.Header>
    });
```
I dont have any problem in android but in web the icon is not correct.

**Comment by samaneh-kamalian** [comment]
Is there any solution? :(

**Comment by lukewalczak** [comment]
Hey @samaneh-kamalian, I tried your code on snack and back icon has the correct direction when switching it, please take a look at my [result](https://snack.expo.dev/KD0bxjYGS).

![webrtl](https://user-images.githubusercontent.com/22746080/145246996-e116aad0-169a-4559-910d-94351dc5337b.gif)

Can you create a sample repository representing your issue?

**Comment by samaneh-kamalian** [comment]
> Hey @samaneh-kamalian, I tried your code on snack and back icon has the correct direction when switching it, please take a look at my [result](https://snack.expo.dev/KD0bxjYGS).
> 
> ![webrtl](https://user-images.githubusercontent.com/22746080/145246996-e116aad0-169a-4559-910d-94351dc5337b.gif)
> 
> Can you create a sample repository representing your issue?

I copied exactly your code into my project but it still has the same problem. Do you have any idea where the problem could come from ?! :(

**Comment by lukewalczak** [comment]
Hey @samaneh-kamalian, it's hard to say what can be the root of the issue in your case without knowing basic information about your technology stack or environment. Could you please create a simple repository with bug reproduction or maybe you are able to present it on the snack?

**Comment by samaneh-kamalian** [comment]
I solved my issue with adding this style to Appbar.backAction: 

style={{transform: this.context.language === "ar" && Platform.OS === 'web' ? "scaleX(-1)" : undefined}}
