### ISSUE TITLE
Divider does not show at all or has a different thickness every time

### ISSUE THREAD

**Issue by AndrewIsBest69** [callstack/react-native-paper#2992]
### Current behaviour

When using the Divider component to... well divide stuff, it does not get displayed, or, if you make it very thick, it does, but with a different thickness every time.

### Expected behaviour

The divider component should be visible without any extra styling and with the same thickness all the time.

### Code sample

`
<Text>Hello</Text>
<Divider style={{ height: 1 }} />
<Text>Hello</Text>
<Divider style={{ height: 1 }} />
<Text>Hello</Text>
<Divider style={{ height: 1 }} />
<Text>Hello</Text>
<Divider style={{ height: 1 }} />
<Text>Hello</Text>
<Divider style={{ height: 1 }} />
`

For some reason, it only happens sometimes on https://snack.expo.dev/ with the divider example - https://snack.expo.dev/?name=Divider&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fdivider.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20View%20%7D%20from%20%27react-native%27%3B%0Aimport%20%7B%20Divider%2C%20Text%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20(%0A%20%20%3CView%3E%0A%20%20%20%20%3CText%3ELemon%3C%2FText%3E%0A%20%20%20%20%3CDivider%20%2F%3E%0A%20%20%20%20%3CText%3EMango%3C%2FText%3E%0A%20%20%20%20%3CDivider%20%2F%3E%0A%20%20%3C%2FView%3E%0A)%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper

### Screenshots (if applicable)

![Screenshot_1638111194](https://user-images.githubusercontent.com/47299500/143773148-89f5b60c-8ca4-48b4-80b1-d9f2842a7b45.png)
![Screenshot_1638111201](https://user-images.githubusercontent.com/47299500/143773149-5cc7acf0-5d97-4acd-bd82-0943135a2f3b.png)

### What have you tried

I tried increasing the thickness by making the height style property larger and while this gives me a visible divider, it's thickness is different every time.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android 11
| react-native          | 0.66.2
| react-native-paper    | 4.10.0
| node                  | v16.13.0
| npm           | 8.1.0
| react-native-vector-icons              | 9.0.0
| yarn              | 0.0.0
| expo              | 0.0.0

**Comment by lukewalczak** [comment]
Hey @AndrewIsBest69, I guess the issue can be related to the `hairLineWidth` property in styles, which comes directly from `react-native` and is based on pixel calculation.
