### ISSUE TITLE
createMaterialBottomTabNavigator doesn't work

### ISSUE THREAD

**Issue by SaiSridhar783** [callstack/react-native-paper#2993]
### Current behaviour

When passing a NativeStackNavigator as a component, only on the first click the proper component is rendered. Thereafter, it's a blank

### Expected behaviour

StackNavigator should render on every click

### Code sample

[Github Repo](https://github.com/SaiSridhar783/React-Native/tree/dfc71825fcf35c7384e2e9102f2143a6b8e13339)

### Screenshots (if applicable)

![Android Emulator - Pixel_4_API_29_5554 2021-12-01 16-18-15](https://user-images.githubusercontent.com/58875230/144221272-47c8b746-dc42-4ac9-bb93-f3f9da1ceac9.gif)

### What have you tried

Normal BottomTabsNavigator works fine but not Material

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.64.3
| react-native-paper    | 4.10.1
| node                  | 16.13.0
| npm or yarn           | yarn
| expo sdk              | ~43.0.2

**Comment by junayed111** [comment]
Any update on this bug? I am facing the same issue

**Comment by lukewalczak** [comment]
Please take a look here: https://github.com/react-navigation/react-navigation/issues/10081 or there: https://github.com/software-mansion/react-native-screens/issues/1197

**Comment by SaiSridhar783** [comment]
Yes, react-navigation/react-navigation#10081 works. Shouldn't this change be made in the original Repo?

**Comment by traviswimer** [comment]
@lukewalczak I am also confused which repo this issue should actually be on. Would it be a good idea to close some of these duplicates and direct them to whichever one is on the correct repo?

Also, for anyone interested, a simple workaround was mentioned here: https://github.com/software-mansion/react-native-screens/issues/1197#issuecomment-993682256

Basically just wrap your stack navigator with `<View style={{flex: 1}} collapsable={false}></View>`

**Comment by Shankhara** [comment]
Hi,
I am using Vanilla React Native, similar bug occurs while testing on Android Simulator & Android Phone.

I recently replaced `createBottomTabNavigator` by `createMaterialBottomTabNavigator` using [ReactNavigation - Material Bottom Tabs Navigator documentation](https://reactnavigation.org/docs/material-bottom-tab-navigator).

The same process as described in this issue makes **the app crash without error**.
### Versions
- package.json
```json
    "@react-navigation/material-bottom-tabs": "^6.0.9",
    "@react-navigation/native-stack": "^6.2.5",
    "react": "^17.0.2",
    "react-native": "^0.67.0",
    "react-native-paper": "^4.11.2",
```

**Comment by Shankhara** [comment]
This issue has no reasons to be closed, since this feature is not working (as explained above)

**Comment by traviswimer** [comment]
@Shankhara Any idea what you're doing differently that the workaround doesn't work?
