### ISSUE TITLE
Mouse cursor does not change for Card onPress (react native web)

### ISSUE THREAD

**Issue by buffaloDeveloper** [callstack/react-native-paper#2998]
`<Card onPress={() => {}}>`

If you add an onPress, the mouse cursor will not change on hover-over (react native web).

**Comment by lukewalczak** [comment]
`Card` component is using the `TouchableWithoutFeedback` under the hood, where default cursor is the intended style, based on the `react-native-web` author [comment](https://github.com/necolas/react-native-web/issues/1847#issuecomment-747625960). If you would like to support it in your application you can easily handle it via styles prop:

```
<Card
  style={[styles.card, { cursor: 'pointer' }]}
  onPress={() => {
    console.log('Pressed');
  }}
> 
	...
</Card>
```
