### ISSUE TITLE
Fab Toolbar

### ISSUE THREAD

**Issue by ahmedlhanafy** [callstack/react-native-paper#30]
[Angular Material Docs Link](https://material.angularjs.org/latest/demo/fabToolbar)

**Comment by sreejithr** [comment]
I've started work on . Will put a pull request once rudimentary features have been added.

**Comment by satya164** [comment]
The angualr page doesn't follow the transitions properly. Here is the design docs -  https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions

**Comment by sreejithr** [comment]
Rudimentary work has been completed. You can check it out at `fab-toolbar` branch in my fork ([link](https://github.com/sreejithr/react-native-paper/blob/fab-toolbar/src/components/FABToolbar.js)).

To test, replace dependency with `react-native-paper: "git+git@github.com:sreejithr/react-native-paper.git#fab-toolbar"` and `npm install`. Sample code:
```
<FABToolbar>
  <View><Text>Buttons go here</Text></View>
</FABToolbar>
```
Following props work:
1. `mini`: `bool`. Smaller button.
2. `direction`: `FABToolbar.Direction`. Direction the toolbar should grow towards.

Planned props:
1. `icon`: `Component`.
2. `open`: `bool`. Control opening with prop.

I see that `Portal` is coming up and would affect `FABToolbar` once it is merged. Hence, before moving forward, let me know if anything here would disrupt `Portal` behavior.

**Comment by satya164** [comment]
@sreejithr Awesome. Will check it out.

Portal is already in master - https://github.com/react-native-paper/react-native-paper/tree/master/src/components/Portal

Use `ThemedPortal` since we will need to preserve the theme and use the `position` to specify it's position in z-axis

**Comment by ahmedlhanafy** [comment]
@sreejithr Are you still interested in completing this component?

**Comment by sreejithr** [comment]
@ahmedlhanafy Yes. I got busy with work lately. I want to sit down for couple hours and finish this. I'll push the rest of the component this week.

**Comment by ahmedlhanafy** [comment]
@sreejithr Awesome waiting for that!

**Comment by sreejithr** [comment]
@ahmedlhanafy I'm almost finished with FAB Toolbar. Here's what's left:

- [ ] Animate elevation of button on touch.
- [ ] Sample code in example project.

I'll get the sample code up in a day. You guys can test using it after that.

**Comment by sreejithr** [comment]
Sample code is up in the example project. Check it out. What's left is to elevate the button on touch. Are you guys OK with the component's API?
