### ISSUE TITLE
fab components labelstyle

### ISSUE THREAD

**Issue by sfalihi** [callstack/react-native-paper#3001]
the problem is sometimes based on label font you need to adjust label to center.(arabic fonts,...) and sometimes you need to change the weight or size of label.
i think its not that hard or time consuming to add this simple thing.
so why dont you provide this simple prop to fab, fabgroup and animatedfab

e.g. => the only way to fix this font height issue is like labelstyle={{top:-1}} 

![imageedit_2_8560594074](https://user-images.githubusercontent.com/24459817/145419939-388ce7f0-b394-4f80-b063-1e03e8333858.png)

**Comment by p-syche** [comment]
Hi @sfalihi,

As you may have noticed our github-actions bot is asking for you to add a reproducible example, in our case that is a snack on expo.
I also noticed you wrote "i think its not that hard or time consuming to add this simple thing." Sounds like you have a pretty good idea of what needs to be done, do you think you could create a PR for this? If you do manage to propose changes they will probably get merged sooner :)

**Comment by sfalihi** [comment]
actually i haven't done a pull request before but it seems just passing a style prop down to a text component so because of that i said it seems not that hard.
but i wrote that because i know this problem exist for a long time and many people asked  for change in color, size, ... and now i faced this font line height problem also.
i'll try to make a PR but pls consider to add this to your todo list.
tnx
