### ISSUE TITLE
TextInput with `mode: 'outlined'` and `label` cutting off beginning of the text

### ISSUE THREAD

**Issue by Risovas** [callstack/react-native-paper#3003]
### Current behaviour

I'm using the library's `TextInput` component with the `mode` prop set to `outlined` and the `label` prop set to some text like `E-mail` for example. Until version 4.10.1 it was working fine, but today when I updated to 4.11.0, the beginning of the text started to be cut out on `Android` when setting the `label` prop. 

### Expected behaviour

The text inside the `TextInput` should be completely shown.

### Code sample

```react
import React from 'react';
import { View } from 'react-native';
import { TextInput } from 'react-native-paper';

    <View style={{ backgroundColor: Theme.Colors.BLACK_0, flex: 1, padding: 16 }}>
      <TextInput mode='outlined' />
      <TextInput label='E-mail' mode='outlined' style={{ marginTop: 16 }} />
    </View>
```

### Screenshots

Result of the code above using `react-native-paper@4.10.1`

![Screenshot_20211211-110334_mobFleet](https://user-images.githubusercontent.com/35196992/145679836-af0e1eea-22c9-48a7-962a-9b7662e93a9e.jpg)

Result using `react-native-paper@4.11.0`

![Screenshot_20211211-110547_mobFleet](https://user-images.githubusercontent.com/35196992/145679856-eecfd6d6-8eec-4a36-92e1-6c1f4c8637af.jpg)

### What have you tried

I went through all the commits of release v4.11.0 that seemed to be related to this issue and I found that this one is causing it: 6aa2c509bb7cb58689912d84d05b956705843991, more specifically, the `zIndex: 3` part on `src/components/TextInput/Label/InputLabel.tsx`. Removing it made the input work again. Not really sure how to solve the issue but I thought it would be good to report since it's affecting my usage. Will leave the lib at version 4.10.1 until this is fixed or someone gives me a hint of how to fix it through style props or something along those lines.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android 11
| react-native          | 0.66.4
| react-native-paper    | 4.10.1 - 4.11.0
| node                  | 14.16.0
| npm or yarn           | npm 6.14.11
| expo sdk              | not using

**Comment by lukewalczak** [comment]
Thanks for reporting a bug an initial investigation. I will try to fix it asap and in the meantime please use version 4.10.1

**Comment by Risovas** [comment]
Thank you very much, I appreciate the effort.

**Comment by lukewalczak** [comment]
Hello @Risovas, please upgrade Paper to version `4.11.1` and please let me know if you encounter any other issues

**Comment by Risovas** [comment]
@lukewalczak tested on `4.11.1`, now it's showing the entire text again, no other bugs that I could notice, will let you know if I encounter anything else. Thank you again!
