### ISSUE TITLE
How can i hide a tab in Bottom Navigation

### ISSUE THREAD

**Issue by sodhigurpreetsingh** [callstack/react-native-paper#3005]
Hello

Can someone please advise how can i hide a tab from display in Bottom Navigation,  i want to jumpTo the tab from code but i don't want it show in the Bottom Navigation. Below is some code i am using, i just want to hide the vehicle_edit tab,

please if someone can advise.

``
  //routes
  const [routes] = React.useState([
    { key: "dashboard", title: "Dashboard", icon: "home" },
    { key: "notifications", title: "Notifications", icon: "bell" },
    { key: "account", title: "My Account", icon: "account" },
    { key: "vehicle_edit", title: "Vehicles", icon: "car"  },
    { key: "appointments", title: "Appointments", icon: "calendar" },
  ]);

  //set bottom tab to first always
  useEffect(() => {
    setIndex(0);
  }, []);

  //screens
  const renderScene = BottomNavigation.SceneMap({
    dashboard: DashboardScreen,
    notifications: NotificationsScreen,
    account: AccountScreen,
    vehicle_edit: VehicleEditScreen,
    appointments: AppointmentsScreen,
  });

  //render
  return <BottomNavigation navigationState={{ index, routes }} onIndexChange={setIndex} renderScene={renderScene} />;
``

**Comment by lukewalczak** [comment]
Please check the discussion in the similar issue: https://github.com/callstack/react-native-paper/issues/1563

**Comment by sodhigurpreetsingh** [comment]
Sorry, i just used stack navigation to solve this. kindly ignore.
