### ISSUE TITLE
Cannot use TextInput static component as separate component

### ISSUE THREAD

**Issue by bombillazo** [callstack/react-native-paper#3008]
### Current behaviour

With `TextInput`, one cannot set the `left` and `right` to an external component that returns a valid TextInput static component i.e `TextInput.Icon` and `TextInput.Affix`. 

### Expected behaviour

I want to be able to separate `TextInput.Icon` into components that can be imported and used with TextInput.

### Code sample

```jsx
// Does Not Work
import React from 'react';
import { TextInput } from 'react-native-paper';

export const TextInput = (props) => {
  return (
    <TextInput
      style={[{ marginVertical: 8, marginHorizontal: 8 }, props.style]}
      {...props}
      left={<TextInputArrowIcon />}
    />
  );
};

const TextInputArrowIcon = () => {
  return <TextInput.Icon name="chevron-down" />;
};
```
Result:
![image](https://user-images.githubusercontent.com/44002321/145874810-ccaefde9-68c8-4e0c-a93d-80ab21911c55.png)

### What have you tried

One can declare the static component directly in the property or as a variable inside the same component:

```jsx
import React from 'react';
import { TextInput } from 'react-native-paper';

export const TextInput = (props) => {
  return (
    <TextInput
      style={[{ marginVertical: 8, marginHorizontal: 8 }, props.style]}
      {...props}
      left={<TextInput.Icon name="chevron-down" />}
    />
  );
};

// OR

export const TextInput: = (props) => {
  const iconComponent = <TextInput.Icon name="chevron-down" />;
  return (
    <TextInput
      style={[{ marginVertical: 8, marginHorizontal: 8 }, props.style]}
      {...props}
      left={iconComponent}
    />
  );
};
```
Result:
![image](https://user-images.githubusercontent.com/44002321/145874897-54ba374b-ec93-4e0b-ad10-11c86f04c6bd.png)

But I need this component to be an external component.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          | 0.66.4
| react-native-paper    | 4.11.1
| node                  |
| npm or yarn           |
| expo sdk              |

**Comment by BrenoVelasco** [comment]
Any updates on this?

**Comment by sidnetopia** [comment]
Updates?
