### ISSUE TITLE
Apps supporting a dark theme frequently crash when the theme is toggled

### ISSUE THREAD

**Issue by DoctorJohn** [callstack/react-native-paper#3009]
### Current behaviour

When switching between a light and a dark theme (e.g. by using the OSs theme setting in combination with the react-native Appearance API) the following error frequently occurs and the app crashes.

```Error: Style property 'backgroundColor' is not supported by native animated module```

Linked issue: #2063 #2574 #2167 #2641
Linked PR: #2113 #2068

### Expected behaviour

Well, the app shouldn't crash

### Code sample

Any app with [Dark Theme support](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#support-dark-theme), dedicated light and dark themes would work. (The app would also need to display one of the affected components described below). Expo go apparently doesn't support system wide dark themes so one would need to copy [this snack](https://snack.expo.dev/fsD5aYi0G) to hopefully have a working repro.

### What have you tried

The root cause for this error is that the `backgroundColor` of the `Surface` component is calculated based on the Surfaces elevation (using the `overlay()` helper). However, `Card`, `Button` and `Chip` animate their elevation which causes their Surfaces `backgroundColor` to be animated as well which causes said error.

There were attempts to fix this by disabling the native animation driver if toggling of the dark mode is detected.
Unfortunately, these attempts did not cover all cases. Furthermore, disabling the native animation driver isn't optimal for performance reasons.

What's the Surface components expected behaviour here? Should its background color change when its elevation is animated?
In this case we can't use the native animation driver and should disable it for elevation animations of said components.

Or should the Surface component keep its background color when its evelation is animated?
In this case we need a way to tell the Surface component which fixed elevation to use to calculate its background color.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.66.4
| react-native-paper    | 4.11.1
| node                  | 14.18.2
| npm or yarn           | npm 8.3.0

**Comment by yuvalotem** [comment]
Had the same problem, you can wrap card content with React Native TouchableOpacity or you can use React native Animated.createAnimatedComponent as described here - https://github.com/callstack/react-native-paper/issues/2364

**Comment by raajnadar** [comment]
@lukewalczak even I can repro this issue

Log from google play pre launch report

[logcat.txt](https://github.com/callstack/react-native-paper/files/7797626/logcat.txt)


```
FATAL EXCEPTION: mqt_native_modules
Process: in.raajnadar.newspaper, PID: 32055
com.facebook.react.common.c: Error: Style property 'backgroundColor' is not supported by native animated module
This error is located at:
    in O
    in Unknown
    in Unknown
    in _
    in Unknown
    in w
    in _
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in l
    in RCTView
    in Unknown
    in RCTScrollView
    in L
    in ScrollView
    in Unknown
    in u
    in j
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in w
    in RNCViewPager
    in M
    in O
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in O
    in Unknown
    in PanGestureHandler
    in Unknown
    in RCTView
    in Unknown
    in O
    in Unknown
    in RCTView
    in Unknown
    in P
    in Unknown
    in RNSScreen
    in O
    in Unknown
    in J
    in p
    in Unknown
    in RNSScreenContainer
    in ScreenContainer
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in _
    in RCTView
    in Unknown
    in h
    in GestureHandlerRootView
    in Unknown
    in K
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in Unknown
    in RNSScreen
    in O
    in Unknown
    in J
    in p
    in Unknown
    in RNSScreenContainer
    in ScreenContainer
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AnimatedComponent(View)
    in Unknown
    in RCTView
    in Unknown
    in AnimatedComponent(View)
    in Unknown
    in PanGestureHandler
    in Unknown
    in X
    in L
    in GestureHandlerRootView
    in Unknown
    in RNCSafeAreaProvider
    in Unknown
    in h
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in c
    in RCTView
    in Unknown
    in Portal.Host
    in P
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in b, js engine: hermes, stack:
validateStyles@1:295495
value@1:316574
value@1:292630
value@1:298597
value@1:316231
value@1:298523
value@1:313840
O@1:313477
value@1:335297
value@1:335717
ar@1:119857
bl@1:131615
la@1:163388
ti@1:148898
ei@1:148801
Za@1:148685
qa@1:146250
anonymous@1:116871
anonymous@1:250276
_t@1:116539
Ct@1:116724
Pt@1:116618
xe@1:164223
Re@1:109777
ze@1:110066
receiveEvent@1:158329
value@1:67417
anonymous@1:66034
value@1:66984
value@1:65992
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:134)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:147)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loop(Looper.java:176)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by hafridi** [comment]
Anyone figured out a way to fix this issue?

**Comment by jhonywalkeer** [comment]
My problem is being the first time the user uses the night mode option the application crashes, and my Google Play console is reporting the same report as @raajnadar

**Comment by lukewalczak** [comment]
Hey, I've refreshed the PR mentioned above, which is resolving the issue with `Card` animation drivers behavior related to switching the theme.

Please try the new PR: https://github.com/callstack/react-native-paper/pull/3041 and let me know about the result ✌🏽
