### ISSUE TITLE
Material design 3 (Material you)

### ISSUE THREAD

**Issue by AndrewIsBest69** [callstack/react-native-paper#3012]
Just a simple question which I have no idea if it was answered before somewhere else. Is react-native-paper planning on supporting Material design 3 (Material you) in the future? I'd love to use it and the essential components like buttons or FABs have been already introduced in Jetpack Compose.

**Comment by lukewalczak** [comment]
Hello @AndrewIsBest69, sure we are going to adjust Paper to Material You. We are planning to start the work at the turn of January and February.
