### ISSUE TITLE
Why aren't "theme" props optional?

### ISSUE THREAD

**Issue by reggi** [callstack/react-native-paper#3013]
I found a couple of instances of components where the `theme` prop is required. Is there a specific reason for this?

https://github.com/callstack/react-native-paper/blob/main/src/components/TextInput/TextInput.tsx#L133

**Comment by peh** [comment]
The documentation states theme as optional and can only be fixed by downgrading to 4.9.2.
It's a bit annoying to bot be able to use the latest version without errors

**Comment by peh** [comment]
Dear bot,
There really is no use for a repro. Would still be great if someone could look into this

**Comment by raajnadar** [comment]
There is already a PR waiting to get it merged.
