### ISSUE TITLE
Stretch Menu.Item to full screen width

### ISSUE THREAD

**Issue by AndrewIsBest69** [callstack/react-native-paper#3016]
![Screenshot_20211217-223015_skola_online_v2](https://user-images.githubusercontent.com/47299500/146610315-02b71980-5533-41c4-a9e8-bafa3992c6ac.png)

I want that menu item to be full width for obvious reasons.

**Comment by lukewalczak** [comment]
Hey @AndrewIsBest69 could you please describe your example of using the `Menu` component?

**Comment by AndrewIsBest69** [comment]
@lukewalczak 
`
export default function More() {
  return (
      <View style={{flex: 1}}>
        <Menu.Item
          icon="message-text"
          title="Received messages"
          onPress={() => {}}
        />
        <Menu.Item
          icon="message-reply-text"
          title="Sent messages"
          onPress={() => {}}
        />
      </View>
  );
}
`
It's the same code that's provided as an example in the official documentation

**Comment by lukewalczak** [comment]
Then you can achieve it by adding max width property into style:

```
      <Menu.Item
        icon="message-text"
        title="Received messages"
        onPress={() => {}}
        style={{ maxWidth: '100%' }}
      />
```

**Comment by AndrewIsBest69** [comment]
Thanks, works like a charm
![Screenshot_20211220-064750_skola_online_v2](https://user-images.githubusercontent.com/47299500/146718022-04038624-5d7f-4e3a-9e59-222a5d8f7281.png)
