### ISSUE TITLE
How can i load a single component from RN Paper

### ISSUE THREAD

**Issue by rizshivalli** [callstack/react-native-paper#3018]
`import {Menu} from 'react-native-paper';`

can i import 

`import Menu from 'react-native-paper/lib/module/components';`

**Comment by raajnadar** [comment]
Yes that should work! are you afraid to ship all the unused components to production if yes you can check the docs to setup a babel plugin to remove unused components.

https://callstack.github.io/react-native-paper/getting-started.html#installation
