### ISSUE TITLE
Menu.Item Error

### ISSUE THREAD

**Issue by chukiatt** [callstack/react-native-paper#3023]
Dear sir, 

i got error when use <Menu>   <Menu.Item>

EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.

thank you

**Comment by chukiatt** [comment]
"react-native": "0.66.4",
"react-native-paper": "^4.11.1",
"react-native-vector-icons": "^9.0.0",

Thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by lukewalczak** [comment]
It should be fixed by that PR: https://github.com/callstack/react-native-paper/pull/3017

**Comment by chukiatt** [comment]
It still have error in last version of react native paper

**Comment by lukewalczak** [comment]
true, since it's not merged and released yet. Currently, you can install react-native-paper from that PR's branch or wait till it will be released.
