### ISSUE TITLE
Correct usage of `dark` property in theme

### ISSUE THREAD

**Issue by traviswimer** [callstack/react-native-paper#3025]
I am having trouble understanding the correct way to implement a dark theme based on the [docs](https://callstack.github.io/react-native-paper/theming.html#dark-theme).

The issue is that there seems to be a conflict between using the `dark` property and using a `DarkTheme` object or I simply don't understand how it is meant to work.

My understanding is that the `dark` property is swapping the `surface` and `primary` colors and altering opacity in some components. The confusing part is that if you set `dark: true` in a `DarkTheme` object, you are actually setting it to a light theme.

1. Is the `dark` property only intended to be used as a quick and lazy way to convert a light theme to a dark one?
2. Should `dark: true` ever be used if you are creating a custom light and dark theme?

------

This isn't a bug. It's just a question or possibly a suggestion to improve the documentation. It doesn't really make sense to include a "minimal repro", but I think this issue is getting ignored since it has a `needs repro` label.

So, here's a completely useless expo snack containing absolutely nothing relevant: https://snack.expo.dev/20dQJ05RQ

**Comment by traviswimer** [comment]
Hello bot. Please remove the `stale` label. 😀

**Comment by lukewalczak** [comment]
Hello @traviswimer, I guess the role of `dark` property was a quick way to define whether component's background color is _dark-ish_, so then the color of the text or icon will be switched to the contrasting color, regardless of what the theme is.

Please check the following snack, where I tried to illustrate it: https://snack.expo.dev/qhgwZULoP
