### ISSUE TITLE
Multiline TextInput backgroundColor does not fully cover surface

### ISSUE THREAD

**Issue by Insider32** [callstack/react-native-paper#3031]
### Current behaviour

Multiline TextInput background color does not cover all the surface on iOS.

### Expected behaviour

Multiline TextInput background color **should** cover all the surface on iOS.

### Code sample

Repro at: https://snack.expo.dev/_SWzxWyTh (select iOS)

### Screenshots (if applicable)

![textinput](https://user-images.githubusercontent.com/3471403/148771075-5f392501-ae53-4463-8e4e-40708c1ecfe8.jpg)

### What have you tried

I have identified the issue to be at the following part of `TextInputFlat`(https://github.com/callstack/react-native-paper/blob/main/src/components/TextInput/TextInputFlat.tsx#L334), and more specifically at https://github.com/callstack/react-native-paper/blob/main/src/components/TextInput/TextInputFlat.tsx#L344 the backgroundColor should not be defined only by `containerStyle`'s `backgroundColor` but `viewStyle`'s (style) `backgroundColor` if provided.

```
{!isAndroid && multiline && (
  // Workaround for: https://github.com/callstack/react-native-paper/issues/2799
  // Patch for a multiline TextInput with fixed height, which allow to avoid covering input label with its value.
  <View
    testID="patch-container"
    pointerEvents="none"
    style={[
      StyleSheet.absoluteFill,
      dense ? styles.densePatchContainer : styles.patchContainer,
      {
        backgroundColor: containerStyle.backgroundColor,
        left: paddingLeft,
        right: paddingRight,
      },
    ]}
  />
)}
```

### Your Environment

| software              | version
| --------------------- | -------
| ios        | 15.2
| react-native          | 0.64.3
| react-native-paper    | 4.11.1
| node                  | 16.13.1
| yarn           | 1.22.17
| expo              | 44.0.4

**Comment by lukewalczak** [comment]
Duplicated of: https://github.com/callstack/react-native-paper/issues/3020
