### ISSUE TITLE
How To Change the size of React Native Paper CheckBox 

### ISSUE THREAD

**Issue by Malik-Usman17** [callstack/react-native-paper#3037]
unable to change the size of a checkbox,  can anyone tell me how to tackle this issue.

My Packages Version:
**react-native: 0.66.0**
**react-native-vector-icons: 8.1.0**
**react-native-paper: 4.9.2**

**Comment by lukewalczak** [comment]
Hey @Malik-Usman17, I think you cannot change the size of the checkbox since imposed arbitrary by Material Design guidelines. If you will find the example on there website where the size is different than regular, please let me know ✌🏽

**Comment by lt35** [comment]
I also have the same problem, unable to change the size(height, width) of a checkbox and radio, please update fix it

**Comment by ravis-farooq** [comment]
<View
                  style={{
                    transform: [{scale: 0.75}],
                  }}>
                  <Checkbox.Android
                    borderless
                    color={PRIMARY_COLOR}
                    status={consentChecked ? 'checked' : 'unchecked'}
                    onPress={() => {
                      handleConsentToggle();
                    }}
                  />
                </View>
