### ISSUE TITLE
EventEmitter.removeListener Deprecated

### ISSUE THREAD

**Issue by edugolive** [callstack/react-native-paper#3042]
When use Menu component , I have this warning "EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener".

**Comment by lukewalczak** [comment]
It should be fixed with https://github.com/callstack/react-native-paper/pull/3017. PR is merged, however it's not released yet (the release will be more likely next week), so in the meantime you can try to install the library for the `main` branch.
