### ISSUE TITLE
settings-outline icon is not displaying

### ISSUE THREAD

**Issue by vipulbuoyancy** [callstack/react-native-paper#3043]
**settings-outline** icon is not displaying and it is displaying as question mark (?)

icon should display **settings-outline** icon

`<Button icon="settings-outline">
  Press me
</Button>`

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          |  0.63.4
| react-native-paper    | 4.10.1
| npm or yarn           | yarn

![processed-3596adfb-f2b0-4343-8fed-8d53899212b6_cGwjsFx5](https://user-images.githubusercontent.com/80636669/150356119-7bad8bcb-ace6-44d2-8e09-f4df2c918723.jpeg)

**Comment by lukewalczak** [comment]
Hey @vipulbuoyancy, looks like there is some issue with that icon, I will check it. I noticed that in the meantime you can use `cog-outline` icon.
