### ISSUE TITLE
Disabled textinput opacity not changing???

### ISSUE THREAD

**Issue by zoobibackups** [callstack/react-native-paper#3044]
**I want to change the opacity of disabled textinput to 1.**  

```
import { TextInput } from 'react-native-paper';

 <TextInput
          placeholder="Enter your email"
          mode="outlined"
          label="Enter your email"
          error={!validEmail}
          value={email}
          onChangeText={text => emailChange(text)}
          left={<TextInput.Icon name="email" color={colors.black} />}
          theme={{colors: {primary:colors.appColor,text:"#000000",})}}
      />
```

**Is there anyway to change the opacity when textinput is disabled????**

**I am using the following versions:**
```
"react-native": "0.67.1",
"react-native-paper": "^4.11.2",
"react-native-vector-icons": "^9.0.0",
```

**Link to the repo:**

[Click here to check my code](https://snack.expo.dev/cgqBNl9NB)

**Thanks!**

**Comment by zoobibackups** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native` (found: `0.63.4`, latest: `0.67.1`)
> * `react-native-paper` (found: `4.10.0`, latest: `4.11.2`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes.

**Comment by lukewalczak** [comment]
Hey @zoobibackups, I think it's not possible when specifying `disabled` prop, however if I remember correctly you can try to use `editable={false}` instead.

**Comment by zoobibackups** [comment]
> Hey @zoobibackups, I think it's not possible when passed `disabled` prop, however if I remember correctly you can try to use `editable={false}` instead.

Perfect, we cant change the opacity of `disabled={true}` textinput but we can use `editable={false}`.

Thanks!
