### ISSUE TITLE
Is there any way to manipulate FAB size?

### ISSUE THREAD

**Issue by jarto666** [callstack/react-native-paper#3045]
I cannot understand how to change the size of FAB manually, except for small flag. I need it bigger and most importantly I need a bigger icon in it.

Latest versions:
`"react-native": "0.66.4",   
"react-native-paper": "^4.11.2",    
"react-native-vector-icons": "^9.0.0"`

**Comment by jarto666** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native` (found: `0.66.4`, latest: `0.67.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

yes

**Comment by cgalo** [comment]
@jarto666 Have you tried of adjusting the FAB size by passing a StyleProp?
