### ISSUE TITLE
Is it possible to remove touchable ripple for Android

### ISSUE THREAD

**Issue by descyther** [callstack/react-native-paper#3056]
regarding:
https://callstack.github.io/react-native-paper/bottom-navigation.html#renderTouchable

The Docs say:
```
renderTouchable
Type: (props: TouchableProps) => React.ReactNode
Default value: (props: TouchableProps) => <Touchable {...props} />
Callback which returns a React element to be used as the touchable for the tab item. Renders a **TouchableRipple** on Android and TouchableWithoutFeedback with View on iOS.
```

is it possible to remove the **TouchableRipple** or have an option to disable it?

**Comment by descyther** [comment]
figured out how to edit it in the library packages yay, i can has no ripple :) thank you for this library

**Comment by swizes** [comment]
> figured out how to edit it in the library packages yay, i can has no ripple :) thank you for this library

Can you explain how you did it?

**Comment by descyther** [comment]
> > figured out how to edit it in the library packages yay, i can has no ripple :) thank you for this library
> 
> Can you explain how you did it?


go to 
node_modules/react-native-paper/src/components/BottomNavigation/BottomNavigation.tsx


CTRL + F and search TouchableRipple
 look for this:
 ```
const Touchable = ({
  route: _0,
  style,
  children,
  borderless,
  centered,
  rippleColor,
  ...rest
}: TouchableProps) =>
  TouchableRipple.supported ? (
    <TouchableRipple {...rest}>
      <View style={style}>{children}</View>
    </TouchableRipple>
  ) : (
    <TouchableWithoutFeedback {...rest}>
      <View style={style}>{children}</View>
    </TouchableWithoutFeedback>
  );
```


either delete the ternary and just return TouchableWithoutFeedback or replace the Ripple with WithoutFeedBack
eg.

```
const Touchable = ({
  route: _0,
  style,
  children,
  borderless,
  centered,
  rippleColor,
  ...rest
}: TouchableProps) => <TouchableRipple {...rest}>
      <View style={style}>{children}</View>
    </TouchableRipple>

```
However, everytime you update anything through yarn itll come back, so then youll have to make your own fork and reference it in package.json as 

"react-native-paper": "https://github.com/descyther/react-native-paper",

or just use my fork :)

**Comment by descyther** [comment]
Glad to know about the patcher package! I didn't want to have to keep updating my fork tbh tyvm!
