### ISSUE TITLE
Add TypeScript Definitions

### ISSUE THREAD

**Issue by timwangdev** [callstack/react-native-paper#306]
### Current behaviour

Has built-in flow definitions.
No definitions for TypeScript.
No definitions on https://github.com/DefinitelyTyped/DefinitelyTyped . 

### Expected behaviour

If it's likely for official to maintain a `index.d.ts` definition file in this project? This is recommend to keep the definition sync with code and maybe add test for this.

Or I could create the community-maintained definition at DefinitelyTyped.

### Code sample

N/A

### Screenshots (if applicable)

N/A

### What have you tried

N/A

### Your Environment

N/A

**Comment by thymikee** [comment]
I think we're not opposed to keep the definition file here, especially if someone is willing to make it work :)

**Comment by thomaswinckell** [comment]
For now, I don't have time to do it by myself, but I can help on it if needed. Let me know.

**Comment by doomsower** [comment]
I've decided to give react-native-paper a shot, and ported some definitions from flow already.
Not sure if I'll stick to this module, but I can submit partial PR. Or maybe we can create work-in-progress PR and others complete it.

**Comment by thymikee** [comment]
@doomsower awesome, WIP PR is better than no PR :)

**Comment by Kausta** [comment]
Note for everyone, I already created type definitions for 1.x branch and submitted a PR, so if anyone is working on type definitions for 2.x branch, they can get the 1.x version from me for saving some time 👍 .

**Comment by Esemesek** [comment]
Yeah, I know. They are kinda messy, because everything is written in one file, and there are no tests, but they will definitely help.

**Comment by Awais6** [comment]
Intellisense not working in Jetbrains Idea or Webstrom
