### ISSUE TITLE
Asking about SearchBar component

### ISSUE THREAD

**Issue by rushkii** [callstack/react-native-paper#3060]
Hello, how to center the search bar and how to change the icon position to the right side of the search bar? [Image](https://i.ibb.co/d4vKzpS/image.png)

**Comment by lukewalczak** [comment]
Hello @rushkii, 

> how to center the search bar

Do you want to center the whole `Searchbar` component or text inside?

> how to change the icon position to the right side of the search bar?

Unfortunately, I guess it's not possible.
