### ISSUE TITLE
Android BackHandler not working correctly with Dialog Component

### ISSUE THREAD

**Issue by dlesendric** [callstack/react-native-paper#3061]
### Current behaviour

Android BackHandler seems that not working properly with Dialog component. Back handler close Dialog, but it seems that he blocks next back press actions like navigation back.
Bug reproduced with latest version 4.11.2 and with 4.10.1
On version 4.8.1 everything working fine.

### Expected behaviour

Dialog back handler should work like in version 4.8.1

### Code sample

It think that problem is in Modal.tsx
```  
const handleBack = () => {
    if (dismissable) {
      hideModal();
     return true; // <- add this
    }
    // return true; 
   return false; // <- change this 
  };
```

How to reproduce:
```
export const PortalDialog: FC<Props> = ({ children, visible, onDismiss, style }) => {
  const theme = useTheme();
  /** From version 4.12 react-native-paper we can enable this peace of code */
  // if (!visible) {
  //   return null;
  // }

  return (
    <Portal>
      <Dialog
        visible={visible}
        onDismiss={onDismiss}
        style={[
          styles.dialog,
          {
            backgroundColor: theme.base.theme_paper,
          },
          tw.selfCenter,
          style,
        ]}
      >
        {children}
      </Dialog>
    </Portal>
  );
};

```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 15.2 / 29
| react-native          | 0.66.3
| react-native-paper    | 4.10.1
| node                  | 17.3.1
| npm or yarn           | 8. 3
| expo sdk              |

**Comment by dlesendric** [comment]
I guess this issue will be fixed with the 4.12 version.
The problem is unmounting of Modal.tsx because there are no removeEvent handlers.
Sometimes I don't want to have mounted Portals when Dialog is not visible.

**Comment by lukewalczak** [comment]
Hello @dlesendric,  Did you check is the issue exists on `4.12.0-alpha.0 `?

**Comment by dlesendric** [comment]
@lukewalczak 
Hi,
Just checked 4.12.0-alpha.0 - and it looks like it was solved in that release. 
Tested on Emulator and real device, it's working.

I still have some issues with Dialog.Action.
Need more time to figure out what's going on.
