### ISSUE TITLE
Add size prop to FAB

### ISSUE THREAD

**Issue by Irfanwani** [callstack/react-native-paper#3064]
**Description.**
It is much difficult and an overwork to add custom styles to FAB especially when it comes to size of the FAB which doesn't work as expected.

**Solution**
Solution which i recommend: There should be a prop `size` where we can change the overall size of the fab as the default size is too big for some cases and `small` doesn't work with label.

The `size` prop should change everything inside the FAB including padding, fontSize of label etc.

**Alternatives**
We can achieve a similar thing by building our own component using `TouchableOpacity` etc and setting styles manually.

[Link](https://snack.expo.dev/@irfanwani/fab-issue) to snack

` "react-native": "0.64.3",`
`"react-native-paper": "4.11.1",`
`"react-native-vector-icons": "^9.0.0",`

**Comment by Irfanwani** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native` (found: `0.64.3`, latest: `0.67.2`)
> * `react-native-paper` (found: `4.11.1`, latest: `4.11.2`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Already verified. This issue still exists after updating to latest versions.

**Comment by joaoGabriel55** [comment]
I can take this task
