### ISSUE TITLE
Add an option to prevent lazy on @react-navigation/material-bottom-tabs.

### ISSUE THREAD

**Issue by Cmoen11** [callstack/react-native-paper#3085]
**Is your feature request related to a problem? Please describe.**
I'm currently a bit frustrated having nested routes not being indexed as the route containing the routes not being loaded, by having a lazy prop I'd allow me to load these routes :) 

**Describe the solution you'd like**
As `import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";` has it, allowing to specify if a route should be lazy loaded or not

**Describe alternatives you've considered**
I'm currently NOT using the material-bottom-tabs for this reason.
.

**Comment by gloredo** [comment]
I believe it should be reopened. `@react-navigation/bottom-tabs` already implements the `lazy` option, I believe that porting the implementation to here shouldn't be complex.

**Comment by gloredo** [comment]
Same problem here. This issue must be reopened.

**Comment by lukewalczak** [comment]
Hey @gloredo, PRs with contributions are more than welcome!
