### ISSUE TITLE
If TextInput value is long, it moves to a new line even though multiline={false} on IOS

### ISSUE THREAD

**Issue by erhanersoz** [callstack/react-native-paper#3088]
### Current behaviour

If TextInput value is long, it moves to a new line even though multiline={false} on IOS.

### Expected behaviour

I expect it to work on IOS just as it works on Android.

### Code sample

In the link below, you can see that it works as expected on android and web, but not as it does on IOS.
[https://snack.expo.dev/@erhanersoz/textinput](https://snack.expo.dev/@erhanersoz/textinput)

### Screenshots (if applicable)

Android
<img width="316" alt="Ekran Resmi 2022-02-12 13 05 40" src="https://user-images.githubusercontent.com/15858441/153708535-a18305c1-9a2f-4ba7-be12-6afce89dffea.png">

IOS
<img width="316" alt="Ekran Resmi 2022-02-12 13 06 58" src="https://user-images.githubusercontent.com/15858441/153708539-972e7b03-98ce-47db-8f80-6d2574d6195a.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android       | 15.2 / 29
| react-native          | 0.67.1
| react-native-paper    | ^4.11.2
| node                  | 14.18.2
| npm           | 8.4
| expo sdk              | 43

**Comment by lukewalczak** [comment]
Hello @erhanersoz, please check discussion [thread](https://github.com/callstack/react-native-paper/discussions/3026) where I explain that issue ✌🏽

**Comment by erhanersoz** [comment]
Hello @lukewalczak, thank you. I added `textAlign: "auto"` style to input. It worked.
