### ISSUE TITLE
Change background color of accordion on list expand

### ISSUE THREAD

**Issue by avinashbarfa-buku** [callstack/react-native-paper#3090]
**Is your feature request related to a problem? Please describe.**

<img width="365" alt="image" src="https://user-images.githubusercontent.com/94440620/154089212-ab0aabbc-715c-4f18-a14c-c2fe50180f3d.png">

Need to update the background color of the `Pengaturan accordion` when the list is expanded

URL: https://snack.expo.dev/w3z-nUzLZ

versions: 
react-native: "0.67.1"
react-native-paper: "4.11.2",
react-native-vector-icons: "^9.0.0"

**Comment by lukewalczak** [comment]
Hello @avinashbarfa-buku, please check the following [snack](https://snack.expo.dev/yeg-c9OVP) and let me know if it solving your problem.

**Comment by avinashbarfa-buku** [comment]
Hi @lukewalczak , in my case I am using **List.AccordionGroup**, and not handling **expanded** state, but AccordionGroup takes care of it. 

I'm not sure how can I get to know which Accordion is open in my case.
https://snack.expo.dev/w3z-nUzLZ

**Comment by lukewalczak** [comment]
Basically you have to use a `List.AccordionGroup` as a controlled component as I presented in the previous snack by introducing state for handling `expanded`.
In group component, according to the [documentation](https://callstack.github.io/react-native-paper/list-accordion-group.html) you have two props which can help you to achieve it: `expandedId` and `onAccordionPress`.
example: https://snack.expo.dev/DT6f45kLO

**Comment by avinashbarfa-buku** [comment]
Hi @lukewalczak , thanks for the help. It worked for me.
