### ISSUE TITLE
Text Input Button Label

### ISSUE THREAD

**Issue by Ghoral** [callstack/react-native-paper#3091]
Hello,

How can we change the label style in text input outline mode?

I want to change my label like in the attached image.

![Screen Shot 2022-02-16 at 9 54 14 AM](https://user-images.githubusercontent.com/49188349/154194689-64107fa1-2ac8-4710-b260-41a90a31dcd0.png)

Thank you.

**Comment by Ghoral** [comment]
"react-native": "0.66.3",
"react-native-paper": "^4.11.1",
"react-native-vector-icons": "^9.0.0"

**Comment by Ghoral** [comment]
https://callstack.github.io/react-native-paper/text-input.html

**Comment by Ghoral** [comment]
found the solution

**Comment by arundevkv** [comment]
> found the solution

How?
