### ISSUE TITLE
Unable to use CheckBox Component

### ISSUE THREAD

**Issue by Aman1706** [callstack/react-native-paper#3094]
Whenever I try to use the Checkbox Component I get the following error

 `ERROR  ReferenceError: Property 'e' doesn't exist`

Any idea what can be done?

**Comment by Aman1706** [comment]
- react-native: 0.66.0
- react-native-paper: 4.9.2
- @expo/vector-icons : 12.0.5,

**Comment by lukewalczak** [comment]
Hey @Aman1706 Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue?

**Comment by aishwarya-singh04** [comment]
> Hello 👋, this issue has been open for more than a month without a repro or any activity. If the issue is still present in the latest version, please provide a repro or leave a comment within 7 days to keep it open, otherwise it will be closed automatically. If you found a solution or workaround for the issue, please comment here for others to find. If this issue is critical for you, please consider sending a pull request to fix it.

It's still there, I'm getting the "Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro" error.
