### ISSUE TITLE
Accordion is not opening on adding onAccordionPress prop.

### ISSUE THREAD

**Issue by ronlobo01** [callstack/react-native-paper#3095]
### Current behaviour

Accordion not opening on adding onAccordionPress prop

### Expected behaviour

Accordion should open

### Code sample

https://snack.expo.dev/e-FJh8pWB

### Your Environment

| software              | version
| --------------------- | -------
| react-native          |0.67.1
| react-native-paper    |3.4.0

**Comment by lukewalczak** [comment]
Hello @ronlobo01, please check the full [example](https://snack.expo.dev/dhK_OVogT) how to use controlled accordion group
