### ISSUE TITLE
TextInput inside Portal behaves incorrectly when using CJK keyboard

### ISSUE THREAD

**Issue by suregi** [callstack/react-native-paper#3097]
### Current behaviour

If you type ㅁ ㅏ ㅇ in Korean keyboard, it shows up as ㅁ ㅏ ㅇ

### Expected behaviour

It should show up as 망

### Code sample

```
import React from 'react';
import { View } from 'react-native';
import { Portal, Provider, TextInput } from 'react-native-paper';

const App = () => {
	const [val, setVal] = React.useState('');
	const [val2, setVal2] = React.useState('');

	return (
		<Provider>
			<Portal>
				<TextInput
					placeholder={
						'ㅁ ㅏ ㅇ will show up instead of 망' /* when typing ㅁ ㅏ ㅇ in Korean keyboard, it should show up as 망  */
					}
					value={val}
					onChangeText={setVal}
				/>
			</Portal>

			<View style={{ flex: 1, justifyContent: 'center' }}>
				<TextInput
					placeholder={
						'망 will show up correctly' /* outside of Portal, it correctly shows up as 망  */
					}
					value={val2}
					onChangeText={setVal2}
				/>
			</View>
		</Provider>
	);
};
```

### What have you tried

It also happens in older version 4.7.2.

It is most likely to happen with other keyboards such as Japanese or Chinese.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android 12
| react-native          | 0.64
| react-native-paper    | 4.11.2
| node                  | 14.15.0

**Comment by suregi** [comment]
Repro attached [here](https://snack.expo.dev/@simbust/e1f3d1)

Please test with Android device and use Korean keyboard. I suppose that you can repro with other CJK keyboard such as Japanese and Chinese also, but I haven't tried myself.

**Comment by nappa0326** [comment]
I have the same issue.
