### ISSUE TITLE
Bottom Navigation: Labels are cut off when system font size is set to large

### ISSUE THREAD

**Issue by ptreitler** [callstack/react-native-paper#3099]
### Current behaviour

When I set the system font size to "Large" or "Largest" on Android, the labels of the Bottom Navigation are cut off at the bottom (see screenshots below). I tried increasing the size of the bar (as per https://github.com/callstack/react-native-paper/discussions/2428#discussioncomment-430524), but that didn't help either.

### Expected behaviour

The Bottom Navigation bar should accomodate the larger label.

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/1749537/155363606-deb7f898-2d31-492d-bc30-ed240ecebdcd.png)

-->

![image](https://user-images.githubusercontent.com/1749537/155363449-b512ca2e-2455-483f-8a36-a5b7f0bcabaa.png)

### What have you tried

- increasing the size of the bar (see above)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android 12
| react-native          | 0.66.3
| react-native-paper    | 4.10.1
| node                  | 16.14.0
| npm or yarn           | 7.20.3
| expo sdk              | -

**Comment by lukewalczak** [comment]
Hello @ptreitler, [PR](https://github.com/callstack/react-native-paper/pull/3100) should fix your issue. Would you like to install the library from the PR's commit or branch in order to check if it solves your problem?

**Comment by ptreitler** [comment]
Thanks @lukewalczak, I'll try it out in the next couple of days
