### ISSUE TITLE
Menu component not rendering when writing tests with react-native-testing-library

### ISSUE THREAD

**Issue by RhyG** [callstack/react-native-paper#3101]
Update: was able to solve this issue with a fairly extensive mock, but it is still not ideal:

```javascript
jest.mock('react-native-paper', () => {
  const OriginalMenuItem = jest.requireActual('react-native-paper').Menu.Item;
  const {View, TouchableOpacity} = require('react-native');
  const Menu = ({children, anchor, ...rest}: PropsWithChildren<{anchor: ReactElement}>) => (
    <TouchableOpacity>
      {anchor}
      <View {...rest}>{children}</View>
    </TouchableOpacity>
  );
  Menu.Item = OriginalMenuItem;
  return {
    ...jest.requireActual('react-native-paper'),
    Menu,
  };
});
```

### Current behaviour

Hi, I am currently writing some tests with Jest and RNTL to test a component that uses `<Menu />` and `<Menu.Item />`. The menu component doesn't seem to actually render, even with the `visible` prop being hardcoded to `true`, and Jest is unable to find any test IDs that should be rendered when the menu is open.

### Expected behaviour

The menu should open when rendering the component with react-native-testing-library.

### Code sample

The repo is private so unable to link.

The component looks like this:
```javascript
export const MenuDropdown = ({
  visible,
  onDismiss,
  onContextMenuPress,
}) => {
  const RightContextMenu = () => (
    <TouchableOpacity onPress={onContextMenuPress} testID="anchor-test-id">
      <Icon  />
    </TouchableOpacity>
  );

  return (
    <Menu visible={true} onDismiss={onDismiss} anchor={<RightContextMenu />}>
      <Menu.Item
        testID="menu-item-1-test-id"
        title="Menu Item 1"
      />
      <Menu.Item
         testID="menu-item-2-test-id"
        title="Menu Item 2"
      />
      <Menu.Item
         testID="menu-item-3-test-id"
        title="Menu Item 3"
      />
    </Menu>
  );
};
```

And the test looks like this:
```javascript
it("Should render menu item", () => {
    const component = render(<MenuDropdown {...props} />);

    expect(component.getByTestId('menu-item-1-test-id')).toBeDefined();
});
```

Error in Jest:
`Unable to find an element with testID: menu-item-1-test-id`

### What have you tried

I have tried mocking the `Menu` component, but the way it sets `Menu.Item` as a static property makes mocking difficult. Mocking the root element in the component I want to test is also not ideal.

Happy to be told I am doing it wrong. 😄 

Thanks heaps, love the package and the work you guys do. 🙂

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | both
| react-native          | 0.66.0
| react-native-paper    | 4.10.1
| node                  |  14.8.1
| npm or yarn           | yarn
| expo sdk              |  n/a

**Comment by mcmxcdev** [comment]
Unfortunately, this is still an issue. Please reopen.

**Comment by ztjdavid** [comment]
Is there anyway to resolve this without using Jest Mock manually?

**Comment by harshilparmar** [comment]
This is same for Searchbar component or maybe for other also.

**Comment by maheshwarimrinal** [comment]
Same issue
