### ISSUE TITLE
Menu not opening inside React Navigation Header

### ISSUE THREAD

**Issue by davepaiva** [callstack/react-native-paper#3107]
### Current behaviour

I have added a **more menu** (3 vertical dots) in the header (configured via navigation.setOptions React Navigation 4). After clicking on the 3 dots the menu which is supposed to open isn't opening.
Note the `toggling menu` get logged to the console

### Expected behaviour

The Menu is supposed to be rendered after triggering by pressing the 3 dots

### Code sample

**Screen.js**
```
handleOpenMenu = () => {
        console.log('toggling menu')
        this.setState({
            showMenu: true
        })
    }

    handleCloseMenu = () => {
        console.log('closing menu')
        this.setState({
            showMenu: false
        })
    }
    
initNavigationOptions() {
        const { navigation } = this.props;
        navigation.setOptions(
            renderHeader(
                this.state.vehicleNumber,
                'NavHeaderTitleStyle',
                'NavHeaderStyle',
                <Menu
                visible={this.state.showMenu}
                onDismiss={()=>this.handleCloseMenu()}
                anchor={
                <TouchableOpacity onPress={this.handleOpenMenu} style={{marginRight: 50}}>
                    <Icon name='more-vertical' size={25} color={'#FFFFFF'} />
                    </TouchableOpacity>
                }
                >
                    <Menu.Item onPress={() => {}} title="Item 1" />
                    {console.log('menu is rendered')}
                    <Menu.Item onPress={() => {}} title="Item 2" />
                    <Divider />
                    <Menu.Item onPress={() => {}} title="Item 3" />
                </Menu>,
                true,
            ),
        );
        
    componentDidMount() {
        this.initNavigationOptions();
    }
    
```

**renderHeader function**
```
export const renderHeader = (
    title,
    headerTitleStyle,
    headerStyle,
    headerRight,
    showBackButton,

) => {
    return {
        title: title,
        headerTitleAlign: 'center',
        headerTitleStyle: (headerTitleStyle === 'NavHeaderTitleStyle') ? globalStyles[headerTitleStyle] : headerTitleStyle,
        headerStyle: globalStyles[headerStyle],
        headerRight: () => {
            if (headerRight === 'default') {
                return null;
            } else if(headerRight) {
                return headerRight;
            }
        },
        headerLeft: () => {
            if (showBackButton) {
                return <HeaderBackBtn headerStyle={headerStyle} />;
            }
        },
    };
};
```

### What I've tried

The same code works if I place the menu code snippet somewhere else on the screen.

       

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          |  0.61.5
| react-native-paper    |  4.11.2
| node                  |  13.7.0
| npm or yarn           |  npm 7.22.0
| expo sdk              | not using expo

**Comment by m7amad-7asan** [comment]
@davepaiva Did you find the solution?
it's not opened even outside the navigation header

**Comment by syahirdev** [comment]
Still had the same problem. Create the menu inside useEffect using navigation.setOptions headerRight, and menu won't popups unless hardcoded visible={true}. But when set up on Stack.Screen, it's working fine.

**Comment by raajnadar** [comment]
@syahirdev you need to pass the dependency value for the useEffect to re-render, that is why it works for you when outside the useEffect

**Comment by da45** [comment]
> ou need to pass the dependency value for the useEffect to re-render, that is why it works for you when outside the useEffect

it solves the issue,

**Comment by lekbit** [comment]
useEffect(() => {
        navigation.setOptions({
            title: 'Title name',
            headerRight: () => (
                <Menu
                    visible={visible}
                    onDismiss={closeMenu}
                    anchor={<TouchableOpacity onPress={openMenu}>
                        <Text>Press me</Text>
                    </TouchableOpacity>}>
                    <Menu.Item onPress={() => {
                        closeMenu();
                        // handleDeleteAll()
                    }} title="Option 1" />
                </Menu>
            )
        });
    }, [visible]);
