### ISSUE TITLE
ListItem release

### ISSUE THREAD

**Issue by PatriceVignola** [callstack/react-native-paper#311]
It's a question, not an issue.

First of all, I want to say that your library is awesome. Pretty easy to use and design an app with it :) I really like how smooth everything is. But one of the reasons I chose this library is because I needed the really nice ListItem components for my project. I didn't realize that it was a new feature and that it wasn't released yet. It's not a blocker as I'll probably just install the dependency via the github repo, but do you have a release date in mind for the next version? I'd also be down to help and contribute to this awesome library.

Thanks!

**Comment by satya164** [comment]
Just did a release 🎉
