### ISSUE TITLE
We can't control the border width of outline

### ISSUE THREAD

**Issue by hipages-ligang** [callstack/react-native-paper#3127]
**Is your feature request related to a problem? Please describe.**
The default outline border width is 1, active outline border width is 2. These are hardcoded, we can't set them to other value.

**Describe the solution you'd like**
Export two properties that can set default border width and active outline border width.

**Additional context**
This is mentioned in https://github.com/callstack/react-native-paper/issues/1650

![image](https://user-images.githubusercontent.com/86226264/159428178-94311f92-fd22-4971-aaa6-89a1a8eabd78.png)
![image](https://user-images.githubusercontent.com/86226264/159428216-e5926e8a-e6c4-4fa6-8387-564bd5e07eb7.png)

**Comment by imSmaity** [comment]
It's workd with outlineStyle={{ borderWidth: 1 }}
