### ISSUE TITLE
Incorrect textinput label position in arabic locale

### ISSUE THREAD

**Issue by nevskij2022** [callstack/react-native-paper#3132]
### Current behaviour
We use the latest versions of libraries.
When the localization is changed to Arabic, an indent appears for the TextInput label.
![image](https://user-images.githubusercontent.com/102587316/160619691-c04cd247-3078-4631-8250-b32d5eb540e9.png)

### Expected behaviour

Should be the same behavior as with in English localization

![image](https://user-images.githubusercontent.com/102587316/160619622-304458d5-d433-4202-9312-a31506112f41.png)
### Code sample 
[Code sample](https://snack.expo.dev/@nevskij2022/label-react-native-paper)
### Screenshots (if applicable)
![Анимация4](https://user-images.githubusercontent.com/102587316/160816006-dbd0b44a-b475-4b54-a2f6-8b99add2da54.gif)

### What have you tried
These changes in the 'TechInputFlat.tsx' component solve the problem
![image](https://user-images.githubusercontent.com/102587316/160603268-41b895b9-a19a-4a95-9cf9-65eb6e00cbdf.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.67.4
| react-native-paper    | 4.11.2
| node                  | 16.14.0
| npm or yarn           | npm 8.5.5
| expo sdk              |

**Comment by lukewalczak** [comment]
Hey @nevskij2022, please check if the issue exists on the latest version.
