### ISSUE TITLE
I18nManager becomes mock-only in react-native-web 0.18 - affect on react-native-paper?

### ISSUE THREAD

**Issue by mikehardy** [callstack/react-native-paper#3133]
I saw this in the react-native-web 0.18 pre-release https://github.com/necolas/react-native-web/pull/2248

> I18nManager is now a mock API included only for compatibility with React Native. The ability to swap between left/right values for RTL writing directions has been removed entirely. See below for new localization APIs.

...and I recall that in a PR I just did I was following some internal convention for handling RTL layouts here in react-native-paper: https://github.com/callstack/react-native-paper/pull/3015/files#diff-abbb75c84e06f0e76a8627a199ea73e45aee12d708f8f839d55603b2151466d9R136-R139

The combination of the two seems worrisome, it appears that *if* I am understanding the RNW 0.18 release notes correctly and "mock API" means we will get a static answer for I18nManager calls on web platform, then RTL will suffer a regression on web platform here until the new RNW APIs are handled?

If this is a problem, easiest forward-port might be to polyfill it back to old behavior on web platform, losing whatever enhancement drove the change but preserving current behavior. Complicated forward-port would involve understanding the enhancement and adapting behavior here accordingly

**Comment by mikehardy** [comment]
@lukewalczak I understand this is not actionable but I thought (as a fellow maintainer of complicated repos...) that this one might be important enough to at least take a look at. react-native-paper uses I18nmanager a lot...

**Comment by lukewalczak** [comment]
Hey @mikehardy, currently my focus is mainly on Material You and distributing the alpha version. I will reopen that issue and dive into it once have some time.

**Comment by mikehardy** [comment]
Totally understand (and seriously: thanks so much for the effort) I just wanted to make sure this wasn't a complete surprise for you  later :-)

**Comment by mikehardy** [comment]
Just cross-pollinating, I thought this was an interesting PR from another native+web repo: https://github.com/react-navigation/react-navigation/pull/10547/files - basically they just converted `I18NManager.isRTL` to `I18NManager.getConstants().isRTL` ?

**Comment by lukewalczak** [comment]
> Just cross-pollinating, I thought this was an interesting PR from another native+web repo: [react-navigation/react-navigation#10547 (files)](https://github.com/react-navigation/react-navigation/pull/10547/files) - basically they just converted I18NManager.isRTL to I18NManager.getConstants().isRTL ?

Hey @mikehardy, thanks for pointing it out. I will adjust it in the Paper codebase as well.

**Comment by lukewalczak** [comment]
PR adjust `I18nManager.getConstants`: https://github.com/callstack/react-native-paper/pull/3352
