### ISSUE TITLE
Stacked label for TextInputs

### ISSUE THREAD

**Issue by SamuelLeclerc33** [callstack/react-native-paper#3136]
**Is your feature request related to a problem? Please describe.**

I used a TextInput in a DatePicker component I wrote. Usually, when I use a component library like Paper I have the possibility to set stacked label and be albe to see the place holder and the label at the same time. Like here : 
![image](https://user-images.githubusercontent.com/23220701/161285582-e56e087e-eea2-453a-9cb1-7e573cab3a49.png)

**Describe the solution you'd like**
I'd like to have an exposed property to set the label to be stacked.

**Describe alternatives you've considered**
Right now the only thing i can think of is to set the value of the input to my "placeholder" value and via style change the color.

**Additional context**
This idea comes from this library : https://quasar.dev/vue-components/input#example--outlined

I guess the goal would be something like this : 
![image](https://user-images.githubusercontent.com/23220701/161287348-128f6a56-c921-4b50-b445-7b0dd1bcb81e.png)

**Comment by lukewalczak** [comment]
Hey @SamuelLeclerc33 could you please point me to the MD documentation/example presenting that behavior is allowed/supported?
