### ISSUE TITLE
JSON.stringify cannot serialize cyclic structures TextInput

### ISSUE THREAD

**Issue by rahmanharoon** [callstack/react-native-paper#3139]
### Current behaviour
Getting `JSON.stringify cannot serialize cyclic structures` this error when setting state of onChangeText 

App getting crash on setState action called.
### Expected behaviour
Need to change state of value of what am typing

### Code sample
```
<TextInput
....(other props)
value={value}
label="Dish Name"
onChangeText={(text: string) => {
	setProductName(text);
}}
```

### Screenshots (if applicable)

![simulator_screenshot_0693C3D4-0EB6-4F3E-AB94-558152CBF0FE](https://user-images.githubusercontent.com/67966429/161425467-0efcb38a-e9b7-455b-9bbc-fef1308c1529.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | both ios and android
| react-native          | 0.64.3
| react-native-paper    | 4.8.1
| node                  | v16.0.0
| npm or yarn           | 8.5.5
| expo sdk              | 5.2.0

**Comment by nouridev12** [comment]
@rahmanharoon if the JSON.stringify function THAT TRIGGER the issue is inside your project(not from the node_modules) then you can use [this solution](https://stackoverflow.com/a/9382383/13378146). Add a function "Replacer" as the second argument to the "JSON.stringify" function.
