### ISSUE TITLE
How to start editing on TextInput programmatically and show keyboard

### ISSUE THREAD

**Issue by goxr3plus** [callstack/react-native-paper#3140]
Hello my question is .

Is there any way to programmatically focus and show keyboard for typing on TextInput ?

I have created a ref to TextInput as follows :

```
<TextInput
				ref={inputRef}
				style={styles.textInput}
				label='Update reason here..'
				value={reason}
				onChangeText={text => setReason(text)}
			/>
```

and tried something like this :

```
	const inputRef = useRef()
	
	useEffect(()=>{
		console.log(inputRef.current)
		inputRef.current.focus()
	},[])
```

But it just focuses the TextInput i need it also to show the keyboard like below instead of the user having to manyally tap on the TextInput in order for it to show the keyboard :

![image](https://user-images.githubusercontent.com/20374208/161439362-2e765713-2553-471f-8136-4e00ec437c26.png)

Let me know if this is possible

**Comment by goxr3plus** [comment]
I am using react-native-paper 4.12.0

**Comment by lucaswitch** [comment]
The current version 4.12.0 has different ref pros than the older releases with a lot less attributes.

**Comment by lucaswitch** [comment]
@goxr3plus the easy fix should be replacing your current paper version 4.12.0 to 4.11.x.

**Comment by goxr3plus** [comment]
@lucaswitch  I will give it a try , though it seems strange i have to go to previous version . I mean ... i will miss the new bug fixes.
