### ISSUE TITLE
Focusing on TextInput programmatically doesn't start also editing with keyboard

### ISSUE THREAD

**Issue by goxr3plus** [callstack/react-native-paper#3141]
Hello 

I have created a ref to TextInput as follows :

```
<TextInput
			ref={inputRef}
			style={styles.textInput}
			label='Update reason here..'
			value={reason}
			onChangeText={text => setReason(text)}
/>
```

and tried something like this :

```
const inputRef = useRef()
	
useEffect(()=>{
	console.log(inputRef.current)
	inputRef.current.focus()
},[])
```

> But it just focuses the TextInput

![studio64_K8OyuPrbOL](https://user-images.githubusercontent.com/20374208/161439700-c0f82e60-b624-45f3-af19-ef218681581a.gif)

>  I need it also to show the keyboard like below instead of the user having to manuallytap on the TextInput in order for it to show the keyboard :

![image](https://user-images.githubusercontent.com/20374208/161439362-2e765713-2553-471f-8136-4e00ec437c26.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 11
| react-native          |  0.64
| react-native-paper    |  4.12.0
| node                  |   16
| npm or yarn           | 6.12
| expo sdk              | 44

 44

**Comment by lukewalczak** [comment]
Hello @goxr3plus, please try to use `inputRef.current.forceFocus()`

**Comment by drplauska** [comment]
@lukewalczak did you manage to repro it? I put `ref` on example `TextInput` and `focus` method works just fine, opens keyboard on both android and ios.

**Comment by goxr3plus** [comment]
.

**Comment by goxr3plus** [comment]
@lukewalczak  Still not working with forceFocus ... let me show you on the gif below

**Comment by lucaswitch** [comment]
In the current update the ref methods/props are passed to parent components through react native imperative handle as described here #3146

**Comment by sbueno-bemobile** [comment]
Same issue with android studio,

`import React from 'react';
import {TextInput} from 'react-native-paper';
import {StyleSheet} from 'react-native';

const AppTextInput = () => {
  const [text, setText] = React.useState('asdf');

  return (
    <TextInput
      label="Email"
      value={text}
      onChangeText={text => setText(text)}
      style={s.input}
    />
  );
};

const s = StyleSheet.create({
  input: {
    width: '100%',
  },
});

export default AppTextInput;
`

When I click on textinput no open keyboard
