### ISSUE TITLE
Label text is not wrapping when text is long - Button.

### ISSUE THREAD

**Issue by Ghoral** [callstack/react-native-paper#3143]
When the text is long button is not wrapping the label instead it ellipses the label. It should expand the button and all the text should be visible.

![Screenshot_20220404-162712_Elephant Insurance, LLC](https://user-images.githubusercontent.com/49188349/161528479-1af7e7ef-bd50-4439-986c-6f6a46ffb00f.jpg)

**Comment by Ghoral** [comment]
"react-native": "0.66.3",
"react-native-paper": "^4.11.1",
"react-native-vector-icons": "^9.0.0",

**Comment by lukewalczak** [comment]
According to the MD guidelines wrapping text in button is not allowed: 

<img width="600" alt="image" src="https://user-images.githubusercontent.com/22746080/161792277-2a21cb89-5dbb-4ea7-bfcc-1331abbbc96d.png">
