### ISSUE TITLE
Breaking changes on TextInput ref between 4.12 and 4.11.x

### ISSUE THREAD

**Issue by lucaswitch** [callstack/react-native-paper#3146]
### Current behaviour 4.12

When setting a ref inside a <TextInput/> element exposes in ref the following:
      focus: ()
      clear: ()
      setNativeProps: (args: Object) 
      isFocused: ()
      blur: ()
      forceFocus: ()

### Expected behaviour 4.11

In older versions than **4.11.x it was possible to access <TextInput/> private component methods like, setFocused() and others**, allowing devs to change the behavior of TextInput more than the exposed in 4.12.0.

**Comment by seahorsepip** [comment]
Here's a gist I've been using to share an internal ref while also using it internally: https://gist.github.com/pie6k/b4717f392d773a71f67e110b42927fea

**Comment by lukewalczak** [comment]
Hey @lucaswitch could you please present on the snack (since it's the easiest way to present the problem using different library versions) the difference in `TextInput` between the latest version and the previous one?

**Comment by lucaswitch** [comment]
Ok, i will do.

**Comment by lucaswitch** [comment]
Hello, any news?

**Comment by goxr3plus** [comment]
It's causing this problem https://github.com/callstack/react-native-paper/issues/3141#issuecomment-1147695589
