### ISSUE TITLE
Dropdown option position is off when inside modal

### ISSUE THREAD

**Issue by anchetaWern** [callstack/react-native-paper#3157]
### Current behaviour
This happens when I use the react native paper dropdown component (https://fateh999.github.io/react-native-paper-dropdown/#/README) inside react native paper's modal component.

This is when clicking the first modal, as you can see the options aren't where they're supposed to be: 
<img width="318" alt="Screen Shot 2022-04-21 at 7 36 59 PM" src="https://user-images.githubusercontent.com/743603/164450072-6ab2f324-5672-4b7f-a6a0-e78f11855cd7.png">

### Expected behaviour

while this is the second (dropdown is covered due to it being clicked). This is the expected behavior: 

<img width="324" alt="Screen Shot 2022-04-21 at 7 37 19 PM" src="https://user-images.githubusercontent.com/743603/164450065-a53349f3-a8e4-40e6-93cc-eca8441983b2.png">

the problem is that even if there's only one dropdown (eg. when leaving only the 2nd dropdown inside the modal), the issue is still the same. So I guess the first instance always gets the issue no matter what.

Note that when not inside the modal. This component works (the option is where they're supposed to be when the dropdown is clicked).

### Code sample

```
<Provider>
	<Portal>
		<Modal
			visible={createCategoryModalVisible}
			onDismiss={() => {
				hideModal();
			}}
			contentContainerStyle={styles.modalView}
		>
			<React.Fragment>
				<FieldContainer>
					<FieldLabel text="Source Fund" />
					<FundsDropdown
						fund={sourceFundId}
						setFund={setSourceFundId}
						showFundsDropdown={showSourceFundDropdown}
						setShowFundsDropdown={setShowSourceFundDropdown}
					/>
				</FieldContainer>

				<FieldContainer>
					<FieldLabel text="Destination Fund" />
					<FundsDropdown
						fund={destinationFundId}
						setFund={setDestinationFundId}
						showFundsDropdown={showDestinationFundDropdown}
						setShowFundsDropdown={setShowDestinationFundDropdown}
					/>
				</FieldContainer>
			</React.Fragment>

		</Modal>
	</Portal>
</Provider>
```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 
| react-native          | 0.67.4
| react-native-paper    | 4.11.2
| node                  | 14.18.0
| npm or yarn           | 6.14.15
| expo sdk              | N/A

**Comment by MathisBarre** [comment]
I met the same issue as you.
