### ISSUE TITLE
Modal component not working with react-native: 0.68.1

### ISSUE THREAD

**Issue by sagark1510** [callstack/react-native-paper#3161]
### Current behaviour

When I tap on the show modal button it is not showing the modal if I use `<Portal />` and if I don't then react navigation header is not getting hidden by Modal.

### Expected behaviour

It should show the modal covering the whole screen.

### Code sample

```
import React, {useContext} from 'react';
import {Alert, Linking, View} from 'react-native';
import {
  Colors,
  Modal,
  Portal,
  Provider,
  Title,
  useTheme,
} from 'react-native-paper';
import {Button, Text} from '../../components';
import {PreferencesContext} from '../../context/PreferencesContext';
import {styles} from './styles';

const HomeScreen = () => {
  const [visible, setVisible] = React.useState(false);

  const showModal = () => setVisible(true);
  const hideModal = () => setVisible(false);
  const containerStyle = {backgroundColor: 'white', padding: 20};
  const {toggleTheme, isThemeDark} = useContext(PreferencesContext);

  const onClick = () => {
    Alert.alert('Comming Soon');
  };

  const iconClick = (param: string) => {
    if (param === 'link') {
      Linking.openURL('https://www.google.co.in/');
    } else {
      Alert.alert(param);
    }
  };

  const {colors} = useTheme();
  return (
    <View style={styles.container}>
      <Title>Current Theme: {isThemeDark ? 'Dark' : 'Light'}</Title>

      <Button
        onPress={() => toggleTheme()}
        color={isThemeDark ? Colors.white : Colors.black}
        style={{backgroundColor: colors.primary}}
        mode={'text'}>
        Theme Button
      </Button>

        <Portal>
          <Modal
            visible={visible}
            onDismiss={hideModal}
            contentContainerStyle={containerStyle}>
            <Text>Example Modal. Click outside this area to dismiss.</Text>
          </Modal>
        </Portal>
        <Button style={{marginTop: 30}} onPress={showModal}>
          Show
        </Button>

    </View>
  );
};

export default HomeScreen;
```
### What have you tried
I tried wrapping the <Portal /> with `<Portal.Host />` and with `<Provider />` even though the whole app is wrapped with Provider in App.tsx.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | both
| react-native          | 0.68.1
| react-native-paper    | ^4.12.0
| node                  | 14.x
| npm or yarn           | yarn-1.22.18
| expo sdk              | -
| react-native-vector-icons | ^9.1.0

**Comment by sagark1510** [comment]
@satya164  ^^

**Comment by Artistixevikas** [comment]
Thanks, For Amazing blog and sharing more useful information. discoverer one of the <a href="https://artistixeit.com/">Software App Development Company</a> in India

**Comment by varem611** [comment]
I had the same problem, the issues occurs only on IOS when you use createNativeStackNavigator(). If change to createStackNavigator() it will work fine.

It's a really weird bug, the react native paper modal/dialog work fine with createStackNavigator(), but doesn't work with createNativeStackNavigator() on ios - android and browser are fine.
