### ISSUE TITLE
TextInput ignores value change when space is pressed, hence cannot remove all spaces from TextInput

### ISSUE THREAD

**Issue by rchaubey** [callstack/react-native-paper#3162]
### Current behaviour

I'm trying to remove all spaces from <TextInput />  on `onChangeText`.  But it ignores the `value` prop change when `space` is pressed on the virtual keyboard.

Tried it with react native's `TextInput` it works as expected

### Expected behaviour

It should not ignore value change when the space is pressed and should update the `value` prop

### Code sample

```
import React, { useState } from "react";
import { StyleSheet, View, TextInput as TextInputRN } from "react-native";
import { TextInput as TextInputPaper, Provider } from "react-native-paper";

export default function App() {
  const [some1, setSome1] = useState("");
  const [some2, setSome2] = useState("");

  const handleChange = (text) => {
    console.log(text, text.length);
    setSome1(text.replace(/\s/g, ""));
  };

  const handleChange2 = (text) => {
    console.log(text, text.length);
    setSome2(text.replace(/\s/g, ""));
  };

  return (
    <Provider>
      <View style={styles.container}>
        <TextInputPaper value={some1} onChangeText={handleChange} />
        <TextInputRN
          value={some2}
          onChangeText={handleChange2}
          style={styles.rnInput}
        />
      </View>
    </Provider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#fff",
    justifyContent: "center",
  },
  rnInput: {
    borderWidth: 1,
    borderColor: "#000",
    marginVertical: 20,
    padding: 10,
  },
});
```
[Github Repo](https://github.com/rchaubey/rnp-text-input-repo)

[Expo Snack](https://snack.expo.dev/@rchaubey/github.com-rchaubey-rnp-text-input-repo)

### What have you tried

Tried `onChange` prop, but same issue.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.64.3
| react-native-paper    | 4.12.0
| node                  | 16
| npm or yarn           | npm
| expo sdk              | 44.0.2
| expo              | 44.0.2
| npm              | 8.1.2

[Github Repo](https://github.com/rchaubey/rnp-text-input-repo)

[Expo Snack](https://snack.expo.dev/@rchaubey/github.com-rchaubey-rnp-text-input-repo)

**Comment by lukewalczak** [comment]
Hey @rchaubey, could you please check if that [PR](https://github.com/callstack/react-native-paper/pull/3145) fix your issue?

**Comment by rchaubey** [comment]
@lukewalczak Just tested the branch, it works great. Closing this issue & will track that PR.

Thanks!
