### ISSUE TITLE
My screen reader reads the content that is outside of the dialog component and I'm not sure if the dialog component doesn't support accessibility or I'm doing something wrong. 

### ISSUE THREAD

**Issue by BozhidarKabzamalovMM** [callstack/react-native-paper#3166]
I've been following the documentation in order to create a dialog and make it accessible to a screen reader. I've done this so far

Wrap the root with a provider:

import { Provider as PaperProvider } from 'react-native-paper';

```
const Root: FunctionComponent = () => {
    return (
        <PaperProvider>
            <App />
        </PaperProvider>
    );
};
```

Then add the example code:

```
import * as React from 'react';
import { View } from 'react-native';
import { Button, Paragraph, Dialog, Portal, Provider } from 'react-native-paper';

const MyComponent = () => {
  const [visible, setVisible] = React.useState(false);

  const showDialog = () => setVisible(true);

  const hideDialog = () => setVisible(false);

  return (
    <Provider>
      <View>
        <Button onPress={showDialog}>Show Dialog</Button>
        <Portal>
          <Dialog visible={visible} onDismiss={hideDialog}>
            <Dialog.Title>Alert</Dialog.Title>
            <Dialog.Content>
              <Paragraph>This is simple dialog</Paragraph>
            </Dialog.Content>
            <Dialog.Actions>
              <Button onPress={hideDialog}>Done</Button>
            </Dialog.Actions>
          </Dialog>
        </Portal>
      </View>
    </Provider>
  );
};

export default MyComponent;
```

Unfortunately, when I open the dialog while using TalkBack, 2 issues happen:

1. The dialog can't be dismissed by clicking anywhere outside the dialog. This only happens while in screen reader mode. Closing it through the button still works
2. After the dialog has been opened, the screen reader reads out the dialog content, however, it still has the button as the selected element, and when I start swiping, the screen reading begins reading out content that is hidden behind the dialog.

The code works exactly as intended while not in screen reader mode, but starts causing issues once I enter screen reader mode. This is why I'm wondering if I'm doing something wrong or react-native-paper dialog just doesn't support accessibility that well yet?

**Comment by drplauska** [comment]
@BozhidarKabzamalovMM it's working fine on both Android (10 QKQ1.190910.002) and iOS. Used your code in example app. Android video attached. Are you sure you're using the latest release?

https://user-images.githubusercontent.com/10409285/169628923-39fe8e4c-0aff-4048-9f27-49ce2d078802.mp4
