### ISSUE TITLE
[Question]: Is there any support for "standard" material UI input in React Native Paper?

### ISSUE THREAD

**Issue by johnny-mcfadden-dailypay** [callstack/react-native-paper#3172]
Hey! 

I'd like to use the latest version of react native paper (text input), however I noticed there is only support for:

```
mode
Type: 'flat' | 'outlined'
```

Is there any support for the React Native Paper V1 style input / Material UI "standard" input?

What I was hoping to get 🤞 🙏 on V1 (https://callstack.github.io/react-native-paper/1.0/text-input.html)

<img width="569" alt="Screenshot 2022-05-10 at 15 35 26" src="https://user-images.githubusercontent.com/93137292/167654378-44a84940-60c5-4326-883f-92e055ad56d2.png">

Similarly seen on material UI "standard" input (https://mui.com/material-ui/react-text-field/):

<img width="696" alt="Screenshot 2022-05-10 at 15 36 16" src="https://user-images.githubusercontent.com/93137292/167654527-dceb0586-b614-4cab-899d-5042f46cde5b.png">

This is the React Native form I have ATM:

<img width="375" alt="Screenshot 2022-05-10 at 15 37 20" src="https://user-images.githubusercontent.com/93137292/167654771-fe47aa43-f18c-41ae-91c9-3760f26b00ed.png">

The library we are currently using: `import { TextField } from 'rn-material-ui-textfield';` is a fork (seemingly unmaintained) from another unmaintained library with input underline issues on android/ios 😢  Which is why I'm moving over to React Paper! 🔥 

This is what the form looks like with the existing unmaintained lib when it "works" (and what I'm hoping to achieve with the latest version React Native Paper):

<img width="366" alt="Screenshot 2022-05-10 at 15 42 31" src="https://user-images.githubusercontent.com/93137292/167655829-d10ea81f-146b-45dd-8558-cdc2d22c86f9.png">

**The Question Really:** 

Do I need to use an older version of Paper? Or is there a way to achieve this with the latest version via styles / props? I _think_ i tried everything style wise, but maybe not! 🤞 

Versions:

`react-native: 0.64.3`
`react-native-paper: ^4.12.1`
`react-native-vector-icons: 0.0.0`

(not using vector icons)

Appreciate any help!

**Comment by johnny-mcfadden-dailypay** [comment]
Verified the issue still exists on latest versions of npm. This is more of a library question that a bug / breaking change :)

**Comment by lukewalczak** [comment]
Hey @johnny-mcfadden-dailypay, answering your question there is no support for the v1 style input. 
The current design is following the v2 MD [documentation](https://material.io/components/text-fields#filled-text-field). 
In the nearest future we'll introduce Material You (v3) and input will look very similar:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/22746080/167666891-8f018cca-acbe-4c5a-aeb1-d707ae9bbe69.png">

**Comment by johnny-mcfadden-dailypay** [comment]
Thanks @lukewalczak for the speedy response!

**Comment by TNAJanssen** [comment]
@johnny-mcfadden-dailypay did you ever get the visuals like the older "standard" version?
