### ISSUE TITLE
'Using on the Web' documentation does not work and/or is not clear

### ISSUE THREAD

**Issue by supagu** [callstack/react-native-paper#3173]
### Current behaviour

https://callstack.github.io/react-native-paper/using-on-the-web.html
The above documentation says to follow this guide first: https://callstack.github.io/react-native-paper/getting-started.html
If you do this you setup a react-native project.

Then it goes on to talk about 'Using CRA (Create react app)' which is contrary to the first instruction.

Then it talks about 'Custom webpack setup', but doesn't make clear how the previous step 'Using CRA' is related? Is this Custom webpack setup the next step OR is it an alternative to 'Using CRA' ?

So I have ended up with some weird hybrid totally unsure if the setup is correct. I am getting the following errors:

> Failed to compile.
> 
> Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable.js' in '/Users/fabian/Projects/react-cross-test/reactjs-react-native-paper/node_modules/react-native-vector-icons/lib'
> ERROR in ./node_modules/react-native-vector-icons/lib/create-icon-source-cache.js 1:0-45
> Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable.js' in '/Users/fabian/Projects/react-cross-test/reactjs-react-native-paper/node_modules/react-native-vector-icons/lib'
> 
> ERROR in ./node_modules/react-native-vector-icons/lib/icon-button.js 110:24-28
> export 'pick' (imported as 'pick') was not found in './object-utils' (module has no exports)
> 
> ERROR in ./node_modules/react-native-vector-icons/lib/icon-button.js 111:29-33
> export 'pick' (imported as 'pick') was not found in './object-utils' (module has no exports)
> 
> ERROR in ./node_modules/react-native-vector-icons/lib/icon-button.js 112:20-24
> export 'omit' (imported as 'omit') was not found in './object-utils' (module has no exports)
> 
> ERROR in ./node_modules/react-native-vector-icons/lib/icon-button.js 114:25-29
> export 'pick' (imported as 'pick') was not found in './object-utils' (module has no exports)
> 
> ERROR in ./node_modules/react-native-vector-icons/lib/icon-button.js 115:25-29
> export 'pick' (imported as 'pick') was not found in './object-utils' (module has no exports)
> 
> ERROR in ./node_modules/react-native-vector-icons/lib/object-utils.js 1:0-45
> Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable.js' in '/Users/fabian/Projects/react-cross-test/reactjs-react-native-paper/node_modules/react-native-vector-icons/lib'
> 
> webpack compiled with 7 errors

### Code sample

My code is available here: https://github.com/bit-shift-io/react-cross-test/tree/main/reactjs-react-native-paper

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    | ^4.12.1
| node                  | v17.7.1
| npm or yarn           | yarn 1.22.18
| expo sdk              |

**Comment by MartijnGevaert** [comment]
I think most of the instructions assume that you already have a react-native project set up.
That project is most likely going to be through CRA or your own custom webpack.
The tutorials then explain which steps to take depending on your setup. (I think)

Although I do think the title for https://callstack.github.io/react-native-paper/using-on-the-web.html#custom-webpack-setup is a bit confussing, it's a small title, and it gives the impression that this is the next step when working with CRA, but I don't think that's actually the case.

Maybe `when using CRA` and `when using custom webpack` would be better titles?

**Comment by jdinard** [comment]
I'm having the exact same issue.

The docs say:
You can also run the example app as a web app using [react-native-web](https://github.com/necolas/react-native-web),

Clone the repository and run yarn in the root
Run yarn example web to start the webpack server and open the app in your browser

That doesn't work. If you clone the app, and run yarn in the root, nothing happens. Zero errors or feedback.

**Comment by KishoreBarik** [comment]
Hi @supagu 
I am facing the same problem, were you able to solve it. I was trying to add it to a clean CRA app. No React Native project. I want to use this CRA app as a demo app.

**Comment by supagu** [comment]
Sorry I haven't got it working.

**Comment by sdustin** [comment]
I got it working. You need to modify _config-overrides.js_
Change the babel/preset-env preset to include the [corejs](https://babeljs.io/docs/en/babel-preset-env#corejs) version option.
```
        presets: [
          ["@babel/preset-env", { useBuiltIns: "usage", "corejs": "3" }],
```
Then you need to add core-js@3 as an explicit dependency, which is [explained here](https://github.com/zloirock/core-js/issues/500#issuecomment-720106620).

So in other words:
`npm add core-js`

You may need to remove it first before adding it again
`npm remove core-js`
