### ISSUE TITLE
Radio button doesn't display on iOS

### ISSUE THREAD

**Issue by imknight** [callstack/react-native-paper#3174]
### Current behaviour

When you display a radio button group on iOS, the circle is missing, only the check mark is show when you click on it

### Expected behaviour

it should display the circle like the web version

### Code sample

[the sample on doc](https://snack.expo.dev/?name=RadioButton&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fradio-button.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20View%20%7D%20from%20%27react-native%27%3B%0Aimport%20%7B%20RadioButton%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bchecked%2C%20setChecked%5D%20%3D%20React.useState(%27first%27)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CView%3E%0A%20%20%20%20%20%20%3CRadioButton%0A%20%20%20%20%20%20%20%20value%3D%22first%22%0A%20%20%20%20%20%20%20%20status%3D%7B%20checked%20%3D%3D%3D%20%27first%27%20%3F%20%27checked%27%20%3A%20%27unchecked%27%20%7D%0A%20%20%20%20%20%20%20%20onPress%3D%7B()%20%3D%3E%20setChecked(%27first%27)%7D%0A%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%3CRadioButton%0A%20%20%20%20%20%20%20%20value%3D%22second%22%0A%20%20%20%20%20%20%20%20status%3D%7B%20checked%20%3D%3D%3D%20%27second%27%20%3F%20%27checked%27%20%3A%20%27unchecked%27%20%7D%0A%20%20%20%20%20%20%20%20onPress%3D%7B()%20%3D%3E%20setChecked(%27second%27)%7D%0A%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%3C%2FView%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper) show the exactly what happen

### Screenshots (if applicable)

[screenshot](https://share.getcloudapp.com/kpuJXE8d)

### What have you tried

tested on my local react native project and found the issues, testing the sample code on documentation to re-produce the same issue on snack.

**Comment by lukewalczak** [comment]
Hey @imknight, there are platform-specific differences in the `RadioButton` appearance that's why iOS version has only the _tick_ icon. The main `RadioButton` is adjusting the appearance based on the device system.

If you would like to have `RadioButton` following platform guidelines for Android you can use `RadioButton.Android`:

```
    <View>
      <RadioButton.Android
        value="first"
        status={ checked === 'first' ? 'checked' : 'unchecked' }
        onPress={() => setChecked('first')}
      />
      <RadioButton.Android
        value="second"
        status={ checked === 'second' ? 'checked' : 'unchecked' }
        onPress={() => setChecked('second')}
      />
    </View>
  ```

**Comment by imknight** [comment]
@lukewalczak argh got it I thought something was broken when it doesn't run like the PWA version, sorry should check the documentation more specific. thanks for the reply, I have been stuck on this for the past few days.

**Comment by Goowwy** [comment]
You can use like this
    ```
<RadioButton.Item 
       mode='android'
    />
```
