### ISSUE TITLE
Snackbar is not appearing after upgrading to expo Sdk 45

### ISSUE THREAD

**Issue by alabsi91** [callstack/react-native-paper#3177]
### Current behaviour

- Snackbar is not appearing anymore after upgrading to Expo Sdk 45.

### Expected behaviour

- Show a snackbar with the message when the user clicks on the button.

### Code sample

```
      <Snackbar style={styles.snackbar} visible={snackbar} onDismiss={() => setSnackbar(false)}>
        <View style={styles.snackbarChildren}>
          <Text style={styles.snackbarTxt}>{snackbarMessage}</Text>
          <Svg width='24' height='24' viewBox='0 0 24 24' ariaHidden='true' fill='#fff'>
            <Path d='M20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4C12.76,4 13.5,4.11 14.2, 4.31L15.77,2.74C14.61,2.26 13.34,2 12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0, 0 22,12M7.91,10.08L6.5,11.5L11,16L21,6L19.59,4.58L11,13.17L7.91,10.08Z' />
          </Svg>
        </View>
      </Snackbar>
```

### What have you tried

- I made sure that onDismiss is called when the snackbar is dismissed.
- I tried to change the style.
- I removed the children of the snackbar and replaced it with a text.

### Your Environment

| software           | version  |
| ------------------ | -------- |
| ios or android     | android  |
| react-native       | 0.68.2   |
| react-native-paper | 4.12.1   |
| node               | v16.14.2 |
| npm or yarn        | npm      |
| expo sdk           | 45       |

**Comment by alabsi91** [comment]
After some debugging I figured out that some react-native elements had covered the `snackbar` element, I don't know why that happened with the new Expo version but I moved some elements around and it's appearing again. thanks you for your help.

**Comment by raajnadar** [comment]
Keep one thing in mind the element at the bottom in the JSX has the higher z index on react native. If you want the element to be at the very top every time you need to use portal or place it at the bottom of the JSX.
