### ISSUE TITLE
react-native 0.69 support for new architecture

### ISSUE THREAD

**Issue by xiongemi** [callstack/react-native-paper#3178]
i try to upgrade my existing project with react-native-paper with react-native 0.69.0-rc.1. i got some errors for `react-native-safe-area-context` and `react-native-vector-icons`:

```
warn Package react-native-vector-icons has been ignored because it contains invalid configuration. Reason: "dependency.assets" is not allowed
error Unrecognized command "link".
info Run "react-native --help" to see a list of all available commands.
```

and 
```
Native Component 'SafeAreaView' that calls codegenNativeComponent was not code generated at build time. Please check its definition.
```
here is my dependencies version:
```
    "react-native": "0.69.0-rc.1",
    "react-native-paper": "^4.12.1",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-web": "^0.17.7",
```
is react-native-paper going to support react-native 0.69.0?

**Comment by thymikee** [comment]
`link` has been removed from the RN CLI paired with RN 0.69. It's no longer needed in majority of use cases. Regarding `react-native-safe-area-context`, are you using new architecture (fabric)? Maybe there's a bug in the library, please check its issue tracker anyway.

**Comment by kyle-ssg** [comment]
> `link` has been removed from the RN CLI paired with RN 0.69. It's no longer needed in majority of use cases. 

Hmm but react-native link is really useful for installing fonts, will this have to be manual now?

**Comment by raajnadar** [comment]
Yes you need to do it manually, check this thread

https://github.com/reactwg/react-native-releases/discussions/21#discussioncomment-2985774

**Comment by yudizAnkita** [comment]
> > `link` has been removed from the RN CLI paired with RN 0.69. It's no longer needed in majority of use cases.
> 
> Hmm but react-native link is really useful for installing fonts, will this have to be manual now?

Same Question...

**Comment by raajnadar** [comment]
@yudizAnkita I already answered it, did you check that?

**Comment by kyle-ssg** [comment]
I think I'll write an npm package if they aren't going to come up with a solution. I'll update here if / when.

**Comment by yudizAnkita** [comment]
This blog is very much useful and worked for me to add Custom Fonts manually for both OS

Link : [Custom Fonts Manual Linking](https://kswanie21.medium.com/custom-fonts-in-react-native-tutorial-for-ios-android-76ceeaa0eb78)
