### ISSUE TITLE
how to change blackout 

### ISSUE THREAD

**Issue by mr-kelk** [callstack/react-native-paper#3181]
Hi  how to change the transparency and color of the darkening when you click on FAB.Group component ?
![image](https://user-images.githubusercontent.com/63808200/169688422-cc875da8-a3e6-4f49-9639-23a8d02aaa80.png)

**Comment by lukewalczak** [comment]
Hey @mr-kelk, you can do that by specifying `backdrop` color via `theme` prop:

```
        <FAB.Group
          theme={{colors: {backdrop: 'beige'}}}
		...
		/>
 ```

**Comment by mr-kelk** [comment]
Thank you very much
