### ISSUE TITLE
Adding `pressIn` and `pressOut` events to Button - how?

### ISSUE THREAD

**Issue by esbenvb** [callstack/react-native-paper#3185]
What is the easiest way to make a button that looks/behaves like Paper's  `<Button>` but also supports `onPressIn` and `onPressOut` events?

**Comment by frannale** [comment]
> What is the easiest way to make a button that looks/behaves like Paper's `<Button>` but also supports `onPressIn` and `onPressOut` events?

This is not a issue bro

**Comment by lukewalczak** [comment]
It's not released yet (will be later today).

**Comment by esbenvb** [comment]
Thanks - so which version will contain that feature?

**Comment by lukewalczak** [comment]
Version `5.0.0-rc.4`
