### ISSUE TITLE
Left and Right text are hidden when using placeholder in textInput

### ISSUE THREAD

**Issue by DabirRahmani** [callstack/react-native-paper#3198]
Hi, I have an issue using placeholder and Left or Right together in textInput

before focus, it doesn't show the left string
![image](https://user-images.githubusercontent.com/48196542/172961014-279c4ae5-12aa-49e1-afd5-d6851bef8605.png)
![image](https://user-images.githubusercontent.com/48196542/172961057-d8f89a7d-2c96-4cd0-8023-35206a63e951.png)

if want "$" to be in every state of textinput

here is a sample code on snack
https://snack.expo.dev/@dabir_rahmani/textinput

**Comment by lukewalczak** [comment]
It's correct behavior according to the [docs](https://material.io/components/text-fields#outlined-text-field). In inactive state, when the input is empty, the prefix shouldn't be visible:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/22746080/175809516-c12b93c5-7a11-46c2-bd51-48d841763eec.png">

**Comment by DabirRahmani** [comment]
> It's correct behavior according to the [docs](https://material.io/components/text-fields#outlined-text-field). In inactive state, when the input is empty, the prefix shouldn't be visible:
> 
> <img alt="image" width="602" src="https://user-images.githubusercontent.com/22746080/175809516-c12b93c5-7a11-46c2-bd51-48d841763eec.png">


What if I want to use inputs with prefix and without prefix together?
now placeholders are not in a line. that's why I want a visible prefix in every state

![image](https://user-images.githubusercontent.com/48196542/175816804-e16facc9-cc97-47ea-a734-aea0d3ccd816.png)
