### ISSUE TITLE
React-native-paper training materials?

### ISSUE THREAD

**Issue by tvpmb** [callstack/react-native-paper#3201]
Are there any udemy courses or something similar for training to use react-native-paper? I need to get my team up to speed on the tooling, development environment and "dev ops" for using react-native-paper.

Any resources would be greatly appreciated, I'm having a hard time finding them.

Thanks!

**Comment by lukewalczak** [comment]
Hey @tvpmb, unfortunately, we don't have any additional resources for learning how to use the react-native-paper library.

**Comment by CodingItWrong** [comment]
@tvpmb I've created a few training resources that include React Native Paper; they might be helpful to you:

- A live stream series where I walk through setting up an Expo app from scratch, including React Native Paper and React Navigation. The recordings are available here: https://codingitwrong.com/streams/expo-mobile-web
- I am doing a three-hour workshop based on that live stream this fall at [React Advanced London](https://reactadvanced.com/workshops-3h) and [React Day Berlin](https://reactday.berlin/workshops-3h), both virtual.
