### ISSUE TITLE
 Using react-native-paper on the web with Expo

### ISSUE THREAD

**Issue by eelior** [callstack/react-native-paper#3202]
I am setting up a cross-platform (including web) project using expo and `react-native-paper` as my UI library.

The [Getting Started](https://callstack.github.io/react-native-paper/getting-started.html) walkthrough detailed the instructions also for Expo but going through the [Using on the Web](https://callstack.github.io/react-native-paper/using-on-the-web.html) there is no instructions on how to integrate it with Expo.

I ran pretty fast in trouble trying to understand what to do with the scripts that needs to be change in the `package.lock`:
<img width="593" alt="Screen Shot 2022-06-11 at 0 10 51" src="https://user-images.githubusercontent.com/59517348/173152578-f1748447-93e5-4df3-b6eb-19b680a64853.png">

My current `package.lock` scripts:
<img width="752" alt="Screen Shot 2022-06-11 at 0 19 05" src="https://user-images.githubusercontent.com/59517348/173152738-b031061c-17f3-4e37-b5db-3460e9f4c049.png">

Any help here? Any guide for Expo on this section?

**Comment by mathias-berg** [comment]
Actually, if you are using Expo you are already ready to go without any further settings. I'm using this in an Expo project (Electron/web) and I didn't do anything except installing this package, didn't follow the web instructions at all.
