### ISSUE TITLE
"settings" is not a valid icon name for family "material-community" at Expo

### ISSUE THREAD

**Issue by yoshiishunichi** [callstack/react-native-paper#3209]
Problem encountered during development at Expo.
`<Appbar.Action icon="settings" />`
when using
`"settings" is not a valid icon name for family "material-community"` error occurred and the settings icon did not appear.
I have confirmed that the settings icon is there by referring to this URL.
https://callstack.github.io/react-native-paper/icons.html
Please confirm if there is a workaround.

## versions
```
"expo": "~44.0.0",
"react-native": "0.64.3",
"react-native-paper": "^4.12.1",
```

**Comment by lukewalczak** [comment]
Hey @yoshiishunichi, please try to use `cog`
