### ISSUE TITLE
TextInput placeholder RTL support?

### ISSUE THREAD

**Issue by yaronlevi** [callstack/react-native-paper#321]
Hi (-:
When using TextInput in RTL mode, the header is placed right side (as it should), but the placeholder text is placed left. How can we tell the placeholder text to also be on the right side:

![unnamed](https://user-images.githubusercontent.com/5398977/38873248-fda33c02-425d-11e8-8de6-f3d1b3693ae7.png)

**Comment by ferrannp** [comment]
@yaronlevi does `text-align: right` works for you in the meantime?

**Comment by necolas** [comment]
LTR languages should always be displayed LTR, so it's the labels that are incorrectly positioned

**Comment by yaronlevi** [comment]
Unfortunately, setting **text-align:right** does not work. Is their a rough estimation on when RTL support to TextInput might be available?

**Comment by ferrannp** [comment]
This should land with https://github.com/callstack/react-native-paper/pull/429 and https://github.com/callstack/react-native-paper/pull/434. So let's keep discussion there.

**Comment by saharjedidi** [comment]
Please can you you give me the code of TextInput in RTL mode 
thanks

**Comment by Trancever** [comment]
@saharjedidi What do you mean exactly saying give me the code?  It's an open source project so feel free to fork/clone it and  use it according to your needs.

**Comment by saharjedidi** [comment]
@Trancever 
this is my code 
<TextInput
        label=' كلمة المرور'
        mode='outlined'
        secureTextEntry='true'
        underlineColorAndroid={'rgba(0,0,0,0)'}
        style={this.getStyle().TextInp} text='white'
        direction ='rtl'
        value={this.state.text}
        editable= 'true'
        onChangeText={password => this.setState({ password })}
        underlineColor='transparent'
        editable= 'true'
        theme={{ colors: { placeholder: 'white', text: 'white', primary: 'white',underlineColor:'transparent',background : '#003489'}}}


I want to drag an icon like this and I don't know how ?
![photo](https://user-images.githubusercontent.com/45098179/48896488-07294000-ee48-11e8-9b68-4388db6c9214.png)
thanks a lot for your reply

**Comment by rsimbu89** [comment]
H @Trancever  @saharjedidi 
 Is there any way to set RTL option for placeholder in android?

Setting textAlign: 'left' || 'right' is working fine with iOS but not with android

**Comment by gaurav8809** [comment]
The text should be right to left but not flipped

**Comment by GrayRubix** [comment]
Hi, On your App.js file add 

```
import { I18nManager } from 'react-native';
I18nManager.allowRTL(true)
I18nManager.forceRTL(true)
```


Like:
```

import React from 'react';
import { createAppContainer, createSwitchNavigator } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import { I18nManager } from 'react-native';
import Home from './src/Pages/Home';
import Login from './src/Pages/Login';
import Splash from './src/Pages/Splash';
I18nManager.allowRTL(true)
I18nManager.forceRTL(true)


const SplashScreen = createSwitchNavigator({

  Splash,
  Login,
  Home,
}, {
  navigationOptions: {
    headerVisible: false,
  }
})

export default createAppContainer(SplashScreen)
```

goodLuck

**Comment by juhipatel27** [comment]
> Hi, On your App.js file add
> 
> ```
> import { I18nManager } from 'react-native';
> I18nManager.allowRTL(true)
> I18nManager.forceRTL(true)
> ```
> 
> Like:
> 
> ```
> 
> import React from 'react';
> import { createAppContainer, createSwitchNavigator } from 'react-navigation';
> import { createStackNavigator } from 'react-navigation-stack';
> import { I18nManager } from 'react-native';
> import Home from './src/Pages/Home';
> import Login from './src/Pages/Login';
> import Splash from './src/Pages/Splash';
> I18nManager.allowRTL(true)
> I18nManager.forceRTL(true)
> 
> 
> const SplashScreen = createSwitchNavigator({
> 
>   Splash,
>   Login,
>   Home,
> }, {
>   navigationOptions: {
>     headerVisible: false,
>   }
> })
> 
> export default createAppContainer(SplashScreen)
> ```
> 
> goodLuck

What it will do?

**Comment by gaurav8809** [comment]
> Hi, On your App.js file add
> 
> ```
> import { I18nManager } from 'react-native';
> I18nManager.allowRTL(true)
> I18nManager.forceRTL(true)
> ```
> 
> Like:
> 
> ```
> 
> import React from 'react';
> import { createAppContainer, createSwitchNavigator } from 'react-navigation';
> import { createStackNavigator } from 'react-navigation-stack';
> import { I18nManager } from 'react-native';
> import Home from './src/Pages/Home';
> import Login from './src/Pages/Login';
> import Splash from './src/Pages/Splash';
> I18nManager.allowRTL(true)
> I18nManager.forceRTL(true)
> 
> 
> const SplashScreen = createSwitchNavigator({
> 
>   Splash,
>   Login,
>   Home,
> }, {
>   navigationOptions: {
>     headerVisible: false,
>   }
> })
> 
> export default createAppContainer(SplashScreen)
> ```
> 
> goodLuck

What it will do?

**Comment by Saff-Elli-Khan** [comment]
Add textAlign attribute directly to the React Native TextInput.

```
<TextInput textAlign="right" placeholder="RTL Text" />
```

**Comment by IlanAvigdor** [comment]
> Add textAlign attribute directly to the React Native TextInput.
> 
> ```
> <TextInput textAlign="right" placeholder="RTL Text" />
> ```

This solution will indeed align the placeholder to the right, but will also force the alignment on the text entered by the user, even if the text is in English.

**Comment by Saff-Elli-Khan** [comment]
You should create a Layout Context and check if the layout is "Left" then add textAlign="left" else add textAlign="right".

Something like this:

const Layout = useLayout();
<TextInput textAlign={Layout === "ltr"? "left" : "right"} />

I hope this answer is helpful to you :)

**Comment by Saff-Elli-Khan** [comment]
> You should create a Layout Context and check if the layout is "Left" then add textAlign="left" else add textAlign="right".
> 
> Something like this:
> 
> const Layout = useLayout();
> <TextInput textAlign={Layout === "ltr"? "left" : "right"} />
> 
> I hope this answer is helpful to you :)

This solution will indeed align the placeholder to the right, but will also force the alignment on the text entered by the user, even if the text is in English.

**Comment by Saff-Elli-Khan** [comment]
> > Add textAlign attribute directly to the React Native TextInput.
> > ```
> > <TextInput textAlign="right" placeholder="RTL Text" />
> > ```
> 
> This solution will indeed align the placeholder to the right, but will also force the alignment on the text entered by the user, even if the text is in English.

You should create a Layout Context and check if the layout is "Left" then add textAlign="left" else add textAlign="right". Something like this: 

const Layout = useLayout();  // Layout Stored In Your Context.

<TextInput textAlign={Layout === "ltr"? "left" : "right"} /> 

I hope this answer is helpful to you :)

**Comment by KianooshSoleimani** [comment]
> > > Add textAlign attribute directly to the React Native TextInput.
> > > ```
> > > <TextInput textAlign="right" placeholder="RTL Text" />
> > > ```
> > 
> > 
> > This solution will indeed align the placeholder to the right, but will also force the alignment on the text entered by the user, even if the text is in English.
> 
> You should create a Layout Context and check if the layout is "Left" then add "left" else add "right". Something like this:
> 
> const Layout = useLayout(); // ltr || rtl
> 
> <TextInput textAlign={Layout === "ltr"? "left" : "right"} />
> 
> I hope this answer is helpful to you :)

I have just add multiline props on my textinput fix scrolling
for now its good trick
😉
