### ISSUE TITLE
[5.0.0-rc.2] TypeError: undefined is not an object (evaluating 't.colors') with material-bottom-tabs

### ISSUE THREAD

**Issue by root-io** [callstack/react-native-paper#3220]
### Current behaviour

```shell
TypeError: undefined is not an object (evaluating 't.colors')

This error is located at:
    in MaterialBottomTabViewInner (created by MaterialBottomTabView)
    in RCTView (at View.js:32)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by MaterialBottomTabView)
    in MaterialBottomTabView (created by MaterialBottomTabNavigator)
    in Unknown (created by MaterialBottomTabNavigator)
    in MaterialBottomTabNavigator (at Home.tsx:15)
    in RCTView (at View.js:32)
    in View (at Home.tsx:13)
    in Home (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (at View.js:32)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (at App.tsx:40)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (at App.tsx:39)
    in App (at my-app/index.js:26)
    in ThemeProvider (created by Provider)
    in RCTView (at View.js:32)
    in View (created by Portal.Host)
    in Portal.Host (created by Provider)
    in Provider (at my-app/index.js:25)
    in ApolloProvider (at my-app/index.js:24)
    in ErrorBoundary (at my-app/index.js:23)
    in MyApp (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in MyApp(RootComponent) (at renderApplication.js:60)
```

### Expected behaviour

No error, it was working with react-native-paper v4.12.1

### Code sample

```typescript
import {MD2LightTheme as DefaultTheme, Provider as PaperProvider} from 'react-native-paper';

const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: 'blue',
  },
};
```

```typescript
<Tab.Screen
  name="Foo"
  component={Foo}
  options={{
    tabBarLabel: 'Foo',
    tabBarIcon: ({color}) => (
      <MaterialCommunityIcons name="home" color={color} size={26} />
    ),
  }}
/>
```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 12
| react-native          | 0.68.2
| react-native-paper    | 5.0.0-rc.2
| node                  | 16.15.1
| npm or yarn           | npm 8.11.0
| expo sdk              | no

**Comment by lukewalczak** [comment]
Hey @root-io, thanks for reporting the issue. Could you please create a simple snack presenting the bug or create minimal repo?

**Comment by lukewalczak** [comment]
Ok, I've found the problem - we have to update the `material-bottom-tabs` since it's using old paper version and using [themes](https://github.com/react-navigation/react-navigation/blob/b1c421445ecb75d514ce27791433b12f9a7e75b7/packages/material-bottom-tabs/src/views/MaterialBottomTabView.tsx#L13) `DefaultTheme` and `DarkTheme` which don't exist in paper anymore.

**Comment by wimil** [comment]
> Ok, I've found the problem - we have to update the `material-bottom-tabs` since it's using old paper version and using [themes](https://github.com/react-navigation/react-navigation/blob/b1c421445ecb75d514ce27791433b12f9a7e75b7/packages/material-bottom-tabs/src/views/MaterialBottomTabView.tsx#L13) `DefaultTheme` and `DarkTheme` which don't exist in paper anymore.

how did you manage to solve it?

**Comment by jwueller** [comment]
Maybe I'm not fully understanding what's going on here, but I am very confused why it is even dealing with themes at all:

https://github.com/react-navigation/react-navigation/blob/d19987b0574975df434aa54e0f1c1fba62e7aaa3/packages/material-bottom-tabs/src/views/MaterialBottomTabView.tsx#L99

Shouldn't the `<BottomNavigation/>` component already inherit and handle theme correctly on its own, since passing in the theme is optional anyway? Would it make sense to just remove any reference to themes in `react-navigation`?

**Comment by RGdevz** [comment]
+1

**Comment by DominickVale** [comment]
> Shouldn't the `<BottomNavigation/>` component already inherit and handle theming correctly on its own, since passing it in explicitly is optional anyway? Would it be reasonable to just get rid of it here?
> 
> I'm not entirely sure why navigation needs to deal with theming in the first place. Can't it just treat those props as opaque?

I'm trying to fix it by myself, I'll open a PR, but I'd like to know this too.

**Comment by Gnadhi** [comment]
Any updates on this ?

**Comment by juliushuck** [comment]
I fixed it in this package: https://www.npmjs.com/package/@juliushuck/react-native-navigation-material-bottom-tabs

I will be using it until this issue is resolved. I think react native paper with material ui 3 is currently release candidate, so maybe we have to wait.

This is the change that was required: https://github.com/react-navigation/react-navigation/commit/78f2ee6fdb721b47a63007d5853db2c35164d219

**Comment by DominickVale** [comment]
This has been fixed on both the react-native-paper side in version 5.0.0-rc.4 and on the react-navigation side after [this commit ](https://github.com/react-navigation/react-navigation/commit/f8feedf8e7cb9363e48fb921304f4cad89f53962)

**Comment by error-try-again** [comment]
This is still an issue in version 5.0.2.

**Comment by YunusAndreasson** [comment]
This is still an issue in version 5.0.3.

**Comment by eisodev** [comment]
Still an issue in ```"react-native-paper": "^5.12.3"``` and ```"@react-navigation/material-bottom-tabs": "^6.2.28"```.

Anyone knows a fix?
