### ISSUE TITLE
BUG: Passing an empty label to the TextInput component breaks the components tree.

### ISSUE THREAD

**Issue by VictorioMolina** [callstack/react-native-paper#3221]
I have created this [PR](https://github.com/callstack/react-native-paper/pull/3215) where I have fixed the issue.

### Current behaviour

Explained in the PR.

### Expected behaviour

Explained in the PR.

### Code sample

Explained in the PR.

### What have you tried

Explained in the PR.

### Your Environment

| software              | version
| --------------------- | -------
| ios        | 14
| react-native          | 0.68.2
| react-native-paper    | ^4.12.1
| node                  | 16.13.0
|  yarn           | 1.22.19
| expo sdk              | ^45.0.0

**Comment by lukewalczak** [comment]
Solved via: https://github.com/callstack/react-native-paper/pull/3215, released in `4.12.2`.
