### ISSUE TITLE
[Feature Request] `SearchBar` loading property

### ISSUE THREAD

**Issue by fabriziocucci** [callstack/react-native-paper#3225]
**Is your feature request related to a problem?**
No, but it would be nice if the `SearchBar` component could expose a `loading` property.

**Describe the solution you'd like**
Ideally, when `loading={true}`, an `ActivityIndicator` could be shown in place of the clear icon (like Google Maps does).

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot from Google Maps below:

![image](https://user-images.githubusercontent.com/8156463/175827667-547d64d6-b554-4800-a870-9d6a77d7574a.png)

**Comment by lukewalczak** [comment]
Hey @fabriziocucci, I think that makes sense. Would you like to add the `loading` property to the `Searchbar` _(e.g. similarly to the one existing in `Button`)_ covered by the unit test?

**Comment by gustavohbeg** [comment]
I installed the package in the most up-to-date version but I'm still seeing the old material design design, how do I see the updated material design you ?

**Comment by lukewalczak** [comment]
Solved by: https://github.com/callstack/react-native-paper/pull/3322
