### ISSUE TITLE
Typescript: Component PropTypes are not exposed from RNP lib

### ISSUE THREAD

**Issue by RahulPol** [callstack/react-native-paper#3230]
### Current behaviour
Hi team,
I have created a project with EXPO (v45) + RNP(v5-rc2) + Typescript (v4.7.4).
I am using react native paper along with styled-components. I have created separate files for styles and actual screen/components and it works like a charm. However, I don't see the propTypes for the RNP component (e.g. ButtonProps, TextProps, etc) and thus I am missing Intelli-Sense on the component file.

### Expected behaviour

The RNP components (Button, Text, FAB, etc) propTypes should be exposed like the way we have for react-native, checkout ViewProps, and ButtonProps types under react-native.

### Screenshots (if applicable)

<img width="889" alt="image" src="https://user-images.githubusercontent.com/4542280/176580713-c623e257-d3d0-4d1a-acff-ae7e1b722d90.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 
| react-native          | 0.68.2
| react-native-paper    | 5.0.0-rc.2
| node                  | 16.13.2
| npm or yarn           | 1.22.18
| expo sdk              | 45.0.0

**Comment by RahulPol** [comment]
Hi Team,

Any update on this?

**Comment by lukewalczak** [comment]
Hey @RahulPol, it's on our board, however hard to say when the work over it will be started.
