### ISSUE TITLE
[5.0.0-rc.2] TypeError: undefined is not an object (evaluating '_ref4.margin') in Surface.tsx

### ISSUE THREAD

**Issue by Jabukiro** [callstack/react-native-paper#3237]
### Current behaviour
If I use Surface without providing an object to its `style` prop, then the following error happens.

TypeError: undefined is not an object (evaluating '_ref4.margin')

This error is located at:
    in Surface (created by Login)
    in RCTView (created by View)
    in View (created by Login)
    in Login (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in ThemeProvider (created by Provider)
    in RCTView (created by View)
    in View (created by Portal.Host)
    in Portal.Host (created by Provider)
    in Provider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)

### Expected behaviour

No error, it was working with react-native-paper v4.12.2

### Code sample
https://snack.expo.dev/@client11/58fb98

### What have you tried

Providing an object to the `style` prop resolves the issue. Not sure if this is intended as it is not mentioned in the docs.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 11
| react-native          | 0.68.2
| react-native-paper    | 5.0.0-rc.2
| node                  | 16.15.1
| npm or yarn           | npm 8.11.0
| expo sdk              | 45

**Comment by lukewalczak** [comment]
Thanks @Jabukiro for reporting the issue with the snack. I'm pushing the fix and will try to release the next RC in 2-3 days _(in the meantime you can use the library from the `main` branch or use patch-package)_.
