### ISSUE TITLE
Change backdrop color with theme prop on Dialog not working

### ISSUE THREAD

**Issue by mathias-berg** [callstack/react-native-paper#3246]
### Current behaviour

If I try to use the `theme` prop on a `Dialog` to change the color of the backdrop, nothing happens.
If I do the same with a `FAB.Group` everything works as expected.

### Expected behaviour

The backdrop color should change to the one I pass into the `theme` prop.

### Code sample

Snack with Dialog showing it is not working:
https://snack.expo.dev/@fyranollfyra/dialog---backdrop

Snack with FAB.Group showing it is working:
https://snack.expo.dev/@fyranollfyra/fab-group---backdrop

In both examples I try to change the backdrop color to `transparent`.

### What have you tried

It should just work when I pass a different color. It works for other components that use a backdrop.

### Your Environment

| software              | version
| --------------------- | -------
| electron       |  19.0.7
| react-native          | 0.67.6
| react-native-paper    | 4.12.2
| react-native-web | 0.17.7
| node                  |  16.13.1
| yarn           | 1.22.17
| expo sdk              | 45

**Comment by mathias-berg** [comment]
Since I am using `expo` SDK 45 this is the latest version of `react-native` available.
I'm not using `react-native-vector-icons` in the provided examples either so I guess this would suffice?

**Comment by lukewalczak** [comment]
Fix released in 4.12.3.

**Comment by micahlt** [comment]
Same issue here, but with the 5.0.0 release candidate.

**Comment by micahlt** [comment]
Awesome, thanks!
