### ISSUE TITLE
How do I change BottomNavigation active item icon bg color?

### ISSUE THREAD

**Issue by eelior** [callstack/react-native-paper#3248]
<img width="216" alt="image" src="https://user-images.githubusercontent.com/59517348/178103155-28accf55-f549-4618-a983-d4271f129481.png">

The new Material You UI adds an ellipse to the background of the active item.
How do I control the color of that element?

**Comment by lukewalczak** [comment]
Hey @eelior, you have to override the `secondaryContainer` color via theme prop:

```
    <BottomNavigation
      ...
      theme={{colors: {secondaryContainer: 'yellow'}}}
    />
  ```

**Comment by eelior** [comment]
> Hey @eelior, you have to override the `secondaryContainer` color, locally in the component via theme prop:
> 
> ```
>     <BottomNavigation
>       ...
>       theme={{colors: {secondaryContainer: 'yellow'}}}
>     />
> ```

Thanks!

**Comment by Judono** [comment]
I found to fix the problem you need to wrap your app in a theme so it would look like this

`
import * as React from 'react';
import {
  MD3LightTheme as DefaultTheme,
  Provider as PaperProvider,
} from 'react-native-paper';
import App from './src/App';

const theme = {
  ...DefaultTheme,
  // Specify custom property
  myOwnProperty: true,
  // Specify custom property in nested object
  colors: {
   // this will turn the 'pill to yellow'
   // to make it 'transparent, you can make it same color as your background
    secondaryContainer: 'yellow',
  },
};

export default function Main() {
  return (
    <PaperProvider theme={theme}>
      <App />
    </PaperProvider>
  );
}
`

**Comment by Isaac-alencar** [comment]
> I found to fix the problem you need to wrap your app in a theme so it would look like this
> 
> `import * as React from 'react'; import { MD3LightTheme as DefaultTheme, Provider as PaperProvider, } from 'react-native-paper'; import App from './src/App';
> 
> const theme = { ...DefaultTheme, // Specify custom property myOwnProperty: true, // Specify custom property in nested object colors: { // this will turn the 'pill to yellow' // to make it 'transparent, you can make it same color as your background secondaryContainer: 'yellow', }, };
> 
> export default function Main() { return ( ); }`

Thank you so much, dude! I tried this and worked fine. Just for the future, I'm replying with your own answer but with syntax highlight:

```js
import * as React from "react";
import {
  MD3LightTheme as DefaultTheme,
  Provider as PaperProvider,
} from "react-native-paper";
import App from "./src/App";

const theme = {
  ...DefaultTheme,
  // Specify custom property
  myOwnProperty: true,
  // Specify custom property in nested object
  colors: {
    // this will turn the 'pill to yellow'
    // to make it 'transparent, you can make it same color as your background
    secondaryContainer: "yellow",
  },
};

export default function Main() {
return (

);
 ```

**Comment by fr3nzy** [comment]
also make sure you pass the modified theme to PaperProvider as <PaperProvider theme={theme}>

**Comment by bitlab-code** [comment]
> Hey @eelior, you have to override the `secondaryContainer` color, locally in the component via theme prop:
> 
> ```
>     <BottomNavigation
>       ...
>       theme={{colors: {secondaryContainer: 'yellow'}}}
>     />
> ```

> locally in the component via theme prop:
@lukewalczak this seem not work with v. `5.8.0`
