### ISSUE TITLE
Use Bottom Navigation without router logic

### ISSUE THREAD

**Issue by leoparis89** [callstack/react-native-paper#3250]
I would like to use the BottomNavigation component alone, with a ReactNavigation Router just on top.

To do so I set renderScene to `()=>null` and I handle my navigation with `onIndexChange`.
It works fine, except that bottomNavigation leaves a padding in what would have been the content of renderScene (I highlighted the element in the screenshot).
How can I remove that element blocking the screen ?
Is there anyway I can display BottomNavigation **alone** ?

Many thanks
<img width="510" alt="Capture d’écran 2022-07-10 à 20 31 14" src="https://user-images.githubusercontent.com/19576344/178157531-6ebee8e0-cfe2-46bd-9821-38d75607eb9c.png">

**Comment by lukewalczak** [comment]
Hey @leoparis89, according to the comment above, please provide the minimal repro demonstrating the issue or use expo snack for it.
