### ISSUE TITLE
Text in Badge not centered

### ISSUE THREAD

**Issue by DeepBlueDevOps** [callstack/react-native-paper#3251]
### Current behaviour

Text within the Badge component will not center (see attached images). It displays properly on some devices however not on a physical iPhone 13 Pro Max I am testing on. First pic is my app, second pic is the react-native-paper demo app from Apple App Store.

### Code sample

Here is a snippet from my app.. 

            <View style={{flexDirection: 'column'}}>
              <View style={{alignContent: 'center'}}>
                <Badge>{count[0]}</Badge>
              </View>
              <View>
              </View>
            </View>

### What have you tried

I have tried to adjust with styling the Badge component. As well as adjusting styling of the Views containing the Badge However nothing seems to help.

It does behave as desired on iOS and Android simulators.

### Your Environment

| software              | version
| --------------------- | -------

Development environment:
OS: macOS 12.4
CPU: (10) arm64 Apple M1 Max
react: 17.0.2
react-native: 0.68.1 
react-native-paper 4.12.2
node v18.4.0
npm 8.12.1

Device info with the issue:
iPhone 13 Pro Max
iOS ver 15.5

![IMG_1573](https://user-images.githubusercontent.com/92817968/178548454-f6aa63cc-d978-46f4-8666-44dc85f03bde.jpeg)
![IMG_1574](https://user-images.githubusercontent.com/92817968/178548474-81baf22b-218b-4334-8a54-5bff690579b0.jpeg)

**Comment by lukewalczak** [comment]
Fix released in `4.12.4`.

**Comment by GoDeepBlue** [comment]
Awesome! Just validated in test – thank you!

 

From: Luke Walczak ***@***.***>
Reply-To: callstack/react-native-paper ***@***.***>
Date: Tuesday, July 26, 2022 at 5:00 AM
To: callstack/react-native-paper ***@***.***>
Cc: JaminJ ***@***.***>, Manual ***@***.***>
Subject: Re: [callstack/react-native-paper] Text in Badge not centered (Issue #3251)

 

Fix released in 4.12.4.
