### ISSUE TITLE
ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

### ISSUE THREAD

**Issue by chhorvon** [callstack/react-native-paper#3253]
### Your Environment

| software              | version
| --------------------- | -------
| react-native          |  0.68.2
| react-native-paper    | 5.0.0-rc.3
| expo sdk              | ~45.0.0

**Comment by danidaryaweesh** [comment]
@chhorvon Has this issue been solved in the 5.x version?
