### ISSUE TITLE
How to remove highlight/outline/shadow from card?

### ISSUE THREAD

**Issue by rexpeditionco** [callstack/react-native-paper#3269]
Is there a way to remove the upper highlight and bottom dark border and shadow from the card component at them preferably at the theme level, or set them to transparent?

**Comment by rexpeditionco** [comment]
"react-native": "0.68.2",
"react-native-paper": "^5.0.0-rc.3",
"react-native-vector-icons": "^9.2.0",
    
  no repro needed, just use a card component standard

**Comment by lukewalczak** [comment]
Hey @rexpeditionco, maybe the card's mode called "contained" will fit for you, since it doesn't have outline and elevation, however, it has a different background color. 
Another approach can be passing a prop `elevation={0}` or changing outline color to "transparent":
```
theme={{
  colors: {
    outline: 'transparent',
  },
}}
```
