### ISSUE TITLE
keyboardHidesNavigationBar not work in BottomNavigation

### ISSUE THREAD

**Issue by cervisebas** [callstack/react-native-paper#3271]
### Current behaviour
Opening the keyboard does not hide the bottom bar

### Expected behaviour
Hide the bottom bar after touching a TextInput or Searchbar

### Code sample
`<BottomNavigation
            navigationState={{
                index: this.state.indexNav,
                routes: this.routesnav
            }}
            sceneAnimationEnabled={true}
            sceneAnimationType={'shifting'}
            keyboardHidesNavigationBar={true}
            onIndexChange={(index)=>this.setState({ indexNav: index })}
            renderScene={this.renderScene}
/>`

### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/52644268/180485530-61afd6ed-5258-4cb0-b1bf-c2c4932182da.png)

### What have you tried
-

### Your Environment

| software              | version
| --------------------- | -------
| android        | 11
| react-native          | 0.69.1
| react-native-paper    | 5.0.0-rc.3
| node                  | 16.15.1
| yarn           | 1.22.19
| expo sdk              | none

**Comment by lukewalczak** [comment]
Hey @cervisebas, could you please check the comment above and attach the expo snack or minimal repo presenting the issue?
