### ISSUE TITLE
Icons not loading in paper, works fine with react-native-vector-icons directly

### ISSUE THREAD

**Issue by sourabhv** [callstack/react-native-paper#3273]
### Current behaviour

Can't load icons from paper. 

The source code checks for material icons with this code 

```js
try {
  // Optionally require vector-icons
  MaterialCommunityIcons =
    require('react-native-vector-icons/MaterialCommunityIcons').default;
} catch (e) {
...
}
```

and shows the console.warn message.

However if I write `require('react-native-vector-icons/MaterialCommunityIcons').default` in my source code, it works fine. I can even load icons using

```ts
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';

// ...

<Icon name="chevron-right" size={20} color={color} />
```

### Expected behaviour

Paper should be able to load icons

### Screenshots (if applicable)

<img width="520" alt="Screenshot 2022-07-24 at 9 50 43 PM" src="https://user-images.githubusercontent.com/2307626/180656599-627000fb-7560-43c1-83d8-6197c2e6d7c3.png">
<img width="520" alt="Screenshot 2022-07-24 at 9 51 12 PM" src="https://user-images.githubusercontent.com/2307626/180656614-0c3edb8f-d5a9-4a3a-b973-e6efbea9599a.png">
<img width="520" alt="Screenshot 2022-07-24 at 9 51 26 PM" src="https://user-images.githubusercontent.com/2307626/180656615-5252f4c6-b813-4b3c-858c-2aab552e63fc.png">

### What have you tried

I am kinda clueless to be honest, how can the same package work in my code and not in paper

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios | 
| react-native          |  0.69.2  | 
| react-native-paper    | 4.12.3  |
| react-native-vector-icons | 9.2.0 |
| node                  | v18.6.0 | 
| npm           | 8.13.2 | 
| expo sdk              | NA |

**Comment by lukewalczak** [comment]
Hey @sourabhv, could you please provide the repro?

**Comment by sourabhv** [comment]
[rnp-sample.zip](https://github.com/callstack/react-native-paper/files/9185149/rnp-sample.zip)

Hi, here's a zip. It shows 2 buttons, one has icon, other doesn't.

**Comment by rzfzr** [comment]
For future reference the install instructions [are these](https://github.com/oblador/react-native-vector-icons#installation)
