### ISSUE TITLE
TextInput label does not remain above input value after user enters value and field loses focus.

### ISSUE THREAD

**Issue by aluminium22** [callstack/react-native-paper#328]
### Current behaviour

When using the TextInput the placeholder animates to the top over the input as though it becomes the label (which is as one would expect).
After removing focus from that field/input the the placeholder drops back down into the input field overlapping previously typed value. This creates a strange unexpected appearance.

### Expected behaviour

After focus leaves the input/field. The placeholder should remain as the label if there is a value in the input.

### Code sample

```
import * as React from 'react';
import { TextInput } from 'react-native-paper';

class MyComponent extends React.Component {
  handleChangeEmail = (email) => {
    console.log('change email', email);
  }
  handleChangePassword = () => {
    console.log('change password');
  }
  render(){
    return (
    <View>
       <TextInput
          label={'Email or Phone Number'}
          onChangeText={this.handleChangeEmail}
          value={''}
       />
      <TextInput
         label={'Password'}
         onChangeText={this.handleChangePassword}
        value={''}
        secureTextEntry={true}
      />
    </View>
    );
  }
}

```
### Screenshots (if applicable)

![screen shot 2018-04-18 at 10 11 37 am](https://user-images.githubusercontent.com/6405831/38937301-e921ca62-42f0-11e8-90c2-b649be5740c7.png)

### What have you tried

I have tried using placholders and not labels, I've tried using values only, to see if this worked. Closest I got was setting the label equal to the same value as the value attribute, but then you lose the animation where the placeholder jumps to the label.

### Your Environment

| software              | version
| MacOS High Sierra | 10.13.3
| ios or android        | both 
| react-native          | yes
| react-native-paper    | yes
| node                  | yes
| npm or yarn           | npm

**Comment by satya164** [comment]
Currently you need to use `TextInput` as a controlled component. https://github.com/callstack/react-native-paper/issues/154
