### ISSUE TITLE
Neither MD2Theme nor MD3LightTheme is available

### ISSUE THREAD

**Issue by DanhDao1997** [callstack/react-native-paper#3281]
### Current behaviour

I'm currently trying to create a custom theme by following the docs from https://callstack.github.io/react-native-paper/theming.html

However, when I import either MD2Theme or MD3LightTheme, VS Code warns me that Module '"react-native-paper"' has no exported member

I tested with a Snack and found that it also generates error when I build because there is no theme to extend

### Expected behaviour

The theme extending should be working

### Code sample

https://snack.expo.dev/@ddao/5595ba

### Screenshots (if applicable)

<img width="313" alt="image" src="https://user-images.githubusercontent.com/110004731/181425094-966bbb03-4288-48ab-aaa1-d44ad969772c.png">

### What have you tried

Followed the instruction in installing and creating theme

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |15.5
| react-native          |0.69.2
| react-native-paper    |4.12.4
| node                  |16.16.0
| npm or yarn           |yarn v1.22.15
| expo sdk              |no

**Comment by lukewalczak** [comment]
Hey @DanhDao1997, you have to install `react-native-paper@5.0.0-rc.3`
