### ISSUE TITLE
ToggleButton multi select: different colors

### ISSUE THREAD

**Issue by dinhopereira** [callstack/react-native-paper#3282]
Hello everyone!

I'm developing an app that will have a page for selecting 10 numbers from 01 to 100.
I'm using the ToggleButton, but I'd like to customize the colors:

[https://snack.expo.dev/@dinhopereira/multiselectnumbers]

Checked: Green background with white font
Unchecked: White background with green font

I'm using line-by-line checking, but I think the code will be wordy.

Does anyone have a tip on how to make the code more "friendly"?

tks

**Comment by dinhopereira** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
>     * `react-native`
> 
>     * `react-native-paper`
> 
>     * `react-native-vector-icons`
> 
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

"react-native": "^0.69.0"
"react-native-paper": "^4.12.2"
"react-native-vector-icons": "^9.2.0"

**Comment by raduly-zalan** [comment]
Hi @dinhopereira,

Is the question still available? If so, then I could create an example for you.

**Comment by lukewalczak** [comment]
Hey @raduly-zalan, feel free to attach the snack with the example or paste some code :)
