### ISSUE TITLE
Material You theme not available in Expo-created app

### ISSUE THREAD

**Issue by digicommons** [callstack/react-native-paper#3285]
### Current behaviour

On a fresh app created with Expo, Paper components (f.e. FAB) are not styled with Material You but with MD2 (e.g. FAB is a circle). I could not find a way to override this behaviour.

### Expected behaviour

Since Material You seems is the new default, Paper components should be styled with MD3/Material You instead of MD2 or the docs should be more clear about setting up MD3.

### Code sample

https://snack.expo.dev/6REz8Lopt

### Screenshots (if applicable)

![Screenshot_20220802-125319-copy](https://user-images.githubusercontent.com/43313518/182358927-e5af58f1-522a-45bb-b6e8-8e97b669076d.png)

### What have you tried

- explicitly setting theme version to 3
- searching related issues
- checking [Paper example app](https://snack.expo.dev/@react-native-paper/github.com-callstack-react-native-paper:example) for differences

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | expo go android
| react-native          | 0.68.2
| react-native-paper    | 4.12.4
| react-native-vector-icons | 9.2.0
| node                  | 18.2.0
| npm           | 8.9.0
| expo              | 45.0.0

Reproduced in [Expo Snack v44.0.0](https://snack.expo.dev/6REz8Lopt)

**Comment by lukewalczak** [comment]
Hey @digicommons, you should use `react-native-paper: 5.0.0-rc.3` version.

**Comment by digicommons** [comment]
Perfect, that works! Thank you.

Could you possibly add a hint in the docs that MD3 is still rc?

**Comment by lukewalczak** [comment]
> Could you possibly add a hint in the docs that MD3 is still rc?

Yup, I will add that note, since we are receiving more issues related to mixing the latest version with Material You.
