### ISSUE TITLE
How to use custom Appbar.BackAction type in Appbar?

### ISSUE THREAD

**Issue by hbriese** [callstack/react-native-paper#3287]
Currently in Appbar, `.type` of the children is used to determine what the child is for e.g. [`AppbarBackAction`](https://github.com/callstack/react-native-paper/blob/6afa4fb98c6826c4d6b80db055ef8f21ed07b59a/src/components/Appbar/Appbar.tsx#L213)

Is it possible to override a component's `.type` so that it can be picked up as the back action?

I can see how this would be done if a different property was used, such as `displayName`
```ts
AppbarBack.displayName = Appbar.BackAction.displayName;
```

| software              | version
| --------------------- | -------
| react-native-paper    | 5.0.0-rc.3

**Comment by lukewalczak** [comment]
Hey @hbriese, could you please describe or present visually what are you trying to achieve?

**Comment by hbriese** [comment]
> Hey @hbriese, could you please describe or present visually what are you trying to achieve?

Currently it is not possible to render a large appbar header with a menu action in place of the back action, for instance

**Comment by hbriese** [comment]
Other basic examples include using my own wrapper component as the back action, for instance.
When using these wrappers, the Appbar header component will not correctly identify the wrapper component as the back action and thus will not layout the component in the correct area

**Comment by hbriese** [comment]
Another basic example of this issue.

# Works (small)
```tsx
<Appbar.Header mode="small">
        <Appbar.Action icon={MenuIcon} />
        <Appbar.Content title="Title" />
</Appbar.Header>
```
![image](https://user-images.githubusercontent.com/14974903/194439461-23f8d984-6c75-4d2a-91bd-f7fdbdfd83c0.png)


# Doesn't work (any other mode)
```tsx
<Appbar.Header mode="large">
        <Appbar.Action icon={MenuIcon} />
        <Appbar.Content title="Title" />
</Appbar.Header>
```
![image](https://user-images.githubusercontent.com/14974903/194439512-92448dce-fbab-4419-979a-a7aca22b38d8.png)


To repeat myself, there is no way to get the menu action to be shown in the place of the back action as `BackAction.type` is used to check and position the component

**Comment by hbriese** [comment]
This was incorrectly closed and is still not possible to achieve (using Appbar.Header)

**Comment by BanDroid** [comment]
this should be opened again, why is it closed without confirmation? i'm having issue with this

**Comment by BanDroid** [comment]
@hbriese  found a solution, your sample already fine, what you need now is to add a middle view between the custom `Appbar.Action` and `Appbar.Content` and make it flex 1:

```jsx
<Appbar.Header mode="large">
    <Appbar.Action icon="menu" />
    <View style={{ flex: 1 }} />
    <Appbar.Content title="Title" />
    <Appbar.Action icon="bell" />
</Appbar.Header>
```
