### ISSUE TITLE
dispatch command called without surface id

### ISSUE THREAD

**Issue by aleluiah** [callstack/react-native-paper#3288]
### Current behaviour
crashed on react native 0.69.1 with fabric enabled

crashes saying dispatch command called without surface id - fabric dispatch command must be called through fabric jsi api
### Expected behaviour
to work normally

work normally
### Code sample
-----

----
### What have you tried
works in paper

debug crash information
### Your Environment
windows 10
| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.69.1
| react-native-paper    | 4.11.1
| node                  | 14.0
| npm or yarn           | 6
| expo sdk              | none

fabric is enabled

**Comment by BloodyMonkey** [comment]
Any update ?
