### ISSUE TITLE
Navigating from a nested material-top-tabs to a material-bottom-tabs doesn't work

### ISSUE THREAD

**Issue by GaylordP** [callstack/react-native-paper#3292]
Hello and thank you for your library :)

Let me copy/paste a problem posted by @andrei-datcu on [react-navigation](https://github.com/react-navigation/react-navigation/issues/10234), because I have the same problem

## Description

Material bottom tabs with two routes:
TopTabs: Material Top tabs with two routes Screen 1 & Screen 2
Screen3 (default)

App starts with Screen2. Navigate to TopTabs. Navigate to Screen 2. Navigate to Screen 3: You'll get a flicker and a navigation back to TopTabs(Screen1)

### Screenshots

https://user-images.githubusercontent.com/10829674/182887916-04ef92b0-396c-4911-a9db-9ae0091448de.mp4

### Expected behavior

The navigation should work and you should not get navigated back.

## Reproduction

https://snack.expo.dev/D35XYxBvr

## Platform

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |      ^0.69.1   |
| @react-navigation/native               |    ^6.0.6     |
| @react-navigation/native-stack         |     ^6.7.0    |
| react-native-screens                   |      ^3.10.2   |
| react-native-safe-area-context         |   ^4.3.1      |
| react-native-gesture-handler           |     ^2.3.2    |
| react-native-reanimated                |      ^2.3.1   |
| react-native-paper                |      ^4.12.2   |
| react-native-vector-icons                |      ^9.1.0   |

**Comment by GaylordP** [comment]
Hello again :)
Sorry for my english, I'm french :) 

I spent the night there but without finding a solution.
I see that [react-native-tab-view : PagerViewAdapter.tsx#L142](https://github.com/satya164/react-native-tab-view/blob/main/src/PagerViewAdapter.tsx#L142) is triggered when we page from one bottom tab to another:

        onPageSelected={(e) => {
          const index = e.nativeEvent.position;
          indexRef.current = index;
          onIndexChange(index);
        }}

`onPageSelected` it's a event from [react-native-pager-view : PagerView.tsx#L152](https://github.com/callstack/react-native-pager-view/blob/master/src/PagerView.tsx#L152)

This situation does not occur with [Bottom-Tabs](https://reactnavigation.org/docs/bottom-tab-navigator), only with [Material-Bottom-Tabs](https://reactnavigation.org/docs/material-bottom-tab-navigator/).

### Simple example :

For a simple example, I have integrated a very simple PagerView in [Bottom-Tabs](https://reactnavigation.org/docs/bottom-tab-navigator) and [Material-Bottom-Tabs](https://reactnavigation.org/docs/material-bottom-tab-navigator/).

Material Bottom Tabs always resets PagerView, and I think this is the problem with [Material Top Tabs](https://reactnavigation.org/docs/material-top-tab-navigator/) :

### With Bottom Tabs : 

https://snack.expo.dev/MEekEpszt

https://user-images.githubusercontent.com/10829674/183068439-655d985a-f516-498d-997d-9ce3a1521a16.mov

### With Bottom Material Tabs (and react-native-paper) :

https://snack.expo.dev/d1i9hcGun

https://user-images.githubusercontent.com/10829674/183068533-dd12eb4c-5bbd-4739-b93f-bae98e53f1a2.mov

Maybe it's related to [detachinactivescreens](https://reactnavigation.org/docs/bottom-tab-navigator#detachinactivescreens) but I didn't find any concrete influence in my examples. If someone more experienced than me could take a look ... :)

**Comment by Boscher-audrey** [comment]
Hello, same issue here :/
Using @react-navigation/bottom-tabs instead of @react-navigation/material-bottom-tabs is not an option for me, so would be nice to have a solution !

**Comment by JacobDel** [comment]
@Boscher-audrey  There is a solution on this stackoverflow post: https://stackoverflow.com/a/73348535/9611924

**Comment by Maclay74** [comment]
@JacobDel this solution doesn't work, we tried.

**Comment by lukewalczak** [comment]
Fix will be released in `5.0.0-rc.5`
