### ISSUE TITLE
ref not working for TextInput

### ISSUE THREAD

**Issue by bombillazo** [callstack/react-native-paper#3295]
### Current behaviour

I am trying to use the `useRef` hook to get the TextInput object used by RNP internally. When doing to, I get this warning:
```sh
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?%s%s, 
```

### Expected behaviour

I am able to use the ref in my hooks to get TextInput state data and setter functions.

### Code sample

```js
...
import { TextInput } from 'react-native-paper';

export const CustomInput: FC<FormTextInputProps> = (props) => {
  const inputRef = useRef(null);

  useEffect(()=> {
    console.log(inputRef.current);
  }, [inputRef])

  return (
    <TextInput
      ref={inputRef}
      {...props}
    />
  );
};
```

### What have you tried

I tried innerRef (doesn't exist).

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          | 0.69.3
| react-native-paper    | 4.12.4
| node                  | v16.14.2
| npm or yarn           | 1.22.19
| expo sdk              | 46.0.0

**Comment by bombillazo** [comment]
Similar to https://github.com/callstack/react-native-paper/issues/1322 but that issue was related to class components.

**Comment by lukewalczak** [comment]
Hey @bombillazo, unfortunately I'm not able to reproduce it.

**Comment by bombillazo** [comment]
Hey, I think it may have been an issue on my side while creating a custom TextInput component, so I'll close this until I can replicate and isolate to RNP if it is the cause. Thanks!
