### ISSUE TITLE
Make Menu component SCREEN_INDENT configurable.

### ISSUE THREAD

**Issue by bombillazo** [callstack/react-native-paper#3296]
**Is your feature request related to a problem? Please describe.**
I have some screens using TextInputs that must be flush to the screen edges. Rather than having a whole separate TextInput component or working around styles, it would be great to have this value overrideable.

**Describe the solution you'd like**
Expose this property somehow to be able to override this value.
**Describe alternatives you've considered**
Either have a separate component (impractical since it would break UI consistency of using RNP) or programmatically remove this gap by offsetting the gap, which is not performant and complicates the code.

**Additional context**
Want to remove this gap caused by SCREEN_INDENT
<img width="394" alt="image" src="https://user-images.githubusercontent.com/44002321/183293251-0ab3f549-b925-409a-a1c4-998732d482ab.png">

react-native: 0.69.3
react-native-paper: 4.12.4
react-native-vector-icons: 9.2.0

**Comment by lukewalczak** [comment]
Hey @bombillazo, I think we can introduce an optional property, which can override the hardcoded value. If you would like to handle that, please open a PR.

**Comment by bombillazo** [comment]
Hey, sure, Ill try to get something done

**Comment by bombillazo** [comment]
Hey, Im closing this as the use case changed and I no longer require to change this.
