### ISSUE TITLE
Menu doesn't open on the Next.js web app after upgrading to React 18

### ISSUE THREAD

**Issue by reck753** [callstack/react-native-paper#3297]
### Current behaviour

What I managed to find out is that the animations are not firing and hence the menu doesn't pop up where it should be nor it gets sized accordingly. The menu appears in the DOM, but it's size (height I think) remains 0.
The Menu works perfectly on plain RN web.

### What have you tried

I tried upgrading Next.js to a larger version, as I thought it might be connected to them, however it didn't help. Tried upgrading the React as well, also, it didn't help.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    |
| node                  |
| npm or yarn           |
| expo sdk              |

**Comment by popejs** [comment]
I found the same issue when upgrading Next.js web Reac 18

**Comment by reck753** [comment]
UPDATE: I did some further debugging and found out that sending the `Menu` through its `Portal` somehow causes the issue. 
For example, replacing `Portal` with `React.Fragment`, in `Menu.tsx` would make menu appear and show (of course, displaced since we removed `Portal`).
With further debugging I found out that setting of `this.menu` in `View` `ref` (here) "lags" behind for the next render and that's why it doesn't show up:

With `Portal`:

<img width="913" alt="Screenshot 2022-08-22 at 23 47 33" src="https://user-images.githubusercontent.com/58557161/186025005-a0c71516-363e-4bf8-b34e-8871bcd4d757.png">

Without `Portal`, kind-a working (we can see the menu):

<img width="892" alt="Screenshot 2022-08-22 at 23 47 10" src="https://user-images.githubusercontent.com/58557161/186025018-38cb85b3-ea8f-46d0-858d-3f175a4cd5a2.png">

I couldn't find any solution for the problem... I hope this can help a bit someone else in the debugging process.

**Comment by gatouillatpy** [comment]
`this.menu` is `null` sometimes when rendered for the first time, as commented here https://github.com/callstack/react-native-paper/blob/main/src/components/Menu/Menu.tsx#L275-L280 (especially since React 18, I have the same problem)

This leads https://github.com/callstack/react-native-paper/blob/main/src/components/Menu/Menu.tsx#L270 to never return.

Solution is to replace https://github.com/callstack/react-native-paper/blob/main/src/components/Menu/Menu.tsx#L183-L187 with:
```
if (this.menu) {
	this.menu.measureInWindow((x, y, width, height) => {
		resolve({ x, y, width, height });
	});
} else {
	resolve({ x: 0, y: 0, width: 0, height: 0 });
}
```

**Comment by lukewalczak** [comment]
@gatouillatpy would you like to prepare the fix for it?

**Comment by mathias-berg** [comment]
Can confirm the above solution works. Just upgraded from Expo 45 to Expo 46 (React 18) and the menu stopped showing in my app, forked this repo and did the above and everything works now.

**Comment by lukewalczak** [comment]
I will be happy to accept your contribution

**Comment by mathias-berg** [comment]
@lukewalczak I will see if I can pull something together in the upcoming days.

**Comment by mathias-berg** [comment]
This seems to be fixed in RC, I'm sorry for not helping out, a lot of things got in the way.

**Comment by lukewalczak** [comment]
> This seems to be fixed in RC, I'm sorry for not helping out, a lot of things got in the way.

Based on that information, closing the issue.
