### ISSUE TITLE
BottomNavigation | The example for BottomNavigation , Icon is not show.

### ISSUE THREAD

**Issue by momolly1024** [callstack/react-native-paper#3299]
Hi , 

In BottomNavigation  [Expo ](https://snack.expo.dev/?name=BottomNavigation&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fbottom-navigation.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20BottomNavigation%2C%20Text%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MusicRoute%20%3D%20()%20%3D%3E%20%3CText%3EMusic%3C%2FText%3E%3B%0A%0Aconst%20AlbumsRoute%20%3D%20()%20%3D%3E%20%3CText%3EAlbums%3C%2FText%3E%3B%0A%0Aconst%20RecentsRoute%20%3D%20()%20%3D%3E%20%3CText%3ERecents%3C%2FText%3E%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bindex%2C%20setIndex%5D%20%3D%20React.useState(0)%3B%0A%20%20const%20%5Broutes%5D%20%3D%20React.useState(%5B%0A%20%20%20%20%7B%20key%3A%20%27music%27%2C%20title%3A%20%27Favorites%27%2C%20focusedIcon%3A%20%27heart%27%2C%20unfocusedIcon%3A%20%27heart-outline%27%7D%2C%0A%20%20%20%20%7B%20key%3A%20%27albums%27%2C%20title%3A%20%27Albums%27%2C%20focusedIcon%3A%20%27album%27%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20%27recents%27%2C%20title%3A%20%27Recents%27%2C%20focusedIcon%3A%20%27history%27%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20%27notifications%27%2C%20title%3A%20%27Notifications%27%2C%20focusedIcon%3A%20%27bell%27%2C%20unfocusedIcon%3A%20%27bell-outline%27%20%7D%2C%0A%20%20%5D)%3B%0A%0A%20%20const%20renderScene%20%3D%20BottomNavigation.SceneMap(%7B%0A%20%20%20%20music%3A%20MusicRoute%2C%0A%20%20%20%20albums%3A%20AlbumsRoute%2C%0A%20%20%20%20recents%3A%20RecentsRoute%2C%0A%20%20%7D)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CBottomNavigation%0A%20%20%20%20%20%20navigationState%3D%7B%7B%20index%2C%20routes%20%7D%7D%0A%20%20%20%20%20%20onIndexChange%3D%7BsetIndex%7D%0A%20%20%20%20%20%20renderScene%3D%7BrenderScene%7D%0A%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper)

The Icons are no show

![image](https://user-images.githubusercontent.com/61406208/183378150-50c4b7f0-f301-49c1-9986-26b8da4fe397.png)

Same as I run this example in android studio.

( Have already install react-native-vector-icons )

**Comment by momolly1024** [comment]
Hi @lukewalczak , Thx for replying.
But When I use the example code 
MD2: https://snack.expo.dev/zfHWw-yrYQ
The icon show like this : 

![image](https://user-images.githubusercontent.com/61406208/183543622-55cb53fa-7d83-4463-85fe-889251cd6953.png)


And When I use example code from MD3: https://snack.expo.dev/mT7Ul3xWE
Icons still no show : 

![image](https://user-images.githubusercontent.com/61406208/183543805-027225ab-13be-4007-bfde-96142c9a7240.png)

My package
```
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/material-bottom-tabs": "^6.2.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "react": "18.0.0",
    "react-native": "0.69.3",
    "react-native-paper": "^4.12.4",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.15.0",
    "react-native-vector-icons": "^9.2.0"
  },
```



Qustion 1:
Did I lost something when setting project ? 

Qusetion 2:
What's different between official website's example code, MD2 and MD3 (from you provided) ?





Thank you, 
and 
Have a nice day !

**Comment by lukewalczak** [comment]
Please check the dependencies version in package.json for each snack, eg. MD3 is within `react-native-paper@5.0.0.rc-4` while MD2 is `4.12.4`.

For more details please check the [migration](https://callstack.github.io/react-native-paper/introducing-v5-with-material-you.html) guide from version 4 to 5.

**Comment by momolly1024** [comment]
Got it !  Thank you.

But How to explain ( or fix ) this one ?

Use [MD2 ](https://snack.expo.dev/zfHWw-yrYQ) example code but icon cannot show correctly.

![image](https://user-images.githubusercontent.com/61406208/183610884-b5fe622d-9a77-4469-8c81-68cddd4529bf.png)

**Comment by lukewalczak** [comment]
On the presented snack icons are displayed properly on both platforms:

ios | android
--- | ---
<img width="1512" alt="Zrzut ekranu 2022-08-9 o 11 37 40" src="https://user-images.githubusercontent.com/22746080/183617326-c6d140db-53ed-4065-9863-5053fb7b3aa9.png"> | <img width="1512" alt="Zrzut ekranu 2022-08-9 o 11 38 57" src="https://user-images.githubusercontent.com/22746080/183617348-279ae9c7-ab3a-43ec-9b14-230a7f97624a.png">

I think the issue might be related to your project setup.

**Comment by aregio** [comment]
When clicking on the [Snack](https://snack.expo.dev/?name=BottomNavigation&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fbottom-navigation.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20BottomNavigation%2C%20Text%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MusicRoute%20%3D%20()%20%3D%3E%20%3CText%3EMusic%3C%2FText%3E%3B%0A%0Aconst%20AlbumsRoute%20%3D%20()%20%3D%3E%20%3CText%3EAlbums%3C%2FText%3E%3B%0A%0Aconst%20RecentsRoute%20%3D%20()%20%3D%3E%20%3CText%3ERecents%3C%2FText%3E%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bindex%2C%20setIndex%5D%20%3D%20React.useState(0)%3B%0A%20%20const%20%5Broutes%5D%20%3D%20React.useState(%5B%0A%20%20%20%20%7B%20key%3A%20%27music%27%2C%20title%3A%20%27Favorites%27%2C%20focusedIcon%3A%20%27heart%27%2C%20unfocusedIcon%3A%20%27heart-outline%27%7D%2C%0A%20%20%20%20%7B%20key%3A%20%27albums%27%2C%20title%3A%20%27Albums%27%2C%20focusedIcon%3A%20%27album%27%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20%27recents%27%2C%20title%3A%20%27Recents%27%2C%20focusedIcon%3A%20%27history%27%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20%27notifications%27%2C%20title%3A%20%27Notifications%27%2C%20focusedIcon%3A%20%27bell%27%2C%20unfocusedIcon%3A%20%27bell-outline%27%20%7D%2C%0A%20%20%5D)%3B%0A%0A%20%20const%20renderScene%20%3D%20BottomNavigation.SceneMap(%7B%0A%20%20%20%20music%3A%20MusicRoute%2C%0A%20%20%20%20albums%3A%20AlbumsRoute%2C%0A%20%20%20%20recents%3A%20RecentsRoute%2C%0A%20%20%7D)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CBottomNavigation%0A%20%20%20%20%20%20navigationState%3D%7B%7B%20index%2C%20routes%20%7D%7D%0A%20%20%20%20%20%20onIndexChange%3D%7BsetIndex%7D%0A%20%20%20%20%20%20renderScene%3D%7BrenderScene%7D%0A%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper) example provided by the [documentation](https://callstack.github.io/react-native-paper/bottom-navigation.html) I have the same issue. Icons are not getting displayed.

**Comment by raajnadar** [comment]
When you open the snack it will ask you to add the dependencies

`package.json (3:5) 'react-native-paper' requires peer-dependency '@expo/vector-icons'.`

Check the very bottom of the screen

**Comment by lukewalczak** [comment]
The commit: https://github.com/callstack/react-native-paper/commit/ec6ed76c46d1fdd728a9942d805366a34d12d1e9 updating the snack link generativity should fix the problem.
