### ISSUE TITLE
Customised Text variant in theme

### ISSUE THREAD

**Issue by DavidZhongSyd** [callstack/react-native-paper#3304]
Version: 
"react-native": "0.68.2",
"react-native-paper": "5.0.0-rc.3",
"react-native-vector-icons": "^9.2.0",

May I ask how to define the customised variant in theme for Text?

eg.

```
        <Text variant="displayCustomizedLarge">
          ABCDEFGHIJKLM
        </Text>
```

**Comment by lukewalczak** [comment]
Hey @DavidZhongSyd, you can override the text variant by `theme` prop, please check the following [snack](https://snack.expo.dev/Or11_QnTA)
