### ISSUE TITLE
Font Family cannot be recognised in theme

### ISSUE THREAD

**Issue by DavidZhongSyd** [callstack/react-native-paper#3305]
Version:
"react-native": "0.68.2",
"react-native-paper": "5.0.0-rc.3",
"react-native-vector-icons": "^9.2.0",

Problem: the fontFamily in the 
`<Text variant="displayLarge" theme={{ typescale: { displayLarge: { fontSize: 30, fontFamily: 'HelveticaNeue-Thin' },},}}> `does not take effect while the  `<Text style={theme.fonts.thin}>` does works as expected.

https://snack.expo.dev/@wztrustgrid/fontfamilyintheme

```
import { StyleSheet, View } from 'react-native';
import {
  configureFonts,
  Provider as PaperProvider,
  MD3LightTheme as DefaultTheme,
  Text,
} from 'react-native-paper';

const fontConfig = {
  web: {
    thin: {
      fontFamily: 'HelveticaNeue-Thin',
      fontSize: 30,
    },
  },
  ios: {
    thin: {
      fontFamily: 'HelveticaNeue-Thin',
      fontSize: 30,
    },
  },
  android: {
    thin: {
      fontFamily: 'HelveticaNeue-Thin',
      fontSize: 30,
    },
  },
};

const theme = {
  ...DefaultTheme,
  fonts: configureFonts(fontConfig),
};

export default function App() {
  return (
    <PaperProvider
      theme={theme}
    >
      <View style={styles.container}>
        {/* Display correct font */}
        <Text style={theme.fonts.thin}>
          ABCDEFGHIJKLM NOPQRSTUVWXYZ abcdefghijklm nopqrstuvwxyz 1234567890
        </Text>

        {/* Display incorrect font */}
        <Text
          variant="displayLarge"
          theme={{
            typescale: {
              displayLarge: { fontSize: 30, fontFamily: 'HelveticaNeue-Thin' },
            },
          }}
        >
          ABCDEFGHIJKLM NOPQRSTUVWXYZ abcdefghijklm nopqrstuvwxyz 1234567890
        </Text>
      </View>
    </PaperProvider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },

});
```

**Comment by lukewalczak** [comment]
Hey @DavidZhongSyd, could you please check if it doesn't work on both mobile platforms or only on iOS?

**Comment by DavidZhongSyd** [comment]
Please see the snack expo

https://snack.expo.dev/@wztrustgrid/fontfamilyintheme

**Comment by DavidZhongSyd** [comment]
Hi @lukewalczak, the font difference are obvious in Web and IOS. The first line is in HelveticaNeue-Thin. The second line is wrong font

However, in android, the fonts in both lines are all wrong.

**Comment by DavidZhongSyd** [comment]
@lukewalczak, why the fontFamily only apply in android?

in react-native-paper source code
src/component/Typography/Text.tsx (Line 102)

```
            ...(Platform.OS === 'android' && { fontFamily }),
            fontSize,
            fontWeight,
            lineHeight,
            letterSpacing,
            color: theme.colors.onSurface,
          },
```

**Comment by bombillazo** [comment]
I'm trying out V5 as well and the whole Text Components lib is riddled with this (in addition to that weird conditional to only apply custom fonts on android):
```
const font = !isV3 ? theme.fonts.regular : {};
```
So all TextInputs, Serachbars, etc that don't directly use RNP Text component will also not be using custom fonts.

I believe the simplest solution is to keep the M2 fonts prop available for use to override the theme-wide font family since at the moment, custom fonts are being applied to Text with variant classes.

**Comment by lukewalczak** [comment]
I will be investigating that issue in the nearest future, and will update you here about the result.

**Comment by bombillazo** [comment]
Thanks Luke!

`AppBarContent` seems to be doing something more sensible, leveraging the existing variants:

```js
 ...(isV3
    ? theme.typescale[variant]
    : Platform.OS === 'ios'
    ? theme.fonts.regular
    : theme.fonts.medium),
},
```

**Comment by lukewalczak** [comment]
Provided a PR which hopefully will fix the issue: https://github.com/callstack/react-native-paper/pull/3351
