### ISSUE TITLE
The example doesn't run on Android

### ISSUE THREAD

**Issue by jessebrennan** [callstack/react-native-paper#3306]
To reproduce the issue:
- click on the [link in the README](https://github.com/callstack/react-native-paper#try-it-out) to the [example app](https://snack.expo.dev/@react-native-paper/github.com-callstack-react-native-paper:example) 
- Notice all of the "problems" listed in the log bellow.
- Click Android in the preview, next to "web". This should fail.

I've found the example here to be extremely helpful, filling in when the documentation is lacking. It seems like they aren't being updated though? Is there a way to republish them with updated dependencies etc.?

**Comment by lukewalczak** [comment]
Hey @jessebrennan, example app on the snack should be updated.

**Comment by jessebrennan** [comment]
@lukewalczak thanks for the prompt action. I noticed one other spot where the link needed to be updated so I made a PR: https://github.com/callstack/react-native-paper/pull/3308. Can you take a look?

**Comment by lukewalczak** [comment]
Done, thanks!
