### ISSUE TITLE
Floating action button doesn't sink in demo app web view

### ISSUE THREAD

**Issue by jessebrennan** [callstack/react-native-paper#3309]
### Current behaviour

Floating action button doesn't sink when scrolling down in demo app from web view

### Expected behaviour

I expect the button to sink when scrolling down

### Code sample

https://snack.expo.dev/@react-native-paper/react-native-paper-example_v5?platform=web

### Screenshots (if applicable)

https://user-images.githubusercontent.com/10734740/184025420-86a8cff8-14d0-46dd-bf69-cde05b8b0be4.mov

### What have you tried

Just what's above

### Your Environment

Just what's in the sample snack

**Comment by lukewalczak** [comment]
Fixed on the snack.

**Comment by jessebrennan** [comment]
I'm seeing different, but still weird behavior on the example app


https://user-images.githubusercontent.com/10734740/184240507-09ad5990-6616-458e-b434-9f0a7b6c73b7.mov

**Comment by lukewalczak** [comment]
Could you please then correct the example and share the snack, so we will be able to upload it?

**Comment by jessebrennan** [comment]
@lukewalczak I'm kind of a noob here so it would take me quite a bit of effort to figure all this out and I don't think I have the time at this point.

Probably I'd look at an example to see how to do it correctly, but ironically it's the example that's broken 😂.

Sorry I'm not more help.

**Comment by jessebrennan** [comment]
I'm kind of a noob here so it would take me quite a bit of effort to figure all this out and I don't think I have the time at this point.

Probably I'd look at an example to see how to do it correctly, but ironically it's the example that's broken 😂.

Sorry I'm not more help.
