### ISSUE TITLE
Expo 46 starts with warnings with rc4 and react-native-web

### ISSUE THREAD

**Issue by dohomi** [callstack/react-native-paper#3310]
### Current behaviour

Console warn on Expo and react-native-paper on rc5

### Expected behaviour

No console warn

### Code sample

[
](https://snack.expo.dev/8rv6CWGDw)

### Screenshots (if applicable)
<img width="864" alt="Screenshot 2022-08-11 at 12 24 33" src="https://user-images.githubusercontent.com/489221/184064583-2f232009-f19f-4175-8c21-65d393206b61.png">

### What have you tried

Just install Expo starter and add rc4 of this repo.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 
| react-native          | 69.1
| react-native-paper    | 5.0.0-rc.4
| node                  | 16.x
| npm or yarn           | 7.x
| expo sdk              | 46.0.3

**Comment by lukewalczak** [comment]
Fixed via commit:https://github.com/callstack/react-native-paper/commit/4adda3551946aafc3194e95877ff11285ced4958. Will be released in `5.0.0-rc.5`
