### ISSUE TITLE
wrong color mapped to TextInput label in flat non-focused mode [v5.0.0-rc.4]

### ISSUE THREAD

**Issue by skosyi** [callstack/react-native-paper#3312]
observe:
TextInput label color in flat mode (outlined mode is fine) mapped to theme.colors.primary

expected:
TextInput label color in flat mode mapped to theme.colors.onSurfaceVariant

https://snack.expo.dev/Fj0K2dFFl

**Comment by lukewalczak** [comment]
Hey @skosyi, thanks for the feedback, I will correct the flat input label color.

**Comment by lukewalczak** [comment]
Will be released in `rc.5`
