### ISSUE TITLE
ActivityIndicator not working in 5.0.0-rc.4

### ISSUE THREAD

**Issue by cervisebas** [callstack/react-native-paper#3313]
### Current behaviour

Mounting the component displays an error message.
### Expected behaviour

I expected the component to display correctly.
### Code sample

`<View style={{ flex: 3, alignItems: 'center', justifyContent: 'center' }}> <ActivityIndicator animating /> </View>`
### Screenshots

![image](https://user-images.githubusercontent.com/52644268/184503736-a753322c-5b4f-4213-8b85-e4fde7c11fe3.png)

### Your Environment

| software              | version
| --------------------- | -------
| android        | 11
| react-native          | 0.69.3
| react-native-paper    | 5.0.0-rc.4
| react-native-vector-icons   |  ^9.2.0
| node                  |  16.15.1
| yarn           | 1.22.19

**Comment by lukewalczak** [comment]
Hey @cervisebas, I copied your code snippet into the expo snack and cannot see any issues. https://snack.expo.dev/RaxMMhxDH

**Comment by lukewalczak** [comment]
If you will be able to attach the snack or minimal repo presenting the problem, feel free to reopen the issue.
