### ISSUE TITLE
Theming documentation needs small update

### ISSUE THREAD

**Issue by matthewlese** [callstack/react-native-paper#3314]
### Current behaviour

Importing `MD3LightTheme` as suggested in the documentation throws an error that the module is undefined.  It appears the package has been updated and it is now imported just as `DefaultTheme` without an alias.

### Expected behaviour

Importing the theme allows for overriding the defaults after passing it as a prop to the Provider.

### Code sample

`import { MD3LightTheme, Provider as PaperProvider } from 'react-native-paper';` throws error

`import { DefaultTheme, Provider as PaperProvider } from 'react-native-paper';` worka

**Comment by BenJeau** [comment]
Which `react-native-paper` version do you have installed? For some reasons the docs is for the release candidate of v5, if you are using v4, take a look at https://callstack.github.io/react-native-paper/4.0

**Comment by lukewalczak** [comment]
Hello @matthewlese, as @BenJeau mentioned, the default documentation is for the v5 RC, if you are looking for the documentation related to the latest stable paper version v4, please check the link mentioned above.

**Comment by lukewalczak** [comment]
Updated docs banner and instructions in the commit: https://github.com/callstack/react-native-paper/commit/ed0f7d72dd0d0e1b781753ed0f384f410aa65759

**Comment by matthewlese** [comment]
Thanks @BenJeau and @lukewalczak
