### ISSUE TITLE
Spelling mistake in Switch component props

### ISSUE THREAD

**Issue by psk-dreampay** [callstack/react-native-paper#3319]
### Current behaviour

Currently the props for the Switch component are exported as SwichProps

### Expected behaviour

Props for Switch component should be exported as SwitchProps where the letter **t** is missing

### Code sample

`import { Switch, SwichProps } from 'react-native-paper';`

### Screenshots (if applicable)

<img width="585" alt="Screenshot 2022-08-16 at 6 36 55 PM" src="https://user-images.githubusercontent.com/80046816/184886989-a0be1620-df5c-4e1d-abe7-b8d64ebcbbc5.png">

No code repro is required in this case

**Comment by psk-dreampay** [comment]
react-native: 0.67.3
react-native-paper: 5.0.0-rc.4
react-native-vector-icons: 9.2.0

**Comment by lukewalczak** [comment]
Hey @psk-dreampay, nice catch! Fixed in the following [commit](https://github.com/callstack/react-native-paper/commit/12b29d1b039b6c259019d27219231928801d0b4d). Will be released in the next RC.

**Comment by psk-dreampay** [comment]
Thanks a lot @lukewalczak
