### ISSUE TITLE
Custom Fonts with Expo

### ISSUE THREAD

**Issue by sidnetopia** [callstack/react-native-paper#3325]
Hello, 

I'm trying to load my custom fonts via Expo according to their [documentation](https://docs.expo.dev/guides/using-custom-fonts/) (please see code below).

```
import * as Font from 'expo-font';

await Font.loadAsync({
    ...Ionicons.font,
    inter: require('../../assets/fonts/Inter-Regular.ttf'),
    'inter-medium': require('../../assets/fonts/Inter-Medium.ttf'),
    'inter-light': require('../../assets/fonts/Inter-Light.ttf'),
    'inter-thin': require('../../assets/fonts/Inter-Thin.ttf'),
});
```

Then I tried to used it as custom fonts as stated [here](https://callstack.github.io/react-native-paper/fonts.html).

```
import { Theme } from 'react-native-paper/lib/typescript/types';
import { configureFonts, DarkTheme, DefaultTheme } from 'react-native-paper';

import useColorScheme from 'hooks/useColorScheme';
import Colors from 'constants/Colors';

const fontConfig = {
    web: {
        regular: {
            fontFamily: 'inter',
            fontWeight: 'normal',
        },
        medium: {
            fontFamily: 'inter-medium',
            fontWeight: 'normal',
        },
        light: {
            fontFamily: 'inter-light',
            fontWeight: 'normal',
        },
        thin: {
            fontFamily: 'inter-thin',
            fontWeight: 'normal',
        },
    },
    ios: {
        regular: {
            fontFamily: 'inter',
            fontWeight: 'normal',
        },
        medium: {
            fontFamily: 'inter-medium',
            fontWeight: 'normal',
        },
        light: {
            fontFamily: 'inter-light',
            fontWeight: 'normal',
        },
        thin: {
            fontFamily: 'inter-thin',
            fontWeight: 'normal',
        },
    },
    android: {
        regular: {
            fontFamily: 'inter',
            fontWeight: 'normal',
        },
        medium: {
            fontFamily: 'inter-medium',
            fontWeight: 'normal',
        },
        light: {
            fontFamily: 'inter-light',
            fontWeight: 'normal',
        },
        thin: {
            fontFamily: 'inter-thin',
            fontWeight: 'normal',
        },
    },
};

export function setupTheme(): Theme {
    const colorScheme = useColorScheme();
    let theme = colorScheme === 'dark' ? DarkTheme : DefaultTheme;
    const colors = colorScheme === 'dark' ? Colors.dark : Colors.light;

    theme = {
        ...theme,
        roundness: 5,
        colors: {
            ...theme.colors,
            ...colors,
        },
        fonts: configureFonts(fontConfig),
    };

    return theme;
}

```

When I tried to load a sample component, the text doesn't show up. As an example, below is a supposed to be text input with email and password placeholders.
![image](https://user-images.githubusercontent.com/36142076/185753197-ca0d93bd-2c54-41f3-95f5-12af7f5ae488.png)

I tried loading the fonts as stated in the [documentation](https://callstack.github.io/react-native-paper/fonts.html), with all the react native link and matching of filenames but nothing works out.

What should be my implementation in using custom fonts with React Native Paper and Expo side-by-side?

**Comment by sidnetopia** [comment]
Maybe it's because expo project doesn't have this folder (`android/app/src/main/assets/fonts`)?

**Comment by lukewalczak** [comment]
> The first thing you need is a font file. For the purpose of a working example, we are going to use Inter Black from the free and open source [Inter font family](https://rsms.me/inter/) by Rasmus Anderson. A common convention in Expo apps is to put your fonts in an ./assets/fonts directory, but you can put them anywhere you like.

Did you follow that part and put fonts into the appropriate directory?

**Comment by sidnetopia** [comment]
Yes, I followed what's in the documentation but still it doesn't work.

**Comment by lukewalczak** [comment]
Is it related to the `react-native-paper` library itself? Are you able to display custom fonts in another component from `react-native` e.g. `Text` or `TextInput`?

**Comment by sidnetopia** [comment]
> Are you able to display custom fonts in another component from react-native e.g. Text or TextInput?
Yes

**Comment by lukewalczak** [comment]
Could you please share the snack, presenting the issue?

**Comment by R4Y-repo** [comment]
i got the same issue but for `"react-native-paper": "4.12.4"` @lukewalczak there's no documentation that explains how to do the setup for expo apps

**Comment by kdowswell** [comment]
I'm having issues with an Expo project as well. the PaperProvider using MD3DarkTheme does not change component backgroundColor to dark. Any suggestions on using PaperProvider with custom theming options with Expo project would be greatly appreciated!

**Comment by mkhoussid** [comment]
There's an example on how to do this properly with Typescript here: https://snack.expo.dev/@react-native-paper/font-styles-variants

**Comment by Harsh-Tuwar** [comment]
@mkhoussid you are a life saver dude ❤️

**Comment by TaylorFoster-Informulate** [comment]
@mkhoussid Followed that example and it seemed way too easy (nothing is react native is every easy), got fonts working perfect. Whats the catch? lol
