### ISSUE TITLE
Problem with Text nesting with textAlign on ios

### ISSUE THREAD

**Issue by szado** [callstack/react-native-paper#3327]
### Current behaviour
On ios, `textAlign: center` in parent component is not working when Text component contains another Text.
On Android and web it works as expected, but also it works on ios when using react-native Text.

### Expected behaviour
Text should be centered.

### Code sample

```js
<Text style={{textAlign: 'center'}}>
foo
<Text>bar</Text>
</Text>
```

### Your Environment

I'm using MD3LightTheme.

| software              | version
| --------------------- | -------
| ios or android        | ios 15
| react-native-paper    | v5
| expo sdk              | yes, latest

**Comment by lukewalczak** [comment]
Hey @szado, I've used your code snippet and compared `Text` from `react-native` and `react-native-paper` on the following snack: https://snack.expo.dev/UXxlrxwRs and the result is the same.

**Comment by szado** [comment]
@lukewalczak You're right, after debugging I noticed the problem is occurring when first child is a Text component. Take a look: https://snack.expo.dev/UmNE0KU9v

**Comment by lukewalczak** [comment]
I've investigated the issue and looks like there is a problem when creating a wrapper around `Text` from `react-native` which has pre-defined _textAlign_ property (added due to RTL functionality). I cannot override that property, however, the style is appropriately passed to the _wrapper_. Please check the following snack: https://snack.expo.dev/bEVqmreJ_

**Comment by lukewalczak** [comment]
Looks like nested `Text` also has to receive `textAlign: 'center'`.

**Comment by szado** [comment]
On android and web it works so this property is probably passed correctly. Maybe this is a problem with layouts engine on ios (so react-native related)?
Temporary solution is to put e.g. whitespace before the Text component, but it is ugly.

**Comment by lukewalczak** [comment]
> Looks like nested Text also has to receive textAlign: 'center'.
 
 You can pass `textAlign` to the nested child:
 ``` 
      <Text style={{ textAlign: 'center' }}>
        <Text style={{ textAlign: 'center' }}>bar</Text>
        react-native-paper text fooo
      </Text>
 ```
