### ISSUE TITLE
BottomNavigation｜How to pass props in renderScene?

### ISSUE THREAD

**Issue by momolly1024** [callstack/react-native-paper#3332]
Hi, Dear developers,
If I want to add a props to components in BottomNavigation,
How can I do?

Some code like this : 
```
const MyComponent = () => {
  const [index, setIndex] = React.useState(0);
  const [routes] = React.useState([
    {key: 'music', title: 'Music', icon: 'gift'},
    {key: 'recents', title: 'Recents', icon: 'history'},
    {key: 'todo', title: 'TodoList', icon: 'github'},
    {key: 'albums', title: 'Albums', icon: 'lock'},
  ]);

  const renderScene = BottomNavigation.SceneMap({
    music: MusicRoute,
    recents: RecentsRoute,
    todo: TodoList,
    albums: AlbumsRoute,
  });

  return (
    <BottomNavigation
      navigationState={{index, routes}}
      onIndexChange={setIndex}
      renderScene={renderScene}
    />
  );
};
```

I have try to add directly like this,
but got an error. 

```
  const renderScene = BottomNavigation.SceneMap({
    music: MusicRoute,
    recents: RecentsRoute,
    **todo: <TodoList test={test}/>,**
    albums: AlbumsRoute,
  });
```

So I open a issue to ask

Thank you very much!

**Comment by lukewalczak** [comment]
Hey @momolly1024, please check the following [snack](https://snack.expo.dev/XPybJQB72), I hope it will help you.

**Comment by MatteoBuffo** [comment]
> Hey @momolly1024, please check the following [snack](https://snack.expo.dev/XPybJQB72), I hope it will help you.

Hello @lukewalczak. I'm working with BottomNavigation and I'm facing an issue. Please check [this Snack](https://snack.expo.dev/@mbuffo/bottomnavigation) out, it's a fork of your last reply.

Steps:
- go to Notifications tab;
- press the "Notification - Add" button;
- see the relative counter increase;
- press the "MyComponent - Add" button;
- see the Notification counter set to 0 again.

Is there a way to prevent this behaviour? One solution may be lifting the state of Notification to MyComponent, but I would like to know if there are some alternatives.
