### ISSUE TITLE
Discussion: Margins

### ISSUE THREAD

**Issue by gawrysiak** [callstack/react-native-paper#334]
It's hard to call it a bug, but I'd like to ask you for your opinion on the subject. I've noticed that some of the components (`Card`, `Button`, `SearchBar`, `Checkbox`, `RadioButton`) are using horizontal margins by default, while other aren't. For `Card`, `Button`, `SearchBar` the horizontal margin is 4, while for `Checkbox`, `RadioButton` it's 6-8.

### Current behaviour

When using mixed components within a single view, the margins aren't equal. It forces to either drop the container padding and add margins to the no-margin components or try getting all the others zeroed. See the screenshots for examples.

### Expected behavior

Normally I'd expect all the components to work within my container padding. Personally, I'd keep all of them zeroed and control it with a container padding.

An extra idea here is to create `Container` and `ScrollContainer` components which will extend the basic `View` and `ScrollView` in order to **support the dark theme** & optional container padding. So far the extra code is getting repeated for each component of the Expo app. It would be handy for any other app as well. Sample use cases could be:

No padding image:
```
<Container>
  <Image source={require('./img.png')} />
</Container>
```

Padded contents (padding 8):
```
<Container padded>
  <Paragraph>The Paragraph margin/padding is now even with the Card.</Paragraph>
  <Card>
    <Title>Example</Title>
  </Card>
</Container>
```

### Screenshots

Current behavior:
![screen shot 2018-04-20 at 22 36 42](https://user-images.githubusercontent.com/7827311/39073306-a3a52de0-44ed-11e8-8dd0-d7f51ac32274.png)

Expected behavior (not sure about the checkboxes):
![screen shot 2018-04-20 at 22 36 03](https://user-images.githubusercontent.com/7827311/39073328-b4a49b62-44ed-11e8-94ad-a60cfaa71ee5.png)

### What have you tried

Using extra styling works, but the behavior feels inconsistent.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | all
| react-native          | ~0.54.4
| react-native-paper    | 1.4.0
| node                  | 8.9.1
| npm or yarn           | yarn 1.3.2

**Comment by satya164** [comment]
>  I'd keep all of them zeroed and control it with a container padding.

We need margins by default for components like Button so that their drop shadow is visible. Otherwise it'll get cut off and users will always have to provide a margin.

I think it'll be better to have a consistent margin by default for elements like Button, TextInput, FAB etc. so they always line-up properly and you don't have to add the margins yourself.

However, since this will be a breaking change, I think we should do it in 2.0 (#350).

> An extra idea here is to create Container and ScrollContainer components

Yeah, we also want a `Container` component with support for dark theme and a default padding of `4`. `ScrollContainer` is unnecessary since you can just nest the `Container` inside `ScrollView`.

**Comment by gawrysiak** [comment]
Shadows is a fair point. Although from the user point of view you don't align elements like Paragraph to TextInput's shadow, you want it to be aligned with the actual component. The issues I've met is on some of the pages I already had a container and several components placed and then Buttons indentation went even deeper than that. I ended up customizing all the margin=4 components to basically do the same without the margins. This way I was able to make it more predictable. The current margins behavior is not exposed/described, this means you have to go wrong first and adjust before you make it right. This affects general user experience. Maybe it would be possible to make it better with the docs. I really like how the material guidelines are handling all the pixel descriptions, e.g:
![components-chips-contact-keyline1](https://user-images.githubusercontent.com/7827311/39674499-243c87ee-514d-11e8-9f25-28a896fbc42e.png)
Good news with the 2.0 plans :+1:

**Comment by gawrysiak** [comment]
With the new guidelines, it seems like the shadows should be rather elevation-based. See the card example:

![screen shot 2018-05-10 at 15 26 57](https://user-images.githubusercontent.com/7827311/39871944-b622db92-5466-11e8-9a29-6609e7bd8275.png)

Do you have any new thoughts on the topic?

**Comment by satya164** [comment]
> it seems like the shadows should be rather elevation-based

They already are. But we might need to change the default elevations.
