### ISSUE TITLE
Why 'TextInput' display incorrect and color on Samsung Note.

### ISSUE THREAD

**Issue by anupong-s** [callstack/react-native-paper#3344]
Why 'TextInput' display incorrect and color on Samsung Note (Real Device).
What should I do?

react-native: "0.69.1"
react-native-paper: "^5.0.0-rc.3"
react-native-vector-icons: "^9.2.0"

As below picture, Run on Samsung Note 9 (Android 10 - Real Device)

![286](https://user-images.githubusercontent.com/1306060/187877111-10ed96a4-91ef-4e32-86f5-f871da4eddc9.jpg)

As below picture, Run on Samsung A52 (Android 12  Real Device)

![324794](https://user-images.githubusercontent.com/1306060/187877325-523450f5-fca8-429e-973d-b203e1e30b93.jpg)

**Comment by anupong-s** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native` (found: `0.69.1`, latest: `0.69.5`)
> * `react-native-paper` (found: `5.0.0-rc.3`, latest: `4.12.4`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Still not working.

**Comment by lukewalczak** [comment]
Hey @anupong-s, could you please reproduce the same issue on the snack and share the link with us? Also it will be awesome if you can do some initial investigation since you have an access to both devices.

**Comment by anupong-s** [comment]
Hello, @lukewalczak
My device is Samsung Note 10 (Android version 10)
I try to run on emulator with android Q (version 10) but it display correct.
I don't know how to reproduce on emulator.
I guess, it problem all model on Samsung Note (real device).

**Comment by lukewalczak** [comment]
Are you able to provide the code sample which you are using when facing the issue?

**Comment by lukewalczak** [comment]
Could you please try to install `react-native-paper` in version `5.0.0-rc.5`?

**Comment by anupong-s** [comment]
> 

Hi @lukewalczak,
I already try to install version 5.0.0-rc.5 but still not working.

1. TextInput: type password but text not hidden.
2. Text color display incorrect.

![828248](https://user-images.githubusercontent.com/1306060/188585200-0c7347ba-91a8-4ea1-816a-8247c1424b09.jpg)

**Comment by raajnadar** [comment]
There is nothing called type = password in react native you need to use this prop https://reactnative.dev/docs/textinput#securetextentry

**Comment by Aycom366** [comment]
I'm having this issue right now on my Redmi note 11.
It's meant to be black but instead I'm seeing a grayish color...
