### ISSUE TITLE
Importing SegmentedButtons throws error (v5.0.0-rc.4)

### ISSUE THREAD

**Issue by matthewlese** [callstack/react-native-paper#3345]
### Current behaviour

Navigating to Screen that imports `SegmentedButtons` throws error:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

### Expected behaviour

`SegmentedButtons` component should be usable on this v5 release candidate

### Code sample

```
import { SegmentedButtons } from 'react-native-paper';
...
        <SegmentedButtons
          value={form.buildType}
          onValueChange={setBuildType}
          buttons={[
            {
              value: '...',
              label: '...',
            },
            ...
          ]}
        />

```

### What have you tried

Tried: 
deleteing package-lock.json, `npm uninstall`, `npm install react-native-paper@5.0.0-rc.4`

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          |  0.69.3
| react-native-paper    | 5.0.0-rc.4
| node                  | v18.2.0
| npm or yarn           | npm 8.9.0

**Comment by lukewalczak** [comment]
Hey @matthewlese, Segmented Button component was merged, however it's not released yet (it will be released most likely tomorrow or Monday).

**Comment by matthewlese** [comment]
ok, sounds great @lukewalczak !

**Comment by lukewalczak** [comment]
Hey @matthewlese, `5.0.0-rc.5` has been released.
