### ISSUE TITLE
Button in React Native Maps Callout without Title on Android

### ISSUE THREAD

**Issue by danieldanielecki** [callstack/react-native-paper#3347]
### Current behaviour

The title is not showing on `Android` when `React Native Paper`'s `<Button />` element is nested into `React Native Maps`'s `<Callout />`. The problem does **not** occur on `iOS` simulators and devices, just on `Android` simulators and devices.

### Expected behaviour

The title should be shown, `react-native`'s `<Button />` works as expected and the title is shown.

#### `react-native`'s `<Button />`
```
import { Button } from 'react-native';
...
<Button
  title="Press me"
  onPress={() => Alert.alert('Simple Button pressed')}
/>
```

#### `React Native Paper`'s `<Button />`

```
import { Button } from 'react-native-paper';
...
<Button icon="camera" mode="contained" onPress={() => console.log('Pressed')}>
  Press me
</Button>
```

#### `react-native`'s `<Button />`

![Screenshot_1662314075](https://user-images.githubusercontent.com/12736263/188327980-ca7e3a2c-393c-453e-b5e9-645ca0ac1ef0.png)

#### `React Native Paper`'s `<Button />`
![Screenshot_1662315630](https://user-images.githubusercontent.com/12736263/188327982-6b5f3e5d-05b7-41f3-8524-982546a19f48.png)

### What have you tried

Running code samples in simulators and my application on real devices. The solution to fix the problem in my app I've committed in https://github.com/tamotam-com/tamotam-app/commit/81fabea7e821ddbfea636e6a6ee4684a615bfc63, but I'm pretty sure the code shouldn't be depended on platform.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | `android`
| react-native          | `0.64.3`
| react-native-paper    | `^4.9.2`
| node                  | `v16.15.0`
| npm or yarn           | `npm`
| expo sdk              | `6.0.1`

**Comment by lukewalczak** [comment]
Hey @danieldanielecki, are you able to provide basic repro e.g. on snack, so we can have the repro sample on which we can investigate the issue and test? Can you also try the latest stable version?
