### ISSUE TITLE
Not possible to change ToolbarAction icon color

### ISSUE THREAD

**Issue by vladikoff** [callstack/react-native-paper#335]
### Current behaviour

Currently it's not possible to match the color of text with the ToolbarAction icon color.

### Expected behaviour

Match icon with text color

### Code sample

the code from: https://github.com/callstack/react-native-paper/blob/91bf179df0d68b60af4095c9a06c98c9998542e0/src/components/Toolbar/ToolbarAction.js#L37

```js
   const iconColor = dark
      ? white
      : color(black)
          .alpha(0.54)
          .rgb()
          .string();
    const rippleColor = color(iconColor)
      .alpha(0.32)
      .rgb()
      .string();
```

### Screenshots (if applicable)

Example to match blue of the Title with the menu icon: 
![image](https://user-images.githubusercontent.com/128755/39079009-bf85ef8e-44e0-11e8-9fca-2accec3067a6.png)

### Your Environment

| software              | version
| --------------------- | -------
| android        | 7,8, etc
| react-native          | 0.54
| react-native-paper    | ^1.2.5
| node                  | 8
| npm or yarn           | 5

**Comment by satya164** [comment]
We should accept a `color` prop. Wanna send a PR?
