### ISSUE TITLE
How to vertically center the right (and left) element of a ListItem?

### ISSUE THREAD

**Issue by MatteoBuffo** [callstack/react-native-paper#3353]
Hi!

I have a List made of basic ListItems and I would like to vertically center both the left and the right element of each item.

As you can see from the screenshot, the left element actually is vertically aligned because it is larger (size={40}) than the right one (default size). The right one, instead, is misaligned.

![listitem_verticalalign](https://user-images.githubusercontent.com/56068232/188461014-c84f234b-8820-4104-ad58-91dfc8eb33d6.png)

The same thing happens when I have a right element that is larger than the left one.

Any hints? I tried passing style={{verticalAlign:"middle"}} to both elements but no luck.

[Check out the Snack example](https://snack.expo.dev/@mbuffo/8eaeec)

Thanks

**Comment by lukewalczak** [comment]
Hey @MatteoBuffo, you can add `style={{ alignSelf: 'center' }}` to the right icon.

**Comment by MatteoBuffo** [comment]
> Hey @MatteoBuffo, you can add `style={{ alignSelf: 'center' }}` to the right icon.

Woah, great! Thank you!
