### ISSUE TITLE
Snack demo not working

### ISSUE THREAD

**Issue by MatteoBuffo** [callstack/react-native-paper#3357]
### Current behaviour

The demo Snack is not working neither on Android or iOS emulator/real devices.

### Expected behaviour

It should work. It only does with the Web version (although the style is all messed up).

### Code sample

Please check [this Snack](https://snack.expo.dev/@react-native-paper/github.com-callstack-react-native-paper:example) out.

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/56068232/188596979-72f9f6c6-b8b2-4578-bcb5-2f4f98c0ef46.png)

### What have you tried

 I updated alle the dependencies (as prompted by the Snack page) and changed the Expo version, but no luck.

### Your Environment

| software              | version
| --------------------- | -------
| Android - iOS       | 12 - 15.1
| react-native          | ?
| react-native-paper    | 4.0.0-alpha.0
| node                  | ?
| npm or yarn           | ?
| expo sdk              | 44, 45 and 46

**Comment by MatteoBuffo** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native-paper` (found: `4.0.0-alpha.0`, latest: `4.12.4`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

The issue persists even after updating the `react-native-paper` dependency.

**Comment by lukewalczak** [comment]
Where did you get the link to this example?

**Comment by MatteoBuffo** [comment]
@lukewalczak [here](https://callstack.github.io/react-native-paper/).

**Comment by lukewalczak** [comment]
Thanks, the mentioned link is outdated (it's based on 4.0.0), I will fix it. The following [link](https://snack.expo.dev/@react-native-paper/react-native-paper-example_v5), presents the latest version.

**Comment by MatteoBuffo** [comment]
Thank you @lukewalczak!
