### ISSUE TITLE
How to access the navigation object from the drawer?

### ISSUE THREAD

**Issue by MatteoBuffo** [callstack/react-native-paper#3359]
Hi! I'm toying with [this snack](https://snack.expo.dev/@mbuffo/53ddc6) (i.e. a fork of [this one](https://snack.expo.dev/@react-native-paper/react-native-paper-example_v5)) and I would like to access the `navigation` object in the `DrawerItems` component.

For example, I edited the `ButtonExample` component and I managed to programmatically toggle the drawer and navigate between screens by passing props to it (please check the `ButtonExample.tsx` file). How can I achieve the same goal in the drawer?

Thanks in advance.

**Comment by lukewalczak** [comment]
I think you can take the advantage of [useNavigation](https://reactnavigation.org/docs/use-navigation/) from `react-navigation`

**Comment by MatteoBuffo** [comment]
@lukewalczak yep, definetely what I needed. Thanks!
