### ISSUE TITLE
Increasing fontSize in labelStyle shifts all text vertically.  Does not allow for center alignment

### ISSUE THREAD

**Issue by byamagata** [callstack/react-native-paper#3361]
### Current behaviour

Modifying the `fontSize` property in the `labelStyle` prop on a button cuts off the text on larger fonts.  Increasing the `height` on the same prop fixes the cut off issue, but then causes issues with text alignment.

### Expected behaviour

The button respects larger font sizes by increasing the height and width automatically to accommodate larger fonts, while still keeping the alignment and justify properties.

### Code sample

[Snack demonstrating the issue](https://snack.expo.dev/FrYXIVyH3)

### Screenshots (if applicable)

Running the snack above gives me this layout: 
![image](https://user-images.githubusercontent.com/26102991/188726721-627536a6-a932-4e64-8c22-29b6ebc6b428.png)

### What have you tried

I have tried:
- manually setting the `justifyContent` and `alignItems` properties on both the labelStyle and the contentStyle
- changing the height of the content and label styles

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |  Android Version 12, One UI version 4.1
| react-native          | 0.69.4
| react-native-paper    | ^5.0.0-rc.4
| node                  | 18.6.0
| npm or yarn           |  npm 8.13.2
| expo sdk              | ~46.0.9

### Other Note

While I did notice this on my machine and my android device, it is easily reproducable through the snack.expo.dev web editor.  I feel that this roots out device specific issues.  (I could be wrong though)

**Comment by lukewalczak** [comment]
Prolly you are missing `linHeight` in the `labelStyle`.

**Comment by byamagata** [comment]
I will try this and get back to you @lukewalczak

**Comment by byamagata** [comment]
@lukewalczak I had no idea about this property.... thank you so much for solving my problem!
