### ISSUE TITLE
Screen-specific BackHandler triggered in any screen

### ISSUE THREAD

**Issue by MatteoBuffo** [callstack/react-native-paper#3364]
Hi! I've defined two BackHandler listeners (by means of the [useBackHandler ](https://github.com/react-native-community/hooks#usebackhandler) hook): the former in the ExampleList screen and the latter in the Button screen. Whenever you click the physical back button (on Android), an alert shows up.

You can try [this snack](https://snack.expo.dev/@mbuffo/react-native-paper-example_v5_navigation_in_drawer) out on an Android device/simulator and verify that the handlers are called correctly. By the way, if you try to edit the code and apply the changes (without reloading the app), the ExampleList handler will be called from any screen. The only way to fix it is reloading the app.

Is there a way to prevent this behaviour? Or should I ignore it since it won't happen in the final result (I guess the reloading can't happen there).

Thanks.

**Comment by lukewalczak** [comment]
Hey @MatteoBuffo, is your question related to the `react-native-paper` library itself?

**Comment by MatteoBuffo** [comment]
Hi @lukewalczak. I've stumbled upon this issue while working with this library, but I guess that the same could happen with a bare RN project set up with `react-navigation`.

**Comment by lukewalczak** [comment]
Hey @MatteoBuffo, based on your answer I'm closing the issue (we are trying to focus mainly on the things related to the library itself).

**Comment by MatteoBuffo** [comment]
Hi @lukewalczak! Sorry, in the end I could find the solution, but forgot to close this issue. Just in case, [this](https://stackoverflow.com/a/72133869) is the way I did it.
