### ISSUE TITLE
Possibility to use specific system font

### ISSUE THREAD

**Issue by eengnr** [callstack/react-native-paper#3365]
**Is your feature request related to a problem? Please describe.**
Currently it seems to be only possible to use custom fonts if they are added as file to an app.
See https://callstack.github.io/react-native-paper/fonts.html

**Describe the solution you'd like**
Would it be possible to e.g. also use Google Sans on a Pixel phone somehow in an app?
The font is available on the system and it's not allowed for an app to integrate it, see https://github.com/flutter/flutter/issues/18266#issuecomment-395482313

Thanks for checking this!

**Comment by lukewalczak** [comment]
Hey @eengnr, as far as I know and understood your problem, it's not possible – the font has to be integrated with the app.
