### ISSUE TITLE
Stacktrace when using animation with progressbar

### ISSUE THREAD

**Issue by alpa-odoo** [callstack/react-native-paper#3366]
Hi guys, does this seem ok to you ?
https://snack.expo.dev/@flaze9/progressbar?name=ProgressBar&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2F4.0%2Fprogress-bar.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20ProgressBar%2C%20Colors%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20(%0A%20%20%3CProgressBar%20progress%3D%7B0.5%7D%20color%3D%7BColors.red800%7D%20%2F%3E%0A)%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper

Because i have issues making it work in my code, the above snack is a minimal example

<img width="1682" alt="Screenshot 2022-09-13 at 21 58 46" src="https://user-images.githubusercontent.com/101560055/189997490-62589899-7614-40c1-8570-1e72c0babaa5.png">

This is what I get in local
Would greatly appreciated some help

**Comment by lukewalczak** [comment]
I think the problem is that your `ProgressBar` with an animated value is wrapped in the regular `View` instead of `Animated.View` in your [app](https://github.com/alexandredepape/chess-recogniser-mobile-app/blob/progress-bar-animation/App.js#L164).

**Comment by lukewalczak** [comment]
> I think the problem is that your ProgressBar with an animated value is wrapped in the regular View instead of Animated.View in your [app](https://github.com/alexandredepape/chess-recogniser-mobile-app/blob/progress-bar-animation/App.js?rgh-link-date=2022-09-15T07%3A17%3A55Z#L164).

Hey @alpa-odoo, did it help you with the issue?

**Comment by lukewalczak** [comment]
so then please try to reproduce it on the fresh react-native project, with the minimum code, required to observe the bug and share the link in the issue, so we can check it.

**Comment by lukewalczak** [comment]
Try to make `ProgressBar` animatable by wrapping component in [createAnimatedComponent](https://reactnative.dev/docs/animated#createanimatedcomponent) and use it then.

```
const AnimatedProgressBar = Animated.createAnimatedComponent(ProgressBar)
```

**Comment by alexandredepape** [comment]
I did:
```js
import { Animated, StyleSheet } from "react-native";
import { ProgressBar } from "react-native-paper";
import { useEffect, useRef } from "react";


export default function App() {
    const progressBarValue = useRef(new Animated.Value(0));
    const AnimatedProgressBar = Animated.createAnimatedComponent(ProgressBar);

    useEffect(() => {
        console.log("progressBarValue", progressBarValue.current);
        Animated.timing(progressBarValue.current, {
            toValue: 1,
            duration: 1000,
            useNativeDriver: true,
        }).start();
    }, []);

    return (
        <Animated.View style={styles.progressBarContainer}>
            <AnimatedProgressBar style={styles.progressBar}
                                 progress={progressBarValue.current}
                                 color={"#9dd4ae"}/>
        </Animated.View>
    )
}

const styles = StyleSheet.create({
    progressBarContainer: {
        flex: 1,
        backgroundColor: "#313845",
        justifyContent: 'center',
        alignItems: 'center',
    },
    progressBar: {
        width: 300,
        // backgroundColor: "white",
        borderRadius: 7.5,
        height: 15,
        margin: 10,

    }
});
```
And I get:
```js
ERROR  Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Context.Consumer`.
    in ProgressBar
    in ThemedComponent (created by withTheme(ProgressBar))
    in withTheme(ProgressBar) (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by App)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
 LOG  progressBarValue 0
```

**Comment by lukewalczak** [comment]
Hey @alexandredepape, did you manage to solve your issue? Unfortunately, atm I don't have much time to help with it and be more involved in it.

**Comment by alexandredepape** [comment]
@lukewalczak I was not able to no, could you take 5 minutes to reproduce this minimal example and try on your end if that works ?

```js
import { Animated, StyleSheet } from "react-native";
import { ProgressBar } from "react-native-paper";
import { useEffect, useRef } from "react";


export default function App() {
    const progressBarValue = useRef(new Animated.Value(0));
    const AnimatedProgressBar = Animated.createAnimatedComponent(ProgressBar);

    useEffect(() => {
        console.log("progressBarValue", progressBarValue.current);
        Animated.timing(progressBarValue.current, {
            toValue: 1,
            duration: 1000,
            useNativeDriver: true,
        }).start();
    }, []);

    return (
        <Animated.View style={styles.progressBarContainer}>
            <AnimatedProgressBar style={styles.progressBar}
                                 progress={progressBarValue.current}
                                 color={"#9dd4ae"}/>
        </Animated.View>
    )
}

const styles = StyleSheet.create({
    progressBarContainer: {
        flex: 1,
        backgroundColor: "#313845",
        justifyContent: 'center',
        alignItems: 'center',
    },
    progressBar: {
        width: 300,
        // backgroundColor: "white",
        borderRadius: 7.5,
        height: 15,
        margin: 10,

    }
});
```

**Comment by lukewalczak** [comment]
We've introduced new property called `animatedValue` https://callstack.github.io/react-native-paper/progress-bar.html#animatedValue. Please check the new [example](https://github.com/callstack/react-native-paper/blob/main/example/src/Examples/ProgressBarExample.tsx#L94-L99), I hope it will help you.

**Comment by amanzrx4** [comment]
@lukewalczak The AnimatedProgressBar example doesn't seem to work in my local environment. I've been trying to get it work since yesterday

**Comment by 17LingShan** [comment]
> We've introduced new property called `animatedValue` https://callstack.github.io/react-native-paper/progress-bar.html#animatedValue. Please check the new [example](https://github.com/callstack/react-native-paper/blob/main/example/src/Examples/ProgressBarExample.tsx#L94-L99), I hope it will help you.

I got the same problem and I fix it with `animatedValue`. Thank for the work of menber! 🎉
