### ISSUE TITLE
[Android Only] Enabling multiline in TextInput without height has the text not centered

### ISSUE THREAD

**Issue by Zeraan** [callstack/react-native-paper#3367]
Using latest React-Native-Paper version (4.12.4), ran across this issue. On android only, if you enable multiline in TextInput, but doesn't specify a height, the text is moved upward vertically a bit, different from the label text:
![Screenshot_20220914_163521](https://user-images.githubusercontent.com/6200715/190275008-f4b72f1b-8ca6-47ec-a6b7-ef9b0a0ffaaf.png)

The textinput field does correctly expand when new lines are added, but it's a bit jarring having the first line be not centered.

**Comment by PunainenAurinko** [comment]
I also experience this issue with TextInput and multiline enabled. On Android the text is not centred. If I remove multiline true, everything is back to normal.
