### ISSUE TITLE
Appbar.Action & Appbar.BackAction color prop doesn't work

### ISSUE THREAD

**Issue by saver711** [callstack/react-native-paper#3368]
### Current behaviour

Appbar.Action & Appbar.BackAction color prop doesn't work

### Expected behaviour

for Appbar.Action & Appbar.BackAction color prop to work

SEE THIS SNACK
https://snack.expo.dev/@ahmedhassan711/color-prop

### What have you tried

some manipulation, but it doesn't work

# Versions
react-native: "0.69.5"
react-native-paper:  "^5.0.0-rc.5"
react-native-vector-icons :  "^9.2.0"

**Comment by saver711** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `react-native`
> * `react-native-paper`
> * `react-native-vector-icons`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

**Comment by lukewalczak** [comment]
@saver711 thanks for reporting the issue, I will investigate the problem.

**Comment by saver711** [comment]
> @lukewalczak 
sorry, i am new to github issues 
if u solved the problem, what should i do to use custom color for Appbar.Action & Appbar.BackAction

**Comment by lukewalczak** [comment]
> sorry, i am new to github issues
if u solved the problem, what should i do to use custom color for Appbar.Action & Appbar.BackAction

I've just provided the PR, which will be merged and released in the next rc version(`5.0.0-rc.6`).

**Comment by error-try-again** [comment]
Had the same issue. Confirming that that moving from 5.0.0-rc.4 to 5.0.0-rc.6 fixed this issue for me.
