### ISSUE TITLE
Text custom font ios not working

### ISSUE THREAD

**Issue by bsubedi26** [callstack/react-native-paper#3369]
Hello, we are using `"react-native-paper": "^5.0.0-rc.5"` and the theme object looks like:
```js
const theme = {
  ...DefaultTheme,
  version: 3,
  typescale: {
    ...DefaultTheme.typescale,
    displayLarge: {
      fontFamily: "ChalkboardSE-Light",
    },
  },
};
```

However, in IOS the `fontFamily` isn't applied for the `<Text>` component. Looking at the code below, is there a reason why `fontFamily` is only set for `android` and not `ios`?
https://github.com/callstack/react-native-paper/blob/main/src/components/Typography/Text.tsx#L102

**Comment by lukewalczak** [comment]
The issue will be fixed by the following PR: https://github.com/callstack/react-native-paper/pull/3351
