### ISSUE TITLE
[5.0.0-rc.5] Searchbar clearIcon should not be visible with empty string value

### ISSUE THREAD

**Issue by dimbslmh** [callstack/react-native-paper#3371]
### Current behaviour
clearIcon is visible with empty string value

### Expected behaviour
clearIcon should not be visible with empty string value

### Code sample
```ts
<Searchbar value="" />
```

### Screenshots (if applicable)
<img width="310" alt="Screen Shot 2022-09-16 at 20 30 08" src="https://user-images.githubusercontent.com/745635/190650612-db4077b5-604e-4594-955e-81ec478ae895.png">

### What have you tried

When the `Searchbar` `value` is false, the `IconButton` `disabled` state is true. This results in the `getIconColor` returning `theme.colors.onSurfaceDisabled`.

https://github.com/callstack/react-native-paper/blob/5efd68ddbed950b8163ff6b58110e05f9885275c/src/components/Searchbar.tsx#L234-L238

https://github.com/callstack/react-native-paper/blob/5efd68ddbed950b8163ff6b58110e05f9885275c/src/components/IconButton/utils.ts#L77-L91

Instead of disabling, an alternative would be to only show the clearIcon when the `Searchbar` `value` is true.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    | 5.0.0-rc.5
| node                  |
| npm or yarn           |
| expo sdk              |

https://snack.expo.dev/SB_vU3_Mx

**Comment by dimbslmh** [comment]
@lukewalczak I have updated the issue.

**Comment by lukewalczak** [comment]
Thanks, I'm able to reproduce it, will fix it in the nearest future.
