### ISSUE TITLE
Bottom Navigation active background visible for multiple screens.

### ISSUE THREAD

**Issue by rakshit087** [callstack/react-native-paper#3372]
### Current behaviour

When I click on a different screen I get Navigated to that page and it's background becomes highlighted, however, the background of the previous tab is still highlighted.

### Expected behaviour

The background of non active tabs should not be highlighted. 

### Code sample

```
import React from 'react';
import {createMaterialBottomTabNavigator} from '@react-navigation/material-bottom-tabs';
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
import {Dashboard} from '../pages/Dashboard';
import {Statistics} from '../pages/Statistics';
import {Settings} from '../pages/Settings';

const Tab = createMaterialBottomTabNavigator();

export const NavigationBar = () => {
  return (
    <Tab.Navigator initialRouteName="Home">
      <Tab.Screen
        name="Home"
        component={Dashboard}
        options={{
          tabBarLabel: 'Home',
          tabBarIcon: ({color}) => (
            <MaterialIcons name="home" color={color} size={26} />
          ),
        }}
      />
      <Tab.Screen
        name="Statistics"
        component={Statistics}
        options={{
          tabBarLabel: 'Statistics',
          tabBarIcon: ({color}) => (
            <MaterialIcons name="bar-chart" color={color} size={26} />
          ),
        }}
      />
      <Tab.Screen
        name="Settings"
        component={Settings}
        options={{
          tabBarLabel: 'Settings',
          tabBarIcon: ({color}) => (
            <MaterialIcons name="settings" color={color} size={26} />
          ),
        }}
      />
    </Tab.Navigator>
  );
};

```

### Screenshots (if applicable)

<img src="https://user-images.githubusercontent.com/50898928/190861121-77b456aa-1792-47fc-9c76-c728e2b36000.gif"  width="300"/>

### What have you tried

I have tried testing the code given in snack, but it didn't worked

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios 16.0
| react-native          | v0.70.0
| react-native-paper    | v5.0.0-rc.5
| node                  | v16.17.0
| npm or yarn           | v1.22.19
| expo sdk              | Using native cli

**Comment by warrior97** [comment]
Exact same issue here with the same versions. Also how do we change the active background color, cause we don't want any.

**Comment by lukewalczak** [comment]
Could you please attach link to the expo snack with the issue reproduction, so it will easier for us to fix it?

**Comment by rakshit087** [comment]
Okay, I will create one.

**Comment by lukewalczak** [comment]
@rakshit087 @warrior97 please provide the version of `react-navigation` as well.

**Comment by abdullahkhan70** [comment]
**I hope it will fix your problem.**

```jsx
import React from 'react';
import {createMaterialBottomTabNavigator} from '@react-navigation/material-bottom-tabs';
import {NavigationContainer} from '@react-navigation/native';
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';

const Tab = createMaterialBottomTabNavigator();

 <NavigationContainer independent={true}>
      <Tab.Navigator
        initialRouteName={screen.HOME}
        activeColor={colors.offWhite}
        inactiveColor={colors.primaryDarkColor}
        barStyle={{backgroundColor: '#694fad', }}
        backBehavior={'history'}>
        <Tab.Screen
          name={screen.HOME}
          component={Home}
          options={({navigation}) => ({
            tabBarColor: colors.homeScreenColor,
            tabBarLabel: tabNames.homeTabName,
            tabBarIcon: ({color, focused}) => (
        <MaterialIcons name="bar-chart" color={color} size={26} />
            ),
          })}
        />
</Tab.Navigator>
</NavigationContainer>
```

**You just need to add a "tabBarColor" props in the "Tab.Screen" component. This will dynamically, change the background color of the selected Bottom Tab item.**

**Comment by prathamrohatgi26** [comment]
> Exact same issue here with the same versions. Also how do we change the active background color, cause we don't want any.

did you find out how to do that?

**Comment by rahultripathi-dev** [comment]
same issue I am facing

**Comment by rahultripathi-dev** [comment]
> ### **I hope it will fix your problem.**
> ```js
> import React from 'react';
> import {createMaterialBottomTabNavigator} from '@react-navigation/material-bottom-tabs';
> import {NavigationContainer} from '@react-navigation/native';
> import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
> 
> const Tab = createMaterialBottomTabNavigator();
> 
>  <NavigationContainer independent={true}>
>       <Tab.Navigator
>         initialRouteName={screen.HOME}
>         activeColor={colors.offWhite}
>         inactiveColor={colors.primaryDarkColor}
>         barStyle={{backgroundColor: '#694fad', }}
>         backBehavior={'history'}>
>         <Tab.Screen
>           name={screen.HOME}
>           component={Home}
>           options={({navigation}) => ({
>             tabBarColor: colors.homeScreenColor,
>             tabBarLabel: tabNames.homeTabName,
>             tabBarIcon: ({color, focused}) => (
>         <MaterialIcons name="bar-chart" color={color} size={26} />
>             ),
>           })}
>         />
> </Tab.Navigator>
> </NavigationContainer>
> ```
> 
> ### **You just need to add a "tabBarColor" props in the "Tab.Screen" component. This will dynamically, change the background color of the selected Bottom Tab item.**
> By the way, which "@react-navigation/material-bottom-tabs" version are you using in your application?

It change tabBarColor but again it overrided by background color passed in Tab.navigator and if will pass transparent then It will still remains same after changing one time when you press any Tab

**Comment by sanaullah-12** [comment]
import { NavigationContainer, TabActions } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import FontAwesome from 'react-native-vector-icons/FontAwesome';
import Ionicns from 'react-native-vector-icons/Ionicons'
import HomeScreen from "./Screens/home-screen";
import FavouriteScreen from "./Screens/favourite-screen";
import DetailScreen from "./Screens/detail-screen";
import SettingScreen from "./Screens/setting-screen";
import ColorScreen from "./Screens/color-screen";



const Tab = createBottomTabNavigator()

 const  Navigation= ()=>{
   return(
   
       
       <NavigationContainer>
       
     <Tab.Navigator   screenOptions={{
      tabBarShowLabel: false,
      tabBarActiveTintColor: '#FF8C71', 
      tabBarInactiveTintColor: 'white',
      tabBarStyle: { width: '90%' , height: 67, backgroundColor: '#040325', borderRadius:7, marginBottom:23,marginLeft:17 }
      
     }}
     >
    
   <Tab.Screen name='Home' component={HomeScreen} options={{
    tabBarIcon:({color,size})=>(
     <FontAwesome name='home' size={size}  color={color}/>
    )
   }}/>
  
 
<Tab.Screen name='Favourite' component={FavouriteScreen} options={{
    tabBarIcon:({color,size})=>(
     <FontAwesome name='heart' size={size}  color={color}/>
    )
   }}/>

<Tab.Screen name='Notification' component={DetailScreen} options={{
    tabBarIcon:({color,size})=>(
     <Ionicns name='notifications' size={size}  color={color}/>
    )
   }}/>

<Tab.Screen name='Settings' component={SettingScreen} options={{
    tabBarIcon:({color,size})=>(
     <Ionicns name='settings' size={size}  color={color}/>
    )
   }}/>

<Tab.Screen name='ColorScreen' component={ColorScreen} options={{
    tabBarIcon:({color,size})=>(
     <Ionicns name='color-palette-sharp' size={size}  color={color}/>
    )
   }}/>
   

   
    </Tab.Navigator>

    </NavigationContainer> 

   
   )
}








export default Navigation;

**Comment by ameerhamzaWAL** [comment]
import { useTheme } from 'react-native-paper';

const theme = useTheme();
theme.colors.secondaryContainer = "transperent"

Work for me...
