### ISSUE TITLE
[5.0.0-rc.5] Jest failures

### ISSUE THREAD

**Issue by iM-GeeKy** [callstack/react-native-paper#3376]
### Current behaviour

There appears to be an issue with Jest tests when upgrading from version `4.12.4` to `5.0.0-rc.5`.

### Expected behaviour

Upgrading the version of `react-native-paper` shouldn't affect Jest tests.

### Code sample

https://github.com/iM-GeeKy/material-you-jest

Check the [`README.md`](https://github.com/iM-GeeKy/material-you-jest) on how to reproduce.

### What have you tried

I was able to identify that upgrading the version seems to have an effect on the outcome of the Jest test. Directions are in the [`README.md`](https://github.com/iM-GeeKy/material-you-jest).

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          | 0.69.5
| react-native-paper    | 5.0.0-rc.5
| node                  | v16.16.0
| npm or yarn           | yarn v1.22.19
| expo sdk              | 46.0.10

**Comment by lukewalczak** [comment]
Hey @iM-GeeKy, due to that [commit](https://github.com/callstack/react-native-paper/commit/25cd448f7eafc62e68844a44056a54b707b7e1e8), since `testID` is extracted from `rest` you need to adjust the `testID` in your test to:

```
    const testInput = await component.queryByTestId(
      "TestInput-flat"
    );
```

**Comment by iM-GeeKy** [comment]
> Hey @iM-GeeKy, due to that [commit](https://github.com/callstack/react-native-paper/commit/25cd448f7eafc62e68844a44056a54b707b7e1e8), where `testID` was extracted from `rest` you need to adjust the `testID` in your test to:
> 
> ```
>     const testInput = await component.queryByTestId(
>       "TestInput-flat"
>     );
> ```

I see now! Thank you. Is that captured in the documentation by any chance? That way it's more obvious for anyone else who may run into the same problem.

**Comment by lukewalczak** [comment]
> I see now! Thank you. Is that captured in the documentation by any chance? That way it's more obvious for anyone else who may run into the same problem.

Tbh, I'm going to revisit that change and confirm it's necessary. If I confirm it's required then I will add it in the migration guide, otherwise will revert that change and inform you about it ✌🏽

**Comment by Duduzera1997** [comment]
@lukewalczak Hello! u have any position for this issue? i have all units tests broken after upgrade :/

**Comment by lukewalczak** [comment]
@iM-GeeKy @Duduzera1997 there is a PR which should handle the issue with tests https://github.com/callstack/react-native-paper/pull/3405
