### ISSUE TITLE
Component not respecting theme setting, am I doing something wrong?

### ISSUE THREAD

**Issue by theabhishek2511** [callstack/react-native-paper#3377]
What I'm using (non-expo project):
```
"react-native": "0.70.0",
"react-native-paper": "4.12.4",
"react-native-vector-icons": "9.2.0"
"@react-navigation/native": "6.0.12",
```

I'm relatively new to React Native so I'm not sure what I'm doing wrong here, but I'm trying to force an app into always light mode, and it seems like for some components, my device's theme setting almost always takes precedent over whatever theme I try to pass to `react-native-paper`'s Provider. Setup is as follows:

App.tsx

```
import {  NavigationContainer,  DefaultTheme as NavigationDefaultTheme } from '@react-navigation/native';
import {  Provider as PaperProvider,  DefaultTheme as PaperDefaultTheme } from 'react-native-paper';

const CombinedTheme = {
  ...NavigationDefaultTheme,
  ...PaperDefaultTheme,
  colors: {
    ...NavigationDefaultTheme.colors,
    ...PaperDefaultTheme.colors,
    ...Colors, // custom color object
  },
};

const App = () => {
...
return (
  <AppContext.Provider
  ...
  //...provider stuff
  >
      <PaperProvider theme={CombinedTheme}>
        <NavigationContainer theme={CombinedTheme}>
          <MainStack /> {/* content goes here /*}
        </NavigationContainer>
      </PaperProvider>
  </AppContext.Provider>
);
}
```
SomeScreen.tsx
```
const SomeScreen = (props: Props) => {
  return (
    <SafeAreaView style={{flex: 1, backgroundColor: Colors.white}}>
      <ScrollView>
        <View style={{flex: 1, padding: 20}}>
          <Switch value={value} onValueChange={setValue} />
          {/* other stuff */}
        </View>
      </ScrollView>
    </SafeAreaView>
  )
}
```
What I want to achieve and what I get when device theme is set to light mode:
![image](https://user-images.githubusercontent.com/2082634/191182846-b9cf0270-9012-4ac3-b930-3490f2ebf190.png)

What I get when device theme is set to dark mode and I fully restart the app:
![image](https://user-images.githubusercontent.com/2082634/191182945-5362448a-9f5f-461a-8ffc-e361fcaeb5a1.png)

**Comment by theabhishek2511** [comment]
I attempted a minimal repro using expo: https://snack.expo.dev/9bPX3BMml , but it seems like everything is working fine through there. It's just my device (Pixel 3a) and my project where this issue crops up.

**Comment by raajnadar** [comment]
https://callstack.github.io/react-native-paper/theming.html

> dark (boolean): whether this is a dark theme or a light theme.

**Comment by theabhishek2511** [comment]
> https://callstack.github.io/react-native-paper/theming.html
> 
> > dark (boolean): whether this is a dark theme or a light theme.

`dark` should already be set to false from the spread operator for `CombinedTheme`. Regardless, setting `dark` to any value doesn't have the desired effect.

`dark: false`
![image](https://user-images.githubusercontent.com/2082634/191193157-9bb59ab8-4186-47d0-9de0-e99b15ae3206.png)
`dark: true`
![image](https://user-images.githubusercontent.com/2082634/191193257-f2fd4ab7-1c76-4c64-bf7b-90c63f45dbb8.png)

**Comment by raajnadar** [comment]
Can you repro on pixel emulator? If yes can you share the config of the emulator?

**Comment by theabhishek2511** [comment]
Weirdly enough, it behaves well on emulators. Seems to be acting up only when I run it on my device. For now I've fixed it by setting `trackColor` manually.

**Comment by lukewalczak** [comment]
Like in the mentioned issue, make sure that your android device doesn't [force the dark theme (https://androidwaves.com/force-android-apps-to-use-dark-mode/) option enabled. However, since it rare case, I'm closing the issue.

**Comment by theabhishek2511** [comment]
> Like in the mentioned issue, make sure that your android device doesn't [force the dark theme](https://androidwaves.com/force-android-apps-to-use-dark-mode/) option enabled. However, since it rare case, I'm closing the issue.

popping in to verify that this indeed was the issue 👍
