### ISSUE TITLE
react-native-paper TextInput change height

### ISSUE THREAD

**Issue by Softkeydel** [callstack/react-native-paper#3379]
### Current behaviour
1.Changing TextInput  height icon and text alignment is not working properly
![photo_6147924464076173696_y](https://user-images.githubusercontent.com/16410754/191337269-af0dfe9b-37ef-4b93-b003-d5ac6aae0025.jpg)
2. How to use MaterialCommunityIcons or other in TextInput  
 ![photo_6147924464076173698_y](https://user-images.githubusercontent.com/16410754/191339216-2deb42f2-a13a-45d5-9fc1-730ccf41612c.jpg)

### Expected behaviour
1. Changing TextInput  height icon and text alignment should be working properly
2. Using MaterialCommunityIcons  should be working properly

### Code sample
```
        <TextInput
          theme={{ roundness: 20 }}
          style={{ height: 40, justifyContent: "center", textAlignVertical: 'center' }}
          placeholder='placeholder'
          left={<MaterialCommunityIcons name={"eye-off"} />}
          value={text}
          onChangeText={text => setText(text)}
        />
```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |android
| react-native          |0.70.1
| react-native-paper    |4.12.4
| react-native-vector-icons    |9.2.0

**Comment by Softkeydel** [comment]
| react-native-vector-icons    |9.2.0

updated the issue

**Comment by abdullahkhan70** [comment]
> ### Current behaviour
> 1.Changing TextInput height icon and text alignment is not working properly ![photo_6147924464076173696_y](https://user-images.githubusercontent.com/16410754/191337269-af0dfe9b-37ef-4b93-b003-d5ac6aae0025.jpg) 2. How to use MaterialCommunityIcons or other in TextInput ![photo_6147924464076173698_y](https://user-images.githubusercontent.com/16410754/191339216-2deb42f2-a13a-45d5-9fc1-730ccf41612c.jpg)
> 
> ### Expected behaviour
> 1. Changing TextInput  height icon and text alignment should be working properly
> 2. Using MaterialCommunityIcons  should be working properly
> 
> ### Code sample
> ```
>         <TextInput
>           theme={{ roundness: 20 }}
>           style={{ height: 40, justifyContent: "center", textAlignVertical: 'center' }}
>           placeholder='placeholder'
>           left={<MaterialCommunityIcons name={"eye-off"} />}
>           value={text}
>           onChangeText={text => setText(text)}
>         />
> ```
> 
> ### Screenshots (if applicable)
> ### What have you tried
> ### Your Environment
> software	version
> ios or android	android
> react-native	0.70.1
> react-native-paper	4.12.4
> react-native-vector-icons	9.2.0

You should better update your react-native-vector-icons version. If, you do that, then it would solve your issue.
