### ISSUE TITLE
Textinput change color inside box not working

### ISSUE THREAD

**Issue by vinothmoorthkumar** [callstack/react-native-paper#3381]
Hi,

Here I m try to change color of text inside textinput box. I m passing color in theme as props still is not working.

`<TextInput theme={{ colors: { text: "white"}}} label="data" value={value}  />
`

Help me please

**Comment by vinothmoorthkumar** [comment]
I using     "react-native-paper": "^5.0.0-rc.6"

**Comment by dakshbhardwaj** [comment]
@vinothmoorthkumar can you please provide the repro steps [snack.expo.dev](https://snack.expo.dev/)?

**Comment by GubanovIgor** [comment]
@vinothmoorthkumar, I have the same issue. Did you solve the problem?

**Comment by cyhnkckali** [comment]
I also have the problem. V5.0.0-rc.6

**Comment by lukewalczak** [comment]
In v5, since there are new theme colors, you have to override the following colors:

* flat input - `onSurfaceVariant`
* outlined input - `onSurface`

**Comment by lukewalczak** [comment]
`<TextInput theme={{ colors: { onSurface: "white"}}} mode="outlined" />`

**Comment by cyhnkckali** [comment]
Thanks Luke, It worked =)
@lukewalczak

**Comment by vinothmoorthkumar** [comment]
@lukewalczak Thank you,

**Comment by meg1770** [comment]
@lukewalczak  thanks!
