### ISSUE TITLE
react-native-paper AppBar cannot take screen title from react-navigation

### ISSUE THREAD

**Issue by R4Y-repo** [callstack/react-native-paper#3382]
The AppBar comes with an empty navbar and when i want to know how can i make it always have the screen's name like react navigation does

when applying the AppBar, by default it displays no title.

the AppBar should automatically have the screen's name as its title.

/shared/navbar.js
```
import { Appbar } from 'react-native-paper';

export function NavBar({ navigation, back, title }) {
  return (
    <Appbar.Header>
      {back ? <Appbar.BackAction onPress={navigation.goBack} /> : null}
      <Appbar.Content title = {title} />
    </Appbar.Header>
  );
}
```

/routes/stackone.js

```
import React from 'react';
import ScreenOne from '../screens/screenOne;
import ScreenTwo from '../screens/screenTwo;
import { createNativeStackNavigator } from '@react-navigation/native-stack';
// import { useNavigationState } from '@react-navigation/native';
import { NavBar } from '../shared/navbar'

// home stack navigator screens
const Stack = createNativeStackNavigator();

export default function StackOne(){
  // const screenName = useNavigationState((state) => state.routes[state.index].name)
  return(
    <Stack.Navigator
    screenOptions={{
      header: (props) => <NavBar {...props} title={screenName} />
    }}>
      <Stack.Screen name="Screen1" component={ScreenOne} />
      <Stack.Screen name="Screen2" component={ScreenTwo} />
    </Stack.Navigator>
  )
}
```
/routes/stacktwo.js

```
import React from 'react';
import ScrenOne from '../screens/screnOne;
import ScrenTwo from '../screens/screnTwo;
import { createNativeStackNavigator } from '@react-navigation/native-stack';
// import { useNavigationState } from '@react-navigation/native';
import { NavBar } from '../shared/navbar'

// home stack navigator screens
const Stack = createNativeStackNavigator();

export default function StackTwo(){
  // const screenName = useNavigationState((state) => state.routes[state.index].name)
  return(
    <Stack.Navigator
    screenOptions={{
      header: (props) => <NavBar {...props} title={screenName} />
    }}>
      <Stack.Screen name="Scren1" component={ScrenOne} />
      <Stack.Screen name="Scren2" component={ScrenTwo} />
    </Stack.Navigator>
  )
}
```

App.js

```
import Tabs from './routes/tabs';
import { NavigationContainer } from '@react-navigation/native';

import { PreferencesContext } from './shared/preferencesContext';
import { Provider as PaperProvider, withTheme } from 'react-native-paper'
import { DarkTheme, DefaultTheme } from './styles/global'

const App = () => {

  const [isThemeDark, setIsThemeDark] = React.useState(false);

  let theme = isThemeDark ? DarkTheme : DefaultTheme;

  const toggleTheme = React.useCallback(() => {
    return setIsThemeDark(!isThemeDark);
  }, [isThemeDark]);



  return (
    <PreferencesContext.Provider value={preferences}>
      <PaperProvider theme = {theme}>
        <NavigationContainer theme = {theme}>
          <Tabs/>
        </NavigationContainer>
      </PaperProvider>
    </PreferencesContext.Provider>
  );
}

export default withTheme(App);
```
shared/preferencesContext.js
```
import {createContext} from 'react';

export const PreferencesContext = createContext({
  toggleTheme: () => {},
  isThemeDark: false,
});
```

i tried to get the name from react navigation but couldn't find how.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          | 0.69.5
| react-native-paper    |5.0.0-rc.5
| node                  |16.17.0
| npm or yarn           |8.19.1
| expo sdk              |6.0.5

**Comment by kelokchan** [comment]
Try `title={options.title}`

**Comment by R4Y-repo** [comment]
> Try `title={options.title}` 

Can you tell me how can I put it in the code because there's no variable called `options`

**Comment by lukewalczak** [comment]
@R4Y-repo please check the following [snack](https://snack.expo.dev/U9EW8Fmne), mainly focus on:

```
    <Stack.Navigator
      screenOptions={{
        header: (props) => <NavBar title={props.route.name} {...props} />,
      }}>
```

**Comment by R4Y-repo** [comment]
> @R4Y-repo please check the following [snack](https://snack.expo.dev/U9EW8Fmne), mainly focus on:
> 
> 
> 
> ```
> 
>     <Stack.Navigator
> 
>       screenOptions={{
> 
>         header: (props) => <NavBar title={props.route.name} {...props} />,
> 
>       }}>
> 
> ```

Thanks! That fixed it 😄

**Comment by lukewalczak** [comment]
> But it would be cooler if that was the default behaviour for react native paper

We can consider that, however, that library should be compatible with other navigation libraries as well, so currently I'm closing that issue.

**Comment by tkalejandro** [comment]
> This only works if the screen `name` prop doesn't have a space. What if the `name` is `MyPage` but I've specified a title `options={{ title: "My Page" }}` is there a way to get the title that is specified there?

I coudlnt find nothing good. However, I did a switch condition to render the title depending of each route.name

Annoying but what to do xD

**Comment by ahmetskilinc** [comment]
@tkalejandro I solved it by adding a prop to each screen where it is added to the navigator and then using it to dynamically add the title prop in the options object.

```javascript
<Stack.Screen name="Device" options={({ route: { params: { title }}) => ({ title: title })} component={DeviceScreen} />
```
