### ISSUE TITLE
Ripple does not respect Border Radius on buttons in 5.0.0-rc.6

### ISSUE THREAD

**Issue by NathanC** [callstack/react-native-paper#3387]
### Current behaviour

In 5.0.0-rc.6, buttons are rounded by default. I don't like the rounded look personally, so tried to set the border radius to 0 (or low at least).

The button border radius changes (for example, for a contained button), but **the ripple is still rounded, looking strange when pressed**

This is the inverse of an old bug: https://github.com/callstack/react-native-paper/issues/1342

### Expected behaviour
The ripple on the button follows the `borderRadius` style

### Reproduction

https://snack.expo.dev/A4FEbJrFh

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 13
| react-native                | 0.69.5
| react-native-paper    | 5.0.0-rc.6
| expo sdk                     | 46.0.9

**Comment by NathanC** [comment]
Thanks @dakshbhardwaj for the quick fix! Always fun to see nullish coalescing in the wild.

**Comment by dakshbhardwaj** [comment]
> Thanks @dakshbhardwaj for the quick fix! Always fun to see nullish coalescing in the wild.

Thank you @NathanC
