### ISSUE TITLE
Checkbox animation on android

### ISSUE THREAD

**Issue by KroekerNick** [callstack/react-native-paper#339]
### Current behaviour

![icon](https://user-images.githubusercontent.com/5189530/39360934-a5cec6b6-4a39-11e8-96e4-dbccccd7aea2.gif)

### Expected behaviour

![icon2](https://user-images.githubusercontent.com/5189530/39360964-cc2974c8-4a39-11e8-8902-05c056708ef6.gif)

Color is not important. From the application Material Design Demo

### Code sample

from the documentation

### Screenshots (if applicable)

above

### Your Environment

| software              | version
| --------------------- | -------
| android        | 7, 8
| react-native          | 0.55.3
| react-native-paper    | ^1.4.1
| node                  | 8
| npm or yarn           | 5

**Comment by ferrannp** [comment]
This issue is being stale for a year.
