### ISSUE TITLE
BottomNavigation in v5 doesn't leverage getColor (breaking @react-navigation/material-bottom-tabs)

### ISSUE THREAD

**Issue by NathanC** [callstack/react-native-paper#3391]
In the past, the Bottom Navigation bar color leveraged the `getColor` prop to determine what color a tab should be. It seems like for v3 theming, it just uses the `customBackground` prop, and never leverages `getColor`

See here: https://github.com/callstack/react-native-paper/blob/main/src/components/BottomNavigation/BottomNavigation.tsx#L621-L625

`getColor` *is* used in the ripple animation ([here](https://github.com/callstack/react-native-paper/blob/main/src/components/BottomNavigation/BottomNavigation.tsx#L805)), which results in a brief flash of color that ripples, and then gets reset to the default (white in my testing) color.

**Comment by NathanC** [comment]
fyi changing the code to
```
  const backgroundColor = isV3
    ? customBackground || v2BackgroundColorInterpolation || theme.colors.elevation.level2
    : shifting
    ? v2BackgroundColorInterpolation
    : approxBackgroundColor;
``` 

Worked for me.

**Comment by lukewalczak** [comment]
Hey @NathanC, could you please attach the snack presenting the issue?

**Comment by NathanC** [comment]
@lukewalczak I've already moved on to using a forked version, and I'm not the best at setting up snacks. If you trace through the usage of [getColor](https://github.com/callstack/react-native-paper/blob/main/src/components/BottomNavigation/BottomNavigation.tsx#L366) you'll see it never propagates to tab bar color (besides ripple).

If you want to reproduce it, just try material bottom. navigation (with different color tabs) with the new React native paper snapshot.

**Comment by lukewalczak** [comment]
@NathanC which `react-native-paper` version are you using?
