### ISSUE TITLE
Banner lacks theme font 5.0.0-rc.6

### ISSUE THREAD

**Issue by iM-GeeKy** [callstack/react-native-paper#3394]
### Current behaviour

The `Banner` components text doesn't appear to support custom theme fonts.

### Expected behaviour

The `Banner` components text should support custom fonts to provide consistent design across application theming via either internally by looking at the theme, by a label style, or by allowing a `Text` component to be passed as the `children` prop.

### How to reproduce?

https://snack.expo.dev/@fitzwabs/font-error-for-paper

### Preview

<img width="282" alt="Screen Shot 2022-10-02 at 6 45 57 PM" src="https://user-images.githubusercontent.com/7604441/193479647-a90a05c6-8b55-49c5-8a00-aee2985306a1.png">

### What have you tried so far?

It looks like the problem originates from here(https://github.com/callstack/react-native-paper/blob/main/src/components/Banner.tsx#L220)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 16.0
| android                        | x
| react-native                | x.x.x
| react-native-paper    | 5.0.0-rc.6
| node                            | x.x.x
| npm or yarn                | npm
| expo sdk                     | 46.0

**Comment by lukewalczak** [comment]
Hey @iM-GeeKy, I think the type for `children` is wrong and it should be `React.ReactNode`, because you can pass the Paper's `Text` component with `variant` as a Banner's children:

```
        <Banner
          visible={true}
          actions={[
            {
              label: 'Fix it',
              onPress: () => setVisible(false),
            },
            {
              label: 'Learn more',
              onPress: () => setVisible(false),
            },
          ]}>
          <Text variant="displayMedium">
            This text does not have custom font applied
          </Text>
        </Banner>
  ```

**Comment by iM-GeeKy** [comment]
> Hey @iM-GeeKy, I think the type for `children` is wrong and it should be `React.ReactNode`, because you can pass the Paper's `Text` component with `variant` as a Banner's children:
> 
> ```
>         <Banner
>           visible={true}
>           actions={[
>             {
>               label: 'Fix it',
>               onPress: () => setVisible(false),
>             },
>             {
>               label: 'Learn more',
>               onPress: () => setVisible(false),
>             },
>           ]}>
>           <Text variant="displayMedium">
>             This text does not have custom font applied
>           </Text>
>         </Banner>
> ```

I'll use that as a workaround until the type for `children` is updated. Thanks for the quick response.
