### ISSUE TITLE
Button loading jumping

### ISSUE THREAD

**Issue by ButuzGOL** [callstack/react-native-paper#340]
Here video attached

![bug](https://user-images.githubusercontent.com/196564/39363639-a88a16d6-4a33-11e8-8aa6-958d868f1490.gif)

**Comment by satya164** [comment]
This should be better with 772b82a

**Comment by ButuzGOL** [comment]
Still see jumping
![loading](https://user-images.githubusercontent.com/196564/39702578-04796bb8-520e-11e8-95be-8ec576aafc07.gif)

**Comment by faljabi** [comment]
any solution for this?
