### ISSUE TITLE
How to use Menu component without onDismiss?

### ISSUE THREAD

**Issue by VityaSchel** [callstack/react-native-paper#3404]
### Current behaviour
Currently it's impossible because onDismiss is required.

### Expected behaviour
I would like it to be possible to control visibility of this menu myself and show it whenever I want, while also allowing user to interact with background. In my case I wanted to use it for autocomplete in TextInput.

v5

**Comment by lukewalczak** [comment]
@VityaSchel could you please present on the snack what you are trying to achieve?

**Comment by VityaSchel** [comment]
@lukewalczak ![Screenshot_20221014-085731_MTProto Mobile.jpg](https://user-images.githubusercontent.com/59040542/195765625-3ba68b3d-a671-415b-9e7b-f9ba3a30354f.jpg)
