### ISSUE TITLE
Is it possible to set default screen to show for a BottomNavigation.SceneMap ?

### ISSUE THREAD

**Issue by remi-p-opka** [callstack/react-native-paper#3406]
I have this and i want to say the default screen for this scene is home: HomeScreen:

````
    const [routesHomeFlow] = React.useState([
        { key: 'home', title: 'Home', focusedIcon: 'home' },
        { key: 'account', title: 'Sign out', focusedIcon: 'logout' },
    ]);

    const renderSceneHome = BottomNavigation.SceneMap({
        home: HomeScreen,
        account: AccountScreen,
    });

                    <>
                        <BottomNavigation
                            navigationState={{ index, routes: routesHomeFlow }}
                            onIndexChange={setIndex}
                            renderScene={renderSceneHome}
                        />
                    </>
````
But every time my rendered scene is renderSceneHome, it puts me in the account screen, and i want it to be the HomeScreen by default, but couldn't find doc on it, is there a way to set the default screen ?
Thanks !

**Comment by lukewalczak** [comment]
Hey @remi-p-opka, I think you could miss the default `index` which should be set to `0` if you want to have `HomeScreen` to be the first (default) tab. Please check the following [snack](https://snack.expo.dev/W-b0mXoWM) for reference.
