### ISSUE TITLE
Button do we need margin ?

### ISSUE THREAD

**Issue by ButuzGOL** [callstack/react-native-paper#341]
Do we need margin for button ?

### Current behaviour
https://github.com/callstack/react-native-paper/blob/master/src/components/Button.js#L249
margin: 4

<img width="333" alt="screen shot 2018-04-27 at 4 09 01 pm" src="https://user-images.githubusercontent.com/196564/39364422-9a21cc12-4a36-11e8-9e4e-5aa83d5161a4.png">

Not align with inputs

### Expected behaviour

Should be align with inputs

**Comment by satya164** [comment]
You need `margin` so that the drop shadow is visible. You can remove margin by passing a `style` prop.

**Comment by gawrysiak** [comment]
I have added a related issue [here](https://github.com/callstack/react-native-paper/issues/334)
