### ISSUE TITLE
Dependency `@material/material-color-utilities` breaks React Native Web

### ISSUE THREAD

**Issue by wallzero** [callstack/react-native-paper#3422]
### Current behaviour
[The additional dependency `@material/material-color-utilities`](https://github.com/callstack/react-native-paper/commit/1d3c4bd864dc49b2c9b7bf3258b6e957afee6ff4) breaks React Native Web builds.

```bash
ERROR in ../node_modules/@material/material-color-utilities/dist/index.js 17:0-30
Module not found: Error: Can't resolve './blend/blend' in 'node_modules/@material/material-color-utilities/dist'
Did you mean 'blend.js'?
BREAKING CHANGE: The request './blend/blend' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

### Expected behaviour
A React Native Web project should build and bundle `react-paper` including its dependencies.

### How to reproduce?

Setup a standard [`react-native-web`](https://necolas.github.io/react-native-web/docs/setup/)  and [`react-paper`](https://callstack.github.io/react-native-paper/using-on-the-web.html) project.

### What have you tried so far?

The project builds if I force Webpack to transpile the dependency. `fullySpecified: false` is required since the package sets `"type": "module"`.

```
{
    include: /(@material\/material-color-utilities)/u,
    resolve: {
	    fullySpecified: false
    },
    test: /\.js$/u,
    use: **babel-loader**
}
```

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.70.3
| react-native-web            | 0.18.9
| react-native-paper    | 5.0.0-rc.7
| node                            | 18.11.0
| npm or yarn                | 1.22.19

**Comment by wallzero** [comment]
[See related issue](https://github.com/material-foundation/material-color-utilities/issues/35)

**Comment by lukewalczak** [comment]
Hey @wallzero, thanks for reporting the issue. Could you please help us and create a minimal repo on which we'll able to test the required changes?

**Comment by wallzero** [comment]
[See here](https://gitlab.com/wallzero/react-native-web-paper-demo)

Like I said above; I basically followed a standard [react-native-web](https://necolas.github.io/react-native-web/docs/setup/) and [react-paper](https://callstack.github.io/react-native-paper/using-on-the-web.html) project.

The two main changes I had to make were:

1. Add the following rule to support the recently added `@material\/material-color-utilities` dependency:

```js
      {
        include: /(@material\/material-color-utilities)[/\\]/,
        resolve: {
          fullySpecified: false
        },
        test: /\.js$/,
        use: babelLoader
      }
```

2. The previous `exclude: /node_modules[/\\](?!react-native-vector-icons)/` no longer seems to work. I've removed the above regex negative lookahead and instead opted for the following alias:

```js
    alias: {
      ...
      'react-native-vector-icons': 'react-native-vector-icons/dist'
    }
```

This small demo just displays a React Native Paper button. The ripple effect also doesn't seem to be working.

**Comment by lukewalczak** [comment]
Thanks @wallzero, we are working on that!
