### ISSUE TITLE
Button Icon colors does not sync with Button text color

### ISSUE THREAD

**Issue by bombillazo** [callstack/react-native-paper#3424]
### Current behaviour
Currently, the color used for a button text is not propagated to the icon colors for the Button `icon` prop.

### Expected behaviour
Ideally, the color used for the text is also used but the icon.

### How to reproduce?
```tsx
<Button
  onPress={onNext}
  textColor="red"
  icon={() => {
    return (
      <Icon
        name="chevron-right"
        size={24}
      />
    );
  }}
  disabled={disabled}
  loading={form.formState.isSubmitting}>
  {nextText}
</Button>
```

### What have you tried so far?
Currently one has to be passing a color available to both the button text and Icon.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by raajnadar** [comment]
Did you try this?

```
<Button
  onPress={onNext}
  textColor="red"
  icon={(props) => {
    return (
      <Icon
        name="chevron-right"
         {...props}
        size={24}
      />
    );
  }}
  disabled={disabled}
  loading={form.formState.isSubmitting}>
  {nextText}
</Button>
```

**Comment by bombillazo** [comment]
Thanks!
