### ISSUE TITLE
Button Children Bug Crash

### ISSUE THREAD

**Issue by Lucasark** [callstack/react-native-paper#3425]
### Current behaviour
Crash when using another components that is not Text

### Expected behaviour
Should accept any component Raect.node

### How to reproduce?
      <Button mode='contained' disabled><View style={{height: 100, width: 100}}>test</View></Button>

### Preview
ANDROID:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/31750882/196859249-20fe7698-05bd-418c-9981-f5a481adcbbe.png">

WEB:
<img width="168" alt="image" src="https://user-images.githubusercontent.com/31750882/196859274-bec8675f-ec40-4023-b5e0-60b3c3a44c55.png">

### What have you tried so far?
Nothing, in this moment.

### Your Environment

| software                      | version
| --------------------- | -------
https://snack.expo.dev/

**Comment by raajnadar** [comment]
You need to use the Text tag

`  <Button mode='contained' disabled><View style={{height: 100, width: 100}}><Text>test</Text></View></Button>`

**Comment by Lucasark** [comment]
> <Button mode='contained' disabled><View style={{height: 100, width: 100}}><Text>test</Text></View></Button>

Component do not crash, but it ignore children
<img width="159" alt="image" src="https://user-images.githubusercontent.com/31750882/196861254-d91e195d-6ee7-4314-83ff-4297e31d83a2.png">

**Comment by Lucasark** [comment]
Better exemple:
Android
<img width="169" alt="image" src="https://user-images.githubusercontent.com/31750882/196861766-946e29fb-2fdc-4b23-b3f5-44f83568705d.png">

Web:
<img width="168" alt="image" src="https://user-images.githubusercontent.com/31750882/196861842-e0ed3cd0-ccf4-4752-b337-4236ba3beb78.png">

```
<Button mode="contained" disabled>
        <View style={{ height: 100, width: 100, backgroundColor: 'blue' }}>
          <Text>test</Text>
        </View>
        <View style={{ height: 100, width: 100, backgroundColor: 'red' }}>
          <Text>test</Text>
        </View>
      </Button>
```

**Comment by raajnadar** [comment]
If you need to do some nesting why not create a custom component?

A button should only have a string as children

**Comment by raajnadar** [comment]
> And, I disagree that a button have only string as children;

It is very clear the library is strict with the material design concepts, if it is mentioned in the material design document please share the maintainer will add the support
