### ISSUE TITLE
ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

### ISSUE THREAD

**Issue by danidaryaweesh** [callstack/react-native-paper#3430]
### Current behaviour

I'm getting a warning about deprecated ViewPropTypes whenever I import this library into my code. 
### Expected behaviour

To not get any warning about deprecated ViewPropTypes when importing the library
### How to reproduce?

Import any component from the library into an active file. 

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 15+
| android                        | 11+
| react-native                | 0.68.4
| react-native-paper    | 4.12.5
| node                            | 14
| npm or yarn                | yarn 1.22.17

**Comment by lukewalczak** [comment]
Does the issue exist on the latest `react-native-paper` version?

**Comment by danidaryaweesh** [comment]
@lukewalczak No it has been solved, but I just forgot to close the issue, apologies for that.
