### ISSUE TITLE
How to give borderRadius to Appbar.Header?

### ISSUE THREAD

**Issue by ase9810** [callstack/react-native-paper#3432]
I'm styling Appbar.Header. The style related to the background color was applied, but the style related to the borderRadius was not applied. What setting should I set to give borderRadius on both sides of the bottom as shown in the picture below?
![defaultHeader](https://user-images.githubusercontent.com/18522328/197432603-16645c18-1120-482d-a1cb-622e30c8f462.PNG)

**Comment by lukewalczak** [comment]
Hey @ase9810, I think it's currently not possible

**Comment by Lucasark** [comment]
I think it's a violation on Material You. Radius is only in Components that is inside full surface, like Cards, Buttons and Modals.

**Comment by polovi** [comment]
Top app bars 
Don’t use curved shapes on top app bars as it implies that the container can expand upon interaction.
-> [Guidelines](https://m3.material.io/components/top-app-bar/guidelines#ff25b95a-0c10-49a6-a7a5-355e029c390b)

**Comment by lukewalczak** [comment]
As mentioned above, it's not typical for MD. 

Currently closing the issue, however if there will be greater interest in that modification we can discuss it.
