### ISSUE TITLE
[5.0.0-RC-8] Use custom font as default

### ISSUE THREAD

**Issue by bombillazo** [callstack/react-native-paper#3435]
### Current behaviour
Currently, there is no way to set the default app font to a specific fontFamily. You either have to use variants or pass the fontFamily as a style prop.

### Expected behaviour
There should be a theme property that sets the default fontFamily to use and propagates it to ALL RNP elements.

### How to reproduce?
N/A

### Preview

Currently, when using themeV3, if you don't choose variant, there is a token object with default fonts that gets used to set the `brandRegular` property.

```tsx

  if (theme.isV3 && variant) {
  } else {
    const { brandRegular, weightRegular } = tokens.md.ref.typeface;
```

This causes all Text objects that do not use variant to simply use the default OS font. We should be able to somehow override this.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.69.6
| react-native-paper    | 5.0.0-RC-8
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by bombillazo** [comment]
Im currently getting around this using this patch and extending fonts to include a default variant `MD3Type`:

```tsx
       />
     );
   } else {
-    const { brandRegular, weightRegular } = tokens.md.ref.typeface;
     const font = theme.isV3
       ? {
-          fontFamily: brandRegular,
-          fontWeight: weightRegular,
+          fontFamily: theme.fonts.default.fontFamily,
+          fontWeight: theme.fonts.default.fontWeight,
         }
       : theme.fonts?.regular;
     const textStyle = {

```

**Comment by lukewalczak** [comment]
Hey @bombillazo, unfortunately looks like I overlooked that case :|

What is the `theme.fonts.default` in your patch?

**Comment by bombillazo** [comment]
Its just another `MD3Type` object like `headlineSmall`, `bodyMedium`... etc. I then set it to use the custom fontFamily

```
  default: {
    fontFamily: 'MyFont',
    fontSize: 0,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 0,
  },
```

**Comment by lukewalczak** [comment]
Could you please if that PR https://github.com/callstack/react-native-paper/pull/3436 is fixing the problem?

**Comment by bombillazo** [comment]
@lukewalczak sorry for the delay, yup! that looks good to me
