### ISSUE TITLE
Hi Team 

### ISSUE THREAD

**Issue by abhilashnyamagoud** [callstack/react-native-paper#3437]
Hi Team , I have used React native paper as my Design framework for my application. Now I am Doing Unit Testing With Jest But In Unit testing It Showing , paper Provider as a bug,  Unit test is not Supported For Paper Provider, 

Look into This Issue.

**Comment by lukewalczak** [comment]
Hey @abhilashnyamagoud, what is the bug/issue which you've faced?

**Comment by abhilashnyamagoud** [comment]
> Hey @abhilashnyamagoud, what is the bug/issue which you've   @@faced?

![Screenshot 2022-10-26 144314](https://user-images.githubusercontent.com/52066411/197986439-d0d71ed6-a71b-4717-91de-51354b1df0ce.jpg)

when I Try to test with react native paper it showing Error,

**Comment by lukewalczak** [comment]
Please check the following [article](https://bobbyhadz.com/blog/typescript-jest-cannot-use-import-statement-outside-module), based on the provided error I think you have misconfigured jest env in your TypeScript project.
