### ISSUE TITLE
How to change List.Accordion rippleColor and underlayColor ?

### ISSUE THREAD

**Issue by cyhnkckali** [callstack/react-native-paper#3439]

**Comment by suleymanbariseser** [comment]
May I contribute to the project by implementing this feature?

**Comment by lukewalczak** [comment]
hey @suleymanbariseser, sure, let's try to add `rippleColor` in the similar way as it's currently done in `Button` or `AnimatedFAB` components.

**Comment by cyhnkckali** [comment]
Thank you @suleymanbariseser

**Comment by lukewalczak** [comment]
Closed via: https://github.com/callstack/react-native-paper/pull/3448
