### ISSUE TITLE
Where is unmountOnBlur from Navigator.Screen options prop?

### ISSUE THREAD

**Issue by thlindustries** [callstack/react-native-paper#3440]
- I was messing around with material-bottom-tabs and bottom-tabs and I realized that some attributes are missing into Screen's options prop from **createMaterialBottomTabNavigator**.

- I was trying to use the **unmountOnBlur** attribute that I was already using while with **createBottomTabNavigator** but when I changed I got the type error saying that the attribute **unmountOnBlur** does not exists

**Some version**:
```
  "@react-navigation/bottom-tabs": "^6.4.0",
  "@react-navigation/core": "^6.4.0",
  "@react-navigation/material-bottom-tabs": "^6.2.4",
  "@react-navigation/native": "^6.0.13",
  "react": "18.1.0",
  "react-native": "0.70.3",
```  

With the Screen component from '@react-navigation/material-bottom-tabs':
![Err](https://i.imgur.com/mGx0y6V.png "Err")

With the Screen component from '@react-navigation/bottom-tabs':
![Err](https://i.imgur.com/FeJwHIU.png "Err")

Expected:
The same attributes from @react-navigation/bottom-tabs into Screen options prop from material-bottom-tabs

**Comment by thlindustries** [comment]
Also other attributes that I was using are miss typed like tabBarLabel, with the material-bottom-tabs it only can be a string, with the  bottom-tabs  it can be a string or a function that returns a ReactNode and receives some params like **focused**

**Comment by mohanataraj** [comment]
This issue exists in the latest version as well
`error: Object literal may only specify known properties, and 'unmountOnBlur' does not exist in type 'BottomTabNavigationOptions`

verisons;
` "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/material-top-tabs": "^7.1.0",
    "@react-navigation/native": "^7.0.14",
    "@react-navigation/native-stack": "^7.2.0",`
