### ISSUE TITLE
TextAlign for Snackbar ("left", "center", "right")

### ISSUE THREAD

**Issue by fmohtadi99** [callstack/react-native-paper#3449]
Most developers use **Snackbar** in their project to show a pure message (no action). In this case, they want to show the text at the **center** of **Snackbar**. But, HOW?

**STEPS**:

1. Open this file:
"[PROJECT]\node_modules\react-native-paper\src\components\Snackbar.tsx"

2. Go to line 210. You might have:
`<Text
          style={[
            styles.content,
            { marginRight: action ? 0 : 16, color: colors.surface},
          ]}
        >
          {children}
        </Text>`

3. Change this to:

`
<Text
          style={[
            styles.content,
            { marginRight: action ? 0 : 16, color: colors.surface, textAlign:'center' },
          ]}
        >
          {children}
        </Text>
`

**NOTE: textAlign:'center' ADDED!**

4. Save it.

**NOTE: This method sets the `textAlign` to `center` for all Snackbars inside the project.**

**Suggestion #3456 **
You can add `textAlign` props to this file (**Snackbar.tsx**) to solve this problem and set `textAlign` of message to desired options (`left`,`center`,`right`):

**NEW SUGGESTED FILE**

1. **LINE: 108** Add `textAlign = 'left'` to the component props with default value of `left`...
2. **LINE: 210** Add `textAlign: textAlign` to the `<Text>` style of `<Surface>`...
3. **USAGE**: Importing component in your project, you can set the `textAlign` like this:
`...
<Snackbar
   ...
   textAlign='center'
   ...>
...`

_New added contents are selected in the screenshot._
![image](https://user-images.githubusercontent.com/62894314/199460027-dfade940-17d2-4fec-b98a-d47fd241fc0e.png)

Thanks for reading 🌝

**Comment by lukewalczak** [comment]
Closing the feature request according to the [explanation](https://github.com/callstack/react-native-paper/pull/3456#issuecomment-1312206734) attached in the PR associated with that request.
