### ISSUE TITLE
Can't install @react-navigation/material-bottom-tabs alongside release candidate

### ISSUE THREAD

**Issue by jardvanroest** [callstack/react-native-paper#3451]
### Current behaviour
@react-navigation/material-bottom-tabs can't be installed alongside release candidate.

### Expected behaviour
I expect this to be possible, since the newest release candidate has a version >= 3.0.0

### How to reproduce?
When I do npm i @react-navigation/material-bottom-tabs, it gives the error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: snelmelder@1.0.0
npm ERR! Found: react-native-paper@5.0.0-rc.9
npm ERR! node_modules/react-native-paper
npm ERR!   react-native-paper@"^5.0.0-rc.9" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-paper@">= 3.0.0" from @react-navigation/material-bottom-tabs@6.2.4
npm ERR! node_modules/@react-navigation/material-bottom-tabs
npm ERR!   @react-navigation/material-bottom-tabs@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\jardv\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jardv\AppData\Local\npm-cache\_logs\2022-11-02T15_13_49_745Z-debug-0.log

### What have you tried so far?
I've tried using --force, which makes the code work, but of course this is not a permanent solution. I've also Googled to see if more people have this issue. There's an issue open on react-navigation about this, but the documentation of react-navigation recommends to post issues with material-bottom-tabs here instead of on their repo.

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.68.2
| react-native-paper    | ^5.0.0-rc.9
| node                            | 16.17.0
| npm                            | 8.15.1
| expo sdk                     | 46

**Comment by okwasniewski** [comment]
Hey @jardvanroest, 

Can you try installing this with yarn? Using this command: `yarn add @react-navigation/material-bottom-tabs`. It has better algorithm of resolving dependencies. And most probably will work 😄 If not please provide a minimal github repro repository were this problem occurs.

**Comment by okwasniewski** [comment]
I think I came up with a solution. There is an open proposal [here](https://github.com/npm/rfcs/pull/397) to support this use case by `npm`. Right now `@react-navigation/material-bottom-tabs` has a peer dependency on `react-native-paper` as `>= 3.0.0` but version `5.0.0-rc.9` is not being recognized as higher than `3.0.0`. 

A quick workaround for this would be to add this to your `package.json`

```json
"overrides": {
    "@react-navigation/material-bottom-tabs": {
      "react-native-paper": "^5.0.0-rc.9"
    }
  }
```

Let me know if this fixes the issue 😀

**Comment by jardvanroest** [comment]
@okwasniewski This workaround fixed it for me

**Comment by okwasniewski** [comment]
Thanks @jardvanroest, closing this 👍🏻

**Comment by dwbra** [comment]
Thanks for this workaround!

**Comment by DevRSC** [comment]
@okwasniewski, Thanks this workaround fixed my problem.
