### ISSUE TITLE
Text Secury "eye" enable KeyBoard

### ISSUE THREAD

**Issue by Lucasark** [callstack/react-native-paper#3453]
### Current behaviour
I don't know if it is necessary a bug. When I click on affix icon from InputText it enable keyboard too.

### Expected behaviour
I think the common behaviour is just "enable/disable" securyText without enable keyboard.

### How to reproduce?
I used InputText from example on documentation

### Your Environment

| software                      | version
| --------------------- | -------

**Comment by lukewalczak** [comment]
Hey @Lucasark, if you don't want to focus input when pressing right icon you can pass into it the prop `forceTextInputFocus={false}`, like on the following [snack](https://snack.expo.dev/@react-native-paper/textinput-securetextentry).
