### ISSUE TITLE
[5.0.0-rc.9] SearchBar component not respecting default font

### ISSUE THREAD

**Issue by bombillazo** [callstack/react-native-paper#3458]
### Current behaviour
The `Searchbar` component is not utilizing the custom default font set in the RNP theme.

### Expected behaviour
Component renders using the custom theme font.

### How to reproduce?
Simply use the `Searchbar` component using a custom font.

### Preview
I believe the issue lies here in the Searchbar component logic:

```ts
style={[
  styles.input,
  {
    color: textColor,
    ...(!isV3 && theme.fonts.regular),
    ...Platform.select({ web: { outline: 'none' } }),
  },
  inputStyle,
]}
```

### What have you tried so far?
To circumvent this, Im using the `inputStyle` prop to override the incorrect default:

```ts
inputStyle={{
  fontFamily: theme.fonts.bodyLarge.fontFamily,
}}
```

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | 5.0.0-rc.9
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hey @bombillazo, would you like to handle the support for it in the `Searchbar`, by adding the ternary expression there `theme.isV3 ? theme.fonts.default : theme.fonts.regular`?

**Comment by bombillazo** [comment]
Sure, what branch should I use as base and to what branch should I create the PR?

**Comment by lukewalczak** [comment]
Main branch as a base and target. Please also check the contribution guide linked in the readme. Thanks!

**Comment by bombillazo** [comment]
PR pending approval

**Comment by lukewalczak** [comment]
Thanks @bombillazo, will handle that in my spare time!
