### ISSUE TITLE
Ios : Can't use TextInput affix with clearButtonMode 

### ISSUE THREAD

**Issue by arochedy** [callstack/react-native-paper#3459]
### Current behaviour
Can't use TextInput affix with clearButtonMode => both affix and clear button are on stacked
### Expected behaviour
get the clear button on the left of the affix and not at the same plac e

### How to reproduce?
    <TextInput
            clearButtonMode="always"
             right={<TextInput.Affix text="test" />}
             
    />

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.70.2
| react-native-paper    |4.11.2
| node                            | x.x.x
| npm or yarn                | npm
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hey @arochedy, I think `TextInput` is not capable to handle properly both right affix and clear icon displayed due to `clearButtonMode`, so I would suggest avoiding mixing those two props.
