### ISSUE TITLE
Card Roundness

### ISSUE THREAD

**Issue by kdutcher** [callstack/react-native-paper#3460]
Is the Card component supposed to follow the same roundness guidelines as button?

In Card.tsx, the Surface component's borderRadius is set the value of roundness on line 225.

In Button.tsx, the Surface component's borderRadius is set to a multiple of roundness base on version.
Line 233:
const borderRadius = (isV3 ? 5 : 1) * roundness;

I was expecting Card to behave like Button.

**Comment by lukewalczak** [comment]
Closing via: https://github.com/callstack/react-native-paper/pull/3465
