### ISSUE TITLE
How to split a column further in DataTable 

### ISSUE THREAD

**Issue by christopher-18** [callstack/react-native-paper#3461]
I need to split the column into further columns. How to achieve it? 

Sno.         Name                    Age
               FName LName.       
1             Chris.     Evan.         78
2.            Harry.    C.               29

**Comment by lukewalczak** [comment]
Hey @christopher-18, it's not clear for me what are you trying to achieve, could you please present some visuals?

**Comment by christopher-18** [comment]
@lukewalczak  
Something like this (the last two columns)
<img width="438" alt="Screenshot 2022-11-09 at 19 04 46" src="https://user-images.githubusercontent.com/23613887/200843915-2cf8ac1e-dc7a-40df-87d6-00040a1283a1.png">

**Comment by lukewalczak** [comment]
I think that `DataTable` may not supporting that layout.
