### ISSUE TITLE
Android elevation/shadow issue

### ISSUE THREAD

**Issue by iM-GeeKy** [callstack/react-native-paper#3467]
### Current behaviour

Navigating around the example app below on Android results in an odd elevation/shadow rendering issue. Note, this behavior isn't present on iOS. This problem seems to be intermittent  and I'd suspect this might be an upstream issue, but I want to post it here as it indirectly affects this repository and to bring visibility to the matter.

### Expected behaviour

The shadow should behave in a consistent manor without the shadow flickering.

### How to reproduce?

https://github.com/iM-GeeKy/shadows-bug

### Preview

This video was captured in Expo Go on a Pixel 5a running Android 13.
https://user-images.githubusercontent.com/7604441/201551315-70020fb4-ee8f-4516-b6ba-aafe6a1efcf5.mov

### What have you tried so far?

I haven't quite been able to pin down a solution, but I did find a few threads that relate to the issue.
- https://github.com/facebook/react-native/issues/23090
- https://github.com/callstack/react-native-paper/issues/1349

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | 13
| react-native                | 0.70.5
| react-native-paper    | 5.0.0-rc.9
| node                            | v16.16.0
| npm or yarn                | yarn
| expo sdk                     | 47.0.3

**Comment by iM-GeeKy** [comment]
@lukewalczak Do you have any ideas on this? I'm still seeing this behavior and am not sure if it's just a react-native issue or if it's a direct result of this library.

**Comment by lukewalczak** [comment]
Hey @iM-GeeKy, unfortunately didn't check that, however I will try to address the issue.

**Comment by dalenaval** [comment]
Currently facing the same issue

**Comment by iM-GeeKy** [comment]
Hi @lukewalczak and @tjaniczek, I'm reopening this issue with the release of Expo 49. I've reproduced the example in the same repo under the sdk-49 branch [here](https://github.com/iM-GeeKy/shadows-bug/tree/sdk-49).

**Comment by iM-GeeKy** [comment]
> Hi @lukewalczak and @tjaniczek, I think this issue should be reopened with the release of Expo 49. I've reproduced the example in the same repo under the sdk-49 branch [here](https://github.com/iM-GeeKy/shadows-bug/tree/sdk-49).

Should I reopen this issue again or will it be tracked in this thread?
