### ISSUE TITLE
Option to remove "elevation" for Toolbar (shadow)

### ISSUE THREAD

**Issue by karelnet** [callstack/react-native-paper#347]
### Current behaviour

I couldn't manage to remove the shadow from the toolbar (on android)

### Expected behaviour

A option to remove the shadow (elevation :0)

**Comment by Trancever** [comment]
Hi. Just pass style prop with elevation set to 0. ```<Toolbar style={{ elevation: 0 }} />```

**Comment by Rajan-Savaliya-spt** [comment]
style={{ elevation: 0 }}  this is work for me to
