### ISSUE TITLE
[5.0.0-rc.9] TextInput right and left props not displaying

### ISSUE THREAD

**Issue by kedaitayar** [callstack/react-native-paper#3470]
### Current behaviour
TextInput not displaying icons from the right and left props

### Expected behaviour
TextInput to display icons from the right and left props

### How to reproduce?
Reproducible from the [example app](https://snack.expo.dev/@react-native-paper/react-native-paper-example_v5)

### Preview
![Preview](https://user-images.githubusercontent.com/49740904/201830957-6d43b91a-58bc-4957-bf25-97c94b6b7849.png)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.69.7
| react-native-paper    | 5.0.0-rc.9
| node                            | x.x.x
| npm or yarn                | yarn
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hey @kedaitayar, fixed the snack, it should be correct right now.
