### ISSUE TITLE
SegmentedButtons are not equal in widths. Reference M3 Material Design.

### ISSUE THREAD

**Issue by maximilianotaverna** [callstack/react-native-paper#3481]
The Button items are shrinking and not stretching to to create equal widths. Therefore labels with shorter names have smaller widths.

Reading the documentation from Material Design, the [SegmentedButtonItem](https://github.com/callstack/react-native-paper/blob/main/src/components/SegmentedButtons/SegmentedButtonItem.tsx) does not meet the material guidelines specifications. 

See [dynamic based on labels, but fixed (equal segments)](https://m3.material.io/components/segmented-buttons/specs) in the layout section. The illustration shows 3 buttons with a width of 1/3 each.

Can be corrected by adding flex: 1 to [SegmentedButtonItem.tsx](https://github.com/callstack/react-native-paper/blob/main/src/components/SegmentedButtons/SegmentedButtonItem.tsx)

`const styles = StyleSheet.create({
  button: {
    flex: 1,
    minWidth: 76,
    borderStyle: 'solid',
  },
  label: {
    textAlign: 'center',
  },
  content: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    paddingHorizontal: 16,
  },
});`

**Comment by lukewalczak** [comment]
Hey @maximilianotaverna, I have seen that you already provided the PR fixing the issue, but could you please attach the snack presenting the issue?

**Comment by maximilianotaverna** [comment]
Hey @lukewalczak , thank you. Here is the [snack](https://snack.expo.dev/wZwRqhuf-).
