### ISSUE TITLE
Snackbar duration bug

### ISSUE THREAD

**Issue by suleymanbariseser** [callstack/react-native-paper#3486]
### Current behaviour
Duration prop does not work in Snackbar. Timer resets whenever onDismiss function updates. It means even when a state changes it will reset the timer.

### Expected behaviour
Duration prop must be independent from any other state and prop.

### How to reproduce?
[Here](https://snack.expo.dev/@suleymanbariseser/react-native-paper-snackbar-issue) is a snack where this issue can be reproducable. 

### What have you tried so far?
The problem about this is adding onDismiss into dependency array of the useEffect which handles the timer in the Snackbar component. However, this is needed because onDismiss must be triggered whenever time will be over and we must trigger the latest version of onDismiss function. The problem can be solved by moving the logic inside the useEffect into event functions and trigger them in the useEffect whenever `visible` updates. The problem and the solution is described [here](https://beta.reactjs.org/learn/separating-events-from-effects#extracting-non-reactive-logic-out-of-effects) in detail. In the detailed url, it is solved by useEvent but useEvent is still an experimental hook. That's why, an alternative hook([useEventCallback](https://www.npmjs.com/package/use-event-callback)) can be used to achieve the same goal.

### Your Environment

| software                      | version
| --------------------- | -------
| react-native-paper    | 4.9.2

**Comment by brucewyne** [comment]
is this issue back? I'm able to reproduce this in 5.2.0

**Comment by suleymanbariseser** [comment]
I tested it with the 5.2.0 and it works fine.
Snack: https://snack.expo.dev/vrTsCQdev

**Comment by brucewyne** [comment]
yup - my bad. I hadn't properly setup my dismiss handler. Dismiss :)

**Comment by ecexplorer** [comment]
I actually ran into this issue updating v4 -> v5. Looking into the source I noticed that some of the state hinges around the `visible` prop, including clearing out the timer.  
In v4 we had:
```typescript
setDuration(3000)
setVisibility(true)
```
but in v5 that would cause the Snackbar to only show/flash briefly. Switching it around to:
```typescript
setVisibility(true)
setDuration(3000)
```
seems to have done the trick
