### ISSUE TITLE
Appbar has no padding when not using centered text or back button

### ISSUE THREAD

**Issue by arjendevos** [callstack/react-native-paper#3490]
### Current behaviour
When using the appbar with only content, it does not apply any padding to the left side of the appbar.
```tsx
<Appbar.Header>
   <Appbar.Content title={'Mand'} />
</Appbar.Header>
```

I think it has to do with this line:
[https://github.com/callstack/react-native-paper/blob/main/src/components/Appbar/Appbar.tsx#L219](https://github.com/callstack/react-native-paper/blob/main/src/components/Appbar/Appbar.tsx#L219)

```tsx
shouldAddLeftSpacing = shouldCenterContent && leftItemsCount === 0;
```

If i don't center the content, `shouldAddLeftSpacing` will always be false, even if `leftItemsCount` is zero.

![Screenshot 2022-11-25 at 15 10 48](https://user-images.githubusercontent.com/67794681/204002626-8d8e6510-7e51-4695-8a87-7fb5eaaa0b2f.png)

I am using version: `Release 5.0.0-rc.10`

### Solution
```tsx
shouldAddLeftSpacing = leftItemsCount === 0;
```

**Comment by lukewalczak** [comment]
Hey @arjendevos, I was not able to reproduce it. Based on your code I've created the following [snack](https://snack.expo.dev/@react-native-paper/appbar_only_content).

**Comment by RichardLindhout** [comment]
@arjendevos It's because we override the appbar component 
```
        if (child.type === AppbarContent) {
 ```
 
 We could change this to use the native app bar but we need to change the SafeAreaView to safe-area-context because the one from react-native has flickering :)

**Comment by RichardLindhout** [comment]
Issue can be closed

**Comment by RichardLindhout** [comment]
https://github.com/callstack/react-native-paper/issues/3491
