### ISSUE TITLE
Fonts List.Item not working in M3

### ISSUE THREAD

**Issue by RobinLindhout** [callstack/react-native-paper#3501]
![Schermafbeelding 2022-12-01 om 12 07 17](https://user-images.githubusercontent.com/79744544/205037457-47daae9b-aead-4449-a0c0-211df1eced6e.png)

**Comment by lukewalczak** [comment]
Hey @RobinLindhout, could you please attach the snack presenting the issue or provide more details about the bug?

**Comment by RichardLindhout** [comment]
@lukewalczak the Text does not have a variant so when no global font is used and a font per variant we can't override the font of thelist item with Material You

**Comment by RichardLindhout** [comment]
E.g. here:
https://github.com/callstack/react-native-paper/blob/main/src/components/List/ListItem.tsx#L207

**Comment by lukewalczak** [comment]
`List.Item` is using the `Text` from the Paper's typography, which in the case when the variant is not specified, is applied the `default` [variant](https://github.com/callstack/react-native-paper/blob/main/src/components/Typography/Text.tsx#L131) from the fonts

**Comment by RichardLindhout** [comment]
Ahh, we will add the default variant then, it was not specified in the docs

**Comment by RobinLindhout** [comment]
![Schermafbeelding 2022-12-01 om 14 09 49](https://user-images.githubusercontent.com/79744544/205061097-fde5569a-5f14-4490-8d66-ac977c2ea803.png)

**Comment by lukewalczak** [comment]
> Ahh, we will add the default variant then, it was not specified in the docs

:( I will keep the issue opened to not forget about updating the docs, unless you would like to do that
