### ISSUE TITLE
Menu position is wrong when changing size of window

### ISSUE THREAD

**Issue by mathias-berg** [callstack/react-native-paper#3515]
### Current behaviour
The position of the menu does not update when changing size of the browser window.

### Expected behaviour
Menu position should render at the anchor that I have specified in the code.

### How to reproduce?
Go to the snack below. Choose web as client, make the preview show in a separate window.
Show the menu, close the menu, make the window more wider. Try to open the menu again. It should render at "show menu" but is instead rendered at the position the "show menu" button first was rendered.

https://snack.expo.dev/@fyranollfyra/faulty-menu-position-when-changing-size

(the same goes for the height also actually. Take the same separate browser window and make it the smallest height. Then reload the window, expand the height as much as you can, then open the menu again. Now the height of the menu is "cropped" and you have to scroll inside the menu to get to all options).

This also happens on iOS for example. Run the snack in Expo Go with your device in portrait mode. Turn it to landscape and the menu renders in the wrong place.

### Preview

Width:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/26097801/206369051-f348f756-4ac3-4670-8d58-e29b316313ca.png">
<img width="1515" alt="image" src="https://user-images.githubusercontent.com/26097801/206369134-4cb233c5-690e-4a6c-94f1-569922db65bd.png">

Height: 
<img width="329" alt="image" src="https://user-images.githubusercontent.com/26097801/206368811-74c5a3c0-c7c3-498c-80bb-30ac39cde17c.png">
<img width="325" alt="image" src="https://user-images.githubusercontent.com/26097801/206368858-5ba0bfd1-dc12-4213-8462-2dbebec06787.png">

### What have you tried so far?
It works fine with 5.0.0-rc.8, but after that version this could be reproduced by following the above steps.

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.70.5
| react-native-paper    | 5.0.1
| node                            | 16.13.1
| yarn                             | 1.22.9
| expo sdk                     | 47.0.0

**Comment by lukewalczak** [comment]
Hey @mathias-berg, would you like to identify the source of the issue and try to fix that?

**Comment by mathias-berg** [comment]
Hi @lukewalczak,

Yes, I just checked the difference between RC8 and RC9 (where this was introduced) and I think I see why this is happening. The dimensions is not set inside the Menu component with RC9 so they don't update unless you refresh everything.

I can try to fix a PR for this.

**Comment by mathias-berg** [comment]
@lukewalczak , PR is up!
