### ISSUE TITLE
Custom height for Button

### ISSUE THREAD

**Issue by ButuzGOL** [callstack/react-native-paper#352]
When i set custom button height with 
```
        <Button
            style={{
              marginTop: 20,
              height: 50,
              marginLeft: 0,
              marginRight: 0,
              justifyContent: 'center',
            }}
            loading={loading}
            raised
            compact
            primary
            onPress={this.onSubmit}
          >
            {t('signIn')}
          </Button>
```

i see on touch start

![screen shot 2018-05-07 at 3](https://user-images.githubusercontent.com/196564/39702751-7a559d0c-520e-11e8-88ef-9a13a39ec88b.png)

is there any way to do 
Hover effect all over button ?

**Comment by esalberg100** [comment]
Any plans for this issue to be solved?

**Comment by satya164** [comment]
@esalberg100 try `contentStyle` prop

**Comment by esalberg100** [comment]
> @esalberg100 try `contentStyle` prop

Thanks, I created 2 different styles `style={styles.buttonStyle} contentStyle={styles.buttonContentStyle}` and setting the `height` to 50 in the `buttonContentStyle` worked.

**Comment by ZeeshanAhmadKhalil** [comment]
Giving padding also works

**Comment by amancodify** [comment]
pass this prop 'contentStyle' in the button and put the same height(or any css changes) which was in style prop.
