### ISSUE TITLE
Jest <SafeAreaProviderCompat> Error

### ISSUE THREAD

**Issue by iM-GeeKy** [callstack/react-native-paper#3520]
### Current behaviour

Upon upgrading to version `5.0.1` or `5.0.0`, Jest tests appear to be failing because of the `<SafeAreaProviderCompat>` component.

### Expected behaviour

Is there a recommended way to mock the `SafeAreaProviderCompat`, so that tests run as they did in previous versions?

### How to reproduce?

Checkout the `README.md` in https://github.com/iM-GeeKy/paper-5-test

### Preview

Personal laptop information hidden, but here is a screenshot of the Jest output. The same output can be generated via the provided repo.
![Group 601](https://user-images.githubusercontent.com/7604441/206595127-f84e4117-03b4-47d6-8cfe-d13e4defe825.png)

### What have you tried so far?

Tests don't fail using `[Release 5.0.0-rc.10](https://github.com/callstack/react-native-paper/releases/tag/v5.0.0-rc.10)` and perhaps the issue can be traced back to this issue https://github.com/callstack/react-native-paper/issues/3506 that was introduced in version `5.0.0`.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 16.1
| android                        | x
| react-native                | 0.70.5
| react-native-paper    | 5.0.1
| node                            | v16.16.0
| npm or yarn                | yarn
| expo sdk                     | 47.0.8

**Comment by lukewalczak** [comment]
Hey @iM-GeeKy, I guess you are missing `react-native-safe-area-context` mocking. You can check the [testing](https://github.com/th3rdwave/react-native-safe-area-context#testing) section in that library or you can try the `mock` below: 

```
jest.mock('react-native-safe-area-context', () => ({
  useSafeAreaInsets: () => ({ bottom: 34, left: 0, right: 0, top: 47 }),
}));
```

**Comment by iM-GeeKy** [comment]
> 

Thanks for the quick reply. The [testing](https://github.com/th3rdwave/react-native-safe-area-context#testing) section seemed to give way to the solution.
