### ISSUE TITLE
Is there any way to decrease the margin on the InternalTextInput when an icon is used?

### ISSUE THREAD

**Issue by idiomattic** [callstack/react-native-paper#3522]
### Ask your Question
There is 56 margin on the left of a `TextInput` when using a `TextInput.Icon` and that's taking up too much space in certain areas.  Is there any way I can overwrite that?

![Simulator Screen Shot - iPhone 14 - 2022-12-10 at 12 58 24](https://user-images.githubusercontent.com/63416154/206875212-591eb876-6fdb-463c-9bbf-33bc25ec8741.png)

**Comment by lukewalczak** [comment]
Should be possible after adding prop for input container style: https://github.com/callstack/react-native-paper/pull/3509
