### ISSUE TITLE
Error while using 5.0.x

### ISSUE THREAD

**Issue by capella55** [callstack/react-native-paper#3523]
### Current behaviour
I was using `5.0.0-rc.8` and installed 5.0.1 but see the errors while running the iOS app.
```
ERROR  TypeError: Cannot read property 'colors' of undefined, js engine: hermes
ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

```
### Expected behaviour
It should work without any issues.

### What have you tried so far?
I tried to use 5.0.0 and 5.0.1 but both didn't work.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 16.1
| react-native                | 0.70.3
| react-native-paper    | 5.0.1
| node                            | 16.13.0
| npm                             | 8.1.0

**Comment by lukewalczak** [comment]
Hey @capella55, could you please create a sample github repo presenting your issue?

**Comment by Aliendreamer** [comment]
https://github.com/Aliendreamer/ExploringJsEcoSystem/tree/master/test hello here is an example. 
I had the same issue and tried to investigate in smaller project today it happens every time. basically if you follow the steps in your tutorial.

**Comment by lukewalczak** [comment]
Hey @Aliendreamer, once I will find some time will check your repo.
