### ISSUE TITLE
How to change Textinput placeholder and text color in version 5.0.1

### ISSUE THREAD

**Issue by harshps08** [callstack/react-native-paper#3526]
I have tried to implement react native paper textinput in outlined mode, I want to change the color of placeholder and also the text value after input , but I am unable to do so 
I have attached the snack link below
(first text input placeholder color and text value)
https://snack.expo.dev/uEaFRaaIl

"react-native-paper":5.0.1,
"react-native": 0.67,

I have mutltiple options like making changes in theme , but nothing seems to work.

**Comment by lukewalczak** [comment]
Hey @harshps08, for changing the placeholder you can override `theme.colors.onSurfaceVariant` _(I will check whether it should be possible also by specifying `placeholderTextColor`)_ . For text color you can use `textColor` prop:

```
      <TextInput
        mode="outlined"
        label="Remitter Mobile Number"
        theme={{ colors: { onSurfaceVariant: 'white'} }}
        style={{ backgroundColor: '#626262' }}
        activeOutlineColor="white"
        placeholder="placeholder"
        outlineColor="white"
        textColor="white"
        onChangeText={(text) => setValue(text)}
        autoCapitalize="none"
        blurOnSubmit={false}
        keyboardType="number-pad"
        returnKeyType="done"
        maxLength={10}
        value={Value}
      />
```

**Comment by sguidotti** [comment]
Thank you I have been looking for this answer forever!

**Comment by chrised123** [comment]
@lukewalczak Its not possible to override it using `placeholderTextColor` right?

**Comment by dhatrishdixit** [comment]
textColor prop is removed or some thing ?? is there any other way

**Comment by Stefan98167** [comment]
How to change the text size?

**Comment by Harikaran99** [comment]
@Stefan98167
you can use contentStyle prop like this         
`<Input
      contentStyle={{
          fontFamily: 'Nunito-Light',
          fontSize: 23,
          paddingLeft: 20,
        }}
/> this will change the placeholder font size and actual size. i hope this is help for you 😊

**Comment by Stefan98167** [comment]
Thank you, I will look into it.
