### ISSUE TITLE
New required props in TextInput component

### ISSUE THREAD

**Issue by bombillazo** [callstack/react-native-paper#3527]
### Current behaviour
TextInput props set to required

### Expected behaviour
Various Textinput props are optional

### How to reproduce?
Import the TextInput object from react-native-paper and as soon as you try to use it, Typescript will warn you about missing required fields

### Preview
![image](https://user-images.githubusercontent.com/44002321/207748597-a2d710c6-4ad1-4a79-bcb0-c71bc684726e.png)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.69.8
| react-native-paper    | 5.0.1
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Adding `@types/react-native@0.70.7` should solve your issue.

**Comment by bombillazo** [comment]
Yup! that did it , thanks!
