### ISSUE TITLE
Animation error when tapping on an `FAB.Group` action label

### ISSUE THREAD

**Issue by atheck** [callstack/react-native-paper#3529]
### Current behaviour

When tapping on the label (not the icon) of a `FAB.Group` action an error occurs:

"Attempting to run JS driven animation on animated node that has been moved to "native" earlier by starting an animation"

Everything works as expected when tapping on the icon of an action.

### Expected behaviour

No error.

### How to reproduce?

1. Display a `FAB.Group` with actions
2. Tap on the label of an action

### What have you tried so far?

It is working with v4 of react-native-paper.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | -
| android                        | 12, 13
| react-native                | 0.69.7
| react-native-paper    | 5.0.1
| node                            | 18.12.0
| npm or yarn                | npm 8.19.2
| expo sdk                     | -

**Comment by kamatsuoka** [comment]
Confirming this with react-native 0.70.6 on android. Despite the error, the fab action onPress works normally.
No error seen on ios.

**Comment by lukewalczak** [comment]
Fixed pushed via commit: https://github.com/callstack/react-native-paper/commit/a981d5c4bc0e877273d1486b4f0429a496058bbe. Will be released in the next update.

**Comment by atheck** [comment]
Thank you a lot. 🙂
