### ISSUE TITLE
[Native] TextInput flex/height issue

### ISSUE THREAD

**Issue by bombillazo** [callstack/react-native-paper#3530]
### Current behaviour
The default TextInput component height is stretched to occupy the space it is inside of.

### Expected behaviour
The TextInput height is set to the default calculated height

### How to reproduce?

Import the TextInput component from RNP. The component is unclickable and occupies full height. By commenting the`flexGrow` property in the `styles.input` style inside the RNP TextInput component, the issue is fixed.

![image](https://user-images.githubusercontent.com/44002321/207874667-0dbe8144-dece-4a0a-83d4-cc4379bffab3.png)

### Preview

👉  [Snack](https://snack.expo.dev/@bombillazo/suspicious-ramen)

<img width="358" alt="image" src="https://user-images.githubusercontent.com/44002321/207874143-07533b9b-76f4-42c5-bf16-eb152295399e.png">

With `flexGrow` commented:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/44002321/207874228-f75fafdb-6bef-4f22-b80d-69cf2f8771a6.png">

### What have you tried so far?

I tried overriding flexGrow with props but that particular internal component does not accept any styling from props. At the moment, we're using patch-package to fix the issue.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.70.8
| react-native-paper    | 5.0.2
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hey @bombillazo, please attach the snack.

**Comment by bombillazo** [comment]
@lukewalczak here you go!

**Comment by bombillazo** [comment]
Seems the issue appears when using alignItems style

**Comment by bombillazo** [comment]
Is this a good pattern though? now I have to add flexDirection to all wrappers that have a TextInput? 🤔

**Comment by lukewalczak** [comment]
> Is this a good pattern though? 

I think it's ok, until I investigate the component behaviour and confirm whether we can remove mentioned `flexGrow: 1`.

**Comment by bombillazo** [comment]
Ok as a temporary fix sure, looking forward to that confirmation, and that PR as well!
