### ISSUE TITLE
Menu position is wrong when rotate device

### ISSUE THREAD

**Issue by chukiatt** [callstack/react-native-paper#3533]
### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hey @chukiatt it will be fixed once https://github.com/callstack/react-native-paper/pull/3521 is merged.
