### ISSUE TITLE
[Card] Add support for `delayLongPress`

### ISSUE THREAD

**Issue by fabriziocucci** [callstack/react-native-paper#3534]
**Is your feature request related to a problem? Please describe.**
We have a list of cards that support drag-and-drop and the default `delayLongPress` value is unfortunately too high. We ended up copying the `Card` code to benefit of the `onPress` animation just to lower the default `delayLongPress` value of the `TouchableWithoutFeedback` [here](https://github.com/callstack/react-native-paper/blob/main/src/components/Card/Card.tsx#L256).

**Describe the solution you'd like**
It would be great to support `delayLongPress` on the `Card` component.

**Describe alternatives you've considered**
Wrapping the `Card` content in a `Pressable` component and the `Card` itself in a `Pressable` component. None of that worked.

**Additional context**
N/A.

**Comment by lukewalczak** [comment]
Hey @fabriziocucci, make sense, I will handle that.
