### ISSUE TITLE
Issue with main site API documentation

### ISSUE THREAD

**Issue by bobOnGitHub** [callstack/react-native-paper#3535]
If I land at https://reactnativepaper.com/
and follow the link at the bottom of the page for docs it brings me to https://callstack.github.io/react-native-paper/index.html where I can see only "text" under "Typography" in the left hand panel.

Inserting a version number into that url to get to https://callstack.github.io/react-native-paper/4.0/index.html
shows the page with all the "Typography" items listed in the left hand panel (Paragraph, Title etc)

I only discovered this when looking at the usage notes for your recommended https://github.com/web-ridge/react-native-paper-tabs - it uses Paragraph which I couldn't then find in your docs (a web search found the correct url)

Same for Docs button at start of web page.

(Firefox Developer 109.0b2 (64-bit))

**Comment by bobOnGitHub** [comment]
Though it seems the alternative url (with the version) leads to content which is then missing other content present at the original url eg. under "Drawer".

**Comment by fabriziocucci** [comment]
> ...where I can see only "text" under "Typography" in the left hand panel.

@bobOnGitHub this is actually expected and a breaking change introduced in V5.

See the [Typography](https://callstack.github.io/react-native-paper/introducing-v5-with-material-you.html#typography) section of the migration guide.
