### ISSUE TITLE
Absolute positioning with start/end properties is broken on iOS

### ISSUE THREAD

**Issue by szaboopeeter** [callstack/react-native-paper#3542]
### Current behaviour
Using a `<Card>` component and `absolute`-positioning it relative to the `start` or `end` of it's parent doesn't work as expected. It will position relative to an `AnimatedContentWrapper` component which is an implementation detail of `react-native-paper`.

Note: Positioning with `right` or `left` as opposed to `start` or `end` works as intended, as well as `start` and `and` working as intended on Android and Web.

### Expected behaviour
The expected behavior in this case (assuming LTR layout) is for the `<Card>` to be right-aligned relative to its parent.
Please refer to the docs: https://reactnative.dev/docs/layout-props#end
<br/>The behavior should be identical to what happens with right alignment.

### How to reproduce?
A minimal repro would be just nesting a `<Card>` inside a `<View>`, with absolute-positioning, and end property set, such as:

```javascript
<View style={{ flex: 1 }}>
    <Card style={
        {
          position: 'absolute',
          end: 0
        }}>
          <Text>I would like to be end-aligned!</Text>
    </Card>
</View>
```

Please refer to a similar repro in my repo: https://github.com/szaboopeeter/rnp-card-absolute-end-ios-bug/blob/main/CardBug/App.tsx

### Preview
End-alignment with `end: 0` does not work:

<img src="https://raw.githubusercontent.com/szaboopeeter/rnp-card-absolute-end-ios-bug/main/BugDescriptionAssets/end-aligned-card.png" width="600" alt="Demonstration of buggy end-alignment"/>

Because the `<AnimatedComponentWrapper>` in the component hierarchy to drops the `end` style:

<img src="https://raw.githubusercontent.com/szaboopeeter/rnp-card-absolute-end-ios-bug/main/BugDescriptionAssets/end-aligned-wrapper.png" width="600" alt="Demonstration of buggy end-alignment causing AnimatedComponentWrapper to drop the end property"/>

The expected behavior is the same as it is with `right: 0`:

<img src="https://raw.githubusercontent.com/szaboopeeter/rnp-card-absolute-end-ios-bug/main/BugDescriptionAssets/right-aligned-card.png" width="600" alt="Demonstration of working right-alignment"/>

### What have you tried so far?

I was able to track this down to the current implementation of the `<Surface>` component for iOS in `react-native-paper`, where some of the relevant properties are skipped from `absoluteStyles`, and only later attached to the component hierarchy as `restStyle`: https://github.com/callstack/react-native-paper/blob/v5.1.0/src/components/Surface.tsx#L224

Seems related to this change: https://github.com/callstack/react-native-paper/pull/3239/files

This causes the `<AnimatedComponentWrapper>` in the component hierarchy to drop the `end` style that was passed to the `Card`. See the style props of the component on screenshot below:

<img src="https://raw.githubusercontent.com/szaboopeeter/rnp-card-absolute-end-ios-bug/main/BugDescriptionAssets/end-aligned-wrapper.png" width="600" alt="Demonstration of buggy end-alignment causing AnimatedComponentWrapper to drop the end property"/>

I'd be happy to open a PR if you can confirm that this is an actual bug, and we can agree on a solution - which seems to be to just pass additional props that are relevant to absolute-positioning to `absoluteSytles` (considering the shadow-layering seems like an intentional difference on iOS).

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 16.2
| android                        | n/a
| react-native                | 0.70.6
| react-native-paper    | 5.1.0
| node                            | 16.15.1
| yarn                             | 1.22.19
| expo sdk                     | n/a

**Comment by lukewalczak** [comment]
> I'd be happy to open a PR if you can confirm that this is an actual bug, and we can agree on a solution - which seems to be to just pass additional props that are relevant to absolute-positioning to absoluteSytles (considering the shadow-layering seems like an intentional difference on iOS).

Hey @szaboopeeter, thanks for reporting the bug and providing its analysis. I agree with you on the proposed solutions, by extending the `absoluteStyles` with missing props. If you would like to open a PR with unit tests I will be more than happy 🙌🏽 
Cheers!
