### ISSUE TITLE
Components cannot be imported in v5

### ISSUE THREAD

**Issue by Volper212** [callstack/react-native-paper#3545]
### Current behaviour

> Error: Unable to resolve module `react-native-paper/lib/module/components/IconButton` from `PROJECT\src\Navigator.tsx`: `react-native-paper/lib/module/components/IconButton` could not be found within the project or in these directories:
>   `node_modules`

TypeScript shows no issue with the types
### Expected behaviour
No error

### How to reproduce?
Install v5 and use this:
```ts
import { IconButton } from "react-native-paper";
```

### Preview
![image](https://user-images.githubusercontent.com/47470991/209214697-a56ab53b-ec80-4759-81f8-cd7a7659951d.png)

I looked into `node_modules` and maybe this is the problem:

![image](https://user-images.githubusercontent.com/47470991/209214971-979029c2-8263-4dfe-98de-cadb57083a6c.png)
I think you should try adding an index.js that exports the IconButton or something because it appears to be just a problem with importing.

### What have you tried so far?
Downgrade, works at v4.12.5 (before v5).

Then I decided to change all the occurences of importing TextButton to this:
```ts
import IconButton from "react-native-paper/src/components/IconButton/IconButton";
```
This removed the error about the IconButton, however now a similar error occurs with Paragraph:

> Error: Unable to resolve module `react-native-paper/lib/module/components/Typography/Paragraph` from `PROJECT\src\utils\Popup.tsx`: `react-native-paper/lib/module/components/Typography/Paragraph` could not be found within the project or in these directories:
>   `node_modules`

So I guess I'd have to do something with the import again for paragraphs to work and I have no idea how many more elements I'd need to do this with so I'd rather ask you to fix this or help me if I'm doing something wrong.

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 13
| react-native                | 0.70.6
| react-native-paper    | 5.1.0
| node                            | 18.6.0
| npm                | 8.19.2

**Comment by lukewalczak** [comment]
Hey @Volper212, could you please create a sample github repo presenting your issue, which will help me to resolve your problem?

**Comment by Volper212** [comment]
I cleaned the caches and reinstalled `node_modules` and it works now.

**Comment by sgshy1995** [comment]
> I cleaned the caches and reinstalled `node_modules` and it works now.

Nice help me
