### ISSUE TITLE
How to change keyboard type in TextInput

### ISSUE THREAD

**Issue by yenpn** [callstack/react-native-paper#3548]
i tried like below, but it seems the keyboardType property is not working, keyboardType={'numeric'}

import { TextInput } from "react-native-paper";

`
<TextInput
      returnKeyType={returnKeyType}
      keyoardType={'numeric}
      secureTextEntry={secureTextEntry}
      value={value}
      onChangeText={onChangeText}
      mode={mode}
      label={label}
      placeholder={placeholder}
/>
`

How can i change the keyboard type on React Native's TextInput it works fine on TextInput default

Many thanks!

**Comment by yenpn** [comment]
Sorry, i'm resolved, because I passed the wrong attribute

**Comment by rumfiske** [comment]
What was the correct attribute?

**Comment by TamasSzigeti** [comment]
To whomever encounters this thread:

```
import { TextInput as NativeTextInput } from 'react-native';

    <TextInput
        render={(props) => <NativeTextInput textContentType={textContentType} keyboardType={keyboardType} {...props} />}
```

**Comment by rumfiske** [comment]
> To whomever encounters this thread:
> 
> ```
> import { TextInput as NativeTextInput } from 'react-native';
> 
>     <TextInput
>         render={(props) => <NativeTextInput textContentType={textContentType} inputMode={inputMode} keyboardType={keyboardType} {...props} />}
> ```

Thank you, gonna try this out now. I guess with the type "NativeTextInput " we got suggestions for the keyboardType and inputMode? :)

**Comment by Nawalnazari** [comment]
> To whomever encounters this thread:
> 
> ```
> import { TextInput as NativeTextInput } from 'react-native';
> 
>     <TextInput
>         render={(props) => <NativeTextInput textContentType={textContentType} inputMode={inputMode} keyboardType={keyboardType} {...props} />}
> ```

i tried this and got issue when after i enter the number and click done on keyboard, the value display is disappear
