### ISSUE TITLE
Extend tool for MD3 color scheme generation to support secondary, tertiary and neutral

### ISSUE THREAD

**Issue by fabriziocucci** [callstack/react-native-paper#3549]
**Is your feature request related to a problem? Please describe.**
Generating custom color schemes using more than the primary color is a bit of a cumbersome process involving:
* using the [Material Theme Builder for custom themes](https://m3.material.io/theme-builder#/custom) to generate them
* copying manually all colors in the JS object generated by the tool in the [creating dynamic theme colors](https://callstack.github.io/react-native-paper/theming.html) section

**Describe the solution you'd like**
It would be great to extend the tool in the [creating dynamic theme colors](https://callstack.github.io/react-native-paper/theming.html) section to support at least primary, secondary, tertiary and neutral for the generation of the color schemes.

This would be in line with the [Material Theme Builder for custom themes](https://m3.material.io/theme-builder#/custom).

<img width="396" alt="Screenshot 2022-12-23 at 11 11 05" src="https://user-images.githubusercontent.com/8156463/209317176-96b4e5cd-6e15-4cbb-a5c8-51c22bac939a.png">

**Describe alternatives you've considered**
Manual process described in the first section.

**Additional context**
N/A

**Comment by lukewalczak** [comment]
Hey @fabriziocucci, creating dynamic theme colors helper is based on the tool powered by [material-foundation](https://github.com/material-foundation/material-color-utilities), which probably doesn't have that option. Would you like to help us with some research or provide the implementation on how it can be done?

**Comment by fabriziocucci** [comment]
@lukewalczak I think I've found a [comment](https://github.com/material-foundation/material-color-utilities/issues/55#issuecomment-1279808470) which might help us.

What do you think?

**Comment by lukewalczak** [comment]
@fabriziocucci if the library is not exposing the util for it itself I guess we can try to approach it in the way mentioned in the comment.

**Comment by fabriziocucci** [comment]
@lukewalczak I've quickly tested this:
```js
function themeFromSourceColors(primary, secondary, tertiary, customColors = []) {
  const palette = CorePalette.of(primary);
  if (secondary != null) palette.a2 = TonalPalette.fromInt(secondary);
  if (tertiary != null) palette.a3 = TonalPalette.fromInt(tertiary);
  return {
    primary,
    schemes: {
      light: Scheme.lightFromCorePalette(palette),
      dark: Scheme.darkFromCorePalette(palette),
    },
    palettes: {
      primary: palette.a1,
      secondary: palette.a2,
      tertiary: palette.a3,
      neutral: palette.n1,
      neutralVariant: palette.n2,
      error: palette.error,
    },
    customColors: customColors.map((c) => customColor(primary, c)),
  };
}
```

It seems to be working reasonably ok, I could submit a PR for extending [`createDynamicThemeColors`](https://github.com/callstack/react-native-paper/blob/8615fc83f3ee0df34ed03b3542a370071fe23e20/docs/pages/src/utils/createDynamicColorTheme.js#L12).

**Comment by fabriziocucci** [comment]
FYI I just realised some colors are inconsistently computed between `createDynamicThemeColors` and the the predefined light/dark themes, specifically:

* `createDynamicThemeColors`
```js
surfaceDisabled: color(schemeModeJSON.onSurface)...
onSurfaceDisabled: color(schemeModeJSON.onSurface)...
```
* light theme:
```js
surfaceDisabled: color(palette.neutral10)...
onSurfaceDisabled: color(palette.neutral10)...
```
* dark theme:
```js
surfaceDisabled: color(palette.neutral90)...
onSurfaceDisabled: color(palette.neutral90)...
```

**Comment by lukewalczak** [comment]
> It seems to be working reasonably ok, I could submit a PR for extending [createDynamicThemeColors](https://github.com/callstack/react-native-paper/blob/8615fc83f3ee0df34ed03b3542a370071fe23e20/docs/pages/src/utils/createDynamicColorTheme.js#L12).

If you could create a draft PR where I will be able to test it on the docs page, it would be awesome 🙌🏽 

> FYI I just realised some colors are inconsistently computed between createDynamicThemeColors and the the predefined light/dark themes, specifically:

Not sure if I understood correctly, however `onSurface` translates into [neutral10](https://github.com/callstack/react-native-paper/blob/main/src/styles/themes/v3/LightTheme.tsx#L36) in `LightTheme` and [neutral90](https://github.com/callstack/react-native-paper/blob/main/src/styles/themes/v3/DarkTheme.tsx#L37) in `DarkTheme`

**Comment by fabriziocucci** [comment]
> If you could create a draft PR where I will be able to test it on the docs page, it would be awesome 🙌🏽

Will do as soon as I have some bandwidth! 👍 

> Not sure if I understood correctly, however onSurface translates into [neutral10](https://github.com/callstack/react-native-paper/blob/main/src/styles/themes/v3/LightTheme.tsx#L36) in LightTheme and [neutral90](https://github.com/callstack/react-native-paper/blob/main/src/styles/themes/v3/DarkTheme.tsx#L37) in DarkTheme

That's fair, I suppose when I was doing some tests I was a bit surprised not to find the same definition based on the palette, i.e. something like:
```js
const neutralTone = palettes.neutral.tone(curr === "light" ? 10 : 90);

const customColors = {
        surfaceDisabled: color(neutralTone)
          .alpha(opacity.level2)
          .rgb()
          .string(),
        onSurfaceDisabled: color(neutralTone)
          .alpha(opacity.level4)
          .rgb()
          .string(),
...
```

**Comment by kendallroth** [comment]
Is there any support for generating dynamic extra colors in the way that this part of the documention seems to indicate?

![image](https://user-images.githubusercontent.com/12562420/216710302-bcefdd5a-55eb-4c1d-be70-fb35b0a1cef8.png)

**Comment by lukewalczak** [comment]
In the [Theming](https://callstack.github.io/react-native-paper/theming.html) page on the documentation, under the section called `Creating dynamic theme colors` you can generate your color schemes based on the passed source color.

**Comment by kendallroth** [comment]
My apologies for lack of clarity; I was able to generate my light/dark themes based on the provided "main" color. However, the above image is taken from the MD3 section on generating _additional_ one-off custom colors (see [docs](https://m3.material.io/styles/color/the-color-system/custom-colors)). The MD3 generation tool supports this currently, allowing inputing a main colour that generates the light/dark themes, but then also allowing additional custom colours that generate light/dark tones for that colour. The RNP docs seemed to indicate support for that (as they directly reference an image from the custom color section), but I couldn't find any support for it in the code and was wondering if it was there or not. Does that clarification make sense?

**Comment by rodydavis** [comment]
Landed here: https://github.com/material-foundation/material-color-utilities/blob/bde4d30cad3cb766c45bcd8187da74ac56a3e292/typescript/palettes/core_palette.ts#L64
