### ISSUE TITLE
SearchBar does not work in ios

### ISSUE THREAD

**Issue by chukiatt** [callstack/react-native-paper#3551]
### Current behaviour

<View style={{ flex: 1, backgroundColor: 'red', flexDirection: 'row' }}>         
 <Searchbar  style={{ flex:1 }} ... />
 <View style={{ ... }} />
</View>

searchbar  does not flex in ios but in android it working properly

### How to reproduce?

![BBE6C7C2-A47F-4DDA-9065-C054C61C675E](https://user-images.githubusercontent.com/17401248/209472300-26ab3e5c-71dc-462e-b1d8-f19d98f61837.png)

### Your Environment
 "dependencies": {
    "@microsoft/signalr": "^6.0.10",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/cli": "^9.3.1",
    "@react-native-community/cli-platform-android": "^9.3.1",
    "@react-native-community/hooks": "^2.8.1",
    "@react-navigation/bottom-tabs": "^6.4.3",
    "@react-navigation/elements": "^1.3.9",
    "@react-navigation/material-top-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.16",
    "@react-navigation/native-stack": "^6.9.4",
    "@reduxjs/toolkit": "^1.9.1",
    "axios": "^0.27.2",
    "babel-plugin-module-resolver": "^4.1.0",
    "base-64": "^1.0.0",
    "clone-deep": "^4.0.1",
    "deprecated-react-native-prop-types": "^2.2.0",
    "i": "^0.3.7",
    "i18next": "^22.0.4",
    "iconv-lite": "^0.6.3",
    "intl": "^1.2.5",
    "moment": "^2.29.4",
    "npm": "^8.19.3",
    "pako": "^2.1.0",
    "react": "18.1.0",
    "react-i18next": "^12.0.0",
    "react-native": "0.70.5",
    "react-native-avoid-softinput": "^3.0.2",
    "react-native-awesome-loading": "^1.0.15",
    "react-native-base64": "^0.2.1",
    "react-native-blob-util": "^0.17.0",
    "react-native-bouncy-checkbox": "^3.0.6",
    "react-native-calendars": "^1.1291.1",
    "react-native-canvas": "^0.1.38",
    "react-native-device-info": "^10.3.0",
    "react-native-dropdown-picker": "^5.4.3",
    "react-native-esc-pos-printer": "^2.2.1",
    "react-native-fast-image": "^8.6.3",
    "react-native-flash-message": "^0.3.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-gifted-charts": "^1.2.41",
    "react-native-hole-view": "^2.1.2",
    "react-native-image-crop-picker": "^0.38.1",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-material-menu": "^2.0.0",
    "react-native-orientation-locker": "^1.5.0",
    "react-native-pager-view": "^6.1.2",
    "react-native-paper": "^5.1.0",
    "react-native-pdf": "^6.6.2",
    "react-native-permissions": "^3.6.1",
    "react-native-ping": "^1.2.7",
    "react-native-print": "^0.10.0",
    "react-native-radio-buttons-group": "^2.2.11",
    "react-native-reanimated": "^2.10.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-share": "^8.0.1",
    "react-native-sound": "^0.11.2",
    "react-native-star-io10": "^1.2.0",
    "react-native-svg": "^12.4.4",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-tab-view": "^3.3.2",
    "react-native-text-input-mask": "^3.1.4",
    "react-native-thermal-receipt-printer-image-qr": "^0.1.10",
    "react-native-vector-icons": "^9.2.0",
    "react-native-view-shot": "^3.5.0",
    "react-native-vision-camera": "^2.14.1",
    "react-native-webview": "^11.23.1",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1",
    "rn-responsive-screen": "^1.1.9",
    "rxjs": "^7.5.7",
    "vision-camera-code-scanner": "^0.2.0"
  },

**Comment by chukiatt** [comment]
OK i found the problem is not only search bar , modal  is same problem .
the problem is found when 
1. modal can't use style width in string like   style={{ width:'100%' }} 
2. search bar wrap in  flexdirection='row' it not flex:1 

that work on android but not in ios

**Comment by lukewalczak** [comment]
hey @chukiatt, please create a snack presenting the issue.
