### ISSUE TITLE
documentation enchancement

### ISSUE THREAD

**Issue by Aliendreamer** [callstack/react-native-paper#3552]
### Ask your Question

Hello I think your documentation is still wrong :
https://callstack.github.io/react-native-paper/theming-with-react-navigation.html
the themes seem wrongly  merged.
The correct should be:
const CombinedDarkTheme = merge(MD3DarkTheme, DarkTheme);
const CombinedDefaultTheme = merge(MD3LightTheme, LightTheme);
or I am mistaken?

Also a good point for new react native devs, or react web devs like me, is to point in the documentation that if your phone/device you test on has force dark mode enabled in android this  will cause you problems,  it caused me 3 days of frustration until I understood why my theming was not working, and if you are not active android/mobile dev this is not something you will know or remember quickly

**Comment by lukewalczak** [comment]
> The correct should be:
const CombinedDarkTheme = merge(MD3DarkTheme, DarkTheme);
const CombinedDefaultTheme = merge(MD3LightTheme, LightTheme);
or I am mistaken?

I've fixed docs via commit: https://github.com/callstack/react-native-paper/commit/761a8906a34e490ca480816e23b643af3bd64bcd

> Also a good point for new react native devs, or react web devs like me, is to point in the documentation that if your phone/device you test on has force dark mode enabled in android this will cause you problems, it caused me 3 days of frustration until I understood why my theming was not working, and if you are not active android/mobile dev this is not something you will know or remember quickly

I'm not entirely sure what you mean, could you please elaborate on it?

**Comment by Aliendreamer** [comment]
As I said I am primarily web developer.
And I delved in react native a bit created on application. But there is a value that you can set on your android phones that force dark theme on applications even if you dont have dark mode in the application.
Good example for this is tinder they don't have dark mode but you can force android os to put dark mode.
https://androidwaves.com/force-android-apps-to-use-dark-mode/#:~:text=Once%20developer%20options%20is%20turned,under%20%E2%80%9Csystems%20settings%E2%80%9D).&text=Step%204%3A%20Open%20systems%20settings,that%20do%20not%20support%20it). here some relevant info.

And what happened is and I suppose it happens to a lot of new mobile devs, on the 2 devices I was testing my react native app, this was turned on, I have them for years probably did it once upon a time and forgot.
And I spend 2 days trying to figure out why my themes are not working. I thought I made mistake implementing it or something is wrong with forcing it to react navigation. I was honestly in a hole.
And luckily I got new phone for chrismas and while configuring it I found this property again and  disabling this on my test devices fixed my issue and theming is wokring perfectly now.
But as I said if I put myself in the shoes of mobile developer, you probably know this by heart ,but as web developer or novice developer this is a bit tricky to find out and frustrating.
So if you add in the documentation a notice or a hint some thing like: "To test if your theming work make sure force dark mode on your android device is disabled / equivelent on mac I have no idea how it is called if exist/" it will helps a lot.

**Comment by Aliendreamer** [comment]
https://github.com/callstack/react-native-paper/issues/3377 this is good example on what I mean seems this was caused by same information missing.

**Comment by lukewalczak** [comment]
I think you can make a PR into the documentation called `Theming` with the explanation related to forcing a dark theme on Android, when it's turned on the device, in the developer options.

**Comment by lukewalczak** [comment]
Added a note via: https://github.com/callstack/react-native-paper/commit/1329ae147be36ec73722406615bc998550d2b95c
