### ISSUE TITLE
change inputText text color

### ISSUE THREAD

**Issue by Frostswing** [callstack/react-native-paper#3553]
### Current behaviour
My code is as:
            <View style={styles.inputContainer}>            
            <TextInput
            placeholder="name"
            value={email}
            onChangeText={text=>setEmail(text)}
            underlineColor='#5C5D5F'
            textColor="white"
            theme={{ colors: { onSurfaceVariant: "white"}}} 
            />
But my text is still black
### Expected behaviour
the text should be the same color of the textColor option

### How to reproduce?
Using react native paper
trying to change text color other than black,
i used style background color as black, so i can bearly see the inputtext

### Preview
![image](https://user-images.githubusercontent.com/114078402/209566242-c9bf6498-4d66-4264-ae09-f90d06bf16d8.png)

### What have you tried so far?
changing style background color, setting theme
setting textcolor value and more

i know that the code above has all of these settings together which may run over each-other, but i have tryed each of them individually

**Comment by lukewalczak** [comment]
Hey @Frostswing I've created a expo [snack](https://snack.expo.dev/@react-native-paper/input) based on your code and I'm not able to reproduce your issue.

**Comment by Frostswing** [comment]
That is wierd...
maybe its a version issue?
my react native paper is v8.19.3

im running on latest expo and on a pixel 7 pro device... i see no reason for bugs...

**Comment by Frostswing** [comment]
solved the issue.
my bad... i needed to change the placeholdertextcolor!


Thank you for helping!
