### ISSUE TITLE
How to remove background color of active tab in @react-navigation/material-bottom-tabs

### ISSUE THREAD

**Issue by transli** [callstack/react-native-paper#3554]
I am using @react-navigation/material-bottom-tabs and I would like to remove background color of active tab. Which props should I use? I tried almost everything from documentation.
![JO5j9](https://user-images.githubusercontent.com/54005837/209573218-6f293cb1-8502-4ba3-a854-b66a61f8749a.png)

**Comment by lukewalczak** [comment]
> I am using @react-navigation/material-bottom-tabs and I would like to remove background color of active tab. Which props should I use? I tried almost everything from documentation.

Hey @transli I would suggest then checking which theme color is used for a specific element, in your case outline pill. Its background color is `theme.colors.secondaryContainer` which you should be able to easily override using the `theme` prop:

`theme={{colors: {secondaryContainer: 'transparent'}}}`

**Comment by mehul2013** [comment]
@lukewalczak 
`theme={{colors: {secondaryContainer: 'transparent'}}}`.**This solution is not working**. Let me know if any other solution you have.

**Comment by mehul2013** [comment]
![Simulator Screen Shot - iPhone 13 - 2023-01-03 at 20 52 49](https://user-images.githubusercontent.com/4091807/210389978-0ab1471c-2ff2-4e7a-8192-df46f1b29fbf.png)

**Comment by vivekbw** [comment]
```tsx
import { useTheme } from 'react-native-paper';

const theme = useTheme();
theme.colors.secondaryContainer = "transperent"
```

should do the trick

**Comment by samkevin1** [comment]
@vivekbw this works, thanks!

**Comment by shahnawaz-pabon** [comment]
@vivekbw, Thank you so much. You've rescued me.

**Comment by VictorVMHC** [comment]
thanks vivekbw I had been looking for this solution for days

**Comment by 0xrasla** [comment]
@vivekbw  Nice thanks for this!

**Comment by gabriel-brito** [comment]
@vivekbw life saver!

**Comment by ritik2727** [comment]
import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';

const Tab = createMaterialBottomTabNavigator();

// Inside your component
<Tab.Navigator
  tabBarOptions={{
    activeBackgroundColor: 'transparent', // Set the background color of active tab to transparent
  }}
>
  {/* Add your tab screens */}
</Tab.Navigator>

**Comment by kholood-ea** [comment]
> ```tsx
> import { useTheme } from 'react-native-paper';
> 
> const theme = useTheme();
> theme.colors.secondaryContainer = "transperent"
> ```
> 
> should do the trick

Thank YOU!!

**Comment by tobecwb** [comment]
not working anymore

using:
- react-native-paper: 5.10.3;
- @react-navigation/material-bottom-tabs: 6.2.16;

tried extending the theme:
`const myTheme = extendTheme({ colors: { secondaryContainer: 'transparent' } });`

useTheme:
```
const theme = useTheme();
theme.colors.secondaryContainer = "transparent"
```

and tabBarOptions:
```
<Tab.Navigator
  ...
  activeColor={activeColor}
  inactiveColor={inactiveColor}
  shifting={true}
  tabBarOptions={{
    activeBackgroundColor: 'transparent'
  }}
>...</Tab.Navigator>

```

**Comment by htthecool** [comment]
> {secondaryContainer: 'transparent'}

this worked perfectly, thanks :)

**Comment by AjmirSarker** [comment]
> ```tsx
> import { useTheme } from 'react-native-paper';
> 
> const theme = useTheme();
> theme.colors.secondaryContainer = "transperent"
> ```
> 
> should do the trick

wher to use it

**Comment by AjmirSarker** [comment]
where to use it

**Comment by AjmirSarker** [comment]
@vivekbw  thank you for your answer.
Now., I have a problem with tabBarColor, it is not changing after giving different tabBarColor in each screen. Can you suggest any solution, Thanks.

**Comment by sheikhshab** [comment]
What i want to change the color of this background?

**Comment by AlModutram** [comment]
Using these lines: 

`import { useTheme } from 'react-native-paper';

const theme = useTheme();
theme.colors.secondaryContainer = "transperent"`

I'm getting this error:

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

Also using this: 
`theme={{colors: {secondaryContainer: 'transparent'}}}`
doesn't work.

Please, can you help me!

This is my code: 

`import { faBars } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome';
import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';
import * as React from 'react';
import * as colors from '../../../../colors';
import { AppTexts } from '../../../assets/languages/ES/AppTexts';
import { ClearProps } from '../../Props';

const Tab = createMaterialBottomTabNavigator();

export default class BottomAction extends React.Component<ClearProps> {
    constructor(props: ClearProps) {
        super(props);
    }

    render() {
        return (
            <Tab.Navigator
                activeColor={colors["secondary-03"]}
                inactiveColor={colors["secondary-03"]}
                barStyle={{ backgroundColor: colors["secondary-15"] }}>
                <Tab.Screen
                    name={AppTexts.BUTTON_BOTTOM_01}
                    component={this.BookingScreen}
                    options={{
                        tabBarIcon: ({ color }) => (
                            <FontAwesomeIcon
                                icon={faBars}
                                size={20}
                                color={color} />
                        ),
                    }}/>
                <Tab.Screen 
                    name={AppTexts.BUTTON_BOTTOM_02} 
                    component={this.MyCheckInSceen} 
                    options={{
                        tabBarIcon: ({ color }) => (
                            <FontAwesomeIcon
                                icon={faBars}
                                size={20}
                                color={color} />
                        ),
                    }}/>
                <Tab.Screen 
                    name={AppTexts.BUTTON_BOTTOM_03} 
                    component={this.QRCodeScreen} 
                    options={{
                        tabBarIcon: ({ color }) => (
                            <FontAwesomeIcon
                                icon={faBars}
                                size={20}
                                color={color} />
                        ),
                    }}/>
                <Tab.Screen 
                    name={AppTexts.BUTTON_BOTTOM_04} 
                    component={this.MyTravelScreen} 
                    options={{
                        tabBarIcon: ({ color }) => (
                            <FontAwesomeIcon
                                icon={faBars}
                                size={20}
                                color={color} />
                        ),
                    }}/>
            </Tab.Navigator>
        );
    }`

**Comment by gonsals** [comment]
Now how can I change the padding of the background pill

**Comment by angelilton** [comment]
just for update is the new one to v5
`activeIndicatorStyle={{backgroundColor: 'transparent'}}`

<img width="918" alt="Image" src="https://github.com/user-attachments/assets/62a0e97c-4066-4916-b3ca-08a25a54a527" />

**Comment by Sakib-203-15-3883** [comment]
Thanks, bro , it's work
