### ISSUE TITLE
Drawer as sidebar on larger screens?

### ISSUE THREAD

**Issue by micahlt** [callstack/react-native-paper#3556]
### Ask your Question
On larger screens (tablets, TVs, etc), is there a way to keep the drawer open and have its overlay be transparent?  In other words, transforming it from a drawer to a sidebar?  This is referred to as Standard vs Modal drawer in the official MD3 docs here: https://m3.material.io/components/navigation-drawer/guidelines#38800092-0149-4251-ac75-4ce8a144042a

If this isn't currently possible, it should probably be a feature in an upcoming version considering that it drastically improves the UX on larger screens!

**Comment by lukewalczak** [comment]
Hey @micahlt, you can achieve that by setting a permanent drawer using [drawerType](https://reactnavigation.org/docs/drawer-navigator/#drawertype) option in `Drawer.Navigator` from `react-navigation`.

**Comment by micahlt** [comment]
Ah, thank you!  I forgot that the Drawer inherits properties from react-navigation.
