### ISSUE TITLE
typescript wrong required props

### ISSUE THREAD

**Issue by mohammadgharouni** [callstack/react-native-paper#3557]
### Current behaviour

some component expect wrong required props

### Expected behaviour
required props to be optional

### How to reproduce?
just use one of these components and you'll see typescript errors  IconButton,Appbar.Action,Appbar.Content,Appbar.BackAction,TextInput.Icon,List.Item,
the workaround to this issue is to pass undefined to every required props like this :
  const fixProps = {
  accessibilityLabelledBy: undefined,
  accessibilityLanguage: undefined,
  onPointerEnter: undefined,
  onPointerEnterCapture: undefined,
  onPointerLeave: undefined,
  onPointerLeaveCapture: undefined,
  onPointerMove: undefined,
  onPointerMoveCapture: undefined,
  onPointerCancel: undefined,
  onPointerCancelCapture: undefined,
  onPointerDown: undefined,
  onPointerDownCapture: undefined,
  onPointerUp: undefined,
  onPointerUpCapture: undefined,
  onBlur: undefined,
  onFocus: undefined,
  onHoverIn: undefined,
  onHoverOut: undefined,
  cancelable: undefined,
  delayHoverIn: undefined,
  delayHoverOut: undefined,
  unstable_pressDelay: undefined,
};
<IconButton {...fixProps} {...rest} />

### Your Environment

| software                      | version
| --------------------- | -------

| react-native                | 0.69.7
| react-native-paper    | 5.1.0
| node                            | 16.14.2
| npm or yarn                | 8.5.0
| expo sdk                     | bare react-native app

**Comment by lukewalczak** [comment]
Installing `@types/react-native` should solve your issue.
