### ISSUE TITLE
Add possibility to override `borderColor` and `borderRadius` with outlined `Card`

### ISSUE THREAD

**Issue by fabriziocucci** [callstack/react-native-paper#3563]
**Is your feature request related to a problem? Please describe.**
Rather than a problem I would say this is an unexpected behaviour.

**Describe the solution you'd like**
Ideally, the following should work as expected:
```js
<Card mode="outlined" style={{ borderColor: ..., borderRadius: ... }} />
```

**Describe alternatives you've considered**
The best alternative is:
```js
<Card mode="contained" style={{ borderColor: ..., borderRadius: ... }} />
```
but it feels hacky.

**Additional context**
Override missing [here](https://github.com/callstack/react-native-paper/blob/v5.1.0/src/components/Card/Card.tsx#L249-L260).

**Comment by lukewalczak** [comment]
Hey @fabriziocucci, I've created a PR which is unblocking the possibility to override `Card` outline radius using styles, however, its color you can customize via `theme.colors.outline`.

**Comment by fabriziocucci** [comment]
Thanks for the fast pace of changes @lukewalczak! ❤️ 

> ...however, its color you can customize via theme.colors.outline.

Does that mean there is no way to customise the border of a one-off outlined card besides acting on the theme? 🤔

**Comment by lukewalczak** [comment]
> Does that mean there is no way to customise the border of a one-off outlined card besides acting on the theme? 🤔

You can override the outline color only for one specific `Card` like in the following example:

```
  <Card mode="outlined" theme={{ colors: { outline: 'magenta' } }}>
    <Card.Content>
      <Title>Card title</Title>
      <Paragraph>Card content</Paragraph>
    </Card.Content>
    <Card.Actions>
      <Button>Cancel</Button>
      <Button>Ok</Button>
    </Card.Actions>
  </Card>
  ```

**Comment by fabriziocucci** [comment]
Ok, that's like passing a theme override to the `Card`, sounds a bit extreme and unintuitive compared to simply passing `borderColor`! 😅 

I suspect we could have done the same thing for `borderRadius`:
```
<Card mode="outlined" theme={{ roundness: ... }}>
```

so I'm wondering what's the catch, why supporting the style override in one case and not in the other?

**Comment by lukewalczak** [comment]
> so I'm wondering what's the catch, why supporting the style override in one case and not in the other?

In terms of `borderRadius` in outlined Card, there is a multiplier `(isV3 ? 3 : 1)` paired with `roundness`, so it can be hard to actually achieve the desired border radius value, by specifying a custom `roundness`.

 > I suspect we could have done the same thing for borderRadius:
 
 Sure, I'm going to revisit that problem in Card but also in other components, to unify the approach.
