### ISSUE TITLE
How to change highlight color of bottom navigation's tabs??

### ISSUE THREAD

**Issue by arasrezaei** [callstack/react-native-paper#3566]
Hi there, and thanks for great library,
Can some one please help me with changing highlight color of bottom navigation?

Also is there any way to change rendered bar component??
For example changing bar component with a blur view?
Thanks.

**Comment by lukewalczak** [comment]
> Can some one please help me with changing highlight color of bottom navigation?
Hey @arasrezaei if I understand correctly, you want to change the color of the _outline pill_ which is `theme.colors.secondaryContainer` and you should be able to easily override it using the theme prop:

`theme={{colors: {secondaryContainer:  'your color' }}}`

> Also is there any way to change rendered bar component??
> For example changing bar component with a blur view?

I have no idea, didn't check/investigate that.

**Comment by fabriziocucci** [comment]
@arasrezaei, to expand on the first point addressed by @lukewalczak, you can do something like:
```js
<Provider theme={{ ...theme, colors: { ...theme.colors, secondaryContainer: "<your-color>" } }}>
    <Tab.Navigator>
        // ...
    </Tab.Navigator>
</Provider>
```

where `theme` is either your custom theme or `MD3LightTheme`/`MD3DarkTheme`.
