### ISSUE TITLE
Different Menu position for different devices

### ISSUE THREAD

**Issue by irekrog** [callstack/react-native-paper#3568]
### Current behaviour
I've noticed a opened Menu component has a different position for different devices.

### Expected behaviour
Menu should have always the same position.

### How to reproduce?
The simplest example of the Menu, and check how it looks on different devices.

```
<PaperProvider>
  <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
    <Text>MENU</Text>
    <Menu
      visible={visible}
      onDismiss={closeMenu}
      anchor={<Button onPress={openMenu}>Show menu</Button>}>
        <Menu.Item onPress={() => {}} title="Item 1" />
        <Menu.Item onPress={() => {}} title="Item 2" />
        <Divider />
        <Menu.Item onPress={() => {}} title="Item 3" />
     </Menu>
  </View>
</PaperProvider>
```

### Preview
1. Physical device - Alcatel 1B
2. Emulator - Pixel 4
3. Emulator - Nexus 5X

![IMG_9257](https://user-images.githubusercontent.com/11172548/210132430-f31049bd-9a05-40b6-aa6a-f3012ee59837.jpg)

### What have you tried so far?
I think maybe there is a problem with different `y` value from `measureInWindow`

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | Alcatel: Android 10, Emulators: Android 11
| react-native                | 0.70.5
| react-native-paper    | 5.1.2
| node                            | 16.16.0
| yarn                | 1.22.19
| expo sdk                     | 47.0.8

**Comment by lukewalczak** [comment]
Hey @irekrog, I've checked your snippet code in the example app and tested it against two emulator and one physical device and wasn't able to reproduce the issue:

Nexus 5x | Nexus 7 | Google Pixel 4a
--- | --- | ---
<img width="398" alt="Zrzut ekranu 2023-01-9 o 11 53 59" src="https://user-images.githubusercontent.com/22746080/211292366-96bb7cec-2f5f-40c5-a0dd-b36c392513c2.png"> |  <img width="400" alt="Zrzut ekranu 2023-01-9 o 11 53 58" src="https://user-images.githubusercontent.com/22746080/211292593-b282acaf-5b26-44a7-aea5-b086051b90d5.png"> | <img width="483" alt="Zrzut ekranu 2023-01-9 o 11 56 14" src="https://user-images.githubusercontent.com/22746080/211292612-6ab86075-7860-4e52-94f0-d42df228d163.png">

**Comment by irekrog** [comment]
Hi @lukewalczak 
I've created a repo. Could you take a look at this? https://github.com/irekrog/expo-test

![Zrzut ekranu 2023-01-9 o 18 11 49](https://user-images.githubusercontent.com/11172548/211366827-d37c9dbd-51ed-4b85-be8d-e38c80424ad2.png)

**Comment by lukewalczak** [comment]
Hey @irekrog, thanks for the repo – if will find some time, definitely look at that ✌🏽

**Comment by barttom** [comment]
Hello @irekrog !
I've tried very hard to reproduce this error, also in Your repo but, quotes classic, 'works for me' 😅 
Also on physical devices like LG Velvet or Xiaomi Redmi Note 5  haven't realized this bug 🤷 



![Screenshot 2023-03-01 at 12 23 20](https://user-images.githubusercontent.com/7682108/222128047-c194970b-37ca-41fa-843d-a0bc8559c9de.png)

**Comment by irekrog** [comment]
@barttom Hi, thanks, mehhh so it looks like I have a very specific case with this. So I think this issue can be closed 🫠
