### ISSUE TITLE
Issue with SegmentedButtons icon display logic causes extra padding

### ISSUE THREAD

**Issue by cmot17** [callstack/react-native-paper#3570]
### Current behaviour
When there is no icon selected for SegmentedButtons, the text is slightly off-center to the right.

### Expected behaviour
The text should be centered.

### How to reproduce?
The example from this page reproduces the bug:
https://callstack.github.io/react-native-paper/segmented-buttons.html

### Preview
![image](https://user-images.githubusercontent.com/25753364/210284625-0eb5285c-d20e-4ae9-a3f5-1a03e46ad478.png)

### What have you tried so far?
I'm pretty sure I have identified the cause of the bug: [Line 149 in SegmentedButtonItem.tsx](https://github.com/callstack/react-native-paper/blob/main/src/components/SegmentedButtons/SegmentedButtonItem.tsx#L149)
The icon is displayed even when there is no icon, which adds 5px of extra padding to the left of the text.
```javascript
const showIcon = icon && !label ? true : checked ? !showSelectedCheck : true;
```
If changed to 
```javascript
const showIcon = !icon ? false : showSelectedCheck && label ? !checked : true;
```
it seems to fix the issue in my testing, but I'm not fully sure of every edge case (and last time I opened a PR in a big repo I messed up a bunch of stuff 😅)
### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Thanks for reporting the issue! I need to properly understand the condition for `showIcon` to decide whether your solution is correct. I will let you know ✌🏽

**Comment by lukewalczak** [comment]
Hey @cmot17, I investigated the issue and formed a similar condition for displaying the icon:

```
  const showIcon = !icon ? false : label && checked ? !showSelectedCheck : true;
```

I will handle creating a PR with the fix and unit tests.
