### ISSUE TITLE
`Appbar.Header.title` renders custom components high on Android

### ISSUE THREAD

**Issue by thehale** [callstack/react-native-paper#3572]
### Current behaviour

The `Appbar.Header`'s `title` prop does accept custom components but does not render them vertically centered in the app bar on Android (iOS and Web seem to work fine). Re-rendering the Appbar via a manual press fixes the issue.

### Expected behaviour

The Appbar should render the custom title component vertically centered on the first render.

### How to reproduce?

https://snack.expo.dev/@thehale/react-native-paper-issue-3572

### Preview

https://user-images.githubusercontent.com/47901316/210291700-ad034b99-40c2-4258-9107-07b975681a08.mp4

#### Wrapping the Button in a View with `flex` settings
Wrapping my Button in a separate View with a red background color reveals that the Button is filling the full space available to it. As such, adjusting flexbox alignment/justifications have no effect on the Button's initially rendered position.

#### Automatically triggering a re-render
Also, automatically forcing a re-render does not appear to fix the button's position. Only a manual press seems to do the trick.
- See the commented line of code in the Snack.

#### Changing the `mode` prop on `Appbar.Header`
This alignment issue shows up on `center-aligned` and `small` modes, but not on `medium` or `large`.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 15.1+
| android                        | 10+
| react-native                | 0.68
| react-native-paper    | 5.1.2
| node                            | 18.10.0
| npm or yarn                | 1.22.19
| expo sdk                     | 45+

**Comment by lukewalczak** [comment]
I think the problem arises from the fact that `Button` passed into the `title` prop is then rendered within `Text` [component](https://github.com/callstack/react-native-paper/blob/main/src/components/Appbar/AppbarContent.tsx#L151). By default `Text` has variant `titleLarge` which has line-height is equal to "28" and accommodates that space, however`Button`'s height is `40`. Probably that's why it jumps, so I would suggest to add `titleStyle={{ height: 40 }}` into `Appbar.Content`.

**Comment by thehale** [comment]
I updated the [linked Snack](https://snack.expo.dev/@thehale/react-native-paper-issue-3572) with your comment, and while `titleStyle={{ height: 40 }}` successfully stops the jumping around, it left the button positioned high.

The style settings that kept the button correctly centered without jumping are `titleStyle={{ height: 40, top: 12 }}`. The extra `top` style pushes the button down the extra 12-pixel height difference between the `Button` and the `Text`.
- Interestingly, it seems like any value for `top` prevents the Button's jumping around.
---

Is this workaround the proper resolution for this issue, or should this bug report stay open until a fix is merged into `react-native-paper`?

**Comment by lukewalczak** [comment]
Hey @thehale could you please if the changes in the https://github.com/callstack/react-native-paper/pull/3596 fix your issue?

**Comment by thehale** [comment]
Hello @lukewalczak 

I have tested your fix in [this repository](https://github.com/thehale/react-native-paper-issue-3572) and found it to solve my issue perfectly as expected. I can recommend merging the linked PR as written. I will let you close this issue in line with this project's issue management policies.

Thanks!
