### ISSUE TITLE
Error when multiple (stack) navigators are nested in Bottom Navigation

### ISSUE THREAD

**Issue by vaporrrr** [callstack/react-native-paper#3578]
### Current behaviour

When multiple stack navigators are nested in a bottom navigation, an error occurs when trying to switch to the second stack navigator. The first stack navigator works as expected
```
Error: Another navigator is already registered for this container. You likely have multiple navigators under a single "NavigationContainer" or "Screen". Make sure each navigator is under a separate "Screen" container. See https://reactnavigation.org/docs/nesting-navigators for a guide on nesting.
```

### Expected behaviour

For both stack navigators to behave the same

### How to reproduce?

https://snack.expo.dev/@vaporrrr/react-native-paper-nested-navs

### What have you tried so far?

I've tried to see if the issue occurs with react navigation's Bottom Tabs Navigator, but it works fine there. I've tried using other navigators instead of stack navigators, but the issue persists. All the iOS/android versions I tried have the same behavior.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.70.5
| react-native-paper    | 5.1.2
| node                            | 16.14.2
| ~~npm~~ or **yarn**                | 1.22.19
| expo sdk                     | 6.0.8

**Comment by lukewalczak** [comment]
Hey @vaporrrr, I'm not entirely sure, but looks like in your case there is a need to use [material-bottom-tabs](https://github.com/react-navigation/react-navigation/tree/main/packages/material-bottom-tabs). According to the Paper's [docs](https://callstack.github.io/react-native-paper/bottom-navigation.html):

> For integration with React Navigation, you can use [react-navigation-material-bottom-tabs](https://github.com/react-navigation/react-navigation/tree/main/packages/material-bottom-tabs) and consult [createMaterialBottomTabNavigator](https://reactnavigation.org/docs/material-bottom-tab-navigator/) documentation.

**Comment by vaporrrr** [comment]
Hello, that seems to use the older material design 1 instead of 3, is there no other option?

**Comment by lukewalczak** [comment]
The latest MD should be supported within the library, please check the following [snack](https://snack.expo.dev/@react-native-paper/nesting-navigators-%7C-react-navigation).

**Comment by vaporrrr** [comment]
I see, thank you
