### ISSUE TITLE
Button Label and Icon misalignment

### ISSUE THREAD

**Issue by stakez** [callstack/react-native-paper#3579]
### Current behaviour
The Button component label and icons are horizontally misaligned on Android but rendered correctly on IOS.

### Expected behaviour
Buttons should be properly rendered

### Preview

IOS 
<img width="87" alt="Screenshot 2023-01-08 at 1 21 12 AM" src="https://user-images.githubusercontent.com/99569934/211188984-8f3786aa-11b1-4c03-8603-d4191e7f0f96.png">

Android
<img width="79" alt="Screenshot 2023-01-08 at 1 21 24 AM" src="https://user-images.githubusercontent.com/99569934/211188997-05cc50d2-fdda-4911-9128-e9ac69203efe.png">

### What have you tried so far?
It is not correctable via contentStyle and style props

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.70.5
| react-native-paper    | 5.1.2

**Comment by stakez** [comment]
import {  Button  } from 'react-native-paper';

() => ( <Button  icon={'emoticon-outline'} children={'Example'}  mode="text" />)

The above code generates the following Button Component in Android
<img width="85" alt="Screenshot 2023-01-08 at 12 38 25 PM" src="https://user-images.githubusercontent.com/99569934/211217943-96c3cbe7-d5c4-4ee1-bb1b-63e1cf85f0e6.png">


The above is all I need to demonstrate the issue

**Comment by stakez** [comment]
@lukewalczak Thanks for the followup but these screenshots were captured on the Android emulator (Pixel 5) on a MacBook. Can you try reproducing it that way?

**Comment by lukewalczak** [comment]
> @lukewalczak Thanks for the followup but these screenshots were captured on the Android emulator (Pixel 5) on a MacBook. Can you try reproducing it that way?

I have tried it on the Pixel 5 emulator and I'm still not able to observe your issue, however, I have noticed on your screenshot that button's text has a different font color. Maybe you have applied some custom styles into button?

<img width="479" alt="Zrzut ekranu 2023-01-10 o 23 40 07" src="https://user-images.githubusercontent.com/22746080/211677962-98b159a0-e830-4577-bc3d-6a5e750a5e61.png">

**Comment by stakez** [comment]
Good observation but my first post above has screenshots of buttons without custom styles (matching yours above) and the android version is misaligned. Since you are unable to re-create the issue thus far, I will pursue a work around. Thanks.
