### ISSUE TITLE
Drawer: Redesign

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#358]
- [x] Change selected state drawer item

![image](https://user-images.githubusercontent.com/1174278/39866026-3936ed88-544f-11e8-91b8-a615947d5be5.png)

https://material.io/design/components/navigation-drawer.html

**Comment by jaulz** [comment]
Can we reintroduce the color property? In my case I have a color coding (e.g., green for done etc.) and hence it was perfect to represent the color also in the drawer.

**Comment by gawrysiak** [comment]
@jaulz, it's still possible to customize the color which is now theme based. If you check the `example/DrawerItems.js` file, you should be able to see this:
```
<DrawerItem
  {...props}
  key={props.key}
  theme={
    props.key === 3 ? { colors: { primary: Colors.tealA200 } } : undefined
  }
  active={this.state.drawerItemIndex === index}
  onPress={() => this._setDrawerItem(index)}
/>
```

So you can either change the primary color globally or pass it through the theme prop for customizations. While having a color prop might look a bit cleaner in this case, it's still good to avoid unnecessary duplication and API bloat. Color props are present mostly in cases when there's no way to change it with any other method.

**Comment by jaulz** [comment]
You are right! Thanks for the hint with the theme... did not thought about that way :-)

**Comment by ManigandanRaamanathan** [comment]
@satya164  @jaulz  How to add badge to the app drawer items?

**Comment by jaulz** [comment]
@ManigandanRaamanathan not sure if that's feasible with the current set up but it might be worth to see if we can use the `children` prop instead of a `label` prop in order to be more flexible. @satya164 what do you think?

**Comment by ManigandanRaamanathan** [comment]
> @ManigandanRaamanathan not sure if that's feasible with the current set up but it might be worth to see if we can use the `children` prop instead of a `label` prop in order to be more flexible. @satya164 what do you think?

What are the props available now?

**Comment by Trancever** [comment]
@ManigandanRaamanathan Please, check the docs if you need information about available props.

**Comment by satya164** [comment]
@jaulz maybe makes sense to support a `badge` prop? we'll need to style and position it properly anyway

**Comment by jaulz** [comment]
Great, then let's take a `badge` property and if you are fine I will try to implement a `Badge` component (à la https://github.com/callstack/react-native-paper/pull/539#issuecomment-426977815) which we could reuse here and across other components.
