### ISSUE TITLE
How to implement system/light/dark theme changing?

### ISSUE THREAD

**Issue by MatteoBuffo** [callstack/react-native-paper#3581]
### Ask your Question

Hello. My goal is to have an app where:

- the theme property is global and can be changed from a Settings screen, like this:
![theme](https://user-images.githubusercontent.com/56068232/211295175-e9f2cafe-5725-4e2c-903a-d4914580f030.jpg)
- the user can set the system, light or dark theme.

Setting the light/dark theme works fine, while setting the system theme doesn't. Theoretically, you should set the `theme` prop in `PaperProvider` component (`index.tsx`) to null. So you need to change the theme definition

```
const theme = {
	2: {
		light: MD2LightTheme,
		dark: MD2DarkTheme,
	},
	3: {
		light: MD3LightTheme,
		dark: MD3DarkTheme,
	},
}[themeVersion][themeMode];
```

to

```
const [theme, setTheme] = React.useState({
	2: {
		light: MD2LightTheme,
		dark: MD2DarkTheme,
	},
	3: {
		light: MD3LightTheme,
		dark: MD3DarkTheme,
	},
}[themeVersion][themeMode]);
```

Then, you should change the `preferences` to

```
const preferences = React.useMemo(
    () => ({
      toggleTheme: () => setIsDarkMode((oldValue) => !oldValue),
      setSystemTheme: () => setTheme(null),
      ...
    }),
    [rtl, theme, collapsed]
  );
```

I tried it, but it raises "theme is undefined"-like errors.

Any suggestion? Should I add a property to the theme object, e.g. a `systemDefault` boolean, to tell whether the app should consider/ignore the system default?

Thanks.

**Comment by lukewalczak** [comment]
`Provider` from the Paper library automatically detects the color scheme set on the device. However, if you want to control themes by yourself you can take the advantage of [useColorScheme](https://reactnative.dev/docs/usecolorscheme) from `react-native`.

```
import { useColorScheme } from 'react-native';
import {  MD3DarkTheme, MD3LightTheme } from 'react-native-paper';
...
  const colorScheme = useColorScheme();
  const isDarkMode = colorScheme === 'dark';
  
  const theme = isDarkMode ? MD3DarkTheme : MD3LightTheme
```

**Comment by MatteoBuffo** [comment]
@lukewalczak thanks! I'll definetely take advantage of that.
