### ISSUE TITLE
`TextInput.Affix` prop `onLayout` is not passed to component

### ISSUE THREAD

**Issue by mfds** [callstack/react-native-paper#3589]
### Current behaviour
Prop `onLayout` for `TextInput.Affix` (https://github.com/callstack/react-native-paper/blob/main/src/components/TextInput/Adornment/TextInputAffix.tsx#L24) is not being passed to the Affix component (https://github.com/callstack/react-native-paper/blob/main/src/components/TextInput/Adornment/TextInputAffix.tsx#L117)

### Expected behaviour
To be able to pass a callback that gets called when layout changes.

### How to reproduce?
```jsx
<RNPTextInput.Affix onLayout={(e) => console.log(e)} text="Hello" />;
```

### Preview
N/A

**Comment by lukewalczak** [comment]
Thanks @mfds, I will check the issue ✌🏽

**Comment by mfds** [comment]
Thanks
