### ISSUE TITLE
FAB icon prop should not be required

### ISSUE THREAD

**Issue by hbriese** [callstack/react-native-paper#3594]
### Current behaviour

`icon` is a required prop for `FAB`.

Not passing in the `icon` prop results in a type error, but the correct behavior

### Expected behaviour

A [MD3 extended FAB](https://m3.material.io/components/extended-fab/overview) is not required to provide an icon.

At least a `icon` or a `label` should be required

### How to reproduce?

```tsx
<FAB label="..." />
```

### Workaround
```tsx
<FAB 
  label="..."
  icon={undefined as unknown as IconSource} 
/>
```

### Your Environment

| software                      | version
| --------------------- | -------
| react-native-paper    | 5.1.3

**Comment by lukewalczak** [comment]
Hey @hbriese, thanks for the feedback. I agree that we can improve types and that one of `icon` or `label` has to be required.
