### ISSUE TITLE
Use a patch created with patch-package in build with gradle for android.

### ISSUE THREAD

**Issue by nmateo** [callstack/react-native-paper#3598]
### Ask your Question

So i created a patch to react-native-paper which is a one-liner just to not display the icon for a specific screen in BottomNavigation:
````
diff --git a/node_modules/react-native-paper/src/components/BottomNavigation/BottomNavigation.tsx b/node_modules/react-native-paper/src/components/BottomNavigation/BottomNavigation.tsx
index 85b0cc9..b3d73a8 100644
--- a/node_modules/react-native-paper/src/components/BottomNavigation/BottomNavigation.tsx
+++ b/node_modules/react-native-paper/src/components/BottomNavigation/BottomNavigation.tsx
@@ -915,7 +915,8 @@ const BottomNavigation = ({
               const isV3Shifting = isV3 && shifting && labeled;
 
               const font = isV3 ? theme.fonts.labelMedium : {};
-
+              if (route.key === 'account')
+                return;
               return renderTouchable({
                 key: route.key,
                 route,
````

Whenever i do nmp ci or npm install my patch is executed as postinstall script, and i can see the change when using expo go to test my app, but when building with gradle for android (gradlew assembleRelease), my modification isn't in the final binary.. any help would be appreciated, thanks in advance.

**Comment by lukewalczak** [comment]
Hey @nmateo, does it happen only for patched `react-native-paper`? Did you try the same on the bare react-native project, without expo?

**Comment by nmateo** [comment]
> Hey @nmateo, does it happen only for patched `react-native-paper`? Did you try the same on the bare react-native project, without expo?

Hi! Yes it's the only change i made in a package for now, so i can't speak for other packages, but yes i see the modifications too when launching bare with "npx react-native run-android", same as expo.
The only time i can't see them and the icon is still present, it's when building with gradlew assembleRelease|assembleDebug 
Thanks in advance, it's surely not a bug that why i tagged it as question i think it's just the gradle build that go to download fresh packages, so my modification isn't there ?

**Comment by lukewalczak** [comment]
Could you please try to apply another patch to the other library, just to check whether your issue is related directly to the `react-native-paper` or `patch-package` when building Android?

**Comment by nmateo** [comment]
> Could you please try to apply another patch to the other library, just to check whether your issue is related directly to the `react-native-paper` or `patch-package` when building Android?

I tried, i can't get anything modified in node_module, when building release build.. either with patch-package, or directly modifying the package, i just want help to get my mdoficiation to be in the final binary... it's not a direct issue with react-native-paper, thanks.

**Comment by lukewalczak** [comment]
I keep my fingers crossed for resolving your issue. Closing the issue due to the lack of connection with the Paper library.
