### ISSUE TITLE
The color of Icon in Chip is always primary

### ISSUE THREAD

**Issue by Bi0max** [callstack/react-native-paper#3599]
### Current behaviour
With theme v3 the color of icon in Chip is always primary.

### Expected behaviour
Should be adjusted to circumstances.

### Preview
![image](https://user-images.githubusercontent.com/4247432/212723228-1b6ceede-c673-41ef-ada8-2e84fc37d74e.png)

### What have you tried so far?
Checked the source.
https://github.com/callstack/react-native-paper/blob/main/src/components/Chip/Chip.tsx#L311-L321

### Solution
I think these lines should be just removed:
```
: !disabled && theme.isV3
? theme.colors.primary
```
because `getIconColor` method from `helpers.ts` already takes all possible situations in account.

**Comment by lukewalczak** [comment]
Actually, from the analysis of the documentation it looks like it's correct - the icon _(not the selected check icon)_ has always `primary` color.  I will improve the documentation to mention which components will adjust according to the `selectedColor`. But don't worry, if you want to use custom color, you can always pass your icon component with the specified color.

**Comment by Bi0max** [comment]
Hi @lukewalczak, but according to material.io specs, it's the case only for Assist chip.
For example, for Filter or Input chip, the Leading icon is onSurfaceVariant or onSecondaryContainer, depending on the current background.
![image](https://user-images.githubusercontent.com/4247432/212878181-731c8c38-f663-4d53-b9bd-44c39a93030e.png)
or
![image](https://user-images.githubusercontent.com/4247432/212878360-fc426483-d2a5-4ff1-a03c-173288f60c74.png)
