### ISSUE TITLE
How to vertically center the content of SegmentedButtons?

### ISSUE THREAD

**Issue by MatteoBuffo** [callstack/react-native-paper#3600]
### Ask your Question
Hello.

As reported in the title, I would like to know if there's a way to vertically center the content (i.e. the labels and their respective icons) of SegmentedButtons.

Please check [this Snack](https://snack.expo.dev/@mbuffo/react-native-paper-example_v5) out and open `src/Examples/SegmentedButtons/SegmentedButtonsDefault.tsx`.

Thanks in advance.

**Comment by lukewalczak** [comment]
Add the `justifyContent` center to the button's style.
