### ISSUE TITLE
How to remove pink and purple sheen in new version?

### ISSUE THREAD

**Issue by DianaKoenraadt** [callstack/react-native-paper#3602]
The FAB.Group has purple buttons now. Also, any Card that I press, turns light pink. How do I remove this?

**Comment by lukewalczak** [comment]
> The FAB.Group has purple buttons now. Also, any Card that I press, turns light pink. How do I remove this?
By "turns light pink", do you mean the ripple effect on the component, when pressing them?

**Comment by DianaKoenraadt** [comment]
Yes

**Comment by lukewalczak** [comment]
Unofrtunately, I'm not sure if you can remove that.

**Comment by DianaKoenraadt** [comment]
Oh, it really clashes with our app colors. Maybe put this as a feature request somewhere then?

**Comment by lukewalczak** [comment]
Maybe there is an option to override that color, but it requires diving into the code, so I will suggest checking that approach.

**Comment by DianaKoenraadt** [comment]
Same goes for the Searchbar, that has a pink sheen too.

**Comment by lukewalczak** [comment]
Ripple effect is a part of the Material Design and it will be visible in many components.
