### ISSUE TITLE
Portal no longer transparent. How to reintroduce transparency?

### ISSUE THREAD

**Issue by DianaKoenraadt** [callstack/react-native-paper#3604]
In the new version, Portal is no longer transparent. It does not have a `style` prop. How do I make it transparent again?

**Comment by lukewalczak** [comment]
Hey @DianaKoenraadt, could you please present your question on the [snack](https://snack.expo.dev/)? The portal doesn't have any styles and it just allows rendering a component at a different place in the parent tree, so I assume that maybe the `children` passed to the `Portal` has issues with transparency.

**Comment by DianaKoenraadt** [comment]
The children have not changed. Yesterday, I upgraded to the latest react-native-paper and now Portal is no longer transparent.

**Comment by lukewalczak** [comment]
> The children have not changed. Yesterday, I upgraded to the latest react-native-paper and now Portal is no longer transparent.

Please attach the snack presenting your issue.

**Comment by DianaKoenraadt** [comment]
Before:

![before1](https://user-images.githubusercontent.com/5881327/213395009-e4db5e6c-5d58-45cc-8aab-f709d0075378.png)
![before2](https://user-images.githubusercontent.com/5881327/213395017-59693b84-820c-4e70-94a6-c3f94d2aa9d0.png)

After:

![after1](https://user-images.githubusercontent.com/5881327/213395052-0b96fe10-e190-4059-8b0c-14b1a2ad4573.png)
![after2](https://user-images.githubusercontent.com/5881327/213395062-3a01154f-8113-4a94-bc80-33ed77d4da22.png)

**Comment by lukewalczak** [comment]
So it's not the `Portal` component, but `FABGroup` and according to the [documentation](https://callstack.github.io/react-native-paper/fab-group.html#backdropColor), there is a prop called `backdropColor` where you can pass "transparent" color.

**Comment by DianaKoenraadt** [comment]
Does that accept RGBA so that I can get the exact old behavior?

**Comment by lukewalczak** [comment]
> Does that accept RGBA so that I can get the exact old behavior?

It should accept the RGBA color.

**Comment by DianaKoenraadt** [comment]
Ok, thanks!
