### ISSUE TITLE
CSS file missing from docs on gh-pages

### ISSUE THREAD

**Issue by TechWilk** [callstack/react-native-paper#3607]
### Current behaviour
CSS is missing from the docs.
`404: Not Found /app.css`

### Expected behaviour

Site should have CSS.

### How to reproduce?

Issue was introduced in the latest commit on `gh-pages` branch where `app.css` and related files were deleted
https://github.com/callstack/react-native-paper/commit/35690ba0ecadc07a239c97ae20ca95f46cdc2340

### Preview

![image](https://user-images.githubusercontent.com/9367803/213494592-22f3b347-6568-435d-8dea-f500bf92e735.png)

### What have you tried so far?

Hard reloading page, etc.

### Your Environment

N/A

**Comment by lukewalczak** [comment]
Hey, thanks for the report. Working on that
