### ISSUE TITLE
Toolbar: Redesign

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#361]
- [x] Rename Toolbar to Appbar
- [x] Support bottom Appbar with actions
- [ ] Support adding FAB in Appbar

![image](https://user-images.githubusercontent.com/1174278/39866811-71147394-5452-11e8-982a-b457883843c8.png)
![image](https://user-images.githubusercontent.com/1174278/39866827-77d56c4c-5452-11e8-8e88-0714f59b9231.png)

https://material.io/design/components/app-bars-bottom.html#anatomy

**Comment by ferrannp** [comment]
Should we split this issue in Top https://material.io/design/components/app-bars-top.html#usage and Bottom?

For Top it would also be very nice to have the Contextual action bar concept: 

![topappbars-contextual](https://user-images.githubusercontent.com/774577/39927750-8b324bd4-5533-11e8-82ff-4690be43f719.png)
