### ISSUE TITLE
FAB: invalid pattern -90deg and rgba(0, 0, 0, 0) This error is located at: in CrossFadeIcon

### ISSUE THREAD

**Issue by matinzd** [callstack/react-native-paper#3610]
### Current behaviour
Stacktrace from sentry:
```
Invariant Violation: invalid pattern -90deg and rgba(0, 0, 0, 0)

This error is located at:
    in CrossFadeIcon
```

<img width="979" alt="Screenshot 2023-01-20 at 11 47 23" src="https://user-images.githubusercontent.com/24797481/213677253-39914383-0ca7-462f-877c-3e6c73486ff0.png">

### Expected behaviour
It should not crash

### How to reproduce?
This is happening on production for some users.

### What have you tried so far?
Nothing

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.70.0
| react-native-paper    | 4.12.1

**Comment by lukewalczak** [comment]
Hey @matinzd, could you please provide more details about the platform and device on which users facing the crash? Based on the stacktrace I assume you are using FAB _(in that component is used `CrossFadeIcon`)_ – are you able to reproduce that crash?

**Comment by matinzd** [comment]
> Hey @matinzd, could you please provide more details about the platform and device on which users facing the crash? Based on the stacktrace I assume you are using FAB _(in that component is used `CrossFadeIcon`)_ – are you able to reproduce that crash?

It's very random but it happens both on iOS and Android. Yes, `CrossFadeIcon` is inside FAB component. I couldn't reproduce it myself since the crash is so random.

**Comment by lukewalczak** [comment]
@matinzd, are you able to replicate the code presenting how FAB is used in your project e.g. on the snack?

**Comment by lukewalczak** [comment]
Closing the issue due to lack of the reproducibility and inactivity. However, feel free to reopen the issue and share new findings if you have them ✌🏽
