### ISSUE TITLE
`cursorColor` support for RenderProps

### ISSUE THREAD

**Issue by mfds** [callstack/react-native-paper#3611]
RN 0.70.x has a new `cursorColor` feature that it would be nice to have available on the `RenderProps` types of the `TextInput` component.

https://github.com/callstack/react-native-paper/blob/622598cd1721dd548900b509a35f755d12fb6e32/src/components/TextInput/types.tsx#L16-L32

### Current behaviour
A small subset of props are passed

### Expected behaviour
New props to be passed to the render props

### Workaround
When using `render` prop, you can pass the prop directly to the native text input.

**Comment by lukewalczak** [comment]
Hey @mfds, I'll be more than happy to accept your contribution with `cursorColor` support.
