### ISSUE TITLE
Font Family Not working in react-native paper's TextInput

### ISSUE THREAD

**Issue by harshps08** [callstack/react-native-paper#3615]
I cannot use my font family in the android build, In normal TextInput it works fine when i add the styles but in paper's TextInput I am not able to do that

I am adding the font family as suggested in other threads but nothing worked for me.

Here Is the link for playground,
https://snack.expo.dev/6_ehtQ_VM

| software                      | version
| --------------------- | -------
| android                        | 12
| react-native                | 0.67.2
| react-native-paper    | 5.0.1

**Comment by lukewalczak** [comment]
Please check the guide related to the configuring [fonts](https://callstack.github.io/react-native-paper/fonts.html), there are some hints for customizing font family.

**Comment by harshps08** [comment]
Tried Everything from fontConfig to configureFonts, can you please guide me how it will work.
I have mentioned my react native paper version , I am trying to change fontFamily inside of TexInput

**Comment by lukewalczak** [comment]
If you want to override the font only in your `TextInput` you can the `theme` prop to use your font by customizing font variant used in the input – `bodyLarge`:

```
  theme={{
    fonts: { bodyLarge: { fontFamily: "Sans-Serif" } },
  }}
```

**Comment by harshps08** [comment]
Thank you for your help, this has done the job for me.

**Comment by nippysky** [comment]
Thank you so much. This also worked for me

**Comment by Vigneshwaran-crypto** [comment]
**Use Like this it will work :**  

import {  TextInput } from "react-native-paper";



   <TextInput
             
                  fontFamily={"Poppins-SemiBold"}                        
                  theme={{ fonts: { regular: "Poppins-SemiBold" } }}
                
                />


_use both of the props and it will work and  , please ensure you writes same font Names_

**Comment by mohcenesegouat** [comment]
> If you want to override the font only in your `TextInput` you can the `theme` prop to use your font by customizing font variant used in the input – `bodyLarge`:
> 
> ```
>  const theme = useTheme();	
> 
>   theme={{
>     fonts: { bodyLarge: { ...theme.fonts.bodyLarge, fontFamily: "Sans-Serif" } },
>   }}
> ```

Thank you very much, it works!

**Comment by raahimkhan** [comment]
> > If you want to override the font only in your `TextInput` you can the `theme` prop to use your font by customizing font variant used in the input – `bodyLarge`:
> > ```
> >  const theme = useTheme();	
> > 
> >   theme={{
> >     fonts: { bodyLarge: { ...theme.fonts.bodyLarge, fontFamily: "Sans-Serif" } },
> >   }}
> > ```
> 
> Thank you very much, it works!

Just came here to say 2 years later, it worked for me too!
