### ISSUE TITLE
AnimatedFAB Animation

### ISSUE THREAD

**Issue by iM-GeeKy** [callstack/react-native-paper#3618]
### Ask your Question

This question is two fold and I'm happy to move this to a discussion if that is the best fit. The first question is a typescript issue that was introduced in the last release and the other is more of an implementation question.

1. The first issue is since the last release `5.1.4` the typescript compiler appears to complain about the following style on the `AnimatedFAB`. The code is in the following [snack](https://snack.expo.dev/@fitzwabs/efe599).
```
style={[
  styles.position,
  { transform: [{ scale: animation }] }, // TYPESCRIPT ERROR HERE (Type 'Value' is not assignable to type 'number')
]}
```
I've had this in my personal project for many previous versions and it never complained until now. Is this an issue or should I restructure the animation? I can use `animation as any`, as a temporary resolution, but wouldn't like to settle on that long term.

2. Long story short, I'm trying to mock the [moving across tabs](https://m3.material.io/components/floating-action-button/guidelines#4dd3a071-5250-4b4b-97b8-78c7ca9e808f) behavior for the FAB suggested by Material Design.

An example is provided in the following [snack](https://snack.expo.dev/@fitzwabs/efe599). Note if you toggle the boolean on the following line

```
extended={isFabExtended} // Toggle this to false to see wrongly positioned start animation.
```

and switch tabs you'll notice the `extended={false}` FAB animates from what looks like the center of the `extended={true}` FAB. When the FAB is `extended={true}` is seems to behave properly.

### Preview

<img src="https://user-images.githubusercontent.com/7604441/214392942-2b3daffa-d30f-4374-a15b-b8b9e8b8c5bc.png" width="240" height="500">

Note: If I inspect the `AnimatedFAB` it looks like it still retains it's `extended={true}` width which might be why the `extended={false}` FAB still animates from the same location. Is this an implementation issue or do you have any ideas why this might be misbehaving?

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 16.2
| android                        | x
| react-native                | 0.70.5
| react-native-paper    | 5.1.4
| node                            | 16.16.0
| npm or yarn                | yarn
| expo sdk                     | 47.0.13

**Comment by lukewalczak** [comment]
@DimitarNestorov could you please take a look on the first point from the issue, related to the TypeScript?

**Comment by lukewalczak** [comment]
@iM-GeeKy If it comes to the second point, I have to _refresh_ my knowledge about that component and dive into the code. Once I get some findings, will let you know.

**Comment by lukewalczak** [comment]
Typescript issue should be solved and release in new library version.

> Note: If I inspect the AnimatedFAB it looks like it still retains it's extended={true} width which might be why the extended={false} FAB still animates from the same location. Is this an implementation issue or do you have any ideas why this might be misbehaving?

I guess that inspected element is the _invisible_ shadow container, which has to be rendered to ensure the correct _elevation_ animation. Please notice that there is no width animation, instead, we decided to play with elements translation to perform the animation on the native thread.

**Comment by iM-GeeKy** [comment]
> 

Alright, I appreciate you looking into this. It sounds like it's behaving as expected, but just seems a little wonky to me, especially when the animation is performed with `expanded={false}`. However, it's not a super high priority for me, so I'm content with closing this.

**Comment by iM-GeeKy** [comment]
> Hey @iM-GeeKy I will still investigate whether we can improve the extended animated fab measurements. In the meantime, could you please let us know whether your TS issue _(from point no 1)_ has been fixed?

Sounds good and the typescript issue has been fixed in the latest release. Thank you 👍🏻
