### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#362]
- [x] Change roundness to 4dp (https://material.io/design/material-theming/implementing-your-theme.html#shape)
- [x] Rename `paper` to `surface` (https://material.io/design/material-theming/implementing-your-theme.html#color)
- [x] Change error color to `#B00020`

![image](https://user-images.githubusercontent.com/1174278/39867119-b6e77f32-5453-11e8-93e0-b3daab138ea6.png)

https://material.io/design/material-theming/implementing-your-theme.html

**Comment by jaulz** [comment]
Do you think it would be worth to move most of the styles to the theme? E.g., in my case I would like to add some spacing to the cards (as in the previous version). In that case I could avoid creating wrapper components for simple adjustments.
