### ISSUE TITLE
Make numberOfLines a prop in Menu.Item

### ISSUE THREAD

**Issue by VariabileAleatoria** [callstack/react-native-paper#3626]
**Is your feature request related to a problem? Please describe.**
I'm showing a <Menu> containing <Menu.Item> elements whose Text is longer than screen size. Since <Text> inside Menu.Item has prop `numberOfLines={1}` it automatically gets truncated.

**Describe the solution you'd like**
It would be nice if the numberOfLines was a prop of the <Menu.Item> component, this would let the text go to new line and not get truncated.

**Comment by lukewalczak** [comment]
Based on the docs' specifications and guidelines I can observe examples where menu item has always one line. I don't see the reason to customize the number of lines, which additionally can bring other issues related to the wrong layout calculations, that's why I'm closing that request.
