### ISSUE TITLE
Button style not apply in theme version 2

### ISSUE THREAD

**Issue by alexanderfsm** [callstack/react-native-paper#3633]
### Current behaviour
<Button style={{ borderRadius: 50 }} buttonColor={colors.buttonAction} contentStyle={{ padding: 5, flexDirection: 'row-reverse' }} icon="open-in-new" mode="contained"
                        onPress={() => openLink("")} uppercase={false}>
                        text button
                      </Button>

import { Provider as PaperProvider, MD2LightTheme, MD2DarkTheme } from 'react-native-paper';

const ThemeDark = {
  ...MD2DarkTheme,
  roundness: 2,
  version: 2,
  colors: {
    ...MD2DarkTheme.colors,
    primary: '#000000',

### Expected behaviour
apply style in button

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 12
| react-native                | 0.71.1
| react-native-paper    | 5.1.4

**Comment by lukewalczak** [comment]
Could you please explain what exactly doesn't work? I've created a [snack](https://snack.expo.dev/@react-native-paper/button) based on your code snippet and I'm not able to observe any issue.

**Comment by pablop94** [comment]
I'm having the same issue with uppercase={false}, when using md2 in latest react native version. The button label is uppercase

**Comment by lukewalczak** [comment]
> I'm having the same issue with uppercase={false}, when using md2 in latest react native version. The button label is uppercase

Thanks for the report, we are going to fix that regression.

**Comment by alexanderfsm** [comment]
https://imgur.com/q2KDIuq

This bug only, this button inside card action

**This is work**

`<Card.Content style={{ marginBottom: 10 }}>
              <Button style={{ flex: 1, borderRadius: 50 }} buttonColor={colors.buttonAction} contentStyle={{ padding: 5, flexDirection: 'row-reverse' }} icon="open-in-new" mode="contained" onPress={() => irExterno(mensagem.rediurl)} uppercase={false}>
                Acessar Conteúdo
              </Button>
            </Card.Content>`

**this not work**

`<Card.Actions style={{ alignSelf: 'center' }}>
                <Button style={{ flex: 1, borderRadius: 50 }} buttonColor={colors.buttonAction} contentStyle={{ padding: 5, flexDirection: 'row-reverse' }} icon="open-in-new" mode="contained" onPress={() => irExterno(mensagem.rediurl)} uppercase={false}>
                  Acessar Conteúdo
                </Button>
              </Card.Actions>`

**Comment by lukewalczak** [comment]
@alexanderfsm I see the problem right now, will investigate that 🧐
