### ISSUE TITLE
Chip docs inconsistent with implementation

### ISSUE THREAD

**Issue by realtux** [callstack/react-native-paper#3635]
The problem is around the Chip's `outlined` mode. In the docs, it's implemented as either a filled chip without an outline (flat) or an unfilled chip with an outline (outlined). Example:

![image](https://user-images.githubusercontent.com/4989650/215551440-bc481b0e-4888-4e02-837f-cbfb3eb844f8.png)

In the implementation the difference between the two is the `borderWidth` only. Example:

![image](https://user-images.githubusercontent.com/4989650/215551705-abf69a0b-bfe2-4b60-8879-11562281f823.png)

I'm not sure if it's a bug or a docs issue, just wanted to mention it.

**Comment by lukewalczak** [comment]
Hey @realtux, could you please elaborate more on the inconsistency and explain exactly what we missed or overlooked?

**Comment by realtux** [comment]
I think what was overlooked was removing the background color of the `outlined` Chip. Currently, `outlined` is just `flat` with an outline.

**Comment by realtux** [comment]
My apologies, I was doing `type` and not `mode` thinking something was wrong, then misunderstood the code while confirming if something was actually wrong.

There's nothing wrong, sorry for wasting your time.
