### ISSUE TITLE
Is there a way to manually add a component within a portal?

### ISSUE THREAD

**Issue by chj-damon** [callstack/react-native-paper#3641]
### Ask your Question

I can create a compnent within a portal easily, but if I want to use a function to manually display this component, I don't know how.

something like this: `Modal.alert` display an AlertModal, or `Toast.success` display a toast in the screen.

also, I need to control when to close it. I suppose `Modal.alert` or `Toast.success` should return the key back and then `Portal.remove(key)` to delete it.

any suggestions?

**Comment by lukewalczak** [comment]
Hey @chj-damon, there is no such option to use `Portal` as a function to display the component.
