### ISSUE TITLE
Card contents can no longer fill card on web because of "fix"

### ISSUE THREAD

**Issue by SleeplessByte** [callstack/react-native-paper#3646]
### Current behaviour

It should be possible to fill a card by its contents, which is no longer possible due to #3469, based on the issue raised in #1775.

**Why does this matter?** Without explicitly setting the card contents size (not in percentages, like 100%), we can no longer add a background that fills, which is vital for complex backgrounds that cannot be set on `Card` directly.

**Why would you want this?** For example what we do a lot is set the `AspectRatio` of the Card via a parent:

```tsx
<AspectRatio w="16" h="9">
  <Card>
    ...
  </Card>
</AspectRatio>
```

This is no longer possible. The fix in #3469 was a breaking change.

### Expected behaviour
We have control over the fill behaviour, for example by exposing another style prop to set on the "inner card".

### How to reproduce?
https://snack.expo.dev/@derk-jan/card

### Preview
![image](https://user-images.githubusercontent.com/1964376/216102608-5cdf4d6f-4fc6-4290-a71f-06ccbde252f5.png)

### What have you tried so far?
Workaround is to inject css on the page to overwrite the behaviour.

**Comment by lukewalczak** [comment]
I think we can introduce the prop `contentStyle` property to allow customize the styles of the `View` wrapping the children.

```
        <View style={[styles.innerContainer, contentStyle]}>
```
