### ISSUE TITLE
Lists: extend functionality

### ISSUE THREAD

**Issue by gawrysiak** [callstack/react-native-paper#365]
2.0 idea. Consider making the ListItem component more flexible to support more use cases. Continuation of #329.

### Current behaviour

The current ListItem was designed to cover the old guidelines Lists, but not really the "Lists: Control" section which provided different use cases, e.g. switches, checkboxes and others. The code below:
```
<ListItem
  title="Push notifications"
  avatar={<MaterialIcons name="vibration" size={24} />}
  icon={
    <Switch
      value={this.state.notifications}
      onValueChange={() => {
        this.setState({ notifications: !this.state.notifications });
      }}
    />
  }
/>
```
is now displayed as:
<img width="362" alt="screen shot 2018-05-11 at 16 04 50" src="https://user-images.githubusercontent.com/7827311/39928894-ddbbb95a-5536-11e8-89ab-f3ba1a8fae36.png">
So despite using it in a strange way (icon placed as avatar, switch placed as icon), it tries to fix the switch size (icon). It also arranges the positions automatically (in case of 1 prop used, it's always on the left side).

### Expected behaviour

I'm currently using the `ListControl` component provided in the #329 PR to make it look better:
```
<ListControl
  title="Push notifications"
  primaryAction={<MaterialIcons name="vibration" size={24} />}
  secondaryAction={
    <Switch
      value={this.state.notifications}
      onValueChange={() => {
        this.setState({ notifications: !this.state.notifications });
      }}
    />
  }
/>
```
which displays:
<img width="373" alt="screen shot 2018-05-11 at 16 07 10" src="https://user-images.githubusercontent.com/7827311/39929149-9bbe8b80-5537-11e8-84e3-388ba4da27f9.png">
It doesn't provide a way to display an icon easily anymore and maybe the API is not perfect (maybe simply "primary" and "secondary", since it's not always actions), but it could be working well as a replacement for current ListItem component.

I feel like the lists are crucial for most of the apps. It would be nice to see them supporting more use cases. If you see any room for changes and have any API ideas, I'd be happy to help with the implementation.

### What have you tried

Using a custom component to provide the expected behavior.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | all
| react-native          | any
| react-native-paper    | 1.7.0
| node                  | 8.9.1
| npm or yarn           | 1.3.2

**Comment by satya164** [comment]
Added `left` and `right` props to `ListItem` as well as a `ListIcon` component which should address this issue.

**Comment by gawrysiak** [comment]
Very nice change. You're really pushing it 👌
