### ISSUE TITLE
Button flex problem on iOS

### ISSUE THREAD

**Issue by szado** [callstack/react-native-paper#3652]
### Current behaviour
There is a problem with buttons with `flex: 1` on iOS - buttons are not visible.

### Expected behaviour
Buttons should have proper width and be visible like on Android or web.

### How to reproduce?
https://snack.expo.dev/@szado/rnp-ios-button-problem?platform=ios
`but1` should occupy the entire available width instead it is invisible.

### Preview
IOS:
![obraz](https://user-images.githubusercontent.com/20907536/216799105-1eb7921b-652e-4cff-afca-c407917488f3.png)
Expected behaviour:
![obraz](https://user-images.githubusercontent.com/20907536/216799117-79481707-abcf-4069-a723-64eb7e8d8608.png)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | newest
| react-native-paper    | newest
| expo sdk                     | newest

**Comment by lukewalczak** [comment]
I will take a look at that
