### ISSUE TITLE
touchColor in BottomNavigation when Tab is active as a prop

### ISSUE THREAD

**Issue by danieldanielecki** [callstack/react-native-paper#3656]
### touchColor in BottomNavigation when Tab is active as a prop

During the upgrade from `react-native-paper` version `^4.9.2` till `^5.1.4` I noticed a new visual effect [BottomNavigation](https://callstack.github.io/react-native-paper/bottom-navigation.html)'s Tab is active, but it's not possible to disable it. It took me a while to realize from which package it's coming, and it wasn't one of the `@react-navigation/*`, as initially thought. It has been added between the v4 and v5 here. Is it possible to disable it, via some kind of prop? I couldn't find the prop.
What's the rationale to add such an effect without making us to control it?

<img width="335" alt="1" src="https://user-images.githubusercontent.com/12736263/216961833-37da97c6-94d6-4f35-b23f-9e17b2344925.png">
<img width="322" alt="2" src="https://user-images.githubusercontent.com/12736263/216961838-4a38e507-7cc4-4fd3-b097-bcb9ea4f20fc.png">

**Comment by lukewalczak** [comment]
> During the upgrade from react-native-paper version ^4.9.2 till ^5.1.4 I noticed a new visual effect [BottomNavigation](https://callstack.github.io/react-native-paper/bottom-navigation.html)'s Tab is active, but it's not possible to disable it. It took me a while to realize from which package it's coming, and it wasn't one of the @react-navigation/*, as initially thought. It has been added between the v4 and v5 here. Is it possible to disable it, via some kind of prop? I couldn't find the prop.
What's the rationale to add such an effect without making us to control it?

Do you mean the animated pill shape below the icon? If so, it was introduced in the latest Material Design generation called Material You.

**Comment by danieldanielecki** [comment]
@lukewalczak, yes! Thanks for the answer, it was my guess it's some kind of new convention. This question might be closed then:)
