### ISSUE TITLE
`fontFamily` get lost when `fontWeight` value is above `'600'`

### ISSUE THREAD

**Issue by jerryfishzz** [callstack/react-native-paper#3664]
### Current behaviour
I set up a font family in the theme setting. When I use List Accordion and List Item, I expect both titles and descriptions in the component should use the family I set up in the theme. But sometimes, they just use the default React Native Paper font family, not the one I set up. This ONLY happens on Android devices, not iOS.

### Expected behaviour
All the text in React Native Paper should use the font family I set up in the theme.

### How to reproduce?
I found out if I set `fontWeight` to any value above `'600'`, like `'700'`, `'bold'`, the font family setting on the text will get lost.

### What have you tried so far?
Since it only happens on Android, I only use `fontWeight` on iOS. For thicker font style on Android, I use the thicker font family instead.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.70.6
| react-native-paper    | ^5.1.3
| node                            | 14.19.3
| npm or yarn                | yarn 1.22.15
| expo sdk                     | x.x.x

**Comment by temchannat** [comment]
In`react-native-paper` version **5.2.0** , I use `TextInput` and set **fontFamily** to `style` props but it still take the default font. 

It doesn't work for me both iOS and Android. 

Here is how I do it: 

```
<TextInput
      label={"First Name"}
      underlineColor={'#FFF'}
      underlineColorAndroid={'#FFF'}
      returnKeyType={'next'}
      theme={inputLabelTheme}
      dense={false}
      style={{fontFamily: 'Lobster-Regular'}}
      value={this.state.lastname}
      onChangeText={lastname => this.setState({lastname})}
/>
```

**Comment by lukewalczak** [comment]
@temchannat to customize the `fontFamily` you need to override it in the `bodyLarge` variant, through the `theme` prop passed directly into the `TextInput` component:

```
      <TextInput
        label="Email"
        value={text}
        onChangeText={(text) => setText(text)}
        theme={{
          fonts: {
            bodyLarge: { fontFamily: 'Lobster-Regular' },
          },
        }}
      />
```

**Comment by lukewalczak** [comment]
@jerryfishzz could you please create the snack with your issue?

**Comment by temchannat** [comment]
> @temchannat to customize the `fontFamily` you need to override it in the `bodyLarge` variant, through the `theme` prop passed directly into the `TextInput` component:
> 
> ```
>       <TextInput
>         label="Email"
>         value={text}
>         onChangeText={(text) => setText(text)}
>         theme={{
>           fonts: {
>             bodyLarge: { fontFamily: 'Lobster-Regular' },
>           },
>         }}
>       />
> ```

Hello @lukewalczak 
Thank you very much. it works.

**Comment by jerryfishzz** [comment]
Hi @lukewalczak, sorry for the big delay of the repo. Here it goes:

https://snack.expo.dev/@jerry_paysauce/blissful-almond

Pls check it on ios and android separately.

Looks like `fontWeight: 'bold'` doesn't work on ios. If I want a bold version of Montserrat-Regular, I should use Montserrat-SemiBold or Montserrat-Bold, instead of using `fontWeight` to make Montserrat-Regular bold.

On android, `fontWeight` works but the sacrifice is the font family goes back to the default but not the custom one.

A little tip: the letter `J` is quite different from the default and custom font families.

**Comment by Athar-glut** [comment]
> Hi @lukewalczak, sorry for the big delay of the repo. Here it goes:
> 
> https://snack.expo.dev/@jerry_paysauce/blissful-almond
> 
> Pls check it on ios and android separately.
> 
> Looks like `fontWeight: 'bold'` doesn't work on ios. If I want a bold version of Montserrat-Regular, I should use Montserrat-SemiBold or Montserrat-Bold, instead of using `fontWeight` to make Montserrat-Regular bold.
> 
> On android, `fontWeight` works but the sacrifice is the font family goes back to the default but not the custom one.
> 
> A little tip: the letter `J` is quite different from the default and custom font families.

I am facing similar problem within react native without using react-native-paper
