### ISSUE TITLE
IconButton mode outlined does not have border

### ISSUE THREAD

**Issue by pablop94** [callstack/react-native-paper#3668]
### Current behaviour
According to the docs, when outline mode is used a border is displayed, but a flat Icon is rendered.

### Expected behaviour
Border is displayed

### How to reproduce?
```jsx
              <IconButton
                icon="plus"
                mode="outlined"
                onPress={() => console.log(true)}
              />
```

### Preview
![imagen](https://user-images.githubusercontent.com/20630332/217982111-0ccf2e0e-d56a-4140-81ea-bad88c24cf41.png)

### What have you tried so far?
I have included style prop to make the border visible.
![imagen](https://user-images.githubusercontent.com/20630332/217982317-87d22992-9056-4b00-a35f-501c95ace1be.png)

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.70.5
| react-native-paper    | 5.2.0
| node                            | 14.9.3
| npm or yarn                | 6.14.17
| expo sdk                     | 47.0.0

**Comment by pablop94** [comment]
Hi, I realized that I was using theme v2, so no border is defined. Maybe you want to add this to the docs, but the issue can be closed

**Comment by lukewalczak** [comment]
> Hi, I realized that I was using theme v2, so no border is defined. Maybe you want to add this to the docs, but the issue can be closed

Documentation exactly indicates that `mode` props is available in v5 only with the theme version 3:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/22746080/218041991-df38d875-1996-4bf3-86fa-014b29b157d2.png">
