### ISSUE TITLE
Move related components to static properties

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#367]
@Trancever implemented grouping for related components in component docs. Now we need to use it in Paper.

- [ ] Add related components as static properties instead of separate exports for `Card`, `Dialog`, `Toolbar`, `ListSection`, `DrawerSection`
- [ ] Add `displayName` to those components, e.g.: `static displayName = "Card.Actions" so that react docgen can read the name
- [ ] Add a comment like `// @component ./CardActions.js` above the static properties for the script
- [x] Read these properties in the script to get the list of files to build

We should do it in 2.0 since it'll be a breaking change.

![kapture 2018-05-12 at 17 35 11](https://user-images.githubusercontent.com/1174278/39958970-efe8a122-560a-11e8-88cb-600407fa5d11.gif)

**Comment by gawrysiak** [comment]
Good news, nicely done @Trancever 👍 

As for ListSection, it should be ListSection, ListSection.Item, ListSection.Accordion, right?

**Comment by satya164** [comment]
> As for ListSection, it should be ListSection, ListSection.Item, ListSection.Accordion, right

Yeah. I think so

**Comment by satya164** [comment]
Fixed in cf0531b
