### ISSUE TITLE
TextInput  Left and right nodes on customisation going out of border 

### ISSUE THREAD

**Issue by somasekharkakarla** [callstack/react-native-paper#3670]
### Current behaviour
When we add a left or right node it is not adjusting the width. It is going out of the outline

### Expected behaviour
TextInput  should adjust its node width and height or at least the width

### How to reproduce?
```
<TextInput.Icon style={{borderRadius:4, alignSelf:'center', marginRight:15,  width:100, backgroundColor:'red'}} onPress={() => {
    }} icon={() =>
      <View style={{flexDirection:'row', margin:5, justifyContent:'center'}}>
        <Text style={{color:COLOR.PLACEHOLDER_TEXT_COLOR, fontFamily:'Inter-Medium', fontSize:16}}>USD</Text>
        <Icon name={'chevron-down'} size={18} style={{alignSelf:'center'}} />
    </View>}
```

### Preview
<img width="401" alt="Screenshot 2023-02-10 at 4 52 10 PM" src="https://user-images.githubusercontent.com/65530762/218098446-7bb05636-941f-4ebe-bb3b-9dd66fe71204.png">

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 12
| react-native                | 0.70.5
| react-native-paper    | 5.0.0-rc.9

**Comment by somasekharkakarla** [comment]
Hi @lukewalczak ,

i upgraded react-native-paper package to v5.2.0. still right and left node issue exists.

It is working fine with one icon on both the left and right. But if we add more than one then there is a problem.

**With single icons**
<img width="967" alt="Screenshot 2023-02-13 at 10 05 35 AM" src="https://user-images.githubusercontent.com/65530762/218383035-0fc20985-4930-43ae-8564-6e828338e4c6.png">

**With two or more icons**
if I give the width
<img width="938" alt="Screenshot 2023-02-13 at 10 06 19 AM" src="https://user-images.githubusercontent.com/65530762/218383133-2a88d7b2-ea1f-43a6-a8da-72edee82c822.png">

without width
<img width="393" alt="Screenshot 2023-02-13 at 10 09 43 AM" src="https://user-images.githubusercontent.com/65530762/218383595-230955fe-295d-4ad2-af77-5d1ffe6e40d9.png">



**Expected behaviour**
<img width="938" alt="Screenshot 2023-02-13 at 10 06 19 AM" src="https://user-images.githubusercontent.com/65530762/218383240-8776e657-d004-48c8-b8df-5076b13eeef3.png">

<img width="906" alt="Screenshot 2023-02-13 at 10 11 37 AM" src="https://user-images.githubusercontent.com/65530762/218383923-4c95e571-cb2f-4059-afed-634170cf737e.png">


it should flexible with left and right. There should not be any limitations

Example code how I am adding more than one icon

```
<RNPTextInput
      outlineStyle={{borderRadius:0, borderWidth:0}}
      mode={'outlined'}
      style={[{margin:0, padding:0}]}
      left={<RNPTextInput.Icon style={{borderRadius:0,marginVertical:10,  backgroundColor:'red'}} icon={() => <View style={{height:25,justifyContent:'center', alignSelf:'center'}}>
        <View style={{flexDirection:'row', padding:5}}>
          <Image style={{width:25, height:25,padding:2,marginLeft:2, alignSelf:'center'}} source={require('../../../assets/images/gallery.png')}/>
          <Image style={{width:25, height:25,padding:2,marginLeft:2, alignSelf:'center'}} source={require('../../../assets/images/gallery.png')}/>
          <Image style={{width:10, height:10,padding:2,marginLeft:2, alignSelf:'center'}} source={require('../../../assets/images/down_arrow.png')}/>
        </View>
      </View>}/>}
      right={<RNPTextInput.Icon style={{borderRadius:0,marginVertical:10,  backgroundColor:'red'}} icon={() => <View style={{height:25,justifyContent:'center', alignSelf:'center'}}>
        <View style={{flexDirection:'row', padding:5}}>
          <Image style={{width:25, height:25,padding:2,marginLeft:2, alignSelf:'center'}} source={require('../../../assets/images/gallery.png')}/>
          <Image style={{width:25, height:25,padding:2,marginLeft:2, alignSelf:'center'}} source={require('../../../assets/images/gallery.png')}/>
          <Image style={{width:10, height:10,padding:2,marginLeft:2, alignSelf:'center'}} source={require('../../../assets/images/down_arrow.png')}/>
        </View>
      </View>}/>}
    />
```
Please fix it or let us know if is there any other way to work it out ASAP.

**Comment by lukewalczak** [comment]
As far as I know, both left and right props should accept only one icon, if I'm wrong please point to the Material Design documentation which indicates that behaviour.

**Comment by somasekharkakarla** [comment]
Hi @lukewalczak ,
Thank you for your reply. yeah, that is also true.
But what about these types of components? These are also used in a wide range. why don't you a leftViewBlock and rightViewBlock in TextInput
<img width="149" alt="Screenshot 2023-02-15 at 12 03 05 PM" src="https://user-images.githubusercontent.com/65530762/218969176-9a52897f-8044-41f2-a710-4859d612e397.png">
<img width="144" alt="Screenshot 2023-02-15 at 12 03 10 PM" src="https://user-images.githubusercontent.com/65530762/218969187-94a3c7bb-cc86-45fa-8b57-f0c10a153cde.png">
<img width="169" alt="Screenshot 2023-02-15 at 12 03 22 PM" src="https://user-images.githubusercontent.com/65530762/218969201-24da460e-81d7-413d-b284-aaf8e9db96a9.png">

**Comment by lukewalczak** [comment]
Hey @somasekharkakarla, I guess that the presented examples are not following the Material Design which the Paper library is supporting. I think we are not going to change the `TextInput` implementation to cover that specific case.

**Comment by lukewalczak** [comment]
Since that behavior does not coincide with our implementation and plans I'm closing the issue.
