### ISSUE TITLE
Animated Fab Label Issue!

### ISSUE THREAD

**Issue by helloworldpro501** [callstack/react-native-paper#3672]
Hi All.

I want to play animation to the left but I want the label to be on the right?? Is there way of doing this. I havent manipulated too much of the example code however I cant figure this out!
`<AnimatedFAB
                icon={'plus'}
                label={'Label'}
                extended={isExtended}
                onPress={() => console.log('Pressed')}
                iconMode={'dynamic'}
                animateFrom={'left'} --> this line make the label go on the left side of the icon which isnt what I want!!
                style={[{
                    position: 'absolute',
                }, fabStyle]}
            />`

**Comment by lukewalczak** [comment]
To achieve it you need to specify the following properties:

```
        animateFrom={'right'}
        iconMode={'dynamic'}
```

You can check it on the [snack](https://snack.expo.dev/@react-native-paper/104f4b)

**Comment by helloworldpro501** [comment]
Yes I tried this. So here is what I want. I want the animation to close on the left. Ill show images below.

<img width="887" alt="animateLeft" src="https://user-images.githubusercontent.com/125127035/218375980-b1461c3f-0060-48de-ae32-b161679643b3.png">
<img width="667" alt="animateLeftClosed" src="https://user-images.githubusercontent.com/125127035/218375932-670afe36-5ce3-4369-99b8-a3f3df4600bb.png">

I want it to close like this. However I want the label to be on the right of the icon before its closed.




With `animateFrom={'right'}` I can achieve the label being on the right side however when it closes its weird.


-----

With `animateFrom={'right'}` here is what I see.

<img width="672" alt="animateRight" src="https://user-images.githubusercontent.com/125127035/218376135-0412df9d-b7aa-431e-85e1-88448384c455.png">
<img width="671" alt="animateRightClosed" src="https://user-images.githubusercontent.com/125127035/218376155-87f80476-1cf1-4a54-a97f-d4c97aa27277.png">

This is what id like however when it closes it leaves a weird left margin.
