### ISSUE TITLE
Request for better documentation on Portal/Portal.Host

### ISSUE THREAD

**Issue by error-try-again** [callstack/react-native-paper#3682]
**Is your feature request related to a problem? Please describe.**
I had several issues when getting <Portal/> components to play nice and wanted to suggest that the documentation and examples on <Portal/> and <Portal.Host/> could be more comprehensive. I believe combining various examples makes more sense here. A real-world example I found when attempting to use a <Dialog/> was that I had issues where <Portal.Host/> was offsetting the height of other components on the screen of the <Portal.Host/>, even when the <Dialog/> component was hidden. 

e.g. 

```

 <>
      {visible && (
        <Portal.Host>
          <JoinTeamPortal
            joinTeam={joinTeam}
            onChangeText={onChangeText}
            handleHide={handleHide}
            visible={visible}
          />
        </Portal.Host>
      )}
      {visible ? null : (
        <>
          <FlashList
            ref={ref}
            data={teamData}
            renderItem={renderItem}
            keyExtractor={keyExtractor}
            removeClippedSubviews
            maxToRenderPerBatch={10}
            initialNumToRender={10}
            onEndReachedThreshold={0.5}
            estimatedItemSize={100}
          />
          <BottomButtonSection handleShow={handleShow} />
        </>
      )}
    </>
```

**Describe the solution you'd like**
Please amend the documentation with better real world examples.. Here is part of my working code. Please advise if you'd like to read over the full piece. 

_Portal Component_
```
const JoinTeamPortal = ({visible, handleHide, joinTeam, onChangeText}) => {
  const {colors, textColor} = Styles();
  return (
      <Provider>
        <KeyboardAwareScrollView>
          <Portal>
            <Dialog
                visible={visible}
                onDismiss={handleHide}
                style={{
                  alignSelf: 'center',
                  backgroundColor: colors.surface,
                  position: 'absolute',
                  top: '10%',
                }}>
              <Dialog.Title style={textColor}>Invite Code</Dialog.Title>
              <Dialog.Content>
                <TextInput
                    onSubmitEditing={joinTeam}
                    placeholder="Enter Invite Code"
                    onChangeText={(input) => onChangeText(input)}
                />
              </Dialog.Content>
              <Dialog.Actions>
                <View style={{flexDirection: 'row'}}>
                  <Button
                      mode="elevated"
                      buttonColor={colors.primary}
                      textColor={colors.text}
                      onPress={joinTeam}>
                    Join Team
                  </Button>
                </View>
                <View style={{flexDirection: 'row'}}>
                  <Button
                      mode="elevated"
                      textColor={colors.text}
                      buttonColor={colors.primary}
                      onPress={handleHide}>
                    Cancel
                  </Button>
                </View>
              </Dialog.Actions>
            </Dialog>
          </Portal>
        </KeyboardAwareScrollView>
      </Provider>
  );
};
```

_In the host component_

```
          {visible && (
              <Portal.Host>
                <JoinTeamPortal
                    joinTeam={joinTeam}
                    onChangeText={onChangeText}
                    handleHide={handleHide}
                    visible={visible}
                />
              </Portal.Host>
          )}
         <ButtonToActivatePortal handleShow={handleShow}/>

```

**Describe alternatives you've considered**
If verbosity is not in the spirit of the documentation, perhaps it would be worthwhile adding links to other examples as the snack was a copy and paste of the documentation code. 

**Additional context**
_with the {visible && (<Portal.Host/>)} logic_
![image](https://user-images.githubusercontent.com/19685177/219341643-dda84f02-bef6-4ea3-acaf-3df7e76e6c5d.png)
![image](https://user-images.githubusercontent.com/19685177/219341719-76c932e9-da26-4c14-806f-28b10a3b94b7.png)

_without the {visible && (<Portal.Host/>)} logic_
![image](https://user-images.githubusercontent.com/19685177/219341945-4b436567-763c-46be-9dbc-674eeedb7965.png)

Let me know if you need any more info.

**Comment by lukewalczak** [comment]
Hey @error-try-again, maybe we can introduce one of your examples into the demo app?

**Comment by error-try-again** [comment]
> Hey @error-try-again, maybe we can introduce one of your examples into the demo app?

Sounds good. Feel free to use the code I've already provided and if you'd like a full minimal reproducible example just let me know.

**Comment by lukewalczak** [comment]
> Sounds good. Feel free to use the code I've already provided and if you'd like a full minimal reproducible example just let me know.

I will appreciate if you can send the snack with your example which then we can adjust within the demo app or even you can directly create a PR with that 🙌🏽

**Comment by error-try-again** [comment]
Np https://snack.expo.dev/@error-try-again/react-native-paper-portal-minimal

**Comment by error-try-again** [comment]
thank you @lukewalczak you've been super helpful
