### ISSUE TITLE
HelperText should not have opacity on text

### ISSUE THREAD

**Issue by codexico** [callstack/react-native-paper#3684]
Why is this alpha used here? (https://github.com/callstack/react-native-
paper/blob/1074ab242280d1fe1b9eba3ab4cd41cd1578ce11/src/components/HelperText.tsx#L131)

According to m3 it should be simply theme.colors.onSurface. (https://m3.material.io/components/text-fields/specs#271a82dc-642c-49fc-8a97-0797b3eeb4dc)

**Comment by lukewalczak** [comment]
@codexico thanks for reporting the issue, I will correct it.
