### ISSUE TITLE
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.  

### ISSUE THREAD

**Issue by vaish8529** [callstack/react-native-paper#3687]
WARN  Require cycle: node_modules\react-native-paper\lib\module\components\FAB\FAB.js -> node_modules\react-native-paper\lib\module\components\FAB\FABGroup.js -> node_modules\react-native-paper\lib\module\components\FAB\FAB.js

    "react-native": "0.68.6",
    "react-native-paper": "^3.10.1",
     "react-native-vector-icons": "^6.6.0",

**Comment by sangameshsomawar** [comment]
@vaish8529 This issue is already fixed, Please update to the latest version and check.

**Comment by lukewalczak** [comment]
Hey @vaish8529, you are using quite outdated version, as @sangameshsomawar suggested, please update to the latest version.

**Comment by vaish8529** [comment]
@sangameshsomawar  @lukewalczak I have updated react-native-paper version to  5.2.0 still it gives following error:

 WARN  Require cycle: node_modules\react-native-paper\src\components\Appbar\AppbarContent.tsx -> node_modules\react-native-paper\src\components\Appbar\utils.ts -> node_modules\react-native-paper\src\components\Appbar\AppbarContent.tsx

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules\react-native-paper\src\components\Appbar\Appbar.tsx -> node_modules\react-native-paper\src\components\Appbar\AppbarHeader.tsx -> node_modules\react-native-paper\src\components\Appbar\Appbar.tsx

**Comment by sangameshsomawar** [comment]
@vaish8529 Yes this is valid.

**Comment by vaish8529** [comment]
Thanks for replying, How could I resolve this?

**Comment by FrederickEngelhardt** [comment]
Hmm, I'm still seeing this issue on 5.3.1

Ran a yarn why
```
yarn why v1.22.18
[1/4] 🤔  Why do we have the module "react-native-paper"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react-native-paper@5.3.1"
info Has been hoisted to "react-native-paper"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "6.78MB"
info Disk size with unique dependencies: "6.95MB"
info Disk size with transitive dependencies: "7.34MB"
info Number of shared dependencies: 11
✨  Done in 0.56s.
```
