### ISSUE TITLE
Disable material community icons

### ISSUE THREAD

**Issue by RichardLindhout** [callstack/react-native-paper#3688]
**Is your feature request related to a problem? Please describe.**
I don't want to add the material community icons

**Describe the solution you'd like**
I want the library to use the override Icon everywhere instead of somethings falling back to MaterialCommunityIcon (this should be done by the user). I want to overridde the material community icon en implement svg icons

**Additional context**
I believe this PR was not good: https://github.com/callstack/react-native-paper/pull/1630

Example in RNP code: https://github.com/callstack/react-native-paper/blob/main/src/components/Checkbox/CheckboxAndroid.tsx#L146

Maybe we could provide an internal implementation of the MaterialCommunityIcon in the provider too?

**Comment by lukewalczak** [comment]
Hey @RichardLindhout, according to the [Icons](https://callstack.github.io/react-native-paper/icons.html) doc if you don't want to instal `MaterialCommunityIcon` you can use [babel-plugin-optional-require]([babel-plugin-optional-require](https://github.com/satya164/babel-plugin-optional-require)):

> If you opted out of vector icons support using [babel-plugin-optional-require](https://github.com/satya164/babel-plugin-optional-require), you won't be able to use icon names for the icon prop. Some components may not look correct without vector icons and might need extra configuration.

Also according to point no 4:

> If you want to use icons other than MaterialCommunityIcons you need to import the icons and pass it to the settings prop within PaperProvider.

**Comment by RichardLindhout** [comment]
Yes I did that but on some components it does not use this settings icon

**Comment by lukewalczak** [comment]
I see, had to overlook that information. Basically what we have to do is replace the `MaterialCommunityIcon` used in a couple of components in favour of internal `Icon` component

**Comment by RichardLindhout** [comment]
Yes indeed :)
I use this component and override also some internal icons in react-native-paper-dates but suddenly I saw the checkbox did not work

**Comment by lukewalczak** [comment]
Unofrtunately I handled that ticket wrongly and introduced the breaking change in `5.3.0` that's why I had to [revert](https://github.com/callstack/react-native-paper/pull/3745) it, to avoid users confusion and further problems.

I will try to re-investigate that topic and apply the correct changes.
