### ISSUE TITLE
onTabLongPress for Bottom Navigation

### ISSUE THREAD

**Issue by alexanderblackh** [callstack/react-native-paper#3690]
**Is your feature request related to a problem? Please describe.**
I'd like to add an additional means of interacting with bottom navigation.

**Describe the solution you'd like**
In addition to onTabPress, add onTabLongPress to fire an event and callable function. Additionally, an onTabLongPressTime where you can customize the time of the press would be useful.

**Describe alternatives you've considered**
I can override the listener to add a double-click, but it's less than ideal.

**Additional context**
None.

**Comment by lukewalczak** [comment]
Hey @alexanderblackh, based on my research it's a common pattern, so feel free to send a PR with new functionality covered by unit tests 🙌🏽
