### ISSUE TITLE
Button: content (icon) style

### ISSUE THREAD

**Issue by kfaracik-odrabiamy** [callstack/react-native-paper#3702]
**Is your feature request related to a problem? Please describe.**
I wanted to use your component to build a button with an icon on top. Unfortunately your static icon margin style overwrote my forwarded content styles and the icon was not centered.

**Describe the solution you'd like**
I suggest expanding the buttons taking into account the possibility of this case (icon at the top). This would require slight modifications to iconStyles. A good solution could be a parameter with the position of the icon: left, right, top

**Comment by lukewalczak** [comment]
If I understand correctly the composition you are trying to achieve is not recommended according to the MD guidelines _(see the screenshot below)_ and most likely we are not trying to add support for it.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/22746080/221140406-bb8446dc-25f3-4665-bcea-1acbaaa42298.png">
