### ISSUE TITLE
`twitter-retweet` icon not working

### ISSUE THREAD

**Issue by Moriring0531** [callstack/react-native-paper#3708]
### Current behaviour

```typescript
<Button
            icon="twitter-retweet"
            mode="contained"
            onPress={() => {}}
          >
            {replyCount}
          </Button>
```
This code displays question-mark icon, not retweet icon on Web and iOS simulator.

### Expected behaviour

Displays retweet icon.

### How to reproduce?
Just do it!

### Your Environment
Using version 5.2.0

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hey @Moriring0531, the library by default support `MaterialCommunityIcons` which doesn't have the mentioned icon called `twitter-retweet`. The full list of available icons you can find [there](https://pictogrammers.com/library/mdi/)
