### ISSUE TITLE
Menu.Item title wrap

### ISSUE THREAD

**Issue by danieljcorreac** [callstack/react-native-paper#3714]
Is it possible to have the text used in the title prop to be wrapped when it is too long to fit on one line?

This functionality is applied in List.Item but it was not applied in Menu.Item.

**Comment by lukewalczak** [comment]
Hey @danieljcorreac, I think that text within the `Menu.Item` should always take only one line and believe shouldn't be wrapped into more. I've checked the documentation guidelines and it's not explicitly stated, however I'm currently against that idea, based on the different apps which are using menu.
