### ISSUE TITLE
Menu Items with long text 

### ISSUE THREAD

**Issue by JonasWho** [callstack/react-native-paper#3718]
**Is your feature request related to a problem? Please describe.**
Texts get cut off when `Menu.Item` has a very long title or when users turn on increased font size in their accessibility settings.

**Describe the solution you'd like**
I would love to see two props introduced on `MenuItem`:

1. `allowFontScaling` on title text.
2. Something like `allowLinkBreaks` which would set the item style `height: 'auto'` and change `numberOfLines` on title `Text` to more than 1.

**Describe alternatives you've considered**
I wonder whether `height: 48` is needed at all on `styles.container` in `MenuItem.tsx`? If not, then `numberOfLines` property on Text could be exposed and this would fix my 2. above.

Screenshot of my issue to be clear:
![Screenshot 2023-03-02 at 15 26 29](https://user-images.githubusercontent.com/925342/222456429-2bedcf6c-bfc2-4f84-baa6-6351021ca131.png)

**Comment by lukewalczak** [comment]
Hey @JonasWho, thanks for the feedback, I will look into it!

**Comment by lukewalczak** [comment]
Actually, the idea about introducing the possibility to customize the `numberOfLines` into `Menu.Item` I recently rejected and explained in the following [message](https://github.com/callstack/react-native-paper/issues/3714#issuecomment-1451619928). 

I think we can follow the approach introduced e.g. in `BottomNavigation` and add the prop for setting `maxFontSizeMultiplier` where you can pass the value which will fit into your case.

**Comment by JonasWho** [comment]
Ok, fair enough. Being able to set `maxFontSizeMultiplier` would be a bit help though 👍
