### ISSUE TITLE
TextInput in a specific configuration shows visual artifact on iOS and Web

### ISSUE THREAD

**Issue by CodingItWrong** [callstack/react-native-paper#3722]
### Current behaviour
I get a dark gray bar appearing at the top of a `TextInput` when all the following are true:

- Displaying in light mode
- Multiline
- Disabled
- Flat

### Expected behaviour

I do not expect the dark gray bar to appear; I expect the field background to display consistently as in the other combinations of settings above.

### How to reproduce?
Just render out a `<TextInput multiline disabled />`.

Reproduction is on this branch: [GitHub - CodingItWrong/paper-sandbox at disabled-multiline-text-issue](https://github.com/CodingItWrong/paper-sandbox/tree/disabled-multiline-text-issue)

### Preview

The issue:

![image](https://user-images.githubusercontent.com/15832198/222819344-6ba0948e-b80a-45fa-a57d-5acd6e922eb2.png)

No issue in dark mode:

![image](https://user-images.githubusercontent.com/15832198/222819484-628833e1-c056-450f-a9de-038d06ab18ee.png)

### What have you tried so far?
Narrowed down the bug to only the configuration described above.

Other than that, I'm not totally sure of workarounds I might be able to do.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 16.2
| react-native                | 0.71.3
| react-native-paper    | 5.2.0
| node                            | 18.14.2
| npm or yarn                | yarn
| yarn                             | 1.22.19
| npm                             | 9.6.0
| expo sdk                     | 48.0.5

**Comment by lukewalczak** [comment]
@CodingItWrong thanks for the report, I'm able to reproduce the issue, so will tackle it.
