### ISSUE TITLE
Document how to use custom fonts

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#373]
We should provide/link to instructions for using a custom font since it's a lot more work than just changing the font family in theme.

**Comment by lucasharada** [comment]
@satya164 Is there really a way to do it? I'm trying to change `<TextInput />` font, but with no success yet.

**Comment by greghaygood** [comment]
It wasn't much work to switch to the Roboto fonts for my current app. Follow the process here: https://medium.com/@moschan/easiest-way-to-load-your-custom-fonts-in-react-native-d091fb380204

Steps 1-4 setup the project, then I configured the provider like so:

```
const theme = {
  ...DefaultTheme,
  fonts: {
    regular: 'Roboto',
    medium: 'Roboto',
    light: 'Roboto Light',
    thin: 'Roboto Thin',
  },
}

class Root extends PureComponent<Props, State> {
  static defaultProps = {}

  render () {   
    return (
      <PaperProvider theme={theme}>
        <MyAppEntryPoint />
      </PaperProvider>
    )
  }
}
```

**Comment by Taym95** [comment]
Hi, where we should add this documentation?

**Comment by satya164** [comment]
@Taym95 I think a new page under "guides" section will be good
