### ISSUE TITLE
IOS - Button Width Design Bug

### ISSUE THREAD

**Issue by Rehankhalil462** [callstack/react-native-paper#3733]
### Current behaviour
Width is not properly being applied for IOS while it is working as it is expected on Android.

### Expected behaviour
It should Show the similiar widths like Android.

### Preview
Android
![android](https://user-images.githubusercontent.com/76107872/223388961-c1f80ed4-a695-4842-861f-42e145161ce0.jpeg) 
IOS
![ios](https://user-images.githubusercontent.com/76107872/223388970-e5b81e88-4c67-4107-9ac4-d011bb032f14.jpeg)

### What have you tried so far?
This is the code for above pictures. It is working fine on Android as you can see above but not working as expected on IOS
 ```javascript 
<View
                      style={{
                        width: "100%",
                        alignItems: "center",
                        justifyContent: "space-between",
                        flexDirection: "row",
                        backgroundColor: "pink",
                      }}
                    >
                      <Button
                        theme={fulltheme}
                        mode="contained"
                        contentStyle={{
                          height: 60,
                          width: "100%",
                        }}
                        style={{
                          width: "48%",
                        }}
                      >
                        <Text
                
                          style={{
                            fontSize: 20,
                            fontWeight: "400",
                            letterSpacing: 0.2,
                          }}
                        >
                          Cancel
                        </Text>
                      </Button>
                      <Button
                        theme={fulltheme}
                        contentStyle={{
                          height: 60,
                          width: "100%",
                        }}
                        style={{
                          width: "48%",
                        }}
                        mode="contained"
                      >
                        <Text
                          style={{
                            fontSize: 20,
                            fontWeight: "400",
                            letterSpacing: 0.2,
                          }}
                        >
                          Send
                        </Text>
                      </Button>
                    </View>
```
### Your Environment

| software                      | version
| --------------------- | -------
| ios                                |  iPhone 11 -  Software Version -15.5
| android                       |  Samsung S22 Ultra
| react-native                | 0.70.5
| react-native-paper    | 5.2.0
| node                            | v16.15.1
| npm or yarn                npm | 8.11.0
| expo sdk                     | 47.0.12

**Comment by DimitarNestorov** [comment]
Snack: https://snack.expo.dev/@dimitarnestorov/mature-tea

**Comment by Rehankhalil462** [comment]
Waiting for this pull request to be merged.
