### ISSUE TITLE
Warning after clean install or update to Expo SDK 48

### ISSUE THREAD

**Issue by mathias-berg** [callstack/react-native-paper#3737]
### Current behaviour
After updating (or creating a new Expo project) this warning shows up as soon as I add `Provider` when using it on web.

### Expected behaviour
Not show the warning.

### How to reproduce?
Create a new Expo project:
`yarn create expo-app folder-to-install-app-in`
`yarn add react-native-web react-dom @expo/webpack-config`

Run `yarn web` and it will start fine without any warning.
Add React Native Paper with `yarn react-native-safe-area-context react-native-paper`
Wrap `App.js` with `<Provider>...</Provider>`.

Run `yarn web`.

Warning shows up. 

### Preview
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/26097801/223860499-054128fd-eb86-47a6-86de-4c66b9f91714.png">

### What have you tried so far?
Nothing but testing a clean install instead of upgrading, both with the same result.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.71.3
| react-native-paper    | 5.3.1
| node                            | 18.14.2
|  yarn                            | 1.22.19
| expo sdk                     | 48.0.0

**Comment by mathias-berg** [comment]
Not sure if this is a problem with Paper or Expo, but since it showed right away after I added `Provider` I put it here. :)

**Comment by lukewalczak** [comment]
@mathias-berg, @rinaldycodes please try the version `5.4.1`

**Comment by mathias-berg** [comment]
@lukewalczak, this fixed the warning! Thanks!
