### ISSUE TITLE
Require cycles in 5.3.1 AppBar, AppbarHeader, AppbarContent, TextInput

### ISSUE THREAD

**Issue by FrederickEngelhardt** [callstack/react-native-paper#3740]
### Current behaviour
Appbar requires AppbarHeader which requires Appbar. Same with the other items listed below.

### Expected behaviour
Behavior should be abstracted away from one of the components. Perhaps both of them should require an AppbarShared and AppBarHeader would only import that shared component.

Same applies for the other use cases. See the other require cycles section below.

### How to reproduce?
Download latest version of react-native-paper@5.3.1 and use with https://reactnavigation.org/docs/material-bottom-tab-navigator/.

### Preview
```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/react-native-paper/src/components/Appbar/Appbar.tsx -> node_modules/react-native-paper/src/components/Appbar/AppbarHeader.tsx -> node_modules/react-native-paper/src/components/Appbar/Appbar.tsx
```

### Other require cycles:
`npx dpdm ./src/index.tsx --tree false`

Outputs this:
```
  1) src/components/Appbar/AppbarContent.tsx -> src/components/Appbar/utils.ts
  2) src/components/TextInput/TextInput.tsx -> src/components/TextInput/Adornment/TextInputAffix.tsx -> src/components/TextInput/helpers.tsx -> src/components/TextInput/types.tsx
```

### What have you tried so far?
Forked the library and looked at the code. From what I'm seeing, one of these components could require the other, and the other one could share information.

See this draft PR for more references on the changes #3739 

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 14.0/14A309
| android                        | API 31 (java 11)
| react-native                | 0.68.1
| react-native-paper    | 5.3.1
| node                            | 16.15.0
| npm or yarn                | 1.22.18
| expo sdk                     | N/A

**Comment by sootood** [comment]
hi 
i have same problem in my custom component how do you fix it because my app is big and cant change  all imported paths
please help me

**Comment by JairajJangleSLIOT** [comment]
Any updates on this to reduce the require cycle noisy logs?
