### ISSUE TITLE
Provider background issue || Modal

### ISSUE THREAD

**Issue by SashaGoncharov19** [callstack/react-native-paper#3742]
### Current behaviour
After dependencies update and move to EAS build modal provider hides screen background elements.

### Expected behaviour
When the modal active, where's provider has opacity and need to show background elements, no hiding it.

### How to reproduce?
https://callstack.github.io/react-native-paper/docs/components/Modal
This sample not working as on video. 

### Preview
[Video](https://www.youtube.com/watch?v=_EAv9Za3dDc)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                               | 15.7.3
| android                       | not used
| react-native                 | 0.71.3
| react-native-paper      | 5.3.1
| node                            | v16.17.1
| npm or yarn                | yarn 1.22.19
| expo sdk                     | 48.0.0

**Comment by lukewalczak** [comment]
Hey @SashaGoncharov19, could you please attach the snack with the code which you've used to record the video?

**Comment by SashaGoncharov19** [comment]
So, I investigated this bug. Problem was on theme config, on 'backdrop' option. I don't know how it's worked before, but if someone will had this problem, just check your theme config.

**Comment by lukewalczak** [comment]
> So, I investigated this bug. Problem was on theme config, on 'backdrop' option. I don't know how it's worked before, but if someone will had this problem, just check your theme config.

Hey @SashaGoncharov19 I assume your issue has been resolved, so closing it.
