### ISSUE TITLE
Proper RTL support

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#375]

**Comment by satya164** [comment]
@colmbrady we don't have an estimate. PRs are welcome on this, or even issues which identify the components which are broken :)

**Comment by iyadthayyil** [comment]
### TODO

- [ ] BottomNavigation
- [x] Button
- [ ] Caption **
- [ ] Card
- [ ] CardActions
- [x] CardContent
- [x] CardCover
- [x] Checkbox
- [x] Chip
- [ ] Dialog
- [x] DialogActions
- [x] DialogContent
- [x] DialogScrollArea
- [ ] DialogTitle **
- [x] Divider
- [x] DrawerItem
- [ ] DrawerSection **
- [x] FAB
- [x] FABGroup
- [ ] Headline **
- [ ] HelperText **
- [ ] ListAccordion **
- [ ] ListItem **
- [ ] ListSection **
- [x] Modal
- [x] Paper
- [ ] Paragraph **
- [x] ProgressBar *
- [x] RadioButton
- [x] RadioButtonGroup
- [ ] Searchbar **
- [ ] Snackbar **
- [ ] Subheading **
- [ ] Switch *
- [ ] Text **
- [ ] TextInput **
- [ ] Title **
- [ ] Toolbar
- [ ] ToolbarAction ***
- [ ] ToolbarBackAction ***
- [ ] ToolbarContent **
- [x] TouchableRipple

* Working when "Force RTL layout direction" option is enabled from developer options not working with `I18nManager.forceRTL(true);`.

** TextAlign issue. 

*** All icons to be filliped.

Tested on Android 8.0 !

**Comment by saharjedid** [comment]
@iyadthayyil i have a wrong position of label when i use the RTL mode please how can i fix it ? 
![error](https://user-images.githubusercontent.com/43675705/49150539-7c47ba00-f30d-11e8-8628-e47c8f57dba0.png)
this is my code 
<TextInput
            mode='outlined'
            label=' رقم بطاقة التعريف الوطنية'
            numberOfLines={1}
            style={this.getStyle().TextInp}
            theme={{ colors: {placeholder: 'white', background:'#003489',text: 'white',primary: 'white'}}}
            
            />

**Comment by avirankatzsofi** [comment]
Checkbox icon is flipped in RTL (#1675). Will there be a fix anytime soon?

**Comment by keiscool2468** [comment]
<img width="185" alt="Screenshot 2020-05-13 at 10 28 25 AM" src="https://user-images.githubusercontent.com/22214095/81764619-89a63380-9504-11ea-9984-acedfaba0b0a.png">
@avirankatzsofi
`<Chip
        mode="outlined"
        icon={{source: 'camera', direction: 'rtl'}}
        onPress={onPress}
>
        {text}
      </Chip>`
do chip able to apply same logic?
