### ISSUE TITLE
Autofill label overlap in 'outlined' mode of textinput.

### ISSUE THREAD

**Issue by avzz-19** [callstack/react-native-paper#3757]
When textinput is autofilled upon loading a page, the textinput label is still in the placeholder place until clicking on the textinput #2764
 Any update on this issue? It is still happening in 'outlined' mode.
<img width="421" alt="image" src="https://user-images.githubusercontent.com/87358607/225514407-02a67717-7c4b-42a7-ac90-bb02e282be57.png">

_Originally posted by @avzz-19 in https://github.com/callstack/react-native-paper/issues/2764#issuecomment-1471287664_

**Comment by lukewalczak** [comment]
Hey @avzz-19, please provide more details about used `react-native-paper` version, MD generation (2 or 3) and ideally provide the snack.

**Comment by avzz-19** [comment]
> Hey @avzz-19, please provide more details about used `react-native-paper` version, MD generation (2 or 3) and ideally provide the snack.
I have used version 5.2.0 of react-native-paper.  I am using a react-native mono repo.
This happens only on browser autofill, so a snack example cannot reproduce the issue.

Code:-
<TextInput
        label='Work email'
        value={email}
        onChangeText={(text) => setEmail(text)}
        mode='outlined'
      />

Details:-
"react": "^18.2.0",
"react-native": "^0.70.1",
"react-native-paper": "5.2.0"
"react-native-web": "^0.18.9",
"react-native-webview": "^11.25.0",
