### ISSUE TITLE
Tooltip appears for a brief time in upper left hand corner before going to correct position

### ISSUE THREAD

**Issue by autovisasaaron** [callstack/react-native-paper#3774]
### Current behaviour
When adding a tooltip to the element
On Hover

### Expected behaviour
Tooltip should appear below hovered item

### How to reproduce?
Add a <Tooltip> to any <Pressable>

### What have you tried so far?
Currently no positioning props are exposed so not much to try

### Your Environment

happening on Chrome web with latest react-native-paper

**Comment by robozb** [comment]
How can I force the Tooltip prefers to put  its position to top?
