### ISSUE TITLE
Tooltip long press bug

### ISSUE THREAD

**Issue by iM-GeeKy** [callstack/react-native-paper#3787]
### Current behaviour

Long pressing a tooltip component causes an error.

### Expected behaviour

The long press action should display the tooltip.

### How to reproduce?

https://github.com/iM-GeeKy/tooltip-bug

### Preview

![Simulator Screen Shot - iPhone 14 Pro - 2023-03-27 at 14 51 25](https://user-images.githubusercontent.com/7604441/228038681-59b65729-dc53-4f39-89de-47f3af24ce36.png)

### What have you tried so far?

N/A

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 16.2
| android                        | x
| react-native                | 0.71.4
| react-native-paper    | 5.5.1
| node                            | 16.16.0
| npm or yarn                | npm
| expo sdk                     | 48.0.9

**Comment by lukewalczak** [comment]
Hey @iM-GeeKy, please try the `react-native-paper@5.5.2`

**Comment by iM-GeeKy** [comment]
> Hey @iM-GeeKy, please try the `react-native-paper@5.5.2`

Looks good, thanks for the quick fix!
