### ISSUE TITLE
Adapt the Default theme when You open the Example App to The default theme of the Device

### ISSUE THREAD

**Issue by AmrouKourchid** [callstack/react-native-paper#3789]
**Problem Description:**
Regardless of my device's default theme (dark mode or light mode), whenever I open the example app, it opens always in Light Theme Instead of my device's theme. 

**Solution Description:**
The Example App opens in my device's default theme, and the switcher in the drawer navigator changes it to the other theme.

**Alternatives**
Make the default value of the dark mode switcher dependent on the device's current theme. To illustrate, if my device is in dark theme, the switcher should be enabled by default. Otherwise, the app opens in light mode and the dark mode switcher is disabled.

**Additional context**
I have checked the previous issues and pull requests for duplicates and it did not seem that this matter has been previously discussed.

**Comment by lukewalczak** [comment]
Hey @AmrouKourchid, by the Example App you meant our demo app available in the store or your own app?

**Comment by AmrouKourchid** [comment]
Hey @lukewalczak  thanks for interacting ! I mean the demo app available in the store.

**Comment by lukewalczak** [comment]
Hey @AmrouKourchid, there is nothing to worry about in the Example app, we are passing there a default theme (the light one) by default, which you can observe in that [line](https://github.com/callstack/react-native-paper/blob/77c60eff37a5817604593e410d9caaf0d9113e9d/example/src/index.tsx#L218). If you want to change it, as you there a switch in the drawer.

If you want to observe the dynamic theme change between those two modes, you can go to the `Theme` item.

**Comment by AmrouKourchid** [comment]
Hello again, @lukewalczak .
While It is true that the switcher and the Theme item exist, the app doesn't automatically adapt to the device's given theme. 
I proposed this as a feature since several apps use this to illustrate their components while giving the user their preferred theme.

 To make it even more Clear, it Shouldn't be just the theme item that adapts to the system preferences, it should be the whole example app, then if the user wants to switch to other themes, there's the switch and `Theme` item as you have mentioned.
 
 Hope this was clear.
