### ISSUE TITLE
ripple effect not working on ios emulator

### ISSUE THREAD

**Issue by sharifashraful** [callstack/react-native-paper#3795]
ripple effect not working on ios emulator

react-native-paper latest version
emulator iphone 14

**Comment by AmrouKourchid** [comment]
Hi,

Can you please provide more info about your issue? For example, the current behavior, the expected behavior and some screenshots? 

Thank you.

**Comment by sharifashraful** [comment]
@AmrouKourchid 
https://user-images.githubusercontent.com/7131239/229228070-d6584fe8-4b06-44a1-a2c1-2da1961b2274.mov

Please check the video. ripple behavior is not like android

**Comment by lukewalczak** [comment]
The ripple effect is specific for Android and web platforms only and on the iOS according to the documentation, it fallbacks to highlight effect:

> On unsupported platforms, it falls back to a highlight effect.

**Comment by LeulAria** [comment]
so for ios it will not work ?
