### ISSUE TITLE
Bug Dialog action button

### ISSUE THREAD

**Issue by elmcapp** [callstack/react-native-paper#3796]
I am using the lates version of react native and react native paper. I am getting an issue where when my dialog have multiple buttons and I have the mode set to contained the buttons spaced. 

"react-native-paper": "^5.5.2",

````
 <Portal>
      <Dialog visible={props.visible}>
        <Dialog.Title>Icon Upload Required</Dialog.Title>
        <Dialog.Content>
          <Text variant="bodyMedium">
            It appears you are using icons that have not been saved to the
            cloud. Would you like to upload the icon to the cloud? If not, any
            icons used in this layout will not be visible
          </Text>
        </Dialog.Content>
        <Dialog.Actions>
          <Button onPress={props.onHide}>Cancel</Button>
          <Button mode="contained" onPress={handleDontUpload}>
            Don't Upload
          </Button>
          <Button mode="contained" onPress={handleUploadPress}>
            Upload
          </Button>
        </Dialog.Actions>
      </Dialog>
    </Portal>
````
    
<img width="295" alt="Screenshot 2023-04-01 at 10 07 38 PM" src="https://user-images.githubusercontent.com/64275658/229328610-d2e09729-4a82-4285-89d7-809a03c43068.png">

**Comment by lukewalczak** [comment]
Hey @elmcapp I've pasted your code into the expo [snack](https://snack.expo.dev/@react-native-paper/multiple-buttons-in-dialog) and I'm not able to observe any issue, could you please create your own snack presenting the problem?

**Comment by lukewalczak** [comment]
The issue is being closed as it has been inactive and the problem cannot be reproduced.

**Comment by SachinKhokharSol** [comment]
It being reproduced. Try https://snack.expo.dev/@react-native-paper/multiple-buttons-in-dialog IPhone 16 pro. Select run in expo when asked.
