### ISSUE TITLE
Enable Running Example App on iOS

### ISSUE THREAD

**Issue by MrLoh** [callstack/react-native-paper#380]
Since it is not possible to run expo apps in your account, that are not your own, it isn't possible to run the example app on iOS anymore, is there any new setup to try out the library on expo, by running a snack project from your own account for example?

**Comment by vikas5914** [comment]
You can download the example and run on your own expo account 

https://github.com/callstack/react-native-paper/tree/master/example

**Comment by satya164** [comment]
We use Snack for the example now which should work on iOS.
