### ISSUE TITLE
Searching `Text` in docs goes to 404 link

### ISSUE THREAD

**Issue by remarkablemark** [callstack/react-native-paper#3804]
### Current behavior

Searching for `Text` in docs goes to 404 link: https://callstack.github.io/react-native-paper/docs/components/Typography/Text/

### Expected behavior

Searching for `Text` in docs should go to: https://callstack.github.io/react-native-paper/docs/components/Text/

### How to reproduce?

1. Given I go to https://callstack.github.io/react-native-paper/docs/components/Text/
2. When I click `Search` and type `Text`
3. Then I should see `Text` page

### Preview

https://user-images.githubusercontent.com/10594555/230241464-a683e56d-cd60-4747-babf-a18134f6d9ab.mov

### What have you tried so far?

N/A

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hey @remarkablemark, thanks for reporting the issue. I've just restarted algolia crawler and looks like it did the trick!
