### ISSUE TITLE
AnimatedFAB should have a shadow at elevation level 3

### ISSUE THREAD

**Issue by ericpoulinnz** [callstack/react-native-paper#3805]
### Current behaviour
When in M3, the shadow of the AnimateFAB is at level 6.

### Expected behaviour
According to [M3 spec](https://m3.material.io/components/extended-fab/specs), the FAB should have a shadow of level 3

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 5.5.2
| react-native-paper    | 0.71.6
| expo sdk                     | 48.0.0

**Comment by lukewalczak** [comment]
Hey @ericpoulinnz, there is applied [elevation level 3](https://github.com/callstack/react-native-paper/blob/main/src/components/FAB/AnimatedFAB.tsx#L339) in the `AnimatedFAB` when `isV3`:

```
  const md2Elevation = disabled || !isIOS ? 0 : 6;
  const md3Elevation = disabled || !isIOS ? 0 : 3;

  return (
    <Surface
		/ ... /
      style={[
        !isV3 && {
          elevation: md2Elevation,
        },
      ]}
      {...(isV3 && { elevation: md3Elevation })}
    >
		/ ... /
```

**Comment by ericpoulinnz** [comment]
@lukewalczak I am using V3. It's in the styles that there is a problem. 

```const styles = StyleSheet.create({
/ ... /
  shadowWrapper: {
    elevation: 0,
  },
  shadow: {
    elevation: 6,
  },
/ ... /
});```

Changing the elevation there to 3 works.

**Comment by lukewalczak** [comment]
Thanks @ericpoulinnz, I will double check it 👍🏽
