### ISSUE TITLE
TextInput outlined strange inside a view

### ISSUE THREAD

**Issue by Angelk90** [callstack/react-native-paper#3811]
### Current behaviour

As you see from start to weird behavior you don't see placeholder text.
Which instead of in the same input field as above but not found in the view, is seen correctly.

### Expected behaviour

Same behavior as the input field above.

### How to reproduce?

You can also try it with android expo emulator:
https://snack.expo.dev/exQQvm0ve

### Preview

https://user-images.githubusercontent.com/20476002/230880067-fe8d8e37-1edf-41ae-9463-43d68709da86.mov

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 10
| react-native                | 0.71.4
| react-native-paper    | 5.6.0
| node                            | 16.14.2
| npm                             | 9.6.2

**Comment by lukewalczak** [comment]
> It seems to work, but you have to understand why the component breaks.

Could you please explain what is the issue on the attached snack?

**Comment by lukewalczak** [comment]
Sorry, but I feel confused atm, has your problem been solved or do you need more help with that issue?

**Comment by lukewalczak** [comment]
I see, I will check what's the problem with the placeholder
