### ISSUE TITLE
Appbar Action icon shake and rotate

### ISSUE THREAD

**Issue by biangwua** [callstack/react-native-paper#3813]
### Current behaviour

When the following situations occur including but not limited to: 1. @react-native-community/viewpager is in the process of sliding (the page is re-rendered at this time) 2. When the textInput component of reatnativepaper is inputting content, the icon in the AppBar will be displayed Jitter and spin
### Expected behaviour

Icons in AppBar do not shake and rotate
### How to reproduce?

https://snack.expo.dev/@biang_wua/searchbar-and-icomoon-in-rnpaper-5-3-1
### Preview

https://user-images.githubusercontent.com/76552428/231208067-3b09a092-6e85-4d25-b9d8-1fbd9784da23.mp4

https://user-images.githubusercontent.com/76552428/231208301-b4bea132-4774-4e3f-88d8-dee341f105f6.mp4

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | latest
| react-native                | 0.71.6
| react-native-paper    | ^5.5.0
| node                            |v18.12.1
| npm or yarn                | 8.19.2
| expo sdk                     | ~48.0.10

**Comment by biangwua** [comment]
> Hey @biangwua, unfortunately, the attached snack has a lot of issues with dependencies, please make it usable 🙌🏽

I have updated the snack (how to reproduce the bug: please enter the content in the input box, you will find that the close icon in the upper left corner will shake and rotate during the input process)

https://snack.expo.dev/@biang_wua/searchbar-and-icomoon-in-rnpaper-5-3-1

**Comment by biangwua** [comment]
> Hey @biangwua, unfortunately, the attached snack has a lot of issues with dependencies, please make it usable 🙌🏽

How to fix this bug?  Our software is about to be packaged and released, but because of this bug, it affects the user experience🤯🤯

**Comment by biangwua** [comment]
> Hey @biangwua, unfortunately, the attached snack has a lot of issues with dependencies, please make it usable 🙌🏽

so... how to solve this problem? It's been five days since this problem😫😫

**Comment by lukewalczak** [comment]
@biangwua I can suggest you lift up the icon component outside the login component, to avoid icon being directly defined as a function within the icon prop of the `Appbar.Action` component.

_based on the code from your snack, I've presented how to do it below:_

```
import React, { useState } from 'react';
import { View, StyleSheet, Dimensions } from 'react-native';

import { AntDesign } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { Appbar, TextInput } from 'react-native-paper';

const { width } = Dimensions.get('window');

const Icon = () => {
  const navigation = useNavigation();
  return (
    <AntDesign
      name="close"
      size={24}
      color="black"
      onPress={() => navigation.goBack()}
    />
  );
};

const Login = () => {
  const [Stu_id, InputStu_id] = useState(null);

  return (
    <View style={styles.container}>
      <Appbar.Action icon={Icon} />
      <View style={{ flex: 1, alignItems: 'center' }}>
        <View style={{ width: width - 60 }}>
          <TextInput
            mode="outlined"
            theme={{
              roundness: 25,
              colors: {
                primary: '#f0732c',
                background: 'white',
              },
            }}
            label="请输入普通登陆账号"
            value={Stu_id}
            onChangeText={(Stu_id) => InputStu_id(Stu_id)}
          />
        </View>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#ffffff',
    // alignItems: 'center'
  },
});

export default Login;

```

**Comment by biangwua** [comment]
> @biangwua I can suggest you lift up the icon component outside the login component, to avoid icon being directly defined as a function within the icon prop of the `Appbar.Action` component.
> 
> _based on the code from your snack, I've presented how to do it below:_
> 
> ```
> import React, { useState } from 'react';
> import { View, StyleSheet, Dimensions } from 'react-native';
> 
> import { AntDesign } from '@expo/vector-icons';
> import { useNavigation } from '@react-navigation/native';
> import { Appbar, TextInput } from 'react-native-paper';
> 
> const { width } = Dimensions.get('window');
> 
> const Icon = () => {
>   const navigation = useNavigation();
>   return (
>     <AntDesign
>       name="close"
>       size={24}
>       color="black"
>       onPress={() => navigation.goBack()}
>     />
>   );
> };
> 
> const Login = () => {
>   const [Stu_id, InputStu_id] = useState(null);
> 
>   return (
>     <View style={styles.container}>
>       <Appbar.Action icon={Icon} />
>       <View style={{ flex: 1, alignItems: 'center' }}>
>         <View style={{ width: width - 60 }}>
>           <TextInput
>             mode="outlined"
>             theme={{
>               roundness: 25,
>               colors: {
>                 primary: '#f0732c',
>                 background: 'white',
>               },
>             }}
>             label="请输入普通登陆账号"
>             value={Stu_id}
>             onChangeText={(Stu_id) => InputStu_id(Stu_id)}
>           />
>         </View>
>       </View>
>     </View>
>   );
> };
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     position: 'relative',
>     backgroundColor: '#ffffff',
>     // alignItems: 'center'
>   },
> });
> 
> export default Login;
> ```

Well, this does work, but I wonder what is causing this?  want to know the reason

**Comment by biangwua** [comment]
@lukewalczak I think you can also use useEffect Hook to initialize customIconRef when the component is mounted, and encapsulate the function of the custom icon in Ref.  Then pass customIconRef.current to the Appbar.Action component as the icon property.

`import { Appbar } from 'react-native-paper';
import { Image } from 'react-native';
import { useRef, useEffect } from 'react';

const MyComponent = () => {
  const customIconRef = useRef(null);

  useEffect(() => {
    customIconRef.current = () => (
      <Image source={require('./path/to/my/icon.png')} />
    );
  }, []);

  return (
    <Appbar>
      <Appbar.Action icon={customIconRef.current} onPress={() => {}} />
    </Appbar>
  );
};`

**Comment by biangwua** [comment]
@lukewalczak I think you can also use useEffect Hook to initialize customIconRef when the component is mounted, and encapsulate the function of the custom icon in Ref.  Then pass customIconRef.current to the Appbar.Action component as the icon property.But I think it may be better if you can fix this bug directly in the component library, because not everyone can find the cause of this bug

`import { Appbar } from 'react-native-paper';
import { Image } from 'react-native';
import { useRef, useEffect } from 'react';

const MyComponent = () => {
  const customIconRef = useRef(null);

  useEffect(() => {
    customIconRef.current = () => (
      <Image source={require('./path/to/my/icon.png')} />
    );
  }, []);

  return (
    <Appbar>
      <Appbar.Action icon={customIconRef.current} onPress={() => {}} />
    </Appbar>
  );
};`

**Comment by lukewalczak** [comment]
Passing a render function as the value of the `icon` prop can lead to an anti-pattern where a new component is generated on each re-render, potentially causing unnecessary rerenders of the `Appbar.Action` props, causing the icon shake issue :

<img width="958" alt="image" src="https://user-images.githubusercontent.com/22746080/232464078-77292bec-31f0-4b2b-adc0-feaf431e311d.png">

**Comment by julian-ev** [comment]
just wanted to share how I resolved the issue with the Appbar Action icon shaking and rotating in my case. I found that simply adding the animated prop with a value of false to the Appbar.Action component did the trick. Here's the updated code snippet that worked for me:

```javascript
<Appbar.Action
  icon={() => <Ionicons name="menu" size={24} color={theme.colors.white} />}
  color={theme.colors.white}
  onPress={openMenu}
  animated={false}
/>
```
