### ISSUE TITLE
Shouldn't TextInput's contentStyle prop use TextStyle?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [callstack/react-native-paper#3814]
### Ask your Question
Currently, TextInput's `contentStyle` prop is typed as `StyleProp<ViewStyle>`. However, as far as I can tell, this could use TextStyle instead of ViewStyle, which would allow styling the text in the TextInput, and this currently does work but throws a type error

**Comment by lukewalczak** [comment]
Hey @vpzomtrrfrt, I think you're right. The `contentStyle` is a property passed to the `styles` of the `TextInput` from `react-native` which means, the type should be the same – `StyleProp<TextStyle>`
