### ISSUE TITLE
Bottom Navigation default touch color

### ISSUE THREAD

**Issue by BlessingAdewale** [callstack/react-native-paper#3815]
Hi, I'm having a difficult time changing the default touch color of the tab bar item using react native paper. Please can you guide me on how to remove it or change it to another type of color apart from the default purple? I've tried many options or tabBarStyle, but there's no prop for that 

![image](https://user-images.githubusercontent.com/75122966/231742395-7d545896-3322-4730-8c46-91d90d4efe0d.png)

<img width="744" alt="case stuy" src="https://user-images.githubusercontent.com/75122966/231742126-1ece2aa4-4763-42bc-94cf-3184b6f7bb51.png">

#bottom navigation: default purple touch color.

**Comment by biangwua** [comment]
`<Provider theme={{ colors: { secondaryContainer: "#ffd8b3" } }}>
      <Tab.Navigator
        shifting={true}
        initialRouteName='Feed'
        activeColor='#ff7e00'
        inactiveColor="#596068"
        barStyle={{ backgroundColor: '#fff2e6' }}
        sceneAnimationEnabled={true}
        sceneAnimationType='shifting'
      >
        <Tab.Screen
          name="Home"
          component={MainPage}
          shifting={true}
          options={{
            tabBarLabel: 'Home',
            tabBarIcon: ({ color }) => (
              <MaterialCommunityIcons name="home-variant" size={26} color={color} />
            ),
            tabBarColor: '#ffd8b3'
          }}
        >
        </Tab.Screen>
        <Tab.Screen
          name='Service'
          component={ServicePage}
          options={{
            tabBarLabel: 'Service',
            tabBarIcon: ({ color }) => (
              <MaterialCommunityIcons name="account" color={color} size={26} />
            ),
            tabBarColor: '#ffd8b3'
          }}
        />
      </Tab.Navigator>
    </Provider>`

**Comment by BlessingAdewale** [comment]
It worked. Please can you explain why it does? Why do I need to wrap the tab.navigator inside a provider @biangwua

**Comment by lukewalczak** [comment]
The components are designed to match the theme, ensuring consistent colors and font styles. To modify specific colors, the theme prop can be used. The following code demonstrates how to apply the theme prop to a BottomNavigation.Navigator component:

```
      <Tab.Navigator
        screenOptions={{
          headerShown: false,
        }}
        tabBar={({ navigation, state, descriptors, insets }) => (
          <BottomNavigation.Bar
            navigationState={state}
            safeAreaInsets={insets}
            theme={{ colors: { secondaryContainer: 'pink' } }}
            / ... /
  ```
  
Usually, `Provider` is used to wrap the root component, providing the theme to all the components in the framework.

**Comment by BlessingAdewale** [comment]
Thanks so much @lukewalczak for the explanation. It was beyond helpful. Please, one more question, how can I know that the default color "pink" is regarded as a secondary container color and not something else? For instance, it could be the primary container, it could be the surface color, and it could be every other theme prop. Why "Secondary Container"? I want to know all the props and the color that corresponds to them.
