### ISSUE TITLE
Use a custom component inside TextInput

### ISSUE THREAD

**Issue by lucasharada** [callstack/react-native-paper#382]
Is there any way to use a custom component inside TextInput, in a way I have the UI of the TextInput with the behaviour of the custom component.

### What have you tried

I tried placing Autocomplete as a child component in TextInput, but it breaks the behaviour of the child component not showing anything. Also, it breaks the behaviour of TextInput, as I am always typing on the second character of the String.

### Your Environment

| software              | version
| --------------------- | -------
| ios         | iOS 11.2 Simulator
| react-native          | 0.55.2
| react-native-paper    | 1.8.0
| node                  | 8.11.2
| npm or yarn           | npm

**Comment by andreluizbellon** [comment]
is it related to #354?

**Comment by lucasharada** [comment]
@andreluizbellon Yes! I'll close it.
