### ISSUE TITLE
Textinput Outlined

### ISSUE THREAD

**Issue by Redoxahmii** [callstack/react-native-paper#3825]
i am using Poppins font for my project and as now that i have applied the fonts all the TextInputs using outlined variant are having text inside them being only show half as being cut off from the top.

The issue goes away if i change the font.

**Comment by seanblonien** [comment]
I am getting this issue as well. I am willing to reproduce, but my setup is on `expo@48.0.11` and `react-native-paper@5.7.0`, but Snack doesn't seem to support those versions. @lukewalczak any idea how i can repo using snack with those versions?

**Comment by seanblonien** [comment]
@lukewalczak I am saying when i try adding `react-native-web@0.19.4` in the package.json depdencies, Snack erases it when i reload and doesn't let me specify that version. the snack doesn't reproduce because it doesn't allow me to specify that version

**Comment by RichardLindhout** [comment]
Can confirm this happening with latest react-native-web

**Comment by seanblonien** [comment]
I would love to be able to create a Snack repro, but every time I specify `react-native-web` version it ignores the dependency and I can't reproduce it in snack

**Comment by Redoxahmii** [comment]
The issue still remains in the latest versions aswell causing label text to be overlapped using a different font then the standards.

**Comment by lukewalczak** [comment]
Could you please then create a basic github repo presenting the issue?

**Comment by seanblonien** [comment]
Repro was provided in the comment above

**Comment by seanblonien** [comment]
Repro was provided in the comment above
