### ISSUE TITLE
Buttons with Icons don't have visually even horizontal margin

### ISSUE THREAD

**Issue by jahirfiquitiva** [callstack/react-native-paper#3827]
### Current behaviour

The current Buttons with Icons have a bigger right margin than left margin, therefore the content does not look centered.

<img width="258" alt="Shot 2023-04-18 at 16 48 40@2x" src="https://user-images.githubusercontent.com/10360816/232913266-6b6b9c3b-b5f5-4b1c-aeb5-304cfa23a52e.png">

<img width="263" alt="Shot 2023-04-18 at 16 48 28@2x" src="https://user-images.githubusercontent.com/10360816/232913275-23e8c528-9923-4515-aae9-8de3dc6db7fe.png">

### Expected behaviour

The Button with Icon should have (at least visually) the same margin in both left and right sides.

Manually changed the Button text `margin-right` to `16px`, I think this should be the default value;

<img width="241" alt="Shot 2023-04-18 at 16 50 20@2x" src="https://user-images.githubusercontent.com/10360816/232913495-7b441b66-68da-40bb-80fa-29f755c92e4a.png">

### How to reproduce?

The project website demos include the issue.

**Comment by lukewalczak** [comment]
Hi @jahirfiquitiva, based on the MD [guidelines](https://m3.material.io/components/buttons/specs#0697c92a-54ba-4921-b28a-0f4abeea0a85), I believe the `Button` layout appears to be correct. The spacing on the side without the icon should be `24dp`, while the side with the icon should have a spacing of `16dp`. Attaching the screenshot from the documentation:

<img width="880" alt="image" src="https://user-images.githubusercontent.com/22746080/233486070-e166abda-70f7-4499-86aa-96ba14dae383.png">

**Comment by lukewalczak** [comment]
> is it possible to customize that margin? if so, how?

since button's label has set `marginHorizontal: 24` I would suggest to use `labelStyle` to override the margin: `labelStyle={{marginRight: 16}}`
