### ISSUE TITLE
FAB.Group Portal: impossible to interact with content exept Fab.Group.

### ISSUE THREAD

**Issue by Djibdjib** [callstack/react-native-paper#3830]
### Why Portal Fab.Group is always above of all my content ?

I have put Fab.Group on my page but now, impossible to interact with my content !

Any ideas ? Thx !!

**Comment by lukewalczak** [comment]
Please attach the code or create the expo [snack](https://snack.expo.dev/) illustrating your question / issue.

**Comment by lukewalczak** [comment]
Hey @Djibdjib, please check the following [snack](https://snack.expo.dev/@react-native-paper/fabgroup-in-scrollview), I hope it will be helpful.

**Comment by Djibdjib** [comment]
Woaw ! thx a lot ! it's working perfectly !

Best regards,
Djib
