### ISSUE TITLE
Card with an image background

### ISSUE THREAD

**Issue by Angelk90** [callstack/react-native-paper#3832]
### Ask your Question
Result I want to get:

[![enter image description here][1]][1]

Result I got:

[![enter image description here][2]][2]

I would like to get the example you see in the image above, with the image as the background of the card.
And the texts of the card as seen in the first image.

Can you give me a hand?

Link expo: [link][3]

Code:
```js
import { Text, View, StyleSheet } from 'react-native';
import { Card, Chip } from 'react-native-paper';

export default function App() {
  return (
    <View style={styles.container}>
      <Card style={{}}>
        <Card.Cover
          source={{
            uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png',
          }}
        />
        <Card.Title title={'React native'} />
        <Card.Content>
          <Text variant="bodyMedium">2 hours ago</Text>
          <Chip
            style={{
              backgroundColor: '#1faeb3',
            }}>
            Ep 4
          </Chip>
        </Card.Content>
      </Card>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: 30,
    backgroundColor: '#000',
    padding: 8,
  },
});
```

  [1]: https://i.stack.imgur.com/kqdCo.png
  [2]: https://i.stack.imgur.com/tgYbC.png
  [3]: https://snack.expo.dev/2TmI6_5Mz

**Comment by lukewalczak** [comment]
Hi @Angelk90 , unfortunately, using `Card.Cover` you won't achieve what you're looking for. Instead, you can try using `ImageBackground` from `react-native` which will act as the top layer for any children components passed within it. You can still maintain the shape of `Card` by wrapping everything inside it:

```
      <Card>
        <ImageBackground
          source={{
            uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png',
          }}>
          <Card.Title title={'React native'} />
          <Card.Content>
            <Text variant="bodyMedium">2 hours ago</Text>
            <Chip
              style={{
                backgroundColor: '#1faeb3',
              }}>
              Ep 4
            </Chip>
          </Card.Content>
        </ImageBackground>
      </Card>
```

**Comment by lukewalczak** [comment]
It seems that you have set the `height` for the entire `Card` along with the `paddingTop` for the `ImageBackground`. This approach could potentially may lead to a layout being misaligned, so the content doesn't fit available space and in the result goes out of the image. Without a design mock with precise dimensions to refer to, it may be challenging to provide accurate assistance. It is also worth noting that the problem you are facing may not be directly related to the library but rather to the styling adjustments you have made.
