### ISSUE TITLE
React native paper button click has shadow

### ISSUE THREAD

**Issue by tingan** [callstack/react-native-paper#3834]
**Is your feature request related to a problem? Please describe.**
the react native paper button has shadow when clicked, there is no way to remove them. 

**Describe the solution you'd like**
tried elevation: 0 , not work. should has some way like property or style to control it.

**Comment by lukewalczak** [comment]
Hey @tingan, could you please specify which mode is used in your `Button`?

**Comment by tingan** [comment]
hi, the mode is  mode="outlined", i want the outline border, but i want to hide the shadow when clicked as i added border color when clicked.

**Comment by lukewalczak** [comment]
@tingan `elevation` should be added only for the `Button` with the `mode="elevated"`. Could you please attach the expo snack presenting your issue?

**Comment by tingan** [comment]
https://snack.expo.dev/@tingan/button , i want the button has no shadow when clicked.

**Comment by lukewalczak** [comment]
Hey @tingan, I guess you meant the `rippleEffect`, however, there is no option to remove it or change it to `transparent`. We will work on supporting `rippleColor` property in pressable components in the near future.
