### ISSUE TITLE
Segmented, disabled buttons don't work

### ISSUE THREAD

**Issue by AlenMartinez** [callstack/react-native-paper#3835]
### Current behaviour
The problem that is currently occurring is that by setting the "disabled" property to "true" in the "SegmentedButtons" component, the segmented buttons are not properly disabled and are still selectable.

### Expected behaviour
The SegmentedButtons component can be disabled to prevent the user from interacting with it. For example, if you use SegmentedButtons in a form where the user chooses options, once the user completes the form and presses the "save" button, you could set the "disabled" property of the SegmentedButtons component to "true" to avoid allow the user to make more selections in the component after the form has been submitted."

### How to reproduce?
`
 <SegmentedButtons
                disabled={true}
                value={valueSegmented}
                onValueChange={(e) => handleValueChange(e)}
                buttons={buttonsValues}
            />
`

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | "0.71.1"
| react-native-paper    | "^5.1.4"
| node                            |18.13.0
| npm or yarn                | npm = 8.19.3, yarn =1.22.10
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hey @AlenMartinez, you have to pass the `disabled` property directly to the button which you want to disable, e.g:

```
      <SegmentedButtons
        value={value}
        onValueChange={setValue}
        buttons={[
          {
            value: 'walk',
            label: 'Walking',
			disabled: true
          },
          {
            value: 'train',
            label: 'Transit',
          },
          { value: 'drive', label: 'Driving' },
        ]}
      />
 ```
