### ISSUE TITLE
Missing Icon receipt-outline and receipt-text-outline

### ISSUE THREAD

**Issue by prime4567** [callstack/react-native-paper#3836]
### Current behaviour
When I use the Icon receipt-outline, or receipt-text-outline it says that Icon name is invalid
 WARN  "receipt-text-outline" is not a valid icon name for family "material-community"
 WARN  "receipt-outline" is not a valid icon name for family "material-community"

### Expected behaviour
Both icon should be valid and available

### How to reproduce?
```
import { IconButton } from 'react-native-paper';

<IconButton icon=receipt-outline />
```

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.71.6
| react-native-paper    | 5.6.0
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | 48.0.10

**Comment by lukewalczak** [comment]
Hey @prime4567, according to the MaterialCommunityIcons [list](https://oblador.github.io/react-native-vector-icons/) supported within `react-native-vector-icons`, unfortunately there is only available icon called `receipt`:

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/22746080/233927490-ee33c469-d7be-4fa9-9377-d33aa2e6687f.png">
