### ISSUE TITLE
Tooltip not showing

### ISSUE THREAD

**Issue by gedu** [callstack/react-native-paper#3843]
### Current behaviour
Wrapping a component with a Tooltip component isn't showing the View when long pressing or hover over it

### Expected behaviour
When long pressing or hover the Tooltip view should appear

### How to reproduce?

You can try on the demo app, isn't working.

### Preview

![Tooltip_not_working](https://user-images.githubusercontent.com/1676818/234233705-62bfae66-8993-4147-ab7a-247a0e72936c.jpeg)

### What have you tried so far?

If we change the wrapped component to a react-native one will work, seems that is a forward ref issue
### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Closing via: https://github.com/callstack/react-native-paper/pull/3844
