### ISSUE TITLE
Title text is cut off with an ellipsis

### ISSUE THREAD

**Issue by PeterFred** [callstack/react-native-paper#3848]
### Current behaviour
Currently, there is no way to display a long title on a small mobile screen in its entirety in a single line. The only option is to use an ellipsis. 
It is possible to increase the number of lines, but then on iOS, the text cannot be centered on the row (android can use textAlignVertical).
It would be ideal to be able to pass in the textProp "adjustsFontSizeToFit".

Single line row saying "This line is just too long to fit on a single row"
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/32250775/234708512-0749b0e5-6cfb-4d4b-9a8d-4d662f1609e5.png">

### Expected behaviour
Should be able to use "adjustsFontSizeToFit" for the Title text prop

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | 4.12.4
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hey @PeterFred, I think that `Title` component should support `adjustsFontSizeToFit` property, however I'm not sure, since we are not maintaining anymore version `4.x`.

**Comment by PeterFred** [comment]
Thanks @lukewalczak I'll upgrade the package, however the current repo does not support the "adjustsFontSizeToFit" param
https://github.com/callstack/react-native-paper/blob/main/src/components/List/ListItem.tsx

**Comment by lukewalczak** [comment]
> Thanks @lukewalczak I'll upgrade the package, however the current repo does not support the "adjustsFontSizeToFit" param
[main/src/components/List/ListItem.tsx](https://github.com/callstack/react-native-paper/blob/main/src/components/List/ListItem.tsx?rgh-link-date=2023-04-28T03%3A12%3A07Z)

Hey @PeterFred, you didn't mention previously anything about `List.Item` component, however you can try to pass custom text component into the `title` prop in `List.Item`, hopefully it will solve your issue:

```
const AdjustableTitle = () => (
  <Title adjustsFontSizeToFit>
    Change code in the editor and watch it change on your phone! Save to get a
    shareable url.
  </Title>
);

/.../

<List.Item title={AdjustableTitle} />
```

**Comment by PeterFred** [comment]
Thanks @lukewalczak , I can work with that.
