### ISSUE TITLE
TextInput outlined wraps text in two lines

### ISSUE THREAD

**Issue by ada-cienciala** [callstack/react-native-paper#3852]
### Current behaviour
I found an IOS specific bug. 

The **outlined** `TextInput` generates 2 lines of text when unfocused. Tested it on the Paper's example app - it happens only on IOS _(web and Android are fine)_ and only on outlined inputs _(dense or not, with the exception of large font)_. 

### Expected behaviour
The text is not wrapped in a second line. The exact behavior like in the normal `TextInput`

### How to reproduce?
1. Go to [example demo app](https://snack.expo.dev/@react-native-paper/react-native-paper-example_v5?platform=ios)
2. Choose iOS as the platform
3. Fill in the outlined inputs (outlined, dense outlined) with long text

### Preview
![image](https://user-images.githubusercontent.com/86961468/235132966-54727908-3287-4cda-9e18-84571a3b276a.png)

### What have you tried so far?
`<TextInput style={{textAlign: auto}} ... />` fixes the issue.

### Your Environment

The example snack's default stuff but here's my setup that also gives this problem:

| software                      | version
| --------------------- | -------
| ios                                | 16.2
| android                        | x
| react-native                | 0.71.6
| react-native-paper    | 5.4.1 (example app has 5.7.0)
| node                            | 18.11.0
| npm or yarn                | yarn 1.22.19
| expo sdk                     | x.x.x

**Comment by gedu** [comment]
I checked with the demo app, and this is what I got

![textInput_overflow_long_text_outline](https://user-images.githubusercontent.com/1676818/235136746-36c32b49-1a88-4476-adb5-fc35683b30d5.jpeg)
