### ISSUE TITLE
docs : Images are not being loaded on reloading the Showcase page (  bug )

### ISSUE THREAD

**Issue by Rehankhalil462** [callstack/react-native-paper#3853]
### Current behaviour
When we navigate to `Showcase` page , it shows and loads the images of the showcase applications correctly. When we refresh the page while being at the showcase page, it does not load the images. 

### Expected behaviour
Refreshing the showcase page giving this error for all the images . Following is one of them.  
`callstack.github.io/:12     GET https://callstack.github.io/react-native-paper/docs/showcase/weatherforecast.png 404`

### How to reproduce?
Navigate to SHOWCASE page  and refresh the page to see this error. 

### Preview
Image is attached for your reference. 

![Error Showcase Page Images](https://user-images.githubusercontent.com/76107872/235135557-3e046dba-e5f1-4e31-acd4-1cae758d527d.PNG)

**Comment by lukewalczak** [comment]
Fixed!
