### ISSUE TITLE
Typescript error for ThemeProvider in v4.12.4

### ISSUE THREAD

**Issue by aaronfg** [callstack/react-native-paper#3857]
### Current behaviour
Using v4.12.4, with RN 0.71.7, I am getting a typescript error for any use of **ThemeProvider** that it doesn't accept child nodes:

`Type '{ children: Element; theme: { colors: { primary: string; accent: string; switchColor: string; background: string; surface: string; placeholder: string; card: string; text: string; border: string; ... 4 more ...; backdrop: string; }; ... 4 more ...; animation: { ...; }; }; }' is not assignable to type 'IntrinsicAttributes & { theme?: Theme | undefined; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { theme?: Theme | undefined; }'.ts(2322)`

### Expected behaviour
Expect ThemeProvider to take children jsx components.

### How to reproduce?
Wrap any component in ThemeProvider. This can be something as simple as this:

```ts
import * as React from 'react';
import { View } from 'react-native';
import { ThemeProvider, useTheme } from 'react-native-paper';

const SomeComponent = () => {
  const currentTheme = useTheme();
  return (
    <ThemeProvider theme={currentTheme}>
      <View />
    </ThemeProvider>
  );
};
```

### What have you tried so far?
I had similar issues with prior versions of RN (.67) and fixed it with solutions in [this issue here](https://github.com/callstack/react-native-paper/issues/2965) but those no longer work having upgraded the app to RN.71.7.  

RN 0.71+ removes the "@types/react-native" dependency from the package.json which was the combo that worked before.

I tried adding the `resolutions` prop to the `package.json`-- which was a solution for other TS errors I found but that did not work.

`package.json` code:

```json
"resolutions": {
    "@types/react": "^18.2.0"
  },
```

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.71.7
| react-native-paper    | 4.12.4
| node                            | 18.6.0
| npm or yarn                | npm
| expo sdk                     | x

**Comment by lukewalczak** [comment]
Hey @aaronfg, I suggest you update the library to the latest version, since `v4` is no longer supported.

**Comment by aaronfg** [comment]
Just tested this one a new CLI created RN project using react-native-paper `"^5.8.0"`

Wrapping any functional component in ThemeProvider gives me the same error about the children prop.

**Comment by lukewalczak** [comment]
Hey @aaronfg, you can use instead `PaperProvider` or just `Provider`. In the meantime, I will investigate the issue with `ThemeProvider` type.
