### ISSUE TITLE
How to force default light theme independent of the device defaults?

### ISSUE THREAD

**Issue by bogdan-marian** [callstack/react-native-paper#3859]
I have an android S22 device that in settings is set to dark. 
How can I force the default device light theme independent of the device 
This is what I try to do but paper seams to do nothing even is I set dark==false

```javascript
import React from 'react';
import {Text, View} from 'react-native';
import {Provider as PaperProvider, DefaultTheme} from 'react-native-paper';

const App = () => {
  const lightTheme = {
    ...DefaultTheme,
    dark: false,
  };

  const theme = lightTheme;

  return (
    <PaperProvider theme={theme}>
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <Text style={{fontSize: 18, marginTop: 20}}>
          Hello there Is this light theme?
        </Text>
      </View>
    </PaperProvider>
  );
};

export default App;


```

I do not want to set any colour values. I just want to use the default sensitive bright and dark values in order to be able to very rapidly prototype but still check that switching theme works properly but I'm having trouble forcing the specific one.

**Comment by lukewalczak** [comment]
If you want to pass the specific theme, in terms of color mode, to the `Provider`, there is no need to modify any field. What you have to do is just pass the chosen theme exported from the library.

* Light theme

```
import {MD3LightTheme} from 'react-native-paper'

/ ... /
<Provider theme={MD3LightTheme} />
```

* Dark theme

```
import {MD3LightTheme} from 'react-native-paper'

/ ... /
<Provider theme={MD3LightTheme} />
```

In order to have the theme based on the device settings then you need to also use `Appearance` module from 'react-native` to determine the preferred colors scheme:

```
import { Appearance } from 'react-native';
const colorScheme = Appearance.getColorScheme();

/ ... /
<Provider theme={colorScheme === 'dark' ? MD3DarkTheme : MD3LightTheme} />
```
