### ISSUE TITLE
How to change TextInput outline label color

### ISSUE THREAD

**Issue by haithem-rihane** [callstack/react-native-paper#3860]
I'm using TextInput component, and I'm wondering how to change label color only without changing outline color.

![image](https://user-images.githubusercontent.com/2827416/235341518-24b7ee03-4677-4940-a6e0-9acef321b53e.png)

**Comment by lukewalczak** [comment]
Hey @haithem-rihane, as far as I remember there no such possibility, the color of the label is tied with outline color.
