### ISSUE TITLE
`surface` in `MD3Theme` doesn't change background colour of `Card` or `Surface` components

### ISSUE THREAD

**Issue by FudgeMunkey** [callstack/react-native-paper#3861]
### Current behaviour
When using an `MD3Theme` with the `Provider` setting the `surface` color doesn't change the background color of the `Card` or `Surface` components.

However, when using an `MD2Theme` instead, the backgrounds do change.

### Expected behaviour
When I change the `surface` setting in a `MD3Theme` I expect the background color of `Card` and `Surface` components to change.

### How to reproduce?
Change the `currentTheme` variable to use the `themeMD2` or `themeMD3`.
https://snack.expo.dev/h5wwp4JC4

### Preview
Using `themeMD2`
![image](https://user-images.githubusercontent.com/13531420/235345528-3fc46a74-fe90-4dec-9a68-4aed18f967e1.png)

Using `themeMD3`
![image](https://user-images.githubusercontent.com/13531420/235345547-6931259b-186b-478a-a91d-e485f154aefd.png)

### What have you tried so far?
I have tried upgrading to the most recent version of `react-native-paper` `5.7.0` and reproducing the issue on `expo`.

Looking at the `Surface` component, it looks like the `backgroundColor` is `colors.elevation.["level1"]` when not animated - I'm unfamiliar with the `.[` syntax. The [docs](https://callstack.github.io/react-native-paper/docs/guides/theming/#theme-properties) state that `elevation` is determined by the `primary` color, however changing the `primary` doesn't seem to work either.

### Your Environment
I have only tried this on web locally, but the issue is reproducible on IOS and Android via expo.

| software                      | version
| --------------------- | -------
| react-native                | 0.71.6
| react-native-paper    | 5.7.0
| node                            | 19.2.0
| npm or yarn                | 1.22.19
| expo                     | 48.0.11

### Misc

Sorry if I have misunderstood, thank you :pray:

**Comment by lukewalczak** [comment]
Hey @FudgeMunkey, in the MD3, to override the background colors using the theme within the `Card` you need to specify the following colors:

```
contained - theme.colors.surfaceVariant
outlined - theme.colors.surface
elevated - theme.colors.elevation.level1
```

In order to modify the `elevation.level1` color follow the code below:

```
<Card theme={{colors: { elevation: { level1: 'orange' }}} />
```

However, I've tried it and looks like it doesn't work as expected, so I will have to check the problem. In the meantime, you can basically pass your `backgroundColor` using `style` prop
