### ISSUE TITLE
Error after updating react-native-paper from 5.7.0 to 5.7.1

### ISSUE THREAD

**Issue by helenachallitanumu** [callstack/react-native-paper#3868]
### Current behaviour
Error: Unable to resolve module @react-navigation/native from /Users/Documents/react-native-mobile/node_modules/react-native-paper/src/react-navigation/navigators/createMaterialBottomTabNavigator.tsx: @react-navigation/native could not be found within the project or in these directories:
 node_modules
  10 |   TabRouterOptions,
  11 |   useNavigationBuilder,
> 12 | } from '@react-navigation/native';
     |         ^
  13 |
  14 | import type {
  15 |   MaterialBottomTabNavigationConfig,

### Environment

| software                      | version
| --------------------- | -------
| ios                                | 16.2
| react-native                | 0.68.5
| react-native-paper    | 5.7.1
| node                            | 20.0.0
| npm                             | 9.6.4

**Comment by lukewalczak** [comment]
Hey @helenachallitanumu could you please provide more details about the issue, how did you face it, which steps are required to observe it?

**Comment by helenachallitanumu** [comment]
Hello Luke,

The app was working fine before updating it;
After updating react-native-paper from v5.7.0 to 5.7.1, the error appeared
on app startup.

**Comment by lukewalczak** [comment]
@helenachallitanumu please install `react-native-paper@5.7.2`, it should work as expected 🙌🏽

**Comment by helenachallitanumu** [comment]
Yes working fine now 🎉 Thank you !
