### ISSUE TITLE
TouchableRipple underlayColor ignored

### ISSUE THREAD

**Issue by jahirfiquitiva** [callstack/react-native-paper#3871]
Hi

I have set a custom underlayColor for TouchableRipple on iOS, but it seems to not display anything at all.

I checked the source code and it looks like the color is ignored and not used?

https://github.com/callstack/react-native-paper/blob/896ab233398ace5d12f7892e31888d57ba298a0a/src/components/TouchableRipple/TouchableRipple.tsx#LL106C3-L106C16

What the correct way to set the underlayColor and have it show on iOS?

**Comment by lukewalczak** [comment]
Hey @jahirfiquitiva could you please present your issue on the snack? I was not able to observe the problem, please check the `TouchableRipple` [example](https://snack.expo.dev/@react-native-paper/underlaycolor-in-touchableripple) with set `underlayColor`.

> I checked the source code and it looks like the color is ignored and not used?
> [896ab23/src/components/TouchableRipple/TouchableRipple.tsx#LL106C3-L106C16](https://github.com/callstack/react-native-paper/blob/896ab233398ace5d12f7892e31888d57ba298a0a/src/components/TouchableRipple/TouchableRipple.tsx#LL106C3-L106C16)

The file is related to the `web` platform, for the mobile please check the file with `.native` extension.

**Comment by jahirfiquitiva** [comment]
@lukewalczak  I don't know how to do the snack thing, but here's what I've found:


```typescript
<TouchableRipple
  testID={`meetingList_${formattedDate}`}
  onPress={() => setExpanded(!expanded)}
  rippleColor={paperTheme.colors.accentRipple}
  underlayColor={paperTheme.colors.accentRipple}
>
  <View
    style={{
      ...styles.header,
      backgroundColor: paperTheme.colors.accentLight,
    }}
  >
	...
  </View>
</TouchableRipple>
```

This does **not** work. The ripple is **not** shown in android and the underlay is **not** shown in iOS. Here's a video:

https://user-images.githubusercontent.com/10360816/236030823-d695b4f3-a8ea-49d6-b91c-9cc69bad26c1.mp4

-----

```typescript
<TouchableRipple
  testID={`meetingList_${formattedDate}`}
  onPress={() => setExpanded(!expanded)}
  rippleColor={paperTheme.colors.accentRipple}
  underlayColor={paperTheme.colors.accentRipple}
  style={{
    backgroundColor: paperTheme.colors.accentLight,
  }}
>
  <View style={styles.header}>
	...
  </View>
</TouchableRipple>
```

This _almost_ works. The ripple is shown in android, but the underlay is **not** shown in iOS. Here's the video:

https://user-images.githubusercontent.com/10360816/236031232-14002679-db53-484b-aa5a-b52957c69739.mp4

----

```typescript
 <TouchableRipple
  testID={`meetingList_${formattedDate}`}
  onPress={() => setExpanded(!expanded)}
  rippleColor={paperTheme.colors.accentRipple}
  underlayColor={paperTheme.colors.accentRipple}
>
  <View
    style={styles.header}
  >
	...
  </View>
</TouchableRipple>
```

Removing the background provides the result I'm looking for, but I need the background. The ripple/underlay should appear on top of the background.

https://user-images.githubusercontent.com/10360816/236032083-a7213ca6-b989-4267-8405-21e3d4c1b6fb.mp4

**Comment by lukewalczak** [comment]
I see, so based on the provided details, the problem occurs when the `TouchableRipple` has specified `backgroundColor` – will check the issue

**Comment by jahirfiquitiva** [comment]
@lukewalczak yup, also, might be worth mentioning that one can't set a background on the child view, because the ripple wouldn't be visible
