### ISSUE TITLE
Modal backdrop stop working when upgrade 4.11.2 to 5.7.1

### ISSUE THREAD

**Issue by nabilAparicio** [callstack/react-native-paper#3872]
![image](https://user-images.githubusercontent.com/87939719/236048476-d9db82c8-fbb8-48ab-8f0c-0ab89410df52.png)

![image](https://user-images.githubusercontent.com/87939719/236048931-889b3efb-372a-4e68-97d2-f1dbc716bf77.png)

`import 'react-native-gesture-handler';
import React, { ReactNode, useEffect, useRef, useState } from 'react';
import { Dimensions, Pressable, TouchableOpacity, View, Animated } from 'react-native';
import { GestureEvent, PanGestureHandler } from 'react-native-gesture-handler';
import { Portal } from 'react-native-paper';
// import Animated from "react-native-reanimated";
import { Close } from '../../../Icons';
import styles from './BottomSheetStyle';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAnimatedKeyboard } from 'react-native-reanimated';
import { useAnimatedStyle } from 'react-native-reanimated';

type props = {
	show: boolean;
	onDismiss: () => void;
	enableBackdropDismiss: boolean;
	children?: ReactNode;
	HeaderComponent?: ReactNode;
	size?: 'S' | 'M' | 'L' | 'FULL';
};

const BottomSheetSimple = ({
	show,
	onDismiss,
	enableBackdropDismiss,
	children,
	HeaderComponent,
	size
}: props) => {
	const paddingSaved = useRef(0);
	const heightSaved = useRef(0);
	const SizeBS = {
		S: 1,
		M: 1.5,
		L: 1.9,
		FULL: 2.8
	};

	const bottomSheetHeight = Dimensions.get('window').height * SizeBS[size];

	if (bottomSheetHeight != heightSaved.current) {
		heightSaved.current = bottomSheetHeight;
	}
	if (paddingSaved.current != bottomSheetHeight * 0.05) {
		paddingSaved.current = bottomSheetHeight * 0.05;
	}
	const insets = useSafeAreaInsets();
	const [open, setOpen] = useState(show);
	const bottom = useRef(new Animated.Value(-bottomSheetHeight)).current;
	const opacityBackdrop = useRef(new Animated.Value(0)).current;

	// const keyboard = useAnimatedKeyboard();
	// const translateStyle = useAnimatedStyle(() => {
	// 	return {
	// 		transform: [{ translateY: -keyboard.height.value }]
	// 	};
	// });

	const relDiff = (translationY: number | any, height: number) => {
		return 10 + ((height - translationY) / height) * 90;
	};

	const changeOpacity = (translationY: number | unknown) => {
		const opacity = (relDiff(translationY, bottomSheetHeight) / 2) * 0.01;
		if (opacity) {
			Animated.timing(opacityBackdrop, {
				toValue: opacity,
				duration: 0,
				useNativeDriver: false
			}).start();
		}
	};

	const onGesture = (event: GestureEvent<any>) => {
		const { translationY } = event.nativeEvent;
		if (translationY > 0) {
			bottom.setValue(-translationY);
			changeOpacity(translationY);
		}
	};

	const onGestureEnd = (event: GestureEvent<any>) => {
		const limitToDismiss = bottomSheetHeight / 3;
		if (event.nativeEvent.translationY > limitToDismiss) {
			onDismiss();
		} else {
			Animated.timing(bottom, {
				toValue: 0,
				duration: 500,
				useNativeDriver: false
			}).start();
		}
	};

	// useEffect(() => {
	// 	console.log(keyboard);
	// 	if (keyboard.state.value === 1) {
	// 		Animated.timing(bottom, {
	// 			toValue: keyboard.height.value - 2,
	// 			duration: 250,
	// 			useNativeDriver: false
	// 		}).start();
	// 	}
	// 	if (keyboard.state.value === 0) {
	// 		Animated.timing(bottom, {
	// 			toValue: 0,
	// 			duration: 250,
	// 			useNativeDriver: false
	// 		}).start();
	// 	}
	// }, [keyboard]);

	useEffect(() => {
		if (show) {
			setOpen(show);
			Animated.timing(bottom, {
				toValue: 0,
				duration: 500,
				useNativeDriver: false
			}).start();
			Animated.timing(opacityBackdrop, {
				toValue: 0.5,
				duration: 500,
				useNativeDriver: false
			}).start();
		} else {
			Animated.timing(opacityBackdrop, {
				toValue: 0,
				duration: 500,
				useNativeDriver: false
			}).start();
			Animated.timing(bottom, {
				toValue: -bottomSheetHeight,
				duration: 500,
				useNativeDriver: false
			}).start(() => {
				setOpen(false);
			});
		}
	}, [show]);

	if (!open) {
		return null;
	}

	return (
		<Portal>
			<Pressable onPress={enableBackdropDismiss ? onDismiss : null}>
				<Animated.View style={[styles.backDrop, { opacity: opacityBackdrop }]}></Animated.View>
			</Pressable>
			<Animated.View
				style={[
					// translateStyle,
					styles.root,
					{
						// minHeight: bottomSheetHeight * 0.98,
						maxHeight: bottomSheetHeight,
						//paddingBottom: bottomSheetHeight * 0.05,
						bottom: bottom
						//	backgroundColor: "gray"
					},
					styles.common
				]}
			>
				<PanGestureHandler onGestureEvent={onGesture} onEnded={onGestureEnd}>
					<View
						style={[
							styles.header,
							//styles.common,
							styles.headerSpacing
						]}
					>
						{HeaderComponent}
						<TouchableOpacity style={{ marginLeft: 'auto', padding: 8, flex: 1 }} onPress={onDismiss}>
							<Close style={styles.closeIcon} />
						</TouchableOpacity>
					</View>
				</PanGestureHandler>
				<View
					style={{
						paddingHorizontal: 24,
						height: bottomSheetHeight * 0.3,
						paddingBottom: insets.bottom
					}}
				>
					{children}
				</View>
			</Animated.View>
		</Portal>
	);
};

export default BottomSheetSimple;
`

I implement this BS like this 

`<Provider>
			<BottomSheetSimple
				size="L"
				show={active_modal ? active_modal === 'SUCURSAL_FAB' : false}
				onDismiss={() => dispatch(set_active_modal(null))}
				enableBackdropDismiss={true}
				HeaderComponent={<Text style={styles.header}>Seleccione Sucursal</Text>}
			>
				<SucursalesBsContent />
			</BottomSheetSimple>
		</Provider>`

help me please

**Comment by lukewalczak** [comment]
Hey @nabilAparicio please format your code and ideally it would be if you create a expo snack. Please also elaborate more on what do you mean by "Modal backdrop stop working" 🙌🏽

**Comment by lukewalczak** [comment]
Closing the issue due to inactivity and lack of communication.
