### ISSUE TITLE
Adding other icons to paper provider

### ISSUE THREAD

**Issue by BlessingAdewale** [callstack/react-native-paper#3877]
import AwesomeIcon from 'react-native-vector-icons/FontAwesome';
// ...

      <PaperProvider
        settings={{
          icon: props => <AwesomeIcon {...props} />,  //Here is what I'm talking about.
        }}
        theme={this.state.theme}
      >
        // ...
      </PaperProvider>

I want to add other icons but the icon prop can only take one Javascript fragment at a time.

**Comment by lukewalczak** [comment]
Hey @BlessingAdewale, if I understood your question/concern correctly you would like to specify more than one icon set within the Paper's `Provider`.  
It's not possible and within the `Provider` you can specify only one icon set, which is going to be the default icon source for all components.
You can always pass the required icon pack through the `icon` prop in the component which supports icon, e.g. `Button`:

```
<Button icon={() => <AwesomeIcon name="camera" />} mode="contained" onPress={() => console.log('Pressed')}>
  Press me
</Button>
```

**Comment by BlessingAdewale** [comment]
I have one more question to ask though but not particular to this.

**Comment by BlessingAdewale** [comment]
<img width="1280" alt="Screen Shot 2023-05-09 at 15 20 39" src="https://github.com/callstack/react-native-paper/assets/75122966/170106e0-c894-4d00-bb1e-3633dc2649b4">

Please how can I put an X button like the one in the picture in react native paper text input. Moreover, when I click on it, I will like to clear all that I've written in the text input.

**Comment by lukewalczak** [comment]
You can either use prop `clearButtonMode` on `TextInput` (however it's working only with ios as far as I remember) or use prop `right` to render a React element to display on the right side, e.g. you can render the icon with the `onPress` functionality which is going to clear the input state.
