### ISSUE TITLE
Unable to center a FAB.Group horizontally

### ISSUE THREAD

**Issue by ldorigo** [callstack/react-native-paper#3885]
### Current behaviour

With a single FAB, I can center it  by setting the containing view to a flex container. However since FAB.Group requires <Portal> in order to be rendered on top of other elements, I can't use the outer element to center it. I have tried a similar solution to https://github.com/callstack/react-native-paper/issues/3682 but it does not work . The only way is to use absolute positioning with some awkward calculations based on screen width and the FAB's width.

### Expected behaviour
There should be a way to center 

### How to reproduce?

1. Make a FAB.Group
2. Attempt to center horizontally :-) 

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | 10.x
| react-native                | 18.2
| react-native-paper    | 5.7.2
| node                            | x
| npm or yarn                | x
| expo sdk                     | 48.0.0

**Comment by ldorigo** [comment]
It seems that the solution in https://github.com/callstack/react-native-paper/issues/3682 actually kind of works if you use the `fabStyle` prop rather than the `style` prop, but not entirely - the icon gets centered, but the action icons are no longer aligned with it.

**Comment by lukewalczak** [comment]
Actually, the `FAB.Group` component was crafted in a way to be placed on the right side of the screen _(when LTR)_, so I guess that all paddings and margins are adjusted to that assumption. I would consider it rather as a component limitation than a bug.
