### ISSUE TITLE
Cannot remove default padding in button

### ISSUE THREAD

**Issue by kashyaprajan11** [callstack/react-native-paper#3892]
### Ask your Question

Cannot reduce the default padding of Button even after using style props.
<Button mode="outlined" style={{ padding: 0, margin:0 }}>
        Follow Back
 </Button>

<img width="206" alt="Screenshot 2023-05-16 at 8 33 17 AM" src="https://github.com/callstack/react-native-paper/assets/80104242/1fd03d78-0b34-4fbb-ada0-60fd4f2c5333">

**Comment by DimitarNestorov** [comment]
Try setting the `margin` of `labelStyle` to `0`:
```
<Button
  mode="outlined"
  labelStyle={{margin: 0}}
>
  Follow Back
</Button>
```

**Comment by lukewalczak** [comment]
```
        <Button mode="outlined" labelStyle={{ marginHorizontal: 0 }}>
          Follow Back
        </Button>
```

**Comment by salesp07** [comment]
If anyone out there is trying to remove button padding try what @lukewalczak mentioned. Changing `marginVertical` and `marginHorizontal`of labelStyle did it for me!
