### ISSUE TITLE
TypeScript error with custom color in theme

### ISSUE THREAD

**Issue by c-goettert** [callstack/react-native-paper#3897]
I am happily using react-native-paper v5.7.2 together with typescript and react-native v0.71.7. I try to add custom colors to my theme and my code looks basically exactly like the [example from the docs](https://callstack.github.io/react-native-paper/4.0/theming.html#typescript):

```
import { DefaultTheme } from 'react-native-paper';

declare global {
  namespace ReactNativePaper {
    interface ThemeColors {
      myOwnColor: string;
    }

    interface Theme {
      myOwnProperty: boolean;
    }
  }
}

//Your main theme
const theme = {
  ...DefaultTheme,
  // Specify custom property
  myOwnProperty: true,
  // Specify custom property in nested object
  colors: {
    myOwnColor: '#BADA55',
  },
};

//Export it
export default theme;
```

However, when I use that custom color, I still get a linter error, telling me that this color doesn't exist:
<img width="895" alt="Bildschirmfoto 2023-05-19 um 14 57 44" src="https://github.com/callstack/react-native-paper/assets/7591624/9f5e4106-d036-4e01-b5df-7c5697f6f444">

Am I missing something? Should I just ignore this? (I am new to typescript..)

**Comment by DimitarNestorov** [comment]
Your link is to React Native Paper 4.0 docs. It's different in 5.0: https://callstack.github.io/react-native-paper/docs/guides/theming#advanced-theme-overrides

**Comment by c-goettert** [comment]
Oh, well - thanks for pointing that out. Using the correct docs for my version solved the issue :)
