### ISSUE TITLE
Edit this page link on TextInputIcon doc is broken/not found.

### ISSUE THREAD

**Issue by cjmling** [callstack/react-native-paper#3900]
### Current behaviour

On bottom of this page https://callstack.github.io/react-native-paper/docs/components/TextInput/TextInputIcon there is link for "edit this page" , when I click on that it says file not found

### Expected behaviour

I should see the file in github repo so I can help edit and send PR

### How to reproduce?

1. Open https://callstack.github.io/react-native-paper/docs/components/TextInput/TextInputIcon
2. Click "edit this page" which at present links to [Edit this page](https://github.com/callstack/react-native-paper/tree/main/src/components/TextInput/TextInputIcon.tsx)

### Preview

![image](https://github.com/callstack/react-native-paper/assets/1612187/0f7a42ae-a506-48c1-b3e9-d910263ed075)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Fixed via: https://github.com/callstack/react-native-paper/commit/9c3ea3f950f10e76f4ebccd75709312ac8fc1430

**Comment by cjmling** [comment]
@lukewalczak now this link to the actual component, but doesn't it suppose to link to docs of that component??
