### ISSUE TITLE
color prop in TextInput.Icon does not work

### ISSUE THREAD

**Issue by cjmling** [callstack/react-native-paper#3901]
### Current behaviour

The `color` prop in `TextInput.Icon` https://callstack.github.io/react-native-paper/docs/components/TextInput/TextInputIcon suppose to change icon color but at present it doesn't work.  But undocumented `iconColor` does work and change the icon color

### Expected behaviour

It should change the icon color

### How to reproduce?

Navigate to TextInput example. I have update the code. Check the top 2 example.

https://snack.expo.dev/@cjmling/react-native-paper-example_v5

```
     <TextInput
            style={styles.inputContainerStyle}
            label="color prop does not work"
            placeholder="Type something"
            value={text}
            onChangeText={(text) => inputActionHandler('text', text)}
            left={
              <TextInput.Icon
                icon="magnify"
                color={'#22C55E'}
                onPress={() => {
                  changeIconColor('flatLeftIcon');
                }}
              />
            }
            right={<TextInput.Affix text="/100" />}
          />
          <TextInput
            style={styles.inputContainerStyle}
            label="iconColor work"
            placeholder="Type something"
            value={text}
            onChangeText={(text) => inputActionHandler('text', text)}
            left={
              <TextInput.Icon
                icon="magnify"
                iconColor="#22C55E"
                onPress={() => {
                  changeIconColor('flatLeftIcon');
                }}
              />
            }
            right={<TextInput.Affix text="/100" />}
          />
```

### Preview

![image](https://github.com/callstack/react-native-paper/assets/1612187/25ac48f2-6517-4bc8-9054-5ca8c4bce1af)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | 5.7.0
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by Nensi9** [comment]
The `color` prop in `TextInput.Icon` it's not working
