### ISSUE TITLE
Dot display in TextInput with secureTextEntry prop at iOS is weird!

### ISSUE THREAD

**Issue by devmyung** [callstack/react-native-paper#3903]
If I set secureTextEntry prop to true 
when using TextInput(react-native-paper) to receive a password, 
it appears strangely as follow images.
================================
However, the Native Text Input below handles it normally.
(It's only weird on iOS. It works fine in aOS.)

Is it because I didn't apply it correctly?
Or is there an error in the component?

![RNPaper_TextInput_1](https://raw.githubusercontent.com/devmyung/dev-playground/main/images/RNPaper_TextInput_01.jpeg)
![RNPaper_TextInput_2](https://raw.githubusercontent.com/devmyung/dev-playground/main/images/RNPaper_TextInput_02.jpeg)
![RNPaper_TextInput_3](https://raw.githubusercontent.com/devmyung/dev-playground/main/images/RNPaper_TextInput_03.jpeg)

**Comment by raajnadar** [comment]
On iOS I think the dot is shown from the font applied

**Comment by devmyung** [comment]
This issue was solved! 

There was a problem with the font(.ttf) I used in the project, 
and I was able to solve the problem because I changed it to a normal font.
