### ISSUE TITLE
Why version 5.8.0 change props of @react-navigation/bottom-tabs

### ISSUE THREAD

**Issue by faisalamin9696** [callstack/react-native-paper#3906]
I was using version 5.3.1 at that time BottomTabBar working fine, But updating to version 5.8.0 is resulted in some design changes that are not fixable natively. Is there something I missing?

![image](https://github.com/callstack/react-native-paper/assets/53206866/2ac81110-acf3-43e9-b872-1f1c6d025f79)

using version 5.8.0
with 
@react-navigation/bottom-tabs

It should not affect the bottom-tabs

**Comment by lukewalczak** [comment]
Hey @faisalamin9696, could you please describe more about what has been changed? Could you please prepare the expo snack?

**Comment by faisalamin9696** [comment]
> Hey @faisalamin9696, could you please describe more about what has been changed? Could you please prepare the expo snack?

I am not using the expo, using cli.

Here the bottom-tab with version 5.3.1

![Screenshot_20230529_123442_SteemPro](https://github.com/callstack/react-native-paper/assets/53206866/a7bcdcc1-0041-4586-a662-d81b3a427baf)

One more thing with version 5.8.0 clicking on bottom-tab is also not work sometime. Longpress work but press not work for the first time.

**Comment by lukewalczak** [comment]
Are you able to reproduce your issue using the [expo snack ](https://snack.expo.dev/)?

**Comment by faisalamin9696** [comment]
This expo using the old version,

Update it to 5.8.0

here I set the bottom-tab as mine

https://snack.expo.dev/CCXPzyh7y7

**Comment by faisalamin9696** [comment]
Now I am using paper bottom nav looking working fine with latest dependencies.
