### ISSUE TITLE
Android - Radio Button looks pixelated

### ISSUE THREAD

**Issue by baochungit** [callstack/react-native-paper#391]
### Current behaviour
I'm not sure if it looks fine on other android devices but on my s7 edge, the radio button looks quite pixelated.

### What have you tried
React Native Paper Example on Expo

### Your Environment
Android 7 on S7 Edge

**Comment by ferrannp** [comment]
@baochungit can you attach an screenshot on how it looks?

**Comment by baochungit** [comment]
Yes. Here it is:
https://ibb.co/dmRe0o
My phone's screen resolution is HD. I see that if I set it to higher resolution (FHD, WQHD) it looks smoother.

**Comment by satya164** [comment]
Seems it's fixed in https://github.com/facebook/react-native/commit/c5ca26a0e5c0660196300ee34d6007c63879611f

Can it be cherry-picked @grabbou ?

**Comment by yaronlevi** [comment]
+1 For solving this in Paper.

**Comment by satya164** [comment]
We can't solve it in Paper since its a bug in React Native.
