### ISSUE TITLE
Invariant Violation: "cursor" is not a valid style property

### ISSUE THREAD

**Issue by YajanaRao** [callstack/react-native-paper#3917]
### Current behaviour

Running application on IOS will give following error on IOS.
![react-native-error](https://github.com/callstack/react-native-paper/assets/38914337/6694c28d-a0ff-4b6a-980f-443f61b4f258)

From here: https://github.com/callstack/react-native-paper/blob/1ce31113cd67e7aa450c72d6f86cd4a20c8157a1/src/components/Tooltip/Tooltip.tsx#L231

### How to reproduce?

By using following react native and react native paper version I get this error on multiple mac systems

### What have you tried so far?

Commenting following line helps: https://github.com/callstack/react-native-paper/blob/1ce31113cd67e7aa450c72d6f86cd4a20c8157a1/src/components/Tooltip/Tooltip.tsx#L231

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.65.3
| react-native-paper    | 5.8.0
| node                            | 16.20.0
| npm or yarn                | 8.19.4
| expo sdk                     | x.x.x

**Comment by dkang23** [comment]
+1

**Comment by bigboss97lnt** [comment]
+1
