### ISSUE TITLE
I want to add right component as icon in textinput but it can't be visible 

### ISSUE THREAD

**Issue by jigarsolanki0212** [callstack/react-native-paper#3919]
#I want to add an icon at the right side of the text input.
<TextInput
                    right={
                        <TextInput.Icon
                            onPress={onpress}
                            name="info"
                            color="red"
                            iconColor="black"
                            background="red"
                            rippleColor="red"
                            containerColor="red"
                        />

**Comment by raajnadar** [comment]
name must be icon props in TextInput.Icon

**Comment by lukewalczak** [comment]
Hey @jigarsolanki0212, as @raajnadar mentioned, the `TextInput.Icon` supports `icon` (not `name`) prop, for the icon to be shown.

**Comment by jigarsolanki0212** [comment]
As you said I have added an icon prop in my code but still icon is now visible.

right={<TextInput.Icon onPress={togglePasswordVisibility} icon="eye" color={colors.black} />}


![image](https://github.com/callstack/react-native-paper/assets/79460184/f6869d7d-cc44-4c39-8760-9cac044a5671)

**Comment by raajnadar** [comment]
In this case you icon package is not setup correctly

Possible reason, please do check on stackoverflow, I once gave a solution to one of the issue in that repo I am not getting the link now

https://github.com/oblador/react-native-vector-icons#the-icons-show-up-as-a-crossed-out-box-on-android

**Comment by jigarsolanki0212** [comment]
@lukewalczak I have tried that also but still icon is not visible.

![image](https://github.com/callstack/react-native-paper/assets/79460184/c3b96f9b-a1c0-4da8-a09c-57451c2bfbab)

**Comment by Enkumicahel** [comment]
@jigarsolanki0212 have you found a solution for this?

**Comment by yasinguness** [comment]
> @lukewalczak I have tried that also but still icon is not visible.
> 
> ![image](https://private-user-images.githubusercontent.com/79460184/245358220-c3b96f9b-a1c0-4da8-a09c-57451c2bfbab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTk0NzEsIm5iZiI6MTcyNTk1OTE3MSwicGF0aCI6Ii83OTQ2MDE4NC8yNDUzNTgyMjAtYzNiOTZmOWItYTFjMC00ZGE4LWEwOWMtNTc0NTFjMmJmYmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA5MDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMmVjNjcwZDllNDk2YjE3MjdjMjVkMGU0NTRjYjNhNGIzMjc4OWNlOTA5Y2EzMGIxMzU2Yjk1ZGE2NGZjZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MDA_oYy_rwc11efgb_IX9yzHHHZRp-DG8SZTzxynD-Y)

Did you solved ?

**Comment by raajnadar** [comment]
Read this answer - https://stackoverflow.com/a/68419318/5519872
