### ISSUE TITLE
Using "react-native-paper/babel" will make Jest not being able to mock Paper

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#392]
### Current behaviour

If we use in `.babelrc`:

```
"plugins": [
  "react-native-paper/babel"
]
```

Then, `jest.mock('react-native-paper')` will not work.

### Workaround

Use `env` in `.babelrc`. However, I think we need to document this somehow. cc @thymikee

**Comment by thymikee** [comment]
You're messing with changing imports, that's definitely something worth documenting.
