### ISSUE TITLE
Card/View onPress not work if tooltip its children

### ISSUE THREAD

**Issue by faisalamin9696** [callstack/react-native-paper#3928]
onPress does not work if we put <Tooltip inside a view for which we setting onPress.

For Example

```
<TouchableOpacity onPress={()=>alert('Hi')} >
    <Tooltip title="Hi">
        <Text>HI</Text>
    </Tooltip>
</TouchableOpacity>
```

**Comment by faisalamin9696** [comment]
Hi @lukewalczak 

https://snack.expo.dev/@faisalamin9696/react-natove-paper-tooltip

**Comment by faisalamin9696** [comment]
Hi @lukewalczak can you check what the issue here?

**Comment by lukewalczak** [comment]
Hey @faisalamin9696, on your example the `Tooltip` should be rendered above the `TouchableOpacity`:

```
        <Tooltip title="Hi">
          <TouchableOpacity onPress={() => alert('Hi')}>
            <Text>Hi Click Me</Text>
          </TouchableOpacity>
        </Tooltip>
```

Could you please present the issue with `Card`?

**Comment by faisalamin9696** [comment]
Hi @lukewalczak 

Using Card inside <Tooltip> in Android results in tooltip text not getting hidden after the long press on Card. 

https://snack.expo.dev/@faisalamin9696/react-natove-paper-tooltip
