### ISSUE TITLE
Disabled IconButton/Input Start or End Adornment Icon Color

### ISSUE THREAD

**Issue by Rehankhalil462** [callstack/react-native-paper#3931]
`react-native-paper: 5.8.0`

How can we change the disabled Icon color ?

Here you can see, Text Input is disabled and also Start Text Input Icon is disabled. But when it is disabled, I can't even see those icons. How can I change the disabled Icons color ??

![TextInput Right Icon](https://github.com/callstack/react-native-paper/assets/76107872/8e28f66c-b979-46ad-a44d-f785b8bafe69)

@lukewalczak

**Comment by lukewalczak** [comment]
Hey @Rehankhalil462, most likely you have to override the `theme.colors.onSurfaceDisabled` in `TextInput.Icon` or `TextInput.Affix`

**Comment by Rehankhalil462** [comment]
Hi @lukewalczak 

Thanks for your quick reply. 
Yes . It is working as it is expected. 🥇
