### ISSUE TITLE
Component example images in latest version of docs are very hard to see - would love better images. 

### ISSUE THREAD

**Issue by meatnordrink** [callstack/react-native-paper#3933]
**Is your feature request related to a problem? Please describe.**
Our team frequently has to go back to previous versions of the docs just to see what a component looks like, as the examples on the screen are often too small to see details clearly.

**Describe the solution you'd like**
Larger, high-resolution images of the components, as found in typical component system's documentation.

**Describe alternatives you've considered**
Looking at earlier versions of the docs. 

**Additional context**
If you have an open-source repo I could build with demos of all the components and then take screenshots of, or a public Storybook instance, I'd be happy to help with this.

**Comment by lukewalczak** [comment]
It's on my list - I will correct those screenshots :)
