### ISSUE TITLE
Nested (Sub) Menu Not Rendering Menu Items

### ISSUE THREAD

**Issue by jfries289** [callstack/react-native-paper#3940]
### Current behaviour
When nesting a `Menu` as a sub-menu element within another `Menu`, the sub-menu never renders. If you put a border on the sub-menu, that is visible and shows the appropriate size, but the menu items do not show.

### Expected behaviour
A `Menu` anchored as an item within another `Menu` should show the menu popup when clicked

### How to reproduce?
Dumbed down snack: https://snack.expo.dev/@jfriesenhahn/rnp-submenu-issue
Click on the `Menu` button, then on `Sub Menu Option`. Instead of the sub menu options, it just shows the border.

### Preview
<img width="293" alt="image" src="https://github.com/callstack/react-native-paper/assets/7132218/a9bd4b47-146c-41b2-a9fe-7d108836e032">

### What have you tried so far?
Tried manipulating zIndex and Provider

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.68.1
| react-native-paper    | 4.12.1
| node                            | x.x.x
| npm or yarn                | yarn
| expo sdk                     | 44.0.6

**Comment by lukewalczak** [comment]
Hey @jfries289, I guess there is a need to render two `Menu` next to each other, without submenu being nested. Another factor is passing the coordinates to the `Submenu`'s anchor, to display it properly. I played with you snack a bit and do some adjustments, please take a look on it: https://snack.expo.dev/@react-native-paper/rnp-submenu.

I hope it will help you!

**Comment by jfries289** [comment]
@lukewalczak Thanks for the help 👍 . Our menu content is dynamic, so a static position wouldn't work, but I was able to use `.measure` in the `onPress` event to get something working. However, it looks like we may have to rework that once we upgrade to RN 0.71+ (https://github.com/facebook/react-native/issues/37551). 

This work around should be fine for us, but it definitely is a work around. Nesting menus would be a nice feature.

**Comment by lukewalczak** [comment]
> This work around should be fine for us, but it definitely is a work around. Nesting menus would be a nice feature.

The `Menu` component, which we have in the current form wasn't crafted to support submenus. I guess it's not so popular approach on the mobile.

> Nesting menus would be a nice feature.

We are open for contributions, so feel free to open a PR with the feature :v:

Currently, closing the issue, however if you would like to work on it, please open the feature request.
