### ISSUE TITLE
react-native-paper/react-navigation module - missing type declarations

### ISSUE THREAD

**Issue by Gruak** [callstack/react-native-paper#3959]
### Current behaviour
When I try to import anything from react-native-paper/react-navigation, typescript complains about missing declaration files

> Could not find a declaration file for module 'react-native-paper/react-navigation'. '(project_root)/node_modules/react-native-paper/lib/commonjs/react-navigation/index.js' implicitly has an 'any' type. [7016]

### Expected behaviour
Typescript doesn't complain about missing declarations

### How to reproduce?
Import anything from react-native-paper/react-navigation when using typescript LSP or run tsc afterwards.

### Preview
![image](https://github.com/callstack/react-native-paper/assets/43846312/3cf44a64-03e7-4c1d-8a23-2eed705195ea)

### What have you tried so far?
There's not much I can do without modifying the library code

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | 12
| react-native                | 0.71.8
| react-native-paper    | 5.9.0
| node                            | 18.16.1
| pnpm                          | 8.6.5
| expo sdk                     | 48.0.19

**Comment by soroush-b** [comment]
created this pull request which solved the problem for me https://github.com/callstack/react-native-paper/pull/3961
