### ISSUE TITLE
Checkbox checkmark displaying as a question mark

### ISSUE THREAD

**Issue by jacquesdev** [callstack/react-native-paper#3966]
### Current behaviour
Using the checkbox component. It doesn't display an icon when unchecked (totally blank, no border), and if is checked, it shows a box with a question mark inside

### Expected behaviour
I expect it to look like the example here https://callstack.github.io/react-native-paper/docs/components/Checkbox/

### How to reproduce?
```
import { Checkbox } from 'react-native-paper'
<Checkbox
        status={checked ? 'checked' : 'unchecked'}
        onPress={onPress}
        color='green'
      />
```

### Preview
<img width="48" alt="Screenshot 2023-07-08 at 14 57 15" src="https://github.com/callstack/react-native-paper/assets/7842197/d06470ee-2dd0-4cba-9b8e-31a9bb712a2d">

### What have you tried so far?
Since it's the most basic setup, not sure what else to try. I did try and install  "react-native-vector-icons": "9.2.0" to see if it would make a difference, but it doesn't.

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.72.0
| react-native-paper    | 5.9.1
| node                            | 18.16.0
| npm or yarn                | 9.6.7

**Comment by lukewalczak** [comment]
Hey @jacquesdev, please make sure that you properly installed the `react-native-vector-icons` library and you covered required steps per platform, under the installation section in the [docs](https://github.com/oblador/react-native-vector-icons#installation). Additionally, you can create a sample github repo with bug repro, so we can take a look on that.

**Comment by jacquesdev** [comment]
Thanks @lukewalczak 

I initially installed react native paper with expo, and then removed expo so didn't realise it was a requirement for a vanilla react-native project.

I'm sure it will work, so will close this now!

Dziękuję!!!
