### ISSUE TITLE
Make `TextInput.Affix` pressable

### ISSUE THREAD

**Issue by fabriziocucci** [callstack/react-native-paper#3968]
**Is your feature request related to a problem? Please describe.**
There are at least two use case we would benefit from having a pressable `TextInput.Affix`:
* create a text input where the `TextInput.Affix` on the left represent the country code of a phone number (e.g. +39) which, on press, allows the user to select the country code from a list (e.g. by opening a dialog)
* create a text input where the `TextInput.Affix` on the left (or right) represent the currency of an expense (e.g. EUR) which, on press, allows the user to select the currency from a list (e.g. by opening a dialog)

**Describe the solution you'd like**
It would be amazing if `TextInput.Affix` would support an `onPress` prop like:
```
<TextInput
    ...
    left={<TextInput.Affix text={currency} onPress={openCurrenciesDialog} />}
/>
```

**Describe alternatives you've considered**
1. We tried to wrap the `TextInput.Affix` in a `Pressable` but, looking at the source, this seems to be explicitly prohibited
2. We have currently settled for two separate text inputs but the final result is not exactly what we would like to have

**Additional context**
N/A

**Comment by smokiebacon** [comment]
Need this as well. Also need boolean on this prop, In my example, I'm trying to show right (or left) if I press a button,

**Comment by shubhadeep29** [comment]
```
         <TextInput
            placeholder="Add new tag"
            value={text}
            onChangeText={text => setText(text)}
            style={{backgroundColor: colors.white}}
            contentStyle={{}}
            right={
              <TextInput.Affix
                text="Add"
                onPress={() => addTag(text)}
              />
            }
          />
```
<img width="307" alt="Screenshot 2024-04-10 at 9 52 51 AM" src="https://github.com/callstack/react-native-paper/assets/24447618/dc9f1f77-8f85-4e0a-b806-9b883998e74e">

```
         <TextInput
            placeholder="Add new tag"
            value={text}
            onChangeText={text => setText(text)}
            style={{backgroundColor: colors.white}}
            contentStyle={{}}
            right={
              <TextInput.Affix
                text="Add"
                // onPress={() => addTag(text)}
              />
            }
          />
```
<img width="312" alt="Screenshot 2024-04-10 at 9 55 08 AM" src="https://github.com/callstack/react-native-paper/assets/24447618/72cc91fb-3a9e-43f3-bb02-1fa8c09e6424">



If I pass the onPress function the "Add" text is not showing, If I didn't pass it then the text is showing. Please let me know if I am doing anything wrong.
