### ISSUE TITLE
Actually compile the library before publishing

### ISSUE THREAD

**Issue by micimize** [callstack/react-native-paper#397]
### Current behaviour
Build systems that don't have flow (e.g. typescript) can't consume this module

### Expected behaviour
module should be consumable as vanilla js, and perhaps have [additional shadow .js.flow files](https://github.com/facebook/flow/issues/1996) alongside the distribution

**Comment by micimize** [comment]
Just to clarify, I don't think this is urgent or blocking. Anyone using webpack can add this to their rules:
```javascript
  {
      test: /\.js$/,
      enforce: "pre",
      use: [ "remove-flow-types-loader" ],
      include: nodeModule('react-native-paper')
  }
```

**Comment by rosswaycaster** [comment]
I am trying to use this with React Native Web and it keeps failing with `You may need an appropriate loader to handle this file type.`

I can't figure out how to make it work.

**Comment by micimize** [comment]
@rosswaycaster you're using the `remove-flow-types-loader` config above before your other webpack rules? `nodeModule` above looks like
```javascript
const path = require('path')
const fs = require('fs')
const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = relativePath => path.resolve(appDirectory, relativePath)
const nodeModule = mod => resolveApp(`node_modules/${mod}`)
```

**Comment by louiechristie** [comment]
https://github.com/callstack/react-native-paper/issues/799#issuecomment-566555156
