### ISSUE TITLE
Have react native expo project and want to use react native paper with web

### ISSUE THREAD

**Issue by joshua-revolutions** [callstack/react-native-paper#3978]
I have react native expo project (bare workflow) and want to use react native paper with web. Am I supposed to do all the steps here:
https://callstack.github.io/react-native-paper/docs/guides/react-native-web/

It mentions (CRA) which I'm not using so wasn't sure.

**Comment by lukewalczak** [comment]
Hey @joshua-revolutions, if you have a project configured based on the expo, there is no need to follow those steps.
