### ISSUE TITLE
Style and theme prop for List.AccordionGroup(Can't change background color of List.AccordionGroup)

### ISSUE THREAD

**Issue by programadoracoriano** [callstack/react-native-paper#3981]
**Is your feature request related to a problem? Please describe.**
List Accordion Group doesn't have a option to change background Color

**Describe the solution you'd like**
Just add a style prop to List.AccordionGroup

**Describe alternatives you've considered**
Wrapping in a view, inside and outside List.AccordionGroup, didn't work, the component don't have any theme or style prop.

**Additional context**

**Comment by lukewalczak** [comment]
Hey @programadoracoriano, `List.AccordionGroup` is just a wrapper which allows controlling a group of `List.Accordion`s and I think there is no need to pass there style or theme prop. You can always wrap your accordions into `List.Section` and change the background color of it.

**Comment by MatkoMilic** [comment]
This is actually needed, @lukewalczak the thing is if u put borderRadius: 8 for example, on the <List.Accordion, then you see a bit of edge being the main theme color, and i dont know how to prevent it.It seems that <List.AccordionGroup> has a background color of theme primary.
