### ISSUE TITLE
Cursor color is ignored

### ISSUE THREAD

**Issue by jahirfiquitiva** [callstack/react-native-paper#3982]
### Current behaviour

TextInput cursor is only visible while active/focused. But `cursorColor` is ignored, and `activeOutlineColor` is the one used for the cursor instead.

### Expected behaviour

`cursorColor` should be used always, whether active or focused, or not.

### How to reproduce?

https://snack.expo.dev/@jahirfiquitiva/rnp-textfield-cursor

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | 5.9.1
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | 47.0.0

**Comment by sangameshsomawar** [comment]
@jahirfiquitiva 

`selectionColor` will set the selection color and cursor color in ios whereas it will only set the selection color in Android. 
`cursorColor` will set only cursorColor in Android and will have no change in iOS.

If you want the same behavior in Android and ios, try setting both with the same colors.

```
selectionColor={'#0ff'}
cursorColor={'#0ff'}
```

Let me know if this fixes the issues.

**Comment by jahirfiquitiva** [comment]
@sangameshsomawar oh no, that is so confusing. would it be possible to at least update the docs with that explicit information? mentioning what works for iOS and what does for Android?

**Comment by sangameshsomawar** [comment]
@jahirfiquitiva Actually this confusion is with the react native itself. 

https://reactnative.dev/docs/textinput#selectioncolor
https://reactnative.dev/docs/textinput#cursorcolor-android

**Comment by jahirfiquitiva** [comment]
@sangameshsomawar 😱 that's even worse ... I wonder if the RNP code or docs could still be modified/updated to make it more developer friendly or intuitive 🤔 

thanks for the advice though

**Comment by sangameshsomawar** [comment]
@jahirfiquitiva  I have raised PR, Please do check if any details are missing now.

**Comment by jahirfiquitiva** [comment]
@sangameshsomawar lgtm, thank you
