### ISSUE TITLE
Icon background colour in iOs inside Searchbar

### ISSUE THREAD

**Issue by psk-dreampay** [callstack/react-native-paper#3986]
While trying to use Searchbar I am getting a background colour for both search and clear icon. The RN paper version is `5.9.1`. However the same scenario is working fine in android. Also when I try to provide a height to Seachbar, the text is getting aligned to the bottom and this happening in both iOs and android. 

This is for android.
<img width="440" alt="Screenshot 2023-07-20 at 2 10 23 PM" src="https://github.com/callstack/react-native-paper/assets/80046816/08bc0caf-8c62-4a6c-a669-9bd7ce4be40f">

This is for iOs.

<img width="341" alt="Screenshot 2023-07-20 at 2 10 04 PM" src="https://github.com/callstack/react-native-paper/assets/80046816/3b0731df-22bd-40db-9cb1-373f6a57ba65">

Can anyone suggest how to remove this background colour?

**Comment by lukewalczak** [comment]
Hey @psk-dreampay, what is the height you passed into the `Searchbar`?

**Comment by lukewalczak** [comment]
Hey @psk-dreampay, to correctly set the Seearchbar height, there is a need to also pass the same value (48 in your case) as a `minHeight` using `inputStyle`:

```
            <Searchbar
              placeholder="Search"
              style={{ height: 48 }}
              inputStyle={{ minHeight: 48 }}
              mode="bar"
            />
```
