### ISSUE TITLE
Icon background colour inside Searchbar

### ISSUE THREAD

**Issue by psk-dreampay** [callstack/react-native-paper#3987]
### Current behaviour
Getting a background colour for icon inside Searchbar in iOs. Also if height is provided to the Searchbar then the content and placeholder is getting aligned to the bottom (this is happening in both android and iOs).

### Expected behaviour
The icon background should be transparent which was previously available in version 5.1.3

### How to reproduce?
Simply render the react native paper Searchbar with custom right icon.
`<Searchbar
      style={styles.container}
      placeholder="Search"
      onChangeText={onChangeText}
      value={searchQuery}
      clearIcon='close'
      autoFocus
    />`

`const styles = export default StyleSheet.create({
    container: {
      borderWidth: 2,
      backgroundColor: '#25303c',
      borderColor: '#ffffff',
      height: 48,
      borderRadius: 8,
  },
});`
### Preview
This is for iOs:

<img width="341" alt="Screenshot 2023-07-20 at 2 10 04 PM" src="https://github.com/callstack/react-native-paper/assets/80046816/bb314287-fc8e-4f24-8301-05aa01d8601e">

This is for android:

<img width="440" alt="Screenshot 2023-07-20 at 2 10 23 PM" src="https://github.com/callstack/react-native-paper/assets/80046816/11d419b1-716d-43df-ad4c-f896fa87f17c">

### What have you tried so far?
Tried adding flex direction row and align items center to align the content / placeholder in the middle but no luck. Was not sure how to change background colour of icon as the default search icon is also getting a background colour.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 15.2
| android                        | 13
| react-native                | 0.71.12
| react-native-paper    | 5.9.1
| node                            | 16.14.0
| npm or yarn                | yarn
| expo sdk                     | bare RN app

**Comment by lukewalczak** [comment]
The thing you called `backgroundColor` is actually the "ripple effect" which appears when icons/buttons are pressed. By default it should always be visible, however, there should be a way to make it transparent, when the user wants it – currently, that possibility is missing, but I will add it.

What you can do atm to get rid of the ripple effect is disabling it totally in the whole app, following the doc: https://callstack.github.io/react-native-paper/docs/guides/ripple-effect#disable-ripple-effect-in-all-components
