### ISSUE TITLE
TextInput documentation error (incorrect type stated for onChangeText parameter)

### ISSUE THREAD

**Issue by bockoblur** [callstack/react-native-paper#3989]
### Current behaviour
[TextInput documentation](https://callstack.github.io/react-native-paper/docs/components/TextInput/) incorrectly states that 
 _**Changed text is passed as an argument**_ to the `onChangeText `handler

Parameter type is, In fact, `NativeSyntheticEvent<TextInputChangeEventData>`

So, to access the text, one should use (for example)

```
const handleTextChange = (ev: NativeSyntheticEvent<TextInputChangeEventData>) => {
    const text = ev.nativeEvent.text;
    // ... deal with text entered in TextInput
  };
```

### Environment

| software                      | version
| --------------------- | -------
| react-native-paper    | 5.9.1

**Comment by sangameshsomawar** [comment]
@bockoblur I think you are gettting confused between 

onChangeText gives you just the string as the argument for the callback.

onChange gives you the synthetic event as the argument.

**Comment by bockoblur** [comment]
Sorry, my bad. 
Maybe if `onChange` prop was mentioned on doc page it would be more clear?
(Not looking for excuse, though. 😉 )

**Comment by lukewalczak** [comment]
> Maybe if onChange prop was mentioned on doc page it would be more clear?

Paper's documentation describes `onChangeText` in the same way how it's done on the RN documentation:

react-native | react-native-paper
--- | ---
<img width="715" alt="image" src="https://github.com/callstack/react-native-paper/assets/22746080/d65e0459-6919-4ddc-9389-bb01b3725abc"> | <img width="691" alt="image" src="https://github.com/callstack/react-native-paper/assets/22746080/30596e70-c687-41f2-b379-602207db81ba">

I think that everything is correct in terms of prop description.
