### ISSUE TITLE
Bottom bar icon loading while app booting 

### ISSUE THREAD

**Issue by FouadMagdy01** [callstack/react-native-paper#3990]
### Current behaviour

the bottom bar icon is blank when app boot and take about 1s to load and appear

### Expected behaviour

icons should appear instantly when app boot, at least provide some boolean value to indicates that icons were loaded successfully so that we don't hide the splash screen untill it loads-

### How to reproduce?

 open the example app and then navigate to the bottom navigation bar example, close the app and re open it and notice how icons are appearing and you will notice some delay in it

### Preview

https://github.com/callstack/react-native-paper/assets/88867595/2d63d4c3-44e8-417c-9509-cb6e7da430f8

### Your Environment

| software                      | version
| --------------------- | -------
|
| android                        | 13
| react-native                | latest
| react-native-paper    | latest
| node                            | latest 
| npm or yarn                | latest
| expo sdk                     | N/A

**Comment by mkhoussid** [comment]
I'm using Expo, and I had an issue with the fonts not loading on time either.

Here's my solution. I'm using `react-native-paper` in my project.

```
import * as React from 'react';
import { Icon, IconButton, PaperProvider } from 'react-native-paper';
import Entry from './Entry';
import * as SplashScreen from 'expo-splash-screen';
import { useFonts } from 'expo-font';
SplashScreen.preventAutoHideAsync(); // After my backend `init` request succeeds, I manually hide the Splash screen

const icons = ['heart', 'mail', 'circle'];
const App = React.memo(() => {
	const [fontsLoaded] = useFonts({
		'Noto-Regular': require('./assets/fonts/NotoSans-Regular.ttf'),
	});

	if (!fontsLoaded) {
		return null;
	}

	return (
		<PaperProvider>
			<Entry />
			{icons.map((icon) => (
				<IconButton
					key={`icon-${icon}`}
					icon={icon}
					size={0}
					style={{ display: 'none' }} // in case `size={0}` doesn't work
				/>
			))}
		</PaperProvider>
	);
});

export default App;
```
If `style={{ display: 'none' }}` doesn't work for you, try `style={{ width: 0, height: 0 }}`
