### ISSUE TITLE
Allow sorting and filtering in DataGrid

### ISSUE THREAD

**Issue by jairaja** [callstack/react-native-paper#3991]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Users should be able to filter (with an option of some predefined quick filters) and sort the grid's data.

**Describe alternatives you've considered**
I am using List instead of Datagrid for filtering and sorting of data in mandate in my current requirement.

**Additional context**

**Comment by lukewalczak** [comment]
Hey @jairaja, could you please present visually what would you like to achieve?

**Comment by jairaja** [comment]
Sorting example - https://www.ag-grid.com/examples/row-sorting/custom-sorting/packages/vanilla/index.html
![sortingExample](https://github.com/callstack/react-native-paper/assets/10957486/49ebe407-2799-4cc5-ab5f-c41b89f6676e)

Filtering example - https://www.ag-grid.com/javascript-data-grid/filtering-overview/

**Comment by lukewalczak** [comment]
> Sorting example - [ag-grid.com/examples/row-sorting/custom-sorting/packages/vanilla/index.html](https://www.ag-grid.com/examples/row-sorting/custom-sorting/packages/vanilla/index.html)

For the sorting example, there is a dedicated prop called `sortDirection` in `DataTable.Title` [component](https://callstack.github.io/react-native-paper/docs/components/DataTable/DataTableTitle). 

> Filtering example - [ag-grid.com/javascript-data-grid/filtering-overview](https://www.ag-grid.com/javascript-data-grid/filtering-overview/)

Filtering functionality you can achieve with already implemented components such as `RadioButton`, `TextInput` or `Menu`, so there is no need to add custom solutions – the library is providing blocks, which you can compose to build required filters.

**Comment by lukewalczak** [comment]
Basically, you have to introduce `useState` state variable for `sortDirection` in order to control it's value and change it by pressing the header. Take a look at the following snack and try it by pressing `Dessert` header title:
 https://snack.expo.dev/@react-native-paper/datatable---sorting

**Comment by pgpankajgoyal** [comment]
Any update on this for sorting and filter ?
