### ISSUE TITLE
Full-screen Searchbar View

### ISSUE THREAD

**Issue by MatteoBuffo** [callstack/react-native-paper#4017]
Hello. I would like to achieve the Searchbar shown in the video below:

[Original video source](https://github.com/callstack/react-native-paper/assets/56068232/cc6ce197-f99e-4601-894c-a96d7dae3c72)

From [Material Design Search guidelines](https://m3.material.io/components/search/guidelines#0487ee07-65c2-4010-9815-24c1abeb057e):
_On focus, the search bar expands into a search view, which can display historical search suggestions. Tap the back icon to release focus from the search box and dismiss search suggestions._

I read [in the docs](https://callstack.github.io/react-native-paper/docs/components/Searchbar) that the Searchbar mode can be either `bar` or `view`, but in the latter I don't know how to make it "full-screen" and put other elements in it (like history entries and/or tips). Is this something that has already been made available in RNP or will it be in future?

The [Snack from RNP website](https://snack.expo.dev/@react-native-paper/react-native-paper-example_v5) should be a good reference.

**Comment by lukewalczak** [comment]
> I read [in the docs](https://callstack.github.io/react-native-paper/docs/components/Searchbar) that the Searchbar mode can be either bar or view, but in the latter I don't know how to make it "full-screen" and put other elements in it (like history entries and/or tips). Is this something that has already been made available in RNP or will it be in future?

The transition from bar to the view you need to handle by yourself. We are not providing ready solution it and currently, there are no plans for supporting it.
