### ISSUE TITLE
Getting error when attempting to update theme on 5.9.1

### ISSUE THREAD

**Issue by impactcolor** [callstack/react-native-paper#4019]
### Ask your Question

According to the documentation and this [post by the team on Medium](https://medium.com/@sisongqolosi/custom-theme-and-colours-in-react-native-paper-bc3388008adf):
One should be able to easily update the theme...

`import {
  MD3LightTheme as DefaultTheme,
  PaperProvider,
} from 'react-native-paper';
import App from './src/App';

const theme = {
  ...DefaultTheme,
  // Specify custom property
  myOwnProperty: true,
  // Specify custom property in nested object
  colors: {
    myOwnColor: '#BADA55',
  },
};`

This causes the error Cannot read property 'level2' of undefined.  Any idea why?
The documentation doesn't suggest any other things to be provided.

**Comment by lukewalczak** [comment]
I think there is a bug in the documentation regarding adding custom colors, there is missing `...DefaultTheme.colors` and it should look like this:

```
  const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    myOwnColor: '#BADA55',
  },
};
```

Please let me know if that solves the problem
