### ISSUE TITLE
fill ListAccordion by data provided from API

### ISSUE THREAD

**Issue by mmor93** [callstack/react-native-paper#402]
### Current behaviour

i can not set data dynamically to ListAccordion.

### Expected behaviour

does the ListAccordion component have a prop like 'data'?

**Comment by gawrysiak** [comment]
There's no data prop, but you should be able to use children instead. For example:

```
<ListAccordion title="Accordion" icon="folder">
  {data.map(row => <ListItem title={data.name} />)}
</ListAccordion>
```
