### ISSUE TITLE
Custom position of close button 

### ISSUE THREAD

**Issue by AngelDev0329** [callstack/react-native-paper#4024]
### Ask your Question

I am going to make close button at top right side on dialog.
How can I do for this?

![Screen Shot 2023-08-11 at 11 52 05 AM](https://github.com/callstack/react-native-paper/assets/54489723/c728429b-4d8f-4d6c-9fc3-56f1ba71ebeb)

**Comment by lukewalczak** [comment]
Hey @AngelDev0329, you can wrap the `Dialog.Title` along with `IconButton` (or your custom icon button) within the `View` with row direction, to achieve the result as below:

<img width="319" alt="image" src="https://github.com/callstack/react-native-paper/assets/22746080/827bd3ba-22d3-43a7-9815-08f3b85fc3fc">

Here you can check the [snack](https://snack.expo.dev/@react-native-paper/dialog-custom-header)

You can also just wrap the icon button inside the `Dialog` and give it an absolute position.

**Comment by AngelDev0329** [comment]
Thank you.
