### ISSUE TITLE
Material bottom tabs change picker colour

### ISSUE THREAD

**Issue by Wari-Dudafa** [callstack/react-native-paper#4025]
There seems to be no way to change to change the colour of the picker indicator when a screen in selected in the bottom tab navigator or how do I turn it off?

**Comment by Wari-Dudafa** [comment]
<img width="111" alt="Screenshot 2023-08-11 at 1 57 59 pm" src="https://github.com/callstack/react-native-paper/assets/60980271/3bd7871a-a96b-455c-912c-7fc184f259a4">

**Comment by Wari-Dudafa** [comment]
<img width="368" alt="Screenshot 2023-08-11 at 1 58 42 pm" src="https://github.com/callstack/react-native-paper/assets/60980271/b59f099f-d7d7-4625-a415-df6faec33c82">

**Comment by omaranwaar** [comment]
I am facing the same issue!!!!

**Comment by lukewalczak** [comment]
It depends which component you are currently using for the bottom navigation.

* For the `BottomNavigation`:

I would suggest checking which theme color is used for a specific element, in your case outline pill. Its background color is `theme.colors.secondaryContainer` which you should be able to easily override using the theme prop in a component:

```
    <BottomNavigation
      ...
      theme={{colors: {secondaryContainer: 'transparent'}}}
    />
```    

* For `BottomNavigation.Bar`:

To modify the pill color also the theme prop can be used. The following code demonstrates how to apply the theme prop to a `BottomNavigation.Navigator` component:

```
      <Tab.Navigator
        screenOptions={{
          headerShown: false,
        }}
        tabBar={({ navigation, state, descriptors, insets }) => (
          <BottomNavigation.Bar
            navigationState={state}
            safeAreaInsets={insets}
            theme={{ colors: { secondaryContainer: 'transparent' } }}
            / ... /
```

**Comment by Wari-Dudafa** [comment]
I don't have a BottomNavigation.Bar, this is how my navigation is setup, how would I implement a different coloured pill with this setup?


```js

import { createMaterialBottomTabNavigator } from "@react-navigation/material-bottom-tabs";
import { useTheme } from "react-native-paper";

import FoodPage from "FoodPage";
import DaysPage from "DaysPage";
import ScalePage from "ScalePage";

function TabBarStack() {
  const theme = useTheme();
  const Tab = createMaterialBottomTabNavigator();

  return (
    <>
      <Tab.Navigator
        labeled={false}
        activeColor={theme.colors.primary}
        inactiveColor={theme.colors.outline}
        barStyle={{
          backgroundColor: theme.colors.elevation.level3,
        }}
       />

        <Tab.Screen
          name="DaysPage"
          component={DaysPage}
        />
        <Tab.Screen
          name="FoodPage"
          component={FoodPage}
        />
        <Tab.Screen
          name="ScalePage"
          component={ScalePage}
        />
      </Tab.Navigator>
    </>
  );
}

export default TabBarStack;


```

**Comment by lukewalczak** [comment]
Ok, then you should use the `createMaterialBottomTabNavigator` from `react-native-paper/react-navigation` and pass the `theme` property to the `Tab.Navigator` where you can overwrite the `secondaryColor`, please check the following [snack](https://snack.expo.dev/@react-native-paper/creatematerialbottomtabnavigator---rnp). I hope it will help you!

**Comment by Wari-Dudafa** [comment]
This is my exact code but I still the pill was not red, it in fact did not change

```js
import { createMaterialBottomTabNavigator } from "@react-navigation/material-bottom-tabs";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { Text, View } from "react-native";

function TabBarStack() {
  const Tab = createMaterialBottomTabNavigator();

  function HomeScreen() {
    return (
      <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <Text>Home!</Text>
      </View>
    );
  }

  function SettingsScreen() {
    return (
      <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <Text>Settings!</Text>
      </View>
    );
  }

  return (
    <>
      <Tab.Navigator theme={{ colors: { secondaryContainer: "red" } }}>
        <Tab.Screen
          name="Home"
          component={HomeScreen}
          options={{
            tabBarIcon: ({ color }) => (
              <MaterialCommunityIcons name="home" color={color} size={26} />
            ),
          }}
        />
        <Tab.Screen
          name="Settings"
          component={SettingsScreen}
          options={{
            tabBarIcon: ({ color }) => (
              <MaterialCommunityIcons name="cog" color={color} size={26} />
            ),
          }}
        />
      </Tab.Navigator>
    </>
  );
}

export default TabBarStack;

```

**Comment by lukewalczak** [comment]
As I mentioned in my previous comment, you need to import the `createMaterialBottomTabNavigator` from `"react-native-paper/react-navigation"` instead of `"@react-navigation/material-bottom-tabs"`.

Read more [there](https://callstack.github.io/react-native-paper/docs/guides/bottom-navigation)

**Comment by Wari-Dudafa** [comment]
This worked perfectly, thank you very much and sorry for the confusion!
