### ISSUE TITLE
App name missing spaces in IOS

### ISSUE THREAD

**Issue by hichemfantar** [callstack/react-native-paper#4027]
### Current behaviour
App name appears as ReactNativePaperExample

### Expected behaviour
It should be React Native Paper Example

### How to reproduce?
Download the IOS app

### Preview
![image](https://github.com/callstack/react-native-paper/assets/34947993/6b218bd0-74ef-41af-a433-1c1794b07946)

**Comment by lukewalczak** [comment]
Hey @hichemfantar, on iOS spaces are removed automatically if the app name is too long. The only way to handle it is to replace spaces in favour of unicode characters in `Info.plist`, however, we don't have iOS native files in the example directory.
Currently, I find no issues with it and I don't feel that it necessarily needs to be changed.

**Comment by hichemfantar** [comment]
@lukewalczak Thanks for the explanation, I didn't know IOS did it that with long names. I'll close this for now.
