### ISSUE TITLE
Card.Title is there a way to add a background image?

### ISSUE THREAD

**Issue by hgjura** [callstack/react-native-paper#4029]
I would like to customize a bit the title section of the Card. Namely I would like to add the Title with an image in the background. And apply an opacity to the image. 

Is this possible? Can you provide an example?

Thanks

**Comment by tjaniczek** [comment]
Hi @hgjura you could try making Card without default Title and then create a custom component that would display your title according to your needs: https://callstack.github.io/react-native-paper/docs/components/Card/CardContent

**Comment by lukewalczak** [comment]
@hgjura you can also just use the wrap the `ImageBackground` from `react-native` with the `Card.Title` inside the `Card` component:

```
      <Card>
        <ImageBackground
          source={{
            uri: 'https://images.unsplash.com/photo-1691962898718-4dfecbf3c0f2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          }}
          resizeMode="cover"
          style={{
            height: 300,
            width: '100%',
            overflow: 'hidden',
            borderRadius: 12,
          }}>
          <Card.Title title="Title" titleVariant="headlineLarge" />
        </ImageBackground>
      </Card>
 ```
