### ISSUE TITLE
Demo Seems To Be Too Old?

### ISSUE THREAD

**Issue by turtlegood** [callstack/react-native-paper#403]
### Current behaviour

It seems that this project is wonderful! However, the demo on expo (at here https://callstack.github.io/react-native-paper/ ) seems to be so old that it merely contains several fundamental components and does not contain things like drawer, textinput and other things? Therefore, I think there could be a newer demo, so people can try it out on a real phone without writing all the code by themselves. If so, this project may be more attractive because they can directly try all the features instead of merely looking at the screenshots.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | N/A
| react-native          |N/A
| react-native-paper    |N/A
| node                  |N/A
| npm or yarn           |N/A

**Comment by satya164** [comment]
The demo is pretty recent. This is how it looks:

![image](https://user-images.githubusercontent.com/1174278/40724241-e4884278-6420-11e8-9a1d-3eb5fe137dee.png)

It has all of the things like drawer and text input.

You can also try to clone the repo and run the `example` app with Expo.

**Comment by turtlegood** [comment]
![screenshot_20180531-073901](https://user-images.githubusercontent.com/5236035/40753553-4cfe93b2-64a7-11e8-9ca3-576ed369d1b8.png)
However, that is why I see when I scan the QR code... Do I do anything wrong when it comes to opening the qr code via the expo app?

**Comment by satya164** [comment]
> Do I do anything wrong when it comes to opening the qr code via the expo app?

Not sure. Maybe some kind of cache?

cc @brentvatne

**Comment by turtlegood** [comment]
@satya164 @brentvatne 
More information: newly installed expo app. directly scan the qr code (yesterday). then see the screenshot.
Therefore, I think there may be a problem with expo code uploading?
Thank you!

**Comment by satya164** [comment]
@turtlegood just to be sure, you installed the expo app from google play store, right? maybe the app has an older sdk version and hence loads an older version of the example.

**Comment by brentvatne** [comment]
you can check the version by going to the "projects" tab and looking at the "Client version" - it should be 2.5.0 as of today

**Comment by turtlegood** [comment]
@brentvatne WOW you are so great!!! I found that my apk version is very old because I use the https://apps.evozi.com/apk-downloader/ to download the apk before. After installing the latest it works well!
