### ISSUE TITLE
rippleColor in List.Accordion works but why it on foreground? how to make it on background?

### ISSUE THREAD

**Issue by hotaryuzaki** [callstack/react-native-paper#4035]
### Ask your Question

i know rippleColor List.Accordion is works (version 5.10.1), but why does the ripple effect on foreground?
by default, if we are not set the rippleColor the ripple effect on background
but if we set the rippleColor the effect will be on foreground.
is it intentional or by mistake?
and how can i make it on background?

**Comment by lukewalczak** [comment]
Hey @hotaryuzaki, in most of the Paper touchable components, the ripple effect is added to the foreground, which is related to the fact that ripple animation from the Pressable component goes beyond the curved shapes, when ripple is added to the background:



https://github.com/callstack/react-native-paper/assets/22746080/de5a8c27-cf66-420a-a918-a66ade7875ff

> and how can i make it on background?

Generally pressable components, based on the `TouchableRipple` should accept the `background` [property](https://callstack.github.io/react-native-paper/docs/components/TouchableRipple/#background), however looks like the `List.Accordion` doesn't have that option. I will double check it.
