### ISSUE TITLE
Switch component for Android uses MD2 not MD3 design.

### ISSUE THREAD

**Issue by Daniel-Mendes** [callstack/react-native-paper#4038]
### Current behaviour

The design of the switch component on Android uses the MD2 style: https://callstack.github.io/react-native-paper/docs/components/Switch/

![image](https://github.com/callstack/react-native-paper/assets/28825568/ca3507a7-ef42-40d0-a803-84a84c5a3586)

### Expected behaviour

Should use the new design from Material Design 3: https://m3.material.io/components/switch/overview

![image](https://github.com/callstack/react-native-paper/assets/28825568/a5d2b51a-1c2c-403e-94ca-a0a172b2f2e7)

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 13
| react-native                | 0.72.4
| react-native-paper    | 5.9.1

**Comment by SavioNicodemos** [comment]
Do you know if they are following the MD3 on the rest of the library? If they are, I think I can contribute with this

**Comment by SavioNicodemos** [comment]
I've observed that the library utilizes the native 'switch' module from React Native. Consequently, modifications may only be possible if React Native itself is updated. However, I'd appreciate to know if this change to MD3 on React Native Paper can be done.

**Comment by Daniel-Mendes** [comment]
Already answered here:

https://github.com/callstack/react-native-paper/issues/3689#issuecomment-1436567611
