### ISSUE TITLE
TextInput component from react-native-paper overlapping bottom sheet

### ISSUE THREAD

**Issue by vvjiju-sustain** [callstack/react-native-paper#4039]
### Current behaviour
TextInput component from react-native-paper overlapping bottom sheet, there is no issue with other components and the TextInput from react-native also.

### Expected behaviour
I am attaching here with the screenshot, There is no issue with IOS, expecting same in android

### How to reproduce?
put the TextInput component at the bottom side of the page and show bottom sheet.

### Preview
<img width="750" alt="Screenshot 2023-08-22 at 6 57 22 AM" src="https://github.com/callstack/react-native-paper/assets/139965800/9aebcf1f-2746-4050-9ded-51ecdeefa6e4">

### What have you tried so far?
1. changed background color for bottom sheet but not fixed.

### Your Environment

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4 |
| react-native                    | 0.72.3 |
| react-native-reanimated         | 3.4.1 |
| react-native-gesture-handler    | 2.12.1  |
| react-native-paper | 5.9.1 |

**Comment by SavioNicodemos** [comment]
Meybe the problem can be the background color of the BottomSheet. On IOS sometimes have a color by default, on android you have to set manually. Try to add `style = {{ backgroundColor: 'white' }}` on your BottomSheet or in the View that is covering your content inside of it.

**Comment by vvjiju-sustain** [comment]
Are you sure?, I already checked with this solution but not resolved my issue

I am attaching here with the piece of code and screenshot, You can check

`<BottomSheetModalProvider>
      <BottomSheetModal
        ref={bottomSheetModalRef}
        index={1}
        snapPoints={snapPoints}
        enablePanDownToClose
        containerStyle={{backgroundColor: 'green'}}
        $modal
        onChange={handleSheetChanges}>
        <View style={{paddingVertical: 16, flex: 1, backgroundColor: 'red'}}>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
              justifyContent: 'space-between',
              alignItems: 'center',
              padding: 8,
            }}>
            <Header variant="headlineMedium">Profile Photo</Header>
             
             ....

          </View>
        </View>
      </BottomSheetModal>
    </BottomSheetModalProvider>`

<img width="406" alt="Screenshot 2023-08-23 at 10 04 10 AM" src="https://github.com/callstack/react-native-paper/assets/139965800/7bdb6777-ab37-4a9a-a8e4-7baeb23c67e6">

**Comment by lukewalczak** [comment]
Can you provide an expo snack, presenting your issue?

**Comment by SavioNicodemos** [comment]
Yes, without a repro is difficult to try to point the problem

**Comment by vvjiju-sustain** [comment]
when I 

> Maybe the problem can be the background color of the BottomSheet. On IOS sometimes is set a color by default, on android you have to set manually. Try to add `style = {{ backgroundColor: 'white' }}` on your BottomSheet or in the View that is covering your content inside of it.

@SavioNicodemos This issue is not about the backgroundColor. This issue occurs if I put newArchEnabled=true in the gradle.properties.
