### ISSUE TITLE
Incompability with native-base

### ISSUE THREAD

**Issue by GKyomen** [callstack/react-native-paper#4043]
### Current behaviour
After installing native-base, app crashes before first rendering. Main error in console states: `Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider`

### Expected behaviour
Possibility to work w/ both libraries without conflicts.

### How to reproduce?
In `package.json`:
```
    "react-native-paper": "5.0.1",
    "native-base": "^3.4.28",
```
In `App.tsx`:
```
<NativeBaseProvider>
    <PaperProvider>
        {/*...*/}
    </PaperProvider>
</NativeBaseProvider>
```

### Preview
![image](https://github.com/callstack/react-native-paper/assets/30750834/cf146a91-737d-4fc9-9cfa-f389f1a4d5d7)
![image](https://github.com/callstack/react-native-paper/assets/30750834/df104b78-586e-4929-bd65-985b9af612f4)

### What have you tried so far?
`rm -rf node_modules/` and lock files followed by `yarn`
Also, only uninstalling one of the libraries to make it work. Removing from `App.tsx` made no effect at all

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | ?
| android                        | ?
| react-native                | 0.70.8
| react-native-paper    | 5.0.1
| node                            | 16.18.1
| yarn                | 1.22.19
| expo sdk                     | ^47.0.0

**Comment by lukewalczak** [comment]
Please check the related issue to your problem: https://github.com/th3rdwave/react-native-safe-area-context/issues/250. 

Most likely both providers requires `react-native-safe-area-context` to be installed, however you can have each of the in a different version in your `node_modules`.
