### ISSUE TITLE
Update between 5.2.0 and 5.9.1 seriously breaks accessibility on Card elements, possibly others

### ISSUE THREAD

**Issue by meatnordrink** [callstack/react-native-paper#4047]
### Current behaviour
Upgrading from `5.2.0` to `5.9.1` , we have found that setting `accessible={false}` on a Card element no longer actually makes the sub-components available to VoiceOver on iOS. 

Functionally, this means that any buttons or links inside RNP Card elements are now unreachable for VoiceOver users. 

We observed this behavior after upgrading to version `5.9.1`; it was resolved after rolling back to `5.2.0`. 

### Expected behaviour
Adding `accessible={false}` to `<Card>` elements should expose child elements to VoiceOver.

### How to reproduce?
Put a <Button> element inside a <Card> element; try to reach it via VoiceOver on iOS.

### What have you tried so far?
Rolling back to `5.2.0` solved the issue.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.71.12
| react-native-paper    | 5.9.1
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hello @meatnordrink, could you assist in pinpointing the exact version where the accessibility stops working as expected?

**Comment by meatnordrink** [comment]
@lukewalczak , thanks for the response! 

Yes - after further testing, I was able to confirm that it's the update from 5.5.2 to 5.6.0 that breaks accessibility for cards with actions within them. 

I took a snapshot of a component exhibiting this behavior, and diffed it going from 5.5.2 to 5.6.0 - this was the result: 

![image](https://github.com/callstack/react-native-paper/assets/35735666/1c6e2222-7b13-459d-b2b3-8e4a2997fba0)

This is the component - and again, nothing changed in the above diff except upgrading RNP from 5.5.2 to 5.6.0.

```ts
    <Card
      accessible={false}
      style={styles.card}
      elevation={2}
      >...
```

So it appears that if you pass in `accessible={false}` to a `<Card>` component as of 5.6.0, it will be overwritten to `true`. 

I noticed these changes in some other components for the 5.5.2 -> 5.6.0 diff and, while they had no negative effects, I wondered if they might be related: 

![image](https://github.com/callstack/react-native-paper/assets/35735666/7800f29a-5e0c-407f-82b3-7fa2c59d73ec)

Thank you for your response and insight on this!

**Comment by meatnordrink** [comment]
@lukewalczak , I tried tracking down the issue in the code myself, and I believe I've found it. I've submitted [a pull request to fix it](https://github.com/callstack/react-native-paper/pull/4049). Details below, but tl;dr - looks like the `accessible` prop got moved during the Card refactor in 5.6.0 from the `TouchableWithoutFeedback` to the child content `View` - where it would have no effect.

----------


State as of `src/components/Card/Card.tsx` in 5.5.2, starting on ln 272:
```ts
      <TouchableWithoutFeedback
        delayPressIn={0}
        disabled={!(onPress || onLongPress)}
        delayLongPress={delayLongPress}
        onLongPress={onLongPress}
        onPress={onPress}
        onPressIn={onPress || onLongPress ? handlePressIn : undefined}
        onPressOut={onPress || onLongPress ? handlePressOut : undefined}
        testID={testID}
        accessible={accessible} // ACCESSIBLE PROP HERE
      >
        <View style={[styles.innerContainer, contentStyle]}>
          {React.Children.map(children, (child, index) =>
            React.isValidElement(child)
              ? React.cloneElement(child as React.ReactElement<any>, {
                  index,
                  total,
                  siblings,
                })
              : child
          )}
        </View>
      </TouchableWithoutFeedback>
      <TouchableWithoutFeedback
        delayPressIn={0}
        disabled={!(onPress || onLongPress)}
        delayLongPress={delayLongPress}
        onLongPress={onLongPress}
        onPress={onPress}
        onPressIn={onPress || onLongPress ? handlePressIn : undefined}
        onPressOut={onPress || onLongPress ? handlePressOut : undefined}
        testID={testID}
        accessible={accessible}
      >
        <View style={[styles.innerContainer, contentStyle]}>
          {React.Children.map(children, (child, index) =>
            React.isValidElement(child)
              ? React.cloneElement(child as React.ReactElement<any>, {
                  index,
                  total,
                  siblings,
                })
              : child
          )}
        </View>
      </TouchableWithoutFeedback>
```

In 5.6.0: 
```ts
  const content = (
    <View
      style={[styles.innerContainer, contentStyle]}
      testID={testID}
      accessible={accessible}  // ACCESSIBLE PROP NOW ON CHILD CONTENT
    >
      {React.Children.map(children, (child, index) =>
        React.isValidElement(child)
          ? React.cloneElement(child as React.ReactElement<any>, {
              index,
              total,
              siblings,
            })
          : child
      )}
    </View>
  );
  
  // ...
  
        {onPress || onLongPress ? (
        <TouchableWithoutFeedback
          delayPressIn={0}
          disabled={disabled}
          delayLongPress={delayLongPress}
          onLongPress={onLongPress}
          onPress={onPress}
          onPressIn={handlePressIn}
          onPressOut={handlePressOut} // NO ACCESSIBLE PROP ON TOUCHABLE
        >
          {content}
        </TouchableWithoutFeedback>
      ) : (
        content
      )}
```

**Comment by lukewalczak** [comment]
Hey @meatnordrink, thanks a lot for the investigation, I'll do my best to get acquainted with it in the following days 🙌🏽
