### ISSUE TITLE
Wrong iconColor assigment in Chip component

### ISSUE THREAD

**Issue by DevHusariaSolutions** [callstack/react-native-paper#4057]
### Current behaviour
Chip should allow us for custom UI. When we define icon as name from builtin package, we can only define this icon color by "onSecondaryContainer". But it will work only, if "icon" was not defined, because otherwise color theme.color.primary will be used instead one resolved by helper function.

### Expected behaviour
Chip should always use iconColor derived from helpers if there is no disabled/selected state.

### How to reproduce?
Simply visit file src/components/Chip and check range of lines 349-355. We can see, that iconColor will be not used, while few lines below we see good condition for defining such color.

### Preview
-

### What have you tried so far?
Dig in code, for now I see no way to fix that.

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.72.4
| react-native-paper    | 5.10.1
| node                            | 16.9.X
| npm or yarn                | pnpm, but doesnt matter
| expo sdk                     | 49

**Comment by lukewalczak** [comment]
Hey @DevHusariaSolutions, in both cases when you pass the icon as a string or as a component, you can override the color using the `theme.colors.primary`:

* icon as string:

```
<Chip
  theme={{ colors: { primary: 'red' } }}
  icon="camera"
  onPress={() => {}}
  style={styles.chip}
>
  Simple
</Chip>
```

* icon as component:

```
import Icon from 'react-native-vector-icons/FontAwesome';
...
  <Chip
    icon={({ size, color }) => (
      <Icon name="rocket" color={color} size={size} />
    )}
    onPress={() => {}}
    theme={{ colors: { primary: 'red' } }}
    style={styles.chip}
  >
    Simple
  </Chip>
```

As a result, you can observe that both icons have the `red` color:

<img width="522" alt="Zrzut ekranu 2023-09-6 o 19 57 32" src="https://github.com/callstack/react-native-paper/assets/22746080/560f5b2e-7b04-452c-aa11-7bd31520c950" width="300">

The `onSecondaryContainer` color, you mentioned, is used for the built-in `check` icon, when both props `selected` and `showSelectedCheck` are true, but user didn't pass any `icon`.

According to the MD Figma kit:

* the `onSecondaryContainer` color is be used for `selected` icon:

<img width="610" alt="image" src="https://github.com/callstack/react-native-paper/assets/22746080/0dce69ef-2ac7-465e-923d-dccc5d8c60a5">

* the `primary` color is used for other icons:

<img width="539" alt="image" src="https://github.com/callstack/react-native-paper/assets/22746080/d4529bbf-b57f-41c7-a353-f92651920e45">
