### ISSUE TITLE
Allow custom disabled text color for buttons

### ISSUE THREAD

**Issue by jahirfiquitiva** [callstack/react-native-paper#4059]
**Is your feature request related to a problem? Please describe.**
I need to set a custom disabled text color for some specific buttons, and can't have a global value

**Describe the solution you'd like**
Add a new prop for custom disabled button text color.

**Describe alternatives you've considered**
Using `theme` prop to override the colors, but it conflicts with the `styled-components` theme property, resulting in undefined values.

**Comment by lukewalczak** [comment]
Hey @jahirfiquitiva, could you please elaborate on how overriding the color, directly in the `Button`, using there a `theme` property, conflicts with `styled-components`? Could you please share your button's code?

**Comment by jahirfiquitiva** [comment]
@lukewalczak I can't share the code

But basically, styled-components include theming support which can be accessed via the `props.theme` field

https://styled-components.com/docs/advanced#theming

The problem with the `theme` prop in React Native Paper, is that it will override the `styled-components` theme (or global theme)

Therefore, the styled component no longer has access to the global theme, but only what is specified in the `theme` prop in RNP.

Meaning I could not do `props.theme.something` because that `something` might not exist in the React Native Paper `theme` prop

**Comment by lukewalczak** [comment]
@jahirfiquitiva you don't have to attach your production code, just create the repro, based on which we can investigate the problem.

**Comment by lukewalczak** [comment]
Hey @jahirfiquitiva, please take a look at the provided [snack](https://snack.expo.dev/@react-native-paper/styled-components-with-paper) where I was able to override the color for disabled text using the `theme` property, keeping the background color from the styled-components theme at the same time.

**Comment by jahirfiquitiva** [comment]
@lukewalczak thanks, so it basically requires spreading the whole styled-components theme into a new object, along with the overridden colors, right?

this is ok for a theme with a single property, will it still be as efficient if there were tens of properties? 🤔

**Comment by lukewalczak** [comment]
You can always lift up merging the theme to the const and memoize it. My goal was to provide you the idea how you can handle both themes to be working with each other.

**Comment by jahirfiquitiva** [comment]
alright, thanks
