### ISSUE TITLE
TextInput keyboard has caps-lock on by default for all characters

### ISSUE THREAD

**Issue by shreyasshetty1468** [callstack/react-native-paper#4062]
I'm using TextInput from 'react-native-paper'. The problem is, 

- In device A, the keyboard has caps-lock on by default all the time. So when I switch off the caps-lock and type a character in lowercase, the caps-lock are on by default for the next character. 
- In device B, the keyboard switches the caps-lock alternatively. For example, string typed would look like 'AbCdEf'.

TextInput component:
```
    <TextInput
          style={styles.inputLayout}
          placeholder={searchLeadsModel.actions.getPlaceholderName()}
          value={searchQuery$.get()}
          onChangeText={handleSearchInputChange}
          selectionColor={colors.black}
          keyboardType={this.obs_search_type.peek() === SearchFilterTypes.PHONE_NUMBER ? 'numeric' : 'default'}
          testID={'SearchLeads_TextInput'}
          autoFocus={true}
          left={
            <TextInput.Icon
              name="arrow-left"
              size={24}
              color={colors.black}
              onPress={handleOnBackPress}
              marginRight={28}
              marginLeft={20}
              testID={'SearchLeads_goBackButton'}
            />
          }
          right={
            <TextInput.Icon name="close-circle" size={24} onPress={handleClearText} testID={'SearchLeads_clearText'} />
          }
          maxLength={searchLeadsModel.actions.findMaxLength()}
          underlineColor="#FFF"
          activeUnderlineColor="#FFF"
          onSubmitEditing={searchLeadsModel.actions.onInputSubmit}
    />
```

onChangeText function: 
```
    private handleSearchInputChange = (searchValue: string) => {
        const searchQuery$ = this.obs_search_query;
        if (this.obs_search_type.peek() !== SearchFilterTypes.FO_NAME) {
          searchQuery$.set(searchValue.toUpperCase());
       } else {
          searchQuery$.set(searchValue);
          if (searchQuery$.peek().length >= 3) {
            this.resetPaginationState();
            this.actions.fetchLeadsList();
          }
       }
    };
```

I'm stuck over here from some time. I tried updating the text using react hooks instead of using legendstate observables, but it is not working. It seems to be an internal issue. Please share your thoughts on this 🙏

**Comment by lukewalczak** [comment]
Hey @shreyasshetty1468, do you observe the same problem using `TextInput` from `react-native`?

**Comment by shreyasshetty1468** [comment]
Hi @lukewalczak, thanks for your reply. I just checked it, the same issue is occurring with `TextInput` from `react-native`.

**Comment by shreyasshetty1468** [comment]
It stopped after I stopped setting dynamic value for keyboardType. now it's just `keyboardType={'default'}`

Earlier the getKeyboardType function was returning a string value 'numeric' or 'default', which might not be accepted as an enum. Although the relation between the cause and effect is weird. 

Is there any other way to use dynamic keyboardType?

**Comment by lukewalczak** [comment]
As this issue isn't directly related to the library itself, I'm closing it. I recommend checking StackOverflow to see if a similar topic has been discussed there. If you don't find an existing discussion, I guess you can open a new post there with your question.
