### ISSUE TITLE
Card Content Rendering HTML

### ISSUE THREAD

**Issue by kingrootid** [callstack/react-native-paper#4065]
Hello, 

I want ask about component <Card.Content> Can render html ?

i was decode entities the html and always printed html

how to rendering html on <Card.Content> ?

**Comment by lukewalczak** [comment]
Hey @kingrootid what do you mean by rendering html inside the `Card.Content`, could please provide some example?

**Comment by lukewalczak** [comment]
Hey @kingrootid, if you properly format your html content code, you can use it inside the `Card.Content`, however it will work only on the web platform. Please take a look at the [snack](https://snack.expo.dev/@react-native-paper/blissful-green-banana)

```
  <Card>
    <Card.Content>
      <Text variant="titleLarge">Card title</Text>
      <Text variant="bodyMedium">Card content</Text>
      <p style={{ textAlign: 'center' }}>ABCDE</p>
      <span style={{ height: 100, width: 100, backgroundColor: 'pink' }}></span>
      <p>
        To force
        <br /> line breaks
        <br /> in a text,
        <br /> use the br
        <br /> element
      </p>
    </Card.Content>
  </Card>
  ```
