### ISSUE TITLE
<Drawer.Item/> Cannot build out in a flatMap or forEach loop

### ISSUE THREAD

**Issue by Javakian12** [callstack/react-native-paper#4066]
### Current behaviour
Drawer.Item does not display from a flatMap or a forEach

### Expected behaviour
Drawer.Item should build out for every flatMap or forEach

### How to reproduce?
You can reproduce by using the code:
```
// forEach:
     const test = [
        {
            val1: "test"
        },
        {
      val2: "test2"
        }
    ]

<Drawer.Section title="Some title">
                    {
                    test.forEach((v,i)=>{
                        <Drawer.Item label={"I am a label!"}/>
                    })
                    }
 </Drawer.Section>

// flatMap:
    const DrawerMenu = [
        {
            label: "Home",
            icon: "home",
            style: {width: '100%', height: '100%'}
        },
        {
            label: "Messages",
            icon: "message-badge",
            style: {width: '100%', height: '100%'}
        },
        {
            label: "Labs",
            icon: "doctor",
            style: {width: '100%', height: '100%'}
        },
        {
            label: "Center",
            icon: "dog-side",
            style: {width: '100%', height: '100%'}
        }
    ]

<Drawer.Section title={"Menu"}> 
        { 
        Items?.length > 0 && Items?.flatMap((v,i)=>{
             <Drawer.Item
                key={i+1}
                label={v?.label&&v?.label}
                Icon={v?.icon&&v?.icon}
                style={v?.style&&v?.style}
                onPress={()=>console.log("Hello")}
            />
        })}
    </Drawer.Section>
```
### Preview
![bug-paper](https://github.com/callstack/react-native-paper/assets/89485382/34a384dc-06d1-4b5b-a8b8-8bc997372c29)

### What have you tried so far?
Per the code, I have tried multiple methods of using dynamic arrays to make a dynamic amount of <Drawer.Item/>. I have only gotten it to work by putting the <Drawer.Item/> outside of the loop, meaning that I have to hard code each <Drawer.Item/>.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | None
| android                        | None
| react-native                | 0.71.8
| react-native-paper    | 5.9.0
| node                            | 16.15.1
| npm or yarn                | yarn 1.22.19
| expo sdk                     | 0.7.3

**Comment by lukewalczak** [comment]
I think there is an issue within your code, concerning rendering `Drawer.Item` – looks like you're missing `return`:

```
        {DrawerMenu?.length > 0 &&
          DrawerMenu?.flatMap((v, i) => {
            return (
              <Drawer.Item
                key={i + 1}
                label={v?.label && v?.label}
                Icon={v?.icon && v?.icon}
                style={v?.style && v?.style}
                onPress={() => console.log('Hello')}
              />
            );
          })}
      </Drawer.Section>
```

**Comment by Javakian12** [comment]
So small and simple yet important. Thank you for the guidance 😊
