### ISSUE TITLE
How to test(see live) changes that i made in the library components (just wanted to contribute in some components)

### ISSUE THREAD

**Issue by ghulamyazdani** [callstack/react-native-paper#4069]
### Ask your Question

I am not able to test the components that I am making changes in, do  I have to always publish the library and install it in the app every time to see the changes?

**Comment by raajnadar** [comment]
You need to run the example app and check the changes that you do locally

https://github.com/callstack/react-native-paper/tree/main/example

**Comment by lukewalczak** [comment]
Hey @ghulamyazdani, please check the [contribution guide](https://github.com/callstack/react-native-paper/blob/main/CONTRIBUTING.md) where you can find all of the important information.
