### ISSUE TITLE
Appbar with Error: Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by josmmv** [callstack/react-native-paper#4070]
### Current behaviour
I am using the Appbar component and when I try to render an App.Action I get the error `"Error: Text strings must be rendered within a <Text> component"`.

### Expected behaviour
To render the icon in the Appbar

### How to reproduce?

https://github.com/callstack/react-native-paper/assets/23065564/6bb1feb0-7b86-4db9-9451-3e00b866b20f

### What have you tried so far?

If I render an icon from MaterialCommunityIcons it works without any problems

https://github.com/callstack/react-native-paper/assets/23065564/1c09077b-3c09-434e-9f04-0f5851768fe1

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 17.0
| android                        | 11
| react-native                | 0.72.4
| react-native-paper    | 5.10.4
| node                            | 18.17.1
| yarn                             | 1.22.19
| react-native-vector-icons | 10.0.0

**Comment by lukewalczak** [comment]
Hey @josmmv, could you please create sample repo with your issue?

**Comment by lukewalczak** [comment]
Closing due to missing response from the author.
