### ISSUE TITLE
How change the entire Text color within theme?

### ISSUE THREAD

**Issue by renaldodev** [callstack/react-native-paper#4071]
### Ask your Question

By default the text color is black so I Would like to change this behavior by defining my custom color using the theme section, but I don't know which color variable changes.

**Comment by lukewalczak** [comment]
`Text` component by default uses using `onSurface` color from the `theme` as it's mentioned in the [documentation](https://callstack.github.io/react-native-paper/docs/components/Text/#theme-colors)
