### ISSUE TITLE
Switch component haptic feedback

### ISSUE THREAD

**Issue by damonmoya** [callstack/react-native-paper#4073]
### Switch component haptic feedback
As a requirement for my project, user may disable vibration (A.K.A. haptic feedback). Nonetheless, Switch component from the library seems to have a light feedback when pressed, and I could not find any information in the docs about it.

**Is it possible to disable haptic feedback for this component?**

**Comment by lukewalczak** [comment]
Hey @damonmoya, on the iPhone, I've disabled Vibration in `Settings -> Accessibility -> Vibration` and when pressing a `Switch` there is no haptic feedback.

What's more, the `Switch` component inside the library, under the hood uses the [native switch ](https://reactnative.dev/docs/switch) from `react-native`, so if you disable the vibration in the settings then it should be applied to the component.
