### ISSUE TITLE
TextInput label is clipped badly in 'flat' mode

### ISSUE THREAD

**Issue by ramakula** [callstack/react-native-paper#4075]
### Current behaviour
When we use two textinputs in 'flat' mode side by side on a Pixel 3 device, label is clipped even though there is a lot of space.

### Expected behaviour
Label on a TextInput with should only clip/wrap if there isn't enough space.

### How to reproduce?
Two text inputs side by side on a small device like pixel 3 with a label.

### Preview
<img width="423" alt="Screenshot 2023-09-12 at 5 36 07 PM" src="https://github.com/callstack/react-native-paper/assets/2745769/3954e793-0050-4745-9bd9-0e12033febcc">

### What have you tried so far?
I've tried setting the style but no luck.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | 13
| react-native                | 0.72.2
| react-native-paper    | 5.4.1
| node                            | 8.5.0
| npm or yarn                | pnpm
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hey @ramakula, I think the [PR](https://github.com/callstack/react-native-paper/pull/3941) with setting min width can fix your issue. Are you able to provide your code related to inputs, so I can confirm it will work as expected?

**Comment by lukewalczak** [comment]
Most likely it should be fixed in `5.10.5`, if not please reopen the issue with some repro.

**Comment by ramakula** [comment]
Sure, I'll do that. Thank you
