### ISSUE TITLE
Expo SDK 49: Menu component is not dismissable on web and causes console error

### ISSUE THREAD

**Issue by szado** [callstack/react-native-paper#4079]
### Current behaviour
When I open the menu in a web browser, I get an error in the console. After this, closing the menu by clicking outside it is not possible (ESC closes the menu correctly).

### Expected behaviour
The menu should close correctly when you click outside of it, and no errors should be emitted in the browser console.

### How to reproduce?
I created the repo because Expo Snack doesn't support SDK 49 yet.

https://github.com/szado/expo49-rnp-bug

### Preview
![obraz](https://github.com/callstack/react-native-paper/assets/20907536/d54dd786-1ec9-4655-b6df-7d83f657b6fe)

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.72.4
| react-native-paper    | 5.10.4
| expo sdk                     | 49

**Comment by lukewalczak** [comment]
Thanks for the repro repository! When I get a chance will take a look at it

**Comment by lukewalczak** [comment]
@szado which browser are you using? I was able to observe the error in the console, however I can close the `Menu` by pressing outside.

**Comment by szado** [comment]
@lukewalczak Firefox 117.0.1

**Comment by szado** [comment]
@lukewalczak thank you for quick fix. One more issue which I noticed after upgrade to 5.10.6 is inadequate cursor over the dismissable area. Previously it was a `default` cursor, now is a `pointer` which doesn't seem appropriate from a UX perspective and it cannot be changed. Described behavior occurs on both Chrome and Firefox.

Before:
![obraz](https://github.com/callstack/react-native-paper/assets/20907536/da7f2786-cb0f-40f8-98d2-30b54077b5ac)

After:
![obraz](https://github.com/callstack/react-native-paper/assets/20907536/e4779640-4c84-4b62-a7b5-46e2794d13b9)
