### ISSUE TITLE
Bug in Dialog: null is not an object (evaluating 'this.props.manager.unmount')

### ISSUE THREAD

**Issue by fahadakhan96** [callstack/react-native-paper#408]
### Current behaviour

Dialog doesn't show on changing state to visible. Instead, an error shows up: "null is not an object (evaluating 'this.props.manager.unmount')"

### Expected behaviour

Dialog should show up as expected.

### Code sample

Used the code on the Dialog page in the docs.
[Here](https://snack.expo.io/H1oKkiMxm) is the Expo Snack.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android
| react-native          | 0.55.2
| react-native-paper    | 1.10.3
| node                  | 8.11.1
| npm or yarn           | yarn 1.6.0

**Comment by Trancever** [comment]
Hi @fahadakhan96 . You have to wrap your root component in a Provider. Please make sure you follow our [Getting-Started guide](https://callstack.github.io/react-native-paper/getting-started.html) - . You will find there all needed informations :)

**Comment by 0x01Brain** [comment]
I had the same problem, where I actually was wrapping the root component in a provider and I was using a custom child component that uses Dialog component inside it, I had to wrap the <Dialog> component with <Portal.Host> instead of <Portal>.

**Comment by asifsha** [comment]
The error resolved if I use <Portal.Host>, but Dialog was not visible, so I wrap my root component with  <Provider> and warp <Dialog> with <Portal>.
