### ISSUE TITLE
Card elevation is not working properly

### ISSUE THREAD

**Issue by SrinivasanJms** [callstack/react-native-paper#4089]
### Current behaviour
I upgraded my react native 0.63.4 to 0.71.6 but the react native paper card elevation props not working properly. outlined props worked but elevated default prop not elevated the card in the react native paper.

### Expected behaviour
Card need to be elevated 

### Preview
**Before Update**
![1695111778343](https://github.com/callstack/react-native-paper/assets/80248449/51edd9df-20e1-4cf7-8022-931c192b197a)

**After Updated:**
![Screenshot_20230919_134353](https://github.com/callstack/react-native-paper/assets/80248449/3d3e74b1-0abc-4710-bc10-5b7a9be71afd)

### What have you tried so far?
1. Tried to change the different version of react native paper. it won't help to elevated the card.
2. Outlined prop is working but elevated prop won't work.
3. Try to <Card.Content> based on the latest version document but it won't elevated.

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.71.6
| react-native-paper    | 4.0.0
| node                            | 16.13.0
| npm or yarn                | yarn 1.22.19

**Comment by SrinivasanJms** [comment]
<img width="1074" alt="Screenshot 2023-09-19 at 6 46 14 PM" src="https://github.com/callstack/react-native-paper/assets/80248449/ac7b56b2-d4f3-4cfb-b4d6-a280e436f6d1">

In repo it was elevated properly but in my internal code doesn't elevated. i don't know the exact reason

**Comment by sj9710** [comment]
Try updating react-native and react-native-paper to their latest version and after updating and before running the app try
react-native start --reset-cache

**Comment by SrinivasanJms** [comment]
@sj9710 
1. Actually i upgraded the react native my old project 0.63.4 to 0.71.4 with help of this website "https://react-native-community.github.io/upgrade-helper/" after i upgraded my react native paper card elevation was not working.
2. I tried the react native paper with new project with this command "npx react-native init newproject" the react native paper card is working fine.
