### ISSUE TITLE
No checkbox appears

### ISSUE THREAD

**Issue by icaroliv** [callstack/react-native-paper#4096]
### Current behaviour
An icon appears instead of a checkbox

### Expected behaviour
I expected a checkbox component to appear instead of icons appearing on my screen

### How to reproduce?
1. Install yarn add react-native-paper
2. Install yarn add react-native-safe-area-context
3. Install yarn add react-native-vector-icons
4. Add the checkbox on any screen

https://github.com/icaroliv/BugReactNativePaper

### Preview
![Screenshot_1695559463](https://github.com/callstack/react-native-paper/assets/39637375/807d386c-9db4-4724-ae41-8a59ab2c6085)

### What have you tried so far?
Reinstall lib, add Provider, Restart App

### Your Environment

| software                      | version
| --------------------- | -------

| android                        | 13
| react-native                | 0.72.4
| react-native-paper    | 5.10.6
| node                            | 18.16.0
| yarn                | 1.22.19

**Comment by lukewalczak** [comment]
Did you follow the additional installation steps related to `react-native-vector-icons` mentioned in the guide? 

Additional steps: https://github.com/oblador/react-native-vector-icons#installation

**Comment by icaroliv** [comment]
Thank! problem solved!
