### ISSUE TITLE
Icon not centered without label and dense true in outlined textinput

### ISSUE THREAD

**Issue by wilav-dev** [callstack/react-native-paper#4097]
TextInput.Icon is not vertically centered when using outlined input and dense, without label.

`<TextInput
mode="outlined"
dense={true}
right={<TextInput.Iconicon="eye"/>}
/>`

![WhatsApp Image 2023-09-27 at 09 30 50](https://github.com/callstack/react-native-paper/assets/71793326/adcf8742-4119-4590-8f8a-0b071a6f3eb6)

It works fine in flat mode.

**Comment by lukewalczak** [comment]
Which library version are you using?

**Comment by wilav-dev** [comment]
React native paper version: 5.10.6
Theme version: 2

**Comment by lukewalczak** [comment]
Are you sure that you have `5.10.6` installed? I've just checked on the example app and looks like everything is properly displayed:

<img width="1512" alt="image" src="https://github.com/callstack/react-native-paper/assets/22746080/4396226d-6910-46e4-8d28-1e5f0b40c105">
