### ISSUE TITLE
Password Strength interactive ring

### ISSUE THREAD

**Issue by Angelk90** [callstack/react-native-paper#4099]
**Is your feature request related to a problem? Please describe.**

Being able to have a similar implementation on TextInputs would be very useful for checking password security, which indicates password strength.

https://github.com/callstack/react-native-paper/assets/20476002/546c525c-a714-463d-8d55-e5f8eb83fa4d

**Describe the solution you'd like**

https://x.com/nitishkmrk/status/1697583481294078136

https://x.com/bufgix_/status/1697772173484507559

https://x.com/akardas16/status/1698000890488398144

https://x.com/jaytel__/status/1697722921874018518

**Comment by lukewalczak** [comment]
The proposed feature request does not align with the Material Design guidelines; hence, it will not be implemented.
