### ISSUE TITLE
Using flow over `propTypes`

### ISSUE THREAD

**Issue by grabbou** [callstack/react-native-paper#41]
The contributing guide as well as the current files use and mention propTypes. Is that going to be our preferred approach or shall we favour Flow types instead?

**Comment by satya164** [comment]
@grabbou I've been thinking about this and I think we'll need to setup a prepublish script which transpiles these flow annotations to propTypes before publishing

**Comment by ahmedlhanafy** [comment]
Does this need to be open? @satya164

**Comment by satya164** [comment]
We've not arrived at a conclusion, so yes.
