### ISSUE TITLE
MaterialBottomTab showing rounded background on icon

### ISSUE THREAD

**Issue by GaboDot** [callstack/react-native-paper#4100]
Hi!
I just recently installed and created MaterialBottomNavigator.

I found something that I'm not sure if it's a bug or a missconfiguration on the component.
The icon on the bottom tab is showing a rounded background for active tabs:

![image](https://github.com/callstack/react-native-paper/assets/8822582/b6167735-7599-4f7a-bda2-15c6d6ccbc2b)

Even without icon I'm getting the pink background:

![image](https://github.com/callstack/react-native-paper/assets/8822582/b1a05af3-ee43-4db7-9b8d-20a159e964a8)

I tried different configurations but I was not able to get rid of this weird background:

```
const Tab = createMaterialBottomTabNavigator ();
const App = () => {
  return (
    <NavigationContainer>
      <StatusBar backgroundColor="#263238" barStyle="dark-content" />
        {islogin ? (
          isNewEvent ? (
          <Tab.Navigator
            initialRouteName="Home"
            labeled={false}
            barStyle={{ 
              backgroundColor: '#263238',              
            }}
            shifting={true}
            activeColor="#00bcd4"
            inactiveColor="#F5F5F5"
            >
            <Tab.Screen name="Home" tabBarColor="blue" options={{
              headerShown: false,
              tabBarColor: 'blue',
              tabBarIcon: ({ color }) => (
                <MaterialCommunityIcons name="home" color={color} size={30}/>
              ),
            }}>
              {() => <Home setIsLogin={setIsLogin} setIsNewEvent={setIsNewEvent}/>}
            </Tab.Screen>
            <Tab.Screen name="Eventos" options={{
              headerShown: false,
              tabBarIcon: ({ color }) => (
                <MaterialCommunityIcons name="calendar" color={color} size={30}/>
              ),
            }}>
              {() => <View><Text>Eventos</Text></View>}
            </Tab.Screen>
            <Tab.Screen name="Settings" options={{
              headerShown: false,
              tabBarIcon: ({ color }) => (
                <MaterialCommunityIcons name="cog" color={color} size={30}/>
              ),
            }}>
              {() => <SettingsScreen setIsLogin={setIsLogin}/>}
            </Tab.Screen>
          </Tab.Navigator>
          ):(
            <MainEventComponent setIsNewEvent={setIsNewEvent}/>
          )
        ) : (
          <Login setIsLogin={setIsLogin} />
        )}
    </NavigationContainer>
  );
};
```
The other parameters are working as expected also the navigation is ok.

Packages versions:

```
react-native: 0.72.5,
@react-navigation/native: ^6.1.7
@react-navigation/material-bottom-tabs: ^6.2.17
react-native-paper: ^5.10.6",
react-native-pager-view: 6.2.0
```

Also I tried downgrading the material-bottom-tabs to 6.2.1 but I got the same result.

**Comment by lukewalczak** [comment]
The `rounded` shape displayed under the icon, on the active tab, is an integral part of the MD navigation bar:

<img width="430" alt="image" src="https://github.com/callstack/react-native-paper/assets/22746080/ac866a76-197c-4781-8210-ccfbb0fa3fa0">


Certainly, it's not a bug, however, you have the option to make it transparent if you prefer. There are two options to accomplish this, and the choice depends on the specific component you are currently using for the bottom navigation.

* For the `BottomNavigation`:

I would suggest checking which theme color is used for a specific element, in your case outline pill. Its background color is `theme.colors.secondaryContainer` which you should be able to easily override using the theme prop in a component:

```
    <BottomNavigation
      ...
      theme={{colors: {secondaryContainer: 'transparent'}}}
    />
```    

* For `BottomNavigation.Bar`:

To modify the pill color also the theme prop can be used. The following code demonstrates how to apply the theme prop to a `BottomNavigation.Navigator` component:

```
      <Tab.Navigator
        screenOptions={{
          headerShown: false,
        }}
        tabBar={({ navigation, state, descriptors, insets }) => (
          <BottomNavigation.Bar
            navigationState={state}
            safeAreaInsets={insets}
            theme={{ colors: { secondaryContainer: 'transparent' } }}
            / ... /
```

**Comment by Keyur-Rao** [comment]
By adding theme prop in Navigator of Tab you can change color and remove by 'transparent' value 
theme={{ colors: { secondaryContainer: 'blue' }}
<Tab.Navigator
      id='#TabNav'
      initialRouteName="Home" // By default render this screen first
      activeColor={Colors.primary} // active tabBar font color
      inactiveColor={Colors.secondary} // Inactive tabBars font color
      barStyle={{ backgroundColor: 'white' }} // TabBar style
      sceneAnimationEnabled={true} // Show screen animated view
      sceneAnimationType='shifting'
      theme={{ colors: { secondaryContainer: 'blue' }}
    >
      <Tab.Screen
        name="Home"
        component={Home}
        options={{
          tabBarColor: 'orange',
          tabBarLabel: 'Home',
          tabBarIcon: ({ color, focused }) => (
            <MaterialCommunityIcons name="home" color={ focused ? 'white' : Colors.secondary} size={26} />
          ),
        }}
      />
      <Tab.Screen
        name="Add"
        component={Add}
        options={{
          tabBarColor: 'blue',
          tabBarLabel: 'Add',
          tabBarIcon: ({ color, focused }) => (
            <MaterialIcons name="add" color={ focused ? 'white' : Colors.secondary} size={26} />
          ),
        }}
      />
</Tab.Navigator>
