### ISSUE TITLE
BottomNavigation Badge Not Refreshing 

### ISSUE THREAD

**Issue by SamJbori** [callstack/react-native-paper#4103]
### Current behaviour
Using `<BottomNavigation />` component with a numbered state  for the `badge` tag in `routes` doesn't refresh the number showing on the icon when the state change.

### Expected behaviour
The number on the icon should update corresponding to the state change.

### How to reproduce?

[https://snack.expo.dev/@samjbori/rnpaper-bottomnavigationissue](https://snack.expo.dev/@samjbori/rnpaper-bottomnavigationissue)
Note: Icons isn't showing correctly on Snack.Expo for unrelated reasons

**Comment by lukewalczak** [comment]
Hey @SamJbori, the `badge` value passed in the `routes` array is not changing the value inside the component because the badge value is set as a static property when the _routes_ array is initialized. 

Changing the `badge` state using `badgeSet` won't automatically update the _badge_ property of the _route_ inside the `routes` array. In order to achieve it you need to update the whole `routes`.

**Comment by SamJbori** [comment]
Seems like an issue to me!
I also noticed that since I switched to RNPaper `<ButtomNavigation /> `my App slowed significantly, I switched back to RNavigation and it resolved all my issues.

**Comment by lukewalczak** [comment]
> Seems like an issue to me!

What do you mean by issue? If you want to have an updated `badge` value in your route, there is a need to introduce _set_ function which lets you update the state of your routes and trigger a re-render, e.g. `setRoutes`:

```
const [routes, setRoutes] = React.useState()
```

then inside functions where you are setting a new badge value use the `setRoutes` to update `routes` appropriately:

```
  const increaseBadge = () => {
    badgeSet(badge + 1);
    
    // Pass updated routes with new badge value
    setRoutes(updatedRoutes)
  };
  
  const decreaseBadge = () => {
    badgeSet(badge - 1);
    
     // Pass updated routes with new badge value
    setRoutes(updatedRoutes)
  };
``` 

> I also noticed that since I switched to RNPaper <ButtomNavigation /> my App slowed significantly, I switched back to RNavigation and it resolved all my issues.

Could you please provide some results/benchmarks?
