### ISSUE TITLE
TextInput Label prop

### ISSUE THREAD

**Issue by VladTabacariu** [callstack/react-native-paper#4106]
TextInput LABEL prop is rendering with the width of the viewport width which is causing overflow issues. 

It should match the width of the container

**Comment by lukewalczak** [comment]
Could you please attach the screenshot presenting your issue and create the expo snack or small demo repro?

**Comment by VladTabacariu** [comment]
I thought i went mad. i tried replicating it in an expo snack but everything was ok. after 1 hour i realized the version of RNP was 4.9.2. *face palm*. My project is using the latest 5.10.6 which has the problem described.
![rnp 4 9 2](https://github.com/callstack/react-native-paper/assets/77915628/05fa2717-8b2c-46f3-acb7-6539b8ff38cd)

RNpaper versions 4.9.2
So as u can see everything ok. My TextInput is 200px and so the label.

![rnp latest](https://github.com/callstack/react-native-paper/assets/77915628/878bc64b-7edf-4365-bcea-cc41791e82b5)

RNpaper latest.
Now in the latest version there are two new props to the label div. z-index and of course width. Set to the viewport width(333px). And making my webpage to scroll horizontally if the TextInput is inline with other elements..

**Comment by lukewalczak** [comment]
Could you please check whether on version `5.10.5` you are facing the same issue?

**Comment by VladTabacariu** [comment]
5.10.5 same issue. found that 5.10.4 works.

**Comment by lukewalczak** [comment]
Correct, thanks for checking. I think I know where the issue is 🤔

**Comment by lukewalczak** [comment]
@VladTabacariu are you able to confirm the changes from the [PR](https://github.com/callstack/react-native-paper/pull/4128) solve the issue?
