### ISSUE TITLE
Tooltip position is off the child component

### ISSUE THREAD

**Issue by efthimispegas** [callstack/react-native-paper#4107]
### Current behaviour
Wrapping the tooltip with a expo component (a <Icon> element for example exported from @expo/vector-icons library) does not seem to get the correct ref to the child element. Instead, the tooltip appears always in the center of the screen, regardless of the child element type.

### Expected behaviour
The Tooltip should reference the child element correctly and be able to get the measurements for the wrapped child correctly in order to position the tooltip respectively.

### How to reproduce?
Run provided expo snack either on embedded emulator or on physical device:
https://snack.expo.dev/@epegas/9a8e5a

### Preview

https://github.com/callstack/react-native-paper/assets/43468988/b0e8f0a2-7a5e-43bf-9366-862194a3f396

### What have you tried so far?
I have taken a look in the Tooltip.tsx codebase and it seems to be doing the calculation of positionX / positionY incorrectly.

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.72.4
| react-native-paper    | 5.10.4
| node                            | 18.15.0 (not really relevant, but oh well 🤷‍♂️ )
| npm                             | 9.5.0
| expo sdk                     | 49.0.0

**Comment by krishna-gujjjar** [comment]
I got the same problem but fix with this.
Just add `alignItems: "Direction of Your child"` and it will work.

```jsx
<Tooltip title="tooltip title" style={{ alignItems: "flex-start" }}>
  { /* Your child */ }
</Tooltip>
```

**Comment by efthimispegas** [comment]
> Hey @efthimispegas, please notice that the `Tooltip` displayed on the `Icon` is wrapped in a parent `View`, which takes the whole width _(try and add into its styles `backgroundColor`)_ hence the position of the tooltip. Idk what is your end goal, however adding at least `flexDirection: "row"` to the `View` will fix the issue.

I don't understand why the parent element should affect the funcionality of the Tooltip. What if, in my real case scenario I have the Tooltip nested inside N <View> elements? Should I change the styles of each of my views in order to position my Tooltip element?

**Comment by thoughtworks-tcaceres** [comment]
> I got the same problem but fix with this. Just add `alignItems: "Direction of Your child"` and it will work.
> 
> ```js
> <Tooltip title="tooltip title" style={{ alignItems: "flex-start" }}>
>   { /* Your child */ }
> </Tooltip>
> ```

There is no styles prop on tooltips (at least in 5.12.3).

**Comment by carlgieringer** [comment]
I had an error where the Tooltip container has `position: relative` within a Portal-like View that has `position: absolute; top: 0; right: 0; bottom: 0; left: 0` with the result that tooltip position, which is relative to the viewport, renders relative to the full page. I fixed it with this CSS:

```
        [data-testid="tooltip-container"] {
          position: fixed;
        }
```
