### ISSUE TITLE
how to bind bind event in Card.Cover？

### ISSUE THREAD

**Issue by Buzhifanji** [callstack/react-native-paper#4111]
### please tell me how to bind click event when card cover on click。

I'am try to do this. But, it did not work.

`    <Card.Cover
      onPress={onClick}
        source={{
          uri: 'https://img95.699pic.com/photo/50046/5562.jpg_wh300.jpg',
        }}
      />`

I tried according to the [official documentation](https://callstack.github.io/react-native-paper/docs/components/Card/)，it can work.
However，I don't know how to distinguish the card.title  card.content card.over。

can you tell me how to do it? Thank you so much

**Comment by lukewalczak** [comment]
I do not entirely understand your question, could you please elaborate more on it? What are you trying to accomplish? What do you mean by distinguishing the card component?

**Comment by Buzhifanji** [comment]
I'm very sorry, my description is not clear enough。

My question is how to bind the cover click event。

I want to do like this:

`
function demo() {
  // title event
  const onTitle = () => {
    console.log('onTitle');
  };

  // content event
  const onContent = () => {
    console.log('onContent');
  };

  // can you tell me how to bind onCover event
  const onCover = () => {
    console.log('onCover');
  };

  return (
    <Card>
      <Card.Title title={<Text onPress={onTitle}>title</Text>} />

      <Card.Content>
        <Text variant="bodyLarge" onPress={onContent}>
          content
        </Text>
      </Card.Content>

      {/* how to bind cover event ? */}
      <Card.Cover
        source={{
          uri: 'https://img95.699pic.com/photo/50046/5562.jpg_wh300.jpg',
        }}
      />
    </Card>
  );
}
`
