### ISSUE TITLE
Keyboard issue with TextInput inside DataTable.Cell

### ISSUE THREAD

**Issue by hgjura** [callstack/react-native-paper#4119]
I am trying to add a TextInput (from React  Native Paper) inside a DataTable Cell. However it seems to be a keyboard issue, as the keyboard shows when focusing on the TextInput but disappears after each keystroke. What would be desirable is keyboard showing when TextInput recives focus and dissappear when it loses focus (click somewhere else).

Is there a piece of code showing how to do this the right way? I feel I am not doing it right. I am noticing in iOS.

**Comment by lukewalczak** [comment]
The problem is the children passed to the `DataTable.Cell` is wrapped into the `Text` component. I will figure out how to handle that.
