### ISSUE TITLE
#feature-request Snackbar: multiple actions? multiple snackbars?

### ISSUE THREAD

**Issue by turtlegood** [callstack/react-native-paper#412]
### Current behaviour
1. The Snackbar only supports 1 action on the right.
2. If there are two Snackbars displaying at the same time, the last one will overlap all the others.

### Expected behaviour
1. I would appreciate it if you could allow us to customize more actions. For example, I hope I can have 2 actions.
2. I would appreciate it if those snackbars could be displayed side by side (instead of overlapping), just as Material Design suggests.

### Code sample
1. maybe `... actions=[{label: 'first', onPress: ...}, {label: '2nd', onPress: ...}]`
2. N/A

### Screenshots (if applicable)
N/A

### What have you tried
I have read the api https://callstack.github.io/react-native-paper/snackbar.html

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | N/A
| react-native          |N/A
| react-native-paper    |N/A
| node                  |N/A
| npm or yarn           |N/A

**THANK YOU VERY MUCH!!!** I like this project very much! Thank you for your hard work!

**Comment by satya164** [comment]
According to Material design guidelines, only one snackbar should be displayed at a time, and can contain a single action: https://material.io/design/components/snackbars.html

If you want to show multiple snackbars, you should show one, hide it, then show second one, hide it and so on.

**Comment by turtlegood** [comment]
OK. Thank you very much for your information and your quick reply!
