### ISSUE TITLE
DarkTheme question

### ISSUE THREAD

**Issue by Giorgio-Zarantonello** [callstack/react-native-paper#4120]
### Current behaviour
tried to call DarkTheme from react-native-paper/src/index.ts , but not found
### Expected behaviour
find DarkTheme in index.ts, as DefaultTheme 

### How to reproduce?
try to write a themes.js , import { DefaultTheme as PaperDefaultTheme, DarkTheme as PaperDarkTheme } from 'react-native-paper';
, DarkTheme is not accessable , so is not Overridable
```
// themes.js

import { DefaultTheme as PaperDefaultTheme, DarkTheme as PaperDarkTheme } from 'react-native-paper';

// Custom Light Theme
export const MyLightTheme = {
  ...PaperDefaultTheme,
  colors: {
    ...PaperDefaultTheme.colors,
    primary: 'blue',
    accent: 'orange',
  },
};

// Custom Dark Theme
export const MyDarkTheme = {
  ...PaperDarkTheme,
  colors: {
    ...PaperDarkTheme.colors,
    primary: 'purple',
    accent: 'yellow',
    // ...
  },
};

```

### What have you tried so far?
in index.tsx : 
```
export {
  useTheme,
  withTheme,
  ThemeProvider,
  DefaultTheme,
  DarkTheme,
  adaptNavigationTheme,
} from './core/theming';
```
in src/core/theming : 
```
export const DefaultTheme = MD3LightTheme;
export const DarkTheme = MD3DarkTheme;
```

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

i don't know if this is the correct way to override the DarkTheme , but using DefaultTheme was natural to me to include in the library also the same MD3Theme in theming 

feel free to say to me this is not the best way , i'm new to this library 

Thanks

**Comment by lukewalczak** [comment]
Hey @Giorgio-Zarantonello, currently from the library we are exporting the following themes:

### Material Design generation 2

```
MD2LightTheme
MD2DarkTheme
```

### Material Design generation 3 - Material You (_the latest available in v5.x.x_)

```
MD3DarkTheme
MD3LightTheme
```

and there is also exported `DefaultTheme` which is actually `MD3LightTheme`.

**Comment by Giorgio-Zarantonello** [comment]
Ok I understand, thank you
