### ISSUE TITLE
conflict between secureTextEntry & autoCapitalize

### ISSUE THREAD

**Issue by jkester1986** [callstack/react-native-paper#4121]
### Current behaviour

If I have a text field that is set to `secureTextEntry` being `true`, then I change it to false, `autoCapitalize` does not work. The characters stay lower-case

### Expected behaviour

Changing the value of `secureTextEntry` should not affect the behavior of `autoCapitalize`

### How to reproduce?

I tried creating a snack.expo.dev, but autoCapitalize doesn't seem to work on there at all, even when removing the other extra props. This is the code that would replicate the issue:

```
import { useState } from 'react';
import { TextInput } from 'react-native-paper';

export default function App() {
  const [ isFocused, setIsFocused ] = useState(true);

  return (
    <TextInput
      autoCapitalize="characters"
      secureTextEntry={!isFocused}
      onFocus={() => setIsFocused(true)}
      onBlur={() => setIsFocused(false)}
    />
  );
}
```
Then, when you tap on the input, the text entry gets changed to not be secure, and when you enter text it's all lower-case

### What have you tried so far?

Our current workaround is to capitalize the value prop every time the text in the input updates

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 15.5
| android                        | N/A
| react-native                | 0.71.11
| react-native-paper    | 4.12.1
| node                            | v18.14.2
| npm or yarn                | 1.22.19
| expo sdk                     | 48.0.9

**Comment by lukewalczak** [comment]
Could you please use `TextInput` from `react-native` to check whether the issue is related strictly to the library?

**Comment by jkester1986** [comment]
@lukewalczak it is - I'll open a but with them instead
