### ISSUE TITLE
tabBarColor is not working in @react-navigation/material-bottom-tabs and using react native paper

### ISSUE THREAD

**Issue by AjmirSarker** [callstack/react-native-paper#4129]
tabBarColor is not working in @react-navigation/material-bottom-tabs and using react native paper

 **<NavigationContainer>
      <Tab.Navigator
        shifting
        barStyle={{backgroundColor: 'lightblue'}}
        activeColor="green">
        <Tab.Screen
          name="Home"
          component={Home}
          options={{
            tabBarIcon: () => <Icon color="red" name="rocket" size={20} />,
            tabBarLabel: 'Home',
            tabBarColor: 'lightblue',
          }}
        />
        <Tab.Screen
          name="Profile"
          component={Profile}
          options={{
            tabBarIcon: () => <Icon name="rocket" size={20} />,
            tabBarColor: 'tomato',
          }}
        />
      </Tab.Navigator>
    </NavigationContainer>**

**Comment by lukewalczak** [comment]
Hey @AjmirSarker, if you are using with MD3 version, then the `tabBarColor` is not available (looks like I have to correct docs to mention about it), however if you are using MD2 version, then you need have specified prop `shifting={true}`:

<img width="715" alt="image" src="https://github.com/callstack/react-native-paper/assets/22746080/e60600ab-50e4-4b33-b403-90b10a381ede">

**Comment by lukewalczak** [comment]
Also, I recommend using `createMaterialBottomTabNavigator` from 'react-native-paper/react-navigation'.
