### ISSUE TITLE
TextInput not visible when disabled set to true 

### ISSUE THREAD

**Issue by Abhishek25031991** [callstack/react-native-paper#4136]
### Current behaviour
The textinput is not visible while textinput prop set to disabled true.
<img width="333" alt="Screenshot 2023-10-17 at 12 35 47 PM" src="https://github.com/callstack/react-native-paper/assets/105962635/b10ce62b-ba60-4818-9801-d81cfe9c33e4">

### Expected behaviour
The textinput should be visible and disabled(user can't edit) when disabled set to true.

### How to reproduce?
https://snack.expo.dev/J9gt8yfmB

### What have you tried so far?
I have set the enabled false than also it has the same issue

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 17
| android                        | 13
| react-native                | "0.70.13
| react-native-paper    | ^5.10.6
| node                            |8.17.0

**Comment by lukewalczak** [comment]
`TextInput` in the `disabled` state receives appropriate styles which makes it _dimmed_, please take a look at the official MD Figma:

* light theme:
<img width="586" alt="Zrzut ekranu 2023-10-17 o 12 40 12" src="https://github.com/callstack/react-native-paper/assets/22746080/acef018a-7d5a-47d8-bf29-1c7a4fdb7d75">

* dark theme:
<img width="598" alt="Zrzut ekranu 2023-10-17 o 12 40 46" src="https://github.com/callstack/react-native-paper/assets/22746080/44b45e82-f6f6-4331-a7e4-5e22c136631a">

**Comment by Abhishek25031991** [comment]
outlineColor={'red'}
activeOutlineColor={'red'}
and label color not working.
 

https://snack.expo.dev/6DJT48fRC
