### ISSUE TITLE
How do I set a component to be the secondary color?

### ISSUE THREAD

**Issue by lewibs** [callstack/react-native-paper#4138]
So I really have two questions:
1. How do I change a component such as Button to be the secondary theme color?
2. Can I make custom colors that can be used as well?

**Comment by lewibs** [comment]
Right now im doing something like this but that seems to change the internal children dimensions:

```
import { DefaultTheme, Provider as PaperProvider, useTheme } from 'react-native-paper';
import useColors from './useColors';
import {View} from "react-native";

const theme = {
    ...DefaultTheme,
    colors: {
        ...DefaultTheme.colors,
    }
}

export function ThemeProvider({children}) {
    return( 
        <PaperProvider theme={theme}>
            {children}
        </PaperProvider>
    );
}

//to be used internally
export function Color({children, primary, status}) {
    const theme = useTheme();
    //If you need a second color then add secondary
    primary = useColors({color: primary, status});

    if (primary) {
        primary = {
            primary: primary?.main, // Your primary color
            onPrimary: primary?.contrastText, // Text color on the primary background
            primaryContainer: primary?.dark, // Background color for primary container
            onPrimaryContainer: primary?.contrastText, // Text color on the primary container background
        }
    }

    return(
        <PaperProvider
            theme={{
                ...theme,
                colors: {
                    ...theme.colors,
                    ...primary,
                }
            }}
        >
            {children}
        </PaperProvider>
    );
}
```

**Comment by lukewalczak** [comment]
> How do I change a component such as Button to be the secondary theme color?

You need to check which theme colors are used internally in `Button` component and override them using `theme` property. 
Docs: https://callstack.github.io/react-native-paper/docs/guides/theming#customizing-all-instances-of-a-component

> Can I make custom colors that can be used as well?

Yes, you can extend the theme with your custom colors and then use them accessing the theme e.g. `theme.colors.customColor`
Docs: https://callstack.github.io/react-native-paper/docs/guides/theming#extending-the-theme
