### ISSUE TITLE
BaseRoute is not exported

### ISSUE THREAD

**Issue by Lev-Shapiro** [callstack/react-native-paper#4145]
Why isn't the BaseRoute type in BottomNavigation component exported? 

I want to have my state of routes to include a type so that it would be easier to work with it, but it seems that there is no available option to import this type, should it be fixed or there is a specific reason why it wasn't exported?

If that's the first option - I'll be more than happy to create a pull request to fix this

**Comment by lukewalczak** [comment]
Sure, we can export it.
