### ISSUE TITLE
Can’t read property 'week' of undefined   this error is located at : statistic...

### ISSUE THREAD

**Issue by imorakzai** [callstack/react-native-paper#4147]
<img width="418" alt="Screenshot 2023-10-22 at 5 38 57 PM" src="https://github.com/callstack/react-native-paper/assets/72260607/20dd11e5-1bf8-4672-8b50-9e141064dfed">

### this is my timer screeen
`import React, { useState, useEffect } from "react";
import { Image, View, Button, Text } from "react-native";
import TextStyle from "../constants/style/TextStyle";
import ProgressCircle from "react-native-progress-circle";
import { Vibration } from 'react-native';

const formatTime = (seconds) => {
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  return `${minutes}:${remainingSeconds < 10 ? "0" : ""}${remainingSeconds}`;
};

const Timer = () => {
  const focusDuration = 30 * 60; // 30 minutes in seconds
  const breakDuration = 5 * 60; // 5 minutes in seconds
  const [isRunning, setIsRunning] = useState(false);
  const [isPaused, setIsPaused] = useState(false);
  const [isFocusTime, setIsFocusTime] = useState(true);
  const [currentPhase, setCurrentPhase] = useState('focus'); // 'focus' or 'break'
  const [elapsedSeconds, setElapsedSeconds] = useState(0);
  const [remainingTime, setRemainingTime] = useState(focusDuration); // Initial value should be focusDuration

  // Add a state to store the timer usage data
  const [usageData, setUsageData] = useState({
    week: 0, // Time spent this week in seconds
    today: 0, // Time spent today in seconds
    month: 0, // Time spent this month in seconds
  });

  useEffect(() => {
    let interval;

    if (isRunning && !isPaused) {
      interval = setInterval(() => {
        setElapsedSeconds((prevSeconds) => {
          if (prevSeconds >= remainingTime) {
            clearInterval(interval);
            setIsRunning(false);
            setIsPaused(false);

            if (currentPhase === 'focus') {
              setCurrentPhase('break');
              setElapsedSeconds(0);
              setRemainingTime(breakDuration);
              setIsFocusTime(false); // Set isFocusTime to false for the break period
            } else {
              setCurrentPhase('focus');
              setElapsedSeconds(0);
              setRemainingTime(focusDuration);
              setIsFocusTime(true); // Set isFocusTime to true for the focus period
            }

            // Automatically start the timer for the next phase
            setIsRunning(true);

            // Vibrate 3 times during break time
            if (currentPhase === 'break') {
              for (let i = 0; i < 3; i++) {
                setTimeout(() => {
                  Vibration.vibrate(500);
                }, i * 1000);
              }
            }

            // Update the usage data based on the current phase
            setUsageData((prevData) => ({
              ...prevData,
              week: currentPhase === 'focus' ? prevData.week + focusDuration : prevData.week + breakDuration,
              today: currentPhase === 'focus' ? prevData.today + focusDuration : prevData.today + breakDuration,
              month: currentPhase === 'focus' ? prevData.month + focusDuration : prevData.month + breakDuration,
            }));

            /////////

          } else {
            return prevSeconds + 1;
          }
        });
      }, 1000);
    } else {
      clearInterval(interval);
    }

    return () => {
      clearInterval(interval);
    };
  }, [isRunning, isPaused, currentPhase, remainingTime]);

  const handleStart = () => {
    setIsRunning(true);
    setIsPaused(false);
  };

  const handlePause = () => {
    setIsPaused(true);
  };

  const handleResume = () => {
    setIsPaused(false);
  };

  const handleCancel = () => {
    setIsRunning(false);
    setIsPaused(false);
    setElapsedSeconds(0);
  };

  const maxDuration = isFocusTime ? focusDuration : breakDuration;
  const animationPercentage = (elapsedSeconds / maxDuration) * 100;

  return (
    <View style={TextStyle.container}>
      <View style={TextStyle.threeLines} >
        <Image source={require('../assets/ThreeLines.png')} ></Image>
      </View>

      <View style={TextStyle.blackCircleImage} >
        <View style={TextStyle.outerCircle}>
          <ProgressCircle
            percent={100 - animationPercentage}
            radius={150}
            borderWidth={2}
            color="#fff"
            shadowColor='#000'
            bgColor="#000"
            rotation={90}
            clockwise={false}
          >
            <Text style={TextStyle.timeText}>
              {formatTime(maxDuration - elapsedSeconds)}
            </Text>
            <Text style={TextStyle.focusText}>
              {isFocusTime ? 'FOCUS' : 'BREAK'}
            </Text>
          </ProgressCircle>

        </View>
      </View>

      <View style={TextStyle.buttonStartView}>
        {!isRunning && (
          <Button color={'#fff'} title="START" onPress={handleStart} />
        )}
        {isRunning && !isPaused && (
          <>
            <Button color={'#fff'} title="PAUSE" onPress={handlePause} />
            <Button color={'#fff'} title="STOP" onPress={handleCancel} />
          </>
        )}
        {isRunning && isPaused && (
          <>
            <Button color={'#fff'} title="RESUME" onPress={handleResume} />
            <Button color={'#fff'} title="STOP" onPress={handleCancel} />
          </>
        )}
      </View>

      <View style={TextStyle.bottomText}>
        <Text style={TextStyle.bottomTimeText}>
          <Text style={TextStyle.smallText}>Focus{'\n'}</Text>
          {formatTime(focusDuration)}{'\n'}
          <Text style={TextStyle.smallText}>Break{'\n'}</Text>
          {formatTime(breakDuration)}
        </Text>
        {/* <Text style={TextStyle.bottomRemainingTime}>
          {currentPhase === 'focus' ? `Focus: ${formatTime(remainingTime)}` : `Break: ${formatTime(remainingTime)}`}
        </Text> */}
      </View>
      {/* <Stats usageData={usageData} /> */}

    </View>
  )
}

export default Timer`
### this my Statistic Screen
`import React from 'react';
import { View, Text } from 'react-native';

const formatTimeInHoursMinutes = (seconds) => {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  return `${hours}h ${minutes}m`;
};

const Statistic = ({ usageData }) => {
    return (
      <View>
        <Text>Stats</Text>
        <Text style={{ color: 'black' }}>This Week: {formatTimeInHoursMinutes(usageData.week)} </Text>
        <Text style={{ color: 'black' }}>Today: {formatTimeInHoursMinutes(usageData.today)} </Text>
        <Text style={{ color: 'black' }}>This Month: {formatTimeInHoursMinutes(usageData.month)} </Text>
      </View>
    );
  }
  

export default Statistic`
### this is my Stats Screen
`import React from 'react';
import { View } from 'react-native';
import Statistic from './Statistic';

const Stats = ({ usageData }) => {
  return (
    <View>
     <Statistic usageData={usageData} />
    </View>
  );
}

export default Stats;
`

**Comment by lukewalczak** [comment]
Hey @imorakzai, I'm closing your issue, since it's not related to the `react-native-paper` library – I can't see any component from the library to be used in the code your provided.

However, the error screen presented on the screenshot typically indicates that you are trying to access a property called 'week' on an object that is undefined, so I would suggest identifying where this property is being accessed and ensuring that the object it is trying to access it on is defined.

**Comment by imorakzai** [comment]
i have solved this issue but it was not `react-native-paper` it didn’t said that is `react-native-paper` issue.
