### ISSUE TITLE
How to make a bottom appbar work with Android 14's transparent nav bar?

### ISSUE THREAD

**Issue by Crissium** [callstack/react-native-paper#4152]
### Ask your Question

I have an appbar positioned at the bottom of the screen, and below is the code:

```jsx
<View style={{ flex: 1 }}>
	<ArticleView />
	<ArticleBottomBar />
</View>
```

```jsx
<Appbar>
	<View style={{ flex: 1, flexDirection: 'row', justifyContent: 'space-between' }}>
		<TextInput />
		<Appbar.Action />
		<Appbar.Action />
		<Appbar.Action />
	</View>
</Appbar>
```

Before the transparent nav bar was introduced, the appbar was positioned just above the nav bar. Now below the appbar there is still a strip of space which I guess is meant for the nav bar. A screenshot clarifies what I mean:

![5026448038084740082_683267670](https://github.com/callstack/react-native-paper/assets/91039086/eadc1ab3-d5fc-44ec-87f0-35f8786afbeb)

While in this screenshot taken from https://www.xda-developers.com/android-14-transparent-navigation-bar/ , this space disappears.

![screenshot](https://static1.xdaimages.com/wordpress/wp-content/uploads/2023/04/android_14_beta_1_transparent_navigation_bar_comparison.png)

So how should I remove this annoying bit?

**Comment by lukewalczak** [comment]
Hey @Crissium, please check the [issue](https://github.com/callstack/react-native-paper/issues/4090) where I explained everything.

**Comment by Crissium** [comment]
> Hey @Crissium, please check the issue where I explained everything.

Thanks! Now I understand.
