### ISSUE TITLE
Web Build Error: Unable to resolve "../Utilities/Platform" from "node_modules/react-native/Libraries/ReactNative/PaperUIManager.js"

### ISSUE THREAD

**Issue by jrobber** [callstack/react-native-paper#4156]
### Current behavior
When including  `<PaperProvider` in the root of my expo appI get the following error:
`Unable to resolve "../Utilities/Platform" from "node_modules/react-native/Libraries/ReactNative/PaperUIManager.js"`

### Expected behavior
The project finishes web bundling

### How to reproduce?
Create an expo project (https://docs.expo.dev/workflow/web/)
Enable metro as the build tool (https://docs.expo.dev/guides/customizing-metro/)
Add Paper
`expo start` 
Press `w` in the terminal to open the web build

### What have you tried so far?
Looked into the issue, and there is a `node_modules/react-native/Libraries/Utilities/Platform.ios.js` and a `node_modules/react-native/Libraries/Utilities/Platform.android.js`, but there is no Platform.js so it fails when trying to build on web

I'm at a loss of what to try.  I see other issues on here by people successfully running paper on expo 49, but I'm not sure how it works for them at all.  I'm not aware of build settings to replace files that don't exist.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | n/a
| android                        | n/a
| react-native                | 0.72.3
| react-native-paper    | ^5.11.1
| node                            | 18.16.0
| npm or yarn                | pnpm
| expo sdk                     | 49

**Comment by jrobber** [comment]
Tracked this down, is not actually react-native-paper.

**Comment by revolution42** [comment]
> Tracked this down, is not actually react-native-paper.

What was the cause of the issue I am getting the same thing

**Comment by Drzaln** [comment]
Hi @jrobber 
can you share how to fix it? I'm getting same error
