### ISSUE TITLE
Close Button on Searchbar

### ISSUE THREAD

**Issue by mmor93** [callstack/react-native-paper#416]
### Current behaviour

I'm using Searchbar component of your library.
I request to an API on clicking the searchbar icon

### Expected behaviour

I want to clear searchValue state variable on clicking the close button on searchbar
what should i do?

**Comment by Trancever** [comment]
Hi, @mmor93 You should just set your variable in state to empty string inside onIconPress callback. Does it work for you?

**Comment by mmor93** [comment]
@Trancever 
i will trigger the search function by onIconPress so i cant set my state to empty. i want to click on close button and set my state to empty.

**Comment by Trancever** [comment]
Ok, so set this variable to empty inside onPress callback of button.

**Comment by mmor93** [comment]
@Trancever 
i cant because there is no props such onClosePress for Searchbar just onIconPress

**Comment by satya164** [comment]
Use `onChangeText` callback.
