### ISSUE TITLE
Primary colour is is correct when generating a theme with DynamicColorTheme.tsx

### ISSUE THREAD

**Issue by richardhensman123** [callstack/react-native-paper#4161]
### Current behaviour
When I enter a primary colour of (for example) #1764C0 I expect the the primary colour in the source to be this colour, however I get the colour rgb(2, 93, 184) not rgb(23, 100, 192) as expected.

### Expected behaviour
Primary colour should be rgb(23, 100, 192) (the RGB value for #1764C0.

**Comment by lukewalczak** [comment]
The source color passed to the generator is used as a base for creating color palette, but it won't be the `primary` color. As you can notice on the screenshot below, passed color is fed into an algorithm to create a color scheme.

<img width="474" alt="image" src="https://github.com/callstack/react-native-paper/assets/22746080/514c1706-7a38-469d-8c4a-8540a54f8dcf">

 The color generator available in Paper documentation is based on the same algorithms as [Material Theme builder](https://m3.material.io/theme-builder#/custom), where you can pass your color (`#1764C0`) and observe similar results.
