### ISSUE TITLE
How to make Dialog backdrop fill the status bar

### ISSUE THREAD

**Issue by saikat0511** [callstack/react-native-paper#4162]
Dialog backdrops in native apps fill the whole screen behind including the status bar, for example in Play Store
[Screencast from 2023-10-31 16-30-03.webm](https://github.com/callstack/react-native-paper/assets/57610828/c5c3b943-9cf1-4cdc-ba60-514c0fdaf32c)

But it isn't doing that in my app...
[Screencast from 2023-10-31 16-35-18.webm](https://github.com/callstack/react-native-paper/assets/57610828/5680608f-f721-4fac-9404-28b73fca8c41)

My component structure looks like this...
```
<AuthContextProvider>
  <StatusBar
    barStyle={isDarkMode ? 'light-content' : 'dark-content'}
    backgroundColor={theme.colors.background}
  />
  <PaperProvider theme={theme}>
    . . .
  </PaperProvider>
</AuthContextProvider>
```
Any idea how to fix this?

**Comment by saikat0511** [comment]
Fixed it.
Turns out the default react native cli "AwesomeProject" settings doesn't allow rendering content in the area under status bar and navbar.

To allow full screen layout edit the override in `android/app/src/main/java/com/<appName>/MainActivity.java`
```
. . .
import androidx.core.view.WindowCompat;
. . .
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(null);
    WindowCompat.setDecorFitsSystemWindows(getWindow(), false);
. . .
```

This will make allow rendering content under the navbar and status bar, but the status bar is still translucent and navbar is solid black. Make them transparent by adding two styles in `android/app/src/main/res/values/styles.xml`
```
. . .
        <item name="android:navigationBarColor">@android:color/transparent</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
. . .
```
We also need to set the status bar style according to current color scheme else the contents will be invisible in light mode. Add the StatusBar somewhere inside the root component:
```
<StatusBar
    barStyle={isDarkMode ? 'light-content' : 'dark-content'}
    backgroundColor="transparent"
/>
```
Now the Dialog backdrop should work as expected! Make sure to use SafeAreaViews to render content inside the user accessible boundaries.

**Comment by Energieman** [comment]
You dont need to mess with native code for what can be easily done with rn StatusBar Builtin component

<StatusBar translucent={true}
    barStyle={1==2 ? 'light-content' : 'dark-content'}
    backgroundColor="transparent"
/>
