### ISSUE TITLE
Text input floating label background design issue on focus

### ISSUE THREAD

**Issue by nabajyotimitra2015** [callstack/react-native-paper#4164]
Please help me to solve the design issue of the text input. 

![Screenshot_20231101_005132_Medical CRM](https://github.com/callstack/react-native-paper/assets/47151783/fae2ad13-dcd5-44a6-a856-97247f9726aa)

`<TextInput
                label={label}
                value={value}
                placeholder={placeholder}
                secureTextEntry={!!secureTextEntry ? secureTextEntry : false}
                onChangeText={text => onChangeText(text)}
                mode="outlined"
                outlineColor={Colors.textInputOutlineColor}
                activeOutlineColor={Colors.textInputOutlineColor}
                textColor={Colors.blackColor}
                style={{
                    //backgroundColor: 'transparent',
                    width: '100%',
                    fontFamily: 'Poppins-Regular',
                    fontSize: responsiveFontSize(1.6),
                    color: Colors.blackColor
                }}
            />`

**Comment by kamilcessak0** [comment]
I have the same problem after updating expo to 49 and rn to 0.72.6
