### ISSUE TITLE
RadioButton.Item Touchable Effect

### ISSUE THREAD

**Issue by tahahaz1374** [callstack/react-native-paper#4165]
Hi there , How to change RadioButton.Item touchable Effect (Ripple color ) when press on it 
I mean grey background color when press on it .
`"react-native-paper": "^4.9.2",`
`"react-native": "0.64.4"`,
`"react-native-vector-icons": "^8.1.0"`

**Comment by lukewalczak** [comment]
It's possible from version 5.11.2.
