### ISSUE TITLE
Entered text and label in the `TextInput` with long `label` value does not fit the width of the input

### ISSUE THREAD

**Issue by irekrog** [callstack/react-native-paper#4168]
### Current behaviour
Entered text and label in the `TextInput` with long `label` value does not fit the width of the input.

### Expected behaviour
The label and entered text should fit the width of the input.

### How to reproduce?
https://snack.expo.dev/@irekrog/hell?platform=ios

### Preview
https://github.com/callstack/react-native-paper/assets/11172548/f2a08142-8e5d-4f60-b123-6706cdfa7579

### What have you tried so far?
I was trying to change the values of `width` and `minWidth` to temporary constant values here:
* https://github.com/callstack/react-native-paper/blob/main/src/components/TextInput/Label/InputLabel.tsx#L135
* https://github.com/callstack/react-native-paper/blob/main/src/components/TextInput/TextInputOutlined.tsx#L385

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 17
| android                        | 12
| react-native                | 0.72.6
| react-native-paper    | 5.11.1
| node                            | 18
| npm or yarn                | 1.2.29
| expo sdk                     | 49

**Comment by badalsaibo** [comment]
Can confirm this bug. What it should do at the least is to show ellipsis and not overflow the parent container.
