### ISSUE TITLE
Fab.Group not working (this.props.manager.mount)

### ISSUE THREAD

**Issue by nazrdogan** [callstack/react-native-paper#417]
### Current behaviour
![simulator screen shot - iphone x - 2018-06-10 at 17 39 11](https://user-images.githubusercontent.com/1672303/41202691-afbeee1c-6cd5-11e8-945c-6f82e098089e.png)

### Expected behaviour
 
![image](https://user-images.githubusercontent.com/1672303/41202694-bc146fde-6cd5-11e8-8fd8-f4575cd15576.png)

### Code sample
 <View style={{ flex: 1 }}>

        <MapView
          followsUserLocation={true}
          showsMyLocationButton={true}
          style={{ ...StyleSheet.absoluteFillObject }}
        />
        <FAB.Group
          open={this.state.open}
          icon={this.state.open ? 'today' : 'add'}
          actions={[
            { icon: 'add', onPress: () => { } },
            { icon: 'star', label: 'Star', onPress: () => { } },
            { icon: 'email', label: 'Email', onPress: () => { } },
            { icon: 'notifications', label: 'Remind', onPress: () => { } },
          ]}
          onStateChange={({ open }) => this.setState({ open })}
          onPress={() => {
            if (this.state.open) {

            }
          }}
        />
      </View>

### Your Environment
I get example from there : #https://3071-71323749-gh.circle-artifacts.com/0/docs/fab-group.html

| software              | version
| --------------------- | -------
| ios or android        | ios 11
| react-native          | expo 27
| react-native-paper    | ^2.0.0-alpha.5
| node                  | 8.9.4
| npm or yarn           | npm 6

**Comment by Trancever** [comment]
@nazrdogan Hey, did you wrap your root component with Provider component from Paper?

**Comment by nazrdogan** [comment]
@Trancever  . nope. Some component works well without Provider.  but tried with Provider its working now. but Another issue I have :) I used tabnavigation. 
its seems over tab nav. is there any trick for this ?
![simulator screen shot - iphone x - 2018-06-10 at 18 29 48](https://user-images.githubusercontent.com/1672303/41203182-4834664e-6cdc-11e8-833c-31d48e0a1a69.png)

**Comment by Trancever** [comment]
Yeah, some of the components work without Provider, but it's good pattern to use it all the time so you will not encounter such problems in future.
Regarding position of FAB button, I think there is no option to change it right now :/ @satya164 @lukewalczak Is there any way to change position?

**Comment by satya164** [comment]
Yeah, we need to support a `style` prop.

**Comment by YashGadle** [comment]
For the TabNavigator, is there any workaround currently? I need to use this FABGroup in my current project. It is kind of urgent.

**Comment by Trancever** [comment]
There is no workaround but I opened PR that will make it possible to pass style prop to FABGroup - #419 . So once it's merged there will be option to change FABGroup position.

**Comment by satya164** [comment]
I published new releases with the change. Now you should be able set a bottom margin with the `style` prop.

**Comment by nazrdogan** [comment]
@satya164 How can reach latest docs ?

**Comment by satya164** [comment]
@nazrdogan check the link here: https://github.com/callstack/react-native-paper/pull/371

**Comment by YashGadle** [comment]
In your example expo app, the FABGroup is only present in the 'FAB Screen'. And it disappears when you navigate to the previous screen. But in my app, the FABGroup is only rendered on 1 of my screens but it persists on all of my screens. Am I missing something or do I need to handle this via state?

**Comment by satya164** [comment]
@YashGadle since `TabNavigator` doesn't unmount a screen when you navigate away, you'll need to manage when the FAB Group is rendered by using focus listeners: https://reactnavigation.org/docs/en/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

**Comment by YashGadle** [comment]
Thank you @satya164 !!

**Comment by satya164** [comment]
Opened an issue to think about how we can do this automatically: https://github.com/callstack/react-native-paper/issues/420

**Comment by YashGadle** [comment]
I tried to handle the FABGroup visibility using the Focus listeners provided by react-navigation, but it's not working properly. I have used 'willBlur' and 'willFocus' in my HomeScreen Tab to change the visibility of my FABG. I am also using context API for this to handle the state globally.
My structure is like this:-
const root = createStackNavigator({
    tabs: TabNavigator with 5 screens
    notabscreen1: StackNavigator
    notabscreen2: StackNavigator
});

Now when I render my Home Screen Tab the FABG shows up, and when I navigate to notabscreen1, the FABG disappears, but after I come back to my HomeScreen Tab it won't work anymore. The focus listeners are not called.

**Comment by tkorakas** [comment]
Focus listeners worked for me. I used willBlur and willFocus to render or not the FAB button.

**Comment by thebergamo** [comment]
Would you guys provide any example to workaround this?

**Comment by RemyMachado** [comment]
Not rendering the FAB with the `withNavigationFocus` workaround is a problem when we navigate back, because it doesn't appear back instantly.

Is there a way to hide the FAB but to keep it rendered for smoothness purposes ?
