### ISSUE TITLE
Change icon for badge

### ISSUE THREAD

**Issue by LVExMachina** [callstack/react-native-paper#4174]
Hi there, can i use a different icon for `Badge` component? For example a heart icon?
I used in my project a `View` component with absolute position to do the same and the result is the following:

![telegram-cloud-photo-size-2-5361591264430115993-m](https://github.com/callstack/react-native-paper/assets/149154549/25e447de-b7e7-4fd5-bf9b-dee1768c572b)

Thank you!

**Comment by lukewalczak** [comment]
Hey @LVExMachina, there is no such option, since in the MD the `Badge` component has always round or pill shape.
