### ISSUE TITLE
`placeholderTextColor` is ignored for TextInputOutlined

### ISSUE THREAD

**Issue by jahirfiquitiva** [callstack/react-native-paper#4175]
### Current behaviour
`placeholderTextColor` is ignored for TextInputOutlined

In [lines 99-114](https://github.com/callstack/react-native-paper/blob/aebeabd8769988b17bb56b0f5673f252e1bda0d9/src/components/TextInput/TextInputOutlined.tsx#L106) the `placeholderColor` property which is result from calling `getOutlinedInputColors` does not take the `placeholderTextColor` prop into consideration, which should be used to override the default label text color

```typescript
  const {
    inputTextColor,
    activeColor,
    outlineColor,
    placeholderColor,
    errorColor,
    selectionColor,
  } = getOutlinedInputColors({
    activeOutlineColor,
    customOutlineColor,
    customSelectionColor,
    textColor,
    disabled,
    error,
    theme,
  });
```

### Expected behaviour
`placeholderTextColor` should be used as the label text color in outlined TextInput

**Comment by jahirfiquitiva** [comment]
If possible, for the outlined TextInput, it might be even better to have `labelTextColor` and `activeLabelTextColor` so that we can customize the label text colors in both states

**Comment by lukewalczak** [comment]
Hey @jahirfiquitiva, `placeholderTextColor` is properly [applied](https://github.com/callstack/react-native-paper/blob/aebeabd8769988b17bb56b0f5673f252e1bda0d9/src/components/TextInput/TextInputOutlined.tsx#L361) to the outlined text input. I've created a [snack](https://snack.expo.dev/@react-native-paper/textinput-with-green-placeholder) where set `green` placeholder and it's properly displayed.

**Comment by jahirfiquitiva** [comment]
@lukewalczak Sorry, I meant that it didn't change the label color as that placeholderTextColor is not used for the label.

https://github.com/callstack/react-native-paper/blob/aebeabd8769988b17bb56b0f5673f252e1bda0d9/src/components/TextInput/TextInputOutlined.tsx#L222C5-L222C21

That's why in the next comment I mentioned the possibility of having `labelTextColor` and `activeLabelTextColor` so that we can customize the label text colors in both states.

Thanks in advance!
