### ISSUE TITLE
[PROPOSAL] TextInput Error Messages

### ISSUE THREAD

**Issue by davidpn11** [callstack/react-native-paper#418]
I'm missing the possibility to add an error message to a text input. When the error prop is true, it displays a custom error message to the user, that was passed by an errorMessage prop or something like that.

The UI whould looks like this:
![error](https://user-images.githubusercontent.com/5813202/41230420-26d7d894-6d56-11e8-9187-4bec090c97cf.PNG)

**Comment by satya164** [comment]
You can use [`HelperText`](https://callstack.github.io/react-native-paper/helper-text.html) for the error message.

**Comment by davidpn11** [comment]
Great!
Sorry. I didn't checked this component.
