### ISSUE TITLE
Accessing font `variants` not finding custom variant names within theme object

### ISSUE THREAD

**Issue by lucksp** [callstack/react-native-paper#4181]
### Current behaviour

Our design system has more font variant names than the default `MD3TypescaleKey` values.

I followed [the directions to create a custom font variant](https://callstack.github.io/react-native-paper/docs/guides/fonts/#using-configurefonts-helper-1) including using a `customText()` component by manually adding a union of variant names.

However, TS is not picking up the variant name when trying to access `theme.fonts.myCustomVariant`.  

### Expected behaviour

Extending the font variants would be found based on TS Definition when `configFonts()` is implemented as per documentation.

### How to reproduce?

1. Define custom font stack:
```
import { TextStyle } from 'react-native';
import { configureFonts } from 'react-native-paper';

const Inter_400Regular = 'Inter_400Regular';
const Inter_500Medium = 'Inter_500Medium';
const Inter_600SemiBold = 'Inter_600SemiBold';
const Inter_700Bold = 'Inter_700Bold';
const Lora_700Bold = 'Lora_700Bold';

const FontWeight = {
    100: '100',
    200: '200',
    300: '300',
    400: '400',
    500: '500',
    600: '600',
    700: '700',
    800: '800',
    900: '900',
} as const

type FontConfig = {
    [T: string]: TextStyle;
};

const fontConfig: FontConfig = {
    bodyXS: {
        fontFamily: Inter_500Medium,
        fontSize: 10,
        fontWeight: FontWeight[500],
        letterSpacing: 1,
        lineHeight: 14,
    },
    bodySmall: {
        fontFamily: Inter_500Medium,
        fontSize: 12,
        fontWeight: FontWeight[500],
        letterSpacing: 0,
        lineHeight: 16,
    },
    headlineXL: {
        fontFamily: Lora_700Bold,
        fontSize: 32,
        fontWeight: FontWeight[700],
        letterSpacing: -1,
        lineHeight: 40,
    },
    button: {
        fontFamily: Inter_600SemiBold,
        fontSize: 14,
        fontWeight: FontWeight[600],
        letterSpacing: -1,
        lineHeight: 20,
    },
    inputLabel: {
        fontFamily: Inter_500Medium,
        fontSize: 14,
        fontWeight: FontWeight[500],
        letterSpacing: -1,
        lineHeight: 20,
    },
};

export const fonts = configureFonts({
    config: { ...fontConfig },
});
```
2. Add fonts to theme:
```
const theme = {
  ...PaperDefaultTheme,
  fonts
}
```
3. Access `fonts.button` from `useTheme` hook:
```
    const theme = useCustomTheme();
    const headerTitleStyle = {
        color: theme.colors.gray[800],
        fontSize: 16,
        fontFamily: theme.fonts.button,
```

### Preview

<img width="615" alt="image" src="https://github.com/callstack/react-native-paper/assets/15162169/c4f843a4-112a-40e4-8c6c-4e615e8bcb03">

any custom variant not found with our custom variant config.

### What have you tried so far?

1. I tried creating a new `react-native-paper.d.ts` file to extend or override the [MD3TypescaleKey](https://github.com/callstack/react-native-paper/blob/aebeabd8769988b17bb56b0f5673f252e1bda0d9/src/types.tsx#L145)  in the root of my project:

```
import 'react-native-paper';

declare module 'react-native-paper' {
    export const enum MD3TypescaleKey {
        default = 'default',

        bodyXS = 'bodyXS',
        bodySmall = 'bodySmall',
        bodyMedium = 'bodyMedium',
        bodyLarge = 'bodyLarge',

        bodyXSBold = 'bodyXSBold',
        bodySmallBold = 'bodySmallBold',
        bodyMediumBold = 'bodyMediumBold',
        bodyLargeBold = 'bodyLargeBold',

        titleXS = 'titleXS',
        titleSmall = 'titleSmall',
        titleMedium = 'titleMedium',
        titlelarge = 'titlelarge',

        headlineXS = 'headlineXS',
        headlineSmall = 'headlineSmall',
        headlineMedium = 'headlineMedium',
        headlineLarge = 'headlineLarge',
        headlineXL = 'headlineXL',

        displaySmall = 'displaySmall',
        displayMedium = 'displayMedium',
        displayLarge = 'displayLarge',

        button = 'button',

        inputLabel = 'inputLabel',
    }
}
```
However it's not working.  Maybe because an enum, but now all other references to the library, such as `import { Card } from 'react-native-paper'` are failing due to `Card` not being exported: 
> Module '"react-native-paper"' has no exported member 'Card'.ts(2305)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 17.1
| react-native                | 0.71.8
| react-native-paper    | ^5.8.0
| node                            | 16
| npm or yarn                | yarn
| expo sdk                     | 48

**Comment by lukewalczak** [comment]
Thanks @DimitarNestorov, closing the issue.
