### ISSUE TITLE
Is it possible to use our own icons along with react-native-paper components

### ISSUE THREAD

**Issue by Yandamuri** [callstack/react-native-paper#4182]
### Ask your Question

This is from `react-native-paper` documents

> Many of the components require the [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) library to render correctly.

and here is an example
```
<Button icon="camera" mode="contained" onPress={() => console.log('Pressed')}>
    Press me
</Button>
```

Is it possible to use our own icons like `svg`?

**Comment by cicerotcv** [comment]
I think it would be great if we could use it like this:

```tsx
<Button 
  icon={({color, ...somethingElse}) => (
    <MyIcon  color={color} size={size} {...somethingElse} />
  )}
  mode="contained"
  textColor="red"
  onPress={() => console.log('Pressed')}
>
    Press me
</Button>
```

**Comment by lukewalczak** [comment]
Yes it's possible and everything is described on the docs page within the [icons guide](https://callstack.github.io/react-native-paper/docs/guides/icons).
