### ISSUE TITLE
Snackbar Action Button - Cannot Correctly Display Text Size Larger Than 14 in iOS 

### ISSUE THREAD

**Issue by leons1767** [callstack/react-native-paper#4187]
### Current behaviour
In RNP 5.11.1, when the action label fontSize is bigger than 14, it couldn't be displayed in full. Increasing the height in labelStyle and set `textAlignVertical: 'center'` can solve the problem in Android, but iOS does not support textAlignVertical.

In React Native Paper 4.9.x, no manual adjustment is necessary when increasing the fontSize of the action label

### Expected behaviour
Able to display fontSize > 14 in iOS

### How to reproduce?
https://snack.expo.dev/@ad9889/snackbar-action-button-text

### Preview
See snack example

### What have you tried so far?
`labelStyle: { fontSize: 32, height: 50, textAlignVertical: 'center' }`, but it only works for Android

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 17
| android                        | 13
| react-native                | 0.72.6
| react-native-paper    | 5.11.1
| node                            | 18.16.0
| npm or yarn                | 1.22.19
| expo sdk                     | 49.0.0

**Comment by lukewalczak** [comment]
Please try to also set appropriate `lineHeight` for the action label.

**Comment by leons1767** [comment]
Thanks @lukewalczak, setting lineHeight sovles the issue. As there is no variant props here, I would expect the lineHeight to scale automatically following the fontSize, like in web. Also, there is no such problem with Text that has a variant prop.

Setting lineHeight doesn't work with TextInput left and right prop. I mean the value is always misaligned with left and right Text.Affix of TextInput. I have to add a manual paddingTop to the Text.Affix textStyle prop, to get it aligned with the value.

lineHeight appears to be a problem in most components if not all. Do you plan to do something about it?

**Comment by lukewalczak** [comment]
> Setting lineHeight doesn't work with TextInput left and right prop. I mean the value is always misaligned with left and right Text.Affix of TextInput. I have to add a manual paddingTop to the Text.Affix textStyle prop, to get it aligned with the value.

lineHeight appears to be a problem in most components if not all. Do you plan to do something about it?

Please share the expo snack
