### ISSUE TITLE
How can I use the `ActivitiIndicator` as a `RefreshControl` on a `FlatList`?

### ISSUE THREAD

**Issue by pvinis** [callstack/react-native-paper#4212]
Basically that. Can I? When I try to do that, I get errors about the view being more than one or something.

**Comment by lukewalczak** [comment]
Hey @pvinis, yes it should be possible. Please create the expo snack with your code, so I will try to assist you.

**Comment by pvinis** [comment]
Here you go.
https://snack.expo.dev/@cointracker/tactless-yellow-nachos
This is what I see with this, and Im not sure how to make this work.
![Screenshot 2023-12-11 at 15 33 18](https://github.com/callstack/react-native-paper/assets/100233/21fe48e0-5fff-4cdc-be8c-cd67118fb9a9)

An example would be super useful, thanks!

**Comment by pvinis** [comment]
I see. As expected, it doesnt really work on your example. The "pull to refresh" drag is literally a 1 pixel pull, which is obviously not even close to the right UX.

I will look at the code to see if I can make it work similarly to the RefreshControl.
