### ISSUE TITLE
Missing animated progress bar from snack examples

### ISSUE THREAD

**Issue by WillSmithTE** [callstack/react-native-paper#4216]
### Current behaviour
The [examples repo](https://github.com/callstack/react-native-paper/blob/main/example/src/Examples/ProgressBarExample.tsx#L96) has an animated progress bar example. This isn't in the official [snack examples](https://snack.expo.dev/@react-native-paper/react-native-paper-example_v5)

### Expected behaviour
An example in the snack of an animated progress bar

### How to reproduce?
No need, it's just missing

### Preview
No need, you can tell the code is differentt

### What have you tried so far?
Not relevant

### Your Environment
Not relevant

I'm trying to get an animated progress bar working in my own app, so  when it failed I wanted to base it off the official example and check the diff, but it's not in the snack. I'm trying to run the whole example repo locally but it's taking forever.

**Comment by lukewalczak** [comment]
Thanks for reporting the issue. Example snack has been updated.
