### ISSUE TITLE
Custom theme styles are not overriding Data Table title 

### ISSUE THREAD

**Issue by surajeaton** [callstack/react-native-paper#4234]
### Current behaviour

Add a custom theme colors to the app, see the Data table title color is updating that

### Expected behaviour

It should override the data table title color with custom theme

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
> Add a custom theme colors to the app, see the Data table title color is updating that

Could you please add more information about your issue or create expo snack presenting your problem?
