### ISSUE TITLE
Error in button component with uppercase text by default

### ISSUE THREAD

**Issue by carl0smat3us** [callstack/react-native-paper#4240]
### Current behaviour
The text inside the button component is displayed in uppercase by default.

### Expected behaviour
The uppercase by default should be turned off.

### How to reproduce?
```tsx
<Button mode="contained">Hello world</Button>
```

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 12
| react-native                | 0.72.6
| react-native-paper    | 5.11.4
| node                            | 18.17.1
| npm                | 10.2.5
| expo sdk                     | 49.0.15

**Comment by lukewalczak** [comment]
In the version that you mentioned in the environment details (5.11.4) with a default theme version 3,  the `Text` inside the button component is not uppercased:

<img width="538" alt="Zrzut ekranu 2023-12-27 o 12 04 19" src="https://github.com/callstack/react-native-paper/assets/22746080/77979a1e-1cba-4910-920f-c35e8833592c">
