### ISSUE TITLE
Drawer documentation is missing

### ISSUE THREAD

**Issue by MuhAssar** [callstack/react-native-paper#4241]
### Current behaviour

in components doc site, the drawer page is missing:
https://callstack.github.io/react-native-paper/docs/components/Drawer/

### Expected behaviour

a page regards the usage of drawer component is expected to be present like the page about the dialog component, not just its child components.

### How to reproduce?

visit: https://callstack.github.io/react-native-paper/docs/components/Drawer/
drawer item is not clickable in the side bar

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
The `Drawer` component is not directly exported by the library; instead, only its subcomponents, such as item or section, are exported. Consequently, documentation for the Drawer itself is unavailable.
