### ISSUE TITLE
 Problem with the onChange and onChangeText properties on the TextInput component

### ISSUE THREAD

**Issue by carl0smat3us** [callstack/react-native-paper#4242]
### Current behaviour
Currently, I've noticed an issue in the library, specifically in the TextInput component. The issue is related to the onChange and onChangeText properties, both of which are intended for the same purpose.

#### With onChange:
> Note: Onchange isn't even working.
  ```tsx
<TextInput
    mode="outlined"
    label="Email"
    onChange={(e) => { } }
/>
```

#### With onChangeText:
  ```tsx
<TextInput
    mode="outlined"
    label="Email"
    onChangeText={(e) => { } }
/>
```

### Expected behaviour

Considering the reasons mentioned, it would be advantageous to focus on making the onChange property work properly by eliminating the need for the onChangeText property. Not only would this simplify the use of the component, but it would also bring the library into line with more semantic and consistent practices.

  ```tsx
<TextInput
    mode="outlined"
    label="Email"
    onChange={(e) => { } }
/>
```

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 12
| react-native                | 0.72.6
| react-native-paper    | 5.11.4
| node                            | 18.17.1
| npm                | 10.2.5
| expo sdk                     | 49.0.15

**Comment by lukewalczak** [comment]
Hey @carl0smat3us, on the following [snack](https://snack.expo.dev/@react-native-paper/textinput-onchange-and-onchangetext?platform=android) you can notice there is no issue with using `onChange` on the `TextInput` from the library.

**Comment by carl0smat3us** [comment]
Now I can understand better, thanks for taking the time to review my issue.
