### ISSUE TITLE
(Flat TextInput) - Input Text color is not matching with MD3 design

### ISSUE THREAD

**Issue by ektaghag-eaton** [callstack/react-native-paper#4250]
### Ask your Question

In the latest version of react-native-paper, the **input text color** is `onSurfaceVariant` when the mode is **flat**. But as per [MD3 design guidelines](https://m3.material.io/components/text-fields/specs), it should be `onSurface`. 

Is there any specific reason to use `onSurfaceVariant` instead of `onSurface` only for flat mode? 

https://github.com/callstack/react-native-paper/blob/726b98f371a84b302b553793679279d4c86555ff/src/components/TextInput/helpers.tsx#L331

**Comment by lukewalczak** [comment]
Hey @ektaghag-eaton, I've noticed that [Material Design](https://m3.material.io/styles/color/system/overview) in October 2023 reorganized their color structure, so there can be an option some colors have been updated. I'll take a look at it.
