### ISSUE TITLE
(Flat TextInput) - Input Text Underline color is not matching with MD3 design

### ISSUE THREAD

**Issue by ArshdeepSingh3-eaton** [callstack/react-native-paper#4252]
### Ask your Question
In the latest version of react-native-paper, the input text underline color is onSurface when the mode is flat. But as per [MD3 design guidelines](https://m3.material.io/components/text-fields/specs), it should be onSurfaceVariant.

Is there any specific reason to use onSurface instead of onSurfaceVariant only for flat mode?

**Comment by lukewalczak** [comment]
Related: https://github.com/callstack/react-native-paper/issues/4250#issuecomment-1880766503
