### ISSUE TITLE
[Feature request] Add Material Extended FAB 

### ISSUE THREAD

**Issue by manojleaton** [callstack/react-native-paper#4253]
Is your feature request related to a problem? Please describe.
This is not related to a problem, it's a component addition request.

Describe the solution you'd like
Currently Extended FAB component is exist in Material Design 3, but not available in React Native Paper Library.
https://m3.material.io/components/extended-fab/overview
If it is possible to add this component to the RNP library, it would be helpful.

Thanks

**Comment by lukewalczak** [comment]
Hey @manojleaton, the `FAB` component has an option to be extended if you pass the `label` [prop](https://callstack.github.io/react-native-paper/docs/components/FAB/#label)
