### ISSUE TITLE
TextInput:Android values is getting clipped from left

### ISSUE THREAD

**Issue by Akashdeep312** [callstack/react-native-paper#4254]
### Current behaviour

TextInput Android values is getting clipped from left works perfectly on ios

<img width="334" alt="Screenshot 2024-01-04 at 1 16 21 PM" src="https://github.com/callstack/react-native-paper/assets/48234644/b14fb7fc-6a80-4e18-bf33-6e0efde1436e">

### Expected behaviour

Should work like ios
<img width="323" alt="image" src="https://github.com/callstack/react-native-paper/assets/48234644/d9bc637f-d3c7-4512-82a0-73b546bfdbe9">

### How to reproduce?

Here is my custom component 
```js
<TextInput
                style={[Styles.input]}
                label={label}
                selectionColor={selectionColor}
                onChangeText={onChangeText}
                value={value}
                mode={mode}
                selectTextOnFocus={selectTextOnFocus}
                maxLength={maxLength}
                onSubmitEditing={onSubmitEditing}
                theme={errorMsg ? errorTheme : theme}
                outlineColor={outLineColor}
                activeOutlineColor={activeOutlineColor}
                pointerEvents={pointerEvents}
                numberOfLines={numberOfLines}
                right={rightView}
                left={leftView}
                keyboardType={keyboardType}
                onBlur={onBlur}
                ref={inputRef}
                defaultValue={defaultValue}
                {...props}
                disabled={isDisabled}
                autoCapitalize={autoCapitalize}
            />
```
usage

```js
                       <InputText
                              label={"Where you want"}
                                value={text}
                                numberOfLines={1}
                                leftView={
                                    <PaperTextInput.Icon
                                        disabled={true}
                                        icon="account-multiple"
                                        color={TextColor.RAISIN_BLACK}
                                        size={20}
                                    />
                                }
                            />
```

ANDROID
<img width="334" alt="Screenshot 2024-01-04 at 1 16 21 PM" src="https://github.com/callstack/react-native-paper/assets/48234644/b14fb7fc-6a80-4e18-bf33-6e0efde1436e">

IOS
<img width="323" alt="image" src="https://github.com/callstack/react-native-paper/assets/48234644/d9bc637f-d3c7-4512-82a0-73b546bfdbe9">

### What have you tried so far?

i've tried fixes from the issue thread below
[https://github.com/callstack/react-native-paper/issues/2581](2581)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 16.2
| android                        | 13
| react-native                | 0.70.1
| react-native-paper    | ^4.12.5
| node                            | v16.20.2
| npm or yarn                | yarn

**Comment by lukewalczak** [comment]
I believe this is the default behavior on the Android platform. You can verify this by checking any system input on your Android device or by utilizing the base `TextInput` from the `react-native` library.

Please check the attachment below:

![android_system_input](https://github.com/callstack/react-native-paper/assets/22746080/2ac0a996-9144-4399-9036-32267bde9721)
