### ISSUE TITLE
Alignment issue when onPress is used in TextInput.Affix

### ISSUE THREAD

**Issue by wshinigamic** [callstack/react-native-paper#4269]
### Current behaviour
When onPress prop in TextInput.Affix is used, the text in affix is displayed below and outside of the text input box.

### Expected behaviour
onPress shouldn't change the alignment of the text affix.

### How to reproduce?
```
<TextInput 
   value={"12345678"}
   left={<TextInput.Affix text={"(+1)"} onPress={()=>{}}/>} 
/>
```
https://snack.expo.dev/wwLzldp2s

### Preview
![Screenshot 2024-01-12 181939](https://github.com/callstack/react-native-paper/assets/18512651/f89e4d90-d4fe-4371-8dd4-fbfd8aa8b52c)

### Your Environment

| software                      | version
| --------------------- | -------
| react-native-paper    | 5.12.0

**Comment by lukewalczak** [comment]
@wshinigamic would you like to investigate what's wrong?
