### ISSUE TITLE
Using Chip results into error

### ISSUE THREAD

**Issue by shubhadeep29** [callstack/react-native-paper#4275]
### Current behaviour
Using Chip results in error
![Screenshot_1705128614](https://github.com/callstack/react-native-paper/assets/24447618/729c2d82-c438-465f-ab84-13c72b855faa)

### Expected behavior
<img width="288" alt="Screenshot 2024-01-13 at 12 22 43 PM" src="https://github.com/callstack/react-native-paper/assets/24447618/dbe786f3-5e30-4058-9620-32ca13ce561d">

### How to reproduce?
Just import and use Chip

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | Emulator Pixel_7_API_33
| react-native                | 0.72.4
| react-native-paper    | 5.12.1
| node                            | 16.20.2

**Comment by lukewalczak** [comment]
Based on the error message you're passing to the `Chip`'s styles a transparent background color, but please notice you have a type, instead of `transparent` you have`transperent`.
