### ISSUE TITLE
[iOS] Extra space in between Component and Tooltip

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [callstack/react-native-paper#4276]
### Current behaviour
Tooltip is added very far from the component, lots of space can be observed clearly.

### Expected behaviour
There should be no space in between the component and the tooltip.

### How to reproduce?
Add a tooltip to a component and observe the position.
`<Tooltip title={"Selected Camera"}>
        <IconButton icon="camera" selected size={24} onPress={() => { }} />
      </Tooltip>`

### Preview
![Simulator Screenshot - iPhone-7-15-2-0 - 2024-01-15 at 12 46 59](https://github.com/callstack/react-native-paper/assets/97147467/7640bb06-0a6d-4925-a3c3-102a9bf62ad8)

### What have you tried so far?
Tried with android and it works fine, there is no extra space between component and tooltip

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 15.2
| android                        | 13
| react-native                | 72.9
| react-native-paper    | 5.4.1
| node                            | 18.17.1
| npm or yarn                | 1.22.19

**Comment by ravindraguptacapgemini** [comment]
@lukewalczak Can you please check this issue once, it happens for iOS only.

**Comment by KrushnaFindingPi** [comment]
keep it open!  this issue is still there
