### ISSUE TITLE
disabled property on IconButton is not working

### ISSUE THREAD

**Issue by atheck** [callstack/react-native-paper#4282]
### Current behaviour

The `onPress` handler is called even when the `IconButton` is disabled.

### Expected behaviour

The `onPress` handler should not be called when the `IconButton` is disabled. 

The docs say:

"A disabled button is greyed out and onPress is not called on touch."

### How to reproduce?

```tsx
<IconButton
  icon={"some-icon"}
  onPress={onPress}
  disabled={true}
/>
```

The icon is grayed out, but the button can still be pressed on `onPress` is called.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | 14
| react-native                | 0.72.9
| react-native-paper    | 5.12.1
| node                            | 20.10.0
| npm or yarn                | npm 10.2.4
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
Hey @atheck, based on the code you've provided, I created the [snack](https://snack.expo.dev/@react-native-paper/icon-button---disabled) where you can observe the `onPress` callback is not triggered.

Closing the ticket, however feel free to reopen it with your issue reproduction.

**Comment by atheck** [comment]
Hi, thank you for trying it. I figured out the reason for the behavior. I use a `Tooltip` around the `IconButton` that seems to cause the issue:

```tsx
<Tooltip title={"Title"}>
  <IconButton
    icon={'camera'}
    onPress={() => console.log("pressed")}
    disabled={true}
  />
</Tooltip>
```

**Comment by lukewalczak** [comment]
@atheck will check it.

**Comment by atheck** [comment]
Thank you @lukewalczak
