### ISSUE TITLE
Please add a startIcon for Snackbar component

### ISSUE THREAD

**Issue by bartplay2499** [callstack/react-native-paper#4288]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem, it's a  modification  props request.

**Describe the solution you'd like**
![image](https://github.com/callstack/react-native-paper/assets/54477221/29173330-8553-4c8a-9ef4-708121663489)

**Comment by lukewalczak** [comment]
Hey @bartplay2499, you can pass an icon along with styled text as a [child](https://snack.expo.dev/@react-native-paper/snackbar-with-leading-icon) into `Snackbar` so currently I believe there is no need to add a leading icon for that component, especially that MD doesn't provide any guidelines for it.
