### ISSUE TITLE
`5.12.1` -> `5.12.3` upgrade: Package entrypoint does not exist

### ISSUE THREAD

**Issue by Yonom** [callstack/react-native-paper#4297]
### Current behaviour

Upgrading to `5.12.3`, I now get: Unable to resolve "react-native-paper/lib/module/components/Portal/Portal"

Upon further inspection, I noticed that the entire /lib folder is missing in `node_modules`

<img width="339" alt="image" src="https://github.com/callstack/react-native-paper/assets/1394504/ae5ee6e4-e451-4280-8da5-23fab242a0ed">

The package entry point is defined as `lib/module/index.js`, and that is missing:

<img width="858" alt="image" src="https://github.com/callstack/react-native-paper/assets/1394504/dbd9963f-81e2-4cef-be34-242f0e3f0140">

### Expected behaviour

I expected my code to keep working during a patch version update.

### How to reproduce?

Install `v5.12.3` in a brand new Expo project and try importing the Portal component.

### What have you tried so far?

Downgrading to `5.12.1` fixed the issue for me

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 17.2
| android                        | -
| react-native                | 0.73.2
| react-native-paper    | 5.12.3
| node                            | v20.11.0
| npm or yarn                | Yarn 1.22.21
| expo sdk                     | 50.0.3

**Comment by lukewalczak** [comment]
Nothing changed related to the `Portal` component, maybe let's try to reinstall node_modules completely and run metro with cache reset `yarn start --reset-cache`?

**Comment by Yonom** [comment]
@lukewalczak I did some more investigation and I think the version does not include any bundled JS (the entire lib folder is missing in my node_modules). 

The portal error message was simply the first point in my code that broke

Updated the issue details.

**Comment by Yonom** [comment]
Upon further inspection the lib folder exists in a Github Workspaces environment, so I think the issue might be local to my machine, sorry about the trouble...
