### ISSUE TITLE
Button, IconButton disabled prop behaves incorrect inside Tooltip

### ISSUE THREAD

**Issue by Wurushu** [callstack/react-native-paper#4298]
I'm new to app development. I don't know if it is a bug or just something normal.

### Current behaviour
When a `Button` or `IconButton` component is inside a `Tooltip` component. `disabled` prop wouldn't stop executing `onPress` handler.

### Expected behaviour
The `onPress` handler of `Button` or `IconButton` should not be executed when `disabled` is true.

### How to reproduce?
```
<Tooltip title="Press to check">
  <IconButton
    icon="check"
    onPress={() => {
      console.log('Button pressed');
    }}
    disabled={true}
  />
</Tooltip>
```

### Preview
![image](https://github.com/callstack/react-native-paper/assets/19490316/e3bf31ba-1cc6-4e20-b723-957be8905741)

### What have you tried so far?
It works well if I remove the `Tooltip` component.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | 13
| react-native                | 0.72.4
| react-native-paper    | 5.10.6
| node                            | 18.17.1
| npm or yarn                | 9.6.7
| expo sdk                     | x.x.x

**Comment by lukewalczak** [comment]
The issue was fixed in `5.12.3`
