### ISSUE TITLE
SearchBar does not seem to work with custom height

### ISSUE THREAD

**Issue by msageryd** [callstack/react-native-paper#4304]
I'm upgrading an old app. React-native-paper was upgraded from 4.10.1 to 5.12.3.
The SearchBar worked fine in v4.10.1

Here is how I'm using it:
```
<Searchbar
  placeholder={'search'}
  onChangeText={onChange}
  value={searchQuery}
  style={{
    height: 30,
    borderColor: 'lightblue',
    borderWidth: 1,
    backgroundColor: 'white',
    margin: 6,
  }}
/>
```

There seems to be an internal padding added, but I'm not able to change it via `padding`, `paddingTop` or `paddingVertical`

<img width="258" alt="image" src="https://github.com/callstack/react-native-paper/assets/4483085/b8a5ac8e-7aca-489b-a05d-dc735ca03c4b">

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 17.2 (simulator)
| react-native                | 0.73.3
| react-native-paper    | 5.12.3
| node                            | 18.19
| npm.                            | 10.2.3

**Comment by msageryd** [comment]
Update:
I tried the same with theme version 2 and it worked as before.

I.e. the problem only regards v3.

**Comment by Aztaro97** [comment]
To make it work, you need to set minHeight value 0 to the input style:

`
<Searchbar
  placeholder={'search'}
  onChangeText={onChange}
  value={searchQuery}
  style={{
    height: 30,
    borderColor: 'lightblue',
    borderWidth: 1,
    backgroundColor: 'white',
    margin: 6,
  }}
  inputStyle={{
        minHeight: 0 // Add this
      }}
/>
`

**Comment by msageryd** [comment]
Thank you!
Your solution works great.

**Comment by hgx** [comment]
> [@Aztaro97](https://github.com/Aztaro97) your solution works, but on android when the input field is focused it shrinks a bit , do you have any idea how to avoid it

Hi @mubarizgh @Aztaro97 
I have the same question, do you have any suggestions?

**Comment by hkniyi** [comment]
@mubarizgh @hgx 
To solve the android problem, 
use something like this 

```
inputStyle={{  
     minHeight: 30, 
     fontSize: 14,
     paddingTop: 0, 
     paddingBottom: 0
}}
style={{
    borderRadius: 25,
    backgroundColor: '#f8f9fa',
    borderWidth: 1,
    height: 30,
    borderColor: '#e0e0e0', 
}}
```

**Comment by Ashraful-Mijan** [comment]
> To make it work, you need to set minHeight value 0 to the input style:
> 
> <Searchbar
>   placeholder={'search'}
>   onChangeText={onChange}
>   value={searchQuery}
>   style={{
>     height: 30,
>     borderColor: 'lightblue',
>     borderWidth: 1,
>     backgroundColor: 'white',
>     margin: 6,
>   }}
>   inputStyle={{
>         minHeight: 0 // Add this
>       }}
> />

this on is worked for me with latest version
