### ISSUE TITLE
Why can't I query react-native-paper elements in my unit tests?

### ISSUE THREAD

**Issue by VCSJacob** [callstack/react-native-paper#4310]
### Ask your Question

When writing the unit tests for my react-native app, react-native-paper elements do not render with my components in my tests.
No queries work, and when I print out the jsx of the component with screen.debug() none of the elements are there. 
When I updated my import to now use the regular react-native button `import { Button } from "react-native";`, the expected elements appeared in my test.

Here is the unit test
```
 it("renders correctly and toggles modal", async () => {

    const { getByText } = render(
      <IDContext.Provider value={{ ID: "mockedID" }}>
        <TaskContext.Provider value={{ tasks: [], setTasks: jest.fn() }}>
          <ModalToggleButton />
        </TaskContext.Provider>
      </IDContext.Provider>
    );
    // Check if the "Show Tasks" button is initially present
    const showTasksButton = getByText("Show Tasks");
   // getByTestId("showTasks") returns null as well
    console.log(showTasksButton)
    expect(showTasksButton).toBeTruthy();
    // Click the "Show Tasks" button to toggle the modal
    fireEvent.press(showTasksButton);
  });
```
This test does not pass when I use the Button imported from react-native-paper like so:
```
// VERSION THAT IS NOT WORKING using react-native-paper
import React, { useContext, useState } from "react";
import { View, Text } from "react-native";
import { Button } from "react-native-paper";
import ToDoList from "./ToDoList";
import {IDContext} from "../../context/IDContext";
export default function ModalToggleButton() {
  const [showModal, setShowModal] = useState(false);
  const { ID } = useContext(IDContext) || {}; // Use default empty object to avoid destructuring undefined
  return (
    <View>
      {showModal ? (
        <ToDoList ID={ID} showToggleButton={()=> setShowModal(false)}/>
      ) : (
        <Text><Button onPress={() => setShowModal(true)} testID="showTasks">Show Tasks</Button></Text>
      )}
    </View>
  );
}
```

But when I update the component to this, the test passes and the Button can be interacted with in the test
```
//WORKING VERSION without react-native-paper
import React, { useContext, useState } from "react";
import { Button, View } from "react-native";
import ToDoList from "./ToDoList";
import {IDContext} from "../../context/IDContext";
export default function ModalToggleButton() {
  const [showModal, setShowModal] = useState(false);
  const { ID } = useContext(IDContext) || {}; // Use default empty object to avoid destructuring undefined
  return (
    <View>
      {showModal ? (
        <ToDoList ID={ID} showToggleButton={()=> setShowModal(false)}/>
      ) : (
        <Button onPress={() => setShowModal(true)} title="Show Tasks"/>
         
      )}
    </View>
  );
}

```
This issue is not isolated to react-native-paper Buttons. In fact, any react-native-paper element cannot be found in my unit test, such as TextInputs, but react-native's TextInput is rendered in the tests with no issue.

**Comment by Balthazar33** [comment]
@VCSJacob 
Are you mocking `react-native-paper` somewhere? I, too, face this issue when I mock `react-native-paper` in `jestSetup.js` as 

```
jest.mock('react-native-paper');
``` 

But, if I remove this, jest throws a different error:
```
Expected a string (for built-in components)...
```

**Comment by VCSJacob** [comment]
I have the react-native-paper mocked in my jestSetup.js file as `jest.mock('react-native-paper)` and if I remove it nothing changes.

**Comment by Balthazar33** [comment]
After removing the mocks for `react-native-vector-icons` (and the one for `react-native-paper`) from my jest setup file, the RN paper elements showed up in my snapshot files and I was able to find them in the queries.

This, however, causes the `name` prop for vector icons to be undefined in the snapshot, but that's a separate issue.


P.S I also have `react-native-paper` added to the `transformIgnorePatterns` property in the jest config file.

**Comment by VCSJacob** [comment]
```
import mockSafeAreaContext from 'react-native-safe-area-context/jest/mock';

jest.mock('react-native-safe-area-context', () => mockSafeAreaContext);
```
Removing 'react-native-paper' mock and adding the above mock in my setup-jest.js file worked, react native paper elements are now rendering in my tests.
