### ISSUE TITLE
FABGroup zIndex/Elevation

### ISSUE THREAD

**Issue by Shamplol** [callstack/react-native-paper#432]
Heya there,

I'm having a problem with the FABGroup component appearing on top of React-Navigation modals and drawers. 

I've tried different styling approach with no success. 

Removing the ThemedPortal wrapper seems to solve the issue but I'd rather not modify the library.

Hopefully someone here has a cleaner solution~

Thanks

PS: Seems to be a duplicate of #420

**Comment by ferrannp** [comment]
Duplicated of #420. It might require some discussion with `react-navigation`. CC @brentvatne

**Comment by satya164** [comment]
Right now there's no way to do this because of limitations in React Navigation. But you can use the focus listeners from react navigation to hide the FAB when the screen loses focus (e.g. it's behind a modal)
