### ISSUE TITLE
Bug : TextInput focus bug 

### ISSUE THREAD

**Issue by Arjun059** [callstack/react-native-paper#4336]
### Current behaviour

code 
import * as React from 'react';
import { TextInput } from 'react-native-paper';

const MyComponent = () => {
  const [text, setText] = React.useState('');

  return (
    <TextInput
      label="Password"
      secureTextEntry
      right={<TextInput.Icon icon="eye" />}
    />
  );
};

export default MyComponent;

issue: when click eye icon keyboard disappear and TextInput loosed focus.

### Expected behaviour
 expected behaviour when i click eye icon the TextInput remain Fucused. 
Like i want to input password the eye icon toggle security text true or false and TextInput should remain Focused

### Your Environment
Test in android 12

package versions
   "react-native-paper": "^5.10.6",
    "react": "18.2.0",

**Comment by donutdonate** [comment]
Faced with the same issue on Android

**Comment by donutdonate** [comment]
@Arjun059 Hi! In my case the problem was with ScrollView settings. If you use ScrollView set the  keyboardShouldPersistTaps prop to "handled", so the keyboard will not dismiss automatically when the tap was handled by children of the ScrollView.
