### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by mehrdad-shokri** [callstack/react-native-paper#437]
This is really not an issue, it's just a way to appreciate for your awesome library and efforts.
Just installed the expo app and the components are really indistinguishable from native components. 
The best material design component library for RN so far. Thank you.

**Comment by yaronlevi** [comment]
+1
react-native-paper is a pleasure to work with. The refinement and polish of the components are truly amazing. Please keep it up (-:

**Comment by ferrannp** [comment]
Thanks! I labelled this with `wontfix` meaning that we will try to keep up the good work, quality and efforts that everybody puts into this library.

**Comment by proof666** [comment]
Thank you! It's a great library. Everything is simple, understandable and beautiful.
Good luck!

**Comment by egunsoma** [comment]
Actually I have tried many Material Design libs so far both for JS and React Native, this is far the most convenient. Thanks 🖖

**Comment by ferrannp** [comment]
Will close to keep sanity in the number of issue but we will still try to keep up the good work :). Thank you all for your support!
