### ISSUE TITLE
Segmented Buttons component should have 'disabled' prop

### ISSUE THREAD

**Issue by jairaja** [callstack/react-native-paper#4371]
**Is your feature request related to a problem? Please describe.**
Need to disable whole 'Segmented Buttons component, instead of individual buttons

**Describe the solution you'd like**
'disabled' prop in SegmentedButtons Props

**Describe alternatives you've considered**
Currently using 'disabled' prop on all buttons within SegmentedButtons

**Additional context**

**Comment by gedu** [comment]
Hey, as you said the only way for now is disabled individual buttons, if you wanna disable all of them at the same time I would suggest using just one flag:
```
const MyComponent = () => {
  const [value, setValue] = useState('');
  const [disableAll, setDisableAll] = React.useState(false);

  return (
    <SafeAreaView style={styles.container}>
      <SegmentedButtons
        value={value}
        onValueChange={setValue}
        buttons={[
          {
            value: 'walk',
            label: 'Walking',
            disabled: disableAll,
          },
          {
            value: 'train',
            label: 'Transit',
            disabled: disableAll,
          },
          { value: 'drive', label: 'Driving', disabled: disableAll, },
        ]}
      />
    </SafeAreaView>
  );
};
```
We don't see the need of one prop to disable all the buttons, that can complicate the logic and maintainability. 
Thanks
