### ISSUE TITLE
clearButtonMode ignored on TextInput when multiline is true

### ISSUE THREAD

**Issue by angelxmoreno** [callstack/react-native-paper#4381]
### Current behaviour
I am on IOS. I have 2 TextInputs, both have `clearButtonMode={'always'}`. The one that has `multiline` set to true ignores the `clearButtonMode`

### Expected behaviour
To see a clear button

### How to reproduce?
I haz a snack: https://snack.expo.dev/@angelxmoreno/rnp-textinput-bug?platform=ios

### Preview
![Screenshot 2024-04-23 at 6 16 13 PM](https://github.com/callstack/react-native-paper/assets/363479/73fde59f-bd70-483b-b40e-c466752ef380)

### What have you tried so far?
not much. tried different "modes" and made a ticket.

### Your Environment
| software                      | version
| --------------------- | -------
| ios                                | idk
| android                        | don't use ATM
| react-native                | 0.73.6
| react-native-paper    | ^5.12.3
| node                            | 18ish
| npm or yarn                | bun@1
| expo sdk                     | ~50.0.14

**Comment by gedu** [comment]
Hey, that is a limitation from [React-Native TextInput](https://reactnative.dev/docs/textinput), not from paper

<img width="836" alt="Screenshot 2024-04-24 at 11 15 41" src="https://github.com/callstack/react-native-paper/assets/1676818/d5624d95-d78a-4b04-95c4-16256ceb2a80">

**Comment by angelxmoreno** [comment]
Great find @gedu. Closing this. Not a big of react-native-paper
