### ISSUE TITLE
TextInput.Icon: Support for defaultProps will be removed from function components in a future major release.

### ISSUE THREAD

**Issue by yannick-softwerft** [callstack/react-native-paper#4382]
### Current behaviour
Warning: TextInput.Icon: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### Expected behaviour
No warning.

![image](https://github.com/callstack/react-native-paper/assets/124596031/59c1112e-0faa-4a72-8c2b-d0f9e0725f37)

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.74.0
| react-native-paper    | 5.12.3
| node                            | 18.18.0
| npm or yarn                | 9.8.1
| expo sdk                     | No Expo

**Comment by choudhary-github** [comment]
I am facing the same. Will this deprecate ? If yes, then what I should use instead?

**Comment by zkteco-home** [comment]
same issue #4386

**Comment by sa1utep1z** [comment]
same issue, same environment

**Comment by keehui9292** [comment]
same issue here, any way to fix this?

**Comment by raajnadar** [comment]
You can ignore the warning until the following PR is merged and released https://github.com/callstack/react-native-paper/pull/4385

**Comment by pooria226** [comment]
i handle this warning 
1. go this address node_modules/react-native-paper/src/components/TextInput/Adornment/TextInputIcon.tsx 
2. comment These lines 
// TextInputIcon.defaultProps = {
//   forceTextInputFocus: true,
// };

**Comment by dillontl** [comment]
> i handle this warning
> 
> 1. go this address node_modules/react-native-paper/src/components/TextInput/Adornment/TextInputIcon.tsx
> 2. comment These lines
>    // TextInputIcon.defaultProps = {
>    //   forceTextInputFocus: true,
>    // };

Confirmed this works, thanks man!

**Comment by Donald646** [comment]
If I ignore this, will the error prevent me from publishing my app?

**Comment by hashreepriya** [comment]
> i handle this warning
> 
> 1. go this address node_modules/react-native-paper/src/components/TextInput/Adornment/TextInputIcon.tsx
> 2. comment These lines
>    // TextInputIcon.defaultProps = {
>    //   forceTextInputFocus: true,
>    // };

still getting same issue

**Comment by Vincenteliezer** [comment]
I don't Know if this is the correct way but the error went away!

`<TextInput
      label="Password"
      secureTextEntry
      right={(
           <TextInput.Icon icon="eye" />
      )}
 />`

**Comment by intentodepirata** [comment]
Same issue

**Comment by ttebify** [comment]
> i handle this warning
> 
> 1. go this address node_modules/react-native-paper/src/components/TextInput/Adornment/TextInputIcon.tsx
> 2. comment These lines
>    // TextInputIcon.defaultProps = {
>    //   forceTextInputFocus: true,
>    // };

Before this current PR is merged and you really need this update up, you can use [patch-package](https://www.npmjs.com/package/patch-package) to apply a patch to the `react-native-paper` package, follow these steps:

If you are using yarn:

1. **Install `patch-package` and `postinstall-postinstall`** as dev dependencies:

   ```bash
   yarn add patch-package postinstall-postinstall --dev
   ```

   `postinstall-postinstall` is used to ensure that patches are applied after each install.

2. **Create the Patch**:
   First, modify the file `node_modules/react-native-paper/src/components/TextInput/Adornment/TextInputIcon.tsx`  as suggested above, see lines `179-181`:

   ```typescript
   // TextInputIcon.defaultProps = {
   //   forceTextInputFocus: true,
   // };
   ```

   Then, create a patch file using `patch-package`. Run:

   ```bash
   npx patch-package react-native-paper
   ```

   This command will generate a patch file in the `patches` directory with a name like `react-native-paper+<version>.patch`.

3. **Add a Postinstall Script**:
   Update your `package.json` to include a postinstall script that applies the patch automatically after each install. Add the following to your `scripts` section:

   ```json
   "scripts": {
     "postinstall": "patch-package"
   }
   ```

   This script will ensure that your patches are applied after every `yarn install`.

You can verify your patch by installing the package again and checking if the changes you made are correctly applied to the `node_modules` directory. The lines should be commented out in `TextInputIcon.tsx`.

> Remember to remove the patch after the fix to this issue has been released as a new version.
