### ISSUE TITLE
React depreciation warning of defaultProps occurring on TextInput.Icon (Suggested solution)

### ISSUE THREAD

**Issue by sethimcclaine** [callstack/react-native-paper#4402]
### Current behaviour
Updating to `"react-native": "0.74.1` / `"react": "18.2.0"` results in depreciation warning of defaultProps

```
 ERROR  Warning: TextInput.Icon: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
 ```
 
 This is noticed in TextInput.Icon, but grepping code base for `defaultProps` will likely reveal other instances

### Expected behaviour

No deprication warnings

### Preview
<img width="620" alt="Screenshot 2024-05-09 at 10 50 26 AM" src="https://github.com/callstack/react-native-paper/assets/2078156/3f6eea2a-a591-42b0-a6c7-6a095359223a">

### What have you tried so far?
updating `src/components/TextInput/Adornment/TextInputIcon.tsx`
```
ln 132
+ forceTextInputFocus = true,
- forceTextInputFocus,
ln 179-180
- TextInputIcon.defaultProps = {
-   forceTextInputFocus: true,
- };
```

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by gedu** [comment]
Already in a PR: https://github.com/callstack/react-native-paper/pull/4385, Closing to avoid duplication
