### ISSUE TITLE
[Text] selectable does not work on android

### ISSUE THREAD

**Issue by ddeath** [callstack/react-native-paper#4411]
### Current behaviour
[Text] selectable does not work on android. I should be able to press and hold to select text, instead nothing happens

### Expected behaviour
I should be able to press and hold to select text

### How to reproduce?
Add:
`<Text selectable={true}>Testing</Text>`

and try to select text on android.

### What have you tried so far?
I tried to use Text from react-native instead and selection works there.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | 15
| react-native                | 0.74.1
| react-native-paper    | 5.12.3
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | 51.0.4

**Comment by seb-zabielski** [comment]
Hey @ddeath 

I have not been able to reproduce it. 

Can you provide more details: 
1. Do you have a custom theme provided?
2. Is the text inside another component (such as FlatList)?
3. Were you able to reproduce it on another device/emulator?

**Comment by ddeath** [comment]
Hi, I am trying to replicate it on fresh repo, but I am unable to do so. Probably some weirdness in other app. I think we can close this.
