### ISSUE TITLE
Text.Icon default props warning on Android and IOS

### ISSUE THREAD

**Issue by stakez** [callstack/react-native-paper#4412]
### Current behaviour
Building both IOS and Android show the following warning

"ERROR  Warning: TextInput.Icon: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    in TextInput.Icon"

### Expected behaviour
No warnings

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by raajnadar** [comment]
https://github.com/callstack/react-native-paper/pull/4385
