### ISSUE TITLE
The tutorial suggests using App.js but this is missing when creating a project?

### ISSUE THREAD

**Issue by Max-Lovell** [callstack/react-native-paper#4425]
### Current behaviour
I am creating an app **with Expo** following this: https://callstack.github.io/react-native-paper/docs/guides/getting-started/#installation I would like to edit App.js as suggested but it doesn't appear to be in my project folder. I'm a newbie to react and am not sure how to proceed with the library.

### Expected behaviour

Presence of App.js file to setup Paper UI with

### How to reproduce?
Setup the app like so:
```
npx create-expo-app@latest my-app
cd my-app
npm install react-native-paper
npm install react-native-safe-area-context
npm i pod-install
npm install react-native-vector-icon
npm run reset-project
```
and create babel.config.js from https://callstack.github.io/react-native-paper/docs/guides/getting-started/#installation

### What have you tried so far?
Googling - found nothing about how to get around this. Perhaps it is an expo Managed app? did run `npx expo prebuild` but this doesn't seem to have created the App.js.

Edit: just discovered this in the Expo docs - is this related then? https://github.com/expo/expo/pull/28833 App.js is now _layout.tsx?

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.74.1
| react-native-paper    | 5.12.3
| node                            | 22.1.0
| npm or yarn                | 10.7.0
| expo sdk                     | 51.0.9

**Comment by jcubic** [comment]
It looks like latest create-expo-app use new expo router and don't use any old files.

I'm not familiar with new router (it looks like file based like in Next.js), but I would say that the documentation needs to be updated to include information how to use library with new base expo project.

**Comment by Max-Lovell** [comment]
Thanks, that put me on the right track. What I've found on this for anyone else confused:

Docs for Paper UI (and I think every UI library suggested by Expo) are not updated with the newest version of Expo, which now uses the Expo file-based routing system by default. This means that the entry point to the app, App.tsx, is largely [replaced with _layout.tsx](https://docs.expo.dev/develop/file-based-routing/#_layout-file) (relevant [PR](https://github.com/expo/expo/pull/28833)), but also index.tsx to some degree. Fortunately, you can still mostly follow the tutorials, noting things like <PaperProvider> need to be inside RootLayout() in _layout.tsx instead of in App.tsx. A useful way to figure out the new system is to compare the Stack Navigator tutorials from the [Expo docs](https://docs.expo.dev/develop/file-based-routing/#stack-navigator) and [Paper](https://callstack.github.io/react-native-paper/docs/guides/react-navigation/).

Alternatively, you can create an app with App.tsx still using `npx create-expo-app@latest ProjectName --template blank@latest` ([see](https://docs.expo.dev/tutorial/create-your-first-app/)), or could create-expo-app with a [lower SDK](https://docs.expo.dev/versions/latest/).

**Comment by sudhanshu2070** [comment]
npx create-expo-app YOUR-PROJECT-NAME --template blank should do the trick.
