### ISSUE TITLE
Button "text" mode colors

### ISSUE THREAD

**Issue by michalzard** [callstack/react-native-paper#4444]
Hey,i was wondering is there a way to set separate colors to text & icon? 

This is my setup : 

![image](https://github.com/callstack/react-native-paper/assets/58849789/a20c6c0b-a042-4777-bdcd-ad0f73dca423)

When i apply textColor it is applied to both,and it doesnt seem like there's way to separate colors here

Here's when i was testing applying black text and in styles.btnIcon i just had color="red" for debugging but both text and icon remained black.

![image](https://github.com/callstack/react-native-paper/assets/58849789/dc7a6c23-007a-43b5-8e41-2fc52e4d140c)

**Comment by web-iou** [comment]
> Hey,i was wondering is there a way to set separate colors to text & icon?
> 
> This is my setup :
> 
> ![image](https://private-user-images.githubusercontent.com/58849789/343325939-a20c6c0b-a042-4777-bdcd-ad0f73dca423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0Njg4NjUsIm5iZiI6MTcxOTQ2ODU2NSwicGF0aCI6Ii81ODg0OTc4OS8zNDMzMjU5MzktYTIwYzZjMGItYTA0Mi00Nzc3LWJkY2QtYWQwZjczZGNhNDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA2MDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NDgyMTNhODVhNGQxYTU2MjM1OTJkOTJjMjM2YzhjZGQ2NTU2NWEzMjAxY2Q3MTYwZTQwMTQyYTVmNzlhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z8E1auI-T83yayd3X2cDWfu7LkQAWyqfcxjCZdgn6gs)
> 
> When i apply textColor it is applied to both,and it doesnt seem like there's way to separate colors here
> 
> Here's when i was testing applying black text and in styles.btnIcon i just had color="red" for debugging but both text and icon remained black.
> 
> ![image](https://private-user-images.githubusercontent.com/58849789/343326487-dc7a6c23-007a-43b5-8e41-2fc52e4d140c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0Njg4NjUsIm5iZiI6MTcxOTQ2ODU2NSwicGF0aCI6Ii81ODg0OTc4OS8zNDMzMjY0ODctZGM3YTZjMjMtMDA3YS00M2I1LThlNDEtMmZjNTJlNGQxNDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA2MDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOWM1MDNhYWJhODNiZTg4ZTM2MWJkMTY5MjYwZDJiNzJkOGZiNTFiNmRiNDFkZTU5ZDZjNTQ1MjZlYzMwZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3P7LgT8kRL3U3rD8gONAXA_2psHxOkWeX0NNxR6rWf4)

try to use labelstyle props change icon color？

**Comment by seb-zabielski** [comment]
I don't know what props your icon has, but try putting `style={styles.btnIcon}` after `{...props}` something like this ` icon={(props) => <BookOpen {...props} style={styles.btnIcon} />}`. The color might be overwritten by other prop.
