### ISSUE TITLE
TextInput not styling properly on version 5.12.4

### ISSUE THREAD

**Issue by SantiagoSiordia** [callstack/react-native-paper#4463]
### Current behaviour

We were previously using `react-native-paper@5.12.3`and getting an warning:

`Warning: TextInput.Icon: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

![simulator_screenshot_4F144702-9110-4214-86A9-4385FEB1EA9C](https://github.com/user-attachments/assets/db32eedd-5fa1-426e-8723-6f7e4aa6ee3a)

So I waited on https://github.com/callstack/react-native-paper/pull/4385 to be merged into `main` so we could get rid of that warning.

As soon as we switch to the latest release version [`5.12.4`](https://github.com/callstack/react-native-paper/releases/tag/v5.12.4)

![simulator_screenshot_9204C3B3-5E5E-4EC9-86DB-A31352B3E2C4](https://github.com/user-attachments/assets/24136f2b-21e4-4e56-9f8f-d08467b3099e)

![Screenshot_1722108992](https://github.com/user-attachments/assets/575bdb8b-d1fb-40b2-93ab-0376e5cc6bb8)

All of the `TextInput`s break in style.

### Expected behavior

Style should work the same way in the two versions.

### How to reproduce

Install the latest version of [`react-native-paper@5.12.4`](https://github.com/callstack/react-native-paper/releases/tag/v5.12.4)

### What have you tried so far?

Restyling the TextInputs but it is not the ideal solution. This should not be a breaking change.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 17.4
| android                        | 36
| react-native                | 0.74.3
| react-native-paper    | 5.12.4
| node                            | 18.17.1
| yarn                             | 1.22.22
| expo sdk                     | 51.0.21

**Comment by aderiushev** [comment]
exactly same +1, for now rolled back to the 5.12.3

**Comment by kamilkedzierski** [comment]
Hey @SantiagoSiordia @aderiushev! I'm taking a look at it! 👀

**Comment by kamilkedzierski** [comment]
Here's PR with the fix! https://github.com/callstack/react-native-paper/pull/4466
