### ISSUE TITLE
Any plans for adding the Tabs component?

### ISSUE THREAD

**Issue by vieiralucas** [callstack/react-native-paper#447]
Hello there, thank you for this very awesome library!

Do you have any plans for adding the [Tabs](https://material.io/design/components/tabs.html) component?

Do you have something like a roadmap?

**Comment by satya164** [comment]
Hey, you can use https://github.com/react-native-community/react-native-tab-view for now :)

**Comment by vieiralucas** [comment]
@satya164 That's perfect!

Thank you! <3
