### ISSUE TITLE
Access theme & colors in navigation (react-navigation)

### ISSUE THREAD

**Issue by victorkvarghese** [callstack/react-native-paper#449]
How can I access theme and colors from navigation page ??
For example : I would like to update tabColor in TabNavigation based on current theme?

Is this possible ?? 
I know about withTheme HOC .. but this will not work here right?

**Comment by macscripter** [comment]
E

**Comment by ferrannp** [comment]
It is not possible to access props from `static`. This is actually an issue with `react-navigation` so you might need to check with them. They also have https://github.com/react-navigation/rfcs.
