### ISSUE TITLE
When I add styles to the React Native Paper Chip, the text is not centered.

### ISSUE THREAD

**Issue by vortex-m** [callstack/react-native-paper#4502]
### When I add styles to the React Native Paper Chip component, the text is not centered within the chip. Despite using properties like justifyContent and alignItems, the text appears off-center, which affects the overall alignment and aesthetics of the UI.

<p>I've attached an image that illustrates the issue with the React Native Paper Chip component. The image shows how the text within the chip appears misaligned, highlighting the off-center placement.</p> 

![Screenshot 2024-09-20 154724](https://github.com/user-attachments/assets/ff79faa0-63a5-430a-aa5a-2809e3053bef)

**Comment by gedu** [comment]
Hey, can you share some code? I just added a style to a Chip component and looks good. Also the platform where that bug happens. thanks

**Comment by vortex-m** [comment]
Thanks for you reply, but The issue with the chip style is resolved!

**Comment by ingkiller** [comment]
<Chip
                style={{
                    backgroundColor:chipColor,
                    borderRadius:24,
                    paddingVertical:2,
                }}
            >
                <Text style={{
                    color:'#FFF',
                    fontWeight:'600',
                    textAlign:'center',
                    display:'flex',
                    flexGrow:1
                    }}>{chipText}</Text>
            </Chip>
