### ISSUE TITLE
Using AppBar with expo router header the back button always showing..

### ISSUE THREAD

**Issue by ahmetskilinc** [callstack/react-native-paper#4504]
When I'm using `<AppBar.Header ... />` with Expo Routers tabs and stack layouts, the back button always show.

I am using it like so:
`_layout.tsx`
```tsx
export default function Layout() {
	return (
		<Stack screenOptions={{ header: (props) => <Header {...props} /> }}>
			{...}
		</Stack>
	);
}
```

`Header.tsx`
```tsx
const Header = (props: NativeStackHeaderProps | BottomTabHeaderProps) => {
	const Left = props.options.headerLeft || (() => null);
	const Right = props.options.headerRight || (() => null);

	return (
		<Appbar.Header {...props}>
			<Left canGoBack={props.navigation.canGoBack()} />
			{props.navigation.canGoBack() ? (
				<Appbar.BackAction onPress={() => props.navigation.goBack()} />
			) : null}
			<Appbar.Content title={props.options.title} />
			<Right canGoBack={props.navigation.canGoBack()} />
		</Appbar.Header>
	);
};

export default Header;
```

This is the output I'm getting:
![Simulator Screenshot - iPhone 15 Pro - 2024-09-23 at 00 52 13](https://github.com/user-attachments/assets/79e09dbf-c346-492e-9826-88f7896a1087)

What am I doing wrong? I've tried to search around but cannot find a solution.

**Comment by gedu** [comment]
Is this a bug from react-native-paper? Are you trying to hide the back arrow button?
Looking at the code, do you know if `canGoBack()` is returning true? that's why it shows the back button? I think in bottom navigation you can go back because the previous tab is in the history?

```
{props.navigation.canGoBack() ? (
				<Appbar.BackAction onPress={() => props.navigation.goBack()} />
			) : null}
			```

**Comment by ahmetskilinc** [comment]
@gedu I think you're right. It's caused by the `Tabs` from `expo-router`. Thanks
