### ISSUE TITLE
"new architecture" touch is very inconsistent for TextInput and Button (both RN and Paper)

### ISSUE THREAD

**Issue by kferch-teamworks** [callstack/react-native-paper#4517]
### Current behaviour

I'm starting a mobile app for my company and am using expo v51, react-native v75, react-navigation (v7 rc), and react-native-paper v5. I turned "new architecture" on because I'm just starting and I want to smoothly switch to RN 76 when it comes out by verifying that I'm not doing anything that would not work with new architecture. I noticed in my eas preview builds that on real android phones I couldn't even press buttons or bring up the keyboard in text input. It all works fine an ios phones and emulators and simulators.

I turned off "new architecture" and android phones work fine. I'm worried that with RN 76 already hitting RC that this problem hasn't been solved yet.

I built up a minimal repo and things worked fine until adding in react-navigation.

I had [posted](https://github.com/expo/expo/issues/31505) on expo and someone there actually debugged and found this:

"this looks like an interaction between react-native-screens and react-native-paper's button component. i investigated this a bit and traced it back to this single line: https://github.com/callstack/react-native-paper/blob/9162a1fdf4e97c0669de8a8fa2057d8cfbe2e728/src/components/Button/Button.tsx#L336

if you comment that out, it fixes all other touches"

### How to reproduce?

Minimal repo:  https://github.com/kferch-teamworks/RNAndroidTouch

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by WoLewicki** [comment]
Hey, does the issue only appear when using `react-navigation` v7? Or is it also there on v6?

**Comment by cortinico** [comment]
> Hey, does the issue only appear when using `react-navigation` v7? Or is it also there on v6?

cc @brentvatne

**Comment by brentvatne** [comment]
@WoLewicki @cortinico - i just tried the repository shared by op and moved it to react-navigation v6, same issue in both cases.

**Comment by coado** [comment]
Hey, this is something that was fixed in this [PR](https://github.com/software-mansion/react-native-screens/pull/2292). If you use react-navigation v7 you can upgrade react-native-screens to [4.0.0-beta.7](https://github.com/software-mansion/react-native-screens/releases/tag/4.0.0-beta.7) version, which includes this fix. It solves the issue for provided repro.

**Comment by kferch-teamworks** [comment]
I tested my android phone with eas build react-navigation v7 and screens 4.0.0-beta.7 and it worked.  Closing this issue.  Thank you!
