### ISSUE TITLE
How to make unique design?

### ISSUE THREAD

**Issue by MonMohon** [callstack/react-native-paper#4534]
### Discussed in https://github.com/callstack/react-native-paper/discussions/4533

<div type='discussions-op-text'>

<sup>Originally posted by **MonMohon** October 23, 2024</sup>
I can't able to figure out how to make it unique design apply material design.
https://callstack.github.io/react-native-paper/docs/guides/theming#creating-dynamic-theme-colors
Two app with same theme its 100% clone.

Please Help</div>

**Comment by gedu** [comment]
Duplicated: https://github.com/callstack/react-native-paper/discussions/4533, closing this issue to focus the Q&A in one place
