### ISSUE TITLE
TextInput not Follow the Latest Material Design?

### ISSUE THREAD

**Issue by turtlegood** [callstack/react-native-paper#457]
### Current behaviour

Hello! Thank you for your wonderful library! When reading the material design official website today, I find that its **text fields** seems to have a new design pattern, which can be seen in this link: https://material.io/design/components/text-fields.html . Therefore, I wonder whether this library will migrate to this style as well? Thank you!

### Expected behaviour
N/A

### Code sample
N/A

### Screenshots (if applicable)
N/A

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | N/A
| react-native          | latest
| react-native-paper    |latest
| node                  |N/A
| npm or yarn           |N/A

**Comment by Trancever** [comment]
Hi @turtlegood ! We are working on new version of paper which will support new material design guidelines. All the code is on "material-next" branch so you can check it out.  Regarding TextInput component, @gawrysiak is working on it and he opened [PR](https://github.com/callstack/react-native-paper/pull/429) so it's gonna be finished soon probably.

**Comment by turtlegood** [comment]
Wow! Thank you very much for the wonderful job! I do hope that it can be finished in two or three weeks as my project is to be released in several weeks. Btw, I am curious about whether there will be many breaking changes or new features? Thanks!

**Comment by ferrannp** [comment]
Dup of #359. First questions please feel free to join our Discord channel: https://discord.gg/zwR2Cdh

**Comment by gawrysiak** [comment]
@Trancever yeah, need to get back to it. Missing just the icons and some polishing :)

**Comment by turtlegood** [comment]
OK Thank you!
