### ISSUE TITLE
[Feature Request] Modification to ListItem

### ISSUE THREAD

**Issue by ballenwillis** [callstack/react-native-paper#458]
Maybe there's a better place for feature requests, but I couldn't find anything. I would like to have a component like this if it's possible. I couldn't find anything in your kitchen sink app.

![image](https://user-images.githubusercontent.com/14190965/42886359-f91ecc7a-8a68-11e8-8b16-711c9ddf09f7.png)

**Comment by ballenwillis** [comment]
This can easily happen by giving the `listItem` a `paddingLeft: 0` to overwrite `paddingLeft: 64`.

**Comment by ferrannp** [comment]
Commented on #459.
