### ISSUE TITLE
Button has no background color

### ISSUE THREAD

**Issue by mehulmpt** [callstack/react-native-paper#468]
### Current behaviour
Button has no background color and primary/secondary colors as text colors

### Expected behaviour
Button should have background color and optimum text color

### Code sample

I trimmed down the example app from react paper and it works fine. See the button is fine here: https://snack.expo.io/rkl-E4wNQ
However, when I try to do it myself, the button has no background and it is driving me nuts: https://snack.expo.io/H1i-VVv4X

Why is that? What am I missing?

### What have you tried

Please check above to snack URLS. What is the difference between the codes in App.js of the working example with non working example?

### Your Environment

| software              | version
| --------------------- | -------
| android        | 8.1
| react-native          | 0.56
| react-native-paper    | 1.11.1
| node                  | 8.1
| npm or yarn           | npm

**Comment by gawrysiak** [comment]
Hi @mehulmpt, nice job providing good description and examples!

Notice your code is using paper 2.0 alpha which has slightly different buttons API, while the paper's example runs 1.10.3.

For the new buttons we're using `mode?: 'text' | 'outlined' | 'contained'`, so like this:
```<Button mode="contained" onPress={() => {}}>```

Hope that helps!

**Comment by mehulmpt** [comment]
Hey thanks @gawrysiak. Weird it happens for v1.11.1 on my real device also. Is alpha version documented right now or should I use v1.10.3 only? Using v1.10.3 on my real device fixes the problem

**Comment by gawrysiak** [comment]
The new alpha docs are available here: https://3917-71323749-gh.circle-artifacts.com/0/docs/index.html. It's an alpha though, so it's your call if you're fine using an early version. Personally I like it already.

Snack seems to be alright with v1.11.1 as well. It looks like there were no button changes lately within the 1.X line. Please make sure if your node_modules package has really updated and the device properly refreshed.
