### ISSUE TITLE
Add flex:1 to Modal?

### ISSUE THREAD

**Issue by fzyzcjy** [callstack/react-native-paper#471]
### Current behaviour

As is shown below, I have a modal which wants to show a *gallery* (library here: https://github.com/archriss/react-native-image-gallery). However, the gallery cannot be shown. After some investigation, I find that if I add `flex: 1` to the inner `Animated.View` then everything works(I have created a gist: https://gist.github.com/fzyzcjy/711abab472af21997157514062d6dc3a#file-part_of_modal-js-L23)! Therefore, I think it is reasonable to add this flex because when using modals, people may want their children to expand as much as possible in many cases.

Thank you very much!

### Expected behaviour

As is shown above.

### Code sample

```
    return (
      <Portal>
        <Modal visible={this.state.showingModal} onDismiss={this._closeModal}>
          <View style={{ flex: 1, flexGrow: 1, alignSelf: "stretch" }}>
            <Gallery
              style={{ flex: 1,  backgroundColor: "black"}}
              images={[{ source: { uri: "http://i.imgur.com/XP2BE7q.jpg" } },{ source: { uri: "http://i.imgur.com/5nltiUd.jpg" } }]}
           </View>
        </Modal>
      </Portal>
    );
```

Or a even simpler sample:

```
    return (
      <Portal>
        <Modal visible={this.state.showingModal} onDismiss={this._closeModal}>
          <Gallery
            style={{ flex: 1, backgroundColor: "black" }}
            images={[{ source: { uri: "http://i.imgur.com/XP2BE7q.jpg" } },{ source: { uri: "http://i.imgur.com/5nltiUd.jpg" } }]}
          />
        </Modal>
      </Portal>
    );
```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | latest
| react-native-paper    | **material-next**
| node                  | latest
| npm or yarn           | latest

**Comment by satya164** [comment]
That's strange. Can you create a Snack? It shouldn't be necessary since Modal is absolutely positioned to fill its parent.

**Comment by fzyzcjy** [comment]
@satya164 Do you mean a online demo or a minimum reproduciable demo? You can try the code above and the problem occurs

**Comment by fzyzcjy** [comment]
I have made a workaround by copying the Model.js info my own folder, modify the code and reference this component whenever I need it :)

**Comment by satya164** [comment]
https://snack.expo.io/

**Comment by fzyzcjy** [comment]
OK I will do it when I am free. But I think it is reasonable, because although the parent of that view is absolutely filled, the view itself is not. Actually it is neither absolutely filled nor flex:1...

**Comment by satya164** [comment]
Ah, you're talking about the content inside. Yeah, agreed. PR is welcome :)

**Comment by fzyzcjy** [comment]
PR created: https://github.com/callstack/react-native-paper/pull/491 :)
