### ISSUE TITLE
Invariant Violation: Element type is invalid

### ISSUE THREAD

**Issue by elllms** [callstack/react-native-paper#473]
### Current behaviour
I am using ListAccordion in my project, but i always get `Invariant Violation`. When i remove `ListAccordion` from source, it works fine.

### Expected behaviour
Here is an error
`Invariant Violation: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of DetailedListContent`.

### Code sample
https://snack.expo.io/Skp6M_aV7

### Your Environment

| software              | version
| --------------------- | -------
|  android        |  7.1.1
| react-native          | 0.55.2
| react-native-paper    |  ^2.0.0-alpha.7
| node                  |  10.5.0
| npm or yarn           |  1.7.0

**Comment by elllms** [comment]
**Solved**
In `index.js` file of react-native-paper missing `export` of ListAccordion. It can be imported directly from liblary: 
`import ListAccordion from '../../node_modules/react-native-paper/src/components/List/ListAccordion'`

**Comment by satya164** [comment]
Are you using the alpha? Check the docs here: https://github.com/callstack/react-native-paper/pull/371#issuecomment-388646154

**Comment by elllms** [comment]
@satya164  Yes
