### ISSUE TITLE
How to align FAB at the bottom of the page?

### ISSUE THREAD

**Issue by brunohkbx** [callstack/react-native-paper#476]
Why FAB button does not align at the bottom of the page?
FABGroup works fine.

How do I align the FAB button?

![whatsapp image 2018-08-01 at 16 50 35](https://user-images.githubusercontent.com/6487206/43545018-1b46acee-95ab-11e8-9ad0-8a0ec0c3018a.jpeg)

The pink button is the FABGroup in this image.

```
<View style={styles.container}>
  <FAB primary /> ( This is just a wrapper that I wrote to add custom styles )
</View>

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  }
})
```

**Comment by brunohkbx** [comment]
I was missing the { flex: 1 }.
Sorry.

**Comment by gawrysiak** [comment]
https://snack.expo.io/B1LPz51HQ
adding snack created by @satya164 for reference
