### ISSUE TITLE
Why does dialogs are underneath cards ?

### ISSUE THREAD

**Issue by brunohkbx** [callstack/react-native-paper#480]
I don't know why this dialog is underneath the cards.
Is it related to the elevation property?

![20180802_173528](https://user-images.githubusercontent.com/6487206/43614110-74c807d0-9688-11e8-825f-5649bd3f8ccf.png)

```
<View style={{flex: 1}}>
  {decks.map((deck, index) => (
    <Deck
      key={`${deck['title']} - ${index}`}
      title={deck['title']}
      flashcardsCount={deck['questions'].length}
    />
  ))}
  <FABContainer>
    <FAB primary onPress={() => this.handleFABPress()}/>
  </FABContainer>
  <DeckFormDialog visible={this.state.formVisible} />
</View>
```

**Comment by Trancever** [comment]
Hi @brunohkbx I created snack which shows how those components should be used together [snack](https://snack.expo.io/Bk5Sn0zLX). If you still has this issue please provide more informations and small repository/snack that reproduces the issue, cause i am not able to reproduce it myself.
