### ISSUE TITLE
TextInput type="password" does not seem to work.

### ISSUE THREAD

**Issue by TeunKooijman** [callstack/react-native-paper#490]
### Current behaviour

When I render a TextInput component with the "type" prop set to "password", the input text is still visible.

### Expected behaviour

I would expect the TextInput to hide the input text with asterixes.

### Code sample

```
            <TextInput type="password" id="password" name="password" label="Password" value={this.state.password} />

```

### Screenshots (if applicable)

![screenshot_20180815-220331](https://user-images.githubusercontent.com/6661478/44170280-268d3000-a0d7-11e8-911d-197534003c71.png)

### What have you tried

Googling for the answer makes it seem like the TextInput component simply does not support this, but this seems unlikely to me.

Any help is greatly appreciated, so thank you in advance!

### Your Environment

| software              | version
| --------------------- | -------
| android        | SDK 26
| react-native          | 16.3.1 
| react-native-paper    | ^1.11.1
| node                  |  v8.11.3
| npm or yarn           | 6.1.0

**Comment by gawrysiak** [comment]
hey,
try this:
```
<TextInput
  secureTextEntry
/>
```
