### ISSUE TITLE
[alpha] FAB elevation on press

### ISSUE THREAD

**Issue by luissmg** [callstack/react-native-paper#495]
### Current behaviour

When we press the FAB the elevation is always the same (12).

### Expected behaviour

The elevation should be 6 by default and should change to 12 while pressing. Check [this](https://material.io/design/environment/elevation.html#default-elevations)!

### Your Environment

| software              | version
| --------------------- | -------
| react-native-paper    | 2.0.0-alpha.7

I would be happy to contribute to this tonight. Can I do a PR with the changes? It would look like what was made for [Button](https://github.com/callstack/react-native-paper/blob/material-next/src/components/Button.js).

**Comment by Trancever** [comment]
Hi @luissmg That's definitely a bug, would be awesome if you could create PR.

**Comment by luissmg** [comment]
Sure. Was going to do this yesterday but had no time. Will make this today!

**Comment by brunohkbx** [comment]
Can you release it to the current version?
When a dialog is opened the FAB button doesn't change it elevation.
I worked around this problem by assigning 0 to elevation.

![whatsapp image 2018-08-25 at 00 16 32](https://user-images.githubusercontent.com/6487206/44614500-3655f400-a7fc-11e8-8d5e-d1beb10184f0.jpeg)

**Comment by luissmg** [comment]
@brunohkbk I don't think they will release a new beta version. I think the next one will be the official 2.0.
Maybe @Trancever could provide better info.

**Comment by brunohkbx** [comment]
It would be nice if they could merge this fix like they did with #476

**Comment by luissmg** [comment]
Even if they do that I don't think they would release another beta...
