### ISSUE TITLE
FAB ripple is wrong on Android P (everything that uses borderRadius)

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#500]
This is more a react-native issue that we need to keep track on. See https://github.com/facebook/react-native/issues/6480.

![screenshot_20180820-124834_2](https://user-images.githubusercontent.com/774577/44336424-b33d4280-a477-11e8-8335-3ddffadd4787.png)

**Comment by yaronlevi** [comment]
Duplicate:
https://github.com/facebook/react-native/issues/6480

**Comment by ferrannp** [comment]
Fixed #788 here. For 3.0 we might go with gesture handler.
