### ISSUE TITLE
[Feature Req] Outlined Button

### ISSUE THREAD

**Issue by stefensuhat** [callstack/react-native-paper#508]
Follow from this guidelines material.io, maybe you can add new outlined button variant and non uppercase label.

https://material.io/design/components/buttons.html#outlined-button

**Comment by stefensuhat** [comment]
@gawrysiak any major bugs on 2.0 branch? I want try to upgrade version to 2.0.

**Comment by satya164** [comment]
no major bugs, just need to finish redesigning some components :)

**Comment by satya164** [comment]
@gawrysiak you could pass `<Text>Something</Text>` currently and it won't be uppercased.
