### ISSUE TITLE
How to create a search toolbar?

### ISSUE THREAD

**Issue by brunohkbx** [callstack/react-native-paper#509]
Hello everyone.
I'm trying to create a search toolbar like youtube/whatsapp.
![whatsapp image 2018-08-28 at 16 48 08](https://user-images.githubusercontent.com/6487206/44746940-3991fe00-aae2-11e8-88a1-f38db78be747.jpeg)

I'm using react navigation and this is what I've done so far:

**routes.js**
```
export const RootStack =  createStackNavigator(
  {
    Main: {
      screen: Main,
      navigationOptions: {
        header: <SearchToolbar />
      }
    }
  },
  {
    initialRouteName: 'Main'
  }
);
```

**SearchToolbar.js**
```
import * as React from 'react';
import { View } from 'react-native';
import { Toolbar, ToolbarBackAction, ToolbarContent, ToolbarAction } from 'react-native-paper';
import { Searchbar } from 'react-native-paper';

export default class SearchToolbar extends React.Component {
  render() {
    return (
      <Toolbar>
        <Searchbar
          placeholder="Search"
          onChangeText={() => {}}
          icon="arrow-back"
        />
      </Toolbar>
    );
  }
}
```

How do I get rid of this padding/marging?
![whatsapp image 2018-08-28 at 16 48 08 1](https://user-images.githubusercontent.com/6487206/44747157-dce31300-aae2-11e8-9b2d-2e77a8b57401.jpeg)

Could someone create a snack with this feature?
Thanks :smile:

**Comment by Trancever** [comment]
How about this?
```
export default class SearchToolbar extends React.Component {
  render() {
    return (
        <Searchbar
          placeholder="Search"
          onChangeText={() => {}}
          icon="arrow-back"
        />
    );
  }
}
```

**Comment by brunohkbx** [comment]
Thanks, this is exactly what I did.
Styling the component with elevation 0 worked fine.
