### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#51]

**Comment by sanketsahusoft** [comment]
@satya164 Have you considered using Shoutem's UI library? It's pretty neat actually and we may be re-writing NativeBase using that.

**Comment by satya164** [comment]
@sanketsahusoft it's very nice, but it has a different design, which is more iOSy than material

**Comment by sanketsahusoft** [comment]
Oops! I actually meant [shoutem/theme](https://github.com/shoutem/theme) Not [shoutem/ui](https://github.com/shoutem/ui)

**Comment by satya164** [comment]
@sanketsahusoft Ah. On first look it looks very CSS-like. I kinda I prefer flat JS styles rather than CSS-like JS style. Neat concept, but it brings the same issues as normal CSS.

**Comment by sanketsahusoft** [comment]
@satya164 We are researching about the pros and cons of the same but our early experiments makes us confident on using it. We will make a final call by Wednesday. I will let you know if we do or don't go forward with it with whys.

**Comment by satya164** [comment]
@sanketsahusoft Cool. looking forward to it.

**Comment by satya164** [comment]
@luissmg can you create a proposal?

**Comment by luissmg** [comment]
Sure thing. Will send you an email with some questions about this

**Comment by kopax** [comment]
Hello, is this still of atuallity? I am starting with react-native and react-native-paper and I am building a native/web app. I have web experience, how should I design form with those tools?

**Comment by kopax** [comment]
I have implemented react final form with native and web, it work great with react native and if someone needs to see an example of implementation please let me know

**Comment by brodybits** [comment]
@kopax please post it, I think it can help others in the future.

General: I discovered Formik a few years ago, would be nice to see these things work together somehow.

**Comment by kopax** [comment]
@brodybits, this is an example form with `react-native-paper` and `react-final-form`:

```jsx
      <Form
        onSubmit={_onConfirmedPressed}
        render={({
          handleSubmit,
          form,
          submitting,
          pristine,
          values,
        }) => (
          <WebForm onSubmit={handleSubmit}>
            <Button
              type="submit"
              mode="contained"
              onPress={handleSubmit}
              loading={submitting}
              // disabled={submitting || pristine}
            >
              {t('form.submit')}
            </Button>
          </WebForm>
        )}
      />
```

With `_onConfirmedPressed` being the user submit action.

I have also created `WebForm.js`:

```jsx
import React, { Fragment } from 'react';
import { Platform } from 'react-native';

/** @component
 *
 * Web semantic require a <form> tag
 */
export default ({ onSubmit, ...rest }) => Platform.OS === 'web'
  ? <form onSubmit={onSubmit} {...rest} />
  : <Fragment {...rest} />;
```

This work fine, feel free to improve share or comment.
