### ISSUE TITLE
[V2] Desktop support (macOS & windows)

### ISSUE THREAD

**Issue by KevinGulj** [callstack/react-native-paper#513]
### Current behaviour
Currently the react-native-paper library is mostly platform-independent except ProgressBar.js, which has 3 child components:
ProgressBarComponent.android.js
ProgressBarComponent.ios.js
ProgressBarComponent.web.js

When I build to windows or macOS I would actually be able to use most of the components that react-native-paper provides since most of them consist of widely-implemented react-native components.

But since we are missing either ProgressBarComponent.js or ( ProgressBarComponent.windows.js and ProgressBarComponent.macos.js) the build instantly fails for not finding the appropriate file.

### Expected behaviour

We should add ProgressBarComponent.macos.js with the same export as .ios.js ( macOS supports the iOS progress-bar out of the box ).
And we should add a placeholder ProgressBarComponent.windows.js which exports atleast View component (maybe with a warning that it is not implemented yet) so it would not break all the other component usage possibilities.

### What have you tried

Right now I have not gotten my project( which is pretty big, and most of the problems are not related to react-native-paper) working with macOS yet, but Windows variant runs fine as long as I add ProgressBarComponent.windows.js file, since I am not using ProgressBar in my project I have no direct complications with that but if I would then I could use a Platform.OS specific component.

I would be happy to do a PR if you think it is a viable solution.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android or windows or macOS   | all of these
| react-native          | 0.55.4
| react-native-paper    | 2.0.0-alpha.7
| node                  | 10.9
| npm or yarn           | 6.2.0

**Comment by satya164** [comment]
Thanks for the report. Sounds good to me.
