### ISSUE TITLE
SUPPORT: Add for BottomNavigation

### ISSUE THREAD

**Issue by magworkss** [callstack/react-native-paper#516]
Hi

Please add PROPS for OPACITY in BottomNavigation.
Opacity calculated from  `const opacity = this.state.tabs[index];` and substituted in  `style={[StyleSheet.absoluteFill, { opacity }]}` which affects on all content and creates the blink/flash effect.
https://snack.expo.io/@avo/reactnavigation-issue

Thank you before hand

**Comment by satya164** [comment]
Try this:

```js
import React, { Component } from 'react';
import { DarkTheme, Provider as PaperProvider } from 'react-native-paper';
import MyTabs from './Navigation';

export default class App extends Component {
  render() {
    return ( 
      <PaperProvider theme={DarkTheme}><MyTabs /></PaperProvider>
    );
  }
}
```

This should set the background color of the actual screen to a dark color to avoid the flash. PR welcome to add the background color as an option in `react-navigation-material-bottom-tabs` since it's a missing feature there.

**Comment by magworkss** [comment]
@satya164 Thank you, it works
