### ISSUE TITLE
[2.0.0] TextInput not correct

### ISSUE THREAD

**Issue by giautm** [callstack/react-native-paper#529]
### Current behaviour

![image](https://user-images.githubusercontent.com/12751435/45045987-f9f98200-b09e-11e8-98ac-de692be8ead7.png)

### Expected behaviour

Show correct TextInput

![image](https://user-images.githubusercontent.com/12751435/45046007-0d0c5200-b09f-11e8-9991-70f5e5ef61ca.png)

### Code sample

Example from Docs: https://callstack.github.io/react-native-paper/text-input.html

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS 12-beta10, iPhone 5s.
| react-native          |  expo@29.0.0
| react-native-paper    | 2.0.0-beta.9
| node                  |
| npm or yarn           |

**Comment by satya164** [comment]
@giautm please try master. it should be fixed there.

**Comment by satya164** [comment]
@giautm we'll release a new version tomorrow

**Comment by giautm** [comment]
@satya164 I found another issues with TextInput label. In `outlined` mode, background color still `colors.background`, not `colors.white.`
```
                color: 'transparent',
                backgroundColor: colors.background,
                fontFamily,
                fontSize: MINIMIZED_LABEL_FONT_SIZE,
```
TextInput on the Surface.
![image](https://user-images.githubusercontent.com/12751435/45047640-d258e880-b0a3-11e8-87f6-da32b5301cad.png)

**Comment by satya164** [comment]
@giautm for now, you'll need to pass `theme={{ colors: { background: ... } }}` to override that. I'll update it to get the background from the style prop later.

**Comment by giautm** [comment]
Yeah, I really did that, tks for quickly response. 😄
