### ISSUE TITLE
[v2] - Searchbar render wrong layout with long text

### ISSUE THREAD

**Issue by giautm** [callstack/react-native-paper#530]
### Current behaviour

![image](https://user-images.githubusercontent.com/12751435/45092006-565fae80-b13e-11e8-9622-55d1b11173c4.png)

### Code sample

https://snack.expo.io/@giautm/searchbar-bug

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    |
| node                  |
| npm or yarn           |

**Comment by giautm** [comment]
I think that related to this fix: https://github.com/callstack/react-native-paper/commit/b573ea228bbb2150bb716a848de1642988e4b5da

**Comment by alvaromb** [comment]
Oops, didn't read that you've assigned it to yourself, @ferrannp 😝

**Comment by ferrannp** [comment]
I cannot reproduce this in a real device, only with the iPhone simulator if I click the Enter key of the computer keyboard. Does it happen on a real device @giautm ?

Default value of `TextIpunt` for `multiline` is already `false`.

**Comment by giautm** [comment]
@ferrannp: The screenshot attached was capture on real device, iPhone 5s.
