### ISSUE TITLE
Feature request: Avatar component

### ISSUE THREAD

**Issue by justinlawrence** [callstack/react-native-paper#531]
It would be great to be able to have a component for avatars, something similar to https://material-ui.com/demos/avatars/

Image avatars:
![screen shot 2018-09-05 at 15 32 16](https://user-images.githubusercontent.com/1521183/45100191-ebec4580-b120-11e8-8bd9-7b7211232bb9.png)

Icon avatars:
![screen shot 2018-09-05 at 15 32 20](https://user-images.githubusercontent.com/1521183/45100222-fc9cbb80-b120-11e8-8a05-14ad3a9e51ec.png)

Letter avatars:
![screen shot 2018-09-05 at 15 32 25](https://user-images.githubusercontent.com/1521183/45100236-032b3300-b121-11e8-85f3-d81e604b9ea8.png)

The props in their docs are great:
https://material-ui.com/api/avatar/

Pleeeeassee :)

Amazing work, everyone!

**Comment by jaulz** [comment]
I created something like that for my application. Maybe I will create a PR for that but otherwise you are of course invited to create a PR as well 😊

**Comment by gawrysiak** [comment]
Merged in [b68fac7](https://github.com/callstack/react-native-paper/commit/b68fac70b0b77a1338ff80ed69e8c1cb293c6337)
