### ISSUE TITLE
How to render a snackbar together with FAB?

### ISSUE THREAD

**Issue by brunohkbx** [callstack/react-native-paper#544]
Hello everyone.
Could someone provide me an example of how to render a snackbar above a FAB?
I'm trying to implement this [example](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1BlhZYfz9EClmRaSVq-sPLwyXVGEQKDlj%2Fsnackbars-layout-fab.png) from material.io. However this is what I've got :

![whatsapp image 2018-09-12 at 16 20 42](https://user-images.githubusercontent.com/6487206/45448860-f753e980-b6a9-11e8-8f41-d60b0efbbb2c.jpeg)

**Comment by satya164** [comment]
@brunohkbx when you have a FAB, you should add a bottom margin to the snackbar so it's rendered above the FAB: https://material.io/design/components/snackbars.html#placement

**Comment by Trancever** [comment]
@brunohkbx I see you are using paper v1.0 so snackbar should push up the fab when it appears. Currently we don't support it so you have to manually animate fab whenever visible prop of snackbar changes. In v2.0 snackbar was redesigned and the guidelines changed so the only thing user has to do is to add bottom margin to snackbar as Satya mentioned.
