### ISSUE TITLE
Can't adjust font size on TextInput

### ISSUE THREAD

**Issue by adamnator92** [callstack/react-native-paper#546]
### Current behaviour
Can't adjust font size of button text, textinput and text

### Expected behaviour
fontSize is adjustable

### What have you tried

| software              | version
| --------------------- | -------
| ios or android        | both
| react-native          | 16.4.1
| react-native-paper    | ^2.0.1
| node                  | v9.6.1
| npm or yarn           | 6.4.0

**Comment by ferrannp** [comment]
In `Text` should be possible passing `style={{ fontSize: 24 }}`.

**Comment by adamnator92** [comment]
Hi @ferrannp, Text component work fine,
how about fontSize of Button and TextInput?

**Comment by gluons** [comment]
Me too. I really need `fontSize` for `Button`.  
For now, `<Button style={{ fontSize: xx }}/>` doesn't work. It does not change button text size.

**Comment by ferrannp** [comment]
@gluons does it work if you wrap your own `Text` inside a `Button` ?

**Comment by gluons** [comment]
@ferrannp It seems to work partially. Text size changed but icon size isn't changed.  
And icon is misplaced. Button doesn't look great.

**Comment by bogdansoare** [comment]
The default font size is way to small for buttons, be able to customize the size of it I think it's mandatory for any reasonable ui kit 🙄

**Comment by ferrannp** [comment]
@bogdansoare, you can just do, for example:

```js
<Button onPress={() => {}}>
  <Text style={{ fontSize: 18 }}>Default</Text>
</Button>
```

For `TextInput` is more tricky as if you change the font size, all animations like labels would be broken. The `TextInput` component just needs much more work for supporting this.

**Comment by gluons** [comment]
@ferrannp It can change only button text. But icon size still really small. And it doesn't match text size.

Button icon size has been fix to `16`. And I'm unable to change icon size of button.

https://github.com/callstack/react-native-paper/blob/3765a079c82da022be8302d356a7d7ab73abc74f/src/components/Button.js#L254

**Comment by spyshower** [comment]
> For `TextInput` is more tricky as if you change the font size, all animations like labels would be broken. The `TextInput` component just needs much more work for supporting this.

So I wasted so many hours using paper and the most basic thing, font size, is not available? Why would anyone use this library then lol?

**Comment by Trancever** [comment]
@spyshower Just think about how many hours did you save by using Paper... If you are not happy with our library you can always send PR with improvements or make a fork and develop on your own.
