### ISSUE TITLE
Can't set Status Bar color of iPhone X when using AppBar.Header Component

### ISSUE THREAD

**Issue by echonox** [callstack/react-native-paper#553]
### Current behaviour

When Adding the AppBar the statusbar stays white on iPhone X

### Expected behaviour

When Adding the App Bar on iPhone X it should fill the status bar or at least there should be possible to change the color of the status bar, I use <SafeAreaView> setting a backgroundColor on the <SafeAreaView> colors the status bar but it also colors the content bellow the <AppBar>

### Code sample

`<Provider theme={theme}>
      <SafeAreaView style={{flex: 1, backgroundColor: '#fff'}}>
      <Appbar.Header style={styles.bottom}>
      <Appbar.Action icon="menu" size={36} onPress={() => console.log('Pressed archive')} />
      <Appbar.Content
        title="Klender"
      />
      <Appbar.Action icon="date-range" size={36} onPress={() => console.log('Pressed mail')} />
      <Appbar.Action icon="message" size={36} onPress={() => console.log('Pressed label')} />
      <Appbar.Action icon="playlist-add-check" size={36} onPress={() => console.log('Pressed delete')} />
    </Appbar.Header>
      </SafeAreaView>
    </Provider>
`

### Screenshots (if applicable)
![screen shot 2018-09-19 at 8 26 20 am](https://user-images.githubusercontent.com/9529847/45734764-f52be680-bbe5-11e8-8212-d59e46c65ca0.png)
![screen shot 2018-09-19 at 8 27 34 am](https://user-images.githubusercontent.com/9529847/45734782-0674f300-bbe6-11e8-858a-a84c020a90fa.png)

### What have you tried

I've tried increasing the height of the Header, setting a different backgroundColor to <SafeAreaView>, tried the react-native statusbar component

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios 11.4 Simulator iPhone X
| react-native          | 0.57.0
| react-native-paper    | 2.0.1
| node                  | v10.10.0
| npm or yarn           | yarn

**Comment by satya164** [comment]
It's because you're wrapping it in `SafeAreaView`. It's already done, you don't need to wrap again.

**Comment by echonox** [comment]
@satya164 Thanks it works!
