### ISSUE TITLE
Snackbar under Keyboard in iOS

### ISSUE THREAD

**Issue by fzyzcjy** [callstack/react-native-paper#555]
### Current behaviour

Thank you very much for this wonderful library! I am here to report a tiny bug :)

In iOS, if the keyboard is shown, and we trigger a snackbar, then that snackbar will be hidden under the keyboard. The only way to see it is to close the keyboard. (The version I use it material-next :) )

### Expected behaviour

The snackbar is shown above the keyboard, so the user can see it when keyboard is open.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    | material-next
| node                  |
| npm or yarn           |

**Comment by ferrannp** [comment]
Can you provide a Snack? I think this can be fixed without changes in the library.

**Comment by fzyzcjy** [comment]
OK I will do that asap. Could you plz give a template of snack?

**Comment by Trancever** [comment]
@fzyzcjy Here you go - https://snack.expo.io/SkYXN8iFX

**Comment by fzyzcjy** [comment]
OK I will do asap!

**Comment by fzyzcjy** [comment]
Here it is: https://snack.expo.io/@fzyzcjy/snackbar-under-keyboard
Actually, I find that it has the problem on *both android and iOS*.

**Comment by fzyzcjy** [comment]
@ferrannp @Trancever Hi the snack is posted above :) I am not sure whether you receive any notification from github so I manually at you again

**Comment by Trancever** [comment]
@fzyzcjy Yeah, we got notification, but we don't have much time to work on issues during weekend :) I'll take a look on it today.

**Comment by fzyzcjy** [comment]
@Trancever it does not matter :) have a good day!

**Comment by Trancever** [comment]
@fzyzcjy Check this - https://snack.expo.io/r1V_79g97

**Comment by satya164** [comment]
Why would you want to show a snackbar above the keyboard? There's already very little space when an input is focused.

**Comment by fzyzcjy** [comment]
@satys164 Hmmmm... Sounds reasonable! But I want to show some errors to notify users. There errors are irrelevant to input boxes so I cannot attach it to textinput. Thank you!

**Comment by satya164** [comment]
@fzyzcjy maybe you can show a red banner at top of the screen

**Comment by dassje** [comment]
Try this...

`<Snackbar wrapperStyle={{postion:"relative"}} ></Snackbar>`
