### ISSUE TITLE
Fab bad ui when using single fab

### ISSUE THREAD

**Issue by echonox** [callstack/react-native-paper#560]
### Current behaviour

Using just FAB without Group for single action renders the fab badly

### Expected behaviour

The <FAB> should be rendered in same way when using <FAB.Group>

### Code sample

`<Portal>
    <FAB
    small
    icon="add"
    onPress={() => console.log('Pressed')}
  />
</Portal>`

### Screenshots (if applicable)

![screen shot 2018-09-28 at 7 24 56 pm](https://user-images.githubusercontent.com/9529847/46223676-465d7800-c354-11e8-8606-270e6ab915ee.png)

### What have you tried

Tried without Portal but same bug only it renders it at bottom this time with same ui bug

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.57.0
| react-native-paper    | 2.0.1
| node                  | v10.11.0
| npm or yarn           | yarn

**Comment by echonox** [comment]
anyone?

**Comment by satya164** [comment]
sorry, this is weekend. that's how flexbox works by default. you can wrap the Fab in a view with `alignItems: center`

**Comment by echonox** [comment]
@satya164  so why does the fab render properly when using it with actions and not when using it as single fab

**Comment by satya164** [comment]
because it already has wrapper views which don't stretch it

**Comment by echonox** [comment]
@satya164  thanks for the suggestion fixed that issue, but now i can't have the fab above other elements, if I use <Portal> the fab doesn't justifyContent properly:

This is without <Portal>

Styles:

`alignSelf: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    margin: 16`

JSX:

<FAB
        style={styles.fab}
            icon="add"
            onPress={() => this.props.navigation.push('Secret')}
          />


Screenshot:

![screen shot 2018-10-02 at 2 25 52 pm](https://user-images.githubusercontent.com/9529847/46348463-61c7cc00-c64f-11e8-9e50-f2009b8fe0ec.png)


If I add Portal with same styles.fab for <FAB>:

`<Portal>
        <FAB
        style={styles.fab}
            icon="add"
            onPress={() => this.props.navigation.push('Secret')}
          />
        </Portal>`

Screenshot:

![screen shot 2018-10-02 at 2 28 28 pm](https://user-images.githubusercontent.com/9529847/46348513-8623a880-c64f-11e8-9f0c-70fd1896ff4f.png)


After Adding the portal the FAB doesn't respect the justifyContent

**Comment by Trancever** [comment]
@echonox Pass following style prop:
```js
{
  position: 'absolute',
  padding: 16,
  right: 0,
  bottom: 0
}
```

**Comment by echonox** [comment]
@Trancever tnx works!

**Comment by kylebarron** [comment]
In case anyone else comes across this issue, the snack two comments above no longer works, but after a couple hours I think I have `fab` and `fab.group` working over a map in a snack:
https://snack.expo.io/@kylebarron/fab-maps-portal
