### ISSUE TITLE
Wrong fontSize for Caption

### ISSUE THREAD

**Issue by vieiralucas** [callstack/react-native-paper#563]
Thank you for all the work you put into this library

### Current behaviour

Currently the fontSize for Caption is 14 
https://github.com/callstack/react-native-paper/blob/ce97029dc900f51b2c3f42335c20459e3688c5fe/src/components/Typography/Caption.js#L41-L47

### Expected behaviour

I expected it to be 12, according to material spec:
https://material.io/design/typography/the-type-system.html#

I can make a PR fixing this, I'm also interested in adding more Typography components like `Body1` `Body2`, all the `H1, H2, H3, etc.`

**Comment by ferrannp** [comment]
Go for it @vieiralucas !

**Comment by vieiralucas** [comment]
@ferrannp I just made a PR to that fixes this issue.
I plan to make more PRs adding more Typography components later if thats ok for you.
