### ISSUE TITLE
Snackbar action is not working

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [callstack/react-native-paper#567]
### Current behaviour

Snackbar action is not working

### Expected behaviour

close snackbar or other  function when click action buttons on snackbar

### Code sample

<Snackbar
            visible={this.state.visible}
            onDismiss={() => this.setState({ visible: false })}
            action={{
              label: 'Undo',
              onPress: () => {
                // Do something
                this.setState({ visible: false })     //<-- problem
              },
            }}
          >
            Hey there! I'm a Snackbar.
          </Snackbar>

**Comment by Trancever** [comment]
Hi @ManigandanRaamanathan Please check this working example on snack - https://snack.expo.io/H1cMtbz9X

**Comment by ManigandanRaamanathan** [comment]
Its still not working

**Comment by Trancever** [comment]
Did you try to run snack? Maybe can you provide us a small repository/snack that reproduces issue

**Comment by ManigandanRaamanathan** [comment]
@Trancever the below is the code:-
<Button
            onPress={() => this.setState(state => ({ visible: !state.visible }))}
          >
            {this.state.visible ? 'Hide' : 'Show'}
          </Button>
          <Snackbar
            visible={this.state.visible}
            onDismiss={() => this.setState({ visible: false })}
            action={{
              label: 'Undo',
              onPress: () => {
                this._goBack
              },
            }}
          >
            Hey there! I'm a Snackbar.
          </Snackbar>

the onPress is not executing the function. If repetitively press than sometime it work but still not right

**Comment by satya164** [comment]
You're not calling the function in your `onPress`. It should be:

```js
onPress: () => {
 this._goBack();
}
```

Notice the braces after `this._goBack`.

**Comment by ManigandanRaamanathan** [comment]
@satya164  Still something isn't right. The button only works after long press. Try it on your side and see. The ripple effect is not present as well. It multiple press to get the  ripple effect and to execute the function.

**Comment by satya164** [comment]
@ManigandanRaamanathan if you're connected to chrome debugger, disconnect it and try. debugger isn't reliable.

**Comment by ManigandanRaamanathan** [comment]
@Trancever @satya164  found where the bug is. It works only if you press below  the text. Its not working if you press on top of the text or top of it.

**Comment by Trancever** [comment]
@ManigandanRaamanathan Can you provide snack that reproduces issue? We can't help if we don't have repo that reproduces issue.

**Comment by satya164** [comment]
you can create a demo on https://snack.expo.io

**Comment by ManigandanRaamanathan** [comment]
@Trancever My app dont use expo tool. How to share on snack?

**Comment by ManigandanRaamanathan** [comment]
@satya164  @Trancever  I can share the file on zip for you to test them out.

**Comment by satya164** [comment]
sure

**Comment by ManigandanRaamanathan** [comment]
@Trancever @satya164  And there is also few seconds delays on the bottom tab bar? Do you know how to fix them?

**Comment by ManigandanRaamanathan** [comment]
@satya164  @Trancever  Any solution?

**Comment by ManigandanRaamanathan** [comment]
@Trancever @satya164  Found the bug. The Bottom Tab Navigator View was clashing with the snackbar. Now works perfectly. However, the snackbar is overlaying the bottom tab navigator

**Comment by Trancever** [comment]
@ManigandanRaamanathan You can pass style prop to snackbar with marginBottom. It should fix the issue.

**Comment by ManigandanRaamanathan** [comment]
@Trancever  Solution works perfectly. Thanks. Could please also answer the #570  and #569

**Comment by ManigandanRaamanathan** [comment]
@Trancever  how to reduce the delay time of the bottom tab navigator?

**Comment by Trancever** [comment]
@ManigandanRaamanathan It's explained in docs - https://callstack.github.io/react-native-paper/bottom-navigation.html

**Comment by ManigandanRaamanathan** [comment]
@Trancever  which part mentioning it? couldn't find

**Comment by Trancever** [comment]
renderScene and SceneMap

**Comment by ManigandanRaamanathan** [comment]
@Trancever  Will that reduce the delay in navigating the tabs?

**Comment by Trancever** [comment]
@ManigandanRaamanathan It should

**Comment by ManigandanRaamanathan** [comment]
@Trancever  its just  having code snippet and there not sample codes. Could you please share the example code with renderScene and Scenemap. I'm new to react native and currently using the top example code in the documentation page.

**Comment by ManigandanRaamanathan** [comment]
@Trancever  could you provide sample code for the tab navigation which you said would fix the delay issues

**Comment by Trancever** [comment]
@ManigandanRaamanathan You can find it in example app. It's placed in example directory.

**Comment by zikrulihsan** [comment]
zIndex:100 solve my problem
