### ISSUE TITLE
How to change the default theme colors and to add multiple secondary, tertiary of theme colors?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [callstack/react-native-paper#569]
### Current behaviour

How to change the default theme colors and to add multiple secondary, tertiary of theme colors? 

### Expected behaviour

Need options to store multiple theme colors (secondary theme, tertiary, quaternary, quinary, senary...) 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 
| react-native          |  0.57
| react-native-paper    | Latest
| node                  | Latest 10+
| npm or yarn           | Latest

**Comment by Trancever** [comment]
@ManigandanRaamanathan Please read our docs, you'll find lots of important informations there - https://callstack.github.io/react-native-paper/theming.html . According to multiple themes, prepared snack showing how to do it - https://snack.expo.io/@trensik/paper-theming-showcase

**Comment by robbiemu** [comment]
this answer really doesnt satisfy -- that documentation describes a themes object. but there apparently is one wired in at the start. it would be nice to understand, from the perspect of a new app with a few views that have rendered some things with default colors, what those colors are and how to inicrementally change them.
