### ISSUE TITLE
Need a list of all accessible icons

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [callstack/react-native-paper#570]
### Current behaviour

Need a list of all accessible icons. Currently there are not documentation available on your site on too check all the available icons and also on using our own custom icons.

### Expected behaviour

Provide us a list of icons we can use and also a instructions on how to use our own icons.

**Comment by satya164** [comment]
Please read our docs https://callstack.github.io/react-native-paper/icons.html.
We have a link to the list there: https://material.io/icons/

**Comment by ManigandanRaamanathan** [comment]
Thanks. found them already.

**Comment by AHMAD19858** [comment]
i need a link for the list!

**Comment by nguyenvanquan7826** [comment]
Please, I need a list of icon name.

**Comment by v4dkou** [comment]
To anyone looking for a list, I often refer to the list of icons from the library that `react-native-paper` depends on for the vector images themselves
https://oblador.github.io/react-native-vector-icons/

It's not clear to me how to choose the icon set though.

**Comment by smoqadam** [comment]
just a reminder that you can use TextInput.Icon component like this:
```js
import Icon from 'react-native-vector-icons/FontAwesome';
import {TextInput} from 'react-native-paper';
      <TextInput
        mode={'outlined'}
        label="Amount"
        value={text}
        keyboardType={'numeric'}
        left={<TextInput.Icon name={() => <Icon name={'usd'} size={20} />} />}
      />
```
if you're using FontAwesome, then you can check the icon list [here](https://oblador.github.io/react-native-vector-icons/)  (everything in FontAwesome section would be accessible)

**Comment by amitsharma-007** [comment]
MaterialCommunityIcons from https://oblador.github.io/react-native-vector-icons/

**Comment by lordi-byte** [comment]
React-native-paper requires the react-native-vector-icons library as mentioned here: https://callstack.github.io/react-native-paper/icons.html. 
If you use expo you don't need to install this library. If you use vanilla react-native you have to install this library yourself. The installation is described here: https://github.com/oblador/react-native-vector-icons#installation.

**Comment by tayyabrajpoot12** [comment]
> Please, I need a list of icon name.

https://callstack.github.io/react-native-paper/icons.html

in this link see See the list of supported icons
