### ISSUE TITLE
Dialog box not working. Error

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [callstack/react-native-paper#573]
### Current behaviour

It throws the below error when including <portal>
also throws error when including <paragraph>

I copied the entire code from your documentation and snack

### Code sample

import { Dialog, Paragraph, Portal } from 'react-native-paper';

<Dialog
            visible={this.state.visibleConfirm}
            onDismiss={this.closeDialog}>
            <Dialog.Content>
              <Paragraph>Are you sure want to delete this?</Paragraph>
            </Dialog.Content>
            <Dialog.Actions>
                <Button onPress={() => this.closeDialog()}>Cancel</Button>
                <Button onPress={() => this.closeDialog()}>Ok</Button>
            </Dialog.Actions>
          </Dialog>

### Screenshots (if applicable)

![screenshot_20181005-122446](https://user-images.githubusercontent.com/22089729/46516083-47356300-c89a-11e8-953a-39af63062320.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 
| react-native          | 0.57
| react-native-paper    | latest
| node                  | 10.*.. latest
| npm or yarn           | latest

**Comment by Trancever** [comment]
Read the docs please - https://callstack.github.io/react-native-paper/getting-started.html . Wrap your components tree with Provider component from Paper.

**Comment by TingAli** [comment]
I still get this error after wrapping with the Provider.

Any ideas

**Comment by Trancever** [comment]
@TingAli Please, provide [Snack](https://snack.expo.io/) that reproduces your issue.
