### ISSUE TITLE
How to add more properties to theme? 

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [callstack/react-native-paper#574]
### Current behaviour
 I would like to add custom colors for certain categories such as selected icons. But I don't want to set  them in each and every icons manually. Instead I would like to set a default icon color within the defaultTheme.js. But whenever I try to add my custom color component. It then throws error saying "Attempting to change the getter of an unconfigurable property".

### Expected behaviour

Is there any simpler solution?

**Comment by Trancever** [comment]
@ManigandanRaamanathan This error comes from Flow, right?

**Comment by ManigandanRaamanathan** [comment]
@Trancever  comes from react native when debug on device

**Comment by ferrannp** [comment]
@ManigandanRaamanathan can you provide code or a Snack ?

**Comment by ferrannp** [comment]
Closing in favour of #799.
