### ISSUE TITLE
Typescript - using withTheme is generating compilation errors when passing a function or a class as a parameter (2.1.0)

### ISSUE THREAD

**Issue by aaska** [callstack/react-native-paper#576]
### Current behaviour

Using the withTheme function with a class or a function generates the following error : 

`error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'Pick<ThemingType<Theme, DeepPartial<Theme>>, "withTheme">' has no compatible call signatures.

export default withTheme(MyComponent);`

### Expected behaviour

This should compile without problems (it was working fine in previous versions)

### Code sample

Sample from help documents generates the error : 

`import * as React from 'react';
import { withTheme } from 'react-native-paper';

function MyComponent(props) {
  const { colors } = props.theme;
  return <Text style={{ color: colors.primary }}>Yo!</Text>;
}

export default withTheme(MyComponent);`

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | both
| react-native          | 0.57.2
| react-native-paper    | 2.1.0
| node                  |  10.11.0
| npm or yarn           | 6.4.1
| typescript | 3.1.1
| tsc | 3.0.3

**Comment by satya164** [comment]
cc @Esemesek

**Comment by satya164** [comment]
We didn't have typescript definitions before.

Probably need `withTheme<Props>(MyComponent)`. We'll add docs soon.

**Comment by aaska** [comment]
@satya164 Thank you for your quick answer !

I've tried, but with no luck, still getting the same error message.

Also, I've noticed that I can't use props from root component in the TextInput (ie: autoCorrect, autoCapitalize, returnTypekey, keyboardType...), getting the issue : [ts] Property 'keyboardType' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<TextInput> & Readonly<{ children?: ReactNode; }> & Readonly<TextInputProps>'.

Should I create a new ticket for this ?

Anyway, thank you so much for the great work ! This library is really good !

**Comment by Esemesek** [comment]
I can confirm that this is a bug. I will fix it ASAP.
