### ISSUE TITLE
Typescript - using a withTheme component with FlatList props, it generates compilation errors

### ISSUE THREAD

**Issue by aaska** [callstack/react-native-paper#583]
### Current behaviour

When using a withTheme component for rendering inside a FlatList (props: renderItem, ListHeaderComponent), it generates a compilation error

```
[ts]
Type 'ComponentType<Pick<IProps, never> & DeepPartial<Theme>>' is not assignable to type 'ReactElement<any> | ComponentClass<any, any> | (() => ReactElement<any>)'.
  Type 'StatelessComponent<Pick<IProps, never> & DeepPartial<Theme>>' is not assignable to type 'ReactElement<any> | ComponentClass<any, any> | (() => ReactElement<any>)'.
    Type 'StatelessComponent<Pick<IProps, never> & DeepPartial<Theme>>' is not assignable to type '() => ReactElement<any>'.
``` 
### Expected behaviour

I believe it should be possible to use withTheme components for props in a FlatList

### Code sample

```
import * as React from "react";
import { TextInput, withTheme } from "react-native-paper";
import { FlatList } from "react-native";

interface IProps {
  theme: any;
}

class MyComponent extends React.Component<IProps> {
  state = {
    text: ""
  };

  render() {
    return (
      <TextInput
        label="Email"
        value={this.state.text}
        onChangeText={text => this.setState({ text })}
      />
    );
  }
}

class ShowFlatList extends React.Component {
  render() {
    return (
      <FlatList
        data={[1, 2, 3, 4]}
        ListHeaderComponent={withTheme(MyComponent)} // index.d.ts(3864, 5): The expected type comes from property 'ListHeaderComponent' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatList<number>> & Readonly<{ children?: ReactNode; }> & Readonly<FlatListProps<number>>'
        renderItem={withTheme(MyComponent)} // index.d.ts(3864, 5): The expected type comes from property 'ListHeaderComponent' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatList<number>> & Readonly<{ children?: ReactNode; }> & Readonly<FlatListProps<number>>'
      />
    );
  }
}

```

### Your Environment

software | version
-- | --
ios or android | both
react-native | 0.57.2
react-native-paper | 2.1.2
node | 10.11.0
npm or yarn | 6.4.1
typescript | 3.1.1
tsc | 3.0.3

**Comment by satya164** [comment]
Unrelated, but don't use `withTheme` inside the `render` function. It's an HOC, so it'll create a new component when called. It means a new component every render which will be very bad for perf, as well as lose any local state.

**Comment by aaska** [comment]
Hi @satya164 thank you very much for your quick reply ! 

This sample was mostly for example purposes to have everything inside one file, so it could be as quick as possible for you to test it :)

But thank you very much for the tip, it's always good to know !

**Comment by Esemesek** [comment]
I still need to merege #584, with new types for withTheme, but I think this is the problem of `@types/react-native` package. If you look closely on `FlatList` types (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L3849), properties aren't annotated with `React.ComponentType`, which has `React.ComponentClass` and `React.StatelessComponent` in it. `withTheme` returns `React.ComponentType` which is not compatible with `react-native` types.

**Comment by aaska** [comment]
I confirm, I've updated `@types/react-native@0.57.4` which has changed  `FlatList` types for `ListEmptyComponent`,`ListFooterComponent `and `ListHeaderComponent `  and it is now compiling without errors using `withTheme`.  All are now defined as `React.ComponentType<any> | React.ReactElement<any>;`

Thank you very much !

**Comment by Esemesek** [comment]
Fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29543 C:
