### ISSUE TITLE
Feature Request: Make BottomNavigation available without routing solution

### ISSUE THREAD

**Issue by dylancompanjen** [callstack/react-native-paper#585]
It would be nice if you could use <BottomNavigation> without a coupled routing solution. So that you could just pass a PressHandler & activeIndex and have your own routing solution.

I'm using a custom tabs implementation of React Navigation: https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js so I can add a custom view on top of my tabbar.
Unfortunately this is not possible with the standard way of using React Navigation: https://github.com/react-navigation/react-navigation-material-bottom-tabs

For e.g. like: https://github.com/timomeh/react-native-material-bottom-navigation (This library doesn't follow the latest Material Standards unfortunately).

**Comment by satya164** [comment]
Bottom Navigation doesn't need a routing solution. You can use it directly: https://callstack.github.io/react-native-paper/bottom-navigation.html
