### ISSUE TITLE
Issue when run on android after installing native in RN 0.55

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [callstack/react-native-paper#586]
### Current behaviour

Its not building the android app. Receiving error. Any compatibility in RN 0.55? 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | -
| react-native          | RN 0.55
| react-native-paper    | Latest
| node                  | Latest
| npm or yarn           | Latest

**Comment by ManigandanRaamanathan** [comment]
Getting this below error:-

![image](https://user-images.githubusercontent.com/22089729/46710359-0cf10a80-cc7a-11e8-9387-1f6c2c8eeaaf.png)

**Comment by Trancever** [comment]
@ManigandanRaamanathan It's not a problem with react-native-paper. Our example app uses react-native version 0.55 and it works fine. Can you provide full stack trace of the exception?
