### ISSUE TITLE
Update Flow types to use exact types.

### ISSUE THREAD

**Issue by Trancever** [callstack/react-native-paper#594]
### Current behaviour

Currently, user can pass additional props that are not specified for given component.

### Expected behaviour

User should be able to pass only those props that are explicitly specified in Props for a given component.

### Code sample

Current behaviour:

For given props:

```js
type Props = {
  value: string,
  onChange: (value: string) => mixed,
};
```

User can pass additional props. Example usage:

```js
<Component value="hello" onChange={value => {}} otherProp1={1} otherProp2="otherProp"  />
```

To prevent such behaviour we would like to declare props types to use exact type like that:

```js
type Props = {|
  value: string,
  onChange: (value: string) => mixed,
|};
```

**Comment by gawrysiak** [comment]
@Trancever it makes sense, but some people might not like it so much. Have you seen #477?

**Comment by satya164** [comment]
For components which pass down the props, we should be able to do something like this:

```js
type Props = React.ElementProps<View> & {
  // rest of the props
};
```

It'll also provide better type checking and autocomplete.
