### ISSUE TITLE
TextInput support Leading Icon

### ISSUE THREAD

**Issue by ButuzGOL** [callstack/react-native-paper#596]
Any plans for 
TextInput support Left Icon
or could you suggest as workaround to freeze label on the top in mode="outlined"

----
from @ferrannp: 

![screenshot 2019-01-31 at 13 13 41](https://user-images.githubusercontent.com/774577/52053584-0bfe2480-255a-11e9-81dd-171a6b0dd5f8.png)

**Comment by webdevsyd** [comment]
Agree to this hoping to get a support from this.

**Comment by Manoj002** [comment]
+1

**Comment by ferrannp** [comment]
Depending on https://github.com/callstack/react-native-paper/pull/587.

**Comment by viv3kk** [comment]
any update on this??

**Comment by jbinda** [comment]
Guys - good news :) Work is in progress ! It will be cover with PR posted to this issue: #903

**Comment by khanhubgit** [comment]
<TextInput
   ....
   left={<TextInput.Icon name="account"/>}
/>

**Comment by ignaciolopez12** [comment]
> <TextInput
> ....
> left={<TextInput.Icon name="account"/>}
> />

I only recognize the "account" icon, another does not recognize me ... how can I solve it?

**Comment by khanhubgit** [comment]
https://callstack.github.io/react-native-paper/icons.html

![Uploading 95650198...]

**Comment by khanhubgit** [comment]
> > <TextInput
> 
> > ....
> 
> > left={<TextInput.Icon name="account"/>}
> 
> > />
> 
> 
> 
> I only recognize the "account" icon, another does not recognize me ... how can I solve it?


https://callstack.github.io/react-native-paper/icons.html

![Uploading 95650213...]

**Comment by khanhubgit** [comment]
https://callstack.github.io/react-native-paper/icons.html

![D3DC08DC-4BEC-4A0C-ADE7-72D4AC21236C](https://user-images.githubusercontent.com/36913458/95650266-04976880-0afc-11eb-832a-ee796d75a088.png)

**Comment by khanhubgit** [comment]
> https://callstack.github.io/react-native-paper/icons.html
> 
> ![D3DC08DC-4BEC-4A0C-ADE7-72D4AC21236C](https://user-images.githubusercontent.com/36913458/95650266-04976880-0afc-11eb-832a-ee796d75a088.png)
