### ISSUE TITLE
How to add badge in App Drawer? 

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [callstack/react-native-paper#602]
### Current behaviour

How to add badge in App Drawer? Does React Native Paper has their own badge component? Else how to add custom badge? I'm following your snack example for the appdrawer

**Comment by raajnadar** [comment]
This page is to track issues you can ask this types of question in stackoverflow or quora!

**Comment by ManigandanRaamanathan** [comment]
@raajnadar  This feature is not even available in React Native Paper yet. This is more of a new required enhancement or additional support as about this feature is not even be found in their documentation nor known to others in stackoverflow or quora.

**Comment by ferrannp** [comment]
Probably good to be done after #620.

**Comment by raajnadar** [comment]
Here we go! https://callstack.github.io/react-native-paper/badge.html
