### ISSUE TITLE
Appbar hides on Android if TextInput focused

### ISSUE THREAD

**Issue by ButuzGOL** [callstack/react-native-paper#604]
When i am focusing text input and keyboard appears Appbar hides

have this property
android:windowSoftInputMode="adjustPan"

![demo](https://user-images.githubusercontent.com/196564/47025848-eb59bc80-d16c-11e8-8f0b-76b50d754eb6.gif)

**Comment by satya164** [comment]
Appbar doesn't hide, your screen moves up to place the input above the keyboard. It's not a bug in paper. You need to add `android:windowSoftInputMode="adjustResize"` in your `AndroidManifest.xml` to customize the behaviour.

https://developer.android.com/training/keyboard-input/visibility
