### ISSUE TITLE
Searchbar crashes on Android when wrapped in Appbar

### ISSUE THREAD

**Issue by bunea** [callstack/react-native-paper#605]
### Current behaviour

`Searchbar` component crashes on Android with 
`Error while updating property 'color' in shadow node of type: AndroidTextInput` 
when it's wrapped in `Appbar` or `Appbar.Header`.  I guess this happens because `Appbar` changes the theme based on the `dark` property. This works fine on iOS.

### Expected behaviour

Should not crash.

### Code sample
```js
class SearchContainer extends React.Component {
    render() {
        return (
            <Appbar.Header>
                <Searchbar
                    value=""
                />
            </Appbar.Header>
        )
    }
}
```

It seems to happen because of [this](https://github.com/callstack/react-native-paper/blob/master/src/components/Appbar/Appbar.js#L136) and [this](https://github.com/callstack/react-native-paper/blob/master/src/components/Searchbar.js#L165). `...rest` contains `color` prop, which crashes the `TextInput`.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 28
| react-native          | 0.57.1
| react-native-paper    | 2.1.3
| node                  | 10.11.0
| npm or yarn           | 1.10.1

**Comment by Trancever** [comment]
@bunea Please wrap Searchbar with additional View as a workaround:

```js
            <Appbar.Header>
              <View style={{ flex: 1 }}>
                <Searchbar
                    value=""
                />
              </View>
            </Appbar.Header>
```

**Comment by devdebajyotidas** [comment]
I'm still facing the same issue. Tried `yarn upgrade react-native-paper` to get the latest fix you merged but still crashes on Android. Is there any other way to get the latest source or am I missing something here? 

Thanks

**Comment by devdebajyotidas** [comment]
On a side note, wrapping it inside a view fixes the problem though. It'd better if we could avoid nesting.

**Comment by jaysbytes** [comment]
@devdebajyotidas This merge is not released yet. In a few days, we should release recent changes.
