### ISSUE TITLE
Portal component doesn't crash app

### ISSUE THREAD

**Issue by denisviklov** [callstack/react-native-paper#606]
### Current behaviour

Throw an error:
TypeError: Cannot read property 'mount' of null

This error is located at:
    in PortalConsumer (at Portal.js:53)
    in Portal (created by Context.Consumer)
    in ThemeProvider (created by Context.Consumer)
    in withTheme(Portal) (at topbar/index.js:18)
    in RCTView (at View.js:44)
    in Topbar (at src/index.js:23)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)
PortalConsumer.componentDidMount
    PortalConsumer.js:14:35
PortalConsumer.proxiedComponentDidMount
    createPrototypeProxy.js:61:39
commitLifeCycles
    ReactNativeRenderer-dev.js:12144:19
commitAllLifeCycles
    ReactNativeRenderer-dev.js:13495:6
Object.invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:92:9
invokeGuardedCallback
    ReactNativeRenderer-dev.js:306:30
commitRoot
    ReactNativeRenderer-dev.js:13701:6
completeRoot
    ReactNativeRenderer-dev.js:15269:2
performWorkOnRoot
    ReactNativeRenderer-dev.js:15197:8
performWork
    ReactNativeRenderer-dev.js:15090:6

### Expected behaviour

Work

### Code sample

import * as React from 'react';
import { Appbar, Modal, Portal, Text, Button, Dialog, Paragraph } from 'react-native-paper';
import { StyleSheet, View } from 'react-native';

export default class MyComponent extends React.Component {
  state = {
    visible: false,
  };

  _showDialog = () => this.setState({ visible: true });

  _hideDialog = () => this.setState({ visible: false });

  render() {
    return (
      <View>
        <Button onPress={this._showDialog}>Show Dialog</Button>
        <Portal>
          <Dialog
             visible={this.state.visible}
             onDismiss={this._hideDialog}>
            <Dialog.Title>Alert</Dialog.Title>
            <Dialog.Content>
              <Paragraph>This is simple dialog</Paragraph>
            </Dialog.Content>
            <Dialog.Actions>
              <Button onPress={this._hideDialog}>Done</Button>
            </Dialog.Actions>
          </Dialog>
        </Portal>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  bottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
});

### What have you tried

Nothing. This example from your docs on fresh app.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |android28
| react-native          |0.57.1
| react-native-paper    |2.1.3
| node                  |8.11.3
| npm or yarn           |1.10.1

**Comment by satya164** [comment]
You need to wrap your app root in `Provider`. Please follow the getting started guide: https://callstack.github.io/react-native-paper/getting-started.html

**Comment by denisviklov** [comment]
lol, wrong answer, I did 'provider'. from the test I got what I need wrap into Portal.Host. So, be careful when you close issue.

**Comment by Trancever** [comment]
@denisviklov https://snack.expo.io/@trensik/ZGlhbG
