### ISSUE TITLE
TextInput multiline not able to press in the middle 

### ISSUE THREAD

**Issue by ButuzGOL** [callstack/react-native-paper#612]
When we have textInput big size we are not able to press in the middle

![ezgif-5-478ba90b364e](https://user-images.githubusercontent.com/196564/47159349-55ea3400-d2f6-11e8-8f45-295cdb03d016.gif)

### Your Environment

| software              | version
| --------------------- | -------
| react-native-paper    | ^2.1.2

**Comment by satya164** [comment]
Please post your code
