### ISSUE TITLE
Allow user to define initial expanded state of List.Accordion

### ISSUE THREAD

**Issue by connercms** [callstack/react-native-paper#616]
### Current behaviour

Unless I am missing something in the code, currently all List.Accordion components are initialized with expanded state as false, but I think some users (myself included) would find it beneficial to have them begin opened.

### Expected behaviour

I think it would be as easy as setting the initial state as follows to allow user to define if the component should start as opened or closed
```
state = {
    expanded: this.props.expanded || false
  }
```

### Code sample

^

**Comment by jimmiehansson** [comment]
Sure, I can go ahead with this 👍

**Comment by jimmiehansson** [comment]
Sure I can go ahead and do this 👍

**Comment by Trancever** [comment]
Hi @connercms . Would you like to submit PR with a fix?

**Comment by bombillazo** [comment]
Is there any way to have a default open accordion *without* needing to control the component? I don't want to track a state variable just to have an initial state on the accordion group.

**Comment by ArnaudFeelbat** [comment]
@bombillazo Did you find a way to do it ?
