### ISSUE TITLE
Unable to set square/fixed ratio button. The button width remains the same.

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [callstack/react-native-paper#624]
### Current behaviour

Unable to set square/fixed ratio button. The button width remains the same. I'm trying to set the button into a circle shape. Therefore, I set the border radius to 100 and the width tried to have the same size as the height but the width is not changing for its current min width.

### Expected behaviour
Perfect circle button.

If I edit the minWidth, then the icon/content within the icon goes missing. Any optimal solution? OR is this a bug?

### Code sample

<Button mode="contained" onPress={()=>{}} style={{justifyContent: 'center', width: 20, height: 20 borderRadius: 100,}}>
       <Icon name={"md-close"} style={{fontSize: 22, color: '#fff' }}  />
</Button>
### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/22089729/47403781-72b2bb80-d77d-11e8-932d-c6ced331ec7e.png)

**Comment by Trancever** [comment]
First of all, it's not Ratio Button, it's just Button :D Check this component - https://callstack.github.io/react-native-paper/icon-button.html

**Comment by ManigandanRaamanathan** [comment]
Thanks. In the icon button component is it possible to have different ripple color instead of the icon color?

**Comment by Trancever** [comment]
No, this behaviour follows material design guidelines.
