### ISSUE TITLE
Out-of-the-box Chip text vertically misaligned

### ISSUE THREAD

**Issue by Caundy** [callstack/react-native-paper#625]
### Current behaviour

Text passed to chip is vertically misaligned (pushed to the bottom).

### Expected behaviour

Text should be vertically centered.

### Code sample
```js
 <ScrollView 
            horizontal={true}
            showsHorizontalScrollIndicator={false}
        >
            {categories.map(c=>(
                <Chip onPress={() => console.log('Pressed')}>Example Chip</Chip>
            ))}
</ScrollView>
```
### Screenshots (if applicable)

![chipmisalignment](https://user-images.githubusercontent.com/21174630/47418535-94f70a00-d77a-11e8-989c-5eacfe83e589.png)

### What have you tried

Also tried wrapping the text in a Text component, which doesn't change the behaviour, neither does using outlined mode. 
No such issue when using Button component from paper.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.50.3
| react-native-paper    | 2.0.1
| node                  |
| npm or yarn           | npm

**Comment by eeshaan** [comment]
bumping. seems like this is still an issue (#626 doesn't have the most optimal implementation either)
