### ISSUE TITLE
Hot Reloading is not support?

### ISSUE THREAD

**Issue by zxccvvv** [callstack/react-native-paper#632]
### Current behaviour

Changing text and save doesn't change while `Hot Reloading` is enabled

### Expected behaviour

Work like normal Hot Reloading

### Screenshots (if applicable)

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/19633881/47848664-a63ab900-de01-11e8-9a8c-8a397704440c.gif)

### What have you tried

- Re-installing using `run-android`
- Uninstall the apps and Re-install
- `react-native start --reset-cache`

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android Lolipop (Emulator BigNox)
| react-native          | 0.55.4
| react-native-paper    | ^2.1.3
| node                  | v8.9.1
| npm or yarn           | v6.4.1

**Comment by EmperorEarth** [comment]
I've been able to get non-functional components (i.e. `class Foo extends React.Component { ... }` hot-reloading with

- redux
- redux-saga
- react-navigation
- react-native-paper

functional components, however, never seem to cooperate

**Comment by ferrannp** [comment]
@zxccvvv this is not related to Paper. I think it's a problem in general with HMR and RN: https://github.com/facebook/react-native/issues/10991. You might need to check this one https://github.com/bvic23/babel-plugin-functional-hmr and see if it helps.
