### ISSUE TITLE
Unable to change font-family of textInput

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [callstack/react-native-paper#634]
### Current behaviour

Unable to change font-family of textInput. Tried setting the fontFamily through style. But not working

### Expected behaviour

Be able to set custom font's for text inputs

### What have you tried

Tried setting the fontFamily through style. But not working

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android 6.0
| react-native          | 0.57.0
| react-native-paper    | 2.1.3
| node                  | Latest
| npm or yarn           | Latest

**Comment by vieiralucas** [comment]
@ManigandanRaamanathan TextInput will pick the regular font from the theme. Check [this code](https://github.com/callstack/react-native-paper/blob/37d911118deddf30cfc369abca6d30bfc8c84b24/src/components/TextInput.js#L388)
So what you can do is pass the `font-family` through the `theme` props

```js
import * as React from 'react';
import { TextInput } from 'react-native-paper';

export default class MyComponent extends React.Component {
  state = {
    text: ''
  };

  render(){
    return (
      <TextInput
        label='Email'
        value={this.state.text}
        onChangeText={text => this.setState({ text })}
        theme={{ fonts: { regular: 'Apple Color Emoji' } }}
      />
    );
  }
}
```

**Comment by bijoycse** [comment]
Good work

**Comment by RuchikaPegasus** [comment]
import * as React from 'react';
import { TextInput } from 'react-native-paper';

export default class MyComponent extends React.Component {
  state = {
    text: ''
  };

  render(){
    return (
      <TextInput
        label='Email'
        value={this.state.text}
        onChangeText={text => this.setState({ text })}
fontFamily:"fontName"
      />
    );
  }
}

**Comment by erhanbicer** [comment]
> ```js
> import * as React from 'react';
> import { TextInput } from 'react-native-paper';
> 
> export default class MyComponent extends React.Component {
>   state = {
>     text: ''
>   };
> 
>   render(){
>     return (
>       <TextInput
>         label='Email'
>         value={this.state.text}
>         onChangeText={text => this.setState({ text })}
>         theme={{ fonts: { regular: 'Apple Color Emoji' } }}
>       />
>     );
>   }
> }
> ```

the following block of code worked💪🏻

```js
import * as React from 'react';
import { TextInput } from 'react-native-paper';

export default class MyComponent extends React.Component {
  state = {
    text: ''
  };

  render(){
    return (
      <TextInput
        label='Email'
        value={this.state.text}
        onChangeText={text => this.setState({ text })}
        fontFamily={"Apple Color Emoji"}
        theme={{ fonts: { regular: "" } }}
      />
    );
  }
}
```

**Comment by anabeatrizzz** [comment]
This code worked for me:
```javascript
<TextInput
  theme={
    {
      fonts: {
        regular: {
          fontFamily: 'Poppins-Regular'
        }
      }
    }
  }
/>
```

**Comment by RNtaate** [comment]
@anabeatrizzz Thank you very much. Took me a while before I found your solution.

**Comment by SubaZetifi** [comment]
Using the below code, Still facing the issue<TextInput
  theme={
    {
      fonts: {
        regular: {
          fontFamily: 'Poppins-Regular'
        }
      }
    }
  }
/>

**Comment by Suba13** [comment]
Using the below code, Still I couldn't change the fontFamily for my Textinput
<TextInput
  theme={
    {
      fonts: {
        regular: {
          fontFamily: 'ProximaNovaMedium'
        }
      }
    }
  }
/>

**Comment by mohcene25100** [comment]
I did all the previous solutions but no one worked for me. 
So after long search and attempts I finally achieved a solution 
just Add the **contentStyle** property with font family like below :

`
<TextInput
        label='Email'
        value={this.state.text}
        onChangeText={text => this.setState({ text })}
        contentStyle={{ fontFamily: "Montserrat" }}
      />
`

**Comment by Pajimo** [comment]
> I did all the previous solutions but no one worked for me. So after long search and attempts I finally achieved a solution **you just need to add the contentStyle property with font family like below :**
> 
> ```
> <TextInput
>      label='Email'
>        value={this.state.text}
>         onChangeText={text => this.setState({ text })}
>         contentStyle={{ fontFamily: "Montserrat" }}
>       />
> ```

This worked for me, thanks

**Comment by shubuu07** [comment]
contentStyle={{ fontFamily: "Poppins-Medium" }}

its worked for me

**Comment by kiing-dom** [comment]
@mohcenesegouat you are a G 🙏🏾.

anyone know how to change the label font?
