### ISSUE TITLE
Can List.Accordian start open with the user having the option to close it.

### ISSUE THREAD

**Issue by Imogynn** [callstack/react-native-paper#635]
Not really a bug, but a small request. Hope that's okay. Thanks for the awesome library.

### Current behaviour

No obvious option to have a list.accordian widget start open.

### Expected behaviour

Hoping there would be an optional open property that I could set to true.

**Comment by vieiralucas** [comment]
That use case seems very common, if maintainers think this is useful I can make a PR implementing this.

Also would be good if it was possible to use it like a "controlled component"
Maybe the user wants to open this accordion when anything else happens.
To allow this we need an API like the following:
```js
<List.Accordion open={this.state.open} onToggle={this.onToggle} />
```

https://reactjs.org/docs/forms.html#controlled-components

**Comment by vieiralucas** [comment]
Just realize that there is another issue opened with a PR related to this

I guess this is duplicated with #616
