### ISSUE TITLE
Keyboard hides input instead of placing it above

### ISSUE THREAD

**Issue by salvariable** [callstack/react-native-paper#636]
### Current behaviour

When input is focused it is being hidden by the keyboard; this is more noticeable on iOS than in Android.

### Expected behaviour

When input is focused, it should be placed over the keyboard... or maybe the screen should be moved upwards to leave space for the keyboard to show? :)

### Code sample

[Check out the snack :)
](https://snack.expo.io/@salvariable/register-for-lemon-pie)
### Screenshots (if applicable)

<img width="282" alt="captura de pantalla 2018-11-02 a la s 18 47 42" src="https://user-images.githubusercontent.com/20668079/47946330-d05aac80-decf-11e8-93cf-5f886557edda.png">

### What have you tried

I found [issue #555 ](https://github.com/callstack/react-native-paper/issues/555) and [issue #604 ](https://github.com/callstack/react-native-paper/issues/604) but cannot reproduce their solutions; I think there may be an issue with the component... or perhaps a more simple solution? :)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.57.1
| react-native-paper    | 2.0.1
| node                  |
| npm or yarn           |

**Comment by Trancever** [comment]
Use this component https://facebook.github.io/react-native/docs/keyboardavoidingview
