### ISSUE TITLE
[bug] build error occurred if using the version 2.2.0 and the switch component

### ISSUE THREAD

**Issue by yacut** [callstack/react-native-paper#642]
### Current behaviour

Build error occurred with version 2.2.0:

```sh
error: bundling failed: Error: Unable to resolve module `ReactNativeVersion` from `.../node_modules/react-native-paper/src/components/Switch.js`: Module `ReactNativeVersion` does not exist in the Haste module map
```
It is possible that the problem is in this code: https://github.com/callstack/react-native-paper/commit/4aa7addb87ed129e546974f6ebf6dee549bb4d90

### Expected behaviour

A project with react-native-paper build without an error.

### Code sample

[Snack example](https://snack.expo.io/?name=Switch&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fswitch.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20Switch%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aexport%20default%20class%20MyComponent%20extends%20React.Component%20%7B%0A%20%20state%20%3D%20%7B%0A%20%20%20%20isSwitchOn%3A%20false%2C%0A%20%20%7D%3B%0A%0A%20%20render()%20%7B%0A%20%20%20%20const%20%7B%20isSwitchOn%20%7D%20%3D%20this.state%3B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3CSwitch%0A%20%20%20%20%20%20%20%20value%3D%7BisSwitchOn%7D%0A%20%20%20%20%20%20%20%20onValueChange%3D%7B()%20%3D%3E%0A%20%20%20%20%20%20%20%20%20%20%7B%20this.setState(%7B%20isSwitchOn%3A%20!isSwitchOn%20%7D)%3B%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%2F%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D%0A)

### Screenshots (if applicable)

<img width="318" alt="screenshot 2018-11-06 at 08 36 15" src="https://user-images.githubusercontent.com/4711633/48049471-16995f80-e19f-11e8-9a57-8149bd684f16.png">

### Your Environment

```sh
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 180.89 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /var/folders/k9/4flyk9zs5ds9_qr79mk6mqfr0000gn/T/yarn--1541489863070-0.02963383312171719/node
      Yarn: 1.12.1 - /var/folders/k9/4flyk9zs5ds9_qr79mk6mqfr0000gn/T/yarn--1541489863070-0.02963383312171719/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react-native: 0.57.7 => 0.57.7 
      react: 16.5.1 => 16.5.1 
      react-native: 0.57.1 => 0.57.1 
      react-native-paper: 2.2.0
```

**Comment by luissmg** [comment]
Yes, I can confirm this. The commit by @satya164 broke the lib. Maybe installing that package fixes the problem.

**Comment by tzitziras** [comment]
Which is that package? And why isn't it in the dependencies?

**Comment by luissmg** [comment]
@tzitziras I don't what is the package. And it is not there because @satya164 forgot to add it. Just install the previous version, `2.1.3` and wait for a fix to then upgrade again 😃

**Comment by MrIceman** [comment]
Same issue.. Please Team of react-native-paper, please check the quality of your commits and contributors.

**Comment by luissmg** [comment]
Jesus! @MrIceman you must be perfect right? You never commit a bug before? Just wait for the fix! Can't you live with that?

**Comment by tzitziras** [comment]
fixed by @satya164 - see latest commit.
