### ISSUE TITLE
InputText : remove the underline in the outlined Type 

### ISSUE THREAD

**Issue by saharjedidi** [callstack/react-native-paper#663]
I want to remove the underline and to support the RTL 
I didn't find a solution to both so please help me 
this the code of TextInput 
<TextInput
         locale={this.state.locale}
        label=' رقم بطاقة التعريف الوطنية'
        Type='outlined'
        
        style={styles.TextInp}
        value={this.state.CIN}
        multiline = 'false'
        editable= 'true'
        onChangeText={CIN => this.setState({ CIN })}
        theme={{ colors: { placeholder: 'white', background: 'red', text: 'white', primary: 'white' }}}
![photo](https://user-images.githubusercontent.com/45098179/48761380-c5ae5e80-eca8-11e8-8ddd-9fe55ae4956b.png)

**Comment by saharjedid** [comment]
@raajnadar  i fix the problem 
i used Type='outlined'
but it's mode='outlined'
this is my fault
