### ISSUE TITLE
accessibility warning when use in `react-native-web`

### ISSUE THREAD

**Issue by geminiyellow** [callstack/react-native-paper#668]
### Current behaviour

use `FAB` in `react-native-web` , this warning show in console 

```shell
Warning: React does not recognize the `accessibilityElementsHidden` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `accessibilityelementshidden` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

    in div (created by Text)
    in Text (created by Icon)
    in Icon (created by Icon)
    in Icon (created by CrossFadeIcon)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by CrossFadeIcon)
    in div (created by View)
    in View (created by CrossFadeIcon)
    in CrossFadeIcon (created by FAB)
    in div (created by View)
    in View (created by TouchableHighlight)
    in div (created by View)
    in View (created by TouchableHighlight)
    in TouchableHighlight (created by TouchableRipple)
    in TouchableRipple (created by Context.Consumer)
    in ThemeProvider (created by Context.Consumer)
    in withTheme(TouchableRipple) (created by FAB)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by Surface)
    in Surface (created by Context.Consumer)
    in ThemeProvider (created by Context.Consumer)
    in withTheme(Surface) (created by FAB)
```

### Code sample

clean console

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/929878/48877744-ee208f00-ee47-11e8-84b9-83fad1646f58.png)

### What have you tried

create a new issue

### Your Environment

| software              | version
| --------------------- | -------
| react-native-web        | ^0.9.5
| react-native          | ^0.57.4
| react-native-paper    | ^2.2.6
| node                  |  v10.13.0
| npm            | v6.4.1

**Comment by geminiyellow** [comment]
hmm. ok , i update `what have i tried`,

have read the code, and know this warning is cause by `icon`, and i can use a `Icon` from `react-native-vector-icon` or a function to solve it.

code is here:

https://github.com/callstack/react-native-paper/blob/1d9340954fe7be000606798d7720fcffd6b538d7/src/components/Icon.js#L123

but when i use `string` source, i dont want to see the warning too.

if can , hope fix it.

**Comment by geminiyellow** [comment]
and same warning happen in `Card`

```
Warning: Received `true` for a non-boolean attribute `compact`.

If you want to write it to the DOM, pass a string instead: compact="true" or compact={value.toString()}.
    in div (created by Text)
    in Text (created by Text)
    in Text (created by Context.Consumer)
    in ThemeProvider (created by Context.Consumer)
    in withTheme(Text) (created by StyledText)
    in StyledText (created by Context.Consumer)
    in ThemeProvider (created by Context.Consumer)
    in withTheme(StyledText) (created by Paragraph)
    in Paragraph (created by CellRenderer)
    in div (created by View)
    in View (created by Card.Actions)
    in Card.Actions (created by CellRenderer)
    in div (created by View)
    in View (created by Card)
```

**Comment by Trancever** [comment]
Hi @geminiyellow Would you like to submit PR with a fix?

**Comment by eightyfive** [comment]
What's to fix?

Seems like a legit attribute (iOS only):
https://facebook.github.io/react-native/docs/accessibility#accessibilityelementshidden-ios

I have the same problem but I'm wondering if it's more `react-native-web` responsibility to fix this.

**Comment by eightyfive** [comment]
FYI

https://github.com/necolas/react-native-web/issues/1187

**Comment by geminiyellow** [comment]
opps, thanks all, waiting `rn4w`

**Comment by raajnadar** [comment]
Closed because this is not a react-native-paper bug!
