### ISSUE TITLE
Icons appear as white boxes

### ISSUE THREAD

**Issue by ViktorJH** [callstack/react-native-paper#675]
### What's currently happening?

[BottomNavigation example](https://callstack.github.io/react-native-paper/bottom-navigation.html) icons don't load, just show white boxes.

### What do you expect to happen? 

BottomNavigation example should display icons

### Code sample

`import * as React from 'react';
import { BottomNavigation, Text } from 'react-native-paper';

const MusicRoute = () => <Text>Music</Text>;

const AlbumsRoute = () => <Text>Albums</Text>;

const RecentsRoute = () => <Text>Recents</Text>;

export default class MyComponent extends React.Component {
  state = {
    index: 0,
    routes: [
      { key: 'music', title: 'Music', icon: 'queue-music' },
      { key: 'albums', title: 'Albums', icon: 'album' },
      { key: 'recents', title: 'Recents', icon: 'history' },
    ],
  };

  _handleIndexChange = index => this.setState({ index });

  _renderScene = BottomNavigation.SceneMap({
    music: MusicRoute,
    albums: AlbumsRoute,
    recents: RecentsRoute,
  });

  render() {
    return (
      <BottomNavigation
        navigationState={this.state}
        onIndexChange={this._handleIndexChange}
        renderScene={this._renderScene}
      />
    );
  }
}`

### Screenshots (if applicable)

https://imgur.com/a/yxcWE3U

### What have you tried

Tried four devices, iOS, android and online Expo emulator.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | expo.io snack
| react-native          | expo.io snack
| react-native-paper    | expo.io snack
| node                  | expo.io snack
| npm or yarn           | expo.io snack

**Comment by satya164** [comment]
Yeah, icons are broken on Snack for some reason. Need to investigate why. They work fine locally though.
