### ISSUE TITLE
Put three FAB in a row.

### ISSUE THREAD

**Issue by zRelux** [callstack/react-native-paper#678]
I tried to display three FAB in a row but instead, they went on a new line. Another question is there anyway to display the text under the icon like youtube's button?

### Current behaviour

Each FAB takes a line.

### Expected behaviour

Three FAB displayed in a row.

### Code sample

```
<FAB
    small
    style={styles.fab}
    onPress={this.showDrawer}
    color="black"
    icon="dehaze"
    label={serie.nEpisodi}
/>
<FAB
    small
    style={styles.fab}
    onPress={this.showDrawer}
    color="black"
    icon="dehaze"
/>
<FAB
    small
    style={styles.fab}
    onPress={this.showDrawer}
    color="black"
    icon="dehaze"
/>
```

### Screenshots (if applicable)

![image-1](https://user-images.githubusercontent.com/23509971/49004339-fafcf580-f15b-11e8-8a1a-0a28f95fc94b.jpg)

### What have you tried

I tried using some helper components that would display them in a row

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |   ios.12
| react-native           |   16.5.0
| react-native-paper|2.2.8
| node                     | v10.8.0      
| npm or yarn          | yarn

**Comment by raajnadar** [comment]
Hey, Paste a issue reproducing snack

**Comment by luissmg** [comment]
Hey. You should wrap the `FAB`'s is a `View` and style it accordingly.
