### ISSUE TITLE
Helper Text not work with TextInput Outlined

### ISSUE THREAD

**Issue by sritharanpalani** [callstack/react-native-paper#679]
### Current behaviour
I am using TextInput with Mode="outlined" and helper text, if helper text appear it does not change the textinput color as per the design in the React native paper

### Expected behaviour

Color needs to be changed as per in the design doc , (TextInput color changed to red in case helper text shows )

### Your Environment

| software              | version
| --------------------- | -------
| react-native          | 0.57.4
| react-native-paper    | 2.1.3

**Comment by satya164** [comment]
Can you post a repro on https://snack.expo.io?

**Comment by sritharanpalani** [comment]
https://snack.expo.io/@sritharan04/try-out-paper-error

**Comment by sritharanpalani** [comment]
@satya164 i found that , i got that changing the error mode by using property call error on TextInput
