### ISSUE TITLE
App crash when render barcode

### ISSUE THREAD

**Issue by jason7toxic** [callstack/react-native-paper#681]
### Current behaviour

Initially my app running smoothing with barcode render perfectly, but after install react-native-paper and try to import a component, my app crashed, please help

I'm using this library to render the barcode --> react-native-barcode-pdf417

After import provider, app crashed.
`import { Provider as PaperProvider } from "react-native-paper";`

![screenshot_1543250993](https://user-images.githubusercontent.com/9715369/49029179-f75e8280-f1de-11e8-8cf0-dc37d3051175.png)

### Expected behaviour

![screenshot_1543251055](https://user-images.githubusercontent.com/9715369/49029192-fe859080-f1de-11e8-92f8-124006afed2d.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.57.5
| react-native-paper    | ^2.2.7
| node                  | v11.1.0
| npm or yarn           | 6.4.1(npm), 1.12.3 (yarn)

**Comment by satya164** [comment]
Can you post the full code?

**Comment by jason7toxic** [comment]
@satya164 
Kindly refer this repo for demo .. thanks
[https://github.com/jason7toxic/testApp](url)

**Comment by satya164** [comment]
Seems to work fine for me: https://snack.expo.io/ryD1njKAX

**Comment by satya164** [comment]
You can run `adb logcat` in a terminal to see the crash logs.

**Comment by jason7toxic** [comment]
@satya164 Is that possible due to I'm building with native code?

**Comment by satya164** [comment]
Impossible to tell without crash log.

**Comment by jason7toxic** [comment]
@satya164 Is this the crash log .. sorry not familiar with adb logcat

https://raw.githubusercontent.com/jason7toxic/testApp/master/log.txt

**Comment by jason7toxic** [comment]
Simulated using expo cli, working fine .. need help on native code.

Thanks

**Comment by jason7toxic** [comment]
@satya164 Re-upload full native build source, sometime prompt this error instead of app crash now.

https://github.com/jason7toxic/testApp

![screenshot_1543292133](https://user-images.githubusercontent.com/9715369/49058323-7a62f580-f23e-11e8-821c-8a8916d6d330.png)
