### ISSUE TITLE
Feature request: Customisable numberOfLines for List.Item

### ISSUE THREAD

**Issue by abn-volk** [callstack/react-native-paper#686]
### Current behaviour

`List.Item`'s title and description texts/components are [wrapped inside a `Text` with fixed `numberOfLines`](https://github.com/callstack/react-native-paper/blob/0ad98f3bf2c397c12e258927b5bdd504ebf9f275/src/components/List/ListItem.js#L97). As a result, long text elements are always cut off (even when using custom text components with `numberOfLines` set).

### Expected behaviour

It'd be better if there is a way to customise the `numberOfLines` for item title/description, or at least a way to disable the default behaviour. I know that I can easily replace `List.Item` with a `View`, but I'd like to use `List.Item` for its standard padding/margin and ripple.

### Code sample
Snack: https://snack.expo.io/@jibi/react-native-paper-list.item-numberoflines

### Screenshots (if applicable)
![Imgur](https://i.imgur.com/J4MQOJ2.png)

### What have you tried

* Use a `Subheading` for title with `numberOfLines`
* Read the source code -> Write a feature request

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android
| react-native          | 0.57 (expo 31)
| react-native-paper    | 2.3.1
| node                  | 10.2.1
| npm or yarn           | yarn 1.12.3

**Comment by raajnadar** [comment]
The feature that you are asking is not under material design guidelines. Can tell me what are you trying to do? Maybe I can give you a better alternative solution.

**Comment by abn-volk** [comment]
I wanted to show some list items with long text, but the text is always cut off. I've switched to a View and it's working fine now. 

Oh, and I didn't realise the 3 line limitation is to comply with the MD guideline. I'll close this then.

**Comment by tonyxiao** [comment]
@raajnadar sometimes guidelines do not correspond to the reality of the data we're trying to present to users.

**Comment by tonyxiao** [comment]
What alternative would you recommend for a list item that takes a few lines?

**Comment by zerobytes** [comment]
I must disagree with @raajnadar and say that the implementation that took place on list item does not corresponde to the guidelines, itself.

Material guideline is very clear on giving 3 independent lines or 2 lines and the last can grow wrapping down.
![image](https://user-images.githubusercontent.com/439445/54005847-c4128480-4139-11e9-8db4-4c377e543ed8.png)

**Comment by raajnadar** [comment]
Ok Ok, I am opening this issue again..!

**Comment by satya164** [comment]
We do support 3 line list items. 3 lines don't mean there should be a 3rd prop. It just means that the total number of lines can be 3, as in your screenshots.

![image](https://user-images.githubusercontent.com/1174278/54023675-d4584d00-4195-11e9-9534-23e08484325f.png)

**Comment by Yajan** [comment]
Is it possible to have max of 1 line in the list

**Comment by brunohkbx** [comment]
#996 will make us be able to customize the description prop of `List.Item`

**Comment by ferrannp** [comment]
Fixed.
