### ISSUE TITLE
No way to change underline focused color on TextInput without affecting other colors

### ISSUE THREAD

**Issue by lamecksilva** [callstack/react-native-paper#688]
I tried to change the cursor color in the textinput but it appears to underline, how to disable the underline? or leave it transparent?

**Comment by satya164** [comment]
Can you give some more info on what you did?

**Comment by lamecksilva** [comment]
#### I want remove this underline color from text input, but the prop "underlineColor" is not working

![screenshot_2018-12-02_14-34-54](https://user-images.githubusercontent.com/31391753/49342881-6b65b400-f63f-11e8-9bcb-54e31faddd20.png)

**Comment by ferrannp** [comment]
Right now the underline when focused uses this logic:

https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput.js#L547-L549

The problem is that you cannot change only that color without affecting the whole TextInput. Moreover, we need more docs on all this, see #775.

**Comment by tinni95** [comment]
still no solution for this??
I would like my textInput to have a customized underline color when focused, cannot change the purple, is there a way to change globally the color used by this plugin??

**Comment by poptocrack** [comment]
Any update on this issue?

**Comment by douglasjunior** [comment]
How to remove the underline without affect text colors?

**Comment by satya164** [comment]
If you don't want a material design themed input, use the input from React Native and apply the styling you want https://facebook.github.io/react-native/docs/textinput

**Comment by douglasjunior** [comment]
I just don't want to have the "underline", but the animated label and everything else I'd like to have.

Unfortunately not every design follows 100% of Material Design. (I have never worked on a project that meets 100% of the recommendations)

To whom it may concern, to "hide" the "underline", I followed this workaround.

```jsx
const styles = StyleSheet.create({
    inputContainer: {
        borderRadius: 4,
        height: 55,
        overflow: 'hidden',
    },
    input: {
        borderRadius: 0,
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
        height: 57,
        overflow: 'hidden',
        backgroundColor: '#fff',
    },
};
...
<View style={styles.inputContainer}>
       <TextInput
            mode="flat"
            label="Username"
            style={styles.input}
        />
</View>
```

Note that Input is 2 pixels bigger than View.

![mrocto](https://user-images.githubusercontent.com/1512341/68532727-ba13d780-02ff-11ea-8891-96c7b61f7df0.gif)

**Comment by KangHyoMun12** [comment]
You can use theme={{
                        colors: {
                            primary: color,
                        }
                     }}

**Comment by EhtishamAli786** [comment]
> I just don't want to have the "underline", but the animated label and everything else I'd like to have.
> 
> Unfortunately not every design follows 100% of Material Design. (I have never worked on a project that follow 100% of the recommendations)
> 
> To whom it may concern, to "hide" the underline I followed this workaround.
> 
> ```js-jsx
> const styles = StyleSheet.create({
>     inputContainer: {
>         borderRadius: 4,
>         height: 55,
>         overflow: 'hidden',
>     },
>     input: {
>         borderRadius: 0,
>         borderTopLeftRadius: 0,
>         borderTopRightRadius: 0,
>         height: 57,
>         overflow: 'hidden',
>         backgroundColor: '#fff',
>     },
> };
> ...
> <View style={styles.inputContainer}>
>        <TextInput
>             mode="flat"
>             label="Username"
>             style={styles.input}
>         />
> </View>
> ```
> 
> Note that Input is 2 pixels bigger than View.
> 
> ![mrocto](https://user-images.githubusercontent.com/1512341/68532727-ba13d780-02ff-11ea-8891-96c7b61f7df0.gif)

I know its not answer, but it solves

**Comment by mateusmarinho1999** [comment]
To change the Underline and Label color when focused, you need to pass the props **theme**, like this:

**theme={{colors: {text: 'green', primary: 'yellow'}}}** 

- _Text_ is to change the values that you put in the input
- _Primary_ is to change the underline and the label color

**Comment by ilhamsa1** [comment]
any update?

**Comment by tinni95** [comment]
The problem

> To change the Underline and Label color when focused, you need to pass the props **theme**, like this:
> 
> ```
>         <TextInput
>             label='Password'
>             underlineColor='#fff'
>             theme={{colors: {text: 'green', primary: 'yellow'}}}
>           />
> ```
> 
> * _Text_ is to change the values that you put in the input
> * _Primary_ is to change the underline and the label color

the problem is when I want to have two different colors for the label and the underline when focused, which apparently is not possible 👎

**Comment by tinni95** [comment]
My workaround has been the following :

`      <TextInput
                label='Email'
                value={email}
                placeholder={"email"}
                onChangeText={text => setEmail(text)}
                style={{ backgroundColor: "white" }}
                selectionColor={Colors.primary}
                underlineColor={"white"}
            />
            <View style={{ marginTop: -2,borderTopColor: "white", borderTopWidth: 10 }} />`

I basically added a view after the textinput with the desired borderTopColor to cover the undesired one from the textinput

**Comment by tinni95** [comment]
My workaround has been the following :

`      <TextInput
                label='Email'
                value={email}
                placeholder={"email"}
                onChangeText={text => setEmail(text)}
                style={{ backgroundColor: "white" }}
                selectionColor={Colors.primary}
                underlineColor={"white"}
            />
            <View style={{ marginTop: -2,borderTopColor: "white", borderTopWidth: 10 }} />`

I basically added a view after the textinput with the desired borderTopColor to cover the undesired one from the textinput

**Comment by jkjellan** [comment]
Following EhtishamAli786's advice (i.e. setting overflow: 'hidden'), but instead setting bottom margin of TextInput to -2 also works to hide the underline when in focus

**Comment by Evilbits** [comment]
+1 also looking for a way to solve this issue.

**Comment by belgamo** [comment]
I think changing only the underline color breaks the [material's guidelines](https://material.io/components/text-fields). But, [here](https://github.com/callstack/react-native-paper/pull/1797) is a possible solution.

**Comment by douglasjunior** [comment]
> I think changing only the underline color breaks the [material's guidelines](https://material.io/components/text-fields). But, [here](https://github.com/callstack/react-native-paper/pull/1797) is a possible solution.

I never worked on a project that follows 100% of material design guildelines. There will always be something that needs to be customized.

The question is: In React Native we do not have the option to override a CSS class as we do on the web, so it is important that libraries offer a certain level of customization.

A simple property that allows customization of the style is enough.

**Comment by AbdelkhalekESI** [comment]
In addition to @douglasjunior solution, I have added a negative marginBottom value -3 to the text input and that's works perfectly!

**Comment by xchwarze** [comment]
This issue is already open... please aprove https://github.com/callstack/react-native-paper/pull/1797 for close this

**Comment by dcangulo** [comment]
I need to hide the underline color as I will replace it with the progress bar.

Adding `theme={{ colors: { primary: 'transparent' } }}` will remove the underline but also the label which is not intended.

Here is my use case:
https://snack.expo.io/@dcangulo/password-with-progress-bar

**Comment by sorxrob** [comment]
> I need to hide the underline color as I will replace it with the progress bar.
> 
> Adding `theme={{ colors: { primary: 'transparent' } }}` will remove the underline but also the label which is not intended.
> 
> Here is my use case:
> https://snack.expo.io/@dcangulo/password-with-progress-bar

Any update?

**Comment by rhuankarlus** [comment]
There isn't a way to completely remove the underline? Even with a container with hidden overflow I really need vertically grouped inputs with no underline at all.

**Comment by renanborgez** [comment]
The solution from @mateusmarinho1999 works very nicely, but feels kinda hacky for me. We are chaging the primary color of the input, and what if something else now/or in future start using the primary color?

Ideally some way to specifically change the color of the underline would be better

**Comment by xchwarze** [comment]
this is fixed in https://github.com/callstack/react-native-paper/pull/1797

**Comment by HassanHaiderIX** [comment]
> this is fixed in #1797

is this working?

**Comment by renanborgez** [comment]
> > this is fixed in #1797
> 
> is this working?
@HassanHaiderIX 
Yes, I'm currently using this on my code and works like a charm

**Comment by HassanHaiderIX** [comment]
Sorry for being naive but I dont see that PR being merged. I am not sure
how can I hide underline color

**Comment by HassanHaiderIX** [comment]
> > > this is fixed in #1797
> > 
> > 
> > is this working?
> 
> @HassanHaiderIX
> Yes, I'm currently using this on my code and works like a charm

Sorry for being naive but I dont see that PR being merged. I am not sure
how can I hide underline color

**Comment by renanborgez** [comment]
> > > > this is fixed in #1797
> > > 
> > > 
> > > is this working?
> > 
> > 
> > @HassanHaiderIX
> > Yes, I'm currently using this on my code and works like a charm
> 
> Sorry for being naive but I dont see that PR being merged. I am not sure
> how can I hide underline color

I might have been a bit unclear, sorry
The underlinecolor feature exists already, what is being added with that PR is the possibility to add colors to different state of the input.

as you can see in this diff bellow got from the PR
![image](https://user-images.githubusercontent.com/1863024/105361067-95043f80-5bf9-11eb-8518-e77085faeb39.png)

**Comment by renanborgez** [comment]
> > > > this is fixed in #1797
> > > 
> > > 
> > > is this working?
> > 
> > 
> > @HassanHaiderIX
> > Yes, I'm currently using this on my code and works like a charm
> 
> Sorry for being naive but I dont see that PR being merged. I am not sure
> how can I hide underline color

sorry, I'm using but not from the release channel, I've just implemented that PR by myself on my code

**Comment by dhaulathu** [comment]
If you don't need the underline at all, you can change the source code at 'node_modules/react-native-paper/src/components/TextInput/TextInputFlat.tsx' like I have done below (comment the height of the underline):

![image](https://user-images.githubusercontent.com/70067457/112338284-7fd28c80-8ce0-11eb-954b-848691b503a3.png)

And it disappears forever :)

P.S.: the lines might differ from version to version, just find the styles constant or search for "underline".

**Comment by OrLevy23** [comment]
> > I just don't want to have the "underline", but the animated label and everything else I'd like to have.
> > Unfortunately not every design follows 100% of Material Design. (I have never worked on a project that follow 100% of the recommendations)
> > To whom it may concern, to "hide" the underline I followed this workaround.
> > ```
> > const styles = StyleSheet.create({
> >     inputContainer: {
> >         borderRadius: 4,
> >         height: 55,
> >         overflow: 'hidden',
> >     },
> >     input: {
> >         borderRadius: 0,
> >         borderTopLeftRadius: 0,
> >         borderTopRightRadius: 0,
> >         height: 57,
> >         overflow: 'hidden',
> >         backgroundColor: '#fff',
> >     },
> > };
> > ...
> > <View style={styles.inputContainer}>
> >        <TextInput
> >             mode="flat"
> >             label="Username"
> >             style={styles.input}
> >         />
> > </View>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note that Input is 2 pixels bigger than View.
> > ![mrocto](https://user-images.githubusercontent.com/1512341/68532727-ba13d780-02ff-11ea-8891-96c7b61f7df0.gif)
> 
> I know its not answer, but it solves



> I just don't want to have the "underline", but the animated label and everything else I'd like to have.
> 
> Unfortunately not every design follows 100% of Material Design. (I have never worked on a project that follow 100% of the recommendations)
> 
> To whom it may concern, to "hide" the underline I followed this workaround.
> 
> ```js
> const styles = StyleSheet.create({
>     inputContainer: {
>         borderRadius: 4,
>         height: 55,
>         overflow: 'hidden',
>     },
>     input: {
>         borderRadius: 0,
>         borderTopLeftRadius: 0,
>         borderTopRightRadius: 0,
>         height: 57,
>         overflow: 'hidden',
>         backgroundColor: '#fff',
>     },
> };
> ...
> <View style={styles.inputContainer}>
>        <TextInput
>             mode="flat"
>             label="Username"
>             style={styles.input}
>         />
> </View>
> ```
> 
> Note that Input is 2 pixels bigger than View.
> 
> ![mrocto](https://user-images.githubusercontent.com/1512341/68532727-ba13d780-02ff-11ea-8891-96c7b61f7df0.gif)


it's a bit dirty hack but made got me an idea and it might be bit better  (added -2 marginBottom) this how the height is dynamic
![image](https://user-images.githubusercontent.com/21291210/131710205-305a1593-478d-432f-aa3d-92b00fe23d2d.png)

**Comment by gideonip** [comment]
Add `theme={{ colors: { primary: 'transparent' } }}` and `selectionColor="black"` to bring back the cursor color back without underline

**Comment by Hasintha-git** [comment]
This is way to solved this problem 

*  underlineColor="transparent"

<TextInput
                    placeholder="Write something with multilines  here.."
                    underlineColor="transparent"
                    theme={{ colors: { primary: 'transparent' } }}
                    style={{
                      maxHeight:300,
                      backgroundColor:'none',
                      width:'100%',
                    }} 

 />

**Comment by johanjq** [comment]
hey @Hasintha-git the problem still persists though, if you want to add a label it won't be visible as color 'transparent' get's applied on the label as well. I can confirm the issue is still there on 4.12.0. does anybody have idea how to resolve this?

**Comment by phanithken** [comment]
How to change only underline color but not the cursor color in iOS?

**Comment by kholidanas27** [comment]
underlineStyle={{
          display: 'none',
        }}

**Comment by lucksp** [comment]
such a hacky component library...

```
            theme={{ colors: { primary: 'transparent' } }}
            underlineColor="transparent"
```
only works for me

**Comment by BerkayAkgurgen** [comment]
```
 underlineStyle={{
        borderColor: "transparent",
        backgroundColor: "transparent",
        opacity: 1,
      }}
```

**Comment by xchwarze** [comment]
Stop being idiots answering an issue from 2018. There was no way to do this in 2018!

**Comment by AnshulAppinventiv** [comment]
Try this:-
<TextInput
                label={'Phone Number'}
                style={styles.phoneNumberInput}
                keyboardType="phone-pad"
                onChangeText={this.handlePhoneNumberChange}
                value={this.state.phoneNumber}
                underlineStyle={{
                  display: 'none',
                }}
                theme={{
                  colors: {
                    primary: 'black',
                  },
                }}
                
            And the line will be invisible.
             underlineStyle={{
                  display: 'none',
                }}
