### ISSUE TITLE
Ability to disable FAB Group overlay when open

### ISSUE THREAD

**Issue by sido378** [callstack/react-native-paper#690]
### Current behaviour

When a FAB.Group is opened, there is an overlay preventing taps on the rest of the UI.

### Expected behaviour

I would like to be able to decide whether I want this overlay or not

### Code sample

Something like
```
<FAB.Group hideOverlay={true}>...</FAB.Group>
```

### What have you tried

There are no properties documented that would enable this behaviour right now, and a short look at the code didn't give me any insights either.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native-paper    | 2.2.8

**Comment by ferrannp** [comment]
@sido378 can you show us the use case? Usually we do not support features that are not in material design guidelines so we can keep the library small.
