### ISSUE TITLE
drawer  sample code?

### ISSUE THREAD

**Issue by littlehome-eugene** [callstack/react-native-paper#695]
There's a Drawer.Item and Drawer.Section . 

But I don't get how to show or hide drawer itself.. There's no sample for drawer in the example directory either. 

https://github.com/callstack/react-native-paper/issues/358 mentions removing Drawer component,
so how do we show the drawer?

**Comment by Pushplaybang** [comment]
Also curious about this, surprised to not see a drawer component, is there an well supported alternative?

**Comment by ferrannp** [comment]
This is how we do it in the `example`: https://github.com/callstack/react-native-paper/blob/dec191f5c714a223fca43fd4fd3cd064971d9db5/example/App.js#L24-L43 and https://github.com/callstack/react-native-paper/blob/dec191f5c714a223fca43fd4fd3cd064971d9db5/example/DrawerItems.js.

**Comment by hotgeart** [comment]
The doc is unclear on how to put a Drawer.

**Comment by Trancever** [comment]
@hotgeart  Our library supports `Drawer.Item` and `Drawer.Section` components which are just building blocks that you can put inside drawer to make it look like material component. If you need drawer component take a look at [react-navigation](https://reactnavigation.org/docs/en/drawer-based-navigation.html) which is a navigation library for react-native and it provides `Drawer` component (we also use it in our example app).

**Comment by hotgeart** [comment]
Since this issue is in the first google results, here a sample code for the beginners:

App.js:

```js
import React from "react";
import { Text, View, ScrollView } from "react-native";
import { createAppContainer, createDrawerNavigator } from "react-navigation";
import { DrawerActions } from "react-navigation";
import { Appbar, Drawer } from "react-native-paper";
import { SafeAreaView } from "react-navigation"; // ⚠ you need the package 'react-navigation'

class First extends React.Component {
  render() {
    return (
      <View>
        <Appbar.Header>
          <Appbar.Action
            icon="menu"
            onPress={() =>
              this.props.navigation.dispatch(DrawerActions.toggleDrawer())
            }
          />
          <Appbar.Content title="First Page" />
        </Appbar.Header>
        <Text>First Page</Text>
      </View>
    );
  }
}

class Second extends React.Component {
  render() {
    return (
      <View>
        <Appbar.Header>
          <Appbar.Action
            icon="menu"
            onPress={() =>
              this.props.navigation.dispatch(DrawerActions.toggleDrawer())
            }
          />
          <Appbar.Content title="Second Page" />
        </Appbar.Header>
        <Text>Second Page</Text>
      </View>
    );
  }
}

const Menu = createDrawerNavigator(
  {
    First: { screen: First },
    Second: { screen: Second }
  },
  {
    contentComponent: props => (
      <ScrollView>
        <SafeAreaView forceInset={{ top: "always", horizontal: "never" }}>
          <Drawer.Item
            label="First Page"
            active="true"
            onPress={() => props.navigation.navigate("First")}
          />
          <Drawer.Item
            label="Second Page"
            active="true"
            onPress={() => props.navigation.navigate("Second")}
          />
        </SafeAreaView>
      </ScrollView>
    )
  }
);

const AppNav = createAppContainer(Menu);

export default class App extends React.Component {
  render() {
    return <AppNav />;
  }
}
```

**Comment by natelowry** [comment]
snack of @hotgeart's example code if you want to see it in action:

https://snack.expo.io/@natelowry/react-native-paper-drawer-sample

**Comment by Leafgard** [comment]
Would it be possible to see an implementation example of a Drawer Item with a Badge ? Tried everything and wasn't able to add one :/

**Comment by zachariahtimothy** [comment]
Am curious if there is any examples out there without relying on react-navigation? React Navigation is a GREAT library but would love to know if there is a reasonable way to implement material style navigation without it.

**Comment by xXFracXx** [comment]
I've gotten the drawer implemented, but the only way currently to dismiss it is by clicking the android back button, would it be possible to click on the screen area next to the drawer to dismiss, by screen area i mean the area that is darkened, though which you can see the base screen, as the drawer only takes up 75% of the screen. Any insight would be appreciated.

**Comment by zachariahtimothy** [comment]
@xXFracXx I ended up setting things up with React Gesture Handler Drawer Layout. I am facing the same issue and my approach will be to either find or write a tap away listener, similar to Material UI's click away listener: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/ClickAwayListener/ClickAwayListener.js

**Comment by wholenews** [comment]
Same. I'm using react-router-native. I just spent a day trying every viable drawer package, but they're all outdated and flawed. Maybe best path forward is to fork react-native-side-menu to accept refs and expose toggle API.

**Comment by Tarvone** [comment]
https://github.com/callstack/react-native-paper/issues/2009#issuecomment-3149678694
