### ISSUE TITLE
My own Theme  isn't working in  HelperText 

### ISSUE THREAD

**Issue by saharjedid** [callstack/react-native-paper#696]
<HelperText 
theme={{ colors: {placeholder: 'green',text: 'green',primary: 'green'}}}
type="error" visible={!this.state.text.includes('@')} >
Invalid Email
</HelperText>

**Comment by saharjedid** [comment]
@iyadthayyil any answer ?

**Comment by Trancever** [comment]
@saharjedid When `type="error"` it takes color from `error` property of `colors` object and when `type="info"` it takes color from `text` property.

**Comment by saharjedid** [comment]
can i change the color of error ? @Trancever thanks

**Comment by saharjedid** [comment]
thanks a lot @Trancever
