### ISSUE TITLE
How to change the label color in text input when its inactive

### ISSUE THREAD

**Issue by gssinghgautam** [callstack/react-native-paper#699]
### Expected behaviour

Label color is black and changed to white once TextInput is active

My Theme
export const EditTextTheme = {
  dark: true,
  colors: {
    primary: "#ffffff",
    accent: "#ffffff",
    background: "transparent",
    text: '#ffffff'
  }
};

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    |
| node                  |
| npm or yarn           |
| expo sdk              |

**Comment by raajnadar** [comment]
Hey, Post details according to the issue template.

**Comment by ferrannp** [comment]
Will group efforts together for colors on #775.

**Comment by anisht42** [comment]
export const EditTextTheme = {
dark: true,
colors: {
primary: "#fa7776",
accent: "#ffffff",
background: "transparent",
text: '#ffffff'
}
};


Text color not reflection,remain in black with the above Theme config

**Comment by akhilesh-leap-club** [comment]
`	theme={{ colors: { placeholder: 'grey', text: 'grey', primary: '#5d5d5d' }}}
`
use placeholder key for inactive and primary fro active in the theme

**Comment by shariqahmed525** [comment]
theme={{
     colors: {
       text: "#f5f5f5",
       accent: "#ffffff",
       primary: "#a3d1ff",
       placeholder: "#f5f5f5",
       background: "transparent"
    }
}}
underlineColor="#f5f5f5"
underlineColorAndroid="#f5f5f5"

**Comment by shariqahmed525** [comment]
`
theme={{
  colors: {
    text: "#f5f5f5",
    accent: "#ffffff",
    primary: "#a3d1ff",
    placeholder: "#f5f5f5",
    background: "transparent"
  }
}}
underlineColor="#f5f5f5"
underlineColorAndroid="#f5f5f5"
`

**Comment by Jahanzeb009** [comment]
`theme={{
     colors: {
         text: colors.text, // it'll change the user input text color,
         placeholder:'#b4b4b450' // it'll change the text color while textinput inactive OR when user enter data and go to another field
}}}`

**Comment by lucasbasquerotto** [comment]
For some weird reason, I was able to define the (unfocused) label color of an outlined TextInput setting the property: 

```tsx
theme={{
    colors: {
         onSurfaceVariant: 'white'
    }
}}
```

as pointed by this SO answer: https://stackoverflow.com/a/74862350/4850646

For focused/active labels, it get from the prop `activeOutlineColor`, but for unfocused labels it doesn't get from `outlineColor`, as I would expect.

I would never guess that `onSurfaceVariant` would solve it, it was a lot of trial and error with several props and theme props.

**Comment by ravithoria** [comment]
Still facing issue, outline colour overwrite label. Here is full code:

"react-native-paper": "^5.12.3",

![Screenshot_2024-03-23-17-49-57-18_a0aa8ea80e4c2e6188751ba02385a958](https://github.com/callstack/react-native-paper/assets/16267564/f5f48909-47a1-405b-b26a-7c4bb911b7b8)

```
import { MD3LightTheme as DefaultTheme, PaperProvider } from 'react-native-paper';
const theme = {
    ...DefaultTheme,
    colors: {
        ...DefaultTheme.colors,
        primary: 'tomato',
        secondary: 'yellow',
        background: 'transparent',
    },
};

export default function Main() {
    return (
        <PaperProvider theme={theme}>
            <App />
        </PaperProvider >
    );
}

AppRegistry.registerComponent(appName, () => Main);

=====
Home.js
=====
import { TextInput, useTheme } from 'react-native-paper';
export default function Home({) {
    const theme = useTheme();
return (
        <View style={CommonStyles.container}>
        <ImageBackground
                style={{ flex: 1, backgroundColor: 'black' }}
                source={require('../assets/images/gradientBlue.png')}>
                <TextInput
                    placeholder='Email'
                    label="Email"
                    mode={'outlined'}
                    value={email}
                    onChangeText={email => setEmail(email)}
                    textColor='white'
                    outlineColor='white'
                    activeOutlineColor='white'
                    style={{fontFamily: fonts.BeVietnamProRegular}}
                     theme={{
                     colors: { onSurfaceVariant: 'white'} // label colour
                      }}
                       />
         </ImageBackground >
        </View >
)
}
```

**Comment by Tejovarmabuddyloan** [comment]
for focused

**Comment by Tejovarmabuddyloan** [comment]
**use this to change label color**
@lucasbasquerotto 

 label={<Text style={styles.inputLabelText}>Loan Amount</Text>} 
inputLabelText{
color: "labelcolor"
}

**Comment by EthanSmithson** [comment]
> For some weird reason, I was able to define the (unfocused) label color of an outlined TextInput setting the property:
> 
> theme={{
>     colors: {
>          onSurfaceVariant: 'white'
>     }
> }}
> as pointed by this SO answer: https://stackoverflow.com/a/74862350/4850646
> 
> For focused/active labels, it get from the prop `activeOutlineColor`, but for unfocused labels it doesn't get from `outlineColor`, as I would expect.
> 
> I would never guess that `onSurfaceVariant` would solve it, it was a lot of trial and error with several props and theme props.

This worked for me as well.
