### ISSUE TITLE
Open FAB.Group open downward

### ISSUE THREAD

**Issue by marcfielding1** [callstack/react-native-paper#701]
### Current behaviour

When I position a fab group top right hand of the screen by giving it a marginBottom sufficient to do so - the FAB group still opens upward

NOTE This is code straight from Demo.
### Expected behaviour

FAB group should open downward.

### Code sample

```
import React, { Component } from 'react'
import { View, StatusBar } from 'react-native'
import ReduxNavigation from '../Navigation/ReduxNavigation'
import { connect } from 'react-redux'
import StartupActions from '../Redux/StartupRedux'
import ReduxPersist from '../Config/ReduxPersist'
import { FAB, Portal } from 'react-native-paper'

// Styles
import styles from './Styles/RootContainerStyles'

class RootContainer extends Component {
  state = {
    open: false,
  };
  componentDidMount () {
    // if redux persist is not active fire startup action
    if (!ReduxPersist.active) {
      this.props.startup()
    }
  }

  render () {
    return (
      <View style={styles.applicationView}>
        <StatusBar barStyle='light-content' />
        <Portal>
        <FAB.Group
          style={{ marginBottom: 580 }}
          open={this.state.open}
          icon={this.state.open ? 'today' : 'add'}
          actions={[
            { icon: 'add', onPress: () => console.log('Pressed add') },
            { icon: 'star', label: 'Star', onPress: () => console.log('Pressed star')},
            { icon: 'email', label: 'Email', onPress: () => console.log('Pressed email') },
            { icon: 'notifications', label: 'Remind', onPress: () => console.log('Pressed notifications') },
          ]}
          onStateChange={({ open }) => this.setState({ open })}
          onPress={() => {
            if (this.state.open) {
              // do something if the speed dial is open
            }
          }}
        />
      </Portal>
        <ReduxNavigation />
      </View>
    )
  }
}
console.disableYellowBox = true;

// wraps dispatch to create nicer functions to call within our component
const mapDispatchToProps = (dispatch) => ({
  startup: () => dispatch(StartupActions.startup())
})

export default connect(null, mapDispatchToProps)(RootContainer)

```

### Screenshots (if applicable)
 
![image uploaded from ios 3](https://user-images.githubusercontent.com/2651211/50055999-f8cffa80-014d-11e9-9cd2-ef4e957cfa1d.png)

### What have you tried

I had a look at source in node_modules/react-native-paper and can't obviously see a way of making open downward, nor can I see a way in the docs.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        React Native
| react-native          0.57
| react-native-paper    ^ 2.0.1
| node                  8.10
| npm or yarn          6.4.1
| expo sdk              N/A

On a side note great work on Paper, we're using it as our Launch UI and will certainly contribute once we get our feet under the table.

**Comment by marcfielding1** [comment]
Sorry to bump this but we might have to move to a third party menu if there's no movement on this as we're on a very tight release schedule, anyone got any ideas please?

**Comment by ferrannp** [comment]
@marcfielding1 if this is not in material design guidelines, we will probably not implement it.

**Comment by viv3kk** [comment]
same issue... might have to leave paper. There are many short coming with TextInput like adjusting height , border width etc
