### ISSUE TITLE
Custom style in searchbar

### ISSUE THREAD

**Issue by nwaughachukwuma** [callstack/react-native-paper#702]
Please how can I use the style property in searchbar. It seems the default style is overriding my custom style

**Comment by raajnadar** [comment]
https://callstack.github.io/react-native-paper/searchbar.html#style

It accepts style prop, What is not working?? Throw a snack.

**Comment by nwaughachukwuma** [comment]
Hi @raajnadar find below my implementation of the Searchbar

```
<Searchbar
        placeholder="Search location"
        onChangeText={query => { this.setState({ firstQuery: query }); }}
        value={firstQuery}
        onIconPress={ () => this.computeGeoCoord()}
        style={{fontSize: 12, elevation: 0}}
/>
```

With this, the fontSize is not responding to my custom style, although it works with the elevation

**Comment by gawrysiak** [comment]
@nwaughachukwuma this seems to be correct since the Searchbar's implementation has multiple components inside. The style prop is applied just to the top wrapper and not the text component. It's maybe a good idea to implement this somehow though

**Comment by nwaughachukwuma** [comment]
Hi @gawrysiak thanks for clarifying. I hope this is added in the near future

**Comment by Jervi-sir** [comment]
use the following properties  
```
inputStyle={{color: 'red', fontSize:1}}
placeholderTextColor={'red'}
```
and about style property, it affects the container directly, so something like backgroudColor or borderRadius ... work in this case
