### ISSUE TITLE
Use react-native-gesture-handler for buttons

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#703]
In order to fix #500, it might be an option.

**Comment by RichardLindhout** [comment]
Can be closed now since the issue is resolved?

**Comment by ferrannp** [comment]
@RichardLindhout we are still considering switching touchables to gesture handler for 3.0 that is why we kept this open.

**Comment by Trancever** [comment]
Closing, because touchables from gesture-handler are not accessible

**Comment by DeniferSantiago** [comment]
@Trancever according to the documentation there is a way that the buttons are accessible [doc](https://docs.swmansion.com/react-native-gesture-handler/docs/component-buttons)
