### ISSUE TITLE
Icons Missing In Example Snack

### ISSUE THREAD

**Issue by oxbits** [callstack/react-native-paper#711]
### Current behaviour

Try it out with Snack:

https://snack.expo.io/@satya164/github.com-callstack-react-native-paper:example

### Expected behaviour

Icons should appear.

### Screenshots (if applicable)

<img width="313" alt="screen shot 2018-12-24 at 5 23 47 am" src="https://user-images.githubusercontent.com/2498359/50397843-1817ea80-0741-11e9-8334-74f88643319a.png">

**Comment by satya164** [comment]
Should be fixed after latest import
