### ISSUE TITLE
Having onKeyPress on Searchbar and TextInput Components

### ISSUE THREAD

**Issue by nwaughachukwuma** [callstack/react-native-paper#712]
Hi Team,

It will be nice if there's is an onKeyPress event for some components. A simple scenario is when one is using the searchbar and the soft key shows up with a search key as part of the soft key. It will be nice if the user can use both search key options (one on the component and other on the soft key) to perform searching.

If this already exists, kindly point me to it. Thanks

**Comment by nwaughachukwuma** [comment]
@ferrannp I would love to, but maybe when am much free to do so. Thanks

**Comment by timothystewart6** [comment]
If you are using `Searchbar />` You have `onChangeText` for the value and I found that you can use `onSubmitEditing` for the softkey submit/search

[onSubmitEditing](https://facebook.github.io/react-native/docs/textinput.html#onsubmitediting)


```
<Searchbar
  onSubmitEditing={()=>console.log('Search softkey pressed!')}
/>
```

**Comment by timothystewart6** [comment]
I can add this to the docs if that helps!

**Comment by juandelacruz23** [comment]
It seems that the TextInput receives all the other properties given to the search input, that's what makes possible what you said @timothystewart6 
[This is the piece of code](https://github.com/callstack/react-native-paper/blob/master/src/components/Searchbar.js#L165-L180) (I don't know how to add a snippet from a github file 😢)

**Comment by jbinda** [comment]
I verified this and passing onSubmitEditing function on TextInput or Searchbar allows to perform futher action.

**Comment by kopax** [comment]
FYI, this is still not in the documentation.

**Comment by ShinobiWPS** [comment]
I can confirm this still works and it's not in the documentation.

**Comment by TheVengefulJalapeno** [comment]
I can confirm this still works (v4.12.5) and it's not in the documentation.
