### ISSUE TITLE
Unable to resolve module `@expo/vector-icons/MaterialIcons` 

### ISSUE THREAD

**Issue by ducaale** [callstack/react-native-paper#713]
### Current behaviour

when i install react-native-paper and run the app, i receive the following error:

bundling failed: Error: Unable to resolve module `@expo/vector-icons/MaterialIcons` from `C:\Users\shara\Desktop\projects\AwesomeProject\node_modules\react-native-paper\src\components\Icon.js`: Module `@expo/vector-icons/MaterialIcons` does not exist in the Haste module map

### Expected behaviour

it should resolve to the currently installed react-native-vector-icons

### Code sample

```jsx
import React, {Component} from 'react';
import {View} from 'react-native';
import {Button} from 'react-native-paper';

export default class App extends Component {
  render() {
    return (
      <View>
        <Button>hello</Button>
      </View>
    );
  }
}
```

### Screenshots (if applicable)

N/A

### What have you tried

1. created a clean project with react-native-cli
2. installed react-native-paper
3. installed and linked react-native-vector-icons

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 8.0
| react-native          | 0.57.8
| react-native-paper    | 2.4.0
| node                  | 10.14
| npm or yarn           | 1.12.3
| expo sdk              | N/A
| os                        | windows 10

**Comment by lin3yx** [comment]
Did you solve the problem? If so, would you mind posting the solution? Thank you very much.

**Comment by ducaale** [comment]
i solved it by clearing the cache https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d
