### ISSUE TITLE
When focus to other TextInput the text in the first one disappeared?! 

### ISSUE THREAD

**Issue by MohammadNehru** [callstack/react-native-paper#717]
`<TextInput
              mode = 'outlined'
              keyboardType='email-address'
              label='Email'
              autoCorrect={false}
              autoCapitalize='none'
              theme={{ colors: { background: '#ffffff', primary: '#1576d1' }}}
              onChangeText={(email) => this.setState({email})}
            />

            <TextInput
              mode = 'outlined'
              label='Password'
              secureTextEntry={true}
              autoCorrect={false}
              autoCapitalize='none'
              theme={{ colors: { background: '#ffffff', primary: '#1576d1' }}}
              onChangeText={(password) => this.setState({password})}
            />`

**Comment by Trancever** [comment]
You need to pass value prop.
