### ISSUE TITLE
Chips: how to change color of the selected ones?

### ISSUE THREAD

**Issue by koo27** [callstack/react-native-paper#725]
I can't figure out how to change the colors (background and text color) of the Chips that are selected.
I'm also using a specific Theme on the chips with the `selectedBackgroundColor` property but it doesn't affect anything at all.
The documentation doesn't say nothing regarding it either: https://callstack.github.io/react-native-paper/chip.html

Any hint?

Thank you

**Comment by lukewalczak** [comment]
Hello @koo27, currently this functionality is not supported, but I'll add missing props soon.

**Comment by raajnadar** [comment]
New api added https://callstack.github.io/react-native-paper/chip.html#selectedColor
