### ISSUE TITLE
Collision with Switch component when using TextInput with label

### ISSUE THREAD

**Issue by tlow92** [callstack/react-native-paper#726]
### Current behaviour

When TextInput with label is used the animation when blurring the TextInput seems to collide with the animation of the switch component.

![textinput_switch_with_label webm](https://user-images.githubusercontent.com/12113052/50977585-e2ba1d80-14f2-11e9-99d6-d921f0d35e75.gif)

### Expected behaviour

The behaviour should be the same as with the TextInput without label.

![textinput_switch_without_label webm 1](https://user-images.githubusercontent.com/12113052/50977599-e6e63b00-14f2-11e9-8897-8644db247239.gif)

### Code sample

```
<ScrollView>
              <TextInput
                label={'Deposit Amount'}
                value={this.state.text}
                onChangeText={(text) => this.setState({text: text})}
              />
            <Switch
                onValueChange={(value) => this.setState({active: value})}
                value={this.state.active}
            />
</ScrollView>
```

### Source of the issue
I know that the issue lies inside the AnimatedText of the Label, which is defined in
https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput.js#L557.
I do not know yet, what the best way is to resolve this.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.57.7
| react-native-paper    | 2.2.8 and 2.4.0

**Comment by ferrannp** [comment]
I created this Snack: https://snack.expo.io/@ferrannp/paper-deposit-amount. I can't reproduce it.

**Comment by luissmg** [comment]
Also tested the Snack in my phone and could no replicate this
