### ISSUE TITLE
Textinput's placeholder disappears

### ISSUE THREAD

**Issue by jsp3536** [callstack/react-native-paper#733]
The textinput's placeholder disappears when clicking in the textinput and then clicking anywhere outside of the textinput using react-native-web
![capture](https://user-images.githubusercontent.com/9041314/51362064-b0cb2d00-1a97-11e9-806d-c6ec18295af0.PNG)

**Comment by raajnadar** [comment]
Hey,
Please follow the issue template and add a live demo or a repository to check what is going wrong..

**Comment by jsp3536** [comment]
I created a repo [here](https://github.com/jsp3536/react-native-paper-textinput) that demonstrates the issue.  It appears the image component is some how effecting the textinput.  If you remove the image component then the placeholder will appear when you focus on the page.  A work around is to use the html img tag as it does not seem to cause a problem.

**Comment by nwpray** [comment]
I am having the same problem. I noticed that `opacity: 1` is not being added back to the second `AnimatedText` element onBlur of the `TextInput`. I changed the opacity value of the second `AnimatedText` to mirror the first `AnimatedText` element and it works now.

```
...
<AnimatedText
              style={[
                styles.placeholder,
                styles.placeholderFlat,
                labelStyle,
                {
                  color: placeholderColor,
                  opacity: this.state.labeled.interpolate({
                    inputRange: [0, 1],
                    outputRange: [hasActiveOutline ? 0 : 1, 1]
                  })
                }
              ]}
              numberOfLines={1}
            >
              {label}
            </AnimatedText>
...
```

This works for the web but I don't know if it is going to mess something up for mobile?

**Comment by murtraja** [comment]
@nwpray, I came up with something similar in #960

**Comment by edujtm** [comment]
We are having the same problem on mobile, but weirdly it only happens after we add three TextInputs or more. Changing the TextInputFlat.js as mentioned by @nwpray didn't solve the issue for us, but I'm not sure if we missed something when changing the downloaded file.
