### ISSUE TITLE
Textinput label bug on RTL

### ISSUE THREAD

**Issue by yaronlevi** [callstack/react-native-paper#734]
I've just downloaded expo and there is a bug in the Textinput's labe.
Pixel 2 XL. Android 9. System language Hebrew.
![screenshot_20190118-094719](https://user-images.githubusercontent.com/5398977/51372675-9ed4a300-1b06-11e9-8d35-7315aa78ff4e.png)

**Comment by lukewalczak** [comment]
Hello @yaronlevi 	, that issue was fixed with PR #721, but it's not released yet. For now you can your `master` branch and replace it once new version will be shipped.

**Comment by satya164** [comment]
Just published a new release.
