### ISSUE TITLE
Searchbar keyboard closes after each entry in FlatList ListHeaderComponent

### ISSUE THREAD

**Issue by makhataibar** [callstack/react-native-paper#736]
### Current behaviour

when the text changes (onChangeText) in Searchbar the keyboard closes

### Expected behaviour

I expect the keyboard will not close after changing the text

### Code sample

<FlatList
          data={works}
          keyExtractor={item => item.id.toString()}
          renderItem={this._renderItem}
          ListHeaderComponent={() => (
            <Searchbar
              placeholder="Поиск"
              onChangeText={query => {
                this.setState({ firstQuery: query });
              }}
              value={firstQuery}
              style={{ margin: 16, marginBottom: 0 }}
            />
          )}
          refreshing={refreshing}
          onRefresh={this._onRefresh}
          ListFooterComponent={() => <View style={{ marginTop: 16 }} />}
        />

### Screenshots (if applicable)

![bug jn4ik 1](https://user-images.githubusercontent.com/27006656/51384700-48d41f80-1b47-11e9-965d-cd19e0371553.gif)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
| react-native-paper    | ^2.2.8
| node                  | v10.15.0
| npm or yarn           | yarn 1.13.0
| expo sdk              | ^32.0.0

**Comment by lukewalczak** [comment]
Hello @makhataibar 	, try render `ListHeaderComponent` directly as a React Element instead of a rendering a function.

```
        <FlatList
          ...
          ListHeaderComponent={
            <Searchbar
              placeholder="Поиск"
              onChangeText={query => {
                this.setState({ firstQuery: query });
              }}
              value={firstQuery}
              style={{ margin: 16, marginBottom: 0 }}
            />
          }
        />
```

More about that issue you can read [here](https://github.com/facebook/react-native/issues/13365)

**Comment by satya164** [comment]
Basically `FlatList` expects you to pass a React Component. When you pass an inline function like that, it creates a new component every render. When the component signatures differ (in this case the function reference), react will unmount the previous tree with the old component and mount a new tree with the new component. Due to this, all of the local state of the previous component is lost, such as focus state.

**Comment by nikbakhtenb4** [comment]
I fixed it by adding below line on my Flatlist component:
<FlatList
 keyExtractor={item => item}
...
/>

**Comment by devendra-learngram-ai** [comment]
https://stackoverflow.com/a/61932641/10912970
this answer helped me fix the issue.
```
<FlatList
....
removeClippedSubviews={false}
...
/>
```

**Comment by cavishek39** [comment]
> Hello @makhataibar , try render `ListHeaderComponent` directly as a React Element instead of a rendering a function.
> 
> ```
>         <FlatList
>           ...
>           ListHeaderComponent={
>             <Searchbar
>               placeholder="Поиск"
>               onChangeText={query => {
>                 this.setState({ firstQuery: query });
>               }}
>               value={firstQuery}
>               style={{ margin: 16, marginBottom: 0 }}
>             />
>           }
>         />
> ```
> 
> More about that issue you can read [here](https://github.com/facebook/react-native/issues/13365)

Still no luck after doing this.

**Comment by zekoliman** [comment]
> Hello @makhataibar , try render `ListHeaderComponent` directly as a React Element instead of a rendering a function.
> 
> ```
>         <FlatList
>           ...
>           ListHeaderComponent={
>             <Searchbar
>               placeholder="Поиск"
>               onChangeText={query => {
>                 this.setState({ firstQuery: query });
>               }}
>               value={firstQuery}
>               style={{ margin: 16, marginBottom: 0 }}
>             />
>           }
>         />
> ```
> 
> More about that issue you can read [here](https://github.com/facebook/react-native/issues/13365)

Working for me ty <3
