### ISSUE TITLE
TextInput editable prop doesn't work

### ISSUE THREAD

**Issue by G1anS** [callstack/react-native-paper#737]
### Current behaviour

I can edit the not editable TextInput

### Expected behaviour

I shouldn't be able to edit the TextInput 

### Code sample

```
import React from 'react';
import { StyleSheet, View } from 'react-native';
import { TextInput as TextInputPaper } from 'react-native-paper';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <TextInputPaper
          label='Flat input'
        />
        <TextInputPaper
          label='Flat input not editable'
          editable={false}
        />
        <TextInputPaper
          label='Outlined input'
          mode='outlined'
        />
        <TextInputPaper
          label='Outlined input not editable'
          mode='outlined'
          editable={false}
        />
    </View>
      );
  }
}
```

### Screenshots

<img width="317" alt="screenshot 2019-01-18 at 17 29 31" src="https://user-images.githubusercontent.com/40580081/51400328-65bd2280-1b48-11e9-904c-6461818b70ec.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |  12.1
| react-native          |  latest
| react-native-paper    |  latest

**Comment by lukewalczak** [comment]
Hello @G1anS , you should use `disabled` props instead of `editable={false}`.

**Comment by raajnadar** [comment]
This code snippet works

```
import React from 'react';
import { StyleSheet, View } from 'react-native';
import { TextInput as TextInputPaper } from 'react-native-paper';

export default class App extends React.Component {
  render() {
    return (
      <View>
        <TextInputPaper label="Flat input" disabled={true} />
        <TextInputPaper label="Flat input not editable" />
        <TextInputPaper label="Outlined input" mode="outlined" />
        <TextInputPaper
          label="Outlined input not editable"
          mode="outlined"
          disabled={true}
        />
      </View>
    );
  }
}

```
[Disabled input in react native paper](https://snack.expo.io/@raajnadar/disabled-input-in-react-native-paper)
[Reference](https://callstack.github.io/react-native-paper/text-input.html#disabled)

**Comment by GlisboaDev** [comment]
Aren't these different properties and behaviors?
I'm having a similar issue here, where we don't want the `disabled` behavior and UI, but don't want the keyboard to come up (related to https://github.com/facebook/react-native/issues/14045) and the closest we can get is having `editable` set to `false`.

**Comment by Jack0815** [comment]
> 
> 
> Aren't these different properties and behaviors?
> I'm having a similar issue here, where we don't want the `disabled` behavior and UI, but don't want the keyboard to come up (related to [facebook/react-native#14045](https://github.com/facebook/react-native/issues/14045)) and the closest we can get is having `editable` set to `false`.

I have the exact same usecase.
I want to build a date input and it should look like a textInput. I surrounded it with a touchableWithoutFeedback to pop up the date picker. But if the textInput looks like it should, the keyboard pops up. And if disabled, it does not look like the user can interact with but prevents the keyboard.
Any help with that? @raajnadar 

Kind regards
Jack

**Comment by raajnadar** [comment]
Reopening the issue

**Comment by raajnadar** [comment]
Sorry for bumping again but @Jack0815 here is a workaround for you.

https://snack.expo.io/@raajnadar/picker-that-looks-like-textinput

**Comment by Jack0815** [comment]
Thanks so far @raajnadar really fast repsonse time  :)
Jepp it looks similar to my current solution. You are right. Instead of preventing the keyboard I could just try to fake the textInput optics. I would still prefer to have the flat react native paper textInput component instead. Otherwise I would have to adopt my faked text-label whenever the textInput optics or behaviour might change.

**Comment by Jack0815** [comment]
Hi @raajnadar ,
jepp I was not thinking about using the onPress. Surrounding it with a touchableWithoutFeedback would be fine for me. What my need is just to have its behaviour as it was disabled (so no keyboard and no direct interaction), but have the style not with gray font and background (just as if it was not disabled). With editable=false  (second textInput in the example at the very top) I still get a keyboard on android and have the "wrong" style.

**Comment by satya164** [comment]
`TextInput` also has a `render` prop which you can use to replace what's rendered inside to render a picker.

**Comment by jbinda** [comment]
fixed in #1069

**Comment by macfanatic** [comment]
Using a `TouchableWithoutFeedback` to wrap the non-editable `TextInput` works well on iOS, but on Android the text input itself doesn't fire any events.  You have to tap on a very small area of the overall containing view to get the event to fire.

In this example, I have a red background to show the area tappable.

```ts
<TouchableOpacity onPress={presentStatePicker} style={{backgroundColor: 'red'}}>
   <TextInput label="Province" mode="outlined" style={styles.input} value={form.province} editable={false} onTouchStart={presentStatePicker} />
</TouchableOpacity>
```

![Screen Shot 2020-05-22 at 4 26 37 PM](https://user-images.githubusercontent.com/162970/82706953-080f7d80-9c49-11ea-96f0-d1d374fb723c.png)

Any thoughts @Jack0815 or @satya164 ?

**Comment by xristos4hax** [comment]
I have the same issue, In my case i remove flex: 1 from style and issue fixed
