### ISSUE TITLE
parenthesis not properly located on: example/App.js

### ISSUE THREAD

**Issue by napolev** [callstack/react-native-paper#740]
On the following line the parenthesis are not properly located:
https://github.com/callstack/react-native-paper/blob/bcef4a60ba72669d51cd9418a341193c9bb0cfc8/example/App.js#L41

this is how it is right now:
drawerPosition: Platform.OS === 'android' && (I18nManager.isRTL ? 'right' : 'left'),

this is how it should be:
drawerPosition: (Platform.OS === 'android' && I18nManager.isRTL) ? 'right' : 'left',

since "drawerPosition" accepts the values: { 'left', 'right' }

Thanks.

**Comment by lukewalczak** [comment]
@napolev 	Can you create a PR with your solution?

**Comment by luissmg** [comment]
#747 Fixed this. You can close this issue.
