### ISSUE TITLE
Typo: ButtomNavigationExample -> BottomNavigationExample

### ISSUE THREAD

**Issue by napolev** [callstack/react-native-paper#741]
There is a typo on the following line:

actual: ButtomNavigationExample
what should be: BottomNavigationExample

https://github.com/callstack/react-native-paper/blob/6785992d8f1c3003e213a6aab33fd1b579cbd93a/example/src/BottomNavigationExample.js#L33

Thanks!

**Comment by Trancever** [comment]
@napolev Do you want to send PR? :)
