### ISSUE TITLE
Add component-specific style configuration to theme

### ISSUE THREAD

**Issue by robertherber** [callstack/react-native-paper#745]
Theming is great. But I'd like more granularity of making more specific configuration for specific component types throughout the entire application in an easy and intuitive way. Right now the granularity provided by the theming is limited and sometimes it's hard to understand which color maps to a specific component.

I'd suggest adding a new configuration type that applies styles to all components of the same type, something like this:

```
{
  ...DefaultTheme,
  components: {
    title: {
      fontSize: 16,
      color: 'rgb(10, 10, 10)'
    },
    surface: {
      backgroundColor: 'rgb(20, 20, 20)'
    }
  }
}
```

I know it's possible to wrap components to achieve this - but it's very verbose if all you want to do is make a minimal customisation. This would make theming so much more powerful out of the box, and it would be very easy and intuitive to follow these overrides.

**Comment by ocarreterom** [comment]
I'm agree with @robertherber and I think themig should be enhanced.
Also there are many components that use this piece of code:
https://github.com/callstack/react-native-paper/blob/dec191f5c714a223fca43fd4fd3cd064971d9db5/src/components/CheckboxAndroid.js#L89-L92

This can be moved to the theme configuration.

**Comment by Pushplaybang** [comment]
It would be great to have access to these styles from the theme
