### ISSUE TITLE
Improve documentation generation

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#76]
These are potential improvements to the docs generation process

- [x] Show info regarding required/optional props
- [x] Support markdown in documentation
- [ ] Add ability to document and link to a type definition, e.g. `Theme`
- [x] Add quick search in sidebar
- [ ] Sections with headers
- [x] Support mobile layout

**Comment by satya164** [comment]
I'll eventually move the generator out of this repo and publish to NPM so more libs can make use of it.

**Comment by ferrannp** [comment]
Keep this on `component-docs`.
