### ISSUE TITLE
Suggestion: Many icons have both Material Design and iOS versions to provide Platform Continuity for users.

### ISSUE THREAD

**Issue by douglaszaltron** [callstack/react-native-paper#760]
how do I disable the need to use the react-native-vector-icons library? I would like to use only the @fanqfanh which has the latest ionicons icons that differentiate between android and ios.
I found this approach quite interesting.
It could be something to include next to the project.

follows the repository.

https://github.com/fanqfanh/react-native-ionicons

**Comment by satya164** [comment]
https://callstack.github.io/react-native-paper/icons.html
