### ISSUE TITLE
DataTable is broken on React Native Web

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#762]
![image](https://user-images.githubusercontent.com/1174278/51801587-2b3a4080-2240-11e9-8db5-499ceddb6c25.png)

cc @jaulz

**Comment by clemos** [comment]
Hi there !
Great work :)
I'm also working on a cross-platform (incl. react-native-web) React / material (not yet public unfortunately...).
Our approach was to conditionnally use https://github.com/mui-org/material-ui when targetting web.
This would be especially useful for "complex" components such as datatables.
What do you think ?

**Comment by jaulz** [comment]
@satya164 will check it.
@clemos that sounds valid but in my opinion that should not be part of this library and instead should be a decision per project.

**Comment by jaulz** [comment]
Seems to work now without any changes. Can you please cross check?

![image](https://user-images.githubusercontent.com/5358638/51903449-77aa8b00-23bc-11e9-98a6-e17a62b9e8b4.png)

**Comment by satya164** [comment]
Yeah seems it works now 😱
