### ISSUE TITLE
Card doesn't have shadow on React Native Web

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#767]

**Comment by jaulz** [comment]
The thing is that `elevation` is an `Animated.Value` which cannot be used in `shadow` function:
https://github.com/callstack/react-native-paper/blob/eefcff37b56c12213c50d48b89d2fccc92de5d70/src/components/Card/Card.js#L93

https://github.com/callstack/react-native-paper/blob/eefcff37b56c12213c50d48b89d2fccc92de5d70/src/components/Surface.js#L68
