### ISSUE TITLE
Cannot update version of package 'react-navigation' to the latest

### ISSUE THREAD

**Issue by napolev** [callstack/react-native-paper#772]
### Current behaviour

I just cloned the `react-native-paper` repository and tried to update the version of package: `react-navigation` from version: `2.18.2` to version: `3.0.9` by doing the following:
```
$ git clone https://github.com/callstack/react-native-paper
$ cd react-native-paper/example
$ npm install
$ npm install --save-dev react-navigation@3.0.9
$ expo start

Output:
[10:38:06] Your app is running at exp://192.168.1.194:19000
Logs for your project will appear below. Press Ctrl+C to exit.
[10:39:25] Unable to resolve "./../node_modules/react-transform-hmr/lib/index.js" from "App.js"
[10:39:25] Failed building JavaScript bundle.
```

### Expected behaviour

The application should be running properly on the device in the same way as before the version update.

### Screenshots

![Issue after updating version of package: react-navigation](https://i.ibb.co/g3V2rLf/image.png)

### Environment

```
Device: Android

$ node -v
v8.11.2

$ expo --version
2.7.0

$ cat package.json
{
  ...
  "dependencies": {
    "@callstack/react-theme-provider": "^1.0.7",
    "@expo/vector-icons": "^8.0.0",
    "create-react-context": "^0.2.3",
    "expo": "^31.0.3",
    "react": "16.5.0",
    "react-lifecycles-compat": "^3.0.4",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",
    "react-native-paper": "^2.4.0",
    "react-navigation": "^3.0.9"
  },
  "devDependencies": {
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-preset-expo": "^5.0.0",
    "expo-cli": "^2.3.8"
  }
  ...
```

If I run the app with the version update for package: `react-navigation` on `snack.expo.io`:

https://snack.expo.io/B1BEUPjmE

I get the following error:

```
Invariant Violation: The navigation prop is missing for this navigator. In react-navigation 3 you must set up your app container directly. More info: https://reactnavigation.org/docs/en/App-containers.html
```

as you can see on the following image:

![Expo Screenshot - Issue after updating version of package: react-navigation](https://i.ibb.co/pfK3Kvt/image.png)

Is it possible to update the version for package: `react-navigation`?. If so, could you please modify the previous `snack` with the proper changes?

or you could start from the official `snack` as well:

https://snack.expo.io/@satya164/github.com-callstack-react-native-paper:example

Thanks!

**Comment by satya164** [comment]
There are breaking changes in latest react-navigation, the details are mentioned here: https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html#breaking-changes

**Comment by napolev** [comment]
thank you @satya164 !
