### ISSUE TITLE
TextInput maximum line size

### ISSUE THREAD

**Issue by RajkumarRamanathan** [callstack/react-native-paper#773]
TextInput maximum line size not able to configure

There is no parameter to control the size of multiline textbox

there should be maximum no of line parameter to control the size 

| react-native          |
| react-native-paper    |
| node                  |
| npm or yarn           |
| expo sdk              |

**Comment by ferrannp** [comment]
If you check here multiline section https://facebook.github.io/react-native/docs/textinput.html. Does setting a `maxHeight` works for you?

**Comment by RajkumarRamanathan** [comment]
Thanks it works, saved the day
