### ISSUE TITLE
Placeholder and value are not in the same baseline on TextInput

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#774]
### Current behaviour

In the efforts of aligning an icon with the text (like [here](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Kezf2nmTVbQdOfNajrotDxeIKs1WlwHl%2Ftextfields-type-stroke.png)), I realized about that.

Currently is not possible to align an icon with the text.

### Expected behaviour

Placeholder line and value should be the same. So we can do things like aligning an icon:

![mio-design_assets_1kezf2nmtvbqdofnajrotdxeiks1wlwhl_textfields-type-stroke](https://user-images.githubusercontent.com/774577/51834331-3ea9e200-22fa-11e9-8c52-30f87817221a.png)

### Code sample

You can try that in our TextInput example.

### Screenshots (if applicable)

On the top with value and on the bottom with placeholder/label.

![textinputalign](https://user-images.githubusercontent.com/774577/51834594-166eb300-22fb-11e9-9d45-13018250c6a0.png)

### Your Environment

| software              | version
| --------------------- | -------
| android   |  P
| react-native          | 0.57.8
| react-native-paper    | 2.4.0

**Comment by jbinda** [comment]
fixed in #1020
