### ISSUE TITLE
Better way to document how to change colors inside TextInput and other components

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#775]
See for example #699 or #775.

Also feel free to comment here what colors you cannot change or you don't know how.

It might require changes to https://github.com/callstack/component-docs.

**Comment by methodbox** [comment]
I feel like there should be a fundamental way of setting the core color of text inputs.

I understand people may want to change each element, but there should be a prop that sets the tone for the entire text input like ```textInputPrimaryColor={'blue'}``` and the label and underline on focus would be changed.

If there is a way to do this already, I can't sort it out based on the documentation.

**Comment by satya164** [comment]
@methodbox have you read our documentation? how is passing theme prop to a single component "set a theme" for our entire app? in the documentation we specifically mention this feature.

**Comment by tinni95** [comment]
It is impossible as of today having two different colors for the label and the underline when the input is focused, this has always put me off from using this library and it's the reason why I end up excluding it in any of my projects, I hope you will make a get around to this problem

**Comment by MuhammadAffanAli123** [comment]
page not found

**Comment by lucamir** [comment]
I'm using the 5.0v and i cannot change the color label when is inactive in the outlined textinput. I read docs and try to use the theme props but the color doesn't change. Any suggestions ?

**Comment by faridrr** [comment]
> I'm using the 5.0v and i cannot change the color label when is inactive in the outlined textinput. I read docs and try to use the theme props but the color doesn't change. Any suggestions ?

Try this :                         
theme={{ colors : {  onSurfaceDisabled: "red"} }}

**Comment by MoinVnr** [comment]
It's working

<FloatingLabelInput
                label={'Projects'}
                value={project}
                onChangeText={value => setProject(value)}
                containerStyles={{
                  borderWidth: 2,
                  paddingHorizontal: 10,
                  backgroundColor: '#fff',
                  borderColor: '#37745C',
                  borderRadius: 5,
                }}
                customLabelStyles={{
                  colorFocused: '#37745C', 
                  colorBlurred: '#999999', 
                  fontSizeFocused: 12,
                }}
                labelStyles={{
                  backgroundColor: '#fff',
                  paddingHorizontal: 5,
                  fontSize: 20
                }}
                inputStyles={{
                  color: '#37745C',
                  paddingHorizontal: 5,
                  top: 5
                }}
              />
     colorFocused: '#37745C',  // on focused
     colorBlurred: '#999999', Inactive text color
