### ISSUE TITLE
All "Try this example on Snack" are broken

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#776]
For example for [Button](https://snack.expo.io/?name=Button&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fbutton.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20Button%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20(%0A%20%20%3CButton%20icon%3D%22add-a-photo%22%20mode%3D%22contained%22%20onPress%3D%7B()%20%3D%3E%20console.log(%27Pressed%27)%7D%3E%0A%20%20%20%20Press%20me%0A%20%20%3C%2FButton%3E%0A)%3B%0A%0Aexport%20default%20MyComponent%3B). You can try running on the device and you won't see anything.

**Comment by satya164** [comment]
@ferrannp what's broken about it? i just tried and it works for me

@luissmg nope

**Comment by luissmg** [comment]
For me it does not work too. Expo says to add Paper as a dependency (not added by default). If you miss that warning and just try the example it will not work

**Comment by satya164** [comment]
@luissmg yeah it's been that way from the beginning since there was no way to specify deps before when opening. I added that feature recently so will update the code.

**Comment by luissmg** [comment]
Well that's the only thing that was not working for me. Don't know if that's what @ferrannp was talking aboht

**Comment by ferrannp** [comment]
Mmm I was trying it and only seeing a transparent background, now I tried again (answering yes to add react-native-paper) and seems ok. I'll keep trying with some other components. If I find something weird I'll open another issues. Thanks guys for your comments!
