### ISSUE TITLE
react-native-paper does not work on react-native 0.58.x

### ISSUE THREAD

**Issue by syedabuthahirm** [callstack/react-native-paper#777]
### Current behaviour
ReactNativePaper is not working in lastet version of reactnative 0.58 and 0.58.1

### Expected behaviour
![whatsapp image 2019-01-28 at 6 10 53 pm](https://user-images.githubusercontent.com/22408257/51836993-1802a000-2328-11e9-96cd-019d3458aee2.jpeg)

### Code sample
```js
/**
 * @format
 * @lint-ignore-every XPLATJSCOPYRIGHT1
 */
import React from "react";
import { AppRegistry } from "react-native";
import { name as appName } from "./app.json";
import {
  Provider,
  Button,
  DarkTheme,
  Surface,
  Text,
  Card
} from "react-native-paper";

const Main = () => (
  <Provider theme={DarkTheme}>
    <Card elevation={1}>
      <Card.Content>
        <Text>Hello o</Text>
      </Card.Content>
    </Card>
  </Provider>
);

AppRegistry.registerComponent(appName, () => Main);
```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 58.1
| react-native-paper    | 2.6.3
| node                  | 8.11.3
| npm or yarn           | 1.10.1

Package.json code
```json

{
  "name": "barbendingEstimation",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.1",
    "react-native-paper": "^2.6.3",
    "react-native-vector-icons": "^6.2.0"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.0.0",
    "jest": "24.0.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by ferrannp** [comment]
We are aware of compatibility issue. We'll work on this at some point (but I am guessing when expo updates).

**Comment by syedabuthahirm** [comment]
Ok. i downgrade my application to old react-native version.
but while debugging i found that [flattenStyle function](https://github.com/callstack/react-native-paper/blob/b799a1e5f8e59e7afab1a04a2da6eabaad07f98a/src/components/Surface.js#L60) return object reference instead of number in surface component. so, in [shadow function](https://github.com/callstack/react-native-paper/blob/b799a1e5f8e59e7afab1a04a2da6eabaad07f98a/src/components/Surface.js#L68) always it's going to [default block](https://github.com/callstack/react-native-paper/blob/b799a1e5f8e59e7afab1a04a2da6eabaad07f98a/src/styles/shadow.js#L16) instead of correct case blocks.

in that function we calculated

```js
default:
      height = elevation - 1; // this result gives NaN result
      radius = elevation;
```

I didn't debugged further.

**Comment by satya164** [comment]
This should be fixed by ec872a5c6188d8fdded269ac2e98f4ba5881e679

Can you try the latest version and let me know if it works?

**Comment by syedabuthahirm** [comment]
Yeah.
It's working.
**Thanks for the quick fix**.

While checking react-native version is 0.58.3.

**Comment by hugopretorius72** [comment]
Great work

**Comment by syedabuthahirm** [comment]
@hugopretorius72 i think this issue was in shadow function not in button component. Surface is basic component. button and card component inherited from surface @hugopretorius72.

**Comment by hugopretorius72** [comment]
I can confirm this as adding style={{elevation: 1}} on button works like a bomb 🙌🏻

**Comment by hugopretorius72** [comment]
@syedabuthahirm thanks for that.  Not sure why that fixes it but it does, hope it can help you troubleshoot

**Comment by koo27** [comment]
Still having this (smilar) problem with version 2.11.0 and react-native version 0.58.4

**Comment by satya164** [comment]
@koo27 can you open a new issue with code sample and error message?

**Comment by koo27** [comment]
@satya164 Sure! I'm still deep debugging in order to get as much information as I can. Thank you

**Comment by syedabuthahirm** [comment]
@satya164 & @koo27  i checked with **react-native-0.58.3**.i will check again with **react-native-0.58.4**

**Comment by koo27** [comment]
@syedabuthahirm @satya164 my bad!
The issue wasn't related to react-native-paper anymore! **The last version actually solves the problem**.
The bug I face is related only to the new version of react-native (basically it throws me error when I have something like width, right, height, etc. calculated dinamically directly into the style).

**Comment by Bonfs** [comment]
hi everyone, this problem persists in react-native 0.59.5, or maybe returned idk. The solution pointed by @hugopretorius72  still working for Button but not worked for BottomNavigation.
I have migrated from 0.57.8 to 0.59.5
