### ISSUE TITLE
Appbar doesn't have shadow on Web

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#781]

**Comment by pnkapadia6** [comment]
@satya164 Can I pick this up?

**Comment by satya164** [comment]
Go ahead

**Comment by pnkapadia6** [comment]
@satya164 https://github.com/callstack/react-native-paper/pull/923

**Comment by edmundojr** [comment]
`Appbar.Header` doesn't have shadow at all, even on react-native.

**Comment by Taym95** [comment]
@edmundojr work in [progress](https://github.com/callstack/react-native-paper/pull/785) will be fixed!

**Comment by Alain00** [comment]
Any progess on this? the shadow on the Appbar.Header is't working for me too
