### ISSUE TITLE
Bottom navigator not centered

### ISSUE THREAD

**Issue by roman-huliak** [callstack/react-native-paper#784]
### Current behaviour

Bottom navigator items are not centered in screen.

### Expected behaviour

Center in screen on all sizes

### Code sample

```
import * as React from 'react';
import { BottomNavigation, Text } from 'react-native-paper';
import EvidenceWaitingScreen from './waiting';
import EvidenceApprovedScreen from './approved';


export default class MyComponent extends React.Component {
  state = {
    index: 0,
    routes: [
      { key: 'waiting', title: 'Čakajúce', icon: 'access-time' },
      { key: 'done', title: 'Schválené', icon: 'check-circle' },
      { key: 'd1', title: 'Schválené 1', icon: 'check-circle' },
      { key: 'd2', title: 'Schválené 2', icon: 'check-circle' }
    ],
  };

  _handleIndexChange = index => this.setState({ index });

  _renderScene = BottomNavigation.SceneMap({
    done: EvidenceApprovedScreen,
    d1: EvidenceApprovedScreen,
    d2: EvidenceApprovedScreen,
    waiting: EvidenceWaitingScreen
  });

  render() {
    return (
      <BottomNavigation
        navigationState={this.state}
        onIndexChange={this._handleIndexChange}
        renderScene={this._renderScene}
      />
    );
  }
}
```

### Screenshots

![screenshot 2019-01-30 06 56 41](https://user-images.githubusercontent.com/7287207/51961420-eb9c7000-245c-11e9-9d3e-8b51f7afc7b8.png)

### What have you tried

Set styles to center.
Tested code from https://callstack.github.io/react-native-paper/bottom-navigation.html

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios or android
| react-native          | 0.57.8
| react-native-paper    | 2.4.0
| node                  | 11.7.0
| npm or yarn           | 6.7.0

**Comment by satya164** [comment]
It should be fixed in latest version. Please upgrade to 2.7.0

**Comment by roman-huliak** [comment]
where is changelog? where i can found changes between released versions?

**Comment by satya164** [comment]
https://github.com/callstack/react-native-paper/releases
