### ISSUE TITLE
FAB.Group Style Change Position with Style

### ISSUE THREAD

**Issue by sinansonmez** [callstack/react-native-paper#789]
### Current behaviour

I am trying to change the position of FAB.Group button by using style props. 
I want to place it next to my glass button. 

### Expected behaviour

The FAB's position doesnt change at all. 

### Code sample

```
          <Portal>
            <FAB.Group 
              open={this.state.open}
              icon={'menu'}
              actions={[
                {icon: require('../assets/images/menu.png'), label:'Menu', onPress: () => console.log('Pressed add')}
              ]}
              onStateChange={({ open }) => this.setState({ open })}
              onPress={() => {this.setState({open: !this.state.open})}}
              style={{position: 'absolute', top: 50, left: 0}}
            />
          </Portal>
```

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/37421564/52005181-22649b80-24da-11e9-8c66-d3bde876d004.png)

### What have you tried

I tried style prop and change it. 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android
| react-native          |
| react-native-paper    |
| node                  |
| npm or yarn           | npm
| expo sdk              |

**Comment by sinansonmez** [comment]
Not an ideal solution but it worked. Thanks

> hey,
> try using padding to reposition it

Not an ideal solution but it worked. Thanks

**Comment by sinansonmez** [comment]
Hello again,

I have tried with padding to reposition it based on width and height to position at the same place both FAB and FAB.group. However it works on some devices but FAB.group button position is not aligned on some devices. 

Can you suggest any other solution. 

Here is a snack for you to see the code
https://snack.expo.io/@sinansonmez/fab-button

**Comment by sinansonmez** [comment]
Hello again,

I have managed to solve it using some basic math by leveraging  width (onLayout prop of view) of view where our FAB button is placed. 

```
  state = {
    fabHeight: 0, // view height of FAB button
    fabWidth: 0, // width height of FAB button
    adHeight: 0, // view height of Ad located under FAB button
  };
```
Style of FAB Button and position it half of view height
```
style={{
  backgroundColor: Colors.tintColor,
  position: 'absolute',
  bottom: this.state.fabHeight / 2,
}}
```
Style of FAB.Group Button and position it half of view height + ad height and minus 16 because FAB.Group by default has 16 px margin
```
style={{
  paddingRight: this.state.fabWidth * 0.2,
  paddingBottom: this.state.fabHeight / 2 + this.state.adHeight - 16,
}}
```

**Comment by kmuthukr** [comment]
is it possible to make the FAB expand/open downwards so that i could place the icon to the top of the screen
