### ISSUE TITLE
The visible props from fab doens't work

### ISSUE THREAD

**Issue by borgogelli** [callstack/react-native-paper#798]
```
   <FAB
    visible="false"
    style={styles.fab}
    icon="add"
  /> 
```
Using the previous snippet of code, the fab component remains still visible

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |  0.57.1
| react-native-paper    | 2.8.0
| expo sdk              | 31.0.6

**Comment by satya164** [comment]
`FAB` accepts a `visible` prop which is a boolean, you're passing the string `"false"` which a truthy value. You need to pass `false`, `<FAB visible={false} />`

**Comment by borgogelli** [comment]
I did a mistake reporting the issue.
`<FAB visible={false} style={styles.fab} icon="add" />`
doesn't work too,
I have used the following a workaround:
{this.state.fabVisible ?     
```
<FAB style={styles.fab} icon="add" />      
: null}
```

**Comment by Trancever** [comment]
@borgogelli Can you try our example app https://expo.io/@satya164/react-native-paper-example. It works fine there.

**Comment by borgogelli** [comment]
Now it works. I have already double checked the problem before posting that issue. I don't know what it was, but it works. Thank you.
