### ISSUE TITLE
Chips auto sizing not working

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [callstack/react-native-paper#801]
### Current behaviour

Chips auto sizing not working. It's by default full width:-
![image](https://user-images.githubusercontent.com/22089729/52160491-02f38b80-26f1-11e9-8dd3-4dfefb4ccc2c.png)

tried setting width to auto but still not working
### Expected behaviour

must able to set width to auto content size

### Code sample

<Chip icon="info" onPress={() => console.log('Pressed')} style={{width: 'auto}}>Example Chip</Chip>

**Comment by psincraian** [comment]
I have the same problem. Any news about how to solve that?

**Comment by xNiallC** [comment]
I solved the issue by placing the Chips in a View with the following style:

`<View style={{flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start'}}>...</View`

Which causes them to behave as expected, with automatic width to match its child content.

**Comment by mitulptridhyatech** [comment]
Not work for me in FlatList
Code:
  renderComponents = ({item, index}) => {
    return (
      <Chip
        style={{width: null}}
        avatar={
          <Image
            source={{
              uri: 'https://picsum.photos/seed/picsum/200/300',
            }}
          />
        }
        onPress={() => console.log('Pressed')}>
        {item.title}
      </Chip>
    );
  };
<View
          style={{
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-start',
            backgroundColor: 'red',
          }}>
          <FlatList
            data={this.state.arrayholder}
            keyExtractor={this.keyExtractor}
            renderItem={(item, index) => this.renderComponents(item, index)}
          />
        </View>

**Comment by Michaelvons** [comment]
An alternative would be 
`<View style={{flexDirection: 'row',  flexWrap: 'wrap', justifyContent: 'flex-start'}}>...</View>`

Adding `flexWrap: 'wrap',` will allow the chips to fall into the next line when it reaches the end of the screen. 

Removing `alignItems: 'center'` will prevent the chips from stretching horizontally.

Cheers !

**Comment by Themrpie** [comment]
> 

I copied that style but for some reason it doesn't fall into the next line:
<img width="1282" alt="Captura de pantalla 2022-12-13 a la(s) 22 17 21" src="https://user-images.githubusercontent.com/73369706/207481088-1395dad6-af5a-4e01-80a0-fdc0893941d1.png">

**Comment by tibbe** [comment]
> flexWrap: 'wrap'

Unfortunately this doesn't prevent chips from overflowing if they are wider than the screen.
