### ISSUE TITLE
Children of Card component are not accessible to Appium for e2e tests

### ISSUE THREAD

**Issue by t-d-o-g** [callstack/react-native-paper#804]
### Current behaviour

"accessible" is not a prop of the Card component. Due to this, testID props added to child components of the <Card> component such as <TextInput> are not accessible to Appium for automated e2e testing.

### Expected behaviour

I expect to be able to add the accessible prop to a Card component and set it to false so that children of the Card component are accessible to Appium by using a testID prop value.

### Code sample

See snippet below from App.js to reproduce issue. 

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Card, TextInput, Button, DefaultTheme } from 'react-native-paper'

export default class App extends React.Component {
  render() {
    return (
      <Card style={styles.container}>
          <TextInput 
            testID='text-input'
            style={styles.inputContainerStyle}
            mode='outlined'
          />
      </Card>
    );
  }
}

const styles = StyleSheet.create({
  inputContainerStyle: {
    margin: 128,
  },
});
```

For complete app example clone this repo containing 2 versions of the app in /apps. One build using master react-native-paper branch and another build with fix branch. [CodeSample](https://github.com/t-d-o-g/CodeSample)

### Screenshots
Using Appium Inspector the text input field is not accessible within the card
<img width="1182" alt="appiuminspector-master" src="https://user-images.githubusercontent.com/5699210/52172130-335e1880-2737-11e9-8309-d5970529ef85.png">

### What have you tried

The text input field is accessible with \<Card accessible={false}>. See snippet below of App.js

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Card, TextInput, Button, DefaultTheme } from 'react-native-paper'

export default class App extends React.Component {
  render() {
    return (
      <Card style={styles.container} accessible={false}>
          <TextInput 
            testID='text-input'
            style={styles.inputContainerStyle}
            mode='outlined'
          />
      </Card>
    );
  }
}

const styles = StyleSheet.create({
  inputContainerStyle: {
    margin: 128,
  },
});
```

### Screenshots
Using Appium Inspector the text input field is accessible within the card
<img width="1180" alt="appiuminspector-pass-accessible-from-card-props-to-touchable-for-appium-tests" src="https://user-images.githubusercontent.com/5699210/52172134-47097f00-2737-11e9-99a9-e726b994d5c5.png">

I created a branch on a fork of the repo with an update that fixes the issue. If approved I can send a PR. [fix/pass-accessible-from-card-props-to-touchable-for-appium-tests](https://github.com/callstack/react-native-paper/compare/master...t-d-o-g:fix/pass-accessible-from-card-props-to-touchable-for-appium-tests)

### Your Environment

| software              | version
| --------------------- | -------
| ios      | 12.1
| react-native          | 31.0.0
| react-native-paper    | 2.9.1
| node                  | 10.9.0
| yarn           | 1.10.0
| expo sdk              | 31.0.2

**Comment by satya164** [comment]
Thanks for opening the issue. Feel free to send a PR :)

**Comment by t-d-o-g** [comment]
Thanks for reviewing this issue, I have submitted the following PR: https://github.com/callstack/react-native-paper/pull/812

**Comment by adanna21** [comment]
having this same issue with Xcode. Card doesn't have the prop accessible so none of it's children are accessible.

**Comment by ferrannp** [comment]
Fixed #812.

**Comment by BoazWarshawsky** [comment]
Hi @ferrannp, I am having the exact same problem with `TouchableHighlight`, any idea how I can solve it there?
Thanks!

**Comment by t-d-o-g** [comment]
@BoazWarshawsky I created a branch you can try in the app you are testing to see if it makes TouchableHighlight accessible.
https://github.com/t-d-o-g/react-native-paper/tree/fix/pass-accessible-from-touchableripple-to-touchables

**Comment by BoazWarshawsky** [comment]
Thanks @t-d-o-g, but I am not sure how I can test this branch,
I am kind of getting iOS RN project as is, building it locally, and testing it with the automation framework which based on Appium. 
I am coming from the automation side of it. not the iOS RN client development 

How can I test these changes?

**Comment by t-d-o-g** [comment]
Are you able to update the package.json file to replace "react-native-paper": "${version}" with "react-native-paper": "t-d-o-g/react-native-paper#fix/pass-accessible-from-touchableripple-to-touchables" and build it? If it works for you, you can submit a PR to this repo.

**Comment by t-d-o-g** [comment]
Or are you saying that you are just getting the XCode project files? If that's the case then yeah this won't work for you.

**Comment by BoazWarshawsky** [comment]
@t-d-o-g Updating the packages json is something I can do actually,
but I don't have in my `packages.json` that `react-native-paper` at all,
if I will just added with your branch and rerun `yarn`, that will work too?

**Comment by t-d-o-g** [comment]
@BoazWarshawsky this is probably not an issue with react-native-paper then, so I'm not sure what the solution is in this case.

**Comment by ferdinand-autumn** [comment]
Hi I'm still encountering this issue in v3.10.1

**Comment by makoy21** [comment]
I'm still encountering this issue in v3.10.1

**Comment by adirkz** [comment]
@ferrannp how did you solve it?
