### ISSUE TITLE
RadioButton "value" prop should not be required

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#807]
### Current behaviour

We have it required in case you use it with `RadioButton.Group` but if not, it should not be required (e.g. when you use a FlatList of `RadioButton(s)`).

### Expected behaviour

`value` should not be required if it is not used inside a `RadioGroup`. We can also think of creating a `RadioGroup.Item` which uses `RadioButton`.

### Your Environment

| software              | version
| --------------------- | -------
| react-native-paper    | 2.9.1

**Comment by satya164** [comment]
`value` refers to the identifier for the radio button. you need to pass it. `status` is optional.
