### ISSUE TITLE
RadioGroup clicking row with children

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#808]
### Current behaviour

RadioGroup will pass `onPress` to the `RadioButton` children. That makes not possible to for example have a whole row clickable.

### Expected behaviour

Proposed solution:

1. If children are solely `RadioButton`(s), place the `onPress` on it
2. If children contain something else, place a `TouchableRipple` around it with the `onPress` prop
3. Suggestions?

### Code sample

```js
<RadioButton.Group
  onValueChange={value => this.setState({ value })}
  value={this.state.value}
>
  <View style={styles.row}>
    <RadioButton value="first" />
    <Text>First</Text>
  </View>
  <View style={styles.row}>
    <RadioButton value="second" />
  </View>
</RadioButton.Group>
```

^ in this case, it'd be nice that `RadioButton.Group` would place a `TouchabelRipple` around the children and control the `onPress`.

[Snack here](https://snack.expo.io/@ferrannp/radiobutton.group?name=RadioButton.Group&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fradio-button-group.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20View%20%7D%20from%20%27react-native%27%3B%0Aimport%20%7B%20RadioButton%2C%20Text%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aexport%20default%20class%20MyComponent%20extends%20React.Component%20%7B%0A%20%20state%20%3D%20%7B%0A%20%20%20%20value%3A%20%27first%27%2C%0A%20%20%7D%3B%0A%0A%20%20render()%20%7B%0A%20%20%20%20return(%0A%20%20%20%20%20%20%3CRadioButton.Group%0A%20%20%20%20%20%20%20%20onValueChange%3D%7Bvalue%20%3D%3E%20this.setState(%7B%20value%20%7D)%7D%0A%20%20%20%20%20%20%20%20value%3D%7Bthis.state.value%7D%0A%20%20%20%20%20%20%3E%0A%20%20%20%20%20%20%20%20%3CView%3E%0A%20%20%20%20%20%20%20%20%20%20%3CText%3EFirst%3C%2FText%3E%0A%20%20%20%20%20%20%20%20%20%20%3CRadioButton%20value%3D%22first%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FView%3E%0A%20%20%20%20%20%20%20%20%3CView%3E%0A%20%20%20%20%20%20%20%20%20%20%3CText%3ESecond%3C%2FText%3E%0A%20%20%20%20%20%20%20%20%20%20%3CRadioButton%20value%3D%22second%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FView%3E%0A%20%20%20%20%20%20%3C%2FRadioButton.Group%3E%0A%20%20%20%20)%0A%20%20%7D%0A%7D&dependencies=react-native-paper).

### Your Environment

| software              | version
| --------------------- | -------
| react-native-paper    | 2.9.1

**Comment by sibelius** [comment]
any workaround for this one?

**Comment by hamidfzm** [comment]
@ferrannp Does react native paper 3 support this feature?

**Comment by Trancever** [comment]
@hamidfzm Unfortunately no, but we will accept a PR that implements this.
