### ISSUE TITLE
DataTable contents collapsing on itself

### ISSUE THREAD

**Issue by zigzter** [callstack/react-native-paper#813]
DataTable rows seem to be collapsing into a single line. Even the [Snack example](https://snack.expo.io/?name=DataTable&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fdata-table.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20DataTable%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aexport%20default%20class%20MyComponent%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3CDataTable%3E%0A%20%20%20%20%20%20%20%20%3CDataTable.Header%3E%0A%20%20%20%20%20%20%20%20%20%20%3CDataTable.Title%3EDessert%3C%2FDataTable.Title%3E%0A%20%20%20%20%20%20%20%20%20%20%3CDataTable.Title%20numeric%3ECalories%3C%2FDataTable.Title%3E%0A%20%20%20%20%20%20%20%20%20%20%3CDataTable.Title%20numeric%3EFat%3C%2FDataTable.Title%3E%0A%20%20%20%20%20%20%20%20%3C%2FDataTable.Header%3E%0A%0A%20%20%20%20%20%20%20%20%3CDataTable.Row%3E%0A%20%20%20%20%20%20%20%20%20%20%3CDataTable.Cell%3EFrozen%20yogurt%3C%2FDataTable.Cell%3E%0A%20%20%20%20%20%20%20%20%20%20%3CDataTable.Cell%20numeric%3E159%3C%2FDataTable.Cell%3E%0A%20%20%20%20%20%20%20%20%20%20%3CDataTable.Cell%20numeric%3E6.0%3C%2FDataTable.Cell%3E%0A%20%20%20%20%20%20%20%20%3C%2FDataTable.Row%3E%0A%0A%20%20%20%20%20%20%20%20%3CDataTable.Row%3E%0A%20%20%20%20%20%20%20%20%20%20%3CDataTable.Cell%3EIce%20cream%20sandwich%3C%2FDataTable.Cell%3E%0A%20%20%20%20%20%20%20%20%20%20%3CDataTable.Cell%20numeric%3E237%3C%2FDataTable.Cell%3E%0A%20%20%20%20%20%20%20%20%20%20%3CDataTable.Cell%20numeric%3E8.0%3C%2FDataTable.Cell%3E%0A%20%20%20%20%20%20%20%20%3C%2FDataTable.Row%3E%0A%0A%20%20%20%20%20%20%20%20%3CDataTable.Pagination%0A%20%20%20%20%20%20%20%20%20%20page%3D%7B1%7D%0A%20%20%20%20%20%20%20%20%20%20numberOfPages%3D%7B3%7D%0A%20%20%20%20%20%20%20%20%20%20onPageChange%3D%7B(page)%20%3D%3E%20%7B%20console.log(page)%3B%20%7D%7D%0A%20%20%20%20%20%20%20%20%20%20label%3D%221-2%20of%206%22%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%3C%2FDataTable%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D&dependencies=react-native-paper) is doing this, both in the web preview and on my phone.

![screenshot feb 5 2019 3_15_58 pm](https://user-images.githubusercontent.com/4925653/52310839-a5ae4300-2959-11e9-8dbc-62382650bccb.jpg)

I'm not running any custom styles, although the same issue being present in the Snack example makes me think it's not on my end.

**Comment by satya164** [comment]
cc @jaulz

**Comment by jaulz** [comment]
I could only replicate it in your example but it seems that a `minHeight` on the row helps to solve the issue. I will raise a PR in a minute.
