### ISSUE TITLE
TextInput not able to press in the middle or end of the box

### ISSUE THREAD

**Issue by RajkumarRamanathan** [callstack/react-native-paper#814]
### Current behaviour
when we create textinput its not allowing to click apart from label 

not able to click and type in the empty area of textinput
### Expected behaviour
Anywhere in the textinput box should be able to click

### Code sample
style={{ height: 100 }} this works incase of multi-line textview but not width. if i give width no effect on clickable area.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    |
| node                  |
| npm or yarn           |
| expo sdk              |

**Comment by RajkumarRamanathan** [comment]
Any Updates?

**Comment by RajkumarRamanathan** [comment]
Please let me know the detail what needed? 

straight issue is textinput in outlined mode only allows to in label area to start type (or get focused)

**Comment by satya164** [comment]
Please provide runnable example code which someone can test to see what's happening.

**Comment by RajkumarRamanathan** [comment]
Hi Satya, I have found the issue (manipulated the width value in input style). Thanks for the timely response.
