### ISSUE TITLE
Card.Title throws Invariant Violation: Element type is invalid

### ISSUE THREAD

**Issue by ShaggyKris** [callstack/react-native-paper#819]
### Current behaviour
When using `<Card.Title title='Hello' />`, throws the following error:

> Invariant Violation: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### Expected behaviour
`<Card.Title title='Hello' />` would display the title as "Hello".

### Code sample
[This is the Snack.Expo.io that is in the documentation. It occurs here as well.](https://snack.expo.io/@krispervin/Y2FyZA?name=Card&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fcard.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20Avatar%2C%20Button%2C%20Card%2C%20Title%2C%20Paragraph%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20(%0A%20%20%3CCard%3E%0A%20%20%20%20%3CCard.Title%20title%3D%22Card%20Title%22%20subtitle%3D%22Card%20Subtitle%22%20left%3D%7B(props)%20%3D%3E%20%3CAvatar.Icon%20%7B...props%7D%20icon%3D%22folder%22%20%2F%3E%7D%20%2F%3E%0A%20%20%20%20%3CCard.Content%3E%0A%20%20%20%20%20%20%3CTitle%3ECard%20title%3C%2FTitle%3E%0A%20%20%20%20%20%20%3CParagraph%3ECard%20content%3C%2FParagraph%3E%0A%20%20%20%20%3C%2FCard.Content%3E%0A%20%20%20%20%3CCard.Cover%20source%3D%7B%7B%20uri%3A%20%27https%3A%2F%2Fpicsum.photos%2F700%27%20%7D%7D%20%2F%3E%0A%20%20%20%20%3CCard.Actions%3E%0A%20%20%20%20%20%20%3CButton%3ECancel%3C%2FButton%3E%0A%20%20%20%20%20%20%3CButton%3EOk%3C%2FButton%3E%0A%20%20%20%20%3C%2FCard.Actions%3E%0A%20%20%3C%2FCard%3E%0A)%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper)

### Screenshots (if applicable)
![screen shot 2019-02-06 at 2 46 53 pm](https://user-images.githubusercontent.com/7747148/52365578-2cc4ef00-2a1e-11e9-8b61-34501e9166ce.png)

### What have you tried
Removing <Card.Title/> solves the problem. Also looked in the node_module folder and found that Card.Title is not being exported, and is entirely missing. **The documentation should be updated to reflect this.**

**Comment by jaulz** [comment]
`Card.Title` was introduced only 10 hours ago... I don't think it made it into npm yet.

**Comment by ShaggyKris** [comment]
> `Card.Title` was introduced only 10 hours ago... I don't think it made it into npm yet.

Kinda odd that the public documentation mentions it, then.

**Comment by Trancever** [comment]
@ShaggyKris What version of paper do you use? It should be available in 2.11.0.
