### ISSUE TITLE
Badge not rendering correctly on React-Native-Windows

### ISSUE THREAD

**Issue by creambyemute** [callstack/react-native-paper#820]
### Current behaviour

I'm using a <Badge> without any special styling, just 
```javascript
<Badge style={{ color: "black" }}>25</Badge>
```

This renders fine on iOS and Android, but on React-Native-Windows just the text is rendered but not the background circle (the actual badge).

See the screenshot

### Expected behaviour

To render the badge correctly

### Code sample
Use 
```javascript
<Badge style={{ color: "black" }}>25</Badge>
```
in a react-native-windows application.

### Screenshots (if applicable)

![badge](https://user-images.githubusercontent.com/3519121/52413008-a02f3500-2ae0-11e9-8b9a-2d7f8b600271.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Windows 10 UWP
| react-native          | 0.57.8
| react-native-paper    | 2.9.1
| node                  | v8.10.0
| npm or yarn           | 1.13.0
| expo sdk              | NO

### Possible fix
Wrap the Animated.Text with an Animated.View, not sure if this would fix it though.

**Comment by jaulz** [comment]
Unfortunately, I never used `react-native-windows`. Could you try to implement your suggested fix locally and let us know if it works? Or even better, could you create a PR?

**Comment by creambyemute** [comment]
Sure, I'll try and let you know if I found a solution that doesn't affect iOS/Android.$

**Comment by satya164** [comment]
Worst case, we can add a check and apply some styles only for windows.
