### ISSUE TITLE
Remove SafeAreaView around Snackbar [suggestion]

### ISSUE THREAD

**Issue by RichardLindhout** [callstack/react-native-paper#830]
It should be better to remove the SafeAreaView around the snackbar because now it's difficult to show it on top of a FAB button. Or e.g. on top of something instead of bottom.

Maybe we could have two components Snackbar and SnackbarContent or something.

**Comment by Trancever** [comment]
Hi @RichardLindhout Can you provide Snack that reproduces issue?

**Comment by RichardLindhout** [comment]
Your pull request could fix the issue (I would only need to add margin to my snackbar of the fab height)
But I don't know. Personally I like freedom and create the safeareviews myself instead of every component. Like three SafeAreaView (one in my screen, one in my fab, one in my snackbar)

**Comment by RichardLindhout** [comment]
+ sometimes I would like the snackbar component just to stay there without duration or something like that and handle it manually.


Material-UI references:
https://material-ui.com/api/snackbar-content/
https://material-ui.com/api/snackbar/
