### ISSUE TITLE
Validation TextInput

### ISSUE THREAD

**Issue by RajkumarRamanathan** [callstack/react-native-paper#832]
### Current behaviour

 validation happens based on textchange
### Expected behaviour
How to add validation based on onblur/ focus loss i am new to react, Please guide

### What have you tried
error={!validation._isUsernameValid(this.state.outlinedText)}

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    |
| node                  |
| npm or yarn           |
| expo sdk              |

**Comment by RajkumarRamanathan** [comment]
The below code worked thanks   

 onBlur={() =>{
             this.setState({
                    hasValidationError:!validation._isUsernameValid(this.state.name)
             });
            }
          }
          error ={this.state.hasValidationError}

**Comment by seungjikim** [comment]
validate 사용자 알림 input text에 onblur함수 정의
이메일 형식이 올바르지 않으면 helpertext 띄움
