### ISSUE TITLE
Add customisable size property for icon in FAB

### ISSUE THREAD

**Issue by soumyamishra89** [callstack/react-native-paper#837]
### Current behaviour
Icons are fixed at size 24 in FAB.

### Expected behaviour
Add a prop to support custom icon sizes similar to color and icon.

will it affect the layout if the icon size is customisable?
Currently the fab style can be customised using fabStyle property, which means the dimension of the FAB can be customised, but the icon is fixed at 24 which looks weird when the FAB is bigger.

**Comment by wibb36** [comment]
https://github.com/callstack/react-native-paper/compare/master...wibb36:patch-1
