### ISSUE TITLE
Customising FAB group

### ISSUE THREAD

**Issue by soumyamishra89** [callstack/react-native-paper#839]
### Current behaviour
1. The FAB component has disable property but not the FAB Group component
2. The label text on Fab Group has only default fontFamily.

### Expected behaviour
1. Add disable property to Fab Group as well as the action FABs.
2. Add an option to style the Label text.

In some screens, i would like to show the FAB Group with some items disabled or the entire Component disabled but visible.
The text on FAB items has a font different from the app font we use and is not customisable now.
Does this affect the material design guidelines? It should be a problem as single FAB component has disable property but is not extended to FAB Group

**Comment by Trancever** [comment]
cc @lukewalczak Could you take a look?

**Comment by soumyamishra89** [comment]
There is one more issue though.
When using FAB group with the portal component, it is rendered on all screens.
Even when i use visibility prop, the FAB becomes invisible but it still has actions enabled. The place where the FAB is rendered still accepts touch events though it is not visible.

**Comment by syedabuthahirm** [comment]
@soumyamishra89 Can you make a example repo (https://snack.expo.io)?

**Comment by gawrysiak** [comment]
@soumyamishra89 this I can confirm. If you're using react-navigation, you can try conditionally displaying it if the current page is focused:
```
import { withNavigationFocus } from 'react-navigation';
```
use this as HOC, then you're getting an isFocused prop. So later you just do:
```
this.props.isFocused ? <FAB.Group...

**Comment by gawrysiak** [comment]
related: #420

**Comment by soumyamishra89** [comment]
@gawrysiak I was using it with visibility prop, which seemed to be an issue. For now i have used to animations to move it from the focus when not visible so that the area is not blocked. 
Sometimes, when the component displaying FAb.Group is unmounted, still the area where it was displayed is left unclickable. I would create an example repo on snack to demonstrate what i mean.

**Comment by soumyamishra89** [comment]
[https://snack.expo.io/@ssmishra/react-native-paper-issue-839](url)
I have created repo for the issue i was talking about.
Here when u open the app, 
Steps: 
1. click on Hide Fab first. (this will set visibility = false)
2. click on show Fab. (this will render the fab group)
3. now click on the Unhide Fab.

At this point the Fab is not visible but u can still click on it and see the action which should not be the case.

**Comment by Trancever** [comment]
@soumyamishra89 Check this [snack](https://snack.expo.io/@trensik/react-native-paper-issue-839). I just changed a bit your example and cleaned it up.

**Comment by soumyamishra89** [comment]
@Trancever thank you for a quick reply, but in this case it solves the issue. I have also, used it in a way that solves the issue i was facing. 
But my point here is that the combination of portal and Fab to render FAB across screens and then hide it on condition does not work as expected as you might have seen with my previous example.
The prop visible on FAB group has issues with it.

**Comment by soumyamishra89** [comment]
@Trancever and coming back to the original issue, is there any update on disable feature on FAB Group?

**Comment by soumyamishra89** [comment]
@Trancever Hi, there is one more issue that i found while animating the FAB.Group. So, when the FAB.Group is clicked i want it to animate (rotate the add icon to look as close).
[https://snack.expo.io/@ssmishra/react-native-paper-issue-839](url) u can check this. instead of animated.value, i have added string to rotate for demonstration, but the issue is same for both. 
so, on my Moto G5 plus and some other phones, when the fabStyle is transformed to rotate beyond 45 deg, the icon disappears.
Is something wrong with the way the animation is used. I had checked the FAB container, and it is Animated.View, so the animation should work here. It works fine on some phone and not in some other phones.

**Comment by Trancever** [comment]
@soumyamishra89 Coming back to original issue, there is no disabled feature on FAB.Group cause Material Design Guidelines suggest not to disable FAB.Group but completely hide it. This prop exists on FAB component only because FAB supports extended mode.

**Comment by soumyamishra89** [comment]
> @Trancever Hi, there is one more issue that i found while animating the FAB.Group. So, when the FAB.Group is clicked i want it to animate (rotate the add icon to look as close).
> [https://snack.expo.io/@ssmishra/react-native-paper-issue-839](url) u can check this. instead of animated.value, i have added string to rotate for demonstration, but the issue is same for both.
> so, on my Moto G5 plus and some other phones, when the fabStyle is transformed to rotate beyond 45 deg, the icon disappears.
> Is something wrong with the way the animation is used. I had checked the FAB container, and it is Animated.View, so the animation should work here. It works fine on some phone and not in some other phones.

this issue is irrelevant now. I was mistaken, i thought changing icon would simply change the icon, but react-native-paper does a nice animation to change the icon, which solves my issue and i do not need to animate it separately. My bad, did not test it thoroughly before using separate animation.

**Comment by Trancever** [comment]
@soumyamishra89 Do you have any other issue or can we close this?

**Comment by soumyamishra89** [comment]
@Trancever i will close this issue.
can u have a look at this issue [https://github.com/callstack/react-native-paper/issues/837](url)

**Comment by kendallroth** [comment]
This can also be solved with the [`useIsFocused`](https://reactnavigation.org/docs/use-is-focused/) hook now.
