### ISSUE TITLE
No cursor displayed if user deletes the previously entered values from TextInput in error mode - [Android]

### ISSUE THREAD

**Issue by 888dev** [callstack/react-native-paper#844]
### Current behaviour

I'm using TexInput, on error mode only on Android, once the previous value was deleted, on focus again cursor is not displayed.
Steps to reproduce:
1. enter the value to the field
2. delete value and leave the field (field should be in error mode, because of its required field)
3. tap again on the field -> no cursor is displayed
4. enter again data and delete, unfocus the filed
5. focus again -> only now the cursor is visible

### Expected behaviour

The cursor should be displayed always on focus

### Code sample

                        <TextInput
                            label="First Name"
                            value={this.state.firstName}
                            error={this.state.firstNameError}
                            onChangeText={this.handleFirstNameChange}
                            onBlur={this.onBlurFirstName}
                        />
### Screenshots (if applicable)

The first one is focused (no cursor is visible)

![image](https://user-images.githubusercontent.com/22195312/52871425-a68c6500-310f-11e9-8610-03d324dbea3b.png)

### Your Environment

| software              | version
| --------------------- | -------
| android only        | 8.0.0
| react-native          | 0.58.4
| react-native-paper    | 2.11.1
| node                  | 8.12.0
| npm or yarn           | yarn 
| expo sdk              | https://snack.expo.io/HJ_m7gsIN

**Comment by 888dev** [comment]
any news on this issue?

**Comment by 888dev** [comment]
anything?

**Comment by Trancever** [comment]
@888dev Could you provide [snack](https://snack.expo.io/) that reproduces issue? It will be easier for us to check it.

Btw, are you able to reproduce it with TextInput from React-Native or only from Paper?

**Comment by 888dev** [comment]
@Trancever you can check this snack it is not working here as well, you cant see the cursor on error field only.
https://snack.expo.io/HJ_m7gsIN

**Comment by satya164** [comment]
I can't seem to repro it. What's your Android version?

![image](https://user-images.githubusercontent.com/1174278/53756198-de89fb00-3eb8-11e9-956d-0ab554350612.png)

**Comment by 888dev** [comment]
I am using galaxy s7 edge, android version 8.0.0

**Comment by Trancever** [comment]
@888dev Could you test on different devices/emulators with different android version?

**Comment by 888dev** [comment]
It is working on Android 9.0, but not on Android 8.0

**Comment by murtraja** [comment]
@888dev, for me this happens when the cursor color changes. Workaround here is to hardcode the value of `selectionColor` to your primary colour, then the cursor color won't change even if there is an error and you should be able to see the cursor always

**Comment by 888dev** [comment]
Thank you
