### ISSUE TITLE
Question : BottomNavigation and Portal

### ISSUE THREAD

**Issue by sm2017** [callstack/react-native-paper#845]
I am using `BottomNavigation` , in a Scene I am using `FAB.Group` , the FAB is rendered in all Scenes , How can I hide FAB in other Scenes?

**Comment by foxlol** [comment]
I'm in the same situation. Couldn't figure it out yet.

**Comment by sm2017** [comment]
@foxlol I found that you can use `Portal.Host`

**Comment by foxlol** [comment]
> @foxlol I found that you can use `Portal.Host`

Hi @sm2017 . I have seen it on the documentation but couldn't figure it out how this works. Can you help me please?

**Comment by sm2017** [comment]
```js
import * as React from 'react';
import {View} from 'react-native';
import { BottomNavigation, Text,FAB,Portal } from 'react-native-paper';

const MusicRoute = () => (
<View>
      <Text>Music</Text>
      <Portal.Host>
        <FAB.Group
          open={this.state.open}
          icon={this.state.open ? 'today' : 'add'}
          actions={[
            { icon: 'add', onPress: () => console.log('Pressed add') },
            { icon: 'star', label: 'Star', onPress: () => console.log('Pressed star')},
            { icon: 'email', label: 'Email', onPress: () => console.log('Pressed email') },
            { icon: 'notifications', label: 'Remind', onPress: () => console.log('Pressed notifications') },
          ]}
          onStateChange={({ open }) => this.setState({ open })}
          onPress={() => {
            if (this.state.open) {
              // do something if the speed dial is open
            }
          }}
        />
      </Portal.Host>
</View>
);

const AlbumsRoute = () => <Text>Albums</Text>;

const RecentsRoute = () => <Text>Recents</Text>;

export default class MyComponent extends React.Component {
  state = {
    index: 0,
    routes: [
      { key: 'music', title: 'Music', icon: 'queue-music' },
      { key: 'albums', title: 'Albums', icon: 'album' },
      { key: 'recents', title: 'Recents', icon: 'history' },
    ],
  };

  _handleIndexChange = index => this.setState({ index });

  _renderScene = BottomNavigation.SceneMap({
    music: MusicRoute,
    albums: AlbumsRoute,
    recents: RecentsRoute,
  });

  render() {
    return (
      <BottomNavigation
        navigationState={this.state}
        onIndexChange={this._handleIndexChange}
        renderScene={this._renderScene}
      />
    );
  }
}
```

**Comment by foxlol** [comment]
Thanks @sm2017, it seems to work, but weirdly when i use <Portal.Host /> the FAB looses its positioning feature.

**Comment by sm2017** [comment]
@foclol I think you must set `flex:1` as style for component, I don't run.my example code , may be it has wrong styles, But the `Portal.Host ` works for me

**Comment by foxlol** [comment]
@sm2017 are you using android or ios? In my app the `Portal.Host` works in the sense that it is not rendered after navigating away from the screen, but the positioning goes to top-right and the z-index is set to 0. Even with `flex: 1` i can't seem to make it work. I'm using the FAB inside a `ScrollView`.

**Comment by sm2017** [comment]
I test in Android, but I think it works on iOS too
Use inspector to find what style you must change, or add `borderWidth:1` to FAB and all parents to see components dimensions
Then use `flex:1` to fix it
