### ISSUE TITLE
Suggestion: Add duration prop to Dialog show/hide

### ISSUE THREAD

**Issue by AlexeyVlasenko** [callstack/react-native-paper#846]
Hi! I want to suggest add duration prop to Dialog component.
I think it would be nice to easily change duration time of show/hide Dialog Modal.

Thanks!

**Comment by Trancever** [comment]
Hi @AlexeyVlasenko I don't think that prop is relevant for Dialog component. Usually Dialogs shouldn't be dismissed automatically, but if you really want that feature, you can build your component which wrapps our Dialog and provides such functionality.
