### ISSUE TITLE
DataTable Header Text Wrap

### ISSUE THREAD

**Issue by rjsajnani1** [callstack/react-native-paper#848]
### Current behaviour

Unable to wrap the header title
<img width="355" alt="screenshot 2019-02-18 at 12 32 44 pm" src="https://user-images.githubusercontent.com/31607484/52930261-b52e8280-3382-11e9-97bb-5a18fb5b5984.png">

### Expected behaviour
I would like to add some style or atleast try to wrap the header title like the given image below

<img width="442" alt="screenshot 2019-02-18 at 12 35 20 pm" src="https://user-images.githubusercontent.com/31607484/52930336-02125900-3383-11e9-98e7-695b1d4f67dc.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios         | ios 12
| react-native          | 0.57.7
| react-native-paper   | 2.11

Any help is much appreciated.

**Comment by satya164** [comment]
We can add a `numberOfLines` prop to `DataTable.Title`. Wanna send a PR?

**Comment by rjsajnani1** [comment]
> We can add a `numberOfLines` prop to `DataTable.Title`. Wanna send a PR?

Yeah sure will work on one. 
Is there a particular process i need to follow or something to create a PR? 
Do let me know thanks.

**Comment by Trancever** [comment]
@rjsajnani1 This is our [Contributing Guide](https://github.com/callstack/react-native-paper/blob/master/CONTRIBUTING.md)

**Comment by Taym95** [comment]
If no one is working on this issue I would like to work on it

**Comment by Trancever** [comment]
@Taym95 Feel free to send PR :)

**Comment by dragneel30** [comment]
Hi

the multi line has been supported but the height of the text is constant to 24, so when doing multi line only first line is shown.

**Comment by charlesoruko** [comment]
This issue still persists any suggestions to make resolve it ?

**Comment by mineturtle2137** [comment]
are there any updates on this issue? the numberOfLines property does not work and there's no option to change the font size of the header

**Comment by Zeyu-Li** [comment]
@rjsajnani1 how do u use this prop? there doesn't appear to be an changes visible

**Comment by mikehardy** [comment]
@Zeyu-Li I feel like I must be missing something. I cannot get a multiline to work with `<DataTable.Header numberOfLines={2}>Text that should wrap</DataTable.Header>`

Can someone post an actual little snippet that is confirmed working? I'd really appreciate it. Thanks!

**Comment by mikehardy** [comment]
I think I repaired the original implementation so that it handles text component's special text alignment issues with wrapping, while allowing a cell height that is a multiple of numberOfLines - patch-package patch available here for testing: https://github.com/callstack/react-native-paper/pull/3015#issuecomment-996956251

**Comment by mikehardy** [comment]
My PR attempting to address this is release now in 4.12.0, hopefully it works for everyone!
