### ISSUE TITLE
Dialog.Content with dynamic content

### ISSUE THREAD

**Issue by ReneDH** [callstack/react-native-paper#850]
### Current behaviour
If I want to display a dynamic collection in the dialog from an array of string, the content is not displayed.
If I add static text to Dialog.Content, the ad will work.
When debugging, I can see that text from the array would be there to display.
 

### Expected behaviour
 The text from the listing is not visible. Why? Do I overlook something here?

### Code sample

 [Sample](https://snack.expo.io/@rene.dh/dialogcontent)

### Screenshots (if applicable)
 please try the sample

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 7.1.1 / ios 12.1.4
| react-native          | ^0.57.8
| react-native-paper    | ^2.5.0
| node                  | 10.15
| npm or yarn           | yarn
| expo sdk              |

**Comment by gawrysiak** [comment]
looks like your map doesn't return anything

**Comment by Trancever** [comment]
Yeah, @gawrysiak is right, just add return statement to your map function.

**Comment by ReneDH** [comment]
Sometimes you do not see the simplest - Thank you.
