### ISSUE TITLE
ProgressBar - Couldn't find a way to set progressBar's height

### ISSUE THREAD

**Issue by quytang** [callstack/react-native-paper#852]
### Current behaviour
I can't find a way to set Progressbar's height.
I managed to use this snippet but It didn't work.
```
<ProgressBar
          style={{ flex: 1, marginRight: 12, height: 20, paddingVertical: 20 }}
          progress={0.5}
          color={Colors.green800}
 />
```

### Expected behaviour
The height of the ProgressBar should be style-able.

**Comment by ferrannp** [comment]
Probably we can wait for https://github.com/callstack/react-native-paper/pull/735.

**Comment by ferrannp** [comment]
Done https://github.com/callstack/react-native-paper/pull/735.
