### ISSUE TITLE
Example app throws compilation error on `yarn web`

### ISSUE THREAD

**Issue by devautor** [callstack/react-native-paper#856]
### Current behaviour

Cloning the repo, and running example for web as given in instructions doesn't work. The app fails to compile.
```
ERROR in ../src/components/FAB/FABGroup.js
Module not found: Error: Can't resolve 'react-lifecycles-compat' in 'G:\git_projs\react-native-web\react-native-paper\src\components\FAB'
 @ ../src/components/FAB/FABGroup.js 50:0-51 296:0-8
 @ ../src/components/FAB/FAB.js
 @ ../src/index.js
 @ ./src/index.js
 @ ./App.web.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 ./App.web.js

ERROR in ../src/components/BottomNavigation.js
Module not found: Error: Can't resolve 'react-native-safe-area-view' in 'G:\git_projs\react-native-web\react-native-paper\src\components' @ ../src/components/BottomNavigation.js 61:0-55 550:29-41
 @ ../src/index.js
 @ ./src/index.js
 @ ./App.web.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 ./App.web.js

ERROR in ../src/components/Portal/PortalConsumer.js
Module not found: Error: Can't resolve 'regenerator-runtime/runtime' in 'G:\git_projs\react-native-web\react-native-paper\src\components\Portal'
 @ ../src/components/Portal/PortalConsumer.js 7:0-37 @ ../src/components/Portal/Portal.js
 @ ../src/index.js
 @ ./src/index.js
 @ ./App.web.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 ./App.web.js
i ｢wdm｣: Failed to compile.
```

### Expected behaviour

I should be able to see paper on web :)

### Code sample

I simply downloaded the repo, and followed instructions from `readme.md`:
>cd example
>yarn
>yarn web

### What have you tried

Nothing what docs didn't ask me to. (Reported as above!) I also tried this with deleting `yarn.lock`, and then doing the install and run, got the same error trace. [I just saw that `package.json` doesn't have `react-native-paper` as a dependency listed, so tried installing it and running, same error.]

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          | "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz"
| react-native-paper    | 
| node                  | v8.11.3
| npm or yarn           | yarn
| expo sdk              |

**Comment by satya164** [comment]
Did you run `yarn bootstrap` as mentioned in our contributing guide? https://github.com/callstack/react-native-paper/blob/master/CONTRIBUTING.md#development-workflow

**Comment by devautor** [comment]
Hello @satya164 I din't, didn't know I was contributing, I simply followed the `readme` from the `example` directory. Let me try and update you!
