### ISSUE TITLE
undefined is not an object (evaluating '_reactNativePaper.DataTable.Header')

### ISSUE THREAD

**Issue by amandeeptherockstar** [callstack/react-native-paper#868]
While using DataTable i am getting this error **"undefined is not an object (evaluating '_reactNativePaper.DataTable.Header')"**

This is expo code https://snack.expo.io/@amandeepkochhar/cmFudG

### Screenshots (if applicable)

![whatsapp image 2019-02-24 at 6 39 35 pm](https://user-images.githubusercontent.com/34765485/53299699-9ee16480-3863-11e9-880b-c9bda0ae72ff.jpeg)

### What have you tried
I was trying out this example for implementing pagination 
https://github.com/callstack/react-nativepaper/blob/master/example/src/Examples/DataTableExample.js

### Your Environment

| software              | version
| --------------------- | -------
| android or ios    | android v6.0
| react-native          |   058.5
| react-native-paper    | 2.11.1
| node                  | 10.3.0
| npm       | 6.7.0
| expo sdk      | 32

**Comment by satya164** [comment]
Update `react-native-paper` to `2.11.1` in the `package.json` in the snack.
