### ISSUE TITLE
TextInput with multiline and without label has incorrect placeholder alignment on iOS

### ISSUE THREAD

**Issue by edmundojr** [callstack/react-native-paper#870]
### Current behaviour

`TextInput` placeholder has incorrect alignment on iOS when used with `multiline={true}` and without `label`.

### Expected behaviour

Expect `TextInput` with `multiline={true}` and `placeholder` to look the same, whether with or without `label`.

Issue happens only on iOS, not on Android (see screenshots below).

### Code sample

```jsx
<TextInput
  placeholder={"Placeholder"}
  multiline={true}
  numberOfLines={1}
/>
```

### Screenshots (if applicable)

iOS  | Android 🤖
------------ | -------------
![ios](https://user-images.githubusercontent.com/213251/53339348-064bf280-38fe-11e9-95fa-e20e2a7e688b.png) | ![android](https://user-images.githubusercontent.com/213251/53339352-09df7980-38fe-11e9-97d6-10039df21416.png)

Note: none of the inputs are focused, problem is on the first screenshot, second input.

### What have you tried

Have tried to set `textAlignVertical` to `center` but that's an Android-only property. Also tried to have the label as an empty string, which fix the alignment but hides the placeholder – which I need.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS
| react-native          | 0.57.8
| react-native-paper    | 2.10.1
| node                  | 11.9.0
| npm or yarn           | yarn
| expo sdk              | no

**Comment by jbinda** [comment]
fixed in #1020
