### ISSUE TITLE
Customising Button dimensions

### ISSUE THREAD

**Issue by Pushplaybang** [callstack/react-native-paper#871]
### Current behaviour

When adjusting the button dimensions, such as width, height or padding, the touchable remains the same size.

### Expected behaviour

I would expect that the hole button remains touchable, rather than just the original size set by the library.

### Code sample

<Button style={{ height: 120 }}>Hi THere</Button>

### What have you tried

* setting various dimension properties, 
* attempting to adjust the size using flex, 
* adjust the size of the inner text element

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios 12.1
| react-native          |  0.58.5
| react-native-paper    | 2.11.1
| node                       | 10.15..0
| npm or yarn           | yarn

## Context
While there is another issue relating to this, it seemed to be about extreme customisation of the component #658. With the given example, I think this is neither a good idea for the library and is not what I'm after.

App developers will need to be able to use this in conjunction with custom elements, and tweak the UI to fit designs.   While this is possible with a number of elements, this can also get tricky in places.

## Needs
The first Instance I've experienced  with this is with the Button component which is an extremely common element to want to customise, but in order to do,  we need to 

* be able to affect the dimensions of the button, and in turn the `surface`, `TouchableRipple` and content wrapper `View` element dimensions. 
* we should be able to parse either text, or a custom element into the button, which we currently cannot.  

## Proposal
My initial proposal would look something like:
```js
// src/components/Button.js . from line 221

let childDimensions = {};

    if (style) {
      // style properties we will pass down.
      const transferableDimensions = [
        'width',
        'height',
        'padding',
        'horizontalPadding',
        'verticalPadding',
        'paddingTop',
        'paddingBottom',
        'paddingLeft',
        'paddingRight',
      ];

      Object.keys(style).forEach(key => {
        if (transferableDimensions.includes(key)) {
          childDimensions[key] = style[key]
        }
      })
    }

    return (
      <Surface
        {...rest}
        style={[
          styles.button,
          compact && styles.compact,
          { elevation },
          buttonStyle,
          style,
          { ...childDimensions },
        ]}
      >
        <TouchableRipple
          //...unchanged props removed for brevity
          style={[
            touchableStyle,
            { ...childDimensions },
          ]}
        >
          <View style={styles.content, {...childDimensions}}>
            {icon && loading !== true ? (
              <View style={styles.icon}>
                <Icon source={icon} size={16} color={textColor} />
              </View>
            ) : null}
            {loading ? (
              <ActivityIndicator
                size="small"
                color={textColor}
                style={styles.icon}
              />
            ) : null}
              {React.Children.map(
                children,
                child =>
                    typeof child === 'string'
                    ? <Text
                        numberOfLines={1}
                        style={[
                          styles.label,
                          compact && styles.compactLabel,
                          textStyle,
                          { fontFamily },
                        ]}
                      >
                        {uppercase ? child.toUpperCase() : child}
                      </Text>
                    : child
              )}
          </View>
        </TouchableRipple>
      </Surface>
    );

```

This allows us to put a view into the button if we choose, or maintain the convenience of the default styling , as well as be able to adjust the dimensions with width, height, and padding

The alternative I suppose would be to keep the additional check for whether we're dealing with a string, and offer a way through the theme, and withTheme to provide `buttonWrapperStyles` .

Material design is a wonderfully flexible design system, and set of principles,  it would be great to be able to bring a more fair level of customisation to this already fantastic library.  Where better to start than with the humble, and mighty Button.

I'm keen to fork and open an initial PR for this, if theres interest in it. @

**Comment by satya164** [comment]
Doesn't #854 address your use case?

**Comment by Pushplaybang** [comment]
@satya164  - unfortunately not.  This solution falls short, if you were to a) resize the button, or b) want to wrap a custom  View etc.    We could parse the values into to a custom prop like in that PR, which would get us away from a whitelist / loop in the button, which I don't like.   In both proposals `wrapperStyles` maybe more appropriate.

**Comment by Pushplaybang** [comment]
@satya164  - actually I SPOKE TOO SOON.  It absolutely addresses the first half of my issue.. being able to set the dimensions on that `View` seems to push the outer wrapper.

The second part would still be the button inner, moving the <Text>> component into a conditional, allowing both easy continued use, as users do, as well as the ability to parse in your own view / text / component element.

```js
{React.Children.map(
                children,
                child =>
                    typeof child === 'string'
                    ? <Text
                        numberOfLines={1}
                        style={[
                          styles.label,
                          compact && styles.compactLabel,
                          textStyle,
                          { fontFamily },
                        ]}
                      >
                        {uppercase ? child.toUpperCase() : child}
                      </Text>
                    : child
              )}
```

**Comment by satya164** [comment]
You can already pass `<Text />` elements since they are valid children of `<Text />`

**Comment by Pushplaybang** [comment]
@satya164 yes you can, but you cannot parse a `View` into `Text` and so you're limited to those styles already imposed on the Text element. There are many reasons to want to do this, including:

**Comment by satya164** [comment]
I don't think the ability to pass a `View` in your proposed solution will address any of those use cases.

Icon and text are separate children and that will only allow you to replace the text which doesn't solve your use case. However, you can already pass a `<Text />` child with custom styles and custom icon element which allows you to style your text.

For gradient backgrounds, you'll need to replace the whole wrapper view, so allowing a custom view instead of text won't address it either.

Not sure what kind of animation and custom interactions you are talking and it's hard to tell without concrete use cases. But in those cases, you can easily create your own Button component if you need that much customization.

We already provide the building blocks to build those things, `Surface` for a card-like element to provide consistent shadows in a cross-platform way, TouchableRipple which allows you to add ripple/highlight effect while handling the platform differences and android version differences automatically. For custom use cases, you can combine these components to create your own button.

Right now the only cumbersome thing to do is the shadow animation that button does. But PR is welcome to move it to Surface with an `animated` prop.

I think it's better not to think of hypothetical use cases and focus on the concrete use cases you have right now. We want things to be customizable, but also need them to be maintainable. It'll be bad if any refactors break people's existing usage.

**Comment by Pushplaybang** [comment]
@satya164  - these aren't hypothetical at all.  and yes, you have a text and icon prop, but allowing us to put a view in, under the Touchable, would allow for complete custom button if it's warranted, by the design, which in the App I'm currently building it does.  

While yes you could build the button from the building blocks, and re-implement it, that seems like an awefully unnecessary amount of additional work, when the framework could provide the flexibility easily, and without a cost to current users.

current problems:
* wrapping a text element in the existing text element means your text element inherits the styles of the 
* We can't parse props to the icon, so we can't style it.  we can't move it.  we can't animate it
  * examples:
    * loading animation / indicator (not the spinner), 
    * animated icon on interaction (we have 3 buttons that do this in our current design)
    * .yes these are still within the material design system, 
    * Material is a foundation, upon which we can build, even [google break their own rules](https://material.io/articles/how-google-created-a-custom-material-theme.html#01)
* yes we can wrap text inside a text, but why limit us?  

I mean no disrespect, but I'm not sure why the limits of what you could imagine, are the limits you seem determined to impose on what others create.

Regarding the proposal above, it superior to the current PR in that:

* **ZERO api change.** Nothing. 
* Dimension properties are parsed to all wrapper components, automatically, so that the Button component doesn't break if the user tries to resize it.
* still accepts plain text as it did
* If you wrap a view in the button, it allows for the options above, here is a demo with a linear gradient:

<img width="1556" alt="screenshot 2019-02-26 at 01 18 53" src="https://user-images.githubusercontent.com/1330359/53375655-89079880-3964-11e9-85ac-f5bc97b11eee.png">

note I'm using [React Native Linear Gradient](https://www.npmjs.com/package/react-native-linear-gradient), which allows you to use a native linear gradient view element 

The above is implemented as:

```js
          <Button
            mode="contained"
            theme={{ roundness: 40 }}
            style={{
              backgroundColor: 'transparent',
              width: 260,
              margin: 16,
              height: 80,
            }}
            onPress={() => this.props.reset()}>
            <View>
              <LinearGradient
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 0 }}
                colors={['#4c669f', '#3b5998', '#192f6a']}
                style={styles.linearGradient}>
                <Text style={styles.lgText}>Here is a gradient</Text>
              </LinearGradient>
            </View>
          </Button>
```

**Comment by Pushplaybang** [comment]
### Updated Proposal
Based on what I gleaned from #854 we only need to parse the dimension properties into the `View`  tag, please see my updated snippet below:

```js
    let childDimensions = {};

    if (style) {
      // style properties we will pass down.
      const transferableDimensions = [
        'width',
        'height',
        'padding',
        'horizontalPadding',
        'verticalPadding',
        'paddingTop',
        'paddingBottom',
        'paddingLeft',
        'paddingRight',
      ];

      Object.keys(style).forEach(key => {
        if (transferableDimensions.includes(key)) {
          childDimensions[key] = style[key]
        }
      })
    }

    return (
      <Surface
        {...rest}
        style={[
          styles.button,
          compact && styles.compact,
          { elevation },
          buttonStyle,
          style,
        ]}
      >
        <TouchableRipple
          borderless
          delayPressIn={0}
          onPress={onPress}
          onPressIn={this._handlePressIn}
          onPressOut={this._handlePressOut}
          accessibilityLabel={accessibilityLabel}
          accessibilityTraits={disabled ? ['button', 'disabled'] : 'button'}
          accessibilityComponentType="button"
          accessibilityRole="button"
          accessibilityStates={disabled ? ['disabled'] : undefined}
          disabled={disabled}
          rippleColor={rippleColor}
          style={touchableStyle}
        >
          <View style={styles.content, childDimensions}>
            {icon && loading !== true ? (
              <View style={styles.icon}>
                <Icon source={icon} size={16} color={textColor} />
              </View>
            ) : null}
            {loading ? (
              <ActivityIndicator
                size="small"
                color={textColor}
                style={styles.icon}
              />
            ) : null}
              {React.Children.map(
                children,
                child =>
                  typeof child === 'string'
                    ? <Text
                        numberOfLines={1}
                        style={[
                          styles.label,
                          compact && styles.compactLabel,
                          textStyle,
                          { fontFamily },
                        ]}>
                        {uppercase ? child.toUpperCase(): child}
                      </Text>
                    : child
              )}
          </View>
        </TouchableRipple>
      </Surface>
    );
```

current advantages over #854 are:

Regarding the proposal above, it superior to the current PR in that:

* **ZERO api change.** Nothing.
* Dimension properties are parsed to all the relevant internal wrappers, automatically, so that the Button component doesn't break if the user tries to resize it.
* still accepts plain text as it did, which is wrapped in a `Text` element with the default styling.
* View makes gradients, and small UI button animation flourishes possible.

**Comment by satya164** [comment]
> We can't parse props to the icon, so we can't style it.  we can't move it.  we can't animate it

You can totally pass a custom animated icon https://callstack.github.io/react-native-paper/

> please see my updated snippet below

Copying `width` and `height` from wrapper to the inner touchable will have zero effect. Also copying all padding and margin properties will double them. I don't think this is the desire behaviour.

If you really want this behaviour, you can easily pass the same style to both `style` and `contentStyle`.

> but allowing us to put a view in, under the Touchable, would allow for complete custom button if it's warranted
> here is a demo with a linear gradient:

Your demo doesn't have an icon or loading indicator. As they are sibling children, what you proposed will break when you have either of them. Sure that's enough for your use case, but as library maintainers, a feature we add should at least fit all use cases and not look ugly in an use which we support.

Also I don't really get why you want to use Button. You set the background color to transparent which removes all things the button actually does (e.g. elevation animation, theme dependent background color).

How is this:

```js
<Button>
 <View>
   <LinearGradient>
     <Text>Foo</Text>
   </LinearGradient>
 </View>
</Button>
```

Better than this?

```js
<LinearGradient>
  <TouchableRipple>
    <Text>Foo</Text>
  </TouchableRipple>
</LinearGradient>
```

`TouchableRipple` fits your use case perfectly. The point of button is to have pre-styled material design button. If you want completely different style then there is `TouchableRipple. 

It will be a bit more code if you add more customzation there and maybe theme dependent colors, but I you'll probably make a single `FancyButton` component ans re-use it everywhere. In that case, this code doesn't really matter.

> I mean no disrespect, but I'm not sure why the limits of what you could imagine, are the limits you seem determined to impose on what others create.

Because at the end of the day, we are the people who maintain it. The more ways we allow to change things freely, the harder it is for us to make sure that everything works properly and we don't break things people rely on every time we change a tiny thing. We want to provide a stable and reliable library.

Besides you are not limited by anything. You don't have to use every component from the library. Mix and match with your own components depending on what works for you. You should feel comfortable doing that, because that gives you more control. You don't have to struggle with a component's limitation when trying to use it in a way it wasn't designed for.

> Material is a foundation, upon which we can build, even [google break their own rules](https://material.io/articles/how-google-created-a-custom-material-theme.html#01)

I know it's just a guidelines. But my point is that why do you want to use a component while discarding all the styling it provides? The sole reason we export these building blocks like `TouchableRipple`, `Surface`, `Modal`, `withTheme` etc. is because you can reuse them to build componentss according to your use cases without having to start everything from scratch.

**Comment by Pushplaybang** [comment]
@satya164 

* please read the code in both proposals above. style properties are filtered, so no margin is transferred 
* I've only included padding as an example, agree this should come out the whitelist
* again but having to parse the icon down through props this is a problem. 
* what if I want the currently design material button with a linear graident background?  As is quite trendy currently?
* what is want a custom animation flourish inside the tradditional material button?
* I do not want to discard all the styles,  but I do want to ability to customize as I and my designers choose to

## Corrections
- By using the button element, as per my last proposal, you DO GET BOTH ELEVATION and the HIGHLIGHT/RIPPLE
- By using the button your code remains semantically clear
- this creates ZERO change for current implementations as opposed to #854 which arbitrarily introduces a new prop to the api

## re your comments
> Because at the end of the day, we are the people who maintain it. The more ways we allow to change things freely, the harder it is for us to make sure that everything works properly and we don't break things people rely on every time we change a tiny thing. We want to provide a stable and reliable library.

I understand the cautiousness, thus the nature of my proposal, to not change the api, but simply provide an escape hatch for advanced use cases, as I've demonstrated. 

> Besides you are not limited by anything. You don't have to use every component from the library. Mix and match with your own components depending on what works for you. You should feel comfortable doing that..

I am comfortable doing that, but I think from the numerous requests from your users, there is a clear desire and need for more flexibility in the framework . The reason for reaching for a UI library, is to speed up development, and provide a foundation.  If then have to go back ,and recreate all of the modules because a button has more padding, or a gradient background (never mind the other more complex needs I have).. 

Currently you can't resize a button without breaking it. #854 arbitrarily introduces a new prop on the button, requiring you to duplicate the size styles, into an arbitrarily named prop.

>Your demo doesn't have an icon or loading indicator. As they are sibling children, what you proposed will break when you have either of them. Sure that's enough for your use case, but as library maintainers, a feature we add should at least fit all use cases and not look ugly in a use which we support.

1. THIS IS A VERY CRUDE DEMO to show you that gradients do in-fact work, which you said they don't.
2.. I agree this should look ugly.
3 If I'm parsing in my own view, Its fair to expect me to then parse in an icon as well if I want it. 

## Minor updates:

    let childDimensions = {};

    if (style) {
      // style properties we will pass down.
      const transferableDimensions = [
        'width',
        'height',
         'alignItems',
        'justifyContent',
        'textAlign',
      ];

      Object.keys(style).forEach(key => {
        if (transferableDimensions.includes(key)) {
          childDimensions[key] = style[key]
        }
      })
    }

    return (
      <Surface
        {...rest}
        style={[
          styles.button,
          compact && styles.compact,
          { elevation },
          buttonStyle,
          style,
        ]}
      >
        <TouchableRipple
          borderless
          delayPressIn={0}
          onPress={onPress}
          onPressIn={this._handlePressIn}
          onPressOut={this._handlePressOut}
          accessibilityLabel={accessibilityLabel}
          accessibilityTraits={disabled ? ['button', 'disabled'] : 'button'}
          accessibilityComponentType="button"
          accessibilityRole="button"
          accessibilityStates={disabled ? ['disabled'] : undefined}
          disabled={disabled}
          rippleColor={rippleColor}
          style={touchableStyle}
        >
          <View style={styles.content, childDimensions}>
            {typeof children[0] === 'string' &&  icon && loading !== true ? (
              <View style={styles.icon}>
                <Icon source={icon} size={16} color={textColor} />
              </View>
            ) : null}
            {loading ? (
              <ActivityIndicator
                size="small"
                color={textColor}
                style={styles.icon}
              />
            ) : null}
              {React.Children.map(
                children,
                child =>
                  typeof child === 'string'
                    ? <Text
                        numberOfLines={1}
                        style={[
                          styles.label,
                          compact && styles.compactLabel,
                          textStyle,
                          { fontFamily },
                        ]}>
                        {uppercase ? child.toUpperCase(): child}
                      </Text>
                    : child
              )}
          </View>
        </TouchableRipple>
      </Surface>
    );

**Comment by satya164** [comment]
> please read the code in both proposals above. style properties are filtered, so no margin is transferred

I have read it. Nothing is filtered in your code example. You are getting few properties from `style` and passing them to the inner item as `childDimensions`. You still pass the `style` prop as is to the container.

Anyway, even if you filter it, there are more properties than `padding` we need to take care of for consistent behaviour (e.g. `alignItems` and `justifyContent` like you added in your revised code, which shows that it's hard to get it right). It'll be very confusing if some styles you pass affect the content and some don't. We can go through list of all style properties and ensure wwe pass all the things necessary, but it's a lotof work and more maintenance burden that just adding a new prop.

It's more work than necessary, while `contentStyle` solves it easily.

> what if I want the currently design material button with a linear graident background?  As is quite trendy currently?

I totally want to support this use case. But react-native doesn't make it easy. The solution you propose won't work at all when you have an icon or loading indicator as I already mentioned.

Also people will also want to do the same for FAB, or Appbar. We should think about a consistent solution which addresses those use cases if we're going to solve it. Adding one off workarounds is where the code will get messy. And in case of a library, it's very hard get rid of old baggage without breaking people's code.

> By using the button element, as per my last proposal, you DO GET BOTH ELEVATION and the HIGHLIGHT/RIPPLE

Pretty sure elevations don't work on Android with transparent background, but happy to be proven wrong.

Also as I mentioned earlier, happy to accept a PR which moves the elevation animation part to `Surface` so you don't need any extra code when building your own button.

> By using the button your code remains semantically clear

With your proposal I'm pretty sure you wouldn't want to duplicate the code and create a button component to reuse. In that case, your code still remains semantically clear.

> this creates ZERO change for current implementations as opposed to #854 which arbitrarily introduces a new prop to the api

Usually I favor not adding new props, but in this case adding a new prop is the best option. Zero changes in API doesn't always mean more maintainable. Core react-native components such as `ScrollView` already expose props like `contentContainerStyle`, so it's not a arbitrary concept.

> THIS IS A VERY CRUDE DEMO to show you that gradients do in-fact work, which you said they don't

Where did I say that gradients won't work? I just said that it won't work in all cases (such as icons and loading indicator). Please avoid all caps text. It makes it seem like you are screaming and honestly it's not very professional.

Anyway, I am unsubscribing from this issue. I have already mentioned all the flaws with your approach and suggested possible solutions. I don't feel like I have anything to add and don't have energy to continue the conversation.

If you come up with a better solution, feel free to post and discuss with other members of the repo.

**Comment by Pushplaybang** [comment]
@satya164 do you understand that you can't resize a button at the moment without duplicating your dimension properties now between `style` and `contentStyle`.  Does that seem intuitive to you?

> where did you say gradients won't work?

> For gradient backgrounds, you'll need to replace the whole wrapper view, so allowing a custom view instead of text won't address it either.

have the decency and self-respect to at least acknowledge when you're wrong.

regarding the icon and loading text, I've addressed this several times.

>you're not filtering anything

I most certainly am and gave an example in the first post of this issue.

> Pretty sure elevations don't work on Android with a transparent background, but happy to be proven wrong.

completely irrelevant to the current discussion, and whether or not shadow should be surface is a separate issue.

>Also people will also want to do the same for FAB, or Appbar 

absolutely, and if those currently break when you **intuitively parse simple dimension properties** to them via the style prop I'd highly recommend we consider a similar approach, as well as provide the ability to embed a View, if it inherently provides value, which I could see with the FAB, but not the Appbar Necessarily.

>Adding one off workarounds is where the code will get messy

this isn't a one-off workaround, its an issue related to the button element that seems inherent in the library.  Its also not a pull request or meant to show a final implementation.

Whats unprofessional @satya164 is that its clear from your responses you have only skimmed this issue, and seem to have been defensive and dismissive from the beginning.  I'd love to hear from someone else, and really hope that we can do better than this.
