### ISSUE TITLE
KeyboardAvoidingView not working with TextInput password fields

### ISSUE THREAD

**Issue by hussainahmad** [callstack/react-native-paper#873]
### Current behaviour
Currently when remove `secureTextEntry={true}` it works fine like when I press `next button` on keyboard it will go to password textInput field from State textInput field and also `password textInput field` scroll up and works perfectly, but when I added  `secureTextEntry={true}` which is mandatory  this is not working for password fields, working fine on other fields perfectly.  I also created a demo code, Please look into this. This issue is only in Android. 
 
### Expected behaviour

On Press `next button` it should be go to password fields and and password filed should also show on screen

### Code sample

[Demo Code](https://github.com/hussainahmad/React-Native-Form-Demo)

### Screenshots (if applicable)

![screenshot_20190226-122648](https://user-images.githubusercontent.com/5903522/53394742-fd245980-39c1-11e9-9734-035712d6c2ae.png)

### Your Environment

| software              | version
| --------------------- | -------
| android        | 8.0.1
| react-native          | 0.57.1
| react-native-paper    | 2.11.1
| node                  | 8.12.0
| npm         | 6.4.1
| expo sdk              | 32.0.0

**Comment by Trancever** [comment]
Hi @hussainahmad, I am pretty sure this issue is not related to our library, cause we don't do anything special with TextInput. Could you try to replace TextInputs from Paper with those from react-native and check if you still encounter that problem? 
Btw, KeyboardAvoidingView has a lot of issues and you can try this package - https://github.com/APSL/react-native-keyboard-aware-scroll-view.

**Comment by hussainahmad** [comment]
HI @Trancever , Yes this is my mistake this issue is not in `react-native-paper`, This issue is in `TextInput` in **react-native**,   Work Around for this issue is : 
```async renderPassword(password, passType) {
    let pass = password;
    let fakePass = '';
    fakePass = pass.replace(/\s|[0-9_A-Za-z]|\W|[#$%^&*()]/g, '*')
    if (passType === 'pass') {
      this.setState({
        password: password,
        fakePassword: fakePass,
      });
    } else if (passType === 'repeatPass') {
      this.setState({
        repeatPassword: password,
        repeatFakePassword: fakePass,
      });
    }
  }
```
[complete solution](https://github.com/hussainahmad/React-Native-Form-Demo/pull/1/commits/d100713158a55527c92158af212b07fe51441c08)

**Comment by Trancever** [comment]
@hussainahmad ?

**Comment by hussainahmad** [comment]
Sorry mate, You are right This is in react-native `TextInput`, not in `react-native-paper`,
