### ISSUE TITLE
Textinput height

### ISSUE THREAD

**Issue by a1lu** [callstack/react-native-paper#877]
### Current behaviour

If i change (make it smaller) the height of the TextInput component the placeholder text is not centered.

### Expected behaviour
A smaller textinput with the placeholder centered

### Code sample

<TextInput style={{width: '100%', height: 44}} mode='outlined' label='Test' />

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android 7
| react-native          | 0.58.5
| react-native-paper    | 2.11
| node                  |
| npm or yarn           |
| expo sdk              |

**Comment by viv3kk** [comment]
Facing the same issue..

**Comment by jcarloTA** [comment]
Same problem, when I add custom styles for height, these are reflected only in the parent but the component seems to have default styles for the child, a suggestion would be to add something like childStyles so that we can customize the child component as well

`style: [
            styles.input,
            childStyles, // <---just here!
            mode === 'outlined'
              ? styles.inputOutlined
              : this.props.label
                ? styles.inputFlatWithLabel
                : styles.inputFlatWithoutLabel,
            {
              color: inputTextColor,
              fontFamily,
              textAlignVertical: multiline ? 'top' : 'center',
            },
  ],`

**Comment by elizamaria** [comment]
I also tried something for this to work, first for the flat input. Is it ok to add a new props style for the input child component that @jcarloTA said? I also make us of the input height in order to fix the label position when the height is smaller.

**Comment by jbinda** [comment]
fixed in #1020

**Comment by jmoliugp** [comment]
It doesn't seem to have been fixed.

I tried it out using this component with `2.16.0` version:

```
import * as React from 'react';

import { TextInput } from 'react-native-paper';

export default class MyComponent extends React.Component {
  state = {
    text: ''
  };

  render(){
    return (
      <TextInput
        label='Email'
        value={this.state.text}
        onChangeText={text => this.setState({ text })}
        style={ { marginVertical: 50, height: 150, textAlign: 'center', backgroundColor: 'grey' } }
        dense={true}
      />
    );
  }
}
```

**Comment by jbinda** [comment]
Hi @jmoliugp

Issue was fixed in 3.0 branch which is current master.

Regards

**Comment by Noorulhuda682** [comment]
{this.state.emailMsg !== '' &&
                  <HelperText type="error" visible={true} >
                         {this.state.emailMsg}
                      </HelperText> 
                  }    
               <TextInput
                  label='Password'
                  value={this.state.password}
                  style={{borderColor:'rgb(18, 48, 92)',height:40}}
                  onChangeText={password =>{ this.setState({ password }), 
                 this.validation(password,'password') }}
                  mode='outlined'
                  error={this.state.passwordErr}
                  secureTextEntry
                />

**Comment by Noorulhuda682** [comment]
When HelperText  appears TextInput do not get focused

**Comment by Noorulhuda682** [comment]
What the best solution for it?

**Comment by Trancever** [comment]
@Noorulhuda682 Please provide a [Snack](https://snack.expo.io/) that reproduces issue.

**Comment by shafqatbari** [comment]
this issue is not resolved i tried it .

    "react-native-paper": "^4.8.1",

when we set height in style
style={{
               height: 50
            }}

then placeholder and entered value is not centered and its scrollable
