### ISSUE TITLE
Snackbar Duration Question

### ISSUE THREAD

**Issue by t-hughes** [callstack/react-native-paper#878]
I assumed any number value could be passed to the duration prop. Is this not the case?

### Current behaviour

Passing Infinity to the duration prop gives me an error:

Expected dynamic type 'double' but had type 'null'. (constructing arguments for Timing.createTimer at argument index 1)

### Expected behaviour

Assumed we could pass any value that is a number to the duration prop.

### Code sample

```
        <Snackbar
          visible={this.props.isBLESnackbarVisible}
          onDismiss={this.onDismiss}
          duration={Infinity}
          theme={theme}
          action={{
            label: 'SETTINGS',
            onPress: () => {
              AndroidOpenSettings.bluetoothSettings();
            },
          }}
        >
          Try resetting bluetooth.
        </Snackbar>
```

### What have you tried

I have passed in other number values with success (i.e. 15000, 30000, etc.)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android
| react-native          | 0.57.8
| react-native-paper    | 2.7.0
| node                  | 7.0.0
| npm or yarn           | 6.4.1

**Comment by Trancever** [comment]
Under the hood we use setTimeout api, and according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Maximum_delay_value) passing bigger value than 32-bit Integer will lead to integer overflow which should be avoided. Additionally, we have exposed 3 different durations recommended by Material Design Guidelines as a static properties which should be used in most cases. Of course you can pass plain number as a workaround but, make sure to not use that big numbers, cause it can lead to random behaviour.

**Comment by satya164** [comment]
Maybe we can add a special check for Infinity?

**Comment by Trancever** [comment]
And what should we do in that case? Pass biggest safe number?

**Comment by satya164** [comment]
@Trancever don't add a timeout at all if Infinity is passed, coz the snackbar is supposed to shown forever in that case, unless dismissed by user

**Comment by Trancever** [comment]
@satya164 Ahh that makes sense :D @t-hughes Do you wanna implement that and send PR?

**Comment by Taym95** [comment]
I would like to work on this issue!

**Comment by satya164** [comment]
@Taym95 awesome! PR welcome :)
