### ISSUE TITLE
How to use avatar on CHIP? 

### ISSUE THREAD

**Issue by ManalLiaquat** [callstack/react-native-paper#879]
I can't understand docs https://callstack.github.io/react-native-paper/chip.html

guide me how to show avatar in chip `<Chip avatar={ ??? }>`

**Comment by Trancever** [comment]
Try `<Chip avatar={<Image source={require('../../assets/images/avatar.png')} />}>Chip</Chip>`

**Comment by LucasLuco** [comment]
hi @Trancever, this seem not working in latest version

**Comment by sandeeptalabathula** [comment]
try this - 
<Chip avatar={<Avatar.Image size={24} source={{ uri: TestImageUri }} />} onPress={() => console.log('Pressed')}>{TestTitle}</Chip>

**Comment by Harikarthyk** [comment]
```
<Chip 
     onLongPress={()=>{}}                  
     onPress={() => { }}
     selectedColor={activeSubCategoryIndex === index ? "#fff" : "#000"}
     selected={activeSubCategoryIndex === index} 
     avatar={< Avatar.Image size={24} source={{ uri: item.coverImage }} />} 
>

     <Text style={activeSubCategoryIndex === index ? {fontWeight : "700" } : {fontWeight : "400"}}>{item.name}</Text>

</Chip>
```
