### ISSUE TITLE
Checkbox invisible when unchecked on iOS

### ISSUE THREAD

**Issue by abaart** [callstack/react-native-paper#881]
### Current behaviour

On iOS an unchecked checkbox is invisible, which is not user friendly. Additionally, the `uncheckedColor` prop is not implemented on iOS.
### Expected behaviour

By default the checkbox should be visible. `uncheckedColor` should be implemented on iOS, or at least in the documentation it should be mentioned that this prop is Android-only.

### Code sample

The code as provided in the documentation

### What have you tried

What I tried (and what I think is also the most logical course of action) is to use the uncheckedColor prop to change the color of an unticked checkbox. However this is not implemented on iOS.
### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-paper    |
| node                  |
| npm or yarn           |
| expo sdk              |

**Comment by getinfyKiranreddy** [comment]
Same thing I have been trying to modify an IOS uncheck color

**Comment by nazrdogan** [comment]
According to this doc , there is no problem at all. but I agree with you :). https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines

**Comment by abaart** [comment]
Hmm, ok so this should be an issue on the material design language then... How shall we proceed?

**Comment by gawrysiak** [comment]
@abaart for iOS, they usually prefer the switch component when building layouts. It could be a good idea to display it conditionally e.g. Platform.OS === 'ios' ? <Switch /> : <Checkbox />

**Comment by gawrysiak** [comment]
related: #390

**Comment by kodayashi** [comment]
Docs should call out that iOS ignores this prop. Would also like to see the ability to set an unchecked color on iOS and/or border/customize the icon.

**Comment by adteague** [comment]
You can always use ‘<Checkbox.Android />’ to just use the Android properties (ie. outlined unchecked box)

**Comment by deathemperor** [comment]
Just wanna note that RadioButton has the same issue. And apply @adteague also works too but code may look confusing for others...

**Comment by snehadange** [comment]
> You can always use `<Checkbox.Android />` to just use the Android properties (ie. outlined unchecked box) on iOS devices.

Thank it works

**Comment by hinalt** [comment]
> <Checkbox.Android

Can you please give an example?
