### ISSUE TITLE
Feature request: custom left and right same as listItem in buttons (Fab and normal)

### ISSUE THREAD

**Issue by RichardLindhout** [callstack/react-native-paper#888]
### Current behaviour

It's hard to add na icon to the right side of a button.

### Expected behaviour

We should make the button more simple and remove loading and icon props. We should however let the user change the left or right inner of button. 

### Code sample
```
<Button left={()=><Button.Icon icon={'check'}}>Press me</Button>
```
Or maybe.
```
<Button>
 <Button.Icon icon={'check'} />
 <Button.Text>press me</Button.Text/>
 <Button.Icon icon={'check'} />
 {loading && <Button.Loader />}
</Button>
```

**Comment by murtraja** [comment]
@RichardLindhout , How do you add an icon on the right instead of the left as of now?

**Comment by RichardLindhout** [comment]
@murtraja I don't or I create a custom component myself. But I think we need the same behaviour with customizing as material-ui does. Let the user change all props of all subcomponents. But I don't know if the maintainers think that's a good idea.
