### ISSUE TITLE
List.Subheader is missing

### ISSUE THREAD

**Issue by nazrdogan** [callstack/react-native-paper#891]
### Current behaviour
 When I try to use List.SubHeader its giving error.

` <List.Subheader>Some title</List.Subheader>`

### Expected behaviour
 it should not in documents or it should be available in paper.

### Code sample
Try on Snack.
https://callstack.github.io/react-native-paper/list-subheader.html

### Screenshots (if applicable)
![img_7952](https://user-images.githubusercontent.com/1672303/53807096-5f97cf80-3f57-11e9-87cb-ec2c86e16fa9.PNG)

**Comment by Trancever** [comment]
@nazrdogan We are generating documentation from master branch and it already contains List.Subheader, but latest npm version does not have it yet. You can expect new version landing on npm in next couple of days.

Btw, we are planning to change the current behaviour and only publish docs when we publish new version of library on npm to prevent such situations.

**Comment by nazrdogan** [comment]
@Trancever  Yeah. I saw PR's but docs are misleading sometimes. it will better published version on docs.
