### ISSUE TITLE
Switch component crashing the app on Android

### ISSUE THREAD

**Issue by cdn34** [callstack/react-native-paper#894]
### Current behaviour
App crashes when adding the Switch component

### Expected behaviour
Component loading correctly.

### Code sample

        <Switch
          value={this.state.includePDF}
          disabled={false}
          onValueChange={() => {
            this.setState({ includePDF: !this.state.includePDF });
          }}
        />
### Screenshots (if applicable)
![screenshot_20190306-120529_paperpile](https://user-images.githubusercontent.com/4263618/53880074-f623c980-4007-11e9-8011-2b7c56c9df98.jpg)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android
| react-native          | 0.57.1
| react-native-paper    | 2.12.0
| node                  | 9.4
| npm or yarn           | Yarn
| expo sdk              | No

**Comment by ferrannp** [comment]
@cdn34 can you provide a Snack?

**Comment by arled** [comment]
🍩

**Comment by TingAli** [comment]
Getting this same issue, it's constantly trying to render it but failing to do so.

**Comment by TingAli** [comment]
Works fine on the following, in case anyone else is wondering:

`"react-native": "0.58.3",
"react-native-paper": "2.11.0",`
