### ISSUE TITLE
Please Help with Bottom Navigation

### ISSUE THREAD

**Issue by ilyaux** [callstack/react-native-paper#896]
## Please Help with Bottom Navigation

I have a BottomNav element. It is located on the main page of the application - Feed Page. When I click on the icon in BottomNav to go to the MapScreen page nothing happens. Help solve the problem.

**BottomNav**
```
import React from "react";
import { StyleSheet } from "react-native";
import { BottomNavigation } from "react-native-paper";
import {  MapScreen } from "../screens/";



export default class BottomNav extends React.Component {
  state = {
    index: 0,
    routes: [
      { key: "Feed", title: "Feed", icon: "photo-album", color: "#6200ee" },
      { key: "MapScene", title: "MapScene", icon: "inbox", color: "#2962ff" }
    ]
  };

  render() {
    return (
      <BottomNavigation
        style={styles.BottomNav}
        navigationState={this.state}
        onIndexChange={index => this.setState({ index })}
        renderScene={BottomNavigation.SceneMap({
          Feed: MapScreen,
          MapScene: MapScreen
        })}
      />
    );
  }
}
```

**MapScreen**
```
import React from "react";
import { View, Text, StyleSheet } from "react-native";
import { HeaderProfile } from "../uikit/";

export default class MapScreen extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      active: "bookmark-border"
    };
  }

  render() {
    return (
      <View style={styles.MapScreen}>
        <View style={styles.Header}>
          <HeaderProfile />
        </View>

        <Text> Text </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  MapScreen: {
    backgroundColor: "#1f1f1f",
    height: "100%",
    flex: 1,
    width: "100%"
  },
  Header: {
    marginTop: 24
  }
});
export { MapScreen };
```

**Comment by Trancever** [comment]
Please check this [Snack](https://snack.expo.io/?name=BottomNavigation&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fbottom-navigation.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20BottomNavigation%2C%20Text%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MusicRoute%20%3D%20()%20%3D>%20<Text>Music<%2FText>%3B%0A%0Aconst%20AlbumsRoute%20%3D%20()%20%3D>%20<Text>Albums<%2FText>%3B%0A%0Aconst%20RecentsRoute%20%3D%20()%20%3D>%20<Text>Recents<%2FText>%3B%0A%0Aexport%20default%20class%20MyComponent%20extends%20React.Component%20%7B%0A%20%20state%20%3D%20%7B%0A%20%20%20%20index%3A%200%2C%0A%20%20%20%20routes%3A%20%5B%0A%20%20%20%20%20%20%7B%20key%3A%20%27music%27%2C%20title%3A%20%27Music%27%2C%20icon%3A%20%27queue-music%27%20%7D%2C%0A%20%20%20%20%20%20%7B%20key%3A%20%27albums%27%2C%20title%3A%20%27Albums%27%2C%20icon%3A%20%27album%27%20%7D%2C%0A%20%20%20%20%20%20%7B%20key%3A%20%27recents%27%2C%20title%3A%20%27Recents%27%2C%20icon%3A%20%27history%27%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%7D%3B%0A%0A%20%20_handleIndexChange%20%3D%20index%20%3D>%20this.setState(%7B%20index%20%7D)%3B%0A%0A%20%20_renderScene%20%3D%20BottomNavigation.SceneMap(%7B%0A%20%20%20%20music%3A%20MusicRoute%2C%0A%20%20%20%20albums%3A%20AlbumsRoute%2C%0A%20%20%20%20recents%3A%20RecentsRoute%2C%0A%20%20%7D)%3B%0A%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20<BottomNavigation%0A%20%20%20%20%20%20%20%20navigationState%3D%7Bthis.state%7D%0A%20%20%20%20%20%20%20%20onIndexChange%3D%7Bthis._handleIndexChange%7D%0A%20%20%20%20%20%20%20%20renderScene%3D%7Bthis._renderScene%7D%0A%20%20%20%20%20%20%2F>%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D&dependencies=react-native-paper)

**Comment by Trancever** [comment]
Btw, do you know that you render same component on both routes?

**Comment by gtbhopale2412** [comment]
Hi,it gives error at MapScene: MapScreen

Type 'typeof MapScreen' is not assignable to type 'ComponentType<{ route: Route; jumpTo: (key: string) => void; }>'.
