### ISSUE TITLE
Badge component is missing

### ISSUE THREAD

**Issue by RaheelJaved** [callstack/react-native-paper#897]
my simple component (code below) fails to render

```
//other imports
import { Text, IconButton, Badge } from 'react-native-paper';
const MyBadge = () => <Badge>0</Badge>;
//inside render()
<MyBadge />
```

I installed react-native-paper using npm like this:
`npm install --save react-native-paper`

I looked into `node_modules\react-native-paper\src\components\` in my project folder and there is no `Badge.js` there

`node_modules\react-native-paper\src\index.js` also has no export of Badge.

Why so? Am I looking at the right place? What do I need to get the Badge component and use it?

**Comment by jaulz** [comment]
@RaheelJaved can you check in `package.json` which version you installed?

**Comment by RaheelJaved** [comment]
@jaulz it is 2.4.0

`"react-native-paper": "^2.4.0",`

**Comment by satya164** [comment]
The latest version is `2.12.0`. Please upgrade.
