### ISSUE TITLE
Add suffix, prefix, leading and trailing Icon to TextInput

### ISSUE THREAD

**Issue by 0x01Brain** [callstack/react-native-paper#903]
## Describe the feature

The current HelperText has only error, and info. But does not have adding custom suffix or prefix, example is shown here:
https://material.io/design/components/text-fields.html#filled-text-field

![image](https://user-images.githubusercontent.com/13728193/53967014-da0a5000-410d-11e9-8a74-c30650c5ac08.png)

**Comment by lemonlimemango** [comment]
Hey thanks for making the great library! Is there a status update on this item? Specifically I am interested in the `trailingIcon`. Do you need someone from the community to pick this up?

**Comment by vikas-chhabra** [comment]
What's the status for add leading and trailing icon in text input of react-native-paper?

**Comment by Raunak-Agrawal** [comment]
Any update on this? It would be useful it would add trailing icon at the end. I was trying to add password field and I needed that eye icon to hide/show password.

**Comment by flowed** [comment]
Waiting for this!

**Comment by conrad90909** [comment]
Any chance of an ETA, even if vague so we know it is coming or being worked on?  We just started using react native paper and had assumed this would work till we tried doing it.  Alternatively we need another solution and frankly this looks like the best one by far!

Many thanks.

**Comment by kamui545** [comment]
Looks like a PR is on its way https://github.com/callstack/react-native-paper/pull/1651

**Comment by Pranav-794** [comment]
This seems useful and fits our use case as well. What is the status on this PR?

**Comment by yohix** [comment]
Waiting for this to Merged :tada:

**Comment by kkkasio** [comment]
i'm waiting this pr <3

**Comment by velidan** [comment]
The same. Please, guys, let's do it

**Comment by antropovAlexandr** [comment]
I`m waiting this pr, too((

**Comment by anuragnagarkota** [comment]
Hey any updates.

**Comment by Vchouliaras** [comment]
Hey guys! do you have an ETA for this feature?

**Comment by jbinda** [comment]
closed via https://github.com/callstack/react-native-paper/pull/1651

**Comment by mrakus-sofomo** [comment]
xD
