### ISSUE TITLE
How can I change textinput borderbottom width?

### ISSUE THREAD

**Issue by mreorhan** [callstack/react-native-paper#910]
## Ask your Question 
How can I change textinput borderbottom width?

![ww](https://user-images.githubusercontent.com/17215194/54087705-9f4f2480-4366-11e9-8601-7e86f6a5cd6e.PNG)

**Comment by ferrannp** [comment]
You can't right now in v2. We might consider this with the TextInput redesign we are working on.

**Comment by jbinda** [comment]
Closed according to comment in #1149
