### ISSUE TITLE
Disabled FAB is see through?

### ISSUE THREAD

**Issue by danielwgraf** [callstack/react-native-paper#913]
Based on the documentation, I thought a disabled FAB should simply be grey, but after trying to disable one over a blue background, I realized that it's actually just becoming opaque (and maybe darkening the background?). Is this intended? And if so, is there a way to set the color to just be grey? I attempted setting the disabled property in colors on the FAB but it didn't seem to work.

**Comment by lukewalczak** [comment]
`FAB` component is designed to match with light / dark theme. If you would like to use `backgroundColor: 'blue'` I can suggest you to wrap `FAB` within a `View` and set there `backgroundColor: 'gray'`, like in the following [example](https://snack.expo.io/@happiryu/ed1350)
