### ISSUE TITLE
How to change the color of action in Snackbar?

### ISSUE THREAD

**Issue by ilyaux** [callstack/react-native-paper#919]
## How to change the color of action in Snackbar?

Hi guys ! Help to understand how to change the color of the action in Snackbar ?

```
         <Snackbar
           visible={this.state.visible}
          onDismiss={() => this.setState({ visible: false })}
          action={{
            
            label: "Undo",
            onPress: () => this.setState({ isHidden: true })}}>
          You are registered on {namefilm}
        </Snackbar>
```

**Comment by Trancever** [comment]
You can change it via theme prop:

```
theme={{ colors: { accent: 'red' }}}
```

**Comment by robertherber** [comment]
Hmm, this doesn't feel quite right. Why doesn't the Context-provided theme apply to this specific component?

**Comment by potier97** [comment]
and, how to change the label color?

**Comment by vsheyanov** [comment]
@potier97 in case you didn't find an answer - it's better to check TS definitions of Theme. I tried a few to find that I needed to change:
![image](https://user-images.githubusercontent.com/1764195/89153816-f4946300-d565-11ea-953c-2d7579b10d6d.png)

**Comment by oberdan-dev** [comment]
`theme={{ colors: {surface: 'blue', accent: 'red'},}}`

The example above describes the snackbar text color (and label color) as blue and the action color as red.

**Comment by shahzaibdev1** [comment]
I think this component should have a mode component that takes 'danger', 'error', 'info' etc...

**Comment by nebojsanb** [comment]
action={{
                icon: "close",
                color: text,

**Comment by alvinmandala** [comment]
With theme version 3, you can use 
`theme={{colors: {inversePrimary: Colors.white }}}`

**Comment by andresfmm** [comment]
Hi, you should use the property textColor inside object action. in this example is red

`<Snackbar
              visible={visible}
              action={{ label: 'Understan', textColor: 'red' }}
              onDismiss={ () => handleErrors() }>
              {message}
</Snackbar>`

**Comment by SvenAndreas** [comment]
Some one knows how to change the size of the label inside the action?Without touching the code inside of the module of react-native-paper ?
