### ISSUE TITLE
Not able to make Appbar.Header background color transparent

### ISSUE THREAD

**Issue by yingapp** [callstack/react-native-paper#920]
## Environment

    "@reach/router": "^1.2.1",
    "create-react-context": "^0.2.3",
    "react": "^16.8.4",
    "react-art": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-native": "^0.58.6",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-paper": "^2.12.0",
    "react-native-vector-icons": "^6.3.0",
    "react-native-web": "^0.10.0-alpha.3",
    "react-native-webview": "^5.3.0",
    "react-navigation": "^3.3.2"

## Description

```js
const RootStack = createStackNavigator(
    {
        home: TaskList,
        ...routes,
    },
    {
        defaultNavigationOptions: ({navigation}) => ({
            gestureResponseDistance: {
                horizontal: 45,
            },
            header: (
                <Appbar.Header
                    style={{backgroundColor:'transparent'}}
                    statusBarHeight={Platform.OS === "ios" ? 0 : StatusBar.currentHeight}
                >
                    <Appbar.Action icon="menu" onPress={() => navigation.openDrawer()}/>
                    <Appbar.Content title=""/>
                </Appbar.Header>
            ),
        }),
        headerMode: 'float',
        headerTransparent:true,
    },
);
```

**Comment by yingapp** [comment]
![Screenshot_1552536661](https://user-images.githubusercontent.com/47973401/54330862-5e9b2800-4652-11e9-8b18-012dbf57cf63.png)

**Comment by yingapp** [comment]
![Screenshot_1552537233](https://user-images.githubusercontent.com/47973401/54331161-99ea2680-4653-11e9-9ec9-4a1fbdabbde8.png)

**Comment by raajnadar** [comment]
It is working properly check this demo https://snack.expo.io/@raajnadar/appbar-transparent
