### ISSUE TITLE
Banner is visible in closed state

### ISSUE THREAD

**Issue by abhijeetskadam** [callstack/react-native-paper#927]
## Environment

RN: 0.59
RN-paper: 2.13.0
Platform: Android

## Description

In closed state Banner is still visible, with Appbar having elevation 0. If I add elevation to Appbar it works fine.

## Reproducible Demo

https://snack.expo.io/SkGqPQKwE

**Comment by satya164** [comment]
That's how elevation works in Android, items with higher elevation appear on top of items with a lower elevation. It's not possible to change this behavior in the library.

**Comment by satya164** [comment]
We should fix if banner is visible in the closed state though. cc @Trancever
