### ISSUE TITLE
Outlined label has background, why? How to set different color?

### ISSUE THREAD

**Issue by Steffi3rd** [callstack/react-native-paper#929]
<img width="95" alt="Capture d’écran 2019-03-15 à 23 24 18" src="https://user-images.githubusercontent.com/814410/54465102-c7c98b00-4779-11e9-8931-cb26c7096f6f.png">

**Comment by peterchibunna** [comment]
The `<TextInput>` component accepts a `style` property which can have a `backgroundColor: '<any color>',` 

`<TextInput style={{backgroundColor: '#fff',}} />`

**Comment by Trancever** [comment]
@Steffi3rd  We set this background to cover the outline and to change it pass style prop just like @peterchibunna  suggested.

**Comment by dhcmega** [comment]
Hi, I don't understand why is this closed. backgroundColor changes de color of the whole input while the problem is with the backgroundColor of the label. They don't match. Am I missing something? Thanks!
