### ISSUE TITLE
How can I change button loading color?

### ISSUE THREAD

**Issue by mreorhan** [callstack/react-native-paper#935]
## Ask your Question

How can I change button loading color?
I changed themes, but color didnt change.

**Comment by ferrannp** [comment]
@mreorhan could you add a snack for us to reproduce the issue and see what is really happening?

**Comment by parmarravi** [comment]
Any update on this. I want to change the loader icon color in button

**Comment by jonasguerra** [comment]
> You can change the button's labelStyle
> 
> i.e. `labelStyle={{color: 'blue'}}`

It worked for me. Thank you!
