### ISSUE TITLE
Only on IOS TextInput with mode=outlined - label is jumping up and down

### ISSUE THREAD

**Issue by realioseb** [callstack/react-native-paper#941]
Sorry for not filling template but this problem is easy to understand and reproduce.

TextInput with mode `outlined` only on IOS, when you are typing really fast, label keeps jumping up and down.

I noticed, this happens when outer component is re-rendered.

**Comment by Trancever** [comment]
Hey @realioseb What version of paper do you use?

**Comment by realioseb** [comment]
Hello @Trancever 

Thanks for replay

Paper version is `2.10.1`

**Comment by Trancever** [comment]
@realioseb Check this [Snack](https://snack.expo.io/@trensik/petrified-banana). I tried to reproduce an issue, but it worked fine on iPhone 6.

**Comment by realioseb** [comment]
@Trancever thank you again for this nice snack

You just didn't notice problem just because it was happening too fast, I added few more fields. Please, try filling all of them and type quickly, you will notice problem on 3rd or 4th input. Try real phone not an emulator please.

This is the link to new [https://snack.expo.io/ryoVI7WuV](snack)

**Comment by realioseb** [comment]
@Trancever @raajnadar Anything new for this issue?

**Comment by Trancever** [comment]
@realioseb For now, try implementing shouldComponentUpdate just like on this snack - https://snack.expo.io/@trensik/petrified-banana as a workaround.

**Comment by Trancever** [comment]
@realioseb It should be fixed in version 2.15.0

**Comment by realioseb** [comment]
Thank you!
Looking forward for the new version
