### ISSUE TITLE
Is it possible to not add React Native Vector Icon to this package?

### ISSUE THREAD

**Issue by Steffi3rd** [callstack/react-native-paper#945]
I just removed React Native Vector Icons because I don't want to use it. 
It causes me some bug on `react-native link...` So I unlink it and remove it from my project.

But now after 2 hours I found why my projects fails with this error :
https://github.com/facebook/react-native/issues/24094

It seems your package use React Native Vector Icons but when I delete it, so it causes bug on your package : 

````
error: bundling failed: Error: Unable to resolve module react-native-vector-icons/MaterialIcons from /front/node_modules/react-native-paper/src/components/Icon.js: Module react-native-vector-icons/MaterialIcons does not exist in the Haste module map
```` 

Now I'm stuck, what can I do?

**Comment by satya164** [comment]
We mention this in our getting started guide

![image](https://user-images.githubusercontent.com/1174278/54789284-49b22c00-4c32-11e9-9f1b-ff9e06c3903c.png)

https://github.com/satya164/babel-plugin-optional-require#usage

**Comment by Steffi3rd** [comment]
❤️ Thank you

**Comment by Steffi3rd** [comment]
Hello @satya164

So I see I have to install Babel-plugin-option-required.

But what do I have to add in blacklist and whitelist?

Do you have a config to opt out  react Native vector icons?

**Comment by satya164** [comment]
@Steffi3rd you just need to add the plugin and run `react-native start --reset-cache` to start the packager. No additional config is needed.

**Comment by MakhouT** [comment]
@satya164 Add the plugin as in install it or add it to babelConfig.js? I'm also having issue opting out of this...

**Comment by x5engine** [comment]
thank you so much!

that vector shitty icons package is shit!

**Comment by Trancever** [comment]
@x5engine Author of vector-icons put a lot of effort in making this library and you're blaming it because it doesn't work for you... that's rude

**Comment by x5engine** [comment]
@Trancever I apologize :) the author indeed did a very good job but those errors seem frustrating sometimes after spending days trying to fix that building and rebuilding your app.
