### ISSUE TITLE
Missing Icon from materialIcons

### ISSUE THREAD

**Issue by tonyxiao** [callstack/react-native-paper#950]
This `arrow-right` icon exists on [material design website](https://material.io/tools/icons/?icon=arrow_forward_ios&style=baseline), but I can't use it within `List.Icon` in react-native-paper. ( I get a question mark with failed prop type warning) Am I missing something?

![image](https://user-images.githubusercontent.com/696842/54850787-4e63f800-4ca5-11e9-9752-6c7f6ec859ab.png)

**Comment by nazrdogan** [comment]
@tonyxiao  react-native-paper depend on react-native-vector-icons  for icons. and MaterialIcons is out of date.
https://github.com/oblador/react-native-vector-icons/issues/949
https://github.com/oblador/react-native-vector-icons/issues/921

**Comment by ferrannp** [comment]
Yep, this issue belongs to `react-native-vector-icons`.
