### ISSUE TITLE
List.Accordion Expanded Title Color

### ISSUE THREAD

**Issue by timothystewart6** [callstack/react-native-paper#953]
## Describe the feature

It seems like `<List.Accordion /`> expanded title cannot be styled and it is based on theme color.  I am not sure if this is a design choice or just hasn't been an option thus far.

## Motivation

It would be nice if the accordion title color when expanded, could be passed in vs. based on `theme.colors.primary`.

https://github.com/callstack/react-native-paper/blob/master/src/components/List/ListAccordion.js#L158

`color: expanded ? theme.colors.primary : titleColor,`

https://callstack.github.io/react-native-paper/list-accordion.html

## Related Issues

None.

**Comment by timothystewart6** [comment]
I can contribute this enhancement if needed.  I just wanted to open an issue before a PR.  Thank you!

**Comment by Trancever** [comment]
@timothystewart6 you can pass theme prop to List.Accordion to customize it.
```
theme={{ colors: { primary: '#fff' }}}
```

**Comment by timothystewart6** [comment]
Thank you so much!  I didn't think of overriding the theme prop for this one instance.  I will close this.  Thanks again!

**Comment by timothystewart6** [comment]
Just beware it overrides it for children too, so you have to revert back to `primary` for children (if that's your intent).
