### ISSUE TITLE
Chip | Support border-radius + default to theme roundness

### ISSUE THREAD

**Issue by agarant** [callstack/react-native-paper#955]
## Describe the feature
The chip component currently ignores the [roundness](https://callstack.github.io/react-native-paper/theming.html) setting of the react-native-paper theme. It would be great if it would set its borderRadius based on the roundness.

## Motivation
Help achieve a consistent [theme](https://material.io/design/components/chips.html#theming).

## Related Issues
Currently, when a borderRadius is explicitly added, the selection animation does not follow. The white background disappeared during the gif export, but it is possible to see the animation roundness issue in the gif below.

![Mar-28-2019 14-34-46](https://user-images.githubusercontent.com/13083475/55183817-080c0e80-5167-11e9-85c5-7d55178aac60.gif)

**Comment by Trancever** [comment]
Hi @agarant. We could do something like that ```const { borderRadius = 16 } = StyleSheet.flatten(style);``` and then pass borderRadius to both wrapping view and touchable. Wanna send a PR?

**Comment by agarant** [comment]
Hi @Trancever. Yes, I can send a PR for it. Are you also ok with using the roundness as the default value ?
