### ISSUE TITLE
Modal component on iOS is not responsive with Keyboard ON

### ISSUE THREAD

**Issue by joaom182** [callstack/react-native-paper#957]
## Environment

`react-native-paper 2.15.0`
`react-native 58.5`

## Description

Modal wrapper is not responsive on iOS with Keyboard On

## Reproducible Demo

![ezgif com-optimize](https://user-images.githubusercontent.com/3612098/55211186-bcd71780-51c9-11e9-8440-844d92a7c194.gif)

## Expected Behavior
Fit height of modal to the available size on screen with keyboard ON. (This is the behavior on Android)

![height-fit](https://user-images.githubusercontent.com/3612098/55211373-71713900-51ca-11e9-89aa-cf47748dfd8a.jpeg)

**Comment by HarisSpahija** [comment]
Same issue when using KeyboardAwareScrollView. I think it really has something to do with text inputs breaking a dialog.

**Comment by HarisSpahija** [comment]
Probably related? #491

**Comment by HarisSpahija** [comment]
Could you share your code example? I would like to fix this issue

**Comment by joaom182** [comment]
@HarisSpahija Simply create a dialog with a scrollable content with TextField.

```html
<Portal>
    <Dialog>
        <Dialog.ScrollArea>
            <TextInput />
           <!-- some content here -->
        </Dialog.ScrollArea>
    </Dialog>
</Portal>
```

When height of content is small, the Dialog appears behind of Keyboard.

![Simulator Screen Shot - iPhone X - 2019-03-29 at 10 27 26](https://user-images.githubusercontent.com/3612098/55235865-58d64280-520d-11e9-8ea2-33ed890eda99.png)

**Comment by joaom182** [comment]
@HarisSpahija i've found a solution, see #963

**Comment by BenWildeman** [comment]
@ferrannp did this ever actually get fixed?
