### ISSUE TITLE
 error: fontFamily 'Material Icons' is not a system font 

### ISSUE THREAD

**Issue by YajanaRao** [callstack/react-native-paper#958]
### Current behaviour
I am using Icons in "react-native-paper": "2.14.0", I am getting warning 
`The syntax "import { Font } from 'expo-font'" is deprecated. Use "import * as Font from 'expo-font'" or import named exports instead. Support for the old syntax will be removed in SDK 33.1` in snack.expo.io and error 
`fontFamily "MaterialIcons" is not a system font and has not been loaded through Font.loadAsync.`

`- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.`

`- If this is a custom font, be sure to load it with Font.loadAsync.`
`- node_modules\react-native\Libraries\YellowBox\YellowBox.js:59:8 in error`
`- node_modules\expo-font\build\Font.js:24:16 in processFontFamily`
`- ... 24 more stack frames from framework internals` 

### Expected behaviour
Icons from react-native paper has to be accessible with the import of react native paper

### Code sample
Link to snack sample: https://snack.expo.io/@yajana/serenity

### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/38914337/55213903-e0767e00-521a-11e9-94e3-540a20d8b6e3.png)

### Solutions Tried
Tried to import using 
`  async componentWillMount() {
    await Font.loadAsync({ 'Material Icons': require('@expo/vector-icons/fonts/MaterialIcons.ttf') })
  }`

### Your Environment

| software              | version
| --------------------- | -------
| android        | 6
| react-native          | 
| react-native-paper    | 2.14.0
| node                  | v8.11.4
| npm           | 6.4.0
| expo sdk              | 2.6.14

**Comment by YajanaRao** [comment]
Solution for me was this:
```
export default class App extends React.Component {
  state = {
    theme: DarkTheme,
    isFontLoaded: false
  };

   async componentWillMount() {
    await Font.loadAsync({ 'MaterialIcons': require('@expo/vector-icons/fonts/MaterialIcons.ttf') })
    this.setState({ isFontLoaded: true })
  }

  render() {
    return (
      <PaperProvider theme={this.state.theme}>
      { this.state.isFontLoaded ?
        <RootNavigator /> :
        <AppLoading/>
      }
      </PaperProvider>
    );
  }
}
```

**Comment by artalat** [comment]
We shouldn't need to do this if we are using expo, as mentioned in the docs. But this isn't the case. I needed to use the solution mentioned above.

**Comment by paras-mathur** [comment]
In expo version 33, install **@expo/vector-icons**

Also change the require statement mentioned above to - 

**await Font.loadAsync({ 'MaterialIcons': require('@expo/vector-icons/src/vendor/react-native-vector-icons/Fonts/MaterialIcons.ttf') })**

**Comment by madrigal1** [comment]
This did not work for me please refer this
https://stackoverflow.com/questions/56089141/unable-to-resolve-module-expo-vector-icons-fonts-ionicons-ttf
