### ISSUE TITLE
TextInput throwing a Animated error

### ISSUE THREAD

**Issue by brunocrpontes** [callstack/react-native-paper#959]
## Environment

Expo v32.0.0
running project in a iOS v12.1.4
react-native-paper v2.15.0

## Description
When i try update error props in a TextInput it returning this error:
 
![IMG_0166](https://user-images.githubusercontent.com/13150168/55214946-e2b6e900-51d6-11e9-875d-900cbcdc58c9.PNG)

## Reproducible Demo

https://snack.expo.io/@brunocardosor/restless-apples

## Update

I tested in a Android device,  everything runs fine, this happening only in iOS

**Comment by satya164** [comment]
cc @Trancever I believe we need to remove `useNativeDriver` from all animations
