### ISSUE TITLE
BUG : OnBlur in TextInput RTL

### ISSUE THREAD

**Issue by saharjedidi** [callstack/react-native-paper#969]
![Screen Shot 2019-04-01 at 5 00 37 PM](https://user-images.githubusercontent.com/45098179/55390899-1627a980-5530-11e9-8988-74512e4530e0.png)

**Comment by hugopretorius72** [comment]
@saharjedidi , any idea why this is happening? Or a possible workaround for it? I experience the same on RN 0.59.3.  Thanks in advance

**Comment by Trancever** [comment]
Check version 2.15.1 of Paper, it should be fixed. Let me know if there are any other issues.

**Comment by hugopretorius72** [comment]
> Check version 2.15.1 of Paper, it should be fixed. Let me know if there are any other issues.

Thanks man, will do!

**Comment by hugopretorius72** [comment]
Thanks @Trancever for the quick reply and the fix.  Legend 🙌🏻
