### ISSUE TITLE
Menu is not working in iOS

### ISSUE THREAD

**Issue by mihaidaviddev** [callstack/react-native-paper#970]
## Description

Menu component relies on StatusBar.currentHeight which is Android only as stated in react native docs
[https://facebook.github.io/react-native/docs/statusbar](url)

I've changed that line with the one below and it's working now
`const top = Math.max(SCREEN_INDENT, y) + 40;`

![Simulator Screen Shot - iPhone 8 - 2019-04-02 at 15 19 25](https://user-images.githubusercontent.com/47058217/55408829-7e46b180-5569-11e9-8bcc-a6c569584398.png)

**Comment by ferrannp** [comment]
Hey! Thanks for opening the issue, @Trancever is working on it!

**Comment by Trancever** [comment]
Once #976 is merged, issue will be fixed

**Comment by ferrannp** [comment]
Should be fixed on `2.15.2`.
