### ISSUE TITLE
List.accordion no titleStyle?

### ISSUE THREAD

**Issue by Unicity-Pimentel** [callstack/react-native-paper#973]
I created a page using List.Section,Accordion and Item where when the List.accordion and List.Item is pressed it will automatically update its styles (font color, bg color). So far the List.Item is the only one working properly atm. Any suggestions on this ?

**Comment by jaysbytes** [comment]
It looks like a missing feature. I think we can add `titleStyle` and `descriptionStyle` to List.Accordion and `titleStyle` to List.Section. @Unicity-Pimentel you know, PRs are welcome if you have some time :D. Just let others know whether you work on it or no. I could probably take it within a few days.
