### ISSUE TITLE
multiline TextInput with fixed height

### ISSUE THREAD

**Issue by aknad** [callstack/react-native-paper#974]
## Environment

react-native: 0.59.3
react-native-paper: 2.15.0
device: iPhone 7Plus - iOS 12.2

## Description

in a multiline TextInput with a fixed height, the text goes under the label when all the visible lines are used
it seems to happen only on iOS
![IMG_289200F6A359-1](https://user-images.githubusercontent.com/7056879/56127124-c3f97600-5f7c-11e9-9c50-ccc23bda83ef.jpeg)
on Android is ok
![Screenshot_20190415-214743__01](https://user-images.githubusercontent.com/7056879/56160872-8e7a7a00-5fc8-11e9-8a0d-1d29744810f7.jpg)

## Reproducible Demo

here's a snack to reproduce the issue
https://snack.expo.io/@aknad/textinput

**Comment by jaysbytes** [comment]
Hi @aknad, I don't really get what is the problem or which behavior would you expect? As you can see when text is not fitting the screen it gets scrollable. I think it is a great behavior. Maybe the distance between the label and text area is too small for you?

**Comment by aknad** [comment]
Hi @jaysbytes , 
the text is scrollable but when it reach the fixed height it scrolls up and it goes over the label
![IMG_289200F6A359-1](https://user-images.githubusercontent.com/7056879/56127124-c3f97600-5f7c-11e9-9c50-ccc23bda83ef.jpeg)

**Comment by jaysbytes** [comment]
@aknad Now I see the issue. I opened your snack on my device and it worked as expected. Could you please add this screenshot to description and describe device on which it happens (platform, device model, OS version) in environment section?

**Comment by aknad** [comment]
Sorry, I forgot to test it on Android
the issue seems to happen only on iOS
Anyway I've updated the description
Thanks

**Comment by jaysbytes** [comment]
I've checked the issue and the same thing happens if native text input is used. So Issue is related to `react-native` itself rather than `react-native-paper`. 
We can fix this replacing padding with margins but then hit area of text input will suffer. We can call the focus method on ref when input container will be pressed but it doesn't sound good. I think this workaround is not worth doing to support this one specific use case. This will mess up TextInput code that we tried to simplify to improve maintainability :/

**Comment by raksahb** [comment]
I am seeing a similar issue but it is when there is an outline on the multiline text input. same versions as in the ticket.
![Text_Input_overlaps_border](https://user-images.githubusercontent.com/2277664/56234417-1d73aa80-603a-11e9-812f-820769d82ba1.png)

**Comment by jaysbytes** [comment]
@raksahb Yes, it happens because of the same reason. As I said before I'm not sure about fixing it in paper as it seems to be an issue in react-native. We are currently refactoring TextInput and to fix this issuse we will need to mess the code.

**Comment by jbinda** [comment]
I've found the reason of that behaviour and will proceed with provide solution

**Comment by GauthierG** [comment]
Hello, I still have this issue with React Native 0.59.10 and react-native-paper 3.2.1

**Comment by gautam678** [comment]
Hey! I'm on version 3.5.1 and this issue exists.

**Comment by yamifr07** [comment]
I have the same issue. any fix?

**Comment by daviddossantos** [comment]
hello guys, I created a component that maybe can solve the problem in IOS, take a look at the repository https://github.com/daviddossantos/textinput-multiline-multiplataform

**Comment by tanmay-patil** [comment]
I still have the same issue, is there any fix or a timeline for when will this fix be released next?

**Comment by raajnadar** [comment]
Can someone test with the latest version?

**Comment by KrifaYounes** [comment]
it's possible to reopen the issue ?
