### ISSUE TITLE
Swipe Action for Bottom Navigator

### ISSUE THREAD

**Issue by YajanaRao** [callstack/react-native-paper#984]
## Ask your Question

I want to move to the next tab by swiping. I found the  SwipeEnabled property for Tab Navigator. Is there any such option for Bottom Navigator

**Comment by jaysbytes** [comment]
According to Material UI docs, Bottom navigation doesn't have sipe functionality by design. We follow MUI docs and we cannot introduce a feature inconsistent with docs.
