### ISSUE TITLE
IconButton with SVG as icon doesn't make ripple effect (Android 8.0)

### ISSUE THREAD

**Issue by manelsanz** [callstack/react-native-paper#987]
## Environment

React Native 0.59.3
React Native Paper: 2.14.0
Device: Huawei Mediapad T5
Android: 8.0.0

## Description

The problem is that, when press the `IconButton` the effect is too retarded or it's impossible to see at least. I think the ripple goes below the Icon. But, the curious thing is that with my Xiaomi Mi 8 Lite with Android 9.0, the ripple shows as expected. And, in all cases, with default icons works well (e. `icon="add"`)

Thanks.

## Example code

```
            <IconButton
              icon="add"
              onPress={() => this.selectLanguage(true)}
            />

            <IconButton
              icon={() => <DownOnSvg height="42" width="42" />}
              onPress={() => this.selectLanguage(false)}
              style={{ marginTop: 20 }}
            />
```

**Comment by ferrannp** [comment]
@manelsanz can you add a repro? and a gif maybe?

**Comment by jaysbytes** [comment]
inactive, closing
