### ISSUE TITLE
undefined is not an object (evaluating '_reactNativePaper.Menu.Item)

### ISSUE THREAD

**Issue by carizzapanopio** [callstack/react-native-paper#990]
### Expected behaviour

Menu.Item from Menu Component doesnt work. I am getting this error:

![image](https://user-images.githubusercontent.com/3467685/56080595-9fdf4d00-5e35-11e9-82ca-f1ac03d0e72b.png)

### Code sample
import { Button, Paragraph, Menu, Divider, Provider } from 'react-native-paper';
render() {
   return (
    <Provider>
        <View
          style={{
            paddingTop: 50,
            flexDirection: 'row',
            justifyContent: 'center'
          }}>
          <Menu
            visible={this.state.visible}
            onDismiss={this._closeMenu}
            anchor={
              <Button onPress={this._openMenu}>Show menu</Button>
            }
          >
            <Menu.Item onPress={() => {}} title="Item 1" />
            <Menu.Item onPress={() => {}} title="Item 2" />
            <Divider />
            <Menu.Item onPress={() => {}} title="Item 3" />
          </Menu>
        </View>
      </Provider>

   )
}
              
### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.58.4
| react-native-paper    | 2.12.0
| node                  | 8.11.3
| npm or yarn           | yarn
| expo sdk              |

**Comment by satya164** [comment]
The latest version is 2.15.2. Please upgrade.
