### ISSUE TITLE
Modal Snack Is Broken

### ISSUE THREAD

**Issue by AlexMachin1997** [callstack/react-native-paper#991]
## Environment

N/A as it's  an online snack

## Description

When the modal snack is run the following error is shown: 
![image](https://user-images.githubusercontent.com/29917195/56095668-0cf6ef00-5ed7-11e9-9182-ad1d9afeb7a3.png)

## Reproducible Demo

[Demo link
](https://snack.expo.io/@alexmachin1997/bW9kYW?name=Modal&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fmodal.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20Modal%2C%20Portal%2C%20Text%2C%20Button%2C%20Provider%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aexport%20default%20class%20MyComponent%20extends%20React.Component%20%7B%0A%20%20state%20%3D%20%7B%0A%20%20%20%20visible%3A%20false%2C%0A%20%20%7D%3B%0A%0A%20%20_showModal%20%3D%20()%20%3D%3E%20this.setState(%7B%20visible%3A%20true%20%7D)%3B%0A%20%20_hideModal%20%3D%20()%20%3D%3E%20this.setState(%7B%20visible%3A%20false%20%7D)%3B%0A%0A%20%20render()%20%7B%0A%20%20%20%20const%20%7B%20visible%20%7D%20%3D%20this.state%3B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3CPortal%3E%0A%20%20%20%20%20%20%20%20%3CModal%20visible%3D%7Bvisible%7D%20onDismiss%3D%7Bthis._hideModal%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%3CText%3EExample%20Modal%3C%2FText%3E%0A%20%20%20%20%20%20%20%20%3C%2FModal%3E%0A%20%20%20%20%20%20%20%20%3CButton%0A%20%20%20%20%20%20%20%20%20%20style%3D%7B%7B%20marginTop%3A%2030%20%7D%7D%0A%20%20%20%20%20%20%20%20%20%20onPress%3D%7Bthis._showModal%7D%0A%20%20%20%20%20%20%20%20%3E%0A%20%20%20%20%20%20%20%20%20%20Show%0A%20%20%20%20%20%20%20%20%3C%2FButton%3E%0A%20%20%20%20%20%20%3C%2FPortal%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D&dependencies=react-native-paper)

**Comment by Taym95** [comment]
I will take it.

**Comment by Taym95** [comment]
You should wrap your root component with `Provider` this should work:

```
import * as React from 'react';
import { Modal, Portal, Text, Button, Provider } from 'react-native-paper';

export default class MyComponent extends React.Component {
  state = {
    visible: false,
  };

  _showModal = () => this.setState({ visible: true });
  _hideModal = () => this.setState({ visible: false });

  render() {
    const { visible } = this.state;
    return (
      <Provider>
        <Portal>
          <Modal visible={visible} onDismiss={this._hideModal}>
            <Text>Example Modal</Text>
          </Modal>
          <Button style={{ marginTop: 30 }} onPress={this._showModal}>
            Show
          </Button>
        </Portal>
      </Provider>
    );
  }
}
```

**Comment by jaysbytes** [comment]
@Taym95 Thank you for finding the solution! Our snack examples are autogenerated from documentation example so If you will fix example in docs the snack will be also fixed. Do you want to create a PR? Otherwise, I will take it.

**Comment by Taym95** [comment]
@jaysbytes I already created a PR, waiting for review!

**Comment by AlexMachin1997** [comment]
@jaysbytes Huh never realized they were auto-generated.
