### ISSUE TITLE
Use List.Item structure in Menu

### ISSUE THREAD

**Issue by RichardLindhout** [callstack/react-native-paper#993]
## Describe the feature

Maybe we could export the List.Item component from the Menu.Item so we could support more customization.

## Motivation
I can't add a description to the menu item.

**Comment by iyadthayyil** [comment]
We could use List.Item, But as per material guidelines Menu.Item doesn't have much customization.
It just has the text in mobile. icons and some little bit extra customization on the web.
Also it supports disabled action unlike List.Item.

If you would like to get more customization you could do this way:
```javascript
<Menu>
   <List.Item ... />
   <List.Item ... />
</Menu>
```
