### ISSUE TITLE
FAB Group auto change StatusBar barStyle when open

### ISSUE THREAD

**Issue by nhatquangsin** [callstack/react-native-paper#999]
## Description

As the title, I can't find a way to persist the barStyle of my StatusBar, it auto turns light when the FAB.Group open.

## Screenshot

<img width="468" alt="Screen Shot 2019-04-17 at 8 11 46 PM" src="https://user-images.githubusercontent.com/23427220/56290428-5486b080-614d-11e9-8956-41d070328d7d.png">

<img width="424" alt="Screen Shot 2019-04-17 at 8 11 43 PM" src="https://user-images.githubusercontent.com/23427220/56290430-551f4700-614d-11e9-8ea9-1e6526d387e9.png">

**Comment by wandrzejczak** [comment]
+1, I've exactly the same problem.

**Comment by satya164** [comment]
Can you send a PR removing it? We'll remove it in 3.0

**Comment by Taym95** [comment]
I can send PR if no one is working on it!
